### ISSUE TITLE
Tabs with dropdowns in nav

### ISSUE THREAD

**Issue by mathieumg** [react-bootstrap/react-bootstrap#100]
Is this feature on the to-do list (if at all)? http://getbootstrap.com/components/#nav-dropdowns

I see https://react-bootstrap.github.io/components.html#navbars, but I didn't find a way to use a `<DropdownButton>` as one of the `<TabPane>`s in a `<TabbedArea>`.

Thanks!

**Comment by mtscout6** [comment]
It looks like the docs are demonstrating this use case today: https://react-bootstrap.github.io/components.html#navbars. Is this still an issue for you?

**Comment by mathieumg** [comment]
That's navbars, no? This issue is about a similar behavior on tabs. Unless one has just become a specific case of the other. If that is the case, it might be relevant to add an example to do the same with tabs. (As is supported by Bootstrap: http://getbootstrap.com/javascript/#tabs)

**Comment by mtscout6** [comment]
Ah, I see tabs not navs.... Ya, we need to fix this.

![](http://cl.ly/image/2l400H2N1A2G/Image%202015-03-30%20at%208.07.33%20PM.png)

**Comment by AlexKVal** [comment]
Superceded by #526

**Comment by mtscout6** [comment]
Not fixed by #526

**Comment by taion** [comment]
Moved to https://github.com/react-bootstrap/react-bootstrap/issues/1418.

**Comment by mathieumg** [comment]
This is now possible by combining https://react-bootstrap.github.io/components.html#tabs-custom-layout and https://react-bootstrap.github.io/components.html#navs-dropdown.

@react-bootstrap/collaborators Are you fine with me closing this? Do you think we would need to add an example of that use case in the docs?

**Comment by taion** [comment]
Does that work? We should add it to the example if so.

**Comment by mathieumg** [comment]
Yeah I tested it quickly directly in the docs' editor. Could try to find the time to document it and write some tests around it even.

**Comment by taion** [comment]
Would you mind if we keep this open until we have an example showing this, then?

**Comment by mathieumg** [comment]
Not at all. I've been pretty busy, just got around upgrading to 0.29 and realized it was now possible... :no_mouth: I feel terrible, I'd like to invest a bit more time into the project, but I lift my hat off to @jquense and yourself for all the awesome work you've been doing. :+1: :grin:

**Comment by taion** [comment]
Let's track this on #2115 instead.

**Comment by auregnamian** [comment]
uhjhjj

**Comment by lailaafrin** [comment]
### _****_
