### ISSUE TITLE
Bug. Docs v0.24. Modal static example doesn't show.

### ISSUE THREAD

**Issue by AlexKVal** [react-bootstrap/react-bootstrap#1001]
<img width="938" alt="screen shot 2015-07-17 at 3 14 37 pm" src="https://cloud.githubusercontent.com/assets/847572/8746977/39129db2-2c97-11e5-993f-c04d3d6fe097.png">

**Comment by taion** [comment]
There's no way sane way to show a static modal dialog any more with the new code as it stands, and I don't think there's any value in exposing a way to do so - I'm going to revise this example entirely.
