### ISSUE TITLE
Docs 0.24. Tooltips first example doesn't show.

### ISSUE THREAD

**Issue by AlexKVal** [react-bootstrap/react-bootstrap#1012]
http://localhost:4000/components.html#tooltips

<img width="915" alt="screen shot 2015-07-17 at 6 58 18 pm" src="https://cloud.githubusercontent.com/assets/847572/8751517/36279818-2cb6-11e5-9e93-48c8de39dc65.png">

**Comment by taion** [comment]
#1013
