### ISSUE TITLE
Style passthroughs on Tooltips

### ISSUE THREAD

**Issue by kennyw12** [react-bootstrap/react-bootstrap#1027]
We think a user should be able to supply a `style` prop to Tooltips, because this would be consistent with the behavior of most other components. Currently, any `style` prop passed into a tooltip will be ignored.

https://github.com/react-bootstrap/react-bootstrap/blob/master/src/Tooltip.js#L72

Style is being defined and supplied with left and top attributes only. We would like to be able to provide other styles as a prop to Tooltips.

```
<Tooltip style={{opacity: 1}} />
```

Should render a tooltip with merged styles (`{opacity: 1, top: Xpx, left: Xpx}`).

Would you be open to a PR?

cc/ @gpleiss @stubbornella @matt-royal @ctaymor

**Comment by taion** [comment]
That's definitely an oversight. PR away.
