### ISSUE TITLE
Bug. Prop data generation fails for 'bsStyle'

### ISSUE THREAD

**Issue by AlexKVal** [react-bootstrap/react-bootstrap#1033]
<img width="890" alt="screen shot 2015-07-21 at 8 36 40 pm" src="https://cloud.githubusercontent.com/assets/847572/8807975/7b7a858a-2fe8-11e5-8c00-c0659f34d88c.png">

Though code is:
```js
/**
 * Style variants
 * @type {("default"|"primary"|"success"|"info"|"warning"|"danger"|"link")}
 */
bsStyle: CustomPropTypes.keyOf(styleMaps.STYLES)
```

**Comment by taion** [comment]
Looks like this only shows up for the instances where there's a default (of `'default'`).

**Comment by taion** [comment]
This issue went away.
