### ISSUE TITLE
<br>'s are lost inside input help text

### ISSUE THREAD

**Issue by binarykitchen** [react-bootstrap/react-bootstrap#1041]
Sometimes we want line-breaks in help texts for inputs but unfortunately the `<` and `>` get encoded.

How can we fix or circumvent this?

**Comment by jquense** [comment]
can we get an example? the input _should_ render your BR's just fine

**Comment by binarykitchen** [comment]
very simple:

```
Input = require('react-bootstrap').Input

...

<Input
    help = "line one: “whales are not fish”;<br>line two: “Real Madrid 6-0”."
/>
```

**Comment by jquense** [comment]
you need to use an actual jsx element in brackets not just a string `help={<span>hi <b>guy</b></span>} `

**Comment by binarykitchen** [comment]
oh  i see, all good then, thx
