### ISSUE TITLE
<Input> (of type select) renders wrong options on Chrome

### ISSUE THREAD

**Issue by yong-at-git** [react-bootstrap/react-bootstrap#1046]
Hi, 
I'm at version **0.23.1** and using **Input** component with **type = 'select'**. I'm using **Reflux**.

The options rendered on **Chrome**(Version 43.0.2357.132 on Windows) are different from the ones listed in HTML code. **Firefox** and **IE 10** don't have this problem. 

**Chrome rendering**

![image](https://cloud.githubusercontent.com/assets/8929454/8854424/1c3c193e-3160-11e5-81b4-66cc2ae36c93.png)

**HTML code**

![image](https://cloud.githubusercontent.com/assets/8929454/8854534/9da80848-3160-11e5-9b3e-8e7d55897e4c.png)

**When does it happen?**
It happens when another component triggers the options update.

My wrapping code of the component:
```
var SysTypesComp = React.createClass({
	render: function () {

		var sysTypeList = this.props.sysTypeList;

		var options = [];

		for(var i=0;i<sysTypeList.length;i++){
			options.push(<option value={sysTypeList[i]}> {sysTypeList[i]} </option>);
		}

		return (
			<Input type='select' ref='multiSelect' help='Use Ctrl/Shift to multi-select.' multiple>
				{options}
			</Input>
        );
    }
});
```
This component is then used as:
```
<SysTypesComp ref='sysType' sysTypeList={this.state.sysTypeList}/> 
```
Thanks!
/ Yong

**Comment by iamstarkov** [comment]
@jquense @AlexKVal @taion can anybody take a look at this? thank you

**Comment by AlexKVal** [comment]
> I'm at version 0.23.1

This project doesn't backport bugfixes to previous versions.
The `Input` componet is under heavy refactoring now https://github.com/react-bootstrap/react-bootstrap/issues/342

**Comment by iamstarkov** [comment]
@AlexKVal so do you mean that latest published version has no this bug?

**Comment by jquense** [comment]
@iamstarkov  we don't really know what the bug is. are you saying the html looks different in dev tools but the actual rendered result is correct?

**Comment by jquense** [comment]
as an aside, you can't render options with tags in them.

```jsx
<option value={sysTypeList[i]}> {sysTypeList[i]} </option>
```

the whitespace on either side of the brackets of `{sysTypeList[i]}` is significant in JSX its causing the extra spans in the markup and breaking it probably.

**Comment by yong-at-git** [comment]
@jquense , thanks. It fixes the problem.
@iamstarkov thanks for helping out.

**Comment by iamstarkov** [comment]
yay
