### ISSUE TITLE
Overlays don't position themselves properly when target is an SVG

### ISSUE THREAD

**Issue by benekastah** [react-bootstrap/react-bootstrap#1050]
`getBoundingClientRect` should provide enough information to make it possible.

**Comment by jquense** [comment]
any more info on this one? We do use `getBoundingClientRect` so A little more info would be helpful for tracking it down

**Comment by benekastah** [comment]
I'm attempting a fix right now. Once I test it out I'll put a PR up.

**Comment by jquense** [comment]
:+1:

**Comment by benekastah** [comment]
I've made a change, but I'm not sure how to build the project at this point. Is there a wiki page for that I'm missing?

**Comment by taion** [comment]
`npm run build` will build it.
