### ISSUE TITLE
Wrapping Modal/Portal with className

### ISSUE THREAD

**Issue by joemcbride** [react-bootstrap/react-bootstrap#1055]
I have a situation where I need to add a top-level class to the div that wraps the `modal` div.  The best place to add this looks like perhaps the `Portal` component.

Use case: We currently have both BS2 and BS3 styles on the same page as we are slowly converting our code to React.  The way we have solved this currently is with a top-level css namespace named `bs3`.  I need the modal wrapped with that namespace so it picks up the BS3 styles.

I may be able to stick with the BS2 styles, however with v0.24 the added `paddingRight` messes up the styling (since the BS2 dialog style is on the `modal` class vs. the `modal-content` class.

Any other ideas on how to achieve this?

**Comment by joemcbride** [comment]
Possibly solved with #1040

**Comment by joemcbride** [comment]
Hacked this solution together, though hopefully can gain access to the DOM node with the `onEnter` event.

```
  componentDidUpdate() {
    this._attachParentStyle();
  }

  _attachParentStyle() {
    // switch to `onEnter` function of modal with #1040 react-bootstrap PR
    // https://github.com/react-bootstrap/react-bootstrap/pull/1040
    if(this.props.isModalOpen && !this.BS3StyleSet) {
      setTimeout(()=> {
        let modal = this.refs.modal.refs.modal;
        if(modal) {
          let node = React.findDOMNode(modal);
          if(node && node.parentNode) {
            this.BS3StyleSet = true;
            node.parentNode.className = 'bs3';
          }
        }
      }, 0);
    }
  }
```

**Comment by taion** [comment]
`onEnter` was exposed in v0.24.1 - is this resolved now?

**Comment by joemcbride** [comment]
v0.24.1 resolves this.  Thanks!
