### ISSUE TITLE
DropdownStateMixin: click listener can incorrectly determine that click occurs outside dropdown

### ISSUE THREAD

**Issue by jmeisenthal** [react-bootstrap/react-bootstrap#1059]
Take the following scenario for example:

You have a custom dropdown component that uses DropdownStateMixin. The component in the dropdown is fairly dynamic. For example, a simple wizard that pages through different forms. In this case, a button click would result in replacing the current wizard page with the next (one component unmounts, the other mounts; this is done in React via a change in the dropdown component's state).

In this case, the mixin's click listener reacts AFTER the dropdown's state change. So the click target belongs to the unmounted component. Therefore, the test to see if the click occurred inside the dropdown fails, because the unmounted DOM node no longer has a parent node.

This can be fixed by modifying the "clicked inside or outside" test: the "clicked outside" result should only occur if the target.parentNode loop reaches the document root itself before reaching the dropdown root node.

**Comment by jquense** [comment]
what version of RB are you working on? cc @taion

**Comment by jmeisenthal** [comment]
v0.21.2

And, I've realized that my "this can be fixed by..." doesn't work for some scenarios. Work-around for now is to put the setState in a setTimeout within the click action to allow the doc click listener to act first.

**Comment by taion** [comment]
I think this is a known issue that's being addressed by #526.

We had the same problem with overlays and the current `RootCloseWrapper` handles it correctly.

**Comment by mtscout6** [comment]
Correct, this will be addressed in #526
