### ISSUE TITLE
Position.js's render() method overwrites left and top properties of "style" 

### ISSUE THREAD

**Issue by methosoldest** [react-bootstrap/react-bootstrap#1064]
Hi, 

I am new to web development and I have been using react-bootstrap for just a couple of weeks. I think I have found a bug and I wanted to submit it and get it confirmed. 

I found it while playing with Overlay example "I am an Overlay target" on this page:
http://react-bootstrap.github.io/components.html#overlays

If I add attribute "left: 100" to "style" const variable which gets passed to "<div>" element surrounding "Holy guacamole! Check this info", that value is ignored. 

I think the culprit for that is Position.js:render() on line 56 where we see following code:

       style: {
          ...child.props.style,
          left: positionLeft,
          top: positionTop
        }

Due to above code, if there is a "left" present in the child.props.style, then it is overwritten and ignored.
To fix this, one would have to just swap the order as follows:

       style: {
          left: positionLeft,
          top: positionTop,
          ...child.props.style,
        }

**Comment by taion** [comment]
What's the use case for overriding the specified position? That's the entire point of the `Overlay` positioning logic.

**Comment by methosoldest** [comment]
I do not see positionLeft property present on Overlay element.
It is only present in Popover element. Even in that element, setting it to some value does not have any effect.

Either way, how is one supposed to position an Overlay element?

**Comment by methosoldest** [comment]
Here is the JSBin for the example: https://jsbin.com/vopofojafu/edit?html,js,output

If I want to position "Holy guacamole! Check this info." left by 50px than the default position, how should I do it?

**Comment by taion** [comment]
Follow the example here: http://react-bootstrap.github.io/components.html#overlays-overlay

Setting `left` wouldn't do what you wanted anyway, even if it weren't overwritten - you'd completely override the positioning of the popover.

**Comment by methosoldest** [comment]
@taion 
The JSBin is created using the same example that you are referring to. However, the earlier JSBin has stopped working for some reason. Here is working JSBin:
https://jsbin.com/jijihutole/edit?html,js,output

The output is as follows:
http://i.imgur.com/f9DPJTt.png

As you can see, in spite of "left: 500", the <div>'s left is overwritten.
I would really appreciate if you could show me how to do it.

**Comment by taion** [comment]
Do what @jquense says in #1066.
