### ISSUE TITLE
positionLeft value in Popover component is useless

### ISSUE THREAD

**Issue by methosoldest** [react-bootstrap/react-bootstrap#1066]
I modified following example code on the bootstrap-react playground:
(I added "positionLeft={200}" to Popover component. The documentation for Popover says:
"positionLeft: number: The "left" position value for the Popover."
However, adding this prop has no effect on the rendered Popover)

---------------------

class Example extends React.Component {
  constructor(props, context){
    super(props, context);
    this.state = { show: false };
  }
  render(){

    return (
      <ButtonToolbar>
        <Button
          bsStyle='default'
          onClick={e => this.setState({ target: e.target, show: !this.state.show })}
        >
          Holy guacamole!
        </Button>

        <Overlay
          show={this.state.show}
          target={()=> React.findDOMNode(this.state.target)}
          placement='bottom'
          container={mountNode}
          containerPadding={20}
        >
          <Popover positionLeft={200} title='Popover bottom'>
            <strong>Holy guacamole!</strong> Check this info.
          </Popover>
        </Overlay>
      </ButtonToolbar>
    );
  }
}

React.render(<Example/>, mountNode);

**Comment by taion** [comment]
Yes - `Overlay` injects those props to position the `Popover` appropriately. What are you trying to do?

**Comment by jquense** [comment]
if yuo want to adjust the position props then you need to provide a custom component to either Overlay or OverlayTrigger that does what you want with the style props that are injected

```
class MyTooltip {
  render(){
    let { style: left, top } = this.props

    return (<Tooltip {...this.props} style={{ left: left + 10, top: top + 15 }}/>
  }
}
```

**Comment by methosoldest** [comment]
@taion 
Perhaps I am misunderstanding the purpose of Overlay, but here is what I think Overlay should do:
1. Trigger it's contents such as Popover at the correct cue
2. Position that content properly
3. Hide the content once again at another cue.

But, if the user wants to override default Overlay positioning logic, then he should be allowed to do so, isn't it? That way, he can still continue to use 1, 3 from Overlay logic while overriding point-2 logic.

@jquense 
I am not sure that works. That's the reason I had submitted following issue/query:
https://github.com/react-bootstrap/react-bootstrap/issues/1064
If you know how to do it, kindly show it to me in that JSBin.

**Comment by methosoldest** [comment]
@jquense 
JSbin on that page had stopped working for some reason.
Here is working version: https://jsbin.com/jijihutole/edit?html,js,output

**Comment by jquense** [comment]
@methosoldest I do know how to do it, that's why I posted that code snippet.

**Comment by methosoldest** [comment]
@jquense 
Wouldn't following code snippet from Position.js overwrite the user sent values of "left" and "top" with calculated values?
        style: {
          ...child.props.style,
          left: positionLeft,
          top: positionTop
        }

**Comment by jquense** [comment]
no, position passing a style prop to a component, that component can do wahtever it wants with it, the default behavior of the Tooltip and Popover is to use it. If you make your own component you can do whatever you want.

**Comment by methosoldest** [comment]
Thanks @jquense & @taion 
The solution with custom component worked.
Thanks for being patient with my query.

**Comment by Sutikshan** [comment]
Thanks guys, this thread helped me little too. I am stuck with similar issue. providing left in style of custom popover element works, but it does not take top value.
I want to customise arrowOffsetTop, arrowOffsetLeft too, but changing them does not reflect... here is my code snippet.
```

        <Overlay
          show={this.state.isOpen}
          target={this.state.target}
          container={this}
          placement="bottom"
          arrowOffsetTop="-6px;"
          arrowOffsetLeft="79%;"
        >
          <PopoverAligned
            links={links}
            givenName={givenName}
            surname={surname}
            greetingText={greetingText}
          />
        </Overlay>


const PopoverAligned = props => (
  <Popover
    id="profilePopover"
    title={`${props.greetingText} ${props.givenName || ''} ${props.surname || ''}`}
    className="dropdown-menu open"
    placement="bottom"
    style={{ top: '43px;', left: '-100px' }}
  >
    {
      props.links.map(link => (
        <li className="menuitem">
          <a href={link.url} target={link.target} className="dropdown-link">
            {link.title}
          </a>
        </li>
    ))
    }
  </Popover>
);
```
