### ISSUE TITLE
Clicking DropdownButton changes page

### ISSUE THREAD

**Issue by kkarimi** [react-bootstrap/react-bootstrap#1070]
I am using react-bootstrap (v0.24.2) DropdownButton in the component below, but clicking the **DropdownButton** always triggers change of route of the page to '/' (index) which changes the page. I should probably mention that I am using this together with [react-mini-router](https://github.com/larrymyers/react-mini-router) (v1.1.5). Not sure if this is the reason for the conflict?

```javascript
var React = require('react');
var ReactBootstrap = require('react-bootstrap'),
    Nav = ReactBootstrap.Nav,
    Navbar = ReactBootstrap.Navbar,
    DropdownButton = ReactBootstrap.DropdownButton;

var Header = React.createClass({
userNameClick: function (e) {
        e.preventDefault();
        console.log('username clicked');
    },
render: function(){
            return (
                    <Navbar fixedTop toggleNavKey={0}>
                    <Nav right eventKey={0}>
                        <DropdownButton
                            title="User Name"
                            onSelect={this.userNameClick}
                            onClick={this.userNameClick}>
                        </DropdownButton>
                    </Nav>
                </Navbar>
      }
    }

});
```

**Comment by taion** [comment]
The rare dropdown related question not related to #526?

http://react-bootstrap.github.io/components.html#navs-dropdown

>Just make sure to set `navItem` property to true.

**Comment by kkarimi** [comment]
Thanks @taion. However I just added this property and the problem still exists.

**Comment by taion** [comment]
Re-filed as #1302.
