### ISSUE TITLE
Affix in IE10 - scrollHeight

### ISSUE THREAD

**Issue by MaaikeB** [react-bootstrap/react-bootstrap#1073]
I know the Affix is not finished for general use yet, but I'm using it in my projects and it works well.

...however... apart from IE10.
Here it gets the 'affix-bottom' class where it is not supposed to, and then the affixed element jumps out of the visible view port. 

This happens because the AffixMixin uses the variable: 
scrollHeight = document.documentElement.offsetHeight
to get the height of the entire page. 

document.documentElement.offsetHeight returns in all the browsers indeed the height of the entire page (in my case 3482), though in IE10 it returns a different value (878).

a StackOverflow question suggests a way to get the height of the entire page in all different browsers is:
pageHeight = Math.max(document.height, document.body.scrollHeight, document.body.offsetHeight)
(http://stackoverflow.com/questions/16384340/internet-explorer-gives-total-webpage-height-as-0)

When I use this to assign the scrollHeight, the Affix indeed works well also in IE10.

**Comment by burtyish** [comment]
Would one of the maintainers please respond on this issue? @MaaikeB has put the time into making a PR, so a response would be nice.

**Comment by taion** [comment]
You need to actually submit the PR - we can't really do much with just a commit on a fork.

**Comment by MaaikeB** [comment]
Thanks, will do.

**Comment by burtyish** [comment]
I mistakenly thought a PR was made. Thanks for the response, @taion

**Comment by AlexKVal** [comment]
Closed by https://github.com/react-bootstrap/react-bootstrap/pull/1180#issuecomment-134212761
