### ISSUE TITLE
Modal component error "Uncaught TypeError: Can't add property dialog, object is not extensible"

### ISSUE THREAD

**Issue by haizz** [react-bootstrap/react-bootstrap#1074]
The error gets raised here: https://github.com/react-bootstrap/react-bootstrap/blob/master/src/Modal.js#L229

Client code:

```javascript
var ItemPropertiesModal = React.createClass({
// ...
    render: function() {
        return (
            <Modal {...this.props} 
                show={true}
                animation={false} backdrop={false}>
                <Modal.Header closeButton>
                    <Modal.Title>Blabla</Modal.Title>
                </Modal.Header>
                <Modal.Body>
                    // ...
                </Modal.Body>
                <Modal.Footer>
                    // ...
                </Modal.Footer>
            </Modal>
        );
    }
});
```

I'm using webpack and babel-loader for my own code excluding installed node_modules:
```javascript
var webpack = require("webpack");
module.exports = {
  // ...
  module: {
    loaders: [{
            test: /\.js/,
            loader: 'babel',
            query: {
                cacheDirectory: 1,
                optional: ['es7.objectRestSpread', 'runtime'],
            },
            exclude: /node_modules/,
        }]
  },
  // ...
}
```

**Comment by jquense** [comment]
version of react?

**Comment by haizz** [comment]
React 0.13.3
Modal works fine with React-Bootstrap 0.24.0

**Comment by jquense** [comment]
I am not sure how to produce this, I can see why it might happen but not when, All our tests work fine with this code.

**Comment by abhinavsingi** [comment]
For me its reproducible every time, I'm using version 0.24.2
Whenever I click to open a modal - it opens 1st time - but 2nd time onwards
this error comes

On Tue, Jul 28, 2015 at 5:28 PM, Jason Quense <notifications@github.com>
wrote:

> I am not sure how to produce this, I can see why it might happen but not
> when, All our tests work fine with this code.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/react-bootstrap/react-bootstrap/issues/1074#issuecomment-125574330>
> .
>



-- 
Regards,
Abhinav Singi
CSE, IIIT-Hyderabad, India

**Comment by jquense** [comment]
I realize that ya'll are suffering from this, what I am saying is that I can't fix it because I cannot create the reproduce it. Can someone provide a jsbin or fiddle that produces the error?

**Comment by haizz** [comment]
Is there any react-bootstrap.js dist file available on https to put into jsfiddle?

Anyway, I've put together the simplest HTML which reproduces the error.
http://sazonets.kiev.ua/react-bootstrap-0.24.2-modal-error-demo.zip

Open test.html, go to browser console, see the error. Try to close the modal, see more errors and modal not closing.

My browser is Chrome 44.0.2403.89 (64-bit) on OS X

**Comment by jquense** [comment]
Thanks @haizz that helps a lot, the key difference it seems is `backdrop={false]`. I have already sent a PR fixing it, in the meantime there are two workarounds.

1. Don't set backdrop to `false`
2. Only run in "production" mode, where there error doesn't occur.

**Comment by mtscout6** [comment]
@haizz For the jsfiddle integration have you tried using the bower package file from https://raw.githubusercontent.com/react-bootstrap/react-bootstrap-bower/master/react-bootstrap.js If that doesn't work perhaps opening another issue about it would help so that support request doesn't get lost.
