### ISSUE TITLE
Modal:  Adding scollbar padding to fixed navbar / other elements

### ISSUE THREAD

**Issue by joemcbride** [react-bootstrap/react-bootstrap#1077]
The new modal adds padding to the page `body` for the size of the scrollbar.  If you are using a fixed `navbar` it doesn't get the padding, so you can visibly see the `navbar` shift.

I can check the page for the navbar-fixed-top/bottom classes and apply the padding (using my own scrollbar calculation), though it would be nice if I could get this information from the modal events.  We have other "fixed" components that will also need this padding when the modal is open.  Maybe provide the padding calculation in the `onEnter/onEntered/onEntering` functions?

**Comment by joemcbride** [comment]
Oh, I also forgot to mention, that IE10/11 appear to not need the scrollbar padding, though IE9 does :tada: .  Different bug for that?

**Comment by jquense** [comment]
tbh I have started and given up trying to track down what the deal is with this particular issue. The side nav on the docs site is also affected, however, http://getbootstrap.com/css/ which also has an affixed side nav doesn't move at all. There must be a difference in how we are applying the padding but I haven't had much luck figuring it out :/

**Comment by dsemenovsky** [comment]
Please, have a look at their approach to this problem and fix this.

https://github.com/twbs/bootstrap/pull/10625/commits/26bbcf0aa0c81d99b41b9d467d323d5c8d011d63

**Comment by jquense** [comment]
I don't think that is a fix to this problem. the upstream bootstrap still has this problem afaict

**Comment by rkhaimov** [comment]
You can just use
`body.modal-open {
  padding-right: 0 !important;
}`

**Comment by BenjaminVanRyseghem** [comment]
I know it's an old issue, but it's worth noting that on OSX, with no mouse, the scrollbars don't appear at all, meaning the padding is unneeded.

**Comment by wmtpratikk** [comment]
it's still there in version 1.0.0-beta.9.
is there any solution for this.

**Comment by nikoisonfire** [comment]
I can't believe it's been 5 years and this still hasn't been fixed :(
