### ISSUE TITLE
Modal (and probably others) should use componentWillUnmount

### ISSUE THREAD

**Issue by zerkms** [react-bootstrap/react-bootstrap#1078]
Currently all listeners and some other routines are handled in `onHide` method:

      componentDidUpdate(prevProps) {
        let { animation } = this.props;

        if ( prevProps.show && !this.props.show && !animation) {
          //otherwise handleHidden will call this.
          this.onHide();
        }
        else if ( !prevProps.show && this.props.show ) {
          this.onShow();
        }
      }

https://github.com/react-bootstrap/react-bootstrap/blob/master/src/Modal.js#L268

So the only way `this.onHide` is invoked is when it was about to update.

If you have a layout like:

    <MyComponent>
        <Modal ... />
    </MyComponent>

and at some moment I remove the `MyComponent` from the page then the `Modal` does not have chance to unbind its listeners and clean up mess after itself.

This might be solved if `this.onHide()` is invoked in `componentWillUnmount` additionally.

As a workaround in `MyComponent` I used a dirty

    componentWillUnmount() {
        this.refs.modal.onHide();
    }

and assigned a `ref="modal"` to the corresponding `Modal` element.

**Comment by jquense** [comment]
nice catch, would like you like to PR that change?

**Comment by zerkms** [comment]
sure, I'll give it a try this evening

**Comment by taion** [comment]
Isn't this conflating a couple of concepts here? i.e. `onHide` means the user requested a hide and will do stuff like `this.setState({showModal: false})`.

I'd think you'd actually want to handle this with a `componentWillUnmount` on whatever is inside the `Modal`.

**Comment by zerkms** [comment]
@taion not sure I see your point, could you please elaborate?

**Comment by taion** [comment]
Let's say you have:

```js
<Modal show={...}>
  <MyComponent />
</Modal>
```

Why can't you put the cleanup in `MyComponent#componentWillUnmount`?

**Comment by zerkms** [comment]
@taion cleanup of *what*? I don't have anything I own that I need to clean up, it's `Modal` that does not clean up after itself.

**Comment by taion** [comment]
Your `onHide` method is going to be something like `() => this.setState({show: false})`, right? Are you saying that it's necessary to call this as the `Modal` unmounts?

**Comment by zerkms** [comment]
I don't have any `onHide` method, it's an internal `Modal`'s method.

**Comment by taion** [comment]
Ah! Sorry, I misunderstood. That makes sense, thanks.

**Comment by zerkms** [comment]
Okay :-) So if none of you will fix it till this evening I'll try to allocate some time to have a look on it. At quick glance it should be a really easy fix, but need to ensure nothing breaks with that.

**Comment by zerkms** [comment]
@jquense 

I have created a PR.

The whole `Modal` component looks a bit tired and requires some refactoring love perhaps. The callbacks are invoked here and there.

**Comment by jquense** [comment]
thanks I added a comment in the PR on a different note, why do you think the modal code looks tired? it was actually all refactoring heavily less then a few weeks ago (hence this bug which is a regression)

**Comment by zerkms** [comment]
@jquense from my perspective the callbacks handling should be in a single place, not spread all over the code. Currently there is no easy way to tell when and why `this.props.onHide` will be called

**Comment by taion** [comment]
Fixed by #1079.
