### ISSUE TITLE
radiogroup getValue return wrong value

### ISSUE THREAD

**Issue by MaxwellZhou** [react-bootstrap/react-bootstrap#1082]
dell all,
the radiogroup getValue return last not current value.what can i do  to get the current value?
here is  my code:
```javascript
<FormControls.RadioGroup name="thing" defaultValue="2" inline ref="radioGroup" onChange={this.radioGroupOnClick}>
                    <FormControls.RadioButton label="1" value="1" />
                    <FormControls.RadioButton label="2" value="2" />
                    <FormControls.RadioButton label="3" value="3" />
                </FormControls.RadioGroup>

```
```
 checkboxGroupOnchange: function (e) {
        console.log(this.refs.checkboxGroup.getValue());
    },
```
can anybody help me? thinks.

**Comment by taion** [comment]
???? We don't have a `RadioGroup` component (yet)

**Comment by mtscout6** [comment]
It's in the works but it hasn't landed yet See #962

**Comment by MaxwellZhou** [comment]
thanks for all .
I find a way to reslove this problem just like this.
```javascript
// find out the htmlNode
getButtonGroupNode() {
        return React.findDOMNode(this.refs.checkboxGroup);
  }
// return the RadioGroup current value.
getValue() {
        let result;
        // convert HTMLCollection  to Array
        let children = Array.prototype.slice.call(this.getButtonGroupNode().querySelectorAll('input[type=radio]'));
        // find out the radio which was checked
        result = children.filter(item => {
            return item.checked;
        });
        // checkbox group only one can be checked.
        return result[0].value;
    }
```

**Comment by aabenoja** [comment]
I seriously question how you're able to pull down my changes when I'm still working on a handful of issues. Either way, the state is still updating by the time your callback is invoked. I don't feel comfortable with iterating over all the inputs to get a checked item when that's already being tracked by the state, especially when a radio group can only have one selected value.

There are a couple of things worth noting. The callback is given the new selected value as a parameter, so the following will yield the expected result:
```js
radioGroupOnClick: function (newValue) {
  console.log(newValue);
}
```

It is possible for me to have it invoke your callback as soon as the state has been fully updated, but I would rather not block the callback on an async operation.
