### ISSUE TITLE
Escape key closes all modals at once

### ISSUE THREAD

**Issue by sergey-cheperis** [react-bootstrap/react-bootstrap#1083]
If there are more than one Modal's on the page, Esc key closes all of them. It seems more logical to close only the latest one.

**Comment by jquense** [comment]
This is actually due to bootstrap modals not supporting stacked, or multiple modals. Boostrap has no concept of "more then one modal open at a time", AS a workaround you can wrap The modal in your own component that disabled keyboard behavior and provide your own.

**Comment by jquense** [comment]
also watch this space: #1084

**Comment by taion** [comment]
Is there anything more we need to do here? Is the idea that we might eventually support this if someone wants to explicitly use `ModalManager` from react-overlays, or is this something for a user to handle directly?

**Comment by jquense** [comment]
So there is probably nothing else to do here, but giving how the ModalManager is currently built, once we move the Modal onto react-overlays it will inherit the only-close-the-most-recent behavior. We should talk about whether that's actually something we want to do though, or do we need a way of disabling that.

**Comment by taion** [comment]
I guess we can figure that out once we get an "escape key doesn't close all the modals" issue.

Superseded by #1084, then.
