### ISSUE TITLE
Proposal: Split Modal, Overlay, Transition, and other utilities into a new library

### ISSUE THREAD

**Issue by taion** [react-bootstrap/react-bootstrap#1084]
Per discussions w/@cesarandreu and @jquense on Slack -

We have really mature/feature-full core utilities for overlays and modals, that are useful to projects that otherwise don't use Bootstrap (including some of my own). However, per e.g. #1060, there's necessarily a conflict between making those components usable in the generic case, v. making them map well to equivalent Bootstrap components.

I think the best way to resolve this is to

1. Spin up a new library that holds the "generic" implementations of the relevant utility components
2. Use this library to handle the core logic for the React-Bootstrap components
3. Keep the components in React-Bootstrap logically similar to the upstream Bootstrap ones

What do you think?

**Comment by jquense** [comment]
I really like this idea I also use these utilities outside of bootstrap styling often. A separate package, lets us defer a lot of more general requests that these components get upstream a ways. Which helps us manage feature quests in a more structure way I think, while this project can focus on providing bootstrap specific stuff.


Selfishly: this would also let me drastically simplify or eliminate my react-bootstrap-modal project

**Comment by AlexKVal** [comment]
:+1:

**Comment by dozoisch** [comment]
I really like this idea!

**Comment by cesarandreu** [comment]
Yes!! Totally think this is a great idea :D.

Although definitely being selfish too, because I wanna use these em without bootstrap.

**Comment by jquense** [comment]
So I have some initial work: https://github.com/react-bootstrap/react-overlays

I'll open up some issues there about it :P

**Comment by jquense** [comment]
done I think?

**Comment by taion** [comment]
Were you still looking to move some of the logic for `Modal` out into react-overlays? Or rather use the logic from there?

**Comment by jquense** [comment]
ahh yes. working on that. Been taking my time though :P
