### ISSUE TITLE
NavItem renders with an unsupported ARIA attribute

### ISSUE THREAD

**Issue by jrullmann** [react-bootstrap/react-bootstrap#1089]
The aria-selected attribute is rendered for NavItems, resulting in markup that looks like this:

```
<a href="#/some-url" aria-selected="true" data-reactid="some-react-id"><span data-reactid="some-react-id"> some-label</span></a>
```

Running this markup through [Google Accessibility audit](https://chrome.google.com/webstore/detail/accessibility-developer-t/fpkknkljclfencbdbgkenhalefipecmb?hl=en) results in an error: 

```
[Severe] This element has an unsupported ARIA attribute
```

Looking at the ARIA docs, it appears that aria-selected is not in the list of [supported states and properties](http://www.w3.org/TR/wai-aria/roles#link).

Changing the attribute to aria-expanded causes the warning to go away, so it may be an appropriate alternative.

It appears that aria-selected was added to NavItem as part of this commit: https://github.com/react-bootstrap/react-bootstrap/commit/722969ddc439310ed612d7adda6b2155389bf64c

**Comment by jquense** [comment]
Hi there, 

thanks for the heads up about the google audit. Is your contention that `aria-selected` is not valid for the `a` tag here or just not valid at all? If you are looking for spec docs this may also be helpful: http://www.w3.org/TR/wai-aria/states_and_properties#aria-selected

**Comment by taion** [comment]
Googling around suggests that it's not valid or correct here: http://www.heydonworks.com/article/the-accessible-current-page-link-conundrum

**Comment by jquense** [comment]
I think the problem is that when they are tabs the `<a>` has a role of `button` to which aria-selected is valid. This should probably be moved up into the `linkProps` conditional, so it isn't set so aggressively

**Comment by taion** [comment]
It doesn't look like `aria-selected` is valid for the `button` role, though - is it? http://www.w3.org/TR/wai-aria/roles#button

**Comment by jquense** [comment]
Sorry, long day. It's valid for `tab` roles: http://www.w3.org/TR/wai-aria/roles#tab which is why it was added originally, but added over zealously I think. it should only be applied when the role is `tab`.
