### ISSUE TITLE
Way to pass props to `SafeAnchor` through `NavItem`

### ISSUE THREAD

**Issue by chrisvfritz** [react-bootstrap/react-bootstrap#1098]
I'd like to set arbitrary attributes on the anchor tag in a `NavItem`, but I don't see a way to do that right now. Could we add the ability to do this through a `linkProps` or similar?

**Comment by AlexKVal** [comment]
just for refs: it's similar to https://github.com/react-bootstrap/react-bootstrap/issues/629 and https://github.com/react-bootstrap/react-bootstrap/pull/764

**Comment by taion** [comment]
I'm closing this to consolidate discussion in #629.
