### ISSUE TITLE
react-14 branch doesn't build because of the react-router dependency

### ISSUE THREAD

**Issue by ncthis** [react-bootstrap/react-bootstrap#1101]
I know that react 0.14 would not be supported until a stable release. But I was looking to build it when I figured out that because of the peer-dependency in react-router, this can't happen. (I'm not using react-router in this particular instance though)

For the moment, I have this "setup" script in my package.json which does:
```shell
$ npm install && cd node_modules/react-bootstrap && npm install || true && npm run lib-build
```

(`|| true` to continue on `EPEERINVALID` of npm)

And in dependencies:
```shell
"dependencies": {
    ...
    "react-bootstrap": "https://github.com/react-bootstrap/react-bootstrap/archive/react-14.tar.gz",
    ...
}
```

**Comment by taion** [comment]
What do you mean? Our only peer dependency is on React: https://github.com/react-bootstrap/react-bootstrap/blob/2ec852809c830e43c4a4a980481ca9e800b8cedd/package.json#L42-L44

**Comment by ncthis** [comment]
Sorry about the confusion.

I meant to say react-router has a peer dependency with react-13.

And react-bootstrap depends on react-router: https://github.com/react-bootstrap/react-bootstrap/blob/2ec852809c830e43c4a4a980481ca9e800b8cedd/package.json#L98

**Comment by taion** [comment]
That's a dev dependency. Why are you specifically installing React-Bootstrap subdeps?

**Comment by ncthis** [comment]
Let's dial it back. If I'm to use the react-14 branch in my project how should I do it?

**Comment by taion** [comment]
You should just be able to set the dependency as `react-bootstrap/react-bootstrap#react-14`. Note that since there hasn't been much work done here, not everything is guaranteed to work.

**Comment by ncthis** [comment]
I think I should have reported this instead. Doing an npm install on that leaves me with: 

![](https://photos-6.dropbox.com/t/2/AAC6Kqd_5aCb8nJ-ZRq1TgZT4yp1MhcNtteOXm0DnEAnwA/12/3240167/png/32x32/1/1438675200/0/2/Screenshot%202015-08-04%2012.11.52.png/COfhxQEgASACIAMgBCAFIAYgBygBKAI/Sg_0xLXUWF1y9Pmto5T2ope0YLsKu_NSvHUKiKBlKYo?size=1280x960&size_mode=2)

I think the there's something wrong with the published package?

**Comment by taion** [comment]
Oh I see - I guess we have to publish a proper pre-release on NPM, since we have the dist files under `.gitignore`. Hopefully someone can take a stab - I'm traveling for the rest of the week.

**Comment by ncthis** [comment]
When installing the dev dependencies to build, the there would be a `EPEERINVALID`. But the build process would be successful, and things would mostly work.

**Comment by jquense** [comment]
there really isn't much we can do about this. npm doesn't let you install invalid peers, either remove the dev deps while you build or upgrade to npm 3.

**Comment by ncthis** [comment]
I'm not saying this is ideal, but you could build a 0.14 compatible version from branch `react-14` and semver it accordingly and publish to npm.

**Comment by jquense** [comment]
The thing is we can't actually build a version without hacking out all or incompatible dev dependencies, we have the same problem as you. We just haven't started doing any work on `0.14` compatibility yet

**Comment by taion** [comment]
@jquense Ahh, you're right.

**Comment by ncthis** [comment]
@jquense Ok, yes, I understand. Thanks.
