### ISSUE TITLE
Prev, Next, Last, First buttons on Pagination handle clicks even if they are disabled

### ISSUE THREAD

**Issue by ilyapalkin** [react-bootstrap/react-bootstrap#1102]
When active page is the last one then button "Next" is disabled but click event is still handled and `activePage` is incremented  

It can be checked on the demo page http://react-bootstrap.github.io/components.html#pagination-more

**Comment by mtscout6** [comment]
We'd accept a pull request to fix this if you care to take a stab at it. :wink:

**Comment by mtscout6** [comment]
Ah didn't realize #1104 was a thing (Quietly walking away)

**Comment by jquense** [comment]
and #1103 we are swimming in PRs for this one :P

**Comment by ilyapalkin** [comment]
@mtscout6 next time then. You fixed it even before I started.
