### ISSUE TITLE
Using Bootstrap Popovers in React without JSX

### ISSUE THREAD

**Issue by vgoklani** [react-bootstrap/react-bootstrap#1112]
I'm trying to re-create this example without JSX:

http://react-bootstrap.github.io/components.html#popovers-overlay-trigger

In particular, this line is causing me a headache:

	 <OverlayTrigger trigger='click' placement='left' overlay={<Popover title='Popover left'><strong>Holy guacamole!</strong> Check this info.</Popover>}>
	      <Button bsStyle='default'>Holy guacamole!</Button>
	 </OverlayTrigger>

and my (more verbose) version:

	React.createElement("div", {id:"some_id"},
		React.createElement(ReactBootstrap.OverlayTrigger, {container:"#some_id" , trigger:'click', placement:'left', overlay:
			React.createElement(ReactBootstrap.Popover, {'title':'Popover left'},
				React.createElement("strong", {}, "Check this info.")
			)
		})
	)

The keyword "overlay" has me confused, as I'm not clear on how to rewrite it. I'm also unclear as to how to properly attach the mountNode to the parent div element, "#some_id". document.getElementbyId() doesn't work.

This is the error message I get when running the above:

    Uncaught Error: Invariant Violation: onlyChild must be passed a children with exactly one child.

**Comment by jquense** [comment]
you forgot the button. why don't you just plug it into: https://facebook.github.io/react/jsx-compiler.html

**Comment by AlexKVal** [comment]
or [babeljs.io/repl](http://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&code=%3COverlayTrigger%20trigger%3D'click'%20placement%3D'left'%20overlay%3D%7B%3CPopover%20title%3D'Popover%20left'%3E%3Cstrong%3EHoly%20guacamole!%3C%2Fstrong%3E%20Check%20this%20info.%3C%2FPopover%3E%7D%3E%0A%20%20%20%20%20%20%3CButton%20bsStyle%3D'default'%3EHoly%20guacamole!%3C%2FButton%3E%0A%20%3C%2FOverlayTrigger%3E) :cherries:
