### ISSUE TITLE
Use a react-bootstrap with a react-starter-kit.

### ISSUE THREAD

**Issue by Alienjob** [react-bootstrap/react-bootstrap#1114]
Hi, I'm trying to use a react-bootstrap with a react-starter-kit. How to do it right?

According to the instructions I cloned repository react-starter-kit and install npm modules. The program works. In the catalog of the program, I performed "npm install react-bootstrap", react-bootstrap appeared in the folder module.

Now, if I write, for example, in "LoginPage.js" : 
"import Button from '../../../node_modules/react-bootstrap/lib/Button';" 
I get error 
"Error: Cannot find module 'babel-runtime/helpers/extends" 

, if i am write 
"import rb from 'react-bootstrap' 
i get error 
"ERROR in ./~/react-bootstrap/lib/OverlayTrigger.js
Module not found: Error: Cannot resolve module 'react/lib/warning' in /home/alien_job/Dropbox/projects/Pet/node_modules/react-bootstrap/lib
@ ./~/react-bootstrap/lib/OverlayTrigger.js 28:23-51
ERROR in ./~/react-bootstrap/lib/utils/deprecationWarning.js
Module not found: Error: Cannot resolve module 'react/lib/warning' in /home/alien_job/Dropbox/projects/Pet/node_modules/react-bootstrap/lib/utils
@ ./~/react-bootstrap/lib/utils/deprecationWarning.js 8:23-51"

**Comment by jquense** [comment]
Hi there. I don't know anything about react starter kit but you can see our getting started guide on the website for how to install and use react bootstrap

**Comment by Alienjob** [comment]
Thank you so much. Sorry for your time

**Comment by Alienjob** [comment]
https://github.com/kriasoft/react-starter-kit
"import Button from 'react-bootstrap/lib/Button';" works
