### ISSUE TITLE
Clarify ES6 import examples on Starting Page

### ISSUE THREAD

**Issue by AlexKVal** [react-bootstrap/react-bootstrap#1115]
https://github.com/react-bootstrap/react-bootstrap/issues/350#issuecomment-128554486

**Comment by jquense** [comment]
I am a bit ambivalent about this one. The comment seems to reflect more a lack of understanding of the module syntax then a failure of bootstrap, but I guess we already have amd and commonJS examples so might as well add an es6 module one?

**Comment by taion** [comment]
Agree that the original comment just shows a lack of understanding of ES6 imports, but we may as well document it anyway for completeness. I bet we have more ES6 than AMD users anyway.
