### ISSUE TITLE
Is it possible to use react-bootstrap in es5?

### ISSUE THREAD

**Issue by misterfresh** [react-bootstrap/react-bootstrap#1118]
I find react-bootstrap useful but so far I'm stuck on the latest es5 version, I think 0.17. I'd like to keep code consistent in my application. A large part is coded in es5. Porting all to es6 just to use the latest version of react-bootstrap seems not practical. Especially all the "require" calls to change to "import" by hand. Is there a way to use the latest version of react-bootstrap in es5 ?

**Comment by AlexKVal** [comment]
You are not required to use ES6 at all to use the `react-bootstrap` library.
The library itself is written on ES6, but it is then transpiled (by `babel`) into ES5.
And this ES5 version is distributed by `npm` and `bower` :sparkle: 

Here http://react-bootstrap.github.io/getting-started.html is the short example how you can use it in ES5 through CommonJS:
```js
var Alert = require('react-bootstrap/lib/Alert');
// or
var Alert = require('react-bootstrap').Alert;
```

or AMD:
```js
define(['react-bootstrap/lib/Alert'], function(Alert) { ... });
// or
define(['react-bootstrap'], function(ReactBootstrap) { var Alert = ReactBootstrap.Alert; ... });
```

I hope it will help :cherries:

**Comment by misterfresh** [comment]
I'm using react-bootstrap in Common JS then browserify. 

When I tried using the es6 versions of react-bootstrap, the problem I ran into, is how to extend a react-bootstrap component? 

For example, say I want to add a custom Glyphicon in the header of a collapsible Panel. In ES5 version , I write my own version of the Panel component with the following modifications : 

    renderPanelGlyph: function () {
        var glyph = this.props.glyph;
        return (
            <Glyphicon
                className="panel-title-icon"
                glyph={glyph}
            />
        );
    },

    renderCollapsableTitle: function (header) {

        return (
            <h4 className={this.prefixClass('title')}>
                {this.renderPanelGlyph()}
                {this.renderAnchor(header)}
                <Glyphicon
                    className={this.isExpanded() ? 'panel-title-glyph panel-title-glyph-expanded' : 'panel-title-glyph'}
                    glyph='menu-left'
                />
            </h4>
        );
    },    
To do so, I need to require dependencies : 
    var BootstrapMixin = require('../../../../../node_modules/react-bootstrap/src/BootstrapMixin');
var CollapsableMixin = require('../../../../../node_modules/react-bootstrap/src/CollapsableMixin');
This is because with React I can't override the "renderCollapsableTitle" method, I am forced to define a new component if I want to change something.

**Comment by jquense** [comment]
I think you are conflating a few things. All versions of react bootstrap are es5. we write in es6, and compile the code to es5 and release that.

From your example you are requiring the modules wrong: `require('react-bootstrap/lib/Button')` is the correct way to do it.

In terms of chaning the component classes, monkey patching our classes is never going to be a supported option, and is generally a realyl bad strategy for extending components. Creating new components that wrap the existing ones is the better option.

**Comment by AlexKVal** [comment]
Ahh.. you real issue is: :tada: :smile: 
> how to extend a react-bootstrap component?

@jquense already gave you the right one answer about it :+1: 
> Creating new components that wrap the existing ones is the better option.

--
Aside question: how are you requiring it from the `src` folder ? :cold_sweat: 
```js
var BootstrapMixin = require('../../../../../node_modules/react-bootstrap/src/BootstrapMixin');
```
`NPM` package doesn't contain the `src` folder:
<img width="212" alt="screen shot 2015-08-07 at 4 43 00 pm" src="https://cloud.githubusercontent.com/assets/847572/9137004/8d3ea574-3d23-11e5-98e1-d502e3a82e2e.png">

**Comment by misterfresh** [comment]
I'm still using v0.18 of react-bootstrap which has an src folder.
Thanks for the advice, I see I have to change the way I was extending react-bootstrap components. Could you point to an example of wrapping maybe?

**Comment by misterfresh** [comment]
I played around a bit with the wrapping.
I don't think you can change the behaviour of the wrapped components' methods, because of immutability.
But I was able to do what I needed with the latest version of React-Bootstrap  by redefining a Panel component, so you can close the issue. Thanks.

**Comment by AlexKVal** [comment]
> I was able to do what I needed with the latest version of React-Bootstrap by redefining a Panel component

Other people had the same problems you had, and they had created issues with a `feature requests` and had created pull requests to make `R-B` components more customizable. :sparkle: 

Like this https://github.com/react-bootstrap/react-bootstrap/pull/1052,
or [feature request](https://github.com/react-bootstrap/react-bootstrap/issues/629) and a [possible solution](https://github.com/react-bootstrap/react-bootstrap/pull/1071) to it,
and like this: [feature request](https://github.com/react-bootstrap/react-bootstrap/issues/878) and the same author made a [PR for it](https://github.com/react-bootstrap/react-bootstrap/pull/879)
You've got the idea :wink: 

That's the cause you now can do it with the latest version :wink: 
And what is the best with it - you can do it as well :+1:

**Comment by misterfresh** [comment]
I dont mind creating a pull request. I just wouldnt want react-bootstrap to become too heavy. If you think adding Glyphicons at the beginning of Panel headers is a widely requested feature that is worth putting in RB core, I can do the pull request. Otherwise the code is all in https://github.com/react-bootstrap/react-bootstrap/issues/1118#issuecomment-128701044 so there is nothing complicated if someone else wants to achieve the same result.

**Comment by jquense** [comment]
I would just open an issue with the feature request you want first, Sometimes components are already in the middle of being refactored by folks so its better to try and coordinate
