### ISSUE TITLE
ListGroupItem doesn't provide eventKey in onClick callback

### ISSUE THREAD

**Issue by deser** [react-bootstrap/react-bootstrap#1120]

**Comment by taion** [comment]
Indeed - looks like that prop is a no-op. Should we just drop it for `ListGroupItem`?

**Comment by deser** [comment]
I think you can support it)

**Comment by taion** [comment]
`eventKey` is for select-ables. We don't support `onSelect` for `ListGroup` - I'm not sure it even has a clear meaning there.

**Comment by deser** [comment]
Still you can apply it on click handler.

**Comment by taion** [comment]
That would make `onClick` here inconsistent with `onClick` elsewhere. If you need to check `eventKey`, just use `this.props.eventKey`.

**Comment by deser** [comment]
OK) Thank you!
