### ISSUE TITLE
How to disable warnings in console

### ISSUE THREAD

**Issue by vgoklani** [react-bootstrap/react-bootstrap#1126]
How do I remove these warnings from my dev console:

"Warning: [react-bootstrap] Specifying only the `"hover"` trigger limits the visibilty of the overlay to just mouse users. Consider also including the `"focus"` trigger so that touch and keyboard only users can see the overlay as well."

I agree with the warnings, but I need the hover.

How do I include both the hover and the focus?

**Comment by AlexKVal** [comment]
You are using `OverlayTrigger` component.
You can look at the documentation for it here at 
http://react-bootstrap.github.io/components.html#overlays-trigger-props.
<img width="728" alt="screen shot 2015-08-09 at 12 51 49 pm" src="https://cloud.githubusercontent.com/assets/847572/9154407/7b5d1138-3e95-11e5-8418-103318da09f7.png">
Then you can do it just by removing `trigger` attribute from your code and it will use
default `["hover", "focus"]` value, exactly what you need.

You can check it here (all examples are editable sources):
http://react-bootstrap.github.io/components.html#popovers-trigger-behaviors
Just remove `trigger='focus'` from the second overlay button and it will work
on focus (as it seen on the screenshot) and with mouse over.
<img width="735" alt="screen shot 2015-08-09 at 12 55 09 pm" src="https://cloud.githubusercontent.com/assets/847572/9154425/1b4cb4b4-3e96-11e5-871b-2539603b5555.png">

I hope it helps :cherries:

**Comment by taion** [comment]
Separately, those warnings only show up when running in a non-production environment. They're suppressed when running in a production configuration.

But you can also just do as @AlexKVal said, or explicitly specify `trigger={['hover', 'focus']}`.

**Comment by vgoklani** [comment]
How do you run this in production mode? is there some type of setting?

**Comment by taion** [comment]
Set `NODE_ENV` to `production`.

**Comment by wmadden** [comment]
We're using it with "hover" in order to exclude touch devices, so the warning's really annoying (and drowns out warnings from other things that we _do_ care about). I can't say I'd be sorry to see this warning removed.

**Comment by taion** [comment]
What's the point of having tooltips that can't be used at all on mobile? That sounds horribly inaccessible.

**Comment by wmadden** [comment]
The tooltips are annoying as hell on mobile. On desktop they're a nice convenience for people exploring the UI, on mobile they're an inconvenience. More to the point though, it's not up to the library to make that decision for the consumer.

**Comment by jquense** [comment]
> More to the point though, it's not up to the library to make that decision for the consumer

that's literally exactly the point of libraries, the alternative is called rolling your own.

If you want to disable warning then mutate the propTypes on the component, or just generate a uid in default props. In either case we aren't making it easy to make something that is broken-by-default for a large subset of users.

**Comment by trentontri** [comment]
@jquense Is it necessary to fill up the console with error messages for something like accessibility? You don't see Twitter Bootstrap doing this. 
I agree with @wmadden not making a component "accessible" across all device types should be a decision made by the end developer. 
There are plenty of use cases for this decision that are not a misuse of the framework.

**Comment by taion** [comment]
We'd consider a PR to disable a11y-related warnings on React prop types. As always these warnings that get stripped out in production anyway are intended as development aids, and in general we want to warn people away from using bad patterns.

**Comment by jquense** [comment]
> Is it necessary to fill up the console with error messages for something like accessibility

yes, warnings are for noting when important things are missing or wrong

**Comment by mezod** [comment]
the truth is that it is really hard to see any other warnings when the console is flooded with these warnings. I am not sure if I made a wrong accessibility decision, I am trying to mimic the preview of twitter/facebook, so if a @nickname is hovered it shows a preview, and if clicked it goes to the user's page. Thus, making it impossible to use focus/click to avoid the warning. I understand this preview wouldn't be accessible for mobile users, but this is exactly what happens to facebook/twitter users, and they kind of set the standard :p

**Comment by taion** [comment]
Like I said upthread, we'd consider a PR for suppressing a11y warnings. Otherwise, further commenting on this thread is not productive.
