### ISSUE TITLE
Modal closes on `Enter` key press when there's a form

### ISSUE THREAD

**Issue by cassidoo** [react-bootstrap/react-bootstrap#1128]
I'm having a weird issue where if I have a form in the modal, the entire modal closes when I hit the enter key.  But when I don't have a form, just the inputs, it doesn't.  How do I fix this?

**Comment by karlguillotte** [comment]
This might do the job. Good luck. 

```
<form onSubmit={event => event.preventDefault()}>
  ...
</form>
```

**Comment by jquense** [comment]
so there is nothing in the modal code, as far as I can see, that would respond to a form submit...I assume tho that the enter is trigger a submit, which is triggering a reload on the page, which causes the components to unmount? Honestly if you are handling the submit yourself I'm not really sure _why_ it'd close...

**Comment by taion** [comment]
I just checked that with e.g. @karlguillotte's code, `Modal`s with forms do not close on submit. Can you verify that you're handling form submission properly?

**Comment by taion** [comment]
I think @karlguillotte's solution handles this correctly, so I'm going to close this for now.
