### ISSUE TITLE
Alert's dismissAfter timer isn't restarting after re-render

### ISSUE THREAD

**Issue by omerts** [react-bootstrap/react-bootstrap#1132]
Hello,

I am using the alert to show a notification for 15 seconds. The problem is that if a new alert came in and I re-render, it disappears after the less than 15 seconds (to be exact it disappears after 15 - (delta between first and second message).

**Comment by omerts** [comment]
Create pull request: https://github.com/react-bootstrap/react-bootstrap/pull/1133

**Comment by taion** [comment]
Per https://github.com/react-bootstrap/react-bootstrap/pull/1133#issuecomment-129899313 - 

You're best off handling the dismiss timeout in your own code as needed. I don't really know why we support timeouts at all in `Alert`, but I think most users would be surprised if we were to change the current behavior.

**Comment by omerts** [comment]
@taion Thanks got it. Will handle it in my code.
