### ISSUE TITLE
How to create a simple anchor outside my single page app using NavItem

### ISSUE THREAD

**Issue by DavidApfel** [react-bootstrap/react-bootstrap#1139]
I have several NavItem(s) in my single page application. I want to create one specific NavItem to link to another page outside the single page application.

If I insert the code below I think the browser events are replaced and the link doesn't work:

    renderHomeItem: function () {
        return (<NavItem key={5} href="https://www.myhome.com" >Home</NavItem>);
    }

How can I insert a working anchor here?

Thanks,
David

**Comment by taion** [comment]
This is the same root issue as #419.

This is happening because you have `onSelect` defined on your `Nav`, and when present we use that instead of the default behavior.

If you want to work around this, I would move the `onSelect` handler to each of the individual `NavItem`s.
