### ISSUE TITLE
onBlur events (maybe others) not passed to inputs with <OverlayTrigger>

### ISSUE THREAD

**Issue by smschrader** [react-bootstrap/react-bootstrap#1140]
It appears that the onBlur event is not firing when the **OverlayTrigger** is applied to an input.

```javascript
<OverlayTrigger placement='top' overlay={<ToolTip>{this.props.errorMsg}</ToolTip>} delayShow={100} delayHide={100}>
    <input disabled={this.props.disable} placeholder={this.props.placeholder} id={this.props.id} data-id={this.props.dataId} className={classes} type={this.props.type} value={this.props.value} onChange={this.props.onChange} onBlur={this.props.onBlur} maxlength={this.props.maxlength} />
</OverlayTrigger>
```

**Comment by taion** [comment]
Is this something specific to our code? Is it possible that the event just isn't triggered at all?

**Comment by taion** [comment]
e.g. does this happen if you use `Overlay` directly instead of `OverlayTrigger`?

**Comment by jquense** [comment]
Is the input disabled? onBlur doesn't fire on disabled inputs, since they can't be focused in the first place

**Comment by smschrader** [comment]
No the input is not disabled. And yes the event doesn't fire at all, but it should be. I have not tested the other wrapper yet, but I worked around the issue by passing the OverlayTrigger the onBlur event I needed to fire.

**Comment by steevel** [comment]
I also ran in to this problem, solved it the same way @smschrader did by putting the onBlur on OverlayTrigger but that doesn't feel right.

I did two jsfiddles pointing the problem out:
onBlur on input: https://jsfiddle.net/g1ck0nt9/1/
onBlur on OverlayTrigger: https://jsfiddle.net/g1ck0nt9/

**Comment by taion** [comment]
It's a bug here: https://github.com/react-bootstrap/react-bootstrap/blob/master/src/OverlayTrigger.js#L186-L204 where we're not also chaining in `trigger.props.{whatever}`.

Any of you care to put together a PR?
