### ISSUE TITLE
Implement support for table column sorting.

### ISSUE THREAD

**Issue by TheDodd** [react-bootstrap/react-bootstrap#1144]
It would be great to have this functionality out of the box with the `Table` component. Simple sorting on columns.
**#FeatureRequest**

**Comment by taion** [comment]
I think this is out-of-scope - it's not part of TWBS tables, and there are a lot of subtleties and complexities to how you might want to implement sorting or e.g. filtering.

Take a look at e.g. https://facebook.github.io/fixed-data-table/example-sort.html if you're looking for a more full-fledged data table display solution.

**Comment by TheDodd** [comment]
Yea, I've looked at this a bit, but I have no need for a **fixed** table. I just need the ability to pass the data into a table component in a declarative fashion, and have the table be built out as normal, except with the ability to sort. Ascending and descending on the column. Nothing fancy.

Supporting this as an option out of the box in `react-bootstrap` seems like it would be an extremely beneficial option.

Maybe I can put together a pull request with an initial attempt and we can see how the community responds to it.

**Comment by taion** [comment]
I'm a little bit hesitant to bring in anything that's distinctly outside upstream TWBS functionality, though. Perhaps it could be a separate repo/package for the extended `Table` component?

**Comment by TheDodd** [comment]
Word. I'm thinking about forking the `react-bootstrap-table` repo to see if I can adapt it to our needs. Currently it renders two different tables ... which can cause a lot of problems under certain circumstances. I'll see what I can do about that.

Thanks for the feedback @taion.

**Comment by taion** [comment]
Sounds good. I'm going to close this for now, then.
