### ISSUE TITLE
bsStyle is no longer supported on Modal, but still documented

### ISSUE THREAD

**Issue by dozoisch** [react-bootstrap/react-bootstrap#1147]
![image](https://cloud.githubusercontent.com/assets/4422516/9237512/291c9818-4100-11e5-851e-ad4982812087.png)

If I'm not mistaken we droppped support for bsStyle on Modal in https://github.com/react-bootstrap/react-bootstrap/issues/750

but somehow the doc still show it.

**Comment by dozoisch** [comment]
Comes from  https://github.com/react-bootstrap/react-bootstrap/blob/v0.24.4/src/ModalDialog.js#L7

**Comment by mtscout6** [comment]
Related to #646

**Comment by jquense** [comment]
Ya lots of components are going to report this until we fix the mixin.

**Comment by taion** [comment]
I'm just going to take the same approach as on https://github.com/react-bootstrap/react-bootstrap/pull/1122. It's not ideal but we can sort this all out later.
