### ISSUE TITLE
Using uncss with react-bootstrap?

### ISSUE THREAD

**Issue by misterfresh** [react-bootstrap/react-bootstrap#1152]
A quick look in the audits tab of chrome console shows over 1,300 unused css rules in my project using react bootstrap.
I use npm module bootstrap-sass, and build the css with gulp-sass. 
Can I use gulp-uncss with react-bootstrap, even though the html is not yet generated?

**Comment by taion** [comment]
I think that depends on the details of how your asset pipeline is set up. I'd just give it a try - if it doesn't work (i.e. it doesn't pick up the classes we use), then it should be pretty obvious.

However, I don't see how it could pick up e.g. dynamically used classes for things like animations that aren't used at initial render but could be used later on.

**Comment by misterfresh** [comment]
It only picks up the classes used in the initial index.html file. To get it to work I probably need to do some server side rendering with react-router. Or use a different solution to remove unused css rules

**Comment by taion** [comment]
Makes sense - let me know if there's anything else you need from us.

**Comment by misterfresh** [comment]
After implementing server side rendering, gulp-uncss works, more or less. I supply it the list of routes of my application, and almost all the useful css of react-bootstrap is kept in the final css file.

However all the css that is triggered by user input, such as active links styling or css transitions, is not kept. Without the css for transitions, react can't figure out when the transition has ended, and this breaks the site. The solution is to manually set an ignore list of selectors to keep.

In the end I didnt notice meaningful performance differences with or without the unused rules, so I decided to keep them and  forget about gulp-uncss. Anyway with sass the css code can be well structured in a modular way so the unused rules are not a big problem.

**Comment by taion** [comment]
That makes sense. Without deep introspection of the JS, there would be no way for uncss to figure out which rules could get added dynamically, and I don't think there'd be a real way to do this in a foolproof manner. Glad you found that you didn't need to do this, though.
