### ISSUE TITLE
Modal header doesn't work when not an immediate child

### ISSUE THREAD

**Issue by jareware** [react-bootstrap/react-bootstrap#1162]
When you create a Modal like this (note the `<div>` in between):

```js
<Modal onHide={this.close}>
  <div>
    <Modal.Header closeButton>
      Hello
    </Modal.Header>
    <Modal.Body>
      <p>Duis mollis, est non commodo luctus, nisi erat porttitor ligula.</p>
    </Modal.Body>
  </div>
</Modal>
```

...then the close button doesn't work anymore.

Looks like [this is where we go wrong](https://github.com/react-bootstrap/react-bootstrap/blob/b29e5ecb6296e24454199cc951fcccb4e4251018/src/Modal.js#L212).

Any easy fix that comes to mind..?

**Comment by jquense** [comment]
yup, the easy fix is to also add an `onHide()` handler to the header and handle the click yourself (should just be same as your Modal onHide). Not much else we can do about that until 0.14 is released and (if we decide) we can use context for nested components like that.

**Comment by jareware** [comment]
That actually works really well for my use case, thanks a lot for the quick response!
