### ISSUE TITLE
Can't scroll <input type=text> on iPhone

### ISSUE THREAD

**Issue by hbridge** [react-bootstrap/react-bootstrap#1164]
If you text that exceeds the width of an <input type=text> field, then try to long press and scroll back, it doesn't scroll.  Reproable on the components page. Screenshot attached.
![no scroll](https://cloud.githubusercontent.com/assets/77620/9280885/5d0fdbf4-428f-11e5-9105-59a1bcb72fbc.png)

**Comment by hbridge** [comment]
this actually affects vanilla Bootstrap as well, so I've filed there as well: https://github.com/twbs/bootstrap/issues/16988

**Comment by taion** [comment]
If it's just an upstream issue, is there anything we can even do about this? I believe we pretty faithfully emit the proper Bootstrap markup.

**Comment by hbridge** [comment]
Nope, and actually, it looks like it's even further upstream: it's an iOS8 safari bug.  Google.com is broken as well.  Closing.

**Comment by dozoisch** [comment]
Obligatory =>

![boy-that-escalated-quickly](https://cloud.githubusercontent.com/assets/4422516/9285059/a68a37e6-4296-11e5-8db7-c156eec4adc4.jpg)
