### ISSUE TITLE
DropdownButton doesn't close

### ISSUE THREAD

**Issue by micahlmartin** [react-bootstrap/react-bootstrap#1170]
I've noticed an issue in the latest version that doesn't close the dropdown menu when selecting an item from the list. http://react-bootstrap.github.io/components.html#btn-dropdowns. Clicking a menu item should close the menu.

<img width="195" alt="screenshot 2015-08-16 22 17 38" src="https://cloud.githubusercontent.com/assets/171773/9296904/a22bc078-4464-11e5-8935-0e2fa8816958.png">

The only way I can get it to close is to pass an `onSelect` prop to the `MenuItem`. Even if that callback does nothing it at least closes the menu.

```
_onSelect() {
 // Do nothing
}

render() {
    return (
    <DropdownButton>
        <MenuItem href="#" onSelect={this._onSelect}>Settings</MenuItem>
    </DropdownButton>
    )
}
```

**Comment by AlexKVal** [comment]
The fix is on the way :wink: https://github.com/react-bootstrap/react-bootstrap/pull/1096
This bug is already known https://github.com/react-bootstrap/react-bootstrap/issues/526
:cherries:
