### ISSUE TITLE
Custom bootstrap css theme with react. [help wanted]

### ISSUE THREAD

**Issue by ammark47** [react-bootstrap/react-bootstrap#1175]
Hello,
I wanted to use a custom css/ bootstrap theme. I was wondering if there was a guide that could help me do that or if someone could help me out with that

**Comment by jquense** [comment]
react-bootstrap doesn't provide any css it just uses the default bootstrap stylesheet, which means taht any bootstrap theme will just work, all you need to do is include the css or follow whatever instructions the theme provides

**Comment by ammark47** [comment]
okay so i am trying to to use this theme(http://startbootstrap.com/template-overviews/landing-page/) with react and have replaced the homepage/node_modules/bootstrap files with the one provided but it is still reading from the original css files. Do you know how I can get this to work?

my repo: https://github.com/ammark47/homepage
