### ISSUE TITLE
Popover Scrolling example doesn't work on first render.

### ISSUE THREAD

**Issue by jquense** [react-bootstrap/react-bootstrap#1177]
http://react-bootstrap.github.io/components.html#popovers-positioned-scrolling

Doesn't work on the first render, because mountNode is null, I assume its due to the way @taion is handling the initial render for the examples.

If you trigger a compile on the live editable code it works perfectly

**Comment by taion** [comment]
Ooh. Yeah. I'm not even sure if I can make this work - `mountNode` doesn't resolve to a DOM node yet when doing the initial server-side render. Hmm.

**Comment by jquense** [comment]
maybe we just wrap the example and set it to `this` instead of mount node, Would that work?

**Comment by taion** [comment]
Huh - I think if I refactor things a little bit, that will work.

**Comment by taion** [comment]
Thinking about this a bit more, it's a little weird that we expose `mountPoint` directly this way. What if we change the examples so they take the form `return {node}`?
