### ISSUE TITLE
How to determine which element `ListGroup` should output.

### ISSUE THREAD

**Issue by apkiernan** [react-bootstrap/react-bootstrap#1181]
As mentioned in #1169 continuing discussion here.

Based on the discussion, it sounds like the current thinking is:
- Check the children of `ListGroup`, and if they are `ListGroupItem`s then we can render as we do currently
- If they are not (user created custom components), then we would fall back to a componentClass prop that the user would specify whether to render `<ul>` or `<div>` and render the user specified element.

**Comment by taion** [comment]
I think that's right. For the latter, `div` should probably be the default. I think this is the safest way to handle it.

**Comment by apkiernan** [comment]
For the `componentClass` prop, I believe everywhere we use this prop its propType is [elementType](https://github.com/react-bootstrap/react-prop-types/blob/master/src/elementType.js). Should we still use that here? I could see using it for consistency, but `<ListGroup>` should only be `<div>` or `<ul>` so I wonder if `React.PropTypes.oneOf(['div', 'ul'])` would be more accurate.

**Comment by AlexKVal** [comment]
I vote for `React.PropTypes.oneOf(['div', 'ul'])` :sparkle:

**Comment by taion** [comment]
Does it make sense to have a custom container component here?

**Comment by taion** [comment]
I mean a custom React component.

**Comment by apkiernan** [comment]
I can see using a custom component, but I think making it `oneOf(['ul', 'div'])` is the right call, as I think we want to ensure that the correct markup is being used.

**Comment by taion** [comment]
I'm okay with that. It wouldn't be a breaking change to allow custom components down the road anyway.

**Comment by taion** [comment]
Fixed by #1348.
