### ISSUE TITLE
Button in ListGroupItem with href causes link click

### ISSUE THREAD

**Issue by jmwyrwas** [react-bootstrap/react-bootstrap#1182]
I have a `Button` inside a `ListGroupItem` which has `href` set. When I click the button, the `onClick` function is called correctly, but then the click handler also thinks the ListGroupItem was clicked, so the page redirects to the href url.

    <ListGroup> 
      <ListGroupItem href='someurl/'>
        <Button onClick={this.onClick}>Click Me</Button>
      </ListGroupItem>
    </ListGroup>

**Comment by taion** [comment]
Isn't this what `stopPropagation` is for?

**Comment by jmwyrwas** [comment]
If both events firing is the expected functionality, this can be closed. I assumed only the Button event would fire since it is a child of the ListGroupItem.

**Comment by jquense** [comment]
yup! they are both firing because of html event bubbling.  which is the expected behavior and not actually one that RB implements itself.

**Comment by taion** [comment]
Yup - just call `e.preventDefault()` in your `onClick` handler to stop this.
