### ISSUE TITLE
[a11y] tabbedarea behavior for accessibility

### ISSUE THREAD

**Issue by Etat-Plateforme** [react-bootstrap/react-bootstrap#1194]
According to http://www.w3.org/TR/wai-aria-practices/#tabpanel, only the active tab should be focusable, for example you can do that by adding a tabindex property on each tab.
`<a role=”tab” tabindex="0" aria-selected=”true”>Active tab</div>`
`<a role=”tab” tabindex="-1" aria-selected=”false”>Inactive tab</div>`

Tabs and their corresponding panes must be linked together trough an aria-controls attribute:
```html
<nav>
	<ul class="nav nav-tabs" role="tablist">
		<li><a role="tab" aria-controls="pane-1"></a><li>
		<li><a role="tab" aria-controls="pane-2"></a><li>
	</ul>
</nav>

<div class="tab-content">
	<div id="pane-1" class="tab-pane" role="tabpanel"></div>
	<div id="pane-2" class="tab-pane" role="tabpanel"></div>
</div>
```
Finally, the user should be able to navigate through the tabs using the keyboard arrows:
* Left and Up arrows should activate the previous tab
* Right and Bottom arrows should activate the next tab

Here, activating a tab means focusing on it, and updating ARIA attributes as needed.

**Comment by taion** [comment]
I believe this has been resolved by #1250.
