### ISSUE TITLE
[a11y] infobulle feature request

### ISSUE THREAD

**Issue by Etat-Plateforme** [react-bootstrap/react-bootstrap#1196]
Feature:
The tooltip and the target element must be linked together through an _aria-describedby_ attribute:
```
<div class=”tooltip-trigger” aria-describedby=”tooltip”>Text</div>
<div id=”tooltip” class=”tooltip” role=”tooltip”>Tooltip text</div>
```
Also, when the element has focus and the tooltip is shown, the _Escape_ key should hide it.

**Comment by jquense** [comment]
Hi there, this is already the behavior of the overlay trigger. it will use the id of the provided overlay but you need to provide the id
