### ISSUE TITLE
[a11y] add aria attributes to accordion and allow keyboard navigation

### ISSUE THREAD

**Issue by Etat-Plateforme** [react-bootstrap/react-bootstrap#1197]
Feature:
According to http://www.w3.org/TR/wai-aria-practices/#accordion, different role attributes must be set on parts of the component:

``` html
<div class=”panel-group” role=”tablist”>
    <div class=”panel”>
        <div class=”panel-heading”>
            <h4><a role=”tab”></a></h4>
        </div>
        <div class=”panel-collapse” role=”tabpanel”></div>
    </div>
</div>
```

Depending on whether a tab is active, some ARIA attributes must be set on tabs and panes to add more information about their state:

``` html
<div class=”panel-group” role=”tablist”>
    <div class=”panel”>
        <div class=”panel-heading”>
            <h4><a role=”tab” aria-selected=”true” aria-expanded=”true”>Active tab</a></h4>
        </div>
        <div class=”panel-collapse” role=”tabpanel” aria-hidden=”false”></div>
    </div>
    <div class=”panel”>
        <div class=”panel-heading”>
            <h4><a role=”tab” aria-selected=”false” aria-expanded=”false”>Inactive tab</a></h4>
        </div>
        <div class=”panel-collapse” role=”tabpanel” aria-hidden=”true”></div>
    </div>
</div>
```

Tabs and their corresponding panes must be linked together trough an _aria-labelledby_ attribute:

``` html
<div class=”panel”>
    <div class=”panel-heading”>
        <h4><a id=”tab-1” role=”tab”></a></h4>
    </div>
    <div class=”panel-collapse” role=”tabpanel” aria-labelledby=”tab-1”></div>
</div>
```

When navigating with the keyboard using **tab** or **shift+tab**, and coming from an element outside the accordion, the focus should land on the first active pane, if any.

Finally, the user should be able to navigate through the tabs using the keyboard:
- _left_ and _up_ arrows should focus on the previous tab
- _right_ and _bottom_ arrows should focus on the next tab
- _space_ and _return_ should toggle the focused tab, i.e. showing it if it is closed and vice versa, thus updating aria attributes as needed.

**Comment by jquense** [comment]
this is partly being addressed byhttps://github.com/react-bootstrap/react-bootstrap/pull/1191. it's debate able whether arrow keys will be used for navigation since tab already works in these instances
