### ISSUE TITLE
ModalTrigger removed?

### ISSUE THREAD

**Issue by sconno05** [react-bootstrap/react-bootstrap#1199]
I noticed the ModalTrigger component was removed in the latest version.  My interpretation of the latest examples is that I should use the *show* prop to control modals now.  I like the addition of the prop for more complex scenarios but I found the ModalTrigger useful for simple scenarios like binding a button to a modal.  I can always roll my own ModalTrigger equivalent, but the removal of it from the library makes me think there may be another alternative that I am missing.  Thanks for your help!

**Comment by taion** [comment]
There is no other equivalent for modals at the moment. We figured that the amount of boilerplate required to set up the show state management was sufficiently low that there wasn't much benefit in having a separate `ModalTrigger` component to handle just a single special case.
