### ISSUE TITLE
Few problems with controlled TabbedArea

### ISSUE THREAD

**Issue by Nutelac** [react-bootstrap/react-bootstrap#1205]
I'm using `react-bootstrap@0.24.5-react-pre.0` together with `react@0.14.0-beta3`. I have few problems with [controlled tabs](http://react-bootstrap.github.io/components.html#tabs-controlled).

My code looks like that:
```javascript
class MyComponent extends React.Component {
  state = {
    selected: null
  }

  render () {
    return (
      <TabbedArea onSelect={this.handleSelect} activeKey={this.state.selected}>
        <TabPane key={0} eventKey={0} tab="tab 1">content 1</TabPane>
        <TabPane key={1} eventKey={1} tab="tab 2">content 2</TabPane>
      </TabbedArea>
    )
  }

  handleSelect (key) {
    this.setState({selected: key})
  }
}
```

**Problems:**
1. First `TabPane` (in this case `"tab1"`) is selected when `this.state.selected` is `null`. I think when `activeKey` is `null`, none of `TabPane` should be selected.
2. `TabbedArea` pass wrong `this` to `handleSelect` function. Passed `this` refer to `Nav` component (which `TabbedArea` using under the hood). It can be "fixed" via `this.handleSelect.bind(this)`.
3. ~~`TabPane` selecting does not work with `animation={true}`. I'm getting `undefined is not a function (evaluating '_reactDom2['default'].findDOMNode(this)` error which is probably caused by [this line](https://github.com/react-bootstrap/react-bootstrap/blob/react-14/src/TabPane.js#L48).~~ Caused by wrong `react-dom` version (`0.1.0` instead of `0.14.0-beta3`).

**Comment by taion** [comment]
1. Good point. Opened https://github.com/react-bootstrap/react-bootstrap/issues/1227 to discuss.
2. This is an error on your side - you're responsible for binding your handlers when using ES6 classes. See https://facebook.github.io/react/blog/2015/01/27/react-v0.13.0-beta-1.html#autobinding

**Comment by jquense** [comment]
I was thinking that we should also make sure not to bind handlers or call them with a context as well just to be a good citizen (and fail faster for folks forgetting to bind).
