### ISSUE TITLE
Scope support / class names replacement

### ISSUE THREAD

**Issue by cusspvz** [react-bootstrap/react-bootstrap#1207]
Is there a way to provide an object with classnames?

We will gonna need to apply different versions of styling, which will require us to use `css-loader` [scope feature](https://github.com/webpack/css-loader#local-scope).

As so, is there a way to configure classes being used by this module on `require`?

**Comment by cusspvz** [comment]
@taion , my technical point is: is there any way to replace globally all classes being used?

Something simple as, use `MyCustomClassName` instead of `btn` on `Button`.

I was reading a little bit of code and documentation ( I'm not at my 100% capacity, little lazy because I'm on vacations :tropical_drink: ) and didn't see any easily form to do so globally. If there's not, i would like to propose an API on top of **CLS**.

**Comment by jquense** [comment]
There isn't a way to globally replace all classes, but there is a good reason for it. React-bootstrap isn't a generic component library, a reimplementation of bootstrap in react. As such we are the components are tightly coupled to the bootstrap css in the same way upstream bootstrap is. Supporting the ability to completely use a new set of styles/classes is probably going to be out of scope for this project.

that being said, why would you need to modularize the bootstrap styles, the maintainance burden of that is already on someone else (the tbs team) why implement it?
