### ISSUE TITLE
Radio button checked bug

### ISSUE THREAD

**Issue by joshhornby** [react-bootstrap/react-bootstrap#1211]
```
<Input wrapperClassName='wrapper'>
    <Col xs={2}>
         <Input type='radio' name="filter" value="1" label='Foo' checked/>
    </Col>
    <Col xs={2}>
          <Input type='radio' name="filter" value="2" label='Bar' />
     </Col>
</Input>
```

Given the following code example, I'd expected the user to be able to toggle between both radio buttons but on page load the radio button with the value of `1` should be checked.

But I am unable to toggle between the buttons, it seems as I have a `checked` prop on the input this stops the toggle from working.

Although, not sure if this is getting fixed in https://github.com/react-bootstrap/react-bootstrap/pull/89

**Comment by jquense** [comment]
I am pretty sure you want `defaultChecked`, https://facebook.github.io/react/docs/forms.html

**Comment by joshhornby** [comment]
You are correct! Next time I will read the docs!

**Comment by wzup** [comment]
What is `defaultChecked`? It doesn't work. There is no info about `defaultChecked` in the link you provided.

**Comment by jquense** [comment]
the link further down https://facebook.github.io/react/docs/uncontrolled-components.html
