### ISSUE TITLE
Aligning Navbar components to the right

### ISSUE THREAD

**Issue by adkim5494** [react-bootstrap/react-bootstrap#1215]
Hi, 

I was a little confused when trying to pull the navbar item to the right. i found that we had to include the word "navbar" like so, 

![screen shot 2015-08-25 at 3 05 48 pm](https://cloud.githubusercontent.com/assets/11645453/9480941/1aca8532-4b3b-11e5-9faa-12bc4ed521b1.png)

I think the documentation was unclear. Hopefully this helps other and maybe clearing that up in the documentation would be helpful! Thanks for a great product nonetheless!

**Comment by kwnccc** [comment]
@adkim5494 the documentation describes the attribute to be boolean, which means it should be used that way:
```
<Nav right="true" />
```
Also make sure which of the attributes you really need since there is the <code>right</code> and also the <code>pullRight</code>.

**Comment by AlexKVal** [comment]
@kwnccc It is not necessary to write it as `right="true"`. It is enough just `right`.

Actually `R-B` project encourages the simplest syntax for boolean attributes.
https://github.com/react-bootstrap/react-bootstrap/pull/1005
https://github.com/react-bootstrap/react-bootstrap/pull/1009

--
@adkim5494 With the latest released version `v0.25` it is working as expected.
You can check it yourself here http://react-bootstrap.github.io/components.html#navbars-basic
Just change `<Nav>` into `<Nav right>` straight in the example code and you will see it realtime :wink: 

`Nav`
<img width="796" alt="screen shot 2015-08-26 at 4 15 10 pm" src="https://cloud.githubusercontent.com/assets/847572/9494292/e22ec82c-4c0d-11e5-85e2-433706a126b7.png">

`<Nav right>`
<img width="859" alt="screen shot 2015-08-26 at 4 15 07 pm" src="https://cloud.githubusercontent.com/assets/847572/9494303/f5aa3cce-4c0d-11e5-82d0-f92ac78135c7.png">

Additional `navbar` attribute is not necessary.
:cherries:

**Comment by adkim5494** [comment]
thanks for your help guys :)! Initially I tried to do the <Nav right> but I kept getting an error but after adding the navbar attribute, it started working but maybe it was a different error. Thanks again!
