### ISSUE TITLE
Process is not defined

### ISSUE THREAD

**Issue by cidevant** [react-bootstrap/react-bootstrap#1216]
After updating to 0.25 whole applications stops work. 

```Uncaught ReferenceError: process is not defined```

I dont have sourcemaps, so I cant provide more detailed stacktrace.

It fails in Accordion (maybe in imported files?)
__domUtils: createDeprecationWrapper(_utilsDomUtils2['default'], 'utils/domUtils', 'npm install dom-helpers')__

```js
exports.FormControls = _FormControls;
var utils = {
  childrenValueInputValidation: _utilsChildrenValueInputValidation2['default'],
  createChainedFunction: _utilsCreateChainedFunction2['default'],
  ValidComponentChildren: _utilsValidComponentChildren2['default'],
  CustomPropTypes: _utilsCustomPropTypes2['default'],
  domUtils: createDeprecationWrapper(_utilsDomUtils2['default'], 'utils/domUtils', 'npm install dom-helpers')
};
```
Here is createDeprecationWrapper
```js
function createDeprecationWrapper(obj, deprecated, instead, link) {
  var wrapper = {};

  if (process.env.NODE_ENV === 'production') {
    return obj;
  }
```

**Comment by taion** [comment]
How are you building or bundling React-Bootstrap? The built bundles don't have this. If you're building it yourself you'll need either envify or `DefinePlugin`.

**Comment by cidevant** [comment]
I have no idea what are you speaking about.

I use browserify, npm, react. When trying to run server - everything is browserified well without any errors, but when i open it in console -> error occurs

**Comment by cidevant** [comment]
I am using gulp as builder

**Comment by jquense** [comment]
when using browserify you need to use [envify](https://www.npmjs.com/package/envify) when bundling react from NPM, to provide values for `process` and `NODE_ENV`. This isn't specific to react-bootstrap, but the entire react ecosystem.
