### ISSUE TITLE
Make 'id' prop type uniform throughout the project

### ISSUE THREAD

**Issue by AlexKVal** [react-bootstrap/react-bootstrap#1219]
There are not uniform prop-type definitions now:

Tooltip, Popover:
```js
id: CustomPropTypes.isRequiredForA11y(React.PropTypes.string)
```
Dropdown:
```js
id: CustomPropTypes.isRequiredForA11y(
  React.PropTypes.oneOfType([
    React.PropTypes.string,
    React.PropTypes.number
  ])
),
```
[fix for MenuItem](https://github.com/react-bootstrap/react-bootstrap/pull/1214/files#diff-bb70ed377da60e0f35071b688a96d337R83)
```js
id: React.PropTypes.oneOfType([
  React.PropTypes.string,
  React.PropTypes.number
])
```
InputBase, ListGroup, Nav, Panel, Tabs, 
```js
id: React.PropTypes.string,
```

--
I propose to change every `React.PropTypes.string` into
```
React.PropTypes.oneOfType([
  React.PropTypes.string,
  React.PropTypes.number
])
```

What do you think guys ?
@react-bootstrap/collaborators

**Comment by mtscout6** [comment]
Sounds reasonable to me!

**Comment by dozoisch** [comment]
yeah go ahead
