### ISSUE TITLE
Regression: overlaytrigger tooltip does not disappear when used with dropdown button

### ISSUE THREAD

**Issue by petejkim** [react-bootstrap/react-bootstrap#1220]
See:
![overlaytrigger-bug](https://cloud.githubusercontent.com/assets/30173/9492248/ba5893fe-4baa-11e5-8bee-42fb8e956010.gif)

``` jsx
  <OverlayTrigger placement='top' overlay={<Tooltip>Hello World</Tooltip>}>
    <DropdownButton title="Menu">
      <MenuItem>Click Me</MenuItem>
      <MenuItem>Click Me</MenuItem>
    </DropdownButton>
  </OverlayTrigger>
```

Expected behavior:
Tooltip should disappear as soon as user moves mouse out of the button.

Actual behavior:
Tooltip does not disappear when user moves mouse from the button to the menu.
Tooltip does not disappear when user clicks on a menu item.
Tooltip does not disappear until after user moves mouse on to the trigger element and then back out to force mouseleave event.

Used to work correctly in the previous release.

**Comment by cbeihl** [comment]
Is this issue being worked ?  I'm still seeing this bug in the 0.28.1 release.

**Comment by irealva** [comment]
Also having this issue. Is there another way an overlay on a DropdownButton?

**Comment by untitledboy** [comment]
Have someone found any acceptable solutions for this bag?

**Comment by ron23** [comment]
I set the trigger to hover only as I don't need mobile support right now. Not a solution though.
