### ISSUE TITLE
OverlayTrigger mountNode location

### ISSUE THREAD

**Issue by kennyw12** [react-bootstrap/react-bootstrap#1226]
Is there a particular reason we mount the overlay at [the end of the document](https://github.com/react-bootstrap/react-bootstrap/blob/master/src/OverlayTrigger.js#L130)? This makes it hard to test OverlayTrigger in isolation.

Specifically, we're trying to do accessibility tests scoped to a particular dom node. When we create the element at the end of the document, this messes up the whole scoping thing.

with: @atomanyih

**Comment by taion** [comment]
That mount node actually is never mounted. It's just used to hold an `<Overlay>` that handles the actual rendering of the overlay.

You can pass in a `container` prop that will determine which node the overlay actually gets attached to.

**Comment by taion** [comment]
https://github.com/react-bootstrap/react-overlays/blob/v0.4.4/src/Portal.js#L20

**Comment by kennyw12** [comment]
Thank you! Sorry for the confusion.
