### ISSUE TITLE
Tooltip reposition problem

### ISSUE THREAD

**Issue by unkw** [react-bootstrap/react-bootstrap#1229]
The tooltip does not recalculate the position if the content has changed:
markup: `<Tooltip>{this.state.users.map(this.renderUserItem)}</Tooltip>`
action: `this.setState({ users: response.users })`

1) http://take.ms/BdK0x
2) http://take.ms/tOlej tooltip close the target because positioning is not recalculated

**Comment by taion** [comment]
I believe this is intentional - we don't want the tooltip to bounce around, and I believe this is how tooltips work upstream.

**Comment by jquense** [comment]
Yeah we are matching upStream, the one difference might be calling `show()` on a bootstrap tooltip will trigger an update if the tooltip is already visible (afaict), though I don't think that is a feature so much as a consequence of the implementation.
