### ISSUE TITLE
Radio buttons are broken when initialised with a 'checked' prop

### ISSUE THREAD

**Issue by amz00** [react-bootstrap/react-bootstrap#1234]
Steps to reproduce:
1) Download the latest react-bootstrap from NPM (0.25.0 as of this filing)
2) Create two checkboxes in a component of your choice and render them:
<ReactBootstrap.Input type='checkbox' label='Testr' checked />
<ReactBootstrap.Input type='checkbox' label='Testr' />
3) Try to click on the checkboxes

Expected:
You can click on both check boxes, and doing so toggles the checked state

Actual:
You can click on both checkboxes, but only the second check box will actually respond to user inputs.  The first check box, where 'checked' is specified, does not respond to user inputs.  You can see stylistic changes to indicate it is trying to do something but the visual checked-state does not change.  It's behaving like it's in read-only mode. 

Notes:
I've tried many variations of this and they all result in the same problem.  I've tried wrapping them in a <form> or leaving them as just DOM elements, no difference.

**Comment by jquense** [comment]
Hi there. unless I am missing something from you description (maybe provide a snippet or gist illustrating the issue?) this is expected. that's how inputs in React work.https://facebook.github.io/react/docs/forms.html#controlled-components if you don't want to handle toggling the checked state yourself use `defaultChecked`

**Comment by AlexKVal** [comment]
@jquense you are faster :smile:

--
@amz00 You can copy/past this code:
```js
const inputTypeInstance = (
  <form>
    <Input type='checkbox' label='Checkbox1' defaultChecked />
    <Input type='checkbox' label='Checkbox2' />
  </form>
);

React.render(inputTypeInstance, mountNode);
```
into example code editor here http://react-bootstrap.github.io/components.html#input-types
and see it yourself.
Just use `defaultChecked` as a starting state,
and `checked` for `controlled` inputs.
<img width="884" alt="screen shot 2015-08-27 at 4 36 05 pm" src="https://cloud.githubusercontent.com/assets/847572/9521819/c6000158-4cd9-11e5-9fac-73880efac4ce.png">

:cherries:
