### ISSUE TITLE
[Regression] Using props "title" for Tabs conflicts with HTML title attribute and causes buggy hover behavior

### ISSUE THREAD

**Issue by agmathew** [react-bootstrap/react-bootstrap#1238]
The switch to using the property name ```title``` is problematic since it's conflicts with the HTML title attribute. This has the side effect of causing the title to display on hover anywhere on the tab's contents. You can see this on the React Bootstrap demo page:

<img width="919" alt="react-bootstrap-tab-title-bug" src="https://cloud.githubusercontent.com/assets/3163971/9535056/8a067f76-4ceb-11e5-9dcb-193b1731eeb8.png">

On my site, I used a component as the title, so you see "[Object object]" whenever I hover anywhere on the tab's contents. I'm on Chrome.

**Comment by jquense** [comment]
thanks for the heads up!

**Comment by taion** [comment]
cc @ctaymor 

Is this intentional?

**Comment by taion** [comment]
Okay, just wanted to make sure that `title` wasn't chosen intentionally to get this behavior.
