### ISSUE TITLE
How to Import React-Bootstrap to Existing Project via JSPM?

### ISSUE THREAD

**Issue by f15gdsy** [react-bootstrap/react-bootstrap#1239]
Hi I want to import react-bootstrap to my existing React project.
I read the document about this but I'm still not very clear about it.
1. Will React-Bootstrap be compatible with my current React version? As I saw the latest one uses react@0.14.0 beta3 while I'm using react@0.13
2. How to set the dependency of the bootstrap downloaded online so that React-Bootstrap can read?

Thanks!

**Comment by f15gdsy** [comment]
I think I have figured it out :)
1. Change the React dependencies of React-Bootstrap to the one used in the existing project.
2. use html <link> tag to import the bootstrap css.

**Comment by jquense** [comment]
the latest released version of react bootstrap is for react 0.13 we also have a prerelease out for the react beta but that's not for proper use yet. using the normal 0.25 v of react bootstrap will work find with your existing Dependencies
