### ISSUE TITLE
Button Keeps Hover Color And Outline After Clicked

### ISSUE THREAD

**Issue by f15gdsy** [react-bootstrap/react-bootstrap#1240]
Hi 
Here is my code:
```
<div className='toolbar'>
    <Button onClick={this.props.addItem}>+</Button>
    <Button onClick={this.props.addItem}>-</Button>
</div>
```
When I clicked on the button, the button keeps the hover color and outline, like [this](https://dl.dropboxusercontent.com/u/27907965/images/Screen%20Shot%202015-08-28%20at%205.17.36%20pm.png), even my mouse moves away. I have to click somewhere else to make the button returns to normal.

I'm wondering how this happens?
I'm using React-Bootstrap 0.25.0 and Bootstrap 3.3.5, and running on Electron.

**Comment by jquense** [comment]
Hi there. this is browser behavior not react bootstraps. Chrome (blink/webkit) for accessibility reasons. it's not maintaining its hover state it's maintaining its focused one, which makes sense because the clicked button is focused
