### ISSUE TITLE
Dropdown menu must be rendered directly into <body>

### ISSUE THREAD

**Issue by deser** [react-bootstrap/react-bootstrap#1241]
As you can see from the picture (https://monosnap.com/file/6nqP4R48JZKZDahCOhhmp5EO4mo5mD)
if you have any parent with overflow: hidden then inner dropdown menu is cut. Also when .dropdown-menu not in <body> in doesn't  affect scrollHeight of body which causes troubles (for example I need to dynamically increase height of iframe according to its content).

**Comment by jquense** [comment]
this is a consequence of bootstraps styles for dropdowns. they are absolutely positioned to their toggle. Since this is an upstream issue there isn't anything we can do about it. you can set the parent overflow to to visible or scroll otherwise

**Comment by aaronbeall** [comment]
I agree that this is an upstream problem, but it's a pretty annoying and common one. None of the vanilla bootstrap solutions worked for me. Is there a workaround in react-bootstrap? Can we render the `Dropdown.Menu` in an `Overlay` somehow?

**Comment by jquense** [comment]
I understand that it's annoying but there really is nothing _we_ can about it here, that's how bootstrap works. You can definately make use of the `react-overlay` (specifically `Overlay` and `Position`) components to build your own version of the dropdown menu that is positioned fixed, and probably reuse the display styles of the dropdown, but you'll need to provide custom styles.

bootstrap v4 has a better dropdown and we are working as fast as we can to get support in RB for it as well

**Comment by jquense** [comment]
The v1 drop-down uses popper.js so you can control what element the drop-down is positioned too, however there isn't built support for appending the drop-down elsewhere like the body. You can easily add this tho by rendering the DropdownMenu into a portal

**Comment by aaronbeall** [comment]
@grydstedt Personally I wasn't able to get it to work with the the current bootstrap v3 dropdown. I went with @jquense's suggestion to build a custom dropdown component `Overlay` and `Popover`. My component is pretty specific to my needs, but the basic idea is:

```
class OverlayMenuButton extends Component {
  state = {
    showing: false
  };
  
  setElem = elem => this.elem = elem;
  
  onHide = () => this.setState({ show: false });
  
  onToggle = () => this.setState(prevState => ({ show: !prevState.showing }));
  
  render() {
    const { button, menu } = this.props;
    const { showing } = this.state;
    return (
      <div ref={ this.setElem } 
           onClick={ this.onToggle }>
        { button }
        <Overlay show={ showing } 
                 target={ () => this.elem } 
                 onHide={ this.onHide } 
                 placement="bottom">
          <Popover onClick={ this.onHide }>
            { menu }
          </Popover>
        </Overlay>
      </div>
    )
  }
}
```

So I can render a dropdown like this:

```
<OverlayMenuButton button={ <MyButton /> } menu={<MyMenu />} />
```
Where `MyButton` and `MyMenu` are my own styled button and menu components, but they could probably be vanilla bootstrap button and menu components.

I had also styled the `Popover` to override some of its default appearance...

**Comment by LennyLip** [comment]
@grydstedt Thanks. I use react-portal and react 15.5 and I got TypeError: Cannot read property 'contains' of null (I think it is because menu appended to the body). Did you have this error?
