### ISSUE TITLE
how to programmatically open / close a Panel

### ISSUE THREAD

**Issue by barbalex** [react-bootstrap/react-bootstrap#1258]
I have an Accordion with Panels.

When the user enters the second panel, I have a function that checks if he has entered all the necessary information in the first. If not:

- the second panel should be closed (or it's opening prevented)
- and the first reopened

So first, I have to get a correct event when the user enters the second panel.
I have tried using 'onSelect' in <Panel onSelect={...} /> but this never fires.
I have found an issue mentioning 'onClick'. That does fire. But of course now I'd have to distinguish opening from closing.

Here are the questions one by one:

- What is a good method to register when the user opens a panel?
- How can I close it (or prevent it from opening) programmatically?
- How can I open the first panel programmatically?

**Comment by jquense** [comment]
Hi there,

Take a look at this example from the documentation for pro grammatically expanding and collapsing a panel http://react-bootstrap.github.io/components.html#panels-collapsible

**Comment by barbalex** [comment]
Well, onSelect does definitely not work when the panel is placed inside an accordion.
When I remove the Accordion it works.

**Comment by barbalex** [comment]
The expanded attribute does not work either, when a Panel is inside an Accordion.
When I remove the Accordion it works.

**Comment by barbalex** [comment]
I want the user to be able to open and close Panels himself. So I have to handle onSelect. When I set the open state in the onSelect function, I get this error:

    Uncaught Error: Invariant Violation: setState(...): Cannot update during an existing state transition (such as within `render`). Render methods should be a pure function of props and state.

So that does not seem to work either.

**Comment by taion** [comment]
Don't use an `Accordion`. Just have separate collapsible panels.

**Comment by barbalex** [comment]
but how can I let the user open and close panels himself if I can't set the open state in the function called by the onSelect event?

I only want to validate the data the user has entered and react if there is an issue there. Otherwise I want the user to open and close panels himself.

**Comment by barbalex** [comment]
maybe the invariant violation is caused by the fact that the onSelect event on the panel is called 5 (!?) times while rendering the page for the first time. I honestly don't get why that should happen.

**Comment by barbalex** [comment]
I tried this now: 

- use an Accordion
- set the activeKey property programmatically
- use the onClick event on the Panel to call a function that decides which Panel to open or close

It basically works very nicely.

BUT: The onClick event fires not only on the panel heading but on the entire panel.
And onSelect does not fire.

Sigh.

**Comment by jquense** [comment]
I am not sure where you issues are coming from here, don't use an accordion, just use a bunch of individual panels like the set up below.

```
class Example extends React.Component {
  constructor(...args){
    super(...args);
    this.state = {
      open: true
    };
  }

  render(){
    return (
      <div>
        <Button onClick={ ()=> this.setState({ open: !this.state.open })}>
          click
        </Button>
        <Panel collapsible 
          expanded={this.state.open} 
          header='I fire the onSelect handler when clicked' 
          onSelect={shouldThisPanelCloseFunction}
        >
          Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad 
        </Panel>
      </div>
    );
  }
}
```

**Comment by jquense** [comment]
Or if you really want to use an accordion just follow this example:

http://localhost:4000/components.html#panels-controlled

the onSelect events fire just fine here as well.

**Comment by barbalex** [comment]
this here:

    <Accordion activeKey={activePanel} onSelect={this.handleOnSelectPanel}>

does work. Thanks.

But: It only works if the user clicks the link in the panel heading. I want the user to be able to click anywhere in the panel heading. Much better for mobile use.

So I will keep my hack using an onClick handler on ```<Panel />```

**Comment by dinzy17** [comment]
Is there any way we can close all accordion manually?
I have search filters inside accordion, on reset filters i need to close all the accordions.

**Comment by tenso2006** [comment]
We can use ref on accordion to get access to all the state and props 
Example
<accordion ref='acco'>
And on componentWillReceiveProps, update the state like so

This.ref.acco.setState({activeItems: [] })

activeItems being array of index of all opened accordion 

Hope this helps

**Comment by tenso2006** [comment]
On accordion pass in ref=acco

**Comment by Mredul-Hasan** [comment]
Hello there, I want something simpler. Just need to know if an accordion is Collapsed / Expanded while onClick header.
I haven't found onCollapsed / onExpanded event. Is there any work around?

**Comment by keshavwebnware** [comment]
I need to open all panel from out side
