### ISSUE TITLE
MenuItem events are not triggered when `href` is not set

### ISSUE THREAD

**Issue by bernharduw** [react-bootstrap/react-bootstrap#1263]
When you use a DropdownButton with MenuItems, the `onSelect` handlers are not triggered. Not even the `handleClick` function in SafeAnchor is executed.

This is because the MenuItems are rendered as `<a>` tags with an empty `href`. Neither of the `onSelect` handlers are triggered with this code:

```JS
<DropdownButton onSelect={::this.handleSelect}>
  <MenuItem eventKey='1' onSelect={::this.handleItemSelect}>Option 1</MenuItem>
  <MenuItem eventKey='2' onSelect={::this.handleItemSelect}>Option 2</MenuItem>
</DropdownButton>
```

I could work around it by manually removing the empty string default for href in [MenuItem.js#L53](https://github.com/react-bootstrap/react-bootstrap/blob/master/src/MenuItem.js#L53) and [SafeAnchor#L27](https://github.com/react-bootstrap/react-bootstrap/blob/master/src/SafeAnchor.js#L27). I don't know about all the implications, but it seems safe to me to have no href on an `<a>` tag.

Using react-bootstrap version 0.25.1, but this was the same with 0.24.5.

**Comment by taion** [comment]
@mtscout6 Is this intentional? Looks like `SafeAnchor` will take care of rendering something for `href`, and explicitly passing in the empty string here blanks the `onClick` handling on `SafeAnchor`.

**Comment by mtscout6** [comment]
No this is not intentional.
