### ISSUE TITLE
Grid in Grid

### ISSUE THREAD

**Issue by tdeheurles** [react-bootstrap/react-bootstrap#1264]
I'm trying to create Grid inside an other Grid. For now it appear not as expected.
Is this functionality available ?

**Comment by taion** [comment]
That depends entirely on what you expect to appear.

In general if you want nested grids, though, you'll want to nest `Row` elements inside `Col` elements.

**Comment by tdeheurles** [comment]
hi, I have created a `first` react component in which I have used Grid for placing Button and Label. Then I try to use that `first` component in a more global Grid.
The rendering is not the exepected one as the `first` component go outside of the cells defined by the more global Grid.

**Comment by taion** [comment]
That doesn't sound like the right approach. Take a look at what's happening in normal Bootstrap here: http://getbootstrap.com/css/#grid-nesting. Our grid components are just thin wrappers around those.

**Comment by tdeheurles** [comment]
Yeah, that was what I expected. 
I wanted à confirmation.

The feeling is bit special as we create components that seems like object. But we are still chained by css globals.

Thank you, I have my response.
