### ISSUE TITLE
Add HTML contents to tab titles

### ISSUE THREAD

**Issue by binarykitchen** [react-bootstrap/react-bootstrap#1265]
I would like to add more contents than just strings for vertical tab titles:
http://react-bootstrap.github.io/components.html#left-tabs

For example, instead of the title `Tab 1` I'd like to have

```html
<h2>Tab 1</h2>
<p>Explain something here</p>
```
as the title itself.

That would be a nice addition to enhance tabbing.

**Comment by taion** [comment]
You can already do this. Just pass a React element into `title`.

**Comment by binarykitchen** [comment]
oh cool - probably you should mention this in the documentation?

**Comment by jquense** [comment]
The docs already mention it :) IF you look at the row for `title` in the prop table, it accepts a `node`
