### ISSUE TITLE
Allow other HTML components in ListGroupItem than <p>

### ISSUE THREAD

**Issue by binarykitchen** [react-bootstrap/react-bootstrap#1271]
ListGroupItem currently pastes a `<p>` inside for any contents.

But I would like to try something like this:

```
<ListGroupItem
  header   = {title}
>
  {
    <ul>
      <li>{archivedCount} archived</li>
      <li>{nonArchivedCount} non-archived</li>
    </ul>
  }
</ListGroupItem>
```

Have a bulleted list of some stats inside the list item. This instead of a paragraph. Is that possible?

**Comment by apkiernan** [comment]
This is currently not possible (technically it renders, but you get that empty `<p>` tag in the markup which isn't ideal). Bootstrap doesn't mention if this is supported, but after messing around with it a bit, it doesn't appear to break anything, and I think it could be implemented.

**Comment by taion** [comment]
Related to discussions RE:idea API for panels.

**Comment by danieljuhl** [comment]
Any news on this? The problem right now, is that though it works it produces invalid HTML.

**Comment by danieljuhl** [comment]
If I look at the Bootstrap documentation, it states nowhere that it has to be a `<p>`, it is just an example of custom content, where they have a `<h4>` combined with a `<p>`.

IMO we could release the API, and only render the `<p>` in case the `children` is pure text.

**Comment by taion** [comment]
PRs welcome.

**Comment by danieljuhl** [comment]
@taion but before I start working on it, I would like to know, whether you have something against the core concept of releasing the API, in regards to `Related to discussions RE:ideal API for panels.`

**Comment by PiTrem** [comment]
Hi,
the `<p></p>` comes from using the props 'header'. [https://github.com/react-bootstrap/react-bootstrap/blob/master/src/ListGroupItem.js#L66](url)
You can avoid using it and define your header yourself, eg:
  `<ListGroupItem>
     <h4 className="list-group-item-heading" > {title} </h4>
     ....
  </ListGroupItem> `

**Comment by danieljuhl** [comment]
Have you actually made it work, @PiTrem ? The way I see the code, that would render a `<span>` as the container, which should only contain inline elements.

**Comment by taion** [comment]
We'll probably support this via https://github.com/react-bootstrap/react-bootstrap/issues/983#issuecomment-203594158.

If we can find a way to do so that's not too breaking, it might be nice to merge #1731, though.
