### ISSUE TITLE
Using a Form inside a Nav

### ISSUE THREAD

**Issue by mtscout6** [react-bootstrap/react-bootstrap#1277]
I was trying to put together a demo that highlights how easy React-Bootstrap is to use, my goal was to implement one of the examples from http://getbootstrap.com/getting-started/#examples.

My goal: http://getbootstrap.com/examples/jumbotron/

Note the form input padding here.

<img width="1000" alt="screen shot 2015-09-02 at 9 16 01 pm" src="https://cloud.githubusercontent.com/assets/736870/9649862/d7edd2e0-51b7-11e5-8770-3df867a33923.png">

When using react-bootstrap:

<img width="709" alt="screen shot 2015-09-02 at 9 19 55 pm" src="https://cloud.githubusercontent.com/assets/736870/9649893/62b18476-51b8-11e5-8dcd-51c24c592777.png">

```
const navbarInstance = (
       <Navbar brand='React-Bootstrap' inverse toggleNavKey={0}>
        <Nav right eventKey={0}>
          <form className='navbar-form' action="">
            <Input type='text' placeholder='email' />
            <Input type='text' placeholder='password' />
            <Button bsStyle='success' type='submit'>Sign in</Button>
          </form>
        </Nav>
      </Navbar>
);

React.render(navbarInstance, mountNode);
```

The problem is that the padding between the inputs is not what I'd expect. Near as I can tell in the few minutes I've looked at this is that a form child of a Nav element is getting wrapped in a `ul` which is messing up the styling.

**Comment by taion** [comment]
This is actually just how JSX handles inline elements. Despite the `Input` and `Block` elements being on separate lines, JSX doesn't insert spaces between them. You'd have to either put them on the same line with a space between them, or do e.g.

```jsx
const navbarInstance = (
       <Navbar brand='React-Bootstrap' inverse toggleNavKey={0}>
        <Nav right eventKey={0}>
          <form className='navbar-form' action="">
            <Input type='text' placeholder='email' />{' '}
            <Input type='text' placeholder='password' />{' '}
            <Button bsStyle='success' type='submit'>Sign in</Button>
          </form>
        </Nav>
      </Navbar>
);

React.render(navbarInstance, mountNode);
```

I don't know that there's anything we can do to get this behavior within R-B itself.

**Comment by mtscout6** [comment]
Ah, gotcha I remember seeing this a few months back now that you say that. Thanks for the help!

**Comment by XuluWarrior** [comment]
Is there any intention to implement a component that represent a form on a Navbar?  It seems a bit clunky to add the necessary classes to a HTML form when for the other elements this is done as part of react-bootstrap

**Comment by taion** [comment]
We'd consider a PR for one. It's pretty damn trivial though.

**Comment by XuluWarrior** [comment]
It is trivial but only if you know you need to do it.  As somebody pretty new to Bootstrap, I didn't.

**Comment by taion** [comment]
It's straight from the TWBS examples.

**Comment by XuluWarrior** [comment]
I wasn't referring specifically to this particular example (I was actually trying to replicate an example from a different site) but it was more a statement that as somebody trying to get familiar with react-bootstrap, I had to flip a number of times between the generated HTML, the example HTML and the documentation to realise that I needed to add navbar related classes to the form element despite not needing to do that anywhere else.
But as I said before, this is probably as much an indication of my ignorance as anything else.

**Comment by XuluWarrior** [comment]
I should probably also add that I'm really appreciating being able to use Bootstrap in a React way and am glad that I found react-bootstrap.
Thanks :)

**Comment by jquense** [comment]
We'd be happy to take a simple component like that, its just that most of us don't have the time to do it over other issues. If you want to take a stab at it and send a PR that'd be the best way to get it done :)

**Comment by XuluWarrior** [comment]
Once I've got a better feel for how it all hangs together, I'll do just that. :)
