### ISSUE TITLE
Uncaught TypeError: this.props.onRootClose is not a function

### ISSUE THREAD

**Issue by chibicode** [react-bootstrap/react-bootstrap#1279]
When I set `rootClose={ true }` on `Overlay` like this:

```
<Overlay ... rootClose={ true }>
  <Popover>...</Popover>
</Overlay>
```

When I click away, I get the following error:

```
Uncaught TypeError: this.props.onRootClose is not a function
```

I tried adding `onRootClose` to `Overlay` but it did not fix the issue. Where should I put `onRootClose`?

**Comment by jquense** [comment]
you need add a `onHide` handler which is passed to the root close wrapper

**Comment by chibicode** [comment]
@jquense thanks!

**Comment by AlexKVal** [comment]
@chibicode thank you for pointing to that issue.
:cherries:
