### ISSUE TITLE
ModalTrigger: Uncaught TypeError: Cannot read property 'toUpperCase' of undefined

### ISSUE THREAD

**Issue by JCzz** [react-bootstrap/react-bootstrap#1282]
This is a duplicate of a question I have on Stackoverflow:
http://stackoverflow.com/questions/32373931/modaltrigger-uncaught-typeerror-cannot-read-property-touppercase-of-undefine

Update: I found that ModalTrigger has been deprecated: 1b1af04 [changed] deprecate ModalTrigger
I will just try this without ModalTrigger.

Anyways I have the following issue - any help is appreciated:
I am having trouble with react-bootstrap ModalTrigger. The following use to work but after upgrading to <br>
"react-bootstrap": "^0.25.1", <br>
"react": "^0.13.3",

I get the following error: Uncaught TypeError: Cannot read property 'toUpperCase' of undefined
<br>

Do you know why?

    export default class Test extends React.Component {
    
        constructor(props) {    
          super(props);
          this.close = this.close.bind(this);
        }
    
      close(){
        this.setState({ showModal: false });
      }
    
        render() {
    
          var mymodal = ( 
            <Modal show={true} onHide={this.close}>
              <Modal.Header closeButton>
                <Modal.Title>Modal heading</Modal.Title>
              </Modal.Header>
              <Modal.Body>
                <h4>Text</h4>
              </Modal.Body>
              <Modal.Footer>
                <Button onClick={this.close}>Close</Button>
              </Modal.Footer>
            </Modal>
          )
    
            return (
            <Table striped bordered condensed hover>
              <thead>
                <tr>
                  <th>
                    <ModalTrigger key='modalinput' modal={mymodal}>
    
                      <Button style={buttonStyle}>
                        <span className="glyphicon glyphicon-plus" aria-hidden="true"></span>
                      </Button>
    
                    </ModalTrigger>
                  </th>
                  <th>X</th>
                  <th>Y</th>
                </tr>
              </thead>
              <tbody>
    
              
              </tbody>
            </Table>
            );
          
        } // Render
    
      }; // Component

**Comment by jquense** [comment]
Yes, because there is no `ModalTrigger` Component, it was removed in 0.24, You should jsut use the Modal Component itself, directly.

**Comment by JCzz** [comment]
Thanks, it just works :-)

**Comment by Deelux** [comment]
How would one use the Modal Component itself, directly?

**Comment by taion** [comment]
See the components page.

**Comment by Deelux** [comment]
Yes I did this already and got it to work. The only thing that I didn't get to work yet is to add it to my current project in the right way. Because I thought using "this.(something)" is the old-fashion way of doing it? I would like to add it in the new way.
