### ISSUE TITLE
SplitButton aria-label

### ISSUE THREAD

**Issue by ducky427** [react-bootstrap/react-bootstrap#1284]
(new to the project, so please forgive my ignorance).

I am using `SplitButton` component in my project and the `label` prop for it another component. So all works as expected.

Just a slight improvment, `SplitButton` on [Line 39](https://github.com/react-bootstrap/react-bootstrap/blob/master/src/SplitButton.js#L39) should check if the `aria-label` is present in props before assigning `aria-label` with `label`.

Thank you.

**Comment by taion** [comment]
That's actually `title`, not `label`, and `title` is required to be present (and it'd be awfully pointless not to have one).

**Comment by ducky427** [comment]
Ah sorry. I meant `title`. 

In my case `title` is a React component and not a string. So when `title` is assigned to `aria-label`, its not correct. `aria-label` is supposed to be a string and not a component. Hence my suggestion.

**Comment by kwnccc** [comment]
@ducky427 how do you use <code>title</code> component, attach an example snippet.

@taion how should we support component passed in title prop? There are many possible ways where text could be, the most simple of them a title prop like <code><Label>label text</Label></code>

**Comment by jquense** [comment]
@kwnccc The `title` prop already supports components. the problem is that that SplitButton assigns `title` to `aria-label` by default, but aria-label can only be a string. It really should just not assign aria-label. better to use the `id` and `aria-labelledby` I think

**Comment by ducky427** [comment]
I use it from ClojureScript. So my JSX won't be upto it. But hopefully you get the idea:
(I am using font-awesome icons)

```jsx
var title=<span>
            <i className="fa.fa-download.fa-fw"></i>
            <span>"Download"</span>
          </span>

<SplitButton bsStyle="primary" title={title} id="example">
 .....
</SplitButton>
```

**Comment by jquense** [comment]
looking at it a bit further, the `id` that is required is attached to toggle proper, not the `title` button. IT seems like the options are:

1. only assign `aria-label` when `title` is a string
2. require a second ID (I really wish we could just generate them...) and use labelledby
3. just bow out of trying to handle a11y on this one.

I am grumpily thinking that 3 is the best choice here...

**Comment by ducky427** [comment]
@jquense for my work option 3 is fine. 

My only concern for opening this issue was that the markup being generated was not right. I had `aria-label=[object Object]` in the DOM. it doesn't cause any issue. But I thought this may bite someone.

**Comment by taion** [comment]
Why can't we just have something like

```js
aria-label={this.props.label || this.props.title}
```

?

React 14 context could potentially let us have a top-level generated-ID-manager that lets us consistently have generated IDs across client and server.
