### ISSUE TITLE
Document better or make it required ? 'onHide' in 'Overlay'

### ISSUE THREAD

**Issue by AlexKVal** [react-bootstrap/react-bootstrap#1285]
https://github.com/react-bootstrap/react-bootstrap/issues/1279

**Comment by taion** [comment]
This should be required, no? I'm surprised it isn't.

**Comment by taion** [comment]
Scratch what I said earlier - this is only required if `rootClose` is specified. Maybe best to update the prop validation in react-overlays accordingly?
