### ISSUE TITLE
ListGroupItem with header and onClick does not display the header

### ISSUE THREAD

**Issue by alainesse** [react-bootstrap/react-bootstrap#1287]

**Comment by taion** [comment]
Thanks for the bug report. It looks like the code here: https://github.com/react-bootstrap/react-bootstrap/blob/v0.25.1/src/ListGroupItem.js#L71 is in fact slightly different. @apkiernan is this intentional?

**Comment by apkiernan** [comment]
Not intentional, although looking at it having a header plus text in a <button> feels awkward.

**Comment by rickychien** [comment]
+1

**Comment by taion** [comment]
Fixed by #1367.
