### ISSUE TITLE
Support unmountOnExit for tabs

### ISSUE THREAD

**Issue by pieterv** [react-bootstrap/react-bootstrap#129]
Currently we are adding all [TabbedPanes to the DOM](https://github.com/react-bootstrap/react-bootstrap/blob/master/src/TabbedArea.jsx#L83) regardless of whether they are active or not. If we were to change this to only mount the active child to the DOM (so only render the active child) it would allow the DOM tree to be smaller and child components would have their React lifecycle methods called at more appropriate times.

Is there any reason that i'm missing for doing it way it currently is?

This came about because of this google groups posting: https://groups.google.com/forum/#!msg/reactjs/fl0z5CZg-BY/tpE5s0-4r_kJ

**Comment by mtscout6** [comment]
This should be achievable today with a nav that is styled like tabs as is demonstrated on the docs, https://react-bootstrap.github.io/components.html#navs. This is what we've been doing in our apps. Do we just need to highlight better docs when working with react-router? Or do you feel that what's there is enough?

**Comment by mathieumg** [comment]
Just to make sure, which (Tab or Nav) covers which case? (Hiding vs unmounting) Other than that, I imagine the two components display the same behavior for the rest? I imagine it would be relevant to indicate these subtle differences in the documentation indeed.

**Comment by mtscout6** [comment]
So Nav does not give you the tabbed area, we are doing that on our own as a sibling node of the Nav.

Something like:

```
  <div>
    <Nav bsStyle='tab'>...</Nav>
    <RouteHandler />
  </div>
```

**Comment by dozoisch** [comment]
Maybe we can lazy mount? Like once its mounted we keep it mounted.

**Comment by taion** [comment]
I feel like it might be reasonable to keep things as-is for consistency with upstream TWBS.

I'm not sure you really want to be using `Tabs` (formerly `TabbedArea`) for anything sufficiently large where you care about this - easy enough to roll your own with `Nav` anyway.

**Comment by mtscout6** [comment]
Perhaps worth mentioning the `Nav` alternative in the docs? That's what I have been doing on my projects anyways, though it would be nice to convey that knowledge to others.

**Comment by taion** [comment]
@mtscout6 Hmm! If that pattern actually is getting used a lot, maybe we should support it in `Tabs` if it's relatively easy (might be with the new `Transition` stuff). No need to tell users to keep re-inventing the wheel.

**Comment by taion** [comment]
Moved to https://github.com/react-bootstrap/react-bootstrap/issues/1418.

**Comment by amolpshinde07** [comment]
Hi
can anyone please give me sample program of NavBar in react with content loading
i am unable to load content on navitem click,
i am using https://react-bootstrap.github.io/components.html#navbars-mobile-friendly

**Comment by taion** [comment]
All that's required here is to pass through `unmountOnExit` via `<Tabs>`, `<TabContent>`, and `<TabPane>` into `<Transition>` (and handle mount/unmount logic otherwise).

**Comment by edmofro** [comment]
+1
