### ISSUE TITLE
How to force the browser to save the user's password (using a POST to another URL)?

### ISSUE THREAD

**Issue by DavidApfel** [react-bootstrap/react-bootstrap#1297]
We have built a single page application using react-bootstrap and we would like the browser to offer to save the user credentials (username/password). We know that we need to make the form to post to another URL but cannot make it to work using react-bootstrap.

We are returning our form in this way:

```javascript
            return this.transferPropsTo(
                <form id="signUpForm" name="signUpForm" method="post" action="/api/users/ping" novalidate>
                    {this.props.inputItems.map(this.renderValidatedInputFor)}
                    {this.renderSubmitItem()}
                </form>
                );
```

The {this.props.inputItems.map(this.renderValidatedInputFor)} creates inputs based on ReactBootstrap.Input but when we press the submit button it doesn't offer to save the password because, I think, the form attribute in the input fields points to some other form=[object Object].

If we replace {this.props.inputItems.map(this.renderValidatedInputFor)} for a vanilla input field it works but prefer to stay within the react-bootstrap framework. What is the best way to make it work with your framework?

**Comment by jquense** [comment]
Hi there, it's a bit tough to try and help you here,  since it doesn't look like anything in your example pertains to react-bootstrap.

**Comment by DavidApfel** [comment]
Sorry, yes the error was on our side, nothing to do with bootstrap, I apologize for not being precise.
