### ISSUE TITLE
NavDropdown triggers change of page

### ISSUE THREAD

**Issue by kkarimi** [react-bootstrap/react-bootstrap#1302]
I am using DropdownButton with navItem prop but it always triggered change of page. The same still happens with NavDropdown. Is there anyway to have a dropdown menu where clicking the dropdown just drops the menu and doesn't change the page?

```javascript
    <NavDropdown
                            title={userName}
                            NavDropdown={true}
                            navItem={true}>
                            <MenuItem
                                href='/user/account'>
                                View/Edit Account Details
                            </MenuItem>
    </NavDropdown>
```

**Comment by jquense** [comment]
Yup the either don't add an href to the menuItem or listen to the onSelect event and call preventDefault() on the event argument

**Comment by kkarimi** [comment]
@jquense Do you mean add onSelect for NavDropDown or MenuItem? can't a MenuItem be a link but not the NavDropDown? I tried adding onSelect for NavDropDown but it doesn't seem to prevent navigation..

**Comment by jquense** [comment]
ah you mean clicking on the actual dropdown toggle button is triggering a page change? Can you screenshot the markup its generating?

**Comment by kkarimi** [comment]
Yes exactly! here it is:

![screen shot 2015-09-08 at 11 41 36](https://cloud.githubusercontent.com/assets/875218/9732823/b613402c-561e-11e5-9197-b82c6fad373b.png)
![screen shot 2015-09-08 at 11 41 20](https://cloud.githubusercontent.com/assets/875218/9732824/b6164db2-561e-11e5-894d-98d4dff67831.png)

**Comment by jquense** [comment]
sorry I meant the actual html generated

**Comment by kkarimi** [comment]
Ah sure, here it is:
```html
<ul>
    <li class="dropdown" data-reactid=".0.0.0.1:$=10:$0.0.$=15:$5">
        <a aria-expanded="false" aria-haspopup="true" class="dropdown-toggle"
        data-reactid=".0.0.0.1:$=10:$0.0.$=15:$5.$=10:0" href="" id=
        "acc-nav-dropdown" role="button" type="button"><span data-reactid=
        ".0.0.0.1:$=10:$0.0.$=15:$5.$=10:0.0">Super man</span>
        <span data-reactid=
        ".0.0.0.1:$=10:$0.0.$=15:$5.$=10:0.1"><span data-reactid=
        ".0.0.0.1:$=10:$0.0.$=15:$5.$=10:0.1.0"></span><span class="caret"
        data-reactid=".0.0.0.1:$=10:$0.0.$=15:$5.$=10:0.1.1"></span></span></a>
    </li>
</ul>

<ul aria-labelledby="acc-nav-dropdown" class="dropdown-menu" data-reactid=
".0.0.0.1:$=10:$0.0.$=15:$5.$=11:0" role="menu">
    <li class="" data-reactid=".0.0.0.1:$=10:$0.0.$=15:$5.$=11:0.$=10:0" role=
    "presentation">
        <a data-reactid=".0.0.0.1:$=10:$0.0.$=15:$5.$=11:0.$=10:0.0" href=
        "/user/account" role="menuitem" tabindex="-1">View/Edit Account
        Details</a>
    </li>
</ul>
```

**Comment by taion** [comment]
This example doesn't reproduce on our components page. It's possible a parent of the `NavDropdown` is injecting an `onClick` handler into it.

Please provide a repro case that we can look at.

**Comment by kkarimi** [comment]
I have provided example with code and hosted pages here at #1331. Many thanks guys.

**Comment by LKay** [comment]
I don't think this issue has been resolved. The same thing happens in my case. Looks like for no reason the `href` attribute is added to dropdown toggle and when clicking on it dropdown menu opens but the page reloads as the attribute is `href=""`. Tried to call `e.stopPropagation()` and `e.preventDefault()` on `onClick` handler but events gets propagated anyway and page reloads.

**Comment by taion** [comment]
You can see in the example above that something else was capturing onClick. There's nothing weird here with `NavDropdown`.

**Comment by LKay** [comment]
I tried many things to find a problem, but couldn't do it without dirty hack removing href attribute from the actual rendered element. My code is as basic as this:
```jsx
<NavDropdown id="top-menu-user" title={ "Username" }>
    <MenuItem href="someurl">{ "Settings" }</MenuItem>
    <MenuItem divider />
    <MenuItem href="someurl">{ "Logout" }</MenuItem>
</NavDropdown>
```
I debugged my code and nothing is injecting `onClick` handler. The component `NavDropdown` (the `<a>` tag contains empty `href` property) when clicked always refreshes page.

**Comment by dceddia** [comment]
I have this same problem. In my case, I'm using React inside Angular (with ngReact) - I suspect something weird is going on where Angular is adding the `href` to the `a` tags or something.

In any case, @LKay's suggestion worked for me. I tweaked it a bit by wrapping the `MenuItem`:

```javascript
var MenuItemHack = React.createClass({
    componentDidMount: function () {
        this.removeHref();
    },

    componentDidUpdate: function () {
        this.removeHref();
    },

    removeHref: function () {
        const dropdownLink = ReactDOM.findDOMNode(this).querySelector('a');
        dropdownLink.removeAttribute('href');
    },

    render: function () {
        // All ES5 except this bit because I got lazy
        return <MenuItem {...this.props}/>
    }
});

// Then, inside Dropdowns, use <MenuItemHack> instead of <MenuItem> 
```

**Comment by preethijayanthi** [comment]
can anyone plsss give the code for using href in menuitem ... i have tried many codes but href is not working

**Comment by jedkass** [comment]
I was able to address this behavior by using the `NativeListener` component from `react-native-listener` to prevent the default native event from being fired (as opposed to the synthetic event react fires). Here's a good article explaining the difference: [https://medium.com/@ericclemmons/react-event-preventdefault-78c28c950e46](url)

```
<IndexLinkContainer to="myRoute">
    <NativeListener stopClick>
        <NavDropdown.Item>My Route</NavDropdown.Item>
    </NativeListener>
</IndexLinkContainer>
```

**Comment by av3000** [comment]
As for today I managed to solve it by using Link together. Although I don't know how much of a leggit way of doing things in this way is.

`import  { Link } from 'react-router-dom';`

`<Navbar  expand="lg">
            <Navbar.Brand as={Link} to="/">JPLearning</Navbar.Brand>
            <Navbar.Toggle aria-controls="basic-navbar-nav" />
            <Navbar.Collapse id="basic-navbar-nav">
                <Nav className="nav navbar-nav navbar-right">
                <Nav.Link as={Link} to="/community">Community</Nav.Link>
                <Nav.Link as={Link} to="/dashboard">Dashboard</Nav.Link>
                <NavDropdown title="Readings" id="basic-nav-dropdown">
                    <Dropdown.Item as={Link} to="/articles">Articles</Dropdown.Item>
                    <Dropdown.Item as={Link} to="/lists">Lists</Dropdown.Item>
                </NavDropdown>
                <NavDropdown title="Material" id="basic-nav-dropdown">
                    <Dropdown.Item as={Link} to="/radicals">Radicals</Dropdown.Item>
                    <Dropdown.Item as={Link} to="/kanjis">Kanjis</Dropdown.Item>
                    <Dropdown.Item as={Link} to="/words">Words</Dropdown.Item>
                    <Dropdown.Item as={Link} to="/sentences">Sentences</Dropdown.Item>
                </NavDropdown>
                <NavDropdown title="New" id="basic-nav-dropdown">
                    <Dropdown.Item as={Link} to="/newarticle">Article</Dropdown.Item>
                    <Dropdown.Item as={Link} to="/newlist">List</Dropdown.Item>
                </NavDropdown>
                </Nav>
            </Navbar.Collapse>
            </Navbar>`

**Comment by jerome-diver** [comment]
I may not really understand the question, but when i click my top level Dropdown link, it doesn't fired a page... it just unroll the menu items list.

And when i do click a link, i had a hard way to fix the problem in my SSR application to not use href and not reload the server side full main page. For this, i did not use NavDropdown.Item, instead i do use NavLink inside NavDropdown. I also add a code in CSS file to get a menu links to not be online, so display: block for them.
but code should be clearer than sentences....

```javascript
import React, { Component } from 'react'
import { Navbar, Nav, NavDropdown } from 'react-bootstrap'
import { NavLink } from "react-router-dom"
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faUsers, faUserPlus, faUserCircle, faUserTie, 
        faUserEdit, faAddressCard, faFolder, faHome, 
        faSignInAlt} from '@fortawesome/free-solid-svg-icons'

class Navigation extends Component {
  render () {
    return (
      <>
        <Navbar expand="lg" bg="dark" fg="light" fixed="top">
          <Navbar.Brand href="">SourceCodeMaker</Navbar.Brand>
          <Navbar.Toggle aria-controls="basic-navbar-nav" />
          <Navbar.Collapse id="basic-navbar-nav">
            <Nav className="mr-auto">
              <Nav.Link as={NavLink} to='/' exact activeClassName="menuselected">
                <FontAwesomeIcon icon={faHome}/> Home</Nav.Link>
              <Nav.Link as={NavLink} to='/subjects' activeClassName="menuselected">
                <FontAwesomeIcon icon={faFolder}/> Subjects</Nav.Link>
              <NavDropdown title={<span><FontAwesomeIcon icon={faUserCircle}/> Users</span>} id="basic-nav-dropdown">
                  <NavLink as={NavLink} to='/signin' activeClassName='menuselected'>
                    <FontAwesomeIcon icon={faSignInAlt}/> Sign in</NavLink>
                  <NavLink as={NavLink} to='/signup' activeClassName='menuselected'>
                    <FontAwesomeIcon icon={faUserPlus}/> Sign up</NavLink>
                  <NavLink as={NavLink} to='/users' activeClassName='menuselected'>
                    <FontAwesomeIcon icon={faUsers}/> Users list</NavLink>
                  <NavLink as={NavLink} to='/profile' activeClassName='menuselected'>
                    <FontAwesomeIcon icon={faUserEdit}/> Profile</NavLink>
                  <NavLink as={NavLink} to='/admin' activeClassName='menuselected'>
                  <FontAwesomeIcon icon={faUserTie}/> Admin</NavLink>
              </NavDropdown>
            </Nav>
          </Navbar.Collapse>
        </Navbar>
      </>
    )
  }
}

export default Navigation

```
my SASS part of related file:
```css
.dropdown-menu
  a
    display: block
```
