### ISSUE TITLE
Unable to have multiple dropdown menus on a NavBar

### ISSUE THREAD

**Issue by devknoll** [react-bootstrap/react-bootstrap#1303]
They all trigger #1302 when clicked, but the drop down menu only opens for the first one.

**Comment by devknoll** [comment]
User error :+1:

**Comment by taion** [comment]
:wave:

**Comment by kkarimi** [comment]
@devknoll can you explain what the user error is?

**Comment by devknoll** [comment]
@kkarimi In my case I wasn't using the `@react-pre` release on npm as I should have been.

**Comment by taion** [comment]
Hah! @devknoll: You know I'm using React 14 for my Relay stuff, though. I wouldn't force people to blow through peer dependency errors just to use this project. Or, at least, I wouldn't be okay with it myself.

**Comment by devknoll** [comment]
To be fair, the stable version was working fine until I was trying to do something funny ;-)

**Comment by taion** [comment]
Yeah, but what about all the warnings from not using `ReactDOM`??
