### ISSUE TITLE
bsSize for ProgressBar

### ISSUE THREAD

**Issue by TimDaub** [react-bootstrap/react-bootstrap#1306]
On: http://react-bootstrap.github.io/components.html#progress-props

there is a prop called `bsSize` specified, but even when I tried to used the latest version of react-bootstrap (0.25.1), its not in the component and does neither work.

**Comment by jquense** [comment]
There is an issue with documentation where some of these properties are shown for components that do not support them see #1257, thisis taht situation. bootstrap progress bars do not support sizes
