### ISSUE TITLE
Popover content not rendered as HTML when stored in variable

### ISSUE THREAD

**Issue by wphampton** [react-bootstrap/react-bootstrap#1308]
Any ideas why the HTML content won't render properly in my Popover component if I first store the value in a variable?

This does **not** work:
```javascript
var popContent = '<strong>Holy guacamole!</strong> Check this info.';
var popover = <Popover title="Popover right">{popContent}</Popover>;

return ( 
    <OverlayTrigger trigger='click' rootClose placement='right' overlay={popover}>
      <Button bsStyle='xsmall'>Holy guacamole!</Button>
    </OverlayTrigger>
);
```
Because it generates this:
![2015-09-09 16_26_41-specimen tracker](https://cloud.githubusercontent.com/assets/1633835/9773564/0a01963c-5711-11e5-9c5b-d2e125cbfd0b.png)

While this **does** work:
```javascript
var popover = <Popover title="Popover right"><strong>Holy guacamole!</strong> Check this info.</Popover>;

return ( 
    <OverlayTrigger trigger='click' rootClose placement='right' overlay={popover}>
      <Button bsStyle='xsmall'>Holy guacamole!</Button>
    </OverlayTrigger>
);
```
![2015-09-09 16_24_09-specimen tracker](https://cloud.githubusercontent.com/assets/1633835/9773601/3e689150-5711-11e5-94de-96540a89681c.png)

Thanks -- I'm stumped!

**Comment by taion** [comment]
That's not the way JSX variables work. You'd want e.g.

```js
var popContent = <span><strong>Holy guacamole!</strong> Check this info.</span>
```

**Comment by aterreno** [comment]
Not sure why @taion reply got a downvote, that's exactly why the popup doesn't get the html styling, you need a jsx variable
