### ISSUE TITLE
Update for React v0.14.0-rc1

### ISSUE THREAD

**Issue by Guro** [react-bootstrap/react-bootstrap#1309]
Hi there, im using react-bootstrap@react-pre with react 0.14.0-rc1
and getting this error: Warning: Button(...): React component classes must extend React.Component.
while using Button component from react-bootstrap
any suggestions?

**Comment by jquense** [comment]
nope this is b/c of a breaking change introduced between beta3 and rc

**Comment by taion** [comment]
`Button` extends `React.Component` just fine... or rather it doesn't need to because it's not an ES6 class. I have no idea where your error came from.

https://github.com/react-bootstrap/react-bootstrap/blob/v0.25.100-react-pre.0/src/Button.js#L7

**Comment by taion** [comment]
I'm going to use this issue to track updating for RC1 anyway.

**Comment by Guro** [comment]
I have switched to beta3 and problem resolved

On Saturday, September 12, 2015, Jimmy Jia <notifications@github.com> wrote:

> I'm going to use this issue to track updating for RC1 anyway.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/react-bootstrap/react-bootstrap/issues/1309#issuecomment-139809289>
> .
>


-- 
Sent from Gmail Mobile

**Comment by taion** [comment]
Released.

**Comment by Kerosene2000** [comment]
Hello,
I still get this error, and don't know how you update ReactBootstrap to beta3(or greater) ?
I want to use meteor + react + bootstrap. thx

**Comment by jquense** [comment]
@Kerosene2000 this is a really old issue, the Normal releases of React-bootstrap have supported React 0.14 for like 3 breaking versions now. Just use the latest version

**Comment by Kerosene2000** [comment]
Ok thank you !
Did React-bootstrap can be used with meteor by the way ?
Like [vazco/universe-react-bootstrap](https://github.com/vazco/universe-react-bootstrap) ?

**Comment by Kerosene2000** [comment]
I think the problem can come from here, universe-react-bootstrap use explicitly an [universe-react-bootstrap old 0.24.2  version](https://github.com/vazco/universe-react-bootstrap/blob/master/bower_components/react-bootstrap/bower.json) of your lib. [Your versions](https://github.com/react-bootstrap/react-bootstrap/releases)

And I use this package to simplify the interface between react and meteor, then I got these error messages...
What do you think about that ?

**Comment by jquense** [comment]
unfortunately I don't know anything about integration with meteor, I assume it should work, but I have no idea what is involved in that. You'll have to talk to someone who has worked with both before, sorry.

**Comment by Kerosene2000** [comment]
Ok no problem, thank you !
Have a good day !
