### ISSUE TITLE
DropDownButton with Input inside MenuItem will not stay open

### ISSUE THREAD

**Issue by rkhayat** [react-bootstrap/react-bootstrap#1311]
Is this a bug? Putting an input inside a menuItem inside a dropdownbutton results in the menu closing before the user has a chance to type...I have been stuck on this all day, I would like to know if this is a bug or just 'id 10 T'

Here is a SO question - http://stackoverflow.com/questions/32510976/react-bootstrap-dropdown-with-input-wont-stay-open

**Comment by rkhayat** [comment]
Update - I fixed using 
React.findDOMNode(this.refs.callIdInput).focus();
 e.stopPropagation();
e.nativeEvent.stopImmediatePropagation();

there is a problem though, MenuItem includes an anchor tag, causing a page refresh.

Is there anyway to stop that?

**Comment by taion** [comment]
I don't believe Bootstrap supports input elements inside of dropdown menus. It doesn't seem like very good UX. If you need to have this, consider using a custom menu item component instead of the stock `MenuItem`.
