### ISSUE TITLE
Any way to close the NavDropdown when using a custom MenuItem?

### ISSUE THREAD

**Issue by agile116** [react-bootstrap/react-bootstrap#1312]
Hi, I'm using a custom MenuItem under NavDropdown like below. But I couldn't get it closed when clicking the CustomMenuItem with NavDropdown. Previously with DropDownButton, I can use this.refs.dropdown.setDropdownState(false). Any other work around here? Thanks.
 <NavDropdown ref='dropdown'>
    <CustomMenuItem />
 </NavDropdown>

**Comment by taion** [comment]
You need to invoke the `this.props.onSelect` that's passed down from the `Dropdown` parent.

**Comment by agile116** [comment]
Can you elaborate how to invoke it? What's the implementation?

杨小林

**Comment by taion** [comment]
https://github.com/react-bootstrap/react-bootstrap/blob/v0.25.2/src/MenuItem.js#L23
