### ISSUE TITLE
How to close the drop down when use custom menu item in NavDropdown?

### ISSUE THREAD

**Issue by agile116** [react-bootstrap/react-bootstrap#1314]
Hi, I'm using a custom MenuItem under NavDropdown like below. But I couldn't get it closed when clicking the CustomMenuItem with NavDropdown. Previously with DropDownButton, I can use this.refs.dropdown.setDropdownState(false). Any other work around here? Thanks.
<NavDropdown>
<CustomMenuItem/>
@tamion replied that I can invoke this.props.onSelect to close it, but could any one tell me how? Code snippets could be helpful, thanks.

**Comment by jquense** [comment]
inside of your CustomMenuItem call the onSelect (`onSelect()`) prop that the Menu injects when you want to it to close (such as after a click)

**Comment by agile116** [comment]
Thanks for your reply. Do you mean add a onClick() function in my Link which calls this.props.onSelect() in the click handler?

杨小林

**Comment by jquense** [comment]
yes

**Comment by agile116** [comment]
Thank you very much. It's clear to me now. :)

杨小林

**Comment by kanji-karanja** [comment]
> Thanks for your reply. Do you mean add a onClick() function in my Link which calls this.props.onSelect() in the click handler?
> 
> 杨小林
> 
> > 在 2015年9月11日，18:11，Jason Quense [notifications@github.com](mailto:notifications@github.com) 写道：
> > inside of your CustomMenuItem call the onSelect (onSelect()) prop that the Menu injects when you want to it to close (such as after a click)
> > —
> > Reply to this email directly or view it on GitHub.

Could you explain this using an example?
