### ISSUE TITLE
Dropdown default export

### ISSUE THREAD

**Issue by atomanyih** [react-bootstrap/react-bootstrap#1326]
We ran into a small issue while trying to make Pivotal UI more specific when requiring react-bootstrap modules.

For most of the modules we use, this works:
```js
var Panel = require('react-bootstrap/lib/Panel');
```

But for Dropdown we have to do:
```js
var Dropdown = require('react-bootstrap/lib/Dropdown').default;
```

When we tried to do it the first way, we got issues invoking `<Dropdown>`.
React was crapping out because the value of the `Dropdown` variable was a module object instead of the class.

Digging in a little, we saw that the transpiled code for `Panel` exported like so:

```js
exports['default'] = Panel;
module.exports = exports['default'];
```

While `Dropdown` was only:
```js
exports['default'] = Dropdown;
```

Not sure if this is something about module exports that I don't understand, but it was kind of confusing that two modules with default exports had to be required in different ways.

 — @atomanyih @clairethompson

**Comment by taion** [comment]
Babel special-cases it when there's only a single default export. We should get rid of the named exports if we don't want to break people not using an ES6 module polyfill.

**Comment by taion** [comment]
Also, I'm disappointed in you guys for not using ES6 modules everywhere ;)

**Comment by atomanyih** [comment]
We're in transition! 😨
