### ISSUE TITLE
Modal not working in react-bootstrap@pre

### ISSUE THREAD

**Issue by tonyalaribe** [react-bootstrap/react-bootstrap#1327]
Since my update to react 0.14, I've been getting the error:

Uncaught Error: Invariant Violation: Modal.render(): A valid ReactComponent must be returned. You may have returned undefined, an array or some other invalid object.

**Comment by taion** [comment]
The modal examples on the components page on `react-pre` with the React 0.14.0-rc1 all work for me. Please provide more details.
