### ISSUE TITLE
Tooltip: Does not render on firefox

### ISSUE THREAD

**Issue by varunshah1106** [react-bootstrap/react-bootstrap#1330]
Exhibits weird behavior when rendering on firefox. The same stuff on Chrome works just fine. May be because of this?
https://github.com/wwayne/react-tooltip/issues/2

**Comment by taion** [comment]
Can you clarify "weird behavior"? I have absolutely no idea what you mean.

**Comment by varunshah1106** [comment]
My bad, I forgot to add screenshots. 
![screen shot 2015-09-16 at 5 00 35 pm](https://cloud.githubusercontent.com/assets/5757012/9946143/05e532c4-5d57-11e5-9818-fbc2c8392308.png)
![screen shot 2015-09-16 at 5 00 18 pm](https://cloud.githubusercontent.com/assets/5757012/9946146/0d617bca-5d57-11e5-869e-8c7d6f91b5e3.png)

**Comment by varunshah1106** [comment]
Any updates?

**Comment by mitchelldemler** [comment]
I have the same thing, even on v4 docs page. I'm using latest Firefox Developer edition.

I only get the arrow to show up:

![capture](https://cloud.githubusercontent.com/assets/995053/10444339/dc582a36-71c1-11e5-9a2c-fee69d804a5a.JPG)

**Comment by bryanliu-gpsw** [comment]
Any updates on this?

**Comment by lichtamberg** [comment]
Is this still open?

**Comment by taion** [comment]
Things look fine for me on Firefox. If you're still seeing issues, please provide a runnable repro.
