### ISSUE TITLE
Weird NavDropdown issue - navigates on self hosted page

### ISSUE THREAD

**Issue by kkarimi** [react-bootstrap/react-bootstrap#1331]
Following my question at #1302 I have a simple page build in react with react-bootstrap and react-mini-router.
I am using the same code in the react-bootstrap example for navigation for dropdown but the page navigates:

```javascript
render: function() {
        var userName = 'Superman';
        return (
            <Navbar brand="React-Bootstrap">
                <Nav>
                    <NavItem eventKey={1} href="/">Home</NavItem>
                    <NavItem eventKey={2} href="/About">About</NavItem>
                    <NavDropdown eventKey={3} title={userName} id="basic-nav-dropdown" onClick={this.userNameClick}>
                        <MenuItem eventKey="1">Action</MenuItem>
                        <MenuItem eventKey="2">Another action</MenuItem>
                        <MenuItem eventKey="3">Something else here</MenuItem>
                        <MenuItem divider />
                        <MenuItem eventKey="4">Separated link</MenuItem>
                    </NavDropdown>
                </Nav>
            </Navbar>
            )
    }

});
```

When I have the same build hosted here at github, the code works as expected, dropdown works without navigating the page:
https://kkarimi.github.io/react-bootstrap-test/#!/About
however when I have this hosted on my server, served by nginx, clicking the dropdown triggers the page to navigate to home:
http://test.karimi.info/#!/About

The code for this example project is [here](https://github.com/kkarimi/react-bootstrap-test/blob/master/src/js/components/Header.jsx).

Can any one help to understand what is causing this?

Many Thanks

**Comment by taion** [comment]
This is some bizarre interaction with react-mini-router attaching a click handler to your entire application. Drop a breakpoint in that `RouterMixin`'s click handler. This is unrelated to React-Bootstrap.

**Comment by kkarimi** [comment]
Thanks guys. I can confirm that this was the conflict, and capturing the event at the handleClick fixed it.
