### ISSUE TITLE
how to set a popover to the label of an input

### ISSUE THREAD

**Issue by barbalex** [react-bootstrap/react-bootstrap#1336]
My labels are underlined like a link. If the user clicks on them a popover opens. Here an example:

![2015-09-19_23h39_07](https://cloud.githubusercontent.com/assets/669783/9978305/deff408c-5f27-11e5-86b3-8021b4a0ae1a.png)

I could not achieve this using react-bootstrap-Inputs. My solution was using a vanilla input and label and combine it with a react-bootstrap popover:

    popover () {
      return (
        <Popover id='InputLinkPopover' title='Wozu ein Link?'>
          <p>Kann die Originalpublikation verlinkt werden?</p>
          <p>Oder eine erläuternde Webseite?</p>
        </Popover>
      )
    },

    render () {
      const { link, validLink } = this.props

      return (
        <div className={validLink ? 'form-group' : 'form-group has-error'}>
          <OverlayTrigger trigger={['click', 'focus']} rootClose placement='right' overlay={this.popover()}>
            <label className='control-label withPopover'>Link</label>
          </OverlayTrigger>
          <input type='textarea' className='form-control controls' value={link} onBlur={this.onBlur} onChange={this.onChange} rows={1} />
          {validLink ? null : <div className='validateDiv feld'>Bitte prüfen Sie den Link. Es muss einge gültige URL sein</div>}
        </div>
      )
    }

But now I am building fields using buttonBefore like this:

![2015-09-19_23h43_40](https://cloud.githubusercontent.com/assets/669783/9978321/4e1b468c-5f28-11e5-9268-73a962c79b56.png)

This is one of many fields, the user can use to filter data: on the left he can choose a comparison operator:
![2015-09-19_23h45_17](https://cloud.githubusercontent.com/assets/669783/9978330/8697230a-5f28-11e5-8278-78f83327e0b2.png)
Then enter the text to filter for on the right.

Beautiful.

Here the code:

    return (
      <Input
        key={fIndex}
        type={fNameKeyObject.fType}
        label={fNameKey}
        bsSize='small'
        className={'controls'}
        onBlur={this.onBlur.bind(this, cNameKey, fNameKey)}
        buttonBefore={selectComparisonOperator} />
    )

But now I need to give the label a popover. It shall give the user information about the field.

I can't use regular input elements now. How can this be achieved with the react-bootstrap input?

**Comment by floriancargoet** [comment]
You can pass a component as a label.

```
var label = <OverlayTrigger trigger={['click', 'focus']} rootClose placement='right' overlay={this.popover()}>
        <span>{fNameKey}</span>
</OverlayTrigger>

return (
  <Input
    key={fIndex}
    type={fNameKeyObject.fType}
    label={label}
    bsSize='small'
    className={'controls'}
    onBlur={this.onBlur.bind(this, cNameKey, fNameKey)}
    buttonBefore={selectComparisonOperator} />
)
```

**Comment by taion** [comment]
Thanks for that.

**Comment by barbalex** [comment]
is this still working in v0.29.4? Not for me...

**Comment by jquense** [comment]
this is irrelevant in 0.29 because there is no more `Input`. And you can put whatever you want inside a `ControlLabel` include an overlay trigger

**Comment by barbalex** [comment]
why is this not working then:

    'use strict'

    import React from 'react'
    import { OverlayTrigger, Popover, FormGroup, ControlLabel, FormControl } from 'react-bootstrap'

    const popover = (
      <Popover
        id="InputBeschreibungPopover"
        title="So beschreiben Sie die Sammlung:"
      >
        <p>
          Die Beschreibung sollte im ersten Teil etwa einem klassischen Literaturzitat entsprechen.<br />
          Beispiel: "Gigon A. et al. (1998): Blaue Listen der erfolgreich erhaltenen oder geförderten Tier-
          und Pflanzenarten der Roten Listen. Methodik und Anwendung in der nördlichen Schweiz.
          Veröff. Geobot. Inst. ETH, Stiftung Rübel, Zürich 129: 1-137 + 180 pp. Appendicesn".
        </p>
        <p>
          In einem zweiten Teil sollte beschrieben werden, welche Informationen
          die Eigenschaftensammlung enthält.<br />
          Beispiel: "Eigenschaften von 207 Tierarten und 885 Pflanzenarten".
        </p>
        <p>
          Es kann sehr nützlich sein, zu wissen, wozu die Informationen zusammengestellt wurden.
        </p>
      </Popover>
    )

    const InputBeschreibung = ({
      beschreibung,
      validBeschreibung,
      onChangeBeschreibung
    }) => (
      <div
        className={validBeschreibung ? 'form-group' : 'form-group has-error'}
      >
        <FormGroup controlId="beschreibungTextarea">
          <OverlayTrigger
            trigger={['click', 'focus']}
            rootClose
            placement="right"
            overlay={popover}
          >
            <div
              className="control-label withPopover"
            >
              <ControlLabel>
                Beschreibung
              </ControlLabel>
            </div>
          </OverlayTrigger>
          <FormControl
            componentClass="textarea"
            className="form-control controls"
            value={beschreibung}
            onChange={(event) =>
              onChangeBeschreibung(event.target.value)
            }
            rows={1}
          />
          {
            !validBeschreibung &&
            <div className="validateDiv feld">
              Eine Beschreibung ist erforderlich
            </div>
          }
        </FormGroup>
      </div>
    )

    InputBeschreibung.displayName = 'InputBeschreibung'

    InputBeschreibung.propTypes = {
      beschreibung: React.PropTypes.string,
      validBeschreibung: React.PropTypes.bool,
      onChangeBeschreibung: React.PropTypes.func
    }

    export default InputBeschreibung

**Comment by barbalex** [comment]
sorry, that was another version I tried. I meant this:

    'use strict'

    import React from 'react'
    import { OverlayTrigger, Popover, FormGroup, ControlLabel, FormControl } from 'react-bootstrap'

    const popover = (
      <Popover
        id="InputBeschreibungPopover"
        title="So beschreiben Sie die Sammlung:"
      >
        <p>
          Die Beschreibung sollte im ersten Teil etwa einem klassischen Literaturzitat entsprechen.<br />
          Beispiel: "Gigon A. et al. (1998): Blaue Listen der erfolgreich erhaltenen oder geförderten Tier-
          und Pflanzenarten der Roten Listen. Methodik und Anwendung in der nördlichen Schweiz.
          Veröff. Geobot. Inst. ETH, Stiftung Rübel, Zürich 129: 1-137 + 180 pp. Appendicesn".
        </p>
        <p>
          In einem zweiten Teil sollte beschrieben werden, welche Informationen
          die Eigenschaftensammlung enthält.<br />
          Beispiel: "Eigenschaften von 207 Tierarten und 885 Pflanzenarten".
        </p>
        <p>
          Es kann sehr nützlich sein, zu wissen, wozu die Informationen zusammengestellt wurden.
        </p>
      </Popover>
    )

    const InputBeschreibung = ({
      beschreibung,
      validBeschreibung, onChangeBeschreibung
    }) => (
      <div
        className={validBeschreibung ? 'form-group' : 'form-group has-error'}
      >
        <FormGroup controlId="beschreibungTextarea">
          <ControlLabel>
            <OverlayTrigger
              trigger={['click', 'focus']}
              rootClose
              placement="right"
              overlay={popover}
            >
              <div
                className="control-label withPopover"
              >
                Beschreibung
              </div>
            </OverlayTrigger>
          </ControlLabel>
          <FormControl
            componentClass="textarea"
            className="form-control controls"
            value={beschreibung}
            onChange={(event) =>
              onChangeBeschreibung(event.target.value)
            }
            rows={1}
          />
          {
            !validBeschreibung &&
            <div className="validateDiv feld">
              Eine Beschreibung ist erforderlich
            </div>
          }
        </FormGroup>
      </div>
    )

    InputBeschreibung.displayName = 'InputBeschreibung'

    InputBeschreibung.propTypes = {
      beschreibung: React.PropTypes.string,
      validBeschreibung: React.PropTypes.bool,
      onChangeBeschreibung: React.PropTypes.func
    }

    export default InputBeschreibung

**Comment by barbalex** [comment]
I realize that for many field types I could also use an input addon as explained here: https://react-bootstrap.github.io/components.html#forms-input-addons.

I have done this successfully in another form.

But that does not work for checkboxes and textareas.

**Comment by barbalex** [comment]
this is the version that works with vanilla bootstrap:

    'use strict'

    import React from 'react'
    import { OverlayTrigger, Popover } from 'react-bootstrap'

    const popover = (
      <Popover
        id="InputBeschreibungPopover"
        title="So beschreiben Sie die Sammlung:"
      >
        <p>
          Die Beschreibung sollte im ersten Teil etwa einem klassischen Literaturzitat entsprechen.<br />
          Beispiel: "Gigon A. et al. (1998): Blaue Listen der erfolgreich erhaltenen oder geförderten Tier-
          und Pflanzenarten der Roten Listen. Methodik und Anwendung in der nördlichen Schweiz.
          Veröff. Geobot. Inst. ETH, Stiftung Rübel, Zürich 129: 1-137 + 180 pp. Appendicesn".
        </p>
        <p>
          In einem zweiten Teil sollte beschrieben werden, welche Informationen
          die Eigenschaftensammlung enthält.<br />
          Beispiel: "Eigenschaften von 207 Tierarten und 885 Pflanzenarten".
        </p>
        <p>
          Es kann sehr nützlich sein, zu wissen, wozu die Informationen zusammengestellt wurden.
        </p>
      </Popover>
    )

    const InputBeschreibung = ({
      beschreibung,
      validBeschreibung,
      onChangeBeschreibung
    }) => (
      <div
        className={validBeschreibung ? 'form-group' : 'form-group has-error'}
      >
        <OverlayTrigger
          trigger={['click', 'focus']}
          rootClose
          placement="right"
          overlay={popover}
        >
          <label
            className="control-label withPopover"
          >
            Beschreibung
          </label>
        </OverlayTrigger>
        <input
          type="textarea"
          className="form-control controls"
          value={beschreibung}
          onChange={(event) =>
            onChangeBeschreibung(event.target.value)
          }
          rows={1}
        />
        {
          !validBeschreibung &&
          <div className="validateDiv feld">
            Eine Beschreibung ist erforderlich
          </div>
        }
      </div>
    )

    InputBeschreibung.displayName = 'InputBeschreibung'

    InputBeschreibung.propTypes = {
      beschreibung: React.PropTypes.string,
      validBeschreibung: React.PropTypes.bool,
      onChangeBeschreibung: React.PropTypes.func
    }

    export default InputBeschreibung

**Comment by barbalex** [comment]
I found out why the popover does not work on the label of a textarea: Because of the `controlId`. It seems to steal the focus and prevent the popover from opening. Without controlId it works.
