### ISSUE TITLE
React-Bootstrap: Unable to load with React 0.14.0 rc1

### ISSUE THREAD

**Issue by jedd-ahyoung** [react-bootstrap/react-bootstrap#1344]
I'm having trouble loading react-bootstrap with the new release candidate. It looks like react-bootstrap contains a reference to `warning.js` in the React library - and it looks like this is missing in the new release candidate. (That, or, the react-bootstrap library assumes that React will be running in development mode with warnings, or something like that. I believe that the warnings are removed with the non-development React builds.)

For what it's worth, I'm loading React and react-bootstrap from the npm repository (using the JSPM package manager). I'm using react-bootstrap version 0.25.2.

Has anyone else run into this issue?

**Comment by taion** [comment]
As documented on both the main landing page: http://react-bootstrap.github.io/ and the project's README: https://github.com/react-bootstrap/react-bootstrap#react-014, we are maintaining specific pre-releases for React v0.14.

It's not an accident that the main release is _not_ marked as compatible with the React 0.14 RCs, and you should not make a habit of ignoring the peer dependency errors from NPM - they're there for a good reason.

**Comment by jedd-ahyoung** [comment]
Whoops. I suppose I missed the errors when I did an install - I don't know
if JSPM formats the errors differently, but I didn't remember seeing
anything amiss in terms of dependencies. I'll try pulling the pre-release
version to see if it fits my pronecr needs. Thanks.
