### ISSUE TITLE
Wrong Popover position with OverlayTrigger when generated by separate component

### ISSUE THREAD

**Issue by wphampton** [react-bootstrap/react-bootstrap#1345]
I apologize for my limited understanding of React and JSX but I haven't been able to understand why I'm getting different results in the positioning of the Popover from the two following examples.

This positions the popover **correctly** and immediately to the right of the item I'm clicking on:
```javascript
var MyComponent = React.createClass({
    render: function () {
        var popover = <Popover title="Popover right">Holy guacamole! Check this info.</Popover>;
        return ( 
            <OverlayTrigger trigger='click' rootClose placement='right' overlay={popover}>
                <Button bsStyle='xsmall'>Holy guacamole!</Button>
            </OverlayTrigger>
        );
    }
});
```

However, this positions the popover in the top-left of the screen each time:
```javascript
var MyComponent = React.createClass({
    render: function () {
        var popover = <MyPopover key={someUniqueKey} />;        
        return (
            <OverlayTrigger trigger='click' rootClose placement='right' overlay={popover}>
                <Button bsStyle='xsmall'>Holy guacamole!</Button>
            </OverlayTrigger>
        );            
    }
});

var MyPopover = React.createClass({
    render: function () {
        return (
            <Popover id={this.props.key} title="Popover right">
                Holy guacamole! Check this info.
            </Popover>
        );
    }
});
```

Usign Chrome Developer Tools I've noticed in the second, non-working example that the Popover div doesn't seem to have some of the elements that the working version does.  Like *target="function bound () { [native code] }"* and *class="fade in"* and *style="left: 407.328px; top: 330px"*  I'm just not sure what to do with that information :)  Thank you!

**Comment by taion** [comment]
Custom popovers need to spread in all the props they get, e.g. `<Popover {...this.props}>`.

**Comment by wphampton** [comment]
Thank you and my apologies -- will post future questions on StackOverflow.

**Comment by skitterm** [comment]
Fixed my issue too! Can this be documented?

**Comment by taion** [comment]
We'd happily accept a PR here to improve the docs.
