### ISSUE TITLE
Document what happens onSelect of a Dropdown

### ISSUE THREAD

**Issue by muraveill** [react-bootstrap/react-bootstrap#1346]
Please add documentation about what is the default behavior of a dropdown menu on click on one of its items (i.e. the menu closes itself), and how to prevent it if we want to keep it open (set onSelect/onClick to an empty function or a kind of preventDefault, use the 'open' prop, or 'onToggle' ?).

**Comment by jquense** [comment]
There is some documentation: http://react-bootstrap.github.io/components.html#btn-dropdowns-props

Notice `onToggle` `open`, etc

**Comment by alexandrethsilva** [comment]
A quick question related to this: why was onClick removed at all?... I couldn't really understand why a generally valid attribute was simply removed like that. Any clues?

**Comment by jquense** [comment]
not sure what you mean @alexandrethsilva

**Comment by taion** [comment]
This already is documented in the props table, and the default behavior is pretty obvious. I don't think having a specific example of a dropdown that doesn't close when you select an item is going to make things clearer for most people.
