### ISSUE TITLE
Dropdown reachable through tab navigation 

### ISSUE THREAD

**Issue by xicombd** [react-bootstrap/react-bootstrap#1347]
Hello!

I was trying to make my custom dropdown reachable through tab navigation by specifying `tabIndex="0"` but noticed that on the latest release that's no longer possible due to [this addition](https://github.com/react-bootstrap/react-bootstrap/commit/da1d0bcb7ecbab10973382083fc6da15ed6b9337#diff-17f754083466fd12638e891008f502b2R100) which sets `tabIndex` to `-1`.

Was this behaviour intended @jquense? 

Here's a snippet of its structure: 
```html
<Dropdown className="selector" id="selector" tabIndex="0">
  <div bsRole="toggle">Dropdown</div>
  <Dropdown.Menu>
     <MenuItem>...</MenuItem>
  </Dropdown.Menu>
</Dropdown>
```

Am I missing something? Is there a better way of making it accessible?  

Thank you!

**Comment by mtscout6** [comment]
Per the W3C Aria spec it's accessible via the up/down arrow keys once you focus on the toggle button. See: http://www.w3.org/WAI/PF/aria-practices/#menubutton

**Comment by jquense** [comment]
also In this instance your tabIndex should go on your toggle, not the surrounding dropdown div.

**Comment by xicombd** [comment]
@mtscout6, the problem was that I wasn't being able to focus the toggle button in the first place.

@jquense, ah ok, that fixes it!

Thank you for the fast replies! :smiley:
