### ISSUE TITLE
Control Focus in DropDownButton / MenuItem

### ISSUE THREAD

**Issue by rkhayat** [react-bootstrap/react-bootstrap#1350]
Hello, is the following scenario intended functionality?

I have an input inside a drop down button, it is wrapped in a menu item, at first the dropdown button would close by itself since the click inside the input was bubbling down (thinking I have clicked a menu item) I fixed this.. 
```
<Bootstrap.MenuItem href="javascript:void(0);" eventKey="1"> 
<Bootstrap.Input
onClick={function(e) {
                this.stopBubble(e);
            }.bind(this)}
/>

```
```
    stopBubble: function(e) {
        e.preventDefault();
        e.nativeEvent.stopImmediatePropagation();
        e.stopPropagation();
    },
```

**I am wondering if its possible to set the cursor inside the input, whenever I try the following using refs, the outside of the input gets focused, and not the inside**

```
var node = React.findDOMNode(this.refs.myRef);
node.focus();
```

Would I be better off creating it from scratch?

**Comment by jquense** [comment]
The default menuItems are not going to work here, they will wrap your input in an anchor and then focus the anchor. You will need to either create a custom MenuItem component or a custom Menu. You can take a look at the docs for dropdowns for details about both.

**Comment by rkhayat** [comment]
Thanks :+1:
