### ISSUE TITLE
tabs with no initially selected tab and animation don't work

### ISSUE THREAD

**Issue by jquense** [react-bootstrap/react-bootstrap#1352]
I have not done enough research to confirm this is the problem (sorry sort on time) but I wanted to make a note of it so I didn't forget later.

The tab animation callbacks are not firing at all (and therefore not selecting a tab) when I render left tabs, with no tab initially selected.

**Comment by taion** [comment]
Moved to https://github.com/react-bootstrap/react-bootstrap/issues/1418.
