### ISSUE TITLE
Using data tags with Dropdown.Menu?

### ISSUE THREAD

**Issue by sharky93** [react-bootstrap/react-bootstrap#1353]
More specifically i'm looking to add "data-container" to the Dropdown menu that is generated.

**Comment by taion** [comment]
`Dropdown.Menu` just forwards all the props onto the `ul`. If you specify it as a prop, it will end up on the DOM node.

**Comment by sharky93** [comment]
I see. I had an older version, this got recently fixed in https://github.com/react-bootstrap/react-bootstrap/commit/ce564cb349dc50c5fb1e05e811fe4ed94a5d396a. Thanks
