### ISSUE TITLE
Input wrapperClass attribute

### ISSUE THREAD

**Issue by srt0422** [react-bootstrap/react-bootstrap#1356]
I think there should be a way to assign a class to the components without overriding the default bootstrap classes.

The point of a library like this is to avoid manually setting up bootstrap components, and if I have to include the bootstrap class every time I want to add a custom class, I think that defeats the purpose of using these components.

**Comment by jquense** [comment]
could you provide details about what and which components your talking about?

**Comment by srt0422** [comment]
sure.  I was using the button component, and it would be nice to add a
custom class without overriding the base bootstrap class.

**Comment by jquense** [comment]
adding a class to a Button component doesn't, at all, override the base bootstrap classes.
