### ISSUE TITLE
textarea value does not reset on using nested state hash

### ISSUE THREAD

**Issue by uptownhr** [react-bootstrap/react-bootstrap#1362]
```
this.state = {
 data: {description: 'testing'}
}

reset(){
 this.setState({
  data: {}
 })
}

render(){
  return <div>
    <Input type="textarea" value={this.state.submitValue} />
   <Button onClick={this.reset}>Reset</Button>
  </div>
}
```
1. Render this
2. Enter in some info into text area
3. Press reset button
4. The entered text will still be there.

You can inspect the state and see that it is empty. All other input types work fine it is just the text area that does not get set properly when the nested hash is emptied.

**Comment by taion** [comment]
Why would setting `this.state.data` do anything for something consuming `this.state.submitValue`? It's also not clear to me that you're properly binding `reset`.

**Comment by uptownhr** [comment]
I just updated the sample code to be correct. I'm using an autobind class so i don't have to manually bind my methods but i added it above. Also, the value for textarea should have been data.description. Sorry about the error but please reopen and investigate. 

Thanks

**Comment by taion** [comment]
You're setting value to `undefined`, which makes the component be uncontrolled. Set it explicitly to `null` or an empty string.

**Comment by uptownhr** [comment]
I understand that is the work around, but all other Input types, do not function this way. Other input types actually removes the text when the hash is set to {}

**Comment by taion** [comment]
I see. That's actually just how React handles `value` on `textarea` v `input`. You can confirm this with raw `<input>` and `<textarea>` components and not using R-B `<Input>`.

**Comment by uptownhr** [comment]
that's an interesting design decision ... here's the thread on react talking about this, https://github.com/facebook/react/issues/2533
