### ISSUE TITLE
Example code for showing a Modal dialog does not work

### ISSUE THREAD

**Issue by ComponentFactory** [react-bootstrap/react-bootstrap#1365]
I am trying to show a modal dialog and am using the sample code from the website as a starting point (a http://react-bootstrap.github.io/components.html#modals-live). 

As the code on the website shows, open and close functions are added for showing and hiding the dialog. A button is shown as the means of invoking the open. Here is the react class I create for testing...

    var Modal = require('react-bootstrap').Modal;
    var Button = require('react-bootstrap').Button;

    var DialogBox = React.createClass({
        getInitialState: function() {
            return { showing: false };
        },
	
        close: function() {
           this.setState({ showing: false });
        },
	
       open: function() {
           this.setState({ showing: true });
       },
  
        render: function() {
            return (
                <div>		
                    <Button onClick={this.open}>Open</Button>
                        <Modal show={this.state.showing} onHide={this.close}>
                            <Modal.Header closeButton>
                                Dialog Title
                            </Modal.Header>
                            <Modal.Body>
                                Hello World!
                             </Modal.Body>
                             <Modal.Footer>
                             </Modal.Footer>
                         </Modal>
                     </div>
                 );
             }
    });

Very simple. Using this component inside my application shows the button as expected. But when pressed it does the following error...

**Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. This usually means that you're trying to add a ref...**

Is there an error with the sample code on the website?

**Comment by jquense** [comment]
This sdoesn't sound like it related to bootstrap. More likely however you are bundling React is including two instances of React instead of one

**Comment by ComponentFactory** [comment]
Aha, your spot on. Discovered react was indeed being included twice in the browser. That resolved it. Many thanks.
