### ISSUE TITLE
How to event fire on onclick React bootstrap Tab?

### ISSUE THREAD

**Issue by ranjan653** [react-bootstrap/react-bootstrap#1366]
<Tab  onClick={this.handleSelectTab}>   </Tab>

Onclick not working on Tab

**Comment by apkiernan** [comment]
Could you provide a code snippet of what you have tried that demonstrates the issue?

**Comment by ranjan653** [comment]
Yes, I am able to handle it.

But I am trying to do dynamic tab creation. Is it possible to do dynamic
tab creation in React?



Thanks
Ranjan

**Comment by taion** [comment]
Yes, just render a list and append to it. That's unrelated to React-Bootstrap though.
