### ISSUE TITLE
[Pagination] how to add text for 'Previous' and 'Next' buttons

### ISSUE THREAD

**Issue by lovedota** [react-bootstrap/react-bootstrap#1371]
Hi friends.

I am using React Bootstrap, and i want ask there are some options for adding text for *previous* and *next* button like this. Thanks !

```
<BootstrapPagination
       bsSize='small'
       prev
       next
       first
       last
       ellipsis={false}
       items={pages}
       maxButtons={Math.min(pages, 5)}
       activePage={this.props.options.currentPage}
       onSelect={this.onPageSelect.bind(this)}
/>
```

![pagination](https://cloud.githubusercontent.com/assets/417914/10244419/56235e54-6929-11e5-88cf-00ac430ac929.png)

**Comment by taion** [comment]
Not yet, but we'd happily take a PR for this; something along the lines of making `first` and the others take a `React.PropTypes.node` as an argument.

**Comment by chilts** [comment]
I'd be keen on tackling this.

Quick question: currently we show (for example) `&laquo;` for first. First is a `React.PropTypes.bool`. If we were to change that to `React.PropTypes.node`, then presumably the defaultProps would be `null`.

When checking if we have nothing in `renderFirst()`, we would obviously show nothing. If we have something, then we render that. However, we lose the ability to have a default *yes* which would just show the `&laquo;`. I'd propose we somehow want to keep that but happy to be guided here.

Of course, you could pass that in as `first` ... but then you gotta remember to do it and it's not automatic like it currently is. :)

**Comment by taion** [comment]
This was actually fixed by https://github.com/react-bootstrap/react-bootstrap/pull/1376 and https://github.com/react-bootstrap/react-bootstrap/pull/1400. Not released yet though.

**Comment by sedi0861** [comment]
Is this functionality released? Could not find proper documentation. Please give me the link if it is there.
