### ISSUE TITLE
Add shouldComponentUpdate to Glyphicon

### ISSUE THREAD

**Issue by Anahkiasen** [react-bootstrap/react-bootstrap#1378]
Component is currently re-rendering every time even though the icon will always stay the same unless `glyph` changes

**Comment by taion** [comment]
Per https://github.com/react-bootstrap/react-bootstrap/issues/633, we've decided not to do this.

**Comment by Anahkiasen** [comment]
@taion I understand the intent but if I have to wrap all React Bootstrap components in my own doesn't that kind of defeat the purpose of using a package in the first place? Couldn't it at least be implemented for at least the very low level components like Fade, Glyphicon etc?

**Comment by taion** [comment]
You should put the SCU on the higher-level component that is or is not pure. Something like `Fade` definitely should not implement SCU on our side because we have no clue what a user might put underneath it.

**Comment by jquense** [comment]
Is there any demonstrative data showing the glyphicon render calls are the bottleneck in an app?  the cost of SCU is not zero you have to do a compare on objects. in addition there is little to now benefit here bc the glyph icons render a single html element, you are doing work to short circuit reconciliation that only saves you a single additional check and a really small one at that. 

SCU is beneficial on components on the high end of a component branch.
