### ISSUE TITLE
onSelect handler for buttons

### ISSUE THREAD

**Issue by jclyons** [react-bootstrap/react-bootstrap#1383]
Buttons, especially those in ButtonToolbar and ButtonGroups, should be able tell their parent component when they become active or inactive. It seems like I currently have to perform a bunch of logic to tell whether a  button in the toolbar is selected or not.

**Comment by taion** [comment]
Huh? Just make your own custom component that takes `onSelected` and `eventKey` and makes a button, something like:

```js
class CustomButton extends React.Component() {
  onClick = () => {
    this.props.onSelected(this.props.eventKey);
  }

  render() {
    return <Button onClick={this.onClick} {...this.props} />
  }
}
```

This is not how those sorts of components are typically used, and this is trivial enough that I don't see a real need to support this in React-Bootstrap.

**Comment by jclyons** [comment]
That's close to what I ended up doing. However, it seems like the ButtonToolbar component exists for precisely this reason - i.e. to make selections from a toolbar/palette (i.e. formatting buttons for 'center-align', etc) that switch on a specific tool . Furthermore, it's not just a matter of determining whether the component is clicked. If a different button in the buttongroup is clicked the parent button group or toolbar should cause the child button to emit a 'deselect' event. I'm probably missing something key - is there a handler for ButtonToolbar or ButtonGroup that I'm not seeing that deals with this logic?

**Comment by jquense** [comment]
my opinion is that this is outside the scope of RB, button toolbar and button group exist to mirror their bootstrap counterparts which is to apply consistent styling to groups of buttons. 

if you want additional callbacks or handlers you can create your own version per @taion 's example.
