### ISSUE TITLE
react/lib/warning no longer.

### ISSUE THREAD

**Issue by grydstedt** [react-bootstrap/react-bootstrap#1387]
react/lib/warning doesn't work anymore. New location is `fbjs/warning` (using the fbjs library). Can do the pull request if we want it.

**Comment by taion** [comment]
We've actually switched to `warning` everywhere on the React 0.14 release. You should generally avoid importing things from `fbjs`.

We need to keep using `react/lib/warning` on the React 0.13 release because we want to preserve the old semantics, i.e. use `console.warn` instead of `console.error`.

**Comment by grydstedt** [comment]
Cool, thanks
