### ISSUE TITLE
Collapsed navbar buttons not showing and click events not firing on iPhone Safari 7.0

### ISSUE THREAD

**Issue by X-Fix** [react-bootstrap/react-bootstrap#1389]
Safari 7 has trouble with click events on elements that aren't typically interactive
https://developer.mozilla.org/en-US/docs/Web/Events/click
On top of that, the default toggle button doesn't display. I've specified a custom component with a glyphicon and that works but the toggle buttons on your component documentation page neither show nor respond when viewed on an iPhone 5s

**Comment by taion** [comment]
They're not showing up because of #1384. Otherwise it's a `button` element which should work.
