### ISSUE TITLE
React peer dependency is installing react 0.14

### ISSUE THREAD

**Issue by robrichard** [react-bootstrap/react-bootstrap#1392]
I think the peer dependency needs to be changed to ~ or ^ for 0.13. Currently npm will install react twice in my project, v0.13 for my app and v0.14 for react-bootstrap. This causes errors because two incompatible versions are loaded at the same time.

**Comment by taion** [comment]
Fixed by #1394.

**Comment by robrichard** [comment]
has this been published to npm?

**Comment by taion** [comment]
Just pushed.
