### ISSUE TITLE
node module 'history' is inside 0.26.3 tarball

### ISSUE THREAD

**Issue by robrichard** [react-bootstrap/react-bootstrap#1395]
http://registry.npmjs.org/react-bootstrap/-/react-bootstrap-0.26.3.tgz

Untar and inside is node_modules/history. Trying to create an npm shrinkwrap file will result in an error:

```
Problems were encountered
Please correct and try again.
extraneous: history@1.12.2 /Users/robrichard/projects/1stdibs-admin-v2/node_modules/react-bootstrap/node_modules/history
```

**Comment by taion** [comment]
Huh??? How is that possible? `node_modules` isn't supposed to be part of that tarball at all: https://github.com/react-bootstrap/react-bootstrap/blob/v0.26.3/package.json#L27-L33

**Comment by taion** [comment]
I mean, I guess I'l cut another release.

**Comment by taion** [comment]
Okay, released v0.26.4 that I checked doesn't include the random module.

**Comment by robrichard** [comment]
it's also in 0.27: http://registry.npmjs.org/react-bootstrap/-/react-bootstrap-0.27.0.tgz

**Comment by taion** [comment]
Okay, this is looking like it's actually an NPM bug. I checked a couple of other packages that have `history` as a dev dependency and they all have `node_modules/history` in the NPM tarball. There's nothing I can do about this.

**Comment by robrichard** [comment]
How did you fix it in 0.26.4?

**Comment by taion** [comment]
ref https://github.com/npm/npm/issues/9894

`history` was left over in my `node_modules` because I was switching between branches. It's not actually a dev dependency on 0.26.x because docs for that release are generated using React Router v0.13.x, so I just pruned my `node_modules` and re-published.

For 0.27.0 and onward, we've switched to the React Router v1.0.0 pre-releases, which do depend on `history`, so we can't publish without having `history` in `node_modules`.

Regardless, this is an upstream issue - there's nothing to fix here.

**Comment by droberts84** [comment]
I see this is an upstream issue, but in the meantime, is there a way to install 0.27 or 0.27.1 if you use `shrinkwrap` without adding a dependency for `history`?

**Comment by taion** [comment]
I don't know. I don't use `shrinkwrap`, so I'll have to defer to someone who does.

**Comment by droberts84** [comment]
Ok duh, I can force it by doing `rm -rf node_modules/react-bootstrap/node_modules/history` prior to running `npm shrinkwrap`.

Hope that helps someone.

**Comment by robrichard** [comment]
@taion now that this has been fixed in npm can you publish a new version that doesn't have history in the tarball

**Comment by taion** [comment]
They haven't cut the new release yet.

**Comment by geminiyellow** [comment]
yes, not cut the history in new release yet.

**Comment by tsing** [comment]
npm 2.14.10 is released.

**Comment by taion** [comment]
I'm well aware of that, since it was my patch that fixed the bug in the first place.

Current plan is to just cut v0.28.0 ASAP.
