### ISSUE TITLE
Provide pre-built package without React bundled in it

### ISSUE THREAD

**Issue by adamziel** [react-bootstrap/react-bootstrap#1397]
I noticed there is no easy way to use this package in a project not depending on nodejs. Correct me if I'm wrong, but there are no pre-built packages around that I could just add to `<script>` or requirejs config. The closest thing I found is react-bootstrap-bower, however it has a version of react bundled with it, which means it does not work if React is already included in the project

https://raw.githubusercontent.com/react-bootstrap/react-bootstrap-bower/master/react-bootstrap.js

**Comment by jquense** [comment]
Hey there,

the bower release doesn't contain react in it, or shouldn't anyway. I think this may be due to the most recent switch to using react 0.14

@taion we probably need to mark ReactDOM as external in our configs as well as React right?

**Comment by adamziel** [comment]
ah you are right, I got an older version from this commit:

https://github.com/react-bootstrap/react-bootstrap-bower/blob/d170fa6bdbe97701ade045caa0c14d7c1358df15/react-bootstrap.js

and it works like a charm

**Comment by taion** [comment]
Oh, you're right. Forgot about marking ReactDOM external.
