### ISSUE TITLE
Nav does not navigate when specify handleSelect to change state

### ISSUE THREAD

**Issue by frankbolviken** [react-bootstrap/react-bootstrap#1403]
I have this implementation:

```
  _handleSelect: function (key, href) {
    this.setState({
      activeKey: key
    });
  },

  render () {
    return (
      <div className="column col-sm-3 sidebar">
        <Nav bsStyle="pills" stacked activeKey={(this.state.activeKey)} onSelect={this._handleSelect}>
          <NavItem eventKey={1} href="#/">NavItem 1 content</NavItem>
          <NavItem eventKey={2} href="#/about">NavItem 2 content</NavItem>
        </Nav>
      </div>
    )
  }
});
```

When user clicks a link, the active state is updated, but no navigation. I guess thats because when you specify a onSelect method, the event is stopped and only code inside onSelect is executed.
But if I disable the onSelect, I don't get how to change the active state in the nav.
What am I missing here?

**Comment by taion** [comment]
You can update `location.href` in `_handleSelect` if you want.

But for this sort of thing you really should use something like React Router.

**Comment by frankbolviken** [comment]
I am indeed using react-router. So the transitioning between components works fine. Just cannot get setting active nav item and transitioning workin at the same time.

**Comment by taion** [comment]
If you're using React Router, then use React-Router-Bootstrap and a `Link` or `LinkContainer` to manage this for you.
