### ISSUE TITLE
Tabs: allow to provide className for `<nav role="tablist">`

### ISSUE THREAD

**Issue by Webkadabra** [react-bootstrap/react-bootstrap#1405]
I'm trying to do the following, and for that it'd be great if one can provide additional className to be added to `<nav role="tablist">`. Currently, you can only provide class name or style object to tabs container (one level above `<nav role="tablist">`)

![tabs_please](https://cloud.githubusercontent.com/assets/1168612/10426210/9f1598e2-70e6-11e5-81a1-30f81d8a8d03.PNG)

**Comment by taion** [comment]
We'd consider a PR for this. That said, why not just use a CSS selector?

**Comment by taion** [comment]
Moved to https://github.com/react-bootstrap/react-bootstrap/issues/1418.

**Comment by M3lkior** [comment]
Same need here.

A workaround is to directly use a Nav in Tab.Container but just for positionning a classname ...

I dont find relative fix/answer in #1418 for this issue, can you help me ?

**Comment by taion** [comment]
That's not a "workaround". That's the intended solution – the `<Tabs>` component is explicitly not meant to cover all possible use cases. We expose the lower-level API specifically to offer this level of customizability.

**Comment by M3lkior** [comment]
Ok @taion, thanks
