### ISSUE TITLE
NavItem gives error: Uncaught Error: Invariant Violation

### ISSUE THREAD

**Issue by lemonCMS** [react-bootstrap/react-bootstrap#1408]
Hello,

Today after updating Nodejs to 4.2.1 and npm 2.14.7 i got the following error.
After debugging i noticed the error started showing when i add a NavItem component into the render.

````
Uncaught Error: Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details: 
````
Package json snippet
````json
{
 "react-dom": "0.14.0",
"react": "^0.14.0",
"react-bootstrap": "^0.27.1"
}
````

Kind Regards

**Comment by taion** [comment]
You're probably using NPM2 and have a peer dependency issue. Try wiping `node_modules` and re-installing deps.

**Comment by lemonCMS** [comment]
I have done that serveral times already. i will do some more debugging

**Comment by taion** [comment]
Check that you don't have an old version of React getting pulled in somehow, maybe via a different dependency.

**Comment by DerekStrickland** [comment]
Same issue happening for me.  Any progress figuring it out?

**Comment by DerekStrickland** [comment]
My problem was in fact that multiple copies of react were getting pulled in.  Once I upgraded to React 0.14 where react-dom was split out, I need to update my gulp browserify dependencies argument to also reference react-dom separately like this.  Once I did this, all was well with the world.

```javascript
var dependencies = [
    'react',
    'react-dom'
];
```
