### ISSUE TITLE
Hide box on Tabs

### ISSUE THREAD

**Issue by KochiyaOcean** [react-bootstrap/react-bootstrap#1409]
![image](https://cloud.githubusercontent.com/assets/8194131/10535273/ee9742fa-7413-11e5-8c96-c5fce0a483a5.png)
There is a blue box on the Tab 2 when click on it.
I'm wondering if there's any way to make it invisible.

**Comment by jquense** [comment]
Hi there, the blue box is the browsers focus indicator not something by react bootstrap, more info about why you should leave it alone at: http://www.outlinenone.com
