### ISSUE TITLE
Dropdown Toggle title prop vs. html global attr title

### ISSUE THREAD

**Issue by alsoscotland** [react-bootstrap/react-bootstrap#1410]
Using the prop named "title" as the button text disallows the ability to get a html global attribute "title" (default browser tooltip behavior) which is desirable at times for buttons.
usage is here:
https://github.com/react-bootstrap/react-bootstrap/blob/master/src/DropdownToggle.js#L26

Might you consider renaming the title prop and allowing the html title attribute to be added to the control?

**Comment by taion** [comment]
Can we just switch that to `this.props.children || this.props.title`?

**Comment by alsoscotland** [comment]
@taion, it would function that way, but it seems inadvisable to overtake attr names that are globally valid attributes in HTML.

**Comment by taion** [comment]
Not overtaking anything. Just using `title` as the default label. Seems like a nice way to simplify declaring dropdowns.
