### ISSUE TITLE
Tooltip "placement" prop not working correctly (even on your example page)

### ISSUE THREAD

**Issue by gbmhunter** [react-bootstrap/react-bootstrap#1420]
If you navigate to the tooltips section of the component example page (https://react-bootstrap.github.io/components.html#tooltips), the "In Text Copy" example has the following line of code:

````
let tooltip = <Tooltip placement="top">{this.props.tooltip}</Tooltip>;
````

This `placement="top"` statement does not appear to work correctly (tooltip is appearing on the right).

**Comment by stefk** [comment]
Docs are still confusing IMO. The `placement` prop appears only in the Tooltip props list, not in the OverlayTrigger one (https://react-bootstrap.github.io/components.html#tooltips-props). Also, there's no mention that the `placement` prop of a tooltip becomes ineffective inside an overlay.
