### ISSUE TITLE
Create a Context Menu components ?

### ISSUE THREAD

**Issue by harobed** [react-bootstrap/react-bootstrap#1422]
What do you think about append Context Menu component to react-bootstrap, like http://vkbansal.github.io/react-contextmenu/#/simple-menu ?

Note : this "react-contextmenu" package isn't compatible with react 0.14.0

**Comment by taion** [comment]
This isn't in upstream TWBS - we might consider a PR if it were relatively simple, but it's not really in-scope for this project.
