### ISSUE TITLE
Set custom width/height and position for React-Bootstrap Modal without using CSS/jQuery

### ISSUE THREAD

**Issue by topgun743** [react-bootstrap/react-bootstrap#1425]
I want to set custom width/height (via width/height numeric props) and also Modal position (via top/left props) for React-Bootstrap Modal and I want to do it without using CSS/jQuery/javascript.

How is it possible by just specifying props for the Modal? 
For the time being I used jQuery for doing all this stuff but I guess this is not a recommended approach by React.

**Comment by taion** [comment]
This is not R-B related. You style a modal the same way you style any block element - in your case probably with an inline `style` prop.
