### ISSUE TITLE
disabling animation in OverlayTrigger displays a React PropType warning

### ISSUE THREAD

**Issue by rdy** [react-bootstrap/react-bootstrap#1435]
When adding an animation: false prop to the overlay to disable animation if you are using React in development mode it displays the following warning:

`Warning: Failed propType: Invalid prop 'transition' of value 'false' supplied to 'Overlay'. Expected an Element `type` such as a tag name or return value of React.createClass(...) Check the render method of `Overlay`.`

We've the offending code to be in how it assigns the transition prop in the Overlay component,  the overlay expects a non-boolean so when disabling the animation it should use undefined or null instead of passing the original animation boolean through.

This is somewhat annoying since its not a true problem, just an issue with the way that the overlay trigger is passing its props through to the base overlay component. We'll add a a pull request to this issue.

**Comment by mmahalwy** [comment]
still getting this problem..

**Comment by jquense** [comment]
@mmahalwy are using you a version with the referenced commit in it?
