### ISSUE TITLE
linter does not pass

### ISSUE THREAD

**Issue by rdy** [react-bootstrap/react-bootstrap#1437]
`npm test` runs the linter first, there are currently 63 errors with eslint 1.7.3. Newly forked versions are probably running slightly newer versions of eslint that changed the default eslint configuration.

**Comment by taion** [comment]
`npm run lint` passes cleanly for me with all of my NPM dependencies reinstalled from scratch.

**Comment by taion** [comment]
And you can tell from the green Travis PR builds as well.
