### ISSUE TITLE
wrong cursor for .navbar-brand

### ISSUE THREAD

**Issue by barbalex** [react-bootstrap/react-bootstrap#1439]
When the mouse hovers over `.navbar-brand` the cursor is `text` instead of `pointer`.
Should be `pointer`.

See an example for the wrong behaviour here: https://react-bootstrap.github.io/components.html#navbars

And an example for the correct behaviour here: https://react-bootstrap.github.io/components.html#navbars

**Comment by taion** [comment]
What? No. You get a pointer cursor if the brand element is a link. The second example shows that. Doesn't make any sense to show pointer if it's not a link.

**Comment by barbalex** [comment]
Thanks for making this clear.

I believe the first example is misleading because NavBrand makes no sense without adding a link and in this example the link is not added.

In contrast NavItem does NOT need a link to work as expected.

So if you are a react-bootstrap noob (and who else would read this documentation) you will probably look at the first example and get it wrong because it contains no link inside NavBrand.

And as you will probably apply onClick handlers to NavBrand as well as NavItem, you will most likely miss the fact that the mouse does not show a pointer on NavBrand.

So NavBrand not showing a pointer cursor is not expected behaviour.

**Comment by jquense** [comment]
I use nav brands that aren't links all the time. in either case that would be a css change which we don't do.

**Comment by taion** [comment]
We could make the initial `Navbar` example make the `NavBrand` a link though. I dunno. Seems pretty trivial to me.

**Comment by jquense** [comment]
if that seems more consistent...and anyone has time for it sure :P I don't think it's a big deal either way

**Comment by barbalex** [comment]
I just forked the project to make a pull request - but it is already done
:-)
Thanks guys!


2015-10-24 0:38 GMT+02:00 Jason Quense <notifications@github.com>:
