### ISSUE TITLE
Giving a class to an Input, Its label is not affected

### ISSUE THREAD

**Issue by dgarciap** [react-bootstrap/react-bootstrap#1444]
Hi,
I've got a problem while trying to make a react-bootstrap Input invisible.

I'm trying to assing style with style={{visibility: hidden}} or just putting a class to this element with className="visibility-off".

The thing is that this class or style is only applied to the input itself, never to the label which comes with this input.

My jsx code looks like this:
```html

<Input ref="myCheckBox" className="visibility-off" type='checkbox' 
                    label='My example of check box'/>
```
Am I doing something wrong?
I think that taking into accound that both label and input are generated with the same tag, this class or style should be applied on both.

**Comment by taion** [comment]
API's a bit messy - `className` applies to the `<input>` or whatever. You probably want `groupClassName`.
