### ISSUE TITLE
Accept componentClass on ListGroupItem

### ISSUE THREAD

**Issue by swoogie** [react-bootstrap/react-bootstrap#1445]
https://github.com/react-bootstrap/react-bootstrap/blob/master/src/ListGroupItem.js#L35

A list item should not be rendering as a button, however it does when onClick is present. Since buttons cannot be rendered within a button, an error is getting thrown when I attempt to but a button on my list items. Below is some sample code.

```
  <ListGroup>
    <ListGroupItem onClick={this.foo}>
      <span>Example list item</span>
      <Button onClick={this.bar}>Button1</Button>
      <Button onClick={this.foobar}>Button2</Button>
    </ListGroupItem>
  </ListGroup>
```

**Comment by taion** [comment]
We're not going to change the default, because a `button` is the most accessible element to render there given just an `onClick` handler, and the example is specifically demonstrated in the TWBS docs.

We would consider a PR that allowed customizing the actual rendered component - this has to ensure the correct behavior with `ListGroup`'s logic for rendering a `div` or `ul`, though.

**Comment by swoogie** [comment]
I could do a PR with that customization. Do you have a preferred name for a this property?

**Comment by taion** [comment]
We typically call this `componentClass`.

**Comment by taion** [comment]
I've updated the title of this issue to reflect the actual task.

**Comment by taion** [comment]
@swoogie Are you still working on this?

**Comment by taion** [comment]
Closing due to staleness.

**Comment by L-u-k-e** [comment]
If anyone else is looking for a workaround, what I did was just put everything that was inside my `ListGroupItem` in a div, then put my `onClick` handler on the div. (This prevents the `ListGroupItem` from rendering as a button.)

Example:

`
 <ListGroup>
    <ListGroupItem>
      <div onClick={this.foo}>
        <span>Example list item</span>
        <Button onClick={this.bar}>Button1</Button>
        <Button onClick={this.foobar}>Button2</Button>
      </div>
    </ListGroupItem>
  </ListGroup>
`
