### ISSUE TITLE
Incorrect utf-8 symbols in Rails

### ISSUE THREAD

**Issue by pfa230** [react-bootstrap/react-bootstrap#1449]
Hi,

Modal close button renders incorrectly in the last version of react-bootstrap.

In July version it looks like this:
`<button class="close" aria-label="Close" style="margin-top:-2px;" data-reactid=".6.1.0.0.$/=10.0">
    <span aria-hidden="true" data-reactid=".6.1.0.0.$/=10.0.0">×</span>
</button>`

(span value is '×')

In the most recent version it renders as:
`<button class="close" data-reactid=".5.1.0.0.$/=10.0"><span aria-hidden="true" data-reactid=".5.1.0.0.$/=10.0.0">Ã—</span></button>`

(span value is 'Ã—' which is I believe '×' encoded as ASCII).

App runs on Rails 3.2 using React 0.14

Is it something I missed when upgrading or expected behavior for older Rails versions?

**Comment by taion** [comment]
The markup is just `&times;`. Make sure you have the right charset configured.

**Comment by alexandresebrao** [comment]
Sometimes we can't set UTF-8 and we are having problems with built-in utf-8 instead of markup
