### ISSUE TITLE
Make React's peerDependency a devDependency

### ISSUE THREAD

**Issue by binarykitchen** [react-bootstrap/react-bootstrap#1450]
It is causing headaches. When you don't run `npm shrinkwrap` and include React Bootstrap components in another custom React component within you app, you might risk initializing React components from different React versions.

This error broke our app:

```Error: Invariant Violation: Objects are not valid as a React child (found: object with keys {type, key, ref, _owner, _context, _store}). It looks like you're using an element created by a different version of React. Make sure to use only one copy of React.```

Hence I suggest not to use peerDependency but make it a devDependency.

**Comment by taion** [comment]
That's NPM2's broken peer dependency handling.

The specification of React v0.14 as a peer dependency is specifically because the current version of the library is not compatible with React v0.13.x any more.

**Comment by binarykitchen** [comment]
Right, I see. Will try different things now.

Can't you at last pinpoint peer dependencies with `^` instead of `>=`?

**Comment by taion** [comment]
No. Why does it even matter? There's exactly one version each of `react` and `react-dom` that matches the specified range.
