### ISSUE TITLE
How can I put MultiChoic CheckBox in Dropdown

### ISSUE THREAD

**Issue by lockelee1015** [react-bootstrap/react-bootstrap#1453]
I wanna build a ComboBox by input and Dropdown button.I wanna put some checkbox in MenuItem.But how can I reject the Dropdown div to close?I wanna my user choice all he wants then close any other places to close the dropdown.Thanks!

**Comment by taion** [comment]
That's not a component offered by Bootstrap. If you want to build this, you'll have to build it yourself using the custom dropdown support.
