### ISSUE TITLE
ModalDialog div attribute tabindex='-1' caused jquery.select2 searchbox could not work

### ISSUE THREAD

**Issue by MaxwellZhou** [react-bootstrap/react-bootstrap#1455]
I use react-bootstrap modal class and jquery select2 in my project .but I found that tabindex will cause select2 searchbox could not be focused.then I remove tabindex attribte it works.could you remove tabindex='-1' attribute? thanks

**Comment by jquense** [comment]
nope, that would break the accessibility of the modal and make it impossible to use with a screen reader. You can use the `autoFocus` prop with react components to focus the select automatically, or you can manually focus the input after the modal opens using one of the transition hooks
