### ISSUE TITLE
Add prop for tabsClass

### ISSUE THREAD

**Issue by ktabori** [react-bootstrap/react-bootstrap#1456]
Just like {Tab} can have a prop for class (tabClassName), it would be nice to have the opportunity for add classes to {Tabs}.

**Comment by taion** [comment]
This is all going to fall under the lower-level API from https://github.com/react-bootstrap/react-bootstrap/issues/1418.

**Comment by M3lkior** [comment]
Same need here.

A workaround is to directly use a `Nav` in `Tab.Container` but just for positionning a classname ...

I dont find relative fix/answer in #1418 for this issue, can you help me ?

**Comment by jquense** [comment]
@M3lkior css precendence doesn't work like that, the order of classnames on an element doesn't matter

**Comment by M3lkior** [comment]
Oh sorry, it's for issue #1405
