### ISSUE TITLE
Problem with componentDidUpdate in Modal component

### ISSUE THREAD

**Issue by kovalenko-sb** [react-bootstrap/react-bootstrap#1458]
In documentation we have that componentDidUpdate is called after all changes have completed (including DOM changes). However I find following issue :

I have the component

	import React, { Component } from 'react';
	import { Modal, Button } from 'react-bootstrap';

	export default class TestApp extends Component {
		constructor (props) {
			super(props);
			this.state = {
				isShow : true,
				isContentHidden : true
			};
		};

		componentDidUpdate(prevProps, prevState) {
			console.log('componentDidUpdate');
			console.log('-ref:', this.contentWrapper ? React.findDOMNode(this.contentWrapper).className : '');
			console.log('-jquery:', $('.test_content').attr('class'));
		};

		refCallback(ref) {
			if (ref !== null) {
				this.contentWrapper = ref;
				console.log('updateRef');
				console.log('--ref:', React.findDOMNode(ref).className);
				console.log('--jquery:', $('.test_content').attr('class'));
			}
		};

		handleClick = () => {
			this.setState({ isContentHidden : !this.state.isContentHidden });
		};

		handleHide = () => {
			this.setState({ isContentHidden : true });
		};

		render () {
			var cssClasses = "test_content";
			if (this.state.isContentHidden) {
				cssClasses += " hidden";
			}
			var content = (
				<div>
					<Button bsStyle="info" onClick={this.handleClick}>Show content</Button>
					<div className={cssClasses} ref={(ref)=>{this.refCallback(ref);}}>content</div>
				</div>
			);

			//return content;

			return (
				<Modal className="test_window" bsSize="large" show={this.state.isShow} onHide={this.handleHide}>
					<Modal.Header closeButton>
						<Modal.Title>Test</Modal.Title>
					</Modal.Header>
					<Modal.Body>
						{content}
					</Modal.Body>
				</Modal>
			);
		}
	}

	React.render(<TestApp />, document.body);

If I press on "Show content" button, I'll have the following information in console

	componentDidUpdate
	-ref: test_content hidden
	-jquery: test_content hidden
	updateRef
	--ref: test_content
	--jquery: test_content

I uncommented following line in the render method

       //return content;

After this I pressed on "Show content", I received following information in console

	updateRef
	--ref: test_content
	--jquery: test_content
	componentDidUpdate
	-ref: test_content
	-jquery: test_content

As you can see methods are called in different order.

When using Modal component, componentDidUpdate method called before DOM is really updated.

Could you please fix it or guide me how to know that DOM update is finished in my component?

**Comment by taion** [comment]
The modal has its own state management for its animation. Use the hooks provided.
