### ISSUE TITLE
The 'affix' on the right web menu isn't working

### ISSUE THREAD

**Issue by mezod** [react-bootstrap/react-bootstrap#1459]

**Comment by taion** [comment]
Works for me. Can you elaborate?

**Comment by mezod** [comment]
There's not much to add, in https://react-bootstrap.github.io/components.html the affix tat shows in which part of the page you are in the menu doesn't show anything, not move while you scroll down to other sections. If you click a section it will take you there and mark it, but if you scroll the mark won't change as you scroll. I'm on FF 41.0.2

**Comment by taion** [comment]
It's just an Affix. There's no scrollspy set up. There isn't in fact a scrollspy in this library at all.
