### ISSUE TITLE
React-bootstrap table is not refresh with new data.

### ISSUE THREAD

**Issue by shekharkul** [react-bootstrap/react-bootstrap#1461]
Hello,

I am using react-bootstrap table into my application, 
It is working  fine at initial load, but when i reload it again with new data then it is not refresh with new data.

Thanks,
Shekhar

**Comment by jquense** [comment]
Could you provide some code that doesn't work? The question doesn't really make sense, since the table doesn't have anything to do with "loading data"

**Comment by shekharkul** [comment]
Please find below code.

 var validateItempropertyList = this.props.ItemProperty;

Object.keys(validateItempropertyList).map(function(validateItemprop){
   products.push({
          ItemId : validateItempropertyList[validateItemprop].ItemId,
          ItemName : validateItempropertyList[validateItemprop].ItemName,
});
 });


 <BootstrapTable  data={products} pagination={true} selectRow={selectRowProp} columnFilter={true}>
        <TableHeaderColumn dataField="ItemId" isKey={true} hidden={true}>ItemId </TableHeaderColumn>
        <TableHeaderColumn dataField="ItemName"  dataSort={true}>ItemName </TableHeaderColumn>
      </BootstrapTable>

**Comment by shekharkul** [comment]
Please find below code.
var validateItempropertyList = this.props.ItemProperty;

Object.keys(validateItempropertyList).map(function(validateItemprop){
products.push({
ItemId : validateItempropertyList[validateItemprop].ItemId,
ItemName : validateItempropertyList[validateItemprop].ItemName,
});
});

 Object.keys(validateItempropertyList).map(function(validateItemprop){
        products.push({
          ItemId : validateItempropertyList[validateItemprop].ItemId,
          ItemName : validateItempropertyList[validateItemprop].ItemName,
});
});

**Comment by jquense** [comment]
thanks but his code doesn't actually contain any react bootstrap code, or react code for that matter, nit sure what to do with it...

**Comment by taion** [comment]
This has nothing to do with React-Bootstrap and is most likely just due to incorrect React state management.
