### ISSUE TITLE
Carousel width and height props are inverted?

### ISSUE THREAD

**Issue by newphew92** [react-bootstrap/react-bootstrap#1462]
Hi, I tried playing with the dimensions of the carousel and it seems that the width and height are inverted? When I shrank the dimensions of the width, it applied the changes to the height instead.

**Comment by newphew92** [comment]
Upon closer inspections it seems that the height of the image takes the value of the width as well.
![screen shot 2015-10-30 at 4 55 24 pm](https://cloud.githubusercontent.com/assets/5588583/10857864/11d2221c-7f27-11e5-8588-16ebca7f32b2.png)
![screen shot 2015-10-30 at 4 55 17 pm](https://cloud.githubusercontent.com/assets/5588583/10857865/11d4198c-7f27-11e5-8098-7ea95d08051e.png)

**Comment by taion** [comment]
We don't control the CSS. The `Carousel` component doesn't even take any dimensions - this is determined entirely by the contents.
