### ISSUE TITLE
Call callback when Tab is selected

### ISSUE THREAD

**Issue by jochenberger** [react-bootstrap/react-bootstrap#1471]
I'd like to be able to register a callback that is executed when a tab is selected (i,e, made active). This could be an additional prop fro `Tabs` or for `Tab`.

**Comment by megapctr** [comment]
Is your desired behavior different from `handleSelect` from [this example](https://react-bootstrap.github.io/components.html#tabs-controlled)?

You could do something like this:
```
handleSelect: function (key) {
    this.props.handleSelect(key);
}
```

**Comment by jochenberger** [comment]
I guess you mean `onSelect`. Yes, I mean something else. I don't want to override the default `onSelect` function. I want the new tab to be shown and my callback to be called afterward.

**Comment by megapctr** [comment]
How about this? Does your callback really depend on whether the tab content has been shown?
```
handleSelect: function (key) {
    this.setState(key);
    this.props.handleSelect(key);
}

render: function () {
    return (
        <Tabs activeKey={this.state.key} onSelect={this.handleSelect}>
            ...
        );
}
```

**Comment by jochenberger** [comment]
> Does your callback really depend on whether the tab content has been shown?
Yes, it does indeed. I need to refresh a CodeMirror instance when the containing tab is activated.

**Comment by taion** [comment]
Just follow the controlled tabs example and manage all the state yourself. Adding this isn't worth increasing the API surface area.
