### ISSUE TITLE
Rapid keyboard navigation on Tabs with animation={true} results in invisible content

### ISSUE THREAD

**Issue by shimy1984** [react-bootstrap/react-bootstrap#1472]
If you toggle through Tabs using left and right arrow keys at a rapid pace with the animation prop set to true, the content of the tabs will disappear and will not reappear until you perform a hard page refresh.

This can be duplicated at the documentation site: http://react-bootstrap.github.io/components.html#tabs

This seems to be a common animation queue issue often found in this sort of situation.

A workaround for now is to set animation={false}.

**Comment by taion** [comment]
Dupe of #557, tracked on #1418 now.
