### ISSUE TITLE
Bug -  FireFox dropdown menu items

### ISSUE THREAD

**Issue by barreyro** [react-bootstrap/react-bootstrap#1474]
Hello. When displaying a dropdown menu item, I've noticed an unwanted border appears on FireFox, but not in Chrome. 
An example screenshot of the FireFox bug using the dropdown menu items from the react-bootstrap docs:
![screen shot 2015-11-04 at 9 07 29 am](https://cloud.githubusercontent.com/assets/8381409/10940778/2673d7ee-82d6-11e5-9308-c3ee23716b3a.png)

On chrome:
![screen shot 2015-11-04 at 9 28 17 am](https://cloud.githubusercontent.com/assets/8381409/10940826/6d78f9d0-82d6-11e5-85a0-931e2833b0b7.png)

**Comment by taion** [comment]
I took a quick look and it seems like it might be related to the `tabindex="-1"` we use on the parent component. Weird.

**Comment by jquense** [comment]
perhaps like a css bug with firefox, ignoring the `outline: none`?

**Comment by taion** [comment]
It's weird because it's just a `<div>` that shouldn't be receiving focus anyway. But what do you think of getting rid of https://github.com/react-bootstrap/react-bootstrap/blob/master/src/Dropdown.js#L102 anyway? It doesn't seem like we need it.

**Comment by jquense** [comment]
I added it here: https://github.com/react-bootstrap/react-bootstrap/commit/da1d0bcb7ecbab10973382083fc6da15ed6b9337 but I am trying to remember why...

The only thing I can think of is that dropdown needs to listen for keyboard events?

**Comment by taion** [comment]
I think FF is doing something deeply messed up - it's actually giving focus to that `<div>` (whether or not it has tabindex -1) after the user clicks on the dropdown button. Why is it doing this?

**Comment by hongrich** [comment]
This also happens on Safari (9.0.1) but the outline is different looking. 
![Safari 9.0.1](https://cloud.githubusercontent.com/assets/11243/11380147/5b4980c6-92c2-11e5-93a7-d6db20129eae.png)

Taking out `tabindex="-1"` **or** adding `outline: none` makes the outline go away.
