### ISSUE TITLE
Overlay component broken in IE 8

### ISSUE THREAD

**Issue by tp** [react-bootstrap/react-bootstrap#1475]
The <Overlay> component does not show in IE 8 at all.

![image](https://cloud.githubusercontent.com/assets/52437/10941162/7299daa4-830a-11e5-8996-73c89183edfe.png)

While I can't see any error or warning on the documentation page (in the dev console), I get "Invalid Argument." exceptions in my local project which indicates that a style is set, that is not compatible with IE 8.

Still investigating where this comes from exactly, because I was unable to find any strange styling properties on the rendered overlays in other browsers but maybe this already breaks in an intermediate state.

**Comment by jquense** [comment]
hey there thanks for the report,

we'd be happy to fix it if you can point us to the specific incompatible part, otherwise, the team is sort of stretched thin to be able to spin up ie8 vms and debug these issues. 

thanks!

**Comment by tp** [comment]
I haven't found the culprit yet but I am actively looking into this in order to get this fixed. Only viable alternative for us would be to bypass R-B and call TBS directly which would be a shame.

Related: https://github.com/facebook/react/issues/2815

**Comment by taion** [comment]
Ultimately our IE8 support is going to be best-efforts - none of us have it as an active priority to maintain 100% IE8 compatibility. We'd be happy to offer help and look at any PRs or suggestions, but this isn't really enough to go off of at this point.

**Comment by tp** [comment]
I found out that the "plain" TBS also does not support tooltips in IE 8, so this probably would need to be fixed a layer deeper.

As a workaround I found this nice library that shares the same look as the TBS tooltips and also works with IE 8: http://react-component.github.io/tooltip/

**Comment by taion** [comment]
If it's broken upstream as well, then I'm going to close this issue for now.
