### ISSUE TITLE
ButtonGroup.js: Invalid argument must be an array

### ISSUE THREAD

**Issue by binarykitchen** [react-bootstrap/react-bootstrap#1476]
When running jest tests, I get plenty of those errors

```
Error: /home/michael-heuberger/Development/something/src/frontend/components/__jest__/Tabs.cjsx: /home/michael-heuberger/Development/something/src/frontend/components/Tabs.cjsx: /home/michael-heuberger/Development/something/node_modules/react-bootstrap/lib/index.js: /home/michael-heuberger/Development/something/node_modules/react-bootstrap/lib/ButtonGroup.js: Invalid argument must be an array
    at Object.all [as default] (/home/michael-heuberger/Development/something/node_modules/react-bootstrap/node_modules/react-overlays/node_modules/react-prop-types/lib/all.js:12:11)
    at Object.<anonymous> (/home/michael-heuberger/Development/something/node_modules/react-bootstrap/lib/ButtonGroup.js:37:45)
    at Object.runContentWithLocalBindings (/home/michael-heuberger/Development/something/node_modules/jest-cli/src/lib/utils.js:394:17)
    at Loader._execModule (/home/michael-heuberger/Development/something/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:234:11)
    at Loader.requireModule (/home/michael-heuberger/Development/something/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:845:14)
    at Loader.requireModuleOrMock (/home/michael-heuberger/Development/something/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:875:19)
    at Object.<anonymous> (/home/michael-heuberger/Development/something/node_modules/react-bootstrap/lib/index.js:75:21)
    ...
```

Using the latest versions of all involved packages here. Any ideas what the issue is with the ButtonGroup.js?

**Comment by taion** [comment]
There's really nothing here for us to go off of, since `ButtonGroup` works just fine on the components page, in our tests, and actually in my own uses of it as well.

I'd be happy to re-open this if you can provide us with something actionable, but you're most likely accidentally mocking something you shouldn't be with Jest.

**Comment by binarykitchen** [comment]
Understand. Trying to reduce this:

The test file:

```cjsx
jest.dontMock('../Help')

Help      = require('../Help')
React     = require('react')
TestUtils = require('react-addons-test-utils')

describe 'Help', ->

  it 'renders without error', ->

    TestUtils.renderIntoDocument(
      <Help></Help>
    )
```

the help component:

```cjsx
React          = require('react')
ReactBootstrap = require('react-bootstrap')

{ Panel } = ReactBootstrap

module.exports = React.createClass(

  displayName: 'Help'

  render: ->
    <Panel>
      <h4>blahblah</h4>
    </Panel>
)
```

causes this

``
[17:07:13] jest
Using Jest CLI v0.7.0
Running 30 test suites...
 FAIL  src/frontend/archiving/components/__jest__/Help.cjsx 
● Runtime Error
Error: /home/michael-heuberger/Development/something/src/frontend/archiving/components/__jest__/Help.cjsx: /home/michael-heuberger/Development/something/src/frontend/archiving/components/Help.cjsx: /home/michael-heuberger/Development/something/node_modules/react-bootstrap/lib/index.js: /home/michael-heuberger/Development/something/node_modules/react-bootstrap/lib/ButtonGroup.js: Invalid argument must be an array
    at Object.all [as default] (/home/michael-heuberger/Development/something/node_modules/react-bootstrap/node_modules/react-overlays/node_modules/react-prop-types/lib/all.js:12:11)
    at Object.<anonymous> (/home/michael-heuberger/Development/something/node_modules/react-bootstrap/lib/ButtonGroup.js:37:45)
...
``

when i remove `ReactBootstrap = require('react-bootstrap')` then it won't happen.

**Comment by taion** [comment]
Looks like something going wrong with Jest mocking React-Bootstrap. Try either not mocking React-Bootstrap or importing like:

```js
var Panel = require('react-bootstrap/lib/Panel');
```

**Comment by binarykitchen** [comment]
oh man, that was the solution. works now! thx

**Comment by binarykitchen** [comment]
@taion I have a new, similar issue now with

``
Error: /home/michael-heuberger/Development/something/src/frontend/components/__jest__/Tabs.cjsx: /home/michael-heuberger/Development/something/src/frontend/components/Tabs.cjsx: /home/michael-heuberger/Development/something/node_modules/react-bootstrap/lib/Tabs.js: /home/michael-heuberger/Development/something/node_modules/react-bootstrap/lib/Nav.js: Invalid argument must be an array
    at Object.all [as default] (/home/michael-heuberger/Development/something/node_modules/react-bootstrap/node_modules/react-overlays/node_modules/react-prop-types/lib/all.js:12:11)
    at Object.<anonymous> (/home/michael-heuberger/Development/something/node_modules/react-bootstrap/lib/Nav.js:51:49)
    at Object.runContentWithLocalBindings (/home/michael-heuberger/Development/something/node_modules/jest-cli/src/lib/utils.js:394:17)
``
I am not repeating the same mistake as above. Must be something else, no idea.

**Comment by taion** [comment]
Just don't mock it. Jest is probably choking on how we have an object named `all`.

**Comment by binarykitchen** [comment]
what shouldn't i mock then? it is not very clear.

something like that? `jest.dontMock('react-bootstrap').Tabs` or it is `jest.dontMock('react-bootstrap').Nav`?

any chance that `all` object can be renamed for the sake of test-ability?

**Comment by taion** [comment]
We're not renaming `all`. I don't know Jest well enough to tell you what to `dontMock`.

**Comment by binarykitchen** [comment]
that's a problem then :(

how are you unit-testing your components at all?

**Comment by taion** [comment]
We use Karma and Mocha. You don't need to mock things just to test them, though.

**Comment by binarykitchen** [comment]
why did you opt for mocha n karma instead of jest if i may ask?

**Comment by taion** [comment]
I don't know. I didn't set up the test suite here.

**Comment by binarykitchen** [comment]
who did?

**Comment by taion** [comment]
I'm not sure.

For what it's worth, the vast majority of community packages in the React ecosystem use Karma and Mocha. Compare e.g. React Router, Redux, &c.

At this point I'm not sure there's anything more to discuss here. You should be able to solve your use case with the appropriate set of tools for not mocking React-Bootstrap components.

**Comment by binarykitchen** [comment]
Alright. I guess I have issues here when mocking react boostrap components. Will ask on Jest how to do this.

**Comment by GregoryPotdevin** [comment]
Not sure it's just a problem with testing, I ran into this in a normal page after installing react-overlays. I solved it by manually installing react-prop-types.
Seems like the latest versions don't use the same version :
- react-bootstrap : ```"react-prop-types": "^0.3.0",```
- react-overlays: ```"react-prop-types": "^0.2.1",```

**Comment by taion** [comment]
Those are subdependencies, npm should be able to deal with then just fine.

**Comment by hgezim** [comment]
Thanks, @GregoryPotdevin, that worked for me.

**Comment by hgezim** [comment]
@taion Using npm3, I've disabled all mocking done by jest (using `jest.autoMockOff()`) for a specific test and I still get this:

```
/home/ubuntu/frontend/src/javascript/components/MyComponent/__tests__/MyComponentListItem-test.js: /home/ubuntu/frontend/src/javascript/components/MyComponent/MyComponentListItem.jsx: /home/ubuntu/frontend/node_modules/react-bootstrap/lib/index.js: /home/ubuntu/frontend/node_modules/react-bootstrap/lib/ButtonGroup.js: Invalid argument must be an array
```

The dependency chain looks fine:

```
...
├─┬ react-bootstrap@0.27.3
│ ├─┬ babel-runtime@5.8.29
│ │ └── core-js@1.2.6
│ ├── dom-helpers@2.4.0
│ ├── keycode@2.1.0
│ ├── lodash-compat@3.10.1
│ ├─┬ react-overlays@0.5.1
│ │ └── react-prop-types@0.2.2
│ ├─┬ react-prop-types@0.3.0
│ │ └─┬ warning@2.1.0
│ │   └─┬ loose-envify@1.1.0
│ │     └── js-tokens@1.0.2
│ ├─┬ uncontrollable@3.1.3
...
```

I'm not sure how ButtonGroup ends up using `react-prop-types` from `react-overlays`. :/

Any help is appreciated.

**Comment by hgezim** [comment]
Alright, figured it out. This is possibly being caused by npm. You see, npm, for some reason is installing 0.3.x of `react-prop-types` in the top-most `node_modules` and not the one for `react-bootstrap`:

$ find . -name 'react-prop-types'
./node_modules/react-overlays/node_modules/react-prop-types
./node_modules/react-prop-types
$ grep 'react-prop-types' package.json # I swear I don't have this as a dependency, here's proof:
$

**Comment by taion** [comment]
Is this just Jest/npm3 incompatibility? It's possible Jest just doesn't work with npm3.

**Comment by hgezim** [comment]
@taion Moving `react-prop-types` fixes the issue:

```bash
$ mv node_modules/react-prop-types node_modules/react-bootstrap/node_modules/
```
