### ISSUE TITLE
Shrinkwrap -  extraneous: history@1.12.6 d:\work\ngen_screen_designer\node_modules\react-bootstrap\node_modules\history

### ISSUE THREAD

**Issue by deser** [react-bootstrap/react-bootstrap#1478]
When I'm trying to run npm shrinkwrap it blames react-bootstrap with error: " extraneous: history@1.12.6 d:\work\ngen_screen_designer\node_modules\react-bootstrap\node_modules\history"

**Comment by jquense** [comment]
https://github.com/react-bootstrap/react-bootstrap/issues/1395
