### ISSUE TITLE
Support for CSS namespacing / prefixing inside the JS components

### ISSUE THREAD

**Issue by cosminnicula** [react-bootstrap/react-bootstrap#1482]
Namespacing / prefixing Bootstrap's CSS classes could be theoretically achieved by using a PostCSS plugin - see https://github.com/twbs/bootstrap/issues/17474

However, the React Bootstrap components hardcode the CSS class names inside the JS code - for example the `ButtonGroup` component hardcodes the following CSS class names: `btn-group`, `btn-group-vertical`, `btn-group-justified` etc. -> https://goo.gl/rnMoZO

Are there any plans to support some sort of namespacing / prefixing variable that could be configured by the consumer of this library?

**Comment by jquense** [comment]
https://github.com/react-bootstrap/react-bootstrap/pull/1465 this PR makes use of bsclass consistent across components so you can change it to prefix the classes

**Comment by taion** [comment]
Yup this is being covered by #1465.

**Comment by cosminnicula** [comment]
Great @jquense! Does this means that components like `ButtonGroup` and others needs to be refactored in order to make use of bsclass?

**Comment by jquense** [comment]
no all these components have always used `bsClass` but changing that prop by the user didn't always affect every class using it, now it does.

**Comment by cosminnicula** [comment]
This means that because components like `ButtonGroup` are hardcoding CSS classes like `btn-group`, `btn-group-vertical`, `btn-group-justified` etc., at least at this point, `React Bootstrap` is not offering support for CSS namespacing / prefixing for all its JS components. Or am I missing something?

**Comment by jquense** [comment]
You are missing something: the classes are __not__ hardcoded, they are prefixed from `bsClass`, so by default ButtonGroup's `bsClass='btn-group'`, if you, the user change it to `'my-btn-group'` then all the classes will be prefixed with that. You can read through the linked PR to see the details

**Comment by cosminnicula** [comment]
Just a short correction in your comment: ButtonGroup's default `bsClass` is `button-group` and not `btn-group`.

Now, here are the steps to reproduce the problem:

- Go to https://react-bootstrap.github.io/components.html#btn-groups-single
- inspect the generated HTML
```
<div class="btn-group" data-reactid=".22vvftuxiww.1.0.2.0.0.1.4.0.0.0">
   <button type="button" class="btn btn-default" data-reactid=".22vvftuxiww.1.0.2.0.0.1.4.0.0.0.0">Left</button>
   <button type="button" class="btn btn-default" data-reactid=".22vvftuxiww.1.0.2.0.0.1.4.0.0.0.1">Middle</button>
   <button type="button" class="btn btn-default" data-reactid=".22vvftuxiww.1.0.2.0.0.1.4.0.0.0.2">Right</button>
</div>
```
- modify, just for testing purposes, inside `src/ButtonGroup.js` the `bsClass` variable from `button-group` into `my-button-group`
- refresh the documentation page -> there is no `my-button-group` prefix anywhere. In fact the `button-group` prefix wasn't present in the original generated HTML (before changing the `bsClass` variable)

**Comment by taion** [comment]
Take a look at the code from the PR - there were some relevant cleanups there.

**Comment by jquense** [comment]
yes as I said we _changed_ the behavior in the PR which has not been released yet. please read that.

**Comment by cosminnicula** [comment]
Ok..."not released yet" changes a bit the things. It's not super easy to spot that the PR was merged inside the v0.28-rc branch :( :100:

**Comment by cosminnicula** [comment]
Anyways, thanks for the clarification.

**Comment by jquense** [comment]
no problem!

**Comment by cosminnicula** [comment]
So, I've switched to the v0.28-rc branch and modified the `bsClass` default property for `ButtonGroup.js` like this:

```
getDefaultProps() {
    return {
      block: false,
      justified: false,
      vertical: false,
      bsClass: 'my'
    };
  }
```

This change has no effect on the generated div CSS class prefix which remains `btn-group-`.

I guess this is not the expected behavior?

**Comment by cosminnicula** [comment]
Ok, for those interested to see how to work with the CSS prefixing stuff, here's the thing: you can write something like `<ButtonGroup bsClass={`my-${ButtonGroup.defaultProps.bsClass}`} />` to achieve prefixing. You could further wrap this inside a `MyButtonGroup` component. However, there's no way that you could specify a global CSS prefix for all the components, since this would increase the complexity of the code inside the library.

**Comment by sag1v** [comment]
shame that there is no way to globally prefix all classes (to avoid conflicts with other libraries for example).
