### ISSUE TITLE
Can't set fontWeight of MenuItem

### ISSUE THREAD

**Issue by chung-leong** [react-bootstrap/react-bootstrap#1484]
A rule in the CSS set the font weight of the A tag to 'normal'. Since the style object passed to MenuItem is only applied to the LI tag, the text ends up being normal. The same rule sets the color too. Would be nice if these two actually have the intended effects.

**Comment by taion** [comment]
Can't you just use a descendent selector?

**Comment by legomind** [comment]
You are assuming that everyone is using global CSS.

What about those of us who are using inline styles like facebook recommends? 
https://facebook.github.io/react/tips/inline-styles.html

**Comment by taion** [comment]
Where in that link do you see that style being recommended? You're already using global CSS via Bootstrap.
