### ISSUE TITLE
Outer Nav shouldn't have a default role

### ISSUE THREAD

**Issue by ndarilek** [react-bootstrap/react-bootstrap#1489]
As a screen reader user, I find the default rendering of your `<Navbar/>` component slightly confusing. NVDA appears to announce the nav component twice. When I arrow into a navbar, I hear "Navigation landmark navigation landmark." This is a bit confusing and redundant. :)

Looking at the markup, I see:

`<nav role="navigation">`

This is unnecessary. Using the `<nav>` tag is effectively specifying a region with the navigation role already. See, for instance, this markup from Bootstrap's docs:

```
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
```

For this component, I'd recommend not assigning a default role, particularly as you're already using the correct element that provides identical information to ARIA. Anyone needing to set a different component and default role already has a means of doing so.

BTW, kudos for building in all this accessible markup out of the box. As a blind web developer, my choice is usually between rolling my own HTML by hand, or pushing for major a11y refactorings in any toolkits that don't work. It's refreshing to only have to file an issue about an obscure ARIA presentation issue where you obviously tried to do the right thing but didn't realize that it'd get presented oddly, and even then the presentation is just excessive and not inaccessible. :) Thanks a bunch for doing the right thing.

**Comment by jquense** [comment]
thanks for the issue,

It looks like our issue is that the `<nav>` tag is actually configurable for the Component, so the default role is there to ensure that if the User uses a `<div>` it will still get the right role. That being said we should just not add it if the component is the default `<nav>`, thanks for the heads up

Also it is great to hear that our efforts are helpful! We try the best we can, please feel free to pint out anything else that isn't great or just missing.

**Comment by ndarilek** [comment]
Right, I get why you're doing it. I don't know that I'd necessarily add 
a check for `<nav/>` when setting the role. I feel like if someone goes 
out of their way to change the element to a `<div/>`, then the resulting 
access issues are on them and not you. :) As such, it's their 
responsibility to set a correct role.

That said, if you *want* to add such a check then I won't oppose it, I 
just worry about it increasing code complexity.
