### ISSUE TITLE
possible to override Dropdown toggle onClick behavior

### ISSUE THREAD

**Issue by perrydt** [react-bootstrap/react-bootstrap#1490]
Is there a way to override the onClick behavior in Dropdown if you are using fully custom toggle and menu?

The use case here is that I am using an input as the bsRole='toggle' and a custom Dropdown.Menu as a 'search term completion' similar to what search engines do.  I want to keep all the behavior in the Dropdown component, keyboard handling, etc, but do not want the onClick handler to ever close the dropdown. 

Unfortunately Dropdown installs its own click handler after the Input (toggle)'s click handler, and event.preventDefault/stopPropagation don't work.    I already have a custom open prop and onToggle, but onToggle can't intervene because it contains no information about which event triggered the toggle, and we want to keep all non-click behavior (ESC key, onBlur, etc).    Other than copying all the behavior into a custom component I don't see a way to do this unless I'm missing something?

**Comment by taion** [comment]
IMO the right fix would be for `Dropdown.handleClick` and others to check for the event having its default prevented. Care to PR this?

**Comment by jquense** [comment]
would it make more sense to just wrap the input and not do anything with the injected onClick?

**Comment by taion** [comment]
Ah, that would be easier :p

**Comment by perrydt** [comment]
Aha, I tried various ways to intercept the onClick handler, but didn't think of using a wrapper for the Input itself -- it works perfectly.  Thanks for the suggestion @jquense! This is what I ended up using:

```javaScript
class InputWrapper extends Component {
  constructor(props) {
    super(props)
    this.handleClick = this.handleClick.bind(this)
    this.wrappedClick = this.props.onClick
  }

  render() {
    let otherProps = _.omit(this.props, ['onClick', 'bsRole'])
    return (
      <Input onClick={this.handleClick} {...otherProps} />
    )
  }

  handleClick(evt) {
    // Prevent the root click handler from closing the dropdown
    evt.nativeEvent.stopImmediatePropagation()
    // Note have to handle anything that needs to happen on "click when closed" in here,
    // not in the wrapped handler.
    if (!this.props.open) {
      this.wrappedClick(evt)
    }
  }
}
```
The issue with stopping propagation is that Drodown hooks into the onClick by replacing it with a chained function that just calls the original handler and then immediately calls its handler; I'm not sure how one would replace that with something that could check that the event was stopped.  I'm still not fully used to React yet -- I think I was tackling the problem from the wrong direction :)

**Comment by jquense** [comment]
if you want to kill the close on Click behavior you might want to just create a custom sort of dropdown menu that doesn't do that. but I think we probably should just expose that option so there isn't a lot of rewriting...

**Comment by perrydt** [comment]
I almost went to the point where I wrote a custom dropdown with styles copied from Bootstrap -- if I'd needed to customize anything else I probably would have, but I didn't want to have to reproduce all the existing component's handling for keyboard and onBlur, since it was invoking a lot of internal utility code in react-bootstrap for this.

I agree that this is a pretty edge case though -- I'll leave it open as an enhancement but feel free to close if it's a bit too niche.

**Comment by bcm** [comment]
I disagree that this is an edge case. I commonly use a dropdown to allow a user to select multiple filters for a large data set. it's very frustrating in this instance to have the dropdown close after every selection.

> IMO the right fix would be for Dropdown.handleClick and others to check for the event having its default prevented. Care to PR this?

this would be fine, but a prop that takes care of business without having to explicitly prevent default on the event would be even better imo.

**Comment by arackaf** [comment]
For those arriving here from Google, who want to keep a dropdown navbar item open under certain circumstances, here's the most straightforward way I've been able to find

```javascript
dropdownToggle(newValue){
    if (this._forceOpen){
        this.setState({ menuOpen: true });
        this._forceOpen = false;
    } else {
        this.setState({ menuOpen: newValue });
    }
}
menuItemClickedThatShouldntCloseDropdown(){
    this._forceOpen = true;
}
```

and related jsx.

```javascript
<NavDropdown open={this.state.menuOpen} onToggle={val => this.dropdownToggle(val)} title={selectedSubjectsHeader} id="sel-subjects-dropdown">
    { this.props.selectedSubjects.filter(s => s).map(s =>
        <MenuItem onClick={() => this.menuItemClickedThatShouldntCloseDropdown()} href={undefined} className="default-cursor no-hover" key={s._id}>
            <span className="label label-info"><span style={{ cursor: 'pointer' }}>X</span><span style={{ marginLeft: 5, paddingLeft: 5, borderLeft: '1px solid white' }}>{s.name}</span></span>
        </MenuItem>)
    }
</NavDropdown>
```

Note the `NavDropdown`'s open binding, the `MenuItem`'s `onClick` binding, the `NavDropdown`'s `onToggle` binding.

**Comment by geminiyellow** [comment]
need more official implement

**Comment by taion** [comment]
@jquense I'm thinking the best solution here is for the user to control `open` on the `<Dropdown>`, and only close the dropdown in `onClose`. Do you think we need first-class support for this inside the library? Not sure what I'd even call a prop to control this.

**Comment by taion** [comment]
And if we do that, then we should close https://github.com/react-bootstrap/react-bootstrap/issues/1894, though possibly rename `onClose` to `onHide` or `onRequestFoo`.

**Comment by jquense** [comment]
that gets ugly...seems like it's better to pass through a `source` argument to onToggle that tells you what triggered it.

**Comment by taion** [comment]
Does that work with uncontrollable?

**Comment by jquense** [comment]
sure, it doesn't care what else you pass it, it just passes it all through

if we want to make it one argument that's easy enoguh to change as well...I'm gonna do something along these lines in react-widgets for a similar situation

**Comment by madhums** [comment]
This would be quite useful. Solution provided by @arackaf works quite well. Still would be nice to support this feature without all the code.

**Comment by arvera** [comment]
Am I missing something I still get a this.state = null and nothing render (I am still junior to all of this)

**Comment by rringler** [comment]
I'm also having trouble with @arackaf solution.

If I click on the element that implements the `onClick={() => this.menuItemClickedThatShouldntCloseDropdown()}` attribute, everything works as planned, but if I click on any of its children, it seems the `dropdownToggle` function is called before the `menuItemClickedThatShouldntCloseDropdown` function.

My component:
```jsx
export default class LoginDropdown extends Component {
  constructor(props) {
    super(props);

    this.state = {
      email:      '',
      password:   '',

      _menuOpen:  false,
      _forceOpen: false,
    };
  }

  dropdownToggle = (newValue) => {
    if (this.state._forceOpen){
      this.setState({ _menuOpen: true, _forceOpen: false });
    } else {
      this.setState({ _menuOpen: newValue });
    }
  }

  dropdownOpen = () => {
    this.setState({ _forceOpen: true });
  }

  render() {
    return (
      <NavDropdown eventKey={2}
                   open={this.state._menuOpen}
                   onToggle={(val) => this.dropdownToggle(val)} >
        <Navbar.Form pullRight
                     onClick={this.dropdownOpen}
                     onSubmit={this.onFormSubmit} >
          <FormGroup>
            <FormControl type="text"
                         placeholder="email"
                         value={this.props.email}
                         onChange={this.onEmailChange} />
          </FormGroup>
          <FormGroup>
            <FormControl type="password"
                         placeholder="password"
                         value={this.props.password}
                         onChange={this.onPasswordChange} />
          </FormGroup>
          <Button bsStyle="primary"
                  type="submit" >
            Submit
          </Button>
        </Navbar.Form>
      </NavDropdown>
    );
  }
}
```

**Comment by arackaf** [comment]
@rringler No idea why your code's not working, but, I do have my own port of the JavaScript-based bootstrap components

https://www.npmjs.com/package/simple-react-bootstrap

The ButtonDropdown has a `ignoreContentClick` property to achieve what the original thread was about, and the NavBar component, which seems to be what you're using above, exposes (though it's not yet documented) `close` and `expand` methods (so you'll need to grab the component with a ref)

**Comment by joelseq** [comment]
@rringler currently working on passing in the event (eg. 'open' or 'close') as well as the source that fired that event over at #2422. Just waiting on [react-bootstrap/react-overlays#142](https://github.com/react-bootstrap/react-overlays/pull/142) to be merged so I can make the required change. But after the PR gets merged it should be very easy to implement the desired behavior (not having the dropdown close when selecting an item in it) by using some basic component level state.

**Comment by bigearsenal** [comment]
This code works for me
`<NavDropdown eventKey={3} onSelect={(e) => {e.stopPropagation();}} >`

**Comment by seyyedmojtaba72** [comment]
$("[data-toggle=dropdown]").prop('onclick', null).off('click');
    $("[data-toggle=dropdown]").click(function (e) {
        e.preventDefault();
        e.stopPropagation();

        let el = $(this);
        let expanded = el.attr("aria-expanded") || false;
        if (!expanded) {
            $(this).dropdown('toggle');
        }

        el.attr("aria-expanded", !expanded);
    })

**Comment by srianbury** [comment]
I'm confused on how to stop the dropdown from closing with `rootCloseEvent`.  Does anyone have an example?

**Comment by srianbury** [comment]
does anyone have an example of using rootCloseEvent to prevent the a custom dropdown from closing when an option is clicked?

**Comment by srianbury** [comment]
I found a solution to keep the dropdown open but it doesn't involve rootCloseEvent which makes me think there is a better way to write this but here it my current solution:

```
const DropdownExample = () => {
  const handleToggle = (isOpen, event, metadata)=> {
    if(isOpen || metadata.source!=='select'){
      setShow(isOpen);
    } 
    event.persist();
  }

  const [show, setShow] = useState(false);
  return(
    <Dropdown
      show={show}
      onToggle={handleToggle} 
      title="Dropdown">
      <Dropdown.Toggle>Title</Dropdown.Toggle>
      <Dropdown.Menu>
        <Dropdown.Item
          eventKey="2">
          Action 2
        </Dropdown.Item>
      </Dropdown.Menu>
    </Dropdown>
  );
}
```

**Comment by carloseustaquio** [comment]
Hey guys!

I've just found another solution for doing this... I was trying to place some Checkboxes inside a  Material UI Select. I achieve this by placing the checkboxes within a 'multiple' Select with no value (empty array). Then, I handle the checkboxes inputs separately, in my case, using Formik.
Here's the code:
`
<Select
                    multiple
                    id="documento"
                    name="documento"
                    className="blue-select"
                    value={[]}
                    MenuProps={{ className: 'document-type' }}
                    >
                      {docTypes.map( e => 
                        <div>
                          <label htmlFor="documento">Documento {e.id}</label>
                          <Checkbox
                          type='checkbox' 
                          name="documento"
                          value={e.id}
                          checked={values.documento.indexOf(e.id) > -1}
                          onChange={handleChange}
                          color="default"
                          classes={{ root: 'drop-checkbox' }}
                          />
                        </div>
                      )}
                    </Select>

`

**Comment by SalimSalici** [comment]
Following @srianbury's solution, I made a short and easily reusable wrapper component that displays the dropdown with the desired behaviour.

Component definition:
```js
const DropdownPersist = (props) => {
  const [open, setOpen] = useState(false);
  const onToggle = (isOpen, ev, metadata) => {
    if (metadata.source === "select") {
      setOpen(true);
      return;
    }
    setOpen(isOpen);
  };
  return <Dropdown show={open} onToggle={onToggle} {...props}></Dropdown>;
};
```

Usage:
```js
<DropdownPersist title="Dropdown">
  <Dropdown.Toggle>Title</Dropdown.Toggle>
  <Dropdown.Menu>
    <Dropdown.Item eventKey="1">Action 1</Dropdown.Item>
    <Dropdown.Item eventKey="2">Action 2</Dropdown.Item>
    <Dropdown.Item eventKey="3">Action 3</Dropdown.Item>
    <Dropdown.Item eventKey="4">Action 4</Dropdown.Item>
  </Dropdown.Menu>
</DropdownPersist>
```
