### ISSUE TITLE
Grid content does not line up with non-grid content

### ISSUE THREAD

**Issue by fwevans** [react-bootstrap/react-bootstrap#1491]
I am expecting grid content to line up with non-grid content per bootstrap's design but having trouble.
"The negative margin is why the examples below are outdented. It's so that content within grid columns is lined up with non-grid content." (http://getbootstrap.com/css/#grid)
See react-bootstrap grid: https://react-bootstrap.github.io/components.html#grids

Was this overlooked or am I missing something?

**Comment by taion** [comment]
This is a CSS question but you're misinterpreting that. It's saying that

```js
<Grid>
  <Row>
    <Col xs={12}>
      Foo
    </Col>
  </Row>
</Grid>
```

should look the same as


```js
<Grid>
  Foo
</Grid>
```
