### ISSUE TITLE
DropdownButton applies classname to both button group and button

### ISSUE THREAD

**Issue by nedharrison** [react-bootstrap/react-bootstrap#1497]
I am using the Dropdown component, however I noticed an odd behaviour at the HTML output level. 

I have a set of 4 buttons, with second one being a Dropdown component. I'm also using ionicons via css style sheet to place an icon to the left of the button name. Normal buttons appear fine, however the Dropdown inserts 2 icons. (see image below)

![image](https://cloud.githubusercontent.com/assets/11803070/11168392/6aa77812-8be1-11e5-8082-fcde95b9b47c.png)

Inspecting the HTML output via the inspector, it appears the initial Dropdown component className I've set is applied twice, one for the encapsulating DIV and one for the BUTTON that follows (encircled in red). Clearly that's not my desired effect I was after. When removing the style inline via inspector from the DIV element while leaving the style for the BUTTON, the final effect is exactly how I'd want it. (see image below) 

![image](https://cloud.githubusercontent.com/assets/11803070/11168408/f7e272fe-8be1-11e5-8348-2c393b42f284.png)

Is this a bug? If so, can it be squashed please?

**Comment by taion** [comment]
Hard to say - @mtscout6 / @jquense? Should `DropdownButton` only apply `className` to one of those? I guess the problem then is, if we do that - which one?

**Comment by jquense** [comment]
I think the current behavior is unintentional, dropdown button omits the dropdown props before passing them to the toggle, but className is not in propTypes so it's missed

**Comment by taion** [comment]
So you think it should apply `className` to the wrapper rather than the toggle?

**Comment by taion** [comment]
I guess - do we want a separate `toggleClassName` then?

**Comment by jquense** [comment]
I think it should be applied to the toggle if anything....maybe just use dropdown if you need finer control?

**Comment by taion** [comment]
I think it makes sense to just forward `className` to the toggle. What about for e.g. `SplitButton` though? Ick.
