### ISSUE TITLE
MenuItem eventKey propType

### ISSUE THREAD

**Issue by Haemoglobin** [react-bootstrap/react-bootstrap#1498]
Hi there - is there a reason for the propType restriction on eventKey of MenuItem? 

 eventKey: React.PropTypes.oneOfType([
    React.PropTypes.number,
    React.PropTypes.string
  ]), 

I am wanting to set it to a boolean (eventKey={true}), but also what would be wrong with an object also? 

Thanks

**Comment by taion** [comment]
It's for consistency with `eventKey` on `NavItem`.

**Comment by Haemoglobin** [comment]
eventKey on NavItem is defined as eventKey: React.PropTypes.any which is correct. MenuItem should be made the same.

**Comment by taion** [comment]
I see. Go ahead and PR a fix then.

**Comment by Haemoglobin** [comment]
No problem - PR open at https://github.com/react-bootstrap/react-bootstrap/pull/1500
