### ISSUE TITLE
Generate AMD + CJS index automatically during build

### ISSUE THREAD

**Issue by stevoland** [react-bootstrap/react-bootstrap#15]
Replace these with one generated automatically: 

https://github.com/stevoland/react-bootstrap/blob/master/tools/amd/index.js
https://github.com/stevoland/react-bootstrap/blob/master/tools/cjs/main.js

**Comment by hipertracker** [comment]
The AMD code does not, and  it cannot work. The browser is assuming absolute paths for require() command.

**Comment by mtscout6** [comment]
Resolved with #326

**Comment by mtscout6** [comment]
Improved in #449
