### ISSUE TITLE
DropdownButton retaining active state after menu item selection

### ISSUE THREAD

**Issue by Haemoglobin** [react-bootstrap/react-bootstrap#1502]
Hi - it seems that the dropdown button stays in an active state after a selection has been made from one of it's child menu items. With the colour scheme in the examples it's hard to see, however it becomes more noticeable with other colour schemes.  

To see what I mean, choose at item from the "default" dropdown (https://react-bootstrap.github.io/components.html#btn-dropdowns) and you will see it remains darker than it did before the selection was made (as it's in active state). In the standard bootstrap examples however you will see that this doesn't happen: http://getbootstrap.com/components/#btn-dropdowns and goes back to its normal background after an item is selected.

**Comment by taion** [comment]
The authoring practices only say that we have to focus the parent dropdown button when the user hits escape. Still - where would we put focus if not on the parent button? I don't think upstream TWBS behavior here makes sense. e.g. the example they have does return focus to the parent menu button.

I think our behavior is more correct than the upstream one from an a11y PoV.

**Comment by jquense** [comment]
yeah, otherwise the focus drops from the document completely which is like a cardinal sin against a11y
