### ISSUE TITLE
<Button type="submit"> inside a form causes whole page refresh when pressing "enter" key

### ISSUE THREAD

**Issue by codecvlt** [react-bootstrap/react-bootstrap#1510]
The documentation example also has this issue.

**Comment by taion** [comment]
You need to handle the form submission yourself. This is not an R-B bug - it's just how building forms with SPAs works.

**Comment by jquense** [comment]
dang beat me too it...maybe we are to active on github :P

**Comment by codecvlt** [comment]
Any suggestions? I'm trying to avoid having to add in any global keyboard event listeners. I'm assuming the <form> tag itself is causing this page refresh. Is there something akin to event.preventDefault from within the form's onSubmit property?

You guys are fast!

**Comment by taion** [comment]
`preventDefault` on the button's `onClick` or the form's `onSubmit`.

**Comment by codecvlt** [comment]
It doesn't seem like the form onSubmit function is ever invoked. I finally solved it with this solution:

componentDidMount() {
   this.refs.form.onsubmit = () => this.login();
}

login() {
  // regular login stuff
  ....

  return false;  // cancels the page refresh
}

**Comment by codecvlt** [comment]
Thanks for the help! Also, I'm really loving react-bootstrap so far. It's definitely a huge help for building nice UI's :+1:

**Comment by Warkst** [comment]
If you keep the button but remove `type='Submit'`, the behavior is also avoided (onSubmit is never called). You can define your behavior by registering an `onClick` handler.

**Comment by charan5181** [comment]
Use e.preventDefault event(e) in your onSubmit function.

**Comment by VenkateshSomu** [comment]
You need to use the event.preventDefault() function to stop the page refresh. an example is like this

handleSubmit(event){
   event.preventDefault();
  alert('form submitted'); // your function here
}

<form onSubmit={(event)=> this.handleSubmit(event)}>
    <button type="submit">Submit</button>
</form>

**Comment by erperejildo** [comment]
didn't work for me

**Comment by anjuSindhu** [comment]
return false; worked for me.

**Comment by songthamtung** [comment]
I was getting e is undefined.

`onClick={e => {e.preventDefault(); this.handleSubmit()}}`

worked for me

**Comment by rogong** [comment]
using typescript 
 const handleSubmit = (event:any) => {
    event.preventDefault();
  }

<form onSubmit={handleSubmit}>

**Comment by solutions4theweb** [comment]
> using typescript
> const handleSubmit = (event:any) => {
> event.preventDefault();
> }

If you wanted full typing you could use:

```
onClick={(event: React.MouseEvent<HTMLButtonElement, MouseEvent>) =>
   event.preventDefault()
}
```

**Comment by IwonaGorska** [comment]
Yes, sure, we can prevent default behavior but then the form validation is not working at all. I can't believe there is no way to create a normal, standard, proper form in such framework :/

**Comment by jquense** [comment]
@IwonaGorska there is you are doing something wrong or misunderstand how "normal, standard, proper" forms work in HTML. The form reloading the page is normal, and standard behavior.
