### ISSUE TITLE
Accordion should be able to open/close on entire header click, not just the link

### ISSUE THREAD

**Issue by hughlomas** [react-bootstrap/react-bootstrap#1512]
Maybe it needs to be an option, but the accordion should allow the entire area to be clickable, not just the link.

**Comment by taion** [comment]
Our implementation exactly follows the Accordion upstream: http://getbootstrap.com/javascript/#collapse-example-accordion

If you need something else, I believe you have all the tools needed right now to wire it up yourself.

**Comment by hughlomas** [comment]
Ok, thank you.

Just for reference to anyone else:

There isn't an obvious way to programmatically open and close the accordion based on clicks to the header, but I found that CSS is sufficient make the <a> element take up the space of the header, which worked as a solution.

**Comment by 6ewis** [comment]
@hughlomas @taion I agree one hundred percent it should be at the very least an option. I fail to understand the point of using react components if we can't customize it easily.

**Comment by jquense** [comment]
@6ewis if you feel so strongly about it feel free to jump in and PR something solving: #983
