### ISSUE TITLE
`rootClose` prop on Overlay component doesn't work and throws error

### ISSUE THREAD

**Issue by benkeen** [react-bootstrap/react-bootstrap#1513]
When using the rootClose = true prop:  `<Overlay ... rootClose={true}>...</Overlay>`

It throws the following warning on page load:
`Warning: Failed propType: Required prop `onRootClose` was not specified in `RootCloseWrapper`. Check the render method of `Overlay`.`

and fails to work when clicking the page to close it. That fires the following error: `Uncaught TypeError: this.props.onRootClose is not a function`

This prop works fine with `<OverlayTrigger />`

**Comment by jquense** [comment]
You need to provide an `onHide` prop when using the rootClose option per the the docs: http://react-bootstrap.github.io/components.html#custom-overlays-props

**Comment by benkeen** [comment]
Apologies! You're absolutely right. Closing.

**Comment by benkeen** [comment]
Apologies! You're absolutely right. Closing.

**Comment by benkeen** [comment]
Apologies! You're absolutely right - thanks! Closing.

**Comment by bryan-foong** [comment]
What should I have within onHide props? <Overlay onHide rootClose={true}>...</Overlay> This doesn't work for me

**Comment by bryan-foong** [comment]
Ok I found out I just need to set the state to false within the onHide props
