### ISSUE TITLE
Modal throws an exception

### ISSUE THREAD

**Issue by IndexOf** [react-bootstrap/react-bootstrap#1514]
In the case when animation is not finished and component is already removed.
If animation property is true.
Modal throws an exception at this line https://github.com/react-bootstrap/react-bootstrap/blob/v0.26.4/src/Modal.js#L424.
And '.modal-open' className doesn't removes from body, which leads to the lack of scrolling on the page

**Comment by IndexOf** [comment]
As example we use react router. And when users click to the link or button in modal, we call transition to another page.
And

**Comment by jquense** [comment]
hi there, this is fixed in the in react-overlays, so if you upgrade to 0.28 you will get the fix.

thanks
