### ISSUE TITLE
Tooltip positioning problem

### ISSUE THREAD

**Issue by jareware** [react-bootstrap/react-bootstrap#1515]
I have two Button instances that both have Tooltips. The first one is positioned relatively, and works fine:

<img width="187" alt="screen shot 2015-11-18 at 17 39 53" src="https://cloud.githubusercontent.com/assets/560055/11245671/806c40aa-8e1c-11e5-9e76-50df68d1ce9e.png">

The 2nd one is consistently rendered off across all browsers, and I just upgraded from 0.26.4 to 0.28.1 and the issue persisted identically:

<img width="94" alt="screen shot 2015-11-18 at 17 43 22" src="https://cloud.githubusercontent.com/assets/560055/11245695/a9c2c3b6-8e1c-11e5-99d1-ddb455cd6283.png">

The funkiest thing is that this 2nd Button is `position: absolute; right: 100px;`, but if I switch it to `position: absolute; left: 100px;` the Tooltip appears in the correct position.

Any ideas as to what might be causing this?

Thanks for your great work with the lib!

**Comment by taion** [comment]
The code handling this is probably here: https://github.com/react-bootstrap/react-overlays/blob/master/src/utils/overlayPositionUtils.js. Might be useful to drop a few breakpoints and see how it's getting confused.

**Comment by taion** [comment]
Any luck?

**Comment by jareware** [comment]
I'm really sorry, haven't had time to look into this more, too many other fires to put out first.

**Comment by thetimbanks** [comment]
@jareware Are the button in different containers? I am experiencing some positioning issues on tooltip with the anchor is in an element that is 100% of the body. I plan on digging into the positioning to see if I can resolve our issue which may take care of yours.

**Comment by jareware** [comment]
@thetimbanks they definitely are in different containers.

Another interesting observation: if I unplug the external mouse from my MBP (and thus OS X hides scroll bars), **the issue goes away**. This has got to be related to the `position: absolute; right: 0;` styles I have.

**Comment by jareware** [comment]
Ha, figured it out after adding a few breakpoints:

![licecap](https://cloud.githubusercontent.com/assets/560055/11607363/3ccd19c2-9b4c-11e5-8df8-fc0530621454.gif)

The issue is that while the positions are being calculated, the tooltip element is already appended to `<body>`. Since it doesn't have `overflow: hidden`, it'll pop out the scrollbars, which are taken into account in the position calculations. Once the calculations are done, the tooltip is positioned absolutely (so it doesn't contribute any height to the body), and the scrollbars disappear.

To reproduce:

1. Use `<body>` as the container (default)
1. Make sure the OS displays scroll bars (e.g. an external mouse on OS X)
1. Position the target relative to the **right edge** of the viewport

So it's a bit of an edge case, but also seems like simply having `top: 0; left: 0;` in the `.tooltip` default styles fixes this (as then the tooltip is never laid out relatively).

What do you think @taion?

**Comment by taion** [comment]
Fixed in https://github.com/react-bootstrap/react-overlays/pull/22. Just need a new release there whenever.

**Comment by jareware** [comment]
Awesome! :bow:

**Comment by jquense** [comment]
Does that change really not break tooltips? It seems like suddenly top/left set all the time (vs null which doesn't get flushed to the node) would introduce different behavior...

**Comment by taion** [comment]
Huh, let me check real quick.

**Comment by taion** [comment]
@jquense As far as I can tell, it doesn't break anything against either the react-overlays or the React-Bootstrap examples. Err, at least on Chrome on OS X. And everyone knows that's the only web browser that matters :p

**Comment by jareware** [comment]
@jquense do you have theories as to how that would break? I've tested this patch* on latest Chrome, Firefox and Safari, and IE10, and the positioning works like it should in all of them.

*) I've actually just added `.tooltip { top: 0; }` to my CSS until I can get this from a release, but the net result is the same.

**Comment by jquense** [comment]
I rember messing with it before and running into some issues with defaulting to 0, but I am be misremembering or the code is different enough that it's not relevant.

My only thought for why it might is that I know that `top: 0` and no `top` at all will have different  effects in situations (of which I am not quite sure of). In general though the implicit default of a missing top/left is not always 0, it seems to be the offset of the element if its inline (in some situations on some browsers). I can't think of why your want that behavior with the tooltip, but I didn't want to just assume it worked fine :).

**Comment by taion** [comment]
@jquense Should we back out https://github.com/react-bootstrap/react-overlays/pull/22, then, and just let this be handled in userspace?

**Comment by jareware** [comment]
@taion Please don't, I'm 100% sure this will hit (or has hit) others as well.

@jquense Think of it this way: Before the tooltip appears, it won't be part of the layout (because the element doesn't exist). After the tooltip has appeared, it won't be part of the layout (because it's positioned absolutely). What would be the case where you'd want it to be part of the layout while it's position is being calculated, but not before or after?

**Comment by jquense** [comment]
I just wanted to make sure that it didn't break something..in the case of Tooltips it shouldn't since they are hidden to begin as @jareware says, but Position is useful outside of tooltips...this probably counts as a breaking change.

Maybe it makes more sense to actually default the top/left values in the Tooltip/Popover components vs (seemingly the correct behavior for tooltips)? I don't mind this as a default but my only concern is its a bit more annoying to reset than the `null` default (not my much tho?)

**Comment by taion** [comment]
@jquense Agreed that it's a breaking change - just want to figure out what concrete problems might be, so we can work to mitigate those.
