### ISSUE TITLE
js code exposed in DOM on Overlay target attribute

### ISSUE THREAD

**Issue by lnmp4000** [react-bootstrap/react-bootstrap#1516]
When rendering an Overlay, the target attribute is present in the DOM, revealing a js function.

The following element is extracted from the Chrome inspector on the React-Bootstrap - custom overlay example.

```
<div style="...some styles" target="function () {
            return ReactDOM.findDOMNode(_this.refs.target);
          }" class="fade in" data-reactid=".o">
  <strong data-reactid=".o.0">Holy guacamole!</strong>
  <span data-reactid=".o.1"> Check this info.</span>
</div>
```

Note the target attribute.

On my project I have

```
<div 
  class=" attribute-tree-overlay" 
  target="function () { [native code] }" data-reactid=".9">
</div>
```

**Comment by taion** [comment]
@jquense Is the issue here that `target` is not valid on a `<div>`

**Comment by jquense** [comment]
ya, just a case of props that have the same name as html Attributes being inadvertently spread to the root DOM node :/
