### ISSUE TITLE
Question: how to set input's maxlength?

### ISSUE THREAD

**Issue by hugotox** [react-bootstrap/react-bootstrap#1517]
I tried `maxLength` and `maxlength` on a `Input` element but it is completely ignored

**Comment by joshhornby** [comment]
@hugotox Did you find the fix this for?

**Comment by M3lkior** [comment]
Same problem here, maxLength attribute not propaged

**Comment by kpott** [comment]
maxlength did not work for me but maxLength does

**Comment by SirLemuel** [comment]
He said that he tried it and neither work.

**Comment by vexilar** [comment]
Same here

**Comment by jecacs** [comment]
Same problem

**Comment by jquense** [comment]
`maxLength="200"` works fine, it needs to be a string not a number, again this is a React issue not a RB one

**Comment by hanquf1** [comment]
`maxLength` good godd thanks

**Comment by JohnnyBDude** [comment]
```
<FormControl
        type="text"
        maxLength={255}
/>
```

Works for me as well

**Comment by atruptoneatma** [comment]
maxLength will not work for type="number", it will work for other types

**Comment by hungdev** [comment]
> maxLength will not work for type="number", it will work for other types

yup, thanks. but how do i solve with case type number and maxlength?
@atruptoneatma

**Comment by aplomBomb** [comment]
> maxLength will not work for type="number", it will work for other types

Why did you put number in quotes? We're talking about numbers vs strings, that's very confusing lol

**Comment by atruptoneatma** [comment]
> > maxLength will not work for type="number", it will work for other types
> 
> Why did you put number in quotes? We're talking about numbers vs strings, that's very confusing lol
I am not able to find any alertnative for this 
<input type="number">
if do you have let me know

**Comment by atruptoneatma** [comment]
> > maxLength will not work for type="number", it will work for other types
> 
> Why did you put number in quotes? We're talking about numbers vs strings, that's very confusing lol

<input type="number">
see how input type will define.

**Comment by atruptoneatma** [comment]
> > maxLength will not work for type="number", it will work for other types
> 
> yup, thanks. but how do i solve with case type number and maxlength?
> @atruptoneatma

you need to take number value and onChange count it's length

**Comment by bhatvikrant** [comment]
> > > maxLength will not work for type="number", it will work for other types
> > 
> > 
> > yup, thanks. but how do i solve with case type number and maxlength?
> > @atruptoneatma
> 
> you need to take number value and onChange count it's length

can you please explain with code?

**Comment by jaccon** [comment]
maxLength="200" work fine with input type="text".

**Comment by ajdumanhug** [comment]
@jaccon try this.

```
<Field
  type="number"
  onInput = {(e) =>{
    e.target.value = Math.max(0, parseInt(e.target.value) ).toString().slice(0,16)
  }}
  className="textbox"
  name="cardNumber"
/>
```

**Comment by wadehammes** [comment]
@jaccon `type="number"` has a `max` attribute which you set to be the highest number you want to allow, with no need for an onChange handler.

**Comment by dvsmedeiros** [comment]
for `<input type="text" maxLength="10"/>` determine the maximum number of characters must be less than or equal 10
for `<input type="number" max="10 />` determines the maximum value that can be entered

**Comment by charanbanka** [comment]
<input type="number" id="phno" 
          onKeyPress={(e) => { formData.phno.length === 4 && e.preventDefault(); }} 
          onChange={handleChange} value={formData.phno} />

This is worked for me

**Comment by Krishna-android-web-dev** [comment]
<Form.Control
                          type="tel"
                          placeholder="Email"
                          aria-describedby="inputGroupPrepend"
                          required
                          // add pattern for phone number
                          pattern="[0-9]{10} 10"
                          // only 10 digit number
                          maxLength="10"
                        />

**Comment by MidnightJava** [comment]
Many solutions are suggested here, but none of them work for me, for type = number, except to change the value in the onInput listener as @ajdumanhug suggested.

**Comment by amineshon** [comment]
const [userName, setuserName] = useState("");
  
  const handleChange =(e)=>{
  
    // Here we are checking if the length is equal to 10
    if(e.target.value.length===5){ 
      window.alert("مقدار وارد شده صحیح نمیباشد")
    }
    setuserName(e.target.value);
  }
  
    <input
                name="username"
                value={userName}
                onChange={ handleChange}
             />
