### ISSUE TITLE
Tab.js - Switching between tabs, previous tabpanel content fades out, and new tabpanel content never fades in

### ISSUE THREAD

**Issue by rslucchese** [react-bootstrap/react-bootstrap#1519]
Hi there,

I am using react-boostrap 0.28.1. Tabs.js and <b>Tab.js</b> components.

<b>In Firefox 15:</b>
- When the page first loads, the tabpanel content appears correctly for the first tab
- When clicking on another tab, the content from the previous tab fades out, and the content from the new tab never fades in
- When clicking back on the previous tab, the content continues not to show.

I did some looking and the tipping point <b>seems to occur on line 84 of node_modules/react-bootstrap/lib/Tab.js</b>: 
<b>_utilsTransitionEvents2['default'].addEndEventListener(_reactDom2['default'].findDOMNode(this), this.stopAnimateOut);</b>

When I commented out that whole line and replaced it with simply <b>this.stopAnimateOut();</b>, the functionality worked as expected (previous tab faded out, new tab faded in).

<b>Considerations:</b>
1. This bug [appears-to-be] only happens on firefox 15. Starting at 16 and forth, the tab transitions from one to the other with no issues. And no other browsers as far as I know.
2. In this link http://www.w3schools.com/css/css3_transitions.asp, we can see that full support for css3 transitions only begin on FF 16 (not sure if that is an issue).
3. I do not have the option on my project of modifying the component directly, given that node-modules is inside of the gitignore.
4. Before I started troubleshooting this issue, i was using react-bootstrap 0.23.7. Upgraded to the latest 0.28.1 to see if it would solve the issue (so it did not occur due to/during the update).
5. I am using bootstrap 3.3.5.

Thank you for looking into this! Much appreciated!

**Comment by taion** [comment]
Does this work upstream?

**Comment by rslucchese** [comment]
Sorry not sure, what do you mean by upstream?

**Comment by taion** [comment]
TWBS

**Comment by jquense** [comment]
http://getbootstrap.com/javascript/#tabs

**Comment by rslucchese** [comment]
Yes, it does

**Comment by rslucchese** [comment]
One thing that I forgot to mention that I had noticed: In FF15, findDOMNode(this) returns a "XrayWrapper" object, whereas in FF16 it returns an html Element, when printed out to the console.

**Comment by taion** [comment]
Do we support FF 15?

**Comment by taion** [comment]
I don't really see a good reason to support FF15 at this point - sorry.

**Comment by phpnode** [comment]
This is happening on other browsers too, e.g. chrome.

To replicate

1. Go to https://react-bootstrap.github.io/components.html#tabs

2. Click on the first tab

3. Press the right and left arrows repeatedly (fast) to switch between the tabs

4. Tab content never shows

**Comment by z-ax** [comment]
Indeed, it's not only FF15 bug, can reproduce in pretty much every browser I have now (all are up-to-date), as well as inside Electron app.

Seems like only solution for now is to disable the [animation](https://react-bootstrap.github.io/components.html#tabs-props).

@phpnode, thanks for the clear steps.
