### ISSUE TITLE
<Navbar.Header> throws exception "type should not be null...."

### ISSUE THREAD

**Issue by rvnath** [react-bootstrap/react-bootstrap#1520]
I am trying to use Navbar in my react application.  I used the example code at https://react-bootstrap.github.io/components.html#navbars as it is without modification. It doesn't work.  The browser console shows the below exceptions..

> Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components). Check the render method of `PageHeader`.

> Uncaught Error: Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. Check the render method of `PageHeader`

While trying to find, **which element** in the hierarchy is causing the problem, I tried removing all elements and started adding them one-by-one to my render method.  As soon as I put Navbar.Header, I get the exception.

```javascript
render: function() {
    return (
  <Navbar inverse>
    <Navbar.Header>
    </Navbar.Header>
  </Navbar>
  );
  }
```

Can someone tell me, what could be going wrong here...

react-bootstrap version of my package.json: "react-bootstrap": "^0.27.3",

**Comment by jquense** [comment]
You are using a component that doesn't exist in bootstrap 0.27. the docs are always for the latest released version which is 0.28
