### ISSUE TITLE
how to AutoAffix / possible bug?

### ISSUE THREAD

**Issue by barbalex** [react-bootstrap/react-bootstrap#1524]
Trying to follow the example [here](http://react-bootstrap.github.io/react-overlays/examples/#affixes) I did:

    import { AutoAffix } from 'react-bootstrap'

then inside render:

    <div>
      <AutoAffix id='nav-wrapper' viewportOffsetTop={150} container={this}>
        (more jsx for a navbar)
      </AutoAffix>
    </div>

Now I get this error in the console:

    Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components). Check the render method of `Header`.

Where `Header` is the displayName of the component.

What am I doing wrong?

I tried to build a codepen example but did not manage wrangling with the configuration.

**Comment by taion** [comment]
That component is not in React Bootstrap. It's in react-overlays.

**Comment by barbalex** [comment]
oops. Not so easy to tell when looking at the url the examples are on:
http://**react-bootstrap.github.io**/react-overlays/examples/#affixes

Plus the example does not show from which library AutoAffix is imported.

Thanks, this solves this error.
