### ISSUE TITLE
Cannot pass `style` and `className` to `react-overlays\Modal`

### ISSUE THREAD

**Issue by jesenko** [react-bootstrap/react-bootstrap#1526]
While `className` and `style` can be set for `container` and `backdrop`, they cannot be set for the `<div>` that contains them.

Setting these props seems to be enabled in `react-overlays\Modal`, however they are not passed on to the `BaseModal`; `className` and `style` are not explicitly listed in `react-overlays\Modal` `propTypes`, nor explicitly passed on. Not sure though which one of these two options would be more appropriate way to fix this...

**Comment by taion** [comment]
The portal root isn't a React component - it's just a mount node and can't be styled that way anyway.

**Comment by jesenko** [comment]
@taion Are you sure about this? Actually, the [bootstrap-overlay example](http://react-bootstrap.github.io/react-overlays/examples/#modals) uses this to set `z-index` of both modal and backdrop... I think that currently, rendered output for modal can be summarized as 
```
<div><!-- portal div, unstylable -->
  <div><!-- base modal div, stylable in react-overlay/Modal, currently unstylable in react-bootstrap -->
    <div><!-- modal backdrop, stylable in react-overlay and react-bootstrap --></div>
    <div><!-- modal container, stylable in react-overlay and react-bootstrap --></div>
  </div>
</div>
```
I have opened related PR that passes `wrapperClassName` and `wrapperStyle` to BaseModal (`className` is already passed to one of Modal children, so it cannot be used)

**Comment by taion** [comment]
That's fine, but this is already handled by Bootstrap's CSS, no?

In general if you want to deeply customize your modals, we'd prefer you to use the react-overlays components directly, rather than massively expanding the API surface area of React-Bootstrap to offer that customizability.

**Comment by jesenko** [comment]
As I needed this for overriding `z-index` for stacked modals, using [react-bootstrap-modal](https://github.com/jquense/react-bootstrap-modal) is probably a better way to go...
