### ISSUE TITLE
Remove the restriction of bsStyle & bsSize

### ISSUE THREAD

**Issue by M4TH76** [react-bootstrap/react-bootstrap#1530]
Hi
I'm using your components with an extension of BootStrap (AppUI) and this extension has new CSS class(Ex: new style "Danger", "Alert"...) 

Change:
bsSize: React.PropTypes.oneOf(['small', 'medium', 'large']),
bsStyle: React.PropTypes.oneOf(['success', 'warning', 'error']),
To:
bssize: React.PropTypes.any,
bsStyle: React.PropTypes.any,

Thanks

**Comment by jquense** [comment]
nope, the styles are restricted intentionally to prevent accidental misspellings or unsupported variants, which is the far more common case than custom style variants.

If you want want to add a new style variant use the addStyle api.

```js
import utils from 'react-bootstrap/lib/utils/bootstrapUtils';
import Button from 'react-bootstrap/lib/Button';

utils.addStyle(Button, ['Danger', 'Alert'])
```
