### ISSUE TITLE
DropdownButton > MenuItem terribly slow load

### ISSUE THREAD

**Issue by crobinson42** [react-bootstrap/react-bootstrap#1531]
Whenever I put MenuItem in the code, the React render takes 3-4 seconds and lags then entire experience. It stops only after I remove MenuItem components from the code.. I'm using React v0.14.* & React-Bootstrap 0.27.3

```
var DropdownButton = require('react-bootstrap').DropdownButton;
var MenuItem = require('react-bootstrap').MenuItem;

        <DropdownButton title="Actions" id="bg-nested-dropdown">
          <MenuItem eventKey="1">Edit</MenuItem>
          <MenuItem eventKey="2">Delete</MenuItem>
        </DropdownButton>
```

**Comment by taion** [comment]
This doesn't happen in any of my use cases - check to make sure you're not rendering something other than what you expect.
