### ISSUE TITLE
Customize Carousel Style

### ISSUE THREAD

**Issue by flyaw** [react-bootstrap/react-bootstrap#1533]
I am trying to use carousel in react-bootstrap and found code as below:
```
const carouselInstance = (
  <Carousel>
    <CarouselItem>
      <img width={900} height={500} alt="900x500" src="/assets/carousel.png"/>
      <div className="carousel-caption">
        <h3>First slide label</h3>
        <p>Nulla vitae elit libero, a pharetra augue mollis interdum.</p>
      </div>
    </CarouselItem>
    <CarouselItem>
      <img width={900} height={500} alt="900x500" src="/assets/carousel.png"/>
      <div className="carousel-caption">
        <h3>Second slide label</h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
      </div>
    </CarouselItem>
    <CarouselItem>
      <img width={900} height={500} alt="900x500" src="/assets/carousel.png"/>
      <div className="carousel-caption">
        <h3>Third slide label</h3>
        <p>Praesent commodo cursus magna, vel scelerisque nisl consectetur.</p>
      </div>
    </CarouselItem>
  </Carousel>
);
```
It will result in a default carousel. But I want to customize the style of control points and the direction arrow. Unfortunately, I cannot figure out how to do it.

Any help?

**Comment by taion** [comment]
These are all the config options available: http://react-bootstrap.github.io/components.html#carousels-props

See e.g. the props related to icons.

**Comment by ErwinALX** [comment]
<Carousel>
                    <Carousel.Item>
                        <img className="img-responsive center-block" width={400} height={400} src={Blartenix} />
                        <Carousel.Caption>
                            <h3>Blartenix</h3>
                            <p>New Game Company In Colombia</p>
                        </Carousel.Caption>
                    </Carousel.Item>
                    <Carousel.Item>
                        <img className="img-responsive center-block" width={400} height={400} src={Blartenix} />
                        <Carousel.Caption>
                            <h3>Focus On </h3>
                            <p>Survival Maze Shooter</p>
                        </Carousel.Caption>
                    </Carousel.Item>
                </Carousel>

**Comment by ErwinALX** [comment]
`<Carousel>
                    <Carousel.Item>
                        <img className="img-responsive center-block" width={400} height={400} src={Blartenix} />
                        <Carousel.Caption>
                            <h3>Blartenix</h3>
                            <p>New Game Company In Colombia</p>
                        </Carousel.Caption>
                    </Carousel.Item>
                    <Carousel.Item>
                        <img className="img-responsive center-block" width={400} height={400} src={Blartenix} />
                        <Carousel.Caption>
                            <h3>Focus On </h3>
                            <p>Survival Maze Shooter</p>
                        </Carousel.Caption>
                    </Carousel.Item>
                </Carousel>`
