### ISSUE TITLE
refs are not set up on tests if inside a react-bootstrap component

### ISSUE THREAD

**Issue by willgm** [react-bootstrap/react-bootstrap#1534]
I am using:

 - "react": "0.13.3"
 - "react-bootstrap": "0.26.4"

Every time when I use a `ref` in a node inside a `<Modal />` or other component, they are correctly setted when I run the system normally, but at test environment they just disappear.

I have tried all the render strategies of the react test utils, but seems to have no difference.

**Comment by taion** [comment]
The modal runs in a portal, so this is expected. Try mounting into an actual DOM node. See also our tests.

**Comment by willgm** [comment]
What does it means run in a portal?

I haven't find any use of `ref` at the tests.

I have the follow example:

```jsx
<Modal.Body className="gridForm">
  <label className="col5 smallPadding nowrap">
     {__( 'Repeats every' )}
    <input type="number" className="form-control" ref="interval" />
  </label>
</Modal.Body>
```

There is no `this.refs.interval` at the tests.

**Comment by taion** [comment]
You need to render into an actual mounted DOM node, rather than a detached one. We do this via `helpers.render` in our tests.
