### ISSUE TITLE
How to access scrolling layer of modal

### ISSUE THREAD

**Issue by kirill-konshin** [react-bootstrap/react-bootstrap#1536]
In the project I have a requirement to add "scroll to top" button to the dialog windows. Also I need to have a section, that becomes fixed when scrolled outside of the viewport.

I am expecting a markup like this:

```js
<Modal>
    <Modal.Title>Foo</Modal.Title>
    <Modal.Body>
        <FixedBlock>Bar</FixedBlock>
        <ScrollToTop />
        Some stuff
   </Modal.Body>
</Modal>
```

In order to do that I need to have access to `.modal-open .modal` from `FixedBlock` and `ScrollToTop` components, so my question is -- how to do that in a most efficient way?

Obviously, I can have a `ref` to root element of those components and go up the parents chain in the DOM until I reach needed `.modal` DIV. Is that OK?

**Comment by taion** [comment]
That doesn't sound quite right. In general if you need more flexibility than is offered in the R-B APIs, you'll want to use the lower-level APIs in react-overlays.

**Comment by kirill-konshin** [comment]
Makes sense.
