### ISSUE TITLE
Provide a way to append classNames to components

### ISSUE THREAD

**Issue by kirill-konshin** [react-bootstrap/react-bootstrap#1537]
Currently there is a prop `bsClass` which allows to set a className for `<Modal>` and others, but it overrides any of default ones, like `modal`. It would be useful to have a way to *append* some classNames instead of to override.

**Comment by taion** [comment]
Just use `className` for that no?

**Comment by kirill-konshin** [comment]
There are some inconsistencies:

- `<Modal dialogClassName="foo" />` -- inconsistent prop
- `<Navbar className="foo"/>` -- failed
- Grid, Panel, Button, ButtonGroup, Table -- OK

I did not check all of them...

**Comment by dozoisch** [comment]
@kirill-konshin well on Modal, both className and dialogClassName are used because they are applied to different elements. It's hard to be "consistent" when there is a need for classnames on a lot of different components and sub components.

**Comment by taion** [comment]
Exactly - also, `className` on `<Navbar>` does in fact work; I just checked on our components page.
