### ISSUE TITLE
Modal doesn't guarantee listener clean up

### ISSUE THREAD

**Issue by joshgagnon** [react-bootstrap/react-bootstrap#1538]
The window resize handler for a modal is controlled by [Modal._onHide](https://github.com/react-bootstrap/react-bootstrap/blob/master/src/Modal.js#L175),  but there is no guarantee that this function will be called by the child base modal component.

This leads to a bug where after a modal is closed, a window resize event can throw an error due to the component no longer existing.

I'm unsure of the best way to ensure cleanup other than adding it to componentWillUnmount (I am currently doing this as a workaround).

**Comment by jareware** [comment]
I was under the impression this was already resolved, with an update to some dependency perhaps..?

**Comment by dclausen** [comment]
@joshgagnon could you show your work around, please?

**Comment by joshgagnon** [comment]
This is the workaround, ugly, but I believe it works https://github.com/joshgagnon/good-company/blob/master/assets/js/components/importCompany.js#L72

**Comment by pgilad** [comment]
@joshgagnon Is your workaround the recommended way to approach this? Seems very hackish (although it works)

**Comment by amalahussein** [comment]
Hi, I just updated to 0.28.2 and I'm seeing this issue--looks there are a few different solutions here--which one should I implement? And more so, will there be a fix for this in the next release?

**Comment by taion** [comment]
We're pretty confident this is fully fixed in the latest release. Make sure you've updated everything correctly.

**Comment by amalahussein** [comment]
@taion sure--i'll clear my jspm cache...thank you for the quick response.

**Comment by amalahussein** [comment]
@taion I've cleared my npm and jspm cache--and i'm run a fresh install, and here is my stack trace:

**Comment by 5punk** [comment]
I'm still facing this issue...

**Comment by chestermjr** [comment]
I'm still receiving this error.

**Comment by jeshio** [comment]
I have too

**Comment by 89465127** [comment]
I am also experiencing this. Did anyone find a workaround?
