### ISSUE TITLE
onExited not called when set in Accordion or Panel component

### ISSUE THREAD

**Issue by prashanw** [react-bootstrap/react-bootstrap#1540]
I'm using Accordion component to create a set of collapsable panels and I needed to assign a call back when the component is collapsed. I did so by setting the onExited prop on Accordion and even tried setting this on the Panel component but, the callback is never getting called. Here's my render method:
```
  render() {
    return (
      <Accordion defaultActiveKey='1' onExited={this.handleExited}>
        <Panel onExited={this.handleExited} >
          <span>Some text</span>
        </Panel>
      </Accordion>
    )
  }
```
I can see that the Panel component is getting the prop onExited but, the generated Transition component never gets the prop onExited set from the parent Panel component. Is this a bug or am I missing something here? Help is much appreciated.

I'm using react-bootstrap 0.25.1

**Comment by martijnvermaat** [comment]
The way `<Collapse />` is used in `<Panel collapsible={true} />`, it looks to me there's no way to give it any of the callback props it accepts.

I'm currently updating a codebase from React-Bootstrap 0.20 which had a `<Panel />` with `CollapsableMixin` where I could do something like this:
```
var TransitionEvents = require('react/lib/ReactTransitionEvents');
TransitionEvents.addEndEventListener(panel.getCollapsibleDOMNode(), callback);
```
But I don't see any way to do this now, short from implementing the collapsing panel myself.

I use this to trigger some DOM magic after the collapse transition completes.

**Comment by jquense** [comment]
I'm sure we'd take a PR that passes Transition hooks to the Collapse
