### ISSUE TITLE
Is there a way to get sourcemaps for the original source

### ISSUE THREAD

**Issue by dustingetz** [react-bootstrap/react-bootstrap#1542]
The lib directory has been processed by babel and it is frustrating to debug. It seems like the src directory has been filtered out of the published package somehow but maybe I am doing it wrong.

**Comment by taion** [comment]
There's not really a convention for distributing source maps with transpiled code (though our UMD bundles have them).

I think the idea is that the general target for this library is something like a webpack bundle, for which those input source maps can't (AFAIK?) be used anyway, so there wouldn't be much of a point.

I'd just install for GitHub if you needed the original ES6 code to debug with.

**Comment by dustingetz** [comment]
I was not very clear. Source maps is not the only way. I dug up more details: 

Redux bundles `src` along with `lib` and `dist` in their npm publish artifact. React-bootstrap can achieve this with a one line change to package.json - here is where [redux publishes es6 src](https://github.com/rackt/redux/blob/master/package.json#L7-L11), and [react-bootstrap doesn't](https://github.com/react-bootstrap/react-bootstrap/blob/master/package.json#L27-L33). This will allow users to debug with es6 source from `npm install`.

re-opening this issue to make sure the issue is re-evaluated in light of this new information. If you close it again i will drop it.

**Comment by dustingetz** [comment]
I guess I'm not allowed to re-open the issue.

**Comment by taion** [comment]
Redux do that specifically for Flow though: https://github.com/rackt/redux/commit/a4b8aff95d5e194500bc8dcc130a6d7f71aadefa

Almost no packages ship `src/` - you can check e.g. upstream React, or e.g. React Router.

**Comment by dustingetz** [comment]
React is written in es5; [react-router actually does ship es6](https://github.com/rackt/react-router/blob/master/package.json#L5-L12)

**Comment by taion** [comment]
Did you see how I made that change? :p

The shipped `es6/` code is transpiled; the only difference is that it uses ES6 modules rather than CJS modules, for better compatibility with rollup and webpack 2. It's not the source.
