### ISSUE TITLE
React-Select Menu Scrollbars don't play nice with Modal

### ISSUE THREAD

**Issue by MrLeebo** [react-bootstrap/react-bootstrap#1543]
This is a cross-repository post for JedWatson/react-select#648 because I'm not sure what the fix is.

When I add a React-Select control to a React-Bootstrap Modal, the options menu closes instead of scrolling when I click on the scrollbars. It looks like the modal's container is taking focus from the menu, which is causing a blur handler on the React-Select component to misbehave.

There is a code to reproduce the problem in the referenced issue.

**Comment by taion** [comment]
`enforceFocus={false}`

**Comment by taion** [comment]
Err, actually, probably `autoFocus={false}`. Oops!

**Comment by MrLeebo** [comment]
@taion Thank you for the speedy response, but neither one of those options seemed to make a difference.

**Comment by taion** [comment]
Err, on the modal?

**Comment by MrLeebo** [comment]
@taion yes, on the Modal. enforceFocus was the first thing I tried when I ran into this.

**Comment by taion** [comment]
Wait, so `Modal` is attempting to steal focus even when you disable `autoFocus` and `enforceFocus`? Do you know what specifically is making it try to do this?

**Comment by MrLeebo** [comment]
Not yet, I dug around in the source but ran out of time yesterday. If I get a chance to look today I will post my findings.

**Comment by taion** [comment]
Closing for staleness.

**Comment by rigobertocontreras** [comment]
Same problem

**Comment by jorgechen** [comment]
Same issue, anyone have a fix?

**Comment by ThieryMichel** [comment]
same problem

**Comment by MrLeebo** [comment]
@jorgechen No, sorry. We just flagged it as a "Known Issue" in our app and moved on. If I am back in that code I will look for it again, but for the time being I am working on unrelated stuff. :(
