### ISSUE TITLE
Partial import is not working

### ISSUE THREAD

**Issue by DmitriyD** [react-bootstrap/react-bootstrap#1544]
I'm using webpack with npm and babel. When I try import some components like this
`import { Panel, Input, Col } from 'react-bootstrap';`
webpack throws error 
```
ERROR in chunk manage [entry]
[name].min.js
No template for dependency: TemplateArgumentDependency
```

**Comment by jquense** [comment]
this is most likely not react-bootstrap's fault, you probably have something wrong with your webpack or Babel config

**Comment by DmitriyD** [comment]
With all other packages this syntax works fine.

**Comment by DmitriyD** [comment]
Ok, it seems this is a problem with webpack.optimize.DedupePlugin(). I removed it from webpack config ant now it works fine.
But, as I said, react-bootstrap is a first package I have problem like this.

**Comment by taion** [comment]
It's an open webpack bug. See e.g. https://github.com/webpack/webpack/issues/1082 and https://github.com/HenrikJoreteg/hjs-webpack/pull/23.

**Comment by jquense** [comment]
glad you figured it out. there is not much we can do about how the dedupe plugin works but we aren't doing anything weird or incorrect in our exports. 

you might want to raise an issue on the dedupe plugin repo.
