### ISSUE TITLE
Testing with shallow rendering

### ISSUE THREAD

**Issue by rkovacevic** [react-bootstrap/react-bootstrap#1546]
Trying to test with shallow rendering, not sure how to set value on an `Input`.

Actual DOM Input element is not rendered in shallow rendering, so I don't think I can set that. 

Would it be possible to add a `setValue` method, or is there a simpler solution that I'm missing?

**Comment by jquense** [comment]
the easiest way is to just pass a `value` prop to the Input.

**Comment by rkovacevic** [comment]
Didn't work for me. I tried this:

```javascript
let usernameInput = findWithRef(component, 'username')
console.dir(usernameInput)
usernameInput.props.value = 'test'
````
Which produces this error at the line where the prop is set:
```
TypeError: Can't add property value, object is not extensible
at Context.<anonymous> (index.spec.js:44:14)
```

and this console output:
```
{ '$$typeof': Symbol(react.element),
  type: { [Function: Input] propTypes: { type: [Object] } },
  key: null,
  ref: 'username',
  props:
   { type: 'text',
     label: 'Username',
     bsStyle: undefined,
     help: undefined,
     placeholder: 'Enter username',
     zindex: 1,
     disabled: false,
     hasFeedback: false,
     multiple: false },
  _owner: null,
  _store: {} }
```
Did I miss something?

**Comment by jquense** [comment]
Why are you trying to mutate `props`? That's a huge no-no. you need to set it when you render the element

```js
renderer.render(
  <Input value={whatever} />
)

renderer.getRenderOutput() //do whatever
```

**Comment by rkovacevic** [comment]
This is in a test, I'm testing with shallow rendering. 

This is the general idea of what I'm trying to do:

```
it('form submit works', () => {
        const login = spy()
        const component = shallowRender(Login, {
            login
        })
        let usernameInput = findWithRef(component, 'username')
        console.dir(usernameInput)
        usernameInput.props.value = 'test'
      
        findWithType(component, 'form').onSubmit()

        let loginCall = dispatch.getCall(0).args[0]
        expect(loginCall).to.deep.equal({
            username: 'testuser',
            password: 'testpass'
        })
    })
```

**Comment by jquense** [comment]
right then you need to an interface to pass the initial values to the input from Login, you can't mutate props, and since there is no underlying DOM there is nothing else to set as the "value" of the input, since the input doesn't exist.

**Comment by rkovacevic** [comment]
Right, but that was my original question, would it be possible to add a `setValue` method to `Input` for this case? So that I don't have to pollute `Login` with testing stuff.

**Comment by jquense** [comment]
what would that method do? There is no input to set a `value` on and a component cannot mutate its own props anymore than you can.

Not that any of that matters becasue what you get back from shallow rendering is not a component instance, that you can call methods on its a ReactElement, so even if that method existed you would not have access to it in this situation.

**Comment by rkovacevic** [comment]
Yeah, you're right, I didn't realise that. Ok, looks like shallow rendering is a lost cause, back to jsdom :) Thanks for the explanation.
