### ISSUE TITLE
OverlayTrigger.js#componentWillUnmount slooow

### ISSUE THREAD

**Issue by ninja-** [react-bootstrap/react-bootstrap#1547]
This function eats as much as 100ms (sum) for me when unmounting all the overlay triggers. Is there something that can be done about it.

**Comment by ninja-** [comment]
this fixed the problem for me...clearTimeout seems sloow in browsers so I am getting rid of it in other parts of my app also
```
	  componentWillUnmount: function componentWillUnmount() {
	    _reactDom2['default'].unmountComponentAtNode(this._mountNode);
	    this._mountNode = null;
	    if (this._hoverShowDelay > 0)
				clearTimeout(this._hoverShowDelay);
			if (this._hoverHideDelay > 0)
	    	clearTimeout(this._hoverHideDelay);
	  },
```

**Comment by taion** [comment]
What browser/OS do you see this on? This doesn't make sense to me.

**Comment by ninja-** [comment]
@taion that's on chrome :/ changed this in a pull request

**Comment by taion** [comment]
I'll change this for consistency, since we check for the handle being defined elsewhere in that component, but on my machine `clearTimeout` takes like 200 us - this is almost certainly not causing you perf issues, unless you're doing something extremely bizarre and inadvisable.

**Comment by taion** [comment]
I misread the timing. It's actually 200 ns. This is a non-factor.
