### ISSUE TITLE
Are inline styles planned?

### ISSUE THREAD

**Issue by pke** [react-bootstrap/react-bootstrap#1549]
I wonder whats the projects opinion on inline styles?

**Comment by taion** [comment]
You're free to use them if you want. We have no formal opinion.

**Comment by pke** [comment]
I am using them. Just wondered if we will find them in react-bootstrap any time soon or have to still deploy/bundle the bootstrap.css file

**Comment by taion** [comment]
We don't deploy any CSS - the point is to give you the flexibility to bring your own.
