### ISSUE TITLE
Manual displaying with OverlayTrigger.

### ISSUE THREAD

**Issue by Nutelac** [react-bootstrap/react-bootstrap#155]
How should I manually control OverlayTrigger displaying (show / hide)?

E.g if I want to show only one popover on page:

``` javascript
var UniquePopover = React.createClass({
    render: function() {
        return (
            <ReactBootstrap.OverlayTrigger container={document.body} trigger="manual" placement="right" overlay={
                <ReactBootstrap.Popover>
                    foobar
                </ReactBootstrap.Popover>
            }>
                <ReactBootstrap.Button onClick={this.handleClick} bsStyle="default">unique popover</ReactBootstrap.Button>
            </ReactBootstrap.OverlayTrigger>
        );
    },
    handleClick: function() {
        /* Abstract */
        showCurrentPopover();
        hideOtherPopovers();
    }
});
```

Is that possible and how can I access to **show** and **hide** methods? Thank you.

**Comment by haizi-zh** [comment]
Thanks! it really helps!

**Comment by avk** [comment]
Still works today! Wish this was documented under `OverlayTrigger`.

**Comment by jquense** [comment]
the show/hide methods are not really public, if you need to control the overlay state directly use the Overlay component directly

**Comment by stuphys1729** [comment]
Just in case anyone is looking at this later, it seems `OverlayTrigger` now only accepts set inputs for `trigger` and 'manual' isn't one of them. A workaround is to use null instead and still use the show/hide methods.

**Comment by charlie632** [comment]
How do you use the show/hide methods? I can't seem to make it work.

**Comment by eugeneborodkin** [comment]
What are the possible values for `trigger=...` for `OverlayTrigger`? They only show `click` in their examples, are there others? And also, how do you **pre-open** a popover in an initial state? I created a StackOverflow thread on this, https://stackoverflow.com/questions/69121013/react-bootstrap-popover-pre-open-popover-on-initialization I need to pre-open a popover on initialization.
