### ISSUE TITLE
Tab in tabs not being properly handled when included via component render

### ISSUE THREAD

**Issue by nathan-rice** [react-bootstrap/react-bootstrap#1554]
[main.tsx.zip](https://github.com/react-bootstrap/react-bootstrap/files/57406/main.tsx.zip)

The header LI elements are not being inserted in the tab header UL for tabs included in tabsets via components.

demonstration plunkr: http://plnkr.co/edit/0SQNtZbbsLTzIpy3WfDU

**Comment by jquense** [comment]
hey thanks for the example but the compiled code output is really hard to read and tell whats going on, do you have the uncompiled source?

**Comment by nathan-rice** [comment]
I've attached the original typescript-x file to the issue.  Let me know if I can be of further assistance.

**Comment by taion** [comment]
Can you include the actual code snippet please, instead of a zip file?

**Comment by nathan-rice** [comment]
```javascript
/// <reference path="./react.d.ts"/>
/// <reference path="./react-global.d.ts"/>

class TestTabset extends React.Component<any, any> {

    constructor() {
        this.state = {key: 1};
        super()
    }

    render() {
        return (
            <ReactBootstrap.Tabs activeKey={this.state.key} onSelect={key => this.setState({key: key})}>
                <ReactBootstrap.Tab activeKey={2} title="Non-component tab works"></ReactBootstrap.Tab>
                <TestTab></TestTab>
            </ReactBootstrap.Tabs>
        )
    }
}

class TestTab extends React.Component<any, any> {
    render() {
        return (
            <ReactBootstrap.Tab title="test tab" key={2}></ReactBootstrap.Tab>
        )
    }
}

window.onload = function () {
    var el = document.getElementById("body");
    ReactDOM.render(<TestTabset/>, el);
};
```

**Comment by taion** [comment]
This just isn't supported with the current API. That API is getting replaced by https://github.com/react-bootstrap/react-bootstrap/pull/1525 anyway though - though I still don't think this will be supported.

Essentially we have to pull apart the `<Tab>` for its constituent parts - it's a configuration object like e.g. a React Router `<Route>`, not something directly render-able.
