### ISSUE TITLE
Input looses focus if addonAfter prop changes

### ISSUE THREAD

**Issue by xsistens** [react-bootstrap/react-bootstrap#1556]
This makes it impossible to use ```addonAfter``` to display a validation result or so. Is there any chance to keep it focused? if you manually focus it after setting the props is no option, because you will loose the position of the cursor. The props ```addonBefore```, ```buttonBefore```, ```buttonAfter``` probably show the same behavior.

thanks in advance, Chris

**Comment by taion** [comment]
Make `addonAfter` a stub of some sort - we need to change the DOM structure to show the addon, and we're not going to render the extra wrapper if we don't need it.
