### ISSUE TITLE
Cannot find var jQuery

### ISSUE THREAD

**Issue by isikfsc** [react-bootstrap/react-bootstrap#1562]
I practically cannot start my sample react-bootstrap app.
The js console gives the error: `ReferenceError: Can't find variable: jQuery`.
What is the proper set up for using react-bootstrap?
How to load the dependencies for `react-bootstrap` and `bootstrap`?

I have following code structure. Before adding anything other than react react-dom this set up was working. And I just transform my code with browserify and babel to work in browser by `browserify -t [ babelify --presets [ react es2015] ] main.js -o bundle.js`

main.js: [in this fiddle](https://jsfiddle.net/isikfsc/dxevtenr/)

index.html:
`
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <title>Hello React!</title>
  </head>
  <body>
    <div id="container"></div> 
    <script src="bundle.js"></script>
  </body>
</html>
`

**Comment by taion** [comment]
This is the setup: http://react-bootstrap.github.io/getting-started.html#setup.
