### ISSUE TITLE
A regression for #1078 "Modal (and probably others) should use componentWillUnmount"

### ISSUE THREAD

**Issue by zerkms** [react-bootstrap/react-bootstrap#1563]
There is a regression for https://github.com/react-bootstrap/react-bootstrap/issues/1078

In the https://github.com/react-bootstrap/react-bootstrap/commit/214bc772e414050779bd37cbfb326c699f6f8be9 commit there was both the fix and the corresponding test removed which brought the initial problem back.

Currently there is no (?) code that invokes `_onHide` on `Modal` unmount event which causes `handleWindowResize` to still be invoked on a window resize, whereas the modal element does not exist in the DOM which causes an exception on `let scrollHt = node.scrollHeight;` line.

@jquense @taion could you guys please comment on that?

**Comment by jquense** [comment]
There is two things here. Your original fix still exists it just moved [here](https://github.com/react-bootstrap/react-overlays/blob/master/src/Modal.js#L281). That being said there is a regression as some not all the work moved to the underlying modal, so we have a bit of a refactor error

**Comment by zerkms** [comment]
Oh, okay :-) If no one donates a fix any time soon I'll try to allocate some free time into the problem.

Thanks.

**Comment by taion** [comment]
Dupe #1538
