### ISSUE TITLE
Rapidly switching between Tabs hides content

### ISSUE THREAD

**Issue by SherClockHolmes** [react-bootstrap/react-bootstrap#1568]
Rapidly switching between tabs results in the content disappearing. You can also reproduce on the website examples: http://react-bootstrap.github.io/components.html#left-tabs

I put together a simple example on jsfiddle:
https://jsfiddle.net/69z2wepo/24363/

```
var TabsRapidTest = React.createClass({
    render: function() {
        return (
        	<Tabs>
            	<Tab eventKey={1} title="Title 1">Content 1</Tab>
                <Tab eventKey={2} title="Title 2">Content 2</Tab>
        	</Tabs>
        );
    }
});
```

**Comment by taion** [comment]
Dupe into https://github.com/react-bootstrap/react-bootstrap/issues/1418
