### ISSUE TITLE
Allow Breadcrumbs to play nicely with RRB Link Container

### ISSUE THREAD

**Issue by jquense** [react-bootstrap/react-bootstrap#1569]
https://github.com/react-bootstrap/react-router-bootstrap/issues/141

also relevant: https://github.com/react-bootstrap/react-bootstrap/pull/1273#discussion_r38807121

**Comment by taion** [comment]
Do you know offhand what TWBS renders for an active breadcrumb with an href set?

**Comment by jquense** [comment]
the active one isn't wrapped in an `<a>`, so I don't think the issue is styling. I think all we need to do is just make sure not to try and add href to the span in that case.

**Comment by jquense** [comment]
I am not actually sure what the warning is protecting against here

**Comment by taion** [comment]
Nothing in particular; it just seemed like a good placeholder to avoid user error when setting these up manually.

Given the RRB context, that's not really the primary concern any more.
