### ISSUE TITLE
Adding documentation on <Popover />'s mountNode

### ISSUE THREAD

**Issue by jefffriesen** [react-bootstrap/react-bootstrap#157]
The container={mountNode} is a bit mysterious in the popover documentation. I see where it's defined in the docs:

```
 executeCode: function() {
    var mountNode = this.refs.mount.getDOMNode();
```
But which node it should reference is hard to decipher. I've tried
```
  componentDidMount: function() {
    var mountNode = this.refs.button.getDOMNode()
}
```
With no luck (it's still positioned incorrectly). A little bit of documentation of what this node should refer to and how to access it would be really helpful.

**Comment by taion** [comment]
This feature actually looks to be broken right now. The example on the components page with scrolling popovers sets `container`, but renders the popover in the wrong place:

![image](https://cloud.githubusercontent.com/assets/3112159/7552417/99e7b05c-f667-11e4-8203-72fc891ac2c9.png)

**Comment by taion** [comment]
This actually is demonstrated in the components demo, though it's broken due to some weirdness. Do we need additional documentation beyond what's there?

**Comment by taion** [comment]
Will add further documentation on `container` with #173.
