### ISSUE TITLE
Load remote url in react-bootstrap modal component

### ISSUE THREAD

**Issue by MQZhangThu** [react-bootstrap/react-bootstrap#1571]
Is there any way to load remote url in react-bootstrap modal component?

**Comment by jquense** [comment]
there isn't a built in way of handling that, no. Just use xhr or whatever ajax lib you are using to load the content and then swap out the model content

```jsx
<Modal.Body>
{ isLoading ? <Loading /> : <MyModalContent }
</Modal.Body>

```
