### ISSUE TITLE
Add 'minBarWidth' to ProgressBars

### ISSUE THREAD

**Issue by sorahn** [react-bootstrap/react-bootstrap#1574]
Hello guys, I'd like to suggest adding a `minBarWidth` feature to the progress bars, that would allow you to achieve what is in this [bootstrap example](http://getbootstrap.com/components/#progress-label).

> To ensure that the label text remains legible even for low percentages, consider adding a min-width to the progress bar.

I tried using a style on the ProgressBar, but it set the style to the outer div, and not the inner one.

Thanks!

**Comment by taion** [comment]
Just do `now={Math.max(now, minWidth)}`.

**Comment by sorahn** [comment]
That sort of works, but if the ProgressBars change size (different page widths) that value is based of percentages of the whole thing rather than being able to stay wide enough to fit empty numbers.

**Comment by sorahn** [comment]
You could maybe just have an option to 'always fill the label' and then you could calculate the width of the label, and set the fill percentage to that or the actual percent.    That would probably be even better for people changing font sizes for a11y reasons.

**Comment by cvrebert** [comment]
FYI, we killed this feature upstream in v4; see https://github.com/twbs/bootstrap/issues/17264 & related.
The new recommendation is to put the label text above or below the bar rather than within the bar.

**Comment by taion** [comment]
@cvrebert Thanks!

On closer inspection, this issue is irrelevant anyway. This can be accomplished right now with:

```js
<ProgressBar>
  <ProgressBar now={now} className="my-bar" />
</ProgressBar>
```

And I need to fix setting up styles shortly.

I don't really like this API, but it doesn't prohibit doing what this issue wants.

**Comment by taion** [comment]
https://github.com/react-bootstrap/react-bootstrap/pull/1719
