### ISSUE TITLE
OverlayTrigger not working on mobile Safari

### ISSUE THREAD

**Issue by marcelpanse** [react-bootstrap/react-bootstrap#1576]
Simple overlay trigger from the docs is not working on mobile safari (on iphone)

      <OverlayTrigger id='ovTrigger' trigger='hover' placement="bottom" overlay={<Popover id="overlay" title="Popover bottom"><strong>Holy guacamole!</strong> Check this info.</Popover>}>
        <Button bsStyle="default">Hover</Button>
      </OverlayTrigger>

Also trigger='focus' as the console suggests does not work.

**Comment by taion** [comment]
Dupe https://github.com/react-bootstrap/react-bootstrap/issues/1570

**Comment by tsteele2013** [comment]
@taion I wouldn't consider this to be a duplicate of #1570. This issue references mobile Safari specifically. 

@marcelpanse I've found the following code to work successfully.
```
<OverlayTrigger
    placement="left"
    trigger={['click', 'hover', 'focus']}
    overlay={
        <Popover title="My Applications" id='MyApps'><div><p>These are all of the applications you have submitted previously or saved as a draft.</p>{helpBlock()}</div></Popover>
    }
>
    <MdHelp size={25} className="pull-right" type="button" />
</OverlayTrigger>
```
Here is the result inside in iPhone 6 running iOS 10.3.2.
<img src="https://cloud.githubusercontent.com/assets/13422144/26010080/890237ea-3719-11e7-86e1-560ec8fd5c25.jpg" width = 400>

**Comment by Sudhir9026** [comment]
`<OverlayTrigger id='ovTrigger' trigger='hover' placement="bottom" overlay={<Popover id="overlay" title="Popover bottom"><strong>Holy guacamole!</strong> Check this info.</Popover>}>
    <Button bsStyle="default">Hover</Button>
  </OverlayTrigger>`

This is not an OverlayTrigger issue. It's Button isuues.  Please change the button to TouchableOpacity.
