### ISSUE TITLE
multiple overlay triggers / overlays

### ISSUE THREAD

**Issue by mmahalwy** [react-bootstrap/react-bootstrap#1580]
I am finding a problem with my rendering time as I rely heavily on tooltips for each text rendered

For example:
```
text() {
    const { line } = this.props;

    if (!line[0].char) { // TODO shouldn't be possible, remove this clause
      return false;
    }

    const lineText = line.map(word => {
      if (word.word.translation) {
        const tooltip = (
          <Tooltip id={word.word.id}>
            <h4>
              {word.word.translation}
            </h4>
          </Tooltip>
        );

        return (
          <OverlayTrigger placement="top" overlay={tooltip} key={word.word.id} animation={false}>
            <b key={word.char.code}
              className={word.char.font}
              title={word.word.translation}
              dangerouslySetInnerHTML={{__html: word.char.code}}>
            </b>
          </OverlayTrigger>
        );
      }

      return (
        <b className={word.char.font}
           key={word.char.code}
           dangerouslySetInnerHTML={{__html: word.char.code}}>
        </b>
      );
    });

    return (
      <span className={`${style.font} line`}>
        {lineText}
      </span>
    );
  }
```

Which really hurts my rendering time from about 30ms+ / component to about 2ms / component when no overlay is added. This is because it has to render many overlay components for each `<b>` and that costs time. Any suggestions to have either 1 overlay component per one of my components and dynamically have it be utilized or one for all my components that render text?

Previously, I decided to go the jquery/bootstrap route to avoid this but I love react-bootstrap.

**Comment by taion** [comment]
Take a look at the React perf tools to figure out where the timing is actually going: https://facebook.github.io/react/docs/perf.html

**Comment by mmahalwy** [comment]
@taion i did, and the problem is the number of instances of `OverlayTrigger` and `Overlay` add up to make the rendering per component slow.

**Comment by kimmobrunfeldt** [comment]
Why are these performance issues closed? I'm seeing similar behaviour. When measuring with React perf tools, one of my components spends 10x more wasted CPU time if I have an `OverlayTrigger` and `Overlay` in the component.

**Comment by jonathanq** [comment]
I am seeing this as well.  Remove all of the OverlayTriggers and performance issues disappear.

**Comment by Zarathustra2** [comment]
For anyone still having this issue, we moved to https://github.com/atomiks/tippyjs-react for overlays. Render time has been improved by 50%; we are rendering a large amount of overlays.
