### ISSUE TITLE
Tooltip: rerenders incorrectly if tooltip element content width changed

### ISSUE THREAD

**Issue by Firfi** [react-bootstrap/react-bootstrap#1581]
Hey,

notice how it rerenders itself if content width is changed: it starts new content width where old content left side was placed initially, making it sort of 'left-aligned', and moving upper triangle in incorrect place therefore

![react-bootstrap-tooltip](https://cloud.githubusercontent.com/assets/947595/12034535/410bf71a-ae43-11e5-8c4f-cdd4dd3fb701.gif)

Code looks like this:

```
render() {
    const {placement} = this.props;
    return <OverlayTrigger placement={placement} overlay={<Tooltip>{this.props.title}</Tooltip>}>
      <div className={cx(this.props.className)}>
        {this.props.children}
      </div>
    </OverlayTrigger>;
  }
```

No additional class-related css was applied.

**Comment by taion** [comment]
https://github.com/react-bootstrap/react-bootstrap/issues/1438
