### ISSUE TITLE
Warning: Failed propType: Invalid prop `bsSize` of value `md` supplied to `Modal`, expected one of ["lg","large","sm","small"]

### ISSUE THREAD

**Issue by mseiwald** [react-bootstrap/react-bootstrap#1583]
I'm trying to get a medium-sized Modal by supplying `bsSize="md"`. It works perfectly fine but gives me this warning. Why is "md" not supported (but applied anyway?) and what is the proper way to get a Modal with medium width?

**Comment by jquense** [comment]
there is no `modal-md` in the css you just don't add a size for a medium sized modal. the only supported sizes (upstream) are large and small

**Comment by kkeri** [comment]
If you simply omit the `size` attribute, you get the same width as if you specified `'md'` or any other unsupported value.
