### ISSUE TITLE
Checkbox does not work inside dropdown

### ISSUE THREAD

**Issue by Tjorriemorrie** [react-bootstrap/react-bootstrap#1585]
Nesting a checkboxes inside MenuItems inside a DropdownButton does not work; clicking the checkboxes has no effect:

```
<DropdownButton title="Projects">
                            <MenuItem key={id}>
                                <Input type="checkbox" label={name} />
                            </MenuItem>;
                        })}
                    </DropdownButton>
```

**Comment by jquense** [comment]
this isn't supported since MenuItem renders an anchor tag around your check box. you have to use a custom MenuItem component or custom  menu. check the dropdown docs for examples of how to do thay

**Comment by Tjorriemorrie** [comment]
Thanks, apologies for missing that.

**Comment by erseversahin** [comment]
https://stackoverflow.com/questions/72920724/checkboxes-inside-dropdown-menu-does-not-work-in-react?noredirect=1#comment128796685_72920724
