### ISSUE TITLE
Tooltips no longer working on upgrade from react 0.14.0 -> 0.14.1

### ISSUE THREAD

**Issue by jclyons** [react-bootstrap/react-bootstrap#1591]
Hi,

For whatever reason, when I upgrade from react 0.14.0 to 0.14.1 (although same goes for 0.14.2, 0.14.3) tooltips no longer work:

`Uncaught TypeError:  Cannot read property 'unstable_renderSubtreeIntoContainer' of undefined`

When I console log `_reactDom2` from within the `renderOverlay()` function the `default` field is undefined.

Tooltips function correctly with react 0.14.0 still. I've looked over React  and React bootstrap changelog and can't find obvious answers.

**Comment by jquense** [comment]
Seems like you have duplicate instances of ReactDom perhaps. that function is definately in all versions of ReactDom

**Comment by taion** [comment]
And specifically our docs page still works, so this is most likely an install error.
