### ISSUE TITLE
ButtonInput does not work like Button

### ISSUE THREAD

**Issue by Industrial** [react-bootstrap/react-bootstrap#1592]
Hi.

I should use `ButtonInput` instead of `Button` to do a form submit, correct?

Right now, if I put a `ButtonInput` inside a `ButtonGroup` it will render incorrectly (http://i.imgur.com/HlFmSzW.png).
If I put something (e.g. a spinner image) inside a `ButtonInput` then it will render as `[object Object]`.

**Comment by jquense** [comment]
I believe ButtonInput is for use in forms (with form-group, etc), if you need to use a ButtonGroup I'd just use the Button component directly and jsut add type='submit' like a normal button

**Comment by Industrial** [comment]
`ButtonGroup` is for displaying buttons side by side.. in a group. Whether that happens inside a `<form></form>` doesn't matter.

If I render a `<Button type="submit">` and then press enter inside one of my inputs (password field probably) then the whole page will refresh. I need a `<ButtonInput/>` there to submit the form properly it seems, but that one doesn't render the same as a `<Button/>`

**Comment by jquense** [comment]
> ButtonGroup is for displaying buttons side by side.. in a group. Whether that happens inside a <form></form> doesn't matter.

You missed my point. ButtonInput is a component _specifically_ for use with bootstrap form classes. It generates a `<button>` inside of a `<FormGroup>` and adds a label. Obviously that extra markup isn't going to work with button group. So you just use Button directly [__which is literally what ButtonInput does__](https://github.com/react-bootstrap/react-bootstrap/blob/master/src/ButtonInput.js#L16)

> If I render a <Button type="submit"> and then press enter inside one of my inputs (password field probably) then the whole page will refresh.

That is the form submitting and that's default browser behavior for forms that have any sort of submit button, input or not, react or not.

**Comment by Industrial** [comment]
You are right. I didn't have an `event.preventDefault()` on the handler of the form submit, and I can use a Button just fine.
