### ISSUE TITLE
NavItem doesn't pass along data-* attributes like MenuItem does

### ISSUE THREAD

**Issue by avk** [react-bootstrap/react-bootstrap#1593]
A NavItem such as:
```js
<NavItem
  data-method="delete" 
  href="/users/sign_out"
>
  Sign Out
</NavItem>
```

does not pass `data-method` to the resulting anchor tag whereas this MenuItem does:
```js
<MenuItem
  data-method="delete" 
  href="/users/sign_out"
>
  Sign Out
</MenuItem>
```

**Comment by taion** [comment]
`<NavItem>` spreads attributes into the `<li>` rather than the `<a>`. Wonder what we should do about that.

**Comment by avk** [comment]
Could attributes that are unique to <a> (e.g. href, target) be stripped out and spread only to <a>?

**Comment by taion** [comment]
They already are.

**Comment by avk** [comment]
Sorry @taion, then I don't understand [your previous comment](https://github.com/react-bootstrap/react-bootstrap/issues/1593#issuecomment-170729004).

**Comment by jquense** [comment]
The problem is that `data-*` attributes are not specific to links, so there is just as good of a reason to pass them to the `<li>` as the `<a>`

**Comment by avk** [comment]
How about supporting a child format like this then for custom `data-*` attributes?
```jsx
<NavItem>
   <a href="#" data-method="delete">Sign Out</a>
</NavItem>
```

Instead of doing what's expected, this currently generates two `<a>`s.

**Comment by taion** [comment]
Let's follow up in https://github.com/react-bootstrap/react-bootstrap/issues/629.
