### ISSUE TITLE
Modal does not render correctly on an isomorphic app.

### ISSUE THREAD

**Issue by bmamouri** [react-bootstrap/react-bootstrap#1594]
In an Isomorphic app, the component `Modal` does not render correctly when the server send the static version. I get the following errors:

```
Warning: ReactMount: Root element has been removed from its original container. New container: [object HTMLDivElement]

Warning: React can't find the root component node for data-reactid value `.1.$=11`. If you're seeing this message, it probably means that you've loaded two copies of React on the page. At this time, only a single copy of React can be loaded at a time.

Uncaught Invariant Violation: findComponentRoot(..., .0.0.0.0.0): Unable to find element. This probably means the DOM was unexpectedly mutated (e.g., by the browser), usually due to forgetting a <tbody> when using tables, nesting tags like <form>, <p>, or <a>, or using non-SVG elements in an <svg> parent. Try inspecting the child nodes of the element with React ID ``.

Uncaught TypeError: Cannot read property 'firstChild' of undefined
```

When the server does not send a static version, there is no error. Here is a very simplified version of the component:

```
class SignInUp extends React.Component {

    constructor() {
        super()
        this.state = { showSignIn: false, showSignUp: false }
    }

    signInClose() {
        this.setState( {showSignIn: false} )
    }

    signInOpen() {
        this.setState( {showSignIn: true} )
    }

    render() {
        const { showSignIn } = this.state

        return (
            <div>
                <Button bsSize='sm' onClick={this.signInOpen.bind(this)}>Sign In</Button>

                <Modal id="signIn" show={showSignIn} onHide={this.signInClose.bind(this)} animation={false}><Modal.Body>
                    Hello
                </Modal.Body></Modal>

            </div>
        )
    }
}
```

**Comment by taion** [comment]
Portal-rendered elements like modals need special handling if you want to render them on the server. I'd suggest just not rendering portals on the initial render (show them in `componentDidMount`) unless you're very familiar with how all the reconciliation stuff works.

**Comment by bmamouri** [comment]
So I think I need to create the `Modal` component in the `componentDidMount` event, find the DOM node of the button that open the dialog using `this.refs.element.getInputDOMNode()` and attach an event to show the dialog. How I should show the dialog thogh?

**Comment by jquense** [comment]
you can render the modal on the server jsut don't render it open.

**Comment by bmamouri** [comment]
Can you elaborate on this @jquense. How can I render the modal but not render it open?

**Comment by jquense** [comment]
Just set show to false, and don't toggle it to `true` until after componentDidMount() when you know you  are in a browser

**Comment by bmamouri** [comment]
I still get the same error. Here is my component:
```
class SignInUp extends React.Component {

    constructor() {
        super()
        this.state = { showSignIn: false }
    }

    componentDidMount() {
        let signInButton = this.refs.signInButton.getDOMNode()
        signInButton.addEventListener('click', this.signInOpen.bind(this))
    }

    signInClose() {
        this.setState( {showSignIn: false} )
    }

    signInOpen() {
        console.log('signInOpen')
        this.setState( {showSignIn: true} )
    }

    render() {
        const { showSignIn } = this.state

        return (
            <div>
                <Button ref='signInButton' bsSize='sm'>Sign In</Button>

                <Modal id="signIn" show={showSignIn} onHide={this.signInClose.bind(this)} animation={false}><Modal.Body>
                    Hello
                </Modal.Body></Modal>

            </div>
        )
    }
}
```

As you can see the `show` property is set to `false` by default. But I still get the following errors:

```
Warning: ReactMount: Root element has been removed from its original container. New container: [object HTMLDivElement]

Warning: ReactMount: Root element has been removed from its original container. New container: [object HTMLDivElement]

Warning: React can't find the root component node for data-reactid value `.0.0.0.0.0.0.$=12.0.$=11`. If you're seeing this message, it probably means that you've loaded two copies of React on the page. At this time, only a single copy of React can be loaded at a time.

Uncaught TypeError: Cannot read property 'firstChild' of undefined
```

**Comment by jquense** [comment]
Could the error be correct and you have two copies loaded? We actually specifcally test that this works in our test suite so I am a bit intrigued...

**Comment by bmamouri** [comment]
As far as I can see there is only one version. Though the `Modal` component is being wrapped inside another `Modal` component. I am not sure if this is the intended behaviour or not.

First time that I load the app:
![screen shot 2016-01-09 at 4 03 10 pm](https://cloud.githubusercontent.com/assets/6419173/12214511/a06aeda6-b6ea-11e5-867c-a6528aa8ea74.png)

After clicking the button for the first time:
![screen shot 2016-01-09 at 4 03 28 pm](https://cloud.githubusercontent.com/assets/6419173/12214513/af96f8b0-b6ea-11e5-878a-34ae3b59dfa9.png)

After closing the window:
![screen shot 2016-01-09 at 4 03 39 pm](https://cloud.githubusercontent.com/assets/6419173/12214514/b7a47bfe-b6ea-11e5-8f84-e9d25c39a1ce.png)

**Comment by azotova** [comment]
@bmamouri Have you solved this issue? I have exactly the same problem (and very similar code).

**Comment by kaktus42** [comment]
@bmamouri any news on this?

**Comment by azotova** [comment]
@kaktus42 In my case, the problem was solved after the upgrade to React v.15.0.
