### ISSUE TITLE
Invalid Peer

### ISSUE THREAD

**Issue by claughlin-r7** [react-bootstrap/react-bootstrap#1595]
Im trying to use react-bootsrap but keep getting issues with peer dependencies
```
npm ERR! peerinvalid The package react@0.14.3 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-bootstrap@0.28.2 wants react@>=0.14.0
```
I have react 0.14.3 installed this should match the peer requirement

**Comment by taion** [comment]
You're hitting weird npm2 dependency quirks. Wipe your `node_modules` and try again.
