### ISSUE TITLE
Can react-bootstrap work with existing bootstrap.js

### ISSUE THREAD

**Issue by fantasy8-me** [react-bootstrap/react-bootstrap#1596]
I am working on a react project that using [alpacajs](http://www.alpacajs.org/index.html), `alpacajs` will load original bootstrap.js, may I know whether loading of original bootstrap.js has any impact to react-bootstrap?

I guess if we don't include `data-toggle`, e.g. `data-toggle="dropdown"`, we might be safe even we include some bootstrap js functions. But not whether this(an env with original bootstrap.js) is being considered as a valid use case.

**Comment by taion** [comment]
Yes - it's orthogonal; R-B manages its components, while anything you run Bootstrap JS on will get managed by Bootstrap JS. Just don't overlap them.
