### ISSUE TITLE
using custom li element not NavItem

### ISSUE THREAD

**Issue by Kepro** [react-bootstrap/react-bootstrap#1597]
Hi, due to router i need call
````
<Link to="/home">Home</Link>
````
so now i using 
````
<li>
  <Link to="/home">home</Link>
</li>
````

but after click dropdown not closing

or something like <NavItem><Link to="/home">Home</Link></NavItem>
if there are no href param or something, or create some way how to use in this case...

**Comment by jquense** [comment]
what dropdown? you are using NavItems or do you mean MenuItem? in either case you might want to just use react-router-bootstrap

**Comment by Kepro** [comment]
och sorry i forget, 
Nav -> NavDropdown -> NavItem and on click NavItem close the NavDropdown
but if i have custom item in NavDropdown like my <li><Link ... then not closing

**Comment by taion** [comment]
Use react-router-bootstrap for React Router compat.

**Comment by ansonkao** [comment]
I'm having the same issue in #1882.
