### ISSUE TITLE
react-bootstrap, lodash, and factor-bundle not playing well together

### ISSUE THREAD

**Issue by micah-bloomerang** [react-bootstrap/react-bootstrap#1598]
I've been working on this problem for a couple of days, and I think I finally have it narrowed down. If I'm using factor-bundle where one file contains a reference to lodash and the other file contains a reference to react-bootstrap, I get the following error:

    TypeError: Cannot read property '0' of undefined

It's hard to tell if this is an issue with factor-bundle or if it's an issue with react-bootstrap. Here is what is needed to reproduce:

    npm install factor-bundle lodash react-bootstrap

**index.html**

    <html>
    <body>
    <script type="text/javascript" src="bundle/common.js"></script>
    <script type="text/javascript" src="bundle/index.js"></script>
    </body>
    </html>

**main/index.js**

    require('../node_modules/react-bootstrap');

**main/bad.js**

    require('../node_modules/lodash/object/keys');

Build with:

    browserify main/index.js main/bad.js -p [ factor-bundle -o bundle/index.js -o bundle/bad.js ] -o bundle/common.js

**Comment by jquense** [comment]
I don't know that any of use are experts (or even notives) at browserify, we tend to use webpack, but I am not sure how our package could be at fault since we just export normal common js modules in the npm version.

**Comment by micah-bloomerang** [comment]
Ok, I'll close out the issue and see if I get help from substack. Thanks!

**Comment by taion** [comment]
Separately, if you have `node_modules` explicitly in your `require` – that's extremely suspicious.
