### ISSUE TITLE
Invalid HTML

### ISSUE THREAD

**Issue by dlakata** [react-bootstrap/react-bootstrap#1600]
It seems that a lot of the HTML that react-bootstrap renders isn't valid: https://validator.w3.org/nu/?doc=https%3A%2F%2Freact-bootstrap.github.io%2Fcomponents.html. I'd perhaps be interested in helping fix this, but this seems like a big project, and I'd have no idea where to start.

Specifically, I realized this when react-bootstrap rendered ```<Input type="select"></Input>``` as ```<select type="select" ...></select>```, since the type attribute isn't valid for <select> elements. I tried simply deleting ```type``` from ```this.props```, but I don't think it's that simple.

**Comment by taion** [comment]
The `<Input>` issue is resolved now. Let's track other cases as they come up.
