### ISSUE TITLE
Can I customize Carousel-indicators in react-bootstrap

### ISSUE THREAD

**Issue by maxluk12** [react-bootstrap/react-bootstrap#1601]
I am trying to customize the carousel-indicators including some texts, and make it look like a button with text, but react render 'ol' tag into a new CarouseItem and no redirect function
``` javascript
<Carousel id="sampleSlide" indicators={false}>
  <ol className="carousel-indicators">
    <li data-target='#sampleSlide' data-slide-to="0" className="active"></li>
    <li data-target= '#sampleSlide' data-slide-to="1"></li>
  </ol>
  <CarouselItem>
    <div className="itemContent">
      Hello World
    </div>
  </CarouselItem>
  <CarouselItem>
    <div className="itemContent">
      Hello World
    </div>
  </CarouselItem>
</Carousel>
```
Is there any way to customize it or any other method to do so?

**Comment by taion** [comment]
http://react-bootstrap.github.io/components.html#carousels-props

Use `prevIcon` and `nextIcon`.

**Comment by maxluk12** [comment]
Thanks Talon, but if i want to remain the nextIcon and prevIcon, just add a unchanged button like the indicator but with text in the button?

**Comment by mika75** [comment]
Hello

could you show your import of CarouselItem.
I have lot of problem with CarouselItem and Carousel.Item

Thank for your help

**Comment by gabiseabra** [comment]
This is still an issue for me. I'd like to have thumbnails for indicators, but it doesn't seem possible to edit the indicator list items in any way.

**Comment by xavierartot** [comment]
The link is broke: http://react-bootstrap.github.io/components.html#carousels-props

**Comment by sateesh2020** [comment]
Can customize like this. 
```jsx
import React, { Component } from 'react';
import classnames from 'classnames';
import {
  Carousel,
  CarouselItem,
} from 'reactstrap';

export default class ProductCarousel extends Component {
  constructor(props) {
    super(props);
    this.state = { activeIndex: 0 };
    this.next = this.next.bind(this);
    this.previous = this.previous.bind(this);
    this.goToIndex = this.goToIndex.bind(this);
    this.onExiting = this.onExiting.bind(this);
    this.onExited = this.onExited.bind(this);
  }

  onExiting() {
    this.animating = true;
  }

  onExited() {
    this.animating = false;
  }

  goToIndex(newIndex) {
    if (this.animating) return;
    this.setState({ activeIndex: newIndex });
  }
  next() {
    let { items } = this.props;
    if (this.animating) return;
    const nextIndex =
      this.state.activeIndex === items.length - 1
        ? 0
        : this.state.activeIndex + 1;
    this.setState({ activeIndex: nextIndex });
  }

  previous() {
    let { items } = this.props;
    if (this.animating) return;
    const nextIndex =
      this.state.activeIndex === 0
        ? items.length - 1
        : this.state.activeIndex - 1;
    this.setState({ activeIndex: nextIndex });
  }
  render() {
    const { activeIndex } = this.state;
    let { items } = this.props;
    return (
      <Carousel
        activeIndex={activeIndex}
        next={this.next}
        previous={this.previous}
      >
        {items.map(item => {
          return (
            <CarouselItem
              onExiting={this.onExiting}
              onExited={this.onExited}
              key={item.src}
            >
              <img
                className="d-block w-100"
                src={item.src}
                alt={item.altText}
              />
            </CarouselItem>
          );
        })}
        <ol className="carousel-indicators">
          {items.map((item, index) => {
            return (
              <li
                key={index}
                onClick={() => this.goToIndex(index)}
                className={classnames({ active: activeIndex === index })}
                style={{ backgroundImage: `url(${item.src})` }}
              />
            );
          })}
        </ol>
      </Carousel>
    );
  }
}
```

**Comment by hungvu193** [comment]
I think that would be nice if there 's some props like:
indicatorVisible or indicatorComponent, I use styled-component and it's really hard to customize.

**Comment by Tanish2000** [comment]
If you are using react-bootstrap and want to change the next and previous icons on Carousel, then use the following CSS declarations.

![Screenshot (171)](https://user-images.githubusercontent.com/68784397/109423073-24c0b900-7a04-11eb-9470-3a7d266003c0.png)

**Comment by Siddharth2212** [comment]
This is how I did it:
`.carousel-indicators li {
border-top: unset;
width: 10px;
border-bottom: unset;
border: 1px solid transparent;
border-left-width: 0;
border-right-width: 0;
border-radius: 10px;
background-color: rgba(169, 29, 42, 0.4);
height: 10px;
width: 20px;}                                                  
                                                               
.carousel-indicators .active {
border-top: unset;
border-bottom: unset;
border: 1px solid transparent;
border-left-width: 0;
border-right-width: 0;
border-radius: 10px;
background-color: #A91D2A;
height: 10px;
width: 50px}`

**Comment by Siddharth2212** [comment]
This is how I did it
`             .carousel-indicators li {
border-top: unset;
width: 10px;
border-bottom: unset;
border: 1px solid transparent;
border-left-width: 0;
border-right-width: 0;
border-radius: 10px;
background-color: rgba(169, 29, 42, 0.4);
height: 10px;
width: 20px;}  
              .carousel-indicators .active {
border-top: unset;
border-bottom: unset;
border: 1px solid transparent;
border-left-width: 0;
border-right-width: 0;
border-radius: 10px;
background-color: #A91D2A;
height: 10px;
width: 50px}`
