### ISSUE TITLE
Could you please expose the FormGroup component to the public api?

### ISSUE THREAD

**Issue by jonathaningram** [react-bootstrap/react-bootstrap#1610]
Per https://github.com/react-bootstrap/react-bootstrap/issues/523#issuecomment-93862709 which went unresponded.

> We did not expose that component to the public api. The discussion for which is in #342. What are you trying to change about Input to necessitate a direct copy?

I'd like to use my own help component opposed to the core one and would prefer to just use the internal `FormGroup` rather than create my own (despite it being a really basic component). E.g.

```
import { FormGroup, Input } from 'react-bootstrap'

<FormGroup>
    <label className="control-label">Name</label>
    <Input standalone/>
    <small>The name.</small>
</FormGroup>
```

If you're against this, no probs I'll just create my own copy of `FormGroup`.

**Comment by taion** [comment]
We're actually considering mostly replacing the current input API with something like what you have above, excepting only the basic "labelled input" case.

**Comment by taion** [comment]
Let's track this on #342.
