### ISSUE TITLE
Option to prevent closing the open panel in accordion

### ISSUE THREAD

**Issue by chadmoller** [react-bootstrap/react-bootstrap#1613]
Is there an option that would allow me to always keep one panel open in an accordion, so that they could never close all the sections? If not, could one be added?

Thanks!
Chad

**Comment by jquense** [comment]
There isn't a specific option for that, but you can build your own accordian with that behavior fairly easily. take a look at the controlled panel example to see how to control the open/close state of a bunch of panels: http://react-bootstrap.github.io/components.html#panels-controlled
