### ISSUE TITLE
Accessing modal in tests via refs

### ISSUE THREAD

**Issue by benkeen** [react-bootstrap/react-bootstrap#1617]
Hi! 

We just upgraded to the 0.28.2 and React 14 and our unit tests started failing for the React Bootstrap modals. Specifically, it's no longer able to find the Modal element. Here's some sample code:

```javascript
it('onClose called by top (x)', function () {
  var spy = sinon.spy();
  var el = TestUtils.renderIntoDocument(
    <CustomModalComponent visible={true} onClose={spy} onSave={stub} />,
    container
  );
  var modal = TestUtils.findRenderedComponentWithType(el, ReactBootstrap.Modal);
  var modalEl = ReactDOM.findDOMNode(modal.refs.modal);

  TestUtils.Simulate.click($(modalEl).find('.close')[0]);
  assert.ok(spy.calledOnce);
});
```

The problem is the `modal.refs.modal` part. With the old code that contained a reference to the modal element, in the new code console.logging modal.refs shows an empty object. 

Did something change in a recent version to prevent accessing that modal via refs? Thanks!

**Comment by jquense** [comment]
Nothing changed to prevent it, however we reworked the Modal structure so the refs are a bit different. Check the source/our tests to see what the updated refs are.
