### ISSUE TITLE
NavItem allowTransitions

### ISSUE THREAD

**Issue by manodupont** [react-bootstrap/react-bootstrap#1618]
Is there any way that we can manage the "allow transitions" on a href on a NavItem ?

I don't want the page to fully reloaded when i click on a NavItem href.

How do i do that ?

**Comment by taion** [comment]
You seem to be very confused about how HTML5 history and client-side routing work. Take a look at react-router-bootstrap.

**Comment by manodupont** [comment]
Yes I am.

And its exactly why I am asking a question.

Thanks for clarifying!
