### ISSUE TITLE
How to Integrate Bootstrap Themes

### ISSUE THREAD

**Issue by ziruixiao** [react-bootstrap/react-bootstrap#1619]
Hi, I am using ```react-bootstrap``` in my app and have the basic layout of my web app completed. I am now looking to apply a third-party theme, such as one on https://bootswatch.com/ or https://wrapbootstrap.com/

I was wondering what the best practice is for using a third-party theme. Most of the ones I have found online give you a single CSS file with instructions to replace the default bootstrap CSS file. However, I don't think this can be applied to ```react-bootstrap``` as easily.

Right now, I'm thinking of using the ```className``` prop and including the non-react-bootstrap class name on each one. For example, it'd look like the following

````
<Button className="customButtonFromTheme"> Here's a formatted button. </Button>
````

Is there a better way to do this? Thanks!

**Comment by taion** [comment]
React-Bootstrap has no opinions on how you get the CSS in there. Replacing the main Bootstrap CSS file is a totally viable way to use a theme.

**Comment by hz0324** [comment]
What about the bootstrap component that use a self-defined class name? For example, in one Material bootstrap theme, it has some class named as "raisedButton". I dont think swapping in the theme css file can get this done. Is there any way to convert this kind of bootstrap class to react-bootstrap component?

Thanks.

**Comment by taion** [comment]
Pass in a custom `bsClass`

**Comment by johnnabil** [comment]
Here can i find the main bootstrap css ? i need to update this file to see the updated theme

**Comment by wzup** [comment]
@taion 

> Replacing the main Bootstrap CSS file is a totally viable way to use a theme.

Ok, how to do it?

**Comment by ifgeny87** [comment]
You can download here http://getbootstrap.com/docs/3.3/getting-started/#download
Then change less files. Then compile with less. Then use in your html page.

**Comment by mojave27** [comment]
Is there anything more than just switching the css files?  I swap out original bootstrap.min.css with one I downloaded from bootswatch.com, (i tried both yeti and superhero).  Most of the styling looks correct, but a lot of it is busted.  (Navbar, Badge, Breadcrumb, etc)

Before with out-of-the-box bootstrap.min.css:
<img width="558" alt="screen shot 2018-05-31 at 5 10 06 pm" src="https://user-images.githubusercontent.com/9810186/40814517-8e4d4ab8-64f5-11e8-8aa4-d863a4ec3475.png">

After with bootswatch's superhero bootstrap.min.css:
<img width="853" alt="screen shot 2018-05-31 at 5 09 34 pm" src="https://user-images.githubusercontent.com/9810186/40814527-9ae52480-64f5-11e8-8cd7-05dc01605c5a.png">

**Comment by taion** [comment]
that's really about it – you just need to make sure you have the same selectors. also, it has to be bootstrap v3 until we cut the v4-compatible release

**Comment by mojave27** [comment]
@taion Thanks!  I had downloaded the v4 version of the bootswatch theme.  Switching to v3 solved it.

**Comment by JosephAkayesi** [comment]
Personally I use the CDN in the index page and it works perfectly well. I don't even npm install bootstrap or bootswatch. Another work around is tto just copy the bootstrap.min.css into App.css or index.css and it works perfectly well.
Since react is tanspiled to vanilla JS is works without any problem.
