### ISSUE TITLE
Modal gets appended twice to body

### ISSUE THREAD

**Issue by reinelmp** [react-bootstrap/react-bootstrap#1621]
I've just followed the Modal basic example showed in Components page on React-Bootstrap site and somehow the modal gets appended twice to the body element

**Comment by taion** [comment]
Does this happen on the components page?

**Comment by reinelmp** [comment]
No it doesn't

**Comment by reinelmp** [comment]
I'm using the latest release

**Comment by taion** [comment]
If it's not happening on the components page, then that points to some sort of error in your code. Double-check that you're following the example correctly.

**Comment by reinelmp** [comment]
Thanks @taion, I was calling the function that renders the modal twice. Sorry for the inconvenience, I'll double check next time before opening an issue.
