### ISSUE TITLE
Popover that shows on OverlayTrigger on hover, how to keep it displayed while hovering over the popover?

### ISSUE THREAD

**Issue by mezod** [react-bootstrap/react-bootstrap#1622]
There are two behaviours: 
- when hovering OverlayTrigger: the popover shows up, but disappears as soon as you stop hovering the OverlayTrigger
- when clicking OverlayTrigger: the popover shows up and stays displayed

I know this is not part of react-bootstrap but how would you go about adapting it so that:
when hovering the OverlayTrigger the popover shows up, and if hovering the popover, the popover doesn't disappear.

I am trying to mimic twitters/facebook's preview for users, you hover a user name and you get a Popover that doesn't disappear.

I would just appreciate any ideas on how to approach this problem, I don't expect a solution, just some kind of ideas of how should I go about overriding the default react-bootstraps' Popover's behaviour. Thank you!

**Comment by taion** [comment]
Take a look at how dropdowns work. You have to nest the overlay under the DOM node that you attach the mouseenter/mouseleave triggers to.

**Comment by jquense** [comment]
Also I believe there is a closed PR that wanted to add this behavior, though it was a bit integrated

**Comment by mezod** [comment]
what you say is without using OverlayTrigger, right?

**Comment by mezod** [comment]
hmm gonna try to find it and see how he did it, because I got no clue of how to...there are some thing doing something similar but not sure how to put them together...

**Comment by Paul-DS** [comment]
I succeeded to fix the problem in my case by implementing my own trigger component.

The code is the following:

hoverable-popover-trigger.jsx:
--------------------------------

```
import React from "react";
import PropTypes from "prop-types";
import classNames from "classnames";

// Custom solution to manage the hovering of a bootstrap popover.
//
// In the basic solution (using an OverlayTrigger), when trying to select anything in the popover,
// the popover disapear (because the cursor is not in the triggered element anymore).
// See https://github.com/react-bootstrap/react-bootstrap/issues/1622
class HoverablePopoverTrigger extends React.PureComponent {
    constructor(props) {
        super(props);
        this.state = {popoverFullyHidden: true, popoverDisplayed: false};

        this.hideTimeout = null;
    }

    handleMouseEnter() {
        this.setState({popoverFullyHidden: false, popoverDisplayed: true});
        
        if (this.hideTimeout) {
            clearTimeout(this.hideTimeout);
            this.hideTimeout = null;
        }
    }

    handleMouseLeave() {
        this.setState({popoverDisplayed: false});
        this.hideTimeout = setTimeout(() => this.setState({popoverFullyHidden: true}), 250);
    }

    handleClickPopover(e) {
        e.stopPropagation();
    }

    render() {
        var popoverClassName = classNames(
            this.props.popover.props.className,
            this.props.placement,
            "fade",
            {"in": this.state.popoverDisplayed},
            {"hidden": this.state.popoverFullyHidden}
        );

        return (
            <div className="hoverable-popover-trigger" onMouseEnter={e => this.handleMouseEnter(e)} onMouseLeave={e => this.handleMouseLeave(e)}>
                {this.props.children}
                {React.cloneElement(this.props.popover, {className:popoverClassName, onClick: e => this.handleClickPopover(e)})}
            </div>
        );
    }
}

HoverablePopoverTrigger.displayName = "HoverablePopoverTrigger";

HoverablePopoverTrigger.propTypes = {
    children: PropTypes.element.isRequired,
    overlay: PropTypes.oneOfType([PropTypes.func, PropTypes.element.isRequired]),
    placement: PropTypes.oneOf(['top', 'right', 'bottom', 'left'])
};

HoverablePopoverTrigger.defaultProps = {
    placement: 'right'
};

export default HoverablePopoverTrigger;
```

hoverable-popover-trigger.less:
--------------------------------
```
.hoverable-popover-trigger {
    position: relative;

    .popover {
        left: auto;
        top: auto;
        bottom: auto;
        right: auto;
        white-space: nowrap;

        &.left {
            top: 50%;
            transform: translateY(-50%);
            right: 100%;
        }

        &.right {
            top: 50%;
            transform: translateY(-50%);
            left: 100%;
        }

        &.top {
            left: 50%;
            transform: translateX(-50%);
            bottom: 100%;
        }

        &.bottom {
            left: 50%;
            transform: translateX(-50%);
            top: 100%;
        }
    }
}
```

Usage:
--------
```
<div>
    <HoverablePopoverTrigger placement="right" popover={(<Popover>The popover content</Popover>)}>
        <div>The initial content</div>
    </HoverablePopoverTrigger>
</div>
```

---------------------------

As @taion indicates before, this component integrate the popover inside the element that contains the triggers (onMouseEnter and onMouseLeave), so the final DOM looks like that:

```
<container on which the onMouseEnter and onMouseLeave events are applied>
    <content to display />
    <popover />
</container>
```


In this case, hovering the popover doesn't trigger the "onMouseLeave" event on the container.

This component does manage only the "hover" trigger, and the "fade" animation. If you want to use other triggers/animations, use delays etc... you should modify the code.

**Comment by lou** [comment]
I did a little Component to handle this exact use case.
https://gist.github.com/lou/571b7c0e7797860d6c555a9fdc0496f9

**Comment by ChrisJohDev** [comment]
I used the "show" property of OverlayTrigger instead of the "trigger" property. Then i attached onMouseEnter and onMouseLeave to a show state.

`
import React, { useState, useEffect, Profiler, useRef } from 'react';
import Nav from 'react-bootstrap/Nav';
import { OverlayTrigger, Popover } from 'react-bootstrap';

const Cart = ({ cartData }) => {
    const [show, setShow] = useState(false);
    const handleOnMouseEnter = () => {
        setShow(true);
    }
    const handleOnMouseLeave = () => {
        setShow(false);
    }
    const ref = useRef(null);
    return (
        <>
            <OverlayTrigger
                //trigger={['hover', 'focus']}
                show={show} // Control trigger behavior with show instead of trigger.
                key='bottom'
                placement='bottom-end'
                container={ref}
                overlay={
                    <Popover id={`popover-positioned-bottom`} onMouseEnter={handleOnMouseEnter} onMouseLeave={handleOnMouseLeave}>
                        <Popover.Header as="h4">Cart Items</Popover.Header>
                        <Popover.Body>
                            <div>Some code or component to show on hover</div>
                        </Popover.Body>
                    </Popover>
                }
            >
                <div className="cart-wrapper" ref={ref} onMouseEnter={handleOnMouseEnter} onMouseLeave={handleOnMouseLeave}>
                            
                         The text or components to hover over to display the Poppover.
                </div>
            </OverlayTrigger>
    );
}`
