### ISSUE TITLE
Prevent dropdown from closing on click

### ISSUE THREAD

**Issue by jonathanasquier** [react-bootstrap/react-bootstrap#1624]
Hi,
I want to [prevent the dropdown from closing on click](http://stackoverflow.com/questions/21982308/bootstrap3-keep-the-dropdown-menu-open-after-click-on-the-item).
I tried using `e.stopPropagation()` in the onClick function of the MenuItem component with no results.
Is there a simple way I can do that?
Note that my onClick function also dispatches a flux action which sets new props to the component and re-renders it.

Thanks!

**Comment by taion** [comment]
Dupe https://github.com/react-bootstrap/react-bootstrap/issues/1490

**Comment by seyyedmojtaba72** [comment]
$("[data-toggle=dropdown]").prop('onclick', null).off('click');
    $("[data-toggle=dropdown]").click(function (e) {
        e.preventDefault();
        e.stopPropagation();

        let el = $(this);
        let expanded = el.attr("aria-expanded") || false;
        if (!expanded) {
            $(this).dropdown('toggle');
        }

        el.attr("aria-expanded", !expanded);
    })
