### ISSUE TITLE
Overlay not positioning correctly

### ISSUE THREAD

**Issue by jamie-sparked** [react-bootstrap/react-bootstrap#1626]
I'm working with react-bootstrap overlays and have been unable to get my overlay to position correctly. I've stepped through the code a few times and tracked it down to the `position` method in dom-helpers. I hope this is the right place to post this issue.

The code I'm stepping through is the browser global build here: https://cdnjs.cloudflare.com/ajax/libs/react-bootstrap/0.28.2/react-bootstrap.js.

My target node is position "fixed", so after line 14303 (actually [this one](https://github.com/react-bootstrap/dom-helpers/blob/master/src/query/position.js#L18) in the source), the offset looks like this, in Chrome:

```
offset: ClientRect
bottom: 545
height: 50
left: 497.5
right: 547.5
top: 495
width: 50
```

The width and height are fine here, but then the `babelHelpers._extends` on line 14315 seems to erase them. After stepping out of the function, on line 14140 ([this one](https://github.com/react-bootstrap/react-overlays/blob/master/src/utils/overlayPositionUtils.js#L30) in the source), the offset looks like this:

```
offset: Object
left: 497.5
top: 495
```

It seems likely that the issue is with the babel helpers, but I thought maybe someone here could help.

I worked up an isolated [fiddle](https://jsfiddle.net/zx03nexL/) to demonstrate the problem.

**Comment by nguyendh2601** [comment]
Hi @jamie-sparked, try removing container prop `container={this}` of `Overlay` component

**Comment by flynfish** [comment]
I'm having the same issue.  My form inputs are initially hidden and when they are shown and you focus into one of them, the popover is in the wrong place. If you then focus out and back in, it's in the correct place.

If I add `shouldUpdatePosition={true}` to OverlayTrigger, it will show the popover in the wrong place, blink and then it appears in the correct position. 

This isn't ideal since there is a blinking effect and it's jarring.

**Comment by ShashankaNataraj** [comment]
@nguyendh2601 If I remove prop `container={this}` my textboxes dont receive focus! I followed @jquense suggestion at https://github.com/react-bootstrap/react-bootstrap/issues/2063 to add `container={this}`

> Without `container={this}`, the textboxes in my popover dont receive focus
> If I add `container={this}` the textboxes receive focus but the popover shows up at the wrong place!

**Comment by ShashankaNataraj** [comment]
Any updates on this?

**Comment by geminiyellow** [comment]
same promblem, remove `container={this}` cannot reset overlay position when resize.

**Comment by AndrewStobie** [comment]
I am having a similar problem removing container={this} makes it so my overlays appear in the same place and don't resize.

**Comment by Phuhwei** [comment]
Same issue here, removing the container={this} is not a perfect solution.
