### ISSUE TITLE
Expose styleMaps.

### ISSUE THREAD

**Issue by asaf** [react-bootstrap/react-bootstrap#1628]
Hey,

I'd like to add new styles to the Button component for every possible bootstrap standard styles,
i.e: `default-custom`, `primary-custom`, etc..

I see styles can be added by:
`utils.bootstrapUtils.addStyle(Button, ['default-custon']);`

But I need access to the styleMaps (was exposed in ver 27.x), is it currently possible or there's another API to read styles/sizes, etc?

Same goes for CLASSES, I need access to the bootstrap class name of `Button`,
I was referring to `styleMaps.CLASSES.button` which doesn't exist any longer,

Thanks.

**Comment by taion** [comment]
I think you just use what's in `bootstrapUtils`.

**Comment by jquense** [comment]
yeah I don't think the we are going to expose that since its really private implementation details. scope of "every possible style" is really pretty small so I feel fine just saying hard code those in your code instead of trying to loop through what we have.

**Comment by asaf** [comment]
`bootstrapUtils` doesn't give much, and I don't think these are really 'implementation details' rather bootstrap standards, I find myself duplicating all those consts that live in `styleMaps.js` and it feels silly.
