### ISSUE TITLE
React Bootstrap NavDropdown throwing error onclick

### ISSUE THREAD

**Issue by ArchanaKalidoss** [react-bootstrap/react-bootstrap#1629]
Hi,
I am using below versions of react and react-bootstrap but on click of "NavDropdown" I an getting the error "TypeError: _reactDom2.default is undefined" on the console. From the file react-bootstrap.inc.js from the below code

Dropdown.prototype.componentWillUpdate = function componentWillUpdate(nextProps) {
if (!nextProps.open && this.props.open) {
this._focusInDropdown = _domHelpersQueryContains2'default';
}
};

Versions I am using : react.inc.js - v0.13.3, react-bootstrap.inc.js - 0.27.3-0,
react-dom.inc.js - v0.14.0.

Kindly inform what is the issue.

**Comment by taion** [comment]
You're using a bunch of mutually incompatible versions; you should probably just use the latest version of everything, or at least pay attention to which versions of React-Bootstrap, React, and ReactDOM are mutually compatible.
