### ISSUE TITLE
Generic validator function as props for input elements

### ISSUE THREAD

**Issue by lalala** [react-bootstrap/react-bootstrap#1630]
Why not add a prop on the input component that takes a generic validator function, which returns e.g. an error message or null/true if valid?

Consider this:

````
const helloValidator = value => {
  if (value == "hello") {
    return true;
  } else {
    return 'Value must be "hello"';
  }
}

<Input type="text" validator={ helloValidator } />
````

The input field could then have a standard error message under it, alternatively, be shown with the bsStyle set to error, or some combination thereof (preferrably configurable...).

If I implement this feature in a pull request, is that something that would be accepted?

**Comment by taion** [comment]
This is out of scope. Use something like https://github.com/jquense/react-formal.

**Comment by lalala** [comment]
Without this kind of functionality, the forms are pretty useless. It would be such an easy and light-weight feature to implement. I mean, if you can't validate forms in a sensible way, why even include them in the first place?

**Comment by jquense** [comment]
as the author of a few form validation libraries I can quite confidently say that nothing about form validation is light-weight. validation, in the general case, is really non trivial, even with a simple proposal such as this. And while form validation is generally needed, as taion said it's really out of scope for this library. bootstrap just aims to  provide some helpful styling for form inputs and layout. 

We do however provide all the hooks needed for you to implement what you need, or use the inputs with one of the many other form validation libraries.

**Comment by jgautheron** [comment]
@taion @jquense Any example on how to combine `react-formal` with the latest `react-bootstrap`? that would be really helpful.
