### ISSUE TITLE
What is the standard process for apply a customized bootstrape theme to react-bootstrap?

### ISSUE THREAD

**Issue by xinghengwang** [react-bootstrap/react-bootstrap#1633]
From the getting started section QUOTE:  

"First add the Bootstrap CSS to your project; check here if you have not already done that. Note that:
Because many folks use custom Bootstrap themes, we do not directly depend on Bootstrap. It is up to you to to determine how you get and link to the Bootstrap CSS and fonts.
React-Bootstrap doesn't depend on a very precise version of Bootstrap. Just pull the latest and, in case of trouble, take hints on the version used by this documentation page. Then, have Bootstrap in your dependencies and ensure your build can read your Less/Sass/SCSS entry point."

But I can't find any intructions on how exactly to apply a cutomized theme (for example, one I got from wrapbootstrap or something). 

I am using the react redux universal hot example.  https://github.com/erikras/react-redux-universal-hot-example

Anyone have any insights?

**Comment by jquense** [comment]
We don't provide any css so the way you use a theme will be the same for react-bootstrap as plain bootstrap. The only exception is that themes that provide extensions or additions to the JavaScript won't be compatible. But if its just styles, just include the styles according to the the theme's instructions
