### ISSUE TITLE
update lodash-compat

### ISSUE THREAD

**Issue by olmobrutall** [react-bootstrap/react-bootstrap#1635]
Hi guys,

My issue: react-bootstrap depends on lodash-compat that has this function.

```
	/**
	 * Checks if `value` is a host object in IE < 9.
	 *
	 * @private
	 * @param {*} value The value to check.
	 * @returns {boolean} Returns `true` if `value` is a host object, else `false`.
	 */
	var isHostObject = (function() {
	  try {
	    Object({ 'toString': 0 } + ''); <-------- ANNOYING EXCEPTION HERE 
	  } catch(e) {
	    return function() { return false; };
	  }
	  return function(value) {
	    // IE < 9 presents many host objects as `Object` objects that can coerce
	    // to strings despite having improperly defined `toString` methods.
	    return typeof value.toString != 'function' && typeof (value + '') == 'string';
	  };
	}());
```

The problem is that this function throws and catches an exception every single time you start the application, even if you don't use it. 

I usually work with `Pause On Caught Exception` in Chrome, so this behavior is killing my nerves. I've switched to bluebird promises to be able to work without this checkbox. It's ok but there's nothing like having the debugger running just when an exception is thrown, so I've re-enabled it again. 

I've checked lodash and looks like in the [new implementation](https://github.com/lodash/lodash/blob/24ffe8650ae33f4701a0a9cc837276048666bcc3/dist/lodash.core.js) the function is not eagerly evaluated, so probably the issue will be fixed.

Could you please consider updating updating (or removing) lodash? 

Thanks for the great work :+1:

**Comment by taion** [comment]
We're not removing lodash. We're also keeping lodash-compat until we can officially drop IE8 support.

**Comment by olmobrutall** [comment]
And what are you guys doing? Suffering the same issue or there is a workaround?

**Comment by taion** [comment]
I don't generally pause on caught exceptions, and otherwise I don't get too bothered by this.

**Comment by olmobrutall** [comment]
No luck getting the function back-ported to lodash-compat and React [is removing IE8 compat](https://facebook.github.io/react/blog/2016/01/12/discontinuing-ie8-support.html), so I'll patiently wait for react-bootstrap updating to React 0.15 and lodash v4.

**Comment by jameswomack** [comment]
It seems to have updated to React 15 but is still using Lodash compat, which is discontinued
https://github.com/react-bootstrap/react-bootstrap/blob/master/package.json
https://github.com/lodash-archive/lodash-compat

**Comment by taion** [comment]
It's at the same release as any Lodash v3. I don't see a reason to upgrade until we e.g. drop React v0.14 support.
