### ISSUE TITLE
Collapsing animation doesn't work properly on Safari

### ISSUE THREAD

**Issue by northerneyes** [react-bootstrap/react-bootstrap#1638]
http://react-bootstrap.github.io/components.html#transitions-collapse

Also in browsers (like Chrome, Safari) on iOS too

**Comment by Sinistralis** [comment]
To clarify, the slide down animation works properly, however sliding up fails to work and the element just pops out of existance. (Basically it's being hidden immediately with no animation to resolve it).

**Comment by Sinistralis** [comment]
I've tracked this down to either handleExit or handleExiting in the Collapse.js file. If I play with the values in this function, Chrome and Safari produce drastically different results (Chrome on Windows, Safari on Mac). There's an inconsistency here somewhere but I'm not sure where. I'm compared the code being generated here to the main bootstrap library and it seems pretty consistent so I don't think that's the issue.

I also compared the collapse classes to the bootstrap source and those are not different either.

I'll look at this more tommorrow, but so far I have no idea whats causing the inconsistency here.

**Comment by taion** [comment]
I wonder if this could be fixed by https://github.com/react-bootstrap/react-overlays/pull/60.

**Comment by Sinistralis** [comment]
I'll load it up and try it out once I get home. Thanks for the reference
link.

**Comment by Sinistralis** [comment]
Great news. I just copied those changes over locally and it solved the problem. The transition is now happening smoothly on Mac OSX Safari. I don't have an iOS device to test it on there unfortunately though.

**Comment by taion** [comment]
It's probably the same thing. Thanks!

**Comment by northerneyes** [comment]
Still doesn't work in Safari

**Comment by andrebower** [comment]
Using 0.29.5 and still not working in Mac Safari and iOS Safari

**Comment by kazazor** [comment]
There is an open issue for that here: https://github.com/react-bootstrap/react-bootstrap/issues/1841
