### ISSUE TITLE
How can I add a button in panel-heading with pull-right

### ISSUE THREAD

**Issue by sarike** [react-bootstrap/react-bootstrap#1641]
I want to render a panel like this:

```html

<div class="panel panel-default">
    <div class="panel-heading">
        Hello
        <a class="pull-right" href="#">ADD</a>
    </div>
    <div class="panel-body"></div>
</div>
```

But, the property `header` always be rendered as `.panel-title`.

How can I render a button in the panel-heading with pull-right class out of the `.panel-title`?

Thanks.

I'm sorry for my poor English.

**Comment by ajbowler** [comment]
+1

I would greatly appreciate the ability to do something like this (regular Bootstrap), if it isn't already supported.
![image](https://cloud.githubusercontent.com/assets/6600392/12937687/cbaaf0c6-cf70-11e5-8cf9-da2bea3f2d4e.png)


If this actually is supported, can someone point me in the right direction? The docs don't say anything about it.

**Comment by taion** [comment]
Probably will be handled by https://github.com/react-bootstrap/react-bootstrap/issues/983

**Comment by chsir17** [comment]
I am really late to this but in case someone else is looking for an answer like I was, here's what fixed it for me: [link](https://stackoverflow.com/questions/18963881/bootstrap-3-panel-header-with-buttons-wrong-position/23831762#23831762)

**Comment by vturcnau** [comment]
dasda
