### ISSUE TITLE
Set Modal custom size?

### ISSUE THREAD

**Issue by rulyotano** [react-bootstrap/react-bootstrap#1643]
I need to create a bootstrap modal, but with a custom size, for instance "xl". How can I do it??? Thanks

**Comment by jquense** [comment]
http://react-bootstrap.github.io/components.html#modal-custom-sizing

**Comment by rulyotano** [comment]
Thanks! I check it after posting this post, thanks for the answer.

**Comment by MidnightJava** [comment]
The link is broken. Is there an explanation available elsewhere, or is this no longer supported? Lots of time searching, and I see may reporting this issue but no fix that works. I need to create a custom width for a Modal, and it seems to not be possible.

**Comment by jquense** [comment]
Save yourself a lot of time search next time and head directly to the documentation page for the component you are interested in ;) https://react-bootstrap.github.io/components/modal/#modal-custom-sizing

**Comment by MidnightJava** [comment]
Thanks. I actually have spent a lot of time on that page. Lots of helpful info there, but I cannot find a way to have the width css property respected. I tried a couple ways:

`<Modal dialogClassName='custom-dialog'...>`
with CSS: `.custom-dialog {width:80%; top:20%;}`

The top is offset as expected, but the width is still whatever bsSize is set to. I'm not successful at setting a width other than small, medium, or large. I'd like to set a width a little bit less than large, so when a modal is stacked on top of a modal with size large, the stacking is visually apparent.

I also tried wrapping the Modal in `<div className="modal-container" style={{width: '80%'}}>` per the instructions for contained modals—also adding the additional CSS classes as instructed—and this does not work either.

**Comment by rulyotano** [comment]
@MidnightJava check by making `.custom-dialog {width:80% !important; top:20%;}`

**Comment by MidnightJava** [comment]
Yes, that works. Thanks. The width is relative to the viewport width in that case, so I had to set it lower than 80% to get it to 80% of the width of the underlying Modal. But I can get the effect I need with this override.

**Comment by jquense** [comment]
you're running into css cascade issues ,you can use `important` or a more specific selector to override the bootstrap styles

**Comment by mbhat94** [comment]
Just try this.
class="modal-dialog modal-lg"

**Comment by Ismail-Vega** [comment]
none talka bout setting the height this is a problem for me that don't work using that way

**Comment by JJamour** [comment]
For anyone here from google years later:

<Modal.Body style={{ height: '600px', overflow: 'scroll' }}>

**Comment by arduinho** [comment]
yes setting the height is still problem
