### ISSUE TITLE
Add 'collapsed' class on NavbarToggle

### ISSUE THREAD

**Issue by Liz303** [react-bootstrap/react-bootstrap#1645]
Bootstrap has a `collapsed` class that is removed from the `navbar-toggle` button when the `navbar-collapse` div is opened. In this way you can customize the navbar toggle styling when the `navbar-collapse` is opened ( specifically I want to  turn the spans inside the navbar-toggle from a hamburger to an x when the nav is closed/open). Here's the bootstrap for reference: http://getbootstrap.com/components/#navbar-default. You'll see that when `<div class="navbar-collapse collapse in">` has the class `in` then `<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="true"> ` doesn't have the class `collapsed` which is has by default.

**Comment by olalonde** [comment]
+1

**Comment by olalonde** [comment]
Think it's a dupe of #1301

**Comment by taion** [comment]
It's not a dupe of #1301, BTW.

**Comment by mikatuo** [comment]
I believe this was resolved as of #1733
