### ISSUE TITLE
Support for Date Type

### ISSUE THREAD

**Issue by nsisodiya** [react-bootstrap/react-bootstrap#1646]
You may want to support this

```js
<Input type='date'>
```

Similar issue - https://github.com/Hacker0x01/react-datepicker/issues/340
I suggest for adding react-datepicker library.
If allowed, I can make a pull request.

**Comment by taion** [comment]
There's no "date" type [here](http://getbootstrap.com/css/#forms), so there will be no "date" type here.

**Comment by jquense** [comment]
bootstrap inputs are just styling for _native_ input types: https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Forms/The_native_form_widgets

**Comment by nsisodiya** [comment]
Ok, I understand.
