### ISSUE TITLE
Support 'justified' for Tabs

### ISSUE THREAD

**Issue by shkfnly** [react-bootstrap/react-bootstrap#1647]
It seems that somewhere along the way the ability to justify tabs was removed. I know that it is possible to justify Navs, and I was looking into simply repeating the functionality for Tabs, however there are different Utils in use it seems tabWidth isn't working for me either. Does anyone have a solution/timeline for implementation? Thank you in advance.

**Comment by shkfnly** [comment]
I got it to work by doing the following:

I added these 2 lines to tabs:

```
var _reactPropTypesLibAll = require('react-prop-types/lib/all');

var _reactPropTypesLibAll2 = _interopRequireDefault(_reactPropTypesLibAll);
```

I added these 2 lines to prototypes in tabs

```
justified: _reactPropTypesLibAll2['default'](_react2['default'].PropTypes.bool, function (_ref) {
      var justified = _ref.justified;
      return null;
    }),
```

I also added a default prop type of       
```
justified: true
```

Obviously this won't work if you don't need justified tabs globally.
The following lines seem to dictate class selection in Nav, but I am not sure how to port them to Tabs
```
var classes = _utilsBootstrapUtils2['default'].getClassSet(this.props);

    classes[_utilsBootstrapUtils2['default'].prefix(this.props, 'stacked')] = this.props.stacked;
    classes[_utilsBootstrapUtils2['default'].prefix(this.props, 'justified')] = this.props.justified;

```

**Comment by taion** [comment]
This entire API is getting replaced for v0.29.x.
