### ISSUE TITLE
EventKey in Tabbing: Allow strings?

### ISSUE THREAD

**Issue by binarykitchen** [react-bootstrap/react-bootstrap#1648]
To me, it seems that I cannot use a string for eventKeys within the tab component like that:

```
<Tabs defaultActiveKey = "test bbb">
    <Tab key = "test aaa" eventKey = "test aaa"/>
    <Tab key = "test bbb" eventKey = "test bbb"/>
    <Tab key = "test ccc" eventKey = "test ccc"/>
</Tabs>
```

It does not pre-select the one tab with the key `test bbb`. Only works when they are numeric.

Is this expected or a known bug?

**Comment by jquense** [comment]
don't some of our examples on the doc site use strings?

**Comment by binarykitchen** [comment]
@jquense really? point me to their source code pls

**Comment by binarykitchen** [comment]
no comments?

**Comment by jquense** [comment]
the editable examples on the docs page work just fine with strings, if they aren't working for you then your strings aren't actually the same
