### ISSUE TITLE
Name attribute of a button is sometimes undefined

### ISSUE THREAD

**Issue by danielstorch** [react-bootstrap/react-bootstrap#1649]
In my code im generating several buttons which all use the same callback method. Now i need to identify which button was clicked. So i tried to set the `name="someid"` attribute and identify the button by doing like this `e.target.name`. But every now and than, the name will show  as `undefined`. After some clicking and switching pages, it will show the entered id. Why is this happening? Is there another way of identifying buttons which all use the same callback method?

Callback method
`	handleDeleteSubscriber(e){
 		console.log(e.target.name)
 	}
  	`

In the render method
```
{subscribers.map((subscriber, index) => {
  return <tr key={subscriber.code}>
	       <td>
		 <ButtonToolbar>
		    <ButtonGroup>
			<OverlayTrigger placement="bottom" overlay={<Tooltip id="TooltipDeleteSubscriber" >sometext </Tooltip>}>
			  <Button
			      bsStyle="default"
			      name={subscriber.id}
			      onClick={this.handleDeleteSubscriber}>
			      <Glyphicon glyph="trash" />
			  </Button>
			</OverlayTrigger>
		    </ButtonGroup>
		 </ButtonToolbar>
	      </td>
	</tr>})}
```

**Comment by taion** [comment]
Use a custom component for your button and read `this.props`.

**Comment by danielstorch** [comment]
Ok thanks, i will try. But is there any explanation why the attribute behaves like that?

**Comment by taion** [comment]
I have no idea, but that's just not the right way to handle this sort of thing in React anyway.
