### ISSUE TITLE
button with href displaying as <a> element

### ISSUE THREAD

**Issue by roberto68** [react-bootstrap/react-bootstrap#1650]
following example on react-bootstrap documentation ` const buttonsInstance = (

    <ButtonToolbar>

      <Button href="#">Link</Button>

      <Button>Button</Button>

    </ButtonToolbar>

  );

​

ReactDOM.render(buttonsInstance, mountNode);

​ `   but it doesn't work like in example on http://react-bootstrap.github.io/components.html. button is displaying as a link

**Comment by taion** [comment]
You need to bring your own CSS.

**Comment by roberto68** [comment]
dafuq ??? what the point of bootstrap then if you've to CSS one simple fukin button.

**Comment by jquense** [comment]
he means you need to include the bootstrap css, components. please follow the setup and getting started directions on the site

**Comment by i-bsd** [comment]
Why was this issue closed? Problem still exists.

Bootstrap <Button> element converts to an <a> tag when href is present.

**Comment by awatansa** [comment]
Is this even a problem or just a feature of react-bootstrap?

**Comment by taion** [comment]
This is intentional. If you have an `href`, it's an anchor, not a button.
