### ISSUE TITLE
Support for adding additional bsSizes?

### ISSUE THREAD

**Issue by athasach** [react-bootstrap/react-bootstrap#1651]
In https://github.com/react-bootstrap/react-bootstrap/issues/1530 the question was asked about removing the restriction on `bsStyle` and `bsSize` values. The answer indicates a way to add a new style, but there doesn't appear to be a way to add a new size.

Is there a way to do this, such as:

```javascript
import utils from 'react-bootstrap/lib/utils/bootstrapUtils';
import Button from 'react-bootstrap/lib/Button';

utils.addSize(Button, ['xxsmall', 'xlarge']);
```

Or should I use another approach?

Thanks.

**Comment by taion** [comment]
Just use `bsSizes`

**Comment by athasach** [comment]
Thanks.
