### ISSUE TITLE
Nav activeKey is ignored when NavItems are nested

### ISSUE THREAD

**Issue by joncppl** [react-bootstrap/react-bootstrap#1655]
I'm using react-router and react-router-bootstrap,
and I found that when a NavItem is nested by react-router-bootstrap's LinkedContainer component,
the component with the corresponding eventKey doesn't get updated as active

Here is an example
```
render: function() {
	//hack: examine pathname to determine if active key is admin
	var activeKey = 1;
	if (document.location.pathname.indexOf("admin") != -1) {
		activeKey = 2;
	}
	console.log(activeKey)
	var adminTab = this.state.is_admin ? (<LinkContainer to={{pathname: "/app/settings/admin", query: getQueryObject()}}><BS.NavItem eventKey={2}>Admin</BS.NavItem></LinkContainer>) : null;
	return (
		<BS.Grid fluid={true}>
			<BS.Nav bsStyle="tabs" activeKey={activeKey}>
				<LinkContainer to={{pathname: "/app/settings", query: getQueryObject()}}>
					<BS.NavItem eventKey={1}>Account</BS.NavItem>
				</LinkContainer>
				{adminTab}
			</BS.Nav>
			{this.props.children}
		</BS.Grid>
	);
}
```

**Comment by joncppl** [comment]
A quick look at the source code shows that Nav only checks it's immediate children for eventKeys, so it probably makes more sense to fix this from react-router-bootstrap's end

**Comment by taion** [comment]
You're not supposed to use `activeKey` and `eventKey` with `LinkContainer`. Check the RRB examples.
