### ISSUE TITLE
Nav ulClassName deprecated 

### ISSUE THREAD

**Issue by ondrejnov** [react-bootstrap/react-bootstrap#1656]
I can't pass ulClassName to Nav component from Tabs. 
`<Tabs className="tab" ulClassName="nav-tabs-bottom" defaultActiveKey={0}>`

ulClassName is transparency pass to Nav here:
https://github.com/react-bootstrap/react-bootstrap/blob/master/src/Tabs.js#L179
There is no convert ulClassName to className for Nav.

**Comment by taion** [comment]
This is resolved by the new API.
