### ISSUE TITLE
Improve MenuItem docs

### ISSUE THREAD

**Issue by jakebuhler** [react-bootstrap/react-bootstrap#1657]
The documentation lists the arguments passed to `MenuItem`'s `onSelect` callback incorrectly. It states that the callback is given `eventKey`, `href`, and `target`:

<img width="552" alt="screen shot 2016-02-13 at 5 23 53 pm" src="https://cloud.githubusercontent.com/assets/259811/13031149/ab9c8110-d276-11e5-817f-4bc39c06d770.png">

But really, `onSelect` gets passed `event` and `eventKey`.

Later in this section, `MenuItem`'s props are listed, but most of them don't have any explanation about what they do. It would be helpful if each one had a short description, similar to how the props of other components are documented. I'm working on a quick PR with these improvements.

**Comment by AlexKVal** [comment]
Closed by #1658
