### ISSUE TITLE
MenuItem divider should render className prop

### ISSUE THREAD

**Issue by mjvestal** [react-bootstrap/react-bootstrap#1660]
The MenuItem returns here when the ```divider``` prop is included:
https://github.com/react-bootstrap/react-bootstrap/blob/master/src/MenuItem.js#L33-L35

I think it should include any classes the consumer provides, such that if I have:
```
<MenuItem divider className="visible-xs visible-sm" />
```

It should render
```
<li role="separator" class="divider visible-xs visible-sm"></li>
```

**Comment by mjvestal** [comment]
It occurred to me, why don't I just:
```
<Dropdown.Menu>
    <MenuItem ..>...</MenuItem>
    <li role="separator" className="divider visible-xs visible-sm" />
    ...
</Dropdown.Menu>
```

Besides the un-DRY-ness of having ```role="separator"``` for dividers, why not just have consumers do that instead?

**Comment by taion** [comment]
Fixed by https://github.com/react-bootstrap/react-bootstrap/pull/1682.
