### ISSUE TITLE
Carousel  controls='false'   hide  prev  and next

### ISSUE THREAD

**Issue by jiangfeng0103** [react-bootstrap/react-bootstrap#1661]
<Carousel className='carousel slide widget-carousel widget-bg-color-white' controls='false'>

![2016-02-18_142421](https://cloud.githubusercontent.com/assets/12807989/13135527/4cf9d17e-d64c-11e5-9817-8f2f68c92bd2.png)
![2016-02-18_142905](https://cloud.githubusercontent.com/assets/12807989/13135526/4cf8b866-d64c-11e5-994b-61e43d28e9b0.png)

**Comment by jquense** [comment]
hi there. I am not sure what you are trying to indicate is wrong/not working
