### ISSUE TITLE
Feature request: Option to disable keyboard navigation for Dropdowns

### ISSUE THREAD

**Issue by glortho** [react-bootstrap/react-bootstrap#1666]
Assuming we didn't overlook the option somewhere...

We've implemented our own keynav system and it would be nice to be able to use it without forking.

Thank you!

**Comment by jquense** [comment]
We aren't going allow disabling it for the built-in components, but you can use a custom Menu that extends the built-in one and just overrides the relevant methods. https://github.com/react-bootstrap/react-bootstrap/blob/master/src/DropdownMenu.js#L23

**Comment by glortho** [comment]
For the benefit of anyone who might land here:

I started to go down that route, but – and please help a guy out and tell me there's a better way here - to use DropdownButton it appears that you actually have to duplicate the `DropdownButton` component (or extend it and override `render()`, which is basically the same thing), and have it render your own extended version of `Dropdown.Menu` that overrides the `handleKeyDown` method therein. This works, but then you still end up with unsightly focus on the first `MenuItem` - one of the reasons to disable the baked-in keynav approach - because it has a `tabIndex` being passed to `SafeAnchor` that I don't think you can override unless you duplicate `MenuItem` (or extend and override `render()` again), not passing in a `tabIndex`.

Ah! `Dropdown` is actually calling the DropdownMenu `focusNext` method via ref, which is focusing that first item when arrowing down. So you can get around this issue by also overriding the `focusNext` method in `DropdownMenu`, or if you truly want all key handling disabled, also extend `Dropdown` and override `handleKeyDown` there as well.

Or you can just fork, which is tempting!

Thanks for your quick response, though. Much appreciated.
