### ISSUE TITLE
Cannot override default styles for components

### ISSUE THREAD

**Issue by dmt0** [react-bootstrap/react-bootstrap#1667]
Sorry, this was probably addressed somewhere before, since it seems like a very basic issue.

When I do something like:
`<Row className="custom-row">`

The result that I get is this:
`<div class="custom-row row">`

So if I'm trying to override the default behavior of "row" in my "custom-row" (such as padding:0), it doesn't work, since "row" is applied to div after "custom-row". So the only workaround I have is not to use the Row component but to just write plain html.

Please advice if this behavior is intentional and whether it can be configured.

Many thanks.

**Comment by taion** [comment]
Use `bootstrapUtils`; see https://github.com/react-bootstrap/react-bootstrap/pull/1465 for more details – as an advanced usage, we're not providing further support for this feature at the moment.

**Comment by oleole90** [comment]
Same issue. [This](https://react-bootstrap.github.io/components.html#custom-styles) helped me.

**Comment by dark-swordsman** [comment]
Sorry for digging this up, it just seemed the most relevant.

I have been fighting for days trying to use a Bootswatch theme with my project. I import the css file before any of my routes in my App.js file and I am using `bootstrapUtils.addStyle()` to try and overwrite the default styles of the React-Bootstrap elements as such:

```js
bootstrapUtils.addStyle(NavItem, 'nav-link');
bootstrapUtils.addStyle(LinkContainer, 'nav-item');
```

I have tried other solutions, like `className` and using the `styles` attribute. It appears that the `styles` attribute works but, a) I can't simply reference the bootswatch class unless I try and use something like LESS, and b) I find it really inconvenient if I have to overwrite the style of each and every element I write on the page.

**Comment by taion** [comment]
Adding a style only lets you set a new `bsStyle`. You'd need to change the `bsClass` to change the "base".
