### ISSUE TITLE
Support for inline radios & checkboxes

### ISSUE THREAD

**Issue by kirill-konshin** [react-bootstrap/react-bootstrap#1674]
Per Bootstrap documentation there is a special inline mode of radio buttons & checkboxes, so far I don't see how this could be supported by React Bootstrap.

Here is a link to docs: http://getbootstrap.com/css/#inline-checkboxes-and-radios

**Comment by sknoslo** [comment]
Until something happens with #962 there is no built in way to do this (that I'm aware of). Here is how I've done it in the past:

``` JSX
<Input
    label="Inline Radios!"
    {...validationStuff}
>
    <div>
        <label className="radio-inline">
            <input
                type="radio"
                value="option1"
                name="radio_option"
            /> Option 1
        </label>
        <label className="radio-inline">
            <input
                type="radio"
                value="option2"
                name="radio_option"
            /> Option 2
        </label>
    </div>
</Input>
```

Note the usage of a plain-old 'input' tag on the inside. You lose out on some of the niceties of react-bootstrap by doing this but at least it renders properly.

**Comment by kirill-konshin** [comment]
That's exactly what I did. But I was expecting "native" support in React Bootstrap...

**Comment by taion** [comment]
Replacing with https://github.com/react-bootstrap/react-bootstrap/issues/1749.
