### ISSUE TITLE
OverlayTrigger causing "Minified exception occurred..." error in staging/production builds

### ISSUE THREAD

**Issue by cmoel** [react-bootstrap/react-bootstrap#1678]
Hi folks!

First, thank you so much for react-bootstrap. I've really enjoyed using it and have found it to be very flexible for the apps I've been working on. Unfortunately, I'm running into an issue with my staging and productions builds, though, after bundling and uglifying with Webpack. This isn't an issue in development.

After building my production build and loading it in a browser, I'm seeing this error in my Chrome dev tools console: `Uncaught Error: Minified exception occurred; use the non-minified dev environment for the full error message and additional helpful warnings`. I have gone through my Git history and pinpointed the issue to a commit where I introduced the following component (slightly simplified but still causes the same error in the console):

```
import React from "react"
import { Button, OverlayTrigger, Popover } from "react-bootstrap"

const NavbarNotifications = () => {
  const overlay = (
    <Popover id="notifications-popover">
      No New Notifications
    </Popover>
  )
  return (
    <OverlayTrigger trigger="click" rootClose placement="bottom" overlay={overlay}>
      <Button>Yo!</Button>
    </OverlayTrigger>
  )
}

export default NavbarNotifications
```

When I remove the `OverlayTrigger` lines (just leaving the `Button` and `Popover` components, there is no error in the console. When I set the `OverlayTrigger`'s `overlay` prop to `overlay={<noscript />}` the issue persists, leading me to think that it's something caused by the `OverlayTrigger` component, but I'm having trouble pinpointing what it is.

Am I doing something wrong? Any idea what's going on and how I can resolve this?

Thanks!

**Comment by taion** [comment]
There's not really anything we can go off of here – this seems like a pretty close match to working examples from our components page. Might be something weird with functional components, but probably not. You could try generating a minified build without setting `NODE_ENV=production` to keep the warnings, but otherwise I can't really tell what the problem would be.
