### ISSUE TITLE
JSFiddle for the examples

### ISSUE THREAD

**Issue by aadrian** [react-bootstrap/react-bootstrap#1679]
Hi,

It's practical that for the examples on the http://react-bootstrap.github.io/components.html page there's a "show code" functionality. Even more helpful would be if there were another button too: "Try example in JSFiddle", that would open for each example the corresponding JSFiddle.

This way the users could try each example live, right away, modify them, experiment with them and give much faster and easier feedback.

Thank you.

**Comment by jquense** [comment]
have you tried to edit the examples on the documentation site? Each example is already live editable.

**Comment by aadrian** [comment]
> have you tried to edit the examples on the documentation site? Each example is already live editable.

They're two different things: JSFiddle (and alike)  allows the user to see and modify **all** the details of the examples (and library versions), to include other stuff, etc. It also allows to save these changes with a new URL that can be supplied as an issue or test case to developers in order to quickly be able to reproduce bugs and pinpoint problems.

These cases are all not possible from the editable examples, so "just live editable" although is "cool",  it's not really helpful :).

**Comment by jquense** [comment]
If you can show a way to do it that is reliable and requires very little maintenance burden on our part we'd consider it. PR's accepted :)

**Comment by aadrian** [comment]
@jquense AFAIK all the pieces are already there (at least for JSFiddle). Only the conventions need to be respected too: http://doc.jsfiddle.net/use/github_read.html  so that JSFiddle can pick the files from GitHub. It has than that special link (that could be added as button on the examples page too).
