### ISSUE TITLE
Using <div> inside <ListGroupItem>

### ISSUE THREAD

**Issue by b4be1** [react-bootstrap/react-bootstrap#1683]
ListGroupItem returns \<p\> element (see line 108 in ListGroupItem.js). If I want to put a \<div\> inside ListGroupItem, React complains that \<div\> cannot be placed inside \<p\>. Replacing \<p\> with \<div\> in ListGroupItem.js solves the problem.

Example to reproduce the issue:
```
<ListGroup>
    <ListGroupItem header="Heading">
      <Input type="checkbox" label="Checkbox" />
    </ListGroupItem>
  </ListGroup>
```

**Comment by taion** [comment]
Dupe https://github.com/react-bootstrap/react-bootstrap/issues/1271
