### ISSUE TITLE
Layout components not working

### ISSUE THREAD

**Issue by diegoaguilar** [react-bootstrap/react-bootstrap#1684]
I'm trying to use `Grid`, `Row` and `Col` for getting a basic layout system. So I got this `MainLayout` component:

    import React from 'react';
    import { render } from 'react-dom';
    import { Grid, Row, Col } from 'react-bootstrap';
    
    const GridComponent = (
      <Grid>
        <Row className="show-grid">
          <Col xs={12} md={8}><code>&lt;{'Col xs={12} md={8}'} /&gt;</code></Col>
          <Col xs={6} md={4}><code>&lt;{'Col xs={6} md={4}'} /&gt;</code></Col>
        </Row>
    
        <Row className="show-grid">
          <Col xs={6} md={4}><code>&lt;{'Col xs={6} md={4}'} /&gt;</code></Col>
          <Col xs={6} md={4}><code>&lt;{'Col xs={6} md={4}'} /&gt;</code></Col>
          <Col xsHidden md={4}><code>&lt;{'Col xsHidden md={4}'} /&gt;</code></Col>
        </Row>
    
        <Row className="show-grid">
          <Col xs={6} xsOffset={6}><code>&lt;{'Col xs={6} xsOffset={6}'} /&gt;</code></Col>
        </Row>
    
        <Row className="show-grid">
          <Col md={6} mdPush={6}><code>&lt;{'Col md={6} mdPush={6}'} /&gt;</code></Col>
          <Col md={6} mdPull={6}><code>&lt;{'Col md={6} mdPull={6}'} /&gt;</code></Col>
        </Row>
      </Grid>
    );
    
    export default GridComponent;

I use it:

    import React from 'react';
    import ReactDOM from 'react-dom';
    import injectTapEventPlugin from 'react-tap-event-plugin';
    import MainLayout from './components/MainLayout'
    //Needed for onTouchTap
    //Can go away when react 1.0 release
    //Check this repo:
    //https://github.com/zilverline/react-tap-event-plugin
    injectTapEventPlugin();
    
    // Render the main app react component into the app div.
    // For more details see: https://facebook.github.io/react/docs/top-level-api.html#react.render
    ReactDOM.render(
      MainLayout,
      document.getElementById('app')
    );

But then my result is not what I expect:

[![enter image description here][1]][1]

What am I doing wrong? :(

  [1]: http://i.stack.imgur.com/cPD1b.png

**Comment by jquense** [comment]
you probably aren't including the css on the page

**Comment by diegoaguilar** [comment]
That was the issue, sorries

**Comment by sumitaryavrat** [comment]
hey Diego Aguilar Aguilar  what you did for that...???????

**Comment by thebradisrad** [comment]
> i seem to be getting the following error
> Failed to compile.
> 
> ./src/components/Home.jsx
> Attempted import error: 'Grid' is not exported from 'react-bootstrap'.
> 
> can anyone advice

Grid seems to be taken out of react-bootstrap. Rows is taking its place.

**Comment by jquense** [comment]
The Component is now called `Container` not Grid

**Comment by Jahanzaib-jb** [comment]
Use separately import for Grid like this
import Grid from "react-bootstrap";

**Comment by raulcrenteria** [comment]
Same problem with <Well>: "./src/components/itemdetails/itemdetails.js
Attempted import error: 'Well' is not exported from 'react-bootstrap'."

**Comment by taion** [comment]
`<Well>` isn't in the 1.0 betas, as it's been removed from TWBSv4.

**Comment by Sachin124** [comment]
**In latest version following thing will be migrated please check**
` https://react-bootstrap.netlify.com/migrating/`

**Comment by abhidevlopment** [comment]
>Grid is now replaced by Container component!!!

**Comment by KaptaanBarbosa** [comment]
> i seem to be getting the following error
> Failed to compile.
> 
> ./src/components/Home.jsx
> Attempted import error: 'Grid' is not exported from 'react-bootstrap'.
> 
> can anyone advice

You must be using latest version no Grid component is there you have to use container instead

**Comment by JennifferCrystine** [comment]
having this problem and can't solve it, can someone please help me?
./src/containers/Home.js
Attempted import error: 'Container' is not exported from 'react-bootstrap/Container'.
i took it from here https://react-bootstrap.github.io/layout/grid/
've read all tips mentioned above but none of them helped me to solve this

**Comment by pavankanth6** [comment]
@JennifferCrystine By default, when you do `npm install react-bootstrap bootstrap` as mentioned in the docs @ https://react-bootstrap.github.io/getting-started/introduction/, the version of react-bootstrap in packagee.json is pointing towards the Bootstrapv3 version. Manually edit the package.json and use `"react-bootstrap": "^1.0.0-beta.16" `. This resolved the same error I had.
