### ISSUE TITLE
Implementation in Meteor Mantra

### ISSUE THREAD

**Issue by sandervanhooft** [react-bootstrap/react-bootstrap#1685]
Hi,

I really am hoping to get react-bootstrap to work in Meteor Mantra.

I installed it using `npm install --save react-bootstrap`. I can for example import and initially render a `<Button />` using Mantra (import { Button } from 'react-bootstrap', but I cannot alter the state in browser. Is it possible these component methods are not loaded correctly?

I am not sure what the cause of this problem is. I have tested it using a container and a component. Should I include additional dependencies somewhere, add it to a preprocessor config, or something else...?

Restarting meteor nor `npm install` solves the issue.

[Here's the gist](https://gist.github.com/sandervanhooft/9b9e5e385fa6d622228f) including the container (header.js), the component (header.jsx), and the root package.json. You can learn more about Mantra [here](https://github.com/kadirahq/mantra).

I have also opened [a similar issue in the Mantra repo](https://github.com/kadirahq/mantra/issues/123), because I really don't know where to start looking for a solution.

**Comment by taion** [comment]
We can't help you with this – whatever this issue is, it looks quite possibly to be specific to something with your tooling/platform. Everything works fine in a standard npm setup.
