### ISSUE TITLE
Compatibility with React 15

### ISSUE THREAD

**Issue by jochenberger** [react-bootstrap/react-bootstrap#1686]
react-bootstrap is not yet compatible with React 15 (RC) because the `uncontrollable` dependency isn't. See https://github.com/jquense/uncontrollable/pull/10

**Comment by xiankai** [comment]
Encountered the same issue, the error that gets thrown is `Error: Cannot read property 'propTypes' of undefined`

**Comment by lolJS** [comment]
+1

**Comment by aadrian** [comment]
+1

**Comment by jerson** [comment]
see http://stackoverflow.com/questions/32854647/reactjs-uncaught-typeerror-cannot-read-property-string-of-undefined

**Comment by jquense** [comment]
The issue is already fixed upstream, We aren't officially supporting react 0.15 until it is properly released.
