### ISSUE TITLE
Tooltip does not render upon window refocusing by clicking the OverlayTrigger

### ISSUE THREAD

**Issue by taahachaudhry** [react-bootstrap/react-bootstrap#1689]
Here are the steps to reproduce the bug, which will provide a better understanding:
1. View the 'With OverlayTrigger' example under http://react-bootstrap.github.io/components.html#tooltips. Everything works great when you hover over the OverlayTrigger and see a Tooltip. 
2. Lose focus of the window and refocus by clicking on the OverlayTrigger.
3. You will notice that the Tooltip does not display until you move out of the OverlayTrigger and re-hover.

This bug does not exist in Bootstrap, and was tested in Chrome.

**Comment by jshaker** [comment]
Can you specify which OS you're running this on?
I tried reproducing this bug on Ubuntu 16.04 with Chrome

**Comment by taion** [comment]
Yeah it's a bit of a hole in how we handle overlay triggers with multiple triggers.
