### ISSUE TITLE
Navbar.Header does not support className 

### ISSUE THREAD

**Issue by mvandiest** [react-bootstrap/react-bootstrap#1693]
I'm attempting to hide the Navbar.Header from all but extra small devices...

The following example does not work as classNames are not merged in [NavbarHeader.js](https://github.com/react-bootstrap/react-bootstrap/blob/master/src/NavbarHeader.js#L17) as they are in [NavbarBrand.js](https://github.com/react-bootstrap/react-bootstrap/blob/master/src/NavbarBrand.js#L21):

```
<Navbar.Header className='visible-xs'>
  <Navbar.Brand>
    <a href="#">My Brand</a>
  </Navbar.Brand>
  <Navbar.Toggle />
</Navbar.Header>
```

I can use the following workaround currently, but it would be nice not to have to add an extraneous div:
```
<div className='visible-xs'>
  <Navbar.Header>
    <Navbar.Brand>
      <a href="#">My Brand</a>
    </Navbar.Brand>
    <Navbar.Toggle />
  </Navbar.Header>
</div>
```

**Comment by taion** [comment]
Looks like just an oversight to me. Care to put together a PR?

**Comment by mvandiest** [comment]
NP. PR submitted.
