### ISSUE TITLE
Navbar defaultNavExpanded prop deprecation warning

### ISSUE THREAD

**Issue by DexterHaslem** [react-bootstrap/react-bootstrap#1696]
using 'defaultNavExpanded' on a Navbar triggers the deprecation warning blurb

```
browser.js:49 Warning: Rendering a deprecated version of the Navbar due to the use
 of deprecated props. Please use the new Navbar api, and remove `toggleButton`, 
`toggleNavKey`, `brand`, `navExpanded`, `defaultNavExpanded` props or 
the use of the `<NavBrand>` component outside of a `<Navbar.Header>`. 

for more details see: http://react-bootstrap.github.io/components.html#navbars
```

however going to http://react-bootstrap.github.io/components.html#navbars doesn't have anything about defaultNavExpanded being deprecated or any alternatives. Is this because it uses navExpanded? What is an alternative that doesn't trigger warnings?

**Comment by taion** [comment]
http://react-bootstrap.github.io/components.html#navs-props-navbar

**Comment by DexterHaslem** [comment]
To be specific, my point is the docs should be updated to not suggest 'defaultNavExpanded'  in #navbars-mobile-friendly and label it deprecated in favor of defaultExpanded

**Comment by taion** [comment]
Can you PR an update?

**Comment by taion** [comment]
Closed by https://github.com/react-bootstrap/react-bootstrap/pull/1738.
