### ISSUE TITLE
NavBar.Collapse with dimension='width' not working

### ISSUE THREAD

**Issue by bhoomit** [react-bootstrap/react-bootstrap#1698]
I tried adding following CSS as well. 

http://stackoverflow.com/questions/18993202/bootstrap-3-0-collapse-horizontally

Am I doing something wrong?

**Comment by taion** [comment]
Please provide a repro.

**Comment by jquense** [comment]
yeah if you can provide an actual fiddle or something that would help. especially since the `width` dimensions isn't really supported, like it isn't really supported in vanilla bootstrap, more of a "use at your own risk" sort of thing
