### ISSUE TITLE
Disable tooltips on touch screens

### ISSUE THREAD

**Issue by nye** [react-bootstrap/react-bootstrap#1699]
Is there a way to disable tooltip on touch screens?

It would be nice to show tooltips only when hoovering with the mouse and hide them when on touch screens, so you don't have to click twice on links.

Sometimes tooltip text is just additional information and it's not necessary to show them on mobile (touch) screens.

It's possible to workaround this with regular Bootstrap:

```javascript
if(isTouchDevice()===false) {
    $("[rel='tooltip']").tooltip();
}
```

But is there a way to do something similar with React and react-bootstrap?

Thanks!

**Comment by jquense** [comment]
just don't render the tooltip on a mobile device. I'd just wrap OverlayTrigger or something to encapsulate that so you only have to write it once

**Comment by glosee** [comment]
It would be really nice if the component could handle this itself...

**Comment by taion** [comment]
You can calculate the value of `trigger` and pass down whatever is appropriate for the current render context
