### ISSUE TITLE
Input field can't be required

### ISSUE THREAD

**Issue by martinbkure** [react-bootstrap/react-bootstrap#1700]
Hi, I'm adding input-fields to my app, but would like to make them required. Without react bootstrap I can do it pretty straightforward:
````
<input ... required />
`````
However when I add the bootstrap input field, the required attribute doesn't seem to be added:
`````
<Input .... required />
``````
Is there a solution to this problem, or is there all ready a property solving this, that I just haven't seen.

/BR

Martin

**Comment by taion** [comment]
It works just fine – gets forwarded to the underlying input component.

**Comment by mdanics** [comment]
doesn't work for me either

**Comment by jdonzet** [comment]
Use like this:
`required="true"`

**Comment by Kielan** [comment]
why can't we just pass required ?

**Comment by pavinduLakshan** [comment]
> 
> 
> Use like this:
> `required="true"`

This doesn't work for me in select component.
<Form.Control required={true} as="select"></Form.Control>

Anyone has a solution?

**Comment by gabrielccarvalho** [comment]
> > Use like this:
> > `required="true"`
> 
> This doesn't work for me in select component.
> <Form.Control required={true} as="select"></Form.Control>
> 
> Anyone has a solution?

Have you found a solution yet? Same problem here.

**Comment by pavinduLakshan** [comment]
To make `required` work for select input, the value of the first option should be empty. See https://stackoverflow.com/questions/8287353/does-the-select-element-have-the-required-attribute
