### ISSUE TITLE
Rendering bug with DropdownButton in addonAfter on Input

### ISSUE THREAD

**Issue by cymen** [react-bootstrap/react-bootstrap#1701]
I am hitting a bug where the `Input` `addonAfter` doesn't render to the correct size when using a `DropdownButton` in it. Here is an example:

<img width="169" alt="screen shot 2016-03-16 at 9 27 55 pm" src="https://cloud.githubusercontent.com/assets/121034/13836425/77f0bab4-ebbe-11e5-9f4a-3f1fcc0091ef.png">

I pushed up an example repo here: https://github.com/cymen/react-bootstrap-input-addonafter-dropdownbutton-bug

**Comment by taion** [comment]
There's an example for this right on the components page...

**Comment by cymen** [comment]
@taion Yes, I'm aware. I'm following that example. I thought the CSS was borked on a project so I went out to try to repro the working example using a react-bootstrap starter skeleton and I'm seeing the same thing. Not clear to me why -- it looks like the components page uses Bootstrap 3.3.6 CSS as the repo (as does the repo I linked to above).

**Comment by taion** [comment]
You are not following the example correctly.

**Comment by cymen** [comment]
Argh -- it's `buttonAfter` not `addonAfter`. Somehow I managed to overlook that. My apologies.

**Comment by taion** [comment]
No worries. In the long run we want to fix this API to be closer to the markup and not have all the magic props, but this is all we have for now.
