### ISSUE TITLE
getInputDOMNode for ButtonInput does not work

### ISSUE THREAD

**Issue by mizki9577** [react-bootstrap/react-bootstrap#1702]
`ButtonInput.getInputDOMNode` returns a `Button` component, not an `input` DOM element. According to [the document](https://react-bootstrap.github.io/components.html#forms), it should return an `input` element (right?).

`InputBase.getInputDOMNode` tries to get a component / element which has an attribute `ref="input"`. `ButtonInput.renderInput` returns (renders) a `Button` component with this attribute, so `ButtonInput.getInputDOMNode` returns `Button` component.

(sorry for my poor English)

**Comment by taion** [comment]
In HTML5 it's correct to have `<button>` rather than `<input type="button">`, so it's correct to have a `<Button>` there as well.
