### ISSUE TITLE
How to replace tab Content on tab click ?

### ISSUE THREAD

**Issue by amolpshinde07** [react-bootstrap/react-bootstrap#1704]
Below is the Code : 
<div id="react_tabs">
	!!!!!!!!!!!!!!!!!!!React Implementation!!!!!!!!!!!!!!!!!!!
	</div>
<script type="text/jsx">
	 var supptabs = {
			stabs: [
				{
					key: 41,
					id: "designs_tab",
					title: "Designs",
					content: "Loading Designs Content . . ."
				},
				{
					key: 42,
					id: "tracks_tab",
					title: "Tracks",
					content: "Loading Tracks Content . . ."
				},
				{
					key: 43,
					id: "known_variants_tab",
					title: "Known Variants",
					content: "Loading Known Variants Content . . ."
				},
				{
					key: 44,
					id: "reference_file_tab",
					title: "Reference File",
					content: "Loading Reference File Content . . ."
				},
				{
					key: 45,
					id: "rule_set_tab",
					title: "Rule Set",
					content: "Loading Rule Set Content . . ."
				}
			]
		};							
		var configtabs = {
			ctabs: [
				{
					key: 31,
					id: "analysis_method_tab",
					title: "Analysis Method",
					content: "Loading Analysis Method Content . . ."
				},
				{
					key: 32,
					id: "categorization_tab",
					title: "Categorization",
					content: "Loading Categorization Content . . ."
				},
				{
					key: 33,
					id: "custom_ngs_template",
					title: "Custom NGS Template",
					content: "Loading Custom NGS Template Content . . ."
				}
			]
		};

var App = React.createClass({
			render: function(){
				return(
					<div>
						1 Welcome to SureCall Web Client Using React
						Here we will render SureCall Tab using React Js
					</div>
				)
			}
			});
			
		const SureCallMainTabs = React.createClass({
			 
			 getInitialState() {
				return {
				  selkey: 1,
				  selSubTabkey:31
				};
			  },

			  handleSelect(selkey) {
				this.setState({selkey});
				//alert('selected ' + selkey);
				
			  },
			  
			  handleSelectSubTab(selSubTabkey) {
				//alert('selected subtab' + selSubTabkey);
				this.setState({selSubTabkey});
				if(selSubTabkey==31){
					ReactDOM.render(<App/>, document.getElementById("analysis_method_tab"));
				}else if(selSubTabkey==32){
					ReactDOM.render(<App1/>, document.getElementById("categorization_tab"));
				}
			  },
			  render() {
				var ctabs = this.props.configtabs.ctabs;
				var stabs = this.props.supptabs.stabs;
				
				 var Tabs = ReactBootstrap.Tabs,
					Button  = ReactBootstrap.Button,
					Tab=ReactBootstrap.Tab;
				  
					return (
					<Tabs activeKey={this.state.selkey} animation={false} position="top" onSelect={this.handleSelect}>
						<Tab eventKey={1} id="home_tab" title="Home">
								Home Content
						</Tab>
						
						<Tab eventKey={2} id="analysis_workflow" title="Analysis Workflow">
							Analysis Workflow Content
						</Tab>
						
						<Tab eventKey={3} id="configure_setting" title="Configure Setting" >
								<Tabs activeKey={this.state.selSubTabkey} animation={true} tabWidth={2} paneWidth={5} position="left" onSelect={this.handleSelectSubTab}>
									{
										ctabs.map(function (ctab) {
											return (
												<Tab eventKey={ctab.key} id={ctab.id} title={ctab.title}> {ctab.content}</Tab>
											);
										})
									}
								</Tabs>
						</Tab>
						
						<Tab eventKey={4} id="supporting_files" title="Supporting Files">
								<Tabs activeKey={this.state.selSubTabkey} animation={true} tabWidth={2} paneWidth={5} position="left" onSelect={this.handleSelectSubTab}>
									{
										stabs.map(function (stab) {
											return (
												<Tab eventKey={stab.key} id={stab.id} title={stab.title}> {stab.content}</Tab>
											);
										})
									}
								</Tabs>
						</Tab>
						
					</Tabs>
					);
			  }
		});
	ReactDOM.render(<SureCallMainTabs  configtabs={configtabs} supptabs={supptabs}/>, document.getElementById("react_tabs"));
	 
    </script>

**Comment by jquense** [comment]
???

**Comment by amolpshinde07** [comment]
I have added code, and I am trying to replace tab content when user clicks on tab but it's throwing exception and nothing get replaced.

**Comment by amolpshinde07** [comment]
#help required
@help required

**Comment by jquense** [comment]
@amolpshinde07 we have no idea what you are talking about, your Issue has no code in it, and you are not explaining what the problem is: read: https://guides.github.com/features/mastering-markdown/ for how to include it
