### ISSUE TITLE
Navbar.Collapse "in" style not removed when menu is uncollapsed by resizing window

### ISSUE THREAD

**Issue by adamgering** [react-bootstrap/react-bootstrap#1710]
Navbar.Collapse "in" style not removed when menu is uncollapsed by resizing window

Reproduce:
1. Reduce the width of the browser until &lt;NavBar.Toggle /&gt; (Hamburger button) is displayed.
2. Expand the Toggle menu.
3. Expand the width of the browser until &lt;NavBar.Toggle /&gt; disappears.

The &lt;NavBar.Collapse /&gt; div still has the classes "navbar-collapse collapse in". The class "in" should have been removed when the Toggle was changed by the resize.

**Comment by taion** [comment]
Matches upstream. Really it wouldn't be possible to do anything about this without tightly coupling JS to CSS anyway, which we're not going to do (because we don't know the CSS breakpoints anyway).
