### ISSUE TITLE
Need way to stopPropogation with rootClose on overlay

### ISSUE THREAD

**Issue by tirams** [react-bootstrap/react-bootstrap#1711]
I have an Overlay component with it's rootClose property set to true, so that any clicks outside the Overlay will close it.

The Overlay appears as a dropdown when clicked and shows up over a table that has rowclick handlers. I want the popover to close but to stop the propagation to the row click handler.

I don't want the rowclick handler or any other actions outside the Overlay to act when clicked on. How might this be done? Can an option be added for rootCloseNoPropagate

**Comment by taion** [comment]
That doesn't make sense – the root close listener is on the document, so it can't stop propagation to your rows.
