### ISSUE TITLE
Install Fails - left-pad@0.0.3 is no longer on npm

### ISSUE THREAD

**Issue by staminaloops** [react-bootstrap/react-bootstrap#1712]
Just for you to be aware, I just cloned your repo and tried npm install, I'm getting:

```
argv "/usr/bin/nodejs" "/home/sofia/local/bin/npm" "install"
npm ERR! node v5.9.0
npm ERR! npm  v3.3.1

npm ERR! No compatible version found: left-pad@0.0.3
npm ERR! Valid install targets:
npm ERR! ["0.0.9"]
```
This is **NOT a problem with `react-bootstrap`**, as you can see in this issue:

> left-pad updated to 0.0.9 and they seem to have removed 0.0.3 from npm: https://www.npmjs.com/package/left-pad

Just want to warn you about it.
https://github.com/facebook/react-native/issues/6595

**Comment by staminaloops** [comment]
For now, the only way of getting everything up and running is putting 

```
"left-pad": "git://github.com/azer/left-pad.git#bff80e3ef0db0bfaba7698606c4f623433d14355"
```
on package.json. Just tested it and works.
I just opened the issue because people will probably ask and now they can have the answer just going to the issues. Sorry to bother if you think that it wasn't relevant, just wanted to help.

**Comment by taion** [comment]
It's totally upstream and there's nothing we can do about it. It's fixed with the updated babel-runtime anyway.
