### ISSUE TITLE
MenuItem issue

### ISSUE THREAD

**Issue by bobdelphi9999** [react-bootstrap/react-bootstrap#1713]
Hello, I am using react-bootstrap components MenuItem. I am not sure how to render a multilevel menu by this. Below is the code that I write for this and all is fine but it will render an another empty menuitem.

 <MenuItem eventKey="8" className="dropdown-submenu" title="">
                           <a tabIndex="-1" href="#">Sign Into Different Room</a>
                           <Dropdown.Menu>
                                <MenuItem header bsClass="inside-title-sections"><b>Team Rooms</b></MenuItem>
                                {otherRooms}
                            </Dropdown.Menu>
                        </MenuItem>

**Comment by bobdelphi9999** [comment]
"<MenuItem eventKey="8" className="dropdown-submenu" title="">
                           <a tabIndex="-1" href="#">Sign Into Different Room</a>
                           <Dropdown.Menu>
                                <MenuItem header bsClass="inside-title-sections"><b>Team Rooms</b></MenuItem>
                                {otherRooms}
                            </Dropdown.Menu>
                        </MenuItem>"

**Comment by taion** [comment]
This isn't part of the Bootstrap menus.

**Comment by bobdelphi9999** [comment]
@taion , you mean MenuItem does not support the multilevel menu, right?
Thanks!
