### ISSUE TITLE
Overwriting component styles (like Input)

### ISSUE THREAD

**Issue by ppiekarczyk** [react-bootstrap/react-bootstrap#1715]
Hey everyone,
This library has been very handy, thank you very much :)

Is there a way to handle overwriting component styles?

For example, `<Input />` includes the `form-group` class which adds `margin-bottom: 20px` to every `Input`. I would like to get rid of, or overwrite that `form-group` class.

Is my only way of handling this so far is to edit the bootstrap css?

Thank you!

**Comment by taion** [comment]
`groupClassName`
