### ISSUE TITLE
Modal component not firing _onHide

### ISSUE THREAD

**Issue by justinwyllie** [react-bootstrap/react-bootstrap#1716]
When you hide the modal it should fire _onHide. It doesn't. Because it doesn't fire _onHide it doesn't turn off listening to the window resize event. Then when the window is resized there is an error in this line:

  var scrollHt = node.scrollHeight

because the node for the Modal no longer exists. (I.e. it was hidden but _onHide wasn't fired: that's the issue).

It seems that _onHide should be called when onExited is fired. So it looks like that is not being fired. 

Our usage seems fairly standard - passing in the show prop as true or false. To close the modal we re-render the parent component passing in false to show on the Modal.

Version: 0.28.1

**Comment by taion** [comment]
You're using an outdated version.

**Comment by justinwyllie** [comment]
Ok. This was indeed resolved in version 0.28.3.
