### ISSUE TITLE
turn off navbar-default on Navbar Component.

### ISSUE THREAD

**Issue by lyquocnam** [react-bootstrap/react-bootstrap#1721]
i only need to change navbar style, but react-bootstrap only support 2 style: default + inverse
i set bsStyle="home" and receive:

`Warning: Failed propType: Invalid prop `bsStyle` of value `home` supplied to `Uncontrolled(Navbar)`, expected one of ["default","inverse"]. Check the render method of `Component`.`

i think we should remove this warning for free to set custom style.

**Comment by taion** [comment]
You can modify the list of available `bsStyle`s yourself.

**Comment by lyquocnam** [comment]
how can i do that @taion ?

**Comment by taion** [comment]
Use `bootstrapUtils`.

**Comment by lyquocnam** [comment]
what is bootstrapUtils ?

**Comment by jquense** [comment]
It is resolved, we aren't removing the warning because in most cases its helpful to users. If you want to add a custom or additional style to a Component, the way to do it is to use the `bootstrapUtils` methods in `/lib/utils`

**Comment by lyquocnam** [comment]
have any docs or demo @jquense  ?
thanks so much !

**Comment by jquense** [comment]
no docs (PR welcome if you'd like to contribute) but its fairly simple

```js
import Button from 'react-bootstrap/lib/Button'
import bUtils from 'react-bootstrap/lib/utils/bootstrapUtils'

bUtils.addStyle(Button, 'minimal') // renders `btn-minimal` when you do <Button bsStyle='minimal' />
```

**Comment by lyquocnam** [comment]
i tried with navbar:
```
import bUtils from 'react-bootstrap/lib/utils/bootstrapUtils';
bUtils.addStyle(Navbar, 'home');
```
this error:
`Uncaught TypeError: styles.forEach is not a function`
any missing ?

**Comment by jquense** [comment]
oops slight bug, it needs to be an array: `bUtils.addStyle(Navbar, ['home']);`

**Comment by lyquocnam** [comment]
it worked ! thanks @jamesakers awesome !
