### ISSUE TITLE
Button:disabled should use pointer events by default

### ISSUE THREAD

**Issue by droganov** [react-bootstrap/react-bootstrap#1726]
Problem:
We need to display a hint why the button is disabled, but hint does not appear because the button has disabled state.

```
<OverlayTrigger placement="bottom" overlay={ tooltip }>
   <Button bsStyle="default" className="btn-invert" disabled={ true }>View Details</Button>
</OverlayTrigger>
```

**Comment by taion** [comment]
That's just how mouse events on disabled elements work (or don't, rather).

**Comment by droganov** [comment]
@taion that's solid example of a design problem: you need to explain why item is disabled and you can't do it because it's disabled.

Please think again.

Disabled html button is able to display it's title.

**Comment by taion** [comment]
This is exactly how it works in upstream Bootstrap with tooltips on disabled buttons as well.

It's not a "design problem" just because the API doesn't happen to do exactly what you expect for your specific use case.

**Comment by droganov** [comment]
this is a poor design indeed

**Comment by jquense** [comment]
We are not magically free from the restrictions of browser limitations.

as @taion said, this isn't a design choice its a restriction due to __browsers not firing mouse events on disabled elements_

**Comment by droganov** [comment]
@jquense please read here: https://react-bootstrap.github.io/components.html#tooltips

> Tooltip component for a more stylish alternative to that anchor tag title attribute.

What is the meaning for word "alternative"? If a real tootltip is shown and "alternaive" is not then is it really an "alternaive"? How do you think?

Does it make sense? If yes, then someone might be have to think a lil' bit how to avoid that "browsers" don't fire events.

**Comment by taion** [comment]
Again, per upstream, this is working as intended: https://github.com/twbs/bootstrap/issues/10049.

Incidentally, `title` on disabled elements is not a cross-browser-safe way of doing things, so you're doubly wrong.

I'm closing this issue thread as being no longer productive.

**Comment by jquense** [comment]
> If yes, then someone might be have to think a lil' bit how to avoid that "browsers" don't fire events.

Unfortunately "believing hard enough" is not actually sufficient to make browsers behave how I want. If you figure out a per-format way to do it by all means, go a head a PR something, instead of just demanding that we boil the ocean for you.
