### ISSUE TITLE
Add import statement at example code

### ISSUE THREAD

**Issue by ev1stensberg** [react-bootstrap/react-bootstrap#1728]
Add: `import {Button, ButtonToolbar} from 'react-bootstrap;'` in the code snippet. People tend to copy paste and they don't care about what's in the previous section. Also, that is in an own sub-url, which means that people may ignore/oversee it. 

[First Code snippet](https://react-bootstrap.github.io/components.html)

**Comment by ev1stensberg** [comment]
This generally goes for all the sample code

**Comment by taion** [comment]
Not appropriate given that we support multiple import styles.

**Comment by ev1stensberg** [comment]
Maybe just add a comment at top of each snippet? :smile:
