### ISSUE TITLE
We try to cloneWithProps non-components

### ISSUE THREAD

**Issue by stevoland** [react-bootstrap/react-bootstrap#174]
Test case from Glanjamin on IRC: http://jsfiddle.net/Hhc8z/1/

Hope to have some time at the weekend to fix this.

**Comment by mtscout6** [comment]
Just tried this in the live docs:

```
let Hello = React.createClass({
    render() {
        return (
          <Navbar brand="Whoops">
            Stuff
          </Navbar>
        );
    }
});
 
React.render(<Hello name='world' />, mountNode);
```

![](http://cl.ly/image/16443J0L2W3t/Image%202015-03-30%20at%207.50.00%20PM.png)

Is this still an issue?
