### ISSUE TITLE
Navbar does not collapse on mobile device/chrome emulator

### ISSUE THREAD

**Issue by mrisoli** [react-bootstrap/react-bootstrap#1741]
I pasted the example responsive navbar from the react-bootstrap website on to a component on a Meteor app, I used the default bootstrap CSS files, while the navbar does collapses when resizing my browser, it does not collapse when using any emulated device on chrome or when testing on my mobile device(Moto X 2014). Could this be a React-Bootstrap issue or is it a Meteor one?(By the way, following the Mantra spec for meteor).

**Comment by piotrromanowski** [comment]
Have you included the viewport meta tag?
Example:
`<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">`
