### ISSUE TITLE
Install issue on ubuntu 14.04

### ISSUE THREAD

**Issue by charlie-ablett** [react-bootstrap/react-bootstrap#1744]
Hi there,

I'm using npm 2.14.20 / nodejs 4.4.0 on Ubuntu 14.04.

When I try to install react-bootstrap to add to my project, I get the following:

    npm ERR! peerinvalid The package history@1.13.1 does not satisfy its siblings' peerDependencies requirements!
    npm ERR! peerinvalid Peer react-router@1.0.3 wants history@^1.17.0

Please advise?

Many thanks
c.

**Comment by taion** [comment]
Those packages are unrelated to React-Bootstrap.
