### ISSUE TITLE
New form controls API

### ISSUE THREAD

**Issue by taion** [react-bootstrap/react-bootstrap#1749]
Replaces https://github.com/react-bootstrap/react-bootstrap/issues/176, https://github.com/react-bootstrap/react-bootstrap/issues/342, https://github.com/react-bootstrap/react-bootstrap/issues/1674.

Combining a number of older issues regarding revamping the forms API. The new, mostly lower-level API will consist of:

- `<FormGroup>`
- `<InputGroup>`
- `<FormControl>`: this will wrap `<input class="form-control">`
  - For component classes, support e.g. `<FormControl componentClass="textarea" />`
  - For static controls, use `<FormControl.Static>`
  - `<FormControl.Label>` will wrap `<label class="control-label">` for horizontal form layouts
- `<Checkbox>`, `<Checkbox inline>`, `<Radio>`, `<Radio inline>`: wrap the TWBS-specific markup around labels
  - No support for `<CheckboxGroup>` or `<RadioGroup>` for now – they're more nice-to-haves that we can figure out later on
- `<Input>`: this will behave mostly like the current version, but it will only support the simple vertical label/field layout; other use cases will have to go to the lower-level API

Questions:

- Better name for `<Input>`? Maybe `<FieldGroup>`?
- Should `onChange` pass through the event, or the value? (for compatibility with React Formal)

**Comment by jquense** [comment]
> Should onChange pass through the event, or the value? (for compatibility with React Formal)

the event is fine, provided we address: https://github.com/jquense/react-formal/issues/39#issuecomment-192356926 I think trying to parse values will get ugly and folks will complain they aren't getting the whole event.

> Better name for <Input>? Maybe <FieldGroup>

I like FieldGroup

**Comment by taion** [comment]
Yeah on second thought it does make more sense for R-B not to coerce `onChange` value.

**Comment by taion** [comment]
I'm thinking `<FieldGroup>` is pointless. The gain from doing:

```js
<FieldGroup
  label="First name"
  type="text"
  onChange={this.onChange}
/>
```

seems is too minimal compared to:

```js
<FormGroup>
  <label>First name</label>
  <FormControl type="text" onChange={this.onChange} />
</FormGroup>
```

**Comment by jquense** [comment]
The only win I think you get from it is `htmlFor` if an ID is provided

**Comment by taion** [comment]
I think I'll handle that by snooping on children in `<FormGroup>`, along with using `bsRole`.

A few more bikesheddy questions:

- For help blocks, do I use `<HelpBlock>` or `<FormGroup.HelpBlock>`? They only make sense in the context of a `.form-group`, but the CSS class is `.help-block`. They're gone in Bootstrap 4 anyway.
- For checkboxes and radios, do I do e.g. `<Checkbox>` or `<FormControl.Checkbox>`? The CSS class is something like `.checkbox`, and the markup is completely different from normal `.form-control`s.
- For validation state icon, I'm leaning toward requiring an explicit component, since this is what's required upstream, and just sniffing for `bsRole` again to figure out whether to apply `.has-feedback` to the `.form-group`. Does it make sense to call this `<FormControl.Feedback>` or `<FormGroup.Feedback>`? The CSS class here is `.form-control-feedback`, but it only makes sense in the context of a `.form-group.has-feedback`.

**Comment by taion** [comment]
Actually, probably less magical to put a `controlId` prop on `<FormGroup>`.

**Comment by taion** [comment]
Let's track this on https://github.com/react-bootstrap/react-bootstrap/pull/1765.
