### ISSUE TITLE
Support mastheads

### ISSUE THREAD

**Issue by ev1stensberg** [react-bootstrap/react-bootstrap#1750]
Do you support Mastheads? I cannot seem to find it in the docs.

**Comment by taion** [comment]
That's not part of Bootstrap. Please check the docs before opening issues to ask questions.

**Comment by ev1stensberg** [comment]
https://todc.github.io/todc-bootstrap/components/#navbar-masthead

**Comment by taion** [comment]
http://getbootstrap.com/

**Comment by ev1stensberg** [comment]
Well, thanks for sorting the misunderstanding out, Jimmy :smile: , sorry for disturbing.
