### ISSUE TITLE
Conditional bsStyle

### ISSUE THREAD

**Issue by DeimonDB** [react-bootstrap/react-bootstrap#1761]
I have an \<Input\> which depending on state changes, will have `bsStyle="error"` style or not.

Currently what I do is something like:
`<Input bsStyle={hasError ? "error" : ""} />`

But this approach shows warning message that bsStyle should be one of ["success", "warning", "error"].
The complete warning message is: 

> warning.js?8a56:45 Warning: Failed propType: Invalid prop `bsStyle` of value `` supplied to `FormGroup`, expected one of ["success","warning","error"]. Check the render method of `Input`.

What is the adviced approach to solve this?

**Comment by jquense** [comment]
use `undefined` as the empty value instead of an empty string
