### ISSUE TITLE
Tab contents not rendered after fast switching

### ISSUE THREAD

**Issue by ktxed** [react-bootstrap/react-bootstrap#1766]
If I'm switching fast between tabs the contents of the tabs won't be rendered anymore.
Workarounds: 
- reload page
- disable animations for `<Tabs>` (`<Tabs defaultActiveKey={1} animation={false}>`)

Can be reproduced here: https://react-bootstrap.github.io/components.html#tabs @ Uncontrolled Tabs section.

How to reproduce:
![tabs_not_rendered 1](https://cloud.githubusercontent.com/assets/6363327/14226296/0fd574fc-f8e7-11e5-8aa6-174bb7fd30db.gif)

**Comment by jquense** [comment]
we've refractored all the internal tab stuff so I'm hoping this isn't still a problem, we'd have to confirm against the "next" branch tho

**Comment by pl12133** [comment]
I was experiencing this issue using `react-bootstrap: "0.28.5"`.

I upgraded to `react-bootstrap: "0.29.4"` and the issue seems to be fixed.

**Comment by ktxed** [comment]
@pl12133 Confirmed. So I will close this issue ;)
