### ISSUE TITLE
Breadcrumb Documentation

### ISSUE THREAD

**Issue by ryayak1460** [react-bootstrap/react-bootstrap#1767]
At the [Breadcrumb](https://react-bootstrap.github.io/components.html#breadcrumbs) documentation, it refers to `Breadcrumb.Item` which raised an invariant error in React.  However, using the following code worked:

    import React, { Component, PropTypes } from 'react'
    import { Breadcrumb, BreadcrumbItem } from 'react-bootstrap'

    class OurComponent extends Component { 
      render() {                                                                       
        return (                                                                       
          <article>                                                                    
            <Breadcrumb>                                              
              <BreadcrumbItem active>                                                  
                Default
              </BreadcrumbItem>                                                        
                                                                                   
              <BreadcrumbItem href="/other">                                
                Other
              </BreadcrumbItem>                                                        
                                                                                   
              <BreadcrumbItem href="/another">                               
                Another
              </BreadcrumbItem>                                                     
            </Breadcrumb>                                                           
                                                                                
            { this.props.children }                                                 
                                                                                
          </article>                                                                
        )                                                                           
      }                                                                             
    }                                                                               

Not sure if the `Breadcrumb.Item` class will actually work, so I just wanted to give you all a heads up.

**Comment by taion** [comment]
You need to upgrade to the new release to use the new syntax.

**Comment by ryayak1460** [comment]
Thanks!
