### ISSUE TITLE
Input: Focus to Input field when <label> is clicked 

### ISSUE THREAD

**Issue by i-anunay** [react-bootstrap/react-bootstrap#1768]
A small accessibility / ease of access issue:

Click on label here:
http://getbootstrap.com/css/#forms

The focus goes to the input fields.

doesn't happen here:
https://react-bootstrap.github.io/components.html#input-types

Happy to submit a PR if this feature is needed.

**Comment by jquense** [comment]
that's just browser behavior when labels have `for` attribute, if you add an ID to the input it will wire that up and it should work fine

**Comment by i-anunay** [comment]
:+1:

Its good to update react-bootstrap.github.io forms section ?

**Comment by taion** [comment]
We're redoing everything on https://github.com/react-bootstrap/react-bootstrap/pull/1765.

**Comment by jquense** [comment]
we should make a point to make sure the docs use ids, it seems to be a point of confusion recently

**Comment by taion** [comment]
All the examples on the PR use `controlId` on the `<FormGroup>`s when a `<ControlLabel>` is present.

**Comment by jquense** [comment]
:+1: nothing else to do then I think
