### ISSUE TITLE
Typescript / babel 5 issue

### ISSUE THREAD

**Issue by tijmenvangulik** [react-bootstrap/react-bootstrap#1770]
There is a problem in babel 5 which prevents me from writing imports like this in typescript when I use react bootstrap (it has to do with a different default implementation):

import Button from "react-bootstrap/lib/Button";
import Input from "react-bootstrap/lib/Input"; 

Without this new es6 notation I have also problems with web storm recognizing the JSX notation.

Can you please upgrade the project to babel 6. I have already tested this and I could upgrade the current code without major problems to babel 6. (To make it working I only had to add the transform-decorators-legacy plugin to the existing commit which is waiting to be integrated https://github.com/react-bootstrap/react-prop-types/pull/18)

**Comment by jquense** [comment]
can you tell us what doesn't work? I have a hunch that upgrading won't help because we would use a plugin to restore Babel 5 export behavior to avoid a terrible API for common JS module users

**Comment by taion** [comment]
Where are you even getting TypeScript definitions for R-B that are compatible with that import syntax? It doesn't look like the definitions on DefinitelyTyped are set up that way.

**Comment by tijmenvangulik** [comment]
I will add more details this evening when I am home. About de typescript definitions, I changed the typescript definitions my selves. It is very easy, The material material-ui trunk is already using babel 6 and has up to date typescript definitions . I could just implemented the bootstrap definitions the same way as the material definitions. (just adding changing a view lines for every component) I am not yet ready with all the definitions so it is not yet ready for publication. I also need a more permanent solution for the babel issue before publication.

**Comment by tijmenvangulik** [comment]
typescript 1.8.9 compiles
```
import Button from "react-bootstrap/lib/Button";
<Button onClick={this.clicked.bind(this)} >click</Button></div>
```
to:
```
var Button_1 = require("react-bootstrap/lib/Button");
 React.createElement(Button_1.default, {onClick: this.clicked.bind(this)}, "click")
```

react bootstrap compiled with Babel 5

exports the de button like this:

```
exports['default'] = _utilsBootstrapUtils.bsStyles(ButtonStyles, _styleMaps.DEFAULT, _utilsBootstrapUtils.bsSizes([_styleMaps.Sizes.LARGE, _styleMaps.Sizes.SMALL, _styleMaps.Sizes.XSMALL], _utilsBootstrapUtils.bsClass('btn', Button)));
module.exports = exports['default'];
```

This results into typescript not finding the default becauses it accesses Button_1.default and in babel 5 Button_1 contains the Button and this button does has no default

react bootstrap compiled in Babel 6

Babel 6 uses a different way of exporting the button which is compatible with typescript:

`exports.default = (0, _bootstrapUtils.bsStyles)(ButtonStyles, _styleMaps.DEFAULT, (0, _bootstrapUtils.bsSizes)([_styleMaps.Sizes.LARGE, _styleMaps.Sizes.SMALL, _styleMaps.Sizes.XSMALL], (0, _bootstrapUtils.bsClass)('btn', Button)));`

This is compatible with typescript because the default is the button it selves. 

I expect that this breaking  babel change will also cause problems when combining other babel 6 libraries with react bootstrap compiled in babel 5.

**Comment by taion** [comment]
We are not going to stop setting `module.exports` to the actual exported class when we use Babel 6, as this would break CJS users.

This appears to be an issue with how TypeScript doesn't use the CJS export fallback when using ES modules; as such, please follow up with them, or use the CJS require syntax.

**Comment by tijmenvangulik** [comment]
As far as I have read is that the Babel 5 way of writing the export is invalid ES6 semantic and that is why it is removed. (in short babel 5 does not follow the standard) At some point the react-bootstrap should comply with the standards otherwise it can not integrate with other new libraries which move on to ES6 and the new version of babel. In my opinion waiting too long with this will only make the upgrade harder because more code needs to be converted.

**Comment by taion** [comment]
We're simply not going to structure our CJS build in such a way as to break the `require('react-bootstrap/lib/Button')` syntax. At some point we might offer a native ES module build, but we are not going to change the semantics of the CJS module build; otherwise there wouldn't be any point.

**Comment by tijmenvangulik** [comment]
Thank you for the quick reply There are two plugins available which can give you best of both worlds migrate to babel 6 and retain backwards compatibility  with babel 5:

- transform-decorators-legacy
- babel-plugin-add-module-exports

Tijmen

**Comment by jquense** [comment]
when it comes to interop with other module systems there is no such thing as "standard". Babel dropped the babel5 behavior because it was sort of "magical" how exports were defined and they made a choice to simplify it. The code that babel 6 outputs tho is no more "valid" es6 module code then the old way, because its all poly fill anyway.

we do know about __babel-plugin-add-module-exports__, and do plan on using it, but as we said that will just make babel 6 behave like babel 5, so it won't fix your problem here.

**Comment by tijmenvangulik** [comment]
If you use the "babel-plugin-add-module-exports" plugin then I only have to disable the plugin to make it work with typescript. An you do not have to modify your code. Both will win. Future developers and existing developers.

Tijmen
