### ISSUE TITLE
DropDown MenuItem disabled color not reflecting if color not default

### ISSUE THREAD

**Issue by andray71** [react-bootstrap/react-bootstrap#1772]
if you set text-primary class on MenuItem content and the item is desabled the color not reflecting it.

**Comment by taion** [comment]
It's not supposed to.

**Comment by andray71** [comment]
It does in bootstrap.

**Comment by andray71** [comment]
here is with out text-primary class (you can see the difference)
[image: Inline image 1]

here is with the text-primary - all looks the same

[image: Inline image 2]

i can not see the differences.

here is the regular bootstrap buttons:
[image: Inline image 3]
you can see the difference.

Thanks,

Andray

**Comment by taion** [comment]
Please fix the attached images.

**Comment by taion** [comment]
I can't reproduce this. `.text-primary` doesn't even do anything for menu items because of the default Bootstrap styling.

**Comment by andray71** [comment]
nice
