### ISSUE TITLE
Context not getting updated in modal child component

### ISSUE THREAD

**Issue by SachaG** [react-bootstrap/react-bootstrap#1777]
I had the idea of building a `ModalTrigger` component that you can call to display any component inside a modal window:

```jsx
<ModalTrigger component={<Button bsStyle="primary">New Post</Button>}>
    <PostNewForm/>
</ModalTrigger>
```

So this would display a "New Post" `<Button/>` that shows the `<PostNewForm/>` modal when clicked. 

Most of this works, except that I don't have access to the proper context inside of `<PostNewForm/>`. To be more specific, when prop `foo` changes from `bar` to `baz` in the context, its value stays as `baz` in `<PostNewForm/>` until the next time the component is rendered. So `<PostNewForm/>` is always one step behind. 

Does this make sense? Any idea what I'm doing wrong?

**Comment by SachaG** [comment]
OK, so here's what I came up with. I'm curious to know if this is the right solution, because it does look a little weird.

I defined a `ContextPasser` component whose sole function is to take props and pass them on as context:

```
class ContextPasser extends Component {

  getChildContext() {

    return {
      foo: this.props.foo
    };
  }

  render() {
    return this.props.children;
  }
}
ContextPasser.childContextTypes = {
  foo: React.PropTypes.object
};
```

Which I then call inside the `ModalTrigger` component's render method:

```
class ModalTrigger extends Component {

  constructor() {...}

  openModal() {...}

  closeModal() {...}

  render() {

    const triggerComponent = React.cloneElement(this.props.component, { onClick: this.openModal });

    return (
      <div className="modal-trigger">
        {triggerComponent}
        <Modal bsSize={this.props.size} show={this.state.modalIsOpen} onHide={this.closeModal}>
          <Modal.Body>
            <ContextPasser foo={this.context.foo}>
              {this.props.children}
            </ContextPasser>
          </Modal.Body>
        </Modal>
      </div>
    )
  }
};
```

**Comment by jquense** [comment]
context is passed through to modals already, so you don't need to do anything special... what version of React and react-bootstrap are you using?

**Comment by SachaG** [comment]
React 0.14.7 and react-bootstrap 0.28.4. To be more precise, context *is* getting passed through, just not the most up to date context, if that makes sense.

**Comment by jquense** [comment]
there might be a pure component blocking the update, if not its probably one of the context bugs in React, react 0.15 may fix it as well, perhaps give the RC a spin to see?

**Comment by taion** [comment]
Are you using Redux?

**Comment by SachaG** [comment]
OK I'll see about giving 0.15 a try. And no I'm not using Redux.

**Comment by taion** [comment]
Closing for staleness. This is most likely a pure component thing.
