### ISSUE TITLE
keyboard escape not working on modal

### ISSUE THREAD

**Issue by hozefaj** [react-bootstrap/react-bootstrap#1783]
the modal is not closing when the escape key is pressed

```
<Modal show={this.props.show}
  keyboard
  onEntered={this.onEntered}
  tabIndex="-1" >
```

**Comment by taion** [comment]
You need to pass on `onHide`.

**Comment by hozefaj** [comment]
👍

**Comment by 00155837364765867** [comment]
> You need to pass on `onHide`.

This is not an answer. GitHub only allowing smiling faces and thumbs up is umm, a very Microsoft policy. No-one is allowed to disagree anymore?! Welcome to Microsoft's entrance into cancel-culture! Yuk!
