### ISSUE TITLE
Modal dialog closes when we drag inside modal and release mouse button on dialog

### ISSUE THREAD

**Issue by akiran** [react-bootstrap/react-bootstrap#1785]
Modal dialog is closing if we drag inside modal and release mouse button on dialog

This bug was also present in bootstrap previously https://github.com/twbs/bootstrap/issues/13816.  I think, it is fixed now

**Comment by taion** [comment]
This was the actual fix in TWBS upstream: https://github.com/twbs/bootstrap/pull/14724

**Comment by kaiyoma** [comment]
Will this be getting fixed anytime soon? I'm running into this issue with an overlay that has a scrollbar, so we hit this problem often when grabbing the scrollbar and releasing the mouse button.

**Comment by jgrisafe** [comment]
Created pull request to fix this, @kaiyoma - https://github.com/react-bootstrap/react-bootstrap/pull/2738

If anyone has any problems using onMouseDown instead of onClick please let me know why. It seems to work fine in my application.

**Comment by qtbit** [comment]
It seems all the sub-issues are closed after a year. Is it fixed to be ready to release?

**Comment by Rupinderthind** [comment]
try 

.modal{
  pointer-events: none;
  .modal-dialog{
    pointer-events: none;
    .modal-content{
      pointer-events: auto;
    }
  }
}

**Comment by Rupinderthind** [comment]
try
`.modal{
  pointer-events: none;
  .modal-dialog{
    pointer-events: none;
    .modal-content{
      pointer-events: auto;
    }
  }
}`

**Comment by justingolden21** [comment]
Coming here from not using Bootstrap and using Svelte, but in case this helps anyone using any CSS framework and any JS framework (since this page ranks high on google)

```
<div class="modal" on:mousedown={close}>
		<div class="modal-content" on:mousedown|stopPropagation>
```

Changing my listener from on click to mousedown solved it for me :)

**Comment by enesekremergunesh** [comment]
I have figure out different way to solve the problem, idk if it will cause a problem later but anyway it works, so basically, I put 'modal-dialog' to another <div> object (I call it 'modal-helper') and then put it to 'modal'. The 'modal-helper' element width and height are inherited (100%) as default but there is small space on top so you can use some margin and padding to close it.

`<div class="modal fade" id="login-modal" tabindex="-1" aria-labelledby="loginModalLabel" style="display: none;" aria-hidden="true">
     <div id="modal-helper" style="pointer-events: auto;">
          <div class="modal-dialog">
               ...
          </div>
     </div>
</div>
`

Then I have used some JS to hide modal when 'modal-helper' (as backdrop) is clicked (by the 'clicked' I mean when pointerup event triggered after pointerdown event on 'modal-helper' triggers).

The code below sets the value of isPointerDownToModalHelper true when pointerdown event triggered on 'modal-helper', then when the pointerup event triggered on any object it hides the modal and sets the value of isPointerDownToModalHelper back to false:
`var login_modal_helper = document.getElementById('modal-helper')
var isPointerDownToModalHelper = false;
addEventListener('pointerdown', (event) => {
     var objectID = event['path']['0']['id'];

     if (objectID === login_modal_helper.id) { // if pointer was over modal-helper
          isPointerDownToModalHelper = true;
     }

});

addEventListener('pointerup', (event) => {

     if (isPointerDownToModalHelper === true) {
          isPointerDownToModalHelper = false;
          $('#login-modal').modal('hide'); // hide the modal
     }

});`

It seems to work fine for now, I hope it can help someone :).

**Comment by enesekremergunesh** [comment]
I have figure out different way to solve the problem, idk if it will cause a problem later but anyway it works, so basically, I put `modal-dialog` to another `<div>` object (I call it `modal-helper`) and then put it to `modal`. The `modal-helper` element `width` and `height` are inherited (100%) as default but there is small space on top so you can use some `margin` and `padding` to close it.

```
<div class="modal fade" id="login-modal" tabindex="-1" aria-labelledby="loginModalLabel" style="display: none;" aria-hidden="true">
     <div id="modal-helper" style="pointer-events: auto;">
          <div class="modal-dialog">
               ...
          </div>
     </div>
</div>
```

Then I have used some JS to hide modal when `modal-helper` (as backdrop) is clicked (by the 'clicked' I mean when `pointerup` event triggered after `pointerdown` event on `modal-helper`).

The code below sets the value of `isPointerDownToModalHelper` `true` when `pointerdown` event triggered on `modal-helper`, then when the `pointerup` event triggered on any object it hides the modal and sets the value of `isPointerDownToModalHelper` back to `false`:

```
var login_modal_helper = document.getElementById('modal-helper')
var isPointerDownToModalHelper = false;
addEventListener('pointerdown', (event) => {
     var objectID = event['path']['0']['id'];

     if (objectID === login_modal_helper.id) { // if pointer was over modal-helper
          isPointerDownToModalHelper = true;
     }

});

addEventListener('pointerup', (event) => {

     if (isPointerDownToModalHelper === true) {
          isPointerDownToModalHelper = false;
          $('#login-modal').modal('hide'); // hide the modal
     }

});
```

It seems to work fine for now, I hope it can help someone :).
