### ISSUE TITLE
Dual react installation with shrinkwrap

### ISSUE THREAD

**Issue by testerez** [react-bootstrap/react-bootstrap#1798]
In my project I started to have strange errors and realised that it was due to a dual installation of react.

I isolated the minimum setup to reproduce the issue:
```
npm init -y
npm i --save react@0.14 react-dom@0.14 react-bootstrap
npm shrinkwrap
rm -rf node_modules/
npm install
npm list react
```

Here is the result I get:
```
npm3@1.0.0 /Users/testerez/projects/trash/npm3
├── react@0.14.8 
└─┬ react-bootstrap@0.28.5
  └── react@15.0.1 
```

Do I do something wrong here?

(using node v4.4.2, npm 2.15.0)

**Comment by testerez** [comment]
It seams to be a srkinwrap error https://github.com/npm/npm/issues/5135
Feel free to close it...

**Comment by testerez** [comment]
Moving react dependency to dev-dependency could solve the issue.
Something to consider?

**Comment by jquense** [comment]
react is already a dev dep in RB or did you mean something else?

**Comment by testerez** [comment]
Ok sorry I did not check. npm is really doing strange stuff here
