### ISSUE TITLE
react 15 released, please upgrade too

### ISSUE THREAD

**Issue by lyquocnam** [react-bootstrap/react-bootstrap#1799]
currently, it will show some warning:
`Warning: `value` prop on `input` should not be null. Consider using the empty string to clear the component or `undefined` for uncontrolled components.`

`Warning: `value` prop on `select` should not be null. Consider using the empty string to clear the component or `undefined` for uncontrolled components.`

`Warning: `value` prop on `textarea` should not be null. Consider using the empty string to clear the component or `undefined` for uncontrolled components.
`

**Comment by taion** [comment]
This is on your end.
