### ISSUE TITLE
ListGroupItem with header emits <p>

### ISSUE THREAD

**Issue by SonOfLilit** [react-bootstrap/react-bootstrap#1800]
`ListGroupItem` checks whether it has a header, and if it does - emits a `<p>` element wrapping the body.

This is bad because we all hate having dozens of warnings:

![image](https://cloud.githubusercontent.com/assets/14973/14412983/fd2ee000-ff75-11e5-908d-a7ad59686486.png)

This is the problematic bit of code:

```
  renderStructuredContent() {
    let content = (
      <p key="content" className={bootstrapUtils.prefix(this.props, 'text')}>
        {this.props.children}
      </p>
    );
```

Yes, the [Bootstrap example](https://getbootstrap.com/components/#list-group-custom-content) shows `list-group-item-text` as a `<p>` element, but surely it doesn't *have* to be, and if `this.props.children` is not a `<span>`, it's better to not make it one?

**Comment by taion** [comment]
Dupe https://github.com/react-bootstrap/react-bootstrap/issues/983
