### ISSUE TITLE
Button bsStyle="self-made" support?

### ISSUE THREAD

**Issue by Siyfion** [react-bootstrap/react-bootstrap#1804]
I use the LESS version of the Bootstrap library and as such I have used their `.button-variant()` mixin to create some custom button classes. While I can specify them as values to `bsStyle` (and they **work fine**) I get warnings all over the place, which makes debugging a bit of a nightmare.

Is there any way that I can get around this? Either by adding a list of "allowable classes" or disabling the warning!?

**Comment by jquense** [comment]
see: https://github.com/react-bootstrap/react-bootstrap/pull/1788

**Comment by Siyfion** [comment]
@jquense Thanks! Had no idea that existed, but it's along my lines 👍
