### ISSUE TITLE
Nav onSelect ES6 - event isn't passed

### ISSUE THREAD

**Issue by sgentile** [react-bootstrap/react-bootstrap#1805]
The documentations shows this example:
```
handleSelect(event, selectedKey) {
    event.preventDefault();
    alert('selected ' + selectedKey);
  },

<Nav bsStyle="tabs" activeKey={1} onSelect={this.handleSelect}>

```

I'm using React.Component ... ie.

```
<Nav bsStyle="tabs" activeKey={this.state.activeKey} onSelect={this.handleSelect}>
```

I'm unable to get access to the event object

this
```
handleSelect(e, selectedKey) {
        e.preventDefault();
        this.setState({
            activeKey: selectedKey
        })
    }
```

nor this

```
handleSelect = (e, selectedKey) => {
        e.preventDefault();
        this.setState({
            activeKey: selectedKey
        })
    };
```

provides the event - e is undefined.   

Is there a way to get both the event and the selectedKey on handleSelect ?

**Comment by jquense** [comment]
Looks like we missed NavItem in the onSelect signature clean up.

There isn't anyway to get the event for Nav's right now, aside from listening to the onClick event on each NavItem. This will change in the next version though

**Comment by sgentile** [comment]
ok thank you for your quick follow up!

I moved the handler to the NavItem and it did what I needed for it to do

Thanks again!

**Comment by taion** [comment]
I thought we did catch it in the cleanup? It is fixed on next, but not master.

**Comment by jquense** [comment]
o oops only checked master, duh

**Comment by taion** [comment]
Okay, well, this is fixed on the alpha releases for the next version.
