### ISSUE TITLE
Nesting Nav components is receiving console warning

### ISSUE THREAD

**Issue by andrewmclagan** [react-bootstrap/react-bootstrap#1806]
When nesting Nav / NavItem stacked as such:

````
<Nav bsStyle="pills" activeKey={1} stacked>
  <NavItem eventKey={1} href="/sdf">
    <i className="fa fa-file-o"></i>Jobs
    <Nav bsStyle="pills" activeKey={122} stacked>
      <NavItem eventKey={121} href="/bvcf">All Jobs</NavItem>
      <NavItem eventKey={122} href="/fgjucd">Add New</NavItem>
      <NavItem eventKey={123} href="/dfbjhu">Categories</NavItem>
    </Nav>                
  </NavItem>
  <NavItem eventKey={2} href="/dcgjuf"><i className="fa fa-street-view"></i>Organisations</NavItem>
  <NavItem eventKey={3} href="/sdvggf"><i className="fa fa-dollar"></i>Payments</NavItem>
  <NavItem eventKey={4} href="/sdfdthsq"><i className="fa fa-bar-chart-o"></i>Reports</NavItem>
</Nav>
````

I get the following warning:

`warning.js:45 Warning: validateDOMNesting(...): <a> cannot appear as a descendant of <a>. See Admin > NavItem > SafeAnchor > a > ... > NavItem > SafeAnchor > a.`

and an invariant error:

`invariant.js:39 Uncaught Invariant Violation: ReactMount: Two valid but unequal nodes with the same `data-reactid`: .....`

**Comment by taion** [comment]
It is in fact illegal to nest `<a>`s (links) that way. This isn't an issue with React-Bootstrap; it's just something that isn't allowed in HTML.

**Comment by andrewmclagan** [comment]
Just to be clear, would that not be the following rendered HTML

````
<ul>
    <li>
        <a>
            <ul>
                <li>
                    <a>link</a>
                </li>
            </ul>
        </a>
    </li>
</ul>
````

And if that is incorrect, as im assuming. What is the correct way to achieve nested nav elements in react-bootstrap.

**Comment by taion** [comment]
Take a look at `<SubNav>` in our docs source. That's one example of rendering nested navigation elements. You can also take inspiration from how it's done in the Bootstrap docs.

**Comment by andrewmclagan** [comment]
wow that is awesome... someone should really migrate that to the actual package no?

**Comment by taion** [comment]
1. It's not part of upstream Bootstrap and probably requires extra styling in user space
2. It's not quite good enough
3. It's not very complicated to reimplement in user space

As such, we're not planning on moving it back into the main package for the time being.
