### ISSUE TITLE
Select Input with optgroup's & initial value, does not set the right option

### ISSUE THREAD

**Issue by Siyfion** [react-bootstrap/react-bootstrap#1810]
For a complete example of the issue please take a look at this CodePen: http://codepen.io/Siyfion/pen/yOKdrj

You can see that the initial value is set to `YYY`, yet when the code first runs the `option` with the value `XXX` is shown by default. Not only that, but if you then change it to the correct option, it (as expected) no longer allows you to change the value.

**Comment by taion** [comment]
This isn't an R-B bug; you get the same thing with a naked `<select>`.

**Comment by Siyfion** [comment]
Sorry @taion but that's utter nonsense. Proof: http://codepen.io/Siyfion/pen/LNmXmM

**Comment by Siyfion** [comment]
Ahhh sorry, you didn't mention that it was the `<optgroup>` causing the issue... See: http://codepen.io/Siyfion/pen/yOKdrj

Okay.... now to figure out a way-around.

**Comment by taion** [comment]
Correct.
