### ISSUE TITLE
Use react-bootsrap and bootstrap - css - only

### ISSUE THREAD

**Issue by Cabanask** [react-bootstrap/react-bootstrap#1811]
Hello  I use the component "bootstrap-react" and the "bootstrap - css - only" module I do not understand why SRK adds "app" to the css class.
eg bootstrap css name: ".btn-success" but the RSK in renome "App_btn-success_1AG". I therefore can not use "React-bootstrap" & "bootstrap - css - only". Someone you already used it both component? Thanks for your help .

**Comment by taion** [comment]
We just use the straight Bootstrap classes. That prefix is getting added elsewhere.

**Comment by Cabanask** [comment]
ok tanks  i  use react-starter-kit  and think it's the probleme or webpack .

**Comment by dozoisch** [comment]
You probably have a css loader in webpack that uses css-modules. You need to make sure it uses a pure css loader with bootstrap and not css-modules.
