### ISSUE TITLE
what is "componentClass={ControlLabel}" for in Horizontal Forms example?

### ISSUE THREAD

**Issue by barbalex** [react-bootstrap/react-bootstrap#1819]
In Horizontal Forms (https://react-bootstrap.github.io/components.html#forms-horizontal) the provided code example includes `componentClass={ControlLabel}` in the Col elements.

If included this way it produces an error, because ControlLabel is undefined.

This is confusing as the role of this code is not explained.

Why is this code there?

**Comment by jquense** [comment]
you are probably looking at the new docs while running an older version

**Comment by barbalex** [comment]
lots of new stuff here, thanks for this great tool!
