### ISSUE TITLE
Where is FormControl explained?

### ISSUE THREAD

**Issue by barbalex** [react-bootstrap/react-bootstrap#1820]
The horizontal form example (https://react-bootstrap.github.io/components.html#forms-horizontal) contains FormControls.

These are not explained. No Props are listed.

Do they differ from Input elements?

Why are they used here and not Input elements?

**Comment by jquense** [comment]
https://react-bootstrap.github.io/components.html#forms-props-form-control there is no more Input, all the examples use form control now

**Comment by barbalex** [comment]
thanks!

**Comment by Itachi-Uchiha78** [comment]
404

**Comment by drews256** [comment]
@Itachi-Uchiha78 

Looks like an updated link is at: 

https://react-bootstrap.github.io/components/forms/#forms

And the valid Bootstrap Form Control Types are here: 

https://v4-alpha.getbootstrap.com/components/forms/#textual-inputs

**Comment by r-bechara** [comment]
Okay, you put the newest API documentation, but where is FormControl docs? What about legacy software built on top of your component set. Should we throw them away?

**Comment by jquense** [comment]
Not sure what the question is...all the docs are in git so if you need docs from a few years ago you can pull the code. Otherwise the latest and v0.32 docs are hosted linked in the readme

**Comment by ErikRobles** [comment]
I have found a lack of info on how to send the form in using React-Bootstrap forms. The documentation is lacking. It does a nice job in showing you how to implement the visual aspects of the form but not how to submit it.
