### ISSUE TITLE
Tab collapses on FormControl focus

### ISSUE THREAD

**Issue by AnderssonChristian** [react-bootstrap/react-bootstrap#1822]
In my application I have three `Tab` components inside of a `Tabs` component. Each `Tab` has a set of `FormControl` elements. I just upgraded to the latest react-bootstrap and with the previous implementation of the above with `Input` all worked fine.

Now, however, whenever a input field is clicked or otherwise given focus, the whole Tab collapses.
I'm not getting any errors or warnings in the console.

Here's a minimal and verifiable code that I tried on its own, which also produces the above issue:

    <Tabs activeKey={this.state.tabsKey} onSelect={this._handleSelect} animation={false} id="sub-task-tabs">
      <Tab eventKey={1} title="Extern länk">
        <FormGroup>
          <ControlLabel>Titel</ControlLabel>
          <FormControl type="text" onChange={this._subTaskInputChange0} value={this.state.subTaskInput0} />
        </FormGroup>
      </Tab>
    </Tabs>

Here's two screenshots I took.

_Before click on input field (Titel):_

![img1](http://i.imgur.com/nRM3jBf.png)

_After:_

![img2](http://i.imgur.com/hjwRaKm.png)

**Comment by jquense** [comment]
Thanks for the heads up! Looks like this is what's happening: 

somewhere in the Tab chain the `onSelect` is being passed to a DOM node, the inputs fire a natvie onSelect which is bubbling up and being confused for the Tab onSelect, so the first arg is the event  object instead of the eventKey, which is in turn used as the activeKey, which doesn't work b/c no tabs have an eventKey that is the event object of a native onSelect :P

**Comment by AnderssonChristian** [comment]
@jquense No worries! Yeah, I figured it had to be the two components conflicting with each other somehow. Hoping for a quick hotfix for this :)

**Comment by jharris4** [comment]
I just hit this bug as well, any word on a fix?

**Comment by yoursdearboy** [comment]
@jharris4 @taion's PR works perfectly. You can clone `react-bootstrap`, merge it and install the package from git.

**Comment by jharris4** [comment]
@yoursdearboy Yes thanks, I was just looking at the PR, wrote the last comment before I realized it was already fixed

**Comment by jharris4** [comment]
In the off chance anyone is looking for an easy workaround before the fix makes it into a release, I was able to workaround the bug by checking the type of the key value passed to the Tabs component's handleSelect callback.

If the key is an object, I ignore it and return immediately, but if the key is a number, I proceed as normal and set the key state for the active tab...
