### ISSUE TITLE
Warning: "hasFeedback" property of "FormGroup" has been deprecated.

### ISSUE THREAD

**Issue by trevorr** [react-bootstrap/react-bootstrap#1826]
When I upgraded from 0.28 to 0.29, I started getting these warnings when using `Input`:

```
Warning: "hasFeedback" property of "FormGroup" has been deprecated.
Use a `<FormControl.Feedback>` element.
```

To be clear, I'm not specifying `hasFeedback` at all in my `Input` instantiation.

Perhaps this is caused by `Input` having `hasFeedback: false` in its `defaultProps` and passing all properties to the underlying `FormGroup`? If `Input` itself is not deprecated, it seems that it should not produce this warning.

**Comment by taion** [comment]
`<Input>` is deprecated.

**Comment by trevorr** [comment]
Shouldn't there be a mention of that somewhere, such as the [changelog](https://github.com/react-bootstrap/react-bootstrap/blob/master/CHANGELOG.md) or issue #1749? I see now in `Input.js` it will generate a deprecation warning, but I must have missed it in the output because the warning above occurs once per instance (and my form has a lot of Inputs).

**Comment by taion** [comment]
It is in the changelog:

>**Feature/Deprecation:** Rewrite form and form control API, and deprecate the old API (#1765)

**Comment by trevorr** [comment]
Ok, thanks. I guess I was looking/grep'ing for `Input` and not "form control".

**Comment by taion** [comment]
I'll update the changelog to make it more clear.

**Comment by taion** [comment]
Done: https://github.com/react-bootstrap/react-bootstrap/commit/d79fb8801453f99c2dafc60cdfa7ef7b16c5e96b
