### ISSUE TITLE
Tooltip `arrowOffsetLeft` or Top doesn't work with overlaysTrigger

### ISSUE THREAD

**Issue by Vivekbhusal** [react-bootstrap/react-bootstrap#1828]
`arrowOffsetLeft` works well on `Tooltip` but if used with `overlayTrigger`, it doesn't work.

### Just Tooltip
![image](https://cloud.githubusercontent.com/assets/1974260/14665375/1941e07e-0716-11e6-9fef-9d1a484884f0.png)

### With OverlayTrigger

![image](https://cloud.githubusercontent.com/assets/1974260/14665418/72fcdef2-0716-11e6-900a-e59ce362357a.png)

**Comment by taion** [comment]
It's not supposed to do so. Wrap it in another component that intercepts the value passed through from position if you want to do this.

**Comment by Vivekbhusal** [comment]
Will you please provide an example? Also, shouldn't Tooltip's behaviour remain same and not change because of another component. I mean to say, component A shouldn't change the behaviour of component B. Just my 2 cents.

**Comment by taion** [comment]
https://github.com/react-bootstrap/react-bootstrap/issues/1640
