### ISSUE TITLE
NavDropdown props not documented

### ISSUE THREAD

**Issue by barbalex** [react-bootstrap/react-bootstrap#1832]
NavDropdown is mentioned and even used in a few spots in the readme. But nowhere are its props listed. Or have I missed something?

**Comment by jquense** [comment]
its b/c its just a DropdownButton with some additional defaults.

**Comment by barbalex** [comment]
It would be very helpful to see that in the documentation, like here: https://react-bootstrap.github.io/components.html#navs-dropdown.

And maybe also here: https://react-bootstrap.github.io/components.html#buttons-props (to explain the misterious navDropdown prop)

**Comment by jquense** [comment]
the `navDropdown` is deprecated legacy at this point

**Comment by barbalex** [comment]
you guys are working hard :-)
