### ISSUE TITLE
onBlur on Input fires twice

### ISSUE THREAD

**Issue by evdelst** [react-bootstrap/react-bootstrap#1834]
I am migrating to version 0.29 from 0.28.5
We rely on onBlur events, and I notice that in the 'old' Input tag, the onBlur is fired twice instead of once.

The new components only fire onBlur once (but we need time to migrate the existing code, so we will have a mix of old/new style inputs).

Example:
```
<form>
    <Input type='text' label='X' onBlur={()=>console.log('blur-input')}/>
    <FormGroup controlId="formControlsText">
      <ControlLabel>Text</ControlLabel>
      <FormControl type="text" placeholder="Enter text" onBlur={()=>console.log('blur-control')} />
    </FormGroup>
</form>
```

**Comment by taion** [comment]
It's probably coming from both the form group and the input or something. Nothing we can really do – it's deprecated.
