### ISSUE TITLE
DropdownButton with no bsStyle

### ISSUE THREAD

**Issue by ruiaraujo** [react-bootstrap/react-bootstrap#1837]
I would to use DropdownButton with bsStyle set to empty since otherwise I can't get the inset effect on the open state.

Currently this triggers a failed prop type warning. Is there another way of doing this?

Setting to any of the variants, even default, prevent the inset effect I wish to have.

**Comment by jquense** [comment]
I'm not quite sure what you are trying to do, but the best way to add your own button style is to _use_ bsStyle to set a custom class like `btn-inset` where `bsStyle` is `"inset"`, you cna add your own bsStyles to the validation lists via the bootstrapUtils and addStyle

**Comment by ruiaraujo** [comment]
Ok. Thanks for the suggestion.
I am porting a angular app to React and because this button wasn't using 'btn-default' on the toggle button it has this inset effect which is part of the bootstrap style.

My problem is that I would the button that is rendered to only have the classes 'dropdown-toggle btn', nothing else. At this moment, it always add one of the variants unless I do my dirty hack.

**Comment by ruiaraujo** [comment]
Your suggestion actually lets me do whatever I want. Hacky or a clean way.

Thanks for the quick response!
