### ISSUE TITLE
FormControl value

### ISSUE THREAD

**Issue by swarthy** [react-bootstrap/react-bootstrap#1838]
Hello everyone!
After an update of react-bootstrap to v0.29 I replaced all <Input/> with <FormControl/>
Input component has 'getValue()' method, but FormControl doesn't have any similar method.
So, the question is how to get a value from FormComponent?
Thank you in advance

**Comment by jquense** [comment]
see https://github.com/react-bootstrap/react-bootstrap/issues/1821#issuecomment-212179038, but you use findDOMNode and just get the value from the input node
