### ISSUE TITLE
Empty tabs cause error on componentWillUpdate

### ISSUE THREAD

**Issue by jakezatecky** [react-bootstrap/react-bootstrap#1839]
After the fix to #1418, if no `<Tab>`'s are passed to a `<Tabs>` component and the component is redrawn, `componentWillUpdate` will error out with the following error:

```
TypeError: this.panes is undefined
```

The culprit is the following line in `TabContent`:

https://github.com/react-bootstrap/react-bootstrap/blob/master/src/TabContent.js#L85

Prior to #1418, no error would occur when the component is redrawn. I do not know if you want to support this behavior or leave it as is. It's relatively easy to workaround, but I feel that this should be handled more cleanly. If desired, I can create a PR with an associated test to fix this, but I was not sure if this is something you wanted to account for.

**Comment by edy** [comment]
I have the same error while using `arr.map()` inside `Tab.Content`.

My workaround so far is adding an empty `<Tab.Pane>` after the `arr.map()`:

	<Tab.Content animate={false}>
		{this.state.myArray.map((item, i) => {
			return <Tab.Pane eventKey={i} key={item.id}>
				... my stuff ...
			</Tab.Pane>;
		})}
		<Tab.Pane eventKey="__empty">
			{/* https://github.com/react-bootstrap/react-bootstrap/issues/1839 */}
		</Tab.Pane>
	</Tab.Content>

**Comment by taion** [comment]
This got fixed.
