### ISSUE TITLE
SplitButton can't be used in Navs/Navbar

### ISSUE THREAD

**Issue by dozoisch** [react-bootstrap/react-bootstrap#184]
The DropdownButton has a property called navItem which can be used when you want to render components in a Nav/navbar.

The SplitButton which is a similar component doesn't have that prop and always render in a button. Is that a wanted behavor or should it have the same prop has DropdownButton to be renderable in a nav?

**Comment by dozoisch** [comment]
Probably going to close this, as it's not something that exists in bootstrap. The only thing we could do is to render it in 2 li (one with the caret, the other one with the text passed). But then they are split like two different lis and the user couldve done it himself.

**Comment by mtscout6** [comment]
I agree, it's not in Bootstrap so let's scrap it.
