### ISSUE TITLE
Alert when moving away from the page of components to the other documentation page

### ISSUE THREAD

**Issue by ya-kostik** [react-bootstrap/react-bootstrap#1842]
When I left [the page of components](http://react-bootstrap.github.io/components.html) through the main menu, I get the alert `selected undefined`

![sitebug](https://cloud.githubusercontent.com/assets/12064332/14748473/f3455494-08ca-11e6-8faf-6cdf4e677392.gif)

It is not critical. Just want to let you know.

Regards.

**Comment by taion** [comment]
This was fixed.
