### ISSUE TITLE
Feature Request: polyfill for <input type="text" placeholder="foo" /> for IE9

### ISSUE THREAD

**Issue by jeffgran** [react-bootstrap/react-bootstrap#1843]
Something like https://github.com/enigma-io/react-input-placeholder/blob/master/src/react-input-placeholder.js

Alternatively, maybe react-bootstrap's <FormControl> could take an optional prop that is the class of the "actual" input that it renders, and we could pass in something like the above?

**Comment by taion** [comment]
You can pass in a custom `className` on `<FormControl>`.

**Comment by jeffgran** [comment]
Thank you for the quick response but that is not what I meant. I wasn't clear -- I meant passing in a React Component so that it would render a `<MyPolyfilledInput />` instead of a `<input />`.

**Comment by taion** [comment]
That's `componentClass`.

**Comment by jeffgran** [comment]
oh, awesome.  I didn't know that was there. Thanks!
