### ISSUE TITLE
Tab content disappears when clicking on text input inside the tab

### ISSUE THREAD

**Issue by ihinsdale** [react-bootstrap/react-bootstrap#1847]
I have a Tab that contains an `<input type="text">`. When I click on that input element, the entire tab disappears from view: the relevant `<div>` goes from
```
<div id="foo-pane-0" role="tabpanel" aria-hidden="false" aria-labelledby="foo-tab-0" class="active tab-pane fade in" data-reactid="240">...</div>
```
to
```
<div id="foo-pane-0" role="tabpanel" aria-hidden="true" aria-labelledby="foo-tab-0" class="tab-pane fade" data-reactid="240">...</div>
```
Losing the `active` and `in` classes causes the Tab to effectively disappear.

This bug also exists for a `<textarea>` element that I have in another Tab. Clicking the `<textarea>` element causes the containing tab to disappear.

This bug was introduced in v0.29.0. I have confirmed that it is not present in v0.28.5.

**Comment by ihinsdale** [comment]
In v0.29.2 this bug is not present.

**Comment by ihinsdale** [comment]
Ah, I see now this was a duplicate of #1822.

**Comment by andrewmclagan** [comment]
cool, also had this. x.29.2 fixed it
