### ISSUE TITLE
Improve Documentation for Forms

### ISSUE THREAD

**Issue by PolGuixe** [react-bootstrap/react-bootstrap#1850]
I can't see in the Docs a good alternative to:

```
const {input1, input2} = this.refs;
submitMethod(input1.getValue(), input2.getValue());
```

How can a value be obtained from the `<FormControl/>` component?

**Comment by jquense** [comment]
you can just use findDOMNode on the component to get the underlying input

**Comment by nmn** [comment]
The switch from the old Input to Form Controls has many downsides. This being just one more.

**Comment by taion** [comment]
`getValue` was a broken API in that it wasn't compatible with any sort of HoCs like from Redux. That you can now use `getDOMNode` to get the DOM node from the `<FormControl>` no matter how you wrap it was one of the explicit goals here.

**Comment by vinnymac** [comment]
I understand that we can now use `getDOMNode` and `ReactDOM.findDOMNode` to get the node from the `FormControl`. In fact I think this is better for everyone, and seems to follow a more react friendly way of obtaining the node. However the name of this issue is `Improve Documentation for Forms`, which I don't believe has been taken care of. 

I only knew to make this change in my projects because I found these issues. I think it would be better to leave this open until documentation for explaining this is added, unless of course we expect people to just assume this is what they need to do from now on.

**Comment by jquense** [comment]
PRs Welcome! we'll happily take a doc improveent

**Comment by chalda** [comment]
I still dont see any end-to-end examples of how to work with values in FormGroups. You mention using findDOMNode but I don't quit understand how to do this easily.

this jsfiddle is probably the most example code I found on the net and it works with inputs directly:
http://jsfiddle.net/mnhm5j3g/1/

I think I might just have to rewrite everything with plain <inputs>.

**Comment by jquense** [comment]
@chalda there is nothing special to be done about managing values, the FormControl's are just wrappers around the plain inputs, so you do the same things to manage values as you would plain inputs

**Comment by Industrial** [comment]
Hi!

first of all thanks to everyone who contributed to this project. It's an enormous help for people trying to bust out apps world wide I think.

I'm now converting an old codebase to a new version of this, and I'm changing all the `<Input>`'s into `<FormControl>`'s.

I've never worked with `findDOMNode` before but the documentation had a big fat WARNING saying it's not a good idea to be using it. I tried to but I'm not sure I understand the API. It seems to be taking a Component, would that be the `this` inside a component definition/class?

It would be highly beneficial for me for the documentation to include small code examples how "how to get stuff done", and in my experience leaving things implied will always get some reader/user in trouble down the line :-)

**Comment by PolGuixe** [comment]
I am having problem while performing unit tests with enzyme. How would you accesss the `input.value` field?

**Comment by nadeemja** [comment]
Could a kind soul please provide a working code example? 
Thanks.

**Comment by taion** [comment]
There are multiple working examples on the components page.

**Comment by vinnymac** [comment]
For those saying that they don't know what `findDOMNode` is or are afraid of using it because of the warnings, read over the [documentation](https://facebook.github.io/react/docs/top-level-api.html#reactdom.finddomnode) more thoroughly. It explicitly states

> This method is useful for reading values out of the DOM, such as form field values

This method is meant to be used for this case.

**Comment by nadeemja** [comment]
@taion 

Apologies, I was unclear. The code example I would greatly appreciate, is one which demonstrates the alternative to this.refs and .getValue().

Thanks :)

**Comment by jquense** [comment]
@nadeemja you use refs and `findDOMNode(this.refs.input).value`

**Comment by taion** [comment]
Clarifying the docs a bit more in https://github.com/react-bootstrap/react-bootstrap/pull/2077.

**Comment by justin808** [comment]
Is there any way that we can do this with the callback syntax: https://facebook.github.io/react/docs/refs-and-the-dom.html#the-ref-callback-attribute

I get the below errors with the latest eslint.

```
  114:15  error  Do not use findDOMNode                                 react/no-find-dom-node
  136:17  error  Using string literals in ref attributes is deprecated  react/no-string-refs
```

**Comment by dozoisch** [comment]
@justin808 You can use the same callback syntax as you would with a normal input. The wrappers are meant to be lightweight! So you can just put an onChange callback on it.

**Comment by josiahsprague** [comment]
I'm a bit unclear on how to get the value of a `<FormControl>` without using `findDOMNode` since [that is now being warned against](https://github.com/yannickcr/eslint-plugin-react/issues/678#issue-165177220).

My component with the ref looks like this;
```
<FormControl ref={node => this.productFilter = node} type="text" placeholder="Type here to filter products" defaultValue={this.props.data.filterValue} />
```
And I want to use the value of the input here;
```
updateFilter(e) {
    e.preventDefault();
    this.props.updateFilter(this.productFilter.value); // this.productFilter.value is undefined
  }
```

**Comment by jquense** [comment]
Folks, there is now a ton of documentation and pass issues where getting and setting the values of form inputs is covered **extensively**. Follow up comments on this and other related issues only serve to ping a bunch of people unnecessarily. 

Our stance on on this API has been clear from the start here. The **correct** way to get values from inputs, is to use controlled inputs. For those don't want to/can't use idiomatic React patterns, we we aren't inventing an interface to native DOM elements when React already provides **two**. I still have no problem recommending using `findDOMNode` regardless of what the 3rd party eslint plugin rules say about it, (`no-set-state` is _also_ a rule but no one would suggest using setState is an "anti pattern"). If you really don't want to use `findDOMNode`, the `inputRef` prop was added just for you.
