### ISSUE TITLE
Modal autoFocus does not refocus on last focused element when Modal is closed

### ISSUE THREAD

**Issue by vga-** [react-bootstrap/react-bootstrap#1851]
According to the documentation when a Modal's `autoFocus = true`, which it does by default, then 

> The modal will automatically shift focus to itself when it opens, and replace it to the last focused element when it closes.

However, this does not seem to be working properly in the react-bootstrap doc. examples and in my own app. It does set focus to the modal when opened, but it does not replace it to the last focused element when it closes. Rather, it resets the focus to the top of the main document.

I checked the react-overlays modal example, and it does seem to be working correctly there; that is why I'm opening the issue here.

For now, my fix is to set ids for the elements that open the modal, and set focus to those elements manually using the `onExited` prop of the Modal.

I haven't had a chance to dig into the code yet to see if I can find a real fix, but I would appreciate it if anyone can confirm that it's broken in the Modal example itself.

**Comment by vga-** [comment]
I think I've pinpointed this bug, and it does reside in react-overlays. I'm going to create an issue there, refer to this issue, and submit a pull request.

**Comment by yelloo98** [comment]
ㅠㅠ픂
