### ISSUE TITLE
Suggested way to style accordions

### ISSUE THREAD

**Issue by josephdburdick** [react-bootstrap/react-bootstrap#1853]
Hi there, I want to control the inner-workings of accordions by using a css class. Specifically I want to target the style of links inside of panel-headings to append a pseudo-selector...I can handle the CSS end of this but no matter what the global values are applied and my style is ignored.

**Comment by jquense** [comment]
you'll need to use a css selector to style the bits of the panel you want. I'd look to best practices for styling normal bootstrap, and make sure you have the css specificity correct so your styles cascade correctly

**Comment by josephdburdick** [comment]
Given the following code, I've passed a css-module hashed CSS class down to the Accordion module, and, in a previous attempt, passed a hashed CSS class down to the <Panel> component as well, attempting bsClass and bsStyle. 

The class gets passed down and it styles ONLY the components that accepts the hashed CSS class, but none of the children within those components gets touched. 

```
export default class AccordionModule extends React.Component {
  static propTypes = {
    title: React.PropTypes.string,
    items: React.PropTypes.oneOfType([
      React.PropTypes.arrayOf(React.PropTypes.shape({header: React.PropTypes.string.isRequired, order: React.PropTypes.number.isRequired, htmlContent: React.PropTypes.string.isRequired}).isRequired).isRequired,
      React.PropTypes.shape({header: React.PropTypes.string.isRequired, order: React.PropTypes.number.isRequired, htmlContent: React.PropTypes.string.isRequired}).isRequired
    ]).isRequired
  }

  render() {
    const titleArea = (!stringNullOrEmpty(this.props.title)
      ? <h1>{this.props.title}</h1>
      : null);
    const itemsArea = this.props.items.map(item => (
      <Panel key={item.order} header={item.header} eventKey={item.order} data-item>
        <div dangerouslySetInnerHTML={{
          __html: item.htmlContent
        }}></div>
      </Panel>
    ));

    return (
      <div>
        {titleArea}
        <Accordion className={styles.accordion}>{itemsArea}</Accordion>
      </div>
    );
  }
}
```

**Comment by jquense** [comment]
I'm not sure how your css is written but you should hook into the actual bootstrap classes using :global if you are using css modules

**Comment by josephdburdick** [comment]
Solution: 
```<Panel className={`${styles['accordion-panel']}`} key={item.order} header={item.header} eventKey={item.order} data-item>
        <div dangerouslySetInnerHTML={{
          __html: item.htmlContent
        }}></div>
      </Panel>```
[This part of the documentation](http://react-bootstrap.github.io/components.html?ref=driverlayer.com/web#panels-props-accordion) didn't state that `className` was an available option.

**Comment by josephdburdick** [comment]
Specifically I had to create a class name that wasn't already specified from the component. `.panel` wouldn't do. Creating a custom class name `.accordion-panel` did the trick.

**Comment by josephdburdick** [comment]
This is still a problem actually. There's currently no straight-forward way to style the inner children of the Accordion components. The only reason I was able to style the panel-title links is because I target them like so:

```
.accordion {
  font-size: 1rem;
}
.accordion-panel{
  display: block;
  border-width: 0;
  box-shadow: none;
  background-color: transparent;

  // Heading links/triggers
  a[aria-expanded]{
    display: block;
    position: relative;
    &:after{
      content: '';
      position: absolute;
      right: 0;
      top:0;
      display: block;
      background-color: $ymblue;

      font-size: 1rem;
      font-family: "proxima-nova", sans-serif;
      font-style: normal;
      font-weight: 700;
      text-align: center;

      width: 1.250em;
      height: 1.250em;
      line-height: 1.250em;
      color: white;
    }
    &[aria-expanded="true"]{
      &:after{
        content: '–';
      }
    }
    &[aria-expanded="false"]{
      &:after{
        content: '+';
      }
    }
  }
}
``` 

Any attempt to style the `panel-heading` or `panel-body` class is futile even if using css-modules. 
Here's my attempt: 

```
.accordion-panel{
  &.panel-default{
    font-size: 1rem;
    & > .panel-heading{
      font-size: 1rem;
      padding-left: 0;
      padding-right: 0;
      border: 0;
      background-color: red;
    }
    // Panel Body
    & > .panel-collapse{
      font-size: 1rem;

      .panel-body{
        font-size: 1rem;
        border-top: 0;
        background-color: red;
      }
    }
  }
}
```

**Comment by taion** [comment]
You need to use `:global` to target global classes with CSS modules. Again, it otherwise works the same as it would with anything Bootstrap-related.

**Comment by josephdburdick** [comment]
@taion I ended up using this and it works but I'm confused as to why:
```
:global(.panel-title){
    background-color: pink;
 }
```
above my `.accordion` definition, which would be given a unique hash name. If `.panel-title` is nested within this hashed class, why does it need to be global to be recognized? Shouldn't the nesting within a unique class name be enough?

**Comment by jquense** [comment]
@josephdburdick take a look at the output css in both cases, it should be clear why one over the other
