### ISSUE TITLE
Doc bug? bootstrapUtils.addStyle takes an array parameter

### ISSUE THREAD

**Issue by kintel** [react-bootstrap/react-bootstrap#1855]
The doc says:
```
bootstrapUtils.addStyle(Button, 'custom');
```

..but in reality the style needs to be an array:
```
bootstrapUtils.addStyle(Button, ['custom']);
```

Is this a doc bug?

**Comment by taion** [comment]
Upgrade your version of React-Bootstrap.

**Comment by kintel** [comment]
thx for the amazingly quick answer - I had just realized I wasn't on the latest version after all.
