### ISSUE TITLE
getValue() and other functions from InputBase

### ISSUE THREAD

**Issue by FQ400** [react-bootstrap/react-bootstrap#1856]
I recently updated react-bootstrap to version 0.29.2 and started the migration.
All the function from InputBase like [`getValue()`](https://github.com/react-bootstrap/react-bootstrap/blob/master/src/InputBase.js#L12) or [`getSelectedOptions()`](https://github.com/react-bootstrap/react-bootstrap/blob/master/src/InputBase.js#L28) are missing in `FormControl`. Is this intended?

**Comment by jquense** [comment]
dup: #1850

**Comment by FQ400** [comment]
Thanks. 😄
