### ISSUE TITLE
Modal has inline display:block style

### ISSUE THREAD

**Issue by RosyTucker** [react-bootstrap/react-bootstrap#1857]
I hit in issue today where it seams that the Modal component is created with an inline style:

```
var modalStyle = _extends({
      display: 'block'
    }, this.props.style);
```

This means that the only way to override it (e.g to use `display:flex`) is to use important in your CSS (as far as I'm aware).

Any idea what the reasoning is for this and why it cannot be in the CSS file?

**Comment by taion** [comment]
It's to override `display: none`. Why not just put the `display: flex` one level down?
