### ISSUE TITLE
RFC: Transition callbacks should be fired when no animation is specified.

### ISSUE THREAD

**Issue by Lavoaster** [react-bootstrap/react-bootstrap#1858]
After talking with @taion, it's clear we have different view on this. I feel that transitions between components, such as the Tabs, where the visibility of the tab is changed should fire the same callbacks that are called when an animation is specified.

What are everyone's thoughts on this?

**Comment by taion** [comment]
I think structurally we just don't want this – we have existing select handlers that pick up on these events. Generally those callbacks are properties of the animation handlers, not of the rest of the component.

**Comment by taion** [comment]
@jquense Any thoughts here?

**Comment by jquense** [comment]
I do sort of find it annoying sometimes that there isn't a symetry here, but overall I agree with @taion the callbacks are explicitly for the sake of animation. I think if it's necessary that a component expose consistant callbacks, they should be distinct from the animation lifecycle hooks (which really exist to facilitate css animations)

**Comment by taion** [comment]
Okay, let's close this out then. To the extent we're missing explicit lifecycle hooks, let's add those.
