### ISSUE TITLE
Should Popover copy props on div?

### ISSUE THREAD

**Issue by jardakotesovec** [react-bootstrap/react-bootstrap#1860]
Popover [copies](https://github.com/react-bootstrap/react-bootstrap/blob/master/src/Popover.js#L83) props on first div.  I am wondering whats the intention here?

I had issue with component using Popover that had prop `onClick` was getting event from DOM, because this props gets copied on that div inside Popover.

So it can get tricky for such scenarios.

**Comment by taion** [comment]
That's quite intentional – it's to let you do something like:

```js
<Popover onClick={this.onClick}>
  {content}
</Popover>
```

and have the popover respond to clicks.
