### ISSUE TITLE
Checkbox getChecked 

### ISSUE THREAD

**Issue by cgreening** [react-bootstrap/react-bootstrap#1863]
Hi All,

I can't work out how to get the checked value from a Checkbox component. Is there any way to do this? findDOMNode doesn't seem to help because it doesn't get the input elements.

Thanks

**Comment by taion** [comment]
You can do `findDOMNode.querySelector('input')`. I'm not sure we really want to wrap this up further; public instance methods are generally not encouraged these days because they don't really work with containers.

Alternatively, add on `onChange` hook and track the state in a parent.

**Comment by taion** [comment]
I wonder if we can add an `inputRef` prop to support a ref function here.

**Comment by jquense** [comment]
thats better then a getValue() api, but still just listen to onChange, anything else is not idiomatic React afaic

**Comment by taion** [comment]
Assigning refs to inputs is a thing though: https://facebook.github.io/react/docs/more-about-refs.html#the-ref-string-attribute
