### ISSUE TITLE
Missing eventKey prop for custom ButtonComponentClass in PaginationButton.js (v.0.29.x)

### ISSUE THREAD

**Issue by northerneyes** [react-bootstrap/react-bootstrap#1866]
I need information about which page is rendered. It is impossible to create SEO wise links now.

**Comment by smashercosmo** [comment]
Could someone explain why evenKey property is removed for buttonComponentClass? How can we render links with real urls and not just onSelect callback?

**Comment by taion** [comment]
Go ahead and PR adding it back for now.

**Comment by smashercosmo** [comment]
Cool) Was doubting may be it was done for reason)

**Comment by taion** [comment]
It was elsewhere, but I agree that you need it here.

**Comment by AndreiRailean** [comment]
The code is in with a test showing how to generate urls. Waiting for next release to roll this into my app.

**Comment by taion** [comment]
v0.29.4
