### ISSUE TITLE
Provide Confirm, Alert and Prompt components

### ISSUE THREAD

**Issue by jochenberger** [react-bootstrap/react-bootstrap#1867]
There should be out-of-the-box replacements for `window.confirm`, `window.alert`, and `window.prompt`, based upon `Modal`.
The functionality could be similar to what http://bootboxjs.com/ offers.
For example, I'd like to be able to write
```jsx
<Confirm show={this.state.showConfirm}
                onConfirm={this.doStuff.bind(this)}
                onCancel={this.hideConfirm.bind(this)}>
  Are you sure?
</Confirm>
```
Maybe there could even be a `WithConfirm` HOC to be used with a `Button`.

**Comment by jquense** [comment]
Hi, while I agree that these are useful components, aren't something we will make as they aren't part of bootstrap and so are out of scope for react-bootstrap. The example above is fairly straight forward to implement yourself as well in your own app components as well luckily.
