### ISSUE TITLE
need inline prop for the FormGroup?

### ISSUE THREAD

**Issue by wufeng87** [react-bootstrap/react-bootstrap#1868]
I want to implement a row form layout, like:
Label_A   Control_A    Label_B    Control_B
Label_C   Control_C    Label_D    Control_D    Label_E    Control_E

I tried the code below, but the label and control in FormGroup are not inline.
Best regards.
```
<Row className="show-grid">
	      	<Col md={1} mdPush={6}>
	      		<FormGroup controlId="cityname" bsSize="small">
		          <ControlLabel>cityname</ControlLabel>
		          <FormControl type="text" placeholder="1" value={_data.cityname}/>
		        </FormGroup>
	      	</Col>
	      	<Col md={6} mdPull={6}>
	      		<FormGroup controlId="name" bsSize="small">
		          <ControlLabel>name</ControlLabel>
		          <FormControl type="text" value={_data.name} />
		        </FormGroup>
	      	</Col>
</Row>
```

**Comment by wufeng87** [comment]
I can do it with css, so close this issue.

**Comment by jquense** [comment]
@wufeng87 use them in Form with `horizontal` set, check the form examples

**Comment by wufeng87** [comment]
@jquense thanks, but I want 2 or 3 FormGroups in one row. :)
