### ISSUE TITLE
Panel.header behaves inconsistently - sometimes it uses panel-title class, another time doesn't

### ISSUE THREAD

**Issue by Liero** [react-bootstrap/react-bootstrap#1870]
If I specify header as string it render without "panel-title" class, but if I specify header as an element, "panel-title" is automatically added and there is no way to avoid it.

```
<Panel header="Lorem ipsum" /> renders as
<div class="panel">
    <div class="panel-heading">Lorem ipsum</div>
</div>
```
but
```
<Panel header="{<div>Lorem ipsum</div>}" /> renders as
<div class="panel">
    <div class="panel-heading">
        <div class="panel-title">Lorem ipsum</div>
    </div>
</div>
```

it gives inconsistent look.
I believe panel-title class should be added in both cases by default and there should be option to turn it of

**Comment by jquense** [comment]
covered in #983
