### ISSUE TITLE
Warning: Invalid prop 'footer' supplied to 'Panel', expected a ReactNode

### ISSUE THREAD

**Issue by StefanoGitHub** [react-bootstrap/react-bootstrap#1871]
Hello,
fairly new to React, but I really don't understand why I get this warning
`Warning: Failed propType: Invalid prop 'footer' supplied to 'Panel', expected a ReactNode. Check the render method of 'GMapPanel'.`
with this (simplified) code:
```
class myPanel extends React.Component {
    constructor(props) {
        super(props);
        this.setLegend = this.setLegend.bind(this);
    } 

    setLegend() {
        return (<div id="legend">myLegend</div>);
    }

    render() {
        return (
            <Panel footer={this.setLegend} bsStyle="primary">
                myBody
            </Panel>
        );
    }
}
```
Isn't `setLegend()` returning a node?
If I create a variable like `legend = (<div id="legend">myLegend</div>)` inside `render()` and using `footer={legend}` then it works, but I've read somewhere it is not good practice putting too much logic inside the render method (I need also to create a header and other stuff). Is this true by the way?

I'm using React-Bootstrap v.0.28.5, and React v.0.14.8.
Thanks,
s.

**Comment by taion** [comment]
You need to call it, like `this.setLegend()`
