### ISSUE TITLE
Update babel-runtime

### ISSUE THREAD

**Issue by khakulov** [react-bootstrap/react-bootstrap#1872]
Babel 6.8.0 now compiled with [Babel 6](https://github.com/babel/babel/releases/tag/v6.8.0).
`npm list babel-runtime` shows me now that only react-bootstrap requires as dependency `babel-runtime@5.8.38`.
Please remove or update babel-runtime dependency to use version 6.
```
...
 "dependencies": {
    "babel-runtime": "^5.8.38",
...
```
to
```
...
 "dependencies": {
    "babel-runtime": "^6.0.0",
...
```

**Comment by jquense** [comment]
fairly certain we can't do other until the RB is also compiled with Babel 6 see the relevant PR for details
