### ISSUE TITLE
"selected undefined" on ghpages

### ISSUE THREAD

**Issue by ahng1996** [react-bootstrap/react-bootstrap#1875]
Hey guys,

I found a little minor issue on the react-bootstrap ghpage where if you go on (https://react-bootstrap.github.io/components.html), and then click on Getting Started there is a dialogue box that says "selected undefined"

edit: running chrome on Windows 10

**Comment by Edward-Lombe** [comment]
Also encountered this issue, running Safari Version 9.0 (11601.1.56)

**Comment by rub1e** [comment]
And me - Chrome on ChromeOS

**Comment by DdMad** [comment]
Encounter the same issue both for Chrome 50.0.2661.102 (64-bit) and Safari Version 9.1.1 (11601.6.17)
on OS X 10.11.5 (15F34)

**Comment by taion** [comment]
This got fixed.
