### ISSUE TITLE
active prop not respected in NavDropdown

### ISSUE THREAD

**Issue by barbalex** [react-bootstrap/react-bootstrap#1878]
I am using NavItems and a NavDropdown for navigation in a Navbar.

When one of the MenuItems of the NavDropdown is active, the NavDropdown needs to be so too and that should be visible to the user (in my App I dynamically change the NavDropdown's title to express the active MenuItem).

Unfortunately it seems that the `active` prop works on NavItems and MenuItems but not on NavDropdowns.
See this jsfiddle: https://jsfiddle.net/barbalex/vh9x7tcp/25/

Obviously this can be achieved by overriding the styling when the NavDropdown is active. And that is my workaround. But the active prop should work, shouldn't it?

**Comment by taion** [comment]
You're not missing anything. This looks like just an oversight. We'd happily accept a PR to fix this.

**Comment by taion** [comment]
Closed by #2015.
