### ISSUE TITLE
How to get value from FromControl?

### ISSUE THREAD

**Issue by hallettj** [react-bootstrap/react-bootstrap#1879]
I feel silly asking this here; but I cannot find any guidance in the documentation or the code.

What is the best practice in v0.29.3 for getting the value of a `FormControl` element when handling a submit event? I would like to do this:

```js
const myValue = this.refs.myFormControl.getValue()
```

But `FormControl` does not extend `InputBase` anymore, and so does not have a `getValue` method.

**Comment by jquense** [comment]
https://github.com/react-bootstrap/react-bootstrap/issues/1850
