### ISSUE TITLE
Don't add new property to synthetic event object

### ISSUE THREAD

**Issue by binarykitchen** [react-bootstrap/react-bootstrap#1880]
React v15.0.2 with react-bootstrap v0.28.5 gives me this warning in Chrome

```
warning.js:44 Warning: This synthetic event is reused for performance reasons. If you're seeing this, you're adding a new property in the synthetic event object. The property is never released. See https://fb.me/react-event-pooling for more information.
```

```
  handleSelect: function handleSelect(e) {
    e.selected = true; <---------------------------------- this is the cause

    if (this.props.onSelect) {
      this.props.onSelect(e, this.props.eventKey);
    } else {
      e.preventDefault();
    }

    if (e.selected) {
      this.handleToggle();
    }
  },
```

**Comment by taion** [comment]
This was fixed by https://github.com/react-bootstrap/react-bootstrap/pull/1864.

**Comment by binarykitchen** [comment]
cool @taion - but can you publish this fix in v0.28.6 too? because we can't bump to v0.29.x here

**Comment by taion** [comment]
No.

**Comment by jquense** [comment]
we don't backport fixes, sorry. it's too much to maintain for us.

**Comment by binarykitchen** [comment]
:(

**Comment by jquense** [comment]
try calling e.persist() yourself on the event, that may fix it

**Comment by binarykitchen** [comment]
How?

I am just using

```
    <Panel
      collapsible
      ...
   </Panel>
```

without any handlers dealing with collapse/expand events. all that happens internally in react-bootstrap.

**Comment by sharma02gaurav** [comment]
You cannot update react component properties just like that. React does have it's own DOM handling.
If you are using redux you can handle that via actions. I was facing the same issue and I solved it by dispatching a state change notifying unavailability of image and setting the state to use the default image.

Actions.js
```
export const useDefaultImage = (useDefault) => {
	return { type: USE_DEFAULT_IMAGE, useDefaultImage: useDefault };
}
```
Reducer.js
```
case USE_DEFAULT_IMAGE:
			return Object.assign({}, state, { useDefaultImage });
```
And the image error handler in JSX.
```
<img src={ useDefaultImage ? defaultImage : `${APPLICATION_ROUTES.OWNER_PROFILE_PIC}/${business}`} onError={() => triggerUseDefaultImage()} height={40} width={40} alt="User Avatar" className="img-circle" />
```

Here i am dispatching a state change on error loading a specific image. And the src element loads the default image on that case.
