### ISSUE TITLE
Imperatively close dropdown?

### ISSUE THREAD

**Issue by ansonkao** [react-bootstrap/react-bootstrap#1882]
I'm using `react-router`, and therefore must replace anchors with the `<Link>` component. The problem occurs when using these `<Link>` components in a dropdown for navigation - click propogation gets overridden, thus preventing the dropdown from closing.

Has anyone else has had the same problem as me?

This is not solved by `react-router-bootstrap`.

**Comment by taion** [comment]
This is a dupe pretty much of https://github.com/react-bootstrap/react-bootstrap/issues/1490, for having more control over dropdown state on click.
