### ISSUE TITLE
Alert can't load react-prop-types/lib/deprecated while using brunch

### ISSUE THREAD

**Issue by janjiss** [react-bootstrap/react-bootstrap#1884]
Hello guys, I am trying to set up the react-bootstrap to work with brunch and I am getting this error. Checked and double checked everything, but can't find a solution:
```
Alert.js:19 Uncaught Error: Cannot find module "react-prop-types/lib/deprecated" from "react-bootstrap/Alert"
```

**Comment by jquense** [comment]
try removing your node_modules and reinstalling

**Comment by janjiss** [comment]
@jquense That does not help.

**Comment by taion** [comment]
There's not really enough information here to go off of. I can verify that with a standard npm install, we still do install `react-prop-types`, and `react-prop-types/lib/deprecated.js` does in fact exist. I don't see much else we can do here.

**Comment by daraclare** [comment]
Hi, I am getting the same error, I'm trying to use React-Bootstrap with Phoenix/Elixir framework using Brunch.io, I'm new to developing so any advice would be great. I am calling in my React Bootstrap in my app.js file: 

```
import React from "react"
import "rect-dom"
import 'react-bootstrap'
import 'react-prop-types/lib/deprecated'
console.log("Hello from Webpack"); 
```

**Comment by jquense** [comment]
@daraclare you probably should be importing from react-prop-types unless you are depending on it directly, if you aren't its likely not installed in the require scope for your app (but is in scope for the RB package itself)

**Comment by daraclare** [comment]
Thanks for the reply jquense, but I'm not sure what you mean (sorry, newbie!). I have tried to import react-props-types without the lib/deprecated, as per below, but I'm still having the same warning, even when emptying cache and hard reloading:

```
import React from "react"
import "rect-dom"
import 'react-bootstrap'
import 'react-prop-types'
console.log("Hello World");
```
Is that what you mean by 'probably should be importing from react-prop-types'? Thanks again!

**Comment by jquense** [comment]
Typo on my comment. you should NOT be importing react-prop-types at all. Why do you have that? You don't import the dependencies of dependencies, they do that themselves

**Comment by daraclare** [comment]
Hi, thanks for your reply, 'should not' makes a lot more sense. Thanks for your reply.

**Comment by janjiss** [comment]
@daraclare I solved the problem by updating brunch. Please try that

**Comment by daraclare** [comment]
Thanks Jan :)

**Comment by janjiss** [comment]
@daraclare did it help?
