### ISSUE TITLE
FormControl support for inputRef

### ISSUE THREAD

**Issue by rwilson** [react-bootstrap/react-bootstrap#1887]
Moving from `Input` to `FormControl` seems to have broken support for specifying an input ref. It looks like `Props` and `Radio` support this via the `inputRef` property, but there is no equivalent for `FormControl`.

**Comment by taion** [comment]
`<FormControl>` doesn't need it; the associated DOM node is the `<input>`.

**Comment by rwilson** [comment]
Ah, that's convenient. I didn't expect that from the changelog on the FormControl refactor. Thanks.

**Comment by oflege** [comment]
If FormControl does not need support for inputRef, how would one invoke, for example, the input's focus() method?
<FormControl ref={(ref) => { this.inputField = ref; }} ...>
associates this.inputField with the FormControl component, so the only way to get the DOM <input> would be s.th. like ReactDOM.findDOMNode(this.inputField).focus()
where instead
<FormControl inputRef={(ref) => { this.inputField = ref; }} ...>
would allow me to invoke this.inputField.focus()

**Comment by taion** [comment]
For now, use `findDOMNode` there. If React offers a general way to expose a specific underlying DOM node, then we'll use that, but unlike for checkboxes, this isn't strictly needed.

**Comment by alexkrolick** [comment]
> this isn't strictly needed.

IMO it is needed if you want to autofocus an input element when, e.g., opening a modal. Using ReactDOM is clunky.

**Comment by sorahn** [comment]
I'd like to throw in another vote for taking the `inputRef` prop on `FormControl`.  I don't think it adds any extra complexity to the component, and accessing form control refs is about the only thing I ever need to do with refs. 

FWIW, I worked around this by copying the FormControl component out of `node_modules/react-bootstrap/es` and putting it in my app.  Then, I added a couple lines of code to pass inputRef as ref, and remove it from the props passed on to 'input'.

**Comment by chrismcband** [comment]
I had a need for this today and whilst findDOMNode does work, it's frowned upon in some circles now and may even be deprecated at some point, see https://github.com/yannickcr/eslint-plugin-react/issues/678#issue-165177220

**Comment by jquense** [comment]
folks we have no real need or desire for this functionality. But if ya'll really like the idea of it, a PR is way more likely to get this in for you then comments here 👍

**Comment by sorahn** [comment]
@jquense good point :)
