### ISSUE TITLE
Where can I find the documents of FormControl?

### ISSUE THREAD

**Issue by hackiechain** [react-bootstrap/react-bootstrap#1888]
Sorry, the question is stupid. After I upgraded to new version 0.29.4, I suddenly find that all of the interfaces and methods of Form were changed. I have read docs on react-bootstrap.github.io, but I cannot find any specified docs related to componentClass of FormControl, except several simple examples and limited explanations.

As the code described below, I try to get the new value of select control. the console log does not fired.
```
<FormControl componentClass="select" placeholder="select" onChange={(e)=>{console.log(e)}}
 <option value="select">select</option>
        <option value="other">...</option>
</FormControl>
```

Without document, I cannot figure out what happened. Does anybody know where can I find those documents? Thanks! 

I know I can read the source code. Due to my limited experience on ES6 programming, I have no clue how to read this huge project. I will be appreciated, if someone can give me any advice.

**Comment by vinnymac** [comment]
I edited the example on the [documentation site](http://react-bootstrap.github.io/components.html#forms) with your onChange handler and it logs just fine.

`FormControl`'s with the `componentClass="select"` will take any props that a `select` element would allow. So onChange should work.

Make sure you have properly installed the latest version of `react-bootstrap`. If you still have trouble try to reproduce the issue in a jsfiddle and post the reproduction steps here.

**Comment by taion** [comment]
Yeah, the first example shows `onChange`. Thanks.
