### ISSUE TITLE
FormControl doesn't correctly support input-sm input-lg

### ISSUE THREAD

**Issue by jquense** [react-bootstrap/react-bootstrap#1889]
Did we forget about these or is there another reason we didn't cover this?

**Comment by taion** [comment]
It's because the Bootstrap CSS sucks – `.form-control` with `.input-sm` doesn't work well with how we do `bsClass`. The size variants on `<FormGroup>` and `<InputGroup>` by contrast look sane.

**Comment by gtwilliams03** [comment]
I ran into this as well - react-bootstrap adds `.form-control-lg` instead of `.input-lg` to a `<FormControl>` inside of a `<FormGroup bsSize="large">` element

**Comment by joelseq** [comment]
I think this should be closed since #2382 was merged

**Comment by taion** [comment]
Oops, thanks!
