### ISSUE TITLE
How get the value with FormControl

### ISSUE THREAD

**Issue by brenopolanski** [react-bootstrap/react-bootstrap#1890]
The react-bootstrap (0.28.5) I have this code:

```js
<Input
     type="text"
     className="amount"
     ref="amount"
     defaultValue="1"
/>
```

and I could use: `this.refs.amount.getValue()`.

and now in **FormControl** ?

**Comment by taion** [comment]
https://github.com/react-bootstrap/react-bootstrap/issues/1879

**Comment by thotruong-allyo** [comment]
In FormControl, you use **inputRef** instead of **ref**

**Comment by thotruong-allyo** [comment]
Use .value and **inputRef** instead of **ref**
`<FormControl inputRef={input => this.textInput = input} type='text' className='amount' .../>
`
Then use this to get value
`this.textInput.value`

**Comment by thomaseuget** [comment]
@thotruong-allyo is it good practice to use refs for all `FormControls` to get the value when submit?
If we don't want to use the standard Submit button.

**Comment by yakupad** [comment]
Hello this solution worked for me!

    <Form
      noValidate
      validated={validated}
      onSubmit={(e) => this.handleSubmit(e)}
      style={{ width: '100%' }}
    >
      <Form.Group controlId="formBasicEmail">
       <Form.Label>Email address</Form.Label>
       <Form.Control type="email" placeholder="Enter email" inputRef={(ref) => { this.email = ref }} required />
       <Form.Text className="text-muted"> Well never share your email with anyone else.
       </Form.Text>
      </Form.Group>
    </Form>

    handleSubmit(event) {
        console.log(event.target.elements.formBasicPassword.value)
    }
