### ISSUE TITLE
Overwhelmed with deprecated warnings

### ISSUE THREAD

**Issue by dlong500** [react-bootstrap/react-bootstrap#1893]
There really needs to be some type of flag other than `NODE_ENV` to toggle the display of deprecation warnings.

With the latest refactor (#1765) deprecating the `<Input>` element, I literally have thousands of deprecation warnings due to large and complex forms.  There are so many that it makes the console slow as molasses and even seems to impact browser performance.  In addition, it becomes just about impossible to see any _real_ errors or pertinent warnings.  Setting `NODE_ENV` to production isn't an option--obviously that will remove all manner of other development messages and tools.

I'm trying to refactor a large project to the new Form Control API, but the deprecation warnings are making it take longer to even do that.

Can we not add some other environment variable that can specifically disable deprecation warnings?  I'm fine with the warnings being on by default as long as we can disable them.

I'd be happy to submit a PR myself at some point but won't have the time for a little while.

**Comment by taion** [comment]
Probably the right thing to do is to only warn once on deprecations. I suspect the issue is with the `deprecated` prop type in react-prop-types.
