### ISSUE TITLE
Independent Collapsing Panel?

### ISSUE THREAD

**Issue by kastork** [react-bootstrap/react-bootstrap#190]
I'm having trouble figuring out how to have panels that collapse and open, but are not exclusive of each other in a group...  i.e., not an accordion behavior, but individually capable of collapsing or expanding.

I can roll my own application of the relevant bootstrap classes, but it seems like this ought to be an option on the Panel component.

Should how to do this be obvious?  What's the formula?

**Comment by mtscout6** [comment]
You can do this today, add the `collapsable` prop. If you want to control the state of whether or not it's expanded externally, use the `collapsable` and `expanded={true|false}` props. We need to document this better.

**Comment by ananya-kundu** [comment]
cv  v

**Comment by ananya-kundu** [comment]
k mnhjhj j j

**Comment by ananya-kundu** [comment]
# ## ###
