### ISSUE TITLE
Checkbox not returning checked value

### ISSUE THREAD

**Issue by mikejonas** [react-bootstrap/react-bootstrap#1900]
I have a checkbox and I'm trying to get the status of it. Everytime I toggle it returns true though. Am I doing this correctly?

`<Checkbox onChange={this.setPermChange.bind(this)}>Admin Access</Checkbox>`

`  setPermChange(e) { console.log( e.target.value ); } // returns 'on' every time`

**Comment by jquense** [comment]
the value of checkbooks is what the value attribute is, use the checked property for whether it's checked or nit

**Comment by mlimat** [comment]
I'm loving your project. Amazing stuff. However, I am also having the same issue.
Like you suggested, I am checking the value attribute. However, like @mikejonas mentioned, `targer.value` always return `"on"`
Can you please clarify your answer, @jquense ?

Thank you

**Comment by mlimat** [comment]
I managed.
To clarify to other users, what I understood is that you need to use `defaultChecked` to set the initial value, the query `target.checked` from within `onChange` to retrieve the checked status.
