### ISSUE TITLE
Having minified exception occurred on Carousel in production

### ISSUE THREAD

**Issue by Artemidas** [react-bootstrap/react-bootstrap#1901]
When I setup Carousel on dev environment it works perfect, but on the production it throws this error:
> Error: Minified exception occurred; use the non-minified dev environment for the full error message and additional helpful warnings.

As the result the slides are not shown, there are indicators only.

**Comment by taion** [comment]
Please provide a repro.

**Comment by Artemidas** [comment]
Its actually my companies project so I cannot reveal the code, although I could show an error message that I'm receiving:
> Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components). Check the render method of `t`.

**Comment by jquense** [comment]
Soundsl ike production may be running an older version of RB, or something. I don't think this is a bug

**Comment by taion** [comment]
We can't proceed without a repro anyway.
