### ISSUE TITLE
Formcontrol input with readonly prop

### ISSUE THREAD

**Issue by jwamsterdam** [react-bootstrap/react-bootstrap#1902]
I would like to make the Input field that is generated within the FormControls to have a prop of readonly="readonly". This way, this field looks the same as my other FormControls, but does not give a keyboard input on IOS.

In my case, the input will be provided by a calendar picker which will be triggered by an popover.

Does anyone know how to give FormControl the parameter readonly="readonly", so that the generated Input field in the browser will have the prop readonly="readonly"?

**Comment by jquense** [comment]
have you tried setting it? props are passed through to the input. (and it's camelcased: readOnly,  in react)

**Comment by jwamsterdam** [comment]
My mistake, works indeed!
