### ISSUE TITLE
Improve Rendering Performance with shouldComponentUpdate

### ISSUE THREAD

**Issue by peterpme** [react-bootstrap/react-bootstrap#1903]
Hey everyone,

React-bootstrap has been super helpful! Thanks for putting this together :)

Whether I end up fixing this myself or just creating a ticket (debugging now) it looks like there's alot of unnecessary renders that take place in each of the elements.

Thanks!

![image](https://cloud.githubusercontent.com/assets/1211905/15301399/25b650d0-1b73-11e6-98c3-3116e119b540.png)

**Comment by taion** [comment]
See https://github.com/react-bootstrap/react-bootstrap/issues/633, https://github.com/react-bootstrap/react-bootstrap/issues/1378 – this just doesn't seem like a great fit for this library.

**Comment by kenchengch** [comment]
hi @peterpme may i know how to avoid rerender by shouldComponentUpdate ?

**Comment by peterpme** [comment]
Hey @kenchengch, the easiest approach would be:

1) create a separate file that you into all of your components into
2) export each of those components out with a higher order component that handles shouldComponentUpdate.

For example. (Please don't copy and paste the code below because it will not work, this is just an example)

```es6

import button from 'react-bootstrap'

// ...

const optimizedComponent = (Component) => class extends React.Component {
    shouldComponentUpdate (nextProps) {
        return shallowCompare(this, nextProps)
    }
    render() {
        <Component {...props} />
    }
}
// ...

export const Button =  optimizedComponent(button);

```

**Comment by kenchengch** [comment]
Finally I find If i bound state to my input control(the form have many input text controls) has performance issue. I solved by changing onChange event to onBlur for setState and then set my state value to html5 defaultvalue attribute to <FormControl defaultValue=.../>. Thank you.
