### ISSUE TITLE
Navbar doesn't turn to mobile view (i.e. collapsed to "burger")

### ISSUE THREAD

**Issue by beesarmy** [react-bootstrap/react-bootstrap#1904]
Hi, I'm quite new to react-bootstrap (and frontend as well).  I'm trying to create a Navbar which would collapse (to become a "burger" button) when viewing in a mobile device.  I copied the sample code and render it [at](http://upickpack.appspot.com/)

On laptop browser, the menu would collapse ok when I narrow the browser width. However, if I use iPhone to view the page, the menu doesn't collapse. (Using the Chrome developer tool to turn on mobile view has the same problem)

My code is [here](https://jsfiddle.net/webpotent/ugdkey06/)  (that does't conform to jsfiddle convention and surely won't work on it. It's just to show the code). 

Have I missed anything?
Thanks

**Comment by taion** [comment]
You need to set viewport-related `meta`

**Comment by beesarmy** [comment]
Thanks a lot!
