### ISSUE TITLE
Missing documentation on how to use the <Radio> component

### ISSUE THREAD

**Issue by larsnystrom** [react-bootstrap/react-bootstrap#1905]
There is no example or documentation (that I've found) on how to group radio buttons together with one name to make them mutually exclusive. The current examples makes it possible to check all radio buttons, which is usually not what you'd want.

Current [example from documentation](http://react-bootstrap.github.io/components.html#forms):

    <form>
      <FormGroup>
        <Radio inline>
          1
        </Radio>
        {' '}
        <Radio inline>
          2
        </Radio>
        {' '}
        <Radio inline>
          3
        </Radio>
      </FormGroup>
    </form>

I would've asked this on StackOverflow or something, but I thought I'd file an issue for the missing documentation as well. I hope that's ok.

**Comment by jquense** [comment]
they are just normal radio buttons, you group them the same way you'd group native inputs, give them the same `name`

**Comment by larsnystrom** [comment]
That seems reasonable, but perhaps the documentation could be updated to reflect that?

**Comment by jquense** [comment]
well its not a function of the component, we don't generally document normal browser behavior, but if you'd like to send a PR we'll merge it.
