### ISSUE TITLE
Popover doesn't close properly when using rootClose on iOS device

### ISSUE THREAD

**Issue by cmsheffield** [react-bootstrap/react-bootstrap#1906]
I'm finding that the popover component does not dismiss correctly when running on an iOS device (iPad, in this case) and using rootClose. I've tried the 3 major browser apps (Safari, Firefox, Chrome) and they all exhibit the same behavior.

With a popover displayed (that part works great), tapping the screen somewhere below the popover will dismiss it, but tapping the screen somewhere above it does not.  Here's my code:

    <div>
            <OverlayTrigger trigger="click" rootClose placement="bottom" overlay=
              {
                <Popover id='needHelpPopover' title="Need help logging in?"><p>If you do not know your account ID, user ID, and password, please ask your teacher for help.</p>
                  <p>Read Naturally cannot give out student login information.</p></Popover>
              }>
              <a href='#' className='need-help'>Need Help?</a>
            </OverlayTrigger>
    </div>

Styles include the following, if this is helpful:

    .need-help {
        font-size: medium;
        margin-top: 40px;
        z-index: 1000;
      }

The z-index was added simply to make sure the anchor was the front-most element, in the hopes that this might fix the problem. It didn't, unfortunately.

Does anyone have any suggestions? I'm wondering if this could be a bug with the rootClose attribute itself. I'm finding a similar issue with the Popover example here https://react-bootstrap.github.io/components.html#popovers when running it on an iPad.

Thanks.

**Comment by BowlingX** [comment]
The outer container (e.g. the body) needs to have `cursor: pointer` to make this work, otherwise no click event(s) will be dispatched.

**Comment by jquense** [comment]
I wonder how upstream bootstrap handles this?

**Comment by taion** [comment]
This isn't a feature in upstream TWBS.

**Comment by jquense** [comment]
Really? TIL. I think the drop down does some sort of backdrop though for this case on mobile,i may be thinking about v4 tho...or something else entirely

**Comment by taion** [comment]
@jquense I take that back. You're right – the dropdown in Bootstrap does add a backdrop to handle iOS's touch delegation wonkiness: https://github.com/twbs/bootstrap/blob/v3.3.7/js/dropdown.js#L69-L75. We used to do something like this in `<Modal>`.

@cmsheffield The code in question is actually all in react-overlays. We'd be happy to look at a PR there that adds the backdrop node functionality to `<RootCloseWrapper>`.

**Comment by singhba** [comment]
@taion This is still an issue with all recat-bootstrap-overlays. Can we please track this issue unless the fix is available?

**Comment by aaronincincy** [comment]
Why is this closed?  Is there a fix?

**Comment by ReactGirl** [comment]
This still a problem. The issue opened to track this is:
https://github.com/react-bootstrap/react-overlays/issues/158
