### ISSUE TITLE
DropdownButton issue

### ISSUE THREAD

**Issue by Siyfion** [react-bootstrap/react-bootstrap#1908]
I'm using a `DropdownButton` in a render function that is only called under certain circumstances, but when it is called I get the following error:

```
invariant.js:38 Uncaught Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).
invariant @ invariant.js:38
ReactOwner.addComponentAsRefTo @ ReactOwner.js:67
attachRef @ ReactRef.js:23
ReactRef.attachRefs @ ReactRef.js:42
attachRefs @ ReactReconciler.js:22
_assign.notifyAll @ CallbackQueue.js:66
ON_DOM_READY_QUEUEING.close @ ReactReconcileTransaction.js:79
Mixin.closeAll @ Transaction.js:202
Mixin.perform @ Transaction.js:149
Mixin.perform @ Transaction.js:136
_assign.perform @ ReactUpdates.js:89
flushBatchedUpdates @ ReactUpdates.js:165
ReactUpdates_flushBatchedUpdates @ ReactPerf.js:66
Mixin.closeAll @ Transaction.js:202
Mixin.perform @ Transaction.js:149
ReactDefaultBatchingStrategy.batchedUpdates @ ReactDefaultBatchingStrategy.js:63
batchedUpdates @ ReactUpdates.js:97
ReactEventListener.dispatchEvent @ ReactEventListener.js:150
```

The Dropdown works when I click, but upon clicking to toggle it off, nothing happens.

It seems to have an issue with this too:
```
Dropdown.prototype.focusNextOnOpen = function focusNextOnOpen() {
    var menu = this.refs.menu;

    if (!menu.focusNext) {
      return;
    }

    if (this.lastOpenEventType === 'keydown' || this.props.role === 'menuitem') {
      menu.focusNext();
    }
  };
```

as `menu` is `undefined`.

**Comment by jquense** [comment]
Hi, Errors like this are usually caused by having more than one copy of React installed

**Comment by Siyfion** [comment]
You are indeed correct, it seems that `react-bootstrap` installed `react` as a dependency as well as me having it already installed. A quick delete of `/node_modules` and a `npm install` seemed to solve it all.

**Comment by SachaG** [comment]
I've actually been running into the same issue, but only with some components (`DropdownButton`) being one of them. I'm looking into the duplicate React issue but haven't been able to track it down yet. But is there anything different about `DropdownButton` that would make it trigger this issue while other components don't?

**Comment by lucianolorenti** [comment]
I'm having the same problem but I could not find a duplicate of react and react-dom. I'm not using any ref related thing. If I replace the DropdownButton with a ButtonGroup, for example, everything works.  What I am missing?

```
$ npm ls react-dom
viz@1.0.0 {path}
└── react-dom@15.4.1 
```

```
$ npm ls react
viz@1.0.0 {path}
└── react@15.4.1 
 ```
