### ISSUE TITLE
Controlled FormControl jumps to end on editing 

### ISSUE THREAD

**Issue by igin** [react-bootstrap/react-bootstrap#1909]
When editing a "controlled" FormControl the cursor jumps to end when editing inside the text. Look at the  validation example in https://react-bootstrap.github.io/components.html#forms . When you type a text everything looks fine. But as soon as you want to edit the typed text in the middle then the cursor will jump to the end of the text.

**Comment by jquense** [comment]
it s a bug in React 15.0.0, make sure to upgrade to the latest patch version

**Comment by igin** [comment]
Thanks for the quick response! Will try that.

**Comment by igin** [comment]
Unfortunately the upgrade to React 15.0.2 didn't fix the issue. I will try to recreate a minimal test that reproduces the behaviour.

**Comment by igin** [comment]
Ok,it looks like the problem was in the combination with a modal dialog. I found a workaround though.

**Comment by ChrisMalherbe** [comment]
@igin I have the same issue with the cursor jumping to the end in a modal. Can you please share the workaround you used?
