### ISSUE TITLE
`getInputDOMNode` no longer works

### ISSUE THREAD

**Issue by swashcap** [react-bootstrap/react-bootstrap#1911]
I’m upgrading to react-bootstrap 0.29.4 and I’m noticing that `getInputDOMNode` doesn’t work on the new `FormControl` components. Example:

```js
import React from 'react';
import { ControlLabel, FormControl, FormGroup } from 'react-bootstrap';

class MyForm extends React.Component {
  handleChange() {
    console.log('My field:' + this.refs.myField.getInputDOMNode().value);
  }
  render() {
    return (
      <form>
        <FormGroup controlId='my-field'>
          <ControlLabel>My field:</ControlLabel>
          <FormControl
            onChange={this.handleChange.bind(this)}
            ref='myField' />
        </FormGroup>
      </form>
    )
  }
}
```

**Comment by swashcap** [comment]
Ah! There’s a potential workaround of using `document.getElementId`, where you pass it the `controlId`. This seems bad because:

1. Developers might accidentally duplicate an `id`
2. Have to figure out `document` shim in tests

**Comment by taion** [comment]
Just call `ReactDOM.findDOMNode` on the element.

**Comment by swashcap** [comment]
@taion Nice! Thanks for the help. Might be worth adding “Forms” component docs.

**Comment by taion** [comment]
Probably makes sense, yes.
