### ISSUE TITLE
Unable to set focus on FormControl, FormGroup, etc

### ISSUE THREAD

**Issue by Edward-Lombe** [react-bootstrap/react-bootstrap#1913]
There seems to be no API implemented to expose either the focused state, or provide a mechanism for mutating the focused state. Does this exist, if not are there plans to implement it? Or should I start on a PR to implement it?

**Comment by taion** [comment]
`<FormControl>` forwards all its props to the `<input>` it directly renders, so it's the same as if you were rendering an `<input>`.

**Comment by jquense** [comment]
which is to say the API is: https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/focus

**Comment by thardy-pd** [comment]
How can this be done?  Trying control.focus(); doesn't work on a FormControl.

**Comment by jquense** [comment]
you need to call focus on the DOM node.

**Comment by MikeInSwitzerland** [comment]
> you need to call focus on the DOM node.

Nope, doesn't work for me.
I have a component with a textbox and I am adding a Clear button next to it.  When the user clicks on Clear I want to clear the text, but then set the focus back to the textbox, ready for the user to continue typing.

It doesn't work.

```
const inputRef = useRef(null);

function clearValue() {
    setSearchString('');

    //  This line doesn't do anything.  The "focus()" command _does_ exist, there's no error when I run the code,
    //  but it doesn't (ever) set the focus back to the textbox,
    inputRef.current.focus();
}

<div className="clearButton" onClick={clearValue}>
    <img src="./../assets/images/clear.png" />
</div>
<Form.Control type="text" name="textboxThing" ref={inputRef} value={searchString}  />

```
Have I missed something....?
