### ISSUE TITLE
Swapping a Carousel to iterate a shorter collection

### ISSUE THREAD

**Issue by jamesmcnamara** [react-bootstrap/react-bootstrap#1914]
I recently ran into an issue with managed carousels.

If I swap out the collection that a carousel is iterating through for a shorter collection, such that the current index in the carousel is larger than the length of the new collection, I receive a blank display until I change the active index again.

This problem is mostly mitigated with a change to the `componentWillReceiveProps`:

``` javascript
this.setState({
    previousActiveIndex: activeIndex,
    ....
```

to:

``` javascript
this.setState({
    previousActiveIndex: Math.min(activeIndex, nextProps.children.length - 1)
    ....
```

However, this caused a few edge condition issues in extreme cases (i.e. overlaying the last component of the new carousel over the appropriate component). 

The only way I could get around those was to skip the animation in that case:

``` javascript
if (nextProps.activeIndex != null && nextProps.activeIndex !== activeIndex) {
    if (activeIndex >= nextProps.children.length) {
        this.setState({
            activeIndex: nextProps.activeIndex,
            previousActiveIndex: null,
            direction: null
        });
    } else {
        this.setState({
            previousActiveIndex: activeIndex,
            direction: nextProps.direction != null ?
                nextProps.direction : this.getDirection(activeIndex, nextProps.activeIndex)
        });
    }
}
```

Am I doing anything obviously wrong?

**Comment by taion** [comment]
If you're going to do something like this, you're probably better off using a controlled carousel and managing the active index yourself.

**Comment by jamesmcnamara** [comment]
Yes, that is the situation I mean.

**Comment by taion** [comment]
Ah, I see. Yeah, you may need to manage waiting to remove that last thing so the animation can play properly. I don't think we want to manage that state at this level in the context of managed carousels, because the user can control that carousel.

**Comment by DiegoGallegos4** [comment]
@jamesmcnamara did you find a way to solve this thoroughly?

**Comment by DiegoGallegos4** [comment]
@taion still I have a controlled carousel and it decrements the index right when it swaps the collection by a smaller one. But on the DOM is see the classes of the Carousel.Item does not change. The previous item has the class='item prev right' for example and not the 'item active'

**Comment by jamesmcnamara** [comment]
I ended up subclassing the carousel and overriding the `componentWillReceiveProps` method to do what I wanted. 

What I had ended up looking like this:
```javascript
import { Carousel as BootstrapCarousel } from 'react-bootstrap'


export class Carousel extends BootstrapCarousel {
    direction(prevIndex, index) {
        if (prevIndex === index) {
            return null;
        }

        if (prevIndex === this.props.children.length - 1 && index === 0) {
            return 'next'
        }

        return prevIndex > index ?  'prev' : 'next';
    }

    componentWillReceiveProps(nextProps) {
        const activeIndex = this.getActiveIndex();
        if (nextProps.activeIndex != null && nextProps.activeIndex !== activeIndex) {
            if (activeIndex >= nextProps.children.length) {
                this.setState({
                    activeIndex: nextProps.activeIndex,
                    previousActiveIndex: null,
                    direction: null
                });
            } else {
                this.setState({
                    previousActiveIndex: activeIndex,
                    direction: nextProps.direction != null ?
                        nextProps.direction : this.direction(activeIndex, nextProps.activeIndex)
                });
            }
        }
    }

}
```

**Comment by DiegoGallegos4** [comment]
@jamesmcnamara thank for your reply. Just a doubt, is the previousActiveIndex the activeIndex props of the Carousel component?

**Comment by jamesmcnamara** [comment]
It's been a long time since I've looked at this but I believe they are internal, stateful implementation details of the carousel. 

At the time, I could not find a way to solve this problem using the public API, so I inspected the source code and found this (fragile) way of doing it.

**Comment by taion** [comment]
I think we just need to add a check in `componentWillReceiveProps` for something like

```js
nextProps.activeIndex == null && this.state.activeIndex >= nextProps.children.length
```

and handle this case accordingly. Should be pretty straightforward if any of you want to PR it.

**Comment by michbil** [comment]
Thanks for the hint, @taion. I ended up with something like that
```
componentWillReceiveProps(nextProps) {
        const activeIndex = this.getActiveIndex();
        if (nextProps.activeIndex == null && this.state.activeIndex >= nextProps.children.length) {
            this.setState({
                activeIndex: 0,
                previousActiveIndex: null,
                direction: null
            });
        }
    }
```
Resets carousel to 0 when children changed
