### ISSUE TITLE
Iframe loses focus after esc from fullscreen from within Modal

### ISSUE THREAD

**Issue by gkcodeman** [react-bootstrap/react-bootstrap#1915]
React Bootstrap modal is housing an iframe with a lab environment inside. I make the lab fullscreen with no problems but when I esc from the iframes full screen lab environment the modal loses the iframes content and nothing is rendered, until I close the modal and reopen it. Any ideas on how to fix this issue as I've tested the iframe out in a plain div tag and it s works perfectly.

**Comment by gkcodeman** [comment]
`var ModalPop = React.createClass({

  getInitialState() {
    return { showModal: false };
  },

  close() {
    this.setState({ showModal: false });
  },

  open() {
    this.setState({ showModal: true });
  },
  
 
  


  render() {
    let popover = <Popover title="popover">very popover. such engagement</Popover>;
    let tooltip = <Tooltip>wow.</Tooltip>;

    return (
      <div style={{display:"inline-block"}} role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        
        
        <Button type="button" className="btnOverRides" bsStyle="primary" bsSize="large" role="button" onClick={this.open}>
          Take The Challenge
        </Button>
    
        
        <Modal show={this.state.showModal} onHide={this.close}>
      
          <Modal.Header style={{background:"#333", border:"none"}} closeButton>
           {/* <ChallengeInstructions data={this.props.data} />  */}
            
            <Modal.Title></Modal.Title>
            
          </Modal.Header>
          <Modal.Body style={{fontFamily:"Century Gothic, sans-serif", background:"#333", border:"none"}}>
            <div className="row">
                {/*<div className="col-md-4">*/}
                   {/* <Challenge data={this.props.data} /> */} {/*this code goes with the code that is commented out above if you ever want to activate it again*/}
                    
        
        {/*
                    <h4>Popover in a modal</h4>
                    <p>there is a <OverlayTrigger overlay={popover}><a href="#">popover</a></OverlayTrigger> here</p>
        
                    <h4>Tooltips in a modal</h4>
                    <p>there is a <OverlayTrigger overlay={tooltip}><a href="#">tooltip</a></OverlayTrigger> here</p>
                    
                    */}
               {/* </div> */}
                <div className="col-md-12 remove-pad-left">
                     <LabPlayer />
                </div>

            </div>{/*end of nested row*/}
          </Modal.Body>
          <Modal.Footer style={{background:"#333"}}>
            <Button className="closeButtonStyle" style={{background:"#222",color:"#fff", border:"none"}} type="button" onClick={this.close} role="button">close</Button>
          </Modal.Footer>
      
        </Modal>
        
       
        
      </div>/*modal container*/
    );
  },
  
  
  
});
/*end of bootstrap modal component*/`

`var React = require("react");


var LabPlayer = React.createClass({
  
     render: function () {
        
        

         return (
           <div className="responsive-iframe-lab">
                <iframe className="myLab" src="https://labs2.remotelabs.com/?resId=4277-Stage01-Pod777" frameborder="0" align="middle" width="100%" height="602px" allowtransparency="true" scrolling="no" allowFullScreen="true" webkitallowFullScreen="true" mozallowFullScreen="true"></iframe>
           </div>
        );
    }
  
})

module.exports = LabPlayer;`

**Comment by gkcodeman** [comment]
Sorry about the way the code came in. Just wanted to give you some context into the problem I'm experiencing.

**Comment by taion** [comment]
You need to disable `keyboard` on the `<Modal>` if you don't want the modal to close on `esc`.
