### ISSUE TITLE
is it possible to use animate.css for animating these bootstrap components?

### ISSUE THREAD

**Issue by tirams** [react-bootstrap/react-bootstrap#1916]
Question:how does one take advantage of [animate.css](https://daneden.github.io/animate.css/) for enter and leave of these components. Can some examples be provided? I'm able to specify class animate slideInRight to a component which it used on display but I'm not sure how to specify exit

**Comment by taion** [comment]
It's exactly the same as for any other React component – these are just React components and there's nothing special about them. Pull out the DOM node or use the React animation utilities or whatever. There's nothing React-Bootstrap specific.
