### ISSUE TITLE
Migrated to tab container, but it cannot parse my tabs

### ISSUE THREAD

**Issue by Someguy123** [react-bootstrap/react-bootstrap#1918]
I have a tabbed application, which previously used RB v0.27. I updated it to v0.29, and it was working, however I noticed the various warnings about updating to a tab container.

So I updated to a tab container, only to get these errors:

    bundle.js:9702 Uncaught Invariant Violation: onlyChild must be passed a children with exactly one child.

(triggered by TabsContainer._render)

followed by:

    bundle.js:15593 Uncaught TypeError: Cannot read property '_currentElement' of null

which seems to be caused by the tab container failing to render the children.

My structure looks like this:

            <div>
                <Tab.Container id="wallet-tabs" defaultActiveKey={2}>
                    <div className="logged_header main_header single">
                        <h1>
                            <span className="pull-right ltc-balance hidden-xs">{this.state.balance}</span>
                        </h1>
                        <Nav bsStyle="pills">
                            <NavItem eventKey={1}>Transactions</NavItem>
                            <NavItem eventKey={2}>Receive</NavItem>
                            <NavItem eventKey={3}>Send</NavItem>
                            <NavItem eventKey={4}>Settings</NavItem>
                        </Nav>
                    </div>
                    <div className="container">
                        <Tab.Content>
                            <Tab.Pane eventKey={1}>
                                <TransactionsTab addresses={this.state.addresses} transactions={this.state.transactions} />
                            </Tab.Pane>
                            <Tab.Pane eventKey={2}>
                                <ReceiveTab setLabel={this.setLabel.bind(this)}
                                            addresses={this.state.addresses} balances={this.state.balances}
                                            generate={this.generate.bind(this, '')}/>
                            </Tab.Pane>
                            <Tab.Pane eventKey={3}>
                                <SendTab balances={this.state.balances} />
                            </Tab.Pane>
                            <Tab.Pane eventKey={4}>
                                <SettingsTab email={this.state.email} setEmail={this.setEmail.bind(this)}
                                             onEmailChange={this.onEmailChange.bind(this)}
                                             importWif={this.importWif} addresses={this.state.addresses}/>
                            </Tab.Pane>
                        </Tab.Content>
                    </div>
                </Tab.Container>
            </div>

**Comment by jquense** [comment]
`TabContainer` only takes a single child because it doesn't render it's own DOM node, wrap everything inside of `Tab.Container` in a single div and it should work fine.

**Comment by Someguy123** [comment]
@jquense Thank you. This wasn't on the documentation, so I never thought it would have an issue with multiple children.

https://react-bootstrap.github.io/components.html#tabs

CTRL-F "Custom tab"

Documentation definitely needs updated with a big bold **Tab.Container can only take ONE child, so wrap everything in a DIV if you need more than one element**

**Comment by jquense** [comment]
The example shows the single child but it  could be clearer. Would take a PR adding that note if your up for it

**Comment by danmolitor** [comment]
Hey there, I've been running into a slightly different issue, along the same line. I'm getting:

> Invariant Violation: A valid React element (or null) must be returned. You may have returned undefined, an array or some other invalid object. 

The code in question is:

`    <Tab.Container id="left-tabs-example" defaultActiveKey={activeTab} onSelect={this.handleTabSelect}>
      <Row className="clearfix tabContainer">
        <Col sm={3}>
          <Nav bsStyle="pills" stacked>
            <NavItem className="questionTabs" eventKey="selections" >
              Selection Questions
            </NavItem>
            <NavItem className="questionTabs" eventKey="comments">
              Comment Questions
            </NavItem>
            <NavItem className="questionTabs" eventKey="reflections">
              Reflection Questions
            </NavItem>
            <NavItem className="questionTabs last-question-tab" eventKey="goals">
              Goal Questions
            </NavItem>
          </Nav>
        </Col>
        <Col sm={9}>
          <Tab.Content animation>
            <Tab.Pane eventKey="selections">

            </Tab.Pane>
            <Tab.Pane eventKey="comments">

            </Tab.Pane>
            <Tab.Pane eventKey="reflections">

            </Tab.Pane>
            <Tab.Pane eventKey="goals">

            </Tab.Pane>
          </Tab.Content>
        </Col>
      </Row>
    </Tab.Container>`

There aren't any problems when I remove each of the `Tab.Pane` tags. I've tried wrapping internal blocks in divs, as well as externally wrapping the entire Tab.Container in a div, and nothing seems to do the trick.

**Comment by danmolitor** [comment]
Hey there, just tried posting but the formatting was buggy, so i'll give it another shot. 

I have been getting a different invariant error, and it's along these same lines. 

The error is: Invariant Violation: Component.render(): A valid React element (or null) must be returned. You may have returned undefined, an array or some other invalid object.

So the code in question is: 

`<Tab.Container id="left-tabs-example" defaultActiveKey={activeTab} onSelect={this.handleTabSelect}>
      <Row className="clearfix tabContainer">
        <Col sm={3}>
          <Nav bsStyle="pills" stacked>
            <NavItem className="questionTabs" eventKey="selections">
            </NavItem>
            <NavItem className="questionTabs" eventKey="comments">
            </NavItem>
            <NavItem className="questionTabs" eventKey="reflections">
            </NavItem>
            <NavItem className="questionTabs last-question-tab" eventKey="goals">
            </NavItem>
          </Nav>
        </Col>
        <Col sm={9}>
          <Tab.Content animation>
            <Tab.Pane eventKey="selections">

            </Tab.Pane>
            <Tab.Pane eventKey="comments">

            </Tab.Pane>
            <Tab.Pane eventKey="reflections">

            </Tab.Pane>
            <Tab.Pane eventKey="goals">

            </Tab.Pane>
          </Tab.Content>
        </Col>
      </Row>
    </Tab.Container>`

(It's not formatting properly in here, but I essentially used the example code for the custom tabs.)

Now I've tracked it down and it works perfectly when I removed all of the `Tab.Pane` tags. I'm not sure if this is a bug or I'm just doing something wrong, but I've tried wrapping any and everything in divs, internally and externally. Any input would be greatly appreciated, thanks!
