### ISSUE TITLE
Support needed for focusing inputs in modals?

### ISSUE THREAD

**Issue by jtlapp** [react-bootstrap/react-bootstrap#192]
I have been unable to figure out how to automatically have an input receive focus in a popup modal dialog. The react ToDoMVC implementation (http://ssorallen.com/react-todos/docs/) suggests that a react solution would allow the following to work:

```
componentDidMount: function() {
    this.refs.myInput.getDOMNode().focus();
}
```

This does not work. ToDoMVC places this in `componentDidUpdate`, but that doesn't work either. Placing the HTML5 `autofocus` attribute on the input also does not work. Thinking about it a bit suggests to me that `ModalTrigger` might need to provide a hook into the trigger callback.

I found discussion (https://github.com/facebook/react/issues/1791) suggesting that there are issues associated with establishing focus in react proper. However, it does seem doable in react, but I've not found a way to do it in react-bootstrap.

Is this a failing of mine, or does react-bootstrap need to provide support for focus in modals?

**Comment by igaltivoni** [comment]
I realize this issue is closed, but my comment might be relevant. Maybe there's sense in opening a new issue? The autoFocus attribute is great but I see that I need the programmatic way to work nevertheless. 

In case someone wants to help, I've created a stackoverflow question here: 
http://stackoverflow.com/questions/27738486/set-focus-on-a-react-bootstrap-input-field-using-refs-x-getdomnode-focus

**Comment by ShivamMishraJi** [comment]
> React provides a cross browser polyfill for the HTML5 `autofocus` attribute, but as with all React attributes it is camel cased so `autoFocus`, see http://jsfiddle.net/pieterv/tawdhs77/

Thanks...!! It Worked for me..

**Comment by bharatgupta99** [comment]
autoFocus is not working now. Is there any other solution?

**Comment by neongreen** [comment]
Can confirm that autoFocus is not working for me either. Perhaps this issue should be reopened.

**Comment by SasSam** [comment]
Same here. The `autoFocus` doesn't work. :(

**Comment by meetajhu** [comment]
@SasSam it works only if a component gets mounted in DOM eg: Modal has a input with autofocus. If the component  already exists in DOM then you have to use 'ref' and write your own event handler to focus the inout 'ref'.
