### ISSUE TITLE
Tooltip inside scrollable content

### ISSUE THREAD

**Issue by kadishay** [react-bootstrap/react-bootstrap#1922]
When triggering a Tooltip from an element (OverlayTrigger) which resized inside a scrollable element (scroll x for example) - tooltip position is incorrect.

**Comment by jquense** [comment]
can you please provide a repo? There are scroll examples on the Docs that work fine as far as we can tell. Thanks

**Comment by kadishay** [comment]
I can only reproduce partially, see that when you scroll right in the green container and then: hover + scroll back - the tooltip moves with the page and is not staying as with the parent element.
http://codepen.io/kadishay/pen/ONKNqZ

**Comment by jquense** [comment]
@kadishay set the `container` prop to the scrollable element, instead of the default which is the document body.
