### ISSUE TITLE
Set 'neutral' validationState

### ISSUE THREAD

**Issue by StefanoGitHub** [react-bootstrap/react-bootstrap#1926]
Hi,
how can I set a validationState of a `FormGroup` only after the user entered some values?
This is my component:
```
<FormGroup className="dateInput" validationState={this.state.validationState}>
    [...]
</FormGroup>
```
where `this.state.validationState` is an empty string as default and can be `error` in case the validation doesn't pass.
With the above I get this warning:
```
Warning: Failed propType: Invalid prop `validationState` of value `` supplied to `FormGroup`, expected one of ["success","warning","error"]. Check the render method of `DateInput`.
```
I do not want to have a green state if no data is entered, actually I don't want the green borders at all, just the red borders in case of invalid data.
How should I handle this?
Thanks!

**Comment by jquense** [comment]
set it to `undefined` or `null`

**Comment by alexbooker** [comment]
@jquense, I think this needs better documentation.

---

I don't know if anything can be done about this, but when we write:

```js
<FormGroup validationState='neutral'>
</FormGroup>
```

... We get an error like:

```
warning.js:44 Warning: Failed propType: 
Invalid prop `validationState` of value `neutral` supplied to `FormGroup`, expected one 
of ["success","warning","error"]. Check the render method of `ChatMessageInputForm`.
```

It's a bit confusing because like you say, `null` and `undefined` _are_ valid and yet the error reads _"expected one of **["success","warning","error"]**"_.

Are you open to a pull request that mentions `null` and `undefined` in the documentation?

Also, what do you think about the error? Do you think there's room for improvement?

**Comment by taion** [comment]
That's just how `React.PropTypes.oneOf` emits validation failures. Besides, this "neutral" validation state is demonstrated on the examples page anyway.

**Comment by alexbooker** [comment]
In the demo, the `FormGroup` is neutral but I don't think it's necessarily clear _why_ or _how_ to put it in that state :confused:

**Comment by L3V147H4N** [comment]
@alexbooker I guess is neutral because the conditions are not checking for length of 0 and so is returning undefined, still, there seems to be no way to detect if the input is 'pristine' or 'untouched'

**Comment by L3V147H4N** [comment]
A possible workaround would be to save the 'untouched' state of every input and set it to 'true' onChange and then you can use it in the validation, although there are some Good Practices about Form Validation which state that validation should be done on submit (or when the user is done with the form)
http://mono.company/journal/design-practice/the-10-commandments-of-good-form-design-on-the-web/

**Comment by mvdwaeter** [comment]
Example for showing errors based on this.state.username_errors for an Username field:

    <FormGroup validationState={this.state.username_errors.length > 0 ? "error" : null}>
      <ControlLabel>{this.state.username_errors}</ControlLabel>
      <FormControl type="text" id="inputUsername" placeholder="Username" required autoFocus/>
    </FormGroup>
