### ISSUE TITLE
ButtonToolbar can't center buttons

### ISSUE THREAD

**Issue by noahmonster** [react-bootstrap/react-bootstrap#1928]
I was trying to center two buttons on a form like this:

```
<ButtonToolbar className='text-center'>
  <Button>Cancel</Button>
  <Button>Create</Button>
</ButtonToolbar>
```

However, the `.btn-toolbar` style class applied by `ButtonToolbar` prevents the `.text-center` class from working properly.  The buttons continue to be left justified even though the class appears to be applied.

**Comment by jquense** [comment]
you can't use `text-center` to align buttons, it only works on (as the name suggests) text. There isn't a utility for centering buttons in a toolbar, you'll have to use some custom css.

**Comment by noahmonster** [comment]
You sure can: [JSFiddle as proof](https://jsfiddle.net/0wszab8a/)

**Comment by jquense** [comment]
Didn't realize that, in any case if they don't work together that's a issue for plain old bootstrap,react-bootstrap doesn't control or include the CSS

**Comment by noahmonster** [comment]
I think you're right, the `.btn-toolbar` is a plain bootstrap issue.  But the reason that I'm using ButtonToolbar is because it appears to be the only component that gives Buttons the proper margin.  When I render two Buttons next to each other without ButtonToolbar, they have no margin and are touching.  All of the examples on the React Bootstrap site use ButtonToolbar as well.

Is there some other component I can use for that, or am I expected to separate those with custom css?  

(I realize this may be a separate issue)

**Comment by noahmonster** [comment]
[This comment](https://github.com/react-bootstrap/react-bootstrap/issues/347#issuecomment-76443147) got me pointed in the right direction.  Apparently this is an issue with React removing whitespace from JSX, which is important for the Button margins.

The "fix" is to render a space into the JSX between the buttons with `{' '}`

**Comment by hassankhan** [comment]
How did you manage it in the end? I'm trying to do the same with mostly the same results 😢

**Comment by NathanCH** [comment]
The text-align property does not work with .btn-toolbar because this component floats its children.

`.btn-toolbar .btn{ float: left; }`

Floated elements are computed as block elements so they cannot be aligned with text-align. That said, I think react-bootstrap's ButtonToolbar should allow the pullRight prop seen on other components.

.pull-right applied to .btn-toolbar: https://jsfiddle.net/0wszab8a/1/

**Comment by quachsimon** [comment]
Have there been any solutions to this? I tried @noahmonster 's solution but it did not work for me. I looked through the docs and could not find any updates

**Comment by NathanCH** [comment]
@quachsimon, looks like ButtonToolBar is now a flex element so set justify-content: center; using a class or inline style.

**Comment by quachsimon** [comment]
@NathanCH I had to manually set the ButtonToolBar component with `display: flex` then justify-content: center for it to properly work. Thanks!
