### ISSUE TITLE
Nested Modal should create a shadow over the bottom modal

### ISSUE THREAD

**Issue by zhaoyao91** [react-bootstrap/react-bootstrap#1929]
I have created a nested nodal. it is placed on top of the bottom modal and the background shadow becomes deeper, but the shadow should overlay the bottom modal, right? 

![image](https://cloud.githubusercontent.com/assets/3808838/15568362/0a797db8-235e-11e6-8d8e-7466d19fa528.png)

**Comment by jquense** [comment]
nested Modals aren't supported by bootstrap, There are a few alternatives tho that do add it, such as my own react-bootstrap-modal, or if you want to build your own the modal used by both underneath is from react-overlays and can handle stacked modals
