### ISSUE TITLE
Upgrade babel-runtime to v6

### ISSUE THREAD

**Issue by Strato** [react-bootstrap/react-bootstrap#1930]
Hello,

React Bootstrap has an old dependency on babel-runtime v5.

Problem is, babel-runtime itself has a dependency on core-js v1, which had a nasty problem of files named with a dollar sign ('$') in them, which is disallowed for TFS source control users. core-js v2 fixes that.

Conclusion : I'm using React Bootstrap but I can't push it to my source control.

For the record, I've tried to use npm-shrinkwrap to force babel-runtime v6 or core-js v2, but webpack stalls.

So could you upgrade the version of babel-runtime you use to the latest, or at least one of the v6 branch that uses core-js v2?

**Comment by Zanadar** [comment]
I believe this is being address by this in progress PR: https://github.com/react-bootstrap/react-bootstrap/pull/1802

**Comment by taion** [comment]
Indeed. Track #1802.
