### ISSUE TITLE
Tabs customization

### ISSUE THREAD

**Issue by MariusGarbea** [react-bootstrap/react-bootstrap#1931]
Hello! I want to place the first 3 tabs on the left and the last 3 on the right (like float). Also, I need to change the color of the Tab's text. What are the classes that I should change? Thanks!

This is how my tabs are arranged right now.
![capture](https://cloud.githubusercontent.com/assets/15181021/15653891/8981f364-2698-11e6-9046-c092fee34d9b.PNG)

**Comment by taion** [comment]
See the custom tabs example where you provide your own `<Nav>`.
