### ISSUE TITLE
Dynamic Tabs throwing in TabContent#registerPane()

### ISSUE THREAD

**Issue by phestermcs** [react-bootstrap/react-bootstrap#1932]
Besides strange and incorrect selection of the content area, an exception is thrown:

> _You cannot have multiple TabPanes of with the same `eventKey` in the same TabContent component. Duplicate eventKey: 1_

...when running the following, and clicking the `change` button. 

```javascript
import * as React from 'react'
import * as Bs from 'react-bootstrap'
class Bug extends React.Component {
	state = {
		list: [1,2,3,4,5]
	}

	onClick = () => {
		const list = this.state.list.slice(0)
		list.splice(0,1)
		this.setState({list})
	}
	render() {
		return <div>
			<Bs.Button onClick={this.onClick}>change</Bs.Button>
			<Bs.Tabs id="test">
				{this.state.list && this.state.list.map(item =>
					<Bs.Tab eventKey={item} 
					        title={`title ${item}`}>{item} content</Bs.Tab>
				)}
			</Bs.Tabs>
		</div>
	}
}
```

It seems `TabPane#componentWillReceiveProps` is being called, unregistering the pane with the old `eventKey`, then registering with the new (`nextProps.eventKey`). However, there's still a registered pane with `nextProps.eventKey`. Seems this logic did not anticipate a TabPane being 'removed' from it's TabParent??

**Comment by phestermcs** [comment]
The following seems to work around the issue:

```javascript
	...
	render() {
		return <div>
			<Bs.Button onClick={this.onClick}>change</Bs.Button>
			<Bs.Tabs id="test">
				{this.state.list && this.state.list.map((item, idx) =>
					// eventKey is position in list, rather than property of item
					<Bs.Tab eventKey={idx} 
					        title={`title ${item}`}>{item} content</Bs.Tab>
				)}
			</Bs.Tabs>
		</div>
	}
	...
}
```

The `eventKey` is no longer based on a unique property of a data element, but rather the index position of iterating the list containing the data elements. Is this by design?

**Comment by jquense** [comment]
The issue here (I believe) is that you aren't providing normalReact `key`s to the tabs, as you map over them. Which is causing odd reconciliation issues.

**Comment by phestermcs** [comment]
@jquense The values I was using for keys were just unique strings. What precisely do you mean by 'normalReact' keys? Can you provide an example of an 'abnormalReact' key?
