### ISSUE TITLE
Cannot add multiple `OverlayTrigger`s to a single node

### ISSUE THREAD

**Issue by jochenberger** [react-bootstrap/react-bootstrap#1933]
I want to add a `Tooltip` *and* a `Popover` to a `div`.
```jsx
<OverlayTrigger placement="top" overlay={<Tooltip>Tooltip text</Tooltip>}>
  <OverlayTrigger trigger="click" rootClose overlay={<Popover title="Popover">Popover text</Popover>}>
    <div>Test</div>
  </OverlayTrigger>
</OverlayTrigger>
```
Only the inner `OverlayTrigger` works, the outer one doesn't.

**Comment by jquense** [comment]
thanks for the issue. This is a limitation with the overlay trigger and there isn't much we can do about it unfortunately. more complicated cases like yours are better handled by the slightly lower level Overlay  component which should work fine here.

**Comment by chayut27** [comment]
Sorry, How did you solve the problem?
i have the same problem

**Comment by chayut27** [comment]
> I want to add a `Tooltip` _and_ a `Popover` to a `div`.
> 
> ```js
> <OverlayTrigger placement="top" overlay={<Tooltip>Tooltip text</Tooltip>}>
>   <OverlayTrigger trigger="click" rootClose overlay={<Popover title="Popover">Popover text</Popover>}>
>     <div>Test</div>
>   </OverlayTrigger>
> </OverlayTrigger>
> ```
> 
> Only the inner `OverlayTrigger` works, the outer one doesn't.

Sorry, How did you solve the problem?
i have the same problem
