### ISSUE TITLE
How to populate the Dropdown in a FormControl?

### ISSUE THREAD

**Issue by purezen** [react-bootstrap/react-bootstrap#1935]
I tried populating a Dropdown in a FormControl by initializing an array with <option> elements since I wanted it to work with dynamic data.
However, when I tried rendering it using
```
<FormControl>
  {selectBoxes}
</FormControl/>
```
it doesn't work. I then found out that the elements of selectBoxes get changed to ReactElements from <option>Value 1</option> format.

**Comment by taion** [comment]
The examples cover all the supported form controls – refer to those..
