### ISSUE TITLE
Better name for "unmountOnExit"?

### ISSUE THREAD

**Issue by bolsen** [react-bootstrap/react-bootstrap#1938]
The documentation for "unmountOnExit" for both `<Tabs>` and `<Tab>` say that "Unmount the tab (remove it from the DOM) when it is no longer visible". This seems to imply that initially the tab content DOM will be initially present on render, but will be removed after it is "no longer visible". However, the actual behavior looks to be that it will only render the tab content if the tab is active.

Could there be better naming for this, such as `renderOnlyWhenVisible`? I started using this for tabs and had to make sure I was doing what I really wanted.

**Comment by taion** [comment]
This is for consistency with `Modals`/&c., and for the names of the animation callbacks.
