### ISSUE TITLE
Modal not closing correctly on Safari

### ISSUE THREAD

**Issue by giacomorebonato** [react-bootstrap/react-bootstrap#1939]
When I close the Modal component on Safari, i get the following error in the console
```
TypeError: undefined is not an object (evaluating 'wrapper.parentNode')
```
The content of the modal disappears, but the overaly and the dialog are still in the DOM.

**Comment by jquense** [comment]
can you provide a Repo please? It's working for us in Safari

**Comment by giacomorebonato** [comment]
My fault: I was using the Modal component... and not the Dialog one.
Cheers.

**Comment by giacomorebonato** [comment]
Sorry. I will provide the repo.
I am getting the problem on IOS Safari and on desktop with Safari in responsive mode.

**Comment by giacomorebonato** [comment]
Sorry again... There was a JS exception from another the library causing the problem.
Thanks.
