### ISSUE TITLE
provide option to customize modal-content

### ISSUE THREAD

**Issue by chandu0101** [react-bootstrap/react-bootstrap#1940]
Hi,
      I am trying to achieve full screen modal dialog (http://stackoverflow.com/questions/18432394/how-to-make-twitter-bootstrap-modal-full-screen) . with `dialogClassName` i am able to customize modal-dialog but not able to style `modal-content` div :s

**Comment by jquense** [comment]
Hi, you should be able to use a css selector for that `.my-dialog > .modal-content`

**Comment by chandu0101** [comment]
@jquense  thank you :)
