### ISSUE TITLE
unmountOnExit for Col

### ISSUE THREAD

**Issue by Sinistralis** [react-bootstrap/react-bootstrap#1941]
Is is possible to unmount components encased inside of a Col that has one of the hide/show properties?

If not, are there plans to add this feature? Would it be a welcome addition if it were added?

**Comment by jquense** [comment]
not quite sure what you mean by this...I don't believe that is a feature in bootstrap. Seems like conditionally rendering the children of Col would get you what you want without the added level of indirection.

```js
<Col>{isShowing && <MyComponent />}</Col>
```

**Comment by Sinistralis** [comment]
What I mean is, hiding/showing elements doesn't really make sense in the context of React (my opinion), it makes more sense to unmount/remount based on the hide/show properties. I know however that this library is trying to keep 1:1 parity with bootstrap, so that's why I asked about having the option of unmounting/mounting instead of hiding/showing, something you could opt into if you wanted.

So for example, if I wrap 2 different views, one that is only shown for xs, and one that is shown for sm/md/lg, you could have a lot of duplicated markup there which can screw up unit tests or functional tests since ID's are no longer usable due to duplication. Beyond that, you potentially are rendering up to twice as much DOM which I would imagine has to cost at least a little bit of performance. I would rather just unmount when something was "hidden", it makes way more sense unless I am missing something.

I'm aware I could make my own component or logic that does this, but at that point I might as well create my own grid setup. I would rather just have this functionality as part of this library if at all possible.

**Comment by taion** [comment]
This isn't really part of Bootstrap, and not something we can really implement because we can't assume where your grid breakpoints sit (for measuring viewport size in JS). I'm against adding this.
