### ISSUE TITLE
react-bootstrap uses a very old version of react-router

### ISSUE THREAD

**Issue by mayhs19** [react-bootstrap/react-bootstrap#1942]
React-Bootstrap uses a Legacy version of React-Router (1.0.3) which causes issues while using it. One classic issue experienced is due to this Bug https://github.com/reactjs/react-router/pull/1295 which was fixed in later version of React-Router.

It would be great if React-Bootstrap points to the Latest version of React-Router

**Comment by dozoisch** [comment]
It is only used in the documentations, and is not at all present in the npm package. What kind of issues are you getting? 

We do accept prs if you want to go ahead and update it for the docs.
