### ISSUE TITLE
<Collapse> can't contain two childs

### ISSUE THREAD

**Issue by asiniy** [react-bootstrap/react-bootstrap#1943]
I'm trying to build `<Collapsible>` element just like how [it's described in official documentation](https://react-bootstrap.github.io/components.html#navbars-mobile-friendly).

There is my code:
``` javascript
  render() {
    return  <Navbar>
              <NavbarBrand>
                <Link to="/">Root</Link>
              </NavbarBrand>
              <Collapse>
                <Nav />
                <Nav />
              </Collapse>
            </Navbar>;
  }
```

I'm getting `invariant.js:38 Uncaught Invariant Violation: onlyChild must be passed a children with exactly one child.`. If I remove one `<Nav />` from `<Collapse />`, everything render fine. The most strange thing is that I can see the example on [your documentation page](https://react-bootstrap.github.io/components.html#navbars-mobile-friendly) and everything is working well:

``` javascript
  <Navbar inverse>
    <Navbar.Header>
      <Navbar.Brand>
        <a href="#">React-Bootstrap</a>
      </Navbar.Brand>
      <Navbar.Toggle />
    </Navbar.Header>
    <Navbar.Collapse>
      <Nav>
        <NavItem eventKey={1} href="#">Link</NavItem>
        <NavItem eventKey={2} href="#">Link</NavItem>
        <NavDropdown eventKey={3} title="Dropdown" id="basic-nav-dropdown">
          <MenuItem eventKey={3.1}>Action</MenuItem>
          <MenuItem eventKey={3.2}>Another action</MenuItem>
          <MenuItem eventKey={3.3}>Something else here</MenuItem>
          <MenuItem divider />
          <MenuItem eventKey={3.3}>Separated link</MenuItem>
        </NavDropdown>
      </Nav>
      <Nav pullRight>
        <NavItem eventKey={1} href="#">Link Right</NavItem>
        <NavItem eventKey={2} href="#">Link Right</NavItem>
      </Nav>
    </Navbar.Collapse>
  </Navbar>
```

What I'm doing wrong? react -v `15.1.0`, react-bootstrap -v `0.29.4`...

**Comment by taion** [comment]
That's `<Navbar.Collapse>`, not `<Collapse>`. They're not the same. The latter does in fact only take one child.
