### ISSUE TITLE
htmlFor attribute not assign when Checkbox is in Col with ControlId 

### ISSUE THREAD

**Issue by M3lkior** [react-bootstrap/react-bootstrap#1947]
htmlFor attribute not assign when Checkbox is in Col with ControlId 

Here is my code snippet : 

```
<FormGroup controlId="cbHor">
                    <Col componentClass={ControlLabel} sm={4} ">Checkbox</Col>
                    <Col sm={8}> <Checkbox defaultChecked  /></Col>
                </FormGroup>
```
![image](https://cloud.githubusercontent.com/assets/5501911/15850371/db5ccde4-2c97-11e6-88e1-43b54035337d.png)

When setting htmlFor on Col and id on checkbox, it works and the focus is applied on checkbox when the user clic on label : 

```
    <FormGroup >
                    <Col componentClass={ControlLabel} sm={4} htmlFor="test">Checkbox</Col>
                    <Col sm={8}> <Checkbox defaultChecked  id="test"/></Col>
                </FormGroup>

```

![image](https://cloud.githubusercontent.com/assets/5501911/15850428/13b754b6-2c98-11e6-85b6-a70209452b41.png)

**Comment by taion** [comment]
Should it? TWBS doesn't show styling checkboxes that way: http://getbootstrap.com/css/#checkboxes-and-radios.

**Comment by jquense** [comment]
I think the ControlLabel is redundant and not "correct" in terms of labeling the checkbox.

In general a checkbox nested in a label is probably enough for a SR to correctly understand what the "associated text" is for the input, but it doesn't hurt here to still label them. Possible to use ControlLabel  internally,  worth it?

**Comment by M3lkior** [comment]
It's sometimes necessary, in horizontal form for example or for specific use case, to display  a checkbox alone, with a form label.

**Comment by jquense** [comment]
@M3lkior even in those examples the extra control label isn't what you want, and if it was required its never going to be the abel that gets an `htmlFor` since the checkbox is always wrapped in it's own label which is the thing that most clearly labels it (even if you want no text you should add `sr-only` text anyway.)

**Comment by taion** [comment]
It's not correct to use ControlLabel internally because the checkbox labels don't have `.control-label`.

Sounds like there's nothing to do here, then. Closing for now.
