### ISSUE TITLE
FormControl text inputs moves cursor to the end when value is defined

### ISSUE THREAD

**Issue by MarcoCanalcar** [react-bootstrap/react-bootstrap#1953]
When you create an state controlled FormControl text input, and you write something in the middle of the text area, the cursor moves to the end of the input.

Suppose we have a text input with the following content:
123456789 
If we place the cursor between the 4 and the 5(1234|56789), and press the 'a' key twice, the result is the following:
1234a56789a|

While the expected would be:
1234aa|56789

This only happens when 'value' prop is set and state-controlled.

**Comment by jquense** [comment]
there is no value logic in FormControl so you are either seeing an early React 15 bug (try upgrading) or the issue is coming from how you are setting the value in your app (such as asynchronously)

**Comment by MarcoCanalcar** [comment]
The problem is that I can replicate it consistently, for example, when I wrote the issue, I could replicate the bug on the docs example, but I can't anymore.

**Comment by MarcoCanalcar** [comment]
@jquense Today, I managed to replicate the problem on your documentation page: [video](https://www.youtube.com/watch?v=HpR3bwH00N8)

When I updated the page, the bug dissapeared. I was able to replicate this 3 or 4 times on chromium, but unable to test it on Firefox yet
