### ISSUE TITLE
Can't setup style for Modal component

### ISSUE THREAD

**Issue by deser** [react-bootstrap/react-bootstrap#1954]
I'm trying to set custom style object for Modal component but it's truncated inside.
The example:
```
<Modal
     style={{top: 1000}}
>
```

Anyway my goal is to tie Modal window to target like it `Overlay` does. How can I do that?

**Comment by taion** [comment]
We'd be happy to take a PR to fix this.

**Comment by deser** [comment]
I'll try

**Comment by deser** [comment]
Done: https://github.com/react-bootstrap/react-bootstrap/pull/1957

**Comment by taion** [comment]
Fixed by #1957.
