### ISSUE TITLE
How to show username on dropdown button using React-Bootstrap and EJS?

### ISSUE THREAD

**Issue by tetsushiomi** [react-bootstrap/react-bootstrap#1959]
I want to show username on dropdown button after users log in to my site.

The base code for the dropdown button looks like this.

    <DropdownButton title="whatever" id="bg-nested-dropdown">
      <MenuItem eventKey="1">Account</MenuItem>
      <MenuItem eventKey="2">Log Out</MenuItem>
    </DropdownButton>
I want to change the title to username so that he/she can confirm that they actually logged in by seeing their username on the dropdown button.

I set `user` like this using Express.

    router.get("/", function(req, res) {
      res.render("index", { user: req.user });
    });
I can retrieve username easily like this using EJS.

    <% if (!user) { %>
      some text
    <% } else { %>
      <%= user.username %>
    <% } %>
But, I want to show the username(`user.username`) on the dropdown button.

I can see the user is set properly because I can show the username wherever on the index page except where React-Bootstrap components are used, in this case, DropdownButton.

I tried this.

    { user ? <DropdownButton title={ user.username } id="bg-nested-dropdown"> : <DropdownButton title="whatever" id="bg-nested-dropdown"> }
      <MenuItem eventKey="1">Account</MenuItem>
      <MenuItem eventKey="2">Log Out</MenuItem>
    </DropdownButton>
It returns "user is not defined".
How can I work around this?

**Comment by taion** [comment]
This isn't related to React-Bootstrap. You'll want to look at general-purpose techniques for getting data into React when doing server-side rendering.
