### ISSUE TITLE
React-Bootstrap Tabs component behaving weird

### ISSUE THREAD

**Issue by topgun743** [react-bootstrap/react-bootstrap#1960]
I was using some older version of react-bootstrap in my application. The version of react at that time was 0.14.7
Today when I upgraded to React version 15.1.0, my Tabs weren't loading or with error.

I then replaced all my react-boostrap related .js files with version 0.29.4 (latest of react-bootstrap)
Please note that in each tab, I am showing a react form with controls like textbox, select etc.
Now whenever I switch to another tab, any changes I've made in my form textboxes/select get reset to their initial values as supplied via props. Previously it wasn't happening.

I have changed my Tabs code according to the Tabs example provided on your Components page but still to no avail. I guess something is causing to reload the tab content whenever any tab's nav is selected. It should not reload the tab content.
Please guide me what is going wrong? Thanks

**Comment by taion** [comment]
Please provide a repro.

**Comment by topgun743** [comment]
I was busy so could not answer @taion 's repro request.
Although this issue has been mark closed, yet pasting here the link of [Repro Fiddle](https://jsfiddle.net/58myq5kb/2/)

Check in firebug log that every time when you switch between tabs, following console log gets printed one or more times. My concern is: When a tab content is already rendered, why does it re-renders again whenever you switch between tabs? In my actual application, there is a form in each tab and it gets reset every time you switch between tabs.

Console log
-----------------------------------------------------------
Textbox with value Hello World 1 rendered
Textbox with value Hello World 2 rendered

**Comment by jquense** [comment]
@topgun743 this is normal, React triggers component renders all the time, this is **not** mean that React is making changes to the DOM, only that props/state changed on a component and so React needs to check if it needs to update anything in the DOM as a result. Nothing gets unmounted and remounted, so if your form is reseting then you have a different issue. Notice that the inputs in your example maintain their values as you switch tabs.

**Comment by topgun743** [comment]
Actually I was using [Subschema](https://github.com/subschema/subschema) to generate forms in my real application. 
When I change tabs, the form inputs values get reset to their original values as passed in the data prop. Note that this wasn't happening in my earlier version of React-Bootstrap.

**Comment by Link631** [comment]
same issue here... I am loading dynamic contents and one of my content is a tab. When I hit the condition for rendering the tab, i am getting this error.
