### ISSUE TITLE
OverlayTrigger + Tooltip doesn't work correctly on inline-block elements

### ISSUE THREAD

**Issue by Moezalez** [react-bootstrap/react-bootstrap#1961]
Code:
```JavaScript
<OverlayTrigger
    placement="top"
    overlay={(<Tooltip id="someId">Tooltip!</Tooltip>)}
>
    <div style={{display: 'inline-block'}}>TRIG</div>
</OverlayTrigger>
```

Result:
![elect your flight20160615144757](https://cloud.githubusercontent.com/assets/8615251/16080281/4f2b6cb4-3308-11e6-9bce-abbefca56371.gif)

EDIT:
I found the issue is something else. For some reason, the tooltip is really low for me. So low that it overlaps with the Overlaytrigger. Meaning, when the mouse is below the triangle of the tooltip, the trigger stops.

![elect your flight20160615153548](https://cloud.githubusercontent.com/assets/8615251/16081690/e0d91386-330e-11e6-9db6-dfe6679536a5.gif)

**Comment by jquense** [comment]
Hmm I don't think its the display thats the problem, all the examples on the documentation are inline-block and work fine.

**Comment by Moezalez** [comment]
Interesting. 
For me, emoving the inline-block statement resolves the issue though.

**Comment by Moezalez** [comment]
Interestingly, if I add a width statement (`width: '4rem'`) I get the same problem.

**Comment by Moezalez** [comment]
I found the issue is something else. For some reason, the tooltip is really low for me. So low that it overlaps with the Overlaytrigger. Meaning, when the mouse is below the triangle of the tooltip, the trigger stops.

**Comment by taion** [comment]
Please provide a repo. You can see this works as expected in our examples.

**Comment by taion** [comment]
repro*

**Comment by Moezalez** [comment]
What's a repro?

**Comment by taion** [comment]
Code demonstrating the issue you are talking about.

**Comment by Moezalez** [comment]
@talon 
The snippet above is really all I can show. I suppose something else on my side breaks it. I guess there is nothing you guys can do.

**Comment by talon** [comment]
@moezalez you goofed the i and and L it looks like

**Comment by Moezalez** [comment]
@talon oh, apologise!
