### ISSUE TITLE
Footer and other components below jumbotron

### ISSUE THREAD

**Issue by meilers** [react-bootstrap/react-bootstrap#1964]
Is there a way to add other components under the jumbotron (at the end)? I added a navbar just fine, but I'm looking to add a footer as well, but every other component I add just goes under the nav bar, over the jumbotron (and masking it).

Something like this:

```
<div>
    <Navbar/>
    <Jumbotron/>
    <SomeFooter/>
</div>
```

**Comment by taion** [comment]
There's nothing in React-Bootstrap that does that – it's a styling issue on your end.
