### ISSUE TITLE
Is it somehow possible to change  the text color of a NavItem using inline style?

### ISSUE THREAD

**Issue by RudolfVonKrugstein** [react-bootstrap/react-bootstrap#1966]
I would like to base the text color of a NavItem on some calculation.
I would like to do something like this:

```
render() {
  return <NavItem textColor={calculatedTextColor}>Nav Item text</NavItem>
}
```

What is the best way to do this?

**Comment by jquense** [comment]
hi there, there are no props to do this, you can use a css selector and a className

**Comment by kudzuu** [comment]
Could you provide css selector example?

**Comment by ruanpotgieter95** [comment]
In the css class:
.NavItem { color: white !important; } // I had to include !important otherwise it wont work.
Component:
<NavItem className="NavItem">Nav Item text</NavItem>
