### ISSUE TITLE
Bug on component page on website

### ISSUE THREAD

**Issue by aaronmoore93** [react-bootstrap/react-bootstrap#1967]
I know this is not a massive issue but when you are on the component section of the website and click another nav bar item up the top, a pop up message occurs with the message "selection is undefined"

**Comment by taion** [comment]
Dupe #1875

**Comment by jquense** [comment]
we should do a doc release, I have this fixed in master I think

**Comment by taion** [comment]
I'll release v0.29.5; we had a couple of bug fixes
