### ISSUE TITLE
Accordions collapse when child events are triggered

### ISSUE THREAD

**Issue by eytan** [react-bootstrap/react-bootstrap#197]
For example, if one adds an input field to a panel in an accordion, clicking on any input field causes the panel to collapse:

```
/** @jsx React.DOM */

var panelGroupInstance = (
  <PanelGroup defaultActiveKey={2} accordion>
    <Panel header="Panel 1" key={1}>Panel 1 content</Panel>
    <Panel header="Panel 2" key={2}><input type="text"/></Panel>
  </PanelGroup>
);

React.renderComponent(panelGroupInstance, mountNode);
```

Perhaps onSelect() is getting triggered for <PanelGroup> or <Panel> when the onSelect() events are triggered for their children?

**Comment by piclez** [comment]
Hello, is this working? I added a `<Select>` inside the Panel header and when I change it's triggering the collapse.
