### ISSUE TITLE
Can't render modal on the server side

### ISSUE THREAD

**Issue by sungwoncho** [react-bootstrap/react-bootstrap#1971]
Version: react-bootstrap 0.29.4, react 15.1.0, react-dom 15.1.0.

I am unable to render react-bootstrap's modal on the server.

When I do the following on the server, I get `<!-- react-empty: 1 -->`:

```js
renderToString(
  <Modal>
    <Modal.Header closeButton>
      some text
    </Modal.Header>

    <Modal.Body>
      some text
    </Modal.Body>
  </Modal>
));
```

There is [this issue](https://github.com/react-bootstrap/react-bootstrap/issues/717) but not sure if related.

**Comment by taion** [comment]
Rendering of shown overlays on the server is intentionally not supported.
