### ISSUE TITLE
FormGroup, FormControl, and ControlLabel components all undefined.

### ISSUE THREAD

**Issue by dwightware4** [react-bootstrap/react-bootstrap#1972]
Hi, since you guys removed the old documentation on how to use components like Input, I'm trying to use the new pattern with components FormControl, FormGroup, and ControlLabel. However, none of these components can be imported from the library.

`var FormGroup = require('react-bootstrap').FormGroup` results in `FormGroup` being `undefined`. The same is true for FormControl and ControlLabel components. I'm using version 0.29.5.

What am I missing? I can still import all other components this way with no issue, but I can no longer use any form components because these new components are undefined and the documentation on how to use to old pattern has been deleted.

**Comment by taion** [comment]
WFFM

```
$ node
> require('react-bootstrap').FormControl
{ [Function: FormControl]
  propTypes:
   { componentClass: { [Function: bound checkType] isRequired: [Function: bound checkType] },
     type: { [Function: bound checkType] isRequired: [Function: bound checkType] },
     id: { [Function: bound checkType] isRequired: [Function: bound checkType] },
     bsClass: { [Function: bound checkType] isRequired: [Function: bound checkType] } },
  defaultProps: { componentClass: 'input', bsClass: 'form-control' },
  contextTypes: { '$bs_formGroup': { [Function: bound checkType] isRequired: [Function: bound checkType] } },
  Feedback:
   { [Function: FormControlFeedback]
     defaultProps: { bsRole: 'feedback', bsClass: 'form-control-feedback' },
     contextTypes: { '$bs_formGroup': [Object] },
     propTypes: { bsClass: [Object] } },
  Static:
   { [Function: FormControlStatic]
     propTypes: { componentClass: [Object], bsClass: [Object] },
     defaultProps: { componentClass: 'p', bsClass: 'form-control-static' } } }
```

Double-check that you have the version you think you do.

**Comment by lcb** [comment]
+1
I had the same problem and found the solution in #1974
