### ISSUE TITLE
Pagination: ellipsis for boundaryLinks=false

### ISSUE THREAD

**Issue by noahmonster** [react-bootstrap/react-bootstrap#1977]
Hi,

It looks like when boundaryLinks is false, only one of the two ellipsis is showing.
![screen shot 2016-06-22 at 3 25 33 pm](https://cloud.githubusercontent.com/assets/975308/16284291/bfc1437e-388d-11e6-8c00-e20bb7461899.png)
There should be an ellipsis between the page 5 button and the previous page button.

Contrast that with boundaryLinks=true.  This correctly shows two sets of ellipsis.
![screen shot 2016-06-22 at 3 25 48 pm](https://cloud.githubusercontent.com/assets/975308/16284318/d9f91384-388d-11e6-8f80-a7773a5e6d90.png)

My component:
```
<Pagination items={Math.ceil(this.state.numItems / this.state.itemsPerPage)}
    onSelect={this.handlePageRequested}
    activePage={this.state.activePage}
    maxButtons={5}
    first={firstIcon} last={lastIcon} next={nextIcon} prev={prevIcon} />
```

**Comment by taion** [comment]
Looking at this a bit more closely, I don't think the R-B `<Pagination>` should have any logic with e.g. `maxButtons`, `ellipsis`, or `boundaryLink`. This sort of logic is always sufficiently app-specific, and it's not very helpful to try to handle them in a generic way in this sort of component library, outside of _maybe_ very simple cases like showing each page in a range.

My inclination then is to get rid of at least `maxButtons`, `ellipsis`, and `boundaryLink` entirely.

cc @roadmanfong

**Comment by noahmonster** [comment]
@taion How do you propose that the contents of the Pagination component get set without these props?

**Comment by taion** [comment]
```js
<Pagination>
  <Pagination.Item ... />
  {pageNumbers.map(pageNumber => <Pagination.Item ... />)}
  <Pagination.Item ... />
</Pagination>
```

**Comment by taion** [comment]
Track https://github.com/react-bootstrap/react-bootstrap/issues/1758 – we'll be revamping this API entirely.
