### ISSUE TITLE
Pagination buttons reload the page; SafeAnchor related

### ISSUE THREAD

**Issue by AoDev** [react-bootstrap/react-bootstrap#1979]
Hello,

I've been trying to use the Pagination component but it seems that the click handler is never fired.
Instead the page is reloaded because the buttons are links with empty href.

I am using the component with mostly default options. (Using React 15.1.0, react-bootstrap: 0.29.5)

I've been looking at the code and I could make it work properly by commenting the "href" prop in the `SafeAnchor` component render function. I couldn't make things work otherwise.

```
    return _react2['default'].createElement(Component, _extends({}, props, {
      role: role,
      // href: href,
      style: style,
      tabIndex: tabIndex,
      onClick: this.handleClick
    }));
```

**Comment by taion** [comment]
You need to use `onSelect`.

**Comment by taion** [comment]
See docs at http://react-bootstrap.github.io/components.html#pagination – these clearly don't refresh the page.

**Comment by AoDev** [comment]
I use onSelect.
```
        <Pagination
            onSelect={changeListPage}/>
```

**Comment by AoDev** [comment]
We have Angular UI Router on the page. I think that it might be causing a conflict.

**Comment by AoDev** [comment]
If someone reaches this page. Sometimes another lib intercepts href on links. The default "button" of the pagination here, has an empty href set on a link. Although not completely sure, it seems they were "highjacked" by angular ui router. (not the typical setup)

To solve this problem I had to replace the default button by my own, using the `buttonComponentClass ` option.

**Comment by elmeister** [comment]
Same thing happens, when you import Pagination with class name change, i.e. `import { Pagination as BootstrapPagination } from 'react-bootstrap';`
