### ISSUE TITLE
OverlayTrigger triggered on first touch on IOS8

### ISSUE THREAD

**Issue by flyon** [react-bootstrap/react-bootstrap#1982]
Using a Tooltip with an OverlayTrigger results in the tooltip showing up the first time you touch the button, and the onClick becomming activated the seccond time you click.

Is it possible to always trigger the onClick on the first click?

**Comment by taion** [comment]
We chain the child `onClick` in `<OverlayTrigger>`, and as such the child `onClick` does in fact get called. There's most likely something in your code that's blocking this behavior.
