### ISSUE TITLE
Modal renders to empty element on server

### ISSUE THREAD

**Issue by olalonde** [react-bootstrap/react-bootstrap#1984]
It seems modal renders to an empty element when run server side. It would be useful it it actually rendered the modal's HTML server side.

**Comment by taion** [comment]
Rendering of shown overlays on the server is not supported, as they require use of the portal pattern, which is only possible with a DOM.

**Comment by olalonde** [comment]
Can't modals be rendered in CSS alone?

**Comment by jquense** [comment]
modals require special handling in React using the Portal pattern (as talon said) which requires a DOM because it renders components into a new mount point next to the document body.

**Comment by olalonde** [comment]
Ah I see, right. I'll try to think of a workaround but it's indeed not as simple as I initially thought.
