### ISSUE TITLE
how to make dropdown button to use 100% width 

### ISSUE THREAD

**Issue by chandu0101** [react-bootstrap/react-bootstrap#1985]
I am using dropdown button  inside form , i want button to use all width available ..

**Comment by taion** [comment]
You can apply the same styling properties as for other buttons – check the docs.

**Comment by chandu0101** [comment]
@taion 

for `DropdownButton` component i passed following props 
```js
 className = "btn-block",
 block = true,
```

here is the output rendered 
<img width="839" alt="screen shot 2016-07-04 at 1 59 40 pm" src="https://cloud.githubusercontent.com/assets/2179670/16555016/07a3e6b8-41f0-11e6-909e-05fe22f6f702.png">

button element got width = 100% , but outer div(dropdown) didn't have `btn-block` classes applied :s

**Comment by JoBa1992** [comment]
I also experience this, bsStyle (although wrong) applies the class to both elements, which also isn't suitable

**Comment by ZhenanH** [comment]
Same here, bsStyle="defaut btn-block" works but there is  error in the console:
"Invalid prop `bsStyle` of value `default btn-block` supplied to `t`, expected one of ["success","warning","danger","info","default","primary","link"]."

**Comment by MacKentoch** [comment]
Despite React Bootstrap being super nice I'm afraid I don't find styling super clear in react bootstrap. 

In some cases like setting dropdown to 100% width I followed what previously mentioned and looked at Button doc :
> Create block level buttons—those that span the full width of a parent— by adding the block prop.

But `block` property does not work on `DropdownButton`.

Anyway congratulation for all work done.

**Comment by VictorChen** [comment]
doesn't look like there's a good solution for this?

**Comment by mguijarr** [comment]
There is, actually. Just wrap the `<DropdownButton>` inside a `<ButtonGroup>` with `justified` prop:

    <ButtonGroup justified>
      <DropdownButton>...</DropdownButton>
    </ButtonGroup>

**Comment by ajalbani1** [comment]
$toggle-btn-width-x: 25px;
.login-container{
    .dropdown{
        width: 100%;
        .btn-default{
            &:not(.dropdown-toggle){
                width: calc(100% - #{$toggle-btn-width-x});
            }
        }
        .dropdown-toggle{
            width: $toggle-btn-width-x;
        }
    }
    .dropdown-menu{
        width: 100%;
    }
}

**Comment by ajalbani1** [comment]
`$toggle-btn-width-x: 25px;
.login-container{
    .dropdown{
        width: 100%;
        .btn-default{
            &:not(.dropdown-toggle){
                width: calc(100% - #{$toggle-btn-width-x});
            }
        }
        .dropdown-toggle{
            width: $toggle-btn-width-x;
        }
    }
    .dropdown-menu{
        width: 100%;
    }
}`

**Comment by AdamMYoung** [comment]
For anyone still having this issue, you can set full width button and menu with some simple CSS

```css
.dropdown-toggle,
.dropdown-menu {
  width: 100%;
}
```

**Comment by darshit-singh** [comment]
> For anyone still having this issue, you can set full width button and menu with some simple CSS
> 
> ```css
> .dropdown-toggle,
> .dropdown-menu {
>   width: 100%;
> }
> ```

This worked, thanks. Sometimes the simplest solution is the best one haha.

**Comment by nardove** [comment]
None of the solutions listed above solve the width 100% for me, I'm using Bootstrap 4 and React-Bootstrap 1.64, are there any other ways to work around this?

**Comment by juliuscalvium** [comment]
I was able to get this working by using the Dropdown and Toggle components, then you can add the `block` boolean prop to `Dropdown.Toggle`

```
<Dropdown>
  <Dropdown.Toggle block>Dropdown title</Dropdown.Toggle>
  <Dropdown.Menu>
    <Dropdown.Item>Publish</Dropdown.Item>
    <Dropdown.Item>Settings</Dropdown.Item>
  </Dropdown.Menu>
</Dropdown>;
```

**Comment by rickyoleary** [comment]
For Bootstrap 5, adding d-grid class to the button worked for me:
<DropdownButton id="dropdown-basic-button" className={"d-grid"}
                           title={"title"}>
        <Dropdown.Item href="#/action-1">x</Dropdown.Item>
        <Dropdown.Item href="#/action-2">x</Dropdown.Item>
        <Dropdown.Item href="#/action-3">x</Dropdown.Item>
    </DropdownButton>
