### ISSUE TITLE
Table component: unable to achieve static header and scrolling body

### ISSUE THREAD

**Issue by kcgunn** [react-bootstrap/react-bootstrap#1989]
There is no functionality to achieve a static header, vertically scrolling Table. This is pretty crucial IMO - there is support for horizontal table scrolling in devices under 768px, shouldn't there also be built in functionality to achieve a vertically scrolling body data table? I can't seem to achieve this with just plain CSS/styling/JS at this point, the data won't dynamically resize and the columns are not lining up at all! Please advise!

**Comment by jquense** [comment]
Bootstrap Table is jsut a few styles around the html `<table>` element, and that element doesn' do static headers. Eventually browsers will support `position: sticky` css for these use cases, but that current support it pretty bare. If you need this functionality you' have to do it in javascript. There are plently of libraries for tables and datagrids out there that do handle this luckily.

**Comment by kcgunn** [comment]
unfortunately, most have CSS libraries attached that don't play well with react-BS CSS

**Comment by taion** [comment]
There is no React-Bootstrap CSS. All the CSS comes from Bootstrap.

**Comment by kcgunn** [comment]
semantics.....sorry I meant bootstrap CSS
