### ISSUE TITLE
Dropdown keys traveling skips items

### ISSUE THREAD

**Issue by liorbentov** [react-bootstrap/react-bootstrap#1990]
Let's say I have a dropdown menu with 5 menu items.
When i'm trying to travel the items with up/down arrows, the items that is suppose to be focused being skipped. For example: if my focus is on the first item, when i'll hit the down key, the focused item will be the third (and not the second, as I expect)

I think the problem is in the handleKeyDown in dropdownMenu.js, maybe i'm not using the Dropdown the right way... but I really need a hand with this.

Here is an exmple of my Code:
            `<Dropdown id="dropdownId">
                <Dropdown.Toggle>
                    Dropdown1
                </Dropdown.Toggle>
                <Dropdown.Menu>
                    <MenuItem eventKey={1} href="http://www.1.com">1</MenuItem>
                    <MenuItem eventKey={2} href="http://www.2.com">2</MenuItem>
                    <MenuItem eventKey={3} href="http://www.1.com">3</MenuItem>
                </Dropdown.Menu>
            </Dropdown>`

Thanks

**Comment by taion** [comment]
This works fine on the dropdowns in our examples: http://react-bootstrap.github.io/components.html#btn-dropdowns (specifically http://react-bootstrap.github.io/components.html#btn-dropdowns)

Most likely you have something else there that's messing with keyboard event handling.
