### ISSUE TITLE
Tooltips, Popovers restrict values of left & top erroneously

### ISSUE THREAD

**Issue by latortuga** [react-bootstrap/react-bootstrap#1991]
Tooltips and Popovers are the only ones I've noticed but I'm sure there are other offenders for this. The `positionLeft` and `positionTop` component arguments are defined to be numbers ([example](https://github.com/react-bootstrap/react-bootstrap/blob/master/src/Popover.js#L31)) but these end up setting CSS values under the hood which can be 'px' '%' or any other allowed css measurement. The restriction to numbers should not be there and the docs should demo with a legitimate measurement instead of a unitless number.

**Comment by taion** [comment]
You can't set those anyway; they're meant to be injected by `<Overlay>` or the appropriate trigger.

**Comment by taion** [comment]
Sorry, you're right – we'll resolve this as part of #2026.
