### ISSUE TITLE
getInitialState was defined on OverlayTrigger

### ISSUE THREAD

**Issue by n8thegr8** [react-bootstrap/react-bootstrap#1997]
When I use OverlayTrigger to trigger a Popover I get the following warning message in the console.
`Warning: getInitialState was defined on OverlayTrigger, a plain JavaScript class. This is only supported for classes created using React.createClass. Did you mean to define a state property instead?`

**Comment by taion** [comment]
`<OverlayTrigger>` is not an ES6 class: https://github.com/react-bootstrap/react-bootstrap/blob/9e09af2b5ecc5f6521bdf16576f0469e241e707c/src/OverlayTrigger.js#L27

**Comment by dozoisch** [comment]
@taion It doesn't seem to be using any mixins, should we just move it to an ES6 class? I can send a pr to do it.

**Comment by taion** [comment]
We should probably eventually get rid of the remaining old-style components. I don't think it's especially urgent, but it'd be quite nice to have!

**Comment by dozoisch** [comment]
I'll try to get that done today, if I can get a few mins
