### ISSUE TITLE
Document cases where component classes must accept refs

### ISSUE THREAD

**Issue by mwilliamson-healx** [react-bootstrap/react-bootstrap#1998]
Unless I've missed something, `dialogComponentClass` cannot be a functional component since `findDOMNode` doesn't work. Although the name of the property suggests this (is that intentional?), I accidentally broke my code by changing the component I was using into a functional component (so wasn't looking at the property itself at the time). Is it worth clarifying this in the docs, or perhaps even better, producing a more informative error message? At the moment, the failure is something like `TypeError: Cannot read property 'scrollHeight' of null`.

In any case, thanks for the library!

**Comment by taion** [comment]
I've updated the topic a bit. This is a fair point though – there are a number of places where we necessarily attach refs to components where the classes can be customized, so we should document that we do this and expect to be able to do so.

**Comment by jquense** [comment]
I was really hoping that React would back track on that eventually but it seems like no. It does seem good to document where we expect ref-abilty. :+1:
