### ISSUE TITLE
Passing className to Popover doesn't work

### ISSUE THREAD

**Issue by oliverswitzer** [react-bootstrap/react-bootstrap#1999]
Seems as though the className prop passed to Popover gets overridden with only bootstrap related classes.

`<Popover className='modeling-popover' title={title} {...otherProps}/>`

`className` evaluates to "fade in popover top"... I think maybe whatever is handling the fade is overwriting the class.

**Comment by taion** [comment]
`<Popover>` composes in `className`. You probably have `className` in `otherProps`, and are clobbering your supplied `className` that way.
