### ISSUE TITLE
Implement Input

### ISSUE THREAD

**Issue by stevoland** [react-bootstrap/react-bootstrap#20]
Some ideas

```
<Input
    type="number"
    addonBefore="$"
    addonAfter=".00"
    label="How much"
    isInline={true}
    bsStyle="warning"
    hasFeedback={true}
    className="col-sm-9"
    labelClassName="col-sm-3"
    groupClassName="blah"
    placeholder="eg: 27"
    help=""
/>
```

If `label` prop is present, a `.form-group` is rendered:

```
<div class="form-group">
    <label></label>
    <input/>
</div>
```

if `addonBefore` or `addonAfter` prop is present, an `.input-group` is added:

```
<div class="form-group">
    <label></label>
    <div class="input-group">
      <span class="input-group-addon">$</span>
      <input/>
      <span class="input-group-addon">.00</span>
    </div>
</div>
```
- Other props are transferred to the input.
- `type` can also be `select`, `textarea` or a custom instance
- If `checkbox` or `radio`, label wraps input
- `hasFeedback` adds icons based on `bsStyle`

**Comment by PetrSnobelt** [comment]
Just note that there is wrapper around selectize.js 
https://github.com/ggarek/react-selectize

**Comment by mtscout6** [comment]
@PetrSnobelt Did you so that library's announcement that it is no longer maintained? What are you looking for?

**Comment by PetrSnobelt** [comment]
I know, but it is only wrapper...
I'm looking for great autocomplete/suggestion component (like selectize) for react-bootstrap
