### ISSUE TITLE
Implement affix

### ISSUE THREAD

**Issue by KurtRMueller** [react-bootstrap/react-bootstrap#200]
Hey guys,

First, thanks for all your hard work. From a random dev, I really appreciate this project!

Second, I'm just curious why this project doesn't implement the bootstraps affix component. Is there any particular reason why/why not? Or maybe you don't have time?

Thanks for any and all info.

**Comment by tomatau** [comment]
Can you please include maybe some inline documentation for people who are looking to use this? It's certainly better than anything else that exists right now so curious to see how it's intended to work as the `offset`, `top` and `bottom` are a little bit ambiguous at the moment!

It looks like what's been created already can support many use cases!

**Comment by julianocomg** [comment]
Hey, how about something like this: https://gist.github.com/julianocomg/296469e414db1202fc86

**Comment by AlexKVal** [comment]
@julianocomg it would need to resolve naming issue at first.

```var React = require('react/addons');```
and it seems you would need to refactor without use of `react/addons`

Though I like the idea of your component simplicity :sparkles: :+1: 

Nevetheless `Affix` component already exists, complex one, and it is in the public API.
That means we cannot just replace it with component with very different API.

**Comment by julianocomg** [comment]
@AlexKVal Yeah, I tried to use the original Affix on my project, and it didn't work as expected... So I made this example to post here, for those who wants a more simple solution. (for now, like me).

I will send a pull request with this idea (It also works without addons).

But the question here is: what is the "offsetTop" and "offsetBottom" use cases on the original component? Anyone really use this? It seems a little complex for those who just wants a boolean affix element.

**Comment by mtscout6** [comment]
Our docs use it for the side nav, though it is a bit jumpy at the moment. Any improvement would be appreciated.

**Comment by darkyen** [comment]
For some reason multiple affixes with very high offset break it.

**Comment by barbalex** [comment]
@julianocomg thanks for your solution!

**Comment by taion** [comment]
https://github.com/react-bootstrap/react-overlays/pull/30
