### ISSUE TITLE
Props warnings

### ISSUE THREAD

**Issue by jgironmi** [react-bootstrap/react-bootstrap#2000]
The console is showing me this warning:
warning.js?8a56:44Warning: Unknown props `active`, `bsStyle`, `now`, `isChild`, `srOnly`, `striped`, `bsClass` on <div> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop.

package.json dependencies: 
....
    "react": "^15.0.2",
    "react-addons-css-transition-group": "^15.1.0",
    "react-addons-pure-render-mixin": "^15.0.2",
    "react-bootstrap": "^0.29.4",
    "react-bootstrap-datetimepicker": "0.0.22",
    "react-datetime": "^2.1.0",
    "react-dom": "^15.0.2",
    "react-redux": "^4.4.5",
    "redux": "^3.5.2",
    "redux-thunk": "^2.1.0",
....

Looks like react bootstrap elements create divs to which invalid props are passed.

**Comment by dozoisch** [comment]
See https://github.com/react-bootstrap/react-bootstrap/issues/1994. This is due to a change in react 15.2.

**Comment by jgironmi** [comment]
Thanks man!!!

**Comment by paulsoft** [comment]
it is released ??

**Comment by dozoisch** [comment]
@paulsoft well https://github.com/react-bootstrap/react-bootstrap/pull/2026 has been merged. https://github.com/react-bootstrap/react-bootstrap/pull/2036 is on its way.  But it's taking some time. We're talking about a diff of more than 6 thousand lines. Taion is doing an amazing job at it :)
