### ISSUE TITLE
Adding css classes to Row

### ISSUE THREAD

**Issue by BorisKozo** [react-bootstrap/react-bootstrap#2002]
I am trying to add my own classes to Row but they are rendered before the Bootstrap classes and therefore I cannot override them:

code:
````
<Row className="outer-wrapper">
</Row>
````

Result:
````
<div class="outer-wrapper row"></div>
````

What I want:
````
<div class="row outer-wrapper"></div>
````

Is there a way to do it without adding extra HTML elements?

**Comment by taion** [comment]
That's not how CSS precedence works.

**Comment by c0b** [comment]
I need similar stuff @taion could you comment is there a workaround?

```jsx
<Col sm={3} md={2} className="sidebar" >
```

generates

```html
<div class="sidebar col-sm-3 col-md-2">...
```

what I want is to put my extra customization class name to be the last one: to override part of the styles

```html
<div class="col-sm-3 col-md-2 sidebar">...
```

**Comment by jquense** [comment]
@c0b as taion said, css precendence doesn't work like that. The order of the classes on the element has no affect on the order they are applied.

**Comment by c0b** [comment]
@jquense so is there a workaround to customize some part of `col-*-*` that I don't want?

what you said could be true as W3C or some standard; but what I found is if I manually define the order, like `<Col className="col-sm-3 col-sm-2 sidebar">` that really works, in Firefox and Chrome at least;
but I hope you can have a better workaround

**Comment by jquense** [comment]
the correct way to do it is to the make sure your class have a higher [specificity](https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity) than the classes you are trying to override

**Comment by c0b** [comment]
I just searched "css precendence" google gives me these answers http://stackoverflow.com/a/25105841 https://css-tricks.com/precedence-css-order-css-matters/

> There are several rules ( applied in this order ) :
> inline css ( html style attribute ) overrides css rules in style tag and css file
> a more specific selector takes precedence over a less specific one
> rules that appear later in the code override earlier rules if both have the same specificity.

> Assuming specificity is exactly the same, order does matter.
> Styles declared later win.

**Comment by jquense** [comment]
You are misreading that article, see this line:

> The order of the attributes in the HTML don't matter. It's the order in the stylesheet.

As I said. the _right_ way to do what you want is to make your class win by declaring it later in the cascade or by making it more specific

**Comment by c0b** [comment]
but it didn't explain how it works in Firefox and Chrome: the `className="col-sm-3 col-sm-2 sidebar"` works and `className="sidebar col-sm-3 col-sm-2"` didn't; the bundled css files are the same, so the order between sidebar and bootstrap classes in css is the same

**Comment by nth-chile** [comment]
My issue is that `<Row className='class'>` does not add the class at all, _until_ the page gets live-updated by making a change to the document (within the returned html tags) and saving it.

**Comment by faeghe-hajiabadi** [comment]
What if we want to use conditions here? 
like this -> <div class='row' > ---> if boolean true class= bordered else class = unbordered
