### ISSUE TITLE
Feature Request: Don't mount to div for tabs until tab is clicked

### ISSUE THREAD

**Issue by AdamKyle** [react-bootstrap/react-bootstrap#2009]
To better explain:

```
  <Tabs defaultActiveKey={2} id="uncontrolled-tab-example">
    <Tab eventKey={1} title="Tab 1">Tab 1 content</Tab>
    <Tab eventKey={2} title="Tab 2">Tab 2 content</Tab>
    <Tab eventKey={3} title="Tab 3" disabled>Tab 3 content</Tab>
  </Tabs>
```

I use components  for tab content. What would be cool is if we didn't mount (or had a way to not mount) the component or show the div inside the tab content until its been clicked on.

So if I inspect the source and I haven't clicked on tab 3, I should see nothing.

Right now because of how it works if I mount a component in tab three and the data isn't ready for that component in tab three there are errors shown in the console. I currently get around this by saying: `if current tab === 3` then show the contents else show empty div. Which to me is a hack and a messy way of doing things.

**Comment by taion** [comment]
Use `unmountOnExit`

**Comment by littlebee** [comment]
Hi.   `unmountOnExit` is great, but I think what I really need is something closer to the original request.  

I have 7-8 tabs each with graphs and tables of infrequently (daily) updated data.   I don't want to load all that data at once and never if it's not viewed, but I don't want to reload it as they go back to a previously visited tab either.

A `mountOnEntry` would be really useful.

**Comment by taion** [comment]
It does both

**Comment by jquense** [comment]
I think the request that it _not_ unmount on exit, but not mount until active, so fetched data isn't lost.

TBH I tend to think this is better solved by whatever is doing the data fetching and a cache. Relying on the mount-ness of a component as a cache can be finicky

**Comment by littlebee** [comment]
Yeah, I know.  I only want one

**Comment by littlebee** [comment]
Yeah that covers the case of the data, but I don't want the react datagrid or the d3 graphs to render either.

**Comment by dozoisch** [comment]
For now, you could do your own wrapping component to do it. Something like:

```
class CachedTab extends Component {
  state = { shouldBeRendered: this.props.active };
   
  componentWillReceiveProps(nextProps) {
    if (!this.state.shouldBeRendered && nextProps.active) {
      this.setState({ shouldBeRendered: true });
    }
  }

  render() {
    if (this.state.shouldBeRendered) {
        return this.props.children; 
    }
    return null;
  }
}
```
