### ISSUE TITLE
Refs does not seem to work on bootstrap components

### ISSUE THREAD

**Issue by ericchaves** [react-bootstrap/react-bootstrap#202]
Hi Folks,

Declaring Refs on bootstrap components only works in the top-level component. For example, when rendering something like the component below, the refs property for the component is empty (eg: {}):

```
        <Navbar brand="MySite">
            <Nav className="navbar-right">
              <DropdownButton ref="profileButton" title={this.state.username + '@' + this.state.merchant}>
                <MenuItem onClick={this.logoffHandler}>Logoff</MenuItem>
              </DropdownButton>
            </Nav>
       </Navbar>
```

Shouldn't this be working as usual, since ref is a React feature?

Regards,

Eric

**Comment by willgm** [comment]
I have a case when I need to focus a field inside a modal when it show up, and I was doing it accessing the field by ref on `componentDidMount`. Now I can't and the only way I see is querying the DOM by class, id or etc. That's the way it should be? The refs loose it meaning for me this way...

**Comment by taion** [comment]
`componentDidMount` on the `Modal` refers to the top-level modal. You'd need to put that lifecycle hook on a nested component inside the portal.

Regardless, that's not relevant to this issue, which deals with old React brokenness pre-`cloneElement`.
