### ISSUE TITLE
React 15.2 completely breaks react-bootstrap

### ISSUE THREAD

**Issue by pdeva** [react-bootstrap/react-bootstrap#2020]
Console is filled with warnings.

Screenshots:
http://screencast.com/t/KEMj2cD0t9x
http://screencast.com/t/C31SHdZJ6Nx
http://screencast.com/t/O0ZiMBdM

**Comment by dozoisch** [comment]
Se https://github.com/react-bootstrap/react-bootstrap/issues/1994
