### ISSUE TITLE
<Form> does not support onSubmit method

### ISSUE THREAD

**Issue by jame-sparker** [react-bootstrap/react-bootstrap#2021]
There is no way to detect submission with horizontal forms.

**Comment by taion** [comment]
It's supported just fine. We pass it down to the underlying `<form>`, as we do with all props not explicitly handled.

**Comment by cchen146** [comment]
No it doesn't work

**Comment by PrimeTimeTran** [comment]
Yeah... it doesn't work for me either

**Comment by PrimeTimeTran** [comment]
@cchen146 it works with <form> though.
