### ISSUE TITLE
Problems with React 15.2.0

### ISSUE THREAD

**Issue by sauravskumar99** [react-bootstrap/react-bootstrap#2023]
There are a few problems showing up in the browser console when upgrading to react 15.2.0 which were not showing up in the earlier versions.. Can somebody please give a solution.

``Unknown props `navItem`, `noCaret`, `useAnchor`, `bsRole`, `active`, `navDropdown` on <button> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop
    in button (created by Button)
    in Button (created by DropdownToggle)
    in DropdownToggle (created by Dropdown)
    in div (created by ButtonGroup)
    in ButtonGroup (created by Dropdown)
    in Dropdown (created by Uncontrolled(Dropdown))
    in Uncontrolled(Dropdown) (created by DropdownButton)
    in DropdownButton (created by App)
    in li (created by App)
    in ul (created by App)
    in nav (created by App)
    in div (created by App)
    in div (created by App)
    in App (created by Connect(App))
    in Connect(App) (created by RouterContext)
    in RouterContext (created by AsyncConnect)
    in AsyncConnect (created by Connect(AsyncConnect))
    in Connect(AsyncConnect) (created by Router)
    in Router
    in Provider``

**Comment by sauravskumar99** [comment]
@taion Can you please direct me to the duplicate issue? Thank You

**Comment by jquense** [comment]
#2001
