### ISSUE TITLE
Unknown props ... with React@15.2.0

### ISSUE THREAD

**Issue by KateKate** [react-bootstrap/react-bootstrap#2024]
Thanks for you lib! It's helpful a lot.
With the latest React version (15.2.0) it shows a lot of warnings kinda:
`Unknown props `active`, `block`, `navItem`, `navDropdown` on <button> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop`

Is it possible to fix it w/o lib changes? 
Thanks in advance!

**Comment by jquense** [comment]
#2001 duplicate
