### ISSUE TITLE
Adding href into thumbnail makes all the button disappeared #177

### ISSUE THREAD

**Issue by maxsonic** [react-bootstrap/react-bootstrap#2028]
Hi, 

I have tried the following code and the result seems weird. The button, h3 and p gone away.

>     <Col xs={6} md={4}>
>       <Thumbnail src="/assets/thumbnaildiv.png" alt="242x200" href="#">
>         <h3 >Thumbnail label</h3>
>         <p>Description</p>
>         <p>
>           <Button bsStyle="primary">Button</Button>&nbsp;
>           <Button bsStyle="default">Button</Button>
>         </p>
>       </Thumbnail>
>     </Col>

Is it a bug or I have misused the 'href'?

**Comment by taion** [comment]
This is getting fixed in the big sweep in #2026
