### ISSUE TITLE
Buttons/Dropdowns retaining hover state

### ISSUE THREAD

**Issue by benheymink** [react-bootstrap/react-bootstrap#2031]
I've found [Issue 1502](https://github.com/react-bootstrap/react-bootstrap/issues/1502) that was closed, mentioning accessibility, but this deviates from the standard Bootstrap behaviour, is the stance still the same? It just looks weird clicking a link, opening a modal, or performing some other action, and the dropdown remaining an active state. Happy to submit a PR if it's a simple fix!

**Comment by taion** [comment]
WAI ARIA authoring guidelines explicitly say to return focus to the button https://www.w3.org/TR/wai-aria-practices/#menubutton

**Comment by jquense** [comment]
additional FYI on that, it only returns focus if focus is still in the dropdown, if you move it when the action happens to your modal or whatever it should stay there. The alternative is that focus is dropped completely from the page, which is not a reasonable alternative

**Comment by acomito** [comment]
Did a dropdown that opens on hover ever get implemented?

via https://github.com/react-bootstrap/react-bootstrap/issues/568

The example of NavDropdown in the docs is good, but a little more info on the props etc. would be good.
