### ISSUE TITLE
Root item of panel header should not get "panel-title"

### ISSUE THREAD

**Issue by kirill-konshin** [react-bootstrap/react-bootstrap#2032]
Currently if I supply a `div` as `header` of `Panel`:

```jsx
<Panel header={<div><h1>Foo</h1><p>Stuff</p></div>}>...</Panel>
```

this `div` will get class `panel-title` automatically. This class should be applied *only* to H1-H7 elements like this (BS doc: http://getbootstrap.com/components/#panels-heading):

```html
<div class="panel-heading">
    <h3 class="panel-title">Panel title</h3>
</div>
```

Because of such behavior the `div` receives improper `font-size`.

The only way to solve this is to supply header items as an array (which is very weird, especially if there will be only one element):

```jsx
<Panel header={[<h1>Foo</h1>, <p>Stuff</p>]}>...</Panel>
```

Root cause of issue:

```js
const className = classNames(
    prefix(this.props, 'title'), header.props.className
);

header = cloneElement(header, {className});
```

**Comment by taion** [comment]
https://github.com/react-bootstrap/react-bootstrap/issues/983, https://github.com/react-bootstrap/react-bootstrap/pull/1769
