### ISSUE TITLE
DropDown.Menu and arrow keys navigation

### ISSUE THREAD

**Issue by af7** [react-bootstrap/react-bootstrap#2035]
Hi, I use the DropDown and DropDown.Menu.

I find that when the submenu opens I cannot press the 'Down' arrow to go to the 1st submenu item, and then go to other items (focus on them) with other 'Down/Up' presses.

Do you have support for arrow keys navigation on Menu items?

Thanks!

**Comment by jquense** [comment]
are you using the normal components? 8ts working fine in the docs page...

**Comment by af7** [comment]
@jquense Thank you for your reply, I missed it somehow.

If you may, please visit this website...
https://www.marinetraffic.com/

...and write something here:
![image](https://cloud.githubusercontent.com/assets/7850073/17301327/130ec05a-581f-11e6-9dae-f8f6d36770a4.png)

You will see that the input box is used to query for items on every character addition after the first 2 ones. This opens a Dropdown.Menu, which has a list of <MenuItem> entities.

How can I send the focus to the <MenuItem> part, so that they keyboard works there as expected?

Thanks!
