### ISSUE TITLE
Center modal window vertically on browser window

### ISSUE THREAD

**Issue by af7** [react-bootstrap/react-bootstrap#2038]
I could not find a prop to center modal window vertically on browser window.

Is there any way to have this?

Thanks!

**Comment by taion** [comment]
Neither React-Bootstrap nor Bootstrap JS explicitly handle modal positioning like that – this is for your CSS to do.

**Comment by mittalabhas1** [comment]
`.modal-dialog {
    display: flex;
    flex-direction: row;
    align-items: center;
    justify-content: center;
    height: unquote("calc(100vh - 20px)");
    // 20px offset for the 10px margin on either side
    .modal-content {
        width: 100%;
    }
}

.modal-backdrop.in {
    opacity: 0.8;
    filter: alpha(opacity=80);
}`

@af7 @amgohan This might help.
