### ISSUE TITLE
For the Overlay Tooltip the initial positioning is causing trouble

### ISSUE THREAD

**Issue by anuprai11** [react-bootstrap/react-bootstrap#2040]
When in OverlayTrigger component we give an overlay.In one case that overlay is a Tooltip. So during rendering first the overlay is inserted with position: absolute but no position is provided. So basically it comes as the last child of the body. After that it finds the target Element and repositions itself as per the target.

The problem here is the element has height and position so when it comes into the dom it increases the height of the body which in turn creates a body scroll (in case if the body had no scroll earlier) and in many cases that scroll can cause disruption in the elements positioning which may persist or may not depending on the cases.

Like in one case

There are three tabs on the screen. Each having body/3 width. Now when the overlay is triggered on the last tab. The tooltip comes to the bottom of the body causing a scroll to come in which causes the scroll to come in in case of systems where scroll is not always active. Now that scroll causes the third tab to go down due to its width. Now the target position of the overlay tooltip is also calculated wrong (as it is calculated based on the new position of the third tab). This causes the whole UI to rupture.

If the initial tooltip is rendered at top:0 this problem could be solved

**Comment by taion** [comment]
The underlying position calculations are all in react-overlays. We'd be happy to look at a PR there. Thanks.
