### ISSUE TITLE
Add ability to prefix all Bootstrap classes

### ISSUE THREAD

**Issue by ixley** [react-bootstrap/react-bootstrap#2041]
It would be great to have the ability to pass in a custom prefix that would get applied to all Bootstrap classes. This would allow react-bootstrap to work with Bootstrap instances that have custom prefixes for namespacing (e.g. `.bs-btn` instead of `.btn`). 

I have been able to customize `bsClass' in some cases, but that's obviously not its intended use, and it only works with a handful of cases.

**Comment by taion** [comment]
That's exactly what `bsClass` is for.

**Comment by ixley** [comment]
Sorry, I gave a poor example. I realize I can use `bsClass` on `<Button>` to customize the base class. What I actually would like is a way to prefix *all* Bootstrap classes (or similarly be able to map any Bootstrap class to a custom one). Because React-Bootstrap relies on a separate instance of Bootstrap to reference its classes for styling (rather than embedding the styles directly), it makes it hard to support any further degree of customization.

We are namespacing *all* Bootstrap classes to keep them scoped and identifiable among other libraries and custom utility classes. So it's not just `.bs-btn`, but also `bs-pull-right`, `bs-col-md-8`, `bs-list-style`, etc. Unless I misunderstand, `bsClass` has a much more limited scope for the component names it can customize.

**Comment by jquense** [comment]
you are right bsClass doesn't cover that case. bsClass covers the component classes, and specifically the ones that affect the rendering of size and style variants (`btn` btn-lg` `btn-primary`) which are generally unavailable to change via the normal component prop API. Utility classes however _are_, our recommendation for those instances is to use `className` to add your version of the classes. We don't usually add the plain pull-right or list-unstyled classes anyway.

Not sure if we also want to support bsClass in purely presentational components like Col, since it adds complexity and the components are already just simple wrappers around the markup

**Comment by taion** [comment]
Well, that part I already did on `next`. I'd rather we take out most of the helpers like `.pull-right` anyway, in which case you only have JS-y classes like `.in`, which would be weird to prefix anyway.

**Comment by jquense** [comment]
most of the places we have `pullRight` stuff is in a prefixed context, like the navbar, or where its explicitly noted as the right way to use it. most ofthe later cases though have been replaced upstream with context specific classes like `dropdown-menu-right`

**Comment by ixley** [comment]
You're right @jquense, there isn't a specific need to have control over _all_ classes in React-Bootstrap, such as the layout components/classes. I was just trying to clarify that _we_ are prefixing *all* Bootstrap classes in an effort to namespace them consistently.

And yes, my actual preference for lightweight and more literal utility classes like `.pull-right` is just to see the styling pulled into JS, rather than relying on class names in the first place. 

I'll take another look and see what I can accomplish with `bsClass` and `bsStyle`. Thanks for your replies, @jquense and @taion

**Comment by hectorsabina** [comment]
I was looking into this option as we need to maintain legacy code that has modified bootstrap css. Now we're starting to launch some react components, using bootstrap for styling and dealing with some old customised rules (directly in the vendor files, they style non react code) is becoming very annoying.

I just happened to bump into this project [bootstrap-namespaced](https://github.com/jonasjancarik/bootstrap-namespaced), which looks promising (I haven't tested it yet). It might not achieve the OP objective of prefixing all bootstrap classes but it might help with the root problem, which I understood it was to gain higher level of customisation of styles that are not affected by `bsClass` / `bsStyle` props.

**Comment by taion** [comment]
I wonder if we could also make `bsUtils` customizable somehow

**Comment by goldylucks** [comment]
I'm developing a web extension and bootstrap has many classes that collide with other libraries, i.e. `.modal`

would be great to be able to do something like
`<ThemeProvider classesPrefix="my-namespace">`

is there a workaround for that?

otherwise need to individually list all the prefixes
