### ISSUE TITLE
It is not possible to make DropdownButton block-level element

### ISSUE THREAD

**Issue by egeriis** [react-bootstrap/react-bootstrap#2043]
Using Bootstrap, a button and button group can be configured to have full width. Unfortunately, this configuration is not possible through react-bootstrap when using `DropdownButton`.

I've attempted to use the same configuration as is available for `ButtonGroup`s:

```jsx
<DropdownButton vertical block>
  <MenuItem>Hello</MenuItem>
  <MenuItem>World</MenuItem>
</DropdownButton>
```

This renders DOM similar to this:

```html
<div class="dropdown btn-group">
  <button class="btn btn-default btn-block">Title</button>
</div>
```

What's missing is a "btn-block" class on the `<div />`, as that seems to resolve what I am attempting to produce—a full-width button dropdown.

A possible solution would be to allow the setting of "block" attribute on `DropdownButton` which will add the "btn-block" class, while keep propagating it to the `Button`.

**Comment by jquense** [comment]
You can use the Dropdown component directly for this sort of this, since it gives you better control over where stuff goes!

**Comment by egeriis** [comment]
Ah, let me give that a try.

**Comment by egeriis** [comment]
That works wonderfully. Solution:

```jsx
<Dropdown block>
  <Dropdown.Toggle block>
    Title
  </Dropdown.Toggle>
  <Dropdown.Menu>
    <MenuItem>Hello</MenuItem>
    <MenuItem>World</MenuItem>
  </Dropdown.Menu>
</Dropdown>
```

Thanks @jquense

**Comment by zikolach** [comment]
@egeriis it works but outputs warning in this case ```Failed prop type: `block` requires `vertical` to be set to have any effect```

**Comment by sajera** [comment]
+1
