### ISSUE TITLE
Modal doesn't retain context

### ISSUE THREAD

**Issue by SeeThruHead** [react-bootstrap/react-bootstrap#2046]
So we're using modal from 'react-bootstrap/lib/Modal' as the basic for our modal in our apps. We also use context to pass down themes from a ThemeProvider style component. Any components that grab themes from context that in nested inside a bootstrap modal have context: undefined.

I've read through the other issues around this. They seem to focus on adding this ability to ModalTrigger, which is not something we use. Any ideas for a workaround?

**Comment by jquense** [comment]
Hi there, those issues are very old. Modal _does_ pass down context, unless you are using a really old version of react-bootstrap.

**Comment by SeeThruHead** [comment]
we're using 0.28.3

**Comment by jquense** [comment]
great! that version passes context down, if you aren't seeing it you may be defining your contextTypes incorrectly or with a typo, perhaps. Otherwise if you can provide Repro with jsFiddle we can address any bugs.

**Comment by amaster507** [comment]
@SeeThruHead, did you ever find your problem? We are using 1.0.0 and are having a hard time handling context pass through.
