### ISSUE TITLE
Radio button documentation insufficient to use efficiently in project

### ISSUE THREAD

**Issue by ChrisRus** [react-bootstrap/react-bootstrap#2048]
I've search high and low for a single complete working example of a controlled group of <Radio> buttons that actually works like one would expect. It's not sufficient to provide a single example that supports no coupling whatsoever between the <Radio> buttons as this leaves developers to troll StackOverflow and waste hours trying to figure out how to make it work.

From this StackOverflow thread: http://stackoverflow.com/questions/30129631/react-bootstrap-buttongroup-as-radio-buttons

... this example looks reasonable to me:

```JavaScript
_onOptionChange(option) {
    this.setState({
        option: option
    });
}

render() {
    render (
        <ButtonGroup>
            <Button onClick={this._onOptionChange.bind(this, 'optionA')} active={this.state.option === 'optionA'}>Option A</Button>
            <Button onClick={this._onOptionChange.bind(this, 'optionB')} active={this.state.option === 'optionB'}>Option B</Button>
        </ButtonGroup>
    );
}
```

... however, it simply doesn't work for me. Seemingly the value of **active** is completely ignored.

If I instead use **defaultChecked** instead of **active** then I at least get the right control checked on initial render. But subsequent re-render does not update the state of the controls.

So, I tried settings **value** directly to make the Radio a controlled component (and specified an onClick handler to update the component state I'm using to track which Radio is selected). 

But this doesn't work either: all callbacks are being called and doing the right thing but the re-render simply doesn't update the controls.

What's the magic? Once I get it working, I will write up a _complete_ example and pass it back.

My latest (attempt at controlled radio using `value` - use of `defaultCheck` is likely wrong?):

```JavaScript
	return (<div id="idViewScaleSlider">
                <div className="title">View Settings</div>
                <div className="mode">
                <strong>Display:</strong>&nbsp;
                <span className="controlgroup">
                <span title="Snap timeline to latest available data..."><Radio inline onClick={this.onComponentUpdateSnap.bind(this, 'latest')} value={this.isSnapOptionChecked('latest')} defaultChecked={this.isSnapOptionChecked('latest')}>Latest</Radio></span>
                &nbsp;&nbsp;&nbsp;
                <span title="Snap timeline to current time..."><Radio inline onClick={this.onComponentUpdateSnap.bind(this, 'now')} value={this.isSnapOptionChecked('now')} defaultChecked={this.isSnapOptionChecked('now')}>Now</Radio></span>
                &nbsp;&nbsp;&nbsp;
                <span title="Manually position timeline..."><Radio onClick={this.onComponentUpdateSnap.bind(this, 'manual')} value={this.isSnapOptionChecked('manual')} defaultChecked={this.isSnapOptionChecked('manual')}inline>Custom</Radio></span>
                </span>
                </div>
                <div className="scalelabel"><strong>Scale:</strong></div>
		<div className="slider">
		<div className="info">One {sliderMarks[viewscaleDescriptor.ordinal]} at {viewscaleDescriptor.pointScale} resolution.</div>
                <Slider disabled={disabled} min={sliderMin} max={sliderMax} marks={sliderMarks} step={null} value={viewscaleDescriptor.ordinal} onChange={this.onComponentUpdateViewSettings} /></div>
		</div>
                
                );
```

Any suggestions would be appreciated. When I get this working, I'm happy to contribute some time to beef up the example and docs.

**Comment by taion** [comment]
Please look at existing issues before opening a new one.

We're already tracking this at https://github.com/react-bootstrap/react-bootstrap/issues/1587.

As noted, this feature is not currently present.
