### ISSUE TITLE
Keeping a <DropdownButton> open when <MenuItem> is selected

### ISSUE THREAD

**Issue by jareware** [react-bootstrap/react-bootstrap#2049]
I tried to look for an answer in the docs and the issue tracker (12 pages of `<DropdownButton>` issues!) but couldn't find one, so:

Is it possible to somehow keep the dropdown from closing when you select one of its items? The use case would be a menu from which you might want to select/toggle several options in one go. An outside-click would still close it as per usual.

**Comment by taion** [comment]
See discussion at https://github.com/react-bootstrap/react-bootstrap/pull/1642.

**Comment by jareware** [comment]
Ah, that makes sense, thanks for the pointer!
