### ISSUE TITLE
Rendering Modal as a child component makes exit callbacks non functional

### ISSUE THREAD

**Issue by rsjorslev** [react-bootstrap/react-bootstrap#2050]
I am trying to implement a "ModalRoot" in a react/redux app as per:
http://stackoverflow.com/questions/35623656/how-can-i-display-a-modal-dialog-in-redux-that-performs-asynchronous-actions/35641680

and i wanted to use the Modal from react-bootstrap.

When i render my <SpecificModal /> it fades in as it should and onEnter function works fine - i am just doing a console.log to verify.
However when i close the modal - by changing the state that show={} is pointed at - it looks like onExit does not fire. Also the fade-out transition that normally shows is no longer there as the modal just disappears so to speak.

If i take the exact same Modal component that i assign to SpecificModal and render it outside <ModalRoot> onExit fires without issues.

Not sure what i am missing here or if this is expected as i might be rendering the Modal component in a wrong way when i do it through ModalRoot component?

Thanks !

**Comment by jquense** [comment]
looking at that issue I think the problem is:

```js
const ModalRoot = ({ modalType, modalProps }) => {
  if (!modalType) {
    return <span /> // after React v15 you can return null here
  }

  const SpecificModal = MODAL_COMPONENTS[modalType]
  return <SpecificModal {...modalProps} />
}
```

that simply unmounts the SpecificModal which doesn't give it any chance to animate out.  If you are using the bootstrap modal, you should use `show` to control visibility of the specific Modals.

**Comment by taion** [comment]
Right – you'd need something like the React transition group approach to keep the old modals around.

**Comment by rsjorslev** [comment]
thank you both.
I am not to worried about the animate out, its more the fact that all exit methods are not being called.

Is there any way i could achieve this concept of a ModalRoot with react-bootstrap Modal component or should i - as stated - use `show` to control this and simply render the exact Modal (e.g. ModalConfirm, ModalInfo etc.) directly?
