### ISSUE TITLE
Dropdown rendering children when not open

### ISSUE THREAD

**Issue by jacktasia** [react-bootstrap/react-bootstrap#2056]
It seems like the `children` of  a `Dropdown` are [always rendered even if it's not opened](https://github.com/react-bootstrap/react-bootstrap/blob/master/src/Dropdown.js#L106). This is problematic when for instance you want to have a large `Dropdown` (for like States) in a dynamic amount of rows because the browser ends up needing to deal with `rowNum * dropdownItemNum` hidden elements. So if you have a 100 rows of employees where they can pick their home state, there are 5000 extra elements in the DOM, which can be slow.

I thought this was going to be as easy as `{this.props.open ? children : null}`, but in my tests it wasn't that straightforward. So maybe this is an intentional decision and I am missing something?

Also, just wanted to thank you guys for making this. It has been a pleasure to use so far.

**Comment by jquense** [comment]
If you need finer control over that sort of thing, i'd use a custom dropdown menu, in this Case I think you probably can get away with wrapping the existing one and passing through the props to it, and then jsut conditionally render children based on `open`. You may have tried that, in which case I'd be interested in what particualr bits of that didn't work.

**Comment by jacktasia** [comment]
>  i'd use a custom dropdown menu, in this Case I think you probably can get away with wrapping the existing one and passing through the props to it, and then jsut conditionally render children based on open

Thanks for the message. So what's unclear to me with that is how to access `open` if I am only wrapping it.  This works, but I don't have access to `open` to conditionally render the `children`

```
class EmptyIfClosedMenu extends Component {
  static propTypes = {
    children: PropTypes.array.isRequired
  }

  render() {
    // can't access 'open' from here
    return (
      <Dropdown.Menu>
        {this.props.children}
      </Dropdown.Menu>
    );
  }
}

class MyDropdown extends Component {
  ...

  render() {
   ....
    return (
      <Dropdown id="dropdown-custom-1">
        <Dropdown.Toggle>
          {currentTitle}
        </Dropdown.Toggle>
        <EmptyIfClosedMenu>
         {choices}
        </EmptyIfClosedMenu>
      </Dropdown>
    );
  }
}

```

**Comment by taion** [comment]
Sure you do. Your custom menu will get `open` injected as a prop from its parent.

**Comment by jacktasia** [comment]
> Your custom menu will get open injected as a prop from its parent.

FWIW, I wasn't lying. I was not getting `open`, but I looked through the code and it behaved as you said once I added `bsRole="menu"` to `<EmptyIfClosedMenu>`. Thanks for your help.
