### ISSUE TITLE
remove lodash-compat - IE8 and lodash-compat both unsupported

### ISSUE THREAD

**Issue by todd-richmond** [react-bootstrap/react-bootstrap#2058]
Now that IE8 is officially unsupported by MSFT and lodash-compat is as well by its author, it will help to eliminate another large library that might cause conflicts

**Comment by taion** [comment]
Who cares it still works. It's gone in #2052 regardless but there's nothing wrong with a package that _works_. `lodash-compat` doesn't magically start failing immediately just because it gets an "unmaintained" label, no more than the rest of lodash v3. We only pull in like 2 or 3 functions anyway.

**Comment by todd-richmond** [comment]
webpack 1.x prints out 70 lodash-compat include files when no other package is referencing it beyond react-bootstrap which is why I entered the RFE. webpack 2.1 tree shaking might cut that down when it goes GA, but I don't have the beta version working w/ my project yet

good to know it is out in a future release though

**Comment by ruiaraujo** [comment]
@todd-richmond you can override it with a webpack alias.

**Comment by todd-richmond** [comment]
I had tried using an alias from lodash-compat -> lodash, but it was loading several sub modules that don't exist in lodash 4 and I didn't have time to enumerate + test + debug everything. I'll just wait a few weeks/month for the next build that has it removed completely
