### ISSUE TITLE
Input in overlay trigger not working 

### ISSUE THREAD

**Issue by ishitakothari** [react-bootstrap/react-bootstrap#2059]
I am trying to pop out an input box in a modal with overlay trigger. I am unable to change text in the box. Can someone please help me out.

Thanks in advance.

**Comment by jquense** [comment]
you might not be wiring your input up correctly, there isn't anything that prevents you from putting an input in an overlay so the problem is probably unrelated. in any case it's not possible to help without a reproduction and some code. thanks!
