### ISSUE TITLE
React Date Picker

### ISSUE THREAD

**Issue by bernadetteguinan** [react-bootstrap/react-bootstrap#206]
Hello,

I am looking for a Date Picker component to work with react-bootstrap. 
Is there anything in the pipeline?

I found this one but not sure if it works with bootstrap:
https://github.com/misino/react-datepicker

Any help appreciated.

thanks
Bernadette

**Comment by wehriam** [comment]
@bernadetteguinan I released a date picker, would appreciate your thoughts on it: https://github.com/pushtell/react-bootstrap-date-picker

**Comment by atapatel** [comment]
@wehriam your plugin is really good but is your plugin also provide Date Range Functionality? and custom Format?

**Comment by taion** [comment]
Your best bet in general is going to be React Widgets, BTW: http://jquense.github.io/react-widgets/docs/

**Comment by atapatel** [comment]
@taion well i try to implement react-widgets but cant get any success.
