### ISSUE TITLE
Noticeable flicker/re-organization on page load

### ISSUE THREAD

**Issue by brandon-arnold** [react-bootstrap/react-bootstrap#2064]
Hi all,

I'm using React-Bootstrap and Bootstrap-Webpack in my setup, with not much more than core and Grid-related stuff enabled. I've noticed for some time that there's about a half-second or more pause when the page loads, and my content is not organized in the grid correctly. The document uses the React-Bootstrap elements such as "Grid","Row","Col," etc.

Anywho I just pulled ```react-bootstrap``` and ```bootstrap-webpack``` out of my project and linked the CDN directly, using simple ```className="col-md-5"``` type syntax in the JSX, and the problem went away entirely.

Is this a known issue?
-Brandon

**Comment by taion** [comment]
You're probably bundling the CSS incorrectly. React-Bootstrap doesn't directly touch on the styling stuff. Look up how to bundle CSS with webpack.

**Comment by brandon-arnold** [comment]
Thanks, @taion. I apparently was; I was just about to come close this and you beat me to it.

Regards.
