### ISSUE TITLE
MenuItem onClick ignores preventDefault

### ISSUE THREAD

**Issue by Kepro** [react-bootstrap/react-bootstrap#2066]
if i use MenuItem then onClick ignores as event.stopPropagation also ignores a event.nativeEvent.stopPropagation also preventDefault and also stopImmediatePropagation

on click page go to href link

what i'm doing wrong? 

```
    <MenuItem
       href="#"
       onClick={(e) => {
         log(item, e);
         e.stopPropagation();
         e.nativeEvent.stopImmediatePropagation();
         this.addItem(item);
       }}
       >{item.label}</MenuItem>
```

only if i add a href="javascript:;" then is working, but i ugly hack...

**Comment by jquense** [comment]
can you provide a fiddle? `preventDefault` is working for me to prevent navigation, thanks.

**Comment by Kepro** [comment]
@jquense, i very sorry for this ticket, we are migrating our application from angular 1 to react and angular take care of routing... but i now found a solution here http://stackoverflow.com/questions/17407024/telling-angular-js-to-ignore-a-specific-route 
i just add target="_self" 

sorry one more time

**Comment by Kepro** [comment]
i rly doesn't know that angular still handle routing outside of angular code... that was a main problem

**Comment by taion** [comment]
You should just be calling `e.preventDefault()` anyway.

**Comment by Kepro** [comment]
yes that is working now
