### ISSUE TITLE
What is componentClass?

### ISSUE THREAD

**Issue by dmitriid** [react-bootstrap/react-bootstrap#2068]
The only page in the entire documentation where `componentClass` is used is https://react-bootstrap.github.io/components.html

However, there's no explanation of what it is, what it does and how it's supposed to be used.

Looking at `FormControl`:

> `type`: Only relevant if `componentClass` is `'input'`.

What? What other `componentClass`es can be there? What other `type`s? How can I find out? How does it affect the `FormControl`? Or other controls?

Please update docs to describe what `componentClass` is and how it can be used.

**Comment by jquense** [comment]
two rows above that line (like 100 pixels up) is the doc entry for componentClass. which can be any element type. see any of the numerous examples for how to use it, thanks.

**Comment by dmitriid** [comment]
Two rows above the entire doc entry is this:

> componentClass	elementType 'input'

Could it be that elementType is described anywhere? Nope.


Oh, I know. componentType and elementType are used not only there, but everywhere on the page. May be they are described elsewhere?

Nope.


In case of `FormControl` I need to scroll down to "Supported controls" and then sift through code to see how all this works.


Please improve this by:

Moving the entire "Supported controls" paragraph to the description of "Form control". Add "view source code in examples for how to use componentClass". Add list of supported component classes to the doc entries (like you do for `bsStyle` in `Button`'s props)

**Comment by jquense** [comment]
`componentClass` is literally any arbitrary react component. It is a common prop and used throughout the code. 

How about don't come rolling into the issue tracker, of an open source project all indignent and entitled that the docs site, with hundreds of live editable, handcrafted examples of ever provided API is missing a level of detail that you feel is your right.

No one here owes you anything, if you are unhappy with the state of the docs, ask nicely, and/or submit a PR, but don't be a jackass towards ppl that work on this stuff in their free time.
