### ISSUE TITLE
Support for es6 modules

### ISSUE THREAD

**Issue by Strato** [react-bootstrap/react-bootstrap#2069]
Hello,

I'm using es6 modules (with TypeScript) but not the Babel transpiler.

React-Bootstrap is quite a big library and right now it gets loaded entirely by webpack.

Doc says es6 modules are not supported yet. Do you have an ETA for this feature?

**Comment by jquense** [comment]
no ETA or concrete plans. PR's are welcome however the reason it's not being worked in is that we already provide commonjs modules whihc you can import individually if you are concernedabout bundle size

**Comment by taion** [comment]
Tree shaking doesn't actually help in most cases, BTW. If anything we're probably going to e.g. drop the explicit ES module build for projects like React Router, because it's a pointless maintenance burden. You need to do the deep module imports no matter what.
