### ISSUE TITLE
Style props don't get passed down in NavItem

### ISSUE THREAD

**Issue by davidweisss** [react-bootstrap/react-bootstrap#2070]
`<NavItem style={{color: 'blue'}} target="_blank" eventKey={2} href="https://mylink.com" >Txt</NavItem>`

Here  ` target="_blank"` gets passed but not `style={{color: 'blue'}}`. It does on Jumbotron for example.

Looking at the code, this may be the culprit:

```
 render() {
    let {
      active, disabled, role, href, onClick, className, style, ...props,
    } = this.props;

```
Maybe removing "style" would fix this.

I'd test/PR this but I'm not experienced enough.

**Comment by jquense** [comment]
`style` is aplied to the outer `<li>` tag in the NavItem not the `<a>` same with `className` this is our general pattern and practice for nested components like this, styling related attributes are given to the root dom node.
