### ISSUE TITLE
Suggestion to improve docs

### ISSUE THREAD

**Issue by dmitriid** [react-bootstrap/react-bootstrap#2073]
On the heels of #2068 

I may have appeared "entitled", I'm just frustrated. Because the docs are confusing.

## Problem statement:

- `componentClass` prop is poorly documented and possible values are largely unknown
- `elementType` (used to describe the type of `componentClass`) is not described and (apparently) can arbitrarily be a `string` or a `class T extends ReactComponent`

It is suggested that one look in the docs for `componentClass` or example source code which only makes things more confusing at times.

## Suggestion

- Dedicate a separate section to describing the `elementType` type
- If `componentClass` accepts a string, provide a list of acceptable strings
- If possible, provide an example how to use a custom component
- Also, improve docs for `type` in `FormControl` (list possible values)

## A long-ish description

The first time `componentClass` is introduced, it's used in `Button`, and it's documentation states:

> `componentClass : elementType`
> You can use a custom element for this component

None of the examples make use of this property. One may assume `elementType` is `class T extends ReactComponent`.

Much further down on the page we can see the docs for `DropdownButton`s. Even though none of the examples show how to use the property, the docs seem to validate the assumption above:

> `componentClass : elementType`
> default: `ButtonGroup `

I haven't looked at all examples for all the components, as I'm mostly concerned with `FormControl`. I may assume that experience is similar.

When we com to `FormControl`s, we encounter a discrepancy:

> `componentClass : elementType`
> default: `'input'`

Here, despite our assumption that `elementType` is actually `class T extends ReactComponent`, the default value suggests that this can, in fact, be a `string`. Same goes for the rest of form controls which seem to accept a `string` as `componentClass` (`FormControl.Static`, `Form`) and quite a few other components on the page.

The use of strings in this and other components may be a shortcut (it's easier to do `componentClass="textarea"` than `import TextArea ... componentClass={TextArea}`). However, this is not explained anywhere and is used quite arbitrarily (what other strings are allowed as values?).

Thankfully, you can deduce available values from the example source code. However, it would be much better if possible values would be listed in the actual documentation.

**Comment by jquense** [comment]
componentClass means anything you can pass to `React.createElement()` the main reason it is under documented is that it's not special or unique but a primitive propType like "node" or Element. There is no set that encompasses what this prop can be, its "anything that React can render". 

The string values aren't magic or shortcuts, they are how React represents "native" (in this case DOM nodes) components. 

```
<div /> // compiles to React.createElement("div")

<MyFoo> // compiles to React.createElement(MyFoo)
```

both "div" and MyFoo are acceptable here.

**Comment by dmitriid** [comment]
> the main reason it is under documented is that it's not special or unique but a primitive propType like "node" or Element

If understand this correctly, this is not a native React PropType. And I see it mentioned in a separate project: https://github.com/react-bootstrap/react-prop-types

It would be really beneficial to those who read the docs to have at least a link to this description.

I also still think that a list of common/acceptable `componentClasses` would be a great addition (especially for `FormControl`, which has "supported controls")

**Comment by jquense** [comment]
the prop is getting a better description in the next release so that should address your concerns here. If it still doesn't seem descriptive enough, we accept PR's very happily.

> I also still think that a list of common/acceptable componentClasses would be a great addition (especially for FormControl, which has "supported controls")

I see why that' be nice but it isn't feasible, the point of this prop is to allow you to specify anything, there are no right or wrong things for this.

**Comment by dmitriid** [comment]
> I see why that' be nice but it isn't feasible, the point of this prop is to allow you to specify anything, there are no right or wrong things for this.

This could be written as:

> Supported controls: 
> - 'textarea'
> - 'input'
> - 'select'
> 
> or a custom element
