### ISSUE TITLE
Dropdown focus behaviour differs from standard bootstrap

### ISSUE THREAD

**Issue by dpwrussell** [react-bootstrap/react-bootstrap#2074]
On standard bootstrap, when selecting an option, the button is not focused afterwards. In React-bootstrap, it is. It's minor, but it makes anything using dropdowns look messy.

Bootstrap: http://getbootstrap.com/components/#btn-dropdowns-single
React-Bootstrap: https://react-bootstrap.github.io/components.html#btn-dropdowns-single

1. Click button
2. Click an action
3. On Bootstrap, the button will not have focus. On React-Bootstrap, it will have focus,

**Comment by taion** [comment]
Dupe of existing issues. The standard BS behavior violates ARIA guidelines. See previous discussion.
