### ISSUE TITLE
I see JS warnings every time I render a popover element in latest React version

### ISSUE THREAD

**Issue by TiraO** [react-bootstrap/react-bootstrap#2075]
I see JS warnings every time I render a popover element:
```
Warning: Unknown props `positionLeft`, `positionTop`, `placement`, `bsClass` on <div> tag. Remove these props from the element. 
```
This appears to be happening because of this line:
https://github.com/react-bootstrap/react-bootstrap/blob/master/src/Popover.js#L83

maybe consider doing something along the lines of `{..._.omit(this.props, _.keys(Popover.propTypes)}` to avoid passing props which exist for the popover not for the div.

**Comment by jquense** [comment]
#1994
