### ISSUE TITLE
change the tooltip default background color

### ISSUE THREAD

**Issue by JpnW** [react-bootstrap/react-bootstrap#2081]
Can anyone tell me any way to add custom background color to the tooltip component?

**Comment by jquense** [comment]
I believe `className` and `style` both work on the tooltip, for all your styling needs

**Comment by taion** [comment]
Or change use a custom Bootstrap theme/bundle.

**Comment by colleenpurcell12** [comment]
*Based on the example from the react-bootstrap docs https://react-bootstrap.github.io/components.html

`
<Tooltip placement="top" className="in" id="tooltip-top">Tooltip top</Tooltip>
`

The CSS to change the background color uses the default ids and classes of nested components that get rendered automatically--

```
#tooltip-top > .tooltip-inner {
  background-color: #fff;
  color: #000;
  border: 1px solid #062e56;
}

#tooltip-top > .tooltip-arrow {
  border-top: 5px solid #062e56;
}
```

**Comment by wzup** [comment]
@jquense 
Nope, `className` doesn't work.

@colleenpurcell12 
What does that mean you have written? Is it possible to change CSS of a tooltip or not?
Your snippet doesn't work, BTW. Even if custom `.id` is set.

**Comment by colleenpurcell12** [comment]
I just checked how my app looks in the browser and that the JSX and the CSS I've provided in July still matches my code. I can verify that both the inner color and the arrow color are being set with this code.

**Comment by trops** [comment]
In case this wasnt clear you can use the className just replace the id selector in the example above from @colleenpurcell12 like so: 

```
<Tooltip className="my-tooltip" ... >
```

Styles
```
.my-tooltip > .tooltip-inner {
...
}

.my-tooltip > .tooltip-arrow {
...
}
```

**Comment by jrkoch** [comment]
I am using `react-css-modules` so the above didn't quite work for me as my CSS class names are generated at compile time.  I could still do it with attribute selectors, commenting here in case it helps anyone else:

```jsx
<Tooltip styleName="tooltip" ...>
```

```css
.tooltip [class$="inner"] {
  background-color: background-color;
  border: 1px solid background-color;
}

.tooltip [class$="arrow"] {
  border-top: 5px solid background-color !important;
}
```

**Comment by fabianstarke** [comment]
The easiest way to change the background color is to apply the `wrapperStyle` prop to `Tooltip`
```
  <Tooltip  wrapperStyle={{ backgroundColor: '#4A4A4A' }} />
```

**Comment by hsolg** [comment]
This works for me, but the contentStyle attribute is not documented:

`<Tooltip  contentStyle={{ backgroundColor: '#4A4A4A' }} />`

**Comment by andyliu-417** [comment]
> *Based on the example from the react-bootstrap docs https://react-bootstrap.github.io/components.html
> 
> `<Tooltip placement="top" className="in" id="tooltip-top">Tooltip top</Tooltip>`
> 
> The CSS to change the background color uses the default ids and classes of nested components that get rendered automatically--
> 
> ```
> #tooltip-top > .tooltip-inner {
>   background-color: #fff;
>   color: #000;
>   border: 1px solid #062e56;
> }
> 
> #tooltip-top > .tooltip-arrow {
>   border-top: 5px solid #062e56;
> }
> ```

now the classNames changed to "ant-tooltip-inner" and "ant-tooltip-arrow"

**Comment by jaypatel1307** [comment]
If you write your CSS inside component CSS file it'll not apply on your tooltip. Because tooltip is added in body root path. There are two ways for this situation.

1.  You have to add ViewEncapsulation in your component.

import { Component, ViewEncapsulation } from '@angular/core';

@Component({
  selector: 'my-app',
  templateUrl: './app.component.html',
  styleUrls: [ './app.component.css' ],
  encapsulation: ViewEncapsulation.None,
})
export class AppComponent  {
}

OR 

2. Write your css in Global css file, which were located in your project src > assets > css OR src > assets > styles.scss

**Comment by meetajhu** [comment]
For React Bootstrap 4

``.tooltip-inner {
  background-color: #fcd308 ;
  color: #000000;
}

.bs-tooltip-auto[x-placement^="bottom"] .arrow::before, .bs-tooltip-bottom .arrow::before{
	border-bottom-color: #fcd308;
}

.bs-tooltip-auto[x-placement^="top"] .arrow::before, .bs-tooltip-top .arrow::before{
	border-top-color:#fcd308 ;
}

.bs-tooltip-auto[x-placement^="left"] .arrow::before, .bs-tooltip-left .arrow::before{
	border-left-color: #fcd308;
}

.bs-tooltip-auto[x-placement^="right"] .arrow::before, .bs-tooltip-right .arrow::before{
	border-right-color: #fcd308;
}``

**Comment by scottyh527** [comment]
> In case this wasnt clear you can use the className just replace the id selector in the example above from @colleenpurcell12 like so:
> 
> ```
> <Tooltip className="my-tooltip" ... >
> ```
> 
> Styles
> 
> ```
> .my-tooltip > .tooltip-inner {
> ...
> }
> 
> .my-tooltip > .tooltip-arrow {
> ...
> }
> ```

The tooltip inner one was working for me but I wasn't able to change the background of the arrow, how is it that you go about changing it?

**Comment by aakashtm** [comment]
> Can anyone tell me any way to add custom background color to the tooltip component?


>   `<UncontrolledTooltip style={{ backgroundColor: "#4A7EFA" }}/>` 

And To style the arrow, we have to over ride the default styling by **reactstrap** in the css file

> `.bs-tooltip-auto[x-placement^="right"] span.arrow::before,
.bs-tooltip-right .arrow::before {
  border-right-color: #4a7efa;
}`

**Comment by DumasOlivier** [comment]
I've tried all the answers, I was able to change the bg color of the tooltip but not the arrow's bg color. The only solution that worked was the one of @aakashtm !
I guess you have to edit the code according to the placement of your Tooltip (top, right, left ...).
Thanks :) !

**Comment by rashid327** [comment]
.tooltip-inner {
    padding: 1rem 0.5rem !important;
    /* background-color: #013220 !important;  */
    font-weight: bold !important;
}

**Comment by hillangat** [comment]
.tooltip > div.tooltip-inner {
  background-color: @accentColor !important;
  color: @whiteColor !important;
}

.tooltip.show {
  opacity: 1 !important;
}

.tooltip > div.arrow::before {
  border-bottom-color: @accentColor !important;
  color: @whiteColor !important;
}

**Comment by Jay-Techify** [comment]
There is a arrowClassName which u can use to change the color of arrow of the ToolTip.
For eg <Tooltip  arrowClassName="tooltipArrow"  ..../>
and in css to change the color

 .tooltipArrow::before{
border-top-color: #554df0!important;
}

**Comment by agnjkafgh** [comment]
This worked for me (react-bootstrap 0.31.0

`React.js`
```
import { OverlayTrigger, Popover as BootstrapPopover } from 'react-bootstrap';
import './styles'

...

<BootstrapPopover className="customPopover" id="popover-positioned-left">
      ...
</BootstrapPopover>
````

`css`

```
.customPopover > .popover-content {
  background: white;
  ...
}
  
.customPopover > .arrow {
  visibility: hidden;
  ...
}
```

**Comment by mburakkalkan** [comment]
react-bootstrap 1.6.1

```
<Tooltip className="greenTooltip" ... >
```

```
.greenTooltip .tooltip-inner {
    background-color: green;
}

.greenTooltip .arrow::before {
    border-top-color: green;
}
```

**Comment by devanshu-jotwani** [comment]
> > In case this wasnt clear you can use the className just replace the id selector in the example above from @colleenpurcell12 like so:
> > ```
> > <Tooltip className="my-tooltip" ... >
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Styles
> > ```
> > .my-tooltip > .tooltip-inner {
> > ...
> > }
> > 
> > .my-tooltip > .tooltip-arrow {
> > ...
> > }
> > ```
> 
> The tooltip inner one was working for me but I wasn't able to change the background of the arrow, how is it that you go about changing it?

just add 
!important;
after the color you used

**Comment by nickfff-dev** [comment]
you can use react-tooltip props 

// Support <br /> to make explicitly multiline tooltip comments
multiline?: boolean;
  // Add 1px white border
  border?: boolean;
  // Popup text color
  textColor?: string;
  // Popup background color
  backgroundColor?: string;
  // Popup border color
  borderColor?: string;
  // Popup arrow color
  arrowColor?: string;

<ReactTooltip type = 'info' textColor="white" backgroundColor="#00755E"  arrowColor="white" />

**Comment by priyank32** [comment]
> In case this wasnt clear you can use the className just replace the id selector in the example above from @colleenpurcell12 like so:
> 
> ```
> <Tooltip className="my-tooltip" ... >
> ```
> 
> Styles
> 
> ```
> .my-tooltip > .tooltip-inner {
> ...
> }
> 
> .my-tooltip > .tooltip-arrow {
> ...
> }
> ```

add !important it not

**Comment by Casesight** [comment]
.tooltip.show{
opacity: 1 !important; 
}
worked for me

**Comment by shonenxnaifu** [comment]
If anyone still face this case, this solution worked for me.
I'm using react-bootstrap version 2.5.0. 
Just override SCSS variable for `tooltip` component, and both background and arrow will change to the color you want
```
$tooltip-bg: #000000;
$tooltip-color: #ffffff;
```

**Comment by dev-Laky** [comment]
You can just simply work with a class on the tooltip tag:

```tsx
<OverlayTrigger overlay={<Tooltip placement="top" className="custom-tooltip">{title}</Tooltip>}>
     <Button className="sign-up-btn" variant="warning">Click Me!</Button>
</OverlayTrigger>
```

Just refer to the class in your css file and use the inbuild bootstrap ccs property `--bs-tooltip-bg`:

```css
.custom-tooltip {
    --bs-tooltip-bg: var(--bs-danger);
}
```
