### ISSUE TITLE
Static modal?

### ISSUE THREAD

**Issue by glenjamin** [react-bootstrap/react-bootstrap#2082]
In the docs, there's an example of a static modal, but it uses some CSS that's only present in the docs site.

I'm using a [devcards](https://github.com/bhauman/devcards/) style approach to building components, so I'd quite like to build up my modal as a static component (using `Modal.Dialog`), and then drop it into the the real app with `<Modal dialogComponentClass={MyThing} />`.

Is there a way to make Dialog sit statically in the page without the custom CSS override used in the docs?

**Comment by taion** [comment]
Huh.

@jquense, do you know why it's set up such that `<ModalDialog>` is the `.modal` instead of the `.modal-dialog`? Seems like we could have it the other way around – i.e. render the `.modal` in `<Modal>`, and render only the `.modal-dialog` in `<ModalDialog>`. Or am I missing something?

**Comment by jquense** [comment]
i have no idea anymore...I think there is a reason tho

**Comment by taion** [comment]
Might be worth seeing what breaks and trying to fix it. @glenjamin?

**Comment by glenjamin** [comment]
When I get a bit more time I might have a look into that, for now I found the simplest approach has been:

```jsx
class MyDialog extends React.Component {
  render() {
    const Wrapper = this.props.static ? Modal.Dialog : "div";
    return (
      <Wrapper style={{position: static}}>
        <Modal.Header /> etc etc
      </Wrapper>
    )
  }
}

// Usage in modal
<Modal>
  <MyDialog />
</Modal>

// Usage for static demo
<MyDialog static />

```

**Comment by isaachinman** [comment]
@glenjamin When you say static here, do you mean the modal only mounts once?

I'm trying to setup a login modal that calls some external scripts when it mounts, but I've realised the standard react-bootstrap modal mounts _every time it opens_. So I need a way to have a modal mount and simply sit there and be shown/hidden without remounting. 

I would have thought that would be expected/default behaviour instead of mounting and unmounting over and over.

**Comment by glenjamin** [comment]
No, I mean a component which looks like the modal dialog but is not actually modal.

In your case I suggest having a parent component which takes care of that data.

**Comment by travisdahl** [comment]
@taion I just ran into the problem you mentioned above. Long story short, I'm trying to migrate some legacy code to use `react-bootstrap` and in my case I need the dialog without the overlay. I assumed that `Modal.Dialog` would just render from `.modal-dialog` down but it gives me the whole `.modal`. Did you ever find out why it was done that way?
