### ISSUE TITLE
What is the proper way to add a class to the Tabs' ul element?

### ISSUE THREAD

**Issue by nuclearspike** [react-bootstrap/react-bootstrap#2085]
I am using a set of style sheets that wrap bootstrap and add additional classes you can use with bootstrap components. However, when I added the class from these stylesheets to the Tabs component, in the DOM, it applied it to the wrapping <div>, not to the <ul> so the styles were not applied. Is there a proper way to add the class to the <ul> without resorting to DOM manipulation or alteration of the CSS? I couldn't find anything in the docs.

The best I've found so far is to do:
refToTabsComponent.refs.inner.refs.tabs.refs.ul.classList.add("nav-top-border")

But that's not ideal.

**Comment by jquense** [comment]
if you need finer tuned access to the sub components we suggest you use the lower level tab pieces instead of the Tabs component, in this case TabContainer,  and Nav.  see the tab example for custom layout in the documentation for more details
