### ISSUE TITLE
tabindex="-1": problem with live chats and modals

### ISSUE THREAD

**Issue by lailo-ch** [react-bootstrap/react-bootstrap#2086]
Hi there

I'm currently using Crisp.im to communicate with my users, but when I have a modal open, the chat text area does not work.

As soon as I remove the `tabindex="-1"` from the modal, it works perfectly. I tried other live chats and talked to a lot of support guys and they all told me that **tabindex** is a problem.

**Problem**
```
<div class="fade in modal" role="dialog" tabindex="-1" style="display: block;">
  // ..
</div>
```

An idea how to fix this?

Cheers
Lailo

**Comment by jquense** [comment]
why is tabIndex a problem? when a modal is open the modal and modal content is the only thing that can be focused, which is what a "modal" means.

**Comment by lailo-ch** [comment]
@jquense What if a user has problems inside the modal and needs live support?

**Comment by taion** [comment]
Then render the support popup inside the modal node. Or else disable `enforceFocus` on the modal.

**Comment by arundhati1213** [comment]
How can we remove it from react modal?

**Comment by arundhati1213** [comment]
<Modal
          show={loginForm}
          onHide={handleClose}
          backdrop="static"
          keyboard={false}
          size="lg"
          autoFocus="false" />
How can I remove the tabindex from here

**Comment by arundhati1213** [comment]
<Modal  backdrop="static"      keyboard={false}/>

**Comment by juanpabloxk** [comment]
@arundhati1213 I solved my problem setting the `enforceFocus` prop like this:

```javascript
<Modal
      show
      title="My modal"
      ...other props
      enforceFocus={false}
>
```
