### ISSUE TITLE
DropdownToggle doesn't define data-toggle="dropdown" attribute

### ISSUE THREAD

**Issue by baran25** [react-bootstrap/react-bootstrap#2089]
Even though dropdown menus work properly on the demo page they fail to close in our setup. If I click outside it - it closes, but when I click an item it stays open.
I googled for a solution and found this comment in bootstrap's issues list:
[https://github.com/twbs/bootstrap/issues/17537#issuecomment-138865803]

Now you can blame our setup of course, but surprisingly adding `data-toggle="dropdown"` to the `a` element rendered by DropdownToggle solves the issue.
I have two questions:
1) Is there a strong reason for not rendering `data-toggle="dropdown"` in DropdownToggle? If not should I submit a PR?
2) How can I diagnose our setup and see what causes dropdowns not to close?

**Comment by baran25** [comment]
It appears that some dropdowns do close, but I have a custom combo box (input and dropdown) which looks like this:
```jsx
const DropdownItem = React.createClass({
    render() {
        return (
            <ReactBootstrap.MenuItem>
				{this.props.item}
            </ReactBootstrap.MenuItem>
        );
    }
});

const Dropdown = React.createClass({
    render() {
        return (
            <ReactBootstrap.InputGroup.Button>
                <ReactBootstrap.Dropdown>
                    <ReactBootstrap.Dropdown.Toggle />
                    <ReactBootstrap.Dropdown.Menu className="pull-right">
                        {this.props.items.map((item, i) =>
                            <DropdownItem key={i} item={item} />
                        )}
                    </ReactBootstrap.Dropdown.Menu>
                </ReactBootstrap.Dropdown>
            </ReactBootstrap.InputGroup.Button>
        );
    }
});

const Combo = React.createClass({
    render() {
        return (
            <ReactBootstrap.InputGroup>
                <ReactBootstrap.InputGroup.Addon>
                    {this.props.addon}
                </ReactBootstrap.InputGroup.Addon>
                <ReactBootstrap.FormControl type="text" />
                <Dropdown items={this.props.items} />
            </ReactBootstrap.InputGroup>
        );
    }
});
```

Clicking a dropdown item doesn't cause dropdown to close.

**Comment by jquense** [comment]
you have to pass all the props to MenuItem,  it's no closing because the onSelect handler isn't being passed through from Dropdown item 

adding data-toggle to the dropdown only works because you also have the non-react bootstrap javascript on your page, that's unnecessary for react bootstrap and likely to cause issues

**Comment by baran25** [comment]
I missed that one! The issue is now fixed thanks to your explanation :smile:
