### ISSUE TITLE
<Input> element has some problem when I use it

### ISSUE THREAD

**Issue by swb2016** [react-bootstrap/react-bootstrap#2090]
`<Input type="checkbox" onTouchTap={checkInput} />`
When I check this Input, then the checkInput method will be checked twice.
I think this is a bug of react-bootstrap. Please tell me whether or not. And What can I do to fix it.

**Comment by jquense** [comment]
it's probably not a bug in RB since I put just uses the native inputs however the Input control is deprecated and been removed,  we suggest upgrading and using the FormControl components instead
