### ISSUE TITLE
FormControl componentClass="select" defaultValue doesn't work

### ISSUE THREAD

**Issue by throoze** [react-bootstrap/react-bootstrap#2091]
How can I set the default value for a `FormControl` component that has its `componentClass` set to `'select'`? For text `FormControl`s it works fine, but for select it wont work.

I tried setting `defaultValue` and `value` properties in `FormControl` component, but it just doesn't work, and also tried setting `selected` property in the corresponding `option` tag, but I got a warning that said I should use `defaultValue` or `value` properties instead, and eitherways the default value was not set.

Any suggestion?

**Comment by taion** [comment]
Works fine for me. Note that you need to set `value` on the `<option>`s.

**Comment by xyuae** [comment]
I have the same issue. @taion Why is the value necessary in <option>s? Is the defaultValue refer to the value in the option?

**Comment by taion** [comment]
That's just how `<select>` and `<option>` work in HTML.

**Comment by isherwood** [comment]
I have this problem as well. I was able to render a conditional option by passing in a default value on a generic property, but then it wasn't treated as a default with respect to validation. Here's what I have now:

```export const renderBootstrapSelect = (field) => {
    const renderOptions = (options) => {
        return options.map((i) => {
            return <option key={i.name} name={i.name} value={i.value}>{i.value}</option>;
        });
    };

    return (
        <FormGroup controlId={field.id}>
            <ControlLabel>{field.label}</ControlLabel>

            <FormControl componentClass="select" defaultValue={field.default} {...field.input}>
                {renderOptions(field.options)}
            </FormControl>

            {field.meta.touched && field.meta.error && <span className="red-text">{field.meta.error}</span>}
        </FormGroup>
    );
};
```

**Comment by crscaballero** [comment]
it's just me or this issue is still happening?

**Comment by AAlvarez90** [comment]
Still happening.

**Comment by AAlvarez90** [comment]
@crscaballero It's not happening any more. Set the `defaultValue` property on the `FormControl` element and make sure the property actually gets there. I had this issue and turns out the property was not getting down to the actual component. In addition, make also sure that the default value is compatible with the value in the `value` property of the `option` element

**Comment by LuuisPortugal** [comment]
I had this error with me when passing a String value to `option.value` and in `select.defaultValue` I passed a variable with the same string gave error. but when I used a boolean value instead of string it worked.

code with error:
`<Form.Control
                  as="select"
                  name="sg_sexo"
                  isInvalid={handleMessageError("sg_sexo")}
                  defaultValue={data.sg_sexo /*data.sg_sexo = "M"*/}
                  disabled={loadingCriarPessoa}
                  ref={register}
                >
                  <option value>SELECIONE</option>
                  <option value="M">MASCULINO</option>
                  <option value="F">FEMININO</option>
                </Form.Control>`

code with success:
`<Form.Control
                    as="select"
                    name="fl_status"
                    isInvalid={handleMessageError("fl_status")}
                    defaultValue={data.fl_status /*data.fl_status = true*/}
                    disabled={loadingCriarPessoa}
                    ref={register}
                  >
                    <option value={undefined}>SELECIONE</option>
                    <option value={true}>ATIVO</option>
                    <option value={false}>INATIVO</option>
                  </Form.Control>`

![image](https://user-images.githubusercontent.com/8116126/71595527-d02d5f80-2b1a-11ea-9b07-1d7e3f2b1896.png)

**Comment by wylanosorio** [comment]
Using `value` instead of `defaultValue` worked for me.

**Comment by meidikawardana** [comment]
> Using `value` instead of `defaultValue` worked for me.

thank you! you really saved me. this is crazy, the defaultValue doesn't work but value works.

**Comment by hosseindelara** [comment]
This way you can set the default value.



` <FormControl as="select" required onChange={hedelonCheng}   >

                    <option  >نوع مجتمع را انتخاب کنید</option>
                    {

                        dataoption.map(item => {

                            return <option key={item.Value} vlaue={item.Value} selected={defaultselect ? defaultselect == item.Value ? true : false : false}  >{item.Text}</option>
                        })
                    }

                </FormControl>`


You may receive an error in the console:
Warning: Use the `defaultValue` or `value` props on <select> instead of setting `selected` on <option>.

But setting `defaultValue` or` value` does not solve your problem

**Comment by Hug0Albert0** [comment]
> Using `value` instead of `defaultValue` worked for me.

That was the solution! Thank you!!!

**Comment by wgomg** [comment]
Having the same problem, setting `defaultValue` does nothing, setting `value` force me to manually add a handler for `onChange`, and directly setting `selected` on `options` warns about being preferable to use `defaultValue` or `value`.

**Comment by sageguy09** [comment]
This is still an issue. defaultValue does not show in the select box if <option> children are present. The first option is shown instead.

**Comment by kyletsang** [comment]
Works here?

https://codesandbox.io/s/smoosh-dawn-38tfg?file=/src/App.tsx

**Comment by amandadovel** [comment]
> @crscaballero It's not happening any more. Set the `defaultValue` property on the `FormControl` element and make sure the property actually gets there. I had this issue and turns out the property was not getting down to the actual component. In addition, make also sure that the default value is compatible with the value in the `value` property of the `option` element

This worked for me! I realized I needed to change my options being returned to uppercase letters to match that which was being called in the defaultValue. Hope this helps someone else!

**Comment by ValeLouvet** [comment]
Does not work here:
https://codesandbox.io/s/polished-paper-rr66zj
