### ISSUE TITLE
Panel or Collapsible default closed

### ISSUE THREAD

**Issue by oklas** [react-bootstrap/react-bootstrap#2092]
I try example of component Panel or Collapse from documentation. I change default to collapsed `{ open: false }` in constructor. Component appear as not collapsed. First click does nothing. Next clicks work as exected. So first rendering ignore state.

**Comment by taion** [comment]
That's not the prop. Check the docs.

**Comment by oklas** [comment]
I'd like to see panel collapsed and start. I take [Documentation example](http://react-bootstrap.github.io/components.html#panels-collapsible) and change true to false (marked below).  Button logic is inverted but panel is not collapsed at start. What's wrong? Which docs you mean to check? 

```
class Example extends React.Component {
  constructor(...args) {
    super(...args);
    this.state = {
      // open: true 
      open: false   // !!!
    };
  }
​
  render() {
    return (
      <div>
        <Button onClick={ ()=> this.setState({ open: !this.state.open })}>
          click
        </Button>
        <Panel collapsible expanded={this.state.open}>
          Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid.
          Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident.
        </Panel>
      </div>
    );
  }
}
​

```

**Comment by jquense** [comment]
@oklas that works fine for me...I changed the documentation to be false initially and it starts collapsed

**Comment by hemantnahar** [comment]
class Example extends React.Component {
  constructor(...args) {
    super(...args);
    this.state = {
      open: false
    };
  }

​   collapse = () => {
    this.state.open = true;
    this.setState(this.state);
    }

  render() {
    return (
        //If you ,ake this open by-defaut use 
        //<Panel header="my-title" defaultExpanded collapsible>
        // </Panel>
      <div>
        <Panel header="my-title" in={this.collapse} collapsible>
            Some words
        </Panel>
      </div>
    );
  }
}

:smiley: :+1:

**Comment by hemantnahar** [comment]
```class Example extends React.Component {
  constructor(...args) {
    super(...args);
    this.state = {
      open: false
    };
  }

​   collapse = () => {
    this.state.open = true;
    this.setState(this.state);
    }

  render() {
        //If you ,make this open by-defaut use 
        //<Panel header="my-title" defaultExpanded collapsible>
        
    return (
      <div>        
        <Panel header="my-title" in={this.collapse} collapsible>
            Some words
        </Panel>
      </div>
    );
  }
}
```

**Comment by srinik16** [comment]
Another way is 
`<Panel defaultExpanded={false} collapsible>`
