### ISSUE TITLE
React-bootstrap's using jQuery or not?

### ISSUE THREAD

**Issue by daiduongbian44** [react-bootstrap/react-bootstrap#2093]
Hi all,
I'm doing with React bases on ReactJS.NET, if i don't use PartialView&AJAX, React-bootstrap seems very nice, very good. It has some errors, however, when i render components in PartialView and then load views with AJAX. More details, example modal, when using PartialView&AJAX, I click into "Launch Modal" and see nothing changing, having no any actions. But if I render component into view directly, Modal is opened very smooth.
So i guess that react-bootstrap's using jQuery and when we load AJAX, the scripts which was placed in bootstrap.js file didn't run again.
Any ideas to solve this problem? I want to use PartialView&AJAX to improve loading time of pages.
Best & Regard.

**Comment by taion** [comment]
You can see from the deps that R-B does not have any jQuery dependency.

**Comment by daiduongbian44** [comment]
Yeah yeah, i see it, i re-read the react-bootstrap docs.
You have any ideas for my problem?
Tks.
