### ISSUE TITLE
Collapse doesn't work when top level child is a component

### ISSUE THREAD

**Issue by rhan-mentad** [react-bootstrap/react-bootstrap#2096]
The Collapse component does not work when the top level child element is a component. Maybe it's the way I have it defined (currently just a placeholder). Building with webpack and babel.
```
const AdvancedOptions = (props) => {
  return (
    <span>
      ADVANCED OPTIONS PLACEHOLDER
    </span>
  )
}
```
Wrapping it in a div works. If the div is not there then collapse doesn't work. Also replacing the component with the raw ```<span>``` code also works.
```
        <Collapse in={boolean}>
          <div>
            <AdvancedOptions/>
          </div>
        </Collapse>
```

**Comment by jquense** [comment]
it works fine with components but Collapse injects props to it's child and uses css animations via classes. your component needs to use them, specifically it need to pass the className to its node.

**Comment by rhan-mentad** [comment]
Works now, thanks!
