### ISSUE TITLE
React.PropTypes validation function warning.

### ISSUE THREAD

**Issue by SteveMellross** [react-bootstrap/react-bootstrap#2097]
It seems the latest React release (15.3.0) has caused a warning in regard to the use of PropTypes. See below.

> Warning: You are manually calling a React.PropTypes validation function for the `block` prop on `ButtonGroup`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.

Also triggered by:

- `justified` prop on `Nav`
- `divider` prop on `MenuItem`
- `id` prop on `Dropdown`

**Comment by mntbkr** [comment]
I have been seeing this with react 15.3.0 and react-bootstrap 0.30.0

- `value` prop on `Input`
-`onHide` prop on `Overlay`
-`block` prop on `ButtonGroup`

**Comment by taion** [comment]
We're working on it. Need an update to `uncontrollable`. Though note that there is no `<Input>` in R-B 0.30.0.

**Comment by mntbkr** [comment]
yup your right thats on me...I just upgraded to react-bootsrap 0.30.0 from 0.27.0 I am still used to seeing Input and thinking its react-bootsrtrap

**Comment by taion** [comment]
See https://github.com/react-bootstrap/react-bootstrap/pull/2095, BTW.

**Comment by microdou** [comment]
Also triggered by:
- `divider` prop on `MenuItem`
- `block` prop on `ButtonGroup`

**Comment by rmemoria** [comment]
I also found this warning in

`id` prop on `Tooltip`

**Comment by benmonro** [comment]
+1 on this we are seeing this as well in Overlay

**Comment by taion** [comment]
Track https://github.com/react-bootstrap/react-bootstrap/pull/2095.
