### ISSUE TITLE
Modal x close button displayed as "Ã—" 

### ISSUE THREAD

**Issue by hilafarmigo** [react-bootstrap/react-bootstrap#2098]
After npm install command I see in the ModalHeader.js that it is build with wrong character like this:
this.props.closeButton && _react2['default'].createElement(
        'button',
        {
          type: 'button',
          className: 'close',
          'aria-label': label,
          onClick: onHide },
        _react2['default'].createElement(
          'span',
          { 'aria-hidden': 'true' },
          'Ã—'
        )
This happens only on our linux production machine and not on osx.
Any chance you know how we can solve this issue?

**Comment by jquense** [comment]
make sure the meta tags on your tag are set to utf8

**Comment by alisman** [comment]
I have this problem too.  jquense I'm not sure what you mean.  Meta tag of HTML page?  This seems like a build issue.
