### ISSUE TITLE
deprecations warnings from React 15.0.3

### ISSUE THREAD

**Issue by chalda** [react-bootstrap/react-bootstrap#2100]
Switched from react 0.14.8 to 15.0.3 for the luls today started getting warnings about PropTypes of some React-bootstrap components such as: 

Warning: You are manually calling a React.PropTypes validation function for the `justified` prop on `Nav`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.

**Comment by taion** [comment]
Dupe other issues
