### ISSUE TITLE
Disable Modal Animation

### ISSUE THREAD

**Issue by L3V147H4N** [react-bootstrap/react-bootstrap#2102]
It would be useful if the Modal Component had a prop `animation` to indicate if the css transition should or should not run.

like:

```
<Modal
  show={true}
  animation={false}>
  <Modal.Body>
    <p>Processing...</p>
  </Modal.Body>
</Modal>
```

**Comment by taion** [comment]
Uhh it does. Please at least take a cursory glance in the docs before opening issues on the issue tracker.

**Comment by L3V147H4N** [comment]
Uff! sorry, I red it a few times :p I really missed it
