### ISSUE TITLE
Button bsStyle propType too much restrictive

### ISSUE THREAD

**Issue by jmfrancois** [react-bootstrap/react-bootstrap#2103]
I have defined custom btn styles 'btn-inverse' and 'btn-add' but when I'm using it with Button component I have a warning due to invalid propTypes.

AFAIK react-bootstrap is supposed to be bootstrap theme friendly.
bsStyle seems to offer only defined in the main theme.

```
warning.js:44Warning: Failed prop type: Invalid prop `bsStyle` of value `add` supplied to `Button`, expected one of ["success","warning","danger","info","default","primary","link"].
```

I think this is too much restricitve, we only should tests if we have a string.
Please tell me if I'm wrong.

**Comment by jquense** [comment]
we have both, check the custom styling section of the docs and the bootstrapUtils import. you can add you own style variants and have them be properly validated by the component as well
