### ISSUE TITLE
DropdownButton usage of `title` prevents usage of html tooltips

### ISSUE THREAD

**Issue by kromit** [react-bootstrap/react-bootstrap#2104]
DropdownButton uses `title` attribute as label for the toggle. Since `title` is a native HTML attribute for tooltips and accessibility, it should not be overridden by react-bootstrap. `Button` handles the `title` in the right way.

Is there a way to provide a naive html tooltip on a DropdownButton?

**Comment by taion** [comment]
Use the lower-level `<Dropdown>` component.

**Comment by kromit** [comment]
Yeah, I know that, but this was not my question. Was it discussed somewhere already? Very discouraging!

**Comment by taion** [comment]
There is not. It seems relatively uncommon to provide a `title` to a button with text, and it was the best name for the prop available.

It's only a few extra lines of code to use `<Dropdown>` and associated components; this is then how you get a dropdown button with an HTML title attribute on the toggle.
