### ISSUE TITLE
Navbar.Text unkown property warnings

### ISSUE THREAD

**Issue by muuki88** [react-bootstrap/react-bootstrap#2106]
Hi,

The [Navbar.Text](https://github.com/react-bootstrap/react-bootstrap/blob/master/src/Navbar.js#L169-L206) has still some unkown property warnings ( thanks for fixin all the others in #2044 , #2036 and co).

Simply create a `Nav` like this

```jsx
<Nav>
  <Navbar.Text>Some text</Navbar.Text>
</Nav>
```

which will log the following error

```
warning.js:44 Warning: Unknown props `active`, `activeKey`, `activeHref` on <p> tag.
Remove these props from the element. For details, see https://fb.me/react-unknown-prop
    in p (created by NavbarText)
    in NavbarText (created by Header)
```

We are using `0.30.1`.

**Comment by taion** [comment]
`<Navbar.Text>` doesn't go in a `<Nav>`. Check the example.

**Comment by Wilfred** [comment]
I bumped into this today. The relevant docs are: https://react-bootstrap.github.io/components.html#navs and https://react-bootstrap.github.io/components.html#navbars-text-link

Previously I had two elements that I wanted to pull right:

```jsx
<Navbar.Collapse>
    <MyWonderfulComponent/>
</Navbar.Collapse>

// MyWonderfulComponent:
    <Nav pullRight>
        <NavItem>foo</NavItem>
        <Navbar.Text>bar</Navbar.Text>
    </Nav>
```

I silenced the warning by changing `MyWonderfulComponent` to return:

```jsx
// MyWonderfulComponent:
    <div>
        <Nav pullRight>
            <NavItem>foo</NavItem>
        </Nav>
        <Navbar.Text pullRight>bar</Navbar.Text>
    </div>
```
