### ISSUE TITLE
request for individual browser bundles

### ISSUE THREAD

**Issue by conceptualspace** [react-bootstrap/react-bootstrap#2109]
when using react-bootstrap with npm, we can import just the modules we need, for example, `require('react-bootstrap/lib/Alert');`, which really helps manage the client bundle

however when using the minified browser library it includes all the components. is there a way to get a js file for use in the browser just for individual components as well?

**Comment by taion** [comment]
Use the `require` form and build your custom bundle using webpack.

**Comment by conceptualspace** [comment]
admit im new to webpack, but running `webpack source.js packed.js` just produced a huge js file that seems to contain everything.

#### source.js only contains:
 `menuitem = require('react-bootstrap').MenuItem;`

if you can steer me correctly its appreciated.. no worries if its beyond the scope of your support here

**Comment by taion** [comment]
You're supposed to use `/lib/` import.

**Comment by conceptualspace** [comment]
same result with

`menuitem = require('react-bootstrap/lib/MenuItem');`

**Comment by conceptualspace** [comment]
oic..
