### ISSUE TITLE
React 15.3.0 causes warnings for React Bootstrap

### ISSUE THREAD

**Issue by mikewli** [react-bootstrap/react-bootstrap#2110]
Components are forwarding props to rendering elements, causing a lot of warnings, especially if the UI is comprised of many react-bootstrap components.

Facebook details the warnings here:
https://facebook.github.io/react/warnings/unknown-prop.html
https://github.com/facebook/react/pull/7132

**Comment by mlandalv** [comment]
There are also warnings related to manually calling proptypes validation functions, eg:

    Warning: You are manually calling a React.PropTypes validation function for the `dismissAfter` prop on `Alert`. This is deprecated and will not work in the next major version.

More info here: https://facebook.github.io/react/warnings/dont-call-proptypes.html

**Comment by taion** [comment]
Dupe of a bunch of old issues. Please search before opening new issues.
