### ISSUE TITLE
<Navbar > with poor effect!!!!

### ISSUE THREAD

**Issue by alpha-one** [react-bootstrap/react-bootstrap#2111]
I want the Navbar to show like this:
![succcess](https://cloud.githubusercontent.com/assets/16613963/17394819/ad7c8ba0-5a5d-11e6-98d1-70492937069a.png)

but the code from "http://react-bootstrap.github.io/components.html#navs" work like this:
![error](https://cloud.githubusercontent.com/assets/16613963/17394852/d65bce6e-5a5d-11e6-8804-7c52a45669c2.png)

**Comment by jquense** [comment]
add the fluid prop
