### ISSUE TITLE
Multi-level dropdown

### ISSUE THREAD

**Issue by miau4** [react-bootstrap/react-bootstrap#2112]
Hi!

I want to build a multi-level dropdown with react-bootstrap but I couldn't find any documentation.

If you click on the dropdown it should open a wide dropdown list in which the links on the very left side can show some subcategory links on the right side of the dropdown.

Is this possible to implement with react-bootstrap? And if yes, how do I have to do this?

Thanks for your help.

**Comment by jquense** [comment]
bootstrap doesn't support "sub menus" in dropdowns and so neither does react bootstrap. you, I'm sure can do it with the lower level dropdown component and custom menus or at the very least custom css, but we don't know how specifically.

**Comment by brendensoares** [comment]
Just wanted to comment on how ridiculous it is not to support menu nesting. [To say that it doesn't have it's place in web dev](http://stackoverflow.com/a/18024991/143225) is ignoring any cursor based UI.

Very disappointing.

**Comment by dozoisch** [comment]
@brendensoares we are not responsible for choices taken by the Bootstrap team. The scope of the project is to be 100% on-par with Bootstrap.

**Comment by taion** [comment]
This discussion is no longer productive. Nested dropdown menus are not part of Bootstrap, and therefore they will not be part of React-Bootstrap.

This isn't the library of "everything you might need to build your website". It's the Bootstrap components wrapped up for React, with the attendant JavaScript logic.
