### ISSUE TITLE
React v15.0 warning: FormControl is changing a controlled input of type text to be uncontrolled.

### ISSUE THREAD

**Issue by redstrike** [react-bootstrap/react-bootstrap#2113]
> Warning: FormControl is changing a controlled input of type text to be uncontrolled. Input elements should not switch from controlled to uncontrolled (or vice versa). Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info: https://fb.me/react-controlled-components

I am new to React, and trying to improve the demo at [Thinking in React](https://facebook.github.io/react/docs/thinking-in-react.html) I wonder will this affects the original idea from that tutorial?

**Comment by jquense** [comment]
this warning is actually coming from React itself, not react-bootstrap (since form control uses the native inputs) it shouldn't affect the tutorial ideas. controlled inputs is another concept to learn
