### ISSUE TITLE
Warning on React.PropTypes validation

### ISSUE THREAD

**Issue by tonynd** [react-bootstrap/react-bootstrap#2119]
Hey guys!

So I am using several components from React-Bootstrap for a project and recently been getting a bunch of warnings about React.PropTypes validation function.

I took a small screenshot of some of the warnings I am getting (hope you guys can see it).
![image](https://cloud.githubusercontent.com/assets/9759347/17419850/3411be7e-5a54-11e6-964a-daa5c68e6f16.png)

I am not sure if I can fix this on my end, but any help would be appreciated. 

Thanks!

**Comment by taion** [comment]
Please search existing issues
