### ISSUE TITLE
Dynamic HelpBlock

### ISSUE THREAD

**Issue by Nift** [react-bootstrap/react-bootstrap#2121]
Is it possible to have a "dynamic" helpblock that changes text and colour depending on validationState?

If not I would appreciate such a feature unless there is a way to cirumvent creating a  new object.

**Comment by taion** [comment]
That's a concern of the your CSS, not of this library.

**Comment by Nift** [comment]
I am unsure how changing the text between the HelpBlock tags is a CSS issue? 
The workaround is pretty simple, while relatively ugly, unless I am doing something wrong.

**Comment by taion** [comment]
If you want to change the text, that's just a conditional in React. That's the point – it's just JavaScript.
