### ISSUE TITLE
Can't find elements beneath Modal for testing

### ISSUE THREAD

**Issue by leth** [react-bootstrap/react-bootstrap#2122]
I'm trying to make assertions about some elements I've got inside a modal dialog, but I can't get hold of a useful handle to let me find any of the elements.
I've found some refs and the `_modal` attribute, but they all seem to be the wrong kind of object.
I need to use the React test util methods, most of which only accept "composite" elements.

I suspect this was broken by 0771d964dd880ed6c487e0ba194feabdab9de3e7, but I might be wrong.

**Comment by taion** [comment]
Attach a ref yourself to whatever you're rendering inside the modal.

**Comment by leth** [comment]
Doh, thanks!

On 5 August 2016 16:58:19 BST, Jimmy Jia <notifications@github.com> wrote:
>Attach a ref yourself to whatever you're rendering inside the modal.
>
>---
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/react-bootstrap/react-bootstrap/issues/2122#issuecomment-237889687

-- 
Sent from my phone. Please excuse my brevity.
