### ISSUE TITLE
All tabs render function getting called at each change of a Tab

### ISSUE THREAD

**Issue by indraneelb1903** [react-bootstrap/react-bootstrap#2123]
I would like you guys to take a look at this and tell me is this a potential bug.
http://stackoverflow.com/questions/38688988/all-react-bootstrap-tabs-render-function-gets-called-every-time-regardless-of-wh

**Comment by taion** [comment]
Yes they should. React renders entire subtrees.

**Comment by indraneelb1903** [comment]
Any particular reason for that to happen?
Cause as i mentioned in my stack-overflow post, if the content in each tab is significant, this affects performance, and makes our ui slow.

**Comment by taion** [comment]
See https://facebook.github.io/react/docs/advanced-performance.html.

**Comment by indraneelb1903** [comment]
Fair enough!
