### ISSUE TITLE
Where is ButtonInput?

### ISSUE THREAD

**Issue by ir-fuel** [react-bootstrap/react-bootstrap#2125]
I am using version 0.30.2, and it seems `ButtonInput` is gone?
I don't find anything about it in the `CHANGELOG.md` document, so can someone tell me what's going on? It's not (or no longer?) in the docs either.

**Comment by taion** [comment]
It was deprecated along with `<Input>` in v0.29.0 and removed in v0.30.0: https://github.com/react-bootstrap/react-bootstrap/blob/master/CHANGELOG.md#v0290
