### ISSUE TITLE
Popover props

### ISSUE THREAD

**Issue by bcarroll22** [react-bootstrap/react-bootstrap#2126]
Not sure what other things this may happen on, but I noticed you're spreading the props for the `Popover` component after you assign the custom props, so they get overwritten. This needs to be changed to:

```
const outerStyle = {
  ...style,
  display: 'block',
  top: positionTop,
  left: positionLeft,
};
```

**Comment by taion** [comment]
That's intentional. We _want_ explicit user-supplied styles to override the ones that we specify.

**Comment by bcarroll22** [comment]
I understand, but what I'm saying is that right now that's not what happens
right now. If you put the spread after the user-supplied stuff, the spread
overwrites them. He spread has to be the first thing in the object not the
last if you want the behavior you're expecting.

**Comment by taion** [comment]
Read that code again. `style` there is from `props`, i.e. it's the user-specified one.
