### ISSUE TITLE
How can I bring out `closeButton` in a modeless dialog?

### ISSUE THREAD

**Issue by ryerh** [react-bootstrap/react-bootstrap#2127]
The following example code is taken from the official documentation.
``` javascript
const modalInstance = (
  <div className="static-modal">
    <Modal.Dialog>
      <Modal.Header closeButton> // NOTICE THE closeButton PROP I ADDED HERE!
        <Modal.Title>Modal title</Modal.Title>
      </Modal.Header>

      /****/
    </Modal.Dialog>
  </div>
);
```

It can't render correctly because `Modal.Header` will find `onHide` from it's [`context`](https://github.com/react-bootstrap/react-bootstrap/blob/master/src/ModalHeader.js#L52), which is provided by the [`Model`](https://github.com/react-bootstrap/react-bootstrap/blob/master/src/Modal.js#L138-L144) component.

How can I get a simple modeless dialog with close button?
Can anyone enrich the official docs by adding a example demonstrating how to achieve this?

**Comment by ryerh** [comment]
The solution I take now is using custom style to override default css, like the following:
``` javascript
const modalInstance = (
  <div className="static-modal">
    <Modal bsStyle="modeless">
      <Modal.Header closeButton>
        <Modal.Title>Modal title</Modal.Title>
      </Modal.Header>

      /****/
    </Modal>
  </div>
);
```

then override styles associated with `modeless` HTML elements.

**Comment by taion** [comment]
Seems fine. Alternatively, you can export the context yourself. Those dialogs right now really aren't set up to be used statically. Track that on https://github.com/react-bootstrap/react-bootstrap/issues/2082.
