### ISSUE TITLE
Access to the <ul> tag in a DropDownButton

### ISSUE THREAD

**Issue by mikeengland** [react-bootstrap/react-bootstrap#2130]
It would be useful to be able to apply CSS classes/styles to the <ul> tag the DropDownButton generates. For example, in the case of applying CSS to enable a scrollable dropdown to be used. Is there no current way of doing this?

Thanks!

**Comment by taion** [comment]
Either use `<Dropdown>` or use something like `.my-dropdown > ul`.

**Comment by mikeengland** [comment]
Works perfectly with <Dropdown>, thanks! It was a bit hidden in the documentation.
