### ISSUE TITLE
i can't use aria-expanded in Panel 

### ISSUE THREAD

**Issue by tomlelouch** [react-bootstrap/react-bootstrap#2132]
Hello,
when i update react-boostrap, the icon disappeared.
![image](https://cloud.githubusercontent.com/assets/5998190/17550741/032e6a12-5f29-11e6-99f0-f757646721e6.png)
![image](https://cloud.githubusercontent.com/assets/5998190/17550750/18ddb1ec-5f29-11e6-8026-4d6121890677.png)

in v0.30.2:
```  javascript
if (!React.isValidElement(header)) {
      return (
        <h4 role="presentation" className={titleClassName}>
          {this.renderAnchor(header, id, role, expanded)}
        </h4>
      );
    }
```
why don't you passing expanded  parameter to renderAnchor function？

**Comment by taion** [comment]
Fixed in https://github.com/react-bootstrap/react-bootstrap/pull/2133

**Comment by tomlelouch** [comment]
ok thanks
