### ISSUE TITLE
Popover placement on wrong location when using Component in overlay

### ISSUE THREAD

**Issue by tayyabshabab** [react-bootstrap/react-bootstrap#2138]
I have prepared a CustomComponent which returns the popover

> CustomComponent
`
      <Popover id="notificationPopover">
          <h4>Notifieringar</h4>
      </Popover>
`

I use the above CustomComponent in the overlay like this
`<OverlayTrigger  trigger="click" placement="bottom" overlay={<CustomComponent />} rootClose><Button>Login</Button></OverlayTrigger>`

The problem is it loads the Popover on the top left section of screen. It works fine if I write the Popover JSX in the same component. However I need to use this popover on several places. Can anyone please help with this?

**Comment by jquense** [comment]
you need to spread the props through to the Popover component from you CustomComponent

```jsx
<Popover {...this.props} id="notificationPopover"> <h4>Notifieringar</h4> </Popover>
```

**Comment by bmueller-sykes** [comment]
Might I humbly suggest adding an example of this in the docs?

**Comment by jquense** [comment]
PR's welcome :)

**Comment by bmueller-sykes** [comment]
well played
