### ISSUE TITLE
Accordion Panel .collapsed class and aria attributes missing 

### ISSUE THREAD

**Issue by NerdCowboy** [react-bootstrap/react-bootstrap#2140]
When passing a string to the Panel header like the following. (in an `<Accordion>`)
```
<Panel header="Test" eventKey="1">
  panel 1 contents
</Panel>
```

The output html seems to be correct:
```
<div class="panel-heading">
  <h4 role="presentation" class="panel-title">
    <a role="tab" aria-expanded="false" aria-selected="false">Test</a>
  </h4>
</div>
```

However, if I try to pass some custom html in the header like this:
```
<Panel header={<h5>Test</h5>} eventKey="1">
  panel 1 contents
</Panel>
```

The output html aria attributes gets changed to this:
```
<div class="panel-heading">
  <h5 class="panel-title">
    <a href="#tab" aria-controls="tab">Test</a>
  </h5>
</div>
```

As you can see, on the `<a>` the `aria-expanded` and `aria-selected` get dropped from the anchor.

Furthermore, there used to be the class `.collapsed` on the `<a>` that allowed me to style active and inactive states of the panel header. Right now, I'd have to rely on the aria attributes, which isn't really ideal.

**Comment by taion** [comment]
https://github.com/react-bootstrap/react-bootstrap/issues/2132, fixed on master
