### ISSUE TITLE
I Think 'ProgressBar' Has minWidth Issue

### ISSUE THREAD

**Issue by uyu423** [react-bootstrap/react-bootstrap#2142]
related #1574 #1639 

```jsx
import React from 'react';
import { ProgressBar } from 'react-bootstrap';

class Item extends React.Component {
  render() {
    const style = {
      midWidth : 30
    }
    return(
      <ProgressBar style={style} now={0}/>
    );
  }
}

export default Item;
```

* rendering result
![image](https://cloud.githubusercontent.com/assets/8033320/17649189/11c2cad0-6269-11e6-8150-612d73f16238.png)

* rendering html
```html
<div class="progress" style="min-width: 30px;">
  <div role="progressbar" class="progress-bar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%;"></div>
</div>
```

I think that the `min-width` style of `.progress` div should go to `.progressbar` div.
* modified html
 ```html
<div class="progress">
  <div role="progressbar" class="progress-bar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%; min-width: 30px;"></div>
</div>
```

* modified html render()
![image](https://cloud.githubusercontent.com/assets/8033320/17649211/c5be52e8-6269-11e6-8540-3f0dfdd69d3c.png)

**Comment by taion** [comment]
Use

```jsx
<ProgressBar>
  <ProgressBar style={{ minWidth: 30 }} />
</ProgressBar>
```

**Comment by jkclark** [comment]
> Use
> 
> ```js
> <ProgressBar>
>   <ProgressBar style={{ minWidth: 30 }} />
> </ProgressBar>
> ```

This seems to be the correct way to do this, but it's not shown in the documentation. I would have expected to see this [here](https://react-bootstrap.netlify.app/docs/components/progress/#:~:text=For%20low%20percentages%2C%20consider%20adding%20a%20min%2Dwidth%20to%20ensure%20the%20label%27s%20text%20is%20fully%20visible). In any case, thanks for posting it here!
