### ISSUE TITLE
Can someone help me add a new component?

### ISSUE THREAD

**Issue by nurulc** [react-bootstrap/react-bootstrap#2145]
Hi,

I have created a new component [RxInput](https://github.com/nurulc/react-rxinput) - there is a [demo](https://nurulc.github.io/). I would love to know if the project is interested interested in incorporating this component. It would be wonderful if some in the community could check it out and let me know what you think.

**Comment by jquense** [comment]
Hi there, thanks for the interest. Your input looks cool, unfortunately this project is concerned with matching the normal twitter bootstrap, so we don't include or support any extra components. 

If you are interested in getting the word out, check out sites like react.rocks and react.parts which curate components

**Comment by nurulc** [comment]
Thanks,
Now I understand the scope of you project. Thanks for the tip. Best Wishes Nurul 

    On Monday, August 15, 2016 10:44 AM, Jason Quense <notifications@github.com> wrote:
 

 Hi there, thanks for the interest. Your input looks cool, unfortunately this project is concerned with matching the normal twitter bootstrap, so we don't include or support any extra components. If you are interested in getting the word out, check out sites like react.rocks and react.parts which curate components—
