### ISSUE TITLE
Resolve tension between componentClass and type props of FormControl

### ISSUE THREAD

**Issue by akarve** [react-bootstrap/react-bootstrap#2150]
The type of a FormControl is spread across two properties: `type=` and `componentClass=`. As a result, dynamically returning varying types of FormComponents from a single component is cumbersome and requires the developer to have two separate codepaths for instances of the same `FormControl` class. Granted `textarea` and `select` are not implemented as `<input>` but then what is the purpose of exposing all three as `FormControl`s?

Ideally `FormControl.type=` would take any one of `[text, textarea, select, email, ...]`

**Comment by taion** [comment]
The point of exposing them as `<FormControl>` is to offer a consistent component that applies Bootstrap styling, and automatically sets up a11y handling when using `<FormGroup>` and `<ControlLabel>`.

If you need to wrap up `<FormControl>` to expose a single prop for configuring what to show, you're free to do so – we want to minimize the API surface area there and not try to paper over real differences in the underlying component use.
