### ISSUE TITLE
Focusing to the FormControl

### ISSUE THREAD

**Issue by cubbuk** [react-bootstrap/react-bootstrap#2153]
How can I focus to `FormControl` component programatically, the following does not work:

```
focusToInput() {
        //I can't reach input component, thus focus function does not exist, any idea how to solve?
        if(this.inputNode && this.inputNode.focus instanceof Function){
            this.inputNode.focus();
        }
    }
<FormControl {...otherProps}
                         name={name}
                         ref={node => this.inputNode = node}
                         bsClass={formControlClass}
                         onBlur={this.onInputBlurred.bind(this)}
                         onFocus={this.onInputFocused.bind(this)}
                         onChange={this.onInputChanged.bind(this)}/>
```

**Comment by jquense** [comment]
you can use `findDOMNode` on the ref

**Comment by cubbuk** [comment]
Thanks @jquense the following worked:

```
focusToInput() {
        let node = ReactDOM.findDOMNode(this.refs.inputNode);
        if (node && node.focus instanceof Function) {
            node.focus();
        }
    }

<FormControl name={name}
                         ref="inputNode"
                         bsClass={formControlClass}
                         onBlur={this.onInputBlurred.bind(this)}
                         onFocus={this.onInputFocused.bind(this)}
                         onChange={this.onInputChanged.bind(this)}
                         {...otherProps}/>
```

**Comment by jquense** [comment]
proTip: you can also make use of `autoFocus` which react implements cross-browser to focus something when it mounts.

**Comment by ThomasVuillaume** [comment]
Better to use autoFocus indeed, as @jquense said, because [eslint](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-find-dom-node.md) is now seeing findDOMNode as error. It's mainly because Facebook will eventually deprecate it.

**Comment by CodeAmend** [comment]
What if you you have 7 inputs and they are controlled components. Each time you type, you lose focus. autoFocus on each of these works as I suspected and the last input on the list gets focussed after a single keystroke on ANY of the other inputs.

**Comment by jquense** [comment]
You've got something wrong if your inputs lose focus after each keystroke that's not normal behavior for controlled inputs

**Comment by neosavvy** [comment]
@CodeAmend did you ever figure out what you had "wrong" when using controlled components. 

I'm assuming you were doing something like this onChange: 

```
handleUpdateState = (property, value) => {
        console.log('propertyToUpdate: ', property);
        console.log('valueToUpdate: ', value);
        this.props.dispatch(updateActiveUserProperty(property, value))
    };
```

ie, letting your store handle the state of an in-process edit form. I'm trying to do the same and seeing the same behavior in that my fields lose focus on each keystroke. I'm trying to avoid my "dumb-component" / "presentational" component from having to maintain any state as that kind of breaks the whole point of having stateless components. 

I'd be curious how folks accomplish this without maintaining state as a user types.
