### ISSUE TITLE
Manually calling a React.PropTypes validation function

### ISSUE THREAD

**Issue by zatziky** [react-bootstrap/react-bootstrap#2154]
After upgrading my project after coming back to it after 2 weeks I receive lots of warning I can't get rid of:

> warning.js:44 Warning: You are manually calling a React.PropTypes validation function for the `onClick` prop on `NavbarToggle`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. 
> 
> warning.js:44 Warning: You are manually calling a React.PropTypes validation function for the `onClick` prop on `NavItem`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. 

I have found [a similar question][1] for **react-native** where the answers suggest to upgrade dependent libraries versions. I have done so but it didn't no help...

I have looked into [the issues on github][2] but there ain't a similar one.

How can I correct my app and dismiss the warnings?

  [1]: http://stackoverflow.com/questions/38690502/manually-calling-a-react-proptypes-validation-react-native-0-30-0
  [2]: https://github.com/react-bootstrap/react-bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by jquense** [comment]
try removing node_modules completely and reinstalling, using the latest version

**Comment by zatziky** [comment]
I did so... It didn't work however. I've replaced all react related goodies with **latest**


```
    "react": "latest",

    "react-bootstrap": "latest",

    "react-dom": "latest",

    "react-redux": "latest",

    "react-router": "latest",

    "react-router-bootstrap": "latest",

```

The version are now:

- react@15.3.0
- react-bootstrap@0.30.2

**Comment by zatziky** [comment]
In turned out that the problem was hidden somewhere else. 

In the code I was using a component `<NavigationHeader>`. It was originally defined as

    const NavigationHeader = () => {
        return (
            <Navbar>
                  ...
            </Navbar>
        );
    }
    
    export default NavigationHeader;

Inspecting my code it was the only component that was different from the rest. I changed the definition to a subclass of **React.Component** and it started to work.

    class NavigationHeader extends React.Component {
        render()
            return (
                <Navbar>
                      ...
                </Navbar>
            );
        }
    }
    
    export default NavigationHeader;
