### ISSUE TITLE
Animation doesn't work on custom overlay?

### ISSUE THREAD

**Issue by jwyuen** [react-bootstrap/react-bootstrap#2155]
It looks like if you use a custom overlay as per the documentation (https://react-bootstrap.github.io/components.html#custom-overlays-overlay), the animations don't work?  I'm not sure if this is intended behavior or not and if the custom component needs to implement something special to be able to have animations.

I wonder if that's the case because when I substitute the custom component with something like the Tooltip component the animations do work....

**Comment by taion** [comment]
You need to accept the styling props injected down from the animation management components, as well as have proper CSS styling to render the animation states.

**Comment by jwyuen** [comment]
Ah I see - thanks for the quick response!
