### ISSUE TITLE
OverlayTrigger with rootClose. Make it easier to suppress rootClose if needed.

### ISSUE THREAD

**Issue by larrydahooster** [react-bootstrap/react-bootstrap#2157]
I am facing a problem with OverlayTrigger with rootClose=true. I am spawning a Modal from within a PopOver.  The PopOver gets triggered by an OverlayTrigger.

I used to set the PopOver as the Modal's container and the rootClose event was suppressed whenever I interacted with the Modal because it was recognized as a child of the PopOver. 

I don't want to go too much into detail, but I refactored the ModalHandler and dispatch it now via redux. The problem is that I can't put the reference to the container onto the store. [See discussion here](https://github.com/reactjs/redux/issues/1248). So for simplicity lets just assume that I can't set the container for the Modal. The PopOver now closes whenever I interact with the Modal.

So I was looking for different ways to take control over the rootClose behavior. 

My first idea was to control the rootClose prop and set it to false whenever I spawn a modal. But this causes the PopOver to flicker because it disappears and appears again, because it triggers the animation. But I can't disable the animation, because I rely on the hooks onEnter/onExit. They only get triggered when animation=true.

I took a deeper look into the OnRootCloseWrapper and saw that it already has a prop to disable the onRootClose event. https://github.com/react-bootstrap/react-overlays/blob/v0.6.6/src/RootCloseWrapper.js#L136

And also a prop to inject an onRootClose handler via props. https://github.com/react-bootstrap/react-overlays/blob/v0.6.6/src/RootCloseWrapper.js#L130

Sadly both props are not going down the prop-chain and never reach the OnRootCloseWrapper.
Wouldn't it make sense to at least pass the disable prop down the prop chain? 

Can you help me here with some advice? Am I missing a point?

**Comment by larrydahooster** [comment]
I identified the problem of the flickering and it is also relates to the lazily added RootCloseWrapper. When you toggle rootClose while the Popover is open it gets unmounted and mounted again which triggers the css transition.

This issue is not related to react-bootstrap but to react-overlays and I link to a similar thread dealing with RootCloseWrapper problems: https://github.com/react-bootstrap/react-bootstrap/issues/1808

**Comment by geoffreyhale** [comment]
Similar issue for me.  I am facing a problem with an Overlay with rootClose=true.  I am spawning a Modal from within a Popover (Modal is descendant, not immediate child).  The Popover gets triggered by an Overlay.  The rootClose event on the Overlay is _not_ surpressed when I interact with the descendant Modal.  I want/expect interactions with descendants (including the Modal) to not trigger rootClose.

This behavior appears similar to #1808 suggesting in this case an Overlay behaves more like a Dropdown than an OverlayTrigger, something about re-mounting causing issue with descendant Modal.

Aside, inspecting the resulting DOM tree, the Modal does not appear to be a descendant of the Popover.  Is this expected?  Or perhaps I need to explicitly set Modal container as the Popover?

**Comment by geoffreyhale** [comment]
**Original**: Modal as descendant of Popover.
```
<Overlay rootClose=true>
    <Popover>
        <ComponentX />
    </Popover>
</Overlay>
```
* ComponentX contains `<ModalWrapper />`.
* ModalWrapper contains `<Modal />`.

Behavior:
Clicking in Modal closes Popover and all contents including Modal.

------
**Alternative A:** Modal (and siblings) as child(ren) of Popover.
```
<Overlay rootClose=true>
    <Popover>
        <ComponentX />
        <ModalWrapper />
    </Popover>
</Overlay>
```
Behavior:
Clicking in Modal closes Popover and all contents including Modal. (same as above)

------
**Alternative B:** Modal outside (as sibling) of Overlay.
```
<Overlay rootClose=true>
    <Popover>
        <ComponentX />
    </Popover>
</Overlay>
<ModalWrapper />
```
Behavior:
Clicking in Modal closes Popover but Modal remains open.

---
Desired behavior:
* Clicking outside of Modal closes Modal.
* Click outside of (Popover or Modal) closes Modal.
* Clicking in Modal does not close Popover or Modal.

**Comment by jquense** [comment]
@geoffreyhale Unfortunately there isn't any way to do in a general way. Modals must be be appended outside the DOM element of the popover in order to work correctly. My suggestion is you implement your own rootClose behavior that checks if the targets of the click events are what you expect.

**Comment by geoffreyhale** [comment]
Thanks, @jquense.

I've been considering the potential value of a "`root` prop".  It would extend the versatility of `rootClose`.  rootClose fires event when we click outside the component itself, but there may be value in being able to specify an alternate node/component, like a parent component, like a Tab.  Rough example, we could specify `root=TabA`.  The resulting behavior would be that rootClose only fires when we've clicked outside TabA.

**Comment by jquense** [comment]
that is an interesting thought, but it wouldn't actually help you here. If you look at the markup the reason this doesn't work is that the Popover and Modal are appended to the document body, they aren't descendants of each other

**Comment by victsant** [comment]
Did anyone ever figure out the working around for this issue? I am having the same modal / popover issue.
