### ISSUE TITLE
Pagination component bug

### ISSUE THREAD

**Issue by intpp** [react-bootstrap/react-bootstrap#2159]
![](https://api.monosnap.com/rpc/file/download?id=jfqQPtze5tAHI3gWPRYe2In1LgMp1I)

Total pages: 18, current page: 15.
Component renders [ 15 ] [ 16 ] [ 17 ] ... [ 18 ]

Same issue when current page is 4, component renders: [ 1 ] ... [ 2 ] [ 3 ] [ 4 ]

React bootstrap version: 0.30.2

**Comment by kevinzwh** [comment]
Found is causing this! The calculation for both`startpage` & `hasHiddenPagesAfter` have off by one errors that cause the ellipses to display when they shouldn't be.

I'll open a PR for the solution to this issue in a moment
