### ISSUE TITLE
Is it possible to force a modal to stay mounted?

### ISSUE THREAD

**Issue by isaachinman** [react-bootstrap/react-bootstrap#2160]
So, I am starting a new application and it's my first time working with react-bootstrap. 

The first thing I did was to build a login modal, which uses [react-facebook-login](https://www.npmjs.com/package/react-facebook-login) and [react-google-login](i.abroadwith.com). Presumably, both of these components make external API calls upon mounting.

So, I threw these two components into my modal and went along my way. Then I noticed these external Facebook and Google scripts were getting loaded into a page multiple times, because the modal was _unmounting and mounting every time it was hidden/shown_. To me that seems very counterintuitive; I would expect the markup to remain in place and merely animate it's display/visibility on the `open` prop.

Regardless, I need a way to produce a modal that _mounts once_ and subsequently hides/shows itself without remounting. Is this possible with react-bootstrap in any capacity? I'd hate to have to go back to material-ui just for a modal.

**Comment by taion** [comment]
Disable `unmountOnExit`. Generally modals are supposed to unmount when hidden though.

**Comment by isaachinman** [comment]
@taion That prop does nothing for the modal component. I see it in the docs for tabs, though.

**Comment by artygrand** [comment]
We a really need keepMounted prop for temporary hidden modal.
