### ISSUE TITLE
(Working) Button-styled radio inside button group / ButtonGroup with radios

### ISSUE THREAD

**Issue by xxRockOnxx** [react-bootstrap/react-bootstrap#2161]
I don't know what others are complaining about this but it is working for me

```
    <ButtonGroup justified data-toggle="buttons">
       <label className="btn btn-default">
         <i className="fa fa-fw fa-male"></i> Male
         <input type="radio" name="gender" value="male" />
       </label>

       <label className="btn btn-default">
         <i className="fa fa-fw fa-female"></i> Female
         <input type="radio" name="gender" value="female" />
       </label>
      </ButtonGroup>
```

NOTE: data-toggle="buttons" is required on the ButtonGroup to apply the style from the Bootstrap which makes the radio button invisible.

**Comment by taion** [comment]
This isn't an issue. Also, the point of https://github.com/react-bootstrap/react-bootstrap/issues/1587 is to have first-class component support here.
