### ISSUE TITLE
Panel collapse without animation

### ISSUE THREAD

**Issue by mfeuermann** [react-bootstrap/react-bootstrap#2163]
Hello,

first of all, thanks for React Bootstrap!
I have one question, Is it possible collapse panels without animation ?

I didnt found that in docs.
Im able to do that with my own code but i think that will be useful... 

Thanks

**Comment by taion** [comment]
Collapsing is implemented via the collapse animation. You can modify the CSS there as needed to remove the visual animation, but right now they're directly coupled.
