### ISSUE TITLE
Modal works with fine version 0.28.1 but breaks with version 0.30.3

### ISSUE THREAD

**Issue by danielehrlich** [react-bootstrap/react-bootstrap#2164]
Hi All:

If you look at this example on CodePen ((old version of React-Bootstrap))[https://codepen.io/top19/pen/jAoNzB], you'll notice that you can click the "Add Recipe" at the bottom to open a Modal.

If you look at this second example ((new version of React-Bootstrap)[https://codepen.io/top19/pen/kXdNEv], which is identical in every way to the first, you are not able to open the Modal by clicking "Add Recipe".

The only difference between the two repos is the version of React-Bootstrap they are using. The working one uses 0.28.1 and the broken one uses version 0.30.3. Perhaps I am missing something, but I couldn't find anything online that showed someone else had a similar issue with non-working Modals. 

Does anyone know why I am getting this behavior? These examples were all forked from a coding lesson project, and looking through the code I can't see anything that looks wrong with it. The issue remains whether I test in Safari or Chrome.

Is React-Bootstrap known to not be backwards-compatible with certain earlier versions?

**Comment by taion** [comment]
By convention, bumps to the first non-zero version (in this case from 0.28 to 0.30) will include breaking changes. We keep a changelog that details everything that does change.

I'd recommend running your CodePen with the unminified code and looking at which exceptions you get.
