### ISSUE TITLE
Is this library compatible with React 15.x.x?

### ISSUE THREAD

**Issue by isaachinman** [react-bootstrap/react-bootstrap#2166]
I am spinning up a new React project, and used ncu to update all my deps to their latest versions.

Seeing a _lot_ of breaking errors coming from react-bootstrap when using React 15.3.1. Is it safe to assume this library only works with 14.x?

**Comment by isaachinman** [comment]
Sorry, should have searched closed issues first.

**Comment by dozoisch** [comment]
Hi! Yes it's compatible and none of the thing you saw 15.3.1 we're breaking errors. They are warnings. They've all been fixed in the latest version of RB.
