### ISSUE TITLE
pullRight on Dropdown doesn't work

### ISSUE THREAD

**Issue by AnderssonChristian** [react-bootstrap/react-bootstrap#2167]
I have the following jsx:

```
<Dropdown id={"cm_" + id} pullRight>
   <Dropdown.Toggle noCaret></Dropdown.Toggle>
   <Dropdown.Menu>
      <MenuItem onClick={this.foo}>Foo</MenuItem>
      <MenuItem onClick={this.bar}>Bar</MenuItem>
   </Dropdown.Menu>
</Dropdown>
```

This generates the following markup:

```
<div class="pull-right dropdown btn-group">
   <button id="cm_56" role="button" aria-haspopup="true" aria-expanded="false" type="button" class="dropdown-toggle btn btn-default"></button>
   <ul role="menu" class="dropdown-menu dropdown-menu-right" aria-labelledby="cm_56">
      <li role="presentation" class="">
         <a role="menuitem" tabindex="-1" href="">Foo</a>
      </li>
      <li role="presentation" class="">
         <a role="menuitem" tabindex="-1" href="">Bar</a>
      </li>
   </ul>
</div>
```

However, the `dropdown-menu-right` does not apply any styles, as if such class doesn't exist.
If I replace it with the deprecated `pull-right` class however, it works.

I've looked for a while now and I cannot find what the possible cause may be. Perhaps I'm missing something, but it seems to me like a bug in react-bootstrap?

**Comment by jquense** [comment]
you may have an older version of the bootstrap css

**Comment by AnderssonChristian** [comment]
I did upgrade all bootstrap files, but the problem persisted. Turns out I had to restart Chrome for it to work, presumably for the cache to clear. I should've realized sooner as it's not the first time I've had to do that. Thank you though.
