### ISSUE TITLE
MS Edge ignores(?) click on the Tabs

### ISSUE THREAD

**Issue by eXtremeX** [react-bootstrap/react-bootstrap#2168]
Hi all,
I'm using react-bootstrap to display tabs among the other things. This is the code I'm using:
```
<Tabs activeKey={this.state.key} onSelect={this.handleSelect.bind(this)} id="uncontrolled-tab-example">
    <Tab eventKey={0} title="TAB-01">
        <Another React Component />
    </Tab>
    <Tab eventKey={1} title="TAB-02">
        <Another React Component />
    </Tab>
    <Tab eventKey={2} title="TAB-03">
        <Another React Component />
    </Tab>
    <Tab eventKey={3} title="TAB-04">
        <Another React Component />
    </Tab>
</Tabs>
```

The tabs are rendered on the page of the URL: localhost:3000/form

It works fine in both Chrome and Firefox, upon clicking on the tab name, that particular tab is shown, I've also noticed that if I'm hovering over the tab with my cursor, it shows "localhost:3000/form" as url! But when I tried it using Microsoft Edge browser, once I click on any tab, instead of displaying its content, it's redirecting me to "localhost:3000" (because when I hover cursor on the tab, it shows as a link "localhost:3000" in Edge, instead of "localhost:3000/form)

Any ideas?

I've even tried adding a simple console.log statement inside handleSelect() function (that's called upon clicking on tabs) and Edge doesn't show the output of that console.log, like it's never even called.

So the difference I was able to notice is:
- Upon hovering over the tab on Chrome/Firefox it shows as "localhost:3000/form"
- Upon hovering over the tab on Edge it shows as "localhost:3000"

I think somewhere in there is a problem.

Thanks!

**Comment by taion** [comment]
See https://github.com/react-bootstrap/react-bootstrap/issues/2065, https://github.com/react-bootstrap/react-bootstrap/pull/2080 I think...
