### ISSUE TITLE
"FormControl select" has a bug

### ISSUE THREAD

**Issue by alpha-one** [react-bootstrap/react-bootstrap#2172]
FormControl's select element seems to keep the selected item 's index of the dropdown list in mind; For example, I put  two kinds of dataset respectively in two successive operation as the content of dropdown list of the same select element. 
In particular，
the first dateset is { A,B,C}, put into the dropdown list of the select. Frist, I  choose the B, so the index of the selected item is 2. (This index will be kept in mind in the select component---I guess).  Then , the  second dataset is {D,E,F}. When the second dataset is put into the dropdown list of the select, the selected  item will be displayed as "F",namely the content of index 2 of the second dataset,while I even don't choose it. It acts as if the select keep the index of the selected item in mind. While the new dataset is put into the same select component, "the old index" of the new dataset will be displayed.

However, I don't want this. I need the select to display its first index of the dataset by default whenever new dataset is put into the same select.    So , how to handle it?

**Comment by taion** [comment]
It's not a "bug" just because something doesn't do exactly what you expect in your particular case. "select" form controls here have the exact same semantics as React `<select>` components. Figure out how to do what you need with that.
