### ISSUE TITLE
<Container>content</Container> component missing?

### ISSUE THREAD

**Issue by jeffschwartz** [react-bootstrap/react-bootstrap#2173]
Shouldn't there be Container components to match `<div class="container">` and `<div class="container-fluid">`? I am unable to find their implementations/documentation.

**Comment by jquense** [comment]
It's called `<Grid>` instead of Container here

**Comment by jeffschwartz** [comment]
@jquense but Containers are not Grids. Grids provide layout for columns and rows whereas Containers are used to wrap content including Grids. Container's implementation is trivial as follows:

```javascript
import React from "react";

export default function Container (props) {
    return (
        <div className="container">
            {props.children}
        </div>
    );
};
```

and for a fluid container it is equally trivial:

```javascript
import React from "react";

export default function FluidContainer (props) {
    return (
        <div className="container-fluid">
            {props.children}
        </div>
    );
};

**Comment by taion** [comment]
Did you bother to look at what `<Grid>` did?

**Comment by jeffschwartz** [comment]
Yes I did. It appears that Grid's implementation accepts a prop of "fluid"  and will use that to make a grid fluid. Bootstrap has standalone containers (i.e. divs with a class of either container or conatiner-fluid -- they have nothing to do with grids other than their ability to contain them.

**Comment by taion** [comment]
Then you didn't understand it, because it _literally_ just renders `<div className="container">`.

**Comment by jquense** [comment]
> they have nothing to do with grids other than their ability to contain them.

That's not right, the Grid system is designed so that rows are contained in containers and nothing else. They have negative margin that is offset by the container padding.

the only other place to use a container, is in a Navbar which we handle for you. The _name_ of the class is generic but it's use and function is not.

**Comment by jeffschwartz** [comment]
What in the library render's <div className="container">?

**Comment by jeffschwartz** [comment]
@jquense that is not true, as quoted from bootstrap's docs:

> Bootstrap requires a containing element to wrap site contents and house our grid system. You may choose one of two containers to use in your projects. Note that, due to padding and more, neither container is nestable.

So containers are targeted at anything that one wants to apply them to except that they cannot be nested. For instance one might have a Navbar and a sibling container for page details. The container will restrain the page content to the same margins that the Navbar uses to center its content. Here's an example:

```javascript
const App = (props) => (
    <div>
        <AppNavBar fixedTop />
        <Container>
            <NavLink to="/">Home</NavLink>
            <PageHeader>My Eliquid Reviews</PageHeader>
            {props.children}
        </Container>
    </div>
);
```

Without the Container both NavLink and PageHeader would not align with the content of the Navbar.

**Comment by jquense** [comment]
> What component in the library render's <div className="container">

Again, Grid is the component you want, replace it's name with Container if that helps. ALL it is is container.

**Comment by jeffschwartz** [comment]
@jquense so you believe then that it is acceptable to call a Container a Grid? Are you aware of what semantic apis are all about? Why call a dog a pig when the 2 aren't even related. Your unreasonableness along with the hostile attitude I've received here makes me believe that this project is almost certainly doomed to failure.

**Comment by dozoisch** [comment]
Hi, sorry if you are having a bad experience right now.

This component has been named like that for over two years, since the early stage of the project. Neither jquense or taion we're involved in that decision. https://github.com/react-bootstrap/react-bootstrap/commit/7d9ec217d26d981354ba6d0120de9f11bc7b65e4. We're sorry if this made it harder for you to find it, but that's how it is.

To answer your original question, the `<div className="container"/>` can be rendered as follow `<Grid/>`.

For informational purposes, it is documented right here http://react-bootstrap.github.io/components.html#grid-props-grid.

In the mean time, if you want to ensure that your code is using the name you want, you can always import it as follow `import { Grid as Container } from 'react-boostrap;`.

**Comment by jeffschwartz** [comment]
@dozoisch I appreciate your human response. Perhaps there is hope for this project afterall. It is never too late to fix what is either broken or misleading. A good library/framework should be easy to reason about. If it were me, I'd start by refactoring out Container from Grid into its own module. That would add clarity for users who already know bootstrap and it could also help to reduce the size of bundles when Grids aren't being used. In anycase, thanks again for your human response.

**Comment by dozoisch** [comment]
I'll bring it up for discussion! 

I'd argue that, at this point, it's probably better just documenting it in an obvious manner than renaming the Grid component. Renaming it would put a burden on every current user to go and rename it in their codebase. The Grid component only purpose right now is to render a container or a container fluid, so there is not much to extract there.

**Comment by deanq** [comment]
Documentation should be updated. `Container` is still being referenced here https://react-bootstrap.netlify.com/layout/grid/

**Comment by jquense** [comment]
@deanq its moved back to `Container` in v1 so the docs are correct
