### ISSUE TITLE
validationState attribute can't get default

### ISSUE THREAD

**Issue by bnsd55** [react-bootstrap/react-bootstrap#2174]
Hey,
I'm using [Validation states](https://react-bootstrap.github.io/components.html#forms-validation) and I was wondering why validationState attribute can get only success / error / warning.
What about default ? I'm using those validation states and sometimes I need the default one, so I need to set validationState to null, it is inconvenient.

It will be great if you will add this option :)

**Comment by taion** [comment]
`null` _is_ the default.
