### ISSUE TITLE
Invalid style='red' passed to Panel causes warning, but makes panel red anyway

### ISSUE THREAD

**Issue by ssteinerx** [react-bootstrap/react-bootstrap#2175]
This is in the sb-admin-react project:
```
          <div className="col-lg-3 col-md-6">
            <StatWidget style = "red"
                    icon = "fa fa-tasks fa-5x"
                    count = "12"
                    headerText="New Tasks!"
                    footerText="View Details"
                    linkTo="/" />
          </div>
```
Console shows this:
`warning.js:36 Warning: Failed prop type: Invalid prop `bsStyle` of value `red` supplied to `Panel`, expected one of ["success","warning","danger","info","default","primary"].`

But the panel does come out red.  

Not sure why it's "working", but "green" and "yellow" also work but "blue" does not.

Seems like it shouldn't be doing what appears to be the right thing with an invalid parameter.

**Comment by taion** [comment]
If the CSS in that project defines something like a `.panel-red`, then the class will work. By default the validation only enables the stock TWBS styles but there's nothing stopping you from adding more.
