### ISSUE TITLE
Can't uncheck checkbox?

### ISSUE THREAD

**Issue by VictorChen** [react-bootstrap/react-bootstrap#2181]
I have a checkbox that's checked initially, eg:

```
<Checkbox checked>
  Checkbox
</Checkbox>
```

This renders fine, but then I can't uncheck it? Is that expected?

https://jsfiddle.net/7aoxjvs4/7/

**Comment by jquense** [comment]
yes, read up on how inputs work in React here: https://facebook.github.io/react/docs/forms.html

**Comment by VictorChen** [comment]
ah thank you, looks like what I need is `defaultChecked` instead of `checked`
