### ISSUE TITLE
Style { display: block } in ModalDialog component

### ISSUE THREAD

**Issue by sdwvit** [react-bootstrap/react-bootstrap#2183]
Could you please explain what is the purpose of having style {display: block} hardcoded in ModelDialog component? I'm also seeing the same hardcoded style in some other components.

https://github.com/react-bootstrap/react-bootstrap/blob/master/src/ModalDialog.js#L23

Is it possible to move that style to some dialog's css class? 

If it is because of position: absolute and centering by {top: 0, bottom: 0, left: 0, right: 0}, then it might be easier and less code to use {display: flex} on parent div and {flex-grow: 1} on ModalDialog div instead of calculating height and having those styles.

**Comment by taion** [comment]
It's to override `display: none` from default styling. You can override it yourself however you wish.
