### ISSUE TITLE
DropdownButton doesn't close when selecting a MenuItem

### ISSUE THREAD

**Issue by ademars94** [react-bootstrap/react-bootstrap#2184]
There are a few issues here asking how to prevent the default behavior of the `DropdownButton`, which is to close when a `MenuItem` is selected.  I am having the opposite problem.  I have a dropdown that will remain open if an item is selected, and will only close when clicking outside of the dropdown itself.  What are the relevant methods here and how do they work?  The docs aren't very helpful here, I am following the example code.

I am using the latest version of Bootstrap CSS.

Relevant Code:

```jsx
// Return statement from my StyleButton component (which just returns MenuItems)
// this.onToggle just toggles a color, which I don't think is relevant to the dropdown closing 
return (
  <MenuItem eventKey={ this.props.index } onSelect={ this.onToggle }> 
    <span style={style}>
      { this.props.label }
    </span>
  </MenuItem>
);
```

```jsx
renderMenuItems = () => {
  // Returns a map of StyleButton components
}
```

```jsx
<DropdownButton title={ 'Color' } id={ 'dropdown-basic' } dropup>
  { this.renderMenuItems() }
</DropdownButton>
```

**Comment by ryuhhnn** [comment]
Have you tried accessing the onClick property? I know that you can use jQuery to run .toggle() on a dropdown button to close it programmatically. I'm thinking the same concept should apply here.

**Comment by taion** [comment]
Do you have a runnable repro? The dropdown menus on our docs page do not have this problem.

**Comment by natevw** [comment]
More discussion of this at https://github.com/react-bootstrap/react-bootstrap/issues/541, which also seems to be closed with no fix.
