### ISSUE TITLE
For tabs, seems that animation=true results in multiple renders for child components

### ISSUE THREAD

**Issue by alisman** [react-bootstrap/react-bootstrap#2185]
When I have animation set to true on a set of tabs, child components are rendering multiple times per dispatch.  Seems like animation should not involve any state changes that would result in render being called.

**Comment by taion** [comment]
We use React component state to track animation state, so re-renders are unavoidable.

**Comment by alisman** [comment]
First of all, thanks for your work on all of this!!! But I think you should reconsider doing that.  Given that these are containers meant to be filled with lots of other components that will be expensive to render (datatables, charts), it would seem to be prohibitive.  I think this should be accomplished with css transitions.

**Comment by jquense** [comment]
I understand why you might be concerned here but the reality isn't waht you think.

> that will be expensive to render (datatables, charts)

That's not how React works, rendering is very cheap; rendering simply returns new description of what the DOM should look like down the component tree, if nothing lower down changes between renders the DOM won't be touched (the slow part). Moreso, if you have a component that is actually expensive to rerender then its that components job to optimize via `shouldComponentUpdate` not the presentational components (like tabs) further up the tree.

>  I think this should be accomplished with css transitions.

they are accomplished via CSS transitions. you still need to add and remove classes to trigger said animations, this is done via state changes in the React components

**Comment by alisman** [comment]
I understand the optimization of vdom/reconciliation and you're right that shouldComponentUpdate  implementation would render this a non issue.  But I still think that library container components should be biased toward the optimal.  They shouldn't cause re-render cycles that will come as surprise to developers.  I don't think it's actually necessary to model animation (especially for short transitional animations) in state.  Suppose you acted directly on DOM ref.  Your DOM would then be out of sync with the vdom for duration of animation.  I think that would be ok and a better compromise than forcing a render cycle on all children.   It also might be possible to invoke the css animation without any change to component's DOM by injecting style tag and using an ID selector.

**Comment by jquense** [comment]
There is just no reason to optimize for this, the benefit would be extremely minimal, if any, while also dramatically reducing the maintainability of the code. Micro-optimizing components to reduce render() invocations is one of React's biggest "anti-patterns" (for lack of a better phrase). The main benefit of React is that you shouldn't have to think about how often render is called. If you do have to think of it, micro optimizing components above the expensive one is the wrong way to solve that problem
