### ISSUE TITLE
React 15 warnings

### ISSUE THREAD

**Issue by afaayerhan** [react-bootstrap/react-bootstrap#2191]
I have searched github issues already. seen that this solved but still getting a lot of warning using a dropdownbutton and menueitem. how do you silence the warnings?

**Comment by jquense** [comment]
if you are upgraded to the latest version of react-bootstrap, then the problem is that your code is passing props that don't belong on those components to them

**Comment by afaayerhan** [comment]
@jquense thanks. maybe help me take a look at this code maybe something is wrong with it   
  ```jsx
       <DropdownButton
              title="Simple Dropdown"
              id="test-id"
            >
              <MenuItem>Item 1</MenuItem>
              <MenuItem>Item 2</MenuItem>
              <MenuItem>Item 3</MenuItem>
              <MenuItem>Item 4</MenuItem>
            </DropdownButton>
```

**Comment by jquense** [comment]
looks fine, if you are still getting errors you aren't on the latest version `0.30.x`, might need to nuke  your node_modules and reinstall

**Comment by afaayerhan** [comment]
@jquense thanks bro, nuking my node_modules solved it
