### ISSUE TITLE
Extended compenents don't work in IE9

### ISSUE THREAD

**Issue by pulmo** [react-bootstrap/react-bootstrap#2192]
Hello, thanks for the great project.  Recently (I can't tell, after what updates) it's an error in IE9. When I just use, for example, Modal component - it's work. But when I'm trying extend it - I got an error.

My extended version:
```javascript
class ModalItem extends Modal {
	constructor(props) {
		super(props);
		this.events = new Events();
	}

	componentWillUnmount() {
		this.events.stopListening();
	}
}
```
It throw error:
```
A `bsClass` prop is required for this component
```
If I specify bsClass it will throw error:
```
ModalItem.getChildContext(): childContextTypes must be defined in order to use getChildContext().
```
In newer browsers everithing works fine.

**Comment by jquense** [comment]
I am not sure why that wouldn't work, but you really shouldn't extend Components. Instead create new components that render the original ones.

```jsx
class ModalItem extends React.Component {
    constructor(props) {
        super(props);
        this.events = new Events();
    }

    componentWillUnmount() {
        this.events.stopListening();
    }

    render() { 
      return <Modal {...this.props} /> 
    }
}
```

**Comment by pulmo** [comment]
Thanks for answer. With this code it can't create Modal.Header, Modal.Body and Modal.Footer.

**Comment by pulmo** [comment]
Thanks for answer. With this code it can't create Modal.Header. Something like that didn't help:
```javascript
ModalItem.Header = ModalHeaderItem;
class ModalHeaderItem extends React.Component {
	constructor(props) {
		super(props);
		this.events = new Events();
	}

	componentWillUnmount() {
		this.events.stopListening();
	}

	render() {
		return <Modal.Header {...this.props}/>;
	}
}
```

**Comment by taion** [comment]
Don't rebind the component. Just use your own instead of `<Modal.Header>`.

**Comment by pulmo** [comment]
Thanks a lot for the help, everything works.
