### ISSUE TITLE
Override NavbarToggle default markup

### ISSUE THREAD

**Issue by muuki88** [react-bootstrap/react-bootstrap#2197]
Hi,

The [NavbarToggle](https://github.com/react-bootstrap/react-bootstrap/blob/master/src/NavbarToggle.js#L47-L54) provides a default markup for the hamburger menu:

```jsx
<button {...buttonProps}>
    <span className="sr-only">Toggle navigation</span>
    <span className="icon-bar" />
    <span className="icon-bar" />
    <span className="icon-bar" />
</button>
```

It would be nice replace the `span`s with a different markup, eg. an `svg` for open and closed state. The API may look somethink like this

```jsx
<Navbar.Toggle toggle={
  (isToggled) => isToggled ? <span>open</span> : <span>closed</span>
} />
```

WDYT?

**Comment by jquense** [comment]
already there :) you  an pass children to the toggle and it will render that instead of the default bars

**Comment by muuki88** [comment]
Ah! Of course. Thanks for the quick reply :)

**Comment by mronoffon** [comment]
@jquense:  how can this be done?  can you show an example or pseudo?

thank you

**Comment by mronoffon** [comment]
@muuki88 :  have you tried jquense's suggestion?  If so, how did you accomplish it?

thanks

**Comment by muuki88** [comment]
@mronoffon This is the code we end up using

```jsx
// storing the toggle state of the hamburger menu
toggleNavbar = () => {
  this.setState({
    mobileNavigationExpanded: !this.state.mobileNavigationExpanded
  });
};

// the render method
renderMenuToggle = () => {
  const collapsedIcon = this.isRegistered() ?
    this.renderProfileImage(this.props.user) :
    <InlineSVG className={`${cssPrefix}-menu-icon`} src={MenuOpen}/>;

  return (
    <Navbar.Toggle onClick={this.toggleNavbar}>
      {this.state.mobileNavigationExpanded ?
        <InlineSVG className={`${cssPrefix}-menu-icon`} src={MenuClose}/> :
        collapsedIcon}
    </Navbar.Toggle>
  );
};
```
