### ISSUE TITLE
defaultExpanded prop does not change behavior of Panel

### ISSUE THREAD

**Issue by vinnymac** [react-bootstrap/react-bootstrap#2198]
I tried to use `defaultExpanded` on the [Panel Accordion](https://react-bootstrap.github.io/components.html#panels-accordion) docs and couldn't get it to work. I put together a [JSFiddle](https://jsfiddle.net/rjdLgcoq/2/) of the issue I am describing. I expected `defaultExpanded` to expand the collapsed panels by default. Am I misunderstanding the docs or is this a bug?

**Comment by taion** [comment]
Use `activeKey` or `defaultActiveKey` on the panel group.

**Comment by vinnymac** [comment]
@taion your response implies that Panels can only have one expanded at a time when used in a `PanelGroup`. My aim was to have all Panels expanded. User interaction could then collapse panels as needed, but I am lead to believe this is not possible with the current implementation. Thanks for the tip.

**Comment by taion** [comment]
That's the meaning of an accordion.

**Comment by vinnymac** [comment]
@taion I was just looking over the [docs](http://getbootstrap.com/javascript/#collapse-example-accordion) and it works as you say. The naming for this bootstrap feature although fun, is inaccurate. I can work around it and implement it myself, thanks for the advice it was very helpful.
