### ISSUE TITLE
Nav active, activeHref, activeKey unknown props warning

### ISSUE THREAD

**Issue by CoreyKaylor** [react-bootstrap/react-bootstrap#2199]
There are warnings still being produced from the Nav component passing props down to its DOM elements. I see others reported this issue in this [thread](https://github.com/react-bootstrap/react-bootstrap/issues/1970) and was resolved, but it appears like there may be some lingering items.

React 15.3.1
react-bootstrap 0.30.3

**Comment by taion** [comment]
Nav shouldn't have any DOM elements as children. It should only hold NavItems. If you're putting your own DOM elements in there, you'll have to deal with these props yourself.

**Comment by gravitycode** [comment]
I dont like the solution that Bootstrap propose. Can´t bootstrap see if any of their childs is the type expected (NavItem for example) before injecting the properties?

**Comment by miguelmich** [comment]
In [NavDropdown](https://github.com/react-bootstrap/react-bootstrap/blob/master/src/NavDropdown.js#L70) you are only expecting a title prop, but what if I want to put an image along with the title?

**Comment by ondy1985** [comment]
The most simple solution would be to check if the child is a DOM element or a React component, which is done pretty easily (typeof child.type === 'string' if it's a DOM element). And don't inject those props to DOM elements.

**Comment by ondy1985** [comment]
At least, do not inject it to DOM elements, it's a pretty easy check...

**Comment by Yuripetusko** [comment]
Agree that bootstrap shouldn't add those attributes to any children within Nav

**Comment by jquense** [comment]
the Nav component only supports NavItems as children or components that wrap NavItem. other components aren't valid so we aren't going to have special, error prone and infeasible, logic to sniff child types.

**Comment by miguelmich** [comment]
So there is no way to extend the default bootstrap components? I can't understand why other elements aren't valid, wasn't one of the bootstrap purposes to be extensible?

**Comment by taion** [comment]
You can extend `<NavItem>` or put something else in there with equivalent semantics. Just don't put a DOM element there directly.

**Comment by miguelmich** [comment]
Great thanks!

**Comment by Yuripetusko** [comment]
Thanks for explaining @taion

**Comment by pengliheng** [comment]
Nav shouldn't have any DOM elements as children. It should only hold NavItems. If you're putting your own DOM elements in there, you'll have to deal with these props yourself.


omg,,,,it is the prefect way to solve my issue

**Comment by loganb** [comment]
Hello, 

I just encountered this warning in 0.31.2 when using the NavText element nested inside a Nav element. I'm relatively new to React, so I'd appreciate any suggestions you have on how I can isolate the issue.

**Comment by taion** [comment]
@loganb `<Navbar.Text>` goes under `<Navbar>`, not `<Nav>`.

**Comment by PedroFerr** [comment]
Solution is to use `LinkContainer` from `react-router-bootstrap` instead of Bootstrap's `<Link />`! It works the same and no error is thrown.  
Check it here:  
https://stackoverflow.com/questions/53559705/react-does-not-recognize-the-activekey-prop-on-a-dom-element

**Comment by Godofbrowser** [comment]
I actually used `<React.Fragment>` to wrap the child/children of `<Nav>` and the errors were gone.

In my case, i was using DOM elements as children and not `<NavItem>`
