### ISSUE TITLE
question: What is the purpose of bsStyle?

### ISSUE THREAD

**Issue by kutyel** [react-bootstrap/react-bootstrap#2200]
Hi!

I know that **Bootstrap** is all about css classes, that's why I expected a bootstrap implementation for *React* to be all based in `className`s. Therefore, what is the `bsStyle` all about? Shouldn't I just be able to style any component with the custom **classNames** that I already know from Bootstrap? What is then the purpose of `bsStyle` in the whole library?

**Comment by taion** [comment]
It lets you use contextual styles. See the button example.
