### ISSUE TITLE
0.30.3 breaks react-router-bootstrap LinkContainers inside NavDropdown

### ISSUE THREAD

**Issue by Zaiban** [react-bootstrap/react-bootstrap#2201]
I have `<LinkContainer>` elements under `<NavDropdown>`s. When I updated to 0.30.3, the `<LinkContainers>`s will have `active={false}` props passed on them. This breaks them because they will never show up as active now.

Rolling back to 0.30.2 fixes the problem.

**Comment by taion** [comment]
How is it getting `active={false}`? Do you have an explicit `activeKey` or `activeHref`?

**Comment by Zaiban** [comment]
I'm having problems trying to find out what is passing it. I don't have any `activeKey` or `activeHref`, and when `console.log`ìng them in `NavDropdown.prototype.render` they show up as `undefined`, so I don't think those 2 are the culprit.

**Comment by Anahkiasen** [comment]
I'm actually having the opposite issue, all my links are marked as active when they didn't. This is only on 0.30.3, 0.30.2 works fine

**Comment by taion** [comment]
That's most likely a bug in your code – you're setting `activeKey` or `eventKey` or `activeHref` in such a way that your children are now (correctly) evaluating as active aside from the `<LinkContainer>` check.
