### ISSUE TITLE
Issue with using floating integer on Input Field

### ISSUE THREAD

**Issue by tusharkhatiwada** [react-bootstrap/react-bootstrap#2202]
Hello,
I have a input field with `type="number"` , there's no problem with using an integer. But when I try to use a decimal value there are some issues:

1. When I press `decimal`, the cursor moves to the initial position. And it doesn't show the `decimal` on the input field.
2. When I double press `decimal` the cursor move to the initial position and uses the `decimal` there. Like, if I want 21.34, I'll have to do : 21 **double press .** 34 and the value that shows will be **.3421** 

**GIF**
![react-bootstrap](https://cloud.githubusercontent.com/assets/5126590/18338639/246fc8f4-75ba-11e6-8f81-b5176afea8f7.gif)

**Code:**

```
<FormGroup bsSize="lg" validationState={this.state.poiValidate}>
   <InputGroup>
      <FormControl
         type="number"
          placeholder="Price"
          defaultValue={this.state.price}
           onChange={(text) => this.setState({price: text.target.value})}
           required />
    </InputGroup>
    <FormControl.Feedback />
</FormGroup>
```

**Comment by taion** [comment]
This isn't specific to React-Bootstrap. Those events are just getting passed down to the wrapped `<input>`.

**Comment by tusharkhatiwada** [comment]
@taion 
Ok. 
Do you have any suggestions to make it work as expected ?

Thanks.
