### ISSUE TITLE
Microsoft Edge Not ReRendering on State Change

### ISSUE THREAD

**Issue by ArledgeMike** [react-bootstrap/react-bootstrap#2203]
I have a react/fluxible app. I am using DropDownButton to make a Client picker list. When a user selects a new Client from the DDB the REACT-Bootstrap components do not change when the state changes. This is bug is specific to Microsoft Edge. IE11, FF, Chrome and Safari all have the proper behavior.

**Comment by taion** [comment]
See #2065, #2080 I think...
