### ISSUE TITLE
SafeAnchor's empty href attributes create browser status bar on hover

### ISSUE THREAD

**Issue by leifkb** [react-bootstrap/react-bootstrap#2205]
When the user hovers over a SafeAnchor (e.g. a MenuItem in a DropdownButton) with no defined href attribute, the browser shows the URL of the current page in the status bar. This is cosmetically annoying, especially because the status bar in modern browsers covers up content at the bottom of the page. If I am navigating a DropdownButton's menu, and it is placed too close to the bottom of the page, the status bar can cover up the bottom elements of the menu.

I saw a comment in SafeAnchor.js, where it adds the empty href attribute, which says it does that to get the right cursor. Is there a reason that couldn't be done with CSS instead?

**Comment by taion** [comment]
See https://github.com/react-bootstrap/react-bootstrap/pull/2080

**Comment by leifkb** [comment]
Thanks for the response. Sorry, it's possible I'm missing something, but I don't think this is a duplicate. #2080 and #2065 are about an Edge-specific issue that doesn't involve the browser status bar. Changing href="" to href="#" wouldn't resolve the status bar issue. Both cause a status bar to be displayed.
