### ISSUE TITLE
Docs: Move "placement" property from "Tooltip" to "Overlay Trigger"

### ISSUE THREAD

**Issue by skitterm** [react-bootstrap/react-bootstrap#2206]
From the [docs](https://react-bootstrap.github.io/components.html#tooltips), I thought I needed to put the "placement" prop on the Tooltip component itself. Only by looking at someone's example did I realize I have to put it on the OverlayTrigger. Can the docs be updated so that it's clear that the "placement" property should be on the OverlayTrigger and not the Tooltip component?

**Comment by taion** [comment]
Interesting. It actually is on the overlay and the tooltip. I think we need to add the prop types to `<Overlay>`.

**Comment by ghusse** [comment]
Does it make sense to have this property in other cases the `Overlay` is used? Or is it specific to tooltips?

**Comment by kevinzwhuang** [comment]
Yep, `placement` is used for custom Overlays too - https://react-bootstrap.github.io/components.html#custom-overlays-overlay

**Comment by taion** [comment]
fixed by #2318?

**Comment by kevinzwhuang** [comment]
I think the new version of the docs still need to be released to the site repo

**Comment by taion** [comment]
Oh... yeah, I'll do that in a bit. Looks like the docs are properly fixed though. Thanks!
