### ISSUE TITLE
Provide size prop for multiple select

### ISSUE THREAD

**Issue by subhamagr** [react-bootstrap/react-bootstrap#2207]
[Screenshot](http://prntscr.com/cgok0h)

and the code for the above screenshot:
```javascript

<FormControl multiple={true} size={5} componentClass="select" onChange={this.handleChange} value={this.state.department}>
    {departments}
</FormControl>
```

By default it shows 2 options. How do I provide the size prop for multiple select?

**Comment by taion** [comment]
Dupe https://github.com/react-bootstrap/react-bootstrap/issues/1889

**Comment by jquense** [comment]
I think 'size' here is the html attribute not the bootstrap sizing styles, judging from the code. if so though that shouldn't be a problem either they should be passed through

**Comment by taion** [comment]
Err then there's nothing to track here?
