### ISSUE TITLE
Tooltip doesn't show when OverlayTrigger child is a custom React component

### ISSUE THREAD

**Issue by lukehorvat** [react-bootstrap/react-bootstrap#2208]
When I place a custom React component inside an `OverlayTrigger`,  it causes the tooltip to no longer display on mouse hover. Example:

```jsx
function Avatar(props) {
  return (<img src={props.url} />);
}
```

```jsx
<OverlayTrigger overlay={(<Tooltip id="hi">Hello, world!</Tooltip>)} placement="top">
  <Avatar url="http://i.imgur.com/cOkr6Um.gif" />
</OverlayTrigger>
```

Whereas the following *does* work:

```jsx
<OverlayTrigger overlay={(<Tooltip id="hi">Hello, world!</Tooltip>)} placement="top">
  <img src="http://i.imgur.com/cOkr6Um.gif" />
</OverlayTrigger>
```

(react-bootstrap@v0.30.2)

**Comment by jquense** [comment]
you need to pass the props through to the DOM element. it's not working because you are swallowing the event handlers in avatar

**Comment by nielk** [comment]
@jquense Can you give us a little example of a Custom component inside an OverlayTrigger? I don't no what to do to have the event handlers in avatar?

Thanks in advance,

**Comment by jquense** [comment]
@nielk 

```jsx
function Avatar({ url, ...props }) {
  return (<img {...props} src={url} />);
}
```
```jsx
<OverlayTrigger overlay={(<Tooltip id="hi">Hello, world!</Tooltip>)} placement="top">
  <Avatar url="http://i.imgur.com/cOkr6Um.gif" />
</OverlayTrigger>
```

**Comment by nielk** [comment]
Thanks ! It works well, I'm my case, I only take onMouseOut and onMouseOver:

```jsx
const MyComp = (props) => {
  return (
    <div onMouseOut={props.onMouseOut} onMouseOver={props.onMouseOver}>
    </div>
  )
}
```

```jsx
<OverlayTrigger overlay={(<Tooltip id="hi">Hello, world!</Tooltip>)} placement="top">
  <MyComp />
</OverlayTrigger>
```

Thank for the work, very good project

**Comment by davidfurlong** [comment]
This should probably be part of the docs?

**Comment by byzg** [comment]
I agree with @davidfurlong , I've got info about react tooltip from https://react-bootstrap.github.io/components.html but there is no something about the problem

**Comment by SachaG** [comment]
An easy fix is to wrap your custom component in an extra div:

```
<OverlayTrigger overlay={(<Tooltip id="hi">Hello, world!</Tooltip>)} placement="top">
  <div> 
    <Avatar url="http://i.imgur.com/cOkr6Um.gif" />
  </div>
</OverlayTrigger>
```

**Comment by konekoya** [comment]
@SachaG Thanks for this workaround! Works great for me.

**Comment by tanweer-et** [comment]
import React, { Component, PropTypes } from 'react';
import { OverlayTrigger, Tooltip } from 'react-bootstrap';

function Avatar({ url, ...props }) {
  return (<img {...props} src={url} />);
}

const LinkWithTooltip = React.createClass({
  render() {
    const tooltip = <Tooltip id={this.props.name}  placement="top" > {this.props.name} </Tooltip>;
    console.log(tooltip);

    return (
            <OverlayTrigger  triggerType="hover" overlay={<Tooltip id={this.props.name}  placement="top" > {this.props.name} </Tooltip>} placement="top">
              <Avatar url={this.props.url} />
            </OverlayTrigger>
    );
  }
});
export default LinkWithTooltip;

my image shown but tooltip not showing by using above code

**Comment by tanweer-et** [comment]
@SachaG please help me out there.

**Comment by SachaG** [comment]
See my example. You have to wrap your component in an extra `<div>`.

**Comment by tanweer-et** [comment]
@SachaG  i have done by this way. but still same condition

**Comment by jaimefps** [comment]
My code doesn't manage to get tooltip to show either. Currently doing the 'quickfix' and still nothing

```
import { Tooltip, OverlayTrigger, Button } from 'react-bootstrap'

function Avatar() {
  return (<label>test</label>);
}



export default class Test extends React.Component {
	constructor(props) {
		super(props) 
		this.state = {}
	}
	render() {
		return (
				<OverlayTrigger overlay={(<Tooltip id="hi">Hello, world!</Tooltip>)} placement="top">
				  <div><Avatar /></div>
				</OverlayTrigger>
		)    		
	}
}
```

**Comment by GAUTAMRAJU15** [comment]
the Avatar is a function here and u are calling <Avatar /> component! it wont work

**Comment by usmanmani0** [comment]
> An easy fix is to wrap your custom component in an extra div:
> 
> ```
> <OverlayTrigger overlay={(<Tooltip id="hi">Hello, world!</Tooltip>)} placement="top">
>   <div> 
>     <Avatar url="http://i.imgur.com/cOkr6Um.gif" />
>   </div>
> </OverlayTrigger>
> ```

Thanks It worked for me!

**Comment by decayedCell** [comment]
> An easy fix

This is by far the best fix imo, just make sure you wrap the component right after using OverlayTrigger. I tried to wrap the wrap the actual custom component (so Avatar in this example) in the div and that didn't work.

**Comment by coler-j** [comment]
How do you type `...rest` for TS? It kind of seems to break having a clean component interface.

**Comment by rishadomar** [comment]
I few years later... 
Here is a working example using rest


```jsx
import React, { forwardRef } from 'react';

export interface FunComponentProps {
    countryCode: string;
    width: number;
    highResolution?: boolean;
    className?: string;
}

export const FunComponent = forwardRef<HTMLImageElement, FunComponentProps>(
    ({ countryCode, width, className, highResolution = false, ...rest }, ref) => {
            return (
                <img
                    ref={ref}
                    {...rest}
                    width={width}
                    src={`${process.env.PUBLIC_URL}/assets/images/${countryCode?.toLowerCase()}-flag.png`}
                    alt={`${countryCode} flag`}
                    className={`h-auto ${className ?? ''}`}
                />
            );
    }
);
```

To use it:
```jsx
            <OverlayTrigger overlay={<Tooltip>Country: South Africa</Tooltip>}>
                <FunComponent countryCode='za' width={100} />
            </OverlayTrigger>
```
