### ISSUE TITLE
Stripping values property from Redux Forms?

### ISSUE THREAD

**Issue by tanepiper** [react-bootstrap/react-bootstrap#2210]
I've raised an issue here, but looking in the source I wonder if there is an incompatibility and workaround?

https://github.com/erikras/redux-form/issues/1750

When I try use the FormControl component to render an input form for Redux Forms it seems to strip the value of the component. e.g:

Input:
`<Field type="text" name="username" placeholder="Please enter your username" component={FormControl}/>`
Output:
`<input type="text" name="username" placeholder="Please enter your username" id="username" class="form-control">`

But if I use a standard "input", e.g:
`<Field type="text" name="username" placeholder="Please enter your username" component="input" />`
I get:
`<input type="text" name="username" value="" placeholder="Please enter your username">`

I'm wondering if it's related to https://github.com/react-bootstrap/react-bootstrap/blob/master/src/utils/bootstrapUtils.js#L150 ?

**Comment by jquense** [comment]
we don't strip any props put except the specific bootstrap props. you can see it passes everything else through

**Comment by tanepiper** [comment]
@jquense OK, I had just noticed there had also been a rather lot of changes to that code (https://github.com/react-bootstrap/react-bootstrap/commit/320c0e780c50e7e7cac9c6cdcd809a666983d4f6) that may have introduced a bug.  Is there any way I can debug what's being passed?

The redux form stuff is picking it up:

![image](https://cloud.githubusercontent.com/assets/376930/18472767/3296ec82-79b1-11e6-993e-2b00321d93aa.png)

But for some reason the value property is not being rendered to the React Bootstrap form elements in the DOM.

**Comment by taion** [comment]
Try using the React dev tools to see what props are being passed through. In this context `<FormControl>` really does just pass things down, so there's no reason you should be seeing props get stripped.

**Comment by tanepiper** [comment]
@taion Think I might have found it

This is the DOM output:

![image](https://cloud.githubusercontent.com/assets/376930/18503170/4c1d469a-7a53-11e6-9f4b-4d2830c62abc.png)

Here are the props:

![image](https://cloud.githubusercontent.com/assets/376930/18503187/60d90fe2-7a53-11e6-8a10-2f7a9c868128.png)

The two props `input`, `meta` are being passed in, and input contains the value.  It looks like for React Bootstrap I may have to create a intermediary element to pass the value down (as per https://github.com/erikras/redux-form/blob/fb03d0a702bcdb2cc1065b5ba3121235683365d6/docs/api/Field.md#usage)

Once I have a working solution I'll add it here for anyone else having any issues with this

**Comment by tanepiper** [comment]
So this is what I had to do:

I created a reusable component called `FieldFormComponent`:

```
import React, { Component } from 'react';
import {FormGroup, FormControl, ControlLabel} from 'react-bootstrap';

export default class FieldFormControl extends Component {

  render () {

    const { placeholder, type, input, meta} = this.props;

    return (
      <FormGroup controlId={input.name} validationState={meta.error ? 'error' : 'success'}>
        <ControlLabel>{this.props.children}</ControlLabel>
        <FormControl type={type} placeholder={placeholder} value={input.value} onChange={input.onChange} />
        <FormControl.Feedback />
      </FormGroup>
    );
  }
}
```

Then I can do:

`<Field type="text" name="username" placeholder="Please enter your username" component={FieldFormControl}>Username</Field>`

**Comment by taion** [comment]
Right, so it looks like that's just the Redux Form API: http://redux-form.com/6.0.2/docs/api/Field.md/#usage

It's different for custom components v. for `<input>`. There's nothing to do on this end – `<FormControl>` has roughly the same signature as `<input>` otherwise.

**Comment by DrYSG** [comment]
@tanepiper I followed your suggestion, and have a short custom control that wraps the FormControl

```
        const FieldInput = ({ input, meta, type, placeholder, min, max }) => {
            return (
                <FormControl
                    type={type}
                    placeholder={placeholder}
                    min={min}
                    max={max}
                    value={input.value}
                    onChange={input.onChange} />
            )
        }
```

and I invoke it like this:

```
<Field name="ServerPort" type='number' component={FieldInput} placeholder={ServerPort} min="1024" max="65535" />
```
and this works, except for one odd thing. When the mouse enters the field the first time, and the field gets selected, then I can press one key, and then field looses the selected state. If I reselect, and continue typing it works fine. It is only the first key press that causes the loss of "selected" or is it focus?

**Comment by mindhaq** [comment]
I am using this function to map the input props to props for FormControl. So far, in a very simple example, it is working quite fine.

```
const ReduxFormControl = ({input, meta, ...props}) => {
    return <FormControl {...props} {...input} />
};

**Comment by aeciolevy** [comment]
@mindhaq the spread for input save me... because I was passing just onChange, so the touched was not working.. tks.

**Comment by shubhamk541** [comment]
It is still not giving all props.
Redux-form +reactstrap
`import React from 'react';
import { Button, Form, FormGroup, Input, Alert,Label,FormText } from "reactstrap";
import {reduxForm,Field} from 'redux-form';
import SurveyField from './SurveyField';

  class SurveyForm extends React.Component {
    
    
    render() {
        
        return (
            <div className="container" ><h1 style={{textAlign:'center'}}>Enter all The Details</h1>

             <Form onSubmit={this.props.handleSubmit(value=>{console.log(value)})}style={{paddingTop:"10px"}}>

                <FormGroup style={{ display: 'flex', flexDirection: 'column'}}>

                    <Field  type="text" name="username" placeholder="Please enter your username" component={SurveyField} />

                </FormGroup>
                

                <div>
                   <Button style={{float:"right"}} color="success" size="lg">Submit</Button>{' '}
                </div>

             </Form>
            </div>
        )
    }
export default reduxForm(
    {    
        form:"surveyForm"
    }
)(SurveyForm);
`
============================Survey Field========================
`
import React, { Component } from 'react';
import {FormGroup, FormControl, ControlLabel} from 'reactstrap';

const SurveyField = ({input, meta, ...props}) => {
    console.log(props);
    return <FormControl {...props} {...input} />
};
export default SurveyField;`

**Comment by mindhaq** [comment]
@shubhamk541 you're using [reactstrap](https://reactstrap.github.io/) and this is an issue in **react-bootstrap**.

**Comment by shubhamk541** [comment]
Is reactstrap is not an upgrade version of react-bootstrap?

**Comment by taion** [comment]
no, it's a different library

**Comment by GFBorelli** [comment]
@mindhaq saved me, thank you!
