### ISSUE TITLE
Passing prop to PaginationButton

### ISSUE THREAD

**Issue by chochihim** [react-bootstrap/react-bootstrap#2213]
I want to create a pagination like: 

![screen shot 2016-09-14 at 4 16 51 pm](https://cloud.githubusercontent.com/assets/19410131/18504893/236a828c-7a97-11e6-9c31-72dc7d870abd.png)

I managed to render the "STEP n-th" by using the eventKey prop but not the step name.

Can we pass in an item array prop so that the PaginationButton can be more customisable?

**Comment by taion** [comment]
The best you can do right now is to use a custom component class. See https://github.com/react-bootstrap/react-bootstrap/issues/1758 for longer-term goals.
