### ISSUE TITLE
How to get the value of "FormControl select" 

### ISSUE THREAD

**Issue by captainwooder** [react-bootstrap/react-bootstrap#2214]
I want to get the value of the "FormControl select" component , not using the 'onChange" function.

Now I get the ref of "FormControl select", and print the value of the ref of “FormControl select”. The value of the ref is displayed as below:
![the ref of formcontrol select png](https://cloud.githubusercontent.com/assets/16228523/18506646/9547d0d2-7a9f-11e6-9f89-dbb322ef9d08.png)

So How to get the value of "FormControl select" ???

**Comment by jquense** [comment]
you can control the input via value and onChange or use find DOM node on the ref and pull it from the input

**Comment by captainwooder** [comment]
pull it from the input ?? I already got the ref of the FormControl, then how to pull it from input??? @jquense

**Comment by jquense** [comment]
with `findDOMNode`

**Comment by avindra** [comment]
`findDOMNode` is likely going to be removed, so I would not recommend using that

https://twitter.com/dan_abramov/status/752950507690455040
https://github.com/yannickcr/eslint-plugin-react/issues/678

**Comment by jquense** [comment]
Please don't show up and spread FUD. I'm well aware of that issue, you'll notice i'm extremely active on it.

If someone doesn't want to use controlled inputs the only way to get the value is to use `findDOMNode`, regardless of what you recommend. This as been covered many many times before on the issue tracker.

**Comment by avindra** [comment]
Regardless of your opinion that I am "spreading FUD", the simple fact remains that using findDOMNode is discouraged. It's a hack that may work for @captainwooder today but may cause issues for him later. It's only fair that he is made aware of this instead of being pushed in one direction.

**Comment by taion** [comment]
It's not a hack and it's not discouraged. Please read through the actual ESLint thread if you want more details. You should not be forming your judgments of best practices through 140 character tweets.

**Comment by avindra** [comment]
@taion : besides Dan discouraging usage on the other thread, this is very clearly spelled out in the react documentation with a big red section. I don't know how much more black and white this can be for you.

**Comment by avindra** [comment]
I think it's important for these things to be spelled out, especially on highly visible projects, such as this one, which aims to provide a connecting API for two of the biggest front-end libraries ever.

**Comment by taion** [comment]
Everything described in the note in the docs applies to using refs on DOM components as well. In general you should not be using uncontrolled inputs.

If you are using them, there's no difference right now between using a DOM component ref and `findDOMNode`.

While your attempt to help here is appreciated, your understanding appears to be a bit limited, and I suggest continuing to develop your familiarity with idiomatic React patterns before adding additional confusion to existing discussion threads.

**Comment by taion** [comment]
I cleaned up some off-topic discussion from this issue. If you are using an uncontrolled input, you access the value via the underlying DOM node, as with `<input>`.

**Comment by avindra** [comment]
Quite disappointed to see that censorship is your response to a very reasonable discussion. @captainwooder I'm sure you'll come to an appropriate conclusion about this on your own.

**Comment by janzenz** [comment]
@taion do you have any sample code to show that? @captainwooder have you found a solution to this?

**Comment by janzenz** [comment]
For people like me who are here late here's what I did:

```
import React, {Component} from 'react'
import ReactDOM from 'react-dom'

class Blah extends Component {
    getSelectValue = () => {
        /* Here's the key solution */
        console.log(ReactDOM.findDOMNode(this.select).value)
    }

    render() {
        return
        <div> 
            <FormControl
            ref={select => { this.select = select }}
            componentClass="select"
            disabled={this.state.added}
            >
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3">3</option>
            </FormControl>
            <Button onclick={this.getSelectValue}>
                Get Select value
            </Button>
        </div>
    }
}
```

**Comment by michaelsterpka** [comment]
Currently following the React-Bootstrap forms templating from [here](https://react-bootstrap.github.io/components/forms/). I'm implementing the select drop form and having some trouble grabbing the value of any specific object. Here's an example from their sample:

`<FormGroup controlId="formControlsSelect">
      <ControlLabel>Select</ControlLabel>
      <FormControl componentClass="select" placeholder="select">
        <option value="foo">foo</option>
        <option value="bar">bar</option>
      </FormControl>
    </FormGroup>`

How would I go about grabbing the value of any selected option? Thanks!

**Comment by michaelsterpka** [comment]
@wcschoonover found a work around that uses this implementation. Thank you! Cheers.

**Comment by PhuongDTran** [comment]
handleChange = (e) => {
    console.log(e.target.value ); // stuff
  };
render(){
...
  <FormControl  as="select"  onChange={this.handleChange} >
    <option value="stuff">stuff</option>
    ...
  </FormControl>
}

**Comment by hansiemithun** [comment]
How to fetch the selected value using stateless function?

**Comment by progamr** [comment]
@hansiemithun i found a solution for this that worked for me

`
const myFunctionalComponent = ({
   param1,
   param2
}) => {
       const updateVal = (e) => {
       console.log('v', e.target.value);  // will log 1 or 2... etc
       anotherFunctionInMyComponent(e.target.value);
   };

  return (
    <Form>
            <Form.Row>
                <Form.Group>
                  <Form.Label>Label 1</Form.Label>
                    <Form.Control
                        as="select"
                        className="rounded-lg-sc"
                        onChange={updateVal}
                    >
                      <option value={1}>opt 1</option>
                      <option value={2}>opt 2</option>      
                    </Form.Control>
                </Form.Group>
);
};
`

I hope this could work for someone else :smile:
