### ISSUE TITLE
Ability to set custom component for item

### ISSUE THREAD

**Issue by intpp** [react-bootstrap/react-bootstrap#2215]
We can use custom class for button but i think would be better if we can set custom component for item.

```javascript
<Pagination
    itemComponentClass={PaginationCustomItem}
/>

...

const PaginationCustomItem = (props) => (<div {...props}>{props.children}</div>)
```

**Comment by taion** [comment]
We're planning on replacing this entire API: https://github.com/react-bootstrap/react-bootstrap/issues/1758
