### ISSUE TITLE
NavDropdown and onMouseLeave broken between 0.29.5 and 0.30.2

### ISSUE THREAD

**Issue by acomito** [react-bootstrap/react-bootstrap#2219]
I have a `NavDropdown` that I need to have open the dropdown on hover, _but also stay open when hovering on the children_ (e.g. `MenuItems`, or `LinkContainer`). 

I was having trouble with this at first because I was using **onMouseOut** which closed the dropdown if you left the top-level nav item (the NavDropdown)-- but I was able to use **onMouseLeave**, which would keep the dropdown open on the nav item _and all of its children_. Great, problem solved.

I just updated from 0.29.5 to 0.30.3 and noticed this no longer works. I tested both MenuItems and MenuItems wrapped in LinkContainer and it seems broken either way. I downgraded to 0.30.2 and it still is not working, so at some point between 0.29.5 to 0.30.2 there seems to have been a change that is breaking my code.

Has anyone else experienced this? Here is some pseudo code:

```
//top-level imports
import React from 'react';
import { LinkContainer } from 'react-router-bootstrap';
import { Nav, NavItem, Row, NavDropdown, MenuItem } from 'react-bootstrap';


// INTERNAL COMPONENTS
//------------------------------

 class MyNavDropdown extends React.Component {
  constructor(props) {
      super(props);
      this.state = {
        isHovering: false
      };
    }

    render() {

    const onMouseOver = () => {
      console.log('onMouseOver fired');
      this.setState({ isHovering: true });
    };

    const onMouseLeave = () => {
      console.log('onMouseLeave fired');
      this.setState({ isHovering: false });
    };

    const dropDownClasses = this.state.isHovering ? 'open nav-links' : 'nav-links';

    return (
      <NavDropdown 
        className={dropDownClasses}
        onMouseEnter={onMouseOver}
        onMouseLeave={onMouseLeave}
        ref="myDropdown"
        eventKey="4" 
        title={this.props.title} 
        id="nav-dropdown" 
        noCaret={true}>
          {this.props.links}
      </NavDropdown>
    );
  }
};


const OpportunitiesLinks = () => (
            <MenuItem className="dropdownMenuItem" eventKey="4.2">Sponsors</MenuItem>
);


// EXPORTED COMPONENT
//------------------------------

export const PublicNavigation = ({festivals}) => (
  <Nav pullRight>
      <MyNavDropdown links={<OpportunitiesLinks />} title="Opportunities" />
  </Nav>
);
```

**Comment by taion** [comment]
We were previously inconsistent in which props we passed where.

@jquense would it make sense to special-case passing the mouse enter and leave events to the `<Dropdown>` instead of the toggle?

**Comment by grydstedt** [comment]
Any workarounds for this?

**Comment by taion** [comment]
It's a pretty simple PR to add the special-casing to `<DropdownButton>` and others...

**Comment by grydstedt** [comment]
@taion Cool. I'd do it, but I'm not super familiar with the internal workings here. I can try to take a look

**Comment by acomito** [comment]
@grydstedt No not right now. I'm unfortunately stuck on an early version (the one that is throwing a lot of unknown prop warnings).
