### ISSUE TITLE
Accordeon Doesn't collapse iterating via map

### ISSUE THREAD

**Issue by kurumkan** [react-bootstrap/react-bootstrap#2221]
am using react-bootstrap to create accordeon. Why my Accordeon doesn't work. It doesn't collapse, or slides down, it doesn't react on my clicks at all! Here is simplified version of my problem: 
Html:
`<div class="container" id="app">
</div>`

Javascript:
```
var Accordion = ReactBootstrap.Accordion;
var Panel = ReactBootstrap.Panel;

var AcEntry = React.createClass({
  render(){
    return(
      <Panel header={this.props.name} eventKey={this.props.id}>
        {this.props.text}
      </Panel>
      )
  }
});


var App = React.createClass({
  render(){
    var entries=[
      {id:1, name: "first entry", text:"first sample text"},
      {id:2, name: "second entry", text:"second sample text"}
    ];
    return (
      <Accordion>    
        {entries.map(function(entry){
          return <AcEntry name={entry.name} id={entry.id} text={entry.text} />
        })}
      </Accordion>    
    )
  }
});

ReactDOM.render(<App/>, document.getElementById("app"));
```

Here is my [codepen ](http://codepen.io/pbweb/pen/bwwjkW)

**Comment by jquense** [comment]
If you wrap Panel (AcPanel) you need to spread the all the props through. It doesn't do anything because you are swallowing the props injected by the Accordion in AcPanel

**Comment by AleksandrSidorov** [comment]
Just move Panel into your App component: 

`
var App = React.createClass({
  render(){
    var entries=[
      {id:1, name: "first entry", text:"first sample text"},
      {id:2, name: "second entry", text:"second sample text"}
    ];
    return (
      <Accordion>    
        {entries.map(function(entry){
          return (
            <Panel header={entry.name} eventKey={entry.id} key={entry.id}>
              <AcEntry text={entry.text} />
            </Panel>
          )
        })}
      </Accordion>    
    )
  }
});
`
