### ISSUE TITLE
Glyphicon inside Dropdown has possibly wrong classes

### ISSUE THREAD

**Issue by ozcelebi** [react-bootstrap/react-bootstrap#2223]
`<Glyphicon glyph="option-vertical" />` ends up in the DOM like this:
`<span class="glyphicon glyphicon-option-vertical"></span>`

But if that Glyphicon is inside a `<Dropdown>` like so:
```
<Dropdown>
  <Glyphicon glyph="option-vertical" bsRole="toggle" />
</Dropdown>
```
it ends up having different classes:
`<span class="dropdown-toggle dropdown-toggle-option-vertical"></span>`

this was not the case in version `0.29.5` but is in version `0.30.3`

**Comment by taion** [comment]
Dropdown toggles receive the parent `bsClass` for consistency. Wrap that Glyphicon with another toggle component if you don't want this behavior. You probably ought to do so anyway to avoid passing through unknown props.
