### ISSUE TITLE
How to insert nav-header  or nav-separator into nav

### ISSUE THREAD

**Issue by Liero** [react-bootstrap/react-bootstrap#2224]
I'm using bootstrap's dashboard theme and I have stacked navigation like this: https://bootstrap-themes.github.io/dashboard/docs/index.html#nav-bordered

However I have troubles to include headers and separators, which should look like this:

    <li class="nav-divider"></li>
    <li class="nav-header">Sections</li>

When I include something else than NavItem, then I get error:

```
warning.js:36 Warning: Unknown props `active`, `activeKey`, `activeHref` on <li> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop
    in li (created by App)
    in ul (created by Nav)
```

**Comment by taion** [comment]
You'd need to add your own component that removes those extraneous props before rendering the DOM component.

**Comment by Liero** [comment]
Just in case anybody needed:

```
export const NavHeader = (props) => {
    return <li className="nav-header">{props.header}</li>;
};
```

```
<Nav bsStyle="pills" stacked>
    <NavHeader header="Category1" />
    <LinkContainer to="/page1"><NavItem title="Item">Page 1</NavItem></LinkContainer>
</Nav>
```
