### ISSUE TITLE
Documentation: Remind users to import glyphicon in their css

### ISSUE THREAD

**Issue by cschoder** [react-bootstrap/react-bootstrap#2225]
In the documentation on glyphicon, it was very helpful to have the link out to the glyphicon page.  However, I forgot that I also had to add it to my CSS.  It would be helpful to mention in [the glyphicon components section]( https://react-bootstrap.github.io/components.html).  It would make it easier to get started using the feature.  Perhaps something like: 

> Remember that you are responsible for adding your CSS when using react-bootstrap.  Glyphicons use a font-family called 'Glyhpicons Halflings' which may need to be added or imported.

It could also be helpful to reference something like a sample glyphicons import line:
`@import url("//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css");`

**Comment by taion** [comment]
We already tell users they need to load the Bootstrap CSS. What's special about this section such that it alone would require an additional warning?

**Comment by cschoder** [comment]
Many other components work without the Bootstrap CSS, even if the display is slightly different. Glyphicons don't work at all without a CSS import.

**Comment by taion** [comment]
I don't really agree with that. Most of the styled components don't have any styling without the associated CSS. Meanwhile, in principle one could have totally separate glyphicon styling. I guess I'm not sure what's special about this use case in particular.

**Comment by Telokis** [comment]
@cschoder Even though this is very old I'd like to thank you because your import solved my issue. Thanks!

**Comment by davidnewcomb** [comment]
I came here looking too! Saw the `<Glyphicon>` which looked helpful but it has unexpectedly disappeared (#3395). My glyphs aren't showing in spite of having `import 'bootstrap/dist/css/bootstrap.min.css'` in my `index.js` and the bootstrap css being visible.

I couldn't find anything in the docs section of react-bootstrap about glyphs. So I guess they are unsupported now.

**Comment by AliSafari-IT** [comment]
you may add:

`import { Glyphicon } from 'react-bootstrap';
import 'bootstrap/dist/css/bootstrap.min.css';`
