### ISSUE TITLE
'npm run docs' Error: Cannot find module 'glob'

### ISSUE THREAD

**Issue by peterma** [react-bootstrap/react-bootstrap#2227]
As the title described, there should be a missing dependency declaration of module 'glob' in package.json. I am new to node, it is just a reasonable guess.

**Comment by jquense** [comment]
hi! did you run npm install first?

**Comment by taion** [comment]
It looks like we're missing `glob` in `package.json`. @peterma wanna make a quick PR?

**Comment by benbraou** [comment]
On my side, I don't have this issue and I don't have glob installed globally. Maybe the full logs and more information on the installation environment could help.
