### ISSUE TITLE
Popover in Modal loses its target after scroll

### ISSUE THREAD

**Issue by pulmo** [react-bootstrap/react-bootstrap#2228]
Hello! If in Modal I will open Popover and scroll window, it will look like this:

![_001](https://cloud.githubusercontent.com/assets/13828946/18740765/2a1fe978-80b4-11e6-9e57-dfd956213c60.png)

Can I avoid that?
About code: I just took popovers from https://react-bootstrap.github.io/components.html#popovers-positioned-scrolling and paste them in https://react-bootstrap.github.io/components.html#modals-live

**Comment by taion** [comment]
You need to set the `container` appropriately.
