### ISSUE TITLE
How to set activekey of the Nav to be inactive

### ISSUE THREAD

**Issue by captainwooder** [react-bootstrap/react-bootstrap#2230]
In a case, I need to set the Nav with a active item to a Nav with none of it's items is active. 
<Nav bsStyle="pills" stacked activeKey={1} onSelect={handleSelect}>

I don't know how to handle it!!   I have tried serveral ways, such as setting the active key to a non-existend key:-1 or 0.But it didn't work!

**Comment by jquense** [comment]
set it to undefined or null?
