### ISSUE TITLE
Allow Popover to be placed above a scrollable container

### ISSUE THREAD

**Issue by nareshbhatia** [react-bootstrap/react-bootstrap#2231]
The example titled [Positioned popover components in scrolling container](https://react-bootstrap.github.io/components.html#popovers-positioned-scrolling) clips the popover to the container. This approach requires the user to scroll the container in order to see the hidden parts of the popover. Is there an option to let the Popover be placed above the scrollable container so that all of it can be seen without scrolling?

Incidentally the raw Bootstrap Popover behaves exactly like that. Please see my JSBin [here](https://jsbin.com/wacaxacoxu/edit?html,css,output). Also note that the select control in this example pops up above the scrollable container.

**Comment by jquense** [comment]
yes use the container prop. the default should do what you want

**Comment by nareshbhatia** [comment]
Oh I didn't realize that container prop is available - it's not in the docs. So would I say something like `container = "body"`?

**Comment by nareshbhatia** [comment]
Confirmed that Popover does not have a container property. The following code produces a warning:

```
<Popover
    id="popover-basic"
    title="Popover right"
    placement="right"
    container={this}
>
```

The warning is:
> Warning: Unknown prop `container` on div tag. Remove this prop from the element.

Surprisingly enough, the exact same code from the docs example is triggering a popup that is on top of the scrollable container. I can't understand why! Here's that code:

```
<OverlayTrigger container={this} trigger="click" placement="bottom" overlay={
    <Popover id="popover-positioned-scrolling-bottom" title="Popover bottom">
        <strong>Holy guacamole!</strong>
    </Popover>
}>
    <Button>Holy guacamole!</Button>
</OverlayTrigger>
```

Here's the result:

![image](https://cloud.githubusercontent.com/assets/1220198/18785723/e39e9e36-8167-11e6-99fb-41927467de4f.png)

**Comment by jquense** [comment]
the Overlay and OverlayTrigger have the `container` prop, look at the code in the examples on the documentation site

**Comment by nareshbhatia** [comment]
Yep, I know that. Unfortunately, I am not interested in OverlayTrigger. I am interested in the raw Popover - that's where I need the container property exposed. Here's some context:

I am using the [react-bootstrap-date-picker](https://github.com/pushtell/react-bootstrap-date-picker) that uses the Popover to display a popup calendar (there is no Overlay and OverlayTrigger involved). When I put this control in a scrollable panel, it clips to the container:

![image](https://cloud.githubusercontent.com/assets/1220198/18787753/2d73d562-8172-11e6-8a35-4cf02864f555.png)

I am trying to work with the author to fix this issue (https://github.com/pushtell/react-bootstrap-date-picker/issues/33), so it involves understanding the behavior of the react-bootstrap Popover. As far as I can tell, there are two things involved
1. The specification of the container, which determines where in the DOM the Popover will be placed.
2. Absolute positioning of the Popover. I don't know how the coordinates for the absolute positioning are calculated - I am assuming they are relative to the container that is specified. Also this probably assumes that the the container is positioned 'relative' and nothing else in between is position 'relative'. Is this correct?

What I don't understand is which of these two things is responsible for allowing the popover to show outside of the scrolling region - does the container have to be outside the scrolling container, or does the relative parent have to be above the scrolling container.

Any insights would be much appreciated.

**Comment by jquense** [comment]
The "raw" popover is just static markup it has no positioning logic in it. It's just a div with classes. The thing that is analgous to normal bootstraps popover jquery plugin is the Overlay component. If you want to take advantage of the bootstrap positioning logic to display a Popover component next to another component you need to use Overlay or OverlayTrigger, otherwise you need to calculate the correct position yourself and pass it  the popover as a style.

**Comment by nareshbhatia** [comment]
@jquense This is VERY helpful. Thanks for your help. I am closing this issue for right now and see what I can do on the date-picker side.
