### ISSUE TITLE
Global Modal Open/Close

### ISSUE THREAD

**Issue by jpmelnik** [react-bootstrap/react-bootstrap#2232]
Hi

Can I open/close modal box from others components buttons?

I have only once modal box for the entire app. I wish to set dynamic modal data and open it from differents components buttons.

So, I have the following components

GlobalModalBox, the Global bootstrap modal,
Component 1, the open modal button One,
Component 2, the open modal button Two,
Component N, the open modal button N.

When I click on button one => GlobalModalBox => Open.
When I click on button two => GlobalModalBox => Open.,

Thanks.

**Comment by taion** [comment]
You'd manage this the same way you manage any other global state with React, e.g. with a Flux library. This doesn't have anything to do with React-Bootstrap specifically.
