### ISSUE TITLE
Question: react-native support

### ISSUE THREAD

**Issue by dmatteo** [react-bootstrap/react-bootstrap#2234]
Hey folks, it's been a while since I stopped by :)

I just started a project where I used `react-bootstrap` to fast prototype a mobile webapp, and that got me thinking on using it to build a native mobile application, with `react-native`.

Googling and NPMing (it's totally a verb) didn't return any interesting result for using `react-bootstrap` in the `react-native` context, so now I'm left wondering...

* Have you ever considered working in that direction?

* Would you even be interested in pursuing the native mobile path or do you see it as a stretch?

**Comment by taion** [comment]
It doesn't really make any sense. Bootstrap is mostly an HTML/CSS framework for web development. While there may be similar widget libraries for React Native, "Bootstrap" for React Native isn't a thing.

**Comment by dmatteo** [comment]
I tend to disagree with the "doesn't really make any sense" point of view, but I get that you're not interested in exploring the idea :)

Thanks for replying, and have a good one!
