### ISSUE TITLE
Item between header and body in Panel

### ISSUE THREAD

**Issue by grydstedt** [react-bootstrap/react-bootstrap#2235]
A couple of times I've been wanting to put something between the panel body and the panel heading, usually an Alert. With the current Panel interface this is pretty tricky to do. Is there a way we could introduce this a way of doing this? Perhaps by getting the Panel api closer to the Modals with Panel.Body?

**Comment by taion** [comment]
That's the idea behind https://github.com/react-bootstrap/react-bootstrap/pull/1769

**Comment by grydstedt** [comment]
Great, thanks
