### ISSUE TITLE
File input alignment

### ISSUE THREAD

**Issue by cdietze** [react-bootstrap/react-bootstrap#2236]
Hi!
I think this issue is really coming from the bootstrap roots, but here it goes.
The vertical alignment of inputs of type file are off when used in a horizontal form.
Chrome:
![Chrome](https://cloud.githubusercontent.com/assets/845979/18875872/d2f1ab7e-84c7-11e6-8cd8-7f0668385e90.png)
Firefox:
![Firefox](https://cloud.githubusercontent.com/assets/845979/18876025/63fa59e0-84c8-11e6-9d83-d12a68d6d658.png)

When I add `padding-top: 7px` it looks much nicer.

**Comment by taion** [comment]
This is just the Bootstrap CSS. Nothing directly related to this library.

**Comment by cdietze** [comment]
FWIW: This won't get fixed in Bootstrap v3: https://github.com/twbs/bootstrap/issues/19082
