### ISSUE TITLE
zombie title remains when using onClick & react-router-redux

### ISSUE THREAD

**Issue by Jan-Jan** [react-bootstrap/react-bootstrap#2238]
Thank you for all the hard work with react-bootstrap.

I found a bug when using `<li onClick={() => dispatch(push(new_route))} title="boo">far</li>`.
If I click on this the router works great, but the title then remains active/visible across all subsequent screens. This gives me the impression that the <li> has been cleared away but the title has been come a zombie.

Anyone else encounter this bug?

**Comment by taion** [comment]
This doesn't seem to have anything to do with React-Bootstrap.
