### ISSUE TITLE
textarea size (height) prop

### ISSUE THREAD

**Issue by crobinson42** [react-bootstrap/react-bootstrap#2239]
How would one use the component to set `textarea` input height?

```
<FormGroup>
       <FormControl
           height="200px"
           componentClass="textarea"
           placeholder={this.props.placeholder}
           value={this.state.value}
           onChange={this.handleChange}
         />
</FormGroup>
```

**Comment by jquense** [comment]
`<FormControl componentClass="textarea" style={{ height: 200 }} />`

they just pass thought the props so you can style it however you would style a textarea normally, inline or via css

**Comment by dschinkel** [comment]
what if I don't want to hard code styles inline?  I don't like doing style={{ height: 200 }}

**Comment by jquense** [comment]
Use css then. You can style however you'd like :)

**Comment by dschinkel** [comment]
Let me explain a different way.  I like the React bootstrap styling and I want that applied Tony form control (input field).  I just want to control and set the width using a CSS class instead of having to hard Code a style using style={{width:300}}.  I don't like magic strings anywhere.

**Comment by jquense** [comment]
Right so use a css class...

**Comment by dschinkel** [comment]
I did and all the bootstrap styles were no longer working on that field after using bsClass

**Comment by jquense** [comment]
Your over thinking it, just add width-300 class to the className prop along with the ft-password class, don't use bsClass that's for bootstrap class prefixes

**Comment by dschinkel** [comment]
I posted wrong, that's exactly what I tried actually:

<FormControl
            bsSize="small"
            className="ft-password width-300"
            componentClass="input"
            placeholder="Enter Password"
            type="text"
          />

And it didn't affect it at all.

**Comment by dschinkel** [comment]
maybe something's f'd up with create-react-app.  They make you put your styles in src/index.css.  And magically they pick that up and bundle it.  I wonder if it's just not there.

**Comment by dschinkel** [comment]
nope, it's not that I put in a { color:  yellow } and it worked.  looks like react-bootstrap isn't working with my width-300.  I'll try another class and see if bootstrap picks it up

**Comment by dschinkel** [comment]
disregard, I thought I could leave out the . with .sss.  It's fine.

**Comment by Billy-** [comment]
Just trying to add maxWidth and height to my text area... Looks like the inline styles are being overridden and height/width set when resizing... Any idea why? I had a little look at the code for FormControl and doesn't seem to be happening there...

**Comment by jquense** [comment]
Any behavior here is the browser behavior for text areas.  I'd check MDN for any quirks

**Comment by bill-dubay** [comment]
<ReactBootstrap.FormControl componentClass="textarea" rows={4} />

**Comment by aelex91** [comment]
@bill-dubay where do I write this <ReactBootstrap.FormControl componentClass="textarea" rows={4} />?

I basically have a textarea like this:
<textarea value={this.state.message} rows='8' cols='50' name='message' placeholder='message' onChange={this.handleChange} />

I thought the "rows" and cols" would work fine?

**Comment by camleng** [comment]
You can just write
```html
<textarea value={this.state.message} rows={8} cols={50} 
name='message' placeholder='message' onChange={this.handleChange} />
```

**Comment by zhao-ji** [comment]
Hi @camleng , can you adjust the rows when input in textarea? I tried to update rows dynamically, but it's failed, even set the style to `height: unset`.

**Comment by Unclemortuary** [comment]
> You can set the height like this. This example sets a height of 4 rows:
> 
> <ReactBootstrap.FormControl componentClass="textarea" rows={4} />

It's not gonna work if you have your `FormControl` surrounded by `FloatingLabel`. In such case you have to unset the height of FormControl (like `style={{ height: 'unset' }}`) to make `rows` property work
