### ISSUE TITLE
<FormControl componentClass="text" /> control broken?

### ISSUE THREAD

**Issue by crobinson42** [react-bootstrap/react-bootstrap#2240]
It appears a "controlled component", is not. Is this expected behavior, where the component's method `setValue` changes the state but the `Input` value in the DOM does not reflect?

```js
setValue(v) { this.setState({ value: v }) }

handleChange(e) { this.setState({ value: e.currentTarget.value }) } 
```

```jsx
<FormControl
         componentClass="text"
         value={this.state.value}
         onChange={this.handleChange}
         /> 
```

**Comment by jquense** [comment]
hi there, "text" is not the componentClass that's its `type`, that code would render a `<text />` which isn't a thing,  or at least not the thing you want

**Comment by crobinson42** [comment]
@jquense *typo, sorry. I do of course include `type="text"` (https://www.dropbox.com/s/tl5c54vk7or3ur5/Screenshot%202016-09-29%2021.22.42.png?dl=0). 

So, is this expected behavior in my example?

**Comment by ivan-kleshnin** [comment]
@jquense a little question if you don't mind.

`componentClass` is such a confusing name. There are JS classes, HTML classes and this is not about them but about tag names instead... 😕 
Do I miss some intention behind this?

**Comment by jquense** [comment]
the name refers to the argument you supply to `createElement(componentClass, props)`. It refers to the class of a react component as opposed to an element or instance. You can use js classes here, its only a bit weird b/c the "classes" for native react components (e.g. DOM) are string identifiers instead of actual classes.

**Comment by ivan-kleshnin** [comment]
@jquense thanx!
