### ISSUE TITLE
Dropdowns are broken in release 0.30.4

### ISSUE THREAD

**Issue by xveganxxxedgex** [react-bootstrap/react-bootstrap#2245]
With the latest release, the dropdowns (both buttons and navigation components) are no longer expanding on click. This bug is happening on the documentation:

https://react-bootstrap.github.io/components.html#btn-groups-nested
https://react-bootstrap.github.io/components.html#navs-dropdown

**Comment by taion** [comment]
Same as https://github.com/react-bootstrap/react-bootstrap/issues/2243. It will work if you reinstall.
