### ISSUE TITLE
Tab does not allow title to be set in custom component

### ISSUE THREAD

**Issue by akarve** [react-bootstrap/react-bootstrap#2246]
react-bootstrap@0.30.4 

Tab component does not allow title to be set by composition.

Example:
Note that the tabs appear without any title whatsoever.

```javascript
import React from 'react';
import {Button, Col, Row, Tabs, Tab} from 'react-bootstrap';
module.exports = React.createClass({
  render() {
    return (
      <Tabs defaultActiveKey={1} id='example-tabs'>
        <CustomTab eventKey={1} titleString='First'/>
        <CustomTab eventKey={2} titleString='Second'/>
        <CustomTab eventKey={3} titleString='Third'/>
      </Tabs>
    );
  }
});


const CustomTab = (props) => (
  <Tab eventKey={props.eventKey} title={props.titleString}>
    <p>Tab {props.eventKey} content</p>
  </Tab>
);
```

**Comment by taion** [comment]
That's correct and mostly intentional. Use the `title` prop. Or else use the lower-level API.

**Comment by jquense** [comment]
yeah you can't compose the tab components as they are not real rendered components. you can use the lower level tab components, tab container, content and pane, for that

**Comment by akarve** [comment]
OK. The challenge with the lower-level tab components is that the tab title (`NavItem`) and tab content (`Tab.Pane`) are peers that cannot be composed into a single component. As a result one has to clumsily manage repeated states in a common ancestor.

For example suppose I have three tabs (X, Y, and Z) and, depending on whether or not a tab is waiting on an ajax call, I want to display a progress icon in the tab's title. The only way to do this is to have `Tab.Pane` (or one of its descendants) call back and `setState` on the common ancestor, leading to three different waiting states in the ancestor: `xWaiting, yWaiting, and zWaiting`.

A much cleaner abstraction would compose the tab title and tab content together so that one component fully encapsulates all of the data to render one tab. In this case there is only a component local `waiting` state needed to render each tab title.

**Comment by jquense** [comment]
What you are seeing is a technical limitation of the API, there isn't any clean way to do want you want, because the Tabs component reads the `title` prop from the children, it doesn't render it. 

`Tabs` is put on top of of the lower level components so if you want to encapsulate and abstract some logic in a way that makes sense for your app go for it, that's why we try and expose flexible apis

**Comment by akarve** [comment]
Understood. I mean to say that even with the lower level API (`NavItem, Tab.Pane`) there is no way to encapsulate tab title and content into a singular component. This stems from the fact that bootstrap implements the tabs as `li` children of a `ul`, and tab content as `div` children of a parent `div`. Since tab title and tab content expect different parents there is no way to compose them and one ends up with a ton of state in the common ancestor. Very messy as all of the state for the tab titles ends up in the ancestor.

Conceptually, tab title and tab content should be encapsulated in one entity but the backing DOM elements in Bootstrap's implementation make it impossible. Fixing this would require bootstrap to implement tabs differently. I am not asking for this :). It's nevertheless a very interesting case study in how data flow depends on the underlying DOM.
