### ISSUE TITLE
Dropdown not working

### ISSUE THREAD

**Issue by onlyongunz** [react-bootstrap/react-bootstrap#2248]
Idk why, but i've tried your example and tried on my own too, and no luck.

``` html
<DropdownButton bsSize="xs" title={<span className="fa fa-eye"/>} id="visibility">
   <MenuItem>Private, Unlisted</MenuItem>
   <MenuItem>Public, Unlisted</MenuItem>
   <MenuItem>Public, Listed</MenuItem>
</DropdownButton>
```

The button shows, but never dropdowning on clicked. Thank you.

**Comment by taion** [comment]
See last couple closed issues. Should work on reinstall, or else downgrade to v0.30.3 (which is tagged latest on npm) until we get a new release out.

**Comment by onlyongunz** [comment]
Installed the v0.30.3. Problem solved.

**Comment by jstray** [comment]
I am having the same problem. Downgrading to 0.30.3 did not solve it :(

**Comment by ekropotin** [comment]
Hello. Have the same issue with 0.31.5 and React 16. Any known workaround for this?

**Comment by ganesharulanantham** [comment]
@ekropotin I have the issue for Dropdown do u have solution?

**Comment by ganesharulanantham** [comment]
@taion Issue exist for React 16 can you reopen this?

**Comment by ekropotin** [comment]
@ganesharulanantham In my particular case the problem was that I used react-bootstrap with bootstrap 4. I switched to bootstrap 3 and the problem gone.

**Comment by tatmanblue** [comment]
how do I downgrade to bootstrap 3?

and Im not sure why this should be closed.  its a problem with bootstrap 4

**Comment by GustavoHGS** [comment]
For me it worked simply downgrading bootstrap version from v4 to v3.

**Comment by saberprashant** [comment]
Hey, if anyone wants to downgrade from v4 to v3 OR simply want that grid button to work,
then go to your public/index.html of you react project and paste this bootstrap CSS link for v3:

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

Just do this, and you can use the react-bootstrap module as it is.
Hope this helps everyone!

**Comment by dayangxiang** [comment]
Looks like @saberprashant missed the link
```
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
```
I copied it from https://react-bootstrap.github.io/getting-started/introduction/#install.

This works for me.

**Comment by kmoec** [comment]
@dayangxiang It works for me as well..except that I'm getting two down arrows instead of one. If I use "noCaret" attribute, I get one. And the font size are a lot smaller than it was and I have to use header tag to make it decent.

<FormGroup>
        <ControlLabel><h4>{label}</h4></ControlLabel>
        <DropdownButton
            bsStyle={bsStyle}
            title={title}
            noCaret
            key={id}
            id={'dropdown-${id}'}>

            {
                menuItemArray.map((item,key) => {

                    return (
                        <MenuItem eventKey={String.valueOf(key)}><h4>{item}</h4></MenuItem>
                    );

                })
            }
        </DropdownButton>
    </FormGroup>
