### ISSUE TITLE
OverlayTrigger do not work

### ISSUE THREAD

**Issue by frontenddeveloping** [react-bootstrap/react-bootstrap#2249]
This is code doesn't work as expected(Popover never shown):
https://jsfiddle.net/frontenddeveloping/1onn363q/1/
```
<OverlayTrigger 
    overlay={<Popover id="123" title="Some title">Some text</Popover>}
    placement="left"
    trigger={["hover", "focus"]}>
    <ExternalLink href="https://example.com">
            123
    </ExternalLink>
</OverlayTrigger>
```

This is code works as expected(Popover shown):
https://jsfiddle.net/frontenddeveloping/1onn363q/2/
```
<OverlayTrigger 
    overlay={<Popover id="123" title="Some title">Some text</Popover>}
    placement="left"
    trigger={["hover", "focus"]}>
    <span>
        <ExternalLink href="https://example.com">
            123
        </ExternalLink>
    </span>
</OverlayTrigger>
```

The little big difference - single span.
Version: 0.30.3/0.30.4

**Comment by taion** [comment]
Your link needs to handle the mouse events passed through from `<OverlayTrigger>`.

**Comment by menghao199339** [comment]
I have also issue.
handle the mouse events?  Can you speak detail

**Comment by wozzo** [comment]
For anyone else coming here:
The `<ExternalLink>` element in the example above must accept props for mouse events, such as `onClick` and handle them.

Assuming `<ExternalLink>` was something like

```javascript
function ExternalLink(props) {
   const {href, children} = props
    return <a href={href}>{children}</a>
}
```

to fix it would become

```javascript
function ExternalLink(props) {
    const {href, children, ...allTheOtherPropsIncludingMouseEvents} = props
    return <a href={props.href} {...allTheOtherPropsIncludingMouseEvents}>{props.children}</a>
}
```
