### ISSUE TITLE
Add new Modal not support customize fields

### ISSUE THREAD

**Issue by sunnyzhang66** [react-bootstrap/react-bootstrap#2255]
Hi 
we are using your react table on our settings page, one of trouble I have is Add Modal not support customize columns.

First table column is textbox which is fine, second column is dropdown, third column is bootstrap multiselect which is dropdown have multi-checkboxes inside.

how do I use your Add new Modal support customize column control inside your new Modal?

Thanks
Sunny

**Comment by jquense** [comment]
sorry unfortunately i'm not sure what your asking here...you can put whatever you like inside a Modal. Maybe a screenshot of what you want, or code?

**Comment by sunnyzhang66** [comment]
Thanks for response Jason.

screenshot below:

Currently table  inline edit mode : Name is textbox, SubEntity Group is dropdown, Entities is multi dropdown with checkboxes, and positioning Message also multi-dropdown.



if I click "New" button, I expected Add New Modal also have same controls, instead I got all textboxes instead .


is there anyway I can populate correct controls like dropdown, multi-dropdown inside "Add New Modal" ?


Thanks

Sunny

[cid:e21c3a3b-e938-486b-beaf-1b4c3627ccbb]

________________________________

**Comment by taion** [comment]
That sounds like an issue with your CSS.
