### ISSUE TITLE
Manually calling a React.PropTypes validation

### ISSUE THREAD

**Issue by HermannHH** [react-bootstrap/react-bootstrap#2257]
I have created a rails app and installed react 15.3.2 alongside browserify 13.1.0. After making sure that I', able to create basic components, I installed react-bootstrap 0.30.5 using npm install react-bootstrap --save.

When I try to load a modal (for example) I am presented with 32 warning messages telling me that I'm manually calling a React.propType validation.

Here is my component (tester.js):

```
import { Modal } from 'react-bootstrap';
let Tester = React.createClass({
  render() {
    return (
      <Modal show={true}>
        <Modal.Body>
          <Modal.Body>Hello world</Modal.Body>
        </Modal.Body>
      </Modal>
    );
  }
});
module.exports = Tester;

```

**Comment by jquense** [comment]
this has been fixed for a while, try deleting your node_modules folder and doing a fresh install.

**Comment by HermannHH** [comment]
I actually just managed to fix this. Or sort of. I was including 'react-server' in my application.js file. Removing react-server seems to remove the warning messages as well.
