### ISSUE TITLE
Modal size warning

### ISSUE THREAD

**Issue by Cemgoktugsorgun** [react-bootstrap/react-bootstrap#2259]
While the default size of a modal is "md", when I try to set the size of a modal to "md" , I get the following warning

`Warning: Failed prop type: Invalid prop 'bsSize' of value 'md' supplied to 'ModalComponent', expected one of ["lg","large","sm","small"].`
(ModalComponent is a wrapper component that passes  'bsSize' to modal)

Is it intended behaviour?

**Comment by jquense** [comment]
yes there are only two options for the size: large and small. if you want the normal size don't provide a size (or set it to `undefined`)
