### ISSUE TITLE
Draggable

### ISSUE THREAD

**Issue by rituvesh** [react-bootstrap/react-bootstrap#2260]
Hi,
Is it possible to have some Boolean property to make Modal draggable so that background text can be readable? Or please let me know if you already have some thing.

Regards,
Rituvesh

**Comment by jquense** [comment]
Hi, draggable Modals this isn't supported by bootstrap. If you need that behavior you can try use the lower level `react-overlays` package to more quickly build your own modal component to your needs!

**Comment by rituvesh** [comment]
Thanks for the reply!
