### ISSUE TITLE
How to set a color for the backdrop background of the modal?

### ISSUE THREAD

**Issue by nicotsou** [react-bootstrap/react-bootstrap#2262]
Hi guys, I have an issue with the modal component and I need your help. I want to change the background color of the modal backdrop. I want to have multiple modals in the page and each of them to have a specific color.

The problem that I have is that `modal-backdrop` is not enclosed to the division that gets the id of the modal:

![image](https://cloud.githubusercontent.com/assets/1083396/19182292/1a80d324-8c7b-11e6-99ba-01a0d522f7c5.png)

One solution is to use javascript when the component mounts and to put a specific selector to its backdrop `div`. Is there any better way to accomplish this?

**Comment by taion** [comment]
Use the lower-level react-overlays API.

**Comment by benmonro** [comment]
@nicotsou you can use bsClass like this: https://github.com/react-bootstrap/react-bootstrap/issues/2282#issuecomment-253838628
