### ISSUE TITLE
Warning: Unknown prop `active` on <div> tag

### ISSUE THREAD

**Issue by asicfr** [react-bootstrap/react-bootstrap#2263]
With react-router-bootstrap 0.23.1
i have some warning on Col div : 

    Warning: Unknown prop `active` on <div> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
        in div (created by Col)

Here is the render of my component : 

    <Row>
    	<Col xs={2}>
    		<Image src={pictoTitre} />
    	</Col>
    	<Col onClick={() => goToElementId(this.props.offreElementId) } 
    		xs={1} mdOffset={1} lgOffset={2} 
    		className="lien-titre text-right hidden-xs hidden-sm visible-lg visible-md">
    		{this.props.offre}
    	</Col>
    	<Col onClick={() => goToElementId(this.props.simulateurElementId) } 
    		xs={1} sm={2} md={1} 
    		className="lien-titre text-right hidden-xs hidden-sm visible-lg visible-md">
    		{this.props.simulateur}
    	</Col>
    	<Col onClick={() => goToElementId(this.props.faqElementId) } 
    		xs={1} sm={1} md={1} className="lien-titre text-right hidden-xs hidden-sm visible-lg visible-md">
    		{this.props.faq}
    	</Col>
    
    	<LinkContainer to={this.props.routeToPersonalInfo}>
    		<Col xs={3} lg={2} className="text-right">
    			<button className="button-jenProfite btn-block hidden-xs hidden-sm visible-lg visible-md">
    				{this.props.jenprofite}
    			</button>
    		</Col>
    	</LinkContainer>
    	<Col xs={3} className="text-right">
    		<button 
    		  onClick={() => goToElementId(this.props.monEspaceId) }
    		  className="button-monEspace btn-block hidden-xs hidden-sm visible-lg visible-md">
    			{this.props.monespacemax}
    		</button>
    	</Col>
    </Row >

Have you any idea to resolve that ? 

Thx

**Comment by jquense** [comment]
you can put the link Container around the button not the Col

**Comment by asicfr** [comment]
Does not resolve the warning.

**Comment by jquense** [comment]
sorry I thought you were using the bootstrap `Button` component.

The LinkContainer is ment to be used with bootstrap button, navitems, menuitems, etc. if you want to use it with plain html elements you need to create your own Button wrapper that doesn't pass through the `active` prop to the dom element
