### ISSUE TITLE
Consider making NavDropdown title its own element instead of a prop.

### ISSUE THREAD

**Issue by ryuhhnn** [react-bootstrap/react-bootstrap#2264]
Currently the syntax for creating a NavDropdown would be:
`<NavDropdown eventKey={1} title="Dropdown" id="basic-nav-dropdown"></NavDropdown>`

but could we consider pulling it out into something like:
`<NavDropdown.Title></NavDropdown.Title>`

so that it can support more styles such as adding images and glyphs?

**Comment by jquense** [comment]
hi, `title` supports any node, so you can do `title={<span><Glyphicon /> foo</span>}` if you want. We probably won't split it out as a component though since that would be really similar to just the lower level Dropdown component

**Comment by ryuhhnn** [comment]
Oh sorry must have overlooked this! Thank you!
