### ISSUE TITLE
Modal: Warning Unknown Props

### ISSUE THREAD

**Issue by lebeier** [react-bootstrap/react-bootstrap#2265]
Ok I have read the main thread regarding the unknown props fixes. After upgrading to latest react-bootstrap 0.30.5 and react 15.3.1, I am still seeing this warning related to modal.

`Unknown props show, onEntering, onHide, backdrop,keyboard, enforceFocus, manager, renderBackdrop, bsClass, dialogComponent, dialogClassName on <div> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop`

So I am wondering has anyone verified that the issue has been fixed for modal?

**Comment by taion** [comment]
You can see that this doesn't arise from our modal examples – make sure you're using the right child element types under the modal.

**Comment by jquense** [comment]
also try nuking `node_modules` and reinstall everything
