### ISSUE TITLE
Overlay does not work as expected in SVG in Google Chrome

### ISSUE THREAD

**Issue by varghesep** [react-bootstrap/react-bootstrap#2266]
I have an SVG app, and uses [ForeignObject](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/foreignObject) to display a [overlay](https://react-bootstrap.github.io/components.html#overlays). I have tried basic **overlay** as well as **overlaytrigger**.

The overlay works as expected in _Microsoft Edge_ browser by positioning the popup next to the component where it is clicked. But it does not in the _Google Chrome_ browser. It is positions at some random location.

I can't see this problem if I use the overlay outside of the **svg** element in any browser.

**Comment by taion** [comment]
ForeignObject is broken on Chromium, see issues on their issue tracker – nothing we can do here.
