### ISSUE TITLE
<FieldGroup> vs. <FormGroup>? What's the difference?

### ISSUE THREAD

**Issue by wzup** [react-bootstrap/react-bootstrap#2267]
You're not clear about it. The only [phrase ](http://react-bootstrap.github.io/components.html#forms-controls)you provide:

> Examples of standard form controls supported in an example form layout, using a custom `<FieldGroup>` component. 

What is `<FieldGroup>`? Why did you suddenly started using it in place of `<FormGroup>`? Before all your text were about `<FormGroup>` and suddenly `<FieldGroup>` without any reasonable explanation.

`<FormGroup>`:
```
      <form>
        <FormGroup
          controlId="formBasicText"
        >
          <ControlLabel>Working example with validation</ControlLabel>
          <FormControl
            type="text"
            placeholder="Enter text"
          />
        </FormGroup>
      </form>
```

**vs.**

`<FieldGroup>`
```
<form>
    <FieldGroup
      id="formControlsText"
      type="text"
      label="Text"
      placeholder="Enter text"
    />
</form>
```

**Comment by jquense** [comment]
FieldGroup doesn't exist,  its shown (along with its implementation)  in a single doc  comment as an illustration of how you can combine the form components into higher level components for your specific app needs
