### ISSUE TITLE
<Col></Col> not inserting default bsClass '.col'

### ISSUE THREAD

**Issue by alecperkey** [react-bootstrap/react-bootstrap#2273]
# `bsClass` prop not working on `<Col>` (and other elements?)

![image](https://cloud.githubusercontent.com/assets/1241041/19253141/03a910b4-8f17-11e6-87d8-acfecdd2c3f9.png)
![image](https://cloud.githubusercontent.com/assets/1241041/19253147/10c87a78-8f17-11e6-8158-b2ce12b084d5.png)

"version": "0.30.5"

## To my understanding this line is not working:

> `export default bsClass('col', Col);`
_https://github.com/react-bootstrap/react-bootstrap/blob/v0.30.5/src/Col.js#L220_

```
<Grid>
  <Row>
    <Col></Col>
    <Col></Col>
  <Row>
<Grid>
```
### should render to (?)
```
<div class="container">
    <div class="row">
        <div class="col"></div >
        <div class="col"></div >
    </div>
</div>
```

### however, I am getting:
```
<div class="container">
    <div class="row">
        <div class></div >
        <div class></div >
    </div>
</div>
```

this throws off the margins on everything and causes me to lose the left 15 pixels of every row.. since my .row has `margin: 0, -15px`

The docs say `bsClass` is default to 'col' http://react-bootstrap.github.io/components.html#grids-props-col

...but `.col` is not a bootstrap class.

there is only:

```
.col-xs-1, .col-sm-1, .col-md-1, .col-lg-1, .col-xs-2, .col-sm-2, .col-md-2, .col-lg-2, .col-xs-3, .col-sm-3, .col-md-3, .col-lg-3, .col-xs-4, .col-sm-4, .col-md-4, .col-lg-4, .col-xs-5, .col-sm-5, .col-md-5, .col-lg-5, .col-xs-6, .col-sm-6, .col-md-6, .col-lg-6, .col-xs-7, .col-sm-7, .col-md-7, .col-lg-7, .col-xs-8, .col-sm-8, .col-md-8, .col-lg-8, .col-xs-9, .col-sm-9, .col-md-9, .col-lg-9, .col-xs-10, .col-sm-10, .col-md-10, .col-lg-10, .col-xs-11, .col-sm-11, .col-md-11, .col-lg-11, .col-xs-12, .col-sm-12, .col-md-12, .col-lg-12 {
  position: relative;
  min-height: 1px;
  padding-right: 15px;
  padding-left: 15px;
}
```
source: https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.css

Which is fine... I can add `.col` to the list and have it inherit props for `.col-xs-12`

Otherwise I have to either:

A. ctrl replace all `<Col>` to `<Col xs={12}>` and make sure I didn't miss any like `<Col className="special-app class">`

B. make my own HOC `<Col>` which injects xs={12} as prop to all React-Bootstrap `<Col>` if no size prop is already. And update all my imports...

**Comment by jquense** [comment]
Column components required you specified a size, we don't render invalid classes so if you don't put a size it's not going to render any classes (since as you point out `col` isn't a bootstrap class)

**Comment by alecperkey** [comment]
Would be an enhancement then. At least for my use case.

At least the docs could be fixed, right?

![image](https://cloud.githubusercontent.com/assets/1241041/19277843/2e505830-8fa9-11e6-8efb-a404d44aa6b3.png)

**Comment by jquense** [comment]
its not being deprecated. `bsClass` isn't a className, it's the prefix used to _derive_ css classes. so if you change the `bsClass` of Col `<Col bsClass='foo' sm={12} />` it will generate: `<div class='foo-sm-12' >`. 

a Column component requires a size specified, so yes it isn't really different from a plain div if you don't provide one, but you are also using component incorrectly. There is no size that makes sense as a default, because that is extremely app dependent.

**Comment by alecperkey** [comment]
I see. this is more of a docs issue then.

'default' is understood as being passed in automatically. 
...but it will only be there if you also provide one of many possible suffixing props.

Anyway I've switched my imports to a custom component like so. Does it look alright to you?

```
import React, {PropTypes} from 'React'
import {Col} from 'react-bootstrap';
import _ from 'lodash'

const bsSizeProps = [
  'xs',
  'sm',
  'md',
  'lg',
  'xsHidden',
  'smHidden',
  'mdHidden',
  'lgHidden',
  'xsOffset',
  'smOffset',
  'mdOffset',
  'lgOffset',
  'xsPush',
  'smPush',
  'mdPush',
  'lgPush',
  'xsPull',
  'smPull',
  'mdPull',
  'lgPull'
]

const _Col = (props) => {
  const alreadyHas =  _.some(bsSizeProps, sizeProp => _.has(props, sizeProp))

  if (alreadyHas)
    return <Col {...props}>{props.children}</Col>
  else
    return <Col {...props} xs={12}>{props.children}</Col>
}

_Col.propTypes = {
  children: PropTypes.node,
  componentClass: PropTypes.elementType,
  xs: PropTypes.number,
  sm: PropTypes.number,
  md: PropTypes.number,
  lg: PropTypes.number,
  xsHidden: PropTypes.bool,
  smHidden: PropTypes.bool,
  mdHidden: PropTypes.bool,
  lgHidden: PropTypes.bool,
  xsOffset: PropTypes.number,
  smOffset: PropTypes.number,
  mdOffset: PropTypes.number,
  lgOffset: PropTypes.number,
  xsPush: PropTypes.number,
  smPush: PropTypes.number,
  mdPush: PropTypes.number,
  lgPush: PropTypes.number,
  xsPull: PropTypes.number,
  smPull: PropTypes.number,
  mdPull: PropTypes.number,
  lgPull: PropTypes.number
};

export default _Col;
```
