### ISSUE TITLE
Closing Chrome search widget with Escape key also closes Modal

### ISSUE THREAD

**Issue by linkleonard** [react-bootstrap/react-bootstrap#2274]
When using the Chrome search functionality (via Ctrl+F) with a React-bootstrap Modal open, closing the Chrome search functionality also closes the currently open Modal. Bootstrap modals do not seem to be affected. This issue also does not occur on Firefox 49. I am experiencing this on Chrome 53.0.2785.116 on Linux.

Replication instructions:
 * Go to https://react-bootstrap.github.io/components.html#modals and click on the `Launch demo modal` button.
 * Open up the Chrome search widget via CTRL+F
 * Press escape with the Chrome search widget in focus

Expected behavior:
 * Chrome search widget closes, modal remains open

Actual behavior:
 * Chrome search widget and modal both are closed

![image](https://cloud.githubusercontent.com/assets/7253020/19284826/774b0d2a-8fc5-11e6-8098-0d85fe1645fa.png)

**Comment by taion** [comment]
I'm not seeing this in Chrome 55. I don't think there's anything we can do about it if Chrome is improperly passing through the "esc" on the search box to the underlying page.
