### ISSUE TITLE
react-modal appears behind some react-bootstrap elements

### ISSUE THREAD

**Issue by Zensavona** [react-bootstrap/react-bootstrap#2277]
### Summary:

![screenshot 2016-10-12 09 03 27](https://cloud.githubusercontent.com/assets/425801/19290324/d884b81c-905a-11e6-9dfd-8c632a83e9a1.png)

The modal appears to sit behind certain kinds of elements, the most obvious being input addons.

I'm not totally sure if this is an issue with `react-modal`, `react-bootstrap` or both, so I've created [a ticket on react-modal](https://github.com/reactjs/react-modal/issues/249) also. If this is totally not your fault and I should take it up with someone else please let me know. My css-fu is very much lacking so forgive my ignorance in that area.

### Steps to reproduce:

I've made a basic repo as seen in the screenshot above.

1.  `git clone https://github.com/zensavona/bootstrap-modal-repro`
2.  `cd bootstrap-modal-repro`
3. `npm install && npm run start`
4. Take a look in your browser

Let me know if there's something else I can provide to help with this, it's a pretty nasty bug(?).

**Comment by jquense** [comment]
seems like like a `z-index` issue. react-bootstrap doesn't adjust or manipulate the bootstrap css, so I'm not sure there is anything we could do here. I think the react-modal repo is probably the best way forward :)

**Comment by Zensavona** [comment]
thanks for the fast reply @jquense :)
