### ISSUE TITLE
Use NavDropdown with unmountOnExit?

### ISSUE THREAD

**Issue by eliperelman** [react-bootstrap/react-bootstrap#2278]
Is it currently possible to use a `NavDropdown` in which selecting or closing the dropdown will not cause a re-render of the menu items, similarly to how `unmountOnExit` works with other components?

**Comment by jquense** [comment]
Not sure what you mean by re-rendering the menu-items but they are always mounted. We did fix a bug recently that caused them to unmount and remount when the dropdown closed.

Other than that, we don't plan on adding a `unmountOnExit` option to dropdowns

**Comment by eliperelman** [comment]
Wow, that was exactly my problem, thanks!
