### ISSUE TITLE
tabs-justified

### ISSUE THREAD

**Issue by texas697** [react-bootstrap/react-bootstrap#2279]
Am I missing somewhere in the docs that explain how to do this? I have read similar posts but they are older and not sure how to add nav-justifed to class?

**Comment by taion** [comment]
You just pass `justified` as a prop in to `<Tabs>`...

**Comment by deltaskelta** [comment]
Is there a reason why this isn't in the docs? I was looking for this feature but I didn't see it in the props for `<Tabs>` in the docs so I didn't even try it until I came across this issue...

**Comment by tomergev** [comment]
Bump! This should be in the docs!
