### ISSUE TITLE
Tables in Panels are forced into Panel body

### ISSUE THREAD

**Issue by philwills** [react-bootstrap/react-bootstrap#228]
Currently if you pass a Table in as the content of a Panel, it gets put into a `<div class="panel-body">`.

This leaves the table with padding around it, as opposed to the examples in the Bootstrap docs which show the `<table>` as a direct child of `<div class="panel">` whereby it gets matches the `.panel>.table` selector and loses the unsightly padding.

I would be happy to open a pull request, but I'm not sure what a good solution to this would look like.

**Comment by mtscout6** [comment]
I'm in favor of the `flush` and `fill` props, with the caveat that @nickcolley's suggestion to ensure the same html order is retained. I don't know the ramifications of having two `panel-body`s, but if it doesn't hurt anything then it sounds good to me. Go ahead and submit a pull request and we'll get it refined from there.

**Comment by taion** [comment]
The PR maintains the HTML ordering. I don't see how to make collapsing work, though.

**Comment by mtscout6** [comment]
@philwills Does #346 resolve everything for you or is there more that I'm missing?

**Comment by philwills** [comment]
Sadly, it doesn't look like it.

**Comment by taion** [comment]
@philwills What is the issue still?

**Comment by taion** [comment]
BTW, the updated example in the docs depends on #348 as well to render correctly.

**Comment by philwills** [comment]
Sorry, this does actually fix things, I just wasn't applying the fill attribute to *all* the things I needed to in my use case. Having done so, it works a charm.

**Comment by taion** [comment]
Cool - let me know if any other bugs crop up here. Otherwise, we should close this issue (:

**Comment by davidnorth** [comment]
In the current version this doesn't work if the panel only has a single child. The table still gets wrapped in a panel body. As a workaround, I had to add <div fill/> after my table.

**Comment by mtscout6** [comment]
@davidnorth Thanks for finding that

**Comment by mtscout6** [comment]
@taion Do you see a quick solution for that?

**Comment by taion** [comment]
My bad. Got too fancy with my test cases and ignored the obvious one.

**Comment by mwhite** [comment]
@taion This doesn't work for `<Panel><TableWrapper /></Panel>` where TableWrapper renders `<Table fill />'.  I couldn't quite figure out how to fix it, not sure it's even possible without pre-rendering the children.  Not sure if worth re-opening or documenting.

**Comment by taion** [comment]
Put `fill` on the `TableWrapper`. We may rewrite the `Panel` API to be more semantic and make better use of children anyway, to remove these issues.
