### ISSUE TITLE
Define element type in DropdownButton

### ISSUE THREAD

**Issue by robbinjanssen** [react-bootstrap/react-bootstrap#2281]
I would like the buttons in my `<DropdownButton>` to render using a `<div>` tag instead of the default `<button>` tag (for CSS purposes, specific flex in combination with firefox). 

With the `<Button/>`-component you can use the `componentClass` property and provide a `div` as string to force a `<div>`-tag. However the DropdownButton (currently) does not support this.

Am I missing something here or is this currently not possible?

**Comment by robbinjanssen** [comment]
Update: i've solved it temporarily/ugly on my end by assigning a custom `<ButtonGroup>`-componentClass to the `<DropdownButton>` which injects the `componentClass` property in the child:

```jsx
const CustomButtonGroup = props => (
  <ButtonGroup>{[
    // The Dropdown.Toggle
    Object.assign({}, props.children[0], {
      props: Object.assign({}, props.children[0].props, {
        componentClass: 'div',
      }),
    }),
    // The Dropdown.Menu
    props.children[1],
  ]}</ButtonGroup>
);
```

Usage:
```jsx
<DropdownButton componentClass={CustomerButtonGroup}>
  ...
</DropdownButton>
```

**Comment by jquense** [comment]
you want to use the Dropdown component directly, which lets you control everything more minutely
