### ISSUE TITLE
feature request: add custom className to backdrop

### ISSUE THREAD

**Issue by benmonro** [react-bootstrap/react-bootstrap#2282]
currently, when backdrop="static", there is no way to add a custom classname to the backdrop div.  it would be nice to do something like this:

```<Modal backdrop="static" backdropClassName="my-backdrop-style">...</Modal>```

**Comment by taion** [comment]
IMO the answer here should be "use react-overlays directly".

**Comment by benmonro** [comment]
What?!  That kinda defeats the purpose.

**Comment by taion** [comment]
See https://github.com/react-bootstrap/react-bootstrap/issues/2262

**Comment by jquense** [comment]
the main point here is that the bootstrap components aren't as general or flexible as primitives like a generic Modal. we follow the normal bootstrap apis (generally) and try to keep the apis simple and focused on providing a good experience with bootstrap. 

if you need more robust or custom versions of things we suggest using the libraries (like react overlays) which are specifically designed to be super flexible and unopinonated

**Comment by benmonro** [comment]
@taion @jquense 

First off let me say that I chose this library for [Concur's](https://www.concur.com/) main interface to bootstrap because I love the idea of bringing bootstrap to react.  Bootstrap made a designer out of me (well sorta) and that's saying something.  The interface makes sense, the docs are good, the examples are solid.  Great job overall.  

now that said.

I strongly disagree with your quick rush to close this issue.  What you're basically saying is that I should just re-implement Modal (or fork the library - which I don't believe in, as an open source hippy) just so I can add a slight tweak to our backdrop.  I'm happy to add a PR if you guys want, but before I jump into that, I ask that you let me know if you will accept the PR (assuming it meets your standards, etc).  My implementation will leave your implementation as the default and will only *allow* others to opt in, which as you showed in #2262 is something other people want.

anyway....  Should I bother with submitting a PR or should I just fork the repo?  Either way...

**Comment by jquense** [comment]
we aren't telling you to fork or reimplement, we are saying that this library has a specific scope and we don't just add new apis that differ from the normal bootstrap lightly. I understand that it'd useful in some context but this isn't something that bootstrap supports and all new code has a maintenance cost, especially for large libraries like this that already have a ton of surface area

**Comment by benmonro** [comment]
But those are the options I'm left with. Since you won't accept a PR then the only way to change the style/class of our backdrop is to either use a sibling selector (which our designers don't want to do) or reimplement all the things that modal does just for this one little thing. Guess I don't have a choice. 🍴

**Comment by jquense** [comment]
ya'll free to handle it however you want, but its not responsible for us any api b/c your designers don't want to add a child selector :P 

fwiw you'd be exactly the same boat using normal bootstrap.

**Comment by taion** [comment]
You can also just style `.backdrop`.

**Comment by mattgoucher** [comment]
I ran into the same problem a couple weeks ago. Although I don't like the solution, setting `bsClass='my-classname modal'` got me around having to pull in overlays directly.

**Comment by benmonro** [comment]
yep @mattgoucher's solution will work, but as he mentioned does put the classname on every modal related div.
