### ISSUE TITLE
Allow more patterns in propTypes

### ISSUE THREAD

**Issue by esphen** [react-bootstrap/react-bootstrap#2284]
Hi,

I would like to discuss weakening the `propTypes` check in some components. In my opinion, currently the `propTypes` are a bit restrictive. I'll give you an example of what I think is problematic. 

You are using `propTypes` to check valid input, which is great. However, you are only marking expected values as valid, thus making some programming patterns impossible. For example, the `FormGroup` `propTypes` for `validationState` are `React.PropTypes.oneOf(['success', 'warning', 'error'])`. Here is an example of two programming patterns which are currently marked as as `propType` failures, and by extension, bugs:

```javascript
import classNames from 'classnames';

function ExampleField({ meta }) {
  return (
    <FormGroup
      controlId="example"
      validationState={meta.invalid && 'error'}>
      // ...
    </FormGroup>

    <FormGroup
      controlId="example2"
      validationState={classNames({
        error: meta.invalid,
    })}>
    // ...
    </FormGroup>
  );
}
```

This example is from a project I am working on which uses [redux-form](http://redux-form.com/). Here the stateless component receives the form field state and passes this to the react-bootstrap component.

I would argue these patterns are completely valid. They are marked as `propType` failures because the first `FormGroup` is passed `false` if the field is valid, and the second `FormGroup` is passed an empty string if the field state is valid.

I feel these kind of patterns are perfectly valid in this case. What do you think? Are there other places in react-bootstrap where these kind of patters would be acceptable?

With a grep, I can see that these files use a `oneOf` propType check

```
src/Pagination.js
src/Tooltip.js
src/OverlayTrigger.js
src/OverlayTrigger.js
src/Radio.js
src/Collapse.js
src/Popover.js
src/Panel.js
src/Overlay.js
src/MediaLeft.js
src/Button.js
src/Dropdown.js
src/DropdownMenu.js
src/Carousel.js
src/Checkbox.js
src/CarouselItem.js
src/TabContainer.js
src/SafeAnchor.js
src/Modal.js
src/FormGroup.js
src/Tabs.js
src/utils/bootstrapUtils.js
src/TabPane.js
src/MediaRight.js
src/TabContent.js
```

**Comment by taion** [comment]
I don't think we want to support those patterns. I think in those cases it makes more sense to just accept the explicit `null`.

**Comment by esphen** [comment]
You already support the explicit `undefined` by not specifying `isRequired`, so a workaround is to instead use the pattern

```javascript
<FormGroup
  controlId="example"
  validationState={meta.invalid ? 'error' : undefined}>
```

It's a lot less ergronomic to read and write, seeing as most jsx-developers are used to the `conditional && value` pattern by now. But if you don't want to support `false` as an option, I will respect that.

**Comment by taion** [comment]
We recommend using `null` instead of `undefined` in those cases.

**Comment by jquense** [comment]
one thought for allowing `false` here, is symmetry with the non-renderable values for `children`

**Comment by esphen** [comment]
Nice, I didn't know `null` was allowed when not using `isRequired`. In which case, I agree that on a general basis `null` is better than my example workaround of `undefined`.
