### ISSUE TITLE
How to set the width of the element : Modal

### ISSUE THREAD

**Issue by captainwooder** [react-bootstrap/react-bootstrap#2285]
I have tried setting like so :
` <Modal style={{width:'300px'}} /> `

But it doesn't work! could you give some examples?

**Comment by taion** [comment]
There are examples on the components page. Please refer to those.

**Comment by shrkw** [comment]
how can I set style by inline style attribte?

**Comment by andrewabogado** [comment]
@shrkw I've tried inline style targeting modal-dialog to no avail. Instead, this works for me. 

Your markup:
`<Modal dialogClassName="your-dialog-classname"/>`

Your style (has to be in a separate stylesheet):
```
.your-dialog-classname {
    display: block; 
    width: 1200px; 
    padding-left: 0px;
}
```

**Comment by jdengsc** [comment]
Has anybody found a solution to this?  I am trying to add min-width to my React-bootstrap modal and have no way to target either the `div class="modal-lg modal-dialog">` or `div class="modal-content" role="document">` elements from the <Modal> component

**Comment by superdev810** [comment]
You have to set state as width and set width in style attributes.
this.state = {
     divWidth: {
        width: 100
     }
}

render(){
   return(
      <div style={this.state.divWidth}>
      </div>
   )
}

**Comment by saramberr12** [comment]
@superdev810 currently experiencing the same issue, that doesn't seem to be working for me

**Comment by khartnett** [comment]
If you want to use modal-lg or modal-sm, use prop bsSize="large" / bsSize="small" on the Modal component. see: https://react-bootstrap.github.io/components/modal/#modal-default-sizing

**Comment by Hedayet** [comment]
I found max-width was required as
