### ISSUE TITLE
autoFocus attribute has odd offset in ie11.

### ISSUE THREAD

**Issue by shikelong** [react-bootstrap/react-bootstrap#2286]
I use autoFocus to FormControl in a modal. and in ie 11. there will be a offset when I open the modal.

```js
<FormControl
          {...input}
          type="text"
          maxLength="128"
          autoFocus
          disabled={disabled}
/>
```

![temp1476331820955](https://cloud.githubusercontent.com/assets/4499997/19433354/f5d4e450-9492-11e6-8b35-503ce898f2c3.png)

Regards.

**Comment by taion** [comment]
That's just a consequence of the modal "slide down" animation. If you want to avoid that, delay the focus until after the modal finishes animating in, or else disable the "slide down" part of the animation.

**Comment by jquense** [comment]
I've also seen oddness related to the placement of browser autocomplete dropdowns as well...I'm not sure who should be fixing it, the browser or React's autofocus polyfill.

**Comment by shikelong** [comment]
@taion   How to  disable the “slide down” part of the animation? I only find the animation props in the document. Thanks.

**Comment by shikelong** [comment]
#2321
