### ISSUE TITLE
validationState prop to have more types

### ISSUE THREAD

**Issue by gsccheng** [react-bootstrap/react-bootstrap#2287]
I'm trying to set up the `validationState` prop for my validated form, and currently it is listed to only accept the values of 'success', 'warning', or 'error'. When the form is first rendered and presented to the user, you probably wouldn't want the `validationState` to be either of those (as shown in the example as well). It would be convenient and clear to have an additional state such as `untouched` or `null` to represent this. Right now, the [example](https://react-bootstrap.github.io/components.html#forms) uses an `undefined` value, so if anything change the docs to show that that can be accepted as well? Thanks.

**Comment by taion** [comment]
Both `null` and `undefined` are accepted there.

**Comment by gsccheng** [comment]
Right, but right now the docs show

> one of: 'success', 'warning', 'error'

without mention of those other two values you just mentioned.

**Comment by jquense** [comment]
null and undefined are the "absent" values in propTypes it's the same as not including the prop,  this is noted by the props not being "required"

**Comment by taion** [comment]
Should we explicitly add `null` to that enum? Does that work?

**Comment by gsccheng** [comment]
After thinking about it some more, perhaps it is better to leave everything as is– as @jquense mentions and it's probably standard this way. Coming from the angle of how I should conceptually treat the validation state, and especially since the example already explicitly declares the prop as it would be the common use case, I thought I'd open the discussion for listing a `null` type value. 

So, I don't feel too strongly either way but thought I should at least express my experience with it. Thanks for the work guys.

**Comment by taion** [comment]
Can you check that our docgen works appropriately if you explicitly add `null` to the `oneOf`? This isn't the first time this has caused confusion.
