### ISSUE TITLE
Add filterable dropdown example

### ISSUE THREAD

**Issue by j20** [react-bootstrap/react-bootstrap#2288]
The React Bootstrap docs currently has one broken example of a filterable dropdown in the Custom Dropdown Components section at https://react-bootstrap.github.io/components.html#forms

It'd be very useful if a section were added with for an example of working filterable dropdown, similar to this example:
https://select2.github.io/examples.html#select-boxes-with-labels

Notable features:
1.) dropdown shows current selection
2.) filtering works properly
3.) clicking outside the dropdown causes it to close

**Comment by jquense** [comment]
The example on the doc site, isn't broken its case sensitive. More importantly its an example of how to make a custom dropdown, not how to make a working fully featured `<select>` replacement. The Dropdown component is a _menu_ component, not a form input like a select, its not intended to be anything like select2 or react-select.

**Comment by j20** [comment]
I think this was misinterpreted as a bug report, but it's intended as a feature request.

I realize that it is not the intent of the current custom dropdown example to serve as a full filterable example. I mention it to acknowledge that I've read the docs and it's the closest thing in the docs to what I'm requesting and the filtering doesn't work so it doesn't serve as an example of what I'm requesting, which is why it would be useful to add a section for this to the docs.

A filterable dropdown example, or component if need be, would be very useful in React Bootstrap given most other solutions depend on Jquery, like the example I provided, and not needing Jquery is React Bootstrap's value proposition.

Do you not a agree filterable dropdown example or component would be useful? If not, that's ok too, but I just want to make sure this Github issue was understood properly.

**Comment by jquense** [comment]
it is a useful component, however it's not part of bootstrap and this library is concerned with implementing the bootstrap plug-ins in React and not much else. there are a good bunch of components that do what you want already in the react ecosystem, check out react-select and/or react-widgets or other react dropdown libraries

**Comment by j20** [comment]
Makes sense. Some things are outside the scope of the project.

+1 I'm going with [react-select](https://github.com/JedWatson/react-select). It appears to be very high quality. 

Thank you
