### ISSUE TITLE
MenuItem without a link

### ISSUE THREAD

**Issue by arthurchipdean** [react-bootstrap/react-bootstrap#2289]
I am using checkboxes in my drop down menu to indicate whether we are displaying a particular dataset or not.  

If I use the MenuItem component however the value of the checkbox does not update properly because the click is being intercepted by the SafeAnchor/MenuItem. I can see the state changing but it is not reflected by the value of the checkbox. If I just change the MenuItem to an li it does work but then the formatting is off and I get warning messages about the 'active' property.

Is there some other component I should be using for a drop down menu item without a link?

Thank you
Arthur

**Comment by taion** [comment]
See the custom dropdown example on the components page.

**Comment by arthurchipdean** [comment]
I see how to customize the Dropdown component but there is nothing at all listed about the MenuItem.
