### ISSUE TITLE
MenuItem without a link

### ISSUE THREAD

**Issue by arthurchipdean** [react-bootstrap/react-bootstrap#2290]
I am using checkboxes in my drop down menu to indicate whether we are displaying a particular dataset or not.

If I use the MenuItem component however the value of the checkbox does not update properly because the click is being intercepted by the SafeAnchor/MenuItem. I can see the state changing but it is not reflected by the value of the checkbox. If I just change the MenuItem to an li it does work but then the formatting is off and I get warning messages about the 'active' property.

I see how to customize the Dropdown component but there is nothing at all listed about the MenuItem. Is there some other component I should be using for a drop down menu item without a link?

Thank you
Arthur

**Comment by arthurchipdean** [comment]
So I guess the answer is that no, there is no other component I should be using. I'll create my own.

Thanks!

**Comment by taion** [comment]
Right, just render whatever component you want in that list.

**Comment by hassankhan** [comment]
Not really an ideal solution, since you start getting errors like: `Warning: Unknown prop `active` on <li> tag.`.

**Comment by jquense** [comment]
you don't need to wrap dropdown you need to create your own MenuItem component and handle the injected props. 

anchor-less MenuItem s aren't supported by the bootstrap css so we don't want to provide an an API to adjust that on menu item component

**Comment by hassankhan** [comment]
Ah right, I guess that makes sense, there just wasn't any documentation saying that was how to do it. Thanks for the explanation!
