### ISSUE TITLE
Modal appends to body and pushes existing content to the top

### ISSUE THREAD

**Issue by atul-ojha** [react-bootstrap/react-bootstrap#2292]
I have a simple react bootstrap Modal but it just doesn't appear as in examples, there it appears on top of the existing contents beautifully, but in my case it just appends below the rest of the content and pushes everything else to the top:-

I have this parent component which renders modal component:-

1. Parent component:- 

import React, { Component } from 'react';
import { Modal } from 'react-bootstrap';
import TestModal from './TestModal.js';

export default class ModalContainer extends Component{

	constructor(props){
		super(props)

		this.state = {
			parAddUpdateBoolean: false
		}
	}
    
    closePARAddUpdate(){
        
        this.setState({parAddUpdateBoolean: false});
    }

    showModal(){
         this.setState({parAddUpdateBoolean: true});
    }

	render(){

		return(
		<div style= {{height: '100%', position: 'relative' }}>
			<button onClick={this.showModal.bind(this)}>Show Modal</button>

			<TestModal closeModel = {this.closePARAddUpdate.bind(this)} showModal={this.state.parAddUpdateBoolean}/>

			Show Modal On top of this Content
			<br/>
			<br/>
			<br/>
			<br/>
			Thats not happening
			<br/>
			<br/>
			<br/>
			<br/>
			And I dont know why
		</div>
		)
	}
}

2. Modal Component:-
 import React , { Component } from 'react';
import { Modal } from 'react-bootstrap';

export default class TestModal extends Component{

  constructor(props){
    super(props)
  }

  
  close() {
    this.props.closeModel();
  };

  
  render(){

  	
  	return(
  		<Modal show={this.props.showModal} onHide={this.close.bind(this)}>
          <Modal.Header closeButton>
            <Modal.Title>Modal heading</Modal.Title>
          </Modal.Header>
          <Modal.Body>
            <h4>Text in a modal</h4>
            <p>Duis mollis, est non commodo luctus, nisi erat porttitor ligula.</p>

            <h4>Popover in a modal</h4>
            
            <h4>Tooltips in a modal</h4>            

            <hr />

            <h4>Overflowing text to show scroll behavior</h4>
            <p>Aenean lacinia bibendum nulla sed consectetur. Praesent commodo cursus magna, vel scelerisque nisl consectetur et. Donec sed odio dui. Donec ullamcorper nulla non metus auctor fringilla.</p>
          </Modal.Body>
          <Modal.Footer>
            <button onClick={this.close.bind(this)}>Close</button>
          </Modal.Footer>
        </Modal>
  		);
  };

};

what to do to get this working the way in example, I have no css anywhere.

**Comment by taion** [comment]
You need the Bootstrap CSS for things to display properly.
