### ISSUE TITLE
Slow in closing modal

### ISSUE THREAD

**Issue by fajarmf** [react-bootstrap/react-bootstrap#2293]
I am using modal for my component. but apparently it has really slow animation. Is it something that's configurable? or did I use the component wrongly?

```
      <Modal show={this.props.show} onHide={this.props.onClose}>
        <Modal.Header closeButton>
          <Modal.Title>Winner</Modal.Title>
        </Modal.Header>
        <Modal.Body>
          <h4>Period:</h4>
          <span>{this.props.startDate}</span> - <span>{this.props.endDate}</span>
        </Modal.Body>
        <Modal.Footer>
          <Button onClick={this.props.onClose}>Close</Button>
        </Modal.Footer>
      </Modal>
```

**Comment by taion** [comment]
That animation is defined in the CSS, not the JS code here.

**Comment by jquense** [comment]
Which the little caveat that the JS does need to know the duration to manage itself properly which can be set here: https://github.com/react-bootstrap/react-bootstrap/blob/master/src/Modal.js#L256-L257

**Comment by fajarmf** [comment]
@taion , @jquense could you help to show me on which css is it?
