### ISSUE TITLE
DropdownButton interferes with react-router IndexRoute

### ISSUE THREAD

**Issue by Muntaner** [react-bootstrap/react-bootstrap#2294]
I'm using react-bootstrap in combination with react-router.
All of a sudden, when I click on a DropdownButton, react-router immediately prompts the browser to its IndexRoute. So, I can't simply use the MenuItem(s) "inside" the DropdownButton, because the page gets abandoned right after the click on the DropdownButton.
I can't figure how to fix this, but it seems to be related to the IndexRoute: if I change it to the react component where the DropdownButton is used, the DropdownButton seems to work decently. But this is a solution that seems like a soft hack and I can't use this in production.

Here you are some snippets.

The Nav bar with his DropdownButtons (I have 3 of them):

```
<Nav style={ {margin: 5} } pullRight>
  <DropdownButton id="cored" className = 'dropdowneffect' bsSize="xsmall" bsStyle = 'default' title={statusHeader} pullRight style={ { width: 170, marginRight: 3} }>
    <MenuItem eventKey='1' onClick={this.sendStartSignal}>
      ...
    </MenuItem>
     //some MenuItems there
    ...
  </DropdownButton>
</Nav>
```

The react-router Routes:

```
import React                        from 'react';
import {Router, Route, IndexRoute, browserHistory}  from 'react-router';

import App                               from './App';
import LoginPage                    from './pages/LoginPage';
...
export default (
  <Router history={browserHistory}>
    <Route path="/" component={App}>
      <IndexRoute component={LoginPage}/>
        <Route path="/login" component={LoginPage} />
        <Route path="/overview" component={OverviewPage} />
        <Route path="/users" component={UsersPage} />
         ...
        <Route path="*" component={OverviewPage} />
    </Route>
  </Router>
);
```

**Comment by taion** [comment]
Our docs site uses React Router, and the dropdowns there work just fine. You should probably use `<NavDropdown>` with `<Nav>`, though.

**Comment by Muntaner** [comment]
For anyone facing this issue, the solution suggested by @taion seems to be working, thank you!
