### ISSUE TITLE
Carousel : load images in the background

### ISSUE THREAD

**Issue by ychen-reol** [react-bootstrap/react-bootstrap#2295]
So I checked network on chrome inspector and found out that the images are only requested when user navigate to its slide.  I checked the documents and there seems to be no properties to change this behavior. I think it is good if we can have an option to load all images in the background.

**Comment by taion** [comment]
We render all the `<img>`s for `<Carousel>` eagerly. If you want to do something beyond that, you'll need to handle it in your own code.
