### ISSUE TITLE
Button with bsStyle="danger pull-right"

### ISSUE THREAD

**Issue by bertjwregeer** [react-bootstrap/react-bootstrap#2296]
What is the proper way (to not get warnings) to set extra styles for Button's so that I can add `pull-right` to the Button?

Everything works fine when I set it, it just warns.

**Comment by TYL3RJC** [comment]
I use `className="pull-right"`

**Comment by jquense** [comment]
yeah className is correct, bsStyle is only for variant styles

**Comment by bertjwregeer** [comment]
Thanks! Sorry for the extra noise!
