### ISSUE TITLE
Add a way to pass className to DropdownMenu through DropdownButton

### ISSUE THREAD

**Issue by leoasis** [react-bootstrap/react-bootstrap#230]
Currently there's no way to pass a custom className to the `DropdownMenu` when using `DropdownButton`. Perhaps we should add a `menuClassName` prop? Or perhaps a `menuProps` to customize other props as well?

**Comment by AlexKVal** [comment]
Superceded by #526

**Comment by jareware** [comment]
I ended up here after wondering why I'm getting an unexpected class on my button that sits within `<DropdownButton className="my-extra-class">`. I would have expected `my-extra-class` to **only** be applied to the top-level element.

Is this intended behaviour?

**Comment by taion** [comment]
Seems pretty natural to me that styles you pass into `DropdownButton` get applied to the button.

**Comment by jareware** [comment]
OK, that's fine then, just making sure it's intentional...
