### ISSUE TITLE
Styles not applied? 

### ISSUE THREAD

**Issue by scheung38** [react-bootstrap/react-bootstrap#2300]
After installing:

$ npm install react-bootstrap --save

myproduct.js

```
import { Button } from 'react-bootstrap';

export default class ProductAddForm extends Component {

render() {

        return (

   <div className="container">
   <Button bsStyle="primary" type="submit">Submit</Button>
   </div>
   );
 }
}
```

But no styling being applied?

**Comment by jquense** [comment]
Hi there, you need to include the bootstrap css. I suggest reading through the getting started guide: http://react-bootstrap.github.io/getting-started.html

**Comment by shehryar96** [comment]
@jquense 404 error at this link 
 http://react-bootstrap.github.io/getting-started.html

**Comment by maneshom** [comment]
@shehryar96 The link changed to https://react-bootstrap.github.io/getting-started/introduction
.Add the stylesheets properly.It will works

**Comment by Msey** [comment]
I used this [guide ](https://react-bootstrap.github.io/getting-started/introduction) but It doesn't work.

**Comment by tamangsuresh** [comment]
I used it too its not working for me too.

**Comment by Faizanamin** [comment]
I used this guide but It doesn't work.

**Comment by AlexanderWatts** [comment]
In the docs it says that bootstrap does not come with any css so you will need to import it into your module: 

`import 'bootstrap/dist/css/bootstrap.min.css';`

I spent ages wondering why it was not working despite having imported `react-bootstrap`

Hope this helps

**Comment by alexanderwhatley** [comment]
I tried everything in the guide, and it's not working :(

**Comment by BryanHo10** [comment]
After installing bootstrap along with react-bootstrap, the styling will apply.

**Comment by kshiraishi22** [comment]
thank you! adding: import 'bootstrap/dist/css/bootstrap.min.css' worked for me too.

**Comment by pifelipes** [comment]
I had this issue and finally found the solution.

You have to delete:
import "./App.css"

**Comment by GabrielNSD** [comment]
> In the docs it says that bootstrap does not come with any css so you will need to import it into your module:
> 
> `import 'bootstrap/dist/css/bootstrap.min.css';`
> 
> I spent ages wondering why it was not working despite having imported `react-bootstrap`
> 
> Hope this helps

This solved my problem!! Thank you a lot!!!

**Comment by sumukhbharadwaj** [comment]
By Importing import 'bootstrap/dist/css/bootstrap.min.css'; It Overrides other Custom css files.

**Comment by SamsAgency** [comment]
I am getting a module not found when i type import 'bootstrap/dist/css/bootstrap.min.css';

**Comment by Pookacz** [comment]
> In the docs it says that bootstrap does not come with any css so you will need to import it into your module: 
> 
> `import 'bootstrap/dist/css/bootstrap.min.css';`
> 
> I spent ages wondering why it was not working despite having imported `react-bootstrap`
> 
> Hope this helps

It works 💪thank you very much

**Comment by saurabh1239** [comment]
try importing css ,  import 'bootstrap/dist/css/bootstrap.min.css' in ypur index.js or app.js file

**Comment by user4302** [comment]
> In the docs it says that bootstrap does not come with any css so you will need to import it into your module:
> 
> `import 'bootstrap/dist/css/bootstrap.min.css';`
> 
> I spent ages wondering why it was not working despite having imported `react-bootstrap`
> 
> Hope this helps

added this to the index.js and its all good now for me
