### ISSUE TITLE
Add more validation hooks similar to react-formsy

### ISSUE THREAD

**Issue by grimunit** [react-bootstrap/react-bootstrap#2301]
Would love to see more validation hooks available for the form components similar to the way react-formsy gives you validations out of the box. Right now it's very cumbersome to add a lot of basic validation to every form component, and it's current not very composable to allow you to have multiple validations with varying help messages. 

If anyone has an example they'd like to share of how they have accomplished multiple help messages I'd love to see some ideas.

**Comment by jquense** [comment]
The form components are intentionally simple. Just like the upstream bootstrap only _styles_ inputs, we also only provide presentational component wrappers around native the inputs. Things like better validation states and hooks, while important and necessary to real apps, are out of scope for react-bootstrap.

We suggest using one of the many good form libraries out there, such as react-formal or redux-form, both of which integrate nicely with the bootstrap presentational components
