### ISSUE TITLE
[ButtonGroup] How to I set one button as active from the beginning?

### ISSUE THREAD

**Issue by wzup** [react-bootstrap/react-bootstrap#2302]
How do you suggest to set one of the buttons in a button group as `active` (after a page load, for example)? And the main thing the button group must not become a controlled button group! Only initial state of one button is set. Then, after very first click, that state is gone and buttons are managed as by default.

There is nothing about it in your docs. What do you suggest? Any best practices on that?

**Comment by jquense** [comment]
we don't have an uncontrolled button group...sorry not sure what you are asking for or what default behavior you are referring to.
