### ISSUE TITLE
Stacked collapsible Nav is not stacked anymore

### ISSUE THREAD

**Issue by oliversturm** [react-bootstrap/react-bootstrap#2303]
You can find my code here: http://codepen.io/oliversturm/pen/gwEkJW 

The Navbar/Nav is meant to be rendered vertically (stacked). However, when the Nav is wrapped in the other components to provide the collapsing functionality, the Nav doesn't render "stacked" anymore - instead it is horizontal.

Looking at the generated code, there is a style `navbar-nav` assigned to the `<ul>` tag. This seems pointless, and when I deactivate that css class in the debugger, the bar is rendered "stacked" again. I suspect that the class is assigned incorrectly in this case.

**Comment by jquense** [comment]
That is the intended behavior of Navs in Navbars, the Nav's styles are modified by being in a navbar

**Comment by oliversturm** [comment]
Well, I don't mind styles being modified. But surely the intention is not to break the display configuration of the embedded Nav - and with pure bootstrap, it is no problem to combine the stacked display with the collapsible feature. With react-bootstrap, this appears to be impossible right now.

**Comment by jquense** [comment]
hi, it's only possible if you add a nav without the `navbar-nav` class in plain bootstrap which isn't correct/supported, in a navbar.  granted they can't stop you from doing it. And yeah the upstream intention is to override the Nav config, to work as intended in the navbar, similarly the justified option isn't supported.

**Comment by oliversturm** [comment]
Okay, understood. I guess this will require a change elsewhere then. Thanks, Jason.
