### ISSUE TITLE
Multiple FormGroups causing 'Warning: FormControl is changing'

### ISSUE THREAD

**Issue by hassankhan** [react-bootstrap/react-bootstrap#2306]
```
class FormExample extends Component {

  constructor(props) {
    super(props);

    this.state = {
      search : {
        facebook_id: '',
        facebook_email : '',
      },
    };

    this.handleChange = this.handleChange.bind(this);
    this.handleSubmit = this.handleSubmit.bind(this);
  }

  handleSubmit(event) {
    //
  }

  handleChange(event) {
    this.setState({
      search: {
        [event.target.id]: event.target.value,
      },
    });
  }

  render() {
    return (
      <Form horizontal onSubmit={this.handleSubmit}>
        <FormGroup
          controlId="facebook_id">
          <ControlLabel>Working example with validation</ControlLabel>
          <FormControl
            type="text"
            value={this.state.search.facebook_id}
            placeholder="Enter text"
            onChange={this.handleChange} />
          <FormControl.Feedback />
          <HelpBlock>{this.state.search.facebook_id}</HelpBlock>
        </FormGroup>

        <FormGroup
          controlId="facebook_email">
          <ControlLabel>Working example with validation</ControlLabel>
          <FormControl
            type="text"
            value={this.state.search.facebook_email}
            placeholder="Enter text"
            onChange={this.handleChange} />
          <FormControl.Feedback />
          <HelpBlock>{this.state.search.facebook_email}</HelpBlock>
        </FormGroup>
      </Form>
    );
  }
}
```

When trying to edit an input in either field, a warning is always triggered (only once though).

**Comment by jquense** [comment]
that's on you and the setup you have, the FormControls have no logic in them controlling or adjust values so you are probably rendering them with an `undefined` value without realizing it.

**Comment by hassankhan** [comment]
That's what I thought but the example I provided is a minor change from the example provided in the docs. Can you tell me exactly what I'm doing wrong? Might help for others who keep running into the same issues (I had searched through the repo issues as well)

**Comment by andela-aabdulwahab** [comment]
@hassankhan The issue is with your implementation of the handleChange function. setState() doesn't do recursive merge, so the search object gets overridden every time you edit the input field. So if you're editing facebook_id field, facebook_email get an `undefined` for its value, enhance the error.

There are two ways to go about it, you can use `object.assign` to change the search object and pass it to setSet()
```
handleChange(event) {
    const newSearch = Object.assign({}, this.state.search, { [event.target.id]: event.target.value});
    this.setState({
      search: newSearch
    });
  }
```

OR

flatten the structure of your state, Which is the preferred way to go for me.

```
constructor(props) {
    super(props);

    this.state = {
      facebook_id: '',
      facebook_email : '',
    }
 }

handleChange(event) {
    this.setState({
      [event.target.id]: event.target.value
    });
}
```

This issue is not a React-Bootstrap problem, it was caused by your implementation.

**Comment by hassankhan** [comment]
Ahh I wasn't aware that the nesting was causing the issue, thanks for all your help 👍
