### ISSUE TITLE
Bootstrap col-8 col-4 breaking into two rows on Chrome <=48, Safari <=8

### ISSUE THREAD

**Issue by somghosh** [react-bootstrap/react-bootstrap#2307]
I have the following high level code (I am using bootstrap via react-bootstrap which uses bootstrap inside it), version `"react-bootstrap": "^0.30.2"`

## Stylesheet used
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/latest/css/bootstrap.min.css">

## My html code
   
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-8 col-xs-12">Choose your Wardrobe</div>
        </div>
        <div class="row">
            <div class="col-md-8 col-xs-12">

                    

            </div>
            <div class="col-md-4 col-xs-12">
                
            </div>
        </div>
    </div>
	

I see both columns appearing in same row in Chrome 49 and above

But with 
1.Chrome 48 and below
2. Safari 8 and below

I see the following

I have found a hacky way to fix it, but does not work always, so trying for an elegant solution

# my hacky solution

### html

	<div class="row myrow">
	
### css	
    .myrow{
		display: flex;
	    flex-direction: row;
	}

The current website is here - http://beta.fashbae.co.nz/ -please scroll down to the middle of the page to see this problem

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/D9NVf.jpg

**Comment by taion** [comment]
You're not showing any React code – this looks like purely a CSS issue, and we don't bundle the CSS.
