### ISSUE TITLE
How to use onSelect in Pager? Where to put onSelect in component's markup? No docs provided

### ISSUE THREAD

**Issue by wzup** [react-bootstrap/react-bootstrap#2310]
From your [docs](https://react-bootstrap.github.io/components.html#pager-props)

![react-bootstrap - google chrome 2016-10-28 17 44 53](https://cloud.githubusercontent.com/assets/3880497/19803542/e3d03546-9d3b-11e6-96d0-592c5d73af99.png)

1) Where to put `onSelect` in markup?
```
  <Pager onSelect={ HERE ??? }>
    <Pager.Item previous href="#" onSelect={ HERE ??? }>Previous</Pager.Item>
    <Pager.Item disabled next href="#" onSelect={ HERE ??? }>Next</Pager.Item>
  </Pager>
```

2) `onSelect` is not passed `event` as the first argument.

3) How to determine which button (`prev` or `next`) was clicked if `onSelect` is not passed an `event`. It is passed some `Proxy` as the second argument. What did you mean passing it as the second argument ignoring `event` as the first? What are your practices on using it?

![submissions - sib management - google chrome 2016-10-28 18 37 39](https://cloud.githubusercontent.com/assets/3880497/19803930/fd68232c-9d3d-11e6-8a62-6587b49d51a6.png)

**Comment by jquense** [comment]
as the docs say it's a prop of the Paper component so it goes there. all onSelect handlers in RB are the same signature.  the first argument is the evenKey of the selected item and the second is the event I think

**Comment by SergeyAlexeev** [comment]
How can I recognize what button was clicked? Next or Previous? I've tried to use the `onSelect` function but there isn't any information about it.
