### ISSUE TITLE
DropdownMenu not performing well

### ISSUE THREAD

**Issue by egeriis** [react-bootstrap/react-bootstrap#2312]
Hi there!

Thank you for providing this great library. It really helps us in our work.

We've been debugging on performance a lot lately and one of the things we've now stumbled upon seem to be a performance hit from the `DropdownMenu` component.

We use the `DropdownButton` in one of our components, which ended up taking ~4s for 750 rendered components. In each render there is a `DropdownButton` and removing this gave us a 1s decrease in loading time. We decided to drill down and attempt to remove as many parts as possible, to see which component exactly took a performance hit. To see if we did something inconvenient with regards to our usage. We found that it was `DropdownMenu` which had the biggest impact.

My theory until this point, is that it is the cloning of element that occurs in L121, that is heavy. However we didn't have time right now to drill down further than at component level to debug this. https://github.com/react-bootstrap/react-bootstrap/blob/master/src/DropdownMenu.js#L121

Do you guys have any comments on this? Could you elaborate on purpose of the cloning, just so I am sure about it. Maybe we could work out a more efficient way to achieve the same result.

**Comment by jquense** [comment]
the cloning is to add new props to the provided element, there really isn't anyway to avoid it, however I'd be _extremely_ surprised if that was the bottleneck. Cloning elements is pretty cheap.

I'd make sure its actually the dropdown menu that is causing the slowdown and not one of menu item components.

**Comment by egeriis** [comment]
I replaced a `MenuItem` instance with the `li` that it renders, and the render performance from `DropdownMenu` was what I could isolate as the sinner.

**Comment by jquense** [comment]
i'm not sure there is anything we can do it increase the performance, its actually a fairly simple component. perhaps its actually the css/layout that's the problem?

**Comment by taion** [comment]
Are you sure you're not running React in debug mode?

**Comment by egeriis** [comment]
@taion I am. But I reckon that doesn't neglect the performance hit, albeit it's obviously bigger than in a production build.

@jquense Do you have benchmarks for the performance of each component? You seem very confident that it's not the component which is performing bad. We have rendered the exact same DOM without react-bootstrap with a huge performance increase. There's definitely something going on.

**Comment by jquense** [comment]
> Do you have benchmarks for the performance of each component?

I don't have any. I'm not confident that it isn't performing bad, but I am pretty confident that there isn't much we can do about it if it is without significantly hanging the API of the component. If you'd like to more specifically debug the component and want to propose a fix we'd happily to take it. Generally though I think we'd probably consider "rendering 750 dropdown menus" an exceptional use case. Any situation i've had to do something like that also called for windowing or incremental loading without or without the dropdown.

**Comment by taion** [comment]
The most likely culprit is that you're unintentionally running React in debug mode.

Creating elements in debug mode re-runs validations and does a bunch of extra work, none of which happens in production mode.

They're absolutely not equivalent in terms of performance – things like `cloneElement` that are essentially free in production are nowhere near that in debug.

**Comment by egeriis** [comment]
> Things like cloneElement that are essentially free in production are nowhere near that in debug

@taion That made me so much smarter, thank you for that. 

I also agree that 750 dropdown menus is a rare case. And we're probably looking to change that design anyway. But for the sake of getting more knowledge, we'll probably dig deeper into this.

**Comment by jquense** [comment]
> we'll probably dig deeper into this.

we always appreciate that :)
