### ISSUE TITLE
Glyphicon in string

### ISSUE THREAD

**Issue by monski** [react-bootstrap/react-bootstrap#2314]
Hi

Anyone can help me on Glyphicon component? i want to put it string to concat in my message something like this
`  componentDidMount() {
    let icon = <Glyphicon glyph="glyphicon-ok" />
    this.notificatonShow(`${icon} Record Successfully saved!`, 'success', 10000)
  },`
but this giving me an outout:

_[object Object] Record Successfully saved!_

any help? thanks in advance

**Comment by jquense** [comment]
hi there, that's not how jsx works. I'd suggest reading up on the syntax or asking your question on stackoverflow or the react discord as its not related to react bootstrap but jsx in general
