### ISSUE TITLE
How do I get a reference to a modal when shown

### ISSUE THREAD

**Issue by holgersindbaek** [react-bootstrap/react-bootstrap#2315]
I need to do some things with jQuery on my modal once I show it. I can't get a reference to it when I show it though. This is my code:

    render: ->
      React.createElement ReactBootstrap.Modal,
        className: classNames("modal_component", @props.classNames)
        ref: "modalComponent"
        show: true
        onHide: @swipeOut
        onShow: @swipeIn
        animation: false
        autoFocus: false
        ReactBootstrap.Modal.Body
          React.DOM.div
            className: "modal_close_button"
            onClick: @swipeOut
            React.createElement IconComponent,
              name: "close_medium"
          React.DOM.div
            className: "modal_content"
            React.DOM.div
              className: classNames("modal_content_container")
              @props.children if @props.children?

    swipeIn: ->
      log "swipeIn:"
      log @refs.modalComponent._modal

And it outputs "null" for "@refs.modalComponent._modal". If I set a timeout of 150ms before I log to the console, then I can get the "@refs.modalComponent._modal" no problem. Seems like there's a delay on rendering the modal. Can that be true? How would I get a reference to the modal on my swipeIn method?

**Comment by jquense** [comment]
> Can that be true?

sure, `onShow` is called when the `show` prop switches from false to true, not when the modal becomes visible. You can use a timeout, or one of the animation hooks (like `onEntering`) if needed. Or put the ref on your inner components

**Comment by holgersindbaek** [comment]
@jquense  I can't use "onEntering" or "onEntered", since I don't use animations. What do you mean by "put the ref on your inner components"? I need to reference the modal itself... not the children rendered in the modal.

What method do I need to look at to know when the modal becomes visible? I would like to create a "didShow" function.

Is there a delay from the time the prop switches and until the modal becomes visible?

**Comment by jquense** [comment]
> Is there a delay from the time the prop switches and until the modal becomes visible?

the delay is between when the prop switches and the modal is rendered/mounted into it's Portal. There isn't really a `didShow`, in general these components are intentionally hard to reach since they really "private" implementation details.

> I need to reference the modal itself... not the children rendered in the modal.

I mean like: `$(this.refs.body).closest('.modal')` or whatever you need, its hacky, but so is using jQuery with react ;) You can also provide a custom DialogComponent perhaps

**Comment by holgersindbaek** [comment]
The following simply returns "undefined" in my "swipeIn" method:

    log @refs.body
    log @refs.modalComponent.body

I'm a bit new to React. What is "body" supposed to do? How would I get ANY html element I can use in jQuery from my modal reference?

**Comment by jquense** [comment]
sorry in me code the body ref is just something _you_ put on Modal.Body, it was meant as an explanation of what I meant by adding the ref to the inner component

**Comment by holgersindbaek** [comment]
If I try to put a reference on the modal body like so:

      React.createElement ReactBootstrap.Modal,
        className: classNames("modal_component", @props.classNames)
        ref: "modalComponent"
        show: @state.isModalVisible
        onHide: @swipeOut
        onShow: @swipeIn
        animation: false
        autoFocus: false
        ReactBootstrap.Modal.Body,
          ref: "testReference"
          React.DOM.div
            className: "modal_close_button"
            onClick: @swipeOut
            React.createElement IconComponent,
              name: "close_medium"
          React.DOM.div
            className: "modal_content"
            React.DOM.div
              className: classNames("modal_content_container")
              @props.children if @props.children?

Then I get the following error:

    Uncaught Error: Objects are not valid as a React child (found: object with keys {ref}). If you meant to render a collection of children, use an array instead or wrap the object using createFragment(object) from the React add-ons. Check the render method of `ModalDialog`.(…)

How would I put a reference on the modal body, if that is the solution?

From what I can tell, this is not so much a referencing issue as it is a delay issue. I'm hiding my modal from the start, so I can animate it in with a custom animation using velocity. So I need to get a callback after the modal has been rendered and the "onShow" method doesn't seem to do that. how would I create a callback for a "didShow" method?

**Comment by taion** [comment]
You can also just use a custom modal dialog class. Or the lower-level hooks in react-overlays. Or use the jQuery selector as recommended above.
