### ISSUE TITLE
How to get reference to dom node for input without using string refs?

### ISSUE THREAD

**Issue by justin808** [react-bootstrap/react-bootstrap#2319]
Is there any way that we can do this with the callback syntax: https://facebook.github.io/react/docs/refs-and-the-dom.html#the-ref-callback-attribute

I get the below errors with the latest eslint.

```
  114:15  error  Do not use findDOMNode                                 react/no-find-dom-node
  136:17  error  Using string literals in ref attributes is deprecated  react/no-string-refs
```

To reproduce:

1. Clone this repo and uncomment this line that disables eslint: https://github.com/shakacode/react-webpack-rails-tutorial/blob/70faf165c2b77ade7d5019d4d69b47ed0765751e/client/app/bundles/comments/components/CommentBox/CommentForm/CommentForm.jsx#L3

Install all dependencies

2. `cd client && npm run lint`

**Comment by jquense** [comment]
you can use callback refs, you still need to use findDOMNode though. I suggest you disable that rule for that line if it's important, or  better yet rework the component to not use DOM nodes at all
