### ISSUE TITLE
Adding FormControl causes react warning iterator should have a unique "key" prop

### ISSUE THREAD

**Issue by Yuripetusko** [react-bootstrap/react-bootstrap#2320]
Simple example like below causes react warning

```
<FormGroup controlId={id}>
  <ControlLabel>{label}</ControlLabel>
  <FormControl {...props} ref="input" />
</FormGroup>
```

Where value of `label` is just a string.

the warning is: `console.js?93a0:26Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of `FormGroup`. It was passed a child from FieldGroup.`

**Comment by taion** [comment]
This is happening in your code, from your `<FieldGroup>` component.

**Comment by Yuripetusko** [comment]
@taion this is what FieldGroup is rendering

```
render() {
    const {id, label, help, ...props} = this.props;
    return (
      <FormGroup controlId={id}>
        {label && <ControlLabel>{label}</ControlLabel>}
        <FormControl {...props} ref="input" />
        {help && <HelpBlock>{help}</HelpBlock>}
      </FormGroup>
    );
  }
```

And as soon as I remove `<ControlLabel>` the warning is gone

**Comment by Yuripetusko** [comment]
Even if I do simpler version like so I can still see the error:

```
return (
      <FormGroup controlId={id}>
        <ControlLabel>test</ControlLabel>
        <FormControl {...props} ref="input" />
      </FormGroup>
    );
```

**Comment by Yuripetusko** [comment]
If I remove `ref` attribute from <FormControl> the error is gone

**Comment by amannv2** [comment]
Assign a unique key to each element.
