### ISSUE TITLE
onEntered triggering before animation end

### ISSUE THREAD

**Issue by AndrewBailMYOB** [react-bootstrap/react-bootstrap#2321]
Under IE browser, when we setup input with autoFocus, the input cursor will render outside the input box, the reason is it's rendered during modal animation and didn't get re rendered properly. 

![issue](https://cloud.githubusercontent.com/assets/1527902/20046284/186e6d14-a4fc-11e6-8115-b4b99ab84870.jpg)

So as a fix for that, we hooked up to the onEntered callback to focus on the input after animation.

We found ourselves with the same issue. After more investigation it seemed like the onEntered callback was being triggered in the last few frames of the animation.

Are there any alternatives to this or are we using the component incorrectly?

**Comment by taion** [comment]
Interesting – I wonder if the animation isn't beginning synchronously, and if we need to RAF before we start the timeout to fire events.

Ideally with the upcoming move of the React transition group component outside of React core into a third-party library that we own, we can migrate to the updated transition group primitive and fix it there.

**Comment by jquense** [comment]
thisbsoundsvluke a browser issue ultimately tho right? we are using the browser transistion end events to even trigger that statr change

**Comment by AndrewBailMYOB** [comment]
I haven't tested rigorously but it certainly was happening on chrome and IE so it's not an IE specific bug. 
I had a look over your code and it seems correct for just listening to events. So I'm not sure whats occurring.

**Comment by taion** [comment]
We set an explicit timeout in `<Transition>`, no?

**Comment by jquense** [comment]
we do tho i think it's a bit more then the actual animation duration? @AndrewBailMYOB have changed the animation duration in css from the default bootstrap one?

**Comment by taion** [comment]
That can't be right? Otherwise `onEntered` would fire too late, no? Anyway it's 300 ms here and 0.3 s in the stock `bootstrap.css` for modals.

**Comment by jquense** [comment]
firing late is less of a problem i think, the timeout is more of a guard than anything else.

I wonder if this is an odd event loop timer drift issue...or a mismatch between the animation timing and the setTimeout.

**Comment by taion** [comment]
it's an interesting question what the guarantees are... the timers are the same duration ATM anyway

**Comment by shikelong** [comment]
#2286

**Comment by taion** [comment]
not sure there's anything we can do here without a concrete repro
