### ISSUE TITLE
Modal: breaks inputs, controlled by stateful component

### ISSUE THREAD

**Issue by alexfedoseev** [react-bootstrap/react-bootstrap#2323]
I faced this bug w/ 2 libs and it took time to figure out what's going on.

**What's happening: from user perspective**

* Modal contains form w/ controlled input
* in form field user types `123`
* places cursor at the beginning
* types `qwe`
* result: `q123we`.

This is happening b/c cursor jumps to the end of the input on every update.

**What's happening: under the hood**

This is happening when this input is controlled by some stateful component and stateful component + input are children of the modal.

Here is what I observe w/ `console.log`s:

* `onChange` handler triggers the update
* `store` is updated and next value passed to root component via props
*  `console.log` placed next to input shows 2 renders:
1. first w/ obsolete value
1. second w/ up-to-date value

This first render w/ obsolete props is the reason of this issue: input receives outdated value (it's the same value, that is set on input, at this point cursor is placed correctly), but next async update sets next value, vdom flushes this update and browser resets cursor position.

Two libs I faced this issue with: 

* [`react-textarea-autosize`](https://github.com/andreypopp/react-textarea-autosize) (might be related [issue](https://github.com/andreypopp/react-textarea-autosize/issues/68))
* [`react-validation-layer`](https://github.com/shakacode/react-validation-layer)

```js
// The bug exists, 2 renders per update
<Modal>
  <ValidationLayer> // <= Setting the local state and passes value for input
    {layer => <input value={layer.value} />}
  </ValidationLayer>
</Modal>

// In this case no bug, single render per update
// Modal receives up-to-date value from ValidationLayer
<ValidationLayer>
  {layer => (
    <Modal>
      <input value={layer.value} />}
    </Modal>
  )}
</ValidationLayer>
```

Also both libs work correctly when they are not wrapped in `Modal`.

Repo to reproduce: https://github.com/alexfedoseev/react-bootstrap-modal-issue
(It contains only `Textarea` case, I have a lot of unpublished code in `ValidationLayer`, so I'll add this case bit later).

**Comment by jquense** [comment]
I'm fairly certain you're running into https://github.com/facebook/react/issues/5990 which is a frustrating bug that results from how react allows things like modals. unfortunately there isn'tuch that can be done here to fix it until react resolves this. the best bet is to not control the form values across a modal, either by using uncontrolled inputs or fully encapsulating the controlled behavior inside the modal component so you don't run unto this

**Comment by alexfedoseev** [comment]
@jquense Looks like facebook/react#5990 is causing this. We're heavily relying on controlled inputs, so I guess encapsulation is a better choice for us. Thanks!

P.S. Not sure what to do w/ this issue.

**Comment by jquense** [comment]
> We're heavily relying on controlled inputs,

yeah us too, i've found the best option here is to encapsulate `onChange` sort of updates in the modal itself, and when needed you can broadcast out changes to the parent. It's all pretty frustrating tbh i'm hoping React addresses this with their reconciler rewrite. For the time being i think closing this makes sense

**Comment by Kielan** [comment]
can somewhere be noted the way most developers seem to be going about this issue vs the alternative to what should actually be done, I'm having to solve this issue myself now and no docs
