### ISSUE TITLE
How to close customized dropdown with Toggle and Menu components by clicking outside the dropdown?

### ISSUE THREAD

**Issue by wzup** [react-bootstrap/react-bootstrap#2324]
This functionality doesn't work if I use an [example provided](https://react-bootstrap.github.io/components.html#btn-dropdowns-custom). 

Customized dropdown with `Toggle` and `Menu` components can be closed only by clicking the `Toggle` component ("Custom toggle" link on the screenshot below). 
How to enable 
1. the dropdown is closed when I select an option in it
2. the dropdown is closed when I click anywhere on a screen (or the `Toggle` component as it is now)

A screenshot
![react-bootstrap dropdown - google chrome 2016-11-08 15 05 36](https://cloud.githubusercontent.com/assets/3880497/20090026/8f579670-a5c5-11e6-9600-2d95e5e56445.png)

**Comment by jquense** [comment]
you'd have to implement it yourself with something like react-overlays RootCloseWrapper

**Comment by wzup** [comment]
Is this the feature what you are talking about?
https://github.com/react-bootstrap/react-overlays/issues/77
https://github.com/react-bootstrap/react-overlays/pull/111
