### ISSUE TITLE
Tooltip max width and alignment can't be changed

### ISSUE THREAD

**Issue by L5eoneill** [react-bootstrap/react-bootstrap#2325]
The max-width of the tooltip-inner div on a Tooltip component is set in bootstrap.css, and the only way to change it is with your own stylesheet (plus '!important'). Different callers can't change it because it doesn't accept props for tip width.

Also, if you want a top or bottom tooltip to be left-aligned or right-aligned from its trigger target, seems it can't be done.

**Comment by taion** [comment]
That's correct. Use CSS as appropriate; this is a pure styling concern. Also, those position options aren't in upstream TWBS either.

**Comment by L5eoneill** [comment]
The alignment issue is not styling. It comes from the OverflowTrigger and Position components. That is, there is nothing you can do with css to position an overlay at the left margin of the target. Is there no way to give the caller more options for that part?
