### ISSUE TITLE
Unknown Props Warning

### ISSUE THREAD

**Issue by valorize** [react-bootstrap/react-bootstrap#2326]
I get the following error in 0.30.6:

```
Unknown props `active`, `activeKey`, `activeHref` on <p> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop
    in p (created by NavbarText)
    in NavbarText (created by AppClass)
    in ul (created by Nav)
```

According to #1994 this should be fixed in 0.30.0 or? Or was it only for the div element? It would be also really cool if the Nav, NavBar could check if the children is a dom element or a component. And in case it's a dom element does not pass the props.

**Comment by taion** [comment]
`<NavbarText>` doesn't go under `<Nav>`

**Comment by valorize** [comment]
@taion Oh ok, how do I add text then into a Nav element?

My snippet is as follows:
```
<NavItem {...href('/register')} className="highlight left">Register</NavItem>,
<Navbar.Text className="divider" key="divider"> / </Nav.Text>,
<NavItem {...href('/login')} className="highlight right">Log in</NavItem>
```

ideally I would enter a <li> / </li> as replacement. But then I also get the unknown prop problem.

**Comment by jquense** [comment]
Boostrap styles don't really allow for that. if you really want to do it you need to write your own NavDivider component that doesn't pass the injected props through.
