### ISSUE TITLE
Stop event propagation when DropdownButton is clicked?

### ISSUE THREAD

**Issue by olalonde** [react-bootstrap/react-bootstrap#2327]
Is there a way to stop the event propagation to parent elements once the `DropdownButton` is clicked? 

Made this gif for illustration (the parent opens a modal but clicking the Private/Public dropdown should not open it):

![k4srouwxk9](https://cloud.githubusercontent.com/assets/416585/20195027/bc00e75a-a749-11e6-94b0-3c35794ea6f1.gif)

**Comment by taion** [comment]
Add an `onClick` handler and call `stopPropagation` there. You might need to use the lower-level `<Dropdown>`-based API.

**Comment by olalonde** [comment]
Just realized I could simply wrap DropDown inside a <div> which captures onClick events and stops their propagation. So I'm not sure it's really something react-bootstrap should take care of.


```javascript
    <div onClick={e => e.stopPropagation()}>
      <DropdownButton> /* .... */ </DropdownButton>
    </div>
```
