### ISSUE TITLE
Provide a means to allow dropdowns to be scrolled into view after opening

### ISSUE THREAD

**Issue by viridia** [react-bootstrap/react-bootstrap#2328]
I'd like to scroll the menu into view after it has opened. Unfortunately, DropdownButton gives no easy way to access the menu object. (I don't want to look up the element by id because I'd like to do this generically for all dropdown buttons.)

**Comment by taion** [comment]
Use the lower level <Dropdown> API.

**Comment by viridia** [comment]
Could you elaborate? I read the source code for DropdownButton & Dropdown and I don't see any lower level API. Is this mentioned somewhere in the docs?

**Comment by taion** [comment]
`<Dropdown>` is the lower-level API. See the custom menu example.
