### ISSUE TITLE
Popover dismiss on next click

### ISSUE THREAD

**Issue by makedonian** [react-bootstrap/react-bootstrap#233]
I've been trying to figure out how to get the popover to close when you click anywhere outside of it. Tried using the markup from the bootstrap documentation (use href with tabindex=0) but looking through the code, it doesn't seem it's handled anywhere. Am I missing something?

**Comment by lukemcgregor** [comment]
+1 this is also implemented for the modal overlay, it would be great to implement it here too

**Comment by knowbody** [comment]
Here is the solution I came out with http://stackoverflow.com/questions/28935314/reactbootstrap-popover-dismiss-on-click-outside

```
var Hello = React.createClass({
  render: function() {
    return (
      <ReactBootstrap.OverlayTrigger trigger="focus" placement="bottom" overlay={<ReactBootstrap.Popover title="Popover bottom"><strong>Holy guacamole!</strong> Check this info.</ReactBootstrap.Popover>}>
        <ReactBootstrap.Button bsStyle="default">Holy guacamole!</ReactBootstrap.Button>
      </ReactBootstrap.OverlayTrigger>
    );
  }
});

React.render(<Hello />, document.getElementById('app'));
```

**Comment by xterr** [comment]
+1

**Comment by taion** [comment]
Adding a note that this sounds like it's different from the "Dismiss on next click" behavior documented here: http://getbootstrap.com/javascript/#dismiss-on-next-click which dismisses on next click _anywhere_, not just outside of the popover.

**Comment by taion** [comment]
The "dismiss on click outside trigger" functionality from base Bootstrap is available by setting trigger to `focus`, though this could be better documented.

As mentioned, the correct logic for "dismiss on click outside popover" would require using logic like in DropdownStateMixin. I think this is worth adding, but it's not in Bootstrap JS as far as I can tell.

What's our policy on adding features that don't have upstream analogues?

**Comment by mtscout6** [comment]
When it comes to the JavaScript we are kind of at liberty to decide a little bit. For small nice things like this I don't see any harm to having it. When it comes to styling and html layout though we should stick with base Bootstrap as much as possible.

**Comment by taion** [comment]
I can add this. I think this should be a prop on `PopoverTrigger`. I can't think of a name for it, though. `autoDismiss` is too ambiguous, while `dismissOnClickOutside` is too verbose and doesn't convey that pressing "escape" will also dismiss.

**Comment by AlexKVal** [comment]
`dismissable` ?

**Comment by taion** [comment]
A little too ambiguous. I'm going to go with something like `modalDismiss`, I think.

**Comment by aldendaniels** [comment]
While this functionality should definitely be supported out of the box, this can be achieved today:

```javascript
constructor() {
    super(...arguments);
    this.bodyOnClick = this.bodyOnClick.bind(this);
}

componentDidMount() {
    $('body').on('click', this.onBodyClick);
}

componentWillUnmount() {
    $('body').off('click', this.onBodyClick);
}

onBodyClick(event) {
    var trigger = this.refs.trigger;
    var overlayElem = React.findDOMNode(this.refs.overlay);
    var isTargetInOverlay = $(event.target).closest(overlayElem).length > 0;
    if (trigger.state.isOverlayShown && !isTargetInOverlay) {
        trigger.setState({
            isOverlayShown: false
        });
    }
}

render() {
    return (
        <OverlayTrigger ref="trigger" placement='top' trigger="click" delay={0} overlay={
            <Tooltip ref="overlay">Hello World!</Tooltip>
        }>
            <span tabIndex="0" className="icon-info2 info-trigger"></span>
        </OverlayTrigger>
    );
}
```

**Comment by taion** [comment]
That's essentially what the `RootCloseWrapper` that I add in #698 does.

**Comment by aldendaniels** [comment]
@taion - Thanks! I'd missed that you had an open PR for this.

**Comment by kadariyp** [comment]
How can it be closed when there is a cross mark in the overlay? I want it to be dismissed onClick of that cross mark. `<OverlayTrigger ref="portfolioKeyOverlay" trigger="click" rootClose placement="bottom"
                        overlay={
                          <Tooltip id="tooltip" className="portfolioPopOver">
                          <span id="portfolioClose" className='glyphicon glyphicon-remove' onClick={this.closeClicked}></span>
                            Encypted Portfolio Key:<br/>{this.props.data.portfolioKey}

                          </Tooltip>
                        }>
                        <span className='portfolioKey'></span>

                      </OverlayTrigger>`

**Comment by 11th** [comment]
```cjsx
	handlePopoverClose: ->
		@refs.trigger.hide()

	render: ->
		<OverlayTrigger
			trigger="click"
			ref="trigger"
			overlay={
                        <Popover><button onClick={@handlePopoverClose}>close</button></Popover>
                        }
		>
                 <button>Open popover</button>
		</OverlayTrigger>
```

**Comment by kadariyp** [comment]
@11th Thanks.

**Comment by larrydahooster** [comment]
I am just wondering about the following behavior. Is this intended?

When rootClose = false the onClick event toggles the overlay visibility. When rootClose = true the onClick on the button does not toggle the overlay anymore. The only way to hide the overlay is by triggering the rootClose (or using the API).

**Comment by taion** [comment]
That looks like a regression. Let me see.

**Comment by akhi9** [comment]
> I am just wondering about the following behavior. Is this intended?
> 
> When rootClose = false the onClick event toggles the overlay visibility. When rootClose = true the onClick on the button does not toggle the overlay anymore. The only way to hide the overlay is by triggering the rootClose (or using the API).




+1

**Comment by leandromalves** [comment]
If my popover have a button, and trigger is "focus" => set a value to "delayHide" para into OverlayTrigger:
<OverlayTrigger
                trigger="focus"
                placement="top"
                delayHide={300}
                overlay={popover}
                
 The button action will be call. Value > 250 is better.
