### ISSUE TITLE
Delete image from carousel

### ISSUE THREAD

**Issue by DiegoGallegos4** [react-bootstrap/react-bootstrap#2330]
I am using 0.30.6. 

I am using the carousel to upload images. I am adding a button that will allow the user to delete the image. The script to delete the images looks like this: 

`deleteImage(idx){
    const {images} = this.state.form
    console.log(this.carousel)
    this.setState({
      form: update(this.state.form,{
        $merge: {
          images: images.filter((img, i) => i !== idx),
        }
      }),
      index: this.state.index > 0 ? this.state.index - 1 : 0
    })
  }`

There are a couple of cases:

CASE 1: When the first image is deleted it behaves as expected. It loads the remaining images.
CASE 2: Delete other than the first. It does not load the remaining images. What I see is that there is no .item div with . active, the images are in the DOM but the carousel renders as empty.

Is there any way to reload the whole component or to toggle the first element with the .active class?

**Comment by taion** [comment]
dupe https://github.com/react-bootstrap/react-bootstrap/issues/1914
