### ISSUE TITLE
Accordion Panel ignores timeout parameter

### ISSUE THREAD

**Issue by mityok69** [react-bootstrap/react-bootstrap#2331]
The Panel component when it's a part of the Accordion and should be collapsable, doesn't pass the timeout parameter to it.
So while you can specify the transition duration in css ('collapsing' class) the animation will still terminate after 300ms.
required fix - inside Panel.js render:

add this line:

`var timeout = _props.timeout;`

and add here:

`this.renderCollapsibleBody(id, expanded, panelRole, children, bsProps, { onEnter: onEnter, onEntering: onEntering, onEntered: onEntered, onExit: onExit, onExiting: onExiting, onExited: onExited, **timeout: timeout** }) : this.renderBody(children, bsProps),`

**Comment by taion** [comment]
It doesn't make sense to add this at the `<PanelGroup>` level (that's all `<Accordion>` is anyway), because the timeout could be different for each panel.

**Comment by mityok69** [comment]
The panel is the one that ignores the parameter. Perhapse the issue isn't clear enough:
No matter what duration is set for collapse / expand in css it gets stopped by default value of Collapse component. And there is no way to override it

**Comment by jeffvandyke** [comment]
I have a very similar issue. In my case, I'm trying to use `<Panel collapsible header={...}>...</Panel>`, and for performance reasons, I wanted to disable the animation. I dug around for a property or even a global value to change, but I just found that Collapse had a defaultProp: timeout: 300, and the Panel component allowed no path to override this. Perhaps `Panel` collapsible property could accept an object with properties to be passed to the `Collapse` component? Just a suggestion.
