### ISSUE TITLE
Multilevel menuItems / dropdowns

### ISSUE THREAD

**Issue by optyler** [react-bootstrap/react-bootstrap#2333]
Hi,

it will be awesome if you guys allow a simple way to create multi-level menu / dropdowns as in this capture below : 
<img width="674" alt="capture d ecran 2016-11-15 a 13 42 51" src="https://cloud.githubusercontent.com/assets/10259/20306214/703fe124-ab39-11e6-9fa9-d92f7360002c.png">

**Comment by taion** [comment]
Did you search at all for older issues before you opened this? If you did, you'd have seen us note that this isn't part of Bootstrap. There's no CSS for this, so there's no way even in principle that we can add this feature.

So no, it's not going to happen.

**Comment by optyler** [comment]
Hi,
I looked through the issues yesterday but did not saw it.
Sorry for the inconvenience.
