### ISSUE TITLE
Responsive navbar example and internal div.container

### ISSUE THREAD

**Issue by VictorVolovik** [react-bootstrap/react-bootstrap#2339]
I tried to use navbar from example - https://react-bootstrap.github.io/components.html#navbars-mobile-friendly and got this:

![screen shot 2016-11-17 at 19 49 38](https://cloud.githubusercontent.com/assets/11180621/20398601/13c8c132-acff-11e6-8ec3-7cc67e9ed2b3.png)

I inspected DOM:

![screen shot 2016-11-17 at 19 50 40](https://cloud.githubusercontent.com/assets/11180621/20398632/3300683e-acff-11e6-8122-75053a075969.png)

I deleted inner container class and got issue fixed:

![screen shot 2016-11-17 at 19 52 06](https://cloud.githubusercontent.com/assets/11180621/20398665/58bf83b6-acff-11e6-9fac-44d1febbe17d.png)

![screen shot 2016-11-17 at 19 52 30](https://cloud.githubusercontent.com/assets/11180621/20398692/6a922044-acff-11e6-822a-4405e158a958.png)

I tried fix this in Navbar component inside react-bootstrap, but didn't understand how this internal container was created.

I'm kindly asking for your help or advice if isn't a bug.

**Comment by jquense** [comment]
its not a bug. The container is supposed to go inside the navbar. Try not nesting the navbar in any other container

**Comment by VictorVolovik** [comment]
As I understand React-Bootstrap functionality is based on Bootstrap.

There are 3 navbars examples on [Bootsrap Getting Started](http://getbootstrap.com/getting-started/#examples-navbars), and 1st of them is [this](http://getbootstrap.com/examples/navbar/).

<img width="1440" alt="screen shot 2016-11-17 at 21 40 41" src="https://cloud.githubusercontent.com/assets/11180621/20402680/b55bc1fc-ad0e-11e6-992b-2eeae6fb7576.png">

Html markup:

<img width="450" alt="screen shot 2016-11-17 at 21 41 18" src="https://cloud.githubusercontent.com/assets/11180621/20402720/f1197892-ad0e-11e6-938a-9d06f9d9c656.png">

As you see, navbar is nested inside container.

**Comment by jquense** [comment]
yes a container > container-fluid, you can add fluid to you navbar if you want the same thing

**Comment by VictorVolovik** [comment]
> you can add fluid to you navbar if you want the same thing

There is no way to do this:

```
<Navbar className="container-fluid" inverse collapseOnSelect>
  <Navbar.Header>
    <Navbar.Brand>
      <a href="#">React-Bootstrap</a>
    </Navbar.Brand>
    <Navbar.Toggle />
  </Navbar.Header>
  <Navbar.Collapse>
    <Nav>
      <NavItem eventKey={1} href="#">Link</NavItem>
      <NavItem eventKey={2} href="#">Link</NavItem>
    </Nav>
    <Nav pullRight>
      <NavItem eventKey={1} href="#">Link Right</NavItem>
      <NavItem eventKey={2} href="#">Link Right</NavItem>
    </Nav>
  </Navbar.Collapse>
</Navbar>
```

Result:

![screen shot 2016-11-18 at 10 54 54](https://cloud.githubusercontent.com/assets/11180621/20422785/88a51982-ad7d-11e6-8e8e-61d7cbc42d4d.png)

![screen shot 2016-11-18 at 10 55 04](https://cloud.githubusercontent.com/assets/11180621/20422791/8bd02ffc-ad7d-11e6-91fc-871c77169918.png)

**Comment by jquense** [comment]
the prop is `fluid`, please read the documentation https://react-bootstrap.github.io/components.html#navs-props-navbar
