### ISSUE TITLE
Attribute data-filter-control is not working

### ISSUE THREAD

**Issue by dudewalking** [react-bootstrap/react-bootstrap#2340]
Hi! I ran into a problem while was rendering a table using such attributes as data-toggle, data-search and etc. For example, with data-search everything is fine, but data-filter-control is not even shown up. Well, I can't use filtration using data-filter-control at all... Please fix it or let me know how to use it in correct way.

Thanks.

**Comment by jquense** [comment]
there is nothing special about the table l component it just passes through your props to the table element.  some other library (presumably the one that uses those attributes) is removing them
