### ISSUE TITLE
TabPane and bsClass issue

### ISSUE THREAD

**Issue by acateland** [react-bootstrap/react-bootstrap#2343]
When i want to actually set a bsClass on TabPane rendered inside a Tabs component 
```javascript
				<Tabs defaultActiveKey={1}>
						<TabPane bsClass="test" eventKey={1} title="Processors">
							<p>tab1</p>
						</TabPane>
						<TabPane bsClass="test" eventKey={2} title="Sink">
							<p>tab2</p>
						</TabPane>
				</Tabs>
```
bsClass are never shown in rendered html.
Minimum case to reproduce this issue incoming

**Comment by acateland** [comment]
https://jsbin.com/tinamepuqo/edit?html,js,console,output

**Comment by jquense** [comment]
https://jsbin.com/fuverukuzo/edit?html,js,console,output

When using the higher level `Tabs` component set bsClass on that component. The actualy TabPane's you specify there aren't rendered, only used as a general pattern to construct them, in fact TabPane doesn't belong inside a Tabs component. 

If you want finer control over the rendering use the lower level TabContainer and friends.
