### ISSUE TITLE
Override default styling using inline styles 

### ISSUE THREAD

**Issue by Extra-lightwill** [react-bootstrap/react-bootstrap#2348]
Is it possible to override default styling using inline styles with react-bootstrap?

For instance, I would expect the below code to make the button 1000px in width - however, there is no effect. 

```
class Header extends React.Component
{
  render() {

       const ButtonStyle = {
        width: 1000,    
      };

    return ( 

    <div className="header">

    <Button bsClass={ ButtonStyle }> Test button
    </Button> 

    </div> 

    );
  }
}

 
```

Any help with this issue is much appreciated. 

Thanks.

**Comment by jquense** [comment]
you want to use the actual style prop. bsClass is for adjusting the way bootstrap css classes are applied to the components not inline styles
