### ISSUE TITLE
Collapse inline style problem

### ISSUE THREAD

**Issue by chochihim** [react-bootstrap/react-bootstrap#2349]
Let's take [https://react-bootstrap.github.io/components.html#transitions-collapse](https://react-bootstrap.github.io/components.html#transitions-collapse) as example. 

Before expanding, element `<div class="collapse" data-reactid="8541">...</div>` does not contain inline style. During expanding, this elements become `<div class="collapsing" data-reactid="8541" style="height: 100px;">...</div>` which contains inline style. After expanding, it turns to `<div class="collapse in" data-reactid="8541"">...</div>`, which is without inline style.

And then I collapse it. I suppose the above changing is totally reversed. However, after collapsing, that element becomes `<div class="collapse" data-reactid="8541" style="height: 0px;">...</div>` which has inline style left.

Can this `style="height: 0px;"` be removed so that the behaviour is more consistent?

**Comment by jquense** [comment]
removing it would cause an additional render for no benefit. I don't see any harm in leaving it, its consistent with how vanilla bootstrap works as well

**Comment by chochihim** [comment]
I have a use case that the collapsable part needs to be 

1) kept shown on screen in desktop view
2) able to be expanded/collapsed in tablet view

I achieve 1) using css. However, if someone resizes his browser and play with the collapsable element, the reductant inline style `style="height: 0px;"` breaks my layout. Can you give me any hint about how to resolve it?

**Comment by taion** [comment]
you can strip it yourself in the `onExit` callback
