### ISSUE TITLE
DropdownButton doesn't pass tabIndex

### ISSUE THREAD

**Issue by txm** [react-bootstrap/react-bootstrap#2350]
```
<DropdownButton tabIndex='1'>
```

```
 60     return _react2['default'].createElement(
 61       _Dropdown2['default'],
 62       _extends({}, dropdownProps, {
 63 tabIndex: 1, // HERE!
 64         bsSize: bsSize,
 65         bsStyle: bsStyle
 66       }),
```

**Comment by taion** [comment]
It passes it just fine to the underlying toggle.

**Comment by txm** [comment]
Would you be so kind to point me to a file/line number where this happens?  HotKeys doesn't seem compatible with DropdownButton when re-rendered (unless called the first time with autoFocus).  

I can't see where tabIndex would be pulled in unless I specifically name it, as above.

**Comment by jquense** [comment]
the tabIndex is passed to the `toggle` component not the wrapping `btn-group` that is the Dropdown container. If you want to pass the tabIndex to the outer container use the Dropdown component instead of the DropdownButton one
