### ISSUE TITLE
Getting Autoaffix elements to work. 

### ISSUE THREAD

**Issue by paschalidi** [react-bootstrap/react-bootstrap#2351]
What I am doing is having a Row with 2 Columns in order to set up the Layout of my main pages.

```
class Layout extends React.Component {
  static propTypes = {
    children: PropTypes.node.isRequired,
  };
  render() {
    return (
      <div>
        <Header />
        <Grid>
          <Row>
            <Col xs={12} md={3}>
              <PersonalInfo />
            </Col>
            <Col xs={12} md={6}>
              <MainPageInfo />
            </Col>
          </Row>
        </Grid>
        <Feedback />
        <Footer />
      </div>
    );
  }
}
```

Wanted functionality is to have a box with my personal Info sticky while the user scrolls the ``<MainPage />`` element.

The problem is that I can make it work only when ``<PersonalInfo />`` looks like that,

```
class PersonalInfo extends React.Component {
  render() {
    return (
      <div>
        <AutoAffix viewportOffsetTop={80} container={this}>
          <div className='panel panel-default'>
            <div className='panel-body'>
              I am an affixed element
              I am an affixed element
              I am an affixed element
              I am an affixed element
              I am an affixed element
              I am an affixed element
              I am an affixed element
              I am an affixed element
              I am an affixed element
            </div>
          </div>
        </AutoAffix>
        <div style={{height: "4000px"}}/>
      </div>
    );
  }
}

```

When I remove the line ``<div style={{height: "4000px"}}/>`` Autoaffix breaks.

Could someone hit me so I can get over this please? 

Like I have thought that a probable solution is to make the height of the column equal with the height of the heightest column but I don't fancy hacking this around. 
I would like to have a more clean and reusable solution please. 

PS I am using only AutoAffix component from react-overlays no Waypoint or something else.

**Comment by taion** [comment]
The element embedding the affix needs to have the appropriate height. Your div presumably doesn't. If your page doesn't satisfy these constraints, just use `<Affix>`, or set the container on the `<AutoAffix>` differently.

**Comment by paschalidi** [comment]
Cool man that works perfectly. Thanks a lot
