### ISSUE TITLE
Problems building with webpack

### ISSUE THREAD

**Issue by kempfe** [react-bootstrap/react-bootstrap#2353]
Hello Guys,

i got a strange problem.
im using 
import { Table, Tab, Tabs } from 'react-bootstrap';
within a container of react boilerplate

in my hot reloader / development everything is working fine !

but when i start building for production i get call() on undefined error.

anyone got similar problems ?
any solutions or ideas where the issue could be ?

thx in advance

**Comment by taion** [comment]
We're using webpack and aren't seeing this problem. Do you have a repro repo available?

**Comment by kempfe** [comment]
https://github.com/mxstbr/react-boilerplate is the base boilerplate im using
i only installed some additional npm packages like ofc react-bootstrap, fetch etc.
whenever i import react-bootstrap - even without a useage - i get call() on undefined when
building production.

**Comment by dozoisch** [comment]
Do you have a stack trace or something? It's really hard to pinpoint the issue without being able to repro by ourselves or having a trace, etc.

**Comment by kempfe** [comment]
im back at work on monday and will post the stacktrace then. 
but as it is webpacked not sure you can read a lot out of it ?!

**Comment by kempfe** [comment]
http://p1004.logmedia.at/
aye here is the link

**Comment by taion** [comment]
Please follow up with the maintainers of the boilerplate. This works fine with a basic webpack setup. It's quite possible that the boilerplate you're using is applying e.g. unsafe optimizations.

**Comment by kempfe** [comment]
i found the issue
building with plugin
webpack.optimize.DedupePlugin()
creates the above stated error.

is this stil something the react-boilerplate team has to look into ?
