### ISSUE TITLE
 Popover causes a warning "You are manually calling a React.PropTypes validation function "

### ISSUE THREAD

**Issue by subhamagr** [react-bootstrap/react-bootstrap#2354]
The Popover component causes an error:

> Warning: You are manually calling a React.PropTypes validation function for the `id` prop on `Popover`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.

> Warning: You are manually calling a React.PropTypes validation function for the `onHide` prop on `Popover`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.

How to fix this?

**Comment by taion** [comment]
Upgrade from whatever ancient version you're using
