### ISSUE TITLE
Feature: Form.get/setFieldValues

### ISSUE THREAD

**Issue by shinxi** [react-bootstrap/react-bootstrap#2355]
Can we add get/set FieldValues to Form class, at least add getFieldValues, that'll be very useful for data submit.
See redux-form/formsy-react, they all have a way to get its form data.

**Comment by jquense** [comment]
see the previous issuea and discussion around this for more context but no, we arent going to add getters/setters because it codifies and encourages a bad/unreacty pattern for dealing with forms
