### ISSUE TITLE
Nesting columns

### ISSUE THREAD

**Issue by nadavkaner** [react-bootstrap/react-bootstrap#2357]
when i'm doing this nesting columns:
`<Row> 
                    <Col xs={11}>
                        <div>
                        </div>
                    </Col>
                    <Col xs={1}>
                        <Row>
                            <Col xs={6}>
                            </Col>
                            <Col xs={6}>
                            </Col>
                        </Row>
                    </Col>
                </Row>
`
the nested columns getting stack in smaller device.
the behavior that i'm expected is that they don't stack like in the original bootstrap.
why this is happening?

**Comment by taion** [comment]
It works the same as it would with normal rows and columns in Bootstrap. This is all in the CSS.
