### ISSUE TITLE
add componentClass for ListGroupItem

### ISSUE THREAD

**Issue by zedrdave** [react-bootstrap/react-bootstrap#2360]
Currently, ListGroupItem automatically selects the component tag, based on other properties. E.g: providing `href` or `onClick` result in a `a` or `button` tag.

It would be nice to have the option to override this by adding a `componentClass` argument similar to `ListGroup`, so that one can get a nice semantic ul/li structure, yet have clickable elements.

Additionally, this would improve consistency with `ListGroup`, which can be overridden (resulting in ul+button etc in the final markup)…

**Comment by taion** [comment]
dupe https://github.com/react-bootstrap/react-bootstrap/issues/983
