### ISSUE TITLE
Question: When the modal 'show' attribute changes to hidden, does it unmount the modal component?

### ISSUE THREAD

**Issue by joetidee** [react-bootstrap/react-bootstrap#2361]
I am experiencing some strange behaviour in my application, so just wanted to ask if the Modal component unmoints itself under certain conditions, e.g. when the `show` attribute is changed to `false` (?)

`<Modal show={this.state.modalVisible}  ... />`

**Comment by taion** [comment]
see `unmountOnExit`

**Comment by joetidee** [comment]
Where is `unmountOnExit` ? In the documentation?

**Comment by archmisha** [comment]
I would like to use this property as well. But react says its unknown prop:
Unknown prop `unmountOnExit` on <div> tag. Remove this prop from the element

**Comment by joetidee** [comment]
It doesn't appear to be a part of the Modal component, so am assuming that the Modal does not need it (?)

**Comment by dperetti** [comment]
In my experience:
1. It's not unmounted.
2. `unmountOnExit` doesn't work on `Modal`.
