### ISSUE TITLE
Media + Thumbnail

### ISSUE THREAD

**Issue by TrejGun** [react-bootstrap/react-bootstrap#2362]
Media + Thumbnail 
Media + Image[thumbnail]

These combinations gives image with zero width

https://codepen.io/trejgun/pen/RojMoZ

**Comment by jquense** [comment]
hi there. looks like this is a css issue, which isn't our domain, since we defer to the upstream bootstrap. Seems this combination isn't supported, you can use the `style` prop to override the styles to make it work if you'd like.

**Comment by TrejGun** [comment]
@jquense , actually this combination works fine

```html
<div class="media">
	<div class="media-left">
		<img src="..." width="100" height="100" class="media-object img-thumbnail">
	</div>
	<div class="media-body">
		<!-- -->		
	</div>
</div>
```

**Comment by jquense** [comment]
that markup is different, specifically the react example doesn't have the media-object class

**Comment by TrejGun** [comment]
yes, its not in example its in issue tracker

https://github.com/twbs/bootstrap/issues/16120
https://github.com/twbs/bootstrap/pull/16350
