### ISSUE TITLE
[overlayTrigger][touch device] trigger='hover' integration with react-fastclick

### ISSUE THREAD

**Issue by Limycuk** [react-bootstrap/react-bootstrap#2363]
I have list of tooltips on the page (below example one of them). If I use react-fastclick it doesn't show first tooltip for touch devices (no matter how much i have clicked), then i click another tooltip and all work fine.

```jsx
<OverlayTrigger animation={false} overlay={tooltip} trigger={['hover']}>
  <i className="fa fa-info" />
</OverlayTrigger>
```

I tried to use trigger click, but it doesn't hide on click out side.

```jsx
<OverlayTrigger animation={false} overlay={tooltip} trigger={['click']}>
  <i className="fa fa-info" />
</OverlayTrigger>
```

Could you investigate this case?

**Comment by taion** [comment]
essentially a dupe of https://github.com/react-bootstrap/react-bootstrap/issues/831
