### ISSUE TITLE
Disabling onClick on disabled with child element

### ISSUE THREAD

**Issue by grydstedt** [react-bootstrap/react-bootstrap#2364]
If a Button has an element inside it the click handler goes through, at least on latest Chrome 54.

```
<Button onClick={() => alert(1)} disabled>
   <span>Some text</span>
</Button>
```

is this something we'd want to handle in react-bootstrap?

**Comment by taion** [comment]
Looks like a bug where we only handle `disabled` in `<SafeAnchor>`

**Comment by jquense** [comment]
that's only because actual buttons and inputs should natively respect `disabled`.

**Comment by grydstedt** [comment]
Right, but react-bootstrap Button could block the propagation. Seems like the more desirable behavior, no?

**Comment by grydstedt** [comment]
Common use case is including some icon element in the button.

**Comment by jquense** [comment]
can you take and post a screen shot of the actual DOM markup that's produced. My tests with a plain `<button disabled>` don't acknowledge the click, and the SafeAnchor version ignores onClicks when its disabled manually

**Comment by taion** [comment]
It happens if you put a `<span>` in the button, like with

```js
<button onClick={() => alert('asdf')} disabled>
  <span>asdf</span>
</button>
```

But I wonder if we shouldn't match the browser behavior here?

**Comment by grydstedt** [comment]
Yeah, not sure. I'm thinking that the use case of having an individual element within clickable while button isn't seems less useful than the opposite, but I guess browsers felt differently.

**Comment by jquense** [comment]
I tried in chrome with an inner span and still no click...

**Comment by grydstedt** [comment]
What version of Chrome? I'm on 54.0.2840.98

**Comment by jquense** [comment]
interestingly I think this is a React bug, due to how it delegates events to the document

http://codepen.io/anon/pen/WodGqx?editors=1010

**Comment by grydstedt** [comment]
https://github.com/facebook/react/issues/8308

**Comment by grydstedt** [comment]
You're right
