### ISSUE TITLE
How to add custom button class

### ISSUE THREAD

**Issue by aaronbeall** [react-bootstrap/react-bootstrap#2368]
I have some additional button class names, such as `btn-toggle`, but when I try to pass this to `<Button bsStyle="toggle">` I get a prop type warning:

> warning.js:36 Warning: Failed prop type: Invalid prop `bsStyle` of value `toggle` supplied to `Button`, expected one of ["success","warning","danger","info","default","primary","link"].

I could rename the style to match one of the bs styles, but is there not a way to add my own?

**Comment by jquense** [comment]
check out: http://react-bootstrap.github.io/components.html#custom-styles

**Comment by aaronbeall** [comment]
Thanks!
