### ISSUE TITLE
ListGroupItem and Button component hrefs are resulting in page loads.

### ISSUE THREAD

**Issue by PaulSavignano** [react-bootstrap/react-bootstrap#2369]
The hrefs on ListGroupItem and Button components are currently resulting in page loads. Is this a bug or should the ListGroupItem use a browserHistory.push() and the Buttons be wrapped in Link elements?

**Comment by taion** [comment]
This package makes no assumptions on what router you're using. You can take a look at React-Router-Bootstrap if you're looking for a React Router integration.

**Comment by PaulSavignano** [comment]
Thanks Taion, I'll check it out!  So is the page loading from the hrefs a correct behavior?  This could result in a reset of state.  I also thought React was free of page loads once inside an app.

**Comment by taion** [comment]
It's just a link. SPA/router/whatever builds on top of that.

**Comment by PaulSavignano** [comment]
Got it.  I appreciate the clarification!
