### ISSUE TITLE
Navbar toggle doesn't work.

### ISSUE THREAD

**Issue by jenil27** [react-bootstrap/react-bootstrap#237]
Hey guys,

I am trying to get the Navbar toggle to work but it doesn't seem to be working. Here is my code:

`<Navbar staticTop={true} fluid={true} brand={brand} toggleButton>`

Anyone?

**Comment by kellyrmilligan** [comment]
ran into the same issue, what I ended up doing was this:

```
<Navbar ref="header" className={classString} brand={brand} fixedTop={true} fluid={true} toggleNavKey={1} bsStyle=''>
        <Nav className="navbar-left" eventKey={1}>
          <NavItem href="/shows">Watch</NavItem>
          <NavItem href="/locations">Explore</NavItem>
          <a href="/app" className="btn btn-default navbar-btn get-app">Get the app</a>
        </Nav>
      </Navbar>
```

and I positioned the link tag above abosolute and right when in desktop mode, and relative when in mobile nav mode.

**Comment by rundis** [comment]
Any progress on this use case (having to ul tags, one of which is pulled right ) ?

**Comment by snario** [comment]
I added on this CSS to get around the issue. (I only have one `li` I want to be on the right and the rest left)

```
@media only screen and (min-width: 760px) {
    ul.navbar-nav {
        width: 90%;
    }
    ul.navbar-nav > li:last-child {
        float: right !important;
    }
}
```

**Comment by mtscout6** [comment]
Does #400 solve your problem?

**Comment by snario** [comment]
yes

**Comment by snario** [comment]
Yes!

**Comment by mtscout6** [comment]
Awesome, @jenil27 if this still crops up on you feel free to re-open.
