### ISSUE TITLE
[OverlayTrigger][iphone 5][Safari] property rootClose doesn't work

### ISSUE THREAD

**Issue by Limycuk** [react-bootstrap/react-bootstrap#2370]
Clickoutside doesn't hide tooltip in safari with "rootClose"
```jsx
<OverlayTrigger animation={false} placement={placement} overlay={tooltip} trigger={['click']} rootClose>
   <i className="fa fa-info-circle"></i>
 </OverlayTrigger>
```

**Comment by taion** [comment]
same as https://github.com/react-bootstrap/react-bootstrap/issues/1906

**Comment by ReactGirl** [comment]
1906 is closed.

Issue opened:
https://github.com/react-bootstrap/react-overlays/issues/158
