### ISSUE TITLE
Is there an 'onCellClick' handler, or something like it?

### ISSUE THREAD

**Issue by bmueller-sykes** [react-bootstrap/react-bootstrap#2371]
Hi,

I'm unclear on how to handle links within cell data. All the examples I've seen in react-bootstrap-table have plain text data as the contents of the `<td>` cells. What I'd like to do is be able to have links in my data. For example, if I have a table showing a list of users, I want to be able to click on the username of said user to drill down into that specific user record. I realize I could `onRowClick()`, but if I had a row of data that had more than 1 item I'd like to click on (e.g. username and user's country), then that method isn't sufficient.

So I guess this is a two-part question: 

* Is there some sort of `onCellClick()` method that I could pass to `TableHeaderColumn`?

* Is it possible for the `data` prop of `BootstrapTable` to take an array where the values are complex strings, or perhaps even React components?, like:

```
const data = [
  { id: 1, username: <UsernameLink name='bob' userId={1} />},
  { id: 2, username: <UsernameLink name='tom' userId={2} />}
]
```

Thanks in advance!

**Comment by taion** [comment]
Just put `onClick` handlers on the `<td>` or whatever you render in the `<td>`.

**Comment by jquense** [comment]
Also I think you are looking for this repo: https://github.com/AllenFang/react-bootstrap-table we don't maintain that component, jsut a plain table

**Comment by bmueller-sykes** [comment]
oh son of a...

sorry about that.
