### ISSUE TITLE
Using Chartjs with Rect-Bootstrap Tab Navigation

### ISSUE THREAD

**Issue by dezmondfinney** [react-bootstrap/react-bootstrap#2373]
I'm not sure if this is the right place to ask for help but if this is not the right place maybe someone can help me get to the right place. Chart.js will not render if the element is hidden. [One solution](http://stackoverflow.com/questions/29806924/chart-js-render-in-hidden-bootsrap-tab) is to manipulate the DOM directly using the `show.bs.tab` event that bootstrap provides. Obviously, this is not the best way to work in react. Broadly speaking, you shouldn't manipulate by hand the DOM that React has created. What is the best way to handle this particular problem?

**Comment by taion** [comment]
Try `unmountOnExit`

**Comment by jquense** [comment]
I may be misunderstanding but I think @dezmondfinney wants to run some code when the tab is shown, not unmount something when it's hidden.

I can't really think of a way to handle this from the prespective of the TabPane. I guess you could check the tabContent context to see if the parent tab is expanded, but that's pretty messy. if the tabs are animating you can use the `onEntered` hook which is similar to the bootstrap event

**Comment by taion** [comment]
`unmountOnExit` would accomplish this right? if you put the logic in cDM, then it won't run until the tab shows, no?

**Comment by jquense** [comment]
o right, sort of i guess. you lose everything tho when the tab is hidden. Less then ideal

**Comment by dezmondfinney** [comment]
Thanks for the quick response but I don't understand the difference between the two functions or if I should put the DOM manipulation in the function. I've avoided doing that by using react-chartjs. Thanks again for helping the noob.

**Comment by dezmondfinney** [comment]
Never-mind, I misread yesterday I thought unmountOnExit had a function callback not a Boolean value. Tried it and it worked. Thanks.
