### ISSUE TITLE
BsClass not working for styling MenuItem

### ISSUE THREAD

**Issue by darewreck54** [react-bootstrap/react-bootstrap#2374]
For MenuItems, the bsClass prop does not work for styling it.

https://jsfiddle.net/m3hg89yt/9/

In this example, notice that the drop down menu item is not colored like it should be.

if you look at the generated html code:

```
<li role="presentation" class >
</li>

```

Shouldn't it be

```
<li role="presentation" class="custom-buttom" >
</li>
```

It looks like the class isn't being set or passed down in the react component;

Any Advice appreciated,
Thanks,
D

**Comment by taion** [comment]
`<MenuItem>` doesn't take `bsClass` because there's no particular class associated with it in Bootstrap.

**Comment by p77u4n** [comment]
@taion What you said is different what the document says, I am very confused about that.

**Comment by aabhas** [comment]
@taion I second @nickvoronin, documentation suggests custom classes can be added. However, bsClass doesn't appear to be working for me either

**Comment by taion** [comment]
This is only relevant for headers. If you want a custom class, just use `className`.
