### ISSUE TITLE
Panel title class should only be added to a heading element

### ISSUE THREAD

**Issue by gavmck** [react-bootstrap/react-bootstrap#2375]
When passing in HTML/JSX to a panel header, it should only add `.panel-title` class if the element is a heading element eg `h3`. 

I have a panel header that contains a title and some buttons so I need to pass in a JSX div containing these elements. The panel title class is added to my wrapper div when it should only be on the title.

**Comment by jquense** [comment]
yup. addressed in https://github.com/react-bootstrap/react-bootstrap/pull/1769 if we can ever get it finished
