### ISSUE TITLE
bsSize property on FocmControl appears to add wrong class

### ISSUE THREAD

**Issue by gavmck** [react-bootstrap/react-bootstrap#2376]
http://getbootstrap.com/css/#forms-control-sizes

The bootstrap docs would suggest this should add the class of `input-lg` if I pass `bsSize="lg"` into FormControl, but it adds `form-control-lg` which has no bootstrap CSS associated with it.

**Comment by taion** [comment]
this is https://github.com/react-bootstrap/react-bootstrap/issues/1889
