### ISSUE TITLE
Ability to add additional css class to anchor element of Panel heading

### ISSUE THREAD

**Issue by softweave** [react-bootstrap/react-bootstrap#2381]
To support toggling icons to accordion panel headers like those in this [accordion with arrow glyphs](https://codepen.io/tofanelli/pen/waadRY/) example, need to be able to configure additional css class for anchor element in Panel heading.

**Comment by taion** [comment]
would be covered by https://github.com/react-bootstrap/react-bootstrap/issues/983

**Comment by softweave** [comment]
I don's see mention of this in the referenced ticket, so will submit my implementation of this feature for your consideration.

**Comment by jquense** [comment]
I might hold off we already have a PR up implementing this

**Comment by softweave** [comment]
I needed this feature now, so couldn't wait. Will be looking for a master update that implements this.
