### ISSUE TITLE
'onClick' handler for <Breadcrumb.item> ?

### ISSUE THREAD

**Issue by bmueller-sykes** [react-bootstrap/react-bootstrap#2384]
hi,

I'm building a site using React-Bootstrap (very nice so far!) and React Router v4, and because `<Breadcrumb.item>` doesn't support click handlers, it doesn't support `<Link>`, which is a bummer. Is this feature on the radar anywhere? For the time being, I've rolled my own (shortened version below), which seems to work okay for now. Including it here in case it's at all helpful:

render method of my `Breadcrumbs` component:

  render () {
    const { crumbs } = this.props;

```
    return (
      <div>
        <ol role='navigation' aria-label='breadcrumbs' className='breadcrumb'>
          { crumbs.map ( (item) => {
            const className = (item.active) ? 'active' : '';
            const content = (item.active) ? <span>{item.text}</span> : <BreadcrumbLink href={item.href} text={item.text} />;
            return (
              <li key={item.text} className={className}>{content}</li>
            )
          })}
        </ol>
    </div>
    )
  }
```

...and then `BreadcrumbLink`:

```
const BreadcrumbLink = (props) => {
  const { href, text} = props;
  return (
    <Link to={href}>
      {text}
    </Link>
  )
}
```

I realize this approach likely wouldn't work for react-bootstrap, but thought it might be useful here anyway.

**Comment by taion** [comment]
`<Breadcrumb.Item>` supports `onClick` just fine. By default all of our components pass through any props they receive to the underlying DOM node.

**Comment by bmueller-sykes** [comment]
Okay. I think that means the link code would have to look something like this:

```
export default class Breadcrumbs extends Component {

  handleClick = (evt) => {
    evt.preventDefault();
    const { router } = this.context;

    router.transitionTo(evt.target.href.substring(window.location.origin.length));
  }

  render () {
    return (
      <Breadcrumb>
          <Breadcrumb.Item href='/path/to/somewhere' onClick={this.handleClick}>Some Text</Breadcrumb.Item>
      </Breadcrumb>
    )
  }
}

Breadcrumbs.contextTypes = {
  router: React.PropTypes.object
}
```

**Comment by annie-l** [comment]
i also need to change breadcrumbs hrefs to links because of an integration with react. @bmueller-sykes is your implementation working fine for you? thanks for adding your code; i'll give it a try.

**Comment by bmueller-sykes** [comment]
@annie-l Yes, the code I have above works. Hope it works for you as well!

**Comment by annie-l** [comment]
thanks :)
