### ISSUE TITLE
MAINTAINING.md links producing 404

### ISSUE THREAD

**Issue by softweave** [react-bootstrap/react-bootstrap#2385]
The 'gitter/react-bootstrap' link (https://gitter.im/react-bootstrap/react-bootstrap) and the 'organization owners' link (https://github.com/orgs/react-bootstrap/teams/owners) both produce 404 errors.  Are they out of date or possible require special permissions to access?

**Comment by softweave** [comment]
Actually, dropping the glitter link does not fix this issue. The owners link also errors out. If one needs special permissions to view it, it would be helpful to have that noted in the md file.

**Comment by taion** [comment]
Ah, I see. Fixed in https://github.com/react-bootstrap/react-bootstrap/pull/2387 then

**Comment by taion** [comment]
thanks!
