### ISSUE TITLE
Incorrect position of overlay popover depending on target element height

### ISSUE THREAD

**Issue by jdpagley** [react-bootstrap/react-bootstrap#2390]
I previously mentioned this problem in https://github.com/react-bootstrap/react-bootstrap/issues/2389#issuecomment-266219459 but have recently discovered new information. 

Overlay popover will position itself the same amount of distance from the target as the height of the target element.

For instance:

**Short Target Element:**
<img width="559" alt="screen shot 2016-12-11 at 12 52 31 am" src="https://cloud.githubusercontent.com/assets/4016177/21078417/5c9266da-bf3c-11e6-8f4a-3d415bb9eed7.png">

**Larger Target Element:**
<img width="577" alt="screen shot 2016-12-11 at 12 53 10 am" src="https://cloud.githubusercontent.com/assets/4016177/21078421/6ef76c76-bf3c-11e6-93a3-1369f308c3c0.png">

```
    render() {
      
      let { id, title, onChange } = this.props;
      let { date } = this.state;
      
      return (
        <div>
          <FormGroup controlId="generic-month-year-picker" >
            <div 
              className="target-node"
              style={{position: 'relative'}}
              ref="target"
              onClick={(e) => {
                e.stopPropagation(); 
                this._displayPopover()
              }}
            >
              <p>Click Me</p>
              <p>Click Me</p>
              <p>Click Me</p>
              <p>Click Me</p>
              <p>Click Me</p>
              <p>Click Me</p>
            </div>
          </FormGroup>
          <Overlay 
            rootClose 
            placement="bottom" 
            show={this.state.displayPopover}
            onHide={this._hidePopover}
            target={() => {
              return ReactDOM.findDOMNode(this.refs.target);
            }}
            container={this.refs.target}
          >
            <Popover id="11223344">
              <span>Hello World</span>
            </Popover>
          </Overlay>
        </div>
      );

    }


```

**Comment by jquense** [comment]
you're doing something weird here, the target and container are the same element. the container is the DOM element the overlay is appended too (generally document body) and the target is the element the overlay is positioned relative too, e.g. the bottom of the target

**Comment by jdpagley** [comment]
@jquense I tried setting the overlay container to `document.body` as well as `this` and both caused the popover to display off the screen?

**Comment by jquense** [comment]
from the last issue it's the _container_, not the target that needs to be position relative. Overlays are absolutely positioned so the container needs to be the element that are positioned against, e. g. the position relative to the  overlays position absolute

**Comment by jdpagley** [comment]
@jquense any idea why the popover would display offscreen when I have the same code from the first comment but container is `document.body`?

**Comment by jquense** [comment]
there is probably another element between the target and body that is positioned relatively.
