### ISSUE TITLE
Fade/Collapse transitionAppear doesn't work as expected

### ISSUE THREAD

**Issue by thomaslee** [react-bootstrap/react-bootstrap#2391]
I wanted to fade in a `Panel` that was being added to a react-bootstrap UI dynamically. Had code something like this in my render method:

```
<Fade in transitionAppear>
  <Panel header={...} />
</Fade>
```

Noticed the Panel wasn't fading in. Even setting the Fade's `timeout={5000}`, the panel would appear immediately.

Eventually traced this quirk down to the fact that `enteringClassName` is set to `"in"`. in `src/Fade.js`. Hacking that to set `enteringClassName=""` improved the situation, but it was still quirky: I now saw a 5 second pause followed by a sudden transition to full opacity.

Quickly realized that the  `timeout` was basically just a delay introduced before signalling the end of the transition at which point the `enteredClassName` is added the panel element. At this point CSS takes over to handle the opacity transition. So as near as I can tell, the `timeout` is basically a glorified sleep before the real transition happens.

I achieved the effect I wanted by removing the timeout and overriding the CSS:

```
.panel.fade {
  opacity: 0;
  -webkit-transition: opacity 1s linear;
  transition: opacity 1s linear;
}
```

Unfortunately the `enteringClassName` hack is still necessary to achieve the desired effect. At this point I think I'm going to be better off replacing the Fade component with my own custom component to work around the issue.

IMO this is a bug -- or at least surprising behavior -- but I guess it's possible it's by design. If it's the latter I'd suggest a doc update to clarify. I'd strongly recommend changing these semantics somehow if you're not yet locked down by semver. Unfortunately integrating the behavior of the JS-driven transition events with the CSS-driven transitions is a bit of a thorny problem, I'm not sure there's a good answer.

Happy to provide a more concrete example of why the existing behavior is undesirable/quirky if it's not obvious from my description here.

**Comment by jquense** [comment]
sorry there is a lot here and I'm nit sure what the bug is. the timeout is a safe guard against transition events not getting ed fired by the browser even the the transition ended. The Fade component works fine in the various places we use it like Modals, and Overlays, so your particular use case is probably due to a conflict with css, in particular it may be conflicting with bootstrap's panel collapse css

**Comment by thomaslee** [comment]
You're right, I blathered a lot :smile:

Here's an easy reproduction: 

```
class MyComponent extends Compnent {
  // ... snip
  constructor(props) {
    super(props);
    this.state = {renderFade: false};
  }
  componentDidMount() {
    setTimeout(() => { this.setState({renderFade: true}); }, 5000);
  }
  render() {
    return {this.state.renderFade ? <Fade in transitionAppear><p>Pop!</p></Fade> : null};
  }
}
```

Note that the `Fade` is introduced dynamically after ~5s. For me "Pop!" appears instantly with no transition animation. Similarly, `<Fade timeout={N} ...` waits N milliseconds then "Pop!" appears instantly, with no visual transition wrt opacity.

Modals and Overlays work fine because they're typically not introduced dynamically (i.e. they're part of the rendered DOM and showing a modal involves making an existing DOM element visible. Where I think it breaks is introducing a _brand new_ DOM element dynamically. I suspect this is because no "transition" occurs from a CSS perspective -- the DOM element appears with the "in" CSS class already set.)

**Comment by jquense** [comment]
I'll take a look however, this:
> showing a modal involves making an existing DOM element visible

isn't actually true, the overlays and modal Dom components are added to the DOM dynamically when shown

**Comment by thomaslee** [comment]
Ah true. And I can confirm that a Modal works as expected on the same test page on which I'm seeing Fade misbehave. Weird.

**Comment by thomaslee** [comment]
Turns out dynamically adding components isn't necessary to reproduce this at all, here's an even simpler case:

```
import { Component, Fade } from 'react';

class MyComponent extends Component {
  render() {
    return <Fade in transitionAppear><p>Pop!</p></Fade>;
  }
}
```

No fade transition occurs. A few slight modifications will force the transition, but it's very hacky:

```
import { Component, Fade } from 'react';

class MyComponent extends Component {
  constructor(props) {
    super(props);
    this.state = {pop: false};
  }

  componentDidMount() {
    setTimeout(() => this.setState({pop: true}), 0);
  }

  render() {
    return <Fade in={this.state.pop} transitionAppear><p>Pop!</p></Fade>;
  }
}
```

**Comment by Truedrog** [comment]
https://github.com/react-bootstrap/react-overlays/issues/146#issuecomment-282036734
