### ISSUE TITLE
Setting disabled on NavItem disables title

### ISSUE THREAD

**Issue by Legogris** [react-bootstrap/react-bootstrap#2392]
Example (with react-router-bootstraps's `LinkContainer`):
``` 
<LinkContainer to="url" disabled title="herp">
  <NavItem>message</NavItem>
</LinkContainer>
```

This is because `pointer-events` is set to `none` in `SafeAnchor.js:69`. Can we skip this?

Alternatively, set it via a CSS class so we can override it in stylesheets if we feel the need to.

**Comment by taion** [comment]
@jquense Do you remember why you added that in https://github.com/react-bootstrap/react-bootstrap/pull/1794? I think maybe we just need to let the Bootstrap CSS handle this for us.

**Comment by jquense** [comment]
it's there to make the behavior closer to that of disabled buttons, which don't accept pointer events in that state. I'm surprised the title doesn't work tho they generally ignore such semantica
