### ISSUE TITLE
DropDown or SplitButton on Modal

### ISSUE THREAD

**Issue by jorgecuesta** [react-bootstrap/react-bootstrap#2393]
Hi guys,

Some way to prevent menu of dropdown and split button generate an overflow on Modal body? I think it should be rendered as [tooltips or popovers](http://react-bootstrap.github.io/components.html#modals-live).

Detail case: 
I have a Form inside body, last items of it is a dropdown, when open menu, body get scroll and look really bad, because should be like tooltips o popovers.

Some idea, tweak, or something about it?

I try to use Overlay and Overlay trigger on Dropdown.Menu but DropDown doesn't work because require bsRole='menu' as child

**Comment by jquense** [comment]
we can't control anything here since it's css related and we defer to the bootstrap css for everything. I'd just remove the overflow on `.modal-body` personally.

**Comment by jorgecuesta** [comment]
But remove overflow on modal body not solve problem. Because the problem is that dropdown/split menu are rendered as siblings. If menu is rendered as tooltips/popovers with overlays and align to button this should not happen.

**Comment by jquense** [comment]
I'm not sure why that wouldn't solve your problem, overflow is result of a parent element being a offset parent and having an `overflow: auto|scroll`. In any case dropdowns aren't overlays or tooltips, they have their own specific logic and implementation, we can't render them as such without differing significant;y from the bootstrap implementation. You can't have dropdowns inside a scrollable container and also have them overflow outside that container.

**Comment by jorgecuesta** [comment]
Attach two screen to explain better this point:

1) right
![seleccion_036](https://cloud.githubusercontent.com/assets/9866992/21113849/db68c05a-c089-11e6-99a4-230a6e5b35a1.png)
2) wrong
![seleccion_037](https://cloud.githubusercontent.com/assets/9866992/21113865/e938250e-c089-11e6-8c05-26f938f5e1bd.png)

DropDown.Menu items are absolute, but the problem is that are rendering at same level that button. When parent element of button have a fixed height with/without overflow does not show properly because are inside parent element of button.

DOM example of my suggestion: 
![seleccion_038](https://cloud.githubusercontent.com/assets/9866992/21114165/f0c2b504-c08a-11e6-8457-62bdc4290422.png)


The way to solve that is if menu are not inside parent element, can be at body (like tooltips/popovers) an aligned to button. This work is doit by Overlay and OverlayTrigger and also (I think) by Affix and AutoAffix.

Sorry about my English, and if you see something that I miss please let me know.

**Comment by jquense** [comment]
Right, I understand the problem and why its frustrating! Unfortunately, i'm saying is that we cannot fix it for you in the way you want. By design, the dropdown menus are positioned to their  parent `.dropdown` **not an arbitrary offset parent**. Upstream bootstrap has that behavior _so we are limited to that behavior as well_ and that means we can't just treat them like Overlays or Dropdowns.

Besides that point, the problem you are having is on your end, the default css and styles do not have this problem: https://jsfiddle.net/69z2wepo/64976/

![image](https://cloud.githubusercontent.com/assets/339286/21115925/54f780fe-c081-11e6-8adc-f7f4dd467ba9.png)

**Comment by jorgecuesta** [comment]
Thanks a lot @jquense you are in the right way.! I have a Loader component that put a div as position relative and my form inside it. When I remove Loader component menu works like a charm!

Really thanks! I will search a different loader solution to prevent definitively this things. You are my hero today! ;)
