### ISSUE TITLE
Carousel without slide animation works only on first click

### ISSUE THREAD

**Issue by fostash** [react-bootstrap/react-bootstrap#2396]
I set to false the slide property of Carousel component because I don't need animation but it works only on first click by hand

I found code which broke my goal on Carousel.js at row 215
``` 
if (this.state.previousActiveIndex != null) {
     // If currently animating don't activate the new index.
     // TODO: look into queueing this canceled call and
     // animating after the current animation has ended.
     return;
}
```
I remove this control and everything works fine, I also run test, all passed

You see any problems in this change?

Thanks

**Comment by taion** [comment]
Thanks, but that's not quite the right change. We should instead just set `previousActiveIndex` to `null` when `slide` is `false`.

**Comment by isaachinman** [comment]
@taion Any update on this? Just came across it myself.

**Comment by nickgerig** [comment]
If you don't want to modify the source, one workaround is to adopt a controlled component approach. (see [docs](https://react-bootstrap.github.io/components.html#carousels))

**Comment by isaachinman** [comment]
@nickgerig Sure, but fixing this very simple and could be done, merged, and deployed in a day. Not sure what's up with it. I'd be happy to PR if needed.

**Comment by jquense** [comment]
we're always happy to get PR's fixing bugs!

**Comment by isaachinman** [comment]
@jquense Sure, I'll get that done then. Last release I can see was in Nov, is that right? How often do you guys release?

**Comment by jquense** [comment]
when there is stuff to release. Its slowed down now because most stuff is fairly stable. but we push bug fixes and patches promptly

**Comment by isaachinman** [comment]
Okay, I will get this in immediately. Cheers.

**Comment by isaachinman** [comment]
So @nickgerig @jquense it's #2466. One liner. Hopefully can get merged and released soon, I (like a lot of people, I imagine) use `react-bootstrap` in a production app. Cheers!

**Comment by fostash** [comment]
@isaachinman thanks for the fix! 
@jquense @taion you know when will be released on npm? tnks

**Comment by taion** [comment]
After we merge https://github.com/react-bootstrap/react-bootstrap/pull/2422

**Comment by isaachinman** [comment]
@taion Any estimate? Looks like there hasn't been activity on #2422 in about a week.
