### ISSUE TITLE
dropdown button: How to set selected value on select MenuItem

### ISSUE THREAD

**Issue by jaybe78** [react-bootstrap/react-bootstrap#2397]
Hello,

The DropdownButton widget does not set the newly selected item chosen within the dropdown.
Is there an an easy way to achieve that ?  
![image](https://cloud.githubusercontent.com/assets/3605098/21188565/b9f2f900-c213-11e6-8790-aaf11bb50d66.png)

Cheers

**Comment by jquense** [comment]
The dropdown button isn't a `<select>` replacement, its a menu. You can implement it yourself if that's the behavior you want, otherwise i'd just use a `<select>`

**Comment by jaybe78** [comment]
Yes I would still kike to use the dropdown button.
How would you implement the replacement ? I've seen some examples where they changed the selected item with JQuery but it's quite "dirty". Is there a more elegant way to do that ?

**Comment by jquense** [comment]
change the `title` of DropdownButton to the value you want, no need for jquery.

**Comment by jaybe78** [comment]
ok cheers.
Also just quick question regarding react-bootstrap, I have jsut start using the widget, I woud like to know whether there are stable enough to be used in production environement ? I can see there's 500 tickets open

**Comment by jquense** [comment]
500 tickets? Where are you getting that number, there are 34 tickets open

**Comment by jaybe78** [comment]
lol I'm tired... was looking at redux-form project which has 500 open tickets. Since I've started to dive into html 5 world, I find myself a bit lost and confused with all those libraries....
