### ISSUE TITLE
Collapse animation not showing when collapsing table rows

### ISSUE THREAD

**Issue by DandyDev** [react-bootstrap/react-bootstrap#2398]
Hi there!

First of all, thanks for the wonderful library! Makes life very easy :)

I'm encountering a problem with `<Collapse>`. I'm trying to collapse/un-collapse a table row, by clicking on the previous table row (for showing details). The showing/hiding works fine, but it's not animated. I created a fiddle to show what I mean: http://jsfiddle.net/z0a32q61/

Can somebody tell me what I'm missing/doing wrong?

Thanks!

**Comment by taion** [comment]
This is https://github.com/react-bootstrap/react-bootstrap/pull/1463

**Comment by DandyDev** [comment]
I read that, and when I give the `<tr>` to be collapsed zero margin and padding, it still doesn't work. Only when I wrap the `<tr>` in a `<div>` does it work, but that's not valid HTML as far as I know.

**Comment by avidrucker** [comment]
@DandyDev Any luck solving this last year? I'm working on a similar issue, animating a collapsible panel opening and closing. I can get it to open and close, but not animate the transition.

**Comment by kick-the-bucket** [comment]
Almost 2 years later this is still a problem with `<tr>`s...

**Comment by i-am-sanju** [comment]
I am facing the same. Could someone help me to fix this?

**Comment by aktan-amanaliev** [comment]
I am not sure if we this solution will work for you, but when my closing animation for a div wasn't working, after checking that I added necessary <link> and <script> tags, I just changed the order of <link> tags, with mine on top, and after that it worked for me. Please reply if it works for you.

**Comment by LucaDallavalleMazzocchi** [comment]
Year: 2019. 
Still no solution.

**Comment by zfisch** [comment]
2020 ...
Also stuck here

**Comment by hieu-htv** [comment]
Year: 2021.
Still no solution.

**Comment by ArturoDucasse** [comment]
Year: 2022
Still no solution

**Comment by wefscto** [comment]
Year: 2023.
Still no solution.

**Comment by rumplin** [comment]
Still no solution

**Comment by tylerjc** [comment]
It's not exactly a fix or what we all want... but if you set the `timeout` prop to something very small it makes it look smoother/more responsive/not as glitchy when collapsing.

- [Fiddle example.](https://jsfiddle.net/xops5cm1/)


```
<Collapse in={open} timeout={1}>
  <tr><td>some data</td></tr>
</Collapse>
```
