### ISSUE TITLE
I can use menu collapse like this, but it's no collapse for NavItem

### ISSUE THREAD

**Issue by sopheakreth** [react-bootstrap/react-bootstrap#2399]
![image](https://cloud.githubusercontent.com/assets/19568260/21211268/c6bc7d04-c2b4-11e6-8fad-3575a20529ae.png)

             <div className="slid-menu">
                <Nav bsStyle="pills" stacked>
                    <NavItem eventKey={1} href="/admin">Dashboard</NavItem>
                    <NavItem eventKey={2} title="Item">User Management
                        <Nav bsStyle="pills" stacked>
                            <NavItem eventKey={3} href="#">Item1</NavItem>
                            <NavItem eventKey={4} href="#">Item2</NavItem>
                        </Nav>
                    </NavItem>
                </Nav>
            </div>

**Comment by taion** [comment]
See https://github.com/react-bootstrap/react-bootstrap/pull/1463
