### ISSUE TITLE
ButtonGroup block property

### ISSUE THREAD

**Issue by mathieumg** [react-bootstrap/react-bootstrap#240]
Would you be open to have a PR that adds the `block` property on `ButtonGroup`, to allow all of the `Button`s in the vertical group to take full width. (See http://jsfiddle.net/jpns7Ltu/)

It can already be done manually by setting `className="btn-block"` on the `ButtonGroup`, but this would be more in line with the rest of the API.

Thank you.

**Comment by taion** [comment]
Are you still planning on submitting such a PR?

**Comment by mathieumg** [comment]
I'll try to look into it this week, I've been extremely busy in the past months but this shouldn't take too long. If you wanted to tackle this, go ahead, but I can give it a shot of my own otherwise.

**Comment by camerow** [comment]
Should this work in instances like: 
```<ButtonToolbar>
              <ButtonGroup block>
                <Button bsStyle="primary" bsSize="medium">Enter</Button>
                <Button bsSize="medium">Cancel</Button>
              </ButtonGroup>
            </ButtonToolbar>```

**Comment by taion** [comment]
You want `justified`, not `block` there.
