### ISSUE TITLE
Passing value={undefined} to FormControl/Inputs shows previous value and changes to uncontrolled

### ISSUE THREAD

**Issue by nicholasgonzalezsc** [react-bootstrap/react-bootstrap#2401]
When `value={undefined}` is passed to an input, the previous value is still shown if there was one being displayed. For example, if I view one item with field "name" = "hello" and then open a new item without field "name", the input will keep showing "hello," even if though the value passed is undefined.

To fix this requires having default values throughout the code, through ternary statements, the data model, or a wrapper around the input. The problem with this is that then you have to maintain all of these extra default values and eventually remove these values/fields from items that would otherwise not have the default value fields saved on them.

![reactbootstrapundefined](https://cloud.githubusercontent.com/assets/22032573/21275833/6db63dba-c383-11e6-9c7e-e4111bf39858.gif)

https://github.com/nicholasgonzalezsc/react-bootstrap-controlled-to-uncontrolled-bug

**Comment by taion** [comment]
this isn't a react-bootstrap bug. this is how react works.

**Comment by taion** [comment]
use `null`

**Comment by nicholasgonzalezsc** [comment]
@taion `null` also doesn't work.
In fact, passing new writes a warning to the console...

![reactbootstrapnull](https://cloud.githubusercontent.com/assets/22032573/21276678/66039406-c387-11e6-98a8-a04814a06793.gif)

**Comment by jquense** [comment]
use an empty string as the error suggests.`null` used to the be the right answer tho :P
