### ISSUE TITLE
Modal's behavior abnormally in ios.

### ISSUE THREAD

**Issue by shikelong** [react-bootstrap/react-bootstrap#2404]
## Env
   + ios 10 +
   + react-bootstap 0.30.7

My Modal's height is beyond the height of screen. So I need scroll the modal. But In safari Mobile.  I can only scroll the modal-backdrop. But the Modal is fixed with the browser window.   In android's chrome, It's ok. But In ios's safari. I can't scroll the modal.

Regards.

**Comment by victsant** [comment]
Did you ever figure out out to fix this issue ?

**Comment by smandavia** [comment]
I have also encountered this issue. Has anyone found a fix for this?

**Comment by bomb-on** [comment]
Bump?
