### ISSUE TITLE
Ability to change bsClass for Component's children

### ISSUE THREAD

**Issue by smashercosmo** [react-bootstrap/react-bootstrap#2407]
Several react-bootstrap components render other react-bootstrap components, for example Dropdown renders ButtonGroup. If I set Dropdown's bsClass propery, then ButtonGroup's bsClass won't be affected in any way and it will still have .btn-group class. Is there any way to achieve that? Can we pass bsStyle prop down to children?

**Comment by taion** [comment]
Use `componentClass` if you want to override that.

**Comment by smashercosmo** [comment]
@taion it's not always possible. For example with Dropdown.Toggle, which renders Button component and you can't override it. Well, the general need is to be able to completely reset all styles for particular components and bsClass approach is ok, except for child components.

**Comment by taion** [comment]
You can use a custom toggle component in that case. We could also just add `componentClass` there.
