### ISSUE TITLE
Cannot run docs website locally

### ISSUE THREAD

**Issue by ginotria** [react-bootstrap/react-bootstrap#2408]
I'm getting this error when trying to do `npm run docs` in `master` branch

[docs-server]  [nodemon] 1.11.0
[docs-server]  [nodemon] to restart at any time, enter `rs`
[docs-server]  [nodemon] watching: /react-bootstrap/docs/**/* /react-bootstrap/src/**/*
[docs-server]  [nodemon] starting `babel-node docs/server.js`
[docs-server]  /react-bootstrap/node_modules/babel-standalone/babel.js:26922
[docs-server]   exports.storage = 'undefined' != typeof window.chrome && 'undefined' != typeof window.chrome.storage ? window.chrome.storage.local : localstorage();
[docs-server]                                           ^
[docs-server]
[docs-server]  ReferenceError: window is not defined
[docs-server]      at Object.<anonymous> (/react-bootstrap/node_modules/babel-standalone/babel.js:26922:42)
[docs-server]      at Object.ES5Regex.NonAsciiIdentifierStart (/react-bootstrap/node_modules/babel-standalone/babel.js:27074:31)
[docs-server]      at __webpack_require__ (/react-bootstrap/node_modules/babel-standalone/babel.js:30:30)
[docs-server]      at Object.<anonymous> (/react-bootstrap/node_modules/babel-standalone/babel.js:3553:16)
[docs-server]      at __webpack_require__ (/react-bootstrap/node_modules/babel-standalone/babel.js:30:30)
[docs-server]      at Object.<anonymous> (/react-bootstrap/node_modules/babel-standalone/babel.js:1464:14)
[docs-server]      at __webpack_require__ (/react-bootstrap/node_modules/babel-standalone/babel.js:30:30)
[docs-server]      at Object.module.exports.version (/react-bootstrap/node_modules/babel-standalone/babel.js:1288:23)
[docs-server]      at __webpack_require__ (/react-bootstrap/node_modules/babel-standalone/babel.js:30:30)
[docs-server]      at Object.exports.__esModule (/react-bootstrap/node_modules/babel-standalone/babel.js:35902:23)
[docs-server]  [nodemon] app crashed - waiting for file changes before starting...

What am I missing?

My npm and node versions..
± npm -v
3.10.9
± node -v
v6.9.2

**Comment by taion** [comment]
File an issue with babel-standalone to cut a new release. It's an issue with `debug` that was fixed in v2.5.1.

**Comment by taion** [comment]
https://github.com/babel/babel-standalone/issues/73
