### ISSUE TITLE
NavBar with react-router Link

### ISSUE THREAD

**Issue by oyaaraas** [react-bootstrap/react-bootstrap#2409]
I am using the `<Link>` element from react-router with the NavBar.
Placing the `<Link>` inside a `<NavItem>` does not make sense, as this warning suggests:

>Warning: validateDOMNesting(...):` <a> `cannot appear as a descendant of `<a>`.

So I am replacing the `<NavItem>` with an `<ul>` tag instead, like so:
```
import React from 'react';
import {Navbar, Nav, NavItem} from 'react-bootstrap';
import {Link} from 'react-router';

class Navigation extends React.Component {
  render() {
    return (
      <Navbar inverse collapseOnSelect>
        <Navbar.Header>
          <Navbar.Brand>
            <Link to="/">Home</Link>
          </Navbar.Brand>
          <Navbar.Toggle />
        </Navbar.Header>
        <Navbar.Collapse>
          <Nav>
            <div>
              <ul>
                <Link to="/about">About</Link>
              </ul>
              <ul>
                <Link to="/contact">Contact</Link>
              </ul>
            </div>
          </Nav>
        </Navbar.Collapse>
      </Navbar>
    );
  }
}
export default Navigation;

```
Which produces the following warning:
> Warning: Unknown props `active`, `activeKey`, `activeHref` on \<ul\> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop

I guess it is related to #1994, but I cannot see that either of those props are passed down to the `<ul>` tag. Maybe I am doing something wrong here or this usecase is not supported?

**Comment by taion** [comment]
see react router bootstrap
