### ISSUE TITLE
onHide and onHidden props for Popover component

### ISSUE THREAD

**Issue by farskid** [react-bootstrap/react-bootstrap#2410]
As seen in bootstrap official documentation http://getbootstrap.com/javascript/#popovers there are events such as `hidden.bs.popover`, `hide.bs.popover` that being triggered when popover element is detached from document and popover starts to fade out.
I did not see any support for `onHide` and `onHidden` props on **Popover** element.
Would be nice to be implemented.

**Comment by taion** [comment]
The popover itself doesn't. Those go on the overlay or overlay trigger. The popover is just the popover itself.
