### ISSUE TITLE
Button bsClass is appending -default 

### ISSUE THREAD

**Issue by pjnovas** [react-bootstrap/react-bootstrap#2415]
Hey, so I'm adding a new type of button "secondary" which means to use a `btn btn-secondary` classes.

Since I'm extending `bootstrap-sass` adding an style is pretty straight forward: 
```sass
.btn-secondary {
  @include button-variant($btn-secondary-color, $btn-secondary-bg, $btn-secondary-border);
}
```

The problem is when I set the `bsClass` it's still appending `-default` class plus another `btn` class

Here is my JSX
```jsx
<Button bsClass="btn btn-secondary">Something</Button>
```

And then the output is:
```html
<button type="button" class="btn btn-secondary btn btn-secondary-default">Something</button>
```

It's not breaking the style but it looks wrong. 

IMO the validation of bsStyle for only the ones implemented could be much better to allow other types, because for my case here I could do:
```jsx
<Button bsStyle="secondary">Something</Button>
```
And everything would work as expected. (it does but it also throws the React Error of PropTypes)

The main point is the case where you want to extend bootstrap style you are in the middle:
* bsClass is for using a non bootstrap style
* bsStyle is only for bootstrap styles
* bsXXX extend bootstrap style (or allow new stlyes in bsStyle)

Thanks for this lib and the effort you'r putting in!

**Comment by jquense** [comment]
> IMO the validation of bsStyle for only the ones implemented could be much better to allow other types, because for my case here I could do:

you CAN do that:  https://react-bootstrap.github.io/components.html#custom-styles you missed the section in the docs about it :)

**Comment by pjnovas** [comment]
@jquense oh man!! I'm so happy now .. thanks!
