### ISSUE TITLE
Button's bsSize="xsmall" has no effect

### ISSUE THREAD

**Issue by fultonm** [react-bootstrap/react-bootstrap#2416]
Creating a `<Button />` with attribute `bsSize="xsmall"` or `bsSize="xs"` has no effect on the size of the button and a normally sized button appears. Other sizes like `"small"` work as described in the documentation.

**Comment by taion** [comment]
This works fine with the stock Bootstrap CSS: https://react-bootstrap.github.io/components.html#buttons-sizes. Make sure you have appropriate CSS.

**Comment by fultonm** [comment]
Well, you're not saying I'm lying are you? I'm using the latest bootstrap CSS file.

**Comment by jquense** [comment]
we're saying that its something off with your css, either an old version or a conflict. you can see in the doc link that it works (and i can verify it also works where we are using RB)
