### ISSUE TITLE
Site Documentation: maintain an index of documentation for older package versions.

### ISSUE THREAD

**Issue by iamgollum** [react-bootstrap/react-bootstrap#2417]
i just joined a company whose version of react-bootstrap is 0.26.2. There is no way of going back in time on the current react-bootstrap site to see what was supported at that time in addition to seeing how components were used then. This is a major problem / best practice violation.

If there is anyway I can get access to react-bootstrap documentation for the above version, that would be greatly appreciated!

**Comment by jquense** [comment]
Hi there. The docs are in git, you can view the code for your version by tag. and/or clone and run them.

**Comment by iamgollum** [comment]
Would you mind elaborating on how to do the above? Thanks. I tried building the docs locally for my version but could not get it to work.

**Comment by tcchau** [comment]
Just to help those who are in the same situation, as the steps are not necessarily obvious and definitely not documented:

```
git clone git@github.com:react-bootstrap/react-bootstrap.git react-bootstrap
cd react-bootstrap
git checkout tags/v0.32.1-docs.0
yarn install
yarn run bootstrap-docs
cd www
gatsby develop
```

**Comment by jeffbonasso-ambifi** [comment]
> Hi there. The docs are in git, you can view the code for your version by tag. and/or clone and run them.

We have used react-bootstrap for many years, and it's been a great set of components for our React app. I understand the need to move forward to Bootstrap 4 and the new library, but the new library is still in Beta and many still have code bases they have to maintain using react-bootstrap based on version 3. For many it is a huge undertaking to migrate all their code to the new library. It seems like posting the last (and currently only) stable release prior to the v1.0.0 release would help the community.

**Comment by jquense** [comment]
@jeffbonasso-ambifi the 0.32.0 docs are hosted and linked in the readme

**Comment by jeffbonasso-ambifi** [comment]
Thanks, that's great! I do see it now. This thread takes people down the path that you need to build the documentation yourself. Thanks for clarifying!

**Comment by jquense** [comment]
tbf this thread is 3 years old :P

**Comment by jeffbonasso-ambifi** [comment]
tbf someone added instructions 7 days ago which seemed like hadn't been resolved, but yes this post really is more about building previous versions of doc compared to where to find old doc. Thanks for your help.

**Comment by ddelrio1986** [comment]
I was able to successfully build the docs for the v0.32.1-docs.0 tag on node v11.10.1 with npm v6.7.0 on macOS v10.14.3 today using the following commands:

`
git clone git@github.com:react-bootstrap/react-bootstrap.git react-bootstrap
cd react-bootstrap
git checkout tags/v0.32.1-docs.0
yarn install
yarn run bootstrap-docs
cd www
npx gatsby develop
`

**Comment by LucasAmos** [comment]
> I was able to successfully build the docs for the v0.32.1-docs.0 tag on node v11.10.1 with npm v6.7.0 on macOS v10.14.3 today using the following commands:
> 
> ```shell
> git clone git@github.com:react-bootstrap/react-bootstrap.git react-bootstrap
> cd react-bootstrap
> git checkout tags/v0.32.1-docs.0
> yarn install
> yarn run bootstrap-docs
> cd www
> npx gatsby develop
> ```

Thanks for explaining how this can be done. This is an unbelievably poor solution. It took me about 20 mins to build these docs and then it takes up over a gigabyte of disk space, just so I can read what should be a bunch of HTML documents. I really don't understand why you don't have docs for different releases available via a simple dropdown on the react-boostrap website, like on the docs site for the original bootstrap.

**Comment by LucasAmos** [comment]
> > Hi there. The docs are in git, you can view the code for your version by tag. and/or clone and run them.
> 
> We have used react-bootstrap for many years, and it's been a great set of components for our React app. I understand the need to move forward to Bootstrap 4 and the new library, but the new library is still in Beta and many still have code bases they have to maintain using react-bootstrap based on version 3. For many it is a huge undertaking to migrate all their code to the new library. It seems like posting the last (and currently only) stable release prior to the v1.0.0 release would help the community.

Thanks for explaining how this can be done. This is an unbelievably poor solution. It took me about 20 mins to build these docs and then it takes up over a gigabyte of disk space, just so I can read what should be a bunch of HTML documents. I really don't understand why you don't have docs for different releases available via a simple dropdown on the react-boostrap website, like on the docs site for the original bootstrap.

**Comment by LucasAmos** [comment]
> Just to help those who are in the same situation, as the steps are not necessarily obvious and definitely not documented:
> 
> ```
> git clone git@github.com:react-bootstrap/react-bootstrap.git react-bootstrap
> cd react-bootstrap
> git checkout tags/v0.32.1-docs.0
> yarn install
> yarn run bootstrap-docs
> cd www
> gatsby develop
> ```

Thanks for explaining how this can be done. This is an unbelievably poor solution. It took me about 20 mins to build these docs and then it takes up over a gigabyte of disk space, just so I can read what should be a bunch of HTML documents. I really don't understand why you don't have docs for different releases available via a simple dropdown on the react-boostrap website, like on the docs site for the original bootstrap.

**Comment by jquense** [comment]
> I really don't understand why you don't have docs

feel free to contribute that. 

> This is an unbelievably poor solution.

Not sure why you didn't click the link in the readme then as noted by this comment 10 days agao: https://github.com/react-bootstrap/react-bootstrap/issues/2417#issuecomment-465137719

**Comment by LucasAmos** [comment]
> I was able to successfully build the docs for the v0.32.1-docs.0 tag on node v11.10.1 with npm v6.7.0 on macOS v10.14.3 today using the following commands:
> 
> ```shell
> git clone git@github.com:react-bootstrap/react-bootstrap.git react-bootstrap
> cd react-bootstrap
> git checkout tags/v0.32.1-docs.0
> yarn install
> yarn run bootstrap-docs
> cd www
> npx gatsby develop
> ```

Thanks for explaining how this can be done. This is an unbelievably poor solution. It took me about 20 mins to build these docs and then it takes up over a gigabyte of disk space, just so I can read what should be a bunch of HTML documents. Considering the number of people who will be maintaining software built using the previous versions I really don't understand why you don't have docs for different releases available via a simple dropdown on the react-boostrap website, like on the docs site for the original bootstrap.

**Comment by jquense** [comment]
> I really don't understand why you don't have docs

feel free to contribute that.

> This is an unbelievably poor solution.

Not sure why you didn't click the link in the readme then as noted by this comment 10 days agao: [#2417 (comment)](https://github.com/react-bootstrap/react-bootstrap/issues/2417#issuecomment-465137719)

**Comment by jquense** [comment]
for those who stumble on this: https://5c507d49471426000887a6a7--react-bootstrap.netlify.com/
