### ISSUE TITLE
How to get the value of a FormControl input. 

### ISSUE THREAD

**Issue by josiahsprague** [react-bootstrap/react-bootstrap#2418]
I'm posting this here since I had a really hard time finding the answer and it may be useful to someone else. This is a followup to https://github.com/react-bootstrap/react-bootstrap/issues/1850#issuecomment-270026825 which was locked before the solution was posted.

If you want to get the value of an input element from a FormControl [without using `findDOMNode`, since that will eventually be deprecated](https://github.com/yannickcr/eslint-plugin-react/issues/678#issue-165177220), you can use [the `inputRef` prop](https://react-bootstrap.github.io/components.html#forms-props-form-control).

Something like this example should work;
```
class MyComponent extends Component {
  componentDidMount() {
    this.inputNode.value;
  }

  render() {
    return (
      <div>
        <FormControl inputRef={node => this.inputNode = node} type="text" />
      </div>
    )
  }
}
```

**Comment by yeti-detective** [comment]
I literally have been searching for this for a full day. Thank you

**Comment by perry0105** [comment]
Thanks, really helps!

**Comment by jjwallace** [comment]
this doesnt work for me :(

**Comment by mikeitexpert** [comment]
I get this warning when I tried. 

index.js:2178 Warning: React does not recognize the `refInput` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `refinput` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    in input (created by FormControl)
    in FormControl (at Params.js:32)
    in div (created by FormGroup)
    in FormGroup (at Params.js:30)
    in form (created by Form)
    in Form (at Params.js:29)

and I am using the below stack of dependencies:

"bootstrap": "^3.3.7",
    "isomorphic-fetch": "^2.2.1",
    "jquery": "^3.3.1",
    "plotly.js": "^1.38.2",
    "popper": "^1.0.1",
    "react": "^16.4.0",
    "react-bootstrap": "^0.32.1",
    "react-dom": "^16.4.0",
    "react-plotly.js": "^2.2.0",
    "react-redux": "^5.0.7",
    "react-scripts": "1.1.4",
    "redux": "^4.0.0",
    "redux-thunk": "^2.3.0"

**Comment by mikeitexpert** [comment]
The below worked for me. 

                  <FormControl id="iterval" type="text" placeholder="Interval"
                    onChange={e => _interval = e.target.value}
                    defaultValue={interval}
                    />

**Comment by AhmetGurbuzz** [comment]
the way i see it, It can be easily get that value with controlID like:

```
<Form.Group controlId="form-name" style={{ marginRight:'10px' }}>
  <Form.Label>Name</Form.Label>
  <Form.Control type="text" placeholder="Enter name"  />
</Form.Group>

console.log(document.getElementByID("form-name").value);
```

Is there any disadvantage of using ID??

**Comment by nitan84** [comment]
Form Control has a `ref` [prop](https://react-bootstrap.github.io/components/forms/#form-control-props), which allows us to use [React Refs](https://reactjs.org/docs/refs-and-the-dom.html)
Sample Code :
```
class MyComponent extends React.Component {
  constructor() {
     /* 1. Initialize Ref */
     this.textInput = React.createRef(); 
  }

  handleChange() {
     /* 3. Get Ref Value here (or anywhere in the code!) */
     const value = this.textInput.current.value
  }

  render() {
    /* 2. Attach Ref to FormControl component */
    return (
      <div>
        <FormControl ref={this.textInput} type="text" onChange={() => this.handleChange()} />
      </div>
    )
  }
}
```

Hope this helps!

**Comment by AhmetGurbuzz** [comment]
@nitan84 Hi, thank you so much...

**Comment by maketroli** [comment]
Yes, @AhmetGurbuzz answer works properly.

**Comment by maketroli** [comment]
I opened a new issue here -> https://github.com/react-bootstrap/react-bootstrap/issues/3579 since this post is from 2017 and we don't get yet a proper answer on how to get the value of an input properly.

**Comment by yakupad** [comment]
Hello this solution worked for me!

    <Form
      noValidate
      validated={validated}
      onSubmit={(e) => this.handleSubmit(e)}
      style={{ width: '100%' }}
    >
      <Form.Group controlId="formBasicEmail">
       <Form.Label>Email address</Form.Label>
       <Form.Control type="email" placeholder="Enter email" inputRef={(ref) => { this.email = ref }} required />
       <Form.Text className="text-muted"> Well never share your email with anyone else.
       </Form.Text>
      </Form.Group>
    </Form>

    handleSubmit(event) {
        console.log(event.target.elements.formBasicPassword.value)
    }

**Comment by jaime-varela** [comment]
I find it ridiculous that it's not in their docs.

**Comment by jaime-varela** [comment]
Posted solution(s) didn't work for me in react so I defaulted to using ID's and "document.getElementById".  Not ideal but works well enough.

**Comment by Maikpwwq** [comment]
Encontre tres formas para abstraer valores de los inputs en un formulario de React Bootstrap:
// Teniendo en cuenta; Deprecated usage getDOMNode() and findDOMNode()
`
import * as React from 'react'
import Form from 'react-bootstrap/Form'

// 1. controlId & getElementById
const Componente1 = (props) => {
    let clave = document.getElementById('formSignupPassword').value
    console.log(clave)
    return (
        <>
            <Form>
                <Form.Group className="mb-2" controlId="formSignupPassword">
                    <Form.Label className="mb-0">Contraseña</Form.Label>
                    <Form.Control
                        type="password"
                        placeholder="Registre una clave"
                    />
                </Form.Group>
            </Form>
        </>
    )
}

// 2. ref & React.createRef
const Componente2 = (props) => {
    let passwordText = React.createRef()
    let clave = passwordText.current.value
    console.log(clave)
    return (
        <>
            <Form>
                <Form.Group className="mb-2" controlId="formSignupPassword">
                    <Form.Label className="mb-0">Contraseña</Form.Label>
                    <Form.Control
                        type="password"
                        placeholder="Registre una clave"
                        inputRef={passwordText}
                        // or Use
                        ref={passwordText}
                    />
                </Form.Group>
            </Form>
        </>
    )
}

// 3 onChange={(e) =>} & Hooks React.useState
const Componente3 = (props) => {
    const [userEmail, setEmail] = React.useState(null)
    console.log(userEmail)
    return (
        <>
            <Form>
                <Form.Group className="mb-2" controlId="formSignupEmail">
                    <Form.Label className="mb-0">Email</Form.Label>
                    <Form.Control
                        type="email"
                        placeholder="Registre una cuenta de email valida"
                        onChange={(e) => setEmail(e.target.value)}
                    />
                </Form.Group>
            </Form>
        </>
    )
}
`
