### ISSUE TITLE
Use different input size

### ISSUE THREAD

**Issue by mathieumg** [react-bootstrap/react-bootstrap#242]
How do I go about using a different `Input` size? According to the Bootstrap documentation I should only have to add the `input-sm` class to the `className` property of my `Input`. However, when looking at https://github.com/react-bootstrap/react-bootstrap/blob/master/src/Input.jsx#L85 I think it is overwritten.

Thank you!

**Comment by andrest** [comment]
+1

**Comment by jbraithwaite** [comment]
In `input.js` for `renderInput`:

```js
default:
        var className = this.isCheckboxOrRadio() || this.isFile() ? "" : "form-control";
        input = React.createElement("input", _extends({}, this.props, { className: classSet(this.props.className, className, {'input-lg': this.props.bsSize == 'large', 'input-sm': this.props.bsSize == 'small'}), ref: "input", key: "input" }));
```

![screen shot 2015-04-15 at 2 02 11 pm](https://cloud.githubusercontent.com/assets/1044105/7169192/21b300fc-e378-11e4-9b8b-b4845a974216.png)

```jsx
<Input type='text' label='Input Large' bsSize="large" placeholder='Large' />
<Input type='text' label='Input Normal' placeholder='Normal' />
<Input type='text' label='Input Small' bsSize="small" placeholder='Small' />
```

**Comment by AlexKVal** [comment]
I works now through `bsSize = 'large | medium | small'`
http://react-bootstrap.github.io/components.html#input-sizes

**Comment by lynnard** [comment]
I'm not sure why the api keeps changing - now we've got `FormControl` and again I can't know how I can change the size. At the end of the day I found piecing together divs and adding classNames to be easier!
