### ISSUE TITLE
Installation command on getting started page

### ISSUE THREAD

**Issue by gitanupam** [react-bootstrap/react-bootstrap#2424]
On the page, https://react-bootstrap.github.io/getting-started.html, it seems that the npm example only installs react-bootstrap whereas the bower example installs both react and react-bootstrap. 

How about having the following?
npm install react react-dom react-bootstrap --save

(and the same for bower)

I am new to React and had to clarify this on [SO](http://stackoverflow.com/questions/41299783/do-i-need-to-install-react-before-i-install-react-bootstrap).

**Comment by taion** [comment]
dupe https://github.com/react-bootstrap/react-bootstrap/issues/2411

**Comment by gitanupam** [comment]
sorry
