### ISSUE TITLE
DropdownButton bsStyle="primary" does not display correctly.

### ISSUE THREAD

**Issue by martinduo** [react-bootstrap/react-bootstrap#2426]
DropdownButton bsStyle="primary" does not display correctly. Using bsStyle="info" produces the desired "primary" display.

**Comment by jquense** [comment]
any more info. it works fine on the docs site. you might have a css conflict

**Comment by martinduo** [comment]
Thanks, you must be right. I've had that problem for awhile when working in
other areas. Just now I went back to that part, saw the problem again and
posted it. Then I did a lot of clean up on the css, and now the problem is
gone. So I'll never know the cause.

**Comment by jquense** [comment]
👍  glad ya figured it out
