### ISSUE TITLE
When a MenuItem is wrapped, it won't close the DropdownButton when clicked

### ISSUE THREAD

**Issue by natevw** [react-bootstrap/react-bootstrap#2429]
With this sample code, clicking the second menu item leaves the list open:

```
import { DropdownButton, ButtonGroup, Button, MenuItem } from 'react-bootstrap'

let MyMenuItem = props => <MenuItem
  {...props}
  onSelect={(arg1,arg2) => console.log("wrapped MenuItem onSelect", arg1,arg2)}
/>

let Test = () => <div>
  <DropdownButton title="Test" id="test123"
    onSelect={(arg1,arg2) => console.log("DropdownButton onSelect", arg1,arg2)}>
      <MenuItem onSelect={(arg1,arg2) => console.log("MenuItem onSelect", arg1,arg2)}>Bare MenuItem</MenuItem>
      <MyMenuItem>Wrapped MenuItem</MyMenuItem>
    </DropdownButton>
</div>

render(<Test/>, document.querySelector('#test'))
```

The cause seems to be in https://github.com/react-bootstrap/react-bootstrap/blob/17fccf68b65cd58a80b9be84b87038548e50f622/src/DropdownMenu.js#L126 where the DropdownMenu attempts to chain its own onSelect to each child's — this works if the child is a MenuItem, but if it's not then the interloping MyMenuItem gets the chained handler, and when the click happens the MenuItem inside it still has its original handler.

Removing the `onSelect` property from the nested MenuItem also hides the issue, since the wrapper in this example then passes the chained version along via `{...props}`. If instead I'd simply wrapped it in a simpler fashion like:

    let MyMenuItem = ({name}) => <MenuItem onClick={someHandler}>{name}</MenuItem>

…then it would also break.

WORKAROUND: any wrapper for shared `MenuItem` logic needs to be aware of this internal implementation detail i.e. that the parent dropdown relies on a monkey-patched `onSelect` to close itself. It must either pass along `this.props.onSelect` verbatim, or if it wants to provide onSelect behavior itself it needs to be sure to call that.

**Comment by jquense** [comment]
seems like you figured out. however, it's not an implementation detail, the MenuItem is injected with props, if you don't pass them through to the real MenuItem then yeah it doesn't work. This is a common pattern and generally how the prop system works. I can understand how it might feel annoying but it actually enables really powerful composition, since your MenuItem can control its behavior.

**Comment by natevw** [comment]
@jquense This behavior was surprising to me, how was I to know that "the MenuItem is injected with props"? I handled all the properties my wrapper exposed to its (visible) uses, and I provided all the properties to the MenuItem that it was documented to need. I guess you could try document this "injecting", but it would be better to leave these internal details as, well, internal details by coordinating through [context](https://facebook.github.io/react/docs/context.html).

**Comment by jquense** [comment]
as I said they are not internal details they are the public API of the MenuItem. if you make you own and change the API by not doing anything with the onSelect then you're able too, that's the power of explicit prop passing vs context, which doesn't allow that, at least not neatly. it's a feature not a bug. This is a really common pattern in React components and part of what makes the system so flexible and compose level. That said, we are always Glad to take PR's documenting behavior more clearly!

**Comment by natevw** [comment]
The documentation right now [simply says](https://github.com/react-bootstrap/react-bootstrap/blob/d4c223d8bc3ac3606f5558d9927ac068df04af06/docs/src/sections/MenuItemSection.js#L25):

> onSelect: a callback that is called when the user clicks the item.

Again, my opinion is that the documentation should *remain* simple and the architecture should be fixed. But I will submit a docs PR in the interim.

**Comment by natevw** [comment]
For anyone else hitting this, I've outlined the two workarounds in more detail on that pull request: https://github.com/react-bootstrap/react-bootstrap/pull/2432

**Comment by con-cso** [comment]
I second the feeling this implementation is at least surprising. It also prevents people from using patterns like this:

```
<NavDropdown>
    <React.Fragment>
        {menuItems}
    </React.Fragment>
</NavDropdown>
```

This doesn't even work if menuItems contains vanilla MenuItems only.

Using fragments in Dropdowns is a very common pattern for me when dealing with dynamic menus.

The only workaround seems to explicitely pass onSelect to any Dropdown's direct children and make sure to pass it all the way down to your MenuItems. Fragments have to be encapsulated into custom components which in turn cannot just use children to render MenuItems, but rather construct them themselves:

```
// props will at some point contain onSelect injected by the parent dropdown
const FragementedMenuItems = (props) => (
    <React.Fragment>
         {/* translate props to menu items, making sure each one is passed props.onSelect /*}
    </React.Fragment>
);

FragementedMenuItems.propTypes = {
    ...menuItemPropTypes,
    onSelect: PropTypes.func
};

const MyDropdown = (menuItemProps) => (
    <NavDropdown>
        <FragementedMenuItems menuItemProps={...menuItemProps} />
    </NavDropdown>
);

MyDropdown .propTypes = {
    ...menuItemPropTypes
};
```
