### ISSUE TITLE
DropdownMenu with ModalTrigger'd MenuItem

### ISSUE THREAD

**Issue by rossj** [react-bootstrap/react-bootstrap#243]
I'm trying to have a DropdownMenu with a ModalTrigger as a child element, such that a modal will upon selecting the menu item. I have a structure like this:

````
<DropdownButton bsStyle="default" title="Menu" pullRight>
	<ModalTrigger modal={<LinkAccountModal />}>
		<MenuItem>Menu Item 1</MenuItem>
	</ModalTrigger>
</DropdownButton>
````

Things mostly work, except that the drop down menu stays opened even once the modal appears. I believe this is because the `onSelect` method that the DropdownMenu passes to its children (the ModalTrigger in this case) does not get forwarded onto the MenuItem.

Am I setting this up correctly? Does it make sense to make ModalTrigger explicitly forward `onSelect` for this case, or make it more generally forward all props?

**Comment by z-ax** [comment]
I'm doing like this: `<MenuItem eventKey='1' onSelect={ this.handleToggle }>`, where:
```jsx
handleToggle: function () {
        this.setState({
            isModalOpen: !this.state.isModalOpen
        });
    },

// ...

renderOverlay: function () {
        if (!this.state.isModalOpen) {
            return <span/>;
        }
// ...
}
```

**Comment by AlexKVal** [comment]
Superceded by #526
