### ISSUE TITLE
Ellipsis between consecutive page numbers in pagination component

### ISSUE THREAD

**Issue by janslow** [react-bootstrap/react-bootstrap#2431]
If `boundaryLinks=true` on the `Pagination` component, ellipsis are rendered between the boundary page link and the main page links, even when they are consecutive numbers.

## Expected Behaviour
![screen shot 2017-01-13 at 14 15 04](https://cloud.githubusercontent.com/assets/1253367/21932899/c7516fac-d99a-11e6-9985-6ad163f04b78.png)

_Note, I just directly modified the DOM, via Chrome DevTools to produce this screenshot._

## Actual Behaviour
From [sample page](https://react-bootstrap.github.io/components.html#pagination)
![screen shot 2017-01-13 at 14 11 04](https://cloud.githubusercontent.com/assets/1253367/21932778/2c624c8c-d99a-11e6-85ff-edeb49423125.png)

**Comment by taion** [comment]
Huh, I thought we fixed this in https://github.com/react-bootstrap/react-bootstrap/pull/2189. Did it break again?

**Comment by janslow** [comment]
I can reproduce it on the react bootstrap sample page (which I'm assuming is the latest version) and locally using `0.30.7`

**Comment by jquense** [comment]
https://github.com/react-bootstrap/react-bootstrap/commit/d76598ea27bdf02d4eb5dca30573410594de18ab#diff-a45cca9cd876d1065465eccb078616e7

**Comment by taion** [comment]
That logic is the same, no?
