### ISSUE TITLE
Custom container class for Navbar?

### ISSUE THREAD

**Issue by oldo** [react-bootstrap/react-bootstrap#2433]
Hi there,
I notice that the `Navbar` component insert the contents of the navbar into a `container` div and I was wondering if there is any way to override this and give a custom class?
I see that you can add a custom element with the attribute `componentClass` but if I add this then I lose all the `nav` styling. `componentClass="nav container-app"` throws an error.
Thanks for your great work!

**Comment by taion** [comment]
Your component can clone its child and inject an additional `className` to _its_ immediate child via `cloneElement`

**Comment by oldo** [comment]
Ok, thanks, I'll give that a go.

**Comment by BrennerSpear** [comment]
I'm having this same problem - I'm not sure what you mean. I'll need to clone Nav and inject into that?

**Comment by BrennerSpear** [comment]
This is my fix for now:

``` 
.navbar > .container {
  width: auto;
}
