### ISSUE TITLE
spacing between breadcrumbs doesn't match bootstrap

### ISSUE THREAD

**Issue by annie-l** [react-bootstrap/react-bootstrap#2434]
i can't figure out what the difference is in the code between https://react-bootstrap.github.io/components.html#breadcrumbs and https://getbootstrap.com/components/#breadcrumbs, but the react-bootstrap implementation is missing spacing before the first forward slash, e.g.

_bootstrap:_
![screen shot 2017-01-16 at 4 31 31 pm](https://cloud.githubusercontent.com/assets/530852/22003543/57a65e9e-dc09-11e6-96fe-a397e6535d55.png)

_react-bootstrap:_
![screen shot 2017-01-16 at 4 31 38 pm](https://cloud.githubusercontent.com/assets/530852/22003547/5bd304ae-dc09-11e6-9209-32ea388bc331.png)

i've overridden this locally by adding a space before the slash in the `li:before`:
```
.breadcrumb > li + li:before {
    content: "\00a0/\00a0";
}
```

_before override:_
![screen shot 2017-01-16 at 4 05 49 pm](https://cloud.githubusercontent.com/assets/530852/22003424/4a1e9fee-dc08-11e6-8143-85478fe6ce75.png)

_after override:_
![screen shot 2017-01-16 at 4 05 23 pm](https://cloud.githubusercontent.com/assets/530852/22003425/4a1f18fc-dc08-11e6-93e2-615f531c458b.png)

but from looking at the react-boostrap source code i see that css is being pulled straight from bootstrap. my project is using what looks like the current version of bootstrap:
```
"bootstrap": "^3.3.7",
"react-bootstrap": "^0.30.7",
```

so i'm just curious what would need to be updated in the source code to make this fix for everyone (i know it's not my above fix). i'm guessing it has to do with how a base component is made, but again i'm not seeing any computed differences with the output between bootstrap and react-bootstrap.

**Comment by jquense** [comment]
think there is just extra extra whitespace in the bootstrap markup. jsx is more aggressive about trimming it off lines than normal html

**Comment by annie-l** [comment]
do you think i should propose the change to bootstrap? or propose a change in react-bootstrap to clean it up?

**Comment by annie-l** [comment]
guessing we can just wait for bootstrap v4 which moves to padding instead of unicode spacing...

https://github.com/twbs/bootstrap/commit/b8c77aaf3b29b1b3d09b3d7bd6ad153d9c315365
