### ISSUE TITLE
Disabled Button triggers onClick after 2nd click

### ISSUE THREAD

**Issue by michaeltomasik** [react-bootstrap/react-bootstrap#2435]
HI I have problem with `<Button>` it look disabled (grey out).
If you click it for the 1st time it won't trigger, but after second it execute onClick.
Here is rendered html:
```
<button type="button" class="btn btn-success" disabled=""><span>Save</span></button>
```
And React code:
```
<Button
     disabled={props.disabledButtons.includes('save') && !props.submitting}
     onClick={props.onSave} bsStyle="success"
  >
```

**Comment by taion** [comment]
Doesn't reproduce for me in the trivial case with something like

```js
<Button disabled onClick={() => alert('foo')}>Default</Button>
```

on the component playground. Please provide a repro.
