### ISSUE TITLE
PanelGroup closes when input element is clicked

### ISSUE THREAD

**Issue by StevePotter** [react-bootstrap/react-bootstrap#244]
I have an Accordion, which in the code is just a PanelGroup.  Inside one of the panels is an input element.  When I click the element, the Accordion collapses.  I did some debugging and what happens is the input element has a select event that fires upon focus (or click, forever).  That event bubbles up to the PanelGroup, which causes the handleSelect to fire.  The key passed to handleSelect is a SyntheticEvent whose target is the input element.

I was going to submit a patch but I don't know what the right fix is.  Currently I fixed it by not doing anything if SyntheticEvent is passed as the key but seems hacky.  Any ideas?

**Comment by aabenoja** [comment]
I'm unable to reproduce this. If you're still seeing this a pull request is always welcome. A sample implementation that reproduces the issue is also appreciated.
