### ISSUE TITLE
Can't get Checkbox on react-bootstrap@0.29.5 working

### ISSUE THREAD

**Issue by javaguy** [react-bootstrap/react-bootstrap#2440]
I'm migrating my code from using the old <Input> components to the new composable components `<FormControl>`, `<Checkbox>`, etc. But I can't seem to get Checkbox to work correctly. I looked through the issues but couldn't find anything related.

My code:
```
<FormGroup>
  <Checkbox>
    issue_alert
  </Checkbox>
</FormGroup>
```

Generates the following incorrect html:

```
<div class="form-group" data-reactid=".0.1.3.1.2.0.0.4.3"><label class="control-label" data-reactid=".0.1.3.1.2.0.0.4.3.0">issue_alert</label></div>
```

My old code:
```
<Input type='checkbox' label='issue_alert' />
```

Generated the following correct html:
```
<div type="checkbox" label="issue_alert" class="form-group" data-reactid=".0.1.3.1.2.0.0.4.3"><div class="checkbox" data-reactid=".0.1.3.1.2.0.0.4.3.$checkboxRadioWrapper"><label class="" data-reactid=".0.1.3.1.2.0.0.4.3.$checkboxRadioWrapper.$label"><input type="checkbox" label="issue_alert" class="" data-reactid=".0.1.3.1.2.0.0.4.3.$checkboxRadioWrapper.$label.$input"><span data-reactid=".0.1.3.1.2.0.0.4.3.$checkboxRadioWrapper.$label.1">issue_alert</span></label></div></div>
```

**Comment by jquense** [comment]
I'd make sure you don't have a stale bunch of files somewhere by nuking  node_modules and reinstalling. also that that version supports the newer API. I sort of thought it was introduced in 0.30 (I could easily be wrong)

**Comment by javaguy** [comment]
Nevermind, as soon as I hit save I realised the issue. I mislabeled ControlLabel as CheckBox when requiring the component, copy-paste issue.
