### ISSUE TITLE
TypeError: Cannot read property 'displayName' of undefined

### ISSUE THREAD

**Issue by futurechan** [react-bootstrap/react-bootstrap#2444]
I changed from `Link` to `LinkContainer` and started getting
> TypeError: Cannot read property 'displayName' of undefined

Here's my jsx.
```
<LinkContainer to={{ pathname: link.link }}>
  <MenuItem>{link.text}</MenuItem>
</LinkContainer>
```

Here are my dependencies.
```
"dependencies": {
    "react": "^15.4.2",
    "react-bootstrap": "^0.30.7",
    "react-dom": "^15.4.2",
    "react-redux": "^5.0.2",
    "react-router": "^3.0.0",
    "react-router-bootstrap": "^0.23.1",
    "react-router-redux": "^4.0.7",
    "redux": "^3.6.0"
  },
  "devDependencies": {
    "babel-cli": "^6.18.0",
    "babel-core": "^6.21.0",
    "babel-loader": "^6.2.10",
    "babel-polyfill": "^6.20.0",
    "babel-preset-env": "^1.1.8",
    "babel-preset-es2015": "^6.18.0",
    "babel-preset-react": "^6.16.0",
    "babel-preset-stage-2": "^6.18.0",
    "css-loader": "^0.26.1",
    "postcss-loader": "^1.2.1",
    "react-hot-loader": "^3.0.0-beta.6",
    "redux-devtools": "^3.3.1",
    "style-loader": "^0.13.1",
    "webpack": "^2.2.0-rc.3",
    "webpack-dev-server": "^2.2.0-rc.0"
  }
```

I'm kinda new to react, so I'm not sure what to do here. I posted this in https://github.com/react-bootstrap/react-router-bootstrap/issues/196 11 days ago and haven't received a response yet. Can someone point me to where I should start debugging?

**Comment by jquense** [comment]
sorry there isn't really enough here to tell what's going on. if I had to guess tho one of your imports is wrong maybe

**Comment by futurechan** [comment]
Hmmm. I don't know how much more I have. What else could I provide?

**Comment by futurechan** [comment]
@jquense I pushed my repo to github. Here's the source: https://github.com/futurechan/react-hello-world

**Comment by futurechan** [comment]
@taion I'm not sure what to do here. Can you please advise?

**Comment by jquense** [comment]
you need to debug a bit more. as much as we'd like to help no one has time to poke through your entire app repo looking for bugs.

**Comment by jquense** [comment]
like I said you are probably importing LinkContainer wrong, make sure you are matching the examples

**Comment by futurechan** [comment]
Is there a module I should put a `debugger` in? I searched for `displayName` and got 1000s of matches. I can try to reduce the jsx as much as possible.

**Comment by jquense** [comment]
> like I said you are probably importing **LinkContainer** wrong, make sure you are matching the examples

check that its not undefined, if it is you are importing it incorrectly. it should be `import { LinkContainer } from 'react-router-bootstrap'`

**Comment by futurechan** [comment]
That was it! Thank you so much!
