### ISSUE TITLE
Maxlength character counter (Feature Request)

### ISSUE THREAD

**Issue by isaachinman** [react-bootstrap/react-bootstrap#2445]
Wondering what the contributors of this project think about this. In my own use cases, I have found it very useful to provide users with a character counter for text inputs and textareas that have a `maxlength` attribute set.

[Here is a random codepen example I found in a few seconds of Googling.](https://codepen.io/kemalb/pen/zGPyjo) Does anyone else think this would be useful? I think it would be relatively easy to implement.

![screen shot 2017-01-24 at 11 39 57](https://cloud.githubusercontent.com/assets/10575782/22243950/e040d4d4-e229-11e6-96bf-f49c4139477d.png)

**Comment by jquense** [comment]
definitely useful however it's also out of scope for react-bootstrap. RB is just trying to reimplement bootstrap, and especially with form inputs it only provides styles over native inputs, not any additional functionality. we encourage folks to use these components as a base for those sorts of improvements tho in other libraries!

**Comment by isaachinman** [comment]
Okay got it. I might look into creating some kind of extension utility that can be use in conjunction with react-bootstrap or as a wrapper. Cheers.

**Comment by isaachinman** [comment]
**Update:** for anyone interested, I hacked together this wrapper component:

GitHub: [react-bootstrap-character-counter](https://github.com/isaachinman/react-bootstrap-character-counter)
npm: [react-bootstrap-character-counter](https://www.npmjs.com/package/react-bootstrap-character-counter)
