### ISSUE TITLE
Using font-awesome is there a "right" way to use fa-bars instead of glyphicons for Navbar.Toggle

### ISSUE THREAD

**Issue by mikedevita** [react-bootstrap/react-bootstrap#2448]
Using font-awesome is there a "right" way to use fa-bars instead of glyphicons for Navbar.Toggle

**Comment by taion** [comment]
https://react-bootstrap.github.io/components.html#navs-props-navbar-toggle

**Comment by mikedevita** [comment]
derp thanks.
