### ISSUE TITLE
Remove h3 from popover title

### ISSUE THREAD

**Issue by cjtafoya** [react-bootstrap/react-bootstrap#2449]
Since a node can be passed in (which is great), doesn't make sense to nest the prop within an h3 tag  (the .popover-title class overrides all the relevant mark up anyway)

**Comment by drsloth** [comment]
bump, I also would like to replace the h3

**Comment by taion** [comment]
@jquense I wonder if we should have `<Popover.Title>` and `<Popover.Content>`... ahaha

**Comment by bpas247** [comment]
So would this just be a re-design of the `Popover` component to make it more modular @taion?

**Comment by taion** [comment]
yup, i think that's how this would look. instead of taking a `title` prop, have a `<Popover.Title>` sub-component as in everything else
