### ISSUE TITLE
Multiline in textarea not working

### ISSUE THREAD

**Issue by sadarshannaiynar** [react-bootstrap/react-bootstrap#2451]
I have created a textarea and have given a value to it but still renders the whole paragraph as single line instead of multiline.  Even when enter key is pressed it doesn't create a new line.

`<FormGroup controlId={this.props.controlId}>
<ControlLabel>{this.props.field}</ControlLabel>   
<FormControl type="textarea" rows={10} defaultValue={this.props.value} onChange=this.props.changeListener}/>
</FormGroup>`

 

That's the code I have used.

**Comment by jquense** [comment]
hi there. form controls have no logic they are only style wrappers of native inputs. `type='textarea'` isn't a valid html5 input type, so it's just rendering a text box. you want componentClass='textarea' to change the tag being used, per the docs

**Comment by sadarshannaiynar** [comment]
Thanks for the reply. It works fine now. :)
