### ISSUE TITLE
Hide custom dropdown menu on losing focus

### ISSUE THREAD

**Issue by ayushchd** [react-bootstrap/react-bootstrap#2452]
I was trying to create a custom dropdown as mentioned here: https://react-bootstrap.github.io/components.html#btn-dropdowns. The fully customized toggle doesn't hide the menu when the focus is lost or when we click on any other element. How can we control the "open" parameter and how is it triggered?

**Comment by jquense** [comment]
it's the Menu component that contains the click outside behavior not the Toggle. in any case tho for the custom case you are responsible for implementing logic like that, the Dropdown component injects props for controlling the open state. I'd recommend looking at the source code to DropdownMenu

**Comment by ayushchd** [comment]
However, the out-of-focus logic seems to be in Dropdown and not DropdownMenu. The reason I am saying this is, on out-of-the-box dropdown elements, when I click outside the focus, I can see the Dropdown (not Menu) element's "open" prop change to false which then gets propagated down to DropdownMenu I believe. In case of customer dropdown menus, this does not happen. Also I could not find anything in particular that is hiding dropdown menu when going out of focus in it's source code.
