### ISSUE TITLE
Uncertain error with hot module reloading

### ISSUE THREAD

**Issue by awitherow** [react-bootstrap/react-bootstrap#2454]
Hello! Thank you for making this project available! Helped me a lot to rapidly prototype my UI.

I have been attempting to set up Hot Module Reloading within my React project on a PR. https://github.com/awitherow/aethernode/pull/70

I continually get the error in the screenshot

![screen shot 2017-01-28 at 22 27 01](https://cloud.githubusercontent.com/assets/1827147/22403462/2c412900-e618-11e6-8d68-e6afee76fa16.png)

I have bootstrap imported as a dependency and it seems to be messing with the hot loader in some way.

Would splitting the vendor js out probably fix things?

Any ideas?

**Comment by jquense** [comment]
the bootstrap file in your error isn't react-bootstrap it's a hot module file that webpack adds with the name bootstrap (from what I can tell here). I'm not sure what or why you have an error but I don't think it's related to RB
