### ISSUE TITLE
Modal closes when selecting text

### ISSUE THREAD

**Issue by basilfx** [react-bootstrap/react-bootstrap#2455]
When selecting some text in a modal, and you release the mouse button when it is positioned on top of the backdrop, the modal closes. This is undesired, because you have to be very accurate when selecting text.

This also affects the modal example on the components page: https://react-bootstrap.github.io/components.html#modals-live. Open the modal and try to select some text. Make sure you release the mouse button when the mouse is on the backdrop.

How can I fix this?

**Comment by taion** [comment]
dupe https://github.com/react-bootstrap/react-bootstrap/issues/1785
