### ISSUE TITLE
Overlay events

### ISSUE THREAD

**Issue by Moeface** [react-bootstrap/react-bootstrap#2456]
First off, thanks for the great library, very happy with it. I had a question about how overlays and events worked.

I'm trying to create an overlay, that when hovered over, shows a popover component. However, I'd also like to be able to keep the overlay open while the popover is being hovered over as well (so that elements within the popover can be interacted with).

When applying a `onMouseEnter` event to the popover to log something to the console (I've also tried a custom wrapper around the popover), the event is not triggered. 

It seems like the overlay gives DOM elements some weird behaviours (e.g. I am unable to inspect elements triggered by the overlay), so is this just a side effect of that?

Am I approaching this the wrong way or is this just the behaviour of overlay elements?

Thanks!

**Comment by taion** [comment]
Use `container`

**Comment by Moeface** [comment]
Could I please get a bit more context on this?

From what I understand, the container prop just gives the popover an area to be confined to. I'm not sure how it would be related to events on the overlay?

**Comment by taion** [comment]
if you set `container` then the mouse enter and leave events should do the right thing. overflow rendering on the container is orthogonal.

**Comment by villesau** [comment]
Setting `container` to `this` offsets the overlay. Why not providing the functionality out of the box? It's something that every hint having links needs.
