### ISSUE TITLE
Stopping event propagation doesn't work with Popover

### ISSUE THREAD

**Issue by alasdairhurst** [react-bootstrap/react-bootstrap#2457]
Noticed an issue with popover (not sure if it's for other things too), but including a popover as part of anything, and calling stopPropagation() on the onClick event ends up being ignored.

I'm surprised this hasn't been brought up by more people, but I guess it's because people don't set the container prop on the overlay trigger that much? 
Someone already created a working fiddle as seen here:
http://stackoverflow.com/questions/35279837/stoppropagation-not-preventing-bubbling-with-bootstrap-popover/35615009
http://jsbin.com/xagopuxeye/edit?js,output

In my case, the popover is within the cell of a table, where the row is clickable. Adding stopPropagation() to the click handler of the overlay trigger correctly stops the row click action from being triggered, but clicking any element within the popover causes the row click handler to fire even when adding another stopPropagation() to the click handlers inside the popover as well.

**Comment by alasdairhurst** [comment]
Actually, I believe it's possibly an issue with the usage of unstable_renderSubtreeIntoContainer  in OverlayTrigger when setting a container:
https://github.com/react-bootstrap/react-bootstrap/blob/master/src/OverlayTrigger.js#L239-L241

Haven't spent much time digging into it, but injecting the node into the DOM seems to mess up the react event handling in some way. Now, this could entirely be an issue with react, but then again the feature is marked as unstable, so should it be used in production? (or the container prop marked as unstable in the docs)

**Comment by taion** [comment]
The portal code is all delegated to react-overlays. I'm not sure if there's much we can do here, though.

**Comment by jquense** [comment]
I looked a bit into this and then gave up. I really am not sure why a native propagation block would propagate up through the portal here. Like i'm surprised bubble works at all, let alone ignores stopPropagation

**Comment by taion** [comment]
Going to close this as unfixable then
