### ISSUE TITLE
Wrong event key for NavDropdown in responsive navbar example?

### ISSUE THREAD

**Issue by shesko** [react-bootstrap/react-bootstrap#2458]
Hello,
I might misunderstand the way NavDropdown event keys work but I think you made a typo in your docs. 

In the responsive navbar example you have the following:

```
<NavDropdown eventKey={3} title="Dropdown" id="basic-nav-dropdown">
          <MenuItem eventKey={3.1}>Action</MenuItem>
          <MenuItem eventKey={3.2}>Another action</MenuItem>
          <MenuItem eventKey={3.3}>Something else here</MenuItem>
          <MenuItem divider />
          <MenuItem eventKey={3.3}>Separated link</MenuItem>
</NavDropdown>
```

Shouldn't the Separated link have an event key of 3.4?

Hope this helps :)

**Comment by taion** [comment]
The event keys just need to be unique. The ordering is irrelevant.

**Comment by jquense** [comment]
they aren't unique here ;0 it doesn't matter for the demo but yes don't do this in a real app

**Comment by taion** [comment]
Oops. It should be 3.4 then.
