### ISSUE TITLE
Disable MenuItem

### ISSUE THREAD

**Issue by alasdaircs** [react-bootstrap/react-bootstrap#246]
I have hacked my MenuItem code to include a `propTypes { disabled: React.PropTypes.bool }`

In recent browsers, (Chrome, IE11) the `transferPropsTo` in the render method produces <li disabled> which renders them as disabled with a "no-entry" icon, but earlier browsers don't respond to the disabled attribute. I have therefore added disabled to the class map:

    var classes = {
        'dropdown-header': this.props.header,
        'divider': this.props.divider,
        'disabled': this.props.disabled
      };

and I have CSS:

```
.disabled {
	color: lightgray;
	cursor: not-allowed;
}
```

But in general, it might be better to allow arbitrary classes to be passed down to the `<li>` - what do you think?

**Comment by SindreSvendby** [comment]
This is actually allowed now, unsure on how this is when the issue was created, but now you can just pass the className props to the MenuItem class. 

```jsx
<MenuItem className='disabled' />
```
and add your own CSS to get the item disabled, e.g.

```css
.disabled {
    color: lightgray;
    cursor: not-allowed;
}
```

https://github.com/react-bootstrap/react-bootstrap/blob/master/src/MenuItem.js#L51

**Comment by mtscout6** [comment]
It would be nice to have this enabled via props. Allowing something like: `<MenuItem disabled>herp derp</MenuItem>`

You shouldn't need custom CSS though since bootstrap should support this: http://getbootstrap.com/components/#dropdowns-disabled
