### ISSUE TITLE
Feature request: Adding custom css classes to a component

### ISSUE THREAD

**Issue by winterstein** [react-bootstrap/react-bootstrap#2460]
Firstly, thank you for making this library.

In our code, we often add extra classes in places to hook in the site-specific css rules. E.g. `<button class='my-funky-button btn btn-primary'>`

Could react-bootstrap components support this, with an `extraClass` property or similar?

**Comment by jquense** [comment]
in React the prop is className,and all the components support it :thumbsup:

**Comment by max-litv** [comment]
Documentations are not as clear as it could be. Just realized that you can use `className="my-funky-button"` to add an extra class to existing list.
ex:

`<Button bsStyle="danger" onClick={} className={"marginTop20"}><Glyphicon glyph="minus"/></Button>`
