### ISSUE TITLE
Disabled menu item not disabling OnClick handler

### ISSUE THREAD

**Issue by sanyamc** [react-bootstrap/react-bootstrap#2462]
I think onClick should not fire when disabled is true.  Especially as per the documentation that "disabled menu item prevents onclick". However onClick still fires even if disabled is true. 
OnSelect seems to work fine and not fire when disabled is true.

**Comment by jquense** [comment]
Thanks for the report. The documentation has a typo, `onSelect`, not `onClick`, is prevented, but we leave the native html events alone since you can't actually disable a `<li>` element.

**Comment by taion** [comment]
@jquense Are you sure that's right? It looks like `<SafeAnchor>` does block `onClick`, but that this logic isn't doing anything because we don't pass through `disabled` from `<MenuItem>` to `<SafeAnchor>`.

**Comment by jquense** [comment]
safe anchor does it because its directly emulating a Button tag. this seems different to me. in any case tho onSelect is the semantically relevant handler to disable here I think

**Comment by taion** [comment]
We do this for `<NavItem>` though

**Comment by akkie** [comment]
I stumbled over the same issue and I do not really understand the argumentation. Could please someone explain why a disabled menu item should be clickable? I'm not really sure why this make sense?

**Comment by calumbrodie** [comment]
If you bind your event to 'onSelect' instead then you will probably get the behaviour you are looking for. It's not intuitive but the 'select' event is dispatched when clicking a menu item.

**Comment by jquense** [comment]
@taion we should be consistent yeah... I'm more inclined tho to not block onClick, and avoid the whole "emulate native disabled behavior" thing since it's more than just click events. at least in onSelect that's all our API so the behavior can be whatever

**Comment by taion** [comment]
@jquense So you're saying drop this support on `<NavItem>`? I dunno, seems cheap to forward `disabled` to me.

**Comment by jquense** [comment]
its cheap to handle onClick, but i'm slightly concerned for scope creep. `disabled` also disables all mouse events, not just onClick. it also prevents capture and blocks propagation. 

Another concern is that it's super easy to handle this in our own code, but hard to opt out of if you need an onclick event on the "disabled" item. I dunno. I don't feel super strong about it, but opt slightly more for not messing with the native behavior.

**Comment by taion** [comment]
Ah, I see – perhaps we should drop that logic in `<NavItem>` then.
