### ISSUE TITLE
Modal is showing console error - NaN is an invalid value for the `paddingRight` css style property

### ISSUE THREAD

**Issue by cmcnamara87** [react-bootstrap/react-bootstrap#2463]
I have recently started getting this console error when I use a modal:
```
Console

    console.error node_modules/fbjs/lib/warning.js:36
      Warning: `NaN` is an invalid value for the `paddingRight` css style property. Check the render method of `ModalDialog`.
```

I'm using 15.4.2 and the error is appearing when I use the example code from here: https://react-bootstrap.github.io/components.html#modals-live

**Comment by taion** [comment]
We don't get this on the docs page, so you're going to have to provide a lot more detail here.

**Comment by pgilad** [comment]
@taion Happens when you use `TestUtils.renderIntoDocument(<Modal...)` using jsdom. This derives from the `getScrollbarSize()` returning `NaN` and React throws a warning

**Comment by pgilad** [comment]
Added a PR to help fix this:
https://github.com/react-bootstrap/dom-helpers/pull/22

**Comment by cmcnamara87** [comment]
thanks @pgilad !

**Comment by YurySolovyov** [comment]
I'm getting almost the same warning but for `top` value when using Overlay/Popover:
```
`NaN` is an invalid value for the `top` css style property
```

**Comment by barmaley443-sfdev** [comment]
> I'm getting almost the same warning but for `top` value when using Overlay/Popover:
> 
> ```
> `NaN` is an invalid value for the `top` css style property
> ```

+1

**Comment by FullStackForger** [comment]
Similar error for 'left' when testing Tooltip with OverlayTrigger.
```
   Warning: `NaN` is an invalid value for the `left` css style property.
``` 
Since it is different component, reported as separate issue [4997](https://github.com/react-bootstrap/react-bootstrap/issues/4997) but there seem to be a pattern here.
