### ISSUE TITLE
React-bootstrap does not support autocomplete, Tree component. is there any plan to add it in future?

### ISSUE THREAD

**Issue by KalpanaPagariya** [react-bootstrap/react-bootstrap#2467]

**Comment by jquense** [comment]
hi there. we only support the components that normal bootstrap supports, as such we are planning on adding any more components types

**Comment by KalpanaPagariya** [comment]
So do you have  any plan to add this in future? Or till bootstrap does not add, react-bootstrap will also not add?

**Comment by larrydahooster** [comment]
If you are looking for a autocomplete library you could check this one: https://github.com/ericgio/react-bootstrap-typeahead

I have had good experiences with it in my project.
