### ISSUE TITLE
onToggle not triggered when clicking outside menu

### ISSUE THREAD

**Issue by japhar81** [react-bootstrap/react-bootstrap#2471]
I've got a custom menu set up per the docs;
```
<Dropdown componentClass='li' className='messages-menu' id='dropdown-custom-menu' open={this.props.open === 1} onToggle={this.props.onOpen}>
    <CustomToggle bsRole='toggle'>
        <i className='fa fa-envelope-o'/>
    </CustomToggle>
    <CustomMenu bsRole='menu'>
        <li className='header'>test</li>
        <li>
            <ul className='menu'>{messageList}</ul>
        </li>
    </CustomMenu>
</Dropdown>
```

Seems to work great with the toggling behavior if i click the menu item to open/close. However, I can't seem to get it to auto-close when i click on the rest of the page. I would have expected `onToggle` to fire, but it doesn't appear to. Is this deliberate? If so, how would I approach this?

**Comment by taion** [comment]
dupe https://github.com/react-bootstrap/react-bootstrap/issues/2324
