### ISSUE TITLE
Tabs in modal

### ISSUE THREAD

**Issue by aroybase** [react-bootstrap/react-bootstrap#2472]
Hi everyone !
I'm currently having an issue with the use of tabs in a modal. I need this feature for my "user informations card" in my application. I have few tabs in the modal and here what is happening : 
- http://hpics.li/bb9a6d1 (default tab)
- http://hpics.li/219595b

When i'm switching from the default tab to another, the default tab is still viewable in background.

And here is a piece of code (not really relevent i think)

```
// People.jsx
<Modal bsSize="large" show={this.state.showEditPerson}
       onHide={this.closeModal.bind(this)}>
    <EditPerson />
</Modal>
```

```
// EditPerson.jsx
<div id="editPerson">
    <Modal.Header closeButton>
        <Modal.Title>
            {this.state.title}
        </Modal.Title>
    </Modal.Header>

    <Modal.Body>
        <Tabs id="person-edit-tabs">
            <Tab disabled={false} eventKey={0} title="Profil"><Profile/></Tab>
            <Tab disabled={true} eventKey={1} title="Compétences"><Skills/></Tab>
            <Tab disabled={true} eventKey={2} title="White list"><WhiteList/></Tab>
            <Tab disabled={true} eventKey={3} title="Black List"><BlackList/></Tab>
            <Tab disabled={false} eventKey={4} title="Affectations"><Assignments/></Tab>
            <Tab disabled={_.isUndefined(person.id)} eventKey={5} title="Absences"><Absences/></Tab>
        </Tabs>
    </Modal.Body>
    <Modal.Footer/>
</div>

/*
 Right now, my tabs dont contain any relevant content
*/
```

**Comment by taion** [comment]
Tab hiding by default is handled by CSS, so make sure your CSS is set up correctly.

**Comment by gop-aroy** [comment]
Why did you close this issue ? This is not resolving the problem at all : 
http://hpics.li/3d7f5d8

Can you please re-open and spend more than 20sec on this ?

**Comment by jquense** [comment]
@gop-aroy can you please spend more than 20 secs reporting the problem then. Put together a working reproduction of the error we can debug in jsbin/jsfiddle thanks

**Comment by gop-aroy** [comment]
Of course I could, if asked as nicely as you did, but i won't… why ? Simple :)
I tried to delete all my CSS on my project, still not working for me. :(
I tried to reproduce on a fiddle, impossible, **it's working** just as we can expect. :/

I'm going to un-import the other libs to see if there is any incompatibility.
If there is not… Maybe there's a ghost in my code.

**Comment by gop-aroy** [comment]
I think I found… Modals are "generated" inside a loop… so i have something like 👍 

```
return this.props.people.map((person, index) => (
    <tr key={index}>
        <td key="fname">{person.first_name}</td>
        <td key="lname">{person.last_name}</td>
        <td key="roles" className="hidden-xs">{person.tags.roles[0].value}</td>
        <td key="skills" className="hidden-xs">{this.renderPersonSkills(person.tags.skills)}</td>
        <td key="projects" className="hidden-xs">{person.projects[0].label}</td>
        <td key="actions" className="actions">
            <ButtonGroup>
                <Button bsStyle="success" bsSize={btnSize} onClick={this.openModal.bind(this, person)}>
                    <FontAwesome data-href={person.url} fixedWidth name="edit"/>
                </Button>
                <Button bsStyle="warning" bsSize={btnSize}>
                    <FontAwesome data-href={person.url} fixedWidth name="ban"/>
                </Button>
            </ButtonGroup>

             <Modal bsSize="large" show={this.state.showEditPerson} onHide={this.closeModal.bind(this)}>
                 <EditPerson />
             </Modal>
        </td>
    </tr>
));
```
Apparently, it doesn't work but this might be legit from a certain POV. Anyway, problem solved, i just took this out and this is workign again. Now you can close the issue. Wait… :D

**Comment by giovannipds** [comment]
Got a similar issue using Custom Tabs layout. I was forgetting to put all the contents in the `Tab.Content` component, which handles the default CSS for `display`. Just commenting if I or someone else come here in the future. 😆
