### ISSUE TITLE
Navigation tags still causing react-unkown-prop errors

### ISSUE THREAD

**Issue by Relequestual** [react-bootstrap/react-bootstrap#2474]
Recreating the example at 
https://react-bootstrap.github.io/components.html#navbars-mobile-friendly
I get the error `Warning: Unknown props `active`, `activeKey`, `activeHref` on <li> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop`.

I see and have read the majority of #1994, including the last few comments where the claim is made that there are no remaining issues. A few comments before the end, someone else has a similar issue, and it's unclear if they were able to resolve it (https://github.com/react-bootstrap/react-bootstrap/issues/1994#issuecomment-242740679)

I then realised I wasn't quite recreating the example exactly, and had an `li` tag at the end of my `Nav` tag, like the following:

```jsx
...
return (
      <Navbar collapseOnSelect className="navbar navbar-default navbar-fixed-side">
        <Navbar.Header>
          <Navbar.Brand>
            <a href="#">{config.title}DDDDD</a>
          </Navbar.Brand>
          <Navbar.Toggle />
          </Navbar.Header>
          <Navbar.Collapse>
              <Nav>
          <NavItem eventKey={1} href="#">Link</NavItem>
          <NavItem eventKey={2} href="#">Link</NavItem>
          <NavDropdown eventKey={3} title="Dropdown" id="basic-nav-dropdown">
            <MenuItem eventKey={3.1}>Action</MenuItem>
            <MenuItem eventKey={3.2}>Another action</MenuItem>
            <MenuItem eventKey={3.3}>Something else here</MenuItem>
            <MenuItem divider />
            <MenuItem eventKey={3.3}>Separated link</MenuItem>
          </NavDropdown>
          <li className="divider"></li>
        </Nav>
        </Navbar.Collapse>
      </Navbar>
    );
...
```

The major difference is the `li` tag before the closing of `Nav`. This must be the `li` tag being refurred to, but I haven't added any of the attributes listsed as causing the warn. I'm pretty new to this, but I thought I was allowed to add HTML tags amoungst my other JSX / react tags? If I remove the `li` tag, then I don't get the warning. 

Is this a bug or am I missunderstanding how some part of this works?

**Comment by jquense** [comment]
> but I thought I was allowed to add HTML tags amoungst my other JSX / react tags? 

its allowed generally, but in this case the `Nav` component injects props automatically into the child elements, because it expects them to be NavItems.

You need to create a wrapper component that doesn't forward the props to the `li` tag:

```js
function NavDivider() {
  return <li className="divider" />
}
```

**Comment by Relequestual** [comment]
Thanks @jquense. So I create that function and then call it in place of where I previously had the `li` and it will work OK? Of course I can test this, but just for clarification for anyone else looking.

**Comment by jquense** [comment]
no don't call it, the above is a component, use it like `<NavDivider />`

**Comment by Relequestual** [comment]
OH. OK. So using a component in that way is treated differently than just using an HTML tag? Is this fairly standard? (Still pretty new to react)

**Comment by jquense** [comment]
they aren't treated differently, both cases are just components. the issue is one of typing, Nav components expect NavItems as children, not any component. the li tag has a different set of props it expects than the NavItem, the workaround above uses an intermediary component to shim that API.

**Comment by jquense** [comment]
and yeah this is a fairly standard idiom in React
