### ISSUE TITLE
Button behavior broken when using Tooltip/OverlayTrigger on it

### ISSUE THREAD

**Issue by pgoldweic** [react-bootstrap/react-bootstrap#2477]
I have a component that essentially displays a button with a particular action associated to the onClick property. When I use this component without a tooltip, it works as expected. However, when adding a tooltip to it, the behavior breaks and the onClick function is never called. Is this a known bug/limitation?

**Comment by jquense** [comment]
> Is this a known bug/limitation?

nope.

can you post code reproducing the issue in a fiddle/jsbin?

**Comment by pgoldweic** [comment]
I've just realized it was actually my fault (unintentionally mixing up react-bootstrap and reactsrap components!). Sorry! Closing this item now.
