### ISSUE TITLE
Checkbox wont allow me toggle

### ISSUE THREAD

**Issue by meghanarora** [react-bootstrap/react-bootstrap#2481]
Won't allow toggling :
<Checkbox inline checked={true} inputRef={ref => { this.input = ref; }} onChange={console.log(this.input)}> Quantity </Checkbox>

Any idea why?

**Comment by jquense** [comment]
check out: https://facebook.github.io/react/docs/forms.html you are using a controlled input without an onChange handler

**Comment by meghanarora** [comment]
Does the onChange function not count as a handler?

**Comment by jquense** [comment]
you have a typo: onChang isn't a function: `onChange={console.log(this.input)}`. its actually evaluating to `onChange={undefined}` since console.log returns nothing

**Comment by joelseq** [comment]
I think your problem is the fact that you have set `checked={true}` which is keeping the Checkbox checked no matter what. If you are going to use the `checked` prop make sure to set it to a variable that you control depending on if the checkbox should be checked or not.
