### ISSUE TITLE
IE8 Dropdown menuitem with href empty/#/javascript void(0)

### ISSUE THREAD

**Issue by sahilkhan99** [react-bootstrap/react-bootstrap#2483]
There is an issue with dropdown menu items in IE8
MenuItem with empty href/#/javascript:void(0); and doing onClick (function) is not doing anything.
The page is navigating to home page.

If there is workaround , please let me know.

Thanks,
In advance.

**Comment by taion** [comment]
https://facebook.github.io/react/blog/2016/01/12/discontinuing-ie8-support.html
