### ISSUE TITLE
<Checkbox> missing 'for' on <label> and 'id' on <input>.

### ISSUE THREAD

**Issue by Tekhne** [react-bootstrap/react-bootstrap#2486]
I'm using `react-bootstrap@0.30.7` with `react@15.4.2` and `node@7.5.0`.

The `<Checkbox>` component, unlike other components, seems to be missing the ability to specify a `for` attribute for the rendered `<label>` element, and an `id` attribute for the rendered `<input>` element. Among other issues, this hurts the accessibility of `<Checkbox>`. I tried specifying a `controlId` prop on the `<FormGroup>`, but that didn't seem to help. If this is actually a problem, and not a misunderstanding on my part, it might be worth checking on `<Radio>` too.

Thanks!

**Comment by taion** [comment]
see https://github.com/react-bootstrap/react-bootstrap/issues/1947

**Comment by Tekhne** [comment]
For anyone else who stumbles on this issue:

Based on the discussion in #1947, it looks like the `for` and `id` attributes are not strictly necessary for accessibility, since the `<label>` produced by `<Checkbox>` wraps the `<input>`.
