### ISSUE TITLE
Modal Styling probelm

### ISSUE THREAD

**Issue by hosusan6** [react-bootstrap/react-bootstrap#2487]
I am using the modal as directed in the example but am finding it appearing right at the top of my page rather than in the middle. what am i missing please?
![screen shot 2017-02-17 at 16 04 25](https://cloud.githubusercontent.com/assets/24848779/23083515/00016a80-f52c-11e6-8992-e12a12d65854.png)

**Comment by taion** [comment]
This is controlled by your CSS, and is out of scope here.
