### ISSUE TITLE
NavItem does not collapse/expand

### ISSUE THREAD

**Issue by c0debreaker** [react-bootstrap/react-bootstrap#2489]
I'm trying to make the Sub items appear/disappear when I click on `Menu Item 4` However, not sure what react-bootstrap code I'm missing. It does call the toggle method which toggles expanded attribute.

Here is the jsfiddle - https://jsfiddle.net/9fd553ay/11/

**Comment by jquense** [comment]
bootstrap navs don't have that feature. if you want hide or show nats you'll have to do it with custom css classes.

**Comment by c0debreaker** [comment]
that sucks. Navbar does have it. Would have been nice if it was consistent in react-bootstrap
