### ISSUE TITLE
How to get actual viewport screen size (xs, sm, md, lg)  as a prop?

### ISSUE THREAD

**Issue by dkudrin** [react-bootstrap/react-bootstrap#2490]
Hello, I need to set some 'IF' statements depending on viewport screen size (xs, sm, md, lg). How can I get it?

Thank you!

**Comment by taion** [comment]
That's out of scope here. It would depend on how specifically you set those breakpoints anyway.

**Comment by popovitsj** [comment]
Why is this out of scope? It would be very useful to have this, for example if you want to know how many Columns to render in a row.

**Comment by mackbrowne** [comment]
+ 1.  Just came here looking for this too

**Comment by toddobryan** [comment]
Me, also. I want to change between long and short versions of text in the Navbar depending on how big the viewport is.
