### ISSUE TITLE
 Maximum call stack size exceeded error

### ISSUE THREAD

**Issue by lkashyap4th** [react-bootstrap/react-bootstrap#2491]
when i use this code: -

`var React = require('react');
var {Link, IndexLink} = require('react-router');
var {Nav, Navbar, NavItem, NavDropdown, MenuItem} = require('react-bootstrap');

var Nav = React.createClass({
  render: function () {
    return (
      <div>
        <h2>Nav Component</h2>
        <Navbar inverse collapseOnSelect>
        <Navbar.Header>
          <Navbar.Brand>
            <a href="#">React-Bootstrap</a>
          </Navbar.Brand>
          <Navbar.Toggle />
        </Navbar.Header>
        <Navbar.Collapse>
          <Nav>
            <NavItem eventKey={1} href="#">Link</NavItem>
            <NavItem eventKey={2} href="#">Link</NavItem>
            <NavDropdown eventKey={3} title="Dropdown" id="basic-nav-dropdown">
              <MenuItem eventKey={3.1}>Action</MenuItem>
              <MenuItem eventKey={3.2}>Another action</MenuItem>
              <MenuItem eventKey={3.3}>Something else here</MenuItem>
              <MenuItem divider />
              <MenuItem eventKey={3.3}>Separated link</MenuItem>
            </NavDropdown>
          </Nav>
          <Nav pullRight>
            <NavItem eventKey={1} href="#">Link Right</NavItem>
            <NavItem eventKey={2} href="#">Link Right</NavItem>
          </Nav>
        </Navbar.Collapse>
      </Navbar>

        <IndexLink to="/" activeClassName="active" activeStyle={{fontWeight: 'bold'}}>Get Weather</IndexLink>
        <Link to="/about" activeClassName="active"  activeStyle={{fontWeight: 'bold'}}>About</Link>
        <Link to="/examples" activeClassName="active" activeStyle={{fontWeight: 'bold'}}>Examples</Link>
      </div>`

show this error 
![image](https://cloud.githubusercontent.com/assets/22653776/23122797/bc4b3ea8-f78b-11e6-8072-617146e1c949.png)

**Comment by taion** [comment]
The equivalent code works fine in our examples. Make sure you're importing everything correctly.

**Comment by vgvenkat** [comment]
For people facing this error, the import statement on line 3 missed `Nav` from `react-bootstrap`.
