### ISSUE TITLE
Dropdown button closes immediately after click

### ISSUE THREAD

**Issue by Vija02** [react-bootstrap/react-bootstrap#2492]
I used the following code :
```
<DropdownButton bsStyle="success" title="Test" key={0} id={`dropdown-basic-${0}`}>
    <MenuItem eventKey="1">Action</MenuItem>
    <MenuItem eventKey="2">Another action</MenuItem>
    <MenuItem eventKey="3" active>Active Item</MenuItem>
    <MenuItem divider />
    <MenuItem eventKey="4">Separated link</MenuItem>
</DropdownButton>
```
Everything looked good. However, when i clicked on the button, nothing showed up. 
Upon further inspection, it turns out that there is an event listener that is triggered when the mouse is clicked right [here](https://github.com/react-bootstrap/react-overlays/blob/master/src/RootCloseWrapper.js#L84) in react-overlays.

The function triggered by the event causes the dropdown to close immediately after it was opened. I looked at how the code in [/docs](https://github.com/react-bootstrap/react-bootstrap/tree/master/docs) behaved and the event isn't triggered there. 
Any ideas as to why this is happening? 

(I'm not sure if i should post this in react-overlays instead)

**Comment by Vija02** [comment]
Looks like this is caused by using [preact](https://github.com/developit/preact)

**Comment by taion** [comment]
Don't think there's anything we can do here, then.
