### ISSUE TITLE
OverlayTrigger unable to specify arrowOffset Left/Top properties to tooltip

### ISSUE THREAD

**Issue by bcowgill** [react-bootstrap/react-bootstrap#2494]
The OverlayTrigger component only passes placement property on to the tooltip it creates so you cannot specify arrowOffsetLeft or arrowOffsetTop properties.

The original problem we had is

```
[ file name ....................................]
.................------^------
.................|..tooltip..|
.................-------------

```
tooltip overlay wrapped around the field above positions tooltip at center of field not center of text.
due to css overflow ellipsis on the container we cannot wrap the filename itself because very long file names will position tooltip off to right outside the field entirely.

If we could set the arrowOffsetLeft we could at least to this:

```
[ file name ....................................]
.....-^-----------
.....|..tooltip..|
.....-------------

```
By wrapping the ToolTip component in our own component we can intercept the creation of the tooltip component and alter to positioning of the tooltip but the tooltip width is not passed in to tooltip props
so there's no way to know what width was used when calculating the new positionLeft and positionTop values.

Would be very useful if toolTipWidth and toolTipHeight were passed into Tooltip and Popover components by the OverlayTrigger when it triggers the tooltip.

Putting a bit of code here in case it helps to explain the idea.

```
export default function ToolTipComponent ({
        message, placement, arrowOffsetLeft, children
        , trigger, container, onCalculatePosition
    }) {
    const ToolTipOrPopOver = getComponent(trigger)
        , content = getLines(message)
        , overlay = (<ToolTipPositioner
                id={Id.getIdNumberOf(Id.unique())}
                component={ToolTipOrPopOver}
                onCalculatePosition={onCalculatePosition}
            >
                <span className={displayName}>{content}</span>
            </ToolTipPositioner>)

    return (<OverlayTrigger {...{
            placement
            , arrowOffsetLeft // <-- not passed from OverlayTrigger to Tooltip on creation
            , overlay
            , trigger
            , container}}
            rootClose={true}>
            <span className={displayName + 'Overlay'}>
                {children}
            </span>
        </OverlayTrigger>)
}

class ToolTipPositioner extends React.Component {
    render(){
        const ToolTipOrPopOver = this.props.component
            , onCalc = this.props.onCalculatePosition
            , calc = (props) => {
                return onCalc ? onCalc(props) : props
            }
            , newProps = calc(omit(
                ['children', 'style', 'component', 'onCalculatePosition']
                , this.props))

        return (<ToolTipOrPopOver {...newProps}>
                { this.props.children }
            </ToolTipOrPopOver>
        )
    }
}
```

**Comment by alexcastillo** [comment]
+1

**Comment by taion** [comment]
I can see why you would use this, but I don't think this makes sense overall as an API. I don't think hooking that much into the details of the position calculation makes that much sense; ultimately, if you want to have custom positioning logic, you can calculate position yourself as needed – e.g. wrap your tooltip in a `<CustomPosition>` component and implement your choice of logic there.
