### ISSUE TITLE
Modal using ES6

### ISSUE THREAD

**Issue by richardvaldiviesomacias** [react-bootstrap/react-bootstrap#2496]
I created a simple modal for testing react-bootstrap. Here is code

import React, {PropTypes}  from 'react';
import {connect} from 'react-redux';
import {bindActionCreators} from 'redux';
import * as actions from '../homeActions';
import {Navigation,Footer,Content,Menu,Profile} from '../../core';
import {Modal, Button} from 'react-bootstrap';

export class HomePage extends React.Component {
  constructor(props) {
      super(props);
      this.state = {showModal:false};
  }
  componentDidMount() {
    this.props.actions.getFlag();

  }
    close() {
        this.setState({ showModal: false });
    }

    open() {
      if (!this.props.user.flag ) {
          this.setState({ showModal: true});
      }
    }

  render() {
    return (
      <div>
        <h1>This is a test for showing a modal</h1>
          <Modal show={this.state.showModal} onHide={this.close.bind(this)}>
              <Modal.Header>
                  <Modal.Title>Modal heading</Modal.Title>
              </Modal.Header>
              <Modal.Body>
                  <h4>Text in a modal</h4>
                  <p>Duis mollis, est non commodo luctus, nisi erat porttitor ligula.</p>
              </Modal.Body>
              <Modal.Footer>
                  <Button onClick={this.close.bind(this)}>Close</Button>
              </Modal.Footer>
          </Modal>
          <button onClick={this.open.bind(this)}>Click me</button>
      </div>
    );
  }

}

HomePage.propTypes = {
  actions: PropTypes.object.isRequired,
  user: PropTypes.object.isRequired
};

function mapStateToProps(state) {
  return {
    user: state.testData.user
  };
}

function mapDispatchToProps(dispatch) {
  return {
    actions: bindActionCreators(actions, dispatch)
  };
}
export default connect(mapStateToProps,mapDispatchToProps)(HomePage);

When I click the open button it shows the content of the Modal but as plain div. No error shows up.

**Comment by taion** [comment]
you need to provide css
