### ISSUE TITLE
color a NavItem

### ISSUE THREAD

**Issue by lordKnighton** [react-bootstrap/react-bootstrap#2497]
I don't know if this is a bug report, or it's just me:

I'm trying to color the contact li item. I've tried `className & bsClass`
Funny thing, it's showing in in the dev tools: elements but not applying the color
all over my app it works, its just the `NavItem` seems to be throwing it off? hmm. 

-------

Shot of the project: ( click for better image )
![screen shot 2017-02-28 at 10 53 12 pm](https://cloud.githubusercontent.com/assets/1773260/23449354/f21e7f38-fe0a-11e6-99e5-28f311d2ecfc.png)

---
shot of App.js:
![screen shot 2017-02-28 at 10 49 13 pm](https://cloud.githubusercontent.com/assets/1773260/23449372/044f1244-fe0b-11e6-9dac-ca5ae0fa5dc6.png)

---

Here a shot of the `css` for my Home/About/Contact that's working fine
myCss was a last ditch effort to see if something could work, but not ❗️ 
myCss is temporary. Just there, for testing this issue. 
![screen shot 2017-02-28 at 10 54 10 pm](https://cloud.githubusercontent.com/assets/1773260/23449340/e256dcee-fe0a-11e6-84b6-bfe3a8dc7c15.png)

**Comment by erinknight242** [comment]
@lordKnighton I'd guess the <a> that is generated inside the <li> has a more specific style defined. Try defining it in your css as li.test a { color: #f00; }

Also I think your CSS screen shot is wrong; you have .li test, but it should actually be li.test (with no space or dot before the li) if you mean to be styling the class named "test" on an li element. The space indicates a child element.

**Comment by lordKnighton** [comment]
This problem is still persisting.  If i comment out 

import 'bootstrap/dist/css/bootstrap.css'
import 'bootstrap/dist/css/bootstrap-theme.css'
these two, then it works great, but i don't get the react-bootstrap features. Any more help would be great. @taion Have you seen a case like this before?

**Comment by dozoisch** [comment]
@lordKnighton what @erinknight242 seems to be the correct answer. When you remove bootstrap it works because `a` then inherits from body instead of the selector `.li test` which doesn't seem to be the correct selector in your case.

**Comment by erinknight242** [comment]
@lordKnighton As I said, you need to make your custom selector more specific than what you are trying to override. I looked at some bootstrap css, and it looks like nav items are styled with `.navbar-default .navbar-nav > li > a`, which is a very specific selector. To make yours more specific, you will need to define your css as `.navbar-default .navbar-nav > li.test > a { color: #f00; }`. If that still doesn't work, inspect your DOM to find the css class that is defining the color for your `a`.

**Comment by lordKnighton** [comment]
Thanks @erinknight242 :   I've tried your suggestion `.navbar-default .navbar-nav > li.test > a { color: #f00; }`  and I've tried it with specificity:   
```css
NavItem[href*="Contact"] {
  border-color: lawngreen;
}
```
And I've inspected it again. getbootstrap is overriding it. I don't know how to override it ... sigh  whatever though. I'll just make a work around. thanks though. @erinknight242 @taion

**Comment by ArslanShakoor** [comment]
you can change the color of MenuItem or NavItem here

     .navbar-default .navbar-nav > li > a {
          color: white;
        }

Basic trick is going to dev-tool and check the css properties and you can do anything.

**Comment by kdstearns** [comment]
I have been having this same issue. What I ultimately ended up doing was changing the className in my .js file to className="navOptions" and then in the CSS I changed it from '.navbar-default .navbar-nav>li>a' to .navOptions {} with all the specifics. HOWEVER.... every property is being read and shown on the app when I run it, EXCEPT the font color. For some reason, react-bootstrap is still overriding the font color, even though the margin, border-bottom, text-align are all working as well as the :hover properties.

Anyone know what may be different/special about the color: attribute that react-bootstrap wont' adhere to?

**Comment by Mulli** [comment]
@kdstearns I do not know much about react-bootstrap, but you did not mention the "!important" CSS option for your color issue. Try `color: red !important;` if you haven't done so, yet.

**Comment by davegreig** [comment]
Jumping on this one too.
Overriding the colour of `nav-link` with `!important` does work for me, but then my problem is I'm unable to style the on hover state, or the active link state.

Other styles are trivial to add - like a border, or different font size. Overriding the colour seems to be the exception to the rule here.

**Comment by MariusCimpoeru** [comment]
thanks a lot, mate. it took me a white to find this solution
