### ISSUE TITLE
Tabs, Pager and DropdownButton mess with my hash router

### ISSUE THREAD

**Issue by flicaflow** [react-bootstrap/react-bootstrap#250]
Hi,
First of all, great effort, great library, it's really a pleasure to develop UI with this, thank you!

However I have a problem with certain components like Tabs, Pager or DropdownButton.
These components and probably other, insert href attributes into the dom nodes like 'href="#"' for no good reason (I didn't specify a href). This in turns navigates my page to the root view since I'm using a hash router (react-mini-router).

Currently I'm working around this Problem by removing the hrefs manually in the componentDidMount method. However this is an ugly workaround.

So it seems like we could drop the href="#" without loosing functionality. 
Am I right? Did I overlook something?

**Comment by AlexKVal** [comment]
Superceded by #526
