### ISSUE TITLE
How to get value of Checkbox

### ISSUE THREAD

**Issue by phamj88** [react-bootstrap/react-bootstrap#2501]
I have a simple form with a checkbox in it.
```
<Form onSubmit={this.handleSubmit}
  <checkbox ref='id'  > ID</Checkbox>
</Form>
```

How do I read the value of the check box in handleSubmit?
I know this is a simple question but I can't seem to find the answer anywhere.
With FormGroups I can do ReactDOM.findDomNode(this.refs.id.value)

**Comment by jquense** [comment]
Use a controlled Checkbox and store the value in state. That's the most correct way. If you really want to do it the imperative, non-react way, you can use the `inputRef` prop to attach a ref to the checkbox input and then you can read the value off it like you would normally.

**Comment by phamj88** [comment]
@jquense thanks for the quick reply.
If i were to go the inputRef way I see examples using:
`<Checkbox inputRef={ref => {this.input = ref }} >`
I feel stupid, i don't understand this. 
How does this set the ref? Do I still need to set ref='id'
In order to get the value in handleSubmit
ReactDOM.findDomNode(this.refs.id.value)

**Comment by erinknight242** [comment]
String refs have been deprecated in React; using the callback style `ref={(input) => { this.textInput = input; }}  ` you would reference it like ReactDOM.findDomNode(this.input.id.value). Check the docs for more info: https://facebook.github.io/react/docs/refs-and-the-dom.html

**Comment by bistrianalin** [comment]
The following example works for me.

` constructor(props) {
    super(props);
    this.state = {
        .....
    };
    this.email = React.createRef();
  }

  updateUsername = () => {
    this.setState({ username: this.email.current.value });
  };
...

<Form.Control
              ref={this.email}
              type="email"
              placeholder="Enter email"
              onChange={this.updateUsername}
            />
`
1. Set this in the constructor: `this.email = React.createRef();`
2. Set a ref in the FormControl: `ref={this.email}`
3. Read it with: `this.email.current.value` 

I hope this helps.
