### ISSUE TITLE
Checkbox validationState inline problem

### ISSUE THREAD

**Issue by luzeduardo** [react-bootstrap/react-bootstrap#2502]
Using checkbox inline with validationState=error doesn't style element

![screenshot from 2017-03-06 19-28-28](https://cloud.githubusercontent.com/assets/770092/23633106/2966fd70-02a3-11e7-9cbb-81a0a3bedd48.png)

![screenshot from 2017-03-06 19-28-43](https://cloud.githubusercontent.com/assets/770092/23633107/296cd876-02a3-11e7-8fee-3f0017449d50.png)

**Comment by erinknight242** [comment]
The docs state "Only valid if inline is not set". https://react-bootstrap.github.io/components.html#forms-props-checkbox
