### ISSUE TITLE
Tooltip position doesn't update when content changes

### ISSUE THREAD

**Issue by aaronbeall** [react-bootstrap/react-bootstrap#2503]
I am rendering a tooltip with dynamic content on an `<input>`, boiled down to something like this:

```
const MyInput = ({value, onChange, tooltip}) => (
  <OverlayTrigger position="top" trigger="focus" overlay={(
    <Tooltip id={tooltip}>{tooltip}</Tooltip>
  )}>
    <input type="text" value={value} onChange={onChange} />
  </OverlayTrigger>
);
```

As the `<input>` value changes the `tooltip` changes in response. However, it seems that the tooltip isn't re-positioned.

For example, an initial rendering looks correct:

![image](https://cloud.githubusercontent.com/assets/2973900/23634567/d527b1b4-0298-11e7-9b3a-5907dd6e668f.png)

But once a different tooltip comes through, the position doesn't update and it looks offset:

![image](https://cloud.githubusercontent.com/assets/2973900/23634578/e439aa7c-0298-11e7-8ae4-b8c32117a6c2.png)

I tried putting unique `key` values on the `<Tooltip>` but that didn't help.

A secondary issue is that when the tooltip is empty, it still renders:
![image](https://cloud.githubusercontent.com/assets/2973900/23634658/66774f12-0299-11e7-8b15-05af8bd435bf.png)

How can I hide the tooltip completely, without removing it from the render tree? The problem with removing it from the render tree is that it causes the inner `<input>` to be unmounted and re-mounted, which causes auto-focus-and-select code to run again.

**Comment by aaronbeall** [comment]
Digging around [`<Position>`](https://react-bootstrap.github.io/react-overlays/#position) I found `shouldUpdatePosition` which fixed my primary issue. I don't see anything about `shouldUpdatePosition` in the React Bootstrap documentation, though, that would have helped me out.

Any ideas on the secondary issue?

**Comment by jquense** [comment]
Bootstrap tooltips/popovers don't really support updating on content changes which is way we don't explicitly document that feature (but you are welcome to use it)

In terms of the empty content, thats up to you to handle, I'd not render a tooltip if there is no content, we can't really know if it's empty or not.

**Comment by aaronbeall** [comment]
> In terms of the empty content, thats up to you to handle, I'd not render a tooltip if there is no content, we can't really know if it's empty or not.

Thanks, this is what I came up with:

```
  <OverlayTrigger position="top" trigger="focus" overlay={
    tooltip ? <Tooltip id={tooltip}>{tooltip}</Tooltip> : <span />
  }>
```

I got errors trying to make `overlay={null}` or `undefined`, and like I was saying in my last comment I can't toggle the rendering of `<OverlayTrigger>` or else it unmounts/re-mounts the `<input>` which causes a mess with blur/focus events (maybe there's a workaround for that, but I couldn't see a clean way out.)

**Comment by aaronbeall** [comment]
Actually, that gives me this error: 

> Warning: Unknown props `placement`, `arrowOffsetLeft`, `arrowOffsetTop`, `positionLeft`, `positionTop` on <span> tag. Remove these props from the element.
    in span (created by Unknown)

I guess I can create a component wrapper... 
```
  <OverlayTrigger position="top" trigger="focus" overlay={
    tooltip ? <Tooltip id={tooltip}>{tooltip}</Tooltip> : <Empty />
  }>

const Empty = () => <span />;
```

**Comment by nikolalsvk** [comment]
@jquense Is there a particular reason Bootstrap tooltips/popovers don't really support updating on content changes? 

Will relying on `shouldUpdatePosition` sometimes fail when passing it as props to tooltips/popovers?

**Comment by chillyistkult** [comment]
In my experience `shouldUpdatePosition` on `OverlayTrigger` is working reliable for Tooltips and Popovers with dynamic content.
