### ISSUE TITLE
Invalid properties passed to DIV in Popover

### ISSUE THREAD

**Issue by osbornm** [react-bootstrap/react-bootstrap#2507]
In the popover component properties such as `placement, positionTop, positionLeft, arrowOffsetTop, arrowOffsetLeft` are [being passed to a div node](https://github.com/react-bootstrap/react-bootstrap/blob/775f497ac9fb827355e4361f20176ac458774cfb/src/Popover.js#L95) This will cause React to complain about invalid properties looking something like
```
Warning: Unknown props `placement`, `arrowOffsetLeft`, `arrowOffsetTop`, `positionLeft`, `positionTop` on <div> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop
    in div (created by Popover)
    in Position (created by Overlay)
    in Transition (created by Fade)
    in Fade (created by Overlay)
    in RootCloseWrapper (created by Overlay)
```
It looks like the properties should be [split](https://github.com/react-bootstrap/react-bootstrap/blob/775f497ac9fb827355e4361f20176ac458774cfb/src/Popover.js#L74) with `splitBsPropsAndOmit` and pass those properties in.

**Comment by jquense** [comment]
Hi there. The props are already split out correctly, make sure you are running an up to date version of RB

**Comment by FerPerales** [comment]
@jquense is 0.30.8 the latest version where this is fixed?
