### ISSUE TITLE
add data-toggle attributes to support external js

### ISSUE THREAD

**Issue by sillyslux** [react-bootstrap/react-bootstrap#2510]
These attributes definitely wouldn't hurt and there are situations where users need them.
quote from #2089:
> Is there a strong reason for not rendering data-toggle="dropdown" in DropdownToggle?

I use react-bootstrap with [gatsby.js](https://github.com/gatsbyjs/gatsby). In `development` everything is fine but for `production` it compiles with option [noProductionJavascript](https://github.com/gatsbyjs/gatsby#structure-of-a-gatsby-site) thus eliminating a 500K+ bundle.js and i'm giving up react-bootstrap's js along with it.
Instead i rely on these `data-toggle` attributes in prod and use 5K of a custom built [bootstrap.native](https://github.com/thednp/bootstrap.native/) (2.5K gzipped) and 4K js of my own. In some situations it's enough to add the attribute to the react-bootstrap component, but sometimes it has to be applied to one of it's children and that's where i'm now. I'll probably just copy code to a custom react-bootstrap component... but this issue first, or more of a question than an issue:
What exactly is the reason for `data-toggle` not be included?

**Comment by sillyslux** [comment]
I'm using [this](https://github.com/sillyslux/react-bootstrap/commit/7702b90e6914dc388d9e4d6a19760a21593b4f19) now, it didn't break anything yet.

**Comment by jquense** [comment]
the data attributes are for plain bootstrap. they are hooks for the JS plugins to find DOM nodes. You **should not** be including the bootstrap.js file, it's redundant and a ton of extra code that doesn't get used *at all* by react-bootstrap. react-bootstrap reimplements all the functionality as react components so these Arriba tests don't do anything

**Comment by sillyslux** [comment]
So you say i should use bundle.js? It does include react-bootstraps javascript afterall.

**Comment by jquense** [comment]
I don't know what bundle.js is but you shouldn't have any code that depends on bootstrap data-toggle

**Comment by sillyslux** [comment]
Somewhere else @taion said
> See other issues – if you're using data-toggle, you're doing something quite wrong

Well then, if it's wrong, it's wrong, but in some constellations, there is no other way than doing what you say is wrong.
As i said it already, currently the filesize ratio of using regular react-bootstrap-js to some external js is 100:1 for me and in my case it will even get much worse.

But ultimately all this doesn't have to concern you.
Please just answer one simple question:
> What exactly is the reason for data-toggle (and the likes) not be included?

I mean i can fork, but please tell me why is it such a bad idea to do so?
**What's so wrong about it?**

**Comment by sillyslux** [comment]
Look, i know it's not your problem that gatsby.js (a static site generator) has to include the necessary javascript along with the whole website it creates _in one giant js file_ and maybe future versions will change this, but still, i can't see the point.
If react-bootstrap tries to stay close to the original twitter bootstrap, there's nothing bad in using other js than yours and it should work out of the box and it does and with ScrollSpy working out of the box and with only 5KB of javascript code at all.
Why is it so bad? Do you expect it to break any time soon?
What's your reasoning?
If you're just not in the mood to route these attributes to the correct child elements _in your project_, just say so.

**Comment by sillyslux** [comment]
in fact i'm not that much interested so let me close the discussion with a joke:
A: "you're holding it wrong"
B: "...but i can make calls"
A: "you're still holding it wrong..."

**Comment by jquense** [comment]
I really don't even understand what you are trying to do. you can't use react-bootstrap with the normal bootstrap javascript file. it doesn't make any sense, doesn't work, and duplicates all the code, making your bundle twice as large. 

I'm sorry but I really don't understand your underlying problem as you've explained it but I can guarantee that data attributes will not solve it.

**Comment by MichaelRando** [comment]
jquense, I've been getting cc'ed on this back and forth, and I'm not convinced you're listening to sillyslux's use case. He would like to use react-bootstrap components for gatsby rendering of his site. He wants the style without the javascript from either bootstrap or react-bootstrap. That can work, if you shim in the minimal custom js code to bridge the gap. His shim needs the data-toggle attribute, as that's the facility bootstrap provided for the use case. 

It's one thing to say that use case is unsupported, and it's another to say it's wrong. You haven't made the case for incorrectness, only unsupportedness.

**Comment by sillyslux** [comment]
@jquense you shouldn't be talking about "twice as big bundles" when you don't even know what bundles are...
> I don't know what bundle.js is but you shouldn't have any code that depends on bootstrap data-toggle

/ignore

**Comment by jquense** [comment]
Omg this issue is ridiculous y'all are using words but not saying anything. 

you cannot use anything from react bootstrap without the javascript. it's entirely javascript. react component are only javascript. 

if you want want to use bootstrap styles then just use them. include the bootstrap css and add the classes to html. I don't have time to be told I don't have a clue what I'm talking about about code I wrote, by someone who can't articulate what they even want clearly
