### ISSUE TITLE
Null at e.target.getAttribute("href") - NavItem

### ISSUE THREAD

**Issue by Shadowman4205** [react-bootstrap/react-bootstrap#2511]
I am using the example with Tab.Container, inside it i have got this

```
<NavItem eventKey="test" href="https://www.google.com" onSelect={this.handleSelect} target="_blank">
              <FormattedMessage {...messages.testl} />
</NavItem>
```

```
handleSelect(eventKey, e) {
        let link= e.target.getAttribute("href")
        window.open(href);
}
```
I am getting null for link.
But if i am using just plain next instead of <FormattedMessage {...messages.testl} />, link getting value https://www.google.com. Any solution for this?

**Comment by taion** [comment]
That's really not the right way to handle link clicks. Bind that href directly.

**Comment by Shadowman4205** [comment]
What do you mean using directly? In  <NavItem> href do not  redirect when i am Using Tab.Container?
