### ISSUE TITLE
data is not inserting dynamically 

### ISSUE THREAD

**Issue by shrutiakki** [react-bootstrap/react-bootstrap#2514]
> 
<html>
<head>
<title>Add options dynamically to bootstrap-select</title>
<link href="css/bootstrap.css" rel="stylesheet" />
<link href="css/custom.css" rel="stylesheet" />
<link href="plugins/bootstrap-select/css/bootstrap-select.css" rel="stylesheet" />
<style type="text/css">
.dropdown-menu {
    -webkit-touch-callout: none;
    -webkit-user-select: none;
    -khtml-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
}
 
.dropdown-menu a {
   overflow: hidden;
   outline: none;
}
 
.additem input
{
   border:0;
   margin:-3px;
   padding:3px;
   outline: none;
   color: #000;
   width: 99%;
}
 
.additem:hover input
{
   background-color: #f5f5f5;
}
 
.additem .check-mark
{
   opacity: 0;
   z-index: -1000;
}
 
.addnewicon {
   position: relative;
   padding: 4px;
   margin: -8px;
   padding-right: 50px;
   margin-right: -50px;
   color: #aaa;
}
 
.addnewicon:hover {
   color: #222;
}
</style>
</head>
<body>
<div class="wrapper">
  <header>
    <div class="container">
    <h1 class="col-lg-9">Add options dynamically to bootstrap-select</h1>
    </div>
  </header>
  <div class="container">
    <h5>ADDING LABELS</h5>
<div class="row">
      <div class="col-lg-6">
        <h2>Select Columns</h2>
        <select class="selectpicker" id="select1">
          <option>Mustard</option>
          <option>Ketchup</option>
          <option>Relish</option>
        </select>    
      </div>
      <div class="col-lg-6">
        <h2>Select Type</h2>
        <select class="selectpicker" id="select2">
          <option>Banana</option>
          <option>Peach</option>
          <option>Orange</option>
        </select>    
      </div>
    </div>
</div>
</div>
<footer>
  <div class="container">
   &copy; 
  </div>
</footer>
 
<script src="http://code.jquery.com/jquery.js"></script>
 

<script src="js/bootstrap.js"></script>
<script src="plugins/bootstrap-select/js/bootstrap-select.js"></script>
<script>
$(function() {
  var content = "<input type=text onKeyDown='event.stopPropagation();' onKeyPress='addSelectInpKeyPress(this,event)' onClick='event.stopPropagation()' placeholder='Add item'> <span class='glyphicon glyphicon-plus addnewicon' onClick='addSelectItem(this,event,1);'></span>";
 
  var divider = $('<option/>')
          .addClass('divider')
          .data('divider', true);
          
 
  var addoption = $('<option/>')
          .addClass('additem')
          .data('content', content)
      
  $('.selectpicker')
          .append(divider)
          .append(addoption)
          .selectpicker();
 
});
 
function addSelectItem(t,ev)
{
   ev.stopPropagation();
 
   var txt=$(t).prev().val().replace(/[|]/g,"");
   if ($.trim(txt)=='') return;
   var p=$(t).closest('.bootstrap-select').prev();
   var o=$('option', p).eq(-2);
   o.before( $("<option>", { "selected": true, "text": txt}) );
   p.selectpicker('refresh');
}
 
function addSelectInpKeyPress(t,ev)
{
   ev.stopPropagation();
 
   // do not allow pipe character
   if (ev.which==124) ev.preventDefault();
 
   // enter character adds the option
   if (ev.which==13)
   {
      ev.preventDefault();
      addSelectItem($(t).next(),ev);
   }
}
</script>
</body>
</html>

**Comment by jquense** [comment]
please fix your issue content so that we can read what's happening. thanks!
