### ISSUE TITLE
NavItem is not working properly

### ISSUE THREAD

**Issue by tawsifalam** [react-bootstrap/react-bootstrap#2516]
I have been trying to use NavItem but it is not redirecting to anywhere. The default behavior of an anchor tag is not working properly through NavItem.

**Comment by taion** [comment]
`href` only works if you don't set `onSelect` on the `<Nav>`

**Comment by tawsifalam** [comment]
I used the following code:
`<Navbar.Collapse>`
                        `<Nav pullRight>`
                            `<NavItem href="https://google.com">Google</NavItem>`
                            `<NavItem href="/abouut">About</NavItem>`
                            `<NavItem href="/howItWorks">How it Works</NavItem>`
                            `<NavItem onClick={this.openSignInModal}>Sign in</NavItem>`
                        `</Nav>`
                   `</Navbar.Collapse>`

**Comment by mariangemarcano** [comment]
I'm having the same issue <NavItem eventKey={1}><a href="#menu">Menu</a></NavItem> 
is not working but if I replaced it with regular <a href="#menu">Menu</a> then it works, is this issue fixed somewhere, why the issue is close?
