### ISSUE TITLE
Any plans to create typescript definitions?

### ISSUE THREAD

**Issue by vitaliel** [react-bootstrap/react-bootstrap#2518]
Hello,

Thank you for great components. 

Is there any plan to create typescript definitions?

**Comment by taion** [comment]
https://github.com/react-bootstrap/react-bootstrap/search?q=typescript&type=Issues&utf8=%E2%9C%93

**Comment by vitaliel** [comment]
It is strange typings search does not return it... But it works.
```
yarn add @types/react-bootstrap --dev
```
