### ISSUE TITLE
href in NavItem doesn't work within Navbar.Collapse

### ISSUE THREAD

**Issue by yangaobo** [react-bootstrap/react-bootstrap#2519]
it's the same as this issue https://github.com/react-bootstrap/react-bootstrap/issues/2516

you r right abt `onSelect`, but please, i don't set `onSelect` myself neither
based on my finding, it's because `Navbar.Collapse` will pass `handleCollapse` as `onSelect` to the `NavItem` so the `href` cannot work

it works perfect by removing `.Collapse`

would like to know if it's an expected behaviour or a bug?

**Comment by taion** [comment]
dupe https://github.com/react-bootstrap/react-bootstrap/issues/2365

**Comment by hussainsaify17** [comment]
Agree on removing "collapseOnSelect" prop from the Navbar. Its working absolutely fine.
And thanks yangaobo for resolving this issue.
