### ISSUE TITLE
<DropdownButton/> has "btn-group" class attached

### ISSUE THREAD

**Issue by timhwang21** [react-bootstrap/react-bootstrap#2520]
![screen shot 2017-03-16 at 2 22 07 pm](https://cloud.githubusercontent.com/assets/5831434/24012333/00014644-0a54-11e7-9ab6-a47fc63bf439.png)

Was wondering if this was intended. It cause some minor styling issues for us that were trivial to fix; however, why would this single standalone button have `btn-group` as a class?

If intended, feel free to close as it's not causing a serious issue for us.

**Comment by jquense** [comment]
It's intended, that's the default markup for bootstrap dropdown buttons (see the upstream examples as well http://getbootstrap.com/components/#btn-dropdowns). You can change tho to whatever you like tho by providing a `componentClass` prop on the `<Dropdown>` component (not DropdownButton) to a plain `div` or whatever you like
