### ISSUE TITLE
ButtonToolbar in MenuItem of Dropdown

### ISSUE THREAD

**Issue by ppoisson** [react-bootstrap/react-bootstrap#2521]
Can you nest a ButtonToolbar in a Dropdown MenuItem Component?  Seems it does not want to pick up the styles.
![btntbinmenudd](https://cloud.githubusercontent.com/assets/8300753/24017379/2b9294ae-0a66-11e7-80f3-77d5d8bd6897.jpg)

**Comment by jquense** [comment]
Hi there! By default you really can't nest anything inside a MenuItem, since its a link, and bootstrap doesn't support that use case. You can do it yourself with a custom menu item perhaps but your mileage will vary.

**Comment by ppoisson** [comment]
Just found that in the docs. Will do Thanks for the feedback!
