### ISSUE TITLE
Use hamburger glyphicon for Navbar.Toggle

### ISSUE THREAD

**Issue by pastaclub** [react-bootstrap/react-bootstrap#2523]
Is there any reason why the `Navbar.Toggle` button renders four `<span>` elements to compose its icon, when bootstrap already brings a glyphicon that looks just the same, namely `hamburger`?

IMHO it would be better to use the hamburger glyphicon. Some reasons against the current approach:
- it unneccessarily bloats HTML code
- it is cumbersome to style
- colors are reversed (i.e. the `background-color` property controls the perceived foreground of the icon, because the `<span>` elements make up the transparent parts of the icon)
- some styles (such as text-shadow) do not work at all, again because of the reversed way the icon is composed

**Comment by taion** [comment]
it's what upstream twbs does http://getbootstrap.com/components/#navbar-default
