### ISSUE TITLE
DropdownButton not render ul li, render div

### ISSUE THREAD

**Issue by hakanozkaptan** [react-bootstrap/react-bootstrap#2524]
I want to change DropdownButton and MenuItem's ul li to div div..

**Comment by taion** [comment]
this is covered in the docs

**Comment by hakanozkaptan** [comment]
i checked twice..  its not a good answer.

**Comment by jquense** [comment]
its the third prop: https://react-bootstrap.github.io/components.html#btn-dropdowns-props

**Comment by jquense** [comment]
MenuItems don't allow changing as it's not supported by the css. you'll need to write a custom MenuItem, to which there is a whole doc section

**Comment by hakanozkaptan** [comment]
okey thank you.
