### ISSUE TITLE
set format of a react-bootstrap formcontrol component

### ISSUE THREAD

**Issue by JWDobken** [react-bootstrap/react-bootstrap#2525]
How to set the format of a datetime form component with a default value as the current time?

I would expect something like:

    import { FormControl, FormGroup } from "react-bootstrap";
    ....
    render () {
      var d = new Date();
      return (
        <FormGroup>
          <FormControl type="datetime-local" timeFormat="YYYY-MM-DD HH:mm" defaultValue={d} />
        </FormGroup>)
    }

**Comment by jquense** [comment]
The form components are jsut simple wrappers around native inputs. Native datetime inputs don't allow specifying a format. If you need something more robust or better supported, try react-widgets
