### ISSUE TITLE
Weird tabIndex behavior for Tabs

### ISSUE THREAD

**Issue by kodeebo** [react-bootstrap/react-bootstrap#2527]
For some reason the buttons on the Togglable Tabs have only the active tab-button reachable by keyboard. The tabIndex value is set to 0 for the active tab and -1 for the others. This goes for both standard and custom layout. 

Is there any reason at all for setting tabIndex to -1?

**Comment by jquense** [comment]
yup there is a reason. the spec for tab behavior says that only the active tab should be focusable (you can change tabs with the keyboard arrows). we achieve that by programmatically adjusting the tabIndex

**Comment by kodeebo** [comment]
Thanks for the reply. Which spec are you refering to? I find it very
strange that the Tab component should behave differently from every other
button or nav component. It is also different than how Bootstrap 3 handles
it, where all the tab-buttons are focusable.

For me this breaks the rules of accessibility and makes the component
unusable.

**Comment by jquense** [comment]
> For me this breaks the rules of accessibility and makes the component

It actually implements the rules correctly unlike normal bootstrap. https://www.w3.org/TR/wai-aria-practices-1.1/#tabpanel

In general tho, they behave differently than buttons and navs because a tab list and panel _are_ different components and have different behavior.

**Comment by kodeebo** [comment]
Ok sorry for my ignorance, did not realize the w3 standard defined tab-behaviour like that. Still think it strange, but I anyway see that I can change the behavior by replacing the default role on the Nav.

**Comment by jquense** [comment]
np, tho if you are concerned with accessibility i'd leave the default behavior alone. as wonky as it might seem it's the expected behavior, and likely to work best with AT (at least from my experience)

**Comment by janpauldahlke** [comment]
still relevant ...
