### ISSUE TITLE
Does mounOnEnter doesn't mount canvas elements?

### ISSUE THREAD

**Issue by VagnerDomingues** [react-bootstrap/react-bootstrap#2528]
i've just tested it with react-chart-js, it does not mount before, i have to click the tab so it can mount and draw the canvas, so that the next time i access it, it is already mounted and drawed OK...

i've made a fiddle to test bootstrap working only with DOM elements and it worked perfectly good, even if the graphic is still animating on first chart and you click the second...
check-it-out...
https://fiddle.jshell.net/ksqotcem/3/

i've used the same chart on my react-bootstrap application.. but it doesn't work so pretty

**Comment by jquense** [comment]
should work with svg just fine, without a reproduction tho it's hard to troubleshoot anything
