### ISSUE TITLE
DropdownButton set props to it's DropdownMenu

### ISSUE THREAD

**Issue by coubeatczech** [react-bootstrap/react-bootstrap#253]
Given this code:

    <DropdownButton className="scrollable-menu">
        <MenuItem key={elem}>Element {elem}</MenuItem>
    </DropdownButton>

the props will be set to the `<ButtonGroup />` element.
It would be nice to have the possibility to set properties to the other element `<DropdownMenu />`

**Comment by AlexKVal** [comment]
Superceded by #526
