### ISSUE TITLE
pre-checked Checkbox, tick is persistent.

### ISSUE THREAD

**Issue by raghavgarg1257** [react-bootstrap/react-bootstrap#2531]
Whenever we use:
`<Checkbox checked onChange={ () => { console.log('changed') } }>Some Text</Checkbox>`
It will give pre-checked checkbox(with tick), clicking it will print to console but do not remove the tick from ui.
I have tried options `active={true/false}`, but it doesn't work
Please share if I am missing something.

**Comment by jquense** [comment]
thats how inputs work in React, check out: https://facebook.github.io/react/docs/forms.html#controlled-components

the prop you want is `defaultChecked`

**Comment by raghavgarg1257** [comment]
Thank you sir, for resolving the problem, `defaultChecked` solved my issue.
