### ISSUE TITLE
Both lib and ES are bundled through Webpack

### ISSUE THREAD

**Issue by AoDev** [react-bootstrap/react-bootstrap#2534]
Hello, I recently checked our app bundles with [Webpack bundle analyser](https://github.com/th0r/webpack-bundle-analyzer).  
I have noticed that both lib and ES "folders" get bundled. (Not good.)

I don't do anything special when importing the components.
` import {something} from 'react-bootstrap'`

Currently the default rule in the Webpack config is to bundle `node_modules` into vendor.js.
 
```
  new SplitByPathPlugin([{
    name: 'vendors',
    path: path.join(__dirname, 'node_modules')
  }]),
```

I would expect there to be only the `lib`, I guess.

<img width="756" alt="screen shot 2017-03-29 at 11 49 08" src="https://cloud.githubusercontent.com/assets/1526150/24449123/b10d203a-1476-11e7-8f48-065e77d24c43.png">

For me it isn't clear if it's some bad Webpack config on my side or something that should be done in react-bootstrap. Do you have any insights on this?

**Comment by taion** [comment]
it's bad webpack config on your side; the es build doesn't link into lib

**Comment by jquense** [comment]
i'd imagine maybe that some dep (or your own code) is consuming stuff from `/lib` directly so both are getting included.

**Comment by AoDev** [comment]
@jquense Thanks a lot! you solved the case.

It was not a Webpack problem. I had to wrap a component and import from  `/lib` directly. This was not a problem since only `lib` existed before. But, with both I suppose that Webpack pulls from the ES folder, so I import directly from the `es` folder now.

I am pretty sure it's happening to more people though.
