### ISSUE TITLE
Carousel broke down when tab is backgrounded

### ISSUE THREAD

**Issue by ash-developer** [react-bootstrap/react-bootstrap#2535]
It happens in Safari browser (my version: 10.0.3 (12602.4.8))

1. open page with carousel (example: https://react-bootstrap.github.io/components.html#carousels)
2. go to any other tab
3. wait for a while (I think for carousel period time)
4. go back
5. carousel doesn't work

**Comment by jshaker** [comment]
I'm unable to reproduce this error, how long did you have to wait for?

**Comment by taion** [comment]
Yeah, I don't see this. Most likely it's something else.
