### ISSUE TITLE
OverlayTrigger/Tooltips positioning issues with position:sticky

### ISSUE THREAD

**Issue by SachaG** [react-bootstrap/react-bootstrap#2537]
It seems like `position:sticky` (which is now supported in Chrome) doesn't play nice with tooltip positioning:

![https://d3vv6lp55qjaqc.cloudfront.net/items/0x0u2z3O030u031v3v0V/Screen%20Recording%202017-03-31%20at%2011.56%20AM.gif?X-CloudApp-Visitor-Id=ff1ef413c9d796b30628c5f004e0535a&v=12d4e09e](https://d3vv6lp55qjaqc.cloudfront.net/items/0x0u2z3O030u031v3v0V/Screen%20Recording%202017-03-31%20at%2011.56%20AM.gif?X-CloudApp-Visitor-Id=ff1ef413c9d796b30628c5f004e0535a&v=12d4e09e)

**Comment by jquense** [comment]
you can specify a container prop to position it to the "static" element you want, in this case the sticky side panel

**Comment by SachaG** [comment]
`container={this}` worked great, thanks! How would this work if the tooltip and container weren't in the same component though? Would you just pass `this` down the chain to the `OverlayTrigger` component?

In any case thanks for the fast answer!

**Comment by jquense** [comment]
you don't have to pass a component instance, it also accepts a Dom node if that makes sense
