### ISSUE TITLE
Tab eventKey cannot use zero as value

### ISSUE THREAD

**Issue by grovesNL** [react-bootstrap/react-bootstrap#2539]
In the [Tabs Controlled example](https://react-bootstrap.github.io/components.html#tabs-controlled), if `eventKey={0}` is used in place of the values, the tab and tab content do not update correctly _only when using the arrow keys to navigate between tabs_ (clicking the tab works as expected). I would guess there is a truthy check for `eventKey` somewhere in the key event handlers causing this issue.

Here is a full example using `eventKey={0|1|2}` instead of `eventKey={1|2|3}`:
```
const ControlledTabs = React.createClass({
  getInitialState() {
    return {
      key: 1
    };
  },

  handleSelect(key) {
    alert('selected ' + key);
    this.setState({key});
  },

  render() {
    return (
      <Tabs activeKey={this.state.key} onSelect={this.handleSelect} id="controlled-tab-example">
        <Tab eventKey={0} title="Tab 1">Tab 1 content</Tab>
        <Tab eventKey={1} title="Tab 2">Tab 2 content</Tab>
        <Tab eventKey={2} title="Tab 3" disabled>Tab 3 content</Tab>
      </Tabs>
    );
  }
});

ReactDOM.render(<ControlledTabs />, mountNode);
```

**Comment by grovesNL** [comment]
I believe it's caused by [`child.props.eventKey` being falsy](https://github.com/react-bootstrap/react-bootstrap/blob/7d342c38861d61f3a93893da3d87e768eb621732/src/Nav.js#L164). Is this intentional?

**Comment by taion** [comment]
so that's wrong then – feel free to fix eventKey falsiness checks to be nulliness checks

**Comment by grovesNL** [comment]
@taion Thanks, I'll submit a PR when I have some time
