### ISSUE TITLE
position attributes not working in docs for example: "Popover component in container"

### ISSUE THREAD

**Issue by jeffboyus** [react-bootstrap/react-bootstrap#2540]
Re: [Popover component in container](https://react-bootstrap.github.io/components.html#popovers-in-container) Example

It appears the `position` attributes on the popover are getting overwritten to a calculated value somewhere. 

To reproduce: Put ANY value into `positionLeft` or `positionTop` on the `Popover` component and they do not get reflected in any way in the rendered example code.

A few issue searches on the `Popover` component seem to also have some of the same symptoms being reported. I actually went into the compiled code and console logged out the values of the props at certain points and could not pinpoint where they are getting overwritten from what a user passes in. For this particular example, you can also pass in `left` or `top` style values into the `style` attribute on `Popover` and they are not reflected either.

**Comment by taion** [comment]
dupe https://github.com/react-bootstrap/react-bootstrap/issues/1066
