### ISSUE TITLE
can not only select one on radio form 

### ISSUE THREAD

**Issue by mengfoobar** [react-bootstrap/react-bootstrap#2544]
Seems like the radio form does not support only one radio selection. Thought this would be available by default

![screenshot from 2017-04-06 08-08-58](https://cloud.githubusercontent.com/assets/15919186/24731982/4a8b2ad4-1aa0-11e7-8ee1-56c0642cc72b.png)

**Comment by jquense** [comment]
These are simple wrappers around html radio inputs, so you can group them together by giving them a common `name` prop

**Comment by taion** [comment]
We should probably fix our example though

**Comment by jquense** [comment]
yes definitely

**Comment by mengfoobar** [comment]
@jquense sweet, thanks for the fast response :)
@taion think that will help a lot with some of the confusion :+1:
