### ISSUE TITLE
Request: universal props that only add universal bootstrap classes

### ISSUE THREAD

**Issue by rbalicki2** [react-bootstrap/react-bootstrap#2545]
We use react-bootstrap extensively for basically all components in our internal app. It's a great piece of work! I'd like to get people's feedback on the following, as I'd be willing to look into implementing it if the community is on board.

Problem:
We want to strictly limit the allowable changes to react bootstrap components. For us, that's usually:
* adding bootstrap classes: pull-right, pull-left, text-center, and adding a few custom utility classes
* a few changes through a styles object, which should be turned into utility classes, but haven't been yet.

Unfortunately, this opens to door to other classes and other style changes. It's harder for developers  to intuitively know that `style={{ display: 'inline-block' }}` can be done more cleanly with `className="display-xs-block"`. It's also hard for developers who are looking at one component for inspiration, who see `className="myCustomClass display-xs-block"` that `display-xs-block` is universal and can automatically work in their component.

Proposed solution:
* I'd like to propose universal props, like `display-block`, `pull-left`, etc. that either add classes to a component, or add inline styles. (Adding classes would be preferred, of course.)
* I'd also like to propose adding an escape hatch, similar to `bootstrapUtil.addStyle` that adds a universal prop. We have custom classes that wrap `cursor: pointer`, for example, which are not existing bootstrap classes.
* It's a lot easier to white list props than it is to white list style properties and classNames. I think this will make it easier to enter a codebase and quickly grok best practices, and keep a large code base clean, especially when some engineers contribute only occasionally.

Please let me know what you think! I'd be happy to make a PR with this.

**Comment by taion** [comment]
That doesn't actually make it universal, though, right? What about for e.g. your own components? You'd end up with the same issue of needing to support `pull-right` or whatever in some manner.

**Comment by rbalicki2** [comment]
You're right. I think that supporting pullRight in your own components could be handled by also exposing a `classProps` decorator which can be applied to your own components, eg.

```
import { classProps } from 'react-bootstrap/lib/utils'

// @classProps by itself would add all of the available props
@classProps([ 'pullRight', 'pullLeft' ])
export default class MyComponent {
  static propTypes = {
     // don't include pullLeft and pullRight here
  };
}

**Comment by rbalicki2** [comment]
Alternatively, I could write this as an external library, whose API is as follows:

```
// src/react-bootstrap
import classProps from 'bootstrap-class-props';
import * as reactBootstrap from 'react-bootstrap';

wrappedReactBootstrap = Object.keys(reactBootstrap).reduce(
  (accum, key) => ({ ...accum, bootstrapClassWrapper(reactBootstrap[key] }),
  {}
)
export wrappedReactBootstrap;
```

Or more simply

```
```

```
// myComponent.js
import { Button } from 'src/react-bootstrap';
import bootstrapClassWrapper from 'bootstrap-classes';
// Button has a pullRight, etc. prop

@bootstrapClassWrapper
export default class MyComponent {
}
```

**Comment by taion** [comment]
Hmm, that's a bit more like it. I could see a case for adding that to React-Bootstrap. @react-bootstrap/collaborators, thoughts?

**Comment by jquense** [comment]
it feels like a lot of bonus complexity to add here, but I'd probably be OK with it being a package in the RB org. 

I'm concerned mostly because the existing bsFoo props already cause headaches with pass through and validation, I'd be concerned adding to tgat

**Comment by taion** [comment]
I'm not sure I'd want to add this to all components here by default, if only to avoid the docgen headaches, but it'd be cool to wrap up the use of the TWBS utility classes somehow.

**Comment by jquense** [comment]
yeah I mean I'd like more consistency on these props for components that support it. I don't want to be clever about it tho.

**Comment by rbalicki2** [comment]
Okay, what I can do is (as a first pass, anyway) is to release two repos:

* a repo that wraps components, and converts props to classNames
* a repo that re-exports everything from RBS, but wrapped to accept the props. Thoughts on a good name for this repo?

**Comment by rbalicki2** [comment]
@jquense @taion 
At long last, I've published the repos I said I'd publish :) https://github.com/rbalicki2/react-bootstrap-extended and https://github.com/rbalicki2/react-class-props

I'd love to chat with y'all about next steps!

**Comment by jquense** [comment]
That's neat @rbalicki2 I like the decorator. I also see the value in wrapping and exporting everything, but there are some significant drawbacks to that approach. he major one being that you can't individually require components without also filling your bundle with all of react-bootstrap.

It might be simpler/more flexible to publish _just_ the decorator with the bootstrap classes already configured instead of each component. and let users use it and re export RB components as they need them.

**Comment by rbalicki2** [comment]
Glad you like it!

Re: wrapping and exporting. That's a really good point, thanks. I'll restructure it so that you can `import Panel from 'react-bootstrap-extended/lib/Panel` and get the same smaller size. Didn't think of that.

That's a good idea to extract the bootstrap class map and decorator into its own package. Other projects could benefit from having these prop types, not just RBS.

**Comment by rbalicki2** [comment]
Ok, there's new versions out

**Comment by taion** [comment]
Is there anything more to track on this issue?

**Comment by rbalicki2** [comment]
I published new versions, separated as per @jquense 's comment

https://github.com/rbalicki2/react-class-props  <- the decorator
https://github.com/rbalicki2/bootstrap-class-props <- a function that takes a component and returns a decorated component, as well as a hashmap of propNames => classNames
https://github.com/rbalicki2/react-bootstrap-extended <- the above function applied to react bootstrap

I think it would be ideal if these were included in a "related libraries" section of react-bootstrap's readme. I could also write up a paragraph explanation, if that would help.

**Comment by taion** [comment]
That'd be great, actually. Care to submit a PR?

**Comment by rbalicki2** [comment]
👍 will do

**Comment by taion** [comment]
I think this is resolved now.
