### ISSUE TITLE
Carousel rotation doesn't work when Items are wrapped into components

### ISSUE THREAD

**Issue by emirotin** [react-bootstrap/react-bootstrap#2551]
I have a carousel with a number of repeating items of some non-trivial structure.
Because of that, I've created my own `Item` component that renders the specific `Carousel.Item` with proper children.
When I do this, the carousel auto-sliding doesn't work, nor was I able to make the manual mode work.

My requirements are really simple, I need the auto-sliding, the dotted navigation, and no arrow controls.

Here's the pen that illustrates the problem: https://codepen.io/emirotin/pen/mWNrxY

The first carousel is rendered with the wrapped items. The items are properly rendered in DOM (you can inspect and make sure that is true), but you can't see the carousel because none of the items gets the `active` class.

The 2nd carousel does exactly the same thing but renders `Carousel.Item` as the direct descendant of the `Carousel`.

Can anything be done about this?

Like I understand I can just stop using my fancy wrapper, but it's really convenient (in reality it does also hold more elements and the scoped styles).

**Comment by aardito2** [comment]
If you manually propagate the props Carousel adds to its children to your wrapped Carousel.Item, everything works as expected - see the following pen: https://codepen.io/anon/pen/XRmxjm

This would be easier to accomplish using the object rest/spread Babel plugin.

**Comment by emirotin** [comment]
Makes sense, thank you
