### ISSUE TITLE
Docs should have individual page <title>s (for browser history, etc.)

### ISSUE THREAD

**Issue by anhhn1** [react-bootstrap/react-bootstrap#2554]
This is how it looks like right now:

![reactbs_docs_no_title](https://cloud.githubusercontent.com/assets/916744/24873038/52ccfa2e-1dd4-11e7-9af6-1cd0bf709962.png)

This is poor UX, and improving it would make it up to par with vanilla Bootstrap's docs, as well as the docs of the other UI kits for React.

Working on this issue seems like a good "starter contribution", and it's something I'd like to do myself once I get some confirmation/feedback.

**Comment by jquense** [comment]
go for it. We happily accept PR's 👍

**Comment by fumblehool** [comment]
@jquense I would like to work on this issue. Can you tell me more about the general format of title text?

**Comment by taion** [comment]
I would make it be "React-Bootstrap | <Page>", where "<Page>" matches whatever is in the Navbar.

**Comment by fumblehool** [comment]
@taion  I was thinking about something like this - `<TITLE> | React-Bootstrap`.
So for introduction page, title would be something like this  - `Introduction | React-Bootstrap`
What do you think?

**Comment by taion** [comment]
That's fine too.
