### ISSUE TITLE
How to import specific component from react-bootstrap with Typescript

### ISSUE THREAD

**Issue by iamsaksham** [react-bootstrap/react-bootstrap#2555]
Earlier my app was in `ReactJs + React-bootstrap`. Now I'm using `Typescript + ReactJs + React-bootstrap`

To reduce the size of the app for production Earlier I used to import react-bootstrap components using - `import Button from 'react-bootstrap/lib/Button'`

After adding Typescript it shows the following error

> ERROR in [at-loader] ./components/Hello.tsx:6:8
TS1192: Module ''react-bootstrap/lib/Button'' has no default export.

`Attempt 1`

`import {Button} from 'react-bootstrap/lib/Button'` but in this case Button is undefined.

`Attempt 2`

`import * as Button from 'react-bootstrap/lib/Button'` but in this case another error pops out

> ERROR in [at-loader] ./components/Hello.tsx:54:12
TS2604: JSX element type 'Button' does not have any construct or call signatures.

This error shows error in line `<Button bsStyle="danger" bsClass="glyphicon glyphicon-new-window"></Button>`

Though `import {Button} from 'react-bootstrap'` works fine but this is not desired because it results in increasing the size of the app by 200kbs for me.

How can we import specific component from react-bootstrap using Typescript??

p.s. I've used Typings for react-bootstrap from [react-bootstrap-typescript](https://github.com/react-bootstrap/react-bootstrap-typescript)

**Comment by jquense** [comment]
the first way is correct, the error from typescript is wrong, I don't know why it says that tho I don't use typescript

**Comment by iamsaksham** [comment]
@jquense you mean Attempt 2 i.e. `import * as Button from 'react-bootstrap/lib/Button'`

**Comment by jquense** [comment]
no sorry, the `import Button from 'react-bootstrap/lib/Button` using typescript won't change how the code exports things
