### ISSUE TITLE
Suggestion: add checked classes to the `<div class="checkbox">` node when the value is set

### ISSUE THREAD

**Issue by rbalicki2** [react-bootstrap/react-bootstrap#2557]
I have a problem, and a suggested solution. I'm attempting to hide the checkbox and replace it with a prettier SVG. Right now, I can accomplish that with:

```
.form-group {
  // some slight modifications required to make this work for inline checkboxes
  .checkbox {
    input[type="checkbox"] {
      visibility: hidden;
    }

    label {
      background: (mySvg);
      background-position: left 50%;
      background-repeat: no-repeat;
    }
  }
}
```

However, because the label is a parent of the checkbox, I can't affect the label's styling (i.e. apply a different svg background) based on the checked-ness of the input. So, I see two solutions:

* make the label a peer of the checkbox. Then, we can use `input:checked + label` to conditionally style the label. This seems unnecessarily disruptive. People's CSS will probably break.
* have RBS apply a class of "checked" to the enclosing div.

Is there another solution others can think of? I'd love to hear it!

Happy to make a PR (after I do the other I promised, which will be soon)

Obviously, the same suggestion goes for radio buttons.

Thoughts?

**Comment by rbalicki2** [comment]
So this is a dirty solution, but it works:

```
    input[type="checkbox"] {
      position: absolute;
      left: -100000px;

    }

    input[type="checkbox"]::after {
      content: "O";
      color: red;
      position: relative;
      left: 100000px;
    }

    input[type="checkbox"]:checked::after {
      content: "X";
      color: green;
      position: relative;
      left: 100000px;
    }
```

except instead of changing the content, I'll change the background.

**Comment by jquense** [comment]
Hi there, This isn't really a use case supported by Bootstrap. The components here are pretty simple presentational wrappers around the markup, for your' use case I'd suggest rolling your own Checkbox component. We don't want to add unsupported classes in react-bootstrap though
