### ISSUE TITLE
suggestion: a way to have `<div class="form-horizontal">` as a component, avoiding nested forms

### ISSUE THREAD

**Issue by rbalicki2** [react-bootstrap/react-bootstrap#2558]
I use `Form horizontal`, `FormGroup` and `FormControl` in a very strict way to keep the formatting always predictable. For example, if I have

![14919275878189](https://cloud.githubusercontent.com/assets/4277077/24919278/2ba1b808-1eb1-11e7-80cf-f50cdc97cda0.png)

I would structure that as:

```
<Form horizontal>
  <FormGroup>
    <Col xs={8}>
      <Form horizontal>
        <FormGroup>
          <Col xs={12}><ControlLabel>Preferences</ControlLabel></Col>
        </FormGroup>
        <FormGroup>
          { preferences.map(p => <Col xs={6}><Radio /></Col> }
        </FormGroup>
      </Form>
    </Col>
    <Col xs={4}>{ dropdowns }</Col>
  </FormGroup>
  <FormGroup>{ textareas }</FormGroup>
</Form>
```

The strict rules are that: 1. FormGroup should not be the child of a `<Col>`, or else it has extra padding, so if you need `FormGroup`'s within `<Col>`s, you create an inner form.

The point is that, if you want to reset the `form horizontal` styling, and have `FormGroup` padding work as it's supposed to, you need nested forms. React, of course, complains about a form being a child of a form. Would it be possible to expose an element that is essentially `<div className="form-horizontal">`? I noticed that the `<form>` element itself 

Possible ways

* `<InnerForm horizontal>` or a `<FormStyle>` component
* get rid of `<form>` entirely, as none of the styling depends on it.

Thoughts? I hope this doesn't come off as a niche concern, I think that nesting forms like that is a pretty standard design pattern, and I don't want to add ugly, hacky classes like "reverse-bootstrap-margin"...

**Comment by rbalicki2** [comment]
WOW way to not read the docs. Sorry

**Comment by ScottGuthart** [comment]
@rbalicki2 Which part of the docs addresses this? I'm trying to figure out how to set up a form the same way, with parts that span multiple rows similar to your preferences component above.
