### ISSUE TITLE
pound sign href="#" changes my url unexpected

### ISSUE THREAD

**Issue by rfvyhn** [react-bootstrap/react-bootstrap#2560]
I am using a SPA

route is using `/#/route`

now I have tabs build with react-bootstrap

```
        <Tabs id='stati-tabs'
          bsStyle='tabs'
          activeKey={this.state.tabActive}
          onSelect={this.showTab}>
          <Tab eventKey={1} title={this.t('tab.counts')}></Tab>
          <Tab eventKey={2} title={this.t('tab.users')}></Tab>
          <Tab eventKey={3} title={this.t('tab.hours')}></Tab>
        </Tabs>
```

evenything is good.

but click the Tab will changes my url to `/#`

I tried

`<Tab onClick={e => e.preventDefault()} title={this.t('stati.tab.view_counts')}></Tab>`

`<Tab href={undefined} title={this.t('stati.tab.view_counts')}></Tab>`

`<Tab href={''} title={this.t('stati.tab.view_counts')}></Tab>`

any ways not working.

I have no idea now.

**Comment by taion** [comment]
your router is probably hijacking clicks on `<a>` elements everywhere in your document to do navigation

use a better router

**Comment by zourtney** [comment]
Requesting this be reopened. "Use a better router" is not an acceptable solution for me (slowly adding React to an old Angular 1.x / UI-Router project).

I've created a pull request that passes along a `Nav`'s `href` prop down to the `SafeAnchor`. When combined with the old `href="javascript:void(0)` hack, this component is at least usable.

Example:

```jsx
<Tabs id="test" bsStyle="pills" defaultActiveKey={1} animation={false}>
  <Tab title="Tab 1" eventKey={1} href="javascript:void(0)">Tab 1 content</Tab>
</Tabs>
```

**Comment by zourtney** [comment]
_Revising my previous comment (pull request denied on the grounds of maintaining a simple API --
 totally understandable). So, for posterity's sake:_

If your hash-router is prematurely navigating, [recreate the component tree](https://react-bootstrap.github.io/components.html#tabs-with-dropdown), then create a `NavItem` with a custom `href` prop. The value doesn't seem to matter, so long as it's not falsy.

For example:

```jsx
<Tab.Container id='MyTabContainer' defaultActiveKey={0}>
  <Row className='clearfix'>
    <Col sm={12}>
      <Nav bsStyle='tabs'>
        <NavItem eventKey={0} href='javascript:void(0)'>
          {m.name}
        </NavItem>
      </Nav>
    </Col>
    <Col sm={12}>
      <Tab.Content animation={false}>
        <Tab.Pane key={m.promoGroupId} eventKey={0}>
          {/* content */}
        </Tab.Pane>
      </Tab.Content>
    </Col>
  </Row>
</Tab.Container>
```
