### ISSUE TITLE
Is it possible to possible to customize navbarToggle

### ISSUE THREAD

**Issue by dinesh-pallapa** [react-bootstrap/react-bootstrap#2562]
I am trying to customize NavbarToggle component , Is it possible to overriding this methods.

       return (
         <button {...buttonProps}>
            <span className="sr-only">Toggle navigation</span>
            <span className="icon-bar" />
            <span className="icon-bar" />
            <span className="icon-bar" />
         </button>
      );

Example 
   
         return (
           <button {...buttonProps}>
              <span className="sr-only">Toggle navigation</span>
              <span className="custom-icon" />
              <span className="custom-icon" />
              <span className="custom-icon" />
           </button>
        );

**Comment by taion** [comment]
per the docs, just give it `children`

**Comment by dinesh-pallapa** [comment]
I understood here

**Comment by maxdonetsk** [comment]
This is my approach:
`<Navbar.Toggle children={this._getNavbarToggleIcon()} onClick={this._onNavbarToggleClick} />`

```  _onNavbarToggleClick() {
    HeaderActionCreators.changeNavbarToogleIcon(this.state.isNavbarCollapsed);
  }```

```
  _getNavbarToggleIcon() {
    return this.state.isNavbarCollapsed ? (
      <div>icon1</div>
    ) : (
      <div>icon2</div>
    );
  }
```
