### ISSUE TITLE
Open file dialog in MenuItem

### ISSUE THREAD

**Issue by elefantino** [react-bootstrap/react-bootstrap#2563]
I use need to put one menu item to the Dropdown component that will act as file input. 
File input is basic:
```
<ControlLabel >Load file <FormControl onChange={this.getFileContent} type="file" /></ControlLabel>
```
If I put it inside MenuItem element, it doesn't open a file selection dialog. In any other place it works normally. It also works in a `<li><a>{fileInputComponent}</a></li>` structure

**Comment by taion** [comment]
see the custom dropdown menu example

**Comment by elefantino** [comment]
For those who are also interested in the issue, there is a way to avoid such misbehaviour. If you set a 'href' prop to something that is not just '#', null or '', it will work correctly
