### ISSUE TITLE
[Pagination] Enable activeClassName and disabledClassName configuration

### ISSUE THREAD

**Issue by jnwelzel** [react-bootstrap/react-bootstrap#2564]
I'm trying to use `Pagination` component with CSS modules in my application, but there's no way to let the component know the "modularized" class names. If there was a way to let the component know these class names it would just work. Currently we can only pass the `bsClass` name.

**Comment by taion** [comment]
Feel free to submit a PR, but this would be entirely superseded by the planned https://github.com/react-bootstrap/react-bootstrap/issues/1758 regardless
