### ISSUE TITLE
Why export default bsClass instead of Button?

### ISSUE THREAD

**Issue by iamsaksham** [react-bootstrap/react-bootstrap#2565]
Is there any specific reason for doing
    ...
    ...
    export default bsClass('btn',
      bsSizes([Size.LARGE, Size.SMALL, Size.XSMALL],
        bsStyles(
          [...Object.values(State), Style.DEFAULT, Style.PRIMARY, Style.LINK],
          Style.DEFAULT,
          Button
        )
      )
    )
instead of export default Button?

This is done with all of the components. This makes it tough to import individual components from react-bootstrap while using Typescript as valid import in Typescript looks like

`import {Button} from 'react-bootstrap/lib/Button'`

But as Button is not exported so when importing Button comes out as undefined. Even `import * as Button from 'react-bootstrap/lib/Button'` does not do the job of proper importing.

I understand its not the best place to ask questions and this queue is for issues. I tried asking the [same question](http://stackoverflow.com/questions/43385638/react-bootstrap-why-export-default-bsclass-instead-of-button) on StackOverflow but no response yet.

**Comment by jquense** [comment]
It is exporting the Button. Your imports are wrong even in typescript, there is no named export in these files only the default export. Your are trying to import a named export that doesn't exist. Please read the getting started page for more details on importing individual components
