### ISSUE TITLE
Multiple Deprecation warnings

### ISSUE THREAD

**Issue by volure** [react-bootstrap/react-bootstrap#2566]
I realize these errors may be getting fixed in newer releases, as deprecation is something that works for now, but will go away later down the road.
What I would like to know, is if there is something I can do to the files that will quell this warning so it does not fill my log.

Perhaps also something put into the readme to enable people to quiet the logs from alerting about every thing that works but may go away in the library..

Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.

printWarning @ warning.js:36
warning @ warning.js:60
get @ React.js:95
(anonymous) @ PanelGroup.js:50
__webpack_require__ @ bootstrap 9d190c2…:555
fn @ bootstrap 9d190c2…:86
(anonymous) @ Accordion.js:25
__webpack_require__ @ bootstrap 9d190c2…:555
fn @ bootstrap 9d190c2…:86
(anonymous) @ index.js:6
__webpack_require__ @ bootstrap 9d190c2…:555
fn @ bootstrap 9d190c2…:86
(anonymous) @ Nav.js:4
__webpack_require__ @ bootstrap 9d190c2…:555
fn @ bootstrap 9d190c2…:86
(anonymous) @ App.js:4
__webpack_require__ @ bootstrap 9d190c2…:555
fn @ bootstrap 9d190c2…:86
(anonymous) @ index.js:3
__webpack_require__ @ bootstrap 9d190c2…:555
fn @ bootstrap 9d190c2…:86
(anonymous) @ bootstrap 9d190c2…:578
__webpack_require__ @ bootstrap 9d190c2…:555
(anonymous) @ bootstrap 9d190c2…:578
(anonymous) @ bootstrap 9d190c2…:578
warning.js:36 Warning: Uncontrolled(Dropdown): React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.
printWarning @ warning.js:36
warning @ warning.js:60
createClass @ ReactClass.js:628
uncontrollable @ createUncontrollable.js:52
(anonymous) @ Dropdown.js:417
__webpack_require__ @ bootstrap 9d190c2…:555
fn @ bootstrap 9d190c2…:86
(anonymous) @ index.js:66
__webpack_require__ @ bootstrap 9d190c2…:555
fn @ bootstrap 9d190c2…:86
(anonymous) @ Nav.js:4
__webpack_require__ @ bootstrap 9d190c2…:555
fn @ bootstrap 9d190c2…:86
(anonymous) @ App.js:4
__webpack_require__ @ bootstrap 9d190c2…:555
fn @ bootstrap 9d190c2…:86
(anonymous) @ index.js:3
__webpack_require__ @ bootstrap 9d190c2…:555
fn @ bootstrap 9d190c2…:86
(anonymous) @ bootstrap 9d190c2…:578
__webpack_require__ @ bootstrap 9d190c2…:555
(anonymous) @ bootstrap 9d190c2…:578
(anonymous) @ bootstrap 9d190c2…:578

warning.js:36 Warning: Uncontrolled(Dropdown): React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.

printWarning	@	warning.js:36
warning	@	warning.js:60
createClass	@	ReactClass.js:628
uncontrollable	@	createUncontrollable.js:52
(anonymous)	@	Dropdown.js:417
__webpack_require__	@	bootstrap 9d190c2…:555
fn	@	bootstrap 9d190c2…:86
(anonymous)	@	index.js:66
__webpack_require__	@	bootstrap 9d190c2…:555
fn	@	bootstrap 9d190c2…:86
(anonymous)	@	Nav.js:4
__webpack_require__	@	bootstrap 9d190c2…:555
fn	@	bootstrap 9d190c2…:86
(anonymous)	@	App.js:4
__webpack_require__	@	bootstrap 9d190c2…:555
fn	@	bootstrap 9d190c2…:86
(anonymous)	@	index.js:3
__webpack_require__	@	bootstrap 9d190c2…:555
fn	@	bootstrap 9d190c2…:86
(anonymous)	@	bootstrap 9d190c2…:578
__webpack_require__	@	bootstrap 9d190c2…:555
(anonymous)	@	bootstrap 9d190c2…:578
(anonymous)	@	bootstrap 9d190c2…:578

**Comment by jquense** [comment]
Duplicate

**Comment by volure** [comment]
Duplicate where ?

**Comment by volure** [comment]
More to the point, is there a solution for getting rid of the deprecations within the react-bootstrap component...

**Comment by jquense** [comment]
https://github.com/react-bootstrap/react-bootstrap/issues/2550
