### ISSUE TITLE
'col' className on Col component

### ISSUE THREAD

**Issue by jwulf** [react-bootstrap/react-bootstrap#2567]
Hey, I'm aware of https://github.com/react-bootstrap/react-bootstrap/issues/2273.

Is there a strong reason to not put a 'col' className on the Col component? We just wrote a HoC to add it, and we're wondering if we're `<DoingItWrong />`, or if it's worth a PR to get the base className on the component?

**Comment by jquense** [comment]
The main reason is that it's not a bootstrap class. You are free to add it but I don't think we will here as it's not a part of bootstrap
