### ISSUE TITLE
ButtonToolbar has some unknown props

### ISSUE THREAD

**Issue by lyssdod** [react-bootstrap/react-bootstrap#2568]
I've got this in my console:
Warning: Unknown props `active`, `activeKey`, `activeHref` on <div> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop
    in div (created by ButtonToolbar)

My code is just 
```
<ButtonToolbar>
    <Button>Test</Button>
</ButtonToolbar>
```

**Comment by dozoisch** [comment]
What's the parent of ButtonToolbar?

**Comment by lyssdod** [comment]
Navbar.Collapse

**Comment by taion** [comment]
you're trying to nest a `<ButtonToolbar>` under a `<Nav>` or something; that doesn't make sense, don't put things that aren't like `<NavItem>`s in there
