### ISSUE TITLE
I want to pass some additional prop and use that in the modal, I can able to do that, But it throws "Unknown prop" Warning

### ISSUE THREAD

**Issue by arunkumarpalaniappan** [react-bootstrap/react-bootstrap#2569]
Hi,

I'm trying to pass some extra props and access that inside Modal, I can do it, But it throws "Invalid Prop Error"

![image](https://cloud.githubusercontent.com/assets/11667975/25088021/b721e842-2390-11e7-9d77-e24fa4df96ce.png)

![image](https://cloud.githubusercontent.com/assets/20218067/25087940/4245158a-2390-11e7-893e-27c11a90ccaf.png)

![image](https://cloud.githubusercontent.com/assets/20218067/25087949/4ad21900-2390-11e7-8323-e9ffed930d71.png)

**Comment by ddelrio1986** [comment]
Are you using a HoC?

**Comment by arunkumarpalaniappan** [comment]
Hi @ddelrio1986  ,

I think using HoC for a simple modal will make the application too complicated..

But, If there is no option except HoC, I will use it..


I'm just trying to show a modal with sending custom props to that modal....

**Comment by taion** [comment]
you're forwarding in extra props from your parent; `ElementId` is not a react bootstrap prop. fix this on your end.
