### ISSUE TITLE
modal box appears but is transparent

### ISSUE THREAD

**Issue by babycannotsay** [react-bootstrap/react-bootstrap#2570]
const { Button, Modal, FormGroup, FormControl, ControlLabel } = ReactBootstrap
	class List extends React.Component {
	  constructor() {
	    super()
	    this.state = {
	      recipes: [],
	      showModal: false
	    }
	    this.open = this.open.bind(this)
	    this.close = this.close.bind(this)
	    this.add = this.add.bind(this)
	  }
	  close() {
	    this.setState({
	      showModal: false
	    })
	  }
	  add() {
	    this.setState({
	      showModal: false
	    })
	  }
	  open() {
	    this.setState({
	      showModal: true,
	    })
	    console.log(this.state.showModal)
	  }
	  render() {
	    return (
	      <div>
	        <Button bsStyle='primary' onClick={this.open}>Add Recipe</Button>
	        <Modal show={this.state.showModal} onHide={this.close}>
	          <Modal.Header closeButton>
	            <Modal.Title>Add a recipe</Modal.Title>
	          </Modal.Header>
	          <Modal.Body>
	            <form>
	              <FormGroup  controlId='formControlText'>
	                <ControlLabel>Recipe</ControlLabel>
	                <FormControl placeholder='Recipe Name'></FormControl>
	              </FormGroup>
	            </form>
	          </Modal.Body>
	          <Modal.Footer>
	            <Button bsStyle='secondary' onClick={this.close}>Close</Button>
	            <Button bsStyle='primary' onClick={this.add}>Add Recipe</Button>
	          </Modal.Footer>
	        </Modal>
	      </div>
	    )
	  }
	}
	
	ReactDOM.render(
	  <List/>,
	  document.querySelector('.container')
	)

The above is my code ..I got stuck for a long time in this issue.Why is the popover transparent when I clicked the 'Add Recipe' button?

**Comment by babycannotsay** [comment]
Maybe I know what happened. I wrote the code in codepen. The class of fade's opacity is 0. Comparing to the example in [Basic example]( https://react-bootstrap.github.io/components.html#overlays),  it didn't have the `.fade.in`.

**Comment by DNAngeluS** [comment]
@babycannotsay I don't get how you end up solving it, I think I'm having the same issue. Did you add the class .fade.in to you modal component???
