### ISSUE TITLE
Doc component examples should have import paths

### ISSUE THREAD

**Issue by kellenp** [react-bootstrap/react-bootstrap#2573]
In examples with nearly any other React UI component library, ex:

[MaterialUI](http://www.material-ui.com/#/components/app-bar)
[Flexbox Grid](https://github.com/roylee0704/react-flexbox-grid#usage)
[React Grid Gallery](https://github.com/benhowell/react-grid-gallery#quick-and-dirty-start)

The import method is displayed - on your react-bootstrap docs, it only exists in the [Getting started](https://react-bootstrap.github.io/getting-started.html) page, which can be rather confusing. I realize that this may be because there are 2 pathways for importing components, either the CommonJS way or ES6 imports, but choosing one prefered way for the docs would be nice so users can see at the top all the components that go into a demo, rather than having to infer them by the elements in the example.

I'd like to propose that examples in components should have their import statements at the top, so

```js
const navbarInstance = (
  <Navbar>
    <Navbar.Header>
      <Navbar.Brand>
        <a href="#">React-Bootstrap</a>
      </Navbar.Brand>
    </Navbar.Header>
    <Nav>
      <NavItem eventKey={1} href="#">Link</NavItem>
      <NavItem eventKey={2} href="#">Link</NavItem>
      <NavDropdown eventKey={3} title="Dropdown" id="basic-nav-dropdown">
        <MenuItem eventKey={3.1}>Action</MenuItem>
        <MenuItem eventKey={3.2}>Another action</MenuItem>
        <MenuItem eventKey={3.3}>Something else here</MenuItem>
        <MenuItem divider />
        <MenuItem eventKey={3.4}>Separated link</MenuItem>
      </NavDropdown>
    </Nav>
  </Navbar>
);

ReactDOM.render(navbarInstance, mountNode);

```

becomes

```js
import ReactDOM from 'react-dom';
import { Navbar, Nav, NavDropdown } from 'react-bootstrap';

const navbarInstance = (
  <Navbar>
    <Navbar.Header>
      <Navbar.Brand>
        <a href="#">React-Bootstrap</a>
      </Navbar.Brand>
    </Navbar.Header>
    <Nav>
      <NavItem eventKey={1} href="#">Link</NavItem>
      <NavItem eventKey={2} href="#">Link</NavItem>
      <NavDropdown eventKey={3} title="Dropdown" id="basic-nav-dropdown">
        <MenuItem eventKey={3.1}>Action</MenuItem>
        <MenuItem eventKey={3.2}>Another action</MenuItem>
        <MenuItem eventKey={3.3}>Something else here</MenuItem>
        <MenuItem divider />
        <MenuItem eventKey={3.4}>Separated link</MenuItem>
      </NavDropdown>
    </Nav>
  </Navbar>
);

ReactDOM.render(navbarInstance, mountNode);

```

**Comment by jquense** [comment]
Unlike those other examples, the RB examples are all editable in the browser, where modules aren't actually supported. I agree that it's a bit confusing but its a technical limitation and we feel that having examples you can tweak and edit is more valuable than ones that are static but show the import statements. If you can figure out a way to get both we'd happily take a PR

**Comment by kellenp** [comment]
I've been going over components and sample code all day, but I had no idea nor expectation that I'd be able to edit the example code - awesome feature, it could certainly get more prominence.
