### ISSUE TITLE
Guide React Bootstrap

### ISSUE THREAD

**Issue by DaoHuyTuan** [react-bootstrap/react-bootstrap#2574]
it't very hard to use your component , with a newbie very hard to understand what should do 
and it's very little guide video about react bootstrap so very hard i use 
or may be just because i newbie so i feel that 
you guys doing greate and hope you guys have more tutorial about this 
and have any one can help me to understand and use this ??

**Comment by jquense** [comment]
Have you read the getting started guide or looked at the numerous editable examples on the documentation site?
