### ISSUE TITLE
Build error with new release

### ISSUE THREAD

**Issue by jwohlfert23** [react-bootstrap/react-bootstrap#2575]
For every component, I'm getting the following error 
```
ERROR in ./~/react-bootstrap/es/NavbarHeader.js
Module not found: Error: Can't resolve 'prop-types' in '/var/app/node_modules/react-bootstrap/es'
 @ ./~/react-bootstrap/es/NavbarHeader.js 8:0-35
 @ ./~/react-bootstrap/es/Navbar.js
 @ ./~/react-bootstrap/es/index.js
```

**Comment by githubdoramon** [comment]
same here

**Comment by luisfuertes** [comment]
+1

**Comment by am80l** [comment]
+1

**Comment by veltman** [comment]
+1, would be great to get a 0.30.10 release with that fix, everything breaks in the meantime

**Comment by jquense** [comment]
folks we will push a release as soon as someone has a moment. In the meantime run `npm i prop-types` yourself and it'll work

**Comment by AryanJ-NYC** [comment]
`warning.js:36 Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.`

Is this a related error? Even after install prop-types, I get this warning. Nothing pops up.

**Comment by jquense** [comment]
no thats related to other libraries included react-overlays.
