### ISSUE TITLE
Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.

### ISSUE THREAD

**Issue by clairtonluz** [react-bootstrap/react-bootstrap#2580]
"react": "^15.5.4",
"react-dom": "^15.5.4",
"react-materialize": "^0.18.1"

**Comment by taion** [comment]
see other issues

**Comment by ruzrulit** [comment]
just update react-bootstrap, they fixed it

**Comment by aleybovich** [comment]
Which version of react-bootstrap has the fix? I am on v 0.31.0 and I still see the warning

**Comment by abobwhite** [comment]
@aleybovich I just upgraded to 0.31.2 and it's fixed for me
