### ISSUE TITLE
Heavy dependency on OverlayMixin - how to use Portals

### ISSUE THREAD

**Issue by andpor** [react-bootstrap/react-bootstrap#2581]
We have a heavy dependency on OverlayMix from an old version of bootstrap. Most of the overlays - popover, modals, tooltips are rendered in the topmost/parent page with smaller child components generating callbacks to parent on certain events happening within them. The popovers and modals are rendered only after some business logic executes so straight UI trigger is not sufficient here. OverlayMixin used to work great but I see it is gone - comment says use Portals instead. But except for one trivial example in react-overlays I can't see any other sample code. How would one transition from OverlayMixin to Portal (accounting for the logic I have described above)?

**Comment by jquense** [comment]
Hi there. It's not clear from your description why the Portal wouldn't work as a replacement. In terms of examples tho I'd look at the overlay and modal code for more complex usages. Maybe if you can distill an example in a gist or code that demonstrates something that doesn't migrate well we can help out as well.
