### ISSUE TITLE
xsHidden and xsOffset with Bootstrap 4

### ISSUE THREAD

**Issue by marcogreselin** [react-bootstrap/react-bootstrap#2591]
Hello, I copied and pasted the code in the example [here](https://react-bootstrap.github.io/components.html#grids-basic) however `xsHidden` and `xsOffset` don't seem to work with Bootstrap 4. Is Bootstrap 4 at all supported? I'm using Bootstrap 4.0.0-alpha.6 downloaded via npm. Thanks.

**Comment by jquense** [comment]
Bootstrap 4 is not currently supported, see the related issue about v4 support

**Comment by marcogreselin** [comment]
Thanks @jquense! Would be helpful to write a note on the home page of the project to avoid misunderstanding especially when I read: 
> React-Bootstrap doesn't depend on a very precise version of Bootstrap
