### ISSUE TITLE
Dropdown Title

### ISSUE THREAD

**Issue by darrylmack** [react-bootstrap/react-bootstrap#2592]
Using the Dropdown in a <UserNav> component for a user menu. The 'title tag dynamically populated with this.props.userData.fullName. Everything works including have the title populated with the logged-in user's name but in the console I'm getting the following error message:
 'The prop `title` is marked as required in `DropdownButton`, but its value is `undefined`.'

**Comment by jquense** [comment]
Not  sure what problem your raising here... PropTypes are validated when you declare the element so the title has to be included then

**Comment by jimyaghi** [comment]
The issue may be a bug in PropTypes. A warning is displayed, despite a title being provided and despite the fact that react-bootstrap actually renders the dropdown correctly.

**Comment by darrylmack** [comment]
Yes, that's the issue. I'm providing a title via `props` but still getting the error message. The dropdown renders correctly.

**Comment by lindslev** [comment]
Getting the same issue.. passing title as a prop to `DropdownButton` but still seeing

```Warning: Failed prop type: The prop 'title' is marked as required in 'Uncontrolled(Dropdown)', but its value is 'undefined;.
    in Uncontrolled(Dropdown) (created by DropdownButton)```

**Comment by lindslev** [comment]
Wouldn't this line https://github.com/react-bootstrap/react-bootstrap/blob/master/src/DropdownButton.js#L27 mean `title` is excluded from `dropdownProps`?

**Comment by taion** [comment]
@jimyaghi @darrylmack If you're setting `title` via `React.cloneElement`, you might get this warning, as React checks props at element creation time.

@lindslev `<Dropdown>` doesn't take a `title` prop and doesn't list it in `propTypes`: https://github.com/react-bootstrap/react-bootstrap/blob/v0.31.3/src/Dropdown.js. Not clear where that error is coming from, but it doesn't look like it's something here.

**Comment by lindslev** [comment]
@taion do these images help you? i'm p stumped


<img width="867" alt="screen shot 2017-09-13 at 2 50 11 am" src="https://user-images.githubusercontent.com/5532139/30363478-5571c276-982e-11e7-886a-5ce0f131f47e.png">


<img width="939" alt="screen shot 2017-09-13 at 2 49 55 am" src="https://user-images.githubusercontent.com/5532139/30363477-556cf976-982e-11e7-9434-b4ca7107af30.png">

**Comment by gnapse** [comment]
A different issue, but why the title is required for a DropdownButton? I think is legit to want to render a dropdown button where the button shows only the caret. And this library's DropdownButton already works ok without a title, except for the warning about the prop being required.
