### ISSUE TITLE
Remove React.PropTypes and React.createClass

### ISSUE THREAD

**Issue by ezhlobo** [react-bootstrap/react-bootstrap#2595]
In react@15.5.0 there are two new warnings about `React.PropTypes` and `React.createClass`. They will be removed in react@16.

https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html

I'm already on this version of react and get many warnings in browser's console and in testing environment. 

Are you going to do anything with it?

**Comment by jquense** [comment]
please search before opening new issues

**Comment by ezhlobo** [comment]
@jquense sorry, have not found any related issue. But now I checked closed issues and I found. It's not obvious to close all issues related to it while the problem exists, though.

I suggest to reopen the first closed issue where you promised to handle the problem.

**Comment by jquense** [comment]
The issues are closed because the PR's fixing them have been merged

**Comment by ezhlobo** [comment]
@jquense well, could you tell me what version should I use? I'm on 0.30.10 and still see the error. Thanks in advance.

**Comment by ezhlobo** [comment]
@jquense well, thank you very much for your patience, it was resolved by upgrading to v0.31.
