### ISSUE TITLE
v0.31.0 still uses React.createClass via uncontrollable

### ISSUE THREAD

**Issue by jochenberger** [react-bootstrap/react-bootstrap#2597]
The 0.31.0 UMD bundle still references `React.createClass`. (See https://unpkg.com/react-bootstrap@0.31.0/dist/react-bootstrap.js) This comes from the uncontrollable package.
I suspect something went wrong with the build, because if I build v0.31.0 locally, it doesn't use `React.createClass`.

**Comment by ezhlobo** [comment]
Waiting while @jquense will close this issue :D.

#2596
#2595
#2594
#2593
...

**Comment by jochenberger** [comment]
@ezhlobo 
See https://github.com/react-bootstrap/react-bootstrap/blob/v0.31.0/package.json#L127
I suggest, you read this issue again. :-)

**Comment by ezhlobo** [comment]
@jochenberger good, v0.31 solved my issue. Actually I was getting the same issue as you posted but in the npm package.

**Comment by azotova** [comment]
I get the same error message from line 8198 here: https://cdnjs.cloudflare.com/ajax/libs/react-bootstrap/0.31.0/react-bootstrap.js  It comes from uncontrollable, although the code in v. 4.1.0 of uncontrollable (file createUncontrollable.js) is different.  It looks like the build is using an earlier version of uncontrollable for some reason.

**Comment by taion** [comment]
I wonder if we just need to rebuild...

**Comment by jochenberger** [comment]
I think so.

**Comment by jochenberger** [comment]
Could you republish a new build as 0.31.1, or are you anywhere near 0.32.0?

**Comment by taion** [comment]
Released v0.31.1. Thanks for the reminder.

**Comment by jochenberger** [comment]
Yes, that did it, thanks!

**Comment by jochenberger** [comment]
Unfortunately, the bundle sizes increased from 0.31.0 to 0.31.1:
0.31.0:
```
react-bootstrap.js:     620400
react-bootstrap.min.js: 207357
```
0.31.1:
```
react-bootstrap.js:     628490
react-bootstrap.min.js: 210264
```
I wonder if that's expeted.

**Comment by taion** [comment]
At least part of that is from our adding the toggle button components.

We strongly recommend not using the UMD bundles and instead using a bundler, and importing the specific modules that you need, or else using a Babel plugin to rewrite your imports appropriately.

**Comment by taion** [comment]
`CloseButton` rather
