### ISSUE TITLE
Panel accordion documentation unclear for collapsed by default

### ISSUE THREAD

**Issue by woot4moo** [react-bootstrap/react-bootstrap#2599]
The documentation for the Panel (https://react-bootstrap.github.io/components.html#panels-props) is unclear on demonstrating how to have a Panel collapsed by default.  The following code demonstrates a Panel that will not start collapsed by default:
```

<Panel header="my header" bsStyle="info">
       Some words
</Panel>
```

The code that is necessary for a Panel to start collapsed is similar, but not explicitly defined in the docs.

```
<Panel header="my header" bsStyle="info" eventKey="someKey>
       Some words
</Panel>
```

It would be great if the documentation could be updated to explicitly call out the necessity of the eventKey property for collapsed by default Panel's

**Comment by jquense** [comment]
the prop for setting the default collapsed state is `defaultExpanded`

**Comment by woot4moo** [comment]
@jquense  Actually supplying `defaultExpanded` without `eventKey` does nothing.

**Comment by jquense** [comment]
that isn't right. I just tried it on the docs site 

```jsx
<Panel header="my header" defaultExpanded collapsible>
       Some words
</Panel>
```

works as expected

**Comment by meghna-saxena** [comment]
Has this feature no longer in use with the updated react-bootstrap version?

**Comment by taion** [comment]
There was a regression in the latest version.

**Comment by taion** [comment]
See https://github.com/react-bootstrap/react-bootstrap/issues/2926
