### ISSUE TITLE
FormControl type="number" -> decimal number support

### ISSUE THREAD

**Issue by destromas1** [react-bootstrap/react-bootstrap#2603]
```
<PDInputWrapper controllerId="pdNumeric" labelText={props.label} meta={props.meta}
                        tooltip={props.tooltip}>
            <InputGroup>
                <FormControl type="number" step={0.1} value={props.input.value}/>
       </InputGroup>            
</PDInputWrapper>
```

I tried ```step={0.1}``` or ```step="0.1"```
Does not work

Is there any bug here ? Any suggestion ?
Thanks in advance!

**Comment by jquense** [comment]
The FormControl inputs are thin, logic-less wrappers around native html inputs. So if it's not work it's either a limitation of hte input itself or in how React handles the input. I'm not sure which one it is :/ but it's not a react-bootstrap issue at least.

**Comment by taion** [comment]
You need to have a correct `onChange` handler if you're setting `value`
