### ISSUE TITLE
Please run a package release

### ISSUE THREAD

**Issue by benkaiser** [react-bootstrap/react-bootstrap#2604]
I see you have implemented the fix for `react-overlays` in the `next` branch, however a release has yet to be done. Currently if I just install the package from npm, then try and use `MenuItem` it breaks completely.

Please do a release so that all new users who just 'install the current version' don't face a broken package.

**Comment by jquense** [comment]
It was released a week ago

**Comment by benkaiser** [comment]
Interesting... Wonder why it was broken then.

I ended up just using an old version form npm, but I'll try update back to latest and see if it works.
