### ISSUE TITLE
Calling proptypes validators directly

### ISSUE THREAD

**Issue by IamTheHttp** [react-bootstrap/react-bootstrap#2605]
Hey.

We've been using React-Bootstrap throughout our app, and we've started getting these errors : 

Warning: Failed Context Types: Calling PropTypes validators directly is not supported by the `prop-types` package. Use `PropTypes.checkPropTypes()`

A specific Component that triggers that is `FormControl`

Any ideas?

**Comment by taion** [comment]
Make sure you're not somehow on a very old version – we've taken out all the code that directly calls prop type validators a while ago.

**Comment by IamTheHttp** [comment]
I'm using version 0.31.0(which seems like the latest at this time) with React 15.1.0

Here's the bare minimum code that reproduces this issue : 

```
import { FormControl } from 'react-bootstrap';
import React from 'react';
import ReactDOM from 'react-dom';
ReactDOM.render(
  <FormControl/>,
  document.getElementById('app')
);
```

I'm getting two specific errors with the above code: 

Warning: Failed propType: Calling PropTypes validators directly is not supported by the `prop-types` package. Use `PropTypes.checkPropTypes()` to call them.

Warning: Failed Context Types: Calling PropTypes validators directly is not supported by the `prop-types` package. Use `PropTypes.checkPropTypes()` to call them.

**Comment by SergioGeeK7** [comment]
I'm getting the same error here...
   "react": "^15.5.4",
    "react-bootstrap": "^0.31.0",
    "react-dom": "^15.5.4",

 help please ?

**Comment by SteveYurka** [comment]
This issue will also occur, if you are mixing dev and prod versions of reactjs and react-bootstrap...

eg: This will cause the above issue to occur:
<script src="https://cdnjs.cloudflare.com/ajax/libs/react/15.6.1/react.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/react/15.6.1/react-dom.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/react-bootstrap/0.31.0/react-bootstrap.min.js"></script>

While this will not:
<script src="https://cdnjs.cloudflare.com/ajax/libs/react/15.6.1/react.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/react/15.6.1/react-dom.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/react-bootstrap/0.31.0/react-bootstrap.min.js"></script>

**Comment by ramintagizade** [comment]
This solved my problem too !

**Comment by vivex** [comment]
I got this error when i was using react version `15.1.0` upgrading to `15.6.0` solved this for me.
