### ISSUE TITLE
NavDropdown html in title

### ISSUE THREAD

**Issue by naldir** [react-bootstrap/react-bootstrap#2606]
The fact that the NavDropdown text is in the property "title" makes impossible to render plain html or react components inside it (a fontawesome icon in my case)
Is this possible to fix that ?
This was possible with the original bootstrap element in plain html

**Comment by jquense** [comment]
the title can be any node, not just text

**Comment by naldir** [comment]
`<NavDropdown className=eventKey={1} title="<FontAwesome name='th-list' />Toto" id="basic-nav-dropdown">`
the `<FontAwesome />` component can't be rendered because it is in a text attribute. The code is written on the page in plain text.

**Comment by sillyslux** [comment]
@naldir try:
```
<NavDropdown
  title={
    <div>
      <FontAwesome name="th-list" size="lg" />
      Toto
    </div>
  }
  id="basic-nav-dropdown"
  className="someclass"
  eventKey={1}
>
```
a) your `className=eventKey={1}` is a typo?
b) it has to be one node, Component <FontAwesome> and TextNode "Toto" would be 2 nodes, so i wrapped it in a div

**Comment by naldir** [comment]
@sillyslux thanks for your answer
a) this was endeed a typo
b) this is even better with a `<span>`

These were beginner mistakes. sorry for the inconvenience

**Comment by sillyslux** [comment]
@naldir 
a) no problem..
b) an issue tracker is not an support channel,
try https://webchat.freenode.net/
type /join ##javascript and /join #reactjs for general help on topics
type /msg alis list keyword to search for "keyword"-channels

get help instantly, when you need it, you don't have to wait 6 days for an answer like this...

**Comment by jquense** [comment]
I'd try stackoverflow.com or the discord channel before irc none of the maintainers are in irc anyway. You are also welcome to post support questions here, as long as they are about react-bootstrap

**Comment by awaisdar001** [comment]
Thanks for the information here, this indeed helped.
