### ISSUE TITLE
Panel header/footer/body handles nulls inconsistently.

### ISSUE THREAD

**Issue by bdkent** [react-bootstrap/react-bootstrap#2607]
`<Panel>` seems to handle `null` vs components that return `null` as the result of rendering quite differently.

To be more concrete, I would expect the following two examples to result in the same Panel:

Example 1
```
const header = null;
const footer = null;
const body = null;

<Panel header={header} footer={footer}>{body}</Panel>
```

Example 2
```
class OnlyNull extends React.Component {
    render() {
        return null;
    }
}

const header = (<OnlyNull />);
const footer = (<OnlyNull />);
const body = (<OnlyNull />);

<Panel header={header} footer={footer}>{body}</Panel>
```

Example 1 results in what I would expect: empty containers.

Example 2 results in containers with `<!-- react-empty: ... -->` nodes that causes ugly contentless but still padded and visible header/footer/body in the Panel.

See the following:

![image](https://cloud.githubusercontent.com/assets/3629629/25758369/533dfe82-319c-11e7-995f-d5dbf2ae334a.png)

Example 2 seems like a bug to me.

`OnlyNull` is of course just for illustrative purposes but in scenarios where one has optional header/footer content, this crops up a lot and is tedious to work around.

**Comment by taion** [comment]
We're replacing this entire API in https://github.com/react-bootstrap/react-bootstrap/pull/1769, so there's nothing actionable here.
