### ISSUE TITLE
FormControl doesn't pass ref prop to the (input) component it creates.

### ISSUE THREAD

**Issue by steviesama** [react-bootstrap/react-bootstrap#2608]
I'm not sure if this is a bug or working as intended, but when I did the following:

```
<FormGroup style={inlineBlock} className="col-50">
    <ControlLabel>Email</ControlLabel><br/>
    <FormControl ref={((input) => this.emailInput = input).bind(this)} type="text"
        className="btn-block"
        placeholder="Used to log in"/>
    <FormControl.Feedback/>
</FormGroup>
```
The ```ref``` prop doesn't get passed to the component it creates apparently. As ```this.emailInput.focus()``` complains that ```focus()``` isn't a function.

I had to change the ```FormControl``` to what it generates manually shown below... to an ```input``` and add ```form-control``` to the ```className``` and it works fine:

```
<FormGroup style={inlineBlock} className="col-50">
    <ControlLabel>Email</ControlLabel><br/>
    <input ref={((input) => this.emailInput = input).bind(this)} type="text"
        className="form-control btn-block"
        placeholder="Used to log in"/>
    <FormControl.Feedback/>
</FormGroup>
```

**Comment by jquense** [comment]
That is how refs work, they are applied to the component you add them too, not the eventual DOM node. We expose `inputRef` for this purpose tho that should work if you don't want to use findDOMNode

**Comment by jquense** [comment]
(lol sorry i must of seen this the moment you made it)

**Comment by steviesama** [comment]
@jquense I know that's how refs work, I was just reporting this because I wasn't sure if bootstrap intended to move the refs prop to the created component or not. I personally haven't created anything that would do such an operation so I don't know the caveats, but it sounds like inputRef is what I'm looking for. I'll try that. I'd prefer be consistent and use ```<FormControl/>```. If I create something like ```<FormControl inputRef={((input) => this.emailInput = input).bind(this)} ... />``` this will pass the assignment I made to inputRef down to the input component it generates?

**Comment by steviesama** [comment]
@jquense I had the time and just went ahead and tried it. Thanks, worked perfectly.

**Comment by dozoisch** [comment]
By the way, with arrow functions you don't need to `bind(this)` as arrow function are bound to current scope by design. Actually arrow functions are just not re-bindable at all.
