### ISSUE TITLE
react bootstrap Cannot read property 'Component' of undefined

### ISSUE THREAD

**Issue by chemseddineZ** [react-bootstrap/react-bootstrap#2609]
I'm trying to create a modal window with react-bootstrap, i'm implementing the jsx file like this

 ```
const WindowModal = React.createClass({
 getInitialState(){
 return {showModal: false};
 },

 close(){
this.setState({showModal: false});
},

open(){
this.setState({showModal: true});
},
render () {
return (

  <div>
         <p>Click!</p>

         <Button bsStyle="primary" bsSize="large" onClick={this.open}>Launch</Button>

         <Modal show={this.state.showModal} onHide={this.close}>
           <Modal.Header closeButton>
             <Modal.Title>Sign Up</Modal.Title>
           </Modal.Header>
           <Modal.Body>
             <h1>Sign Up in Studio</h1>
         </Modal.Body>
           <Modal.Footer>
             <Button onClick={this.close}>Close</Button>
           </Modal.Footer>
         </Modal>
       </div>

);
}
});

 ReactDOM.render(<WindowModal/>,
 document.getElementById('contenu')
);
```
however when i run my app i get errors in the browser console

> Uncaught TypeError: Cannot read property 'Component' of undefined
> at Object.exports.__esModule (react-bootstrap.js:2137)
> at webpack_require (react-bootstrap.js:30)
> at Object.exports.__esModule (react-bootstrap.js:435)
> at webpack_require (react-bootstrap.js:30)
> at Object.exports.__esModule (react-bootstrap.js:62)
> at webpack_require (react-bootstrap.js:30)
> at exports.__esModule (react-bootstrap.js:50)
> at react-bootstrap.js:53
> at webpackUniversalModuleDefinition (react-bootstrap.js:9)
> at react-bootstrap.js:10

**Comment by taion** [comment]
you need to include the `<script>` tag for react before you include the one for R-B
