### ISSUE TITLE
form-control class not applied when <FormControl type="file"/> is used

### ISSUE THREAD

**Issue by krishnagopinath** [react-bootstrap/react-bootstrap#2611]
Kinda weird, but it looks like a one-off thing. Even in the [Forms Demo](https://react-bootstrap.github.io/components.html#forms-controls), for the `<FormControl type="file"/>` component, the `form-control` class isn't applied to the nested `<input/>` tag.

![57647a38-e78f-46d0-9b1e-b779ec5989e6](https://cloud.githubusercontent.com/assets/4935809/25782704/1106045a-331e-11e7-805d-7e982cd0d88e.jpg)

I know it's not big deal, I could always add the class by myself, just wanted to report for the sake of uniformity :smile:

**Comment by taion** [comment]
It's not supposed to be. Upstream TWBS doesn't style file inputs.
