### ISSUE TITLE
Nav Items are stacked and can't be put horizontally when using <Navbar> 

### ISSUE THREAD

**Issue by antoniofpereir** [react-bootstrap/react-bootstrap#2612]
I've been trying to create a navbar with horizontally placed items but they are always vertically aligned. I'm not using the stacked utility and it only happens when I wrap the Nav and the NavItem in the Navbar

**Comment by taion** [comment]
Please follow the examples, which demonstrate this. Otherwise, make sure your CSS isn't busted.

**Comment by jww52** [comment]
The examples I'm following are giving me the same issue.  Do you have a link to any examples you are referring to?  Thanks

**Comment by antoniofpereir** [comment]
I was following the react-bootstrap documentation. Meanwhile I was evaluating the css from the navbar and for some reason the default flex values (apparently react-bootstrap uses flexbox for some tweaks) were set to column instead of row. I fixed it by changing the following css:
```
.navbar-nav{
    -webkit-flex-direction: row;
    -ms-flex-direction: row;
    flex-direction: row;
}
```

**Comment by serixscorpio** [comment]
It's possible the nav items stack vertically instead of horizontally due to responsive collapsing.  From [bootstrap documentation](https://getbootstrap.com/docs/4.1/components/navbar/#how-it-works):
> Navbars require a wrapping .navbar with .navbar-expand{-sm|-md|-lg|-xl} for responsive collapsing

For example, if one has `.navbar-expand-lg`, try changing to `.navbar-expand-md` or `.navbar-expand-sm` to see if the nav items stack differently.

**Comment by harshwchaudhary** [comment]
k

**Comment by draicor** [comment]
You need to add the class .navbar-expand to your navbar-nav to make the flex-direction: row..
