### ISSUE TITLE
defaultOpen not recognized

### ISSUE THREAD

**Issue by aaron-m-kent** [react-bootstrap/react-bootstrap#2613]
I am trying to add the `defaultOpen` property to a `DropdownButton`, but it is not opening the button and is generating the below warning. 

```Warning: Unknown prop `defaultOpen` on <button> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
    in button (created by Button)
    in Button (created by DropdownToggle)
    in DropdownToggle (created by Dropdown)
    in div (created by ButtonGroup)
    in ButtonGroup (created by Dropdown)
    in Dropdown (created by Uncontrolled(Dropdown))
    in Uncontrolled(Dropdown) (created by DropdownButton)
    in DropdownButton (created by Unknown)
    ...```

**Comment by taion** [comment]
need to add it to `propTypes`. care to PR?

**Comment by aaron-m-kent** [comment]
Thank you. Even if not in `propTypes`, shouldn't behavior be observed? There is no observable change in behavior. Will adding to `propTypes` produce desired behavior?

**Comment by jquense** [comment]
something else is not right. uncontrollable won't pass through `default` props I suspect the problem is the prob is on the wrong element. can you post your code

**Comment by aaron-m-kent** [comment]
Thanks. Here is my usage:
```
<DropdownButton
  id={id}
  title={title}
  disabled={isDisabled()}
  defaultOpen={true}
>
  {content}
</DropdownButton>
```

**Comment by taion** [comment]
@jquense think the issue is that https://github.com/react-bootstrap/react-bootstrap/blob/v0.31.0/src/DropdownButton.js#L27-L28 won't include `defaultOpen`

**Comment by skwon-mdsol** [comment]
should this issue be addressed? I can open a pr for this if necessary?

**Comment by taion** [comment]
Yeah it should be a simple fix. Thanks!

**Comment by skwon-mdsol** [comment]
nice, will open a pr later.
