### ISSUE TITLE
autoFocus in overlay effects scroll position

### ISSUE THREAD

**Issue by bdkent** [react-bootstrap/react-bootstrap#2614]
I have a `<FormControl/>` that appears inside an overlay. If I set the `autoFocus`, the screen repositions to the top of the page, regardless of where the scroll position may be.

I have recreated the issue in a [fiddle](https://jsfiddle.net/bkent/fs39moqq/).

**Comment by jquense** [comment]
Hi there. This mostly browser behavior and React's polyfill of `autoFocus` the popover is initially positioned in the top left of the screen while it's measured and then moved to the right spot. At the same time the input is being focused. Browsers scroll focused inputs into view which is putting it at the at the top. BEst I can say is to defer setting autofocus in a timeout or until the popover is positioned correctly.

**Comment by jonahparampara** [comment]
I have run into this issue quite often. My workaround is to focus in the input from the Overlay `onEntered` event but yeah it's pretty annoying to need to do this

**Comment by HomiG** [comment]
You should focus input onEnter event passing the flow from the event-loop:

`<OverlayTrigger
        onEnter={e => {
            setTimeout(() => {
                e.querySelector('input').focus()
            },0)
        }} />`

**Comment by DemianQuad** [comment]
> You should focus input onEnter event passing the flow from the event-loop:
> 
> `<OverlayTrigger onEnter={e => { setTimeout(() => { e.querySelector('input').focus() },0) }} />`

this is a good suggestion but with some small changes it is less hacky i think.
```ts
const inputRef = useRef<HTMLInputElement>(null);
...

<OverlayTrigger
      onEnter={() => inputRef.current?.focus({ preventScroll: true })}
      overlay={
          <Popover>
              <Popover.Body>
                  <input ref={inputRef} type="text"/>
              </Popover.Body>
          </Popover>
      }
  />
```

**Comment by gabrielpetersson** [comment]
you can just use `input.focus({ preventScroll: true });`
