### ISSUE TITLE
Pagination onSelect Update data

### ISSUE THREAD

**Issue by RelaxLiu** [react-bootstrap/react-bootstrap#2617]
Pagination(event){
    var $this = this;
    $.ajax({
      url:'/api/......',
      type: 'GET',
      dataType: 'json',
      data: {
        pager: event
      },
      success: function(map){
        $this.setState({
          data: map.data.data,
          pager: map.data.pager
        })
      }
    }) 
  }

$this.setState is not function
Is there any way to update the data

**Comment by taion** [comment]
Impossible to tell what this issue is saying. We rewrote this API anyway.

**Comment by RelaxLiu** [comment]
@taion 

constructor(props){
    super(props);
    this.state = {
      city: [],
      area: [],
      community: []
    }
  }
SelectCity(event){
    var $this = this;
    $.ajax({
      url:'/api/....',
      type: 'GET',
      dataType: 'json',
      data: {
        city_id : event.target.value
      },
      success: function(map){
        $this.setState({
          area : map.data
        });
      }
    }) 
  }

Error reporting：$this.setState is not a function
I don't know why

**Comment by jquense** [comment]
You probably didn't bind your method, this is a javascript issue not  a react-bootstrap one
