### ISSUE TITLE
ability to remove btn-* css classes from Dropdown.Toggle

### ISSUE THREAD

**Issue by farukg** [react-bootstrap/react-bootstrap#2618]
Hello,

i wanted to remove the default css classes on the Dropdown.Toggle Component (btn, btn-default), but was not able to configure this via props.

I ended up using following  a workaround which results in a warning of course  :)

```js
{/* ... */}
<Dropdown.Toggle componentClass='div' useAnchor />
{/* ... */}
```
--> Unknown prop \`useAnchor\` on \<div\> tag

Is there any other way to achieve my goal? or will there be more flexibility in the future?

**Comment by jquense** [comment]
you can make any component a Dropdown toggle by adding the prop `bsRole='toggle'` to it. See the custom Dropdown example in the docs.
