### ISSUE TITLE
All page events crash when contained modal is open

### ISSUE THREAD

**Issue by joseucarvajal** [react-bootstrap/react-bootstrap#2622]
In components [demo page](https://react-bootstrap.github.io/components.html#modals), try open contained modal, and then click in another element on page, this doesn't works, all events die, it works again when contained modal is closed. In fact when another element is clicked, the page moves scroll to opened contained modal.

![cm-pic1](https://cloud.githubusercontent.com/assets/5514431/26031764/fe5f1162-3844-11e7-8340-712268c39284.png)

I need an app, with many modals opened at time from navbar, currently, it doesn't works.

**Comment by jquense** [comment]
Yes that's what a Modal means :)  it's not a generic popup it's a modal popup, so it blocks interaction with anything behind it
