### ISSUE TITLE
Export CloseButton for public use?

### ISSUE THREAD

**Issue by natevw** [react-bootstrap/react-bootstrap#2623]
There is a CloseButton component used internally. It ± follows Bootstrap's own documented suggestion for such: <https://v4-alpha.getbootstrap.com/utilities/close-icon/>

Any particular reason this can't be exposed for reuse outside of react-bootstrap, either alongside the normal button component or at least under utilities?

**Comment by taion** [comment]
sure go for it

**Comment by skwon-mdsol** [comment]
this can be closed, correct?

**Comment by taion** [comment]
thanks!
