### ISSUE TITLE
With some browsers, and some window sizes, the dropdown (Select options) borders have issues - ex: no bottom border, very thick left border

### ISSUE THREAD

**Issue by padiyan** [react-bootstrap/react-bootstrap#2624]
With some browsers, and some window sizes, the dropdown (Select options) borders have issues - ex: no bottom border, very thick left border.

**Comment by jquense** [comment]
That sounds like a css issue if anything. Since we don't provide any of own css the best place to report those issues is on the normal bootstrap repo
