### ISSUE TITLE
Inconsistent order of class and id attributes server-side for Dropdown.Toggle

### ISSUE THREAD

**Issue by azotova** [react-bootstrap/react-bootstrap#2625]
I have an isomorphic app with the following component:
```
class CoursesMenu extends React.Component
  render: ->
    <Dropdown id="course-menu-dropdown">
      <Dropdown.Toggle className="top-nav__button" noCaret>
        Courses
      </Dropdown.Toggle>
      <Dropdown.Menu>
        <MenuItem eventKey="1" href="/math">Math</MenuItem>
        <MenuItem eventKey="2" href="/phys">Physics</MenuItem>
      </Dropdown.Menu>
    </Dropdown>
```
It worked fine with react-bootstrap 0.29 (up to 0.29.5). I tried upgrading to 0.31.0 and got the 'the checksum was invalid' error (the issue is present when I try 0.30.0 too).

This is the html generated both client-side and server-side with 0.29:
```
<button class="dropdown-toggle top-nav__button btn btn-default" id="course-menu-dropdown" role="button" aria-haspopup="true" aria-expanded="false" type="button" data-reactid="23">
```
With 0.31, the html generated client-side is the same, but server-side I get:
```
<button id="course-menu-dropdown" role="button" aria-haspopup="true" aria-expanded="false" type="button" class="top-nav__button dropdown-toggle btn btn-default" data-reactid="23">
```
(the order of attributes is different; the order of classes is different too).
Is there a way to fix this?

**Comment by taion** [comment]
This is an upstream issue – we have no control over this. Make sure you're not on an old and broken version of React.

**Comment by azotova** [comment]
Thanks @taion  I am on React 15.5.4. Is there anything in react-bootstrap that changed between 0.29 and 0.30 and could be causing this?
