### ISSUE TITLE
Uncaught TypeError: (0 , _typeof3.default) is not a function

### ISSUE THREAD

**Issue by ishantmehta01** [react-bootstrap/react-bootstrap#2626]
When I upgraded my react-bootstrap from "0.28.1" to "0.31.0",
I am getting this error, in typeOf.js  
React version `"react": "15.4.2",`
Babel `"babel-cli": "^6.24.1",`

```
Uncaught TypeError: (0 , _typeof3.default) is not a function
at exports.default (eval at <anonymous> (main.space.en_US.js:1031), <anonymous>:12:122)
at eval (eval at <anonymous> (main.space.en_US.js:6362), <anonymous>:18:87)
```

Any help would be appreciated.

Thanks in Advance.

**Comment by jquense** [comment]
your stack trace isn't really helpful, but you are probably trying to call some util or component that was moved/changed/removed between those versions

**Comment by ishantmehta01** [comment]
<img width="1067" alt="screen shot 2017-05-16 at 10 48 28 pm" src="https://cloud.githubusercontent.com/assets/6848746/26119120/cda89326-3a89-11e7-9f65-3abb4060ac58.png">


This is the actual error

**Comment by taion** [comment]
Your build environment is set up wrong. Hard to tell how from here, but it's not an issue in this repo.
