### ISSUE TITLE
popover always at top left of the screen

### ISSUE THREAD

**Issue by joeSaad** [react-bootstrap/react-bootstrap#2627]
Created the same popover in two different applications. One time it appends to the component as expected. Another time in which case the calling component is a child, it appends the popover the body. This cause the Overlay to not do anything with the target and will always show the popover at the top left of the screen. 
Any other options for the container? 
putting it as container = {this} shows the popover altogether out of the screen. 
what are other options for container property? 
is this the reason why the popover is always appearing top left of the screen when a child component calls it?

**Comment by taion** [comment]
containers need to have `position: relative`

**Comment by joeSaad** [comment]
it actually appends to the body tag. Just noticed the component act little different when using  trying to get props from Redux other than when trying to work it all within react only. Could it be the lifecycle issue?

**Comment by glekner** [comment]
i'm facing this issue aswell after getting props from redux, did you solve this?

**Comment by davidhamann** [comment]
Had a similar issue with the Popover showing at the top left when passing a function to OverlayTrigger's `overlay`. I just forgot to handle the passed props (style, ref, arrowProps, etc.) in my render function and thus no transforms, etc. were applied to the div. I fixed it by passing the props on, so something like `<Popover ref={props.ref} style=...` or `<Popover {...props} ...`. Hope this helps.

**Comment by davidroman0O** [comment]
I had the same problem... but I replace it with https://www.npmjs.com/package/react-tiny-popover

**Comment by daniel-ilan** [comment]
I also tackled with this and found the solution was to use React.forwardRef as a wrapper for the custom popover component. 
This is my code:
`
const CustomPopover = React.forwardRef((props, ref) => {
  return (
    <Popover id='popover-basic' {...props} ref={ref}>
      <Popover.Title as='h3'>Popover right</Popover.Title>
      <Popover.Content>
        And here's some <strong>amazing</strong> content. It's very engaging.
        right?
      </Popover.Content>
    </Popover>
  );
});`


And here I am using it:
`<StyledLinkButton onClick={() => setShow(!show)} ref={target}>
            Subscribe to new movie
          </StyledLinkButton>
          <Overlay
            show={show}
            target={target.current}
            placement='bottom'
            flip
            rootClose>
            {({ ...props }) => <CustomPopover {...props} />}
          </Overlay>`

Not sure if that's the best way to do this though, feels over complicated. If anyone has a better solution I would love to hear

**Comment by TAGC** [comment]
The popover is appearing in the top-left of the screen despite being nested within a container that has `position: relative` set. I've spent three hours and counting trying to debug this issue. Other tooltips within the page are working fine but not this one.

The weird thing is that it _was_ working for a few minutes while I was developing it and then suddenly seemed to stop working. I'm not even sure how that's even possible.

**Comment by mrowles** [comment]
Why is this closed? It's still an issue
