### ISSUE TITLE
FormControl type="text" placeholder behaviour not consistent across browser

### ISSUE THREAD

**Issue by kunwarshesh** [react-bootstrap/react-bootstrap#2628]
Behavior of placeholder is not consistent on different browsers. Like in Chrome it looks fine, but placeholder text is missing while focus is on that field in IE.
![input text placeholder issue](https://cloud.githubusercontent.com/assets/6037549/26155699/b8e6d0d0-3b31-11e7-9d77-35f2e0ae2138.png)

**Comment by erinknight242** [comment]
That is typical placeholder behavior in IE

**Comment by jquense** [comment]
hi! The FormControl components are extremely simple wrappers around html inputs, so all the same restrictions that are present in normal inputs are present here, as in this case!

**Comment by kunwarshesh** [comment]
Thanks @erinknight242 and @jquense for your valuable comments. I was aware about it but thought we may have some hack to fix it.
