### ISSUE TITLE
Edit in popup window

### ISSUE THREAD

**Issue by nishasobhanan** [react-bootstrap/react-bootstrap#2633]
Hello, I am using "react-bootstrap-table". I need to use popup window of the insert row, for the edit purpose also. I place a button in the react bootstrap table and I need to fill the popup window with corresponding data. So I need to pass values to the popup window. Is it possible?

**Comment by nishasobhanan** [comment]
In some cases we can list only few fields in the grid. So the editable option in the grid doesn't work for all the fields. If we can have the edit option through the popup window, it will be great. We are not able to find an option for this. Will you help for the same?

**Comment by taion** [comment]
You just pass them to the component as props. This isn't really relevant as an issue for this repo.
