### ISSUE TITLE
rootClose behavior for a custom overlay is sometimes triggered incorrectly

### ISSUE THREAD

**Issue by kaiyoma** [react-bootstrap/react-bootstrap#2636]
I'm noticing that - in some browsers - the `rootClose` functionality for a custom overlay is incorrectly triggered on a "mouse up" event rather than a "mouse click" event. To see this in action easily, go to this example in the docs:

https://react-bootstrap.github.io/components.html#custom-overlays-overlay

Click "show code" and add `rootClose={true}` to the `Overlay` component. On the rendered component, click the button so the pop-up appears, click inside the pop-up and hold down the mouse button, drag outside the pop-up area, then release the mouse button. You'll see the pop-up close even though you never clicked.

I've also noticed this behavior is different among the browsers. Chrome, IE, and Edge all exhibit this unexpected close behavior, but Firefox and Safari don't.

**Comment by taion** [comment]
dupe https://github.com/react-bootstrap/react-bootstrap/issues/1785
