### ISSUE TITLE
MenuItem without href

### ISSUE THREAD

**Issue by domehead100** [react-bootstrap/react-bootstrap#2637]
I'd like to be able to have a MenuItem in a NavDropdown where right-clicking on the item does not show the user an "open in new window" or "open in new tab" option on the browser's context menu because, for example, the given MenuItem has an onClick handler that launches a popup window or does something else.

As far as I can see, SafeAnchor will always render an href attribute on the anchor tag, defaulting to "#" if the href prop is falsy.  So, right-clicking on a MenuItem without a provided href prop will not do anything bad, but it does give the user what appears to be the option to open the link in a new window/tab, when in fact it does not.  I think a user would find this confusing.

Maybe there is a standard, proper, accessible way to accomplish this right now, e.g., so that the MenuItem behaves like a button instead of a link?  Maybe I shouldn't be using a MenuItem at all?  The correct thing to do is not clear to me.

Looks like it would be easy to prevent rendering an href attribute, perhaps with a new noHref prop on the MenuItem, but since there are accessibility ramifications I thought I'd ask.

**Comment by jquense** [comment]
You should make a custom menuitem instead, see the custom dropdown example on the docs page. We aren't going to make changes to the MenuItem component tho since the css doesn't work without an anchor tag

**Comment by aengin** [comment]
I think he is right ▼

**Comment by olmobrutall** [comment]
@jquense Hi again, 
 
I'm also interested in this feature. When you have a `MenuItem` where you want to allow middle-click button (to open in another screen) there is no way to preventDefault, click/contextMenu/mouseUp doesn't work and the browser is going to insist in opening a tab to `http://yourcurrenturl/#`, on top of what you're currently opening. 

Of course I could create my on MenuItem but with what name? `MenuItemMiddleMouseNoTab`...?

**Comment by jquense** [comment]
not sure why preventDefault wouldn't work here. If your browser is still navigating after the click is prevented that's probably some router code ni your app, not the MenuItem

**Comment by olmobrutall** [comment]
If happens with Chrome 55+ only, IE/Firefox work ok

**Comment by olmobrutall** [comment]
I think is related to https://developers.google.com/web/updates/2016/10/auxclick and https://stackoverflow.com/questions/41110264/middle-button-click-event

**Comment by olmobrutall** [comment]
looks like react is not actively working on it... https://github.com/facebook/react/issues/8529

**Comment by jquense** [comment]
whelp that's interesting...I'd use a workaround in this, I've added my thoughts to that issue so we can get a fix moving as well in React

**Comment by hakunin** [comment]
Can anyone paste their custom MenuItem workaround here?
