### ISSUE TITLE
activeKey vs eventKey for panel group/accordion

### ISSUE THREAD

**Issue by rbalicki2** [react-bootstrap/react-bootstrap#2639]
The docs (https://react-bootstrap.github.io/components.html) indicate that the prop is named eventKey, but the code says activeKey.

If the docs are incorrect, happy to make a PR with a fix

Also, Accordions seem to extend PanelGroup, but in the docs they look like they are a Panel. I think the docs are also incorrect on this front.

**Comment by jquense** [comment]
`activeKey` corresponds to an `eventKey` on the children Panels. e.g the `activeKey` names the Panel (with an eventKey) that is currently expanded

**Comment by rbalicki2** [comment]
Ok, awesome! I think then the docs are mistaken about the Accordion being a Panel instead of a PanelGroup!

**Comment by jquense** [comment]
ah yeah that is a typo, thanks!
