### ISSUE TITLE
button toolbar exports SIZES, but does not seem affected by bsSize property

### ISSUE THREAD

**Issue by rbalicki2** [react-bootstrap/react-bootstrap#2640]
Is this a bug? Am I missing something?

-R

**Comment by jquense** [comment]
it passes them to the buttons in the toolbar

**Comment by jquense** [comment]
or should...

**Comment by rbalicki2** [comment]
Just to give you a heads up, I'm writing flow types for the latest react-bootstrap for my company's internal use. I'll make a PR at some point with it when it's done as well.

**Comment by taion** [comment]
@jquense should it do that? it's weird to use `bsSize` there anyway since there are no size variants for `.btn-toolbar`

**Comment by jquense** [comment]
maybe it shouldn't maybe it's just bsClass?

**Comment by taion** [comment]
yeah i'd just drop `bsSize`

**Comment by n8thegr8** [comment]
I know we have bootstrap 2.3.2 and in using this, I noticed 'large' gets transformed to 'lg' for bootstrap 3+.   'large' should just be 'large' and 'lg' should be 'lg'.   Maybe that is why @rbalicki2 is not seeing the size change.

**Comment by taion** [comment]
no, `.btn-toolbar` just doesn't have any size variants. we should drop `bsSize` here
