### ISSUE TITLE
Dropdown calls onBlur while selecting a value

### ISSUE THREAD

**Issue by zee0786** [react-bootstrap/react-bootstrap#2641]
There is an unnecessary onBlur event called while selecting a value on dropdown. This bypasses the onSelect event when a setState function is called within onBlur function

**Comment by jquense** [comment]
It's not unnecessary, the focus is being moved to the correct element after the click. I'm not sure I understand the bug tho. When does onSelect get skipped and can you please provide some code that reproduces the bug? Thanks!

**Comment by zee0786** [comment]
this code works properly with keyboard tabbing in/out but doesn't work on mouse click event

  onFocus() {
    this.setState({ open: true });
  }

  onBlur() {
    this.setState({ open: false });
  }

  onSelect(item, event) {
    if (item) {
      this.setState({ optionValue: item });
     
      }
    }
        <Dropdown
          style={styles.dropDownControl}
          id={this.props.id}
          onSelect={this.onSelect}
          open={this.state.open}
          onFocus={this.onFocus}
          onBlur={this.onBlur}
        ></Dropdown>

**Comment by taion** [comment]
You're going to have to do some bookkeeping here yourself. The blur is necessary to move the focus appropriately, as noted above.
