### ISSUE TITLE
FormControl type="number" not taking - (hypen) as valid entry

### ISSUE THREAD

**Issue by shashuec** [react-bootstrap/react-bootstrap#2642]
Hi,

I want to open the numerical keyboard for date field which is in the format (YYYY-MM-DD).
I m using FormControl type="number" for that.
Problem is after typing - the value it returns becomes empty string.
Is this a bug?
If not how to achieve this

**Comment by jquense** [comment]
The native html inputs don't work like that, if you use the number input you can only enter a valid number. Maybe consider using a date input or text input with some custom parsing logic you add
