### ISSUE TITLE
How to add className to anchor in NavItem

### ISSUE THREAD

**Issue by ujovlado** [react-bootstrap/react-bootstrap#2644]
Props you pass to `NavItem` are filtered this way:
```js
var props = _objectWithoutProperties(_props, ['active', 'disabled', 'onClick', 'className', 'style']);
```
... and then passed to `SafeAnchor`.

Which makes sense, because we don't want to apply same styles for `li` and nested `a`.

But there are situations when you want to simply add class to mentioned anchor. For example to make it look like button.

`SafeAnchor` accepts `componentClass` property, so passing custom `componentClass` will allow rendering custom react element with passing additional props.

So
```js
const CustomAnchor = ({children, anchorClassName, ...rest }) => {
  return (
    <a className={anchorClassName} {...rest}>{children}</a>
  );
};
```
and
```js
<NavItem
  componentClass={CustomAnchor}
  anchorClassName="btn btn-primary"
  eventKey={2}
>
  Item
</NavItem>
```
will render:

```html
<li role="presentation" class=""><a class="btn btn-primary">Item</a></li>
```

Hope it helps others!

**Comment by taion** [comment]
I don't think we need to generally support this. Note that upstream TWBS here styles something like `li.nav-item > a`.
