### ISSUE TITLE
MenuItem in Dropdown's active attribute isn't being applied correctly

### ISSUE THREAD

**Issue by jsnoops** [react-bootstrap/react-bootstrap#2646]
I have a dropdown in my react-bootstrap navbar, you select a song and it brings you to localhost:8080/song/id

Then it makes that MenuItem have the active class, but even when I click a new Menu Item, the active class stays there and doesn't switch. 

How can I remove this behavior altogether so I can just use logic to decide if the MenuItem is active?

Here us the code which makes the MenuItems

```
     const mappedSongChoices = this.props.user.songs.map(song =>
                     <LinkContainer key = { 'song' + song.id } to= { "/song/" + song.id }>
                         <MenuItem href = { "/song/" + song.id} onClick = { (event) => this.handleSongSelection(event, song.id) } eventKey = { 'song' + song.id }
                             title={ song.title } >
                             { song.title }
                         </MenuItem>
                     </LinkContainer>
                 )
```

**Comment by jquense** [comment]
You can manually set the active prop on the LinkContainer if you don't want the RR active semantics

**Comment by jsnoops** [comment]
@jquense I've tried that, and it works, but it doesn't take the active class off of the original one I clicked for some reason. 
http://imgur.com/a/h6Fyy

**Comment by jquense** [comment]
they aren't exclusive, any MenuItem with an active link is going to have the active class, that's how the RR "active" state works unfortunately

**Comment by jsnoops** [comment]
But the link isn't active... it'll be on song/32 but if i went to song/3 first.. it'll keep song/3 active as well as song/32

**Comment by jquense** [comment]
sounds like a bug in RR then, or you have a misconfigured route perhaps
