### ISSUE TITLE
Allow preventing NavItem default action eg switching a tab

### ISSUE THREAD

**Issue by xumix** [react-bootstrap/react-bootstrap#2649]
Im' tying to prevent default action but have no succcess.
```
onClick: function (key, e) {
                (e || key).preventDefault();
                (e || key).stopPropagation();
                return false;
            }
```
This does not work at all, I've tried onSelect but no luck also.
What I actually want is to disable the NavItem but be able to show title and tooltip, adding "disabled" attr removes this ability.

**Comment by jquense** [comment]
You need to manually "control" the `activeKey` via `onSelect` on the Nav to handle that case. When the key is the one you want disabled don't update the activeKey, otherwise just pass them back through.

**Comment by xumix** [comment]
Ok, thank you, I'll try your solution

**Comment by xumix** [comment]
@jquense I can't figure out, how do you mean should I "control" the active key?

**Comment by xumix** [comment]
Ok I got it, but it would be much more declarative to set this "selectable" state or property in the NavItem element

**Comment by MikeProcudin** [comment]
could you share ?

**Comment by xumix** [comment]
@MikeProcudin 
```
onTabChange = (key, event) => {
        if (key === "should not switch") {
            return;
        }

        this.setState({ curTab: key });
    }
<Tab.Container id="tabs-with-dropdown" activeKey={this.state.curTab} onSelect={this.onTabChange}>
<Nav bsStyle="tabs">
<NavItem eventKey={"should not switch"} href={NewIppTabs.ProjectInfo}>No switch</NavItem>
<NavItem eventKey={"should switch"} href={NewIppTabs.ProjectInfo}>Switch</NavItem>
</Nav>
<Tab.Content>
<Tab.Pane eventKey={"should not switch"}>
Content
</Tab.Pane>
<Tab.Pane eventKey={"should switch"}>
Content
</Tab.Pane>
</Tab.Content>
</Tab.Container>
```
