### ISSUE TITLE
[Popover] use with React Motion

### ISSUE THREAD

**Issue by Floriferous** [react-bootstrap/react-bootstrap#2650]
I'm trying to animate the Popover component with react motion. So far it works great when the component enters, but not when the component leaves:

```jsx
// myOverlay.jsx
<Transition>
  {({ key, style }) => (
    <Popover
      {...this.props}
      key={key}
      style={{ opacity: style.opacity, transform: `scale(${style.scale})` }}
    >
      Some Text
    </Popover>
  )}
</Transition>
```

This is all wrapped inside an `overlayTrigger` to function properly, so this component is passed to its `overlay` prop.

My `Transition` component, basically is a wrapper of React Motion that does all of the styles magic. 

My problem is that it doesn't work onLeave, or onHide. I think that when the component is dismissed, the entire `overlay` prop is unmounted, and therefore the whole `Transition` component unmounts as well, which means it can't animate the exit. 

Is there a way to use the events on `overlayTrigger` to somehow make this work? Or could I use the `animation` prop with react motion?

**Comment by Floriferous** [comment]
Well, writing this helped me figure it out. Feel free to ping me if this of interest to anyone, it's a bit messy, but it works.

**Comment by Floriferous** [comment]
Turns out, wrapping a Popover makes the positioning of it break. It is no longer contained inside the container when it overflows.

**Comment by taion** [comment]
If you want a custom transition, you need to specify this with the `animation` prop, and roughly match the React Transition Group API (especially around calling this callbacks at the right times).

This is because, to handle mounting and unmounting, `<Overlay>` hooks into this API to figure out the transition lifecycle.
