### ISSUE TITLE
Child of OverlayTrigger throwing "Uncaught Error: getNodeFromInstance: Invalid argument."

### ISSUE THREAD

**Issue by jhdielman** [react-bootstrap/react-bootstrap#2651]
#### Description
`Uncaught Error: getNodeFromInstance: Invalid argument.` is thrown on `handleMouseOverOut` by one of the child nodes of `OverlayTrigger`.

#### Implementation
```
renderTooltip() {
    let {callSid, description} = this.props;

    if (description) {
        let tooltip = (
            <Tooltip id={callSid}>
                {description}
            </Tooltip>
        );
            
        return (
            <OverlayTrigger
                placement="top"
                overlay={tooltip}
            >
                <span className="text-muted m-l-xs">
                    <i className="aria-hidden icon icon-question-circle help-tooltip"></i>
                </span>
            </OverlayTrigger>
        );
    }

    return null;
}
```

#### Error Source: _ReactDom_
The method `getNodeFromInstance` below is looking specifically for `_hostNode` of `inst`. In the case of the above implementation, the error is thrown because the `<span>` child node does not contain `_hostNode` and instead contains a reference to `_nativeNode` as shown in the example `inst` object below. One possibility would be to submit a PR to have _ReactDom_ look for `_nativeNode` if `_hostNode` is not available.
```
function getNodeFromInstance(inst) {
  // Without this first invariant, passing a non-DOM-component triggers the next
  // invariant for a missing parent, which is super confusing.
  !(inst._hostNode !== undefined) ? process.env.NODE_ENV !== 'production' ? invariant(false, 'getNodeFromInstance: Invalid argument.') : _prodInvariant('33') : void 0;

  if (inst._hostNode) {
    return inst._hostNode;
  }

  // Walk up the tree until we find an ancestor whose DOM node we have cached.
  var parents = [];
  while (!inst._hostNode) {
    parents.push(inst);
    !inst._hostParent ? process.env.NODE_ENV !== 'production' ? invariant(false, 'React DOM tree root should always have a node reference.') : _prodInvariant('34') : void 0;
    inst = inst._hostParent;
  }

  // Now parents contains each ancestor that does *not* have a cached native
  // node, and `inst` is the deepest ancestor that does.
  for (; parents.length; inst = parents.pop()) {
    precacheChildNodes(inst, inst._hostNode);
  }

  return inst._hostNode;
}
```
#### Example argument `inst`
```
inst: {
    _currentElement: Object,
    _domID: 126,
    _flags: 1,
    _mountImage: null,
    _mountIndex: 0,
    _namespaceURI: "http://www.w3.org/1999/xhtml",
    _nativeContainerInfo: Object,
    _nativeNode: span.text-muted.m-l-xs,
    _nativeParent: f,
    _previousStyle: null,
    _previousStyleCopy: null,
    _renderedChildren: Object,
    _rootNodeID: 124,
    _tag: "span",
    _topLevelWrapper: null,
    _wrapperState: null
};
```
I'd like to get some thoughts on the best way to handle this. Whether it be a fix to `react-dom` or a fix to `react-bootstrap`.

**Comment by jquense** [comment]
You mismatched or duplicate versions of react and react Dom. Judging from my limited knowledge of the react internals you have an old version of react-dom and newer React. Make sure your installed versions are compatible

**Comment by jhdielman** [comment]
I'm using both latest versions of React and ReactDom 15.5.4.

**Comment by jquense** [comment]
I'd check again, you definitely have an old version somewhere, `_nativeNode` property doesn't exist in the newest v15 of React

**Comment by jhdielman** [comment]
I've checked. It actually works if I downgrade to 15.1.0. I've tried this multiple times. I've deleted he node modules and reinstalled with latest versions. When I place a breakpoint at the line checking for `inst._hostNode !== undefined`, all the parent instances contain _hostNode until it gets to the span. This happens for the children of OverlayTrigger.

**Comment by jquense** [comment]
that behavior _really_ suggests that you have an older version of React nested somewhere in your node_modules. In any case even if it was a bug it'd be a bug in React not react-bootstrap :)

**Comment by jhdielman** [comment]
Good point, either way it does point to React. I shall dig deeper good sir! Many thanks for your help :).
