### ISSUE TITLE
[Modal] onExit, onExited, onExiting do not work

### ISSUE THREAD

**Issue by tuanna30** [react-bootstrap/react-bootstrap#2653]
I can't get 3 functions onExit, onExited, onExiting working on Modal. Any idea?

Thanks

**Comment by jquense** [comment]
They are animation callbacks so only work if you specify a Transition component

**Comment by rjworks** [comment]
> They are animation callbacks so only work if you specify a Transition component

How do i specifiy a transition component?

**Comment by rjworks** [comment]
> I can't get 3 functions onExit, onExited, onExiting working on Modal. Any idea?
> 
> Thanks

did you find a fix?
