### ISSUE TITLE
Modal responsiveness is missing

### ISSUE THREAD

**Issue by idangozlan** [react-bootstrap/react-bootstrap#2654]
Right now, there's no way to give Modal wrapper class names, that means that responsive classes can't be added.

**Comment by jquense** [comment]
Hi, you can add dialogClassName for this, per the documentation

**Comment by idangozlan** [comment]
This is not a good solution, since modal has backdrop, so you can't apply class that will hide it. Please reopen the issue.

**Comment by jquense** [comment]
I see, that's not really a supported pattern, if you want to conditionally show or hide a modal, I'd use the `show` prop.

**Comment by idangozlan** [comment]
That's not solution, all the idea of bootstrap is to use media queries and not JS.

Please open the bug, i will create pull request and will submit it asap.
