### ISSUE TITLE
Hide/Show Modal instead of removing from dom

### ISSUE THREAD

**Issue by nasospsa** [react-bootstrap/react-bootstrap#2655]
Is there a way to hide/show the modal instead of just returning null when the prop show is false?

**Comment by taion** [comment]
Hmm @jquense is this a react-overlays bug?

Can we use `unmountOnExit` to handle https://github.com/react-bootstrap/react-overlays/blob/v0.7.0/src/Modal.js#L253 ?

**Comment by jquense** [comment]
its not a bug, but I don't remember why. I'd assume it's because you'd have issues when there is no Transition.

**Comment by geenino** [comment]
i have missed to import transition css. After import, modal close problem solved for me. Thank you @jquense
