### ISSUE TITLE
how can i get dropdown menuitem's innerhtml

### ISSUE THREAD

**Issue by yokeyang** [react-bootstrap/react-bootstrap#2656]

**Comment by jquense** [comment]
add a ref to the `MenuItem` and get the DOM node, via `findDOMNode()` and the ref.

**Comment by yokeyang** [comment]
@jquense sorry i have 28 MenuItem and if there has no way to do on the outer DropdownButton?

**Comment by yokeyang** [comment]
@jquense or can i get eventKey of the MenuItem?

**Comment by jquense** [comment]
there are lots of ways to get the DOM nodes and and then navigate to the menu item you want..this use case is really outside the normal React idioms though so I'm not sure how to make it easier for you. You'll have to explore yourself unfortunately :/
