### ISSUE TITLE
Pager: how to detect what button(next or previous) was clicked

### ISSUE THREAD

**Issue by SergeyAlexeev** [react-bootstrap/react-bootstrap#2657]
How can I detect what button was clicked? Next or Previous? I've tried to use the `onSelect` function but there isn't any information about it:

    <Pager
       onSelect={(page, event) => {
          // event -> there isn't any information about a clicked button
       }}
    >
        <Pager.Item previous />
         {' '}
        <Pager.Item next />
    </Pager>

**Comment by taion** [comment]
Just put `onClick` on the items
