### ISSUE TITLE
CarouselItem.js  TransitionEvents Problem

### ISSUE THREAD

**Issue by suweya** [react-bootstrap/react-bootstrap#2658]
in CarouselItem.js line: 50  - use setTimeout(()=>{}, 0)  the effect is not good, there is no good way?
```js
import TransitionEvents from './utils/TransitionEvents';

// TODO: This should use a timeout instead of TransitionEvents, or else just
// not wait until transition end to trigger continuing animations.

TransitionEvents.addEndEventListener(
        ReactDOM.findDOMNode(this), this.handleAnimateOutEnd
      );
```

**Comment by suweya** [comment]
I try this code `setTimeout(this._handleAnimateOutEnd, 600)`  & `transition: transform .6s ease-in-out;`  is looks much better, Is that correct?

**Comment by taion** [comment]
The "end event listener" should mostly work anyway barring some edge cases. The choice of which CSS to use is yours.
