### ISSUE TITLE
React Component in Panel header

### ISSUE THREAD

**Issue by gravitycode** [react-bootstrap/react-bootstrap#2659]
When i use React class Components in Panel header, the panel doesn't open. Header render perfectly but when i click him, the panel doesn't expand. The click event doesn't work anymore. It looks like the Panel can not associate click events to the header when it comes to a component. Do I have to do it manually like Controlled PanelGroup? 

I would like to know when the strategy is taken and why of node vs Component.

```
                    <Panel
                        collapsible
                        header={
                            <MyHeader
                                title={'hello'}
                            />
                        }
                    >
                  ...
                  </Panel>
```

Thank you!

**Comment by taion** [comment]
You need to pass through event handlers

Note that this API is getting rewritten though https://github.com/react-bootstrap/react-bootstrap/pull/1769
