### ISSUE TITLE
Using Overlay & Popover in div that has scaling transform bad position

### ISSUE THREAD

**Issue by Michael-Tajmajer-Emrsn** [react-bootstrap/react-bootstrap#2661]
I'm using an  Overlay + Popover in a div that has xscale/yscale applied.  When not at 1.0 scale, the position of the Popover is invalid.  It's to far away from the target.

The fiddle shows it when there are scrollbars and the view is panned.

https://jsfiddle.net/pvzb0pLy/1/

![position](https://user-images.githubusercontent.com/26899055/26997028-300e37e0-4d3c-11e7-84ef-abc625d6075d.png)

I searched for the positioning logic in the source code but was unable to find it -- if somebody can point me towards this, I can try to find a clue :-)

**Comment by taion** [comment]
The position calculation logic is in react-overlays, not here.
