### ISSUE TITLE
Unnecessary re-render 

### ISSUE THREAD

**Issue by vinityad** [react-bootstrap/react-bootstrap#2662]
I started using components like Row Col in my project, After I added https://github.com/garbles/why-did-you-update to check what is being re-rendered unnecessarily. And found that Row and Col re-renders itself even if there is no change to state/props. Is it just me noticed this or this lib do not care about re-rendering?

**Comment by taion** [comment]
Please search issues before opening a new one: https://github.com/react-bootstrap/react-bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue%20shouldComponentUpdate
