### ISSUE TITLE
Using react-bootstrap with redux-form

### ISSUE THREAD

**Issue by aikidoshi** [react-bootstrap/react-bootstrap#2663]
I love redux-form, but it frustrated me that I could not get a complete set of fields working properly with react-bootstrap, so when I finally did work it all out I created Steve's Opinionated React Project - https://github.com/aikidoshi/Opinionated

It is a starter kit with all of the necessary tools in place in the form of a real-world application complete with SQL Server database and a Web API as well.

It showcases beautiful redux forms, with every common react-bootstrap input field type fully working.

I'm not sure how best to spread the word though.

**Comment by skwon-mdsol** [comment]
No offense, but not sure if this is the best place to spread the word about your project. Kudos for creating the starter-kit though

**Comment by jquense** [comment]
I wouldn't worry to much about it if the project maintainers don't say anything :)

thanks for the info, I'm gonna close this tho as there is nothing actionable here.
