### ISSUE TITLE
OverlayTriggers should swallow click events, using stopPropagation

### ISSUE THREAD

**Issue by csillag** [react-bootstrap/react-bootstrap#2664]
I am seeing a behavior which I find counter-intuitive.
If I place an [OverlayTrigger](https://react-bootstrap.github.io/components.html#custom-overlays) within a DIV which also has it's own click handlers, and I click on the overlay trigger, I expect the overlay to open, but I don't expect the other click handler to fire.

This would be the case if the click handler of the overlay trigger would call `stopPropagation()` on the event, but it doesn't. Is this a bug? Or can I configure it somehow to do this? If so, I couldn't find the option.

Thanks.

**Comment by taion** [comment]
You can add your own `onClick` and call `stopPropagation` yourself. This doesn't make sense as a general default.

**Comment by rtmann** [comment]
You can't add onClick handlers to overlay triggers, you add them to overlays which makes overlay triggers unusable when you need to click to stop event propagation.  OverlayTrigger should have a property called "eventBubble" that defaults to true that we can set to false to prevent event propagation on OverlayTriggerTypes "click" | "hover" | "focus".

**Comment by daviddwmd** [comment]
+1
