### ISSUE TITLE
Large bundle size in production build

### ISSUE THREAD

**Issue by bgazzera** [react-bootstrap/react-bootstrap#2665]
Hi, I have been using react-bootstrap (0.31.0) in a create-react-app (v1.0.7) app.

I have been careful to import each component referencing the individual component inside /lib like so:
`import Grid from 'react-bootstrap/lib/Grid';`

I ran a [bundle analyzer](https://github.com/chrisbateman/webpack-visualizer) and found that inside the bundle, webpack added all of the files inside the /node_modules/react-bootstrap/es folder. This adds 287KB to the bundle. The /lib components add just 37KB and I can see the individual components I imported there, and not all the rest.

<img width="367" alt="screen shot 2017-06-14 at 5 42 42 pm" src="https://user-images.githubusercontent.com/6751553/27154084-26f97ea2-512a-11e7-9d54-72b351b8f1ee.png">

Is there a way to avoid bundling the /es folder? 
Thanks in advance!

**Comment by taion** [comment]
Check again – you probably still do have something pulling in the top-level `react-bootstrap` package. Nothing in `lib/` references `es/`.
