### ISSUE TITLE
Modal calls 'onHide' with mouseUp outside of modal, possibly should only be if mouse is clicked down outside of modal

### ISSUE THREAD

**Issue by ericdcobb** [react-bootstrap/react-bootstrap#2666]
You can see this behavior with the demo modals here:

https://react-bootstrap.github.io/components.html#modals

Click down inside the modal, then drag your mouse outside of the modal, and let go. The modal closes. 

Compare that to the bootstrap example here:

http://getbootstrap.com/javascript/#live-demo

This occurs for us when we have sliders inside the modal, sometimes while dragging the slider to a min or max value the mouse goes off the edge of the modal and the modal closes.

**Comment by taion** [comment]
please search existing issues before opening new ones

**Comment by woohling** [comment]
Would be nice if you can link the existing issues here.

**Comment by zishon89us** [comment]
> Would be nice if you can link the existing issues here.

https://github.com/react-bootstrap/react-bootstrap/issues/3373

Happy Helping!
