### ISSUE TITLE
When using ListGroups if an item has an onClick property its rendered as button

### ISSUE THREAD

**Issue by Jaredmmx** [react-bootstrap/react-bootstrap#2667]
There are times when such ListGroupItems with an onClick property may have children such as links or buttons. In such cases everything works fine with Chrome but not with IE11 or Firefox

I suggest to publish another property of ListGroupItem that lets the programmer choose whether or not to change 'li' into 'button', 'span' or whatever.

**Comment by taion** [comment]
dupe https://github.com/react-bootstrap/react-bootstrap/issues/983
