### ISSUE TITLE
Modal does not work, not even when mimicking documentation example

### ISSUE THREAD

**Issue by Shirikatsu** [react-bootstrap/react-bootstrap#2669]
I am trying to simply use modal but all attempts of mine have resulted in nothing.

Using the exact same code found in the documentation [here](https://react-bootstrap.github.io/components.html#modals-live) renders a button that does absolutely nothing when clicked.

My own attempts below result in the same thing, a button that does nothing on click.

    class Login extends Component {
        constructor(props){
            super(props)
            this.state = {
                modalShow:true
            }
        }

        render() {
            let modalClose = () => this.setState({ modalShow: false})

            return (
                <div>
                    <Button onClick={() => this.setState({modalShow: true})}>Show</Button>

                    <Modal show={this.state.modalShow} onHide={modalClose} container={this}>
                        <Modal.Body>
                            Elit est explicabo ipsum eaque dolorem blanditiis doloribus sed id ipsam, beatae, rem fuga id earum? Inventore et facilis obcaecati.
                        </Modal.Body>
                    </Modal>

                </div>
            )
        }
    }

**Comment by jquense** [comment]
You probably aren't including the the bootstrap css or there is an error somewhere else on the page, you may not be noticing

**Comment by jquense** [comment]
Note, your above example doesn't work because you aren't passing `modalShow` to the `show` prop of the Modal, you just set it to a static`true` so it will always be visible

**Comment by Shirikatsu** [comment]
Thanks for your response, Jason. You're right about the mistake in the above code, as I pasted a later iteration of modifications in an attempt to force the modal to show. I've since corrected my sample to what it 'should' be.

I checked out your other point and I do indeed have the css included (correctly I believe):
`import 'bootstrap/dist/css/bootstrap.css';`

It seems like a functional screen is brought up as once the button is clicked, hovering over it does not highlight it which suggests an overlay has appeared but invisible. Clicking again seems to remove it and allow access to the button on the page.

I have used the base modal successfully from `import Modal from 'react-overlays/lib/Modal';` but still unable to get react-bootstrap Modal to work.

**Comment by Shirikatsu** [comment]
Above was a styling issue due to stylesheets not actually being included properly.

[Getting started documentation](https://react-bootstrap.github.io/getting-started.html) simply drops a mention of the stylesheet and instructs to 'include' it without specifying for the lesser informed.

To include the styles needed for components to render properly, paste 
    `<!-- Latest compiled and minified CSS --> `
`<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/latest/css/bootstrap.min.css">`
between the `<head>` tags of `public/index.html` file of your React project root directory.
