### ISSUE TITLE
Badge component does not have bsClass attribute

### ISSUE THREAD

**Issue by drwatson1** [react-bootstrap/react-bootstrap#2670]
Badge should have bsClass attribute as written [here](https://react-bootstrap.github.io/components.html#badges-props). 

But index.d.ts looks like:

``` javascript
    // <Badge />
    interface BadgeProps extends React.HTMLProps<Badge> {
        pullRight?: boolean;
    }
    type Badge = React.ClassicComponent<BadgeProps, {}>;
    var Badge: React.ClassicComponentClass<BadgeProps>;
```

**Comment by taion** [comment]
refile on https://github.com/react-bootstrap/react-bootstrap-typescript – TS typings don't live in this repo
