### ISSUE TITLE
Prevent responsive Nav stacking

### ISSUE THREAD

**Issue by naheller** [react-bootstrap/react-bootstrap#2673]
Hi there,

I'm developing a MacOS app that lives up in the menu bar. The window width is restricted to 400px, and I've implemented the Nav and NavItem components. They look like this:

![screen shot 2017-06-23 at 4 02 17 pm](https://user-images.githubusercontent.com/18204925/27503161-a8368dec-582e-11e7-95a9-f39d8e1f78ff.png)

As you can see, the bottom line extends out to the right of the "Settings" NavItem a bit. In an effort to get rid of this, I added the `justified` prop to the Nav component, which results in a stacked appearance:

![screen shot 2017-06-23 at 4 07 48 pm](https://user-images.githubusercontent.com/18204925/27503218-1bc1aaee-582f-11e7-82d7-635dbda4cf4c.png)

Unfortunately, adding the `stacked` prop and setting it to `{false}` does not cause the Nav to display horizontally as it had before. What _does_ cause the `justified` Nav to display properly is widening the window, however this would make the app much too large.

Here is my code:

```
    <Nav justified stacked={false} bsStyle="tabs" activeKey={this.getActiveKey()} onSelect={this.props.handleTabSelect}>
        <NavItem eventKey={1} title="Tracker">Tracker</NavItem>
        <NavItem eventKey={2} title="Submit" disabled={this.checkLock()}>Submit</NavItem>
        <NavItem eventKey={3} title="Past Training">Past Training</NavItem>
        <NavItem eventKey={4} title="Settings">Settings</NavItem>
    </Nav>
```

How can I eliminate that extra line without stacking my NavItems? Your advice is appreciated!

**Comment by taion** [comment]
This is all CSS. There's nothing JS-relevant here.

**Comment by naheller** [comment]
Hi taion,

Thanks for your response. I feel that the functionality of the `stacked` and `justified` props is JS-relevant, and as a newer developer, I'd definitely appreciate any elaboration you could provide.

One question I have is: at a width of 400px, why do the NavItems stack even when I set `stacked` to `{false}`? If there is a way, how can I alter this functionality?

**Comment by jquense** [comment]
All the responsive behavior is in the css, you can alter the css to change it, I'd try stackoverflow.com and the like for info on how to extend and alter bootstrap styles
