### ISSUE TITLE
Nav pullRight is spilling out of the container

### ISSUE THREAD

**Issue by bookercodes** [react-bootstrap/react-bootstrap#2677]
Woah, something really funky is happening with my `Navbar` and `Nav` with `pullRight`:

![](https://www.dropbox.com/s/bwcm45bcfatfh8m/Screenshot%202017-06-28%2017.26.33.png?dl=0)

Link: https://www.dropbox.com/s/bwcm45bcfatfh8m/Screenshot%202017-06-28%2017.26.33.png?dl=0

And here is the code,

```
export default ({ session, children }) =>
  <Layout>
    <div className="container">
      <Navbar collapseOnSelect>
        <Navbar.Header>
          <Navbar.Brand>
            <a href="#">Sessions</a>
          </Navbar.Brand>
          <Navbar.Toggle />
        </Navbar.Header>
        <Navbar.Collapse>
          <Nav pullRight>
            <NavItem eventKey={1} href="#">Link Right</NavItem>
            <NavItem eventKey={2} href="#">Link Right</NavItem>
            {/*<NavDropdown title={session.user.displayName} id="basic-nav-dropdown">
            <MenuItem onClick={logout}>Logout</MenuItem>
          </NavDropdown>*/}
          </Nav>
        </Navbar.Collapse>
      </Navbar>
      <h2>Admin</h2>
      {children}
    </div>
  </Layout>
```

The `container` class is coming from Bootstrap.

And I am using the latest Boostrap:

```
      <link
        rel="stylesheet"
        href="https://maxcdn.bootstrapcdn.com/bootstrap/latest/css/bootstrap.min.css"
      />
```

**Comment by jquense** [comment]
i'd make sure "latest" doesn't point to v4 just to start

**Comment by bookercodes** [comment]
Good shout, it is still version 3. See: https://maxcdn.bootstrapcdn.com/bootstrap/latest/css/bootstrap.min.css

**Comment by bookercodes** [comment]
Update: This happens in Chrome and Safari

**Comment by bookercodes** [comment]
https://www.dropbox.com/s/e98s4lcj7r95l6i/Screenshot%202017-06-28%2017.36.52.png?dl=0

Hm, if I add `margin-right: 15px` to the last menu item, the formatting looks decent again

**Comment by taion** [comment]
This is a CSS issue. It's not an issue with React-Bootstrap JS.

**Comment by bookercodes** [comment]
Happening like this out of the box, mate 😕

**Comment by bookercodes** [comment]
Yeah, fair enough 👍 

In the meantime, here is a work-around for those with the same problem:
```
        <Navbar.Collapse>
          <Nav pullRight>
            <NavDropdown
              title={session.user.displayName}
              id="basic-nav-dropdown"
              style={{
                marginRight: 15
              }}
            >
              <MenuItem onClick={logout}>Logout</MenuItem>
            </NavDropdown>
          </Nav>
        </Navbar.Collapse>
```

(Just need to add `margin-right: 15px` to the last list item, essentially. Weird!)

**Comment by damianfabian** [comment]
Actually this problem is related with the width of the container. Depends in different situations, but it's a css problem.

**Comment by mplis** [comment]
I'm having the same issue, and I don't have any custom styles in my code.

**Comment by damianfabian** [comment]
@mplis take a look on this https://codepen.io/damianfabian/pen/XadQPa maybe It could help you

**Comment by mplis** [comment]
So it looks like this is happening because I'm wrapping my entire page in the `container` class. I believe this causes issues since the `Navbar` component uses the `Grid` component internally, which has its own `container` class.

The possible solutions are:
1. Remove outer `container` class
2. Set `fluid` on `Navbar` component
3. Change outer `container` class to `container-fluid`

Examples here: https://codesandbox.io/s/jqWk8rP4Y
