### ISSUE TITLE
[Feature Request] add device specific text align options to Col element

### ISSUE THREAD

**Issue by zhenyulin** [react-bootstrap/react-bootstrap#2678]
output would be something like ```<Col mdalign="right" smalign="justify"></Col>```

This is quite useful for arranging group navigation elements in places like NavBar, Footer and similar situations. The proposed prop API may not be the best, would be happy to discuss here and potentially put my hands on implement them if being pointed out the right contribution direction.

Thanks.

**Comment by taion** [comment]
Do these classes exist in Bootstrap?

**Comment by skwon-mdsol** [comment]
https://github.com/twbs/bootstrap/issues/11292 Referencing old post from bootstrap itself. I don't think the designers working with bootstrap are ok with device specific text aligns. Unless you can show everyone that bootstrap is actively working on such a features. If else, not sure if it should be implemented.

**Comment by skwon-mdsol** [comment]
any word on this? I feel this one should be closed.

**Comment by taion** [comment]
Oops, missed this. Thanks!
