### ISSUE TITLE
How to add a custom class name to outer div tooltip element?

### ISSUE THREAD

**Issue by binarykitchen** [react-bootstrap/react-bootstrap#2679]
When you use a tooltip like that example here https://react-bootstrap.github.io/components.html#tooltips with `<OverlayTrigger>` and `<Tooltip>` and move your mouse over the button, a new div block is automatically appended to DOM before end of `body` which looks like this for example:

```html
<div><div data-reactroot="" id="ips-tooltip" role="tooltip" class="fade in tooltip top" style="top: 184px; left: 0px;"><div class="tooltip-arrow" style="left: 44.0445%;"></div><div class="tooltip-inner">blahblah</div></div></div>
```

For the app I am working on I need to add a classname to that first `<div>` block for some technical reasons. There is no such prop yet. Is such a feature missing or is there a hidden trick to do so?

**Comment by binarykitchen** [comment]
Probably the solution is here?
https://github.com/react-bootstrap/react-bootstrap/blob/master/src/OverlayTrigger.js#L127
 
```js
  componentDidMount() {
    this._mountNode = document.createElement('div');
    this.renderOverlay();
  }
```

add code to set a classname to that `_mountNode`? If you think that's a good idea, I can do a PR.

**Comment by taion** [comment]
use `<Overlay>` if you need to customize how your overlay works

**Comment by binarykitchen** [comment]
ah, thanks, must have missed that out.
