### ISSUE TITLE
Mouse="pointer" over collapsible panels

### ISSUE THREAD

**Issue by manumid** [react-bootstrap/react-bootstrap#2680]
Mouse should convert to "pointer" when it is over a collapsible panel. Instead, Mouse turns to "text" style. See [https://react-bootstrap.github.io/components.html#panels-accordion](url) for an example.

**Comment by jquense** [comment]
Hi there! That is up to you and your css. We don't make changes to the default bootstrap styles, but if you'd like to add a pointer to the entire panel header, you can do so like: `.panel-header { cursor: pointer; }`, Thanks!
