### ISSUE TITLE
What's the suggested approach for dismissing Alert when onDismiss's `this` is an unmounted component?

### ISSUE THREAD

**Issue by justin-calleja** [react-bootstrap/react-bootstrap#2682]
Hi,

I am passing the `onDismiss` function from a parent component to a child (the child is a wrapper around this project's Alert (it adds Fade to it)).

I am getting the Warning (error) message:

```
setState(...): Can only update a mounted or mounting component.
```

In my parent component, I am using `setState` to set `showAlert` to `false` in the function I'm passing to the child component for `onDismiss`. When the parent is unmounted (e.g. navigating away), and the alert was shown... after a while it's dismissed, `onDismiss` happens... but this function now tries to `setState` on an unmounted component.

I can't find a non-deprecated way of checking if a React component is mounted or not.

Is there a standard approach for dealing with this?

Thank you

**Comment by taion** [comment]
keep track of it yourself; or just cancel the timeout when the thing unmounts

**Comment by justin-calleja** [comment]
@taion thanks - I though the Alert was setting the timeout (since I was passing it `onDismiss` and completely didn't see my own `setTimeout` in render).

I case somebody else comes across this situation - here's one example. 

```js
import React from 'react'
import { Alert as RBAlert, Fade } from 'react-bootstrap'

class Alert extends React.Component {
  componentWillUnmount () {
    if (this.dismissTimeoutId) clearTimeout(this.dismissTimeoutId)
  }

  render () {
    // RBAlert's onDismiss is called when the 'x' on the RBAlert is clicked.
    if (this.props.show) {
      this.dismissTimeoutId = setTimeout(this.props.handleDismiss, 2500)
      return (
        <Fade in timeout={this.props.timeout || 500}>
          <RBAlert bsStyle={this.props.bsStyle || 'success'} onDismiss={this.props.handleDismiss}>
            {this.props.children}
          </RBAlert>
        </Fade>
      )
    } else {
      return null
    }
  }
}

export default Alert
```
