### ISSUE TITLE
[Feature Request] SplitButton - disabled separately for button and dropbutton

### ISSUE THREAD

**Issue by Dammic** [react-bootstrap/react-bootstrap#2684]
Hello,

SplitButton has prop 'disabled', which allows us to control if the SplitButton is disabled or not. The problem with it is that this prop controls both the button and the dropdown button which shows the menu and there is no possibility to control them separately.

It would be great if one could do it - an example use case would be actions, of which the first one appears as the button and all the others appear as menuitems in the menu. Sometimes I would like to disable the button, but still be able to show the menu.

**Comment by jquense** [comment]
We recommend for cases where you need more control or nuance in the api that you use the Dropdown component directly. It's really minimal code over using SplitButton but you can define everything yourself.
