### ISSUE TITLE
Is there any way to may the react-bootstrap modal draggable/ resizeable?

### ISSUE THREAD

**Issue by piu** [react-bootstrap/react-bootstrap#2685]
Hi,

We have been using react-bootstrap 0.29.0 version for Modal dialogs in our application, recently we want to support dragging of the Modal dialogs in our application. There are couple of libraries that we found for making it draggable but for supporting Modal React component most of them has open issues. So it there any way inbuilt in react-bootstrap-modal to support the draggable/ resizable feature through any methods/ props?

If not then is there any plan to add this support to the library in near future? Cause it seems to be the quite a popular feature for Modals these days.

**Comment by jquense** [comment]
Hi there, no there is no support for resizing or dragging modals and plans to add it, since it's not a feature of bootstrap modals. You may be implement those features for your own app by using the API or the lower level react-overlays modal
