### ISSUE TITLE
OverlayTrigger: "manual" trigger results in invalid prop warning

### ISSUE THREAD

**Issue by iUltimateLP** [react-bootstrap/react-bootstrap#2686]
When using the OverlayTrigger manually to just show a popover when a button is clicked, we need to use the "manual" trigger. Example code I am using with this:
```jsx
<OverlayTrigger ref="submitErrorPopover" enabled={false} trigger="manual" placement="right" overlay={errorPopover}>
    <Button id="submit-button" bsStyle="primary" bsSize="large">A button</Button>
</OverlayTrigger>
```
In the browser's console, the following error is shown:
```Warning: Failed prop type: Invalid prop 'trigger' supplied to 'OverlayTrigger'.```
Changing the trigger to "hover" for example doesn't show this error.

**Comment by skwon-mdsol** [comment]
It's because there is no `manual` trigger type. https://github.com/react-bootstrap/react-bootstrap/blob/master/src/OverlayTrigger.js#L25 Just asking but what are you trying to achieve. If you just need to activate your popover with a click, why not just set the trigger to "click"?

**Comment by taion** [comment]
use `null`
