### ISSUE TITLE
'onError' was not passed down in Thumbnail

### ISSUE THREAD

**Issue by Yuyz0112** [react-bootstrap/react-bootstrap#2687]
It looks like we are not passing down 'onError' in Thumbnail component. Users may need that event handler to show a placeholder when image broken.

https://github.com/react-bootstrap/react-bootstrap/blob/master/src/Thumbnail.js#L27

**Comment by skwon-mdsol** [comment]
http://andrewhfarmer.com/detect-image-load/ Or you could detect whether the image loads correctly or not and implement accordingly via a parent component.

**Comment by skwon-mdsol** [comment]
Actually bump for this, makes sense that we should pass down onError and onLoad props. I can take a stab at this?

**Comment by jquense** [comment]
go for it @skwon-mdsol 👍  thanks

**Comment by taion** [comment]
fixed in #2691
