### ISSUE TITLE
Adding Live Search to Select form item

### ISSUE THREAD

**Issue by batjko** [react-bootstrap/react-bootstrap#2688]
Hi there,

Bootstrap supports the `data-live-search` attribute on select inputs:

![image](https://user-images.githubusercontent.com/7287076/27863414-efd1af86-6181-11e7-8706-1935b72ffbcc.png)

I haven't found this in React-Bootstrap, though.
Could we add this as an extra prop somehow?

e.g. like this:

![selection_031](https://user-images.githubusercontent.com/7287076/27863529-6dccc966-6182-11e7-9bf8-5b230f5cddf0.png)

I'm open to other solutions as well.

**Comment by skwon-mdsol** [comment]
This looks like http://ericgio.github.io/react-bootstrap-typeahead/. Unless you really need the search bar inside the dropdown?

**Comment by jquense** [comment]
> Bootstrap supports the data-live-search attribute on select inputs:

I don't think that's true of vanila bootstrap@3...could you link to the bootstrap docs where they say that? thanks!

**Comment by taion** [comment]
It's bootstrap-select actually. Not part of upstream TWBS

**Comment by batjko** [comment]
> It's bootstrap-select actually

Yes, apparently. Sorry, I must have mixed up my sources. 
Still, I don't see why that's a reason not to even consider it.

**Comment by jquense** [comment]
As a general rule the scope of this project is to implement bootstrap in react. Something like a type ahead is very complicated and would be (and is!) be suited for it's own library, just like bootstrap-select is separate from bootstrap

**Comment by batjko** [comment]
It's fairly easy to implement, though. When I couldn't find this available, I just added an input field on top of the select and wrapped both with a parent component to be able to pass state from the input to the select (i.e. filtering the select options by whatever is typed in the input)...

Would be a few hours max, to do it properly, no? I might be misunderstanding, but I do get the argument that this project wants to stick to Bootstrap-only scope. Fair enough.

**Comment by amitshahc** [comment]
This is not typeahead feature. this should be working using `data-live-search` attribute same as there in bootstrap. but how to add it is the question.
