### ISSUE TITLE
Removing focus from 'Tab' when changing activeKey

### ISSUE THREAD

**Issue by FBosler** [react-bootstrap/react-bootstrap#2689]
I have the following:

```
handleSelect(key) {
	history.push("/Home",{'category':key})
}

<Tabs activeKey={this.state.selectedCategory} onSelect={this.handleSelect} id="SportOrSocialSelector">
  <Tab eventKey={'sports'} title="SPORT"><EventSubcategoryPicker chosenEventCategory={'sports'}/></Tab>
  <Tab eventKey={'social'} title="SOCIAL"><EventSubcategoryPicker chosenEventCategory={'social'}/></Tab>
</Tabs>
```

I implemented history to get access to location.state to enable timewalking (i.e. using the back button on the browser to navigate back in the selection). this.state.selectedCategory also gets updated through a listener on location changes (i.e. triggered by handleSelect or the back button).

This does work fine on clicks on the Tabs. It works somewhat fine on clicking the browser back button as the selected Tab changes and also the respective content is displayed. However, the previously selected tab would receive focus and therefore the styles associated with a:focused. This is only a cosmetic issue, but looks a bit silly.

Cheers

**Comment by taion** [comment]
If you want to manage focus, you'll need to add code (e.g. in `componentDidUpdate`) to manage focus

**Comment by FBosler** [comment]
Could you add a little bit more of color? Do you mean in TabPane? See below the code from TabPane.js

  ```
TabPane.prototype.componentDidUpdate = function componentDidUpdate() {
    if (this['in']) {
      if (!this.shouldBeIn()) {
        // We shouldn't be active any more. Notify the parent.
        this.handleExited();
      }
    } else if (this.shouldBeIn()) {
      // We are the active child. Notify the parent.
      this.handleEnter();
    }
  };
```
