### ISSUE TITLE
offsetBottom doesn't appear to work with AutoAffix component?

### ISSUE THREAD

**Issue by CoreyDH** [react-bootstrap/react-bootstrap#2692]
This appears to be working correctly with the Affix tag, but the AutoAffix tag doesn't properly stop the affixing X pixels from the bottom. 

`<AutoAffix
        viewportOffsetTop={50}
	offsetBottom={150}
	container={this.parent}>`

**Comment by skwon-mdsol** [comment]
Shouldn't this issue be in https://github.com/react-bootstrap/react-overlays?

**Comment by CoreyDH** [comment]
Whoops, you're right! Let me make it there.
