### ISSUE TITLE
Doc files line wrap

### ISSUE THREAD

**Issue by cyanliu** [react-bootstrap/react-bootstrap#2700]
As I was reviewing the comments on my previous PR (#2695), I was wondering if there was a set rule for whether lines should be hard or soft wrapped. Some .js files (namely `docs/src/NavbarSection.js` and `docs/src/ModalSection.js` seem to have both hard wraps and longer lines, although the latter of the two has some unusually long line lengths (up to 155 characters)).

**Comment by taion** [comment]
I personally prefer no wrapping, because I soft wrap in my editor, but I'd be interested to hear what others think.

**Comment by taion** [comment]
(I used to prefer imposing line limits back before I turned on line wrap in my IDE, though.)

**Comment by jquense** [comment]
I wouldn't mind if we had a recommended line length for docs at least. It's a pain to be strict about since it makes copy editing more annoying but a general recommendation for shorter lines seems reasonable. 

We could just use prettier alternatively and let it do the work

**Comment by cyanliu** [comment]
I also personally prefer just using the soft wrap within my editor, and I'm worried that editors like myself and @taion might have an interesting time copy editing with soft wraps and hard line breaks. 


(but I wanted to bring up a discussion about it before just moving forward with my personal preferences)
