### ISSUE TITLE
Popover doesn't work on mobile on first tap

### ISSUE THREAD

**Issue by povtasci** [react-bootstrap/react-bootstrap#2709]
I have items on the page like this
```
<OverlayTrigger trigger={['hover', 'focus']} placement="top" 
     overlay={<Popover id={`member-info-${index}`}>{member.info</Popover>}>
     <div className="team-member">
         ...
     </div>
</OverlayTrigger>
```

all is working well on desktop by hover, but when I'm trying it in mobile and tap on one of the items the popover doesn't appear. when tap on another item it appears and all item start work well.

any idea how to fix ?

**Comment by taion** [comment]
If you want to respond to taps, use "click" as the event.

**Comment by ChampionRoy** [comment]
Same situation here. And use "click" event as trigger value already.

**Comment by chimit** [comment]
The problem still exists. I need a simple behavior: on desktop show it on hover, on mobile show it on tap. To make it possible I set:
```javascript
trigger={['hover', 'click']}
```
On desktop it works, but on mobile a popover appears only after the second tap.

The same behavior if I set all 3 events:
```javascript
trigger={['hover', 'focus', 'click']}
```

@taion please reopen this.

**Comment by williangd** [comment]
I'm having the same problem react-bootstrap@1.6.6
