### ISSUE TITLE
Modal component doesn't work with the react 16 alpha code

### ISSUE THREAD

**Issue by brollins90** [react-bootstrap/react-bootstrap#2712]
While testing an upgrade to react 16 alpha I saw that the modal component doesn't load properly.  I made a small repro with create react app at https://github.com/brollins90/modal-ref.  

It looks like `setModalNode` https://github.com/react-bootstrap/react-overlays/blob/master/src/Modal.js#L404 is never getting called after the update to react 16.

I would be happy to look into this some more if you have any insight as to where to look.
Thanks

**Comment by jochenberger** [comment]
See https://github.com/react-bootstrap/react-overlays/issues/188

**Comment by brollins90** [comment]
This is a duplicate of https://github.com/react-bootstrap/react-overlays/issues/188.  Thanks!
