### ISSUE TITLE
ReactBs 1.0 roadmap - styleMaps roadmap item needs update

### ISSUE THREAD

**Issue by Inlesco** [react-bootstrap/react-bootstrap#2714]
Hey guys!

Just wanted to contribute to this fantastic lib and get familiar with the components one by one first. Preferably, starting with the simpler tasks while gaining more knowledge about the internals.

I noticed that the StyleMaps roadmap item needs an update (https://github.com/react-bootstrap/react-bootstrap/wiki#100-roadmap) - the link of `styleMaps.js` is dead. I've looked into the current state of the repo and, from what I've gathered, `styleMaps.js` file has become `StyleMaps.js` in `/src/utils`? Is that correct?

Also, it'd be great if someone provided more detail on the `styleMaps` bullet point because it may not be clear enough what needs to be done. Thanks!

**Comment by taion** [comment]
Thanks! I checked off that item – I believe the work there is now complete, since those styling things have now been moved to the individual components.
