### ISSUE TITLE
Some kind of pop up that disappears

### ISSUE THREAD

**Issue by dschinkel** [react-bootstrap/react-bootstrap#2716]
I've looked at the components page.  I'm looking for some kind of really small confirmation popup after a user clicks a button where I'll show a message showing success or failure.  I need it to just pop up for x seconds and fade and then disappear.  Is there any way to do this with the current library?  What component if so would work best for this?

I need this to gracefully happen without interrupting the flow of the elements on the page (doesn't move surrounding elements..basically a layover or something)

I suppose I need a transition with maybe an overlay together or something like that.

What I kinda want is something like this and to fade the overlay out after x seconds using a transition or something...I'll put something like `some success message`

<img width="208" alt="screen shot 2017-07-18 at 10 30 27 pm" src="https://user-images.githubusercontent.com/338798/28349500-cdf6ec32-6c08-11e7-9081-048565df7baa.png">

I don't really want an overlay though because they'd have to mouse over to see it.  What would be nice if I got an overlay effect that I could trigger programmatically in JS in my React component based on some prop check.

**Comment by taion** [comment]
This isn't a Bootstrap primitive. Just set up the timeouts yourself.

**Comment by dschinkel** [comment]
is there a way to force the overlay to show on demand?

**Comment by dschinkel** [comment]
eh I guess a popover is what I really need thx.
