### ISSUE TITLE
Bootstrap Sidebar

### ISSUE THREAD

**Issue by Galti** [react-bootstrap/react-bootstrap#2717]
Is there a sidebar component in "react-bootstrap"? Or is there a component through which I can get Sidebar? I want to create [SB-Admin's](https://blackrockdigital.github.io/startbootstrap-sb-admin-2/pages/index.html) sidebar. 

https://drive.google.com/file/d/0B0GoElBnJs5yc1RtSnI0NGt5MEk/view?usp=sharing

**Comment by taion** [comment]
There's no such component in Bootstrap, so there will be no such component here.
