### ISSUE TITLE
Uncontrolled Tabs not updating props in child components

### ISSUE THREAD

**Issue by dnbr2002** [react-bootstrap/react-bootstrap#2720]
So my issue is I am using tabs.  The tabs have child components.  When the state of a prop Im passing to the child from the parent changes, there doesn't seem to be an on onChange happening.  The child component  isn't getting the updated state changes from the parent.  Based on what Im seeing in my React Chrome extension the tabs appear to be uncontrolled?
![tabs](https://user-images.githubusercontent.com/19315113/28376374-f8227f34-6c77-11e7-81a4-afe4bec6be35.jpg)

This seems to be the desired effect for uncontrolled objects in react based on these articles. The links seem to confirm the behavior of the uncontrolled objects in React is 'as designed', in short, they will not get an onChange automatically like controlled elements when state changes.
  
https://discuss.reactjs.org/t/how-to-pass-in-initial-value-to-form-fields/869/5

https://facebook.github.io/react/docs/uncontrolled-components.html

So my question is there a way to make the tabs controlled so they will generate a render when the parent updates the state of prop in the child?  If not, how should I update the state??

Relevant code.

In the parent component (Convert), I have the tabs with the child component (TestConvert)where I pass in the state.populatedTestSchema object as  prop. 

``` <Tabs defaultActiveKey={1} id="Mytabs">
         {/*Test Convert Form*/}
             <Tab eventKey={1} title="Test Convert">
              <TestConvert schema={this.state.populatedTestSchema} uiSchema={testUISchema} fetchTarget={this.props.fetchTarget} />
               </Tab>
      </Tabs>

```

The problem is TestConvert will render before Convert.  Convert should trigger a rerender in TestConvert since this.state.populatedTestSchema is updated in CDM in Convert but it doesn't, because I think these are uncontrolled tabs.  Im not saying this is a bug.  It maybe by design in React-Bootstrap.  But how should I update my child component if that is the case.  Preferrably, I'd rather just make the tabs controlled, in which case React would take care of the onChange automatically and I wouldn't have to do anything.  In my case the data that is changing is the fetched data for some dropdown menus.  I would really appreciate any advice.  Thanks

**Comment by taion** [comment]
The tabs don't meaningfully interact with your form at all. You're misunderstanding the intention of `onChange` – it's for native form elements, and it fires on user interaction. There is no `onChange` for our tab components themselves.

**Comment by dnbr2002** [comment]
@taion  So im not sure why this closed so quickly, I don't really understand your response.  Are the tabs in React-Bootstrap uncontrolled?  Is this why if I have a state value in the parent that gets passed as a prop in the tab to  the child component not getting updated?  Is there a way to make the tab controlled?  If not what is the best methodology for updating prop Im passing the tab?

**Comment by dnbr2002** [comment]
Just leaving some info for anyone else that might want to know more about controlled or uncontrolled tabs.  We stopped used the ReactBootstrap tabs and started using React-Tabs (https://github.com/reactjs/react-tabs#controlled-mode).  The information was pretty clear regarding controlled and uncontrolled behavior with the tabs.

**Comment by jquense** [comment]
@dnbr2002 the tabs can be either controlled or uncontrolled. But that isn't related to Forms at all, it just means you can _control_ which tab is shown via state in the parent the props that do that are 'activeKey' and `onSelect`, there is no `onChange`.

**Comment by dnbr2002** [comment]
@jquense, I wasn't asking a question about forms.  I was asking a question about controlled vs uncontrolled tabs in React Bootstrap.  I got no help on that here.  So I found this information for React-Tabs which was clear and wanted to at least leave some helpful information.  We switched to these tabs.  Our dropdowns on our form are not having issues from the props we pass in the tabs anymore now so to say there is no relationship, Id say I disagree.  Really im not sure why someone couldn't just point me in the direction of more specific information regarding controlled and uncontrolled tabs in React-Bootstrap.  Really thats all I was asking.

**Comment by jquense** [comment]
> Really im not sure why someone couldn't just point me in the direction of more specific information regarding controlled and uncontrolled tabs in React-Bootstrap. Really thats all I was asking.

I'm sorry, I was trying to do that. Also the documentation about tabs provides examples for both controlled and uncontrolled tab usage here: https://react-bootstrap.github.io/components.html#tabs

**Comment by dnbr2002** [comment]
Yeap.  And it seems I missed that somehow.  I did look, at least I thought I did.  Thank you for the helpful link @jquense.  I'll compare it to the React-Tab Im using now  which does the same basic thing to make the tab controlled.  Very similar.
