### ISSUE TITLE
ToggleButtonGroup component does not implement verticle prop

### ISSUE THREAD

**Issue by JeremiahDotNet** [react-bootstrap/react-bootstrap#2721]
Adding the prop to the ToggleButtonGroup component and passing that prop to the ButtonGroup component's active prop should work. Then ToggleButtonGroup will more accurately reflect the functionality of the ButtonGroup component.

**Comment by taion** [comment]
Let's track this in https://github.com/react-bootstrap/react-bootstrap/pull/2719.
