### ISSUE TITLE
Overlay not positioning

### ISSUE THREAD

**Issue by matiasgarcia** [react-bootstrap/react-bootstrap#2722]
I am not sure if this a bug or not, but giving the following code:

```
const Test = (props) => {
  var popover = (
    <ReactBootstrap.Popover id={this.props.voteId}>
      {_.map(this.props.names, (n, index) => <p key={index}>{n}</p>)}
    </ReactBootstrap.Popover>
  );

  return (
    <ReactBootstrap.OverlayTrigger
      trigger={['hover', 'focus']}
      placement="top"
      overlay={popover}>
      {this.props.children}
    </ReactBootstrap.OverlayTrigger>
  )
};
```

If the names array changes while the OverlayTrigger is displaying the popover, it's position will be misaligned, is there anyway to change this?

![image](https://user-images.githubusercontent.com/2261869/28384611-b468bd3e-6c9b-11e7-8e45-a25111a25238.png)

![image](https://user-images.githubusercontent.com/2261869/28384629-bd679f90-6c9b-11e7-95cb-687b182e344f.png)

**Comment by taion** [comment]
Please see existing issues on automatic repositioning of overlays.
