### ISSUE TITLE
ToggleButton and ToggleButtonGroup are not exported in v0.31.1

### ISSUE THREAD

**Issue by ChuckIrvine** [react-bootstrap/react-bootstrap#2724]
After installing react-bootstrap with:

`npm install react-bootstrap --save`

and importing it into my project file with:

`import {ToggleButton, ToggleButtonGroup} from 'react-bootstrap';`

I get the following compilation error when trying to use:

```
 <ToggleButtonGroup type="radio" name="options" defaultValue={1}>
          <ToggleButton value={1}>
            Radio 1 (pre-checked)
          </ToggleButton>
          <ToggleButton value={2}>Radio 3</ToggleButton>
          <ToggleButton value={3}>Radio 3</ToggleButton>
</ToggleButtonGroup>
```

`2:10-27 'react-bootstrap' does not contain an export named 'ToggleButtonGroup'.`

**Comment by taion** [comment]
This was already fixed on master in https://github.com/react-bootstrap/react-bootstrap/pull/2704

**Comment by tmm1** [comment]
Could we get a new release with this fix?
