### ISSUE TITLE
Allow multiple bgStyle on a Button

### ISSUE THREAD

**Issue by anativ** [react-bootstrap/react-bootstrap#2725]
I want to create a 'red' link
So I try to do:
```xml
<Button  bsStyle="link danger">
```
This works but I get a warning
```
Warning: Failed prop type: Invalid prop `bsStyle` of value `link danger` supplied to `Button`, expected one of ["success","warning","danger","info","default","primary","link"].
```

Thanks,

**Comment by jquense** [comment]
Hi there, we don't allow this because the styles really don't support it. In this case it may seem to work but that's accidental not intended. In general styles are all mutually exclusive
