### ISSUE TITLE
ToggleButtonGroup requires polyfill for IE (any version)

### ISSUE THREAD

**Issue by richardwilko** [react-bootstrap/react-bootstrap#2729]
ToggleButtonGroup uses [Array#includes](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Array/includes), which requires a polyfill for IE (any version).

Not sure if this is intended or a mistake, so flagging up to you.

**Comment by taion** [comment]
Thanks for the bug report. Care to PR a fix?

**Comment by taion** [comment]
Actually I'll fix it.

**Comment by taion** [comment]
@jquense got to it before me
