### ISSUE TITLE
React-bootstrap duplicates a <Modal/> on dom.

### ISSUE THREAD

**Issue by soulclown** [react-bootstrap/react-bootstrap#2730]
I noticed a strange behaviour . 
When i render a Modal component, it is duplicated.

I noticed i'm not the only one who got this problem:
https://stackoverflow.com/questions/44761650/react-bootstrap-duplicated-modal-components

Any tips how to fix the issue?

Thank you,
Andrea.

**Comment by taion** [comment]
This is most likely a bug in your code, where you're mounting your component that renders the modal more than once. If you have a repro, though, we'd be glad to look at it.

**Comment by soulclown** [comment]
I'm not sure about it, I realize this happens when you declare a Modal inside a wrapper, for example:

```
const ChildrenWrapper = ({children}) => {
  return <div>{children}</div>
}
```

And the modal is a child in the wrapper:
```
const ModalWrapped= ({}) => {
return <ChildrenWrapper>
                 <Modal show={true}>some content</Modal>
           </ChildrenWrapper>
}
```

Than the App :

```
const App = () => {
   return <ModalWrapper/>
}
```

The result is that the instance of the Modal is rendered 2 times in the virtual dom.

I'm very courious to discuss about this approach :)
Thank a lot for your answer.

**Comment by jquense** [comment]
IS there actually two Modals or do you only see 2 in the React Devtools? The latter case is probably due to Modals using a portal to render the DOM components outside the body of the document, and so you see two things called "Modal" but really it's two different parts of the Modal with the same name.

**Comment by soulclown** [comment]
It's actually 2 modals, this is the final virtual dom:
```
<body>
  <div id="root"></div>  // react root
  <script src="/main.js"></script>  // webpack bundle
  <div>...</div> // first modal rendered
  <div>...</div> // second time modal rendered
</body>
```

Can be possible that `<Modal/>` component is rendered first time when is founded in the return statement of `<ModalWrapped/>` , than the second time once the `<ChildrenWrapper/>` render its own children?

**Comment by flygis** [comment]
I am having this issue as well, and my modal is only wrapped by the container component. I have a strong feeling that it is not because of my code, but I can't be sure. Hard bug to trace.

**Comment by soulclown** [comment]
I solved the issue moving all modals to a top level, controlling them with a state manager instead (Redux or MobX).

**Comment by flygis** [comment]
I am using redux, I can't move the modal anywhere higher, though.

**Comment by suhailaleryani** [comment]
Hi, I solved this by wrapping the modal html inside a div.
```
<div className="some-modal-container">
   <div className="modal ..."> ........ ...... ...... </div>
</div>
```

Hope this help anyone

**Comment by kyletsang** [comment]
@RobertSigma can you post a repro on CodeSandbox?

**Comment by Ghadahb** [comment]
Had the same issue. I solved it by wrapping the modal in a <View> at the bottom of my code. (after the last view) Just make sure there isn't another View below it

**Comment by pinguluk** [comment]
I had the same or similar issue, where my modal would be rendered twice
https://github.com/mui/material-ui/issues/24641#issuecomment-1729167309

**Comment by kalekachali** [comment]
Still facing a similar issue. My modals are being rendered twice in the DOM.
Please help.
<img width="1042" alt="Screenshot 2023-11-06 at 07 37 11" src="https://github.com/react-bootstrap/react-bootstrap/assets/9469970/886a56b4-2e18-47ac-8137-e5230022c145">

**Comment by kalekachali** [comment]
Well, I'm using react, not webpack.
The modal mounts once on some occasions but on others it mounts twice as seen above.

**Comment by kalekachali** [comment]
> > Still facing a similar issue. My modals are being rendered twice in the DOM. Please help. <img alt="Screenshot 2023-11-06 at 07 37 11" width="1042" src="https://user-images.githubusercontent.com/9469970/280595804-886a56b4-2e18-47ac-8137-e5230022c145.png">
> 
> have you looked into the webpack configuration? [mui/material-ui#24641 (comment)](https://github.com/mui/material-ui/issues/24641#issuecomment-1729167309)

Well, I'm using react, not webpack.
The modal mounts once on some occasions but on others it mounts twice as seen above.
