### ISSUE TITLE
Carousel broke down when tab is backgrounded

### ISSUE THREAD

**Issue by ash-developer** [react-bootstrap/react-bootstrap#2733]
It happens in Safari browser (my version: 10.0.3 (12602.4.8))

1. open page with carousel (example: https://react-bootstrap.github.io/components.html#carousels)
2. go to any other tab
3. wait for a while (I think for carousel period time)
4. go back
5. carousel doesn't work

sorry, didn't see answers before at https://github.com/react-bootstrap/react-bootstrap/issues/2535
still can reproduce this bug, recorded it https://www.dropbox.com/s/nj9yorlkncuhqc1/carousel-bug.mov?dl=0

**Comment by taion** [comment]
We can't do anything here without a repro.
