### ISSUE TITLE
Modal: isMounted is deprecated.

### ISSUE THREAD

**Issue by ademahendra** [react-bootstrap/react-bootstrap#2736]
I'm working with react-bootstrap modal and I've got error  
`Warning: Modal: isMounted is deprecated. Instead, make sure to clean up subscriptions and pending requests in componentWillUnmount to prevent memory leaks`  
I've been following this guide   
https://react-bootstrap.github.io/components.html#modals-live

**Comment by taion** [comment]
That's in your code. We don't call `isMounted` anywhere.

**Comment by carlos-max** [comment]
The dependency react-overlays calls the isMounted method (Latest version 0.8.0), so the issue is not on ademahendra's code.

**Comment by taion** [comment]
No it doesn't: https://github.com/react-bootstrap/react-overlays/search?utf8=%E2%9C%93&q=isMounted&type=

**Comment by 3plusalpha** [comment]
@ademahendra you have an outdated version of react-bootstrap. I faced the same issue and in fact isMounted was called in previous versions. Updating to the latest version fixed the issue.

**Comment by qnodesign** [comment]
The latest version supposingly is the 0.31.2 but in fact it contains the react-overlays 0.7.0 which still contains the isMounted.

Where did I do the mistake?

FTR: I have the same warning on my app.

**Comment by taion** [comment]
That's incorrect. v0.7.0 of react-overlays does not call `isMounted`.

**Comment by qnodesign** [comment]
https://github.com/react-bootstrap/react-overlays/blob/v0.7.0/src/Modal.js

enforceFocus = () => {
    let { enforceFocus } = this.props;

    if (!enforceFocus || !**this._isMounted** || !this.isTopModal()) {
      return;
    }

    let active = activeElement(ownerDocument(this));
    let modal = this.getDialogElement();

    if (modal && modal !== active && !contains(modal, active)) {
      modal.focus();
    }
  };

At least the browser throws the error because of this line.

**Comment by taion** [comment]
Yeah, no, that's not what's happening. Look again. That's an instance field. It's not calling the `this.isMounted()` that's going away.

**Comment by ZephD** [comment]
To answer the confusions:

`this._isMounted` is NOT the react `this.isMounted()`

`this._isMounted` is React-Bootstrap's custom _instance_ boolean to track the mounted state.
It is set `true` in `componentDidMount` and `false` in `componentWillUnmount`, [as is encouraged](https://reactjs.org/blog/2015/12/16/ismounted-antipattern.html):

> Just set a _isMounted property to true in componentDidMount and set it to false in componentWillUnmount, and use this variable to check your component’s status.

**Comment by zaraustra** [comment]
Hello, I read the topic as I'm having the error as well. I double checked the packages of each module and react-bootstrap@0.31.5 still uses react-overlays: "^0.7.4".
Is there a specific reason the package is not updated to the latest 0.8.3 ?

**Comment by searchMeOut** [comment]
s
