### ISSUE TITLE
PropTypes warning on OverlayTrigger

### ISSUE THREAD

**Issue by psachs21** [react-bootstrap/react-bootstrap#2739]
I've noticed that OverlayTrigger has strange proptypes for onHide and show. They are set to PropTypes.oneOf([null]) despite being documented as functions. Is this just an oversight or what? I'd like to clean up warnings during dev.

**Comment by taion** [comment]
The point is that they should never be set.

**Comment by cooperka** [comment]
Can you please elaborate @taion? They're props that are expected never to be set? Why do they exist?

I'm trying to detect an overlay being hidden, and when I set `onHide` on the `OverlayTrigger` it does nothing (though `rootClose` does work as expected).

**Comment by taion** [comment]
That's actually the point. Passing `onHide` in to `<OverlayTrigger>` doesn't do anything, so we figured we'd save you the hassle and just fail on the prop types check.

**Comment by cooperka** [comment]
Hmm, I didn't see any console warnings, the prop seems to have just been eaten. In any case, I solved my problem by using `OverlayTrigger`'s `onExit` instead of `onHide`. Thanks for the quick reply.
