### ISSUE TITLE
Focus isn't properly rendered for button groups

### ISSUE THREAD

**Issue by flaviut** [react-bootstrap/react-bootstrap#2748]
This is what checkbox buttons buttons look like when they are focused using the tab key on the bootstrap demo page:

![button example bootstrap](http://i.imgur.com/vEY3dp4.png)

There's subtle blue border around the button, and the button background is dark blue, but without the drop shadow.

With react-bootstrap:

![button example react-bootstrap](http://i.imgur.com/xOr0bat.png)

There's no indication that Checkbox 2 is selected. Pressing spacebar confirms that it is selected.

**Comment by taion** [comment]
That's interesting. It looks like upstream TWBS is actually using JS to do the focus management here.

**Comment by AhmedFat7y** [comment]
It seems that adding tabIndex="0" to the labels makes it focusable when you press TAB. However, when you press Space, nothing happens. You need to press another TAB (to focus the child input) then you can press Space to toggle the button.
To avoid focusing the input with the next TAB, we can add tabIndex="-1" to it.

I think we can add another handler for onKeyUp to check for space press on the label and trigger the change. 

Here's a link for a sandbox showing the solution https://codesandbox.io/s/rwpr6lxnx4

I tried to clone and run the repo in develop mode, but I couldn't manage to run it.

**Comment by joshalling** [comment]
I'll take this one. I'll probably use the same type of solution that they are currently using in bootstrap. Add a focusin handler to the input that adds a focus class to the label so that it looks like it is being focused.

**Comment by jquense** [comment]
sounds good 👍

**Comment by joshalling** [comment]
It actually looks like this was fixed back in March.

**Comment by taion** [comment]
ah, can we close this out then?

**Comment by mainadwitiya** [comment]
Hey you can go to the css files of bootstrap and make some changes.

**Comment by stevehanson** [comment]
I haven't been able to find where this was fixed. I just upgraded to the latest pre-1.0 (Bootstrap 3) release, v0.33.1, which was released November 2019, and am still seeing this issue. I'm also seeing the same tabindex behavior as described by @AhmedFat7y.
