### ISSUE TITLE
Modal animation triggers every time component is rerendering

### ISSUE THREAD

**Issue by michaeltomasik** [react-bootstrap/react-bootstrap#2751]
Hello, I'm using simply
```<Modal show={this.props.isOpen}>```
and inside of it I have
```
<Checkbox checked={this.props.isChecked} onChange={this.props.toggle}>
       Checkbox
</Checkbox>
```

Every time I change my checkbox It change `isChecked` which leads to rerender of component.
Problem is that even if `isOpen` didnt changed and is `true` the animation triggers.

Problem can be easly eliminated by adding `animation={false}` to Modal but still its this behaviour is bothering me

**Comment by jquense** [comment]
Hi there can you put together a reproduction jsfiddle or codesandbox? we aren't seeing the behavior your describing

**Comment by shellyjindal10** [comment]
Hi @michaeltomasik, can you share ur code ?

**Comment by taion** [comment]
Closing for staleness.
