### ISSUE TITLE
Alert Component is not rendering 

### ISSUE THREAD

**Issue by AbdullahWali** [react-bootstrap/react-bootstrap#2753]
I was trying to use Alert in a project and the whole page kept crashing whenever it tries to render Alert. So I tried creating a new clean project using create-react-app and used the same example code given in the documentation in my index.js:

`import React from 'react';`
`import ReactDOM from 'react-dom';`
`import {Alert} from 'react-bootstrap';`

`import registerServiceWorker from './registerServiceWorker';`
`const alertInstance = (
  <Alert bsStyle="warning">
    <strong>Holy guacamole!</strong> Best check yo self, you're not looking too good.
  </Alert>
);`
`ReactDOM.render(alertInstance, document.getElementById('root'));
registerServiceWorker();`

running that only rendered the element inside the Alert like [this](https://image.prntscr.com/image/mJZqYfYdQJmZICuY-3dq_g.png):

**Comment by taion** [comment]
You need to include the Bootstrap CSS.

**Comment by AbdullahWali** [comment]
Aah I presumed it was included in the react-bootsrap package

**Comment by dozoisch** [comment]
![image](https://user-images.githubusercontent.com/4422516/29236761-fcc1be42-7ec4-11e7-94c4-55711f4788a8.png)


https://react-bootstrap.github.io/getting-started.html
