### ISSUE TITLE
Modal error > modalNode undefined

### ISSUE THREAD

**Issue by Mikkoun** [react-bootstrap/react-bootstrap#2755]
Hi,

after upgrading to react@next and react-dom@next, modals will not open anymore.
In the console, it's throwing: Uncaught TypeError: Cannot read property 'contains' of undefined.

After some debugging I saw that in Modal.js this.modalNode is undefined.

Any ideas how to fix that?

**Comment by taion** [comment]
track this on https://github.com/react-bootstrap/react-overlays/issues/188
