### ISSUE TITLE
dropdown item with form input -- worthy of react-bootstrap component?

### ISSUE THREAD

**Issue by danbiagini** [react-bootstrap/react-bootstrap#2756]
Caveat: I'm a react/bootstrap newbie.  The last time I built any web components was 2005, when PHP & javascript were the go-tos.  

I've been searching stackoverflow and github trying to determine how to build a react-bootstrap dropdown (specifically in a navbar) which contains form elements (input fields).  There have been a number of related questions (i.e. [1](https://stackoverflow.com/questions/40840042/dropdown-with-input-field), [2](https://stackoverflow.com/questions/32510976/react-bootstrap-dropdown-with-input-wont-stay-open), [3](https://stackoverflow.com/questions/31597846/dropdown-with-form-fields-bootstrap-3), [4](https://github.com/react-bootstrap/react-bootstrap/issues/2366)) over the last few years, most pointing to an undesired behavior whereby the dropdown collapses on click inside the form (making it impossible to enter data into the form).  

A few solutions point to using the Dropdown customization, which does seem to work (there's an issue wrt how to close the dropdown, but seems solvable).  My problem with the custom dropdown is all the navbar/dropdown styling is lost.  It may be possible to manually setup this styling, but "how to" is not obvious for someone not well versed in CSS & bootstrap.  

I was considering building a new "MenuItem" like component (i.e. MenuForm or something) to try and solve this within a react component and not require custom CSS styling to try and match the react-bootstrap styling.  

a. Does this sound like a good approach, or is there a better way?  Most of the stackoverflow content on this is rather old, has anything changed to make this easier today?
b. I understand the goal of react-bootstrap is feature parity, but it seems that building such a form (and matching the "out of the box" styling) within a menuItem requires using native bootstrap.  Would such a "MenuForm" component fit within the react-bootstrap project (IOW, should I do this as a potential contribution?  I'm willing to go through the extra process if this seems worthwhile).

Thanks,
Dan

**Comment by jquense** [comment]
hey there. You can do a custom Menu (or MenuItem, i've done both) to handle some of these. The big thing is the close on click behavior which is driven by the RootCloseWrapper in the dropdown menu, you can do something like this:

```
class MenuPanel extends React.Component {
  static defaultProps = {
    bsRole: 'menu',
    rootClose: true
  }

  render() {
    let { className, rootClose, open, children, onClose, ...props } = this.props;

    let menu = (
      <div
        {...props}
        className={cn(className, 'dropdown-menu')}
        onSelect={undefined}
      >
        {children}
      </div>
    );

    if (rootClose && open)
      return <RootCloseWrapper noWrap onRootClose={onClose}>{menu}</RootCloseWrapper>

    return menu
  }
}

export default MenuPanel;
```

**Comment by taion** [comment]
Something like `<MenuForm>` sounds like it'd be a good fit for a new project. For the time being, we do want to limit React-Bootstrap itself to just what's in Bootstrap, though.

**Comment by ortonomy** [comment]
There was never a solution to this, was there? I could really do with this now....

**Comment by danbiagini** [comment]
Not that I know of, I've moved on so haven't been tracking it closely.
