### ISSUE TITLE
modal show target 

### ISSUE THREAD

**Issue by lgbcscs** [react-bootstrap/react-bootstrap#2757]
How can i know the target for the modal. just like the jquery method:
`$("modal").on("show.bs.modal",function(e){
     var btn = $(e.relatedTarget),
           dataId = btn.data("id");
})`

**Comment by taion** [comment]
The code you have there just gets the button and some IDs.

In general, you'll want to just follow standard React patterns for grabbing DOM nodes, event targets, &c.

This isn't anything specific to React-Bootstrap.
