### ISSUE TITLE
Radio example?

### ISSUE THREAD

**Issue by nato90** [react-bootstrap/react-bootstrap#2758]
Hi, How to assign and get the value of a Radio?

**Comment by taion** [comment]
`<Radio>` is just a thin wrapper around a normal `<radio>`. It's the exact same.

**Comment by c0d3ster** [comment]
I believe this issue should be reopened because as of right now, I can see no way to modify the value attribute of the <Radio> wrapper.  I don't see how this component can be useful without any way of propagating the value attribute down to the element for the click event handler.  Is there something I'm missing here?

**Comment by jquense** [comment]
What are you trying to do? There is no logic in this component it just forwards all props to the underlying input. you can `value` and that will be the value

**Comment by c0d3ster** [comment]
ahhh, my mistake. I'm not sure why it wasn't passing down the value initially, but it worked after rebuilding my project.

**Comment by c0d3ster** [comment]
One more question about the `<Radio>` component though.  Why do we need to rely on `{' '}` to provide spacing between the radio buttons?  It seems to me as though it would be cleaner to apply a class with margins as opposed to manually entering in this whitespace.  Thoughts?

**Comment by jquense** [comment]
We don't control the styles in react-bootstrap since it's just the upstream bootstrap css. What your seeing tho is sort of a quirk of JSX vs HTML, html the whitespace would almost always exist naturally via a line break but jsx it's all collapses, hence needing to add it manually.

**Comment by c0d3ster** [comment]
okay, that makes sense.  Thanks for the fast and clear responses by the way, love the communication on this repository.

**Comment by jquense** [comment]
we try!

**Comment by MaheshK02** [comment]
<Radio name="radioGroup" inline value={this.state.gender === 'current'} onChange={this.handleChange}>
unable to update value using <Radio/>
