### ISSUE TITLE
Dropdown props does not work

### ISSUE THREAD

**Issue by prajapati-parth** [react-bootstrap/react-bootstrap#2762]
Hello,
I'm trying to create custom dropdown components as shown [here](https://react-bootstrap.github.io/components.html#btn-dropdowns-custom) as custom toggle.

My concern:
- `rootCloseEvent` does not work and the dropdown remains open when clicking outside the component
- Up and down arrow key do not select the dropdown options
- How do I close the dropdown on option select?

My code:
```jsx
<Dropdown
    id='customdropdown'
    rootCloseEvent='click'
>
    <Button bsRole='toggle'>
        <span>Select item</span>
        <span className='caret'></span>
    </Button>

    <ul className='dropdown-menu ' bsRole='menu'>
        {
            {/* Array.map returning <li> elements */}
        }
    </ul>
</Dropdown>
```

Thanks.

**Comment by taion** [comment]
You can see that the logic for those are implemented on `DropdownMenu`. If you use a completely custom menu component, then you don't get that logic.

**Comment by prajapati-parth** [comment]
All right @taion. Thanks :+1:

**Comment by prajapati-parth** [comment]
@taion So I dropped the idea of using custom toggle and dropdown list and used the following code
```jsx
<DropdownButton
    title='Select item'>
    {
        options.map(item => {
            return (
                <MenuItem
                    key={item.key}>
                    <span>{item.text}</span>
                </MenuItem>
            )
        })
    }
</DropdownButton>
```
Now the `DropdownButton` component here renders the `button` and the `ul` tag. I'm trying to have a `div` wrapper around the `ul` but have no success. How can I wrap the `ul` with a `div`?
