### ISSUE TITLE
Error in ./~/react-bootstrap/lib/Collapse.js, Fade.js | Module not found: 'react-overlays/lib/Transition'

### ISSUE THREAD

**Issue by ronachong** [react-bootstrap/react-bootstrap#2763]
The full errors I get:
```
Error in ./~/react-bootstrap/lib/Collapse.js
Module not found: 'react-overlays/lib/Transition' in /Users/20/kusamochi/docker-frontend/react-app/node_modules/react-bootstrap/lib

 @ ./~/react-bootstrap/lib/Collapse.js 41:18-58

Error in ./~/react-bootstrap/lib/Fade.js
Module not found: 'react-overlays/lib/Transition' in /Users/20/kusamochi/docker-frontend/react-app/node_modules/react-bootstrap/lib

 @ ./~/react-bootstrap/lib/Fade.js 33:18-58
```

This is L41 in my Collapse.js:
`var _Transition = require('react-overlays/lib/Transition');`

Not sure if this is because of some package versioning issue - I don't see any Transition source code in react-overlays' github repo nor in my local copy of the module.

```p3-6:lib 20$ ls -la
total 176
drwxr-xr-x  12 20  HBTN\Domain Users    408 Aug 22 14:35 .
drwxr-xr-x   7 20  HBTN\Domain Users    238 Aug 22 14:35 ..
-rw-r--r--   1 20  HBTN\Domain Users  10193 Jul 24 07:52 Affix.js
-rw-r--r--   1 20  HBTN\Domain Users   8362 Jul 24 07:52 AutoAffix.js
-rw-r--r--   1 20  HBTN\Domain Users  17394 Jul 24 07:52 Modal.js
-rw-r--r--   1 20  HBTN\Domain Users   4978 Jul 24 07:52 ModalManager.js
-rw-r--r--   1 20  HBTN\Domain Users   7274 Jul 24 07:52 Overlay.js
-rw-r--r--   1 20  HBTN\Domain Users   5564 Jul 24 07:52 Portal.js
-rw-r--r--   1 20  HBTN\Domain Users   7092 Jul 24 07:52 Position.js
-rw-r--r--   1 20  HBTN\Domain Users   5540 Jul 24 07:52 RootCloseWrapper.js
-rw-r--r--   1 20  HBTN\Domain Users   1221 Jul 24 07:52 index.js
drwxr-xr-x  12 20  HBTN\Domain Users    408 Aug 22 14:35 utils
p3-6:lib 20$ pwd
/Users/20/kusamochi/docker-frontend/react-app/node_modules/react-overlays/lib
```

[my-project-package-json.txt](https://github.com/react-bootstrap/react-bootstrap/files/1243559/my-project-package-json.txt)
[react-bootstrap-package-json.txt](https://github.com/react-bootstrap/react-bootstrap/files/1243560/react-bootstrap-package-json.txt)

I'm also a little confused because this example of passing a transition to a Modal component uses a Transition component from react-transition-groups rather than any Transition component from react-overlays:
https://github.com/react-bootstrap/react-overlays/blob/master/examples/Transition.js

**Comment by taion** [comment]
You have mismatched versions of the libraries installed. Wipe your node_modules and reinstall.

**Comment by ronachong** [comment]
Thanks - I also npm uninstalled react-bootstrap since the example uses Modal from react-overlays/lib/Modal instead of react-bootstrap.

**Comment by reduxdj** [comment]
Wiping  out the  modules does not solve this problem

**Comment by hoodsy** [comment]
@reduxdj I'm experiencing this as well for `Modal` and `Accordion` – did you find a fix/workaround?

**Comment by alexkrolick** [comment]
```
ModuleNotFoundError: Module not found: Error: Can't resolve 'react-transition-group/Transition' in '<...>/node_modules/react-bootstrap/es'
    at factoryCallback (<...>/node_modules/webpack/lib/Compilation.js:276:40)
```

**Comment by alexkrolick** [comment]
I'm seeing this issue after upgrading to 0.32.

Here's the error when running Webpack in production mode:

```
ModuleNotFoundError: Module not found: Error: Can't resolve 'react-transition-group/Transition' in '<...>/node_modules/react-bootstrap/es'
    at factoryCallback (<...>/node_modules/webpack/lib/Compilation.js:276:40)
```

- The only package in the react-bootstrap folder in node_modules is react-transition-group, all the other ones are hoisted up a level.
- RTG 1.x is also a dep for other modules in the project

<img width="1145" alt="screen shot 2018-01-23 at 3 44 36 pm" src="https://user-images.githubusercontent.com/1571667/35306876-dfa02224-0054-11e8-8514-71a33e2b3f3e.png">

<img width="949" alt="screen shot 2018-01-23 at 3 45 29 pm" src="https://user-images.githubusercontent.com/1571667/35306878-dfd537d4-0054-11e8-977c-cd7d407cebce.png">

<img width="960" alt="screen shot 2018-01-23 at 3 45 49 pm" src="https://user-images.githubusercontent.com/1571667/35306879-dfefa970-0054-11e8-80f3-74fa0fe758fe.png">

**Comment by taion** [comment]
Are you using something for deduping in webpack?

**Comment by alexkrolick** [comment]
No, we aren't. I commented out anything related to module splitting or concatenation and it still fails.

**Comment by melwynfurtado** [comment]
I am facing the same problem and this looks to me like the transitive dependency issue. `react-transition-group` hoisted/installed at top level of `node_modules` is different/lower to what `react-bootstrap` expects. Check the versions of `react-transition-group` under `node_modules` of your project and the one installed under `node_modules/react-transition-group/node_modules/...`. they should be different. `yarn` takes care of this kind of problems for you.
