### ISSUE TITLE
Error when passing "danger" validationState to form element

### ISSUE THREAD

**Issue by mweiczorek** [react-bootstrap/react-bootstrap#2764]
Warning: Failed prop type: Invalid prop `validationState` of value `danger` supplied to `FormGroup`, expected one of ["success","warning","error",null].

I realize this project is quite new and not in full release, but will there be support for Bootstrap 4?

**Comment by taion** [comment]
See https://github.com/react-bootstrap/react-bootstrap/issues/1187 and https://github.com/react-bootstrap/react-bootstrap/pull/2752.
