### ISSUE TITLE
Docs page seems broken

### ISSUE THREAD

**Issue by jole78** [react-bootstrap/react-bootstrap#2766]
getting this error in the console and can't click on anything or expand code etc
![rs_error](https://user-images.githubusercontent.com/2247346/29713778-84f09ef6-89a0-11e7-89b2-f2414467405f.png)

**Comment by taion** [comment]
Which page specifically, and which browser? https://react-bootstrap.github.io/components.html works fine for me on Chrome 61.

**Comment by jole78** [comment]
OK, this problem seems to have magically gone away for me. Can't really say why and how (which in somewhat troublesome) but I'm gonna close the issue anyway.

**Comment by taion** [comment]
Could have been some weird caching thing.
