### ISSUE TITLE
Disabled Toggle button is working as regular one

### ISSUE THREAD

**Issue by AlexanderKozhevin** [react-bootstrap/react-bootstrap#2767]
If I set up toggleButton and try to disable it.
But it's still clickable. Which is basically not right.

```
<ToggleButton 
   key={index}
  disabled={true} 
  value={item.name}>

  {item.name}

</ToggleButton>
```

**Comment by taion** [comment]
This was fixed in https://github.com/react-bootstrap/react-bootstrap/pull/2760.
