### ISSUE TITLE
Horizontal Form requires a <Row>?

### ISSUE THREAD

**Issue by jmargolisvt** [react-bootstrap/react-bootstrap#2769]
The docs say:

> Use `<Form horizontal>` instead of `<form>`, then use `<Col>`s to align labels and controls. Do not use `<Row>` here, as `<FormGroup>` will already serve as a grid row in a horizontal form.

But I needed to add those `<Row>`s to get the horizontal layout to work correctly.  They were not automatically inserted as the docs suggest.  I'm using Bootstrap ^4.0.0-alpha.6 and react-bootstrap ^0.31.2.  Has something changed in Bootstrap 4 maybe?  Or are the docs out of date?  Something else?

**Comment by jquense** [comment]
Hi there, We don't support bootstrap v4 yet. You don't need the rows with the v3 bootstrap css
