### ISSUE TITLE
Warning: Specifying a `<Nav>` `activeKey` or `activeHref` in the context of a `<TabContainer>` is not supported

### ISSUE THREAD

**Issue by cbll** [react-bootstrap/react-bootstrap#2771]
Sample code and question in this [stackoverflow post](https://stackoverflow.com/questions/45915394/reac-bootstrap-warning-specifying-a-nav-activekey-or-activehref-in-the)

**Comment by taion** [comment]
It's exactly what the error message says. The active key comes down from the top-level container. Don't set it on the `<Nav>`.
