### ISSUE TITLE
Cannot control border-radius of Modal

### ISSUE THREAD

**Issue by benomatis** [react-bootstrap/react-bootstrap#2772]
The node `<div class="modal-content" role="document">` cannot be controlled, and as this is the place `border-radius` is set, I'm stuck with the default setting of `6px`. Any ways I could override this?

**Comment by benomatis** [comment]
Here is a workaround:

Set prop `dialogClassName` to custom class name:
```jsx
<Modal
  dialogClassName="border-radius-2"
>
```

Add your custom rule to your CSS file - make sure the rule applies to the `div` child of the class defined above:
```css
.border-radius-2 div {
  border-radius: 2px !important;
}
```
Hope this helps someone.

**Comment by taion** [comment]
Just use CSS, or use `bsClass`.
