### ISSUE TITLE
App won't load after adding component

### ISSUE THREAD

**Issue by JarrodJ83** [react-bootstrap/react-bootstrap#2778]
I'm sure this is something stupid I'm doing but I can't see what I'm doing wrong. I tried following the "getting started" guide but it seems to assume you're well versed in React and I'm just starting to learn. I have a working react app and I tried to start simple and add a button to it. I imported the button
`import Button from 'react-bootstrap'`
then added it to my component 
```
class App extends Component {
  render() {
    return (
        <div className="App">
            <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/latest/css/bootstrap.min.css" />
            <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/latest/css/bootstrap-theme.min.css" />
            <div className="App-header">
                <img src={logo} className="App-logo" alt="logo" />
            </div>
            <div id="container">
                <div id="nav">
                    <Button href="#">Link</Button>
                </div>
                <div id="main">
                    ...
                </div>
            </div>
      </div>
    );
  }
}
```

Now my app fails to load with the following errors:
> Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in. Check the render method of `App`.

> Uncaught TypeError: Cannot read property '__reactInternalInstance$kv7rc6i003a' of null

Any guidance would be greatly appreciated!

PS: A step by step guide to setting up a new react app and adding one of your components to it on the getting started guide would be a great addition.

**Comment by taion** [comment]
That's not quite the correct import. See https://react-bootstrap.github.io/getting-started.html#es6.

**Comment by JarrodJ83** [comment]
Thanks you, @taion
