### ISSUE TITLE
Bug: NavItem href not propagating new hash value

### ISSUE THREAD

**Issue by winterstein** [react-bootstrap/react-bootstrap#2780]
Hello,

I'm using the responsive Navbar example, but setting href='#foo', href='#bar' etc in the NavItems.
The menu opens and closes when you click on an item -- but the url doesn't update to show the item's href value.

All the best,
 - Daniel

**Comment by taion** [comment]
this is https://github.com/react-bootstrap/react-bootstrap/issues/2365
