### ISSUE TITLE
Dropdown + tab key, doesn't work for input, links or items

### ISSUE THREAD

**Issue by Catwashere** [react-bootstrap/react-bootstrap#2782]
Cannot navigate inside a Dropdown with tab key. 

Cannot move in items
![image](https://user-images.githubusercontent.com/1081220/30135387-1e7249de-9320-11e7-92a9-a210e62d7d22.png)

Cannot move in inputs or links
![image](https://user-images.githubusercontent.com/1081220/30135390-2308750e-9320-11e7-8e1e-4b0f2e20bb34.png)

The dropdown automatically close when tab key is press instead of moving through items

**Comment by taion** [comment]
If you're embedding something this complicated, you should probably use a popover or something equivalent. It's not a good fit for the dropdown menu use case, and we're not looking to support it there.
