### ISSUE TITLE
Missing tabIndex attribute using Tabs.js 

### ISSUE THREAD

**Issue by kecsolecso** [react-bootstrap/react-bootstrap#2783]
Generated HTML code structure of list elements:
div > ul > li
At this level would be nice to have tabIndex html attribute to be able to change focus on tabs with keyboard tab button.

The following elements contain tabIndex attribute so seems a bug for me:
div > ul > li > a
So if these contain tabIndexe attribute seems logical to have it in their parents as only one link sits in a list element we cannot navigate on one element but only on their parents

**Comment by jquense** [comment]
The setup for tab focus follows the ARIA authoring standards for tabs. Which is that the keyboard arrows move change tabs. and only the *active* tab is focusable and in the tab order. That's why you see the tabIndex added to just one tab at a time

**Comment by kecsolecso** [comment]
Actually all li>a elements contain tabIndex attribute except the li:active>a.
But I understand your point and standards are standards :)
Thanks for the quick response!
