### ISSUE TITLE
Export Props interfaces

### ISSUE THREAD

**Issue by mayerwin** [react-bootstrap/react-bootstrap#2785]
In my Typescript 2.3 project, I am trying to import ModalProps and ButtonProps to extend them for my own derived components using: 
`import { ModalProps, ButtonProps } from 'react-bootstrap';`
But this causes Intellisense errors as ModalProps and ButtonProps are not exported in the corresponding  type definition files.

Is there any workaround I could use until the definitions are fixed?

**Comment by taion** [comment]
The TS defs don't live in this repo. Also, I know of no such exports, so it's not even clear what you're referring to there.

**Comment by mayerwin** [comment]
I have opened the issue here: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/19664
