### ISSUE TITLE
active key not working with state change

### ISSUE THREAD

**Issue by amit-mn** [react-bootstrap/react-bootstrap#2787]
I am using Tab.Container and using a state to manage active tabs. It is working fine with click on tabs. But when I try to change state on button click than it is not changing the active tab according to state.

I want to change active tab on click on a button also. And also on close active tab, active tab should also changed but it is not working for me.

**Comment by taion** [comment]
Please post a repro.

**Comment by amit-mn** [comment]
Issue resolved thanks.

**Comment by originaltimster** [comment]
Hi,
I am having similar issue, how did you resolve. Is it in your public repos somewhere?
