### ISSUE TITLE
Tabs does not propagate bsClass into NAV

### ISSUE THREAD

**Issue by kecsolecso** [react-bootstrap/react-bootstrap#2788]
At https://github.com/react-bootstrap/react-bootstrap/blob/d07578a8c7390ec693204842244ecc1d23e120be/src/Tabs.js#L120

TabContent inherits bsClass, but Nav does not. In this way we cannot have common class prefix

**Comment by taion** [comment]
It's not supposed to, because that would mess up standard Bootstrap styling. Just use the lower-level API if you need this.
