### ISSUE TITLE
Navbar brand element (using v8js php)

### ISSUE THREAD

**Issue by jamesgrayillustration** [react-bootstrap/react-bootstrap#279]
So, i'm able to get everything working properly so far using react-bootstrap with a reactjs php implementation (based on [this](https://github.com/reactjs/react-php-v8js) and [this](https://github.com/Cohros/laravel-reactjs)) . However, when I try to output HTML, I get a string literal, and not actual HTML tags. It seems maybe that the V8Js php extension may somehting to do with stripping out the actual HTML? Or, maybe it's the ````sprintf()```` function.

````php
    ReactJS::component('ReactBootstrap.Navbar');

    $navbar = [
      'fixedTop' => 'fixedTop',
      'inverse' => 'inverse',
      'fluid' => 'container-fluid',
      'brand' => '<a class="navbar-brand" href="#"><img src="assets/imgs/dddialogue_app_logo_web.png" style="width: 150px;"></a>'
    ];

    ReactJS::data($navbar);

    $navbar_markup = ReactJS::markup();
````

Anyways, i'm assuming what i'm trying to do won't work. However, is there a way to not use the default ````span```` element and instead use an anchor tag with a nested ````img```` tag?

**Comment by taion** [comment]
Is this still an issue? I'm not aware of any problems using this outside of the v8js context.

**Comment by AlexKVal** [comment]
I presume this question is kind of out of scope and we safely can close this issue for now.
If it becomes the hot topic we always can re-open it.

Of course if somebody wants to make any contribution (docs, gists, workarounds) on the topic,
it is always appreciated :wink:
