### ISSUE TITLE
Pagination/PaginationButton is not compatible with latest Bootstrap v3

### ISSUE THREAD

**Issue by lhr0909** [react-bootstrap/react-bootstrap#2792]
Was trying to use `Pagination` component, and found that the styles are broken. Further investigation tells me that originally Bootstrap pagination was using `.pagination>li>a` for styling, but now the `li` tags has `page-item` class, and `a` tag has `page-link` class, and styling is based on the class tags instead. Looking at the `Pagination` code, I found that the corresponding class names are not in the `PaginationButton`.

Let me know if there is anything else I should provide, and I can submit and pull request for this. I know what to change to make it work again.

**Comment by taion** [comment]
You mean v4, which we don't support yet. See https://github.com/react-bootstrap/react-bootstrap/issues/1187.
