### ISSUE TITLE
OverlayTrigger is not working in Chrome with disabled Button

### ISSUE THREAD

**Issue by axten** [react-bootstrap/react-bootstrap#2796]
The overlay is shown on firefox but not on chrome:
```
<OverlayTrigger trigger={['hover', 'focus']} placement="top" overlay={nextStateOverlay}>
      <Button
            bsStyle="primary"
            onClick={() => {...}}
            disabled={true}
    >go on</Button>
</OverlayTrigger>
```

maybe this is helpful: https://github.com/jquery/jquery/issues/2558#issuecomment-136372453

**Comment by taion** [comment]
That's just how these things work. See https://github.com/react-bootstrap/react-bootstrap/issues/2428
