### ISSUE TITLE
Tooltips arrowOffsetLeft overriden by Overlay

### ISSUE THREAD

**Issue by jeffredodd** [react-bootstrap/react-bootstrap#2798]
I noticed when trying to set arrowOffsetLeft on Tooltip inside an Overlay I was not able to set the value. Anyone have any idea what may be causing this?

**Comment by taion** [comment]
See https://github.com/react-bootstrap/react-bootstrap/issues/1828

I don't think we want to let you just set it... would the idea be to completely disregard the calculated value?

**Comment by jeffredodd** [comment]
In my case I was hoping to affect the alignment of the arrow to shift from the center to either the left or right.

**Comment by taion** [comment]
A nice way to handle this might be to update `<Position>` in react-overlays to not override child props that are explicitly specified on the child... at least for `arrowOffset<Dir>`. Want to take a stab?
