### ISSUE TITLE
Console errors with OverlayTrigger

### ISSUE THREAD

**Issue by itzsaga** [react-bootstrap/react-bootstrap#2805]
With `trigger="hover"` I get:
> Warning: [react-bootstrap] Specifying only the `"hover"` trigger limits the visibility of the overlay to just mouse users. Consider also including the `"focus"` trigger so that touch and keyboard only users can see the overlay as well.

So I switched to `trigger={['active', 'hover']}` and still get the same error plus an additional:
> Warning: Failed prop type: Invalid prop `trigger` supplied to `OverlayTrigger`.

I'm looking at https://react-bootstrap.github.io/components.html#popovers-trigger-behaviors and not seeing what I may be missing in my code.

**Comment by taion** [comment]
active isn't a valid trigger
