### ISSUE TITLE
OverlayTrigger {['hover', 'focus']} Error

### ISSUE THREAD

**Issue by itzsaga** [react-bootstrap/react-bootstrap#2806]
With `trigger="hover"` I got:
> Warning: [react-bootstrap] Specifying only the `"hover"` trigger limits the visibility of the overlay to just mouse users. Consider also including the `"focus"` trigger so that touch and keyboard only users can see the overlay as well.

I switched to `trigger={['hover', 'focus']}` and still get the same error message.

I'm looking at https://react-bootstrap.github.io/components.html#popovers-trigger-behaviors and not seeing what I'm missing.

**Comment by prmichaelsen** [comment]
did you find the solution?

**Comment by itzsaga** [comment]
@prmichaelsen yes. There was a second component on the page that was missing `'focus'`. I guess I should've added that comment when I closed this. Thanks for checking :smile:
