### ISSUE TITLE
Incorrect code in components section on website

### ISSUE THREAD

**Issue by nareddyt** [react-bootstrap/react-bootstrap#2807]
[This code sample](https://react-bootstrap.github.io/components.html#forms-controls) on the components section of the official website has HTML tags of the type `FieldGroup`. 

`FieldGroup` does not exist in the react-bootstrap libraries. I believe that should be replaced with `FormControl`

**Comment by taion** [comment]
That example defines `<FieldGroup>` and is meant, inter alia, to demonstrate defining such a component.
