### ISSUE TITLE
Proper way to add text input to nav element?

### ISSUE THREAD

**Issue by robbiemilejczak** [react-bootstrap/react-bootstrap#2808]
It's really unclear on the docs what I should do to achieve this. The only example of an input in a Nav element is specifically a Navbar which I am not using.

When I use

`<NavItem>`
`    <FormGroup>`
`        <FormControl type='text' />`

I have an input field in my Nav, but that input field does not respond to the space key. Why this happens is a complete mystery to me, but the spacebar key does nothing. This is obviously problematic, so I thought maybe I am doing this the wrong way. I've tried using an Input element to no success (I get the error 'element type is invalid' no matter what I've tried)

All in all, what I need is an input field that responds to the spacebar key. I am assuming this problem is arising from the fact that I am adding an input field to my Nav improperly so I'm hoping someone can clarify how I should be going about this. Thanks

**Comment by jquense** [comment]
Inputs aren't supported inside of NavItems, or Navs, which is specifically for lists of navigation options. I can see why the Navbar might not be suitable for your use-case but that is the component that is meant for holding both navigation options and potential inputs (like searches)

**Comment by robbiemilejczak** [comment]
so I have to use a NavBar to get the desired behavior?

**Comment by taion** [comment]
Yes, see https://react-bootstrap.github.io/components.html#navbars-form.

**Comment by robbiemilejczak** [comment]
that is a shame, thanks!

**Comment by zsayenko** [comment]
Ran into the same issue, super inconvenient, since having a search bar in the header is a fairly common scenario.

There is a hacky workaround though. 
It seems that <input> stops working when being nested inside <NavItem>.
One way is to simply use a simple <li> instead of <NavItem> and put your text field there, keeping the rest of the Navbar the same.
Something like:

<Nav>
        <NavItem className="brand-container">
          <Navbar.Header>
            <Navbar.Brand>
              <Link to="/">
                <img alt="Logo" className="logo-img" />
              </Link>
            </Navbar.Brand>
          </Navbar.Header>
        </NavItem>
        <li role="presentation">
          <input type="text" />
        </li>
        <NavItem className="user-name-container">
          Joe Doe
        </NavItem>
</Nav>
