### ISSUE TITLE
Typescript : the 'Tab' component does not follow the React type on the title attribute

### ISSUE THREAD

**Issue by talend-jphautin** [react-bootstrap/react-bootstrap#2809]
Tab component is using a 'title' attribute. This attribute can be a string or a react fragment.
This is working fine with Javascript but we can not compile with typescript because of react.d.ts 
file that define a title as a string ONLY attribute as the title is part of HTMLAttributes interface.

To make compilation work, you need to patch the index.s.ts file of  "types/react" to modify 
line 
```
interface HTMLAttributes<T> extends DOMAttributes<T> {
 ...
title?:` string;
...
}
```
to 
```
interface HTMLAttributes<T> extends DOMAttributes<T> {
 ...
title?: string|React.ReactNode;
...
}
```

I think the best solution is to allow a new attribute *header* on the Tab component, as in Panel component, that will not conflict with this definition and allow React Fragment in it.

**Comment by taion** [comment]
We don't manage the TS defs here.
