### ISSUE TITLE
Screen gets pixeled when Modal opens.

### ISSUE THREAD

**Issue by hbulgarini** [react-bootstrap/react-bootstrap#2811]
Hello Everybody ,

I'm having a really strange issue and i cannot determine if there is a bug or something related.
FYI, this is only happening using Chrome on Windows (7 & 10 ) , then on MacOS and Ubuntu Desktop the issue is not present.

The issue is that everytime i open a modal ( by setting a state flag to true ) the screen gets pixeled and some items from the background gets into the modal area by error ( please check the screenshots where i show the error:
![react-modal_error](https://user-images.githubusercontent.com/12089572/30896386-c29136ae-a326-11e7-8444-d3fdaeda5237.PNG)

I have updated my react-bootstrap to   "react-bootstrap": "^0.31.3" and below is my code definition for the modal:

  ```  render() {
  return (
        <div className="wrapper wrapper-content animated fadeIn">

           <div className="row">
             <Modal show={this.state.showModal} onHide={this.close}>
               <Modal.Header closeButton>
                 <Modal.Title>Borrar persona</Modal.Title>
               </Modal.Header>

               <Modal.Body>
                 <h3>Esta seguro que desea borrar la persona: </h3>
                 <h4>{this.state.CurrentName}</h4>
               </Modal.Body>
               <Modal.Footer>
                 {button_confirm}
                 <Button onClick={this.close}>Cancelar</Button>
               </Modal.Footer>
               </Modal>

```

Any comment?

**Comment by yodiman** [comment]
The same issue. I noticed that it depends on the browser width. Chrome 61.0.3163.100

**Comment by hbulgarini** [comment]
@yodiman  Exactly... i have the same Chrome version:

Version 61.0.3163.100 (Official Build) (64-bit)

**Comment by lghamie** [comment]
I've got exactly the same problem

**Comment by taion** [comment]
We don't control the rendering here beyond setting up the DOM. This might be an issue with your CSS, or possibly a browser bug.

**Comment by hbulgarini** [comment]
I don't think is a CSS issue since in the same pc using firefox the issue is not present. 
So definetly i believe is bug with chome in windows with a certain width

**Comment by hbulgarini** [comment]
Today on my mac i upgraded Chrome to version to 61.0.3163.100 (Official Build) (64-bit).
We have different users having the same issue , so it's quite useless that with the latest version of Chrome the modal gets crashe. Really the answer will be "we don't control the rendering..." and the case is closed and that's it?

**Comment by khumphrey-sb** [comment]
I've been chasing the same thing and found this:

https://github.com/react-toolbox/react-toolbox/issues/1695

it does appear to be a bug in Chrome:

https://bugs.chromium.org/p/chromium/issues/detail?id=770354

**Comment by leonardobaggio** [comment]
as @khumphrey-sb said, this is a Chrome bug.  

There are some issues open at Chromium's project adressed to solve this issue.
By now, the fastest workaround is to change from hexadecimal syntax background-color to RGBA. 
`background-color: #fff;` => `background-color: rgba(0,0,0,0.9);` 

![glitch_solved](https://user-images.githubusercontent.com/18285859/30973537-bdede890-a443-11e7-8401-1313f8198676.gif)

This artifacts also vanishes when the hardware acceleration at Chrome's advanced settings is Disabled

![image](https://user-images.githubusercontent.com/18285859/31246632-5a46b744-a9e4-11e7-9189-907c0d1e713f.png)
.

**Comment by khumphrey-sb** [comment]
Google has not linked the issue to this: 

https://bugs.chromium.org/p/chromium/issues/detail?id=770733#c12

Using the suggested fix has worked for me:

> We had the same issue with bootstrap based dialogs. We tracked the issue down to background-clip: padding-box in the .modal-content css class.
> 
> Changing this to the default value of background-clip: border-box solved it.
