### ISSUE TITLE
Collapse not offering onClick

### ISSUE THREAD

**Issue by raghavgarg1257** [react-bootstrap/react-bootstrap#2817]
Hello,
I am using `Collapse` component and having a hard time differentiating between programmatically and manually(click) opening the collapse. I want simple functionality where I programmatically change the state to manage the opening/closing but if it is opened manually then it should remain open. To achieve this I need an event which can detect the click, so while updating I can check for it too. 

Some trimmed code for better understanding:

    class ListItem extends Component {

      constructor(props) {
        super(props);

        this.state = { 
          show: this.props.product.metadata.open // coming from redux
        };
      }

      componentWillUpdate() {
        // updating state if redux is updated
        /* add check if manually opened then persist the previous state, means don't update */
        if (this.state.show !== this.props.product.metadata.open) {
          this.setState({
            show: this.props.product.metadata.open
          });
        }
      }

      render() {
        return (
          <Collapse in={this.state.show} onClick={/* manually opened */}>
            ...
          </Collapse>
        );
      }
      
    }

`Collapse` change the state given to `in` automatically, and events like `onEntered` also change the given state but we don't have any function like `onClick` to detect the manual opening of the component.

Please share if I am doing something wrong else please address the issue so that I can decide if I have to switch to some other component or not. Thanks.

**Comment by taion** [comment]
This was rewritten on `next`, and `<Collapse>` is just a standard implementation of a React Transition Group transition. But otherwise, sure, wrapping it with another component is how you do composition with React.
