### ISSUE TITLE
Best way to use with Rails??

### ISSUE THREAD

**Issue by andyl** [react-bootstrap/react-bootstrap#282]
It looks like react-bootstrap uses a 'define' method, which I think is part of RequireJS.  As far as I can tell, RequireJS doesn't work well with the Rails native asset manager, Sprockets.  At this point, I can't see an easy way to use react-bootstrap in my rails App.  

I tried using this repo and `react-bootstrap-bower`, pulling from rails-assets.org and direct download from github.  No luck.

Perhaps I am missing something obvious.  Can anyone give me a tip on how to get react-bootstrap working in a rails app??

**Comment by killy** [comment]
https://github.com/mariopeixoto/react-bootstrap-rails

**Comment by mtscout6** [comment]
@jakcharlton Using `var Button = require('react-bootstrap/lib/Button');` may not seem practical at first until you consider that you may only be using a small portion of this library. If you only use a few components then only bring in the components you need and don't force your end user to download more than necessary. Using this in unison with something like webpack or browserify will ensure your assets are as small as possible.

@mariopeixoto I'm not a rails guy myself, but that feels really heavy handed. If you get some sign-off from some more rails folks and care to add this into the release process getting introduced in #449 than I guess we can figure out some means to keep that gem up to date with each release programatically.

**Comment by mariopeixoto** [comment]
@mtscout6 Hi, yeah it's kinda heavy handed but the gem only acts as a bridge to access the library using the asset pipeline. Would you mind to take a look at what the guys from facebook are doing for the react library (https://github.com/facebook/react/tree/master/gem-react-source)? They've integrated a ruby gem with their own release process, so every time they have a new release, the gem gets a new release as well (react-source gem). So, in the react-rails gem (https://github.com/reactjs/react-rails), they only need to point to the right version of the react-source gem. This would be the ideal way to keep the gem up-to-date and less messy.

**Comment by mtscout6** [comment]
@mariopeixoto Sorry for the delay in responding. I had not looked at what react was doing till just now. I'd be fine with a plug in to our release process to programmatically do this when we run our releases. That would help those in rails stay up to date with all of our changes. Would you be up to drafting a PR for this? After you do this then you'd need to add me as one of the owners that can publish there.

**Comment by mtscout6** [comment]
Keep in mind that there is a new `--dry-run` flag to the `./tools/release` script which would allow you to test this locally.

**Comment by mtscout6** [comment]
I'm going to go ahead and close this since React is doing away with theirs as well. See facebook/react#4069

**Comment by JohnReedLOL** [comment]
So if I have a rails bootstrap project and I want to make it use React for SPA, what do I do?

**Comment by konung** [comment]
@JohnReedLOL 
Mine is steup like this:

In Gemfile:
gem 'react-rails'
gem 'react-bootstrap-rails'

In application.js
//= require react
//= require react_ujs
//= require react_bootstrap

in your haml or erb view
= react_component('MyVeryOwnReactContainerComponent')

MyVeryOwnReactContainerComponent - lives in assets.
