### ISSUE TITLE
Allow align prop in Media.Body component ?

### ISSUE THREAD

**Issue by eladlevy** [react-bootstrap/react-bootstrap#2824]
It seems Media.Body component should be able to accept `align` prop as well. When I try to align middle but Media.Body height is lower than Media.Left it behaves like align top:
![image](https://user-images.githubusercontent.com/4246412/31337224-01564e66-ad03-11e7-994d-00171d91e50a.png)

as I see it, it should align like so:
![image](https://user-images.githubusercontent.com/4246412/31337326-7674e3b0-ad03-11e7-9d30-60e74ab161f0.png)

I'm adding `align-middle` class manually to Media.Body in order for it to be aligned like the former image. Does it makes sense to add this prop or its just me? if so i'll be happy to issue a PR that fix this

**Comment by taion** [comment]
Feel free to send in a PR. It'd be the `align` prop, as for e.g. `MediaLeft`.
