### ISSUE TITLE
[Docs] Add 'checked' prop to Radio component doc

### ISSUE THREAD

**Issue by fangyizhu** [react-bootstrap/react-bootstrap#2826]
Hi, as someone who have little experience with React, I thought for React-bootstrap's Radio component, onChange fires whenever the radio is toggled on and off. 

Turns out, onChange only fires the first time you click on it or when checked prop is set under some React-bootstrap versions (0.30.7) in my local environment.
 
For example:
```
<Radio name='radios'
             value={'a'}
             onChange={event => this.setState({radio: event.target.value})}>A
             </Radio>

<Radio name='radios'
               value={'b'}
               onChange={event => this.setState({radio: event.target.value})}>B
               </Radio>
```

onChange would only fire the first time you click on the Radio

You have to add `checked={this.state.radio === 'a'}` to make onChange always fire.

I spent a lot of time on this and found the fix here: https://stackoverflow.com/questions/45450285/radio-input-onchange-only-fires-once

It'd be nice to add checked prop to Radio's documentation.

**Comment by bpas247** [comment]
Is this issue still relevant? Seems to be pretty stale at the moment.

**Comment by mxschmitt** [comment]
We usually pass all the props to the underlying component e.g. input fields. But yes, very stale. Let's close it here.
