### ISSUE TITLE
[v4]: style handling proposal

### ISSUE THREAD

**Issue by jquense** [react-bootstrap/react-bootstrap#2829]
As we think about a move to v4 i'd like to simplify the way we handle theme variants, sizes and the like.

Right now we have a bunch of complexity around validating all these inputs. It's a nicety but adds a bunch of complexity and confusion for folks who want to tweak stuff easily.

I propose that we take reactstrap's approach here and have no specific propType validation for variants, styles, and styles, e.g

I also think that we should maybe take this time to rethink some of the names? maybe 
- bsStyle -> `variant`
- bsClass -> `variantPrefix` (intentionally verbose, most ppl shouldn't use it)
- bsSize -> `size` (this is maybe problematic b/c of the ns conflict with html input `size`

This should help remove our dependency on runtime propType usage as well.

**Comment by taion** [comment]
One thing I've been wondering about – are variants fully disjoint? It's a little weird that on `<ButtonGroup>`, `vertical` and `justified` are their own things, for example. Would they both be variants?

**Comment by jquense** [comment]
they are more disjointed than not i think. there are weird bits like that tho... we could go with what reactstrap does which is `color` which is a bit more specific but a bit too generic for my tastes...I do think that `variantPrefix` makes it sound like its solely for the variant prop tho

**Comment by taion** [comment]
sure or variant could take like an array or a space-separated string or something

**Comment by jquense** [comment]
like: e.g. `variant="primary block"`? I don't hate that...

**Comment by taion** [comment]
I guess that's more pure-component-friendly than the array thing. Yeah. What do you think? Really everything would then be a variant. Something like:

```js
<Button variant="lg info">
<Button variant="danger">
```

**Comment by meteorplus** [comment]
I think what you have now in the props format is very good otherwise if you follow reactstrap it will just bad and confusing since the color props isn't actually a color it's just the type of the button success or error ...

better keep it as you did here and IMO it's very well done :)

**Comment by meteorplus** [comment]
and what's awesome too is the documentation! so neat! so keep it up!

**Comment by jquense** [comment]
If we try the single `variant` prop, do we just not care about invalid combinations? e.g. `variant="outline-primary secondary lg sm"`

**Comment by taion** [comment]
We already said we weren't going to validate?

**Comment by jquense** [comment]
yeah, just wondering if it's ergonomic...

**Comment by taion** [comment]
Maybe we can make validation opt-in somehow.

**Comment by aaronbeall** [comment]
> `<Button variant="outline-primary secondary lg sm"/>`

This will not play nicely with type systems, either. At least TypeScript, which currently has excellent support for React-Bootstrap, has no real way to describe a property that contains a mashup of various substrings. Separating out each value as an enum is the solution. I can say for myself (using TypeScript) this mashup "variant" property would be very annoying to work with.

**Comment by taion** [comment]
How do you make that work with custom styles or sizes? Part of the thought here is that our current validation is too strict.

**Comment by aaronbeall** [comment]
@taion I probably don't really understand the use-case where you want a custom style that you pass *as a bootstrap style* -- ie wouldn't that just be a `className`?

In any case, I would expect the type-defs for those properties to describe the styles and sizes that bootstrap supports, and if you want to customize that it's on you to augment the definitions. But, again, maybe I don't understand something about people use bootstrap that they'd want to write styles that they "pretend" are built-in bootstrap styles or sizes? Personally I've just used `className` for this.

I know `react-bootstrap` certainly doesn't revolve around TypeScript, just giving my opinion as a TypeScript user of this wonderful library, about a dozen projects. :)

**Comment by taion** [comment]
@aaronbeall 

The goal right now is to let people do stuff like `<Button bsStyle="custom">` and get the class `.btn-custom`, or do something like `<Button bsClass="my-btn" bsSize="large">` and get `.my-btn-large`.

I agree that, when working with stock TWBS, it'd be nice to have type checks on the values, but it is a goal here to support custom extensions of TWBS in a nice way, and it's nice to have an easy way to follow the prefixed class name convention.

It's not "pretending", it's extending the framework.

**Comment by aaronbeall** [comment]
Sorry I didn't mean "pretend" in a derogatory way, I just mean with a property like `bsStyle` I would think that to mean a "bootstrap enumerated style" not my own custom style. But clearly this isn't how everyone thinks! Since its not an actual bootstrap style, all you are getting by passing it through the `bsStyle` is a prefix of `btn-`, right?

**Comment by jquense** [comment]
I think if we allow an array of strings as well as the one string that should be typeable? Honestly tho the reason I'm considering a single prop is that the method we have no doesn't actually work as neatly as one would imagine. There are many basic modifiers that don't fit the mold well, e.g. justified and block vs size and style.

I understand the perspective that just mimicking the classnames as the app isn't generally the best choice, but in this case that may be the simpler and clearer api.

**Comment by aaronbeall** [comment]
@jquense Yeah an array of strings would go a long way to making it more typeable. It won't provide the best experience to have something like `(BsStyle | BsSize | BsDisplay | BsDirection)[]` (or whatever you all `block | vertical | horizontal` etc)... personally I much prefer explicit component props over a space delimited string directive.

BTW thank-you guys for all the awesome work on this library!

**Comment by jquense** [comment]
Ok current thinking:

we maintain the general `bsClass`, `bsStyle`, `bsSize` breakdown (but rename them to `bootstrapPrefix`, `variant`, and `size`). We worry a bit less about uniformity across all components, I don't think it's a big deal that things likes `block` or `vertical` are technically also variants but different props. There seem to be less of them in general in v4, delegating instead to util classes, anyway. 

It's not the "cleanest" but its more inline with how other frameworks handle this stuff, like material-ui@1 and a much easy migration path than cramming them into one. Plus it's easier to add in validation for folks that want that, and works better for typing i think.

**Comment by taion** [comment]
`bsPrefix` for less typing? :p and keep `bsRole` of course. but those sounds good.

**Comment by taion** [comment]
i think this is done now
