### ISSUE TITLE
ButtonGroups which are justified do not work unless they are href'ed breaking disabled functionality

### ISSUE THREAD

**Issue by greenreign** [react-bootstrap/react-bootstrap#2832]
See PEN for results:  
https://codepen.io/greenreign/pen/JrZwLb

Button width is minimized/broke
```
<ButtonGroup justified>
  <Button>One</Button>
  <Button>Two</Button>
</ButtonGroup>
```

Buttons are justified when adding href's thus turning them into anchors
```
<ButtonGroup justified>
  <Button href='#' >One</Button>
  <Button href='#' >Two</Button>
</ButtonGroup>
```

However this breaks the btn.disabled `cursor: not-allowed`
```
<ButtonGroup justified>
  <Button href='#' disabled>One</Button>
  <Button href='#' disabled>Two</Button>
</ButtonGroup>
```

**Comment by taion** [comment]
This is a CSS thing. See the caveats on https://getbootstrap.com/docs/3.3/components/#btn-groups-justified.
