### ISSUE TITLE
Change the DropdownButton title after clicking on the MenuItem

### ISSUE THREAD

**Issue by EhsanFahami** [react-bootstrap/react-bootstrap#2834]
Hello . I'm looking for a way to change the title of DropdownButton when I click on a child.
What solution do you recommend?

**Comment by taion** [comment]
Just pass down the title as a prop and use `setState`? This isn't really related to React-Bootstrap.

**Comment by EhsanFahami** [comment]
Thanks for your guidance @taion .
I did not want to use the state for some reason, so I asked the question, so perhaps it was considered possible.
