### ISSUE TITLE
Import in body of module

### ISSUE THREAD

**Issue by edoudou** [react-bootstrap/react-bootstrap#2836]
When ever I try to "npm start" my react app, I got this error :

> ./node_modules/react-bootstrap/es/index.js
> 
>   Line 3:    Import in body of module; reorder to top  import/first
>   Line 5:    Import in body of module; reorder to top  import/first
> ...
>   Line 139:  Import in body of module; reorder to top  import/first
>   Line 141:  Import in body of module; reorder to top  import/first

I don't know where the problem comes from, it only appears recently, but I am using React-bootstrap for a month now on this projet. I tried to clone again the project and it is still the same.

I am using react-bootstrap@0.31.3

Thanks for helping.

**Comment by taion** [comment]
Your ESLint is misconfigured and is running on your dependencies.
