### ISSUE TITLE
Media.Left doesn't work correctly, if you dont add className='pull-left'

### ISSUE THREAD

**Issue by DastanSE** [react-bootstrap/react-bootstrap#2840]
`
<Media>
<Media.Left >
                    <Image
                      className='pull-left'
                      width={ 100 }
                      height={ 100 }
                      src='../../assets/img/changdi.jpg'
                      alt='Image'
                    />
                  </Media.Left>
                  <Media.Body>
                    <Media.Heading>Media Heading</Media.Heading>
                    <p>
                      Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante
                      sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus
                      viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec
                      lacinia congue felis in faucibus.
                    </p>
                  </Media.Body>
                </Media>
                <Media>
                `

**Comment by DastanSE** [comment]
![screen shot 2017-10-16 at 10 31 47](https://user-images.githubusercontent.com/24663729/31592804-6376a478-b1f0-11e7-8714-020cf58d5c3b.png)

**Comment by taion** [comment]
It works fine, you're just missing the CSS: https://react-bootstrap.github.io/components.html#media-objects

**Comment by DastanSE** [comment]
`
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/latest/css/bootstrap.min.css">


<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/latest/css/bootstrap-theme.min.css">`

No, i didn't miss it. 
Or there is another css?

**Comment by kevindtimm** [comment]
> It works fine, you're just missing the CSS: https://react-bootstrap.github.io/components.html#media-objects

This link no longer works
