### ISSUE TITLE
Button component does not appear to support ref

### ISSUE THREAD

**Issue by alexpreynolds** [react-bootstrap/react-bootstrap#2845]
Given a `<Button>` component with a `ref` attribute:

```
    <Button 
      className="some-button"
      ref="someButton"
      bsStyle="primary" 
      bsSize="xsmall"
      onClick={this.handleClick} 
      name="someButton">Some Button
    </Button>
```

Or:

```
    <Button 
      className="some-button"
      ref={(button) => { someButton = button; }}
      bsStyle="primary" 
      bsSize="xsmall"
      onClick={this.handleClick} 
      name="someButton">Some Button
    </Button>
```

Calls to `this.refs.someButton` or `this.someButton` elsewhere in the class (e.g., to change style or other properties when some event is triggered) are `undefined` and cause a fatal error.

**Comment by taion** [comment]
Refs work fine with these components. I think you're encountering some broader issue with your React setup.

**Comment by Rodrirokr** [comment]
Somebody have a working example? When I use `ref` in the `<Button>` component I only get the ref to the Button element itself, not the inner button DOM node, can someone help?

**Comment by jquense** [comment]
Yes you get the button element, you need to use findDOMNode on it. Once we only support react 16 it's likely we'll use forward Ref to get around this sort of thing in the future

**Comment by Rodrirokr** [comment]
Thank you so much, I did it like this if someone find it useful: `ReactDOM.findDOMNode(this.submitButton).focus();`

**Comment by krbrts** [comment]
I just ran into this issue and solved it by using a regular HTML button with Bootstrap classes:
`<button type="button" className="btn btn-primary btn-lg" onClick={handleClick} ref={btnRef}>`

**Comment by jquense** [comment]
You shouldn't need that, the Button component current accepts refs that are the DOM node

**Comment by krbrts** [comment]
> You shouldn't need that, the Button component current accepts refs that are the DOM node

My project uses TypeScript and strict mode ([where findDOMNode is deprecated](https://reactjs.org/docs/strict-mode.html#warning-about-deprecated-finddomnode-usage)) and it just wants no part of that.

**Comment by jquense** [comment]
like i said the ref is the DOM node, you don't need `findDOMNode`, the info from up thread is 3 years old. 

The value of the ref in both of these examples is the same: 
`<button type="button" className="btn btn-primary btn-lg" ref={btnRef}>` and `<Button ref={btnRef}/>

**Comment by krbrts** [comment]
> like i said the ref is the DOM node, you don't need `findDOMNode`, the info from up thread is 3 years old.
> 
> The value of the ref in both of these examples is the same:
> `<button type="button" className="btn btn-primary btn-lg" ref={btnRef}>` and `<Button ref={btnRef}/>`

@jquense There may be some implied knowledge that I don't have. They're not the same and `Button` doesn't work. If you can advise based on this error I'd appreciate it. If not, it doesn't do me a whole lot of good to be told the same thing and that you already said it.

![Screen Shot 2020-10-16 at 12 42 24 PM](https://user-images.githubusercontent.com/58005205/96285499-0bffbb80-0fad-11eb-881b-d3d41431fe7c.png)

![Screen Shot 2020-10-16 at 12 38 20 PM](https://user-images.githubusercontent.com/58005205/96285085-79f7b300-0fac-11eb-893a-cc1003aaf2a0.png)
