### ISSUE TITLE
Update `defaultActiveKey` on <Tabs> re-render.

### ISSUE THREAD

**Issue by DaddyWarbucks** [react-bootstrap/react-bootstrap#2849]
I have an uncontrolled `<Tabs>` components with the `defaultActiveKey`  set from a url search param, for example `.../boards?tab=1` and then `<Tabs defaultActiveKey={tab.from.url}>`.

This is working as expected, setting the default and then allowing me to switch tabs. But I noticed that when the tab re-renders (not re-mounts) with a different `defaultActiveKey`, that the tabs do not switch to that new active key. This actually makes sense, as I presume the defaultActiveKey is set in the constructor then internal component state takes over. I realize this could (and arguably should) be accomplished with a controlled Tabs component, but I really like the simplicity of the uncontrolled tabs.

Would you consider putting some logic into the `componentWillReceiveProps` method to update the active tab when the `defaultActiveKey` is different?

**Comment by taion** [comment]
The current behavior is consistent with how e.g. `defaultValue` works for uncontrolled inputs in general. As such, it's the correct behavior here. It's relatively easy to implement the state management you describe on your own, and we recommend doing so if you need it.
