### ISSUE TITLE
Modal open/hide cannot be controlled by JavaScript

### ISSUE THREAD

**Issue by hipertracker** [react-bootstrap/react-bootstrap#285]
How to open/hide the Modal component on demand using JavaScript? <Modal title="foo"/> automatically launches but never closes. Adding <Modal title="foo" onRequestHide={true}/> does not work either. Also <Modal title="foo" onRequestHide={handleHide}/> where handleHide=function(e){ ??? } does not help because it has access only to the button element, not to the whole bootstrap modal HTML. I could hack it by jQuery(e.target).parents...modal('hide') but this is very ugly and does not look like the right way.

And I do not want to use ModalTrigger because I do not want to display any visible elements.

**Comment by taion** [comment]
Looks like this question was answered a while ago. Closing for now.
