### ISSUE TITLE
How to use Tooltips with Tabs?

### ISSUE THREAD

**Issue by daredevil82** [react-bootstrap/react-bootstrap#2857]
With a Tab component, how can I add a Tooltip overlay to the button component?

```
const tooltip = text => {
    return <Tooltip>{text}</Tooltip>
};
 
<Tabs defaultActiveKey={1} animation={true} id='catalog-tabs'>
    <OverlayTrigger placement='left' overlay={tooltip('Primary tab panel')>
        <Tab eventKey={1} title='Primary'>
           // content component here
        </Tab>
    </OverlayTrigger>
</Tabs>
```

but all that occurs is this particular tab not rendering.  It would help, when building a dashboard-style application, to be able to add tooltips to layout components like this.

**Comment by taion** [comment]
Use the lower-level tab API; don't use `<Tabs>` if you need to customize the nav.
