### ISSUE TITLE
pane content inside tabs rendered incorrectly

### ISSUE THREAD

**Issue by derikson** [react-bootstrap/react-bootstrap#286]
Under certain circumstances, panes will be rendered with their content showing, but the pane closed, causing the content to overlap the panes below it.

See the code at https://gist.github.com/derikson/a1b3be59c4ee8c17a052

Using this code, if you click pane 2, then click tab 2, then click tab 1, you'll see that the content of pane 2 is displaying, but pane 2 is closed.

It appears that reverting 1a631d56dee6502d3fd3ea109cfe35df472e75ca fixes the problem.

**Comment by AlexKVal** [comment]
Same as https://github.com/react-bootstrap/react-bootstrap/issues/339
