### ISSUE TITLE
Open Modal within a ListGroupItem causes ListGroupItem onClick to fire when clicking anywhere on screen.

### ISSUE THREAD

**Issue by gavingregory** [react-bootstrap/react-bootstrap#2863]
Please refer to [jsfiddle](https://jsfiddle.net/gavingregory/ufrcwwgt/1/).

When using `react@16.0.0`, I have encountered a bug when a Modal is nested within a ListGroupItem and the ListGroupItem has an onClick property bound. Once the Modal has been opened, clicking anywhere on the screen causes the ListGroupItem's onClick event to fire.

In the jsfiddle example, the ListGroupItem's onClick event opens the modal, so the modal can no longer be closed with a mouse click as clicking anywhere re-fires the "open modal method". (check the console logs to see that the ListGroupItem's onClick event is firing).

This did not exist with react 15 and can be fixed if the Modal is not nested within the ListGroupItem, which is a valid fix but I still think there's an issue here.

versions that caused the issue:
```
    "bootstrap": "3.3.7"
    "react-bootstrap": "0.31.5"
    "react": "16.0.0"
    "react-dom": "16.0.0"
```

Hope that helps?

**Comment by taion** [comment]
This is the intended behavior: https://reactjs.org/docs/portals.html#event-bubbling-through-portals

**Comment by gavingregory** [comment]
Wonderful, thanks for that!
