### ISSUE TITLE
Modal touch events

### ISSUE THREAD

**Issue by Jaikant** [react-bootstrap/react-bootstrap#2865]
The touch events does not seem to work on the Modal. Does anyone know why?

**Comment by taion** [comment]
Please be more specific.

**Comment by Jaikant** [comment]
I am using react-rating. I use a modal to get the user rating. It works fine on a laptop with a mouse. But when I try it on a mobile device it doesn't work. The issue is on the modal as it works alright on a mobile device when not on the modal.

**Comment by taion** [comment]
Please post a minimal reproducible example. We can't really help if it's some complex interaction with a separate library.

**Comment by mxschmitt** [comment]
Closed due no response.
