### ISSUE TITLE
displaying content based on trigger event

### ISSUE THREAD

**Issue by gmarathi-nisum-com** [react-bootstrap/react-bootstrap#2866]
Hi,

Can we Display the content in overlay based on event triggered.

For example,   if trigger=[{'hover','focus'}],  overlay="focussed content"
if trigger={'click'} overlay="clicked content"

thanks.

**Comment by taion** [comment]
No; `<OverlayTrigger>` is meant to be relatively simple. If need be you use two triggers, or else write the logic yourself.
