### ISSUE TITLE
React-Bootstrap Carousel Animaton works on Chrome but not on Safari OS X with blank during slide

### ISSUE THREAD

**Issue by PSPanesar** [react-bootstrap/react-bootstrap#2867]
I am developing a web app using Next.js and React as the front end. I have install React-Bootstrap to use in my app and I've added a bootstrap carousel to my home page. It displays four slides with images from my static folder plus captions. I've followed the instructions on the react-bootstrap carousel page:

https://react-bootstrap.github.io/components.html#carousels

When I load the home page in a chrome browser the slide transition work fine with each slide transitioning in from the right with a smooth animation. When I load the same home page on Safari OS X on Mac the carousel transition does not work properly. When the a slide moves off screen the next slide is not animated in smoothly but rather pops on the screen at the end of the slide. I have not found a solution to this behaviour and I have not customised my code from the example on react-bootstrap carousel page.

I wonder if anyone could help me with advice on how to resolve this issue?

I'm assuming this must be a common issue for people using react-bootstrap but I am fairly new to it.

Thank you for your help and advice.

**Comment by taion** [comment]
This works fine for me in Safari on our components page. You should verify that there are no problems with your CSS.

**Comment by PSPanesar** [comment]
Hi, I have checked the CSS and I'm using the base CSS for bootstrap 3.3.7 with no theme in minified form. I've still got the slider issue on safari OS X 11. Is there any advice you could give to look at with this? The problem does not exist on chrome. 
Bw
P
