### ISSUE TITLE
TabbedArea: componentWillReceiveProps causes tab content to stay empty.

### ISSUE THREAD

**Issue by sokra** [react-bootstrap/react-bootstrap#287]
When updating props for a TabbedArea with new TabPanes: When a TabPane is removed while its active and animation is true, `componentWillReceiveProps` sets `previousActiveKey` to a not existing (it was removed) eventKey. This causes the tab content to stay empty (it stucks in the animation).

A possible fix would be to check in `componentWillReceiveProps` if the new `previousActiveKey` exists and set it to `null` if not.

**Comment by stathism** [comment]
In my case it doesn't fully work with animation={false} as no tab is selected when going from 2-->1 TabPane.

**Comment by magicae** [comment]
I am trapped into this bug, and with animation={false} it works. Hope fix soon.

**Comment by AlexKVal** [comment]
Pull requests are welcome :wink:

**Comment by AlexKVal** [comment]
/cc @magicae https://github.com/react-bootstrap/react-bootstrap/issues/287#issuecomment-105405690
/cc @stathism https://github.com/react-bootstrap/react-bootstrap/issues/287#issuecomment-74989419
You can check out `master` branch now. 
It contains #1017 fix merged. 
:cherries:

**Comment by magicae** [comment]
@AlexKVal 
:+1: :+1: :+1:
