### ISSUE TITLE
Inconsistent handling of disabled in onClick

### ISSUE THREAD

**Issue by mongakshay** [react-bootstrap/react-bootstrap#2870]
This is exactly similar to => https://github.com/Semantic-Org/Semantic-UI-React/issues/1964

Which was fixed in https://github.com/Semantic-Org/Semantic-UI-React/pull/2006/commits/0f111c3c9141eae5b4b29ce3d3b4ea5238b739f0

Can this be fixed in react-bootstrap as well ?

**Comment by taion** [comment]
We're not quite consistent here across `<Button>`, `<NavItem>`, and `<MenuItem>`. We should probably pick one convention and stick to it.
