### ISSUE TITLE
Documentation for onClick and onSubmit

### ISSUE THREAD

**Issue by antonmills** [react-bootstrap/react-bootstrap#2872]
Hi there,
I'm essentially trying to keep the React-Bootstrap validation in place but prevent the page refreshing as I'm building a SPA.
![image](https://user-images.githubusercontent.com/522013/32311660-ebb9623e-bfed-11e7-99a3-28fa1ec5954c.png)

I found the documentation a bit lacking and ended up going down a path which led to this:
Gist here: https://gist.github.com/antonmills/0d04b1d90cd6889ed770bd619aaf82b0

The correct solution was actually this:
https://github.com/react-bootstrap/react-bootstrap/issues/2873

Is there any thoughts on putting something like this (onSubmit, vs onClick) in the documentation to help others too? its intuitive to use the onClick of the Button which can override the refresh with preventDefaults but you lose the components inbuilt validation (unless there is another way to invoke it?).

Also, first post here - should say I really like the framework - thanks for all your time working on this.

Best,
a.

**Comment by taion** [comment]
I don't think this makes sense here – it's not a React-Bootstrap thing. This is how `<input>`s and `<form>`s and `<button>`s work in normal React too.
