### ISSUE TITLE
React Bootstrap Checkbox in Nav -> NavItem does not rerender on click

### ISSUE THREAD

**Issue by Ogglas** [react-bootstrap/react-bootstrap#2876]
I have a peculiar problem with using a `Nav ` and `NavItem` with a `Checkbox ` or `input type=checkbox`  from React Bootstrap. The thing is that if I click directly on the checkbox and not the NavItem button the checkbox will not re-render correctly but my state has updated.

Example: Given the code below I render the component and click directly on the checkbox. In this case showMap will be set to false since we set it to true in the constructor but the checkbox will still be checked in the html view. If I however click on the NavItem but not directly on the checkbox both the state showMap is updated correctly as well as the view.

I have asked the question first on StackOverflow but no luck there.

https://stackoverflow.com/questions/47116194/react-bootstrap-checkbox-in-nav-navitem-does-not-rerender-on-click

https://react-bootstrap.github.io/components.html#navs

Example here by @GarryTaylor on SO:

https://codesandbox.io/s/3r63j11pzm

    import * as React from "react";
    import * as ReactDOM from "react-dom";
    import { LinkContainer } from 'react-router-bootstrap';
    import { Col, Nav, NavItem, Checkbox } from "react-bootstrap";
    
    interface IProps {
    
    }
    
    interface IState {
        showMap: boolean
    }
    
    export class Menu extends React.Component<IProps, IState> {
        constructor(props: any) {
            super(props);
            this.state = {
                showMap: true
            }
        }
    
        toggleCheckbox = (event: any) => {
            event.preventDefault();
            this.setState({ showMap: !this.state.showMap });
        }
        
        render() {
            return (
                <div>
                    <Nav bsStyle="tabs" activeKey="1">
                        <LinkContainer to="/test">
                            <NavItem eventKey="1">Test</NavItem>
                        </LinkContainer>
                        <LinkContainer to="/test2">
                            <NavItem eventKey="2">Test2</NavItem>
                        </LinkContainer>
                        <NavItem eventKey="3" onClick={this.toggleCheckbox}><Checkbox name="showMap" inline checked={this.state.showMap} readOnly >
    					Show Map </Checkbox></NavItem>
                    </Nav>
                </div>
            )
        }
    }

**Update:**

Tried it like this as well, still the same result:

    import * as React from "react";
    import * as ReactDOM from "react-dom";
    import { LinkContainer } from 'react-router-bootstrap';
    import { Navbar, Nav, NavItem, Checkbox } from "react-bootstrap";
    
    interface IProps {
    
    }
    
    interface IState {
        showMap: boolean
    }
    
    export class Menu extends React.Component<IProps, IState> {
        constructor(props: any) {
            super(props);
            this.state = {
                showMap: true
            }
        }
    
        toggleCheckbox = (event: any) => {
            event.preventDefault();
            this.setState({ showMap: !this.state.showMap });
        }
        
        render() {
            return (
                <div>
					<Navbar>
                        <Nav bsStyle="tabs" activeKey="1">
							<LinkContainer to="/test">
								<NavItem eventKey="1">Test</NavItem>
							</LinkContainer>
							<LinkContainer to="/test2">
								<NavItem eventKey="2">Test2</NavItem>
							</LinkContainer>
                            <NavItem eventKey="5" onClick={this.toggleCheckbox}><input type="checkbox" name="showMap"
                                checked={this.state.showMap} readOnly />Show map</NavItem>
                        </Nav>
                       </Navbar>
                </div>
            )
        }
    }

**Comment by taion** [comment]
This looks like a bug with React. This happens with just:

```js
class Menu extends React.Component {
  constructor(props) {
    super(props);

    this.state = {
      showMap: true
    };
  }

  toggleCheckbox = event => {
    event.preventDefault();
    this.setState({ showMap: !this.state.showMap });
  };

  render() {
    return (
      <div>
        <h1>{this.state.showMap ? "Show" : "hide"}</h1>
        <a href="#" role="button" onClick={this.toggleCheckbox}>
          <input
            type="checkbox"
            title="test" 
            name="showMap"
            checked={this.state.showMap}
            readOnly
          />
          asdf
        </a>
      </div>
    );
  }
}
```

**Comment by taion** [comment]
It seems like it has to do with the `preventDefault`. I'd file an issue upstream.

**Comment by Ogglas** [comment]
Hello @taion 

This is not an issue with React. If I remove `event.preventDefault();` it works in React but not in React Bootstrap. Please re-open this.

Not working example with react bootstrap:

```
import React from "react";
import { render } from "react-dom";
import { LinkContainer } from "react-router-bootstrap";
import { Nav, NavItem, Checkbox } from "react-bootstrap";
import { BrowserRouter as Router } from "react-router-dom";

class Menu extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      showMap: true
    };
  }

  toggleCheckbox = event => {
    this.setState({ showMap: !this.state.showMap });
  };

  render() {
    return (
      <div>
        <h1>{this.state.showMap ? "Show" : "hide"}</h1>
        <Nav bsStyle="tabs" activeKey="1">

          <NavItem eventKey="3" onClick={this.toggleCheckbox}>
            <Checkbox
              title="test" 
              name="showMap"
              inline
              checked={this.state.showMap}
              readOnly
            >Show Map</Checkbox>
          </NavItem>
        </Nav>
      </div>
    );
  }
}

const App = () => (
  <Router>
    <div>
      <Menu />
      <h2>Start editing to see some magic happen {"\u2729"}</h2>
    </div>
  </Router>
);

render(<App />, document.getElementById("root"));
```

Working example with only react:

```
class Menu extends React.Component {
  constructor(props) {
    super(props);

    this.state = {
      showMap: true
    };
  }

  toggleCheckbox = event => {
    this.setState({ showMap: !this.state.showMap });
  };

  render() {
    return (
      <div>
        <h1>{this.state.showMap ? "Show" : "hide"}</h1>
        <a href="#" role="button" onClick={this.toggleCheckbox}>
          <input
            type="checkbox"
            title="test" 
            name="showMap"
            checked={this.state.showMap}
            readOnly
          />
          asdf
        </a>
      </div>
    );
  }
}
```

**Comment by taion** [comment]
You'd never want to use code like that in practice, though. You need to call `preventDefault` in `<a onClick>` to prevent the link from scrolling your page to the top.

**Comment by Ogglas** [comment]
@taion That's true. Created an issue with React. https://github.com/facebook/react/issues/11539
