### ISSUE TITLE
Multple errors summarized to Interface x incorrectly extends interface y.

### ISSUE THREAD

**Issue by parissge** [react-bootstrap/react-bootstrap#2879]
I have 8 errors in my project all related with the below message:
Error	TS2430	(TS) Interface 'PopoverProps' incorrectly extends interface 'Pick<HTMLProps<Popover>, "title" | "accept" | "acceptCharset" | "action" | "allowFullScreen" | "a...'.
  Types of property 'title' are incompatible.
    Type 'ReactNode' is not assignable to type 'string'.
      Type 'number' is not assignable to type 'string'.	Modelia.Web (tsconfig project)	C:\Test\node_modules\@types\react-bootstrap\lib\Popover.d.ts

Severity	Code	Description	Project	File	Line	Suppression State
Error	TS2430	(TS) Interface 'ProgressBarProps' incorrectly extends interface 'Pick<HTMLProps<ProgressBar>, "title" | "accept" | "acceptCharset" | "action" | "allowFullScreen" ...'.
  Types of property 'label' are incompatible.
    Type 'ReactNode' is not assignable to type 'string'.
      Type 'number' is not assignable to type 'string'.	Modelia.Web (tsconfig project)	C:\Test\node_modules\@types\react-bootstrap\lib\ProgressBar.d.ts

.......... and more..........

I don't know what to do to resolve this. I have updatedall npm packages running npm update.
Currently my package.json is:
  "devDependencies": {
    "@types/jquery": "^3.2.16",
    "@types/react": "^16.0.22",
    "@types/react-bootstrap": "^0.31.7",
    "@types/react-dom": "^16.0.3",
    "awesome-typescript-loader": "^3.3.0",
    "css-loader": "^0.28.7",
    "expose-loader": "^0.7.3",
    "extract-text-webpack-plugin": "^3.0.2",
    "file-loader": "^1.1.5",
    "source-map-loader": "^0.2.3",
    "typescript": "^2.6.1",
    "url-loader": "^0.6.2",
    "webpack": "^3.8.1"
  },
  "dependencies": {
    "jquery": "^3.2.1",
    "react": "^16.1.0",
    "react-bootstrap": "^0.31.5",
    "react-dom": "^16.1.0"
  }

Can anyone please advise me what to do?

**Comment by taion** [comment]
The TS defs don't live in this repo. Follow up in the appropriate place.

**Comment by parissge** [comment]
Sorry, what is the appropriate place?
I am new to this.

**Comment by taion** [comment]
Try https://github.com/react-bootstrap/react-bootstrap-typescript

**Comment by JanezStupar** [comment]
@parissge how did you work around this issue?
