### ISSUE TITLE
Support for Horizontal Layout of Radio Buttons and Check Boxes

### ISSUE THREAD

**Issue by justin808** [react-bootstrap/react-bootstrap#288]
I don't believe there is support for horizontal layout of radio buttons and check boxes.

I tried something like

```jsx
      <form className="form-horizontal">
        <h5>Input Group Label</h5>
        <Input type="radio" label="Input Label 1" wrapperClassName="col-sm-offset-2 col-sm-2" />
        <Input type="radio" label="Input Label 2" wrapperClassName="col-sm-offset-4 col-sm-2" />
        <Input type="select" label='Long Field Label' defaultValue="select" labelClassName="col-xs-2" wrapperClassName="col-xs-10">
          <option value="select">select</option>
          <option value="other">...</option>
        </Input>
        <hr/>
      </form>
```

![radio-horizontal](https://cloud.githubusercontent.com/assets/1118459/5158350/1dd749e4-72de-11e4-97c2-b5b2a917213b.jpg)

**Comment by chrisbianca** [comment]
It looks like this is because react-bootstrap puts each <Input> within it's own form-group wrapper.

I'd imagine that the fix is not particularly trivial, but it would be good if this could be supported.  Horizontal layout for radio buttons and check boxes is pretty common on the web...

**Comment by chrisbianca** [comment]
I did find a workaround to this.  It's not great from a HTML perspective, but did allow me to display some radio buttons side by side:

    <Input label="sex" labelClassName="col-sm-2" wrapperClassName="col-sm-10">
        <Input name="sex" type="radio" ref="male" value="male" label="Male" groupClassName="col-sm-2" />
        <Input name="sex" type="radio" ref="female" value="female" label="Female" groupClassName="col-sm-2" />
    </Input>

**Comment by mtscout6** [comment]
This would probably get easier once we split those things out, see #342

**Comment by taion** [comment]
Per upstream docs, the correct class to use here is actually `.form-inline` if you want an inline form. `.form-horizontal` just makes the labels be horizontal.

Alternatively, wrap everything yourself up in `Col` elements to use the grid.
