### ISSUE TITLE
Shouldn't it be here <Form> instead of <form>

### ISSUE THREAD

**Issue by cowCrazy** [react-bootstrap/react-bootstrap#2880]
https://github.com/react-bootstrap/react-bootstrap/blob/d0fb4d316f0c8f79b8c89368d508fc5a458ce910/docs/examples/FormInputAddons.js#L2

**Comment by taion** [comment]
It's fine actually – `<Form>` doesn't do anything unless you specify either `horizontal` or `inline`.
