### ISSUE TITLE
TypeScript type declaration for AccordionProps is missing `activeKey` and other properties

### ISSUE THREAD

**Issue by antmdvs** [react-bootstrap/react-bootstrap#2881]
AccordionProps is missing `activeKey`, `defaultActiveKey` and `onSelected` per [the docs](https://react-bootstrap.github.io/components.html#panels-props-group). Related to #2639

**Comment by taion** [comment]
Typings don't live in this repo – please file this against https://github.com/react-bootstrap/react-bootstrap-typescript.
