### ISSUE TITLE
Tabs' content overlap in Modal

### ISSUE THREAD

**Issue by LarryZhao0616** [react-bootstrap/react-bootstrap#2882]
Hi,

I'm a new front-end developer. Here I want to make a login page. But I found my tabs' content shows in a wrong place, overlap with the tabs. like this:
<img width="509" alt="screen shot 2017-11-14 at 10 59 31" src="https://user-images.githubusercontent.com/6835509/32793294-1ade1e74-c92b-11e7-8ef4-bfd8f1f17460.png">
this is my code:

```
class LoginRegisForm extends React.Component{

    render (){
        return(
        <div>
          <Modal show={this.props.show} onHide={this.props.onHide}>
            <Modal.Header closeButton>
              <Modal.Title> Welcome  </Modal.Title>
            </Modal.Header>
            <Modal.Body style={{marginTop:"2rem"}}>
              <Tabs defaultActiveKey={1} id="loginTabs">
                <Tab eventKey={1} title="Sign in"><Button> 11</Button></Tab>
                <Tab eventKey={2} title="New account"><Button> 22</Button> </Tab>
              </Tabs>
            </Modal.Body>
            <Modal.Footer>
            </Modal.Footer>
            </Modal>
        </div>
        );
    }
}
export default LoginRegisForm;
```

I can use some 'br' in content to solve this : 
```
<Tab eventKey={1} title="Sign in">
                  <br/>
                  <br/>
                  <br/>
                  <Button> 11</Button></Tab>
```
<img width="493" alt="screen shot 2017-11-14 at 11 04 08" src="https://user-images.githubusercontent.com/6835509/32793456-92705510-c92b-11e7-89ea-02dd5997cb67.png">

But can someone help me to explain why??
==============================update===============================
BTW: The modal will show when I click a button in NavBar. I found without this NavBar, there is no overlap problem.

**Comment by taion** [comment]
This doesn't happen when we drop this into our component examples page. As such I think it's an issue with your CSS.
