### ISSUE TITLE
Release a v0.32 alpha

### ISSUE THREAD

**Issue by jansohn** [react-bootstrap/react-bootstrap#2885]
I want to use one of the bug fixes available in the `next` branch. How can I switch to the `next` branch easily in my `package.json`?

I've tried `"react-bootstrap": "react-bootstrap/react-bootstrap#next"` followed by an `npm install` but it does not download any JS sources.

**Comment by taion** [comment]
We'd need to cut a release. It'd be the prereleases for the next minor release.

**Comment by jansohn** [comment]
I'd definitely appreciate it!

**Comment by taion** [comment]
We released v0.32.0.
