### ISSUE TITLE
Modal in case of backdrop={'static} or false

### ISSUE THREAD

**Issue by knnemade99** [react-bootstrap/react-bootstrap#2886]
I used the property backdrop='static' or false for a modal, but with that the fields inside a modal can be focused from the outside click on modal
area clicked outside modal is shown by black circle.

![untitled](https://user-images.githubusercontent.com/20987636/33006281-cb7906e0-cdef-11e7-90f1-53fa05b91743.png)

**Comment by taion** [comment]
That doesn't have anything to do with the backdrop property as far as I'm aware. The modal does capture focus, though, for a11y.
