### ISSUE TITLE
[BUG] Child element Panel 

### ISSUE THREAD

**Issue by kenzouno1** [react-bootstrap/react-bootstrap#2887]
I wan't custom panel with #1769 but throw to erros
###My Render Method
````
 render() {
        return (
            <Col md={4}>
                <Panel >
                    <Panel.Heading>
                        <Panel.Title>hello</Panel.Title>
                    </Panel.Heading>
                    <Panel.Body>
                        world
                    </Panel.Body>
                </Panel>
            </Col>
        );
    }
````
````Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.````

**Comment by taion** [comment]
This was merged to `next`, not `master`. We don't have a release cut from that branch yet. You can track https://github.com/react-bootstrap/react-bootstrap/issues/2885.
