### ISSUE TITLE
Supporting React-Router v4?

### ISSUE THREAD

**Issue by kajmagnus** [react-bootstrap/react-bootstrap#2889]
Hi, looks to me as if React-Router v4 is not yet supported, right? Are there any plans to upgrading to v4 now the nearest month(s) or so?

Details:  `"react-router": "^2.6.1",` is in `packaes.json`, which I would think in practice means that React-Bootstrap works with v2 and v3 of React-Router. At least I've been using React-Router v3 with React-Bootstrap and it's been working fine. In v4, though, React-Router did a complete rewrite, so I suppose upgrading React-Bootstrap to -Router v4 might take some time.

**Comment by taion** [comment]
That's a development-only dependency used for generating our docs page, and it will go away with https://github.com/react-bootstrap/react-bootstrap/pull/2818. React-Bootstrap works with your choice of routing framework, and doesn't have any compat issues.

**Comment by kajmagnus** [comment]
Thanks! I just noticed that yes, it works for me with v4 too, and I was going to go here and close this issue.
