### ISSUE TITLE
Unknown prop `active` on <div> tag. Remove this prop from the element.

### ISSUE THREAD

**Issue by robinprashanth** [react-bootstrap/react-bootstrap#2890]
I am using following code 
`<NavDropdown eventKey={2} title="User 1" id="basic-nav-dropdown" className="navbar-name">
              <RadioGroup
                name="userroles"
                selectedValue={this.state.currentUser}
                onChange={this.handleRoleChange}
              >
                <div className="userList"><Radio className="radioB" value="HeadOfficials" /> Headquarters Officials </div>
                <div className="userList"><Radio className="radioB" value="ComplianceOff" /> Compliance Officers </div>
                <div className="userList"><Radio className="radioB" value="DeskOfficers" /> Desk Officers </div>
                <div className="userList"><Radio className="radioB" value="FocalPoints" /> Focal Points </div>
                <div className="userList"><Radio className="radioB" value="Visitors" /> Visitors </div>
              </RadioGroup>
            </NavDropdown>`

Here RadioGroup is a 3rd party component.When I add this component inside Navdropdown I get below error. Can anyone help fixing this issue?
![capture](https://user-images.githubusercontent.com/3203423/33126488-b1ee2afe-cfaa-11e7-80f9-3f9c76864e11.PNG)

**Comment by taion** [comment]
You can't put `<div>`s directly under `<Nav>`. Use `<NavItem>`.
