### ISSUE TITLE
rootCloseEvent doesn't work on custom dropdown

### ISSUE THREAD

**Issue by DennisOosterling** [react-bootstrap/react-bootstrap#2891]
Exactly what the title says,

I found this issue: https://github.com/react-bootstrap/react-bootstrap/issues/2762
Pointing out that the logic is implemented in DropdownMenu.

It is at least confusing that the documentation shows rootCloseEvent as a property in the Dropdown Component. See:
![image](https://user-images.githubusercontent.com/31688709/33176595-de472442-d05f-11e7-961e-ec83e06f78ce.png)

Perhaps a mention of this would be appropriate?

**Comment by jquense** [comment]
Care to PR a tweak to the docs?

**Comment by YouNoCanNoBB** [comment]
i have the same confusion

**Comment by kevinzwhuang** [comment]
Just opened #2903 to add this to the docs.
