### ISSUE TITLE
NavDropdown does not get active class when NavDropdown is clicked

### ISSUE THREAD

**Issue by otakueadwine** [react-bootstrap/react-bootstrap#2892]
For some reason my NavDropdown button does not get the active class when selected. The activeKey remains the previously selected NavItem. I'm fairly new to react and typescript, perhaps I'm doing something wrong?

I have the following navbar setup:
```
<Nav bsStyle="pills" stacked activeKey={this.state.activeKey} onSelect={this.handleSelect}>
        <NavItem eventKey={1} href="#">
                Nav 1
        </NavItem>
	<NavItem eventKey={2} href="#">
		Nav 2
	</NavItem>
	<NavItem eventKey={3} href="#">
		Nav 3
	</NavItem>
	<NavDropdown id="nav-dropdown-4" eventKey={4} title="Item 1">
		<MenuItem eventKey={4.1} href="#">Item 1.1</MenuItem>
		<MenuItem eventKey={4.2} href="#">Item 1.2</MenuItem>
		<MenuItem eventKey={4.3} href="#">Item 1.3</MenuItem>
	</NavDropdown>
</Nav>
```

With the following select handler:
```
public handleSelect(selectedKey: React.SyntheticEvent<Nav>) {
	this.setState({activeKey: selectedKey});
}
```

![schermafbeelding 2017-11-27 om 13 41 19](https://user-images.githubusercontent.com/8110976/33267153-b507023e-d378-11e7-8134-4804a943b5e8.png)
In this example I expect Nav 3 to not be active and Item 1 to be active.
The handleSelect does not seem to be called at all when I click Item 1

**Comment by taion** [comment]
This was partially addressed in https://github.com/react-bootstrap/react-bootstrap/pull/2423, though that PR didn't sort out into a mergeable state. It would be great if someone could pick up on it, though.

**Comment by otakueadwine** [comment]
@taion That is really too bad :( Is there a way to get the eventKey property of that dropdown when using an onclick event for example? It would be nice if I could just reset the activeKey state and possibly set it to the eventKey

**Comment by taion** [comment]
It's a bug in `<NavDropdown>`. The code in the PR above mostly resolves it. It can't really be addressed by doing stuff from outside.

**Comment by otakueadwine** [comment]
Allright ended up creating a custom onClick listener for the nav dropdown in which I send the correct active key. Probably not the prettiest, but it works ;)

![schermafbeelding 2017-12-05 om 10 05 36](https://user-images.githubusercontent.com/8110976/33598700-01cc31b2-d9a4-11e7-93f3-3d53f27435b3.png)

```
<NavDropdown id="nav-dropdown-4" eventKey={4} title="Item 1" onClick={(e) => this.handleDropdownSelect(4)}>
```

```
public handleDropdownSelect(key: number) {
	this.setState({activeKey: key});
}
```
