### ISSUE TITLE
Modal element not removed from DOM after transition

### ISSUE THREAD

**Issue by sfeldkamp** [react-bootstrap/react-bootstrap#2894]
The Modal element used to be removed from the DOM after the Fade transition was completed.  After upgrading from 0.30.9 to 0.31.5 the element remains in place.

This causes the screen to be unclickable because the inline style display:block overrides the display:none from the .modal class.

Also upgraded to react@16.1.1 and react-dom@16.1.1

**Comment by sfeldkamp** [comment]
It turns out a (vendor) script was moving any .dialog elements and appending them to the body.  Thus it was not removed from the DOM and continued to block the screen.

inspinia.js if anyone else is experiencing this.  Comment near the offending code says that it was to "Fix Bootstrap backdrop issue with animation.css".

**Comment by houzhitaohzt** [comment]
The Modal element used to be removed from the DOM after the Fade transition was completed. I've got it now

**Comment by houzhitaohzt** [comment]
> It turns out a (vendor) script was moving any .modal elements and appending them to the body. Thus it was not removed from the DOM and continued to block the screen.
> 
> inspinia.js if anyone else is experiencing this. Comment near the offending code says that it was to "Fix Bootstrap backdrop issue with animation.css".
> 
> I'm not certain why this was not an issue in 0.30.9, but was an issue in 0.31.5 but the fault is clearly not react-bootstrap.

how to solve it ?
