### ISSUE TITLE
Cannot add dragable=false attribute to Thumbnail element

### ISSUE THREAD

**Issue by VicoErv** [react-bootstrap/react-bootstrap#2897]
```html
    <Col xs={3}>
      <Thumbnail src={single48_a}>
        <h4><Label bsStyle='primary'>¥ 914</Label></h4>
        <p>Negaigoto no Mochigusare Type-A</p>
      </Thumbnail>
    </Col>
```

how to add draggable attribute to img in `Thumbnail` element?

**Comment by karuppasamy** [comment]
@VicoErv `react-bootstrap` is not supporting draggable events. You could try this [react-draggable](https://github.com/mzabriskie/react-draggable).

#2260 #2685

**Comment by VicoErv** [comment]
I mean, if I drag an image, there will be shadow of image following my mouse, I want to disable that using draggable=false argument. maybe there is an alternative for this?

**Comment by VicoErv** [comment]
![untitled](https://user-images.githubusercontent.com/26959883/34415835-4f539240-ec23-11e7-8d55-bd19e4b0d4d2.png)
if I drag image like that, there will be a shadow following, so I need to make it not draggable

**Comment by karuppasamy** [comment]
Oh. yeah. there is no support for this (and any extra) attribute;  only these attributes [ {src, alt, onError, onLoad} ](https://github.com/react-bootstrap/react-bootstrap/blob/master/src/Thumbnail.js#L46) will be accepted in the `img` tag.

But, you could do this by CSS.

```
.unselectable {
  -moz-user-select: none;
  -webkit-user-select: none;
  -ms-user-select: none;
  user-select: none;
}
```

Ref: https://developer.mozilla.org/en-US/docs/Web/CSS/user-select#CSS
