### ISSUE TITLE
Error when viewing code in components documentation 

### ISSUE THREAD

**Issue by mike-kelly** [react-bootstrap/react-bootstrap#2898]
When clicking 'show code' on examples at the documentation page, [https://react-bootstrap.github.io/components#](https://react-bootstrap.github.io/components#), an error results:
`Uncaught Error: Minified React error #34` and the code is not displayed.

**Comment by taion** [comment]
Interesting. This will go away once we merge #2818 though.

**Comment by jquense** [comment]
lets merge #2818 i jsut need to solve the dang local package thing GRRR

**Comment by taion** [comment]
Seems to work fine now
