### ISSUE TITLE
Handeling a click on the radio buttons, where there is no change of the selected button 

### ISSUE THREAD

**Issue by carpben** [react-bootstrap/react-bootstrap#2904]
I'm using a toggleButtonGroup of type radio. This component uses the function onChange to which it passes the value of the new selected button upon change. While I'd like it to act as a radio button, and allow only one selected button at a time, I also want an action to fire when there is a click on the button. I tried using the onClick property. The problem it passes a proxy to the given function, and not the selected button value. 
I can give examples to common radio buttons that work this way. Just for example - gmail's inbox button. while only one button box can be selected at a time, pressing the same button renders a function. 
I'm looking for an elegant way to solve this. If I have both onChange and onClick properties, will they both fire upon change?

**Comment by taion** [comment]
You'll need to implement it yourself. If it's not something you get out-of-the-box with standard radio buttons in React (and I don't think it is), it's not something we're going to provide here.
