### ISSUE TITLE
FormControl (select), placeholder and selected value don't show

### ISSUE THREAD

**Issue by DennisOosterling** [react-bootstrap/react-bootstrap#2907]
When using a FormControl of the select type the placeholder and selected value don't show in the selectbox.

example:
![image](https://user-images.githubusercontent.com/31688709/34098942-4730569a-e3de-11e7-8a50-1dd32a66dae5.png)

When selecting a value the onChange gets triggered with the correct value.

```jsx
 <FormGroup controlId="formControlsSelects">
                    <Col componentClass={ControlLabel} sm={2}>
                        Beerstyle
                </Col>
                    <Col sm={10}>
                        <FormControl componentClass="select" placeholder="select" name="beerstyle" onChange={props.handleChange}>
                            <option value="AmberAle">Amber ale</option>
                            <option value="PaleAle">Pale ale</option>
                        </FormControl>
                    </Col>
</FormGroup>
```

even the example code has the same effect: 

```jsx
 <FormGroup controlId="formControlsSelect">
      <ControlLabel>Select</ControlLabel>
      <FormControl componentClass="select" placeholder="select">
        <option value="select">select</option>
        <option value="other">...</option>
      </FormControl>
    </FormGroup>
```

**Comment by jquense** [comment]
This would a limitation of the native select component. RB (or React for that matter) doesn't implement placeholder, so what you see is just how the browser input works unfortunately

**Comment by DennisOosterling** [comment]
Ok so apparently it's my mistake, but still nice to know for other people I think.
So when you override the padding of a select component with something like:

```css
padding: 20px 12px;
```

The padding somehow pushes away the text, this is only in select component and not in the other form components.

As an alternative you can use: 

```css
height: 45px;
```

Thanks @jquense for your help
