### ISSUE TITLE
CollapsableMixin errors if unmounted before it's mounted

### ISSUE THREAD

**Issue by mathieumg** [react-bootstrap/react-bootstrap#291]
Currently, if we try to unmount a component that uses `CollapsableMixin` before it's done being mounted, we get an error because the DOM node doesn't exist yet.

I tried changing [this line](https://github.com/react-bootstrap/react-bootstrap/blob/master/src/CollapsableMixin.js#L87) to:

```
var node = this.isMounted() && this.getCollapsableDOMNode();
```

and it fixed the problem. Before submitting a PR, I wanted to validate that this was effectively the underlying issue and that I fixed it at the right level in the call chain (I imagine it could be fixed below or higher up...)

In my case it was that line that triggered the error, perhaps it should be the done doing the check instead: https://github.com/react-bootstrap/react-bootstrap/blob/c7a2cbfc166719040a571435da4982be073da0cc/src/Nav.jsx#L35

Thank you.

**Comment by mtscout6** [comment]
@joemcbride This may also relate to the Panel stuff you're doing today.

**Comment by AlexKVal** [comment]
I guess it is not a bug anymore, because it has been deprecated.
