### ISSUE TITLE
Tooltip Anchoring Issue

### ISSUE THREAD

**Issue by ethankong113** [react-bootstrap/react-bootstrap#2910]
The tooltip seems to be anchoring from top left corner instead of the tail of the tooltip. This causes an issue when the tooltip content changes from a very short text to a very large text. The size of the tooltip gets changed but the positioning of it stays the same. Is there anyway to fix this issue?

**Comment by taion** [comment]
Can you elaborate? This seems to work fine on our components pag

**Comment by ethankong113** [comment]
Let's say you have a button that shows the tooltip when you hover over it. And when you click the button, the tooltip message changes. This is not a problem when the message length before and after are about the same. But if you do something like "ok" first and then changes to "this is a really really really really really really really really really really really really really really really really really really really really really string." The tooltip would enlarge proportionally, which is great. But it is anchoring at the top left corner, so the tail of the tooltip gets pushed down.

I'm wondering why is it anchoring by the top left corner instead of the tail.. and is there anyway to fix it or bypass it?

**Comment by taion** [comment]
It's not "anchoring", that's just how absolute positioning for this sort of thing works. Turn on position recalculation if you're changing contents

**Comment by ethankong113** [comment]
i have seen this issue reported before: https://github.com/react-bootstrap/react-bootstrap/issues/1229

But position recalculation is not documented.. Where can I find the related info?

**Comment by ethankong113** [comment]
Actually I found it after digging it into the source code, there's this `shouldUpdatePosition` for react-overlay and I'm able to fix it. Thanks for the hint.
