### ISSUE TITLE
Consider moving away from `ReactDOM.unstable_renderSubtreeIntoContainer`?

### ISSUE THREAD

**Issue by krazi3** [react-bootstrap/react-bootstrap#2911]
This is more of a suggestion than an issue.

I was trying to use the `OverlayTrigger` component and found that my `mouseover` and `mouseout` events did not bubble properly. By looking at the code i discovered that the overlays were added to the dom through the `unstable render` function. Although i found this approach quite interesting but the event bubbling was an issue for me ... i have solved this issue by making my own `CustomOverlayTrigger` component and removed the `unstable render` stuff and added the overlays to the dom like normal jsx elements. I was wondering that if we could get rid of `unstable renders` to solve some issues like events bubbling or is this the decided way? Btw the popover components perfectly mimics the functionality of the popover in the Bootstrap v3 library.

Thanks

**Comment by jquense** [comment]
If you use react v16 it will use the newer `createPortal` api, which will have events buble through as if they were actually sub elements, prior versions tho really have top use renderSubtreeIntoContainer though

**Comment by jkjustjoshing** [comment]
@jquense can you point out where `<OverlayTrigger>` uses the `ReactDOM.createPortal()` API? I don't see that anywhere in the source code. Thanks!
