### ISSUE TITLE
npm run build error

### ISSUE THREAD

**Issue by owzzyozz** [react-bootstrap/react-bootstrap#2912]
Please assist me in solving this issue

$ npm run build

> fireadmin@0.1.0 build C:\Users\Mercy\Desktop\radio Android\radioAdminPanel
> react-scripts build

Creating an optimized production build...
Failed to compile.

./src/containers/Master.js
1:2268-2276 "export 'default' (imported as 'firebase') was not found in './../config/database'

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fireadmin@0.1.0 build: `react-scripts build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fireadmin@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Mercy\AppData\Roaming\npm-cache\_logs\2017-12-26T09_54_13_880Z-debug.log

Thanks.

**Comment by taion** [comment]
This appears to have nothing to do with React Bootstrap.
