### ISSUE TITLE
Compatibility with Bootstrap v4 beta2

### ISSUE THREAD

**Issue by Justplayit** [react-bootstrap/react-bootstrap#2913]
Hey guys, I was wondering if this package is compatible with Bootstrap v4 beta 2, because I've tried using the Modal component, only to find out that it does not show on the screen, because its using CSS classes ```fade in``` instead of ```fade show```(which is now in Bootstrap v4). Thanks.

**Comment by taion** [comment]
see https://github.com/react-bootstrap/react-bootstrap/pull/2752
