### ISSUE TITLE
Documentation is dead

### ISSUE THREAD

**Issue by TeoTN** [react-bootstrap/react-bootstrap#2924]
https://react-bootstrap.github.io/ returns 404 File not found

**Comment by jquense** [comment]
yup its back up now

**Comment by TeoTN** [comment]
Nope, it's not :P
![404](https://user-images.githubusercontent.com/5840198/34581980-b5613a96-f192-11e7-8041-5f00ff381567.PNG)

**Comment by taion** [comment]
Works fine for me. The URLs are changed around, though. Instead of https://react-bootstrap.github.io/components.html, it's now e.g. https://react-bootstrap.github.io/components/alerts/.
