### ISSUE TITLE
Accordions allow more than one panel open as of 0.32.0

### ISSUE THREAD

**Issue by leviwheatcroft** [react-bootstrap/react-bootstrap#2926]
Previously, the behaviour with a PanelGroup accordion was that when you expanded one panel, the previous panel would collapse. This no longer occurs. You can see this behaviour [in the docs](https://react-bootstrap.github.io/components/panel/#panels-accordion).

I note that previously the example in the docs used `<Accordion>` where now the docs are using `<PanelGroup accordion>`, but I'm not sure if that's relevant.

**Comment by mreishus** [comment]
Running into the same problem.  If I copy and paste the `PanelGroupControlled.js` example ( https://github.com/react-bootstrap/react-bootstrap/blob/5ff1962588facf4a51d59ac9aea558330133cc3c/docs/examples/PanelGroupControlled.js ) I can open multiple panels.

**Comment by jquense** [comment]
anyone want to take a stab at a fix?

**Comment by taion** [comment]
This was fixed in #2940
