### ISSUE TITLE
How to toggle a DropdownButton programmatically?

### ISSUE THREAD

**Issue by rkpatel33** [react-bootstrap/react-bootstrap#2928]
How can I a toggle `DropdownButton` programmatically? I intend to do it via Electron shortcut but not sure what to hook into.

I tried setting `defaultOpen` to a state variable that I can then toggle like so:

`defaultOpen = { this.state.defaultOpen }`

But this does not seem to work. 

Could not find anything in the documentation or the issues regarding this so sorry if its a repeat.

**Comment by taion** [comment]
Pass in `open` as a prop:
