### ISSUE TITLE
0.32.0 Typescript support

### ISSUE THREAD

**Issue by asaarnak** [react-bootstrap/react-bootstrap#2929]
I bumped into this when updating dependencies.
Is this repo the right place to create this issue or shoud it be in DefinitelyTyped repo?

Here are the Typescript definitions for 0.31.x version only. https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-bootstrap

**Comment by taion** [comment]
They're in https://github.com/react-bootstrap/react-bootstrap-typescript, not here.

**Comment by patsissons** [comment]
@taion are you suggesting https://github.com/react-bootstrap/react-bootstrap-typescript is the official typings repo for `react-bootstrap`?

**Comment by taion** [comment]
I believe so, yes.

**Comment by patsissons** [comment]
it is extremely outdated compared to the DT typings, doesn't appear to even support TS 2.x, and isn't consumable via npm?

**Comment by gytisgreitai** [comment]
IMHO DefinitelyTyped is the way to go.
