### ISSUE TITLE
Window object in utilities causes not defined error in server side rendering

### ISSUE THREAD

**Issue by zquintana** [react-bootstrap/react-bootstrap#2936]
While attempting to convert an app to isomorphic architecture I ran into an issue with this module because it was attempting to use the global window object. That causes an issue with server side rendering because it’s not defined. That in turn breaks the entire rendering engine. Anyway this module can be updated to shim the window? I used a module called window-or-global to shim my project modules. Perhaps this package could take advantage of the same module to solve that hole in server side rending.

**Comment by jquense** [comment]
Do you have any info one what specifically is accessing window? We already attempt to make sure this doesn't happen, and test that components are SSR-able. More than likely the error is coming from something else, or there is a regression we don't know about

**Comment by zquintana** [comment]
It was my mistake. The problem was in the bootstrap javascript not in react-bootstrap. Sorry for the confusion.
