### ISSUE TITLE
Website Components Documentation Gone

### ISSUE THREAD

**Issue by hdon** [react-bootstrap/react-bootstrap#2937]
Not sure if this is the right repo for this issue...

This page has gone missing:

https://react-bootstrap.github.io/components.html

Is there a replacement or a new URL?

**Comment by jquense** [comment]
Please check the issues before posting new one thanks!

**Comment by hdon** [comment]
I did search the issues for components.html. Wasn't sure what else to look for.

Could you point me to the relevant issue(s)?

Thanks :)

**Comment by jquense** [comment]
Any of the 4 issues closed this week about the same thing. The url changed with new documentation
