### ISSUE TITLE
Modals Require I add code to stop redirecting?

### ISSUE THREAD

**Issue by AdamKyle** [react-bootstrap/react-bootstrap#294]
So I have a modal:

```js
  <ReactBootstrap.ModalTrigger modal={<PostsListModal post={post}/>}>
    <a href="javascript: void(0)" id="info" className="icon-info move-left-10px push-bottom-10px">
      <i className="fa fa-info-circle"></i>
    </a>
  </ReactBootstrap.ModalTrigger>
```

Now if I click this link with out the `javascript: void(0)` what will happen is that the modal will open but the page redirects to "#".

I could add a `onClick` event, but with how the modal works today in bootstrap, you don't need that because they allow you to append a modal to anything.

So is this something I am doing wrong or is this a legit bug?

**Comment by mtscout6** [comment]
This is a CSS styling issue and not an issue with react-bootstrap.
