### ISSUE TITLE
Bug in exemplary code on web in section forms.

### ISSUE THREAD

**Issue by JanKaifer** [react-bootstrap/react-bootstrap#2941]
There is custom function which doesn't work properly:
```
function FieldGroup({ id, label, help, ...props }) {
	return (
		<FormGroup controlId={id}>
			<ControlLabel>{label}</ControlLabel>
			<FormControl {...props} />
			{help && <HelpBlock>{help}</HelpBlock>}
		</FormGroup>
	);
}
```
It throws this error:
```
TypeError: Cannot read property 'line' of undefined
```
However, when I remove this one by using props as an argument:
```
function FieldGroup(props) {
	return (
		<FormGroup controlId={props.id}>
			<ControlLabel>{props.label}</ControlLabel>
			<FormControl {...props} />
			{props.help && <HelpBlock>{props.help}</HelpBlock>}
		</FormGroup>
	);
}
```
It works.

So if someone could tell why react-live doesn't support this function({arg1, arg2, arg3, ...args}) {...} feature.

Link to playground: https://react-bootstrap.github.io/components/forms/?radioGroup=on#forms-controls

**Comment by taion** [comment]
dupe https://github.com/react-bootstrap/react-bootstrap/issues/2933
