### ISSUE TITLE
Unable to import Panel.X

### ISSUE THREAD

**Issue by hoodsy** [react-bootstrap/react-bootstrap#2944]
```js
import { Panel } from 'react-bootstrap'

<Panel>
    <Panel.Heading>Panel heading without a title</Panel.Heading>
    <Panel.Body>Panel content</Panel.Body>
</Panel>
```

Throws errors that `Panel.Heading` and `Panel.Body` aren't components – I can only import `Panel`. Attempting to collapse `Panel` throws errors: `TypeError: cannot read property 'style' of null`

**Comment by taion** [comment]
Make sure you have the right version of React-Bootstrap installed. You're probably on an older version.

**Comment by hoodsy** [comment]
I'm on the latest, 0.32.0... working around using `lib/X` imports

**Comment by leviwheatcroft** [comment]
Are you using any webpack loaders to manipulate your jsx ? For example, I use react-pug so I can't use dot notation. I need to deconstruct like:

```
cosnt { Body: PanelBody } = Panel
return pug` PanelBody Panel Body`
```

`Panel.Heading` and `Panel.Body` definitely work, maybe try logging the `Panel` object to the console to see what you're getting.

**Comment by hoodsy** [comment]
I've wiped `node_modules`, etc at this point... can use `Panel.Body` and the rest with no issue.

But I get an error pointing to `Transition` whenever `Panel.Collapse` is triggered. Separate issue, but maybe related.

**Comment by Aiso786** [comment]
I'm having the same issue but looks like the typescript definition file is not up to date.

**Comment by davisford** [comment]
also cannot use panel subcomponents.

```
$ npm ls | grep bootstrap
+-- react-bootstrap@0.31.5
```

**Comment by taion** [comment]
They’re not in that version.

**Comment by obayol** [comment]
Could anyone solve this problem? I'm currently trying to solve it.

**Comment by taion** [comment]
They're only present in v0.32.x. The 1.0.0 betas that track BSv4 do not have a `<Panel>` component, as it's no longer present upstream.
