### ISSUE TITLE
Input element in Tab title - spacebar is not registered

### ISSUE THREAD

**Issue by frees11** [react-bootstrap/react-bootstrap#2946]
Hi, with input element in Tab title, spacebar is not registered, but every other key works. 

Here is example of this markup
`<Tab eventKey={i}   title={<Input value={} onChange={} />}></Tab>`

It seems that, problem is similar to this one https://github.com/atlassian/react-beautiful-dnd/issues/149, but I wasn't able to repair it with their solution, could you please help me?

**Comment by taion** [comment]
If you're looking to customize the nav items for a tab group, use the lower-level components instead of `<Tabs>` and `<Tab>`.

**Comment by frees11** [comment]
It's not solved, because even with custom layout spacebar is still eaten when there is input in tab title

I need to mimic excel sheet, that's reason why I need this behaviour

`<Tab.Container id="left-tabs-example" defaultActiveKey="first">
	<Row className="clearfix">
		<Col sm={4}>
			<Nav bsStyle="pills" stacked>
				<NavItem eventKey="first"><Input value={} onChange={} /></NavItem>
				<NavItem eventKey="second"><Input value={} onChange={} /></NavItem>
			</Nav>
		</Col>
		<Col sm={8}>
			<Tab.Content animation>
				<Tab.Pane eventKey="first">Tab 1 content</Tab.Pane>
				<Tab.Pane eventKey="second">Tab 2 content</Tab.Pane>
			</Tab.Content>
		</Col>
	</Row>
</Tab.Container>;`
