### ISSUE TITLE
New Pagination component doesn't properly documented

### ISSUE THREAD

**Issue by adrian3d** [react-bootstrap/react-bootstrap#2947]
Hey !

How can I get value of PaginationItem I click ? This doesn't appear on [documentation](https://react-bootstrap.github.io/components/pagination/#pagination). onSelect worked on the old Pagination Component.

Thanks.

**Comment by jquense** [comment]
There isn't an `onSelect` anymore, the component is purely presentational, to better match the "real" bootstrap. You'll have to implement login on top of it or use something like this: https://github.com/react-bootstrap/pagination/blob/master/stories/experiment.js
