### ISSUE TITLE
Example in Documentation over 'Supported Controls' for Forms displays 'TypeError'.

### ISSUE THREAD

**Issue by I2oy** [react-bootstrap/react-bootstrap#2948]
Going through the examples for creating Forms and viewing the different examples, there seems to be an issue in one section that is currently displaying an error instead.

`TypeError: Cannot read property 'line' of undefined`

The location of the error is located in this section:
[https://react-bootstrap.github.io/components/forms/#forms-controls](https://react-bootstrap.github.io/components/forms/#forms-controls)

**Comment by taion** [comment]
dupe https://github.com/react-bootstrap/react-bootstrap/issues/2933
