### ISSUE TITLE
Pagination.Item onSelect doesn't work

### ISSUE THREAD

**Issue by SergeyAlexeev** [react-bootstrap/react-bootstrap#2949]
Hi, after upgrade to the `0.32.0` version I can't handle an event when the current page is changed.

Previously, I used the `onSelect` prop of the `Pagination` component. I found the similar [prop](https://github.com/react-bootstrap/react-bootstrap/blob/master/src/PaginationItem.js#L11) for `Pagination.Item` but it [doesn't work](https://stackblitz.com/edit/react-ffk9qy?file=index.js). So, how do you recommend handling such event?

Moreover, when I use the code from your [docs](https://react-bootstrap.github.io/components/pagination/#pagination):
```js
let active = 7;
let items = [];
for (let number = 1; number <= 10; number++) {
  items.push(
    <Pagination.Item active={number === active}>{number}</Pagination.Item>
  );
}
```

I have the warning `Each child in an array or iterator should have a unique "key" prop.` Yes, it's quite easy to fix, but I think the code that is copy-pasted from docs should work without warnings or exceptions.

Thanks!

[UPD]

I found the similar [issue](https://github.com/react-bootstrap/react-bootstrap/issues/2947). But still, It would be great if you remove `onSelect` from code-base))

**Comment by sarimj-cc** [comment]
React-bootstrap-pagination is not that much robust. It is just basic.
