### ISSUE TITLE
Inconsistent behavior of disabled pagination and pager items

### ISSUE THREAD

**Issue by SergeyAlexeev** [react-bootstrap/react-bootstrap#2950]
Disabled pagination item has the related 🚫 icon as a mouse cursor. But pager disabled item doesn't.

This [sample](https://stackblitz.com/edit/react-npdsa4?file=index.js) shows it in action.

According to [Bootstrap docs](https://getbootstrap.com/docs/3.3/components/#pagination), both items in disabled state should have the same behavior and use 🚫 icon as a mouse cursor.

**Comment by GoPro16** [comment]
For the time being I have just an inline conditional for these items put most likely going to fix this and create pull request.

`
<Pagination.Last
     disabled={current == pages.length}
     onClick={() => setPage(pages.length)}
>
     &raquo;
</Pagination.Last>
`

**Comment by bpas247** [comment]
Is this still an issue in the latest release (`v1.0.0-beta.14`)?

**Comment by kosmiq** [comment]
Closing since no feedback for a long time.
