### ISSUE TITLE
[Web] bsStyle is wrong

### ISSUE THREAD

**Issue by xurei** [react-bootstrap/react-bootstrap#2951]
In Alert and Buttons (probably elsewhere also) : 
![screenshot from 2018-01-17 17-24-09](https://user-images.githubusercontent.com/621695/35053760-49017c80-fbab-11e7-92c8-6e8839a81868.png)

It should be "danger", "warning", "info", "success".

**Comment by sboudouk** [comment]
Is this why I've an error when I follow the Utilities example for custom CSS ? 

Exemple: `<Button bsSize="large" bsStyle="custom-register">Register</Button>` generate a Warning in Chrome console.

**Comment by heatherbooker** [comment]
I tried to find the docs code to update this but I am having no luck - if anyone can point it out, maybe we can get it fixed faster!

**Comment by sermustang** [comment]
@heatherbooker I think it in this [part](https://react-bootstrap.github.io/components/buttons/#buttons-props) of docs.

**Comment by heatherbooker** [comment]
@sermustang Can you find the code that is behind those parts of the docs?

**Comment by sermustang** [comment]
@heatherbooker Sorry, I don't know where to search code of the docs.

**Comment by sboudouk** [comment]
@sermustang This is what you're looking, I guess : https://github.com/react-bootstrap/react-bootstrap/blob/master/src/utils/bootstrapUtils.js

**Comment by taion** [comment]
I'm not sure why, but the problem went away when I republished the docs.
