### ISSUE TITLE
No "dropright" prop for <Dropdown /> component

### ISSUE THREAD

**Issue by DhawalRank** [react-bootstrap/react-bootstrap#2952]
No "dropright" prop for <Dropdown /> component for opening dropdown on right of the dropdown button. Bootstrap has class "dropright" for it.

Are you going to add that to this?

**Comment by taion** [comment]
That's a TWBS4 thing; currently this targets TWBS3. If you need extra classes, you can add them yourself

**Comment by DhawalRank** [comment]
I am sorry! I realized that later that it is only provided by BS4.
