### ISSUE TITLE
Submit Bootstrap Form Programmatically?

### ISSUE THREAD

**Issue by EdwaRen** [react-bootstrap/react-bootstrap#2953]
I have been trying to find a submit to submit forms programmatically with React-Bootstrap similar to how in JavaScript we could write
```
document.getElementById("FormSubmit").submit();
```

I have tried using refs in React however the form does not appear to be submitting. Is there a way to do this using React-Bootstrap, or would I have to rethink the interface to only support button-based form submission?
```
var MyForm = React.createClass({
  handleSubmit: function(e){
   //Do stuff
  },
  submitForm : function(e){
    this.refs.theForm.submit();
  },
  render: function() {
    return (
    <Form ref=“theForm” onSubmit={this.handleSubmit} horizontal method="POST" action="/users" enctype="multipart/form-data" >
    <FormControl type = 'text' name='myInput'/>
    <a onClick={this.submitForm}>Submit</a>
    </Form>);
  }
});

ReactDOM.render(
  <MyForm />,
  document.getElementById(‘root’)
);
```

**Comment by dozoisch** [comment]
@EdwaRen I'm not sure why you would put an anchor instead of a input[type=submit] or button[type=submit] given that they are more accessible and allow for keyboard base submission. Also on mobile browsers will change the carriage return button to a submit button instead.

**Comment by EdwaRen** [comment]
@dozoisch I see, I suppose it is much easier to just do everything with a button type submit. However, a client requirement is to have custom invalid input error messages be rendered when the user *clicks* the submit button. Currently, the Form's onSubmit() function does work however it gets instantly redirected to the POST request without displaying an error message for invalid inputs.

Or maybe this is getting overcomplicated and I should just convince the client that <input required> suffices.

**Comment by dozoisch** [comment]
If you don't want the redirection to happen, you need to prevent default on the event.

**Comment by EdwaRen** [comment]
Hmmm, I'll take a nice look at manipulating the defaults on the submission event. Thanks for taking the time to help!!

**Comment by dozoisch** [comment]
I'll go ahead and close this issue. Ping me if there is anything and we can reopen it.
