### ISSUE TITLE
Panel's descendants ignores "bsClass" prop

### ISSUE THREAD

**Issue by sermustang** [react-bootstrap/react-bootstrap#2954]
Panel's descendants such as <Panel.Heading> ignores "bsClass" prop.
There is no prop "bsClass" for Panel itself but it can implements it in incorrect way.

Here is a [jsfiddle](http://jsfiddle.net/jecj38h2/3/)

**Comment by taion** [comment]
Well, we do want them to share the `bsClass` on `<Panel>`, as the alternative API would be a bit of a pain to use. Are you trying to override the `bsClass` on just the heading/&c. elements in a way inconsistent with the parent? That seems a bit odd.

**Comment by sermustang** [comment]
I've override `bsClass` prop just for example. I also tried it together with default class names. 
I think it's possible to use `bsClass` in `<Panel.Heading>` and others like in `<Modal>` components for example. [Here](http://jsfiddle.net/jmrd4wLt/1/) is an example what I mean with `<Modal.Header>`.  

Maybe I'm wrong in something.

**Comment by taion** [comment]
Right, we're not fully consistent here. Overall, though, it seems like it would be better to have components inherent the class from the parent, no?

If you have `bsClass="custom-panel"` on the parent, then it seems reasonable to have `.custom-panel-heading` on a heading child.

**Comment by sermustang** [comment]
So, if child components inherit the class from parent it's needed to remove prop `bsClass` of `<Panel.Heading>` and others from docs.

And on my opinion, in some cases it's usefull to have possibility to add some extra class only to child component like in `<Modal>` components. But it's not necessary, we can add needed styles in CSS with default classes.

Anyway, thank you for responses and for your framework.

**Comment by taion** [comment]
It's hard to say what the right thing is.

I think the resolution order should be:
1. Explicit `bsClass` on child component
2. Something calculated from `bsClass` on parent component
3. Default `bsClass`

How does that sound?

**Comment by sermustang** [comment]
For me it's the best solution.

**Comment by montycheese** [comment]
Is there any status on this issue?

**Comment by bpas247** [comment]
> Is there any status on this issue?

Seems to be pretty stale right now, but I'm guessing this issue is only relevant to our Bootstrap 3 implementation since `Panel` isn't in our bootstrap 4 implementation.

**Comment by kyletsang** [comment]
Closing since bs3 is no longer supported
