### ISSUE TITLE
is it compatible with new version v16 of react ? 

### ISSUE THREAD

**Issue by toolaugh** [react-bootstrap/react-bootstrap#2958]
- I found that It  has problems with modal ? Is it resolved ?

**Comment by jquense** [comment]
its compatible with v16, yes

**Comment by toolaugh** [comment]
when update v16 . I got a problem like this : 
![errr](https://user-images.githubusercontent.com/15774100/35313501-456c4102-00f3-11e8-8d30-2ae784d76d39.PNG)
-  How can I resolve ?. thanks a lot

**Comment by toolaugh** [comment]
@jquense
