### ISSUE TITLE
Tooltip's arrow position

### ISSUE THREAD

**Issue by GTDunk** [react-bootstrap/react-bootstrap#2962]
Discovered an incorrect behavior of tooltips with 'OverlayTrigger'. It can be found also on a page with examples: https://react-bootstrap.github.io/components/tooltips/#tooltips-overlay-trigger. In case of a resized window, the arrow of a tooltip is shifted and is not centered anymore:
![image](https://user-images.githubusercontent.com/31467161/35326348-7464402c-0107-11e8-85de-497d2cd1d8ea.png)

**Comment by taion** [comment]
You'd need to enable recalculating position in these cases.
