### ISSUE TITLE
React Hot Loader v4 causes ProgressBar prop type warning

### ISSUE THREAD

**Issue by Kimahriman** [react-bootstrap/react-bootstrap#2963]
I am trying to upgrade my project from React Hot Loader v3 to v4, and it's causing me to have a prop type warning with the ProgressBar component. It looks like the ProgressBar checks that all children are also ProgressBars, but I guess RHLv4 basically wraps every component, so this check fails even though the child is actually a (proxied) ProgressBar.

Is there a way make this check more lenient and work with proxied components? I haven't found a way to disable a specific warning in React and I don't want to turn off all warnings.

**Comment by taion** [comment]
Yes, RHLv4 exposes a way to check for this. I guess you can PR a fix to use that check? @jquense do you think that's reasonable?

**Comment by Kimahriman** [comment]
If that's acceptable I can work on that
