### ISSUE TITLE
Make it easier to find the documentation for a given component

### ISSUE THREAD

**Issue by taion** [react-bootstrap/react-bootstrap#2964]
Right now, if all you have is a component name, it's not always straightforward to find the docs for that component, unless I'm missing something.

It'd be nice if there were a easy way to find that.

**Comment by lorenwrightdesign** [comment]
Would it be helpful to have an index of all of the components on https://react-bootstrap.github.io/getting-started/introduction with links to each component? If so, I could work on that!

**Comment by taion** [comment]
Maybe. A manual list would get out of sync, though. What can Gatsby do for us?

**Comment by jquense** [comment]
I think there a few search plugins as well

**Comment by BoyWithSilverWings** [comment]
A search plugin on top of the sidebar should help

**Comment by taion** [comment]
I guess we'll track https://github.com/react-bootstrap/react-bootstrap/issues/3042 instead
