### ISSUE TITLE
Collapsable Panel animation jumps when opening and closing

### ISSUE THREAD

**Issue by Temmermans** [react-bootstrap/react-bootstrap#2966]
Hard to explain so check out this little video (I'm using chrome):

![gif](https://user-images.githubusercontent.com/14975555/35470046-0df205c6-0342-11e8-85e1-15fecd66d068.gif)

Notice how for the collapsable panel with larger content, the last part jumps. The smaller content panel does not animate at all when opening.

I tried to remove the padding from my element but it still behaves the same way.

Am I missing something? (I just copied the code from the docs and pasted it in, nothing custom here).

**Comment by taion** [comment]
see https://github.com/react-bootstrap/react-bootstrap/pull/1463
