### ISSUE TITLE
Tooltip remains visible after disabling element

### ISSUE THREAD

**Issue by captain-igloo** [react-bootstrap/react-bootstrap#2969]
See #1432 which has been closed but the problem still exists.  When you click on the button it becomes disabled and the tooltip remains visible.

I am using React 16.2.0 and react-bootstrap 0.32.0.

```javascript
import React, { Component } from 'react';
import { OverlayTrigger, Tooltip, Button } from 'react-bootstrap';

export default class LinkWithTooltip extends Component {

    constructor() {
        super();
        this.onClick = this.onClick.bind(this);
        this.state = {
            disabled: false,
        };
    }

    onClick() {
        this.setState({
            disabled: true,
        });
    }

    render() {
        const tooltip = <Tooltip id="tooltip">tooltip</Tooltip>;

        return (
            <OverlayTrigger overlay={tooltip}>
                <Button
                    onClick={this.onClick}
                    disabled={this.state.disabled}
                >
                    click me
                </Button>
            </OverlayTrigger>
        );

    }

}
```

**Comment by taion** [comment]
Is this another side-effect of our disabling pointer-effects?

**Comment by jquense** [comment]
i don't think so the `pointer-events` thing merely mimics the behavior of a native `button` element, and only for anchor elements which the example above isn't rendering right?

**Comment by murphyke** [comment]
I'm seeing this also, react-bootstrap 0.32.1, React 16.4.0.

**Comment by keul** [comment]
I'm working on this, see https://github.com/react-bootstrap/react-bootstrap/pull/3251

The solution if the PR is not the best probably, as at every click on the OverlayTrigger container the tooltip will be closed. This is probably acceptable for buttons, but what about form elements?

However: another solution is not that easy: I think this is happening because browsers stop triggering _onmouse-something-like_ events when an element became disabled, so there's no easy way to track this kind of change.

Any suggestion about a different approach is welcome.

**Comment by keul** [comment]
Some other hint about this is mostly a browser behavior: https://developer.mozilla.org/en-US/docs/Web/Events/mouseleave#Browser_compatibility

* Issue is not hitting Firefox 61
* Issue can be reproduced on Chrome 68 (see below)

![react-bootstrap-2969](https://user-images.githubusercontent.com/284924/44838080-93f2a200-ac3b-11e8-98e8-a30a158bd032.gif)

**Comment by keul** [comment]
Just in case folks are looking for a workaround to this, explicitly adding an `onClick` on the `OverlayTrigger` worked for me (using the same approach of my pull request, so maybe not optimal, but still better than the current bug):

```jsx
<OverlayTrigger
        ref={(ov) => {
          this.overlayTrigger = ov;
        }}
        onClick={() => {this.overlayTrigger.handleDelayedHide()} }
        {...whatever}
      >
        <div {...rest}>{children}</div>
      </OverlayTrigger>
```

**Comment by mehagar** [comment]
I'm still seeing this using `react-bootstrap@0.33.1`.
