### ISSUE TITLE
Accordion not working using code from documentation

### ISSUE THREAD

**Issue by ecabrera1** [react-bootstrap/react-bootstrap#2971]
ERROR: Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components). Check the render method of `Accordion`.

CODE: 
import React, { Component } from 'react';
import { Panel, PanelGroup } from 'react-bootstrap';

export default class Accordion extends Component {
    constructor(props, context) {
      super(props, context);
  
      this.handleSelect = this.handleSelect.bind(this);
  
      this.state = {
        activeKey: '1'
      };
    }
  
    handleSelect(activeKey) {
      this.setState({ activeKey });
    }
  
    render() {
      return (
        <PanelGroup
          accordion
          id="accordion-controlled-example"
          activeKey={this.state.activeKey}
          onSelect={this.handleSelect}
        >
          <Panel eventKey="1">
            <Panel.Heading>
              <Panel.Title toggle>Panel heading 1</Panel.Title>
            </Panel.Heading>
            <Panel.Body collapsible>Panel content 1</Panel.Body>
          </Panel>
          <Panel eventKey="2">
            <Panel.Heading>
              <Panel.Title toggle>Panel heading 2</Panel.Title>
            </Panel.Heading>
            <Panel.Body collapsible>Panel content 2</Panel.Body>
          </Panel>
        </PanelGroup>
      );
    }
  }

**Comment by kjrocker** [comment]
I'm having the same problem with Panels more generally. Logging out `Panel.Body` or any other Panel sub-component shows they're undefined.

**Comment by taion** [comment]
It's likely that you either have the wrong version installed, or else it's something weird with TypeScript.
