### ISSUE TITLE
Modal does not work in React 16.2.0

### ISSUE THREAD

**Issue by mwaz** [react-bootstrap/react-bootstrap#2972]
I am using modal boxes and my version of react does not render them using the react strap  bootstrap, here is my . code

what could the problem be?

<img width="1436" alt="screen shot 2018-01-31 at 20 23 18" src="https://user-images.githubusercontent.com/10160787/35637213-9f4a4c38-06c4-11e8-8c75-64b849ab43dd.png">

**Comment by mahongquan** [comment]
I use react 16.2.0 and react-bootstrap 0.32.0, it is ok for me.
 "dependencies": {
    "bootstrap": "^3.3.7",
    "chart.js": "^2.3",
    "flux": "^3.1.3",
    "immutability-helper": "^2.6.4",
    "moment": "^2.20.1",
    "react": "^16.2.0",
    "react-autosuggest": "^9.3.2",
    "react-bootstrap": "^0.32.0",
    "react-chartjs-2": "^2.6.4",
    "react-datetime": "^2.11.1",
    "react-dom": "^16.2.0",
    "yarn": "^1.3.2"
  }

**Comment by taion** [comment]
Works fine on our docs page as well.
