### ISSUE TITLE
Dropdown does not open

### ISSUE THREAD

**Issue by lal12** [react-bootstrap/react-bootstrap#2973]
Hello,

I have a Nav and in it a NavDropdown, but when I click on it, the child menu is not popping up. So I did some debugging and found that it actually is opened, but directly afterwards closed again, due to the rootClose eventListener. So I guess there should be an event.stopPropagation() in the dropdown onClick Handler anyway. I would create a PR myself, but I cannot exactly see where this should happen. I am also unsure if this is an bootstrap or an react-bootstrap related bug.

**Comment by taion** [comment]
Works fine on our docs example: https://react-bootstrap.github.io/components/navs/#navs-dropdown

**Comment by lal12** [comment]
It seems that this issue somehow related to preact, because with react it works.
