### ISSUE TITLE
Modal closed on mouse up

### ISSUE THREAD

**Issue by qtbit** [react-bootstrap/react-bootstrap#2974]
1. go to https://react-bootstrap.github.io/components/modal/
2. click `Launch demo modal` button in `Basic example` section.
3. start selecting text inside the shown modal by pressing the left mouse button and hold
4. move the mouse outside the modal window and release the mouse button

**desired behavior**: the modal is not closed, since you select text inside
**actual behavior**: the modal closes and your selected text is lost

**Comment by taion** [comment]
Dupe https://github.com/react-bootstrap/react-bootstrap/issues/1785
