### ISSUE TITLE
Can't specify place where modal is appended

### ISSUE THREAD

**Issue by qtbit** [react-bootstrap/react-bootstrap#2975]
The Modal component always adds elements to `body` element and it cannot be changed.
This causes issues with styling.

E.g. you have a section element with class="settings" in an app.
Define a CSS style for it: `.settings .modal { font-size: 30px }`
Render a react component to the section element displaying a popup by using the React-Bootstrap Modal component.

However, the Modal component appends its elements to `body` element of the page, so the style does not work. I suppose you can't adjust CSS style to be global  `.modal { font-size: 30px }` since the app already use such class `.modal` for other components.

Please add a possibility to set target element into which the modal will append its elements.

**Comment by jquense** [comment]
The modal won't work correctly if it's appending to the a nest component like that, because css `position: fixed` is weird. Warning a aside you can control this by changing the `container` prop
