### ISSUE TITLE
Fix Bootstrap CSS version in CDN link in documentation

### ISSUE THREAD

**Issue by rimatla** [react-bootstrap/react-bootstrap#2978]
Navigation broke the UI out of the blue without me touching any of the files with the navigation code using react-bootstrap "^0.32.1"

In one page refresh the site went from:
![screen shot 2018-02-04 at 2 39 42 pm](https://user-images.githubusercontent.com/14306250/35782145-5c726074-09b9-11e8-9139-ccac6f8a1040.png)

to:
![screen shot 2018-02-04 at 2 41 46 pm](https://user-images.githubusercontent.com/14306250/35782159-b0fb0560-09b9-11e8-8bf4-b3ac83a6d010.png)

There are no errors showing in the console.

**EDIT:**
Issue occurring on Chrome, Firefox and Safari, However still works on Opera (for now).

**Comment by VonTran** [comment]
same issue a long with misalignment of columns 
![firefox](https://user-images.githubusercontent.com/15680299/35782361-b1b922ec-09c4-11e8-9533-0129d26ec367.png)
![jan24](https://user-images.githubusercontent.com/15680299/35782363-b3c5290a-09c4-11e8-81dd-3d0b450173c0.png)

**Comment by rimatla** [comment]
How's possible to have all broken after I had the library version locked into my package.json?

**Comment by VonTran** [comment]
It probably doesn't have much to do with the actual package. You use a required cdn in your head to pull down the styles it's something wrong with that.

**Comment by rimatla** [comment]
You're right, updating the CDN worked. But... That's a vulnerability, my question to the developers here is how can I prevent such issue after my app is shipped to prod?

**Comment by taion** [comment]
Seems unrelated to this package then. In general if these things matter, either use hashes or don’t use third party CDNs.

**Comment by Planeshifter** [comment]
While the issue was not caused by the react-bootstrap package, it can be reproduced by loading the stylesheets from the CDN suggested in the documentation:

```
!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/latest/css/bootstrap.min.css">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/latest/css/bootstrap-theme.min.css">
 ```

I suggest you change these as otherwise many more users will run into this issue. Thanks!

**Comment by rimatla** [comment]
My case exactly. I used that cdn per documentation's instructions.

**Comment by taion** [comment]
Thanks. I updated the issue topic to reflect the actual problem. Feel free to submit a PR.

**Comment by NikhilVerma** [comment]
We have this same issue with our application as well, the CSS has completely broken the layout. It seems like the CDN is pointing to https://maxcdn.bootstrapcdn.com/bootstrap/latest/css/bootstrap.min.css which is Bootstrap version 4.

**Comment by apelsina** [comment]
I've replaced "latest" to "3.3.7" in the link in my index.html and everything seems back to normal for now.
Thank everyone for investigation.

**Comment by RyanNerd** [comment]
Are the docs somewhere I can fork, fix and submit a PR? Spent the last 3 hours pulling my hair out trying to figure out why the bootstrap styling for Tabs went stupid. Here's my fix (in `styles.scss` -- see @apelsina comment as well):

`@import url("https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css");`

**Comment by jquense** [comment]
🙄  ya'll last few folks could have sent a PR fixing this in the time it took to complain about it. this has been fixed (not sure about deployed)

**Comment by taion** [comment]
We updated the docs page.
