### ISSUE TITLE
Bootstrap 4 makes react-bootstrap break

### ISSUE THREAD

**Issue by wijhuang** [react-bootstrap/react-bootstrap#2983]
In react-bootstrap getting started section, we must include stylesheet in order to work
```
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/latest/css/bootstrap.min.css">
```
but it didn't work, I tried and the problem is because Bootstrap in the CDN is 4.0.0
If I change to Bootstrap 3.3.7 it works
```
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
```

I wonder if Bootstrap 4 is unsupported for now?
or 
do you have solution to migrate to bootstrap 4?

**Comment by jquense** [comment]
Please see the other issues, RB is bootstrap v3 at the moment, we love help getting to v4 compatible, check out the discussion and PR

**Comment by wijhuang** [comment]
Thank you very much
