### ISSUE TITLE
Dropdowns not expanding in browser (CDN)

### ISSUE THREAD

**Issue by robbiemilejczak** [react-bootstrap/react-bootstrap#2985]
I have an app that uses React Bootstrap. Afaik 30 days ago it was working without any issue. It is running on react 15.6.1, reactDOM 15.6.1, react-bootstrap 0.32.1, and using bootstrap 4.0 styles with no theme. 

I am receiving no errors, and when I inspect the element the "open" class does toggle on click and aria expanded is set to true, which leads me to believe it's a stylesheet issue. From what I can tell the rendered HTML is identical to the rendered HTML in your site examples.

Here is a small fiddle showcasing the issue: https://jsfiddle.net/6419ngkg/

I've tested on both Firefox Nightly and the latest stable Chrome release and it is happening on both.

The fiddle is on react 16 but I can confirm the issue seems to be version agnostic in regards to react. I hope I'm just doing something blatantly wrong and you can point it out to me. Thanks for your time and I love this library!

**Comment by robbiemilejczak** [comment]
The stylesheet listed in your docs:

```
Because React-Bootstrap doesn't depend on a very precise version of Bootstrap, we don't ship with any included css.

<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/latest/css/bootstrap.min.css">
```

was the problem. I had to switch to bootstrap 3.3.7 to make it work. Here's a link for anyone who ends up here with the same issue: https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css

**Comment by sekharp** [comment]
Robbie, thank you so much for finding this! I had some solid trouble figuring out the issue here for a small app I built. This was super helpful :fireworks:
