### ISSUE TITLE
Checkbox in Navbar.Form vertical alignment not correct when there are no other elements in the Form

### ISSUE THREAD

**Issue by Warkst** [react-bootstrap/react-bootstrap#2989]
I am working on a React app in which I use react-bootstrap for styling. I am using a `Navbar` with only 2 elements, a `Navbar.Header` (with nested `Navbar.Brand`) and a `Navbar.Form`. Inside the form, I placed only a `Checkbox`. In the browser, the resulting label and input are not vertically aligned on the baseline of the brand.

A quick fix is to add a `Button` with `style={{visibility: 'hidden'}}`, but I suppose this should not be necessary?

**Comment by taion** [comment]
That sounds like purely a CSS issue. We don't manage the CSS here, so it's possible that combination just isn't supported by your CSS.
