### ISSUE TITLE
ButtonToolbar order messed if using DropdownButtons

### ISSUE THREAD

**Issue by nnarhinen** [react-bootstrap/react-bootstrap#299]
Consider following code:

```js
var buttons = [], menuitems = [];

menuitems.push(ReactBootstrap.MenuItem({}, 'Menuitem 1'));
menuitems.push(ReactBootstrap.MenuItem({}, 'Menuitem 2'));

buttons.push(ReactBootstrap.Button({}, '1. Normal button'));
buttons.push(ReactBootstrap.DropdownButton({
    title: '2. Dropdown button',
    children: menuitems
}));

var App = React.createClass({
    render: function() {
        return ReactBootstrap.ButtonToolbar({
            children: buttons
        });
    }
});

React.render(App(), document.getElementById('app'));
```

The rendered output is ordered wrong (Dropdownbutton is leftmost, then the normal button):

![image](https://cloud.githubusercontent.com/assets/265438/5300397/7e2739f0-7bd8-11e4-8fb4-4bd73bbc7d38.png)

It's because `.btn-group` has `float: left` in bootstrap CSS.

I don't know if this even should be considered a bug or one that could be handled by react-bootstrap.

Still surprising it is.

Live demo at: http://jsfiddle.net/w4hsaz6s/

**Comment by AlexKVal** [comment]
Superceded by #526
