### ISSUE TITLE
Latest styling from CDN causes breaking changes

### ISSUE THREAD

**Issue by philest** [react-bootstrap/react-bootstrap#2991]
Following the docs, I'm pulling in the stylesheets via CDN: 

```
    <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/latest/css/bootstrap.min.css" %>
```

Sometime over the past few days, the `latest/` CDN import caused breaking changes on styling, mostly by changing `_reboot.scss` to have new default styles. 

Importing instead from `3.3.7` fixed the breaking changes: 

```
    <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" %>
```

Here's the original view, as well as the breaking change: 

<img width="1280" alt="screenshot 2018-02-08 11 10 04" src="https://user-images.githubusercontent.com/7172356/35983856-0a660fdc-0cc1-11e8-9f0a-ba6c2f2f4ecf.png">

<img width="1280" alt="screenshot 2018-02-08 11 09 26" src="https://user-images.githubusercontent.com/7172356/35983847-05ebecec-0cc1-11e8-975a-b909f0111e97.png">

**Comment by taion** [comment]
We updated the docs page to recommend pinning TWBS v3  https://react-bootstrap.github.io/getting-started/introduction
