### ISSUE TITLE
Have a copy paste code feature 

### ISSUE THREAD

**Issue by Abhay07** [react-bootstrap/react-bootstrap#2993]
It would be really helpful to have a copy paste the examples using a copy button.

**Comment by taion** [comment]
I don't think that's really worth adding here. The examples aren't really meant to be used as-is; they're more for illustration purposes.

**Comment by jquense** [comment]
they really can't be copy and pasted anyway, there is a lot of hidden environement to running them (for the sake of illustrating the api)
