### ISSUE TITLE
Overlay, container, and target

### ISSUE THREAD

**Issue by ddelrio1986** [react-bootstrap/react-bootstrap#2995]
I am trying to setup a custom overlay and am having a bit of trouble understanding how the overlay component works. On the documentation page I see a container and target prop referenced in some places but they are not listed in the list of props at the bottom. What are these props for?

**Comment by taion** [comment]
see https://react-bootstrap.github.io/react-overlays/

**Comment by ddelrio1986** [comment]
Thank you so much!!!

**Comment by pavs94** [comment]
This link shows a blank page now.

**Comment by taion** [comment]
Thanks for bringing this to our attention. We're working on fixing it. For now, use https://react-bootstrap.github.io/react-overlays/overlay/.
