### ISSUE TITLE
Custom overlays requires passing down className to enable transitions

### ISSUE THREAD

**Issue by ghidosoft** [react-bootstrap/react-bootstrap#2997]
I was implementing a custom overlay but I cannot make the `Fade` (that's the default) transition work.

I later discovered that I have to pass down the `className` prop to my custom div. I think that the Custom overlays documentation (https://react-bootstrap.github.io/components/overlays/#custom-overlays-overlay) should reflect this, the edit is pretty simple, just add `className` and `className={className}`:

```jsx
function CustomPopover({ className, style }) {
  return (
    <div
      className={className}
      style={{
        ...style,
        position: 'absolute',
        backgroundColor: '#EEE',
        boxShadow: '0 5px 10px rgba(0, 0, 0, 0.2)',
        border: '1px solid #CCC',
        borderRadius: 3,
        marginLeft: -5,
        marginTop: 5,
        padding: 10
      }}
    >
      <strong>Holy guacamole!</strong> Check this info.
    </div>
  );
}
```

**Comment by jquense** [comment]
Happy to take PR improving the example!

**Comment by ghidosoft** [comment]
Hi @jquense, PR opened!
