### ISSUE TITLE
Tab samples don't set state because aren't defined with arrow functions

### ISSUE THREAD

**Issue by hanspoo** [react-bootstrap/react-bootstrap#2999]
I've just doing copy paste with the samples of the Tab component, i noticed that state didn't get updated after setState, then i double looked at the event handlers definition and noticed they are not defined with arrow functions and then "this" is not binded to the component (but eventually to the window  object), the best solution was to redefine handlers as arrrow functions. I guess  in the new version for bootstrap 4 everything is defined with arrows and may be this post is a little obsolete.

**Comment by taion** [comment]
Our playground environment doesn't support class properties. The `ControlledTabs` example does have the `.bind(this)` in the constructor, though, so it is correct.
