### ISSUE TITLE
addStyle from bootstrapUtils warning in 2.13.0

### ISSUE THREAD

**Issue by MadLord80** [react-bootstrap/react-bootstrap#3000]
I updated react-bootstrap from 2.8.0 to 2.13.0 and get warning for addStyle.
This code (i used typescript)
```
import * as React from 'react';
import ReactDOM from 'react-dom';
import * as RB from 'react-bootstrap';

RB.utils.bootstrapUtils.addStyle(RB.Panel, 'my');
class App extends React.Component {
  render() {
    return (
      <div className="App">
        <RB.Panel bsStyle="my">
          <RB.Panel.Heading>Test</RB.Panel.Heading>
        </RB.Panel>
      </div>
    );
  }
}
ReactDOM.render(<App />, document.getElementById('root'));
```
create the warning: "Warning: Failed prop type: Invalid prop `bsStyle` of value `my` supplied to `Panel`, expected one of ["success","warning","danger","info","default","primary"]."

But class in HTML added:
`<div class="panel panel-my"><div class="panel-heading">Test</div></div>`

**Comment by taion** [comment]
@jquense This looks like a glitch with uncontrollable. Should it be `Panel.ControlledComponent` here, or should we change the order of wrapping?

**Comment by MadLord80** [comment]
I think need to change the order of wrapping, because addStyle should work for all components with bsStyle property.

**Comment by rluiten** [comment]
I have had a hiccup like this myself.
I have an extra bootstrap panel style called `panel-teal`
I was running but still getting warning.

`bUtils.addStyle(Panel, 'teal')` 

When I added the ControlledComponent as follows

`bUtils.addStyle(Panel.ControlledComponent, 'teal');`

The warning went away.
Thanks for the information.

**Comment by taion** [comment]
`addStyle` is gone in v1
