### ISSUE TITLE
`DropdownButton` should blur on selection.

### ISSUE THREAD

**Issue by nelhage** [react-bootstrap/react-bootstrap#3002]
I maintain a [project](https://github.com/nelhage/crossme/) that uses `react-bootstrap` and also a global keydown listener. A user recently reported a bug that, after selecting an option from a dropdown (created via a `DropdownButton`), keyboard focus remained on the dropdown, and arrow key events were consumed by the menu, instead of the app's keyboard handler.

I [fixed the issue](https://github.com/nelhage/crossme/pull/19) by `blur`ing the dropdown in my `onSelect` handler, but this seems like something the dropdown should do itself on close.

**Comment by jquense** [comment]
This isn't a bug, focus should return to the button once a menu item is selected, that's the correct focus behavior as outlined by the w3c accessability guidelines. Dropping focus from the document is generally very bad behavior and poor UX for anyone not using a mouse/finger to use your site, I'd consider an alternative for your user's sake :)
