### ISSUE TITLE
OverlayTrigger 'show' prop does not actually hide the tooltip overlay if passed in as 'false'

### ISSUE THREAD

**Issue by wangytangy** [react-bootstrap/react-bootstrap#3004]
I'm attempting to wrap a OverlayTrigger with a tooltip around a button to display error messages. However I want to hide the tooltip entirely if there are no errors. If I pass in `show` as false to the OverlayTrigger just as the docs indicate, the tooltip still appears.

```
<OverlayTrigger
  placement='top'
  overlay={toolTip}
  show={false}
> // tooltip still appears
```

**Comment by taion** [comment]
see https://github.com/react-bootstrap/react-bootstrap/issues/155
