### ISSUE TITLE
CDN react-bootstrap/0.32.1/react-bootstrap.min.js is not minimized

### ISSUE THREAD

**Issue by s-nesbigall** [react-bootstrap/react-bootstrap#3005]
Hi,

it seems the CDN
https://cdnjs.cloudflare.com/ajax/libs/react-bootstrap/0.32.1/react-bootstrap.min.js

is not minimized.

**Comment by webpepper** [comment]
It's actually the same story when it's included as an npm dependency.

`node_modules/react-bootstrap/dist/react-bootstrap.min.js` is not minified.

**Comment by taion** [comment]
fixed in https://github.com/react-bootstrap/react-bootstrap/pull/3044
