### ISSUE TITLE
Generated docs not clear for OverlayTrigger?

### ISSUE THREAD

**Issue by boompig** [react-bootstrap/react-bootstrap#3006]
Are there any docs for OverlayTrigger? It's mentioned in both [Tooltip](https://react-bootstrap.github.io/components/tooltips/) and [Popover](https://react-bootstrap.github.io/components/popovers/) but it's unclear exactly what all the parameters do.

Here is the most comprehensive documentation of OverlayTrigger, found on the Tooltip page:

![screen shot 2018-02-21 at 10 19 41 am](https://user-images.githubusercontent.com/2791268/36497686-dab362c8-16f0-11e8-87d8-eb9846ec7643.png)

Some questions I have:

- what are the other possible values for `trigger`? Can you use 'click' as a trigger? If so, how does that work?
- can you pre-empt `delayHide`? Can you combine `delayHide` with `hide` to hide the overlay earlier in response to an event?
- what are the arguments passed to the functions for `onMouseOver`, `onClick`, etc.
- what is `target`?
- how does `show` work?

**Comment by jquense** [comment]
you can look at the code for the examples on the doc site for more usage examples, or the tests here: https://github.com/react-bootstrap/react-bootstrap/blob/master/test/OverlayTriggerSpec.js 

We are happy to take improvements to the docs if you are up for sending a PR thanks!

**Comment by jquense** [comment]
actually, gonna keep this open because the doc generation is clearly bugged here.
