### ISSUE TITLE
Passing target element to Overlay component

### ISSUE THREAD

**Issue by boompig** [react-bootstrap/react-bootstrap#3007]
In the docs for [Overlay](https://react-bootstrap.github.io/components/overlays/), it seems the standard way to pass a target is via DOM node. This requires doing something like

```
class Example extends React.Component {
  constructor(props) {
    super(props);

    this.getTarget = this.getTarget.bind(this);
  }

  getTarget() {
    return ReactDOM.findDOMNode(this.target);
  }

 render() {
    return (
      <div>
        <Button
          ref={button => {
            this.target = button;
          }}
        >
          Click me!
        </Button>

        <Overlay target={ this.getTarget } placement="left">
          <Tooltip id="overload-left">Tooltip overload!</Tooltip>
        </Overlay>
      </div>
    );
  }
}
```

(basically the code from the first example).

That seems to be the minimum amount of code to specify a target for an overlay. Would it be possible to instead do:

```
class Example extends React.Component {

render() {
const btn =  <Button>
          Click me!
        </Button>;
    return (
      <div>
       { btn }
        <Overlay target={ btn } placement="left">
          <Tooltip id="overload-left">Tooltip overload!</Tooltip>
        </Overlay>
      </div>
    );
  }
}
```

? As an aside, while the `target` prop seems key to getting the Overlay component to work, it is currently missing from the documented props here:

![screen shot 2018-02-21 at 11 17 56 am](https://user-images.githubusercontent.com/2791268/36500341-e9555c02-16f8-11e8-9de6-773dedbaebb5.png)

**Comment by taion** [comment]
No that doesn't work because `btn` in this case is just another React Element, and we can't infer what it's supposed to be. You could do:

```jsx
<div>
  {btn}
  {btn}
</div>
```

**Comment by boompig** [comment]
@taion I don't understand. You're saying to not include the Overlay?

**Comment by taion** [comment]
I’m saying your example proposed syntax literally doesn’t work. A React element does not uniquely identify a rendered React component.
