### ISSUE TITLE
how to change the navbar background color?

### ISSUE THREAD

**Issue by eliram9** [react-bootstrap/react-bootstrap#3011]
<img width="641" alt="screen shot 2018-02-28 at 12 15 21 am" src="https://user-images.githubusercontent.com/28363124/36771245-3b8fc376-1c1d-11e8-82d2-9309c6dc856b.png">

**Comment by taion** [comment]
Use `style` or `className`

**Comment by eliram9** [comment]
somehow calssName doesn't work, can you please give me an example how to write style?

**Comment by featTheB** [comment]
Did someone found a solution?
