### ISSUE TITLE
v4: Tabs and Nav components Proposal

### ISSUE THREAD

**Issue by jquense** [react-bootstrap/react-bootstrap#3012]
bootstrap v4 allows for simpler Nav markup, using just `<nav><nav-link></nav>` You can still use the `ul` but the extra `li` isn't needed except when it's relevant semantically.

This makes the focus logic in Nav a bit harder to handle because we need to map `eventKey` to index to increment/decrement as you use the arrow keys, and having two ways to define markup is hard to handle in that case (sometimes the NavLink is the direct child, sometimes it's wrapped in a NavItem)

My proposal, i think, is to move the focus logic out of Nav and into a set of Tab specific components, that's a bit hard tho because we have a 1000 tab components so:

- Remove the higher level `Tabs` component, it's convenient but not so much so i think it's required, plus how many tabs to you write in an application?
- Use the newly freed `Tabs` and `Tab` component names to wrap Nav and NavItem/Link (decide on one markup style which is fine we understand the semantics of the elements in this case.

**Comment by taion** [comment]
Do we necessarily care which component holds the `eventKey`? Can we require that the `eventKey` be defined on whatever is the direct descendant of `<Nav>`?

**Comment by jquense** [comment]
Ahh, yeah that's true!  I guess we can also handle state passing via context as well, since the active state needs to make it to the nav-link other the item

BTW can we come up with a better name for that prop? I want to just call it `value` but that's also sort of weird

**Comment by taion** [comment]
Hah, I mean, it is sort of an "event key", but I agree the name is awful. Maybe `itemKey`? Changing APIs too much is going to make migration harder for users though \:

**Comment by jquense** [comment]
itemKey is better, I don't mind these sort of name changes so much tho since they are really easy to grep and replace

**Comment by jquense** [comment]
Slight complication. the `disabled` state is nested as well, which we need to know to skip over the element when tabbing...

I think that the Nav component is sort of annoyingly complicated with all the tab focus logic...I still think we'll end up with simplified components splitting the explicit "I'm using this as an actual tab list" from any other case? Idk i guess that doesn't cover something like tabs as routes. but maybe that's actually good?

**Comment by jquense** [comment]
ok yeah I don't think it makes sense to have so many Tab containers. the "high level" one doesn't offer much value i don't think. Lets cuts some stufffff
