### ISSUE TITLE
Do not toggle when just selecting text

### ISSUE THREAD

**Issue by binarykitchen** [react-bootstrap/react-bootstrap#3013]
Within a Panel that has a toggler, sometimes I just want to select text and copy it. Without toggling.

For example

```
        <Panel.Heading>
          <Panel.Title toggle>Some useful text I might want to select and copy</Panel.Title>
        </Panel.Heading>
```

Pressing mouse and selecting that panel title text unfortunately toggles it.

Can event handling be a bit smarter here and distinguish whether I am after selecting text before toggling?

Using v0.32.1 here

**Comment by taion** [comment]
It's semantically correct to just handle `onClick` here. You can do what the upstream TWBS examples do and e.g. put the `onClick` handling on the text itself rather than making the entire heading a toggle.

**Comment by binarykitchen** [comment]
nope @taion, i tried with onClick on Panel.Title but that doesn't help nor solve the issue here
