### ISSUE TITLE
NavItem is not displaying on desktop browser. but works fine in mobile

### ISSUE THREAD

**Issue by DarkArtistry** [react-bootstrap/react-bootstrap#3014]
Hi I revised a website that I created with react bootstrap, and suddenly the navItem is no longer working.

![screen shot 2018-03-01 at 9 31 48 am](https://user-images.githubusercontent.com/25150257/36822515-674db1f0-1d33-11e8-9fa0-2e2698de3326.png)

https://www.kennethgzh.com/
https://degoldenspoon.com/

any advice ? I updated the packages. "react-bootstrap": "^0.31.0"

**Comment by taion** [comment]
Sounds like a CSS issue. Make sure you have an appropriate version of TWBS CSS installed (i.e. v3, not v4).

**Comment by DarkArtistry** [comment]
hi sorry where can i cehck for the css version ? when the website was created months ago it was working fine... =/

**Comment by DarkArtistry** [comment]
OH i see i get it , i just copied the updated minified css link thank you @taion
