### ISSUE TITLE
Documentation Bug

### ISSUE THREAD

**Issue by PuneetSingh-Batra** [react-bootstrap/react-bootstrap#3015]
Hello,
Seems like a documentation bug, Just want to report it. Close it, once confirmed. 
![screenshot_1](https://user-images.githubusercontent.com/9452175/36829919-4913965a-1d47-11e8-8ae1-cc58de19b64b.png)

**Comment by ChrisLFieldsII** [comment]
![screenshot 2](https://user-images.githubusercontent.com/30332608/36881692-12509ae8-1d95-11e8-9e37-28ca5870f38a.png)

I also noticed a typo in 2nd the Navbar example. There is no starting <Navbar.Toggle> which might throw off some copy-pasters lol.

**Comment by manishsaraan** [comment]
Thanks @PuneetSingh-Batra . Will look into it.

**Comment by astronomersiva** [comment]
Hi @manishsaraan , just wanted to know if you are still working on this. I would like to take this up if you are held up with something.

**Comment by manishsaraan** [comment]
@astronomersiva Thanks for asking. I am bit busy right now. You can take this issue :)

**Comment by astronomersiva** [comment]
@jquense , I am not able to reproduce this in both the master and v4-support branch. However, the documentation at https://react-bootstrap.github.io/components/buttons/ has this. Can you please check once?

**Comment by mxschmitt** [comment]
Seems not reproducible in the new version.
