### ISSUE TITLE
v4: Internal api trimming, style context

### ISSUE THREAD

**Issue by jquense** [react-bootstrap/react-bootstrap#3021]
So we have ended up accumulating a bunch of bootstrapUtils around the variaous props apis, I think we should simplify a bit and try and drop some of the stuff that was more important in the past and take advantage of the newer language features like string interpolation :P 

I am thinking something like this leaveraging the new Context api, Here is the `Button` component without bootstrap utils.

```js
class Button extends React.Component {
  render() {
    return (
      <StyleContext.Consumer variantType="Button" props={this.props}>
        {({ bsStyle, bsClass, bsSize, props }) => {
          const { active, block, className, componentClass, ...rest } = props;
          const classes = classNames(
            className,
            bsClass,
            `${bsClass}-${bsSize}`,
            `${bsClass}-${bsStyle}`,
            block && `${bsClass}-block`,
            active && 'active'
          );

          if (props.href) {
            return (
              <SafeAnchor
                {...rest}
                componentClass={componentClass}
                className={classNames(classes, rest.disabled && 'disabled')}
              />
            );
          }

          const Component = componentClass || 'button';
          return <Component {...rest} type={rest.type} className={classes} />;
        }}
      </StyleContext.Consumer>
    );
  }
}
```

The `StyleContext.Consumer` takes in the props and passes through the `props.bsClass` or the one on context for `'Button'`, this lets you set class prefixes per root or component but with very little code. We could also make it a HOC, thoughts?

**Comment by taion** [comment]
You added the prefixing helpers :p I'd be fine with dropping them.

Do you think the single `variant` array is too generic? What about type checking/&c. for the variants? Do them in `render`?

**Comment by jquense** [comment]
O yeah the helpers are all my fault :P I'm annoyed at past me. Idk about the single variant field. I'm starting to think there isn't a ton of value in have this super unified approach, I don't know that it offers much more over individual, semantically relevant names. Plus most libraries seem to do the 'variant', 'color', 'size' etc. It's also an easier migration path. I would stop prefixing the props tho, that seems like a fairly legacy api thing we never wanted to break

**Comment by jquense** [comment]
how do you feel about the above for the internal style management and variant prefix customization? maybe worth making it a decorator?

**Comment by taion** [comment]
so as discussed, i think we should either use a HoC, or have a separate helper for creating context-styling-aware components, to minimize the required code contortions

**Comment by jquense** [comment]
Updating coming!
