### ISSUE TITLE
v4: Alerts

### ISSUE THREAD

**Issue by jquense** [react-bootstrap/react-bootstrap#3023]
**Read first!** [Contributing](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md) | [Structuring a PR](https://github.com/react-bootstrap/react-bootstrap/blob/v4-support/V4-Contributing.md ) | [Bootstrap docs](https://getbootstrap.com/docs/4.0/components/alerts/)

- [ ] new variants
- [ ] Heading component
- [ ] Link component

**Comment by abdullahtariq1171** [comment]
I would love to take this.

**Comment by jquense** [comment]
all yours 👍
