### ISSUE TITLE
v4: Cards

### ISSUE THREAD

**Issue by jquense** [react-bootstrap/react-bootstrap#3025]
**Read first!** [Contributing](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md) | [Structuring a PR](https://github.com/react-bootstrap/react-bootstrap/blob/v4-support/V4-Contributing.md ) | [Bootstrap docs](https://getbootstrap.com/docs/4.0/components/cards/)

**Comment by manishsaraan** [comment]
I would like to take this.

**Comment by jquense** [comment]
awesome thanks!

**Comment by kendaganio** [comment]
Hi @manishsaraan just checking in if you're still interested in this issue. I can pick this up if you're a bit busy. Thanks!

**Comment by kendaganio** [comment]
Hi @manishsaraan following up if you're still interested! 😺

**Comment by jquense** [comment]
@kendaganio I think it's safe for you to work on this if you'r interested.

**Comment by kendaganio** [comment]
Thanks @jquense, i'll take this one.

**Comment by manishsaraan** [comment]
Sorry for the late reply guys. I am little busy these days so @kendaganio you can work on it. :)

**Comment by jquense** [comment]
No problem.feel free to come one back if you get some time, plenty of other stuff to do

**Comment by manishsaraan** [comment]
Sure will do.
