### ISSUE TITLE
Forms

### ISSUE THREAD

**Issue by jquense** [react-bootstrap/react-bootstrap#3026]
**Read first!** [Contributing](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md) | [Structuring a PR](https://github.com/react-bootstrap/react-bootstrap/blob/v4-support/V4-Contributing.md ) | [Bootstrap docs](https://getbootstrap.com/docs/4.0/components/forms/)

sort of in progress

**Comment by astronomersiva** [comment]
@jquense is this issue taken or can I take a shot at it?

**Comment by jquense** [comment]
I think it's mostly done, all that's left is the custom form element styles https://getbootstrap.com/docs/4.1/components/forms/#custom-forms

**Comment by astronomersiva** [comment]
I am taking a shot at this 👍
