### ISSUE TITLE
v4: List Group

### ISSUE THREAD

**Issue by jquense** [react-bootstrap/react-bootstrap#3027]
**Read first!** [Contributing](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md) | [Structuring a PR](https://github.com/react-bootstrap/react-bootstrap/blob/v4-support/V4-Contributing.md ) | [Bootstrap docs](https://getbootstrap.com/docs/4.0/components/list-group/)

- [ ] New sub component API

**Comment by alacroix** [comment]
Hi @jquense ! I would like to take this one :)

**Comment by jquense** [comment]
👍 awesome all yours.

**Comment by jquense** [comment]
This one will involve some API changes, because the API we have now is not great, we want something more along the lines of the Panel api

**Comment by jquense** [comment]
hey @alacroix just a friendly ping to see if you're still up for this. No problem either way, i want to know if someone else could work on it or if you're still planning on it 👍

**Comment by alacroix** [comment]
Hey @jquense, sorry for the delay. I just changed job so I won't have free time to work on this, sorry 😕 

@kendaganio it's all yours.

**Comment by kendaganio** [comment]
@jquense taking this on next!
