### ISSUE TITLE
v4: Dropdown

### ISSUE THREAD

**Issue by jquense** [react-bootstrap/react-bootstrap#3028]
**Read first!** [Contributing](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md) | [Structuring a PR](https://github.com/react-bootstrap/react-bootstrap/blob/v4-support/V4-Contributing.md ) | [Bootstrap docs](https://getbootstrap.com/docs/4.0/components/dropdowns/)

- [x] update classes
- [ ] POPPER support in react-overlays

**Comment by grady-lad** [comment]
Hey @jquense this one still available to work on ?

**Comment by jquense** [comment]
hey @grady-lad I've actually already started this one since it involves a lot of back and forth between react-overlays. I should have added the taken issue

**Comment by taion** [comment]
this was done
