### ISSUE TITLE
v4: Layout component?

### ISSUE THREAD

**Issue by jquense** [react-bootstrap/react-bootstrap#3029]
**Read first!** [Contributing](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md) | [Structuring a PR](https://github.com/react-bootstrap/react-bootstrap/blob/v4-support/V4-Contributing.md ) | [Bootstrap docs](https://getbootstrap.com/docs/4.0/layout/utilities-for-layout/)

v4 contains a ton more helper and utility classes for layout, flexbox, margins, padding, etc. It might be a good idea to try and wrap some of that up into a single abstract `Layout` or `Flex` component as a library supported way to use some of these new utilities. It's unclear to me whether using it internally would be a good idea but I think it'd be a useful value-add component

**Comment by highskillzz** [comment]
Could you please explain more what do you mean?

**Comment by chenesan** [comment]
Hi @jquense I'd like to take this one 😄

**Comment by jquense** [comment]
@chenesan go for it! Setting expectations a bit first though so we are on the same page. I'm not sure what this component should/would look like, so there will probably be a lot of back and forth on the api and structure. It's not entirely clear yet whether adding it is even a good call, but we'd love to see some exploration!

**Comment by chenesan** [comment]
@jquense Thanks! I'll read through the utility api docs and try to write some possible usage examples in the next few days.

**Comment by chenesan** [comment]
Hi @jquense 

I think we can have a `wrapLayoutUtil` hoc to handle all the utility className for internal use:

```javascript

// hoc.js

const utilityClassNameMap = {
  dFlex: "d-flex",
  // and other layout utility...
}

const wrapLayoutUtil = (Component) => {
  return (props) => {
    const utilityClassNames = Object.keys(props)
    .map(propName => utilityClassNameMap[propName])
    .filter(className => !!className)
    return <Component
      {...this.props}
      className={classnames(utilityClassNames, this.props.className)}>
    </Component>
  }
}

export default wrapLayoutUtil


// Button.js (or any react-bootstrap component)

import wrapLayoutUtil from "./hoc"

class Button extends React.Component {
  // Implementation of Button component.
  // Must has a `className` props to receive passed custom class name
}

export default wrapLayoutUtil(Button)

// App.js (client code)

// will output <button className="btn d-flex"></button>
const App = () => <Button dFlex></Button>

```

With this way, It's easy to map all the utility class onto all library components. Also it's less error prone than using className directly.

The con is that all the components will be wrapped with the util hoc class, which makes it a little verbose in the react developer tool.

As for use case in client code, Besides the above hoc, maybe we can have a component like:

```

// App.js (client code)

// render <div className="d-flex">Hello world</div>
const App = () => <LayoutUtil componentClass="div" dFlex>Hello world</LayoutUtil>

```

**Comment by jquense** [comment]
Hey, thanks for writing this up. I think the HoC approach is good generally, but I'm not sure it's a good fit here. We aren't sure  yet if we _want_ to allow the built-in components to provide layout props like that. There are a bunch of potential issues that make that a bit challenging. The big one is that it adds a huge amount of prop surface area to many components, which may conflict with existing ones or ones the user wants to add personally. The other concern is it gives the impression that all the Layout props are supported on the component, which may or may not be the case. (e.g. i'm not sure changing the `display` on a Button is actually safe to do with the default styles).

What I was thinking to start with is something like a `<Layout >` component you could use more generally (and maybe we could use internally as well). A normal component gives us a bit more flexibility in how we use or process the props and we can eventually write a HOC on top of it if it makes sense. What do you think?

**Comment by chenesan** [comment]
Hmm, It's indeed a problem that HOC override lots of props in this way. Maybe we can try to wrap all the layout utitlity bool props to one single object prop like:

```javascript
// hoc.js

const utilityClassNameMap = {
  // still the same..
}

const wrapLayoutUtil = (Component) => {
  return (props) => {
    // Use a single `layoutUtil` prop to pass layout utility user wants
    const {layoutUtil} = props
    // The following is the same...
    const utilityClassNames = Object.keys(layoutUtil)
    .map(propName => utilityClassNameMap[propName])
    .filter(className => !!className)
    return <Component
      {...this.props}
      className={classnames(utilityClassNames, this.props.className)}>
    </Component>
  }
}

export default wrapLayoutUtil

```

So we can write `<Button layoutUtil={{ dFlex: true }}></Button>`. It becomes a little longer, though.

And I think it's fine to make all library component support the Layout hoc. Yes it's strange to have a `display: flex` on a button, But I think user should know what will happen when they decide to use the layout utility. 

I guess it's also OK to simply has a normal `<Layout />` component like

```javascript

class Layout extends React.Component {
  render() {
    const Component = this.props.componentClass || "div"
    // as same as the same way in hoc
    const className = this.buildUtilClassNames() 
    return <Component className={className}>{this.props.children}</Component>
  }
}
// So <Layout dFlex><Button /></Layout> can render <div class="d-flex"><button></button></div>
```

Though I wonder what the internal use case will be in this way. And, what if the user wants to directly add the utility class on the library component, ex. `<div class="col-sm-2 mb-2>`? So I may prefer hoc a little.

**Comment by jquense** [comment]
The big reason we want a plan Layout component, is that it's useful generally. Think of it as something that can replace general usage  of `'div'` in an app using RB. That is a lot more annoying if I have to wrap all my components in an HOC to get that. The other thing a HoC provides is the ability to transform or introspect the props coming in below the the HOC, we don't really need that here since all props are heading to `className`. I'd start with writing the general component first and then we can talk about integrating into the rest of the library, but there is a lot of value in the component even if we don't get that far

**Comment by taion** [comment]
Function children? :D

**Comment by chenesan** [comment]
Oh ok @jquense  I got what you want for the `Layout` component now 😁

So should I start to work on the normal `Layout` component or you have worked on it? I think we can simply start from wrapping all utility class into boolean prop?

**Comment by jquense** [comment]
> or you have worked on it?

I have not so go for it 👍 

> ...wrapping all utility class into boolean prop

We can start there, but i'd like this to be more intentional and nicer than a simple mapping to the classes, but instead build a pleasant react-ish api over the classes. I'm totally sure waht the means practically, though something like `mr="1|2|3|auto"` is preferable to `mr3 mrAuto` etc

**Comment by chenesan** [comment]
> I have not so go for it 👍

I may send a PR for this in this week 😄 

>  but i'd like this to be more intentional and nicer than a simple mapping to the classes, but instead build a pleasant react-ish api over the classes.

OK I'll try to group those class names into some meaningful props. I'm not sure what they will be and will be back if we need some discussion. Thanks for your guidance!

**Comment by chenesan** [comment]
Have sent a [PR](https://github.com/react-bootstrap/react-bootstrap/pull/3089).

**Comment by muuvmuuv** [comment]
Looking forward for this! I'm really missing `d-none d-lg-block` 😁

**Comment by jquense** [comment]
@muuvmuuv no need to miss them, you can add `className='d-none d-lg-block'` to all the components

**Comment by muuvmuuv** [comment]
@jquense yep noticed that after I wrote this :D sorry, I'm new to react

**Comment by QuantumInformation** [comment]
Where can I find documentation for componentclass. I've inherited a legacy codebase.

**Comment by bpas247** [comment]
I'm starting to think this might not be a good direction to go with our API... All previous attempts at tackling this have not turned out well.

What do y'all think? IMO I don't think we should pursue supporting this as a part of the main API.

**Comment by taion** [comment]
so... we've taken to just using the TWBS helper classes when we need those, and it's largely worked fine for us. not sure there's much benefit to adding a react component here

**Comment by kosmiq** [comment]
Should this issue be closed? So it can be removed from the list for https://github.com/react-bootstrap/react-bootstrap/projects/1 :)

**Comment by taion** [comment]
Yup, I think so, thanks!
