### ISSUE TITLE
v4: Tabs

### ISSUE THREAD

**Issue by jquense** [react-bootstrap/react-bootstrap#3030]
**Read first!** [Contributing](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md) | [Structuring a PR](https://github.com/react-bootstrap/react-bootstrap/blob/v4-support/V4-Contributing.md ) | [Bootstrap docs](https://getbootstrap.com/docs/4.0/components/navs/#javascript-behavior)

The below is still TBD, but my current thinking:

- [ ] Get rid of the current high level `Tabs` and `Tab` components (leave TabContainer et all)
- [ ] Repurpose names to move tab specific focus/navigation logic from `Nav` and `NavItem` to a `Tabs` and `Tab` component

**Comment by taion** [comment]
I feel like we see enough people complain about `<Tab>` and `<Tabs>` that it might be worth keeping. What about a `<TabNav>` or something?

**Comment by jquense** [comment]
I think naming will be subpar here for most any other name. Idk I'm sure some ppl will complain but this component is weird in the current context of the rest of the library, full of many components and sub components. I'm fine keeping if it's not getting in the way of better apis elsewhere, I'm still not sure how to handle the nav case with the nested components
