### ISSUE TITLE
v4: Tooltips & Popovers

### ISSUE THREAD

**Issue by jquense** [react-bootstrap/react-bootstrap#3031]
**Read first!** [Contributing](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md) | [Structuring a PR](https://github.com/react-bootstrap/react-bootstrap/blob/v4-support/V4-Contributing.md ) | [Bootstrap docs](https://getbootstrap.com/docs/4.0/components/tooltips/)

- [ ] clean up existing components
- [ ] get POPPER support upstream in react-overlays (see also #3028 )

**Comment by imsergiobernal** [comment]
It's done? Should you close this issue?
