### ISSUE TITLE
v4: Modals

### ISSUE THREAD

**Issue by jquense** [react-bootstrap/react-bootstrap#3032]
**Read first!** [Contributing](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md) | [Structuring a PR](https://github.com/react-bootstrap/react-bootstrap/blob/v4-support/V4-Contributing.md ) | [Bootstrap docs](https://getbootstrap.com/docs/4.0/components/modal/)

**Comment by jeffreyroshan** [comment]
I am interested to take this up, if still available.

**Comment by jquense** [comment]
@jeffreyroshan lets stick with one at the time for now to give folks a chacne to jump in! Would you prefer this one or the #3036 ?

**Comment by jeffreyroshan** [comment]
@jquense I'll take this

**Comment by jquense** [comment]
done!

**Comment by jeffreyroshan** [comment]
I should start from v4-support branch, right?

**Comment by jquense** [comment]
yes :) !

**Comment by jeffreyroshan** [comment]
I need some help setting up local module for development.

I cloned my repo locally, pointed it to v4-support branch and installed the module locally on my react project as follows:

`sudo npm install ./react-bootstrap --save
`

I can see it in the package.json

`"react-bootstrap": "file:react-bootstrap",`

However, when I run my code by importing the module using `import { Alert, Button } from 'react-bootstrap';` I get the following error.

`Module not found: Can't resolve 'react-bootstrap' in '/.../rb-app-v4/src'
`

**Comment by jquense** [comment]
I'm not sure there, I would use the docs as a playground for testing personally. We also recommend using `yarn` instead of `npm`

so:
- `yarn install` in react-bootstrap/
- `yarn install` in react-bootstrap/www
- `yarn run develop` in react-bootstrap/www

The docs will always use whatever is in your local `src/` directory

**Comment by jeffreyroshan** [comment]
@jquense Thanks that works.

**Comment by jeffreyroshan** [comment]
@jquense I started working on it. Got some errors fixed and got the modal working on v4.

![basic-modal](https://user-images.githubusercontent.com/2136271/37211337-95f19ed2-23d1-11e8-8dbd-9a68fe1d31cd.png)

I am now trying to add **vertically centered** modal. I need to add the class "modal-dialog-centered" to the ModalDialog component. What's the recommended way to do this?

![vertically-centered-modal](https://user-images.githubusercontent.com/2136271/37211333-91886cfe-23d1-11e8-8c90-9883f85ba42c.png)

My latest commit is here:
https://github.com/jeffreyroshan/react-bootstrap/commit/365cca546e2e122700260f1b4656ad530ccf3b67

Thanks

**Comment by jquense** [comment]
I'd say make the prop `centered` and pass it through to the Modaldialog component where we add the class

**Comment by jeffreyroshan** [comment]
@jquense I've added the `centered` prop and updated the doc page with an example.

![centered-modal](https://user-images.githubusercontent.com/2136271/37245559-fa499828-24bf-11e8-91ba-5c1728b83367.png)

Now, to update the **tests** should I append it to `test/ModalSpec.js` or create a new test file?

Latest commit: [https://github.com/jeffreyroshan/react-bootstrap/commit/d140d7bf7aea7025a1e05aa6ccb061658b301f07](url)

**Comment by jquense** [comment]
> Now, to update the tests should I append it to test/ModalSpec.js or create a new test file?

You can keep adding to ModalSpec.js 👍

**Comment by jquense** [comment]
@jeffreyroshan Also feel free to open a PR while your working on it if you want feedback

**Comment by jeffreyroshan** [comment]
@jquense sure, thanks.

**Comment by dragoroff** [comment]
I'm using the code that you provided [here](https://react-bootstrap.github.io/components/modal/). I get the button, but when I click nothing is changing only window is blocking. I'm working in React. What information should I provide you else?

**Comment by RefX32** [comment]
Hi, what is the progress on this? It seems like @jeffreyroshan at least got a working commit to display Modal in  V4. Has these changes been submitted to main branch? @jquense

**Comment by RefX32** [comment]
Anyone that's having trouble, I got a working modal using V4 of bootstrap. It's pretty hacky and I don't recommened it, but at least it pops up. I've added this in my .css

```
.modal-backdrop.fade {
  opacity: .6;
}

.modal {
  opacity: 1 !important;
}

.modal.fade .modal-dialog {
  -webkit-transform: translate(0,-10%);
  transform: translate(0,10%);
}
````

**Comment by jeffreyroshan** [comment]
@jquense I am held up with some work at office. If someone wants to take over, please do. All modals work now, some tests and some minor changes are pending.

**Comment by jquense** [comment]
No worries, I've got those changes up in a follow up pr
