### ISSUE TITLE
v4: Progress bars

### ISSUE THREAD

**Issue by jquense** [react-bootstrap/react-bootstrap#3033]
**Read first!** [Contributing](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md) | [Structuring a PR](https://github.com/react-bootstrap/react-bootstrap/blob/v4-support/V4-Contributing.md ) | [Bootstrap docs](https://getbootstrap.com/docs/4.0/components/progress/)

**Comment by grady-lad** [comment]
@jquense I can take a look at this one

**Comment by jquense** [comment]
great! thanks :)
