### ISSUE TITLE
v4: Jumbotron

### ISSUE THREAD

**Issue by jquense** [react-bootstrap/react-bootstrap#3036]
**Read first!** [Contributing](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md) | [Structuring a PR](https://github.com/react-bootstrap/react-bootstrap/blob/v4-support/V4-Contributing.md ) | [Bootstrap docs](https://getbootstrap.com/docs/4.0/components/jumbotron/)

**Comment by jeffreyroshan** [comment]
I am interested to take this up, if still available.

**Comment by stephanieinez** [comment]
@jquense I can take a look at this one

**Comment by jquense** [comment]
all yours! thanks :)
