### ISSUE TITLE
v4: Breadcrumb

### ISSUE THREAD

**Issue by jquense** [react-bootstrap/react-bootstrap#3039]
**Read first!** [Contributing](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md) | [Structuring a PR](https://github.com/react-bootstrap/react-bootstrap/blob/v4-support/V4-Contributing.md ) | [Bootstrap docs](https://getbootstrap.com/docs/4.0/components/breadcrumb/)

- [ ] Update markup to use a `nav` element
- [ ] Auto add `aria-current`? I'm not sure about this one

**Comment by kendaganio** [comment]
I can take this @jquense if it's still available

**Comment by jeffreyroshan** [comment]
I am interested to take this up, if still available.

**Comment by jquense** [comment]
@AnderssonChristian  and @jeffreyroshan lets let @kendaganio take since @AnderssonChristian already has Badge and @kendaganio was first on the issue here :)

@kendaganio All yours

**Comment by kendaganio** [comment]
thanks @jquense!
