### ISSUE TITLE
v4: Badge

### ISSUE THREAD

**Issue by jquense** [react-bootstrap/react-bootstrap#3040]
**Read first!** [Contributing](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md) | [Structuring a PR](https://github.com/react-bootstrap/react-bootstrap/blob/v4-support/V4-Contributing.md ) | [Bootstrap docs](https://getbootstrap.com/docs/4.0/components/badge/)

Badge in v4 is the `Badge` and `Label` combined. Label should be renamed to Badge and the other Badge removed.

**Comment by AnderssonChristian** [comment]
@jquense I can take this one, as well as #3039 if they are not taken

**Comment by jquense** [comment]
go for it! the v4-support branch is a bit broken with tests right now (working on it!)

**Comment by jquense** [comment]
oops it likes this might mostly be done 😳 already I may have messed with it earlier in the process.

**Comment by jquense** [comment]
it does look like tests and probably documentation still need to be updated if you are up for it!

**Comment by AnderssonChristian** [comment]
@jquense I can do documentation, sure. I'd like some code too though, what about #3047 ?

btw, do we want an alias component for Label -> Badge (that maybe logs a deprecation warning)?

**Comment by jquense** [comment]
Definitely can have #3047 just mention tho in that issue so folks can see.

No need for depreciation warnings, this will already be a hard break for anyone upgrading so there isn't a ton of value in aliasing the components
