### ISSUE TITLE
Documentation design!

### ISSUE THREAD

**Issue by jquense** [react-bootstrap/react-bootstrap#3041]
Our documentation could use a facelift! We've recently updated it to a Gatsby js site, and could definitely benefit from some design work.

- [ ] Clean up all the forked bootstrap doc css, removing unused stuff
- [ ] Update from LESS to Sass

**Comment by maaz93** [comment]
I'd like to take this up. I'm experimenting with Gatsby, so this would be a fun experience I hope. Could you elaborate a bit on the first task?

**Comment by jquense** [comment]
Awesome! thanks for helping out.

>  Could you elaborate a bit on the first task

Yes, a lot of the styling you'll see in `www/src/css/` is a complete copy/paste of the v3 bootstrap docs styles and then heavily modified. We don't use a lot of it and the current docs site structure isn't even similar to the v3 docs. I'd love if we could essentially "start over" with the style files and build something up with a bit more modern of a style architecture.

Does that help? In terms of design I think we are ll pretty open to whatever, though maybe not a complete copy of the bootstrap docs :P

**Comment by maaz93** [comment]
When you say _modern style architecture_, you mean the way the styles are organized or written?

Also honestly, when I first read the issue description, I got the impression that it's more of a clean-up (as in remove unused things, format the CSS to a way it is more readable etc.) task than a re-design the website task. Sadly, I won't have the time to do a new website from scratch 😞 But, I can definitely help with testing the new site, whenever somebody starts working on it. Hope that's ok!

**Comment by jquense** [comment]
> as in remove unused things, format the CSS to a way it is more readable etc.

That would be great! We probably do need a bunch of redesign eventually, but a great first step would be to clean up the css that's there and update the existing styles to not be broken with the new bootstrap v4 css. If you're up for that please go for it 👍

**Comment by maaz93** [comment]
Awesome! I'll start it off and come back if I have any questions.

**Comment by maaz93** [comment]
@jquense I've started looking at this. Is the docs site broken in the v4-support branch? I get this error after doing `yarn run bootstrap` and then `yarn start` from the project root.

> Uncaught (in promise) ReferenceError: React is not defined
    at Basic.js:10
    at Array.map (<anonymous>)
    at Object.C:\Users\i317212\oss\react-bootstrap\www\node_modules\babel-loader\lib\index.js??ref--0-0!C:\Users\i317212\oss\react-bootstrap\www\src\examples\Alert\Basic.js (Basic.js:1)
    at __webpack_require__ (bootstrap 29aec30bfecc1bb7691d:678)
    at fn (bootstrap 29aec30bfecc1bb7691d:88)
    at Object.C:\Users\i317212\oss\react-bootstrap\www\node_modules\babel-loader\lib\index.js??ref--0-0!C:\Users\i317212\oss\react-bootstrap\www\src\pages\components\alerts.js (alerts.js:8)
    at __webpack_require__ (bootstrap 29aec30bfecc1bb7691d:678)
    at fn (bootstrap 29aec30bfecc1bb7691d:88)
    at Object.C:\Users\i317212\oss\react-bootstrap\www\node_modules\babel-loader\lib\index.js??ref--0-0!C:\Users\i317212\oss\react-bootstrap\www\.cache\sync-requires.js (sync-requires.js:15)
    at __webpack_require__ (bootstrap 29aec30bfecc1bb7691d:678)

I can't figure out what I'm doing wrong here.

**Comment by jquense** [comment]
It shouldn't be maybe try removing node_modules in the root and in www and reinstalling

**Comment by jquense** [comment]
its totally a windows path, issue. Sorry fix incoming

**Comment by maaz93** [comment]
I can confirm it's working after your fix. Thank you so much! 🎉 It really means a lot when OSS maintainers support cross OS dev environments.

**Comment by maaz93** [comment]
I was wondering how I could get a quick start on clean up and figure out what is really unused. I stumbled upon the [Chrome coverage](https://developers.google.com/web/updates/2017/04/devtools-release-notes#coverage) feature. The cool part about this is it tracks coverage even when you're interacting with the site. I basically ran this coverage and went through the entire RB site thrice (for different CSS breakpoints).

Just a quick demo of what the coverage tool looks like

![coverage](https://user-images.githubusercontent.com/6594255/38451698-6c263eb8-3a52-11e8-8e01-70904b041f47.gif)

Will start the investigation on the uncovered lines and maybe have an initial PR soon.

**Comment by maaz93** [comment]
@jquense I had a few queries

1. What are the differences between `docs.css` and `styles.less`? Is it like `docs.css` is a Bootstrap docs copy with some modifications and `styles.less` is meant to override stuff in `docs.css`?
1. And `examples.less` is another file which has a few styles related to the examples only?
