### ISSUE TITLE
Documentation Search

### ISSUE THREAD

**Issue by jquense** [react-bootstrap/react-bootstrap#3042]
We need search in the documentation! The reactjs site has a nice one maybe we can borrow it ;)

**Comment by BoyWithSilverWings** [comment]
react docs is using algolia for search

**Comment by BoyWithSilverWings** [comment]
https://community.algolia.com/docsearch/ 
This is the URL for docsearch from algolia that React and Bootstrap uses. The owner of the site needs to fill in the details and receive the key.

**Comment by iamnapo** [comment]
@jquense If you request a key from algolia, I can work on this

**Comment by jquense** [comment]
you bet 👍

**Comment by jquense** [comment]
this sort of done. We do need to eventually update it for the v4 docs once those are live

**Comment by iamnapo** [comment]
what needs to be done to update it? You mean add it to (maybe changed) `NavMain` accordingly?
