### ISSUE TITLE
v4: Figures

### ISSUE THREAD

**Issue by jquense** [react-bootstrap/react-bootstrap#3048]
**Read first!** [Contributing](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md) | [Structuring a PR](https://github.com/react-bootstrap/react-bootstrap/blob/v4-support/V4-Contributing.md ) | [Bootstrap docs](https://getbootstrap.com/docs/4.0/content/figures/)

I think the only thing needed here is the `figure-img` bits? Maybe it's worth rolling into Images

**Comment by iamnapo** [comment]
I'd like to work on this

**Comment by jquense** [comment]
go for it!

**Comment by iamnapo** [comment]
You can close this now

**Comment by iamnapo** [comment]
You can close this now :smiley:
