### ISSUE TITLE
v4: Images

### ISSUE THREAD

**Issue by jquense** [react-bootstrap/react-bootstrap#3049]
**Read first!** [Contributing](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md) | [Structuring a PR](https://github.com/react-bootstrap/react-bootstrap/blob/v4-support/V4-Contributing.md ) | [Bootstrap docs](https://getbootstrap.com/docs/4.0/content/images/)

**Comment by iamnapo** [comment]
I guess I'll take this as well as #3048

**Comment by jquense** [comment]
good call they seem related 👍

**Comment by iamnapo** [comment]
You can close this now

**Comment by iamnapo** [comment]
You can close this now :smiley:
