### ISSUE TITLE
v4: Media Object

### ISSUE THREAD

**Issue by jquense** [react-bootstrap/react-bootstrap#3051]
**Read first!** [Contributing](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md) | [Structuring a PR](https://github.com/react-bootstrap/react-bootstrap/blob/v4-support/V4-Contributing.md ) | [Bootstrap docs](https://getbootstrap.com/docs/4.0/layout/media-object/)

I think this one is mostly deleting things, like MediaList and updating the markup

**Comment by sliw** [comment]
@jquense 

I have attempted to this issue - https://github.com/react-bootstrap/react-bootstrap/pull/3057

But I am not sure about the markup bit you mentioned.

Feel free to give me feedback.
