### ISSUE TITLE
Storybook issues

### ISSUE THREAD

**Issue by AnderssonChristian** [react-bootstrap/react-bootstrap#3052]
I'm trying to get storybook to work on my fork but I am getting:

`ERROR in ./.storybook/config.js. Module build failed: Error: Plugin/Preset files are not allowed to export objects, only functions.`

I have tried installing dependencies a few times but it doesn't help. What could be the issue?

**Comment by jquense** [comment]
oops looks like i may have broken the storybook recently i've been use the docs directly (`npm run develop` in the `www` directory) to do component visual testing.

**Comment by bpas247** [comment]
Closing this issue due to #3625
