### ISSUE TITLE
v4: Remove Glyphicons components

### ISSUE THREAD

**Issue by jquense** [react-bootstrap/react-bootstrap#3054]
**Read first!** [Contributing](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md) | [Structuring a PR](https://github.com/react-bootstrap/react-bootstrap/blob/v4-support/V4-Contributing.md )

These are v3 only!

**Comment by tgfbikes** [comment]
@jquense, I can give this a shot if you'd like.

**Comment by jquense** [comment]
go for it!

**Comment by jquense** [comment]
@tgfbikes you still working on this, or should we move it back to the pile, no rush, but wanted to check in

**Comment by tgfbikes** [comment]
@jquense I am still planning on getting it done.  Sorry for the delay.  Life and stuff.  Would I be able to PM you some questions...actually just clarifications?  Thank you.

**Comment by jquense** [comment]
No worries, ya feel free to reach out as well with any questions

**Comment by jquense** [comment]
Nope, the glyphicon component is removed in v1 because bootstrap doesn't include any icons anymore. We recommend using react-icons or fontawesome and the like directly
