### ISSUE TITLE
Popover not closing when holding cmd or Shift

### ISSUE THREAD

**Issue by fhavrlent** [react-bootstrap/react-bootstrap#3056]
I am not sure if this is a bug, since boostrap example works, or this is a correct and intended, but when using "Click w/rootClose", the popover will not close. Or am I just missing something? 😶

**Comment by taion** [comment]
intentional per https://github.com/react-bootstrap/react-overlays/issues/68, https://github.com/react-bootstrap/react-overlays/issues/69
