### ISSUE TITLE
Allow custom bsStyle

### ISSUE THREAD

**Issue by janmarek** [react-bootstrap/react-bootstrap#306]
Now you can't add classes like btn-custom or alert-custom to your stylesheet and use them with react-bootstrap components. bsStyle property should be validated less strictly.

**Comment by ivan-kleshnin** [comment]
@trentgrover-wf you can't rely on bootstrap draft semantics and call it "rules". 
It were built for user extension. Bootstrap `info`, `warning`, etc. were built more for demo purpose than for real use. Thats BS developers opinion, not mine. End users may and should create their own sets of statuses etc. The current way of handling this is very uncomfortable, I 100% agree here with @janmarek. You don't need to validate class names against predefined sets at all. That simple.

**Comment by mtscout6** [comment]
I can see the value in doing some kind of validation against a known set of styles you support, yet I can also see the value in allowing for custom styles. I think you can add your own custom styles and still keep the existing validation by doing:

```
var constants = require('react-boostrap/constants');
constants.STYLES.custom = 'custom';
```

The name constants is deceiving here since nothing has been done to ensure that those values have been modified. If you did this as one of your initial tasks prior to rendering anything, then you'd have the custom options you want with the validation to support it.

**Comment by mathieumg** [comment]
Until the day these are enforced to be constant, or the filename changes.

**Comment by mtscout6** [comment]
We can cross that bridge when that day comes :smile:. I'm not planning to change that anytime soon.

**Comment by ivan-kleshnin** [comment]
@mtscout6 thank your for this trick, it may help.

**Comment by mtscout6** [comment]
No problem!

**Comment by mtscout6** [comment]
@janmarek Does the above suggestion help? Do we need to keep this issue open for any reason?

**Comment by janmarek** [comment]
OK, I'm closing it.

**Comment by nemothekid** [comment]
If you set `bsStyle=""`, you get a ton of console errors where
```
Warning: Invalid prop `bsStyle` of value `` supplied to `Button`, expected one of ["default","primary","success","info","warning","danger","link","inline","tabs","pills"]. Check the render method of `DropdownButton`.
```

Unfortunately, if you aren't using CommonJS/AMD, then `constants` isn't exposed either. If `bsStyle=""` isn't a valid property `bsStyle={false}` or something like that should be enabled to prevent this validation. For us, we use a modified version of the bootstrap css (which I think is pretty common) and having designers provide a JS file listing out all the `btn` classes (or having developers hunt down all the `btn` classes in css) they used in a design seems like an unnecessary build step.

**Comment by ivan-kleshnin** [comment]
@nemothekid, agree. react-bootstrap devs just created a problem out of thin air. I don't care about class name validation at all (the cost of error is very low). But I do care about my development time which is wasted (not a lot, but...) on thise hackaround. I stay with my prev. opionion – "thou should not validate class names".

**Comment by mtscout6** [comment]
@nemothekid I'd take a pull request to fix the problem with the constants not being available when using requirejs.

**Comment by trevorr** [comment]
@mtscout6's workaround for webpack (missing `t` typo fixed and `lib` added):

    var constants = require('react-bootstrap/lib/constants');
    constants.STYLES.custom = 'custom';

It's not a perfect workaround because it has to be included before anything else includes react-bootstrap, since `BootstrapMixin` copies the keys when loaded.

**Comment by trevorr** [comment]
Did v0.20.0 break the workaround of modifying `constants`? It's not working for me anymore.

**Comment by mtscout6** [comment]
Thanks @trevorr I didn't realize that I missed that when we transitioned to using ES6 source. I just published a fix in version 0.20.1.

**Comment by AlexKVal** [comment]
Maybe it would be appropriate to implement some kind of configuration option for disabling
all style checking at all for those who needs it ? 
Maybe as temporary solution ?

**Comment by mtscout6** [comment]
I don't think that's entirely necessary. All that happens with prop validation is console warnings. No errors, and #496 really did provide a nice means to include supported values by downstream users.

**Comment by AlexKVal** [comment]
It seems that hardcoded "bottlenecks" exists only in three components now.
```<Input />```
```js
propTypes: {
  bsStyle: React.PropTypes.oneOf(['success', 'warning', 'error'])
...
```
and
```<FormGroup />``` ```bsStyle: React.PropTypes.oneOf(['success', 'warning', 'error']),```
```<ListGroupItem /> ``` ```bsStyle: React.PropTypes.oneOf(['danger', 'info', 'success', 'warning'])```

Is there any value to implement something like #496 for these three components ?
I don't have enough expertise in `react-bootstrap` for this to answer.

**Comment by mtscout6** [comment]
What's difficult about this is that bootstrap does not have the same set of styles for each component. For example the `Button` css styles support more types than `Input` of type text. It would be worth taking an inventory of each of the sets that bootstrap uses and make a decision with some better knowledge. What I think has happened is that we have been starting to see that disparity, and haven't figured out a decent solution for it.

**Comment by mtscout6** [comment]
The other problem is that some folks are still able to write their own css which may add more available styles. So, for those components these users want to allow those added styles without console warnings. Having the global pool of options through the old `constants` and now `styleMaps` though is sub-optimal since it would not catch usage of styles that may not exist for a particular component. This needs more thought....

**Comment by chellberg** [comment]
+1 @nemothekid, would be great if `bsStyle={false}` suppressed the warnings. I'm trying to conditionally apply `bsStyle` and there doesn't appear to be a falsey option that doesn't generate warnings.

(thanks for the great library, guys)

**Comment by bbtfr** [comment]
Seems we don't have `react-bootstrap/lib/constants` anymore?
+1 for bsStyle={false}

**Comment by taion** [comment]
This got fully replaced now. We're not dropping validation anyway.

**Comment by tonyspiro** [comment]
Running into this also.  Please update.

**Comment by tonyspiro** [comment]
Ok, looks like bsStyle={ null } suppresses the errors.

**Comment by Dragonqos** [comment]
tonyspiro - thanks, bsStyle={null} works great

**Comment by bbtfr** [comment]
@tonyspiro :+1: thanks!

**Comment by thinkshihang** [comment]
@tonyspiro Thanks. bsStyle={null} +1
