### ISSUE TITLE
There is no 'npm run docs' npm script in package.json

### ISSUE THREAD

**Issue by manishsaraan** [react-bootstrap/react-bootstrap#3060]
There is mention of `npm run docs` in readme but no script with name in package.json. @jquense can provide the script which is used to create docs. Thanks.

**Comment by jquense** [comment]
To start the docs run `yarn install && yarn run bootstrap-docs` to set everything up, and then navigate to `www` and run `yarn run develop` 

I'll update the readme to make this easyier!

**Comment by manishsaraan** [comment]
Ok cool. Thanks

**Comment by jquense** [comment]
fixed everywhere!
