### ISSUE TITLE
Broken examples in the grid documentation

### ISSUE THREAD

**Issue by RKushnir** [react-bootstrap/react-bootstrap#3066]
This is what https://react-bootstrap.github.io/layout/grid/ looks like for me(Mac, Firefox/Chrome/Safari). Also, if I try to edit the code, it goes all crazy by adding these chars `">">">` for each key pressed.

<img width="880" alt="screen shot 2018-03-08 at 12 39 27 pm" src="https://user-images.githubusercontent.com/205906/37149291-cbea5ede-22cd-11e8-9c38-10dfdcfcc22d.png">

**Comment by highskillzz** [comment]
Can I take this issue

**Comment by highskillzz** [comment]
I am sorry, but where can I find the documentation to edit it

**Comment by jquense** [comment]
It's in this repo in the www/ folder

**Comment by astronomersiva** [comment]
Hi @highskillzz, just wanted to know if you are still working on this. I would like to take this up if you are held up with something.

**Comment by highskillzz** [comment]
I am working on it but it is my first open source so it's not getting done as fast as normal.

**Comment by jquense** [comment]
No worries @highskillzz , no rush. If it's helpful feel free to open up the pull request as as a WIP (work in progress) if you need feedback as you're doing it. Pull requests don't need to be "done" to open, since you can always make changes to it by pushing more updates to your branch

**Comment by highskillzz** [comment]
I made some changes and I am trying to run it but it shows me this error
![Uploading image.png…]()
I been stuck here unable to solve this. Can someone help

**Comment by jquense** [comment]
picture seems broken!

**Comment by highskillzz** [comment]
ohh sorry
![image](https://user-images.githubusercontent.com/20688709/37983131-25a0ec6c-3210-11e8-83d4-9b7a027126ac.png)

**Comment by iamnapo** [comment]
You need to use Node >= 8.3.0

**Comment by jquense** [comment]
yes, we should add that to the "engines" field

**Comment by highskillzz** [comment]
Thank you @iamnapo  and @jquense. It has compiled successfully

 But there is another another error popping up 
![image](https://user-images.githubusercontent.com/20688709/38046153-7ff73c76-32dc-11e8-8a69-fb77e88fd5ee.png)

But i do not think that react is not defined could be an error as it has been compiling in your computers. 

I looked around and it said fix webpack file or import react properly which do not seem to the problem.

Your suggestions?

**Comment by jquense** [comment]
I'm not sure maybe the docs are set up right? have you followed the instructions here: https://github.com/react-bootstrap/react-bootstrap#local-setup

**Comment by highskillzz** [comment]
Yeah exactly as told 
![image](https://user-images.githubusercontent.com/20688709/38084307-fea6725c-3369-11e8-9402-5c55fa8a5761.png)
Can you notice anything wronrg? I even updated the node

I will clone the repo and try again

**Comment by iamnapo** [comment]
maybe delete the two `yarn.lock` files and try again?

**Comment by taion** [comment]
this was resolved
