### ISSUE TITLE
Button in MenuItem

### ISSUE THREAD

**Issue by qtbit** [react-bootstrap/react-bootstrap#3067]
Have a problem with creating a button in a menu item.

Two possibilities how to implement it:
1. `<MenuItem>[icon] item1 <Button>Remove</Button></MenuItem>`
2. `<MenuItem>[icon] item2 </MenuItem><Button>Remove</Button>`

Two results:
1. `<li><a>[icon] item1 <button>Remove</button></a></li>`
2. `<li><a>[icon] item2 </a></li><button>Remove</button>`

However, none of those is correct :-(

*Expected is:*

`<li><a>[icon] item1</a><button>Remove</button></li>`

**Comment by taion** [comment]
a menu item is a list item with a link in it, so it's possible you just can't do this with `<MenuItem>`

**Comment by qtbit** [comment]
So, the advice is to go to the source code of MenuItem, copy it and change it as I need? :-D

**Comment by jquense** [comment]
Mostly, bootstrap v3 doesn't really support anything other than links in menus so your in uncharted territory. The v4 does allow this by and RB will update to facilitate that when we get there
