### ISSUE TITLE
dropdownButton noCaret is not working

### ISSUE THREAD

**Issue by redmerten** [react-bootstrap/react-bootstrap#3068]
"react-bootstrap": "^0.32.1",
"react": "^16.2.0",
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

`render() {
    const item=this.props.navItem
    return (
      <Nav>
        <DropdownButton
          title={item.label}
          onMouseEnter = { this.handleOpen }
          onMouseLeave = { this.handleClose }
          open={ this.state.isOpen }
          noCaret           
        >
          <MenuItem>Hello</MenuItem>
        </DropdownButton>
      </Nav>
    )
  }
`

I've tried noCaret, noCaret={true}, noCaret={false} //=2 carets

**Comment by taion** [comment]
works fine in our examples https://react-bootstrap.github.io/components/dropdowns/#btn-dropdowns-nocaret

**Comment by redmerten** [comment]
Maybe, but it doesn’t work in my example.

**Comment by redmerten** [comment]
Here is my new example. It does not work. It also displays a caret.  What css link are you using?  What is bsstyle='default'?

`return (
        <ButtonToolbar>
        <DropdownButton
          bsStyle="default"
          title={item.label}
          onMouseEnter = { this.handleOpen }
          onMouseLeave = { this.handleClose }
          open={ this.state.isOpen }
          noCaret
          id="dropdown-no-caret"
        >
          <MenuItem>Hello</MenuItem>
        </DropdownButton>
        </ButtonToolbar>

    )`

**Comment by jessqnnguyen** [comment]
+1 Did the noCaret prop get deprecated? What is the current best way to hide the caret?

**Comment by jefelewis** [comment]
This worked for me!

```css
.dropdown-toggle::after{
    display: none;
}
```

**Comment by radu-cs** [comment]
See how to solve this [here](https://github.com/react-bootstrap/react-bootstrap/issues/3499#issuecomment-830110170)
