### ISSUE TITLE
xs={6} xsOffset={6} => (Offset) - fail

### ISSUE THREAD

**Issue by Binhngoc** [react-bootstrap/react-bootstrap#3069]
<Row className="show-grid">
    <Col xs={6} xsOffset={6}>
      <code>&lt;{'Col xs={6} xsOffset={6}'} /">&gt;</code>
    </Col>
</Row>

**Comment by taion** [comment]
offsets work fine in https://react-bootstrap.github.io/layout/grid/. check your css

**Comment by Binhngoc** [comment]
@taion thanks pro :D
