### ISSUE TITLE
issue 3068 is not resolved. Still shows caret

### ISSUE THREAD

**Issue by redmerten** [react-bootstrap/react-bootstrap#3071]
Updated code per your recommendation.  Still shows caret.  What css link are you using?  What is bsStyle ="default"?

`render() {
    const item=this.props.navItem
    return (
        <ButtonToolbar>
        <DropdownButton
          bsStyle="default"
          title={item.label}
          onMouseEnter = { this.handleOpen }
          onMouseLeave = { this.handleClose }
          open={ this.state.isOpen }
          noCaret
          id="dropdown-no-caret"
        >
          <MenuItem>Hello</MenuItem>
        </DropdownButton>
        </ButtonToolbar>

    )
  }

`

**Comment by jquense** [comment]
please check the docs. you need the v3 css.

**Comment by redmerten** [comment]
"react-bootstrap": "^0.32.1",
"react": "^16.2.0”,

from docs = not working

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

Not working
render() {
  const item=this.props.navItem
  return (
      <ButtonToolbar>
      <DropdownButton
        bsStyle="default"
        title={item.label}
        //onMouseEnter = { this.handleOpen }
        //onMouseLeave = { this.handleClose }
        //open={ this.state.isOpen }
        noCaret
        id="dropdown-no-caret"
      >
        <MenuItem>Hello</MenuItem>
      </DropdownButton>
      </ButtonToolbar>

  )
}

**Comment by jquense** [comment]
I'm not sure what to tell you..it works in our docs which are using the latest version. I think you probably have the bootstrap v4 case somewhere. if you could post something that reproduces what your seeing in jsfiddle or codesandbox that would be the most helpful

**Comment by redmerten** [comment]
You must get a free lunch if you close things regardless of whether they are actually resolved.

**Comment by jquense** [comment]
please provide a reproduction demostrating that it's not resolved and we'll be happy to help!

**Comment by redmerten** [comment]
https://github.com/redmerten/BeautyCounts <https://github.com/redmerten/BeautyCounts>

**Comment by jquense** [comment]
hey, that's not super helpful, no one here has time to figure out how to deploy your website. Please use jsfiddle or codesandbox (like i noted above) to show a **minimal** reproduction of the issue. Please respect maintainers time by doing at least the minimum amount of work to help us help you.

**Comment by redmerten** [comment]
clone cd server and type nom run dev

**Comment by jquense** [comment]
good luck!
