### ISSUE TITLE
V4: Update documentation for DropdownButton to clarify behavior of splitComponentProps

### ISSUE THREAD

**Issue by timhwang21** [react-bootstrap/react-bootstrap#3077]
I was using `<DropdownButton/>` and wanted to attach a handler for when the dropdown closed. I saw in the docs that this prop was supported on `<Dropdown/>`, and thought that I had to implement the more complex approach described in section "Custom Dropdown Components." However, looking in the source, the `splitComponentProps` util intelligently applies props where they need to be. This makes my life a lot easier, but it wasn't clear that this happened from the docs -- I had to look at the source itself.

Was wondering if it might be a good idea to describe this in the docs? If so I can make a quick PR, or a new contributor can do so as an easy task. Thanks!

**Comment by mxschmitt** [comment]
@timhwang21 sure you can fire up an PR. But I will close this for now, because it's quite stale.
