### ISSUE TITLE
Warning: Each child in an array or iterator should have a unique "key" prop. in PanelGroup

### ISSUE THREAD

**Issue by ESTEBANMURUZABAL** [react-bootstrap/react-bootstrap#3079]
Hi guys, Could you give me a hand on this one please:

I am getting a unique key warning because I am putting a PanelGroup inside a map so the keys if each child are the same.. How could I pass a unique key to each PanelGroup component? I have already tried passing "key={idx}".

Warning:
<img width="776" alt="screen shot 2018-03-17 at 12 47 30" src="https://user-images.githubusercontent.com/9825036/37557312-6d898674-29e1-11e8-880b-bb5b5bf25a4c.png">

My code:
<img width="495" alt="screen shot 2018-03-17 at 12 45 15" src="https://user-images.githubusercontent.com/9825036/37557301-3f217abc-29e1-11e8-8a0b-ec1779514650.png">

A millon of thanks to anybody that can suggest something.. :)

**Comment by jquense** [comment]
The key prop needs to go on the return value of the map,the PanelGroup
