### ISSUE TITLE
MultiSelect keeps selected first or last element

### ISSUE THREAD

**Issue by WinWinHost** [react-bootstrap/react-bootstrap#3084]
Hi,

I tried this with a raw select, and I got the same result. 
So I am sure that this is not something isolated to react-bootstrap, but I didn't know where else to post my question. 

Here is how I am generating it:

        <FormGroup controlId="formControlsSelectMultiple">
           <ControlLabel>Sensors</ControlLabel>
           <FormControl componentClass="select" multiple onChange={this.handleSelectChange}>
             {sensorOptions}
           </FormControl>
         </FormGroup>

where:

    const sensorOptions = this.props.sensors.map( option => {
      if( this.state.observers && this.state.observers.includes( option._id ) ){
        console.log( `<option value=${option._id} selected>${option._id}</option>`);
        return <option value={option._id} selected="selected">{option._id}</option>
      }
      else
        return <option value={option._id} selected="false">{option._id}</option>
    })

I thought I would get clever and put a selected="false", but that just made the last element also selected, instead of just the first.

What am I doing wrong here?

https://github.com/WinWinHost/mqtt-data-generator/blob/master/components/FormAssets.js

**Comment by dozoisch** [comment]
Have you tried using `selected={true}` or `selected={false}` instead of string values. React probably passes the properties as is if they are string which means it's gets the selected attribute and HTML only check if that attribute is present or not..
