### ISSUE TITLE
Using react-bootstrap cdn gives `TypeError: Cannot read property 'version' of undefined`

### ISSUE THREAD

**Issue by shivam-tripathi** [react-bootstrap/react-bootstrap#3085]
Using react-bootstrap CDN gives 
`TypeError: Cannot read property 'version' of undefined
    at Object.eval
    at __webpack_require__ 
    at Object.exports.__esModule 
    at __webpack_require__ 
    at Object.eval 
    at __webpack_require__
    at Object.eval 
    at __webpack_require__ 
    at module.exports 
    at eval`
I am using [https://cdnjs.cloudflare.com/ajax/libs/react-bootstrap/0.32.1/react-bootstrap.min.js](https://cdnjs.cloudflare.com/ajax/libs/react-bootstrap/0.32.1/react-bootstrap.min.js). 
Where am I going wrong?
Please note the previous versions work fine. Thanks for your help! 😃

**Comment by iamnapo** [comment]
Hi there, that's because you need to include `react` and `react-dom`. Check [this](https://react-bootstrap.github.io/getting-started/introduction/).

**Comment by iamnapo** [comment]
Hi there, that's because you need to include `react` and `react-dom` as well. Check [this](https://react-bootstrap.github.io/getting-started/introduction/).

**Comment by shivam-tripathi** [comment]
@iamnapo Sorry for not explaining the problem in full detail before (thought it wasn't necessary). I am trying to write a userscript where I am including all the relevant scripts, and I get the above error. 
I just tested what you said in a html file and it works great. I am unsure how to do it with userscripts though 😞 
By any chance, do you know how to do it with userscripts (I know it's a pretty specific problem and probably this is not the best place to ask).
```
// @require      https://cdnjs.cloudflare.com/ajax/libs/react/16.2.0/umd/react.production.min.js
// @require      https://cdnjs.cloudflare.com/ajax/libs/react-dom/16.2.0/umd/react-dom.production.min.js
// @require      https://cdnjs.cloudflare.com/ajax/libs/react-bootstrap/0.32.1/react-bootstrap.min.js
```

**Comment by jquense** [comment]
@shivam-tripathi you need to make sure that React and ReactDom are loaded first i think
