### ISSUE TITLE
Update Bootstrap 4 issue label

### ISSUE THREAD

**Issue by nickmccurdy** [react-bootstrap/react-bootstrap#3086]
I see the `bootstrap v4` label is currently only on two issues, even though there are many issues prefixed with `v4:` https://github.com/react-bootstrap/react-bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue+v4.

Please label these issues to make contribution easier and update the readme and site to point to this instead of https://github.com/react-bootstrap/react-bootstrap/pull/2752.

**Comment by jquense** [comment]
V4 issues are tagged to the v4 support project. Feel free to search by that. I'll love the label when I get a chance

**Comment by nickmccurdy** [comment]
Are you suggesting that issues added to the project should be labelled? Because it seems like there are some issues in the project that start with `v4:` but aren't labelled as such.

**Comment by jquense** [comment]
I'm saying that the project functions as the label in this case: https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aopen+is%3Aissue+project%3Areact-bootstrap%2Freact-bootstrap%2F1

**Comment by nickmccurdy** [comment]
I see thanks, I didn't realize you could filter projects in issues! 😄 

Could we remove the label to reduce confusion then? Since it's just a subset of this project.

**Comment by jquense** [comment]
yup done

**Comment by nickmccurdy** [comment]
Thanks! I guess we could delete the label too right?
