### ISSUE TITLE
Custom content in DropdownButton

### ISSUE THREAD

**Issue by Semigradsky** [react-bootstrap/react-bootstrap#309]
Hello, can I use my content in `a.dropdown-toggle`? Not `span.caret`.
It's looks like [hardcoded](https://github.com/react-bootstrap/react-bootstrap/blob/master/src/DropdownButton.jsx#L46-L47)

**Comment by defrex** [comment]
Looks like you could pass `noCaret={true}` and put a custom caret in the `title` attribute.

**Comment by mtscout6** [comment]
Is that link still pointing at what you expect? Can you change the link to not point at master but at the latest tagged release.

**Comment by Semigradsky** [comment]
Oh, thank you, it seems to be what I need
