### ISSUE TITLE
Modal's dependency on Object.assign is not resolved via AMD

### ISSUE THREAD

**Issue by gerryster** [react-bootstrap/react-bootstrap#310]
For example in foo.jsx:

```esx
var Button = require('react-bootstrap/Button');
var Modal = require('react-bootstrap/Modal');
var ModalTrigger = require('react-bootstrap/ModalTrigger');

var MyModal = React.createClass({
  render: function() {
    return (
      <Modal {...this.props} title="Modal heading" animation={false}>
        <div className="modal-body">
          <h4>Text in a modal</h4>
          <p>Duis mollis, est non commodo luctus, nisi erat porttitor ligula.</p>
        </div>
        <div className="modal-footer">
          <Button onClick={this.props.onRequestHide}>Close</Button>
        </div>
      </Modal>
    );
  }

  render() {
    return (
        <ModalTrigger modal={<MyModal />}>
          <Button bsStyle="primary" bsSize="large">Launch demo modal</Button>
        </ModalTrigger>
    )
  }
});
```

When Launch demo modal button is pressed, a "Uncaught TypeError: undefined is not a function" error is thrown in Chrome because of the Object.assign in line four of the generated code: 

```javascript
var MyModal = React.createClass({displayName: 'MyModal',
  render: function() {
    return (
      Modal(Object.assign({}, this.props, {title: "Modal heading", animation: false}), 
        React.DOM.div({className: "modal-body"}, 
          React.DOM.h4(null, "Text in a modal"), 
          React.DOM.p(null, "Duis mollis, est non commodo luctus, nisi erat porttitor ligula.")
        ), 
        React.DOM.div({className: "modal-footer"}, 
          Button({onClick: this.props.onRequestHide}, "Close")
        )
      )
    );
  }
```

I was able to workaround this by including an Object.assign polyfill.  However, it looks like there is already an [Object.assign polyfill](https://github.com/react-bootstrap/react-bootstrap/blob/master/src/utils/Object.assign.js) included in this project.  Is there a missing require to this for Modals?

**Comment by mtscout6** [comment]
Are you still seeing this issue?

**Comment by taion** [comment]
This looks like it's an issue with your JSX compiler emitting an `Object.assign` for your use of `{...this.props}` in your example, and doesn't have anything to do with the `Modal` itself.

However, currently neither Facebook's jsx compiler nor Babel emit this code (they respectively use `React.__spread` and a custom `_extends`). Perhaps this was an old bug in one of those? I'm going to close this as invalid for the time being, because the `Object.assign` call is not coming from React Bootstrap.
