### ISSUE TITLE
[Question] V4 release date

### ISSUE THREAD

**Issue by JonyTek** [react-bootstrap/react-bootstrap#3104]
Hi guys, 

I wanted to ask about the expected release date for the move up to V4 of Bootstrap.

Thanks in advance.

**Comment by taion** [comment]
Take a look at https://github.com/react-bootstrap/react-bootstrap/pull/2752#issuecomment-378223315

We don't have an exact date set, but you can keep tabs on the progress fairly easily.

**Comment by JonyTek** [comment]
Appreciate the response. I look forward to it.
