### ISSUE TITLE
Events fired inside a Modal get hijacked by parent

### ISSUE THREAD

**Issue by xiaolin99** [react-bootstrap/react-bootstrap#3105]
Version: react@16.3.0, react-bootstrap@0.32.1

Symptom: Let's say I have a Dropdown MenuItem that pops up a Modal, the events fired inside the Modal will propagate to the parent (the Dropdown in this case and cause unintended behaviors such space key does not work inside the input):
```
import React from 'react';
import { DropdownButton, MenuItem, Modal } from 'react-bootstrap';

export default class Test extends React.Component {
    constructor(props) {
        super(props);
        this.state = {
            showModal: false,
        };
        this.open = this.open.bind(this);
        this.close = this.close.bind(this);
    }
    open() {
        this.setState({ showModal: true });
    }
    close() {
        this.setState({ showModal: false });
    }
    render() {
        return (
          <div>
            <DropdownButton title="testing" id="DropdownButton">
              <MenuItem eventKey="1" >
                <div>
                  <div onClick={this.open}>Pop up</div>
                  <Modal show={this.state.showModal} onHide={this.close}>
                    <Modal.Header closeButton>
                      <Modal.Title>Test Modal - try to press Space or Up key</Modal.Title>
                    </Modal.Header>
                    <Modal.Body>
                      <input type="text" />
                    </Modal.Body>
                  </Modal>
                </div>
              </MenuItem>
            </DropdownButton>
          </div>
        );
    }
}
```

I'm guessing this is caused by the new Portal API, but apparently React does not think this is a bug: https://github.com/facebook/react/issues/11387 (this thread contains a workaround), so I'm posting it here.

Edit: workaround - add stopPropagation to the parent div of the modal e.g.
```
<div
     onKeyDown={e => e.stopPropagation()}
     onClick={e => e.stopPropagation()}
     onFocus={e => e.stopPropagation()}
     onMouseOver={e => e.stopPropagation()}
     ... can add other events if they are giving you issues
>
  <Modal>
   ...
  </Modal>
</div>
```

**Comment by jquense** [comment]
I do think we should probably provide a workaround for this in the Modal case, since it's almost never the intended behavior. The general problem with a workaround tho is the "React Way" to implement it would be a ModalProvider component at or near the root of the app, which i don't love.

**Comment by taion** [comment]
Meh. I don't suppose React would consider adding some sort of extension to the portal API that would kill event bubbling?

**Comment by jquense** [comment]
probably not soon. There is a lot of discussion around it tho, but very little movement.

**Comment by yashka713** [comment]
That's worst, when I tried to add `<form>` onto the `<Modal> in`<Navbar>`, form did the same that 
 @xiaolin99 said and `onSubmit` stoped work, but 'onSubmit' starts work from my own component.

**Comment by sbilinski** [comment]
Same happens when embedding a `Checkbox` inside a `<NavDropdown>`, which seems like a common use-case as well (e.g. a list of filters). 

@xiaolin99's workaround [fixed](https://gist.github.com/sbilinski/8907e6b13b49dd6b41221068f5103caa) the problem for me.

**Comment by craigkovatch** [comment]
@jquense can you help me understand why we've had so much discussion over adding such a small flag? What is the drawback?

**Comment by jquense** [comment]
In React? I can't really speak for the team there. It's not a small flag tho, at least not internally, there is no quick little implementation that would turn off bubbling, the apis would deviate completely in their implementation. they also take API changes and deviations very seriously and especially when they are as messy as these would be.ive tried to start the conversation a bit again in the one issue

**Comment by etaybarzilay89** [comment]
Reproduces for me too.
When clicking on the modal, the parent container catches the onClick event.

Experiencing a very unstable behavior...

Is someone from React addressed this issue?

**Comment by jquense** [comment]
this is the expected behavior with React Portals. I'd suggest taking it up on the existing issue on the react repo if you disagree with the behavior, thanks!
