### ISSUE TITLE
Reloaded: React 16 – Modal.Body input refs no longer usable from componentDidUpdate() in parent

### ISSUE THREAD

**Issue by dperetti** [react-bootstrap/react-bootstrap#3114]
The [original issue](https://github.com/react-bootstrap/react-bootstrap/issues/2841) was closed when it was [moved](https://github.com/react-bootstrap/react-overlays/issues/224) to and [fixed](https://github.com/react-bootstrap/react-overlays/pull/229) in `react-overlays` `0.8.3` but the fix has not been incorporated back into react-bootstrap, which is still using [0.8.0](https://github.com/react-bootstrap/react-bootstrap/blob/master/package.json#L109).

**Comment by taion** [comment]
The dependency isn't pinned; you can just reinstall.

**Comment by jquense** [comment]
we should prolly bump it tho

**Comment by dperetti** [comment]
OK, re-installed react-bootstrap with react-overlays 0.8.3... and alas **the issue is not fixed**. Please re-open !

**Comment by henrych4** [comment]
Maybe it's a bit late but there is a fix in https://github.com/react-bootstrap/react-overlays/pull/229.

Upgrade react-overlays to ^0.9.0 should fix the problem.
