### ISSUE TITLE
Modals not scrolling

### ISSUE THREAD

**Issue by BellaMay95** [react-bootstrap/react-bootstrap#3116]
By default, the 'overflow' property is set to "hidden" on the outside div created by Modal.Dialog, which prevents scrolling of the Modal when the modal overflows the screen. Using the tab key brings into focus the hidden fields but that's obviously not a real solution.

I fixed the scrolling in my code by adding `style={{ overflow: 'auto' }}` to the Modal.Dialog tag in my component as a temporary fix.

**Comment by taion** [comment]
See https://react-bootstrap.github.io/components/modal/#modals-live. Works fine on our examples.

**Comment by jkinley** [comment]
@taion Works fine? From what I can see, you don't have any examples of scrollable modals. As usual, React-Bootstrap needs a lot of improvements to the documentation. @BellaMay95 is right, it's not working as expected.

**Comment by stereodenis** [comment]
Yep
It's not working with fullscreen + scrollable

**Comment by jquense** [comment]
Guys it's absolutely useless to respond to a 5 year old closed issue. It makes zero sense to assume that the state of repo, docs, and code from a completely different major version would apply to your needs 5 years later. If you have a bug open a new issue
