### ISSUE TITLE
docs: html entities not rendered in code blocks

### ISSUE THREAD

**Issue by AndersDJohnson** [react-bootstrap/react-bootstrap#3118]
https://react-bootstrap.github.io/layout/grid/

![screen shot 2018-04-10 at 3 31 57 pm](https://user-images.githubusercontent.com/615381/38582098-53ceefac-3cd4-11e8-8b2e-bdde96c83d40.png)

**Comment by astronomersiva** [comment]
Running this on my machine renders the content correctly..Maybe this was fixed and the site never deployed?

cc: @jquense

**Comment by taion** [comment]
this got resolved
