### ISSUE TITLE
Modal cannot be scrolled if content overflows viewport

### ISSUE THREAD

**Issue by cmwelsh** [react-bootstrap/react-bootstrap#312]
On the live demo there is an issue with the modal component:

http://react-bootstrap.github.io/components.html

Scroll down to Modals and then click Launch Demo Modal. When scrolling with the modal open, the modal content does not scroll and the greyed out page content behind it scrolls instead.

Tested in Firefox 34 and Chrome 39.

Compare with behavior on official Bootstrap website: http://getbootstrap.com/javascript/#modals

**Comment by mtscout6** [comment]
This was fixed by #321.
