### ISSUE TITLE
Setting height and direction of a React-Bootstrap select element

### ISSUE THREAD

**Issue by carpben** [react-bootstrap/react-bootstrap#3120]
Is there a way to define a max-height for the select element when it opens? I noticed different select element have different heights before a scroll bar appears. I'm using the select element in a project, and it requires about 12 options, before the inner scroll appears. Is there a way to reduce it?

**Comment by jquense** [comment]
by select element do you mean the form input? The behavior for those is browser specific since they are just the native elements with some styling. As far as i know you can't control the height via css, but that's likely browser specific as well

**Comment by carpben** [comment]
Yes I mean the form input.

**Comment by taion** [comment]
Not really much we can do here – this is just a pass-through to the underlying Bootstrap styling/markup, so you'd just do so however you would if you weren't using React-Bootstrap.
