### ISSUE TITLE
Webpack bundle size is too large

### ISSUE THREAD

**Issue by jcguarinpenaranda** [react-bootstrap/react-bootstrap#3123]
Hello,

I am working with `react-bootstrap` and it's a great level of abstraction. However, I am inspecting the bundle size of my generated code in `webpack`and it seems to be that it is including both the `lib` and `es` directories into my bundle.

Look at this:

![captura de pantalla 2018-04-17 a las 11 28 21 a m](https://user-images.githubusercontent.com/7200821/38883598-0d5bc0b8-4233-11e8-8ddf-b982495d0f18.png)

This causes an extra weight of ~300kb to the bundle, and it would be very nice to reduce it.

Please help me find what is the issue

**Comment by jquense** [comment]
That happens when you import from both. We recomment only cherry-picking the modules you need like `import Button from 'react-bootstrap/es/Button`

**Comment by jcguarinpenaranda** [comment]
Thank you, so I should use only the `es` version?
I have problems testing this with `jest` :S

**Comment by jquense** [comment]
you can use either lib or es, the latter is es modules, so you need to use it in an environment that understands them
