### ISSUE TITLE
Tooltips & popovers incorrectly positioned when target is close to right edge of the screen

### ISSUE THREAD

**Issue by charlieharris1** [react-bootstrap/react-bootstrap#3127]
First of all thanks for this project!

The following screenshot is of the react-bootstrap docs with a narrow browser window. You can see that the tooltip appears below the target rather than inline with it.

<img width="400" alt="screen shot 2018-04-22 at 15 59 50" src="https://user-images.githubusercontent.com/11438777/39096390-4d0612aa-4647-11e8-849f-7259719776ea.png">

I'm going to try and dig into it, but if anyone is able to give me a hand that'd be great.

**Comment by taion** [comment]
Yeah... the initial render doesn't account for the wrapping I guess
