### ISSUE TITLE
Namespacing modals

### ISSUE THREAD

**Issue by keul** [react-bootstrap/react-bootstrap#3129]
I'm facing the issue to integrate a react-bootstrap application inside a 3rd party site.

I'm using a namespaced bootstrap theme so I'm reducing CSS clashing, but modals are still an issue: modals are created in the site root node (maybe it uses portals internally?) while my namespace class attribute is added deeper in the dom itself.

I'm wondering if there's a way to:

* choose where to create modal DOM elements (not in the DOM root in my case)
* adding a class name to the `data-reactroot` DOM node created when using modals

**Comment by jquense** [comment]
> choose where to create modal DOM elements (not in the DOM root in my case)

Yes! you can set the `container` prop which is the document body by default to control that.

> adding a class name to the data-reactroot DOM node created when using modals

Unfortunately not, but you can add a class to the node right above it since you control that.

**Comment by keul** [comment]
Great! I'm sorry, the `container` prop seems not really well documented so I missed its power!

Thanks again!

**Comment by jeremyisatrecharm** [comment]
> Yes! you can set the container prop which is the document body by default to control that.

> Loosely related: the same container prop can be used also for Tooltips components (found by inspecting react-overlays package).

These were both really helpful. Specifically, I used: `document.getElementById(this.MODAL_CONTAINER_ID)` and assigned the value to the `container` prop on `OverlayTrigger` and `Modal`. Thanks to @jquense and @keul !
