### ISSUE TITLE
(question/discussion) Warn users about issues with nested modals?

### ISSUE THREAD

**Issue by timhwang21** [react-bootstrap/react-bootstrap#3130]
Hi, this is about the `autoFocus` and `enforceFocus` [props](https://react-bootstrap.github.io/components/modal/).

Currently, we're using react-bootstrap's modals as a generic windowing component (which I understand is a terrible idea, but I'm just going to blame organizational politics and that's neither here or there...)

We were unaware of these props and ran into issues regarding modals stealing focus from other elements, and from each other.

The description for these props is pretty thorough, but I was wondering if it would be appropriate to add caveats about the modal somewhere in the docs (e.g. discourage using many at once, discourage using as generic windows), and if so, where these would best belong. I'd be happy to make a PR. Thanks!

**Comment by taion** [comment]
Well, we should probably document or link to the `ModalManager` bits in react-overlays that actually allow using multiple modals. This would go on the modals docs page, in any event.

**Comment by timhwang21** [comment]
@taion thanks! I added a note to the docs in a PR.
