### ISSUE TITLE
Panel introduces warning 

### ISSUE THREAD

**Issue by Ognian** [react-bootstrap/react-bootstrap#3137]
When moving to react 16.3.2 I'm getting this warning:
```
Warning: Failed prop type: You have provided a `expanded` prop to `Panel` without an `onToggle` handler. This will render a read-only field. If the field should be mutable use `defaultExpanded`. Otherwise, set `onToggle`
    in Uncontrolled(Panel) (created by TableOptions)
    in TableOptions (created by Connect(TableOptions))
    in Connect(TableOptions) (created by Items)
    in div (created by Items)
    in Items (created by Connect(Items))
    in Connect(Items) (created by Main)
    in div (created by Main)
    in Main (created by RouterContext)
    in div (created by Background)
    in Background (created by RouterContext)
    in RouterContext (created by Router)
    in Router (created by App)
    in App (created by HotExportedApp)
    in AppContainer (created by HotExportedApp)
    in HotExportedApp (created by Connect(HotExportedApp))
    in Connect(HotExportedApp)
    in div
    in IntlProvider
    in Provider
```
looking in the debugger the tree looks like:
![image](https://user-images.githubusercontent.com/1231174/39399494-e804d710-4b1e-11e8-84b3-95f88ae23591.png)

So there is only an uncontrolled Panel where onToggle is not set; and actually the above error also says that the uncontrolled Panel is responsible for the warning.

For me these even looks like a react error since such a warning should not be thrown for an uncontrolled component, but I'm not sure...
What do you think?
Thanks
Ognian

**Comment by taion** [comment]
you can see in your component trace above that you've passed in `expanded={false}` to the `UncontrolledPanel`

**Comment by Ognian** [comment]
OK, thanks a lot @taion,
the actual solution is to pass an empty function to onToggle in Panel 
```
 <Panel expanded={showColumnOptions} onToggle={()=>{}} 
```  
maybe your documentation at https://react-bootstrap.github.io/components/panel/ should also be corrected:
<img width="859" alt="image" src="https://user-images.githubusercontent.com/1231174/39404414-f732d52e-4b92-11e8-91da-5a839b63e694.png">
