### ISSUE TITLE
npm run dist error

### ISSUE THREAD

**Issue by Advancedbg** [react-bootstrap/react-bootstrap#3139]
macOS 10.13.4
Please help

> bootstrap@4.0.0 dist /Users/client/Dropbox/bootstrap
> npm-run-all --parallel css js

> bootstrap@4.0.0 css /Users/client/Dropbox/bootstrap
> npm-run-all --parallel css-lint* css-compile* --sequential css-prefix* css-minify*

> bootstrap@4.0.0 js /Users/client/Dropbox/bootstrap
> npm-run-all js-lint* js-compile js-minify

> bootstrap@4.0.0 js-lint /Users/client/Dropbox/bootstrap
> eslint js/ build/

> bootstrap@4.0.0 css-lint-vars /Users/client/Dropbox/bootstrap
> node build/lint-vars.js scss/ assets/scss/

> bootstrap@4.0.0 css-lint /Users/client/Dropbox/bootstrap
> stylelint --syntax scss "scss/**/*.scss"

> bootstrap@4.0.0 css-compile-docs /Users/client/Dropbox/bootstrap
> node-sass --output-style expanded --source-map true --source-map-contents true --precision 6 assets/scss/docs.scss assets/css/docs.min.css

> bootstrap@4.0.0 css-compile /Users/client/Dropbox/bootstrap
> node-sass --output-style expanded --source-map true --source-map-contents true --precision 6 scss/bootstrap.scss dist/css/bootstrap.css && node-sass --output-style expanded --source-map true --source-map-contents true --precision 6 scss/bootstrap-grid.scss dist/css/bootstrap-grid.css && node-sass --output-style expanded --source-map true --source-map-contents true --precision 6 scss/bootstrap-reboot.scss dist/css/bootstrap-reboot.css

sh: node-sass: command not found
npm ERR! file sh
sh: node-sass: command not found
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! bootstrap@4.0.0 css-compile-docs: `node-sass --output-style expanded --source-map true --source-map-contents true --precision 6 assets/scss/docs.scss assets/css/docs.min.css`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the bootstrap@4.0.0 css-compile-docs script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! bootstrap@4.0.0 css-compile: `node-sass --output-style expanded --source-map true --source-map-contents true --precision 6 scss/bootstrap.scss dist/css/bootstrap.css && node-sass --output-style expanded --source-map true --source-map-contents true --precision 6 scss/bootstrap-grid.scss dist/css/bootstrap-grid.css && node-sass --output-style expanded --source-map true --source-map-contents true --precision 6 scss/bootstrap-reboot.scss dist/css/bootstrap-reboot.css`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the bootstrap@4.0.0 css-compile script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/client/.npm/_logs/2018-05-01T20_46_11_336Z-debug.log

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/client/.npm/_logs/2018-05-01T20_46_11_341Z-debug.log

> bootstrap@4.0.0 css-lint-docs /Users/client/Dropbox/bootstrap
> stylelint --syntax scss "assets/scss/*.scss" && stylelint "docs/**/*.css"

Finding unused variables in "scss/"...
ERROR: "css-compile-docs" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bootstrap@4.0.0 css: `npm-run-all --parallel css-lint* css-compile* --sequential css-prefix* css-minify*`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bootstrap@4.0.0 css script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/client/.npm/_logs/2018-05-01T20_46_11_455Z-debug.log
ERROR: "css" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bootstrap@4.0.0 dist: `npm-run-all --parallel css js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bootstrap@4.0.0 dist script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/client/.npm/_logs/2018-05-01T20_46_11_538Z-debug.log

**Comment by jquense** [comment]
I'm not sure what this is but it doesn't look like react-bootstrap, seem like you are trying to do something with plain old bootstrap but it's unclear what, or what these errors are from

**Comment by Advancedbg** [comment]
This is my very first tryout, I am testing dist, yes on fresh downloaded Bootstrap. I have no idea where that older version coming from. I have downloaded the last by bootstrap website

**Comment by astronomersiva** [comment]
By the looks of it, it seems like you have downloaded the source of Bootstrap and running `npm dist`. 

Are you sure you ran `yarn` or `npm install` before doing this?

**Comment by Advancedbg** [comment]
Yes, I followed all steps. Since I try almost everything, I have decided to remove all and begin from blank. Here is what I did:
+ node.js - installed fresh v8.11.1
+ npm - installed fresh + npm@6.0.0
+ fresh bootstrap sources downloaded - bootstrap-4.0.0
Try to npm install, then find out python missing, but installation requires:
+ OSX GCC - installed
+ Homebrew 1.6.2 - installed
+ Python-3.6.5
+ jquery@3.3.1
+ jquery@1.9.1 (missing dependencies)
+ popper.js@1.14.3 (missing dependencies)
--- npm install PASSED 

clients-MacBook-Pro:bootstrap client$ npm run dist

> bootstrap@4.0.0 dist /Users/client/Dropbox/bootstrap
> npm-run-all --parallel css js


> bootstrap@4.0.0 css /Users/client/Dropbox/bootstrap
> npm-run-all --parallel css-lint* css-compile* --sequential css-prefix* css-minify*


> bootstrap@4.0.0 js /Users/client/Dropbox/bootstrap
> npm-run-all js-lint* js-compile js-minify


> bootstrap@4.0.0 css-lint /Users/client/Dropbox/bootstrap
> stylelint --syntax scss "scss/**/*.scss"


> bootstrap@4.0.0 css-lint-vars /Users/client/Dropbox/bootstrap
> node build/lint-vars.js scss/ assets/scss/


> bootstrap@4.0.0 js-lint /Users/client/Dropbox/bootstrap
> eslint js/ build/


> bootstrap@4.0.0 css-lint-docs /Users/client/Dropbox/bootstrap
> stylelint --syntax scss "assets/scss/*.scss" && stylelint "docs/**/*.css"


> bootstrap@4.0.0 css-compile-docs /Users/client/Dropbox/bootstrap
> node-sass --output-style expanded --source-map true --source-map-contents true --precision 6 assets/scss/docs.scss assets/css/docs.min.css


> bootstrap@4.0.0 css-compile /Users/client/Dropbox/bootstrap
> node-sass --output-style expanded --source-map true --source-map-contents true --precision 6 scss/bootstrap.scss dist/css/bootstrap.css && node-sass --output-style expanded --source-map true --source-map-contents true --precision 6 scss/bootstrap-grid.scss dist/css/bootstrap-grid.css && node-sass --output-style expanded --source-map true --source-map-contents true --precision 6 scss/bootstrap-reboot.scss dist/css/bootstrap-reboot.css

"scss/": Not a valid directory!
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bootstrap@4.0.0 css-lint-vars: `node build/lint-vars.js scss/ assets/scss/`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bootstrap@4.0.0 css-lint-vars script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/client/.npm/_logs/2018-05-02T13_05_34_728Z-debug.log
ERROR: "css-lint-vars" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bootstrap@4.0.0 css: `npm-run-all --parallel css-lint* css-compile* --sequential css-prefix* css-minify*`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bootstrap@4.0.0 css script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/client/.npm/_logs/2018-05-02T13_05_34_864Z-debug.log
ERROR: "css" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bootstrap@4.0.0 dist: `npm-run-all --parallel css js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bootstrap@4.0.0 dist script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/client/.npm/_logs/2018-05-02T13_05_34_938Z-debug.log
clients-MacBook-Pro:bootstrap client$
