### ISSUE TITLE
Pin node_version to 9.x in travis.yml?

### ISSUE THREAD

**Issue by timhwang21** [react-bootstrap/react-bootstrap#3143]
Looks like CI tests will always fail because `travis.yml` currently has `node_version` set to `stable` (v10) which causes a Yarn error.

[Example](https://travis-ci.org/react-bootstrap/react-bootstrap/jobs/374120358)

**Comment by taion** [comment]
i think we just need to run `yarn upgrade`

**Comment by timhwang21** [comment]
ah looks like this has been fixed upstream in the problematic lib (upath), [steps to fix here](https://github.com/facebook/create-react-app/issues/4367#issuecomment-385406565).

**Comment by taion** [comment]
resolved
