### ISSUE TITLE
Dropdown causing error when imported from component library

### ISSUE THREAD

**Issue by BenRoz** [react-bootstrap/react-bootstrap#3145]
Hey,
I'm building  a component library and using react-bootstrap for it.
For some reason using Dropdown component when imported from the component library causing the following error : 
Uncaught Error: Element ref was specified as a string (inner) but no owner was set. You may have multiple copies of React loaded.

few things : 
1) I do not get an error when using the component inline (not imported) 
2) I am using different react-bootstrap components like Button and Menu Item which are working when imported.
3) react and react DOM have similar versions in both libraries     "react": "^16.2.0",
    "react-dom": "^16.2.0"
4) react-bootstrap 0.32.1 is similar as well

Really need your help!
Many thanks!

**Comment by taion** [comment]
It's exactly as the error message suggests. You've ended up with multiple copies of React or React-DOM loaded somehow. Perhaps the library you're using has React as a direct dependency.

**Comment by BenRoz** [comment]
@taion thanks! just solved it by adding to webpack 
resolve: {
    alias:  react: path.resolve(paths.base(), 'node_modules/react')
}
