### ISSUE TITLE
Navbar.Toggle and NavDropDown not working offline with service worker

### ISSUE THREAD

**Issue by pasl10** [react-bootstrap/react-bootstrap#3146]
I'm developing a React app using react-bootstrap and I added a simple service worker to make my app work offline.

Everything works fine expect for the Toggle button and the Dropdown button in my navbar. My navbar is equal to the one in the documentation (https://react-bootstrap.github.io/components/navbar/#navbars-mobile-friendly).

When I'm working online, it works, but when I go offline, these two problems happen when I'm refreshing the page or when I'm in that page for the first time.

Let's say the page that has the navbar is /home. When I go there for the first time, the problem happens. Then, I go to home/anotherpage and press the back button, going back to /home. Now, everything works fine. I refresh /home and the problem is there again.

I added bootstrap.min.js and jquery.min.js to cache (the jquery file loading before the bootstrap.min.js file) to see if it worked, but it still happens. Nothing shows up in the console as well.

**Comment by taion** [comment]
do you have any sort of repro here? i'm not sure what possible interaction there could be between R-B and the use of service workers

**Comment by jquense** [comment]
you shouldn't be including `bootstrap.js` that sounds like the normal bootstrap js file, not the react-bootstrap one which is different
