### ISSUE TITLE
React.createElement: type is invalid -- expected a string (for built-in components)

### ISSUE THREAD

**Issue by alexbigapps23** [react-bootstrap/react-bootstrap#3147]
Hi I get this warning 

Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in. Check the render method of

**Comment by KagamiChan** [comment]
Please provide some code to reproduce, and the most probable cause for your issue is that the component you use is actually `undefined`

**Comment by alexbigapps23** [comment]
`import React, { Component, PropTypes } from "react";
import { connect } from "react-redux";
import { Button, FormGroup, form, type, FormControl, Checkbox } from "react-bootstrap";
import TopTitle from "../../components/Header/TopTitle";
import { GetUsers, GetCompany } from "./actions";
import { GetStore } from "../Company/actions";
import { add } from "../Countability/actions";




import '../../react-datepicker.css';
import moment from 'moment';

const DAY_FORMAT = 'DD/MM/YYYY';

class CountabilityNew extends Component {

	constructor(props) {
		super(props);
		this.state = {
			management: "",
			company: "",
			store: "",
			storeCode: "",
			startDate: "",
			startRation: "",
			endRation: ""
		};
		this.handleChange = this.handleChange.bind(this);
		this.handleSubmit = this.handleSubmit.bind(this);
	}

	componentWillMount() {
		this.props._addUserRole();
		this.props._getCompany();
	}

	handleChange(event) {
		if (event.target.name == "company") {
			this.props._getStore(event.target.value);
		}

		if (event.target.name == "storeCode") {

			const code = event.target.value;
			document.getElementById("store").value = code;
		}

		if (event.target.name == "store") {

			const code = event.target.value;
			document.getElementById("storeCode").value = code;
		}

		this.setState({
			[event.target.name]: event.target.value
		});
	}
	handleSubmit(event) {


		event.preventDefault();
		this.props._addCountability(this.state);
	}

	handleDayChange = (selectedDay, modifiers) => {

		this.setState({
			["startDate"]: selectedDay
		});
	};

	render() {



		return (
				<div className="col-lg-4">
					<div className="panel panel-default">
			
						<div className="panel-body">
							<form id="userForm" onSubmit={(e) => this.handleSubmit(e)}>
							
								<FormGroup controlId="formInlineEmail">
									<FormControl type="text" name="name" onChange={this.handleChange} placeholder="name" />
								</FormGroup>


								<Button type="submit">
									שלח
								</Button>

							</form>

						</div>
					</div>
				</div>
			</div>

		);
	}
}


const mapDispatchToProps = (dispatch) => {
	return {
		_addUserRole: () => {
			dispatch(GetUsers());
		},
		_getCompany: () => {
			dispatch(GetCompany());
		},
		_getStore: (id) => {
			dispatch(GetStore(id));
		},
		_addCountability: (params) => {
			dispatch(add(params));
		}
	};
};


const mapStateToProps = (state) => {
	return state;
};

export default connect(
	mapStateToProps,
	mapDispatchToProps
)
	(CountabilityNew);


`

**Comment by taion** [comment]
See the error message from React. Likely one of your imports is wrong, as one of your element types you’re attempting to use is instead undefined.
