### ISSUE TITLE
Documentation: Button doc duplicates bsSize examples for bsStyle

### ISSUE THREAD

**Issue by jpdail01** [react-bootstrap/react-bootstrap#3149]
https://react-bootstrap.github.io/components/buttons/

![react-bootstrap-documentation](https://user-images.githubusercontent.com/2530815/39894678-a8474dc8-5475-11e8-8e14-1d76f5ae7e68.PNG)

**Comment by jpdail01** [comment]
Should be:

primary
success
info
warning
danger 
link

**Comment by abdullahtariq1171** [comment]
Fixed. We can close this one @jpdail01
