### ISSUE TITLE
Getting error as "Warning: In the context of a `<TabContainer>`, `<TabPanes>` are given generated `id` and `aria-labelledby` attributes for the sake of proper component accessibility."

### ISSUE THREAD

**Issue by ruchijn** [react-bootstrap/react-bootstrap#3155]
I am using the sample code provided at https://react-bootstrap.github.io/components/tabs/#tabs-controlled. I keep getting warning as `Warning: In the context of a `<TabContainer>`, `<TabPanes>` are given generated `id` and `aria-labelledby` attributes for the sake of proper component accessibility. Any provided ones will be ignored. To control these attributes directly provide a `generateChildId` prop to the parent `<TabContainer>`.`

Any idea how to resolve this?

**Comment by taion** [comment]
follow exactly what that says – don't pass in those props when using the tabs component

**Comment by ruchijn** [comment]
@taion - I see you closed my issue. Here is my code: 
```
        <Tabs
          activeKey={this.state.key}
          onSelect={this.handleSelect}
          id="my-tab-menu"
        >
          <Tab eventKey={1} title={tab1}>
            Tab 1 content
          </Tab>
          <Tab eventKey={2} title={tab2}>
            Tab 2 content
          </Tab>
        </Tabs>
```

Will it be possible to point out what am I doing wrong. Thanks
