### ISSUE TITLE
Panel is getting toggled even after calling event.stopPropagation()

### ISSUE THREAD

**Issue by jainvizz** [react-bootstrap/react-bootstrap#3156]
Hi I am using react-bootstrap panel accordion like this:

```
<Panel eventKey={this.state.eventKey}>
              <Panel.Heading onClick={(event) => this.onPanelHeadingClick(event)}>
                  <Panel.Title toggle>
                    {this.state.currentResource.resourceName}
                    <Switch align="right" checked={this.state.currentResource.isAllowed ? "checked" : ""} onSwitchChange={this.onResourceSwitchChange} />
                  </Panel.Title>
              </Panel.Heading>
              <Panel.Body collapsible>
                   ...
              </Panel.Body>
</Panel>
```

Now on click of panel heading I am checking the event target and if it is my switch component I want to restrict the panel from opening. Code provided below:

```
onPanelHeadingClick(e){
    if(e.target.classList.contains('slider')){
      e.stopPropagation();
    }
  }
```

Even after calling e.stopPropagation(); panel is getting opened. I have tried using preventDefault, return false as well but no help.

Can any one please help me out with this.

**Comment by taion** [comment]
the _title_ is the toggle-able element, not the heading (you're using `<Panel.Title toggle>`), so there's no reason to expect the click handler on the heading to do much for the title event
