### ISSUE TITLE
Would like to make a contribution!

### ISSUE THREAD

**Issue by ejachang** [react-bootstrap/react-bootstrap#3157]
Hi! I'm looking to make my first contribution and saw that there is help wanted on this project on up-for-grabs.net. Are there any issues or new features that haven't been assigned yet that I could work on? Thank you!

**Comment by taion** [comment]
yup! take a look at any of the issues, esp the "v4" ones, that aren't marked as "Issue taken!"

**Comment by ejachang** [comment]
Thanks! Will do.
