### ISSUE TITLE
[Q/feature request] Is there support for resizeable panels?

### ISSUE THREAD

**Issue by vladp** [react-bootstrap/react-bootstrap#3161]
In my use case, I need one panel on the bottom and 2 sitting on top of the first one.
All need to be resizeable.

I followed this examples for bootstrap 3
https://www.bootply.com/89285  and this
https://codepen.io/barbalex/pen/ogZWNV,    however not I cannot see how this can be implemented in react-bootstrap (because they both rely on bootstrap's java script)

Is there a feature/approach that I could leverage with react-bootstrap ?

thank you

**Comment by KagamiChan** [comment]
They're not relying on BS's JavaScript but jQUery-UI's `resiable`

IMO it's out of RB's scope, take a look at [re-resiable](https://github.com/bokuweb/re-resizable) or some other similar libs

**Comment by vladp** [comment]
ok, thank you @KagamiChan
