### ISSUE TITLE
No spacing when wrapped in ButtonToolBar?

### ISSUE THREAD

**Issue by miriam-z** [react-bootstrap/react-bootstrap#3164]
```
<div className="row">
                    <div className="col-6" align="center">
                        <h5 id="colorID">Colour: {colourName}</h5>
                        <ButtonToolbar>
                            <Button bsStyle="info" onClick={this.handleClickColourGold}>
                                Gold
                            </Button>

                            <Button bsStyle="info" onClick={this.handleClickColourSilver}>
                                Silver
                            </Button>

                            <Button bsStyle="info" onClick={this.handleClickColourBlack}>
                                Black
                            </Button>
                        </ButtonToolbar>
                    </div>
```

<img width="269" alt="screen shot 2018-05-28 at 17 17 43" src="https://user-images.githubusercontent.com/19760229/40620951-191b68e4-629b-11e8-8f98-102ae044c7c3.png">

**Comment by gtwilliams03** [comment]
I think you have to wrap your buttons in ButtonGroups and then wrap the various ButtonGroups inside ButtonToolbars. If you just want spaced Buttons, just wrap them in a div with spaces {‘ ‘} between them.

**Comment by taion** [comment]
right or add `{' '}` in JSX between the buttons

**Comment by sdiemert** [comment]
Just noting that the examples for ButtonToolbar are misleading on this front if @gtwilliams03 is indeed correct. 

See [examples here](https://react-bootstrap.netlify.com/components/buttons/#examples).

**Comment by refactorized** [comment]
Why is this issue closed when the documentation is clearly misleading?

**Comment by jamesw6811** [comment]
Agreed - documentation needs to change.

**Comment by jamesw6811** [comment]
Also, for me wrapping as suggested above does not create spacing either:

```
        <ButtonToolbar><ButtonGroup>
        <Button variant="primary" type="submit">
          Sign In
        </Button>

        <Button variant="secondary" onClick={submitCreateAccountInfo}>
          Create Account
        </Button>
        </ButtonGroup></ButtonToolbar>
```

**Comment by taion** [comment]
The spacing is what upstream TWBS uses. We’d be happy to take a PR here.

**Comment by taion** [comment]
I mean the literal white space in the HTML
