### ISSUE TITLE
v4: css module supports!

### ISSUE THREAD

**Issue by lytc** [react-bootstrap/react-bootstrap#3165]
Do we have plan to support css module in the next major release?

**Comment by taion** [comment]
What does that mean? React-Bootstrap works fine with CSS modules. We're using such a setup right now. You just use `:global` with the TWBS class names.

**Comment by cotwitch** [comment]
In a case that someone is looking for a little deeper "explanation", I'll leave note below. 
I'm not sure if this is "the right solution" (if not, correct me, please, anyone) but it works for me 😄👍:

1. Import global CSS at **application/root level** (in my case, I'm importing bootstrap SCSS in `_app.js` via `import "~/bootstrap/scss/bootstrap.scss"`)
2. Then **at component level**, import CSS module styles (in my case `import styles from "./Header.module.scss"`)
3. So, I want to **overload global bootstrap class** `.navbar-toggler`. To do so, just use following markup **in CSS module**: ```:global(.navbar-toggler) {
  your-overloading-rule: value;
}```

So, it will tell to CSS module parser that specified class **should not** be "locally scoped" (ie. suffixed with class suffix,like: `.navbar-toggler__3gtt4`) but use (unchanged) class name (`.navbar-toggle`) so it will successfully overload global bootstrap value.
