### ISSUE TITLE
Error "Element ref was specified as a string" (only for <Tabs>, only when npm link)

### ISSUE THREAD

**Issue by odrzutowiec** [react-bootstrap/react-bootstrap#3166]
Hello I think this might be a bug in react-bootstrap. Here's repo to reproduce (very minimal, takes 3 minutes to reproduce).  Please HELP

https://github.com/odrzutowiec/react-bootstrap-jest-link-bug

**Comment by taion** [comment]
You can't in general use link with things that have peer dependencies without jumping through hoops. In this case the dependency is on React. See https://github.com/npm/npm/issues/5875.

**Comment by odrzutowiec** [comment]
@taion could you elaborate, I don't really understand. I don't have any peerDeps in this example

**Comment by odrzutowiec** [comment]
Also I don't think that is the case, I tested <Button> and it doesnt produce this error.

**Comment by taion** [comment]
r-b has a peer dep on react, so you can't link it without jumping through hoops. same with any react component libarry
