### ISSUE TITLE
Can we make it easier to remove focus from buttons and maintain good accessibility?

### ISSUE THREAD

**Issue by jfbloom22** [react-bootstrap/react-bootstrap#3168]
<img width="141" alt="p1lim" src="https://user-images.githubusercontent.com/5193247/40685684-eb4da4b8-6362-11e8-9f9b-aff57395cf60.png"><img width="138" alt="nudkl" src="https://user-images.githubusercontent.com/5193247/40685711-ff765a48-6362-11e8-92c3-b2ce2e15820c.png">

Typically developers solve the "focused" look with something like this:
```
.btn:focus {
  outline: none;
}
```
However, this hurts the accessibility of the application.  Below is my ugly solution to this problem and I have to wonder if there is an easier way?  And does it make sense to implement something in React-Bootstrap to help solve this problem?

Desired button functionality:  buttons are focusable by "tabbing" to them.  Return and spacebar keys will click the button.  When clicking the button it does not look "focused".  The button looks depressed while actively clicking or tapping (:active).

My ugly but effective solution:
```
onMouseDown={this.handleClick} 
 onKeyUp={(e) => {if (e.keyCode === 13 || e.keyCode === 32) {this.handleClick()}}}

handleClick(e) {
    if (e) {e.preventDefault()};
}
```

The focusing of a button happens after the MouseDown event, so I prevent that when users click. If I stop there, then the space bar and return key do not "click" the button. I do not preventDefault for the onKeyUp event because then the button continues to look "focused" after clicking somewhere else.

more info: https://stackoverflow.com/questions/19053181/how-to-remove-focus-around-buttons-on-click

**Comment by jquense** [comment]
eventually css will handle this via the `:focus-visible` psuedo selector, in the meantime i don't really consider this a problem. Personally i don't mind the focus ring showing up on clicks and we always style it to something more "on brand" than the browser default. In terms of what RB can do, I don't think there is a great place for something like this in the library since the behavior is really design and app specific.

**Comment by jfbloom22** [comment]
I also personally don't mind the focus ring or some other focus style.  But out of the last 17 clients I have built an app for, most if not all of them asked to remove the focus ring.  I am primarily building enterprise web applications.  I imagine my clients want the buttons to work more like they do in their native desktop applications.   
Will leave this open for a few days to see if anyone else who cares about this or has some thoughts.

**Comment by jquense** [comment]
> see if anyone else who cares about this or has some thoughts.

:) to be clear, i think this is a totally reasonable feature and behavior, just not a good fit for react-bootstrap the library, even If only because it'd probably involve style changes and we have a hard limit at only using what upstream provides for stylesheets

**Comment by jfbloom22** [comment]
I am thinking this might be solved well by an additional prop.  Something like:  `clickFocus={false}`. Which would effectively prevent the focus after mouse clicks, while keeping it around for accessibility devices.

**Comment by mschwartz** [comment]
It doesn't seem right that on a tablet, when you press a button, it remains pressed or highlighted or focused.  It should just animate pressed in, then pop back out.

IMO
