### ISSUE TITLE
Inside PanelGroup a div around Panel will get bsStyle set on it and raise Unknown prop `bsStyle`

### ISSUE THREAD

**Issue by rluiten** [react-bootstrap/react-bootstrap#3169]
I happen to need to have some elements around the Panel inside my PanelGroup and have seen warnings as follows
* Warning: Unknown prop `bsStyle` on <div>

Here is a cut down example of the what I am seeing in my local project.

https://codepen.io/anon/pen/oygQvb?editors=1111

It appears to be because PanelGroup is trying to set bsStyle on children and the child of PanelGroup is not a Panel or a react-bootstrap control.

Not sure if there is any work around this ?
I am not sure if I will get the time to work on a fix at the moment either.

**Comment by rluiten** [comment]
Had a quick look at the code base of Panel Group and it seems fairly clear it sets bsStyle on each child.

Has anyone got any context on why it does this unconditionally ?
Is it possible to do conditionally or remove it ?

The warning I am getting does not appear to affect the styles of the contained panels.
In my project i have a number of tag elements between the PanelGroup and the Panels it contains.
I am using the structure to allow a single accordion panel to show details depending on which row in a grid is active.

https://github.com/react-bootstrap/react-bootstrap/blob/master/src/PanelGroup.js#L118
![image](https://user-images.githubusercontent.com/670472/40944301-9cc717fe-6897-11e8-8a6e-6aef5d460b01.png)

**Comment by veswill3** [comment]
bump. I am having the same issue at the moment and there does not appear to be a workaround. Currently using 0.32.4

**Comment by rluiten** [comment]
Ive used npm patch-package, to remove it in my repository.

I modify the file node_modules/react-bootstrap/es/PanelGroup.js so that the cloneElement call now looks like.

```javascript
````
The diff it generated for my change is
```
patch-package
--- a/node_modules/react-bootstrap/es/PanelGroup.js
+++ b/node_modules/react-bootstrap/es/PanelGroup.js
@@ -136,9 +136,9 @@ var PanelGroup = function (_React$Component) {
       'div',
       _extends({}, elementProps, { className: classNames(className, classes) }),
       ValidComponentChildren.map(children, function (child) {
-        return cloneElement(child, {
+        return cloneElement(child/* , {
           bsStyle: child.props.bsStyle || bsProps.bsStyle
-        });
+        } */);
       })
     );
   };
```
