### ISSUE TITLE
No easy way to learn when modal contents has been rendered

### ISSUE THREAD

**Issue by x-yuri** [react-bootstrap/react-bootstrap#3171]
I've run into it when trying to focus the first form input element. Consider the following code:

```jsx
import React from 'react';
import Button from 'react-bootstrap/lib/Button';
import Modal from 'react-bootstrap/lib/Modal';
import FormGroup from 'react-bootstrap/lib/FormGroup';
import FormControl from 'react-bootstrap/lib/FormControl';

export default class Page extends React.Component {
  constructor(props, context) {
    super(props, context);
    this.state = {
      show: false
    };
  }

  handleShow = () => {
    this.setState({ show: true });
  }

  render() {
    return (
      <div>
        <Button bsStyle="primary" bsSize="large" onClick={this.handleShow}>
          Launch demo modal
        </Button>

        <Modal show={this.state.show}
            animation={false}
            onEnter={() => {
                this.firstInputRef.focus();
            }}
        >
          <Modal.Header closeButton>
            <Modal.Title>Modal heading</Modal.Title>
          </Modal.Header>
          <Modal.Body>
              <form>
                <FormGroup>
                  <FormControl type="text" inputRef={ref => this.firstInputRef = ref} />
                </FormGroup>
              </form>
          </Modal.Body>
          <Modal.Footer>
            <Button>Close</Button>
          </Modal.Footer>
        </Modal>
      </div>
    );
  }
}
```

When `animation={true}`, I can rely on `onEnter`. But if not... I can probably move modal contents into separate component, and focus the first form input element in `componentDidMount()`. But isn't there supposed to be an easier way?

Here's [the archive][archive] with the test app:

```
$ unzip focus-first-input.zip && cd focus-first-input && yarn && yarn start
```

[archive]: https://github.com/react-bootstrap/react-bootstrap/files/2073175/focus-first-input.zip

**Comment by taion** [comment]
render a class component and add a `componentDidMount` hook there

**Comment by x-yuri** [comment]
@taion You mean this?

> But if not... I can probably move modal contents into separate component, and focus the first form input element there in componentDidMount().

Otherwise, I don't understand. Which class component?

The other option I tried is:

```jsx
this.setState({ show: true }, () => {
    this.firstInputRef.focus();
});
```

But that doesn't work too. That must has something to do with `Modal` contents being [initially hidden][modal-mount].

And to make it clear, why not add `onShown` or something...

[modal-mount]: https://github.com/react-bootstrap/react-overlays/blob/master/src/Modal.js#L259

**Comment by taion** [comment]
exactly that. though the modal should auto-focus inputs anyway?

**Comment by x-yuri** [comment]
@taion It autofocuses [itself][autofocus], not inputs.

[autofocus]: https://github.com/react-bootstrap/react-overlays/blob/v0.8.3/src/Modal.js#L504
