### ISSUE TITLE
Modal Does Not Appear On Click

### ISSUE THREAD

**Issue by chasen-bettinger** [react-bootstrap/react-bootstrap#3177]
I am using `"react-bootstrap": "^0.32.1"` and `"react": "^16.3.2"`.

**Goal**
Open a modal on click. 

**What I have done**

`Parent.js`
```
class Parent extends Component {
 constructor() {
  super();
  this.state = { 
    modalVisible: false
  }
 }

 toggleModal = () => {
    this.state.modalVisible
      ? this.setState({
        modalVisible: false
      })
      : this.setState({ modalVisible: true });
  };


 render() {
  <div onClick={() => this.toggleModal()}>Contact Us<div>
  <Modal modalVisible={this.state.modalVisible} />
 }
}
```

`Modal.js`
```
<Modal show={props.modalVisible} />
 ....
</Modal>
```

Here's a video of this in action:

![Bootstrap Issue](https://i.imgur.com/2iAkeZ3.gif)

I receive no errors in the console.

**Comment by chasen-bettinger** [comment]
Removing 

```
<Modal.Dialog >
{children}
</Modal.Dialog>
```

that was inside of my `<Modal>` fixed this problem. Would it be helpful if there was documentation about this?

**Comment by abhishek71994** [comment]
Can I contribute to this issue if its open?

**Comment by taion** [comment]
Go for it! I think this may just be a docs thing, though.

**Comment by abhishek71994** [comment]
@taion So should I head to the website repo and create an issue there?

**Comment by taion** [comment]
This is the website repo, actually. The source code for the website is here.

**Comment by taion** [comment]
BTW, the answer here is "don't use `<Modal.Dialog>` when using `<Modal>`".

**Comment by taion** [comment]
See e.g. https://react-bootstrap.github.io/components/modal/#modals-live.

**Comment by eugenio1590** [comment]
I have resolved this issue using the external library. This is an example of this:

https://codesandbox.io/s/k9n900jx2r?fontsize=14
