### ISSUE TITLE
ProgressBar - how to keep text in the center horizontally?

### ISSUE THREAD

**Issue by jeghers** [react-bootstrap/react-bootstrap#3179]
I've seen recommendations how to do hacks and keep the title text horizontally centered no matter what the value is.  But that is just for bare bootstrap (not React wrappers) using raw HTML and CSS.  Is there a way to do the same using these react component wrappers?

**Comment by taion** [comment]
All the same methods apply – we're rendering the same HTML, so set the CSS appropriately.

**Comment by jeghers** [comment]
Not the same, in raw HTML there are multiple DIVs for the bar and text. The
React wrapper cannot do this.
