### ISSUE TITLE
Let me set the "name" attribute on Input

### ISSUE THREAD

**Issue by nickretallack** [react-bootstrap/react-bootstrap#318]
I'd like to use some Input elements in a form, then gather the form's data like so:

```javascript
var formdata = new FormData(this.refs.myform)
```

Unfortunately, react-bootstrap doesn't set the ```name``` attributes on any of the form fields, so this method yields no data.

It would also be useful if I wanted to submit the form in the traditional way.

**Comment by mtscout6** [comment]
You can do so on the current docs page at: http://react-bootstrap.github.io/components.html#input

Here's an example:

![](http://cl.ly/image/1n0B171i2Z1B/Image%202015-02-27%20at%2011.39.48%20AM.png)

Although you may want to be cautious with which browsers actually support `FormData`: https://developer.mozilla.org/en-US/docs/Web/API/FormData

```
var formdata = new FormData(this.refs.myform)
```

Also, that example will not actually get the form DOM node. Try:

```
var formdata = new FormData(this.refs.myform.getDOMNode());
```

**Comment by jtbennett** [comment]
Newbie question:  Without the name attribute, the event.target coming from onChange doesn't have any way of identifying an input element.  You are recommending ref to do this. But what if I need to access the event target in a parent component?  

How would I do this? I'd rather not write an event handler for every input field.

My code:

TodoPage:
```
onChange(event) {
    this.state.todo[event.target.name] = event.target.value; // error here - event.target.name is undefined.
    this.setState({ todo: this.state.todo });
}

render() {
    return (
        <TodoForm
            todo={this.state.todo}
            onChange={this.onChange} />
    );
}
```

TodoForm:
```
render() {
return (
        <form>
            <Input type="text" ref="foo" value={this.props.todo.foo} onChange={this.props.onChange} />
            <Input type="text" ref="bar" value={this.props.todo.bar} onChange={this.props.onChange} />
            [ other stuff ]
        </form>
    );
}
```

**Comment by taion** [comment]
You _can_ set it. `<Input>` passes it through.

**Comment by jtbennett** [comment]
Deleted my question.   I see that.  Problem is that the Typescript definition for InputProps doesn't have name in it.  Thanks.
