### ISSUE TITLE
Multiple versions of react error when importing a dependency that uses react-bootstrap

### ISSUE THREAD

**Issue by Yahkob** [react-bootstrap/react-bootstrap#3183]
I set up an example repo (https://github.com/Yahkob/reactbsissue). I get the multiple versions of react error if I import a module from npm that comes bundled with react-bootstrap (https://github.com/Yahkob/reactbsissue-dep). Even after setting the alias in webpack I will still get this error. If I understand correctly this is because the module is bundled with react-bootstrap which gets bundled with react@15.x. 

Unless I did something wrong with my webpack aliases I feel like it would make sense to make an alpha version of react-bootstrap that bumps react & react-* dependencies to 16.x. I cloned react-bootstrap and bumped the versions at my work on github/npm enterprise and it at least prevents the errors from breaking the UI. 

Obviously I think just bumping react up to 16.x comes with dangerous side effects if there are breaking changes that need to be refactored in react-bootstrap but I think it is a viable solution temporarily. 

Let me know if this sounds good and I can open a PR you all can publish under alpha

**Comment by taion** [comment]
React is not actually a dependency of this package – it's a peer dependency, which means npm (and Yarn) won't install it for you. Thus you'll get whichever version you specify.

If you're installing the version via npm link, see documentation elsewhere on the caveats with peer dependencies and npm link.

You can find a few other issues in this repo discussing similar things. There's nothing actionable here.

**Comment by Yahkob** [comment]
I looked through issues for a couple days and the only thing I found was webpack aliases which in my case didn't work for me. The only thing that worked for me is what i mentioned - cloning and publishing react-bootstrap with peerDependencies and devDependencies bumped to react 16. 

Are there any issues you can track down that would actually fix my problem I reproduced in the repos I mentioned?

I resolved the issue for myself but took the time to open this issue to help anyone else that might run into this issue. More importantly I made this issue because I couldn't find anything within issues on this repo or google that solved my problem.
