### ISSUE TITLE
Grid Offset Prop not working

### ISSUE THREAD

**Issue by taylerhughes** [react-bootstrap/react-bootstrap#3184]
I'm using 
- "bootstrap": "^4.1.1", 
- "react": "^16.4.1", 
- "react-bootstrap": "^0.32.1"

Can't get any of the Offset props to work. I've started adding them in manually (using class names).

		<Row className="skills-container">
			<Col className="offset-lg-1" xs={12} lgOffset={1} md={6} lg={2}><img className="skill-logo" style={skillLogoStyle} src={html} alt="HTML5 Logo"/></Col>
			<Col xs={12} md={6} lg={2}><img className="skill-logo" style={skillLogoStyle} src={css} alt="HTML5 Logo"/></Col>
			<Col xs={12} md={6} lg={2}><img className="skill-logo" style={skillLogoStyle} src={js} alt="HTML5 Logo"/></Col>
			<Col xs={12} md={6} lg={2}><img className="skill-logo" style={skillLogoStyle} src={react} alt="HTML5 Logo"/></Col>
			<Col xs={12} md={6} lg={2}><img className="skill-logo" style={skillLogoStyle} src={node} alt="HTML5 Logo"/></Col>
		</Row>

Anyone else?

**Comment by taion** [comment]
Make sure you have the Bootstrap v3 CSS.
