### ISSUE TITLE
Progress Bar Progress Not Updating on Edge

### ISSUE THREAD

**Issue by chasen-bettinger** [react-bootstrap/react-bootstrap#3186]
Using: 

`    "react-bootstrap": "0.31.5" `,  `"react": "^16.3.2" ` and edge: `Microsoft Edge 42.17134.1.0`. 

Expected Behavior:

![Expected](https://i.imgur.com/TWqsgms.gif)

Actual Behavior:

![Actual](https://i.imgur.com/XGEeaAe.gif)

The progress bar is not loading.

Here is the relevant code:

`<ProgressBar styleName="progressBar" now={props.progress} />`;

**Comment by mxschmitt** [comment]
Please provide us an example on https://codesandbox.io

**Comment by chasen-bettinger** [comment]
lol?
