### ISSUE TITLE
[Question] Source code for <Dropdown /> base component - what is <Component />?

### ISSUE THREAD

**Issue by ortonomy** [react-bootstrap/react-bootstrap#3188]
On https://github.com/react-bootstrap/react-bootstrap/blob/v0.31.5/src/Dropdown.js#L320

I can see this code in the render function:

```js
  return (
    <Component
      {...props}
      className={classNames(className, classes)}
    >
...
```

 I can't find a reference to ``<Component />`` -- is this some kind of React short hand?

In the props extraction in ``render()``, I can see

```js
const {
      componentClass: Component,
      id,
      dropup,
      disabled,
      pullRight,
      open,
      onSelect,
      role,
      bsClass,
      className,
      rootCloseEvent,
      children,
      ...props
    } = this.props;
```

=> ``componentClass: Component`` -- but it's not clear to me if this is creating the ``Component`` const, or a new const called ``componentClass`` with ``Component`` prop as its value. Can someone help explain?

**Comment by jquense** [comment]
It's restructuring and renaming the identier so it's the equivalent to `const Component = this.props.componentClass`, we assign the prop to an uppercase variable name because can you use it as jsx like: `<Component\>`, upper case is important because he considers lowercase tags to be only "native" or html tags

**Comment by jquense** [comment]
It should be said, that this is allow to allow you to control what tag the dropdown renders as via a prop, the defaultProps show what the default is (a `div` I believe)

**Comment by jquense** [comment]
Sorry I meant destructuring :P phone autocorrected it to the wrong thing

**Comment by ortonomy** [comment]
FYI for anyone coming here with same question, relevant MDN docs are here:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment

> ### Assigning to new variable names

> A property can be unpacked from an object and assigned to a variable with a different name than the object property.

> ```js
> var o = {p: 42, q: true};
> var {p: foo, q: bar} = o;
>  
> console.log(foo); // 42 
> console.log(bar); // true
> ```
