### ISSUE TITLE
Panel.Body is undefined when imported

### ISSUE THREAD

**Issue by rluiten** [react-bootstrap/react-bootstrap#3191]
The code sand box project is a create react app one.

Using `import Panel from 'react-bootstrap'` Panel.Body is undefined.
Using `import Panel from 'react-bootstrap/lib/Panel'` Panel.Body is defined.

Using.

    "react": "16.4.1",
    "react-bootstrap": "0.32.1",
    "react-dom": "16.4.1",
    "react-scripts": "1.1.4"

Example https://codesandbox.io/s/7jzw1xyy66

I did see a previous issues for this, but it was closed as being a version problem, this is the latest react-bootstrap. Screenshot of codesandbox, and the stack trace attached.

![image](https://user-images.githubusercontent.com/670472/42353295-f9f350ae-8102-11e8-8d76-c19c279339a6.png)

```
TypeError
Cannot read property 'Body' of undefined
App
/src/index.js:15:11
  12 | <div>
  13 |   <Panel>
  14 |     outside
> 15 |   <Panel.Body>
     |         ^
  16 |       body
  17 |   </Panel.Body>
  18 |   </Panel>
View compiled
▶ 22 stack frames were collapsed.
evaluate
/src/index.js:22:7
  19 |   </div>
  20 | );
  21 | 
> 22 | render(<App />, document.getElementById('root'));
     |       ^
  23 | 
View compiled
▶ 10 stack frames were collapsed.
```

**Comment by taion** [comment]
that's not the right syntax for importing

```js
import Panel from 'react-bootstrap';
```

takes the default export from `react-bootstrap` and binds it to `Panel`. you want either

```js
import { Panel } from 'react-bootstrap';
import Panel from 'react-bootstrap/lib/Panel';
```

**Comment by BassamHajar** [comment]
Panel#
removed, replaced with Card components
