### ISSUE TITLE
Glyphicons show only empty square 

### ISSUE THREAD

**Issue by sanBastia** [react-bootstrap/react-bootstrap#3192]
i just dont get it, how to show these glyphicons 

package.json
<img width="408" alt="screen shot 2018-07-06 at 11 03 45 am" src="https://user-images.githubusercontent.com/23252753/42359459-493891fc-810c-11e8-9b73-bea1344594f2.png">

index.html
<img width="901" alt="screen shot 2018-07-06 at 11 04 45 am" src="https://user-images.githubusercontent.com/23252753/42359500-71cc94b0-810c-11e8-8511-be9f41514714.png"

Code 
`<NavItem eventKey={2} href="#">
              <Glyphicon glyph="star" />
            </NavItem>`

Result
<img width="279" alt="screen shot 2018-07-06 at 11 06 00 am" src="https://user-images.githubusercontent.com/23252753/42359535-99918212-810c-11e8-8b73-d77fd3ceb828.png">

please help me, thank you

**Comment by jquense** [comment]
Make sure you've include the font files and css!

**Comment by sanBastia** [comment]
@jquense can you show me the example ? isn't CDN enough to take care of that ?

**Comment by jquense** [comment]
it should be, make sure they are being loaded tho in your dev tools. Brower extensions may be blocking them, or you don't have the right html tags setup: https://getbootstrap.com/docs/3.3/css/#overview-doctype

**Comment by TowerX** [comment]
Can you inspect the icon and see if it's getting block or if it's loading as an empty element? That would be helpful in the case your setup is right (css and font files correctly located).
