### ISSUE TITLE
 React does not recognize the `activePage` prop on a DOM element. webpack 3 , react 16.4

### ISSUE THREAD

**Issue by IzaGz** [react-bootstrap/react-bootstrap#3194]
> Warning: React does not recognize the `activePage` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `activepage` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
>     in ul (created by Pagination)

react-bootstrap 0.32.1

**Comment by taion** [comment]
you need to render appropriate pagination items under pagination, not DOM components that receive props they may not be able to handle
