### ISSUE TITLE
Dropdown menu doesn't close when rootCloseEvent="mousedown" in dropdown toggle.

### ISSUE THREAD

**Issue by sachinshettigar** [react-bootstrap/react-bootstrap#3196]
Hi,

I have dropdown toggle implemented with rootCloseEvent="mousedown".
The dropdown menu closes when a mouse down event occurs outside the dropdown.
However when i click the toggle button it doesn't close the dropdown menu.

```
      <Dropdown
          id="dropdown-custom-1"
          onToggle={onToggle}
          rootCloseEvent="mousedown"
        >
          <Dropdown.Toggle>Pow! Zoom!</Dropdown.Toggle>
          <Dropdown.Menu className="super-colors">
            <MenuItem eventKey="1">Action</MenuItem>
            <MenuItem eventKey="2">Another action</MenuItem>
            <MenuItem eventKey="3" active>
              Active Item
            </MenuItem>
            <MenuItem divider />
            <MenuItem eventKey="4">Separated link</MenuItem>
          </Dropdown.Menu>
        </Dropdown>
```

On debugging i found that it was calling the ontoggle function twice, once with isOpen=false and second time with isOpen=true as the parameter.

Below is the codesandbox link with the issue reproduced.
[Code Sandbox](https://codesandbox.io/s/6vm90n0w1k)

**Comment by taion** [comment]
I guess the "root close" thing is triggering on the toggle. I seem to recall this has come up before but I can't find the issue.

**Comment by jquense** [comment]
I don't know that we can support this case internally. Is there a good reason to use onMousedown vs up?

**Comment by sdkevorkian** [comment]
Hello, I'm late to the party but noticed issues with this same behavior. @jquense my use case is that we have a custom Dropdown.Menu with an input box, similar to the one here: https://react-bootstrap.github.io/components/dropdowns/#custom-dropdown-components

If the user clicks in the input, and accidentally drags off the menu (say when highlighting) the menu closes, which is undesirable, and i think a pretty good reason to use onMouseDown. I was able to fix it with adding the useRootClose hook in my customMenu and using the rootCloseEvent prop. However I am also seeing issues with the toggle now.
