### ISSUE TITLE
Panel, PanelGroup, Accordion Collapse Bug/Issue

### ISSUE THREAD

**Issue by ayantalha14** [react-bootstrap/react-bootstrap#3197]
Hello World,

I have an issue with my "react-bootstrap" Panel, Panel Group and Accordion collapse function. Basically, when you click the panel title, for a brief moment the panel collapsing animation is viewed, but a mere second the entire Panel.Body disappears. I have done a lot of research on this, and apparently no other person has gone through such an ordeal. The only fault I can identify is when you observe the event in your console, for the brief period the panel.collapsing class is shown to be initiating, but afterwards it shows returns to its default state. Furthermore, I noticed that the display is not blocked when the panel is collapsed and that the panel though is collapsed doesn't display the Panel.Body.

**This is Before the panel is clicked**
![screenshot 8](https://user-images.githubusercontent.com/40995679/42676738-b487acbe-8692-11e8-8c97-2187ca3b780f.png)

**This is after the panel is clicked**
![screenshot 9](https://user-images.githubusercontent.com/40995679/42676751-c0054434-8692-11e8-90b8-ae4216fc9af5.png)

class EventsPanel extends Component {
  constructor(props) {
    super(props);

    this.state = {
      open: false
    };
  }

  render() {
    return (
      <div className="card bg-white card-events-upcomming">
        <div className="card-body p-0">
          <Panel EventKey="1">
            <Panel.Heading>
              <Panel.Title
                onClick={() => this.setState({ open: !this.state.open })}
              >
                <h4>{this.props.name}</h4>
              </Panel.Title>
            </Panel.Heading>
            <Collapse in={this.state.open}>
              <Panel.Body>
                      //This area is poplulated
              </Panel.Body>
            </Collapse>
          </Panel>
        </div>
      </div>
    );
  }
}

export default EventsPanel;

===================================================================
P.S. It won't make a difference if I add a Panel Group or Accordion, plus I have also tried the Panel.Body collapsible to no avail.

Thanking you for your Support....

**Comment by ayantalha14** [comment]
For anyone with a similar issue, I solved the problem by using 'div' instead on Panel and PanelGroup. Basically I avoided using react-bootstrap and my problem was solved.Nonetheless, if someone finds a reason why react-bootstrap reacted the way it did above, please let me know. The code I used is attached below,

![screenshot 29](https://user-images.githubusercontent.com/40995679/42804393-5a94c150-89c2-11e8-9def-2c52863b91c9.png)

**Comment by aleX8664** [comment]
It seems that the Panel component has been replaced by Card and PanelGroup with CardGroup. I don't know if Accordion was replaced though.

**Comment by taion** [comment]
gone in v1 anyway
