### ISSUE TITLE
When Slide is true it doesn't Auto Slide on load

### ISSUE THREAD

**Issue by simeoncalixte** [react-bootstrap/react-bootstrap#3198]
I am having an issue with implementing the auto slide feature for a controlled Carousel. 
On load when I set slide to "true", the Carosuel component does not automatically begin to slide, in contrast with what the  documentation actually states.  Am i missing something here
Below is my code implementation of the Carousel:

Does the Parent Component activeIndex state overide the slide prop  ,because it needs to be changed? And I need to implement my own version to auto slide?

          

````

<Carousel
            activeIndex={index}///controlled by parent component
            direction={direction}///controlled by parent component
            onSelect={this.handleSelect}///controlled by parent component
            indicators={this.state.indicators}///controlled by parent component
            controls={false}///controlled by parent component
            slide={true}///controlled by parent component
            
          >
              {this.slides()}
</Carousel>
```

**Comment by taion** [comment]
There's no `slide` prop here. You need to set `interval` if you want automatic cycling. If you're controlling `activeIndex`, you'll additionally need to handle `onSelect` in the parent.
