### ISSUE TITLE
Do I really need to not pass onClick when control is disabled as documentation suggests?

### ISSUE THREAD

**Issue by x-yuri** [react-bootstrap/react-bootstrap#3200]
The documentation suggests the following code:

```jsx
      <Button
        bsStyle="primary"
        disabled={isLoading}
        onClick={!isLoading ? this.handleClick : null}
      >
```

From what I can see, it can be rewritten as:

```jsx
      <Button
        bsStyle="primary"
        disabled={isLoading}
        onClick={this.handleClick}
      >
```

Am I missing something? Or the documentation is to be amended?

**Comment by taion** [comment]
For `<SafeAnchor>`, `onClick` won't get called if `disabled` is set. See https://github.com/react-bootstrap/react-bootstrap/issues/2870, though.

**Comment by x-yuri** [comment]
@vinay72 With `href` or without `componentClass` `onClick` wouldn't get called. But with `componentClass` I can render it any way I want. As a `span` for example. And in that case it will.
