### ISSUE TITLE
A way to specify custom className for a button

### ISSUE THREAD

**Issue by x-yuri** [react-bootstrap/react-bootstrap#3205]
I probably can use [`bsStyle`](https://react-bootstrap.github.io/utilities/custom-styles/), but what if I want to customize `primary` style? I'd like to avoid duplicating `primary`'s styles.

Also, there's a mistake in the [docs](https://react-bootstrap.github.io/components/buttons/#buttons-props). It lists `lg`, `large`, `sm`, `small` and so on for possible values of `bsStyle` property.

**Comment by taion** [comment]
Just pass in `className`. Or override the `.btn-primary` class.

**Comment by x-yuri** [comment]
I wonder what made me not [notice][1] [that][2]...

[1]: https://github.com/react-bootstrap/react-bootstrap/blob/v0.32.1/src/Button.js#L61
[2]: https://github.com/react-bootstrap/react-bootstrap/blob/v0.32.1/src/Button.js#L69
