### ISSUE TITLE
Disable Button inside Modal until input values are filled.

### ISSUE THREAD

**Issue by bhgjmorton** [react-bootstrap/react-bootstrap#3206]
Hi there,
Im using react-bootstrap for a Modal popup and am using it to fill out a form to create an object. Is it possible to make my "Create" button disabled until a dropdown value and the two input fields are selected/filled?

"<Modal show={this.state.ShowModal} onHide={this.HandleClose}>
                <Modal.Header closeButton>
                    <Modal.Title>Test Run Creation</Modal.Title>
                </Modal.Header>
                <Modal.Body>
                    <div>Select a Test Definition to use: <div style={{ paddingLeft: "200px" }}> {testDefDropdown}</div></div><br />
                    <div>User Name:<div style={{ paddingLeft: "150px" }}> <input type='text' id='ModalUser' placeholder='Enter your name' /></div></div><br />
                    <div>Revoke Duration:(Min)<div style={{ paddingLeft: "150px" }}><input type='text' id='ModalRevoke' placeholder='Enter revoke duration' /> minutes</div></div>
                </Modal.Body>
                <Modal.Footer>
                    <Button bsStyle='success' onClick={() => { this.CreateTestRun() }}>Create</Button>
                    <Button bsStyle='danger' onClick={this.HandleClose}>Close</Button>
                </Modal.Footer>
            </Modal>"
So I want my close button 'disabled' until those three fields are selected and filled.

**Comment by taion** [comment]
There's nothing React-Bootstrap specific about this. Consider using something like React Formal here.

**Comment by bhgjmorton** [comment]
That actually looks like itll suit my needs perfectly. Thanks a ton!
