### ISSUE TITLE
FormControl component has problems creating the options when used as a select

### ISSUE THREAD

**Issue by EliaMelfior** [react-bootstrap/react-bootstrap#3210]
A select component with options should be displayed as shown in the image below:   
![image](https://user-images.githubusercontent.com/13088640/43591533-f4f875e6-9649-11e8-9279-5a950c67ea9e.png)
But it actually is displayed differently, with the options being wider.   
![image](https://user-images.githubusercontent.com/13088640/43591566-05851702-964a-11e8-9a7b-ba12fc763b53.png)

Maybe the default behavior should be not letting child options have a width that is bigger than the select.

**Comment by taion** [comment]
This is just how TWBS styles these by default. It's a CSS issue, not an issue of the JS here.

**Comment by EliaMelfior** [comment]
Indeed, it is the default behaviour of bootstrap, but is it right?

**Comment by jquense** [comment]
It doesn't look right to me, but I don't think bootstrap can do much about it, styling options for selects are pretty limited
