### ISSUE TITLE
Lines missing from table 

### ISSUE THREAD

**Issue by bngo97** [react-bootstrap/react-bootstrap#3211]
My table renders with missing lines. Cases of vertical and horizontal lines. 

My code:
`<BootstrapTable data={this.state.filteredData}>
          <TableHeaderColumn dataField="none" dataFormat={indexN} isKey={true} hidden>Index</TableHeaderColumn>
          {Object.entries(this.state.data[0]).map(function([key,value]) {
            return <TableHeaderColumn width='175' dataField={key}>{key}</TableHeaderColumn>
          })}
        </BootstrapTable>`

![screen shot 2018-08-02 at 10 54 49 am](https://user-images.githubusercontent.com/22105689/43601937-6b69dbc2-9643-11e8-881a-1718f275522d.png)

**Comment by jquense** [comment]
I think this is the wrong repo. Bootstrap Table is a separate project not run by us!
