### ISSUE TITLE
Tooltip component does not work if the button is disabled

### ISSUE THREAD

**Issue by JulsRicketti** [react-bootstrap/react-bootstrap#3214]
I need to use a Tooltip button to display a message when a button is disabled.
This did not work appropriately as sometimes it would appear, sometimes it wouldn't and when it did, it would get stuck on the screen.

If I were to enable the button, it would work as expected.

I also ran this on the Tooltip example code in the documentation, and it did not work there either.

[Here is a simple sandbox, showing the problem. ](https://codesandbox.io/s/py644jwlk0)

You can also recreate this using the code from [the OverlayTrigger section](https://react-bootstrap.github.io/components/tooltips/#tooltips-overlay-trigger). Just disable one of the buttons shows the problem.

If there a way around this that perhaps was not made clear or that I missed?

Thanks!

**Comment by taion** [comment]
dupe https://github.com/react-bootstrap/react-bootstrap/issues/2428
