### ISSUE TITLE
Syntax Error when running "yarn start"

### ISSUE THREAD

**Issue by isian8814** [react-bootstrap/react-bootstrap#3219]
My node version is v6.11.5

Here is the output of my console.

yarn start
yarn run v1.9.4
$ yarn --cwd www run develop
$ gatsby develop
success delete html and css files from previous builds — 0.011 s
error We encountered an error while trying to load your site's gatsby-config.js. Please fix the error and try again.

  Error: /Users/owh072/Documents/COFI Projects/ReactJS/react-bootstrap-master/www/gatsby-config.js:12
    ...require('.babelrc.js'),
    ^^^
  SyntaxError: Unexpected token ...

  - v8-compile-cache.js:226 NativeCompileCache._moduleCompile
    [www]/[v8-compile-cache]/v8-compile-cache.js:226:18

  - v8-compile-cache.js:172 Module._compile
    [www]/[v8-compile-cache]/v8-compile-cache.js:172:36

  - v8-compile-cache.js:159 require
    [www]/[v8-compile-cache]/v8-compile-cache.js:159:20

  - get-config-file.js:27
    [www]/[gatsby]/dist/bootstrap/get-config-file.js:27:22

  - next

  - get-config-file.js:54 getConfigFile
    [www]/[gatsby]/dist/bootstrap/get-config-file.js:54:27

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by jquense** [comment]
Yes you need at least node 8.9 I believe, to run the docs locally

**Comment by isian8814** [comment]
Thanks that works.
