### ISSUE TITLE
When is the next release?

### ISSUE THREAD

**Issue by mlucool** [react-bootstrap/react-bootstrap#3224]
Hi,

https://github.com/react-bootstrap/react-bootstrap/commit/f6864f272f5d568dd6e5b414134a117420aa9974 makes a pretty big difference in terms of bundle size (in my use case it went from 123kb to 43kb). Is there something holding up releasing this? If not, can this repo please be re-released?

Thanks!

**Comment by taion** [comment]
Soon, I hope.

That said, have you seen https://react-bootstrap.github.io/getting-started/introduction#commonjs? You should not be using the top-level import if you can help it.

**Comment by jquense** [comment]
@taion if you have moment let's publish something, I also hope to get a beta out for the v4 support

**Comment by taion** [comment]
released v0.32.2

**Comment by taion** [comment]
it is on master; the default branch is different
