### ISSUE TITLE
How to have custom feedback icons for each validation state?

### ISSUE THREAD

**Issue by jfbloom22** [react-bootstrap/react-bootstrap#3225]
I am trying to use custom icons for the feedback.  I see in the documentation how to do a custom icon, but how do I specify a different icon for each validation state?

```
        <FormControl.Feedback type="valid">
          <FontAwesomeIcon icon={['far', 'check']} />
         </FormControl.Feedback>
         <FormControl.Feedback type="invalid">
          <FontAwesomeIcon icon={['far', 'times']}  />
         </FormControl.Feedback>
```

I added the "type" prop hoping that might help, but it does not.

**Comment by taion** [comment]
The current API doesn't really support this. Perhaps this would work with a functional child that passes in the current validation state. Would you be up for taking a stab at a PR?

**Comment by jfbloom22** [comment]
Sure I will take a stab at it.  But please don't wait on me.  I am not sure how much time I will have to through at this. 
Quick question, I looked at the feedback component and it looks like what I am trying to do is supported in v4:  https://github.com/react-bootstrap/react-bootstrap/blob/v4-support/src/Feedback.js
With the v4 component I should be able to do something like:

```
const CustomFeedback = ({type}) => {
  if (type === 'valid'){
    return <FontAwesomeIcon icon={['far', 'check']} />
  } else if (type === 'invalid'){
    return <FontAwesomeIcon icon={['far', 'times']}  />
  } else {
    return null;
  }
}

<FormControl.Feedback>
          <CustomFeedback />
</FormControl.Feedback>
```

https://github.com/react-bootstrap/react-bootstrap/blob/master/src/FormControlFeedback.js
It looks like I just need to change line 61 from:
```
return React.cloneElement(child, {
      ...elementProps,
      className: classNames(child.props.className, className, classes)
    });
```
to: 
```
return React.cloneElement(child, {
      ...elementProps,
      ...bsProps,
      className: classNames(child.props.className, className, classes)
    });
```

Then I expect I will start receiving the `type` prop in my CustomFeedback component.
