### ISSUE TITLE
Document error: &larr; should be displayed as ↞

### ISSUE THREAD

**Issue by JaDogg** [react-bootstrap/react-bootstrap#3226]
I suggest using something like `{"↞"}`

https://react-bootstrap.github.io/components/pagination/

<img width="879" alt="screen shot 2018-08-10 at 9 48 29 am" src="https://user-images.githubusercontent.com/498642/43948394-9de586a6-9c82-11e8-94a3-373cef078b86.png">

**Comment by rrs94** [comment]
It's similar to [3118](https://github.com/react-bootstrap/react-bootstrap/issues/3118), I was able to render it correctly on my computer: 
<img width="450" alt="screen shot 2018-08-14 at 12 47 39 am" src="https://user-images.githubusercontent.com/7096948/44073860-aec0c586-9f5b-11e8-820e-a39d3ec5a1f2.png">
 It seems like they fixed it but haven't updated the documentation.

**Comment by taion** [comment]
this was resolved
