### ISSUE TITLE
Labels not sizing correctly

### ISSUE THREAD

**Issue by caseyahlan** [react-bootstrap/react-bootstrap#3228]
According to the [documentation](https://react-bootstrap.github.io/components/label/), labels should resize to their enclosing tag, like so:
![label](https://user-images.githubusercontent.com/24910873/44050557-20e3af9a-9eec-11e8-9cef-8c5ff4d4d7ac.PNG)

This isn't working for me. My code is: 
` <h1> fail <Label bsStyle=fail > FAIL </Label> </h1>`

but my labels appear like so:
![fail](https://user-images.githubusercontent.com/24910873/44050597-417bc97c-9eec-11e8-836e-1f21f4750dd8.PNG)

How can I achieve the desired state?

**Comment by taion** [comment]
This is purely a CSS thing; check that you're not using e.g. CSS that behaves differently from that of stock TWBSv3.
