### ISSUE TITLE
controlled versus uncontrolled nav

### ISSUE THREAD

**Issue by mteichtahl** [react-bootstrap/react-bootstrap#323]
Im having an interesting issue where by when I run the example code for controlled navs everything's works fine. However the uncontrolled nav fails to switch between the tabs. 

As they both use the same child components I'm stuck as to why this may be happening. 

I'm hoping for some guidance or troubleshooting assistance to identify and resolve the root cause of this difference in behaviour.

**Comment by mteichtahl** [comment]
Im still looking into this though have made little progress. any guidance would be appreciated

**Comment by trentgrover-wf** [comment]
Can you provide some example code that demonstrates the issue?

**Comment by mteichtahl** [comment]
I have uploaded the sample code which can be found at

https://gist.github.com/mteichtahl/60b852e0d8e91959f3b5 <https://gist.github.com/mteichtahl/60b852e0d8e91959f3b5>


i have also included a grab of the issue Im seeing



-----------------------------------------------
Marc Teichtahl
marc@teichtahl.com
Ph: +61 434 100 259
http://www.teichtahl.com

**Comment by trentgrover-wf** [comment]
I don't think this is an issue with react-bootstrap code.  Your gist is concatenating some react-bootstrap tabPane and tabArea code in with your application JSX in an odd way.  Why not just require these 2 components into the code?

**Comment by mteichtahl** [comment]
I have noticed, that an uncontrolled carousel seems to have the same problem.
-----------------------------------------------
Marc Teichtahl
marc@teichtahl.com
Ph: +61 434 100 259
http://www.teichtahl.com

**Comment by mtscout6** [comment]
Can't say that I follow your gist. Are you still running into this issue or can you provide a cleaned up gist?

**Comment by AlexKVal** [comment]
I'm closing it.
