### ISSUE TITLE
Cannot find module '@babel/runtime/core-js/object/entries' from 'bootstrapUtils.js'

### ISSUE THREAD

**Issue by shirbr510** [react-bootstrap/react-bootstrap#3234]
I assume this is related to https://github.com/react-bootstrap/react-bootstrap/issues/3231 but basically, my unit tests on jenkins fail with this error while local development is working properly.

**Comment by shirbr510** [comment]
it seems like my local package is version 0.32.1 while jenkins is installing  0.32.2

currently falling back to 0.32.1 until this is fixed and stable again

**Comment by mreishus** [comment]
My project doesn't use babel 7 (it isn't released yet), it's till on babel 6.  Updating from 0.32.1 to 0.32.2 makes my project pull in `+"@babel/runtime@^7.0.0-beta.42":` and `npm test` no longer works with this error.

**Comment by shirbr510** [comment]
@mreishus I'm on the same boat with you buddy :)

**Comment by shirbr510** [comment]
this seems like a broader discussion about the issue: https://github.com/react-bootstrap/react-bootstrap/issues/3235
