### ISSUE TITLE
Documentation links on home page do not work

### ISSUE THREAD

**Issue by A-E-Jones** [react-bootstrap/react-bootstrap#3237]
Documentation link on https://react-bootstrap.github.io/ home page doesn't work, nor does search box. Tested in Microsoft Edge and Chrome 68.

**Comment by dominusbelli** [comment]
https://react-bootstrap.github.io/getting-started/introduction/
It does work if you click links and then refresh, I guess there's something wrong with hydrate server-side on docs, and the console confirms this

**Comment by A-E-Jones** [comment]
Thanks for that suggestion, it works around the issue I was seeing. I'm also seeing the hydrate issue you mention when I enable the JS console, so at least it's reproducible. :-)
