### ISSUE TITLE
Cannot find module from babel-runtime (core-js/object/entries)

### ISSUE THREAD

**Issue by vinz51** [react-bootstrap/react-bootstrap#3238]
Hello,

i install react-bootstrap with the version 0.32.2, and i got an error each time i tried to launch my app.

```
Browserify Error { Error: Cannot find module '@babel/runtime/core-js/object/entries' from '/node_modules/react-bootstrap/lib/utils' }
```

I saw that you reached this new version since 3 days ago, do you have news about this problem ?

**Comment by xprazak2** [comment]
We hit this too in our [tests](https://travis-ci.org/theforeman/foreman/jobs/418104521):

```
● Test suite failed to run

    Cannot find module '@babel/runtime/core-js/object/entries' from 'bootstrapUtils.js'
      
      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:179:17)
      at Object.<anonymous> (node_modules/react-bootstrap/lib/utils/bootstrapUtils.js:13:39)
```

**Comment by shirbr510** [comment]
duplicate: https://github.com/react-bootstrap/react-bootstrap/issues/3234
I've also found a temporary solution
