### ISSUE TITLE
Hosted Website Down

### ISSUE THREAD

**Issue by luketherrien** [react-bootstrap/react-bootstrap#3241]
Navigating to the documentation throws the following error:
```
TypeError: window.docsearch is not a function
```

**Comment by jquense** [comment]
no seeing that, maybe you have an extension blocking the angolia search script?

**Comment by luketherrien** [comment]
I'm not getting that behavior on the version of Chrome I'm running (67.0.3396.99). It may be a problem with the version of Firefox I was using this morning; will report back.

**Comment by luketherrien** [comment]
Sorry for the very late response... I learned that our corporate proxy is blocking some JS being served up by jsDelivr. The problem is not on your end!
