### ISSUE TITLE
Make keyboard trap for Modal (accessibility purpose)

### ISSUE THREAD

**Issue by zoharbob** [react-bootstrap/react-bootstrap#3243]
Hello, 

Is there a way to make keyboard trap (pressing tab would focus on the elements inside the modal only) for the Modal Component for accessibility purpose? 

I tried to add the prop `enforceFocus: true` to the Modal component but it didn't work.

**Comment by jquense** [comment]
Not sure what you mean, the modal already works this way...focus cycles through the modal to the browser chrome and back to the model, just like if it was the only content on the page

**Comment by zoharbob** [comment]
The focus cycles outside the modal also, for accessibility purpose it's not right, 
you can check the following example for keyboard trap on modal:
[](http://udacity.github.io/ud891/lesson2-focus/07-modals-and-keyboard-traps/solution/index.html)

**Comment by jquense** [comment]
what do you mean "outside the modal"? Focus is trapped within the document, but allows cycling out of the browser tab (to url bar) and back into the document. You can see from the examples that it's not possible to focus anything else in the browser window. 

The example you've linked is _less correct_ than our implementation, according to the research we've done, including consulting some a11y experts. It's not _wrong_ but it's not ideal, the react-bootstrap behavior mimicks native dialogs as well: https://fiddle.jshell.net/oh93rzb6/show/light/
