### ISSUE TITLE
Grid Giving Me Issues

### ISSUE THREAD

**Issue by vigneshprasad** [react-bootstrap/react-bootstrap#3244]
![image](https://user-images.githubusercontent.com/35379937/44550748-c172b380-a742-11e8-8928-5b5c9888f057.png)
```
<Grid>
        <Col style={howItWorksStyle} xs={12} sm={4} md={2} lg={2}>
		<figure>
			<Row>
				<img alt="img1" src={img1} />
			</Row>
			<Row>
				<Col style={textAlign} md={12} sm={12} xs={6}> 
					<figcaption style={captionStyle}> Market survey, guided by professionals </figcaption>
				</Col>	
			</Row>
		</figure>
	</Col>
</Grid>
```
I've been running into this issue with many grids in my code. This is an image example along with the code for each of the elements. I'm using the typical create react app setup and running into these issues.

**Comment by rrs94** [comment]
Hi! Is that the code for each of the elements? If yes, you shouldn't use more than one grid, think of the grid system as a container for all the rows in your layout, so you could have something like this: 

```
<Grid>
  <Row>
    <Col>
      <Element />
    </Col>
    <Col>
      <Another Element />
    </Col>
  </Row>
</Grid>
```

Let me know if that helps, also it would be great if you could upload a working demo so that we can see what's actually going on.

**Comment by vigneshprasad** [comment]
Hey sorry I didn't copy the code right. I only have one grid element. I just didn't think it was sensible to have the whole code so I snipped it. Could you give me some advice on how I can upload a working demo?

**Comment by rrs94** [comment]
Hi, perhaps upload the full file that you've been using so I can try to reproduce and see if it's a problem with ``react-bootstrap``.
