### ISSUE TITLE
Warning: unmet peer dependency

### ISSUE THREAD

**Issue by Skagevang** [react-bootstrap/react-bootstrap#3246]
I upgraded to version 0.32.3 because of the new API for Panel. But yarn gives me this:

```warning "react-bootstrap > enzyme-adapter-react-16@1.2.0" has unmet peer dependency "enzyme@^3.0.0".```

**Comment by rrs94** [comment]
Hi! I was able to reproduce the issue with ``0.32.3``, updated to ``0.32.4`` and the warning disappeared, maybe you can try that.
