### ISSUE TITLE
Modal does not show

### ISSUE THREAD

**Issue by tudrare555** [react-bootstrap/react-bootstrap#3248]
I am using this to create a modal:

`import React, { Component } from 'react';
import { Button, Form, Modal } from 'react-bootstrap'

class AddModal extends Component {
    constructor(props) {
        super(props);

        this.handleShow = this.handleShow.bind(this);
        this.handleClose = this.handleClose.bind(this);

        this.state = {
            show: this.props.show,
        }
    }

    handleClose() {
        this.setState({ show: false });
    }

    handleShow() {
        this.setState({ show: true });
    }

    render() { 
        return (
            <Modal show={this.state.show} onHide={this.handleClose}>
                <Modal.Dialog>
                    <Modal.Header>
                        <Modal.Title>Modal title</Modal.Title>
                    </Modal.Header>

                    <Modal.Body>One fine body...</Modal.Body>

                    <Modal.Footer>
                        <Button>Close</Button>
                        <Button bsStyle="primary">Save changes</Button>
                    </Modal.Footer>
                </Modal.Dialog>
            </Modal>
        );
    }
}
 
export default AddModal;`

But, in the end I  have just a line, not a modal:
[https://imgur.com/ILKj3HZ](url)

I should mention that, if I click on screen, the modal closes.

What should I do?

**Comment by jquense** [comment]
seems like you might have a css issue, or something conflicting with the bootstrap styles (or forgot to include them?)

**Comment by BrentLabasan** [comment]
I'm experiencing the same issue.\ with Modals

I'm able to select the elements in Developer Tools, and they have a width and height. But for some reason, they're invisible. Setting the elements to z-index: 99999 didn't help.

The modal was in a sub-component, so I tried to move the modal to the topmost React component, but that didn't help.

**Comment by jquense** [comment]
if someone can put together a runnable repo we can troubleshoot we can check it out, but we aren't seeing this on the docs site

**Comment by tudrare555** [comment]
I solved it removing the Modal.Dialog tags. I don't know why, but it worked.

**Comment by StuartMartinho** [comment]
Hi,

I added the prop animation={false} and the modal appeared but with the background in black.
Then i just changed the background color to transparent and it worked.

Try it and u will see.

**Comment by YChebotaev** [comment]
Hi! I'm experience same issue, `animation={false}` approach not work for me. Help, please.

**Comment by jquense** [comment]
please put together a working reproduction of the bug your seeing otherwise we can't help thanks!

**Comment by YChebotaev** [comment]
I get it! Just remove `<Modal.Dialog></Modal.Dialog>` section completely from markup.

**Comment by bnovc** [comment]
Few years later, but same problem seems to persist in current versions/today. Using animation={false} fixes it for me also, but its not intuitive.
