### ISSUE TITLE
npm release v0.13.0 is raw source code

### ISSUE THREAD

**Issue by Dashed** [react-bootstrap/react-bootstrap#325]
npm release v0.13.0 is raw source code. Thus, I can't `require('react-bootstrap')`.

At the moment only `v0.12` is viable.

**Comment by mtscout6** [comment]
:+1: 

This could be cleaned up and automated with a pre-publish script as I proposed in #292.

**Comment by mtscout6** [comment]
@Dashed 0.13.1 should be good to go :)
