### ISSUE TITLE
About the component <MenuItem> can not nest the <Link> tag BUG

### ISSUE THREAD

**Issue by 755966092** [react-bootstrap/react-bootstrap#3262]
Since the <MenuItem> component is an <a> tag after rendering, the <Link> tag cannot be nested within the <MenuItem> component for the jump route, and the route to the `href` attribute of <MenuItem> is refreshed. Page, I think this is a bug, it should be improved;

## code
```
<MenuItem eventKey={index} key={index} active={item.active}>
          <Link to={item.link} className="route-link">
            {item.text}
          </Link>
</MenuItem>
```

## Error message
```
 Warning: validateDOMNesting(...): <a> cannot appear as a descendant of <a>.
```

**I hope to reply soon**

**Comment by taion** [comment]
Again, there's no bug here; you need to use a link container

**Comment by 755966092** [comment]
thinks
