### ISSUE TITLE
Tabs Issue: componentDidMount of each tabs are getting called even if the tab is not selected

### ISSUE THREAD

**Issue by rupesh-jaiswal** [react-bootstrap/react-bootstrap#3265]
I have 4 tabs and in each of the the tabs contents i am doing api calls in componentDidMount function.
componentDidMount of each tabs are getting called even if I am not click on that tabs

I guess the issue is that all the tabs content are present in the dom and just displayed when the tabs are clicked. But this is approach will have a performance issue as well. It would be better if the tabs contents are added to the dom only when that tab is clicked and hence all the lifecycle methods will also be triggered again. Your thoughts on this?

**Comment by jquense** [comment]
Yes all tabs are mounted by default since this is how bootstrap works. You can use the mountOnEnter prop on the tab panes or conditionally render them yourself by controlling the tab container
