### ISSUE TITLE
`<Nav navbar>` Error in Console

### ISSUE THREAD

**Issue by DBombay** [react-bootstrap/react-bootstrap#3266]
On our application's home page header, the console is logging the following error:

<img width="1665" alt="screen shot 2018-09-10 at 10 05 40 am" src="https://user-images.githubusercontent.com/4355236/45302451-603c3580-b4e1-11e8-8511-5c54c6138c02.png">

In case that's too small:

```
Warning: Received `true` for a non-boolean attribute `navbar`.

If you want to write it to the DOM, pass a string instead: navbar="true" or navbar={value.toString()}.
```

I followed the warning message's suggestion and changed the `prop` to `<Nav navbar={true}>` and `<Nav navbar{true.toString()}>`.

Both returned the following error:

<img width="1666" alt="screen shot 2018-09-10 at 10 11 04 am" src="https://user-images.githubusercontent.com/4355236/45302661-e5274f00-b4e1-11e8-815c-47abc20a389b.png">

or:

```
Warning: Failed prop type: Invalid prop `navbar` of type `string` supplied to `Nav`, expected `boolean`.
```

A) Is there a way to pass the prop to the Nav component that doesn't throw an error?

if not

B) How can I disable the warning?

**Comment by jquense** [comment]
Looks like you are rendering a plain html `nav` element, not the react-bootstrap `Nav` component

**Comment by DBombay** [comment]
Here's an excerpt from that .js file
```
import React from "react";
import Media from "react-media";
import {Collapse, Navbar, NavbarToggler, NavbarBrand, Nav, NavLink, Button} from 'reactstrap';

...

      <Nav navbar='true'>
        <Navbar fixed='top' expand="lg" color="primary" className='justify-content-between'>
          <div>
            <Media query="(max-width: 991.98px)">
              {matches =>
                matches ? (
                  <Button size="sm" color="secondary" href={`/start`}>Go</Button>
                ) : (
                  <Button size="lg" color="secondary" href={`/start`}>Go</Button>
                )
              }
            </Media>
          </div>
```

**Comment by jquense** [comment]
Thats `reactstrap` different library :P

**Comment by DBombay** [comment]
*facepalm*

Should've double-checked the repo... Sorry about that
