### ISSUE TITLE
Bug,FormControl with type number,does not prevent letters input,in Firefox

### ISSUE THREAD

**Issue by sbk201** [react-bootstrap/react-bootstrap#3268]
[Live Editor](https://codesandbox.io/s/m515xvqymy)

Environment:
Firefox 62.0

react 16.4.2
react-dom 16.4.2
react-scripts 1.1.4
react-bootstrap 0.32.4

How to test:
Open the live editor with firefox
Type letters in it

Expected Result:
In Firefox,it should prevent users to type letters on it other than number.
When typing numbers,it should logs the number in the input.
Exactly the same in Chrome.

Actual Behavior:
In Firefox,it allows users to put letters on it.
Typing letter,also won't trigger onChange function.

Workaround:
I can use default type="text",but for mobile user,the keyboard show up will be with letters.
If I keep using type="number",onChange won't get triggered,so I have no control over it,cannot check the user input,or strict if user type letter.

**Comment by jquense** [comment]
that's unfortunately the browser behavior for number inputs, you'll have to apply a regex or clamp the values yourself. RB doesn't have any logic in the form controls we only render native inputs with the bootstrap classes
