### ISSUE TITLE
A modal with different Modal.Body

### ISSUE THREAD

**Issue by susuwatari2** [react-bootstrap/react-bootstrap#3271]
I want to have 2 steps on a modal, what is the better way to do it?

First, show a Cancel and Next buttons on Modal.Footer.
Then, click on the Next button will change the Modal.Body context and show a Back and Apply buttons on the Modal.Footer
Lastly, click on the Apply button and close the modal

My current code, same as the docs

<Modal bsSize="large" show={!!changingRows.length} onHide={this.cancelEdit}>

    <Modal.Header closeButton></Modal.Header>

    <Modal.Body>content 1 </Modal.Body>

    <Modal.Footer>
        <Button onClick={this.cancelDelete}>Cancel</Button>
        <Button onClick={this.changeRows}>Apply</Button>
    </Modal.Footer>

</Modal>

What I want 

<Modal bsSize="large" show={!!changingRows.length} onHide={this.cancelEdit}>

    <Modal.Header closeButton>Title</Modal.Header>

    <Modal.Body>content 1 </Modal.Body>

    <Modal.Footer>
        <Button onClick={this.cancelDelete}>Cancel</Button>
        <Button onClick={this.previewRows}>Next</Button>
    </Modal.Footer>

</Modal>

<Modal>

    <Modal.Header closeButton>Title</Modal.Header>

    <Modal.Body>content 2 </Modal.Body>

    <Modal.Footer>
        <Button onClick={this.back}>Back</Button>
        <Button onClick={this.changeRows}>Apply</Button>
    </Modal.Footer>

</Modal>

**Comment by jquense** [comment]
you can put whatever you want in there, i'd do a switch like below

```jsx
<Modal.Header closeButton>Title</Modal.Header>

<Modal.Body>{step1 ? content1 : content2}</Modal.Body>

<Modal.Footer>
    <Button onClick={this.back}>Back</Button>
    <Button onClick={this.changeRows}>Apply</Button>
</Modal.Footer>
```

**Comment by susuwatari2** [comment]
But I have different modal.body and modal.footer. Can you explain more in this case?
