### ISSUE TITLE
Modal - How to distinguish between closing by clicking on backdrop and on closeButton?

### ISSUE THREAD

**Issue by NERDYLIZARD** [react-bootstrap/react-bootstrap#3276]
I'm writing the application that has an editor inside the modal. I'd like to distinguish whether the close event is fired by clicking `backdrop` or by clicking on `closeButton`. 

My aim is when users click on the close button, they intend to exit the editor. The editor, therefore, clears all data and closes the modal. On the other hand, when users click on the backdrop, it is considered as an accidental exit of modal. The editor retains the data and populate them when the modal is opened again.

Could you suggest a way to distinguish how the modal is closed?

**Comment by taion** [comment]
You'll get an `onBackdropClick` event when the backdrop is clicked. Just pass in a handler for that and implement the relevant logic there.

**Comment by NERDYLIZARD** [comment]
I tried. Nothing was fired.
```
import React from 'react';
import Modal from 'react-bootstrap/lib/Modal';

export class EditorModal extends React.Component {
  render () {
    <Modal 
    	show={isOpenedWithModal}	
    	onBackdropClick={() => console.log('backdrop')}
    />	
  }
}
```
The console logged nothing.
