### ISSUE TITLE
Document: broken link

### ISSUE THREAD

**Issue by gentarok** [react-bootstrap/react-bootstrap#3280]
The “Get started” link on the top page is broken.
https://react-bootstrap.netlify.com/

**Comment by taion** [comment]
works fine for me?

**Comment by gentarok** [comment]
Really?
It doesn't work for me right now.

![image01](https://user-images.githubusercontent.com/26685009/45696358-68aa0580-bb9e-11e8-8fb2-e20c192c3f7b.png)
![image02](https://user-images.githubusercontent.com/26685009/45696362-6b0c5f80-bb9e-11e8-9bb7-af88193ff2fd.png)

**Comment by gentarok** [comment]
Yes, works fine now.
It was fixed yesterday.

https://github.com/react-bootstrap/react-bootstrap/commit/85327d3b86c911d06ad2b6ea0648ec82a5c7a2c9#diff-4f6481783b8c01deb00387b1edb7e79dR115
