### ISSUE TITLE
Modal - onBackdropClick does not trigger any event.

### ISSUE THREAD

**Issue by NERDYLIZARD** [react-bootstrap/react-bootstrap#3282]
How to listen to `onBackdropClick` event in `<Modal/>`?
```javascript
import React from 'react';
import Modal from 'react-bootstrap/lib/Modal';

export class EditorModal extends React.Component {
  render () {
    <Modal 
      show={isOpenedWithModal}	
      onBackdropClick={() => console.log('backdrop')} />	
  }
}
```
The console logged nothing.

**Comment by abdullahtariq1171** [comment]
hey @NERDYLIZARD  there is no prop like `onBackdropClick` (see docs for available props https://react-bootstrap.netlify.com/components/modal/#modal-props)

From my understanding, you are looking for `onExit`

**Comment by NERDYLIZARD** [comment]
@taion who is a member said there is though. [Issue#3276](https://github.com/react-bootstrap/react-bootstrap/issues/3276)

**Comment by jquense** [comment]
There is a backdrop click event on the underlying react-overlays modal, however because of how markup and styles work for the bootstrap modal work it doesn't actually fire because technically only the outer dialog element is clicked.

**Comment by NERDYLIZARD** [comment]
Do you have any suggestion for the workaround?

**Comment by jquense** [comment]
unfortunately i can't think of a workaround...we should maybe expose the event to `onHide` like we do for dropdown's so you can tell why something was closed
