### ISSUE TITLE
Modal with single line of content appears stacked on 'second' modal

### ISSUE THREAD

**Issue by bentayloruk** [react-bootstrap/react-bootstrap#329]
When I create a modal that has only a single line of content in it, I get this weird looking stacked modal.  Has anyone else seen this?  I've not smart enough (yet) in the HTML CSS area to know whether this is an issue or it's something I've done (although I always bet on me!).  Clicking the bottom modal edge results in the modal being dismissed.

![rb-modal](https://cloud.githubusercontent.com/assets/189409/5650283/e2799f8e-9694-11e4-98b8-ced70380129b.png)

This is what the DOM looks like for the modal.  *Not sure why the `input` appears unclosed, but it is closed in the JSX.*

    <div class="modal-dialog" data-reactid=".o.1.0">
        <div class="modal-content" data-reactid=".o.1.0.0">
            <div class="modal-header" data-reactid=".o.1.0.0.0">
                <button class="close" data-reactid=".o.1.0.0.0.0" type=
                "button">×</button>

                <h4 class="modal-title" data-reactid=".o.1.0.0.0.1">Edit the
                promo name</h4>
            </div>

            <div class="modal-body" data-reactid=".o.1.0.0.1:0">
                <input data-reactid=".o.1.0.0.1:0.0" value="2_SimpleDiscount">
            </div>

            <div class="modal-footer" data-reactid=".o.1.0.0.1:1">
                <button class="btn btn-default" data-reactid=".o.1.0.0.1:1.0"
                type="button">Cancel</button><button class="btn btn-primary"
                data-reactid=".o.1.0.0.1:1.1" type="button">Save</button>
            </div>
        </div>
    </div>

Any thoughts or help much appreciated!

**Comment by trentgrover-wf** [comment]
what's the JSX that you're using to generate this?  can you replicate the problem by modifying the JSX snippet in 1 of the modal examples here: http://react-bootstrap.github.io/components.html#modals?

**Comment by bentayloruk** [comment]
@trentgrover-wf thanks for the response.  I had not realised you could edit the code on those examples.  This is awesome!  I will try and replicate tomorrow.

**Comment by bentayloruk** [comment]
I've fixed this by simplifying the controls and mixin I'm using for launching the modal and it now works fine.  Unfortunately, I don't know what was causing the issue and I'm not sure if I ever will know (unless it happens again).  Thanks again for the response.
