### ISSUE TITLE
closeLabel not working in 1.0.0-beta.1 

### ISSUE THREAD

**Issue by abdullahtariq1171** [react-bootstrap/react-bootstrap#3290]
**Bug or feature request?** Bug

**Version**: 1.0.0-beta.1  

---------------------------------------------------------------------------------------

From https://react-bootstrap.netlify.com/components/alerts 
It says `Alert` accepts a parameter `closeLabel` but it is not working.

```
 <Alert variant='primary' dismissible={true} closeLabel="foo">
   hello alert
 </Alert>
```

<img width="846" alt="screen shot 2018-09-24 at 2 16 56 pm" src="https://user-images.githubusercontent.com/5623766/45944772-c73f0b80-c004-11e8-8546-3f30ef8e418e.png">

---------------------------------------------------------------------------------------

I looked in the code and found we are using `CloseButton` inside `Alert` for this. 

```
class CloseButton extends React.Component {
  render() {
    const { label, onClick } = this.props;
    return (
      <button type="button" className="close" onClick={onClick}>
        <span aria-hidden="true">&times;</span>
        <span className="sr-only">{label}</span>
      </button>
    );
  }
}
```

See we are not using `label` and rendering `&times;`. 

Also we are using `CloseButton` inside `ModalHeader` ([docs](https://react-bootstrap.netlify.com/components/modal/#modal-header-props)) and similar issue there it as well.

Happy to fix and send PR if someone could confirm this. Thanks

**Comment by jquense** [comment]
close label is the accessible text that's used to label the button, since &times; is not necessarily clear to folks using assistive tech to browse the page. The label is rendered but off screen so it's not visible. The close button doesn't allow changing the visible rendered look, since this button is very specific

**Comment by abdullahtariq1171** [comment]
aah, I see. 
I think the docs are a little misleading, it describes it as "Sets the text for alert close button.". If we could add this `accessible text` bit,  that could be helpful. What do you say?

**Comment by jquense** [comment]
sure, happy to take a PR

**Comment by abdullahtariq1171** [comment]
Fix merged in v4-support
