### ISSUE TITLE
Dropdown not rendering properly

### ISSUE THREAD

**Issue by neihcnim** [react-bootstrap/react-bootstrap#3292]
Somehow, the dropdown is not rendering properly. Might I know where I went wrong?

![dropdown](https://user-images.githubusercontent.com/41287490/46125282-ffd82280-c25a-11e8-8480-44fec522f2c0.PNG)

In my router file, I call render on my .jsx file. 
`
router.get('/modelsearch', function(req,res) {
        res.render('Dd');
})
`
Here's the code in my .jsx file.
`
import { DropdownButton , MenuItem } from 'react-bootstrap';
import React from 'react';
import { UncontrolledDropdown, DropdownToggle, DropdownMenu, DropdownItem } from 'reactstrap';

class Dd extends React.Component {
        render () {
  return (
    \<DropdownButton title="Dropdown" id={1}>
     \<MenuItem href="#books">Books</MenuItem>
      \<MenuItem href="#podcasts">Podcasts</MenuItem>
      \<MenuItem href="#">Tech I Like</MenuItem>
      \<MenuItem href="#">About me</MenuItem>
      \<MenuItem href="#addBlog">Add a Blog</MenuItem>
    \</DropdownButton>
  );
}
}

export default Dd
`

**Comment by jquense** [comment]
Looks like you've not included the case file

**Comment by neihcnim** [comment]
What case file needs to be included? Thanks.

**Comment by jquense** [comment]
CSS* file, sorry. Please read the docs for more info
