### ISSUE TITLE
Error loading maxcdn CSS - Failed to find a valid digest in the 'integrity' attribute for resource 

### ISSUE THREAD

**Issue by FrozenKiwi** [react-bootstrap/react-bootstrap#3294]
When loading CSS from CDN, Chrome pops error message

> localhost/:17 Failed to find a valid digest in the 'integrity' attribute for resource 'https://maxcdn.bootstrapcdn.com/bootstrap/latest/css/bootstrap.min.css' with computed SHA-256 integrity 'LA89z+k9fjgMKQ/kq4OO2Mrf8VltYml/VES+Rg0fh20='. The resource has been blocked.

This is from the link provided in "Getting Started": 
```
<!-- Latest compiled and minified CSS -->
 <link
   rel="stylesheet"
   href="https://maxcdn.bootstrapcdn.com/bootstrap/latest/css/bootstrap.min.css"
   integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
  crossorigin="anonymous"
>
```

Workaround - remove the integrity tag

**Comment by chiwoojo** [comment]
having same issue.

**Comment by musab** [comment]
+1

**Comment by leonardocregis** [comment]
+1

**Comment by jquense** [comment]
update the checksum https://getbootstrap.com/docs/4.2/getting-started/introduction/#css

**Comment by sachinrr147** [comment]
If we already setup output bootstrap file while setup preprocessor css then we dont need to use **integrity** and **crossorigin** , you just remove it from bootstrap.css file to execute it properly, then it will work.
It has the perfect solution.
