### ISSUE TITLE
Additional responsive view size between xs and sm (suggestion)

### ISSUE THREAD

**Issue by anddero** [react-bootstrap/react-bootstrap#3295]
Playing around with the width of a website built on react-bootstrap v3, it can be seen that the size "xs" for columns in a grid has quite a large variation: can be 300px (usually not smaller), can be 480px or even 767px.

Usually, for view-size **xs**, form inputs take the whole width of the page to support very small screen sizes. But for view-size **sm**, if the form input size spans, let's say, 6 columns instead of 12, there is a huge variation in change between **xs** and **sm**. From about 767px to 768/2=384px for the form input field.

My suggestion is adding another view size between xs and sm, let's say, in the range of 480px to 767px, for example. It would not break any existing builds, if users ignore it, but might be a useful feature for many.

**Comment by taion** [comment]
we don't control this; this is purely a matter of the underlying framework. you can set the breakpoints as you wish, but we can't change bootstrap semantics
