### ISSUE TITLE
Remove Collapse need for an extra div

### ISSUE THREAD

**Issue by tkrotoff** [react-bootstrap/react-bootstrap#3302]
This is a known issue: Collapse requires an extra `<div>` in some cases.

I believe this can be improved. With my app, using reactstrap's [Collapse.js](https://github.com/reactstrap/reactstrap/blob/6.4.0/src/Collapse.js) there is no need for an extra `<div>`.

It seems to me the interesting bit is here:
https://github.com/reactstrap/reactstrap/blob/da10db02699a68c511da4a79b126db316ffc3974/src/Collapse.js#L46-L48

```JS
function getHeight(node) {
  return node.scrollHeight;
}
```

The "equivalent" in React-Bootstrap is:
https://github.com/react-bootstrap/react-bootstrap/blob/cd47c897871954b5c5be818cbf8b22ae2b51ea1c/src/Collapse.js#L21-L31

MDN documentation about [Element.scrollHeight](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollHeight):
> a measurement of the height of an element's content, including content not visible on the screen due to overflow

FYI Material-UI implementation (I did not test it with my app): https://github.com/mui-org/material-ui/blob/dbd67aa892a4e9885d763fcb0d1f6c1691fbf763/packages/material-ui/src/Collapse/Collapse.js
It seems to use [Element.clientHeight](https://developer.mozilla.org/en-US/docs/Web/API/Element/clientHeight).

Maybe there is a way to get rid of the extra `<div>`.

**Comment by jquense** [comment]
I don't think changing the height calculation would ultimately solve the problem. The reactstrap version isn't written with the same fidelity to the upstream bootstrap, which uses the same calculation we have here.
