### ISSUE TITLE
ToggleButtons with Popover don't render correctly.

### ISSUE THREAD

**Issue by tizzle** [react-bootstrap/react-bootstrap#3303]
When wrapping a ToggleButton (in ToggleButtonGroup) in an OverlayTrigger, the ToggleButton is rendered incorrectly. The input in the ToggleButton is displayed as a regular text input.

The markup looks like this:

```
<ToggleButtonGroup
  name="options"
  defaultValue={1}
>
  <ToggleButton value={1}>One</ToggleButton>
  <ToggleButton value={2}>Two</ToggleButton>
  <OverlayTrigger
    trigger="hover"
    placement="top"
    overlay={
      <Popover id="popover">
        Check this info.
      </Popover>
    }
  >
    <ToggleButton value={3}>Three</ToggleButton>
  </OverlayTrigger>
  </ToggleButtonGroup>
```

See a [reproduction in this codepen](https://codepen.io/tizzle/pen/GYZBKR).

It seems when the ToggleButton is rendered it does not get the `type="radio"` parameter passed down.

**Comment by qualitymanifest** [comment]
If you add `type="radio"` to the problem `ToggleButton` it will render properly, but then your ToggleButton inside the OverlayTrigger will not toggle to `active` when clicked. So, along with `type="radio"` not being passed down, `name="options"` isn't passed down either.

**Comment by taion** [comment]
looks like this is because `OverlayTrigger` forwards injected props to the overlay rather than to the child. i'm not sure this is the best approach, but it would be a breaking change to change this. you may want to consider using the "custom overlay" API here

**Comment by tizzle** [comment]
Hi @jquense,

that's a nice workaround, thanks a lot.

From my point of view this can be closed now.
Thanks for all your efforts!

Till
