### ISSUE TITLE
Safari:  iPhone 7 Modal component is not getting focus with autofoucs / enforceFocus 

### ISSUE THREAD

**Issue by dinesh-here** [react-bootstrap/react-bootstrap#3305]
Hi,

The modal component is not transferring focus when it's open accessibility mode. even though autofoucs & enforceFocus  is enabled.

I have tested in the below stackblitz url
https://react-hs3aio.stackblitz.io

React version: 16.5.0
React-bootstrap : 0.32.4
IPhone 7

**Comment by mxschmitt** [comment]
Closed due it's quite stale. If it's still reproducible in the latest version, fell free to create a new issue.
