### ISSUE TITLE
Question: React Bootstrap 4 installation npm vs yarn

### ISSUE THREAD

**Issue by flexpeace** [react-bootstrap/react-bootstrap#3306]
According to this documentation https://react-bootstrap.github.io/getting-started/introduction, you simply run npm install --save react-bootstrap to get react-bootstrap.  

However, on the project Github main page https://github.com/react-bootstrap/react-bootstrap, it is stated that _**yarn is the our package manager of choice here**_. 

**My Question then is:** 

- How do l install react-bootstrap 4 using npm? I am used to npm and l do not want to mix it with yarn?
- Also, is it possible to just drop components into a project, for example Alert.js without installing the whole react-bootstrap 4 library?

**Comment by jquense** [comment]
You can use either interchangably for installing RB, npm or yarn. If you are contributing to RB i.e. working on the code base directly then yarn is recommended for installing the dependencies in the RB repo.

There isn't any way to install just one component, but you you can important only one, limiting want code makes it into your bundles. See the getting started guide
