### ISSUE TITLE
alignRight in Dropdown Menu not working when inside the Navbar

### ISSUE THREAD

**Issue by mewben** [react-bootstrap/react-bootstrap#3310]
The dropdown menu in the following code does not alignRight when inside the Navbar.
It works however when outside.
Same issue with NavDropdown.

```jsx
<DropdownButton
  alignRight
  title="Dropdown right with long long text"
  id="dropdown-menu-align-right"
>
  <Dropdown.Item eventKey="1">Action</Dropdown.Item>
  <Dropdown.Item eventKey="2">Another action</Dropdown.Item>
  <Dropdown.Item eventKey="3">Something else here</Dropdown.Item>
  <Dropdown.Divider />
  <Dropdown.Item eventKey="4">Separated link</Dropdown.Item>
</DropdownButton>
```

**Comment by jsrhome** [comment]
@jquense thanks for the quick response, and the excellent effort on Bootstrap 4 support.  But I'm not sure how #3338 fixes this problem, since it doesn't change DropdownButton.  I had to change DropdownButton to forward the alignRight property to DropdownMenu.

**Comment by jquense** [comment]
it'll fix it because `alignRight` can be passed to the Dropdown, but before this fix it was ignored, and only used from the Menu.

**Comment by jsrhome** [comment]
Thanks for the explanation.  Will this be published as an npm update to try it out?  I tried making a similar change locally and it didn't seem to fix the problem.

**Comment by razvan100** [comment]
Hi,

  was this fixed? I experience same issue https://stackoverflow.com/questions/57260868/react-bootstrap-navdropdown-alignright-not-working

**Comment by BenMorel** [comment]
Same issue here. Any feedback?

**Comment by poveilleux** [comment]
I does not seem to be fixed, however, I was able to make it work with the following piece of code. The `as={NavLink}` gives the proper styling to the Dropdown.Toggle.
```typescript
<Navbar.Collapse className="justify-content-end">
  <Nav>
    <Dropdown alignRight>
      <Dropdown.Toggle id="user-dropdown" as={NavLink}>
        John Doe
      </Dropdown.Toggle>

      <Dropdown.Menu>
        <Dropdown.Item>Sign out</Dropdown.Item>
      </Dropdown.Menu>
    </Dropdown>
  </Nav>
</Navbar.Collapse>
```

**Comment by randerson57261** [comment]
This is not working for me:
```
    <Navbar fixed="top" variant="dark" className="px-5" expand="md">
      <Container fluid>
        <Navbar.Brand href="#home">
          <img src={logo} className="d-inline-block align-top" alt="logo" />
        </Navbar.Brand>
        <Navbar.Brand>Argo Database</Navbar.Brand>
        <Navbar.Toggle aria-controls="responsive-navbar-nav" />
        <Navbar.Collapse id="responsive-navbar-nav" className="justify-content-end">
          <Nav>
            <NavDropdown alignRight title="Floats">
              <NavDropdown.Item href="index">Deployed</NavDropdown.Item>
              <NavDropdown.Item href="floats_predeployment">Predeployment</NavDropdown.Item>
              <NavDropdown.Item href="floats_tracking">Tracking</NavDropdown.Item>
              <NavDropdown.Item href="sensor_qc">Sensor QC</NavDropdown.Item>
              <NavDropdown.Item href="float_serial_no">Serial Numbers</NavDropdown.Item>
            </NavDropdown>
            <NavDropdown alignRight title="Data" id="basic-nav-dropdown">
              <NavDropdown.Item href="profile_explorer">Profile Explorer</NavDropdown.Item>
              <NavDropdown.Item href="map">Map</NavDropdown.Item>
              <NavDropdown.Item href="latest_profiles">Latest Profiles</NavDropdown.Item>
              <NavDropdown.Item href="cohort">All Profiles</NavDropdown.Item>
              <NavDropdown.Item href="compare_latest_profiles">
                Compare Latest Profiles
              </NavDropdown.Item>
            </NavDropdown>
          </Nav>
        </Navbar.Collapse>
      </Container>
    </Navbar>
```

**Comment by RezaGhx** [comment]
> I does not seem to be fixed, however, I was able to make it work with the following piece of code. The `as={NavLink}` gives the proper styling to the Dropdown.Toggle.
> 
> ```ts
> <Navbar.Collapse className="justify-content-end">
>   <Nav>
>     <Dropdown alignRight>
>       <Dropdown.Toggle id="user-dropdown" as={NavLink}>
>         John Doe
>       </Dropdown.Toggle>
> 
>       <Dropdown.Menu>
>         <Dropdown.Item>Sign out</Dropdown.Item>
>       </Dropdown.Menu>
>     </Dropdown>
>   </Nav>
> </Navbar.Collapse>
> ```

is this working right now?
cause seems it doesn't.
https://codesandbox.io/s/relaxed-pike-thrnz8?file=/src/App.js
