### ISSUE TITLE
Write id="something" get an error 

### ISSUE THREAD

**Issue by akramsameer** [react-bootstrap/react-bootstrap#3311]
when ignore writing id it give me an error that is there multiple input with the same id in the dom 

and when i give it an id it give me the following error 
Warning: `controlId` is ignored on `<FormControl>` when `id` is specified.

**Comment by taion** [comment]
it sounds like you have multiple `<FormControl>`s with the same `controlId`; specify a unique one for each component

**Comment by IkramELMAACHI** [comment]
You should write controlId not just id

**Comment by IkramELMAACHI** [comment]
I don't think you need to write id because formcontroll already has an id in the formgroup with controllId.
