### ISSUE TITLE
Dropdown.Toggle

### ISSUE THREAD

**Issue by frederikhors** [react-bootstrap/react-bootstrap#3312]
I need to use React-Bootstrap 4 custom `Dropdown`: I don't need a `<button>`, I need a custom `<div>` instead.

Following this doc: https://react-bootstrap.netlify.com/components/dropdowns/#custom-dropdown-components I understood that I only can use a new `class CustomToggle extends React.Component...`, right?

Really?

We can't have something like this code below?

```js
<UncontrolledDropdown className='some class' inNavbar>
  <DropdownToggle nav>
    <div>My div</div>
  </DropdownToggle>

  <DropdownMenu className='some class'>
    <div>My menu</div>
  </DropdownMenu>
</UncontrolledDropdown>
```

**Comment by taion** [comment]
Use the `as` prop on `Dropdown.Toggle`. The full custom thing is only if you need more customization than that.

**Comment by frederikhors** [comment]
Yes, I know I have to use the `as` prop. What I'm suggesting is to avoid create a new element using only, directly the `children` way, like this:

```js
<UncontrolledDropdown className='some class' inNavbar>
  <DropdownToggle nav>
    <div>My div</div>
  </DropdownToggle>

  <DropdownMenu className='some class'>
    <div>My menu</div>
  </DropdownMenu>
</UncontrolledDropdown>
```

Is this already possible?

Now the default is `<Button/>`, or am I wrong?

**Comment by jquense** [comment]
Yes it's possible use the `as` prop on the drop-down toggle component, you can look at the docs for navdropdown to see how it renders not-a-button as well

**Comment by taion** [comment]
It's just `<DropdownToggle as="div">`. Though note that it's sort of weird to do this for something that is semantically a button.
