### ISSUE TITLE
Updating from 0.31.3 to 0.32.4 breaks on prod

### ISSUE THREAD

**Issue by H-a-w-k** [react-bootstrap/react-bootstrap#3315]
Hey. I get a react error on prod which i don't get on dev. A minified react error 185.
I am still using webpack 3 and babel 6. Can this be an issue? Is it a breaking change or should it actually work with older versions of babel and webpack, and it's just the code which need to be changed.
I would like to have the new panels, so it would be nice to go back to 0.32.0 at least.
But if I can't be sure which parts of the code is influenced, I must go all the way back.

**Comment by taion** [comment]
Please post a repro.

**Comment by H-a-w-k** [comment]
Seems like the uglifyjs-webpack-plugin 1.1.1 was too old. Looks like it's working with 1.3.0
