### ISSUE TITLE
Support `flip` on dropdowns

### ISSUE THREAD

**Issue by ShaileshPrajapati-BTC** [react-bootstrap/react-bootstrap#3317]

**Comment by taion** [comment]
you could do something like this yourself with the underlying primitives (popper) but it’s not part of the intended bootstrap api

**Comment by ShaileshPrajapati-BTC** [comment]
@taion it's working in jquery and other bootstraps API it's not working in React only

**Comment by jquense** [comment]
Flip should already be supported. Maybe I broken it accidentally?

**Comment by jquense** [comment]
oops
