### ISSUE TITLE
OverlayTrigger with Popover in overlay throw Warning: Failed prop type: Invalid prop `outOfBoundaries` ...

### ISSUE THREAD

**Issue by Daarien** [react-bootstrap/react-bootstrap#3328]
Warning: Failed prop type: Invalid prop `outOfBoundaries` of type `boolean` supplied to `Popover`, expected `function`.
    in Popover (created by Context.Consumer)
    in Transition (created by Fade)
    in Fade (created by InnerPopper)
    in InnerPopper (created by Context.Consumer)
    in Popper (created by Overlay)
    in WaitForContainer (created by Portal)
    in Portal (created by Overlay)
    in Overlay (created by WaitForContainer)
    in WaitForContainer (created by ForwardRef(withContainer(Overlay)))
    in Overlay (created by OverlayTrigger)

**Comment by smallstepstoday** [comment]
I created a [repo](https://github.com/smallstepstoday/popover.git) that corroborates the error.

**Comment by SailingSteve** [comment]
I just dropped the example code onto my page and reproduced the problem.  
https://react-bootstrap.netlify.com/components/overlays/#overlay-trigger    

Another minor issue about that demo code is that it uses `placement="right-start"` which I don't think is correct anymore.
