### ISSUE TITLE
yarn start exception when running react-bootstrap after a fresh git clone

### ISSUE THREAD

**Issue by eladlevy** [react-bootstrap/react-bootstrap#3329]
when running `yarn start` after `yarn run bootstrap` I get the following error:

```
...
info bootstrap finished - 4.791 s

error UNHANDLED REJECTION

  Error: ./public/sorted-assets.json: ENOENT: no such file or directory, open './public/sorted-assets.json'
  
  - render-page.js:4445 Object.readFileSync
    /Users/elad/projects/react-bootstrap/www/public/render-page.js:4445:22
  ...
```

I fixed it by creating a mock `sorted-assets.json` file in public directory. The commit that caused that issue was : [docs: fix link, sorted assets](https://github.com/react-bootstrap/react-bootstrap/commit/85327d3b86c911d06ad2b6ea0648ec82a5c7a2c9)

I think the problem is because `public` dir is in .gitignore file and most of the maintainers has this file already from somewhere. 

How should I permanently fix this for the future? Move sorted-assets.json outside of public directory? Or maybe public directory shouldn't be git ignored?

**Comment by McSam27** [comment]
+1 - also have this issu

**Comment by yorch747** [comment]
+2 - also have this issue

**Comment by yorch747** [comment]
I have "fixed it" by removing or comment 'gatsby-plugin-sorted-assets' plugin at gatsby-config.js file
`plugins: [
    //'gatsby-plugin-sorted-assets',
    {
      resolve: 'gatsby-mdx',
      options: {
        defaultLayout: require.resolve('./src/layouts/ApiLayout'),
        mdPlugins: [remarkSlug],
      },
    } ...`
