### ISSUE TITLE
Redux Compatible Navs

### ISSUE THREAD

**Issue by innotivity** [react-bootstrap/react-bootstrap#3334]
Noting ahead of time I just may be messing up.... apologies if that is the case.  

It does not appear that the Nav system integrates smoothly with redux and router.  When I used the NavItems as suggested, since it is an achor it did a full page load on every click, thus clearing out any loaded state into Redux.  I was able to work around this by surrounding the NavItems with LinkContainers from Router.  

If this is a legitimate issue, I don't mind helping to resolve it.  But I figured it would be best to at least note it in an Issue in case it is just me being stupid.  Again.  

Thanks for the phenomenal library.  5 out of 5 stars.  

Regards, 
DB

**Comment by taion** [comment]
You are supposed to use something like react-router-bootstrap to integrate with React Router.
