### ISSUE TITLE
0.13.2 Release

### ISSUE THREAD

**Issue by mtscout6** [react-bootstrap/react-bootstrap#334]
Contains pull requests

- #262
- #298 
- #302 
- #316 
- #321

**Comment by mtscout6** [comment]
Pushed to npm and to sibling npm repo

**Comment by mtscout6** [comment]
And just finished updating the sibling bower repo

**Comment by mtscout6** [comment]
I'm not sure if there's anything else to do with the bower repo aside from pushing the repo. Bower experts can you weigh in on that? Is it working for you?

**Comment by cmwelsh** [comment]
I upgraded to 0.13.2 in my `bower.json` file and installed/tested the new version successfully.

**Comment by mtscout6** [comment]
Thanks for testing it out for me. I also just updated the docs! So, I think that's a wrap.
