### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by ksarlou** [react-bootstrap/react-bootstrap#3344]
Hello,

I have a problem installing the new version of react-bootstrap which targets Bootstrap 4 and I saw that you fixed it in #3331

I was wondering what is your release cycle in order we get those changes while installing the library.

Thanks in advance!

**Comment by SebTM** [comment]
@ksarlou Can you test again and give feedback/close the issue if fixed? There are two new releases which should include your mentioned change :)
