### ISSUE TITLE
Rendering <Context> directly is not supported  when upgraded to React 16.6

### ISSUE THREAD

**Issue by Richard87** [react-bootstrap/react-bootstrap#3347]
Hi, I just upgraded to React 16.6 and got this error in my console:

```
Warning: Rendering <Context> directly is not supported and will be removed in a future major release. Did you mean to render <Context.Consumer> instead?
    in Nav (created by Context.Consumer)
    in Uncontrolled(Component) (at src/index.js:127)
    in div (created by Context.Consumer)
    in Transition (created by Collapse)
    in Collapse (created by Context.Consumer)
    in NavbarCollapse (created by Context.Consumer)
    in nav (created by Navbar)
    in Navbar (created by Uncontrolled(Navbar))
    in Uncontrolled(Navbar) (at src/index.js:127)
    in div (created by Row)
    in Row (created by Context.Consumer)
    in div (created by Container)
    in Container (created by Context.Consumer)
    in NavContainer (at Page.js:31)
```

For this component:
```jsx
const NavContainer = ({children}) => {
    return (<Container>
            <Row className="justify-content-md-center">
                <Navbar>
                    <Navbar.Toggle/>
                    <Navbar.Collapse>
                        <Nav className="mb-auto">
                            {children}
                        </Nav>
                    </Navbar.Collapse>
                </Navbar>
            </Row>
        </Container>
    )
}
export default NavContainer
```

What can I do?

**Comment by hbliang** [comment]
+1

**Comment by jquense** [comment]
We've got to fix it, no workaround. If anyone wants jump in and send over a PR we'd happily accept

**Comment by DrogoNevets** [comment]
I updated and now get the following error....
`Rendering <Context.Consumer.Consumer> is not supported and will be removed in a future major release. Did you mean to render <Context.Consumer>` instead?

anyone else getting this?

**Comment by dspacejs** [comment]
What can we do as a workaround until the fix is published?

**Comment by studiad** [comment]
Now what can i do?

**Comment by LasithaPrabodha** [comment]
It was not fixed in the latest version 1.0.0-beta.2

**Comment by LasithaPrabodha** [comment]
I received a new beta version yesterday. But I can still see this warning in the console. react v16.5.2.

> Warning: Rendering <Context.Consumer.Consumer> is not supported and will be removed in a future major release. Did you mean to render <Context.Consumer> instead?

**Comment by lq3297401** [comment]
Same problem here, the whole error message is:
Warning: Rendering <Context.Consumer.Consumer> is not supported and will be removed in a future major release. Did you mean to render <Context.Consumer> instead?

**Comment by chandanaccure** [comment]
Same problem for me as well.

**Comment by eparizzi** [comment]
Same problem here. Waiting for a fix.

**Comment by Arpit1989** [comment]
Same problem.

**Comment by zeyad-belal** [comment]
make sure you import the provider right not the context
for me i fixed it by destructruing my import because i had the context and my custom provider in the same file
so
 import {AuthContextProvider} from "myfile"
instead of 
 import AuthContextProvider from "myfile"

**Comment by zeyad-belal** [comment]
make sure you import the provider right not the context
for me i fixed it by destruct ruing my import because i had the context and my custom provide in the samer file
so
 import {AuthContextProvider} from "mypath"
instead of 
 import AuthContextProvider from "mypath"

**Comment by ronit49gupta** [comment]
@zeyad-belal 
It worked for me, Thanks a lot.
