### ISSUE TITLE
How to dismiss a popover from code

### ISSUE THREAD

**Issue by davidrojo** [react-bootstrap/react-bootstrap#3351]
Hello.

I want to show a popover to confirm an operation, with a submit button and a cancel button. I want the cancel button to dismiss the popover but I've not been able to figure what code to use in the onClick action to do it.

This is the example I want to accomplish:

![captura de pantalla de 2018-10-25 17-11-31](https://user-images.githubusercontent.com/1050749/47510857-49775580-d879-11e8-9fdf-d4fdc1b36662.png)

And this is the code I have currently:

```
const popoverDelete = (
  <Popover
    rootClose
    className="popover-over-modal"
    title="Delete payment"
  >
    <p>Are you sure to delete this payment?</p>
    <div className="fl">
      <Button bsStyle="default" className="fl-grow">Cancel</Button>
      <div className="mr-1" />
      <Button bsStyle="danger" className="fl-grow">Delete</Button>
    </div>
  </Popover>
);

return (
  <OverlayTrigger
    trigger="click"
    placement="bottom"
    overlay={ popoverDelete }
  >
    <span className="fa fa-trash" />
  </OverlayTrigger>
);
```

I've also tried to use Overlay instead of OverlayTrigger:

```
<span className="fa fa-trash" onClick={ (event) => this.setState({ showPopover: false, target: event.target }) } />
<Overlay
  show={ this.state.showPopover || false }
  target={ this.state.target || null }
  placement="bottom"
  container={ this }
  containerPadding={20}
>
  <Popover
    id={`popover_payment-${payment.id}`}
    className="popover-over-modal"
    title="Eliminar pago"
  >
    <p>¿Está seguro de eliminar este pago?</p>
    <div className="fl">
      <Button bsStyle="default" className="fl-grow" onClick={() => { this.setState({ showPopover: false }) }}>Cancelar</Button>
      <div className="mr-1" />
      <Button bsStyle="danger" className="fl-grow">Eliminar</Button>
    </div>
  </Popover>
</Overlay>
```

But in this case I am receiving an error of the show parameter at OverlayTrigger, I don't know why because I am using Overlay and not importing or using OverlayTrigger at any point:

```
Warning: Failed prop type: Invalid prop `show` of value `false` supplied to `OverlayTrigger`, expected one of [null].
    in OverlayTrigger (created by PaymentRow)
```

I am currently using react-bootstrap 0.32.4.

Thanks.

**Comment by kishan143-jaiswal** [comment]
Facing with the same problem ,cant able to dismiss popover on button click 
  <OverlayTrigger
                trigger="click"
                key='top'
                placement='top'
                container={this}
                target={i + 1}
                ref="trigger"
                rootClose
                overlay={<Popover id={`popover-positioned-top`} className={'comment-pophover'}>
                 
                    <div>
                        <div className="c-input-outer">
                            <i className="mm-icon">MM</i>
                            <input name="comment" id="comment" title="Comment" placeholder="Write your Comments....." value={this.state.comment} onChange={this.handleChange} />
                        </div>
                        {this.state.isError ? <span>Please enter valid message</span> : null}
                        <button type="button" id="cancel" title="Cancel" className="cancle-btn">Cancel</button>
                        <img id="emoji" title="Emoji" src={smile} className="smile-icon" />
                        <button type="button" id="post" title="Post comment" className="post-btn" onClick={() => this.postComment(file)}>Post</button>
                    </div>
                </Popover>}
            >
                <button type="button" id="comment" title="Add comment" className="ico-button" >
                    <i className="icomoon icon-comments f24"></i> Comment</button>
            </OverlayTrigger>

    postComment = () => `{`
            this.refs.trigger.hide()
      }
i have added like this way , everthing is perfect but i have just tried to close on button click its not happening

**Comment by taion** [comment]
We don't currently support specifying `show` for `<OverlayTrigger>`. If you need to directly control shown state, use `<Overlay>` directly.

**Comment by akhi9** [comment]
> Facing with the same problem ,cant able to dismiss popover on button click
> <OverlayTrigger
> trigger="click"
> key='top'
> placement='top'
> container={this}
> target={i + 1}
> ref="trigger"
> rootClose
> overlay={<Popover id={`popover-positioned-top`} className={'comment-pophover'}>
> 
> ```
>                 <div>
>                     <div className="c-input-outer">
>                         <i className="mm-icon">MM</i>
>                         <input name="comment" id="comment" title="Comment" placeholder="Write your Comments....." value={this.state.comment} onChange={this.handleChange} />
>                     </div>
>                     {this.state.isError ? <span>Please enter valid message</span> : null}
>                     <button type="button" id="cancel" title="Cancel" className="cancle-btn">Cancel</button>
>                     <img id="emoji" title="Emoji" src={smile} className="smile-icon" />
>                     <button type="button" id="post" title="Post comment" className="post-btn" onClick={() => this.postComment(file)}>Post</button>
>                 </div>
>             </Popover>}
>         >
>             <button type="button" id="comment" title="Add comment" className="ico-button" >
>                 <i className="icomoon icon-comments f24"></i> Comment</button>
>         </OverlayTrigger>
> 
> postComment = () => `{`
>         this.refs.trigger.hide()
>   }
> ```
> 
> i have added like this way , everthing is perfect but i have just tried to close on button click its not happening

I am facing the same issue. I am not able to dismiss the popover on click outside the popover. Were you able to solve this @kishan143-jaiswal ?

**Comment by anuradhawarade** [comment]
Hi,

set rootClose={true} it close the overlaytrigger, when click outside

<OverlayTrigger                 
                    rootClose={true}
                    trigger="click"
                    placement="bottom"
                    overlay={()=>popover('S')}                    
                  >
                    <input
                      type="button"
                      value="FILTER"
                      onClick={() => dosome()}
                    />
                  </OverlayTrigger>
