### ISSUE TITLE
Form controls disabled on mobile

### ISSUE THREAD

**Issue by jslade** [react-bootstrap/react-bootstrap#3352]
I feel like I must be missing something obvious -- a simple form with two text fields and one select. Everything works fine on desktop in every browser I've tested. On mobile, everything renders correctly and I can navigate between pages, but all of the form controls are readonly (and the submit button), totally non-responsive to input / touch events. Switching the mobile browsers to the desktop site makes the controls work.

So the issue is just with mobile browsers in mobile mode. What might be missing?

The site is here if you want to look yourself: http://www.fcultimate.net/hpnc

**Comment by SebTM** [comment]
I had a quick look into your issue and found out that it seems the sidebar to be the problem. As you can see in my Screenshot it overlays in mobile-view over the main area.

<img width="1202" alt="screenshot 2018-11-09 at 09 00 14" src="https://user-images.githubusercontent.com/17243347/48250450-a2f58d80-e3fe-11e8-8c9e-4ca06169f45f.png">

Is your source-code available on github to have a look into? @jslade

**Comment by jslade** [comment]
https://github.com/jslade/fcultimate

Interesting... the sidebar content is displaying below everything else, but the div itself overlaps the top... hopefully that's just a simple css fix? Not that anything is simple with css these days.

Thanks for taking a look.
