### ISSUE TITLE
unclear browser support documentation

### ISSUE THREAD

**Issue by MariusMeiners** [react-bootstrap/react-bootstrap#3353]
Hey guys,

I'm having trouble understanding which Browsers you guys actually support. In your documentation you state that you aim to support all browsers supported by React and Bootstrap (with a link to bootstrap 3). 
However in your layout section it is stated that bootstraps grid system is based on **flexbox**, which isnt supported in IE9 but bootstrap 3 has IE9 support. So how does that work ? Do you guys use some type of polyfill to make it IE9 accessible or anything else ? I'm slightly confused... Also from my understanding bootstrap 3 still uses a float based grid system and not a flexbox based one, however i could be mistaken on that one. 
It would be great to get some feedback as to whether or not **IE9 is actually supported** by this package.
Thanks a lot in advance !

Marius

**Comment by jquense** [comment]
We need to update the link in the readme. Our browser support is essentially the same  as what ever version of bootstrap css your using. So for bootstrap v4 (react-bootstrap v1) that's IE10+

If you still need IE9 support, you can use one of the react-bootstrap versions that track bootstrap v3

**Comment by MariusMeiners** [comment]
so if i run `npm i --save react-bootstrap@next` as of right now, it will install a bootstrap v3 tracked version right?

**Comment by jquense** [comment]
no `@next` is the v1 branch, (which tracks bootstrap 4) at the moment. installing latest will give you a bootstrap3 version: see branch for a bit more detail: https://react-bootstrap.netlify.com/migrating/#versioning

**Comment by MariusMeiners** [comment]
thanks ! @jquense
