### ISSUE TITLE
Invalid tag name $ on install

### ISSUE THREAD

**Issue by mentallyretarded** [react-bootstrap/react-bootstrap#3356]
I followed the documentation to install the package, but when I run `npm install --save react react-dom $ npm install --save react-bootstrap` it gives me following error.
```
npm ERR! code EINVALIDTAGNAME
npm ERR! Invalid tag name "$": Tags may not have any characters that encodeURIComponent encodes.
```
My npm version is 5.6.0

**Comment by mentallyretarded** [comment]
My Bad. Got it working.

**Comment by hidaytrahman** [comment]
What was the issue?
