### ISSUE TITLE
Request) Clean up README.md!

### ISSUE THREAD

**Issue by guledali** [react-bootstrap/react-bootstrap#3359]
The related modules section is probably not needed anymore bootstrap 4 offers a lot of these components and utilities, I don't think you need to add any extra features. It also links to version 3 rather than 4.

**Comment by bpas247** [comment]
Which modules are you referring to exactly?

**Comment by guledali** [comment]
![related-modules](https://user-images.githubusercontent.com/20647282/48225590-86753900-e39d-11e8-892d-251c16bc4780.png)

**Comment by guledali** [comment]
@bpas247 Just remove it entirely
