### ISSUE TITLE
the whole docs site loads and disappears immediately

### ISSUE THREAD

**Issue by ahuggins** [react-bootstrap/react-bootstrap#3361]
This is in the console: 

<img width="1505" alt="screen shot 2018-11-07 at 7 21 01 pm" src="https://user-images.githubusercontent.com/1791228/48169751-7a687900-e2c2-11e8-90b4-0e4db20b3027.png">

**Comment by neosavvy** [comment]
Yeah this is still broken. There was a fix submitted earlier today but none of us are able to get to the site. I get the same error on all machines and networks I've tried from.

**Comment by neosavvy** [comment]
https://github.com/react-bootstrap/react-bootstrap/issues/3360 @jquense

**Comment by ahuggins** [comment]
appreciate the response

**Comment by jquense** [comment]
What url are y'all using

**Comment by neosavvy** [comment]
Wish I could help you fix it man - I'm just in the same boat and saw that it was reported as an issue earlier today, but claimed to be fixed. 

https://react-bootstrap.github.io/ and https://react-bootstrap.github.io/getting-started/introduction/

**Comment by neosavvy** [comment]
Just realized this is in your Readme now - but all SEO / Google Search results point to the above, and it's the links I have bookmarked for months. Doh. 

https://react-bootstrap.netlify.com/ does work.

**Comment by neosavvy** [comment]
I think I am coming to grips with what's going on, do you happen to know where the React Bootstrap 3 docs will live moving forward? I'm not sure we are going to be able to upgrade right now, as we're pretty tightly coupled to the Bootstrap 3 codebase at the current moment.

**Comment by pascalwhoop** [comment]
Where is the <1.0 documentation to be found? I can of course archive.org it but it's nicer to use one that has all the javascript still working.

**Comment by jquense** [comment]
Sorry folks we'll have this fixed soon.

**Comment by jquense** [comment]
fixed!

**Comment by neosavvy** [comment]
@jquense thanks for pushing the old docs up there for us laggards!
