### ISSUE TITLE
Old Version Docs website is broken https://react-bootstrap.github.io/

### ISSUE THREAD

**Issue by ajitStephen** [react-bootstrap/react-bootstrap#3363]
A console error on docs website.

<img width="1440" alt="screenshot 2018-11-08 at 5 39 46 pm" src="https://user-images.githubusercontent.com/12784114/48197961-528a1b80-e37d-11e8-9e00-987242af9c55.png">

**Comment by jquense** [comment]
https://github.com/react-bootstrap/react-bootstrap/issues/3361
