### ISSUE TITLE
Modal - Warning: Unknown props (0.32.4)

### ISSUE THREAD

**Issue by alexcigulin** [react-bootstrap/react-bootstrap#3365]
Hello! I got the errors in 0.32.4 using Modal component:
`Warning: Unknown prop backdropTransition on <div> tag. Remove this prop from the element.`
`Warning: Unknown prop transitionAppear on <div> tag. Remove this prop from the element.`
What I do wrong? My react version is 15.5.4, and react-dom 15.5.4.

PS: these errors appear using Modal (from your examples), not Modal.Dialog

**Comment by bpas247** [comment]
Do you mind posting a screenshot of your code? Link to a repo would work too

**Comment by taion** [comment]
This is likely happening because you're stripping prop types. The version of react-overlays shipped with the v3-dev line of R-B depends on its own prop types to avoid these problems.
