### ISSUE TITLE
Getting Started missing important step for create-react-app

### ISSUE THREAD

**Issue by JianbaoTao** [react-bootstrap/react-bootstrap#3367]
I use create-react-app to set up a new React app. When enabling react-bootstrap for my app, I need to do two steps. 
1. `yarn add react-bootstrap@next bootstrap`
2. In the `src/index.js` file, add `import 'bootstrap/dist/css/bootstrap.min.css';` as the first line

Step 1 is covered by the Getting Started page, but step 2 is missing. It may be obvious for seasoned web devs, but it will help for less seasoned ones if it is also covered.

**Comment by bpas247** [comment]
I'll open a PR soon to include step 2.

**Comment by bpas247** [comment]
After discussing this on #3377, this might not be the best documentation to be added here.

For create-react-app users, [it is already documented how to integrate bootstrap](https://facebook.github.io/create-react-app/docs/adding-bootstrap). 

We could possibly add this link to the getting started docs for CRA users, but it might make the getting started page a bit more overwhelming.
