### ISSUE TITLE
Pass props to typeless (grouping) Input 

### ISSUE THREAD

**Issue by flying-sheep** [react-bootstrap/react-bootstrap#337]
When specifying no type, nothing receives `{...this.props}`.

i’d like to e.g. pass a `title` to the whole form group

**Comment by mtscout6** [comment]
Can you provide a little more context on this?

**Comment by flying-sheep** [comment]
well, `<Input .../>` with no `type` attribute creates a `<div class="input-group"></div>` in the HTML.

and doing `<Input title="foobar">...</Input>` makes the title attribute vanish instead of attaching it to that `<div/>`

**Comment by AlexKVal** [comment]
`Input` is currently under re-factoring. Superceded by #342
