### ISSUE TITLE
SyntaxError: Unexpected token import

### ISSUE THREAD

**Issue by namuwikilover** [react-bootstrap/react-bootstrap#3375]
SyntaxError: Unexpected token import

Error is occured When I import bootstrapUtils with yarn start, I'm using react-boilerplate now
Error is not occured When I use bootstrapUtils in Storybook
Another module is imported well now like react ... etc. so I thought, This is not related to babel
What is it?...... help me 😢 

```
/Applications/babeltop-front-pro-react/node_modules/react-bootstrap/es/utils/index.js:1
(function (exports, require, module, __filename, __dirname) { import * as _bootstrapUtils from './bootstrapUtils';

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
```

**Comment by taion** [comment]
Your transpile settings are somehow incorrect. Import under `lib/`, not `es/` if you're not using native ES modules.
