### ISSUE TITLE
is there a way to create a link to an open modal?

### ISSUE THREAD

**Issue by jiehan1029** [react-bootstrap/react-bootstrap#3376]
I'm using react 15.5.4 and react-bootstrap 0.32.
I need to create an external link (on another page or email) that leads to an open modal in a different react component. For example, user clicks on the email link and will be directed to an open modal showing contact form. I searched and found a way to do it in bootstrap is to assign the modal an id and set href to /website.com#modal_id [https://gist.github.com/MrDys/3512455](https://gist.github.com/MrDys/3512455) , but how can I do it with react-bootstrap?

**Comment by jquense** [comment]
I would do something like checking for the id in the hash and setting the modal to open if it's the right one maybe?

```js
componentDidMount() {
  if (location.hash === '#my-modal') this.setState({ show: true })
}

render() {
  return <Modal show={this.state.show} ... />
}
```

**Comment by jiehan1029** [comment]
@jquense 
Thanks! the location.hash worked well.
