### ISSUE TITLE
Input[type="range"]

### ISSUE THREAD

**Issue by flying-sheep** [react-bootstrap/react-bootstrap#338]
This will suck on Chrome, because that browser for some reason uses the element’s box as slider groove…

**Comment by AlexKVal** [comment]
This is not the problem with R-B.
This a browser vendor's customizing of control elements.
`Bootstrap` doesn' deal with it either.

Answer http://stackoverflow.com/a/24465732/3874570

Firefox:
![firefox](https://cloud.githubusercontent.com/assets/847572/8406158/5e7d14da-1e62-11e5-8390-d90fd0f9257c.png)

Safary:
![safary](https://cloud.githubusercontent.com/assets/847572/8406160/6351d612-1e62-11e5-9352-ed5ac5c1e55d.png)

Chrome:
![chrome](https://cloud.githubusercontent.com/assets/847572/8406167/6da52722-1e62-11e5-890d-9a12df9740b6.png)
