### ISSUE TITLE
Progressbar does not display correctly in firefox

### ISSUE THREAD

**Issue by nwabdou85** [react-bootstrap/react-bootstrap#3385]
Hey,

Weird, progressbar display correctly in chrome but not in firefox; 

I means by that is the fact that does not display any border or color but only percentage;

here are some information may hep you help me to fix this isssue;

"react-bootstrap": "^0.31.5",
Firefox quantunm 57.0(64 bit)
 
Thank's

**Comment by taion** [comment]
this is purely a css issue on your side then; the stock progress bar works fine on firefox since it's just rendering the standard bootstrap markup
