### ISSUE TITLE
How to achieve Panel Group accordion functionality using 1.0.0-beta.3

### ISSUE THREAD

**Issue by jainvizz** [react-bootstrap/react-bootstrap#3386]
I am using react-bootstrap 1.0.0-beta.3, which is build for supporting bootstrap 4 update.

Before this I was using react-bootstrap 0.32.1 and created Accordion using Panels and Panel group.

But after bootstrap upgrade it was suggested to Card component. I tried to achieve the same behavior like this:

`<CardGroup>
 <Card eventKey={this.state.eventKey} className="border-0">
              <Card.Header>
                <div className="row">
                  <div className="col-xs-9 col-sm-9 col-md-9 col-lg-9">
                    <Card.Title>
                      This is test
                    </Card.Title>
                  </div>
                  <div className="col-xs-3 col-sm-3 col-md-3 col-lg-3">
                    Test Text 123
                  </div>
                </div>
              </Card.Header>
              <Card.Body>
                Test Text 456
              </Card.Body>
           </Card>
</CardGroup>`

Please help me out with this implementation.

**Comment by jquense** [comment]
At the moment there is no accordian behaviour out of the box with cards. We just haven't built it yet.

You can add it manually with the Collapse component just fine but there isn't a shortcut component right now

**Comment by jainvizz** [comment]
Thanks @jquense for the quick reply.

I have checked collapse component but that only work for single card, can you please tell me how to achieve accordion behavior with the same.

Like when I open one card it should close others.

**Comment by jquense** [comment]
You have to wrap each card in a collapse and control the open state for each of them yourself to achieve the effect. That's how we'd implement it internally at least

**Comment by bpas247** [comment]
> At the moment there is no accordian behaviour out of the box with cards. We just haven't built it yet.

Is this something we should add support for? I can probably start work on a PR for this, if it's something we would like to add.

**Comment by jquense** [comment]
We should add it, but I'm not sure how best to implement it. Not very happy with the way panel group works (or it's complexity) in previous versions so didn't want to just copy it

**Comment by bpas247** [comment]
Looking at the previous implementation of PanelGroup right now, I see what you mean by being unhappy wit its complexity.

> You have to wrap each card in a collapse and control the open state for each of them yourself to achieve the effect. That's how we'd implement it internally at least

Looking at the [accordion example](https://getbootstrap.com/docs/4.1/components/collapse/#accordion-example) on bootstrap's docs, it seems simple enough to replicate this without all of the complexities of the previous implementations if we just separate the accordion logic into its own component. Although I'm not sure how well this would work with CardGroup.

**Comment by jquense** [comment]
Please go for it 👍

**Comment by mxschmitt** [comment]
Looking forward that this will be implemented. Thanks for your work!

**Comment by mxschmitt** [comment]
It's now implemented: https://react-bootstrap.netlify.com/components/accordion/
