### ISSUE TITLE
Accordion not working in TabbedArea

### ISSUE THREAD

**Issue by mcoetzee** [react-bootstrap/react-bootstrap#339]
Hi there, thanks for the great work. There is an issue when you have a TabbedArea with an Accordion in a TabPane that isn't initially shown. The Accordion's default Panel (set by 'defaultActiveKey') doesn't display properly. A closer inspection shows that its height remains at '0px'. If the Accordion is placed in the TabbedArea's default TabPane (set by 'defaultActiveKey'), then it works as expected.

Here's an example that is not working:

```
   <TabbedArea defaultActiveKey='1'>
           <TabPane eventKey='1' tab="Hello">Hello World</TabPane>
           <TabPane eventKey='2' tab="Accordion">
             <Accordion defaultActiveKey='1a'>
               <Panel header="Option 1a" eventKey='1a'><p>Option 1a Accordion</p></Panel>
               <Panel header="Option 1b" eventKey='1b'><p>Option 1b Accordion</p></Panel>
             </Accordion>
          </TabPane>
  </TabbedArea>
```

**Comment by philipwhiuk** [comment]
I have seen this as well. I think my solution is going to be to re-implement tab panes....

**Comment by philipwhiuk** [comment]
I think the bug is caused by the fact that:

```javascript
  getCollapsableDimensionValue: function () {
    var node = this.refs.ul.getDOMNode(),
        height = node.offsetHeight,
        computedStyles = domUtils.getComputedStyles(node);

    return height + parseInt(computedStyles.marginTop, 10) + parseInt(computedStyles.marginBottom, 10);
  },
```

returns 0 for an element that is currently offscreen. So it sets the hidden yet expanded container to 0 when you change tab.

**Comment by AlexKVal** [comment]
Pull requests are welcome :wink:

**Comment by taion** [comment]
This was actually fixed at some point with one of the challenges to collapsible height calculations.
