### ISSUE TITLE
Overlays stay open in mobile

### ISSUE THREAD

**Issue by volkanunsal** [react-bootstrap/react-bootstrap#3391]
We've been noticing that tooltips and popovers stay open on mobile devices after the user clicks on an overlay trigger. There is nothing comparable to a "hover away" in mobile. So is it possible to indicate a maximum duration for the tooltips and have them disappear after the duration has elapsed?

Thanks.

**Comment by mxschmitt** [comment]
Please provide us an example on https://codesandbox.io
