### ISSUE TITLE
react-bootstrap 1.0.0-beta.3 disabling animation in modal not working

### ISSUE THREAD

**Issue by iamlazynic** [react-bootstrap/react-bootstrap#3399]
#### Version and browser:
react-bootstrap@^1.0.0-beta.3
Electron so chrome/chromium (v66)

#### Usage:
      <Modal animation={false} show={show} onHide={onHide}>
        <Modal.Header closeButton>
          <Modal.Title>
            Some header...
          </Modal.Title>
        </Modal.Header>
        <Modal.Body>
          Some body paragraphs...
        </Modal.Body>
        <Modal.Footer>
          Some buttons ...
        </Modal.Footer>
      </Modal>

#### Expected
Modal shown when `show` is set to `true` no matter `animation` is set to `true` or `false`

#### But
When `animation` is not set (default is `true`), modal is shown properly (btw, animation not so smooth); when `false`, screen becomes completely black without the modal.

#### Observation
By looking at developer tools, I see that the `div[role=dialog]` element which is the parent of the modal `div.modal-dialog` has style `display: none`.

**Comment by SoulKa** [comment]
Can confirm the same behaviour in Firefox with react-bootstrap@^1.0.0-beta.5.

**Comment by MichaelBurgess** [comment]
Same behaviour in `react-bootstrap@v1.0.0-beta.5` and `Chrome Version 73.0.3683.56 (Official Build) beta (64-bit)`.

**Comment by iantbarker** [comment]
Same behavior for me. `react-bootstrap@v1.0.0-beta.5` and Firefox and Chrome.
