### ISSUE TITLE
Internet Explorer 9 breaks many components

### ISSUE THREAD

**Issue by vertti** [react-bootstrap/react-bootstrap#340]
Viewing the React Bootstrap examples shows empty example boxes instead of working components for many components (like all Navbar examples) when using IE 9. These same components work on the official Bootstrap examples page so this seems to be an issue with React Bootstrap.

**Comment by AlexKVal** [comment]
I'm closing it. It is too broad description.

--
Anyway PRs with fixes are welcome :wink:
