### ISSUE TITLE
Button should accept type=undefined, 1.0.0-beta.3

### ISSUE THREAD

**Issue by aappddeevv** [react-bootstrap/react-bootstrap#3403]
I noticed that `type=undefined` causes an error in the Button component 1.0.0-beta.
```js
// Button.js
    return <Component {...props} type={type} className={classes} />;
```
I'm thinking that since it needs to be a string (enum) or null, that this should default to null on that line, otherwise, when you provide props, you always have to provide the type. Or is that planned?

**Comment by kosmiq** [comment]
Closing this. You can use `<Button>` without supplying the type.

**Comment by aappddeevv** [comment]
Thanks!
