### ISSUE TITLE
MAXCDN integrity value in documentation is outdated and invalid. 

### ISSUE THREAD

**Issue by PhilippeDunbar** [react-bootstrap/react-bootstrap#3406]
Relevant location in documentation (creating a new issue, since previous issues have been closed)

 https://react-bootstrap.netlify.com/getting-started/introduction#stylesheets

This appears to be a reoccurring issue #3294, #2991, #2978 

https://maxcdn.bootstrapcdn.com/bootstrap/latest/css/bootstrap.min.css

I believe the underling issue here is your tagging **latest** with an integrity value. Each time **latest** changes the integrity is invalidated (thats the point) and the documentation needs to be updated. 

I'm not sure if maxcdn has an option to link to a page with the various versions and integrity values, this would be the ideal solution(or some other form of automation). Otherwise removing the integrity value from the example would clear up a lot of the confusion and prevent these issues from popping up (less then ideal)

**Comment by taion** [comment]
Could we also just calculate the integrity value as part of the build pipeline @jquense?

**Comment by gritex** [comment]
I had this issue when setting up react-bootstrap. I would see the file load in Devtools but it just wouldn't style the elements. Please fix this so people don't get confused.

**Comment by taion** [comment]
fixed in https://github.com/react-bootstrap/react-bootstrap/pull/3432
