### ISSUE TITLE
(DropdownMenu) Warning: Rendering <Context> directly is not supported, React 16

### ISSUE THREAD

**Issue by WBad** [react-bootstrap/react-bootstrap#3408]
Hi Guys I'm getting the same issue as #3347 but on another component

react: 16.5.2
react-bootstrap: 1.0.0-beta.3
react-dom: 16.5.2

Exception

		Warning: Rendering <Context> directly is not supported and will be removed in a future major release. Did you mean to render <Context.Consumer> instead?
		    in DropdownMenu (created by Context.Consumer)
		    in span (created by NavItem)
		    in NavItem (created by Context.Consumer)
		    in DfNavItem (created by ReactOverlaysDropdown)
		    in Manager (created by ReactOverlaysDropdown)
		    in ReactOverlaysDropdown (created by Dropdown)
		    in Dropdown (created by Uncontrolled(Dropdown))
				...
		    in div (created by AbstractNav)
		    in AbstractNav (created by Context.Consumer)
		    in Nav (created by Context.Consumer)
				...
		    in div (created by Context.Consumer)
		    in Transition (created by Collapse)
		    in Collapse (created by Context.Consumer)
		    in NavbarCollapse (created by Context.Consumer)
		    in nav (created by Navbar)
		    in Navbar (created by Uncontrolled(Navbar))
				...
		    in HeaderMain (created by Connect(HeaderMain))
		    in Connect(HeaderMain) (created by Route)
				...
		    in Main (created by Route)
				...
		    in Router (created by BrowserRouter)
				...

For this component

    const DfNavItem = ({ children, ...props }) => (
      <Nav.Item as="span" {...props}>
        {children}
      </Nav.Item>
    );

    const DfNavDropdown = ({
      id,
      when,
      inCollection,
      toggle,
      children,
      ...props
    }) => {
      if (when && !isInCollection(when, inCollection)) {
        return null;
      }
      return (
        <Dropdown as={DfNavItem} drop="down" {...props}>
          <Dropdown.Toggle id={id} as={Nav.Link}>
            {toggle}
          </Dropdown.Toggle>
          <Dropdown.Menu>{children}</Dropdown.Menu>
        </Dropdown>
      );
    };

**Comment by kosmiq** [comment]
DropdownMenu.js has been rewritten since this issue was posted. Closing.
