### ISSUE TITLE
Cannot remove caret in DropdownButton

### ISSUE THREAD

**Issue by radiosilence** [react-bootstrap/react-bootstrap#341]
Surely there should be a prop or something like caret={false}?

**Comment by JazLow** [comment]
You may just overwrite the default css in your current project instead by:-

.caret {
display: none;
}

Then the caret/dropdown arrow will be hidden, or customise the caret's css again based on your specific requirement.

**Comment by warent** [comment]
Note: noCaret is not a prop for Dropdown.Toggle and .caret is not the classname. Instead the caret now renders in :after

```
.my-dropdown-toggle:after {
    display: none;
}
```

**Comment by dharkness** [comment]
@warent Is this tweak possible with `styled-components` in inline for a single dropdown menu?

**Comment by nguyenhoavuong** [comment]
In the situation can replace DropDownButton with DropDown, use DropDown and set Dropdown.Toggle bsPrefix attribute with your style class to replace the default style like this:
`<Dropdown>
      <Dropdown.Toggle variant="link" bsPrefix="py-0 pr-1">
         <FontAwesomeIcon icon="ellipsis-v" />
      </Dropdown.Toggle>
      <Dropdown.Menu>
        <Dropdown.Item href="#/action-1">Action</Dropdown.Item>
        <Dropdown.Item href="#/action-2">Another action</Dropdown.Item>
        <Dropdown.Item href="#/action-3">Something else</Dropdown.Item>
      </Dropdown.Menu>
    </Dropdown>`

Hope it help
