### ISSUE TITLE
Bootstrap documents

### ISSUE THREAD

**Issue by hungdomanh** [react-bootstrap/react-bootstrap#3412]
![image](https://user-images.githubusercontent.com/18446429/51164564-eae9d280-18cf-11e9-99c5-abe284b27061.png)

Link https://react-bootstrap.github.io/components/buttons/

bsStyle is one of: primary, success, warning ...

**Comment by tjdavey** [comment]
It looks like this issue was fixed in the v1 documentation. However, the defect still exists in the historical documentation for the 0.x releases: https://5c507d49471426000887a6a7--react-bootstrap.netlify.com/components/buttons/#buttons-props

**Comment by jquense** [comment]
not likely to fix for old docs, but will happily take a PR if anyone wants to send one over

**Comment by ashu8912** [comment]
ok working on this one
