### ISSUE TITLE
can't install react-bootstrap (404 not found)

### ISSUE THREAD

**Issue by amirbr** [react-bootstrap/react-bootstrap#3416]
When i run this command `npm install react-bootstrap@next bootstrap` or `npm install react-bootstrap`
i got this error 
```
code E404
404 Not Found: react-bootstrap@latest
```
Run on:

npm - 6.4.1
node - 11.1.0
yarn - 1.12.3

someone know why?

**Comment by taion** [comment]
wffm; likely a transient error in the npm registry, or else misconfiguration there
