### ISSUE TITLE
Question about show-grid

### ISSUE THREAD

**Issue by sche0025** [react-bootstrap/react-bootstrap#3419]
Hi there:
I was trying to draw a matrix like: 
![image](https://user-images.githubusercontent.com/35447735/51452414-4fa0a380-1d8e-11e9-85d8-ec919379bef9.png)

However, I failed to displace the grid via "show-grid", my code:

![image](https://user-images.githubusercontent.com/35447735/51452598-482dca00-1d8f-11e9-98a9-707b06c46092.png)

This results in :
![image](https://user-images.githubusercontent.com/35447735/51452557-f9803000-1d8e-11e9-8f64-7d4ee0e5aced.png)

where the grid is still not showing. Besides, I also tried display: "grid" which is not the solution,
so could someone show me some insights?

**Comment by jquense** [comment]
what is 'show-grid'? I don't think that is a bootstrap class?
