### ISSUE TITLE
[DOCS] Minified React error #185

### ISSUE THREAD

**Issue by nearwood** [react-bootstrap/react-bootstrap#3421]
Windows 10 64
FF 64.0.2 (64-bit)

I keep running into into this on the current docs:

```
Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
```

The full message being:

> Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.

I will attempt to note how to reproduce it later today, as it happens often.

**Comment by nearwood** [comment]
Well, it failed to occur yesterday, but it did just now. I clicked this link `https://react-bootstrap.netlify.com/components/forms/#form-row-props` from within the Forms docs.

Got a full stack trace:

```
Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
```

```
Error: Script terminated by timeout at:
Sn@https://react-bootstrap.netlify.com/2-68b2153cc7f036eae14f.js:1:726504
An@https://react-bootstrap.netlify.com/2-68b2153cc7f036eae14f.js:1:726401
Mn</e.prototype.componentDidUpdate@https://react-bootstrap.netlify.com/2-68b2153cc7f036eae14f.js:1:730550
Aa@https://react-bootstrap.netlify.com/app-436a48db75de79f1b072.js:1:203493
Na@https://react-bootstrap.netlify.com/app-436a48db75de79f1b072.js:1:199152
ja@https://react-bootstrap.netlify.com/app-436a48db75de79f1b072.js:1:198497
Ea@https://react-bootstrap.netlify.com/app-436a48db75de79f1b072.js:1:197518
Zi@https://react-bootstrap.netlify.com/app-436a48db75de79f1b072.js:1:196421
enqueueSetState@https://react-bootstrap.netlify.com/app-436a48db75de79f1b072.js:1:161349
x.prototype.setState@https://react-bootstrap.netlify.com/app-436a48db75de79f1b072.js:1:80940
M</t.prototype.componentDidMount/t.unlisten</</<@https://react-bootstrap.netlify.com/app-436a48db75de79f1b072.js:1:18652
```

**Comment by nearwood** [comment]
Also note: This kills the browser.

At least until the FF watchdog intervenes.

**Comment by wgarvey** [comment]
"Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops."

Is setState() being called by componentDidUpdate()? Because componentDidUpdate() is called after each state change, this will cause an infinite loop until you run out of stack. This is likely the problem.

**Comment by taion** [comment]
do you have a specific page in the docs that triggers this?

**Comment by nearwood** [comment]
@taion It has happened on other pages than the one mentioned in my last comment. I *think* it might be isolated to the API links, but can't confirm definitively.

**Comment by mxschmitt** [comment]
@nearwood is this issue still reproducible?

**Comment by nearwood** [comment]
Yes, but not easily. I clicked around the docs for a while. Then left the Button page open for a while. Came back to it. Edited the example shown, then tried to click the ToggleButtonGroup API link:

![image](https://user-images.githubusercontent.com/1929778/54556101-852ccc00-498e-11e9-8adc-788eab7a31b8.png)

![image](https://user-images.githubusercontent.com/1929778/54556164-a8f01200-498e-11e9-8543-9d85223470c5.png)

Wondering if the inline editor has something to do with it -- I rarely use it, but can't discount it.

**Comment by oscles** [comment]
I got the error when I implemented the redux-reset library, click on the logout button, and since the status, I have in redux is something big it sends me that error

**Comment by dareedyone** [comment]
> @nearwood
> 
> "Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops."
> 
> Is setState() being called by componentDidUpdate()? Because componentDidUpdate() is called after each state change, this will cause an infinite loop until you run out of stack. This is likely the problem.

i am having this same kind of error and i did not use componentWillUpdate or componentDidUpdate what i use is componentDidMount. Any help or insights about this ?

**Comment by taion** [comment]
We're going to need a more self-contained repro to do anything here. None of these components are doing much of anything that should cause this.

**Comment by shankarm123** [comment]
So above issue was solved with what change?

**Comment by kyletsang** [comment]
This issue is pretty stale, and I haven't run into this, so will close it for now.

**Comment by rasel-xs** [comment]
I fetching the same issue when importing in WordPress plugin.  see error [https://prnt.sc/24wb1xu](https://prnt.sc/24wb1xu)
and this my code [https://prnt.sc/24wb6po](https://prnt.sc/24wb6po)
Can anyone  help me how can i fix this error

**Comment by fahimanwer** [comment]
Having same error
Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at al (https://www.ofzenandcomputing.com/wp-content/plugins/gutenberg/build/vendors/react-dom.min.js?ver=18:1:82569)
    at Rt (https://www.ofzenandcomputing.com/wp-content/plugins/gutenberg/build/vendors/react-dom.min.js?ver=18:1:50477)
    at Tt (https://www.ofzenandcomputing.com/wp-content/plugins/gutenberg/build/vendors/react-dom.min.js?ver=18:1:50283)
    at Ur (https://www.ofzenandcomputing.com/wp-content/plugins/gutenberg/build/vendors/react-dom.min.js?ver=18:1:73397)
    at El (https://www.ofzenandcomputing.com/wp-content/plugins/gutenberg/build/vendors/react-dom.min.js?ver=18:1:93217)
    at fl (https://www.ofzenandcomputing.com/wp-content/plugins/gutenberg/build/vendors/react-dom.min.js?ver=18:1:85533)
    at zn (https://www.ofzenandcomputing.com/wp-content/plugins/gutenberg/build/vendors/react-dom.min.js?ver=18:1:32460)
    at al (https://www.ofzenandcomputing.com/wp-content/plugins/gutenberg/build/vendors/react-dom.min.js?ver=18:1:82706)
    at Rt (https://www.ofzenandcomputing.com/wp-content/plugins/gutenberg/build/vendors/react-dom.min.js?ver=18:1:50477)
    at https://www.ofzenandcomputing.com/wp-content/plugins/gutenberg/build/vendors/react-dom.min.js?ver=18:1:50336

**Comment by tsgeorgieva** [comment]
We're having the same issue and we don't even use componentWillUpdate or componentDidUpdate.

**Comment by MGParisi** [comment]
Just started with us as well.

**Comment by denglad93** [comment]
> Ours was related to the Ultimate Addons for Gutenberg Plugin

I've got the same for Gutenberg plugin, when i hover on the blocks (in the left bar), which was created with Carbon Fields WP plugin.
