### ISSUE TITLE
Can't set border radius on Toggle Buttons

### ISSUE THREAD

**Issue by Theeeus** [react-bootstrap/react-bootstrap#3422]
I'm using the sample implementation of the Toggle Buttons and they don't seem to accept border radius (with or without a custom class). 

The border-radius value I'm setting is showing on the Google Console but it doesn't seeem to affect the button.

**Comment by jquense** [comment]
how are you setting it?

**Comment by Theeeus** [comment]
This is how I see it just implementing the example Toggle Buttons, without any custom css class.

If I add a custom css class all styles will be implemented except border-radius.

![1](https://user-images.githubusercontent.com/18108551/51622644-fc049600-1f04-11e9-8aeb-1c40deaac877.jpg)

![2](https://user-images.githubusercontent.com/18108551/51622643-fc049600-1f04-11e9-8e02-54e51652ec22.jpg)

**Comment by TWKDreamState** [comment]
I was having the same issue using styled-components. I don't know if this will help you, but by adding !important; after the border-radius, it worked for me.

**Comment by kosmiq** [comment]
Closing since no new feedback.
