### ISSUE TITLE
[DOCS] Import Path of Components missing .../lib/... ?

### ISSUE THREAD

**Issue by m31415** [react-bootstrap/react-bootstrap#3424]
Hi, 
since I often c&p the import statements from the docs I recognized today, that they didn't resolve because ```.../lib/...```is missing.

Example:
```import Form from 'react-bootstrap/Form'```

Make it work:
```import Form from 'react-bootstrap/lib/Form'```

**Comment by jquense** [comment]
So this is a problem with how our beta docs are deployyed they pull of of master not release tags. We made this change in how we publish to not need the `lib` anymore but haven't pushed a release out yet with that behavior. going to do that today.

**Comment by taion** [comment]
we've since cut the release that updated the import paths
