### ISSUE TITLE
Overlay rendered outside of the Root / Redux Provider can not be connected to Redux store

### ISSUE THREAD

**Issue by kromit** [react-bootstrap/react-bootstrap#3426]
Using
react-redux: 6.0.0
react: 16.7.0
redux: 4.0.1

```
<Provider store={configureStore()} context={ReactReduxContext}>
  <OverlayTrigger overlay={<MyConnectedComponent/>}>
      <a>click me</a>
  </OverlayTrigger>
</Provider>
```

`MyConnectedComponent` can not be connected to the store when using an overlay. Always getting `Could not find "store" in either the context or props`.

**Comment by taion** [comment]
let's track this on https://github.com/react-bootstrap/react-bootstrap/issues/3434 which has more details
