### ISSUE TITLE
Old Docs Are Gone?

### ISSUE THREAD

**Issue by jimniels** [react-bootstrap/react-bootstrap#3429]
The Readme states:

> To find the documentation for the latest Bootstrap 3 compatible release, check out: https://react-bootstrap.github.io/

However, I can't find anywhere at that URL which shows the ability to "switch" to the old Bootstrap 3 version of react-bootstrap.

Is this an oversight? Seems like a good idea to keep the old docs around at *some* URL...

**Comment by jquense** [comment]
We are working on exposing previous version docs, so bear with us while we figure it out. In the meantime https://5c507d49471426000887a6a7--react-bootstrap.netlify.com/ works and i'll update the readme

**Comment by harshilsharma63** [comment]
Damn, that's a shame.

**Comment by jquense** [comment]
Link is in the readme

**Comment by rlovtangen** [comment]
I downloaded the source for react-bootstrap 0.27.3 and was able to get the docs up and running locally by running
```
$ npm install
$ npm run docs
```
