### ISSUE TITLE
Problems with new version

### ISSUE THREAD

**Issue by ChuchoPV** [react-bootstrap/react-bootstrap#3430]
Hey! I tried to make a new project and I realize that there are a new version.
I just install the new version and also introduce the style in the index.html but I realize that there's no working. The buttons are without styles. 

Any idea?

**Comment by jquense** [comment]
Had to say without specifics. Please post the error and what you've tried (code)

**Comment by yash2code** [comment]
same issue . variant property of button component is not working.

**Comment by ChuchoPV** [comment]
<img width="1440" alt="screen shot 2019-01-30 at 9 12 52 am" src="https://user-images.githubusercontent.com/20933458/51990833-7ab28380-246f-11e9-9aa1-fd67eafde9c7.png">

This one was my styling before I update to the new version.

Then I update using :  npm install react-bootstrap@next bootstrap
I locate this

```
<!-- Latest compiled and minified CSS -->
<link
  rel="stylesheet"
  href="https://maxcdn.bootstrapcdn.com/bootstrap/latest/css/bootstrap.min.css"
  integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
  crossorigin="anonymous"
/>
```

in my index.html as before and nothing happened. May be I'm doing it wrong but now it is not working.

This is how it looks now:

<img width="1440" alt="screen shot 2019-01-30 at 9 10 42 am" src="https://user-images.githubusercontent.com/20933458/51991408-aa15c000-2470-11e9-8ec3-b2e3cf06e2bf.png">

If I'm doing something wrong please I ask for help

**Comment by jquense** [comment]
remove the `integrity` value for now and make sure the css file is actually loaded.

**Comment by ChuchoPV** [comment]
How can I know were the css file is it, and if is not loaded. Where can I get it?
