### ISSUE TITLE
0.32.x does not work with react-redux@6

### ISSUE THREAD

**Issue by ztanner** [react-bootstrap/react-bootstrap#3434]
Attempting to use an `OverlayTrigger`, where the overlay component is connected to the redux store, fails with errors about not being able to access the store. This is likely because react-redux uses the new context API, and the way overlays are being rendered does not place them inside of a Provider.

Minimal reproduction:
https://codesandbox.io/s/905221j9r

The same code above works when changing to the latest react-bootstrap v1 beta, but I'm hoping to stay on Bootstrap 3.

It looks like this is the culprit:
https://github.com/react-bootstrap/react-bootstrap/blob/3360fdee104758d94136a7adf54cedb068197ea5/src/OverlayTrigger.js#L236-L240

**Comment by ztanner** [comment]
Going to take a stab at fixing this tonight.

**Comment by cstrnt** [comment]
I'm forced to use Bootstrap 3 and the error still occurs to me. Is there any workaround?
