### ISSUE TITLE
DropDown menu is not showing since 1.0.0

### ISSUE THREAD

**Issue by lavoiekeven** [react-bootstrap/react-bootstrap#3435]
When I click on the button the menu is not showing.

From what I understand it miss the style ".show>.dropdown-menu{display:block}" in the CSS

Also the dropdown is not closing when I click outside the menu. 

In version 0.32 it was working well.

**Comment by jquense** [comment]
Please provide a reproduction thanks!

**Comment by lavoiekeven** [comment]
I found out. When I remove redux it works well.

It seems to have a link with mapDispatchToProps. When I remove it it works.

Sample:
https://mega.nz/#!yRNyzaTZ!3TgoyeBQGOptlxfBAu2KzO1WZGzYnDYusXz5KPB9VLA

**Comment by jquense** [comment]
Sounds like maybe it's not able to add a ref to drop-down toggle

**Comment by taion** [comment]
you should ensure that you've configured redux to pass through refs (e.g. in v6)

additionally, note that going from 0.32 to 1.x means going from bootstrap v3 to bootstrap v4, so there could be other issues with CSS incompatibility
