### ISSUE TITLE
react-bootstrap-alerts

### ISSUE THREAD

**Issue by renetanikolova** [react-bootstrap/react-bootstrap#3436]
Hello Guys, 
I hope I find you well!

I wanted to ask you something about the Alerts, ref: 
https://react-bootstrap.netlify.com/components/alerts/ 
I was wondering why when I set the property:  variant="warning" does not change at all? I have the imported CSS file, I have installed the react-bootstrap package but still shows as an **Info Alert**, which I did not want. After a little research, I found out that the old way of specifying the theme is working, and that is: bsStyle="warning", which is strange. 
I have just checked my version of the package, and it is "react-bootstrap": "^0.32.4"
I tried to update with the command 'yarn upgrade react-scripts' which usually updates the dependencies if there is a newer version of some of them available.
And as I can make a conclusion, the current documentation is about the newest version of react-bootstrap which is still not available for usage. 
If I am correct, would you please specify this somewhere in your page and also it would be really really helpful if you keep the documentation of the older version of react-bootstrap in the site available. That way no other people will get confused as I got yesterday.

Thank you in advance!

Best wishes and happy coding,
Reneta

**Comment by taion** [comment]
the docs apply to the v1 betas, not the v0.32 releases. see https://github.com/react-bootstrap/react-bootstrap/issues/3429#issuecomment-458640080
