### ISSUE TITLE
Could not find InputGroup.Append (etc..)

### ISSUE THREAD

**Issue by Hienphamthe** [react-bootstrap/react-bootstrap#3441]
Hi guys, I could not import InputGroup.Append or Prepend according to the [doc](https://react-bootstrap.github.io/components/input-group/). 
react-bootstrap is updated to the latest version. 
Code as below:
`import { FormControl, InputGroup } from 'react-bootstrap';`
`class ... {`
`render() {`
`return(`
`<InputGroup>...`
`<InputGroup.Append >` <= error here
`...`
`</InputGroup.Append >`
`</InputGroup>`
`)}}`

Please help, thanks

**Comment by Hienphamthe** [comment]
`import InputGroup from 'react-bootstrap/InputGroup'` does not work as well.

**Comment by jquense** [comment]
what version do you have installe?

**Comment by Hienphamthe** [comment]
> 
> 
> what version do you have installed?

Hi, it is the latest version: 1.0.0-beta.5.
Only Addon and Button is available according to InputGroup.d.ts file:
```import * as React from 'react';
import { Sizes } from 'react-bootstrap';
import InputGroupAddon = require('./InputGroupAddon');
import InputGroupButton = require('./InputGroupButton');

declare namespace InputGroup {
    export interface InputGroupProps extends React.HTMLProps<InputGroup> {
        bsClass?: string;
        bsSize?: Sizes;
    }
}
declare class InputGroup extends React.Component<InputGroup.InputGroupProps> {
    public static Addon: typeof InputGroupAddon;
    public static Button: typeof InputGroupButton;
}
export = InputGroup;

**Comment by jquense** [comment]
Looks like the types are wrong, but the components should still be there. Would you want to send a PR fixing the types?

**Comment by Hienphamthe** [comment]
sorry restart VScode solve the problem.
