### ISSUE TITLE
<v1.0.0 doc

### ISSUE THREAD

**Issue by Hienphamthe** [react-bootstrap/react-bootstrap#3442]
Hi, where could I find the old doc for <v1.0.0. It is impossible for me to migrate to new version, old version is enough for me atm. Thanks

**Comment by jquense** [comment]
It's linked in the readme

**Comment by Hienphamthe** [comment]
Sorry, could you check again? it redirects to the latest doc (v1.xxx)

**Comment by jquense** [comment]
![image](https://user-images.githubusercontent.com/339286/52221657-9fdc3300-286f-11e9-8627-53c3dcb1b29e.png)

under the main documentation link
