### ISSUE TITLE
Typescript className

### ISSUE THREAD

**Issue by madroneropaulo** [react-bootstrap/react-bootstrap#3446]
Hello!

I'm using bootstrap beta 1.0.0-beta.5 with typescript (I'm not using the Definitely Typed repo), but I'm getting an error when I try to set a className for a Navbar.Collapse component.

```
Type '{ children: Element; class: string; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<NavbarCollapse> & Readonly<{ children?: ReactNode; }> & Readonly<ReplaceProps<typeof Collapse, BsPrefixProps<typeof Collapse>>>'.
```
How can I add a className to react-bootstrap components and typescript?

**Comment by jquense** [comment]
The type def is probably incomplete. happy to take PR's fixing them!

**Comment by aMarCruz** [comment]
@jquense , you're right, typings are incomplete and has errors.
I'll be uploading PRs with the corrections and documenting them in the coming days.

**Comment by jquense** [comment]
Yup 👍

**Comment by webivan1** [comment]
Hello! I`ve a problem **Type '{ children: Element; id: string; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<NavbarCollapse>** This error is due to <Navbar.Collapse **id={'test-id'}**>

**Comment by fredriklengstrand** [comment]
Another issue I have found with the typings is that the type for the `onChange` event on a `<Form.Control>` input does not seem to match the type `ChangeEvent<HTMLInputElement>` like it does for a regular `<input>` element:

```
Type '(event: ChangeEvent<HTMLInputElement>) => void' is not assignable to type '(event: FormEvent<ReplaceProps<"input", BsPrefixProps<"input"> & FormControlProps>>) => void'.
  Types of parameters 'event' and 'event' are incompatible.
    Type 'FormEvent<ReplaceProps<"input", BsPrefixProps<"input"> & FormControlProps>>' is not assignable to type 'ChangeEvent<HTMLInputElement>'.
      Types of property 'target' are incompatible.
        Type 'EventTarget' is not assignable to type 'EventTarget & HTMLInputElement'.
          Type 'EventTarget' is missing the following properties from type 'HTMLInputElement': accept, align, alt, autocomplete, and 286 more.
```

**Comment by jquense** [comment]
feel free to send over any type improvements. we will merge em right in

**Comment by aMarCruz** [comment]
@fredriklengstrand , in fact, it happens with several events but it has a simple solution.

The problem that I have had these days is with the classes that use forwardRefs. It is currently impossible to declare a class with `ref` to a different type (`ref` is not a regular prop).

The solution seems to be to declare them as a functional component but, although they are similar to them, they are not the same and I have not got `"as"` to work dynamically (which depends on the type of `ref` and events).

As a side note, personally I don't like to use ref to return the dom element, it seems confusing and does not allow access to the functionality of the component. Other libraries use a different property and that simplifies the code, but anyway I'm still looking for a solution.

**Comment by prateekkathal** [comment]
+1

![Image Of Error](https://cdn-std.dprcdn.net/files/acc_641929/YMFsG9)

**Comment by mxschmitt** [comment]
was integrated in #3519 (not released yet to npm)

**Comment by aleksandraif** [comment]
Hello! I have the same problem -  Type '{ children: Element[]; id: string; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<NavbarCollapse> & Readonly<{ children?: ReactNode; }> & Readonly<ReplaceProps<typeof Collapse, BsPrefixProps<typeof Collapse>>>'.
