### ISSUE TITLE
Injected props from Overlay to Tooltip results in errors

### ISSUE THREAD

**Issue by msteitle** [react-bootstrap/react-bootstrap#3450]
Per the documentation:

https://react-bootstrap.github.io/components/overlays/#tooltip-examples

> You can pass the Overlay injected props directly to the Tooltip component.

```javascript
<Overlay target={target} show={show} placement="right">
    {props => (
    <Tooltip id="overlay-example" {...props}>
        My Tooltip
    </Tooltip>
    )}
</Overlay>
```

Using this exact example results in the following runtime error:

> console.js?00ac:35 Warning: Received `true` for a non-boolean attribute `show`.
> 
> If you want to write it to the DOM, pass a string instead: show="true" or show={value.toString()}.
>     in div (created by Tooltip)
>     in Tooltip
>     in Transition (created by Fade)
>     in Fade (created by InnerPopper)
>     in InnerPopper
>     in Popper (created by Overlay)
>     in RootCloseWrapper (created by Overlay)
>     in WaitForContainer (created by Portal)
>     in Portal (created by Overlay)
>     in Overlay (created by WaitForContainer)
>     in WaitForContainer (created by ForwardRef(withContainer(Overlay)))
>     in Overlay (created by OverlayTooltip)

Browser: Chrome v72.0.3626.81 (Official Build) (64-bit)
OS: MacOS v10.14.2
react-bootstrap v1.0.0-beta.5
bootstrap v4.2.1
react v16.4.1

**Comment by patrka54** [comment]
I have noticed that too. [done that and still not working](https://reactjs.org/warnings/unknown-prop.html )

**Comment by lclement57** [comment]
A workaround is to remove the `show` property when passing the props to the `Tooltip` since it does not belong to this object (from the [API doc](https://react-bootstrap.github.io/components/overlays/#tooltip-props)

eg. with lodash
```
<Overlay target={target} show={show} placement="right">
    {props => (
        <Tooltip id="overlay-example" {..._.omit(props, ['show']}>
            My Tooltip
        </Tooltip>
    )}
</Overlay>
```

**Comment by taion** [comment]
fixed in https://github.com/react-bootstrap/react-bootstrap/pull/3443; thanks @otanim!
