### ISSUE TITLE
Overlay + Tooltip placement right, right-end, right-start all the same and all misplaced

### ISSUE THREAD

**Issue by msteitle** [react-bootstrap/react-bootstrap#3451]
In react-bootstrap v0.32.3, setting the Overlay + Tooltip prop `placement = 'right'` results in a tooltip placement at the end of the containing element.

[screenshot - react-bootstrap v0.32.3](https://i.imgur.com/tR87hUO.png)

In react-bootstrap 1.0.0-beta.5, the same thing, `placement = 'right'` (or right-end, right-start), and using the target attribute (per the api docs) results in a completely unexpected placement:

[screenshot - react-bootstrap 1.0.0-beta.5](https://i.imgur.com/d9Ghekz.png)

Browser: Chrome v72.0.3626.81 (Official Build) (64-bit)
OS: MacOS v10.14.2
react-bootstrap v1.0.0-beta.5
bootstrap v4.2.1
react v16.4.1

**Comment by kosmiq** [comment]
Closing since I assume this is not an issue any longer.
