### ISSUE TITLE
navbar toggle not working (because height is fixed)

### ISSUE THREAD

**Issue by kerorojason** [react-bootstrap/react-bootstrap#3453]
![image](https://user-images.githubusercontent.com/15242893/52359474-ed75bd00-2a74-11e9-8adb-8ac9d439fa3f.png)

I'm using react bootstrap to make my navbar. When the width of the window is small, the toggle button appears, but after clicking the button, my nav-items just can't appear. It seams that the navbar's height is fixed. How to fix this? This is my code:

```import React, { Component } from "react";
import { connect } from "react-redux";
import { Link } from "react-router-dom";
import Payments from "./Payments";
import { LinkContainer } from "react-router-bootstrap";
import {
  Navbar,
  Nav,
  NavItem,
  NavDropdown,
  MenuItem,
  Container,
  Card,
  Button
} from "react-bootstrap";

class Header extends Component {

  render() {
    return (
      <Container>
        <Navbar collapseOnSelect bg="dark" variant="dark" expand="lg">
          <LinkContainer to={this.props.auth ? "/surveys" : "/"}>
            <Navbar.Brand>Emaily</Navbar.Brand>
          </LinkContainer>
          <Navbar.Toggle aria-controls="basic-navbar-nav" />
          <Navbar.Collapse id="basic-navbar-nav">
            <Nav className="ml-auto">
              <Nav.Link href="#home">Home</Nav.Link>
              <Nav.Link href="#link">Link</Nav.Link>
            </Nav>
          </Navbar.Collapse>
        </Navbar>
      </Container>

    );
  }
}

function mapStateToProps({ auth }) {
  return { auth };
}
export default connect(mapStateToProps)(Header);```

**Comment by taion** [comment]
please take a look at the examples, where we demonstrate this functionality (you'll need to resize your viewport width to see the collapse behavior)

**Comment by taion** [comment]
https://react-bootstrap.github.io/components/navbar/

**Comment by kerorojason** [comment]
But my problem is not collapse. 
My problem is after collapse, when I toggle the button, the nav-items doesn't show properly.

**Comment by taion** [comment]
ah, okay; see https://github.com/react-bootstrap/react-bootstrap/issues/3394 then

**Comment by kerorojason** [comment]
Although I still can't fix the navbar height problem ...
But thanks!

**Comment by kerorojason** [comment]
Finally found the problem:
```import "materialize-css/dist/css/materialize.min.css";```
Because I was previously using Material Design, its styling is conflicting to react-router's.

**Comment by Alberto505061** [comment]
Sorry, may you explain how did you solve it? I'm having the same problem.

**Comment by kerorojason** [comment]
I think I just removed the import line of Material Design.
