### ISSUE TITLE
Incorporating React Hooks

### ISSUE THREAD

**Issue by bpas247** [react-bootstrap/react-bootstrap#3455]
[With the official release of react hooks](https://reactjs.org/blog/2019/02/06/react-v16.8.0.html), I was wondering if there were plans to migrate the codebase to utilize them.

Is this something that's already in the works?

**Comment by taion** [comment]
see https://github.com/react-bootstrap/react-bootstrap/pull/3454

**Comment by taion** [comment]
this doesn't seem to change the API much for normal users of the library, though

**Comment by bpas247** [comment]
Awesome! Can't wait to see it get merged :+1:
