### ISSUE TITLE
How to override modal-content class in Modal?

### ISSUE THREAD

**Issue by zverexe** [react-bootstrap/react-bootstrap#3459]
Hi, I'm using Modal component and cannot override modal-content class or add some custom class to that div. I'm using css modules. I cannot find in the docs appropriate way of adding custom components to the Modal except modalClassName

**Comment by taion** [comment]
set the `bsPrefix` on the `<ModalDialog>` to something other than `modal`; the class is calculated from there

alternatively, use a nested selector on whatever your modal class is, and the global `.modal-content`

**Comment by zverexe** [comment]
I use react bootstrap react-bootstrap": "^0.32.1" and I think I cannot use bsPrefix there

**Comment by zverexe** [comment]
@taion ?

**Comment by hazemyth** [comment]
Could we re-open this issue?

> set the `bsPrefix` on the `<ModalDialog>` to something other than `modal`; the class is calculated from there
> 
> alternatively, use a nested selector on whatever your modal class is, and the global `.modal-content`

The recommended route would also alter the class of the Modal.Dialog component. As far as I can see, there isn't any way to modify the class of the model-content element specifically.

Most of the components of the  modal can be targeted in precise fashion, either directly with props such as 'as' or 'className' or indirectly with specialized props such as 'dialogAs' or 'backdropClassName', when the component/element comes packaged inside another.

However, the model-content element comes packaged inside the Modal.Dialog component, without any independent means of modification that I can identify.

**Comment by taion** [comment]
sure, that's a slightly different question – if you need to modify that class name for some reason, like you're using CSS modules and you want to compose stuff in...

We'd be happy to take a PR that adds a `contentClassName` prop or something.

**Comment by akzarma** [comment]
any update on this?

**Comment by taion** [comment]
As above, we'd be happy to take a PR to add a `contentClassName` prop.

**Comment by Gantushig77** [comment]
Same here.
