### ISSUE TITLE
Form.Control.Feedback renders invisible text

### ISSUE THREAD

**Issue by aikidoshi** [react-bootstrap/react-bootstrap#3465]
I've got redux form that has touched, error & warning values passed in to my custom text component, but in both cases I get the "div class='invalid-feedback'" with the appropriate error or warning text but for some reason the display attribute is set to 'display: none' so the text is invisible.

      <Col md={4}>
        {touched && (
          error && <Form.Control.Feedback type='invalid'>{error}</Form.Control.Feedback> ||
          warning && <Form.Control.Feedback type='invalid'>{warning}</Form.Control.Feedback>
        )}
      </Col>

I'm geting my bootstrap css from: 
    <link
            rel="stylesheet"
            href="https://maxcdn.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css"
            integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS"
            crossorigin="anonymous"
    />
Please help.
Regards,
aikidoshi

**Comment by taion** [comment]
see the TWBS docs: https://getbootstrap.com/docs/4.3/components/forms/#custom-styles

these only display if they're positioned appropriately next to valid or invalid form inputs

**Comment by futhrevo** [comment]
@aikidoshi  It looks like you need to provide` isInvalid `prop to Form.Control to trigger invalid feedback and  `isValid` prop to trigger valid feedback details in docs _https://react-bootstrap.netlify.com/components/forms/#forms-validation-libraries_
