### ISSUE TITLE
Compilation Error while using react-bootsrap with typescript

### ISSUE THREAD

**Issue by nikhilbisht21** [react-bootstrap/react-bootstrap#3466]
I am recently facing an issue with react-bootstrap. Everything was working fine with the previous version of react-bootstrap library. I am getting following error on compilation:

```
/client/node_modules/@types/react-bootstrap/lib/Accordion.d.ts
(2,10): Module '"../../../react-bootstrap"' has no exported member 'Sizes'.
```

**Comment by jquense** [comment]
sounds like you have type mismatch, the DT types aren't compatible with v1, but v1 also just ships with ts types

**Comment by mark-schaal** [comment]
@jquense Thank you for this

**Comment by tarim** [comment]
I have the same issue. What is the right solution for this, please? I downloaded the latest versions.

Thank you,

**Comment by mark-schaal** [comment]
@tarim, run ```yarn info react-bootstrap```. If you are using a version >= 1.0, then you should not have the package ```@types/react-bootstrap``` installed, since the types have first class support in the official package.

**Comment by hisuwh** [comment]
I'm getting this with v1.3.0
```
Module '"../../../node_modules/react-bootstrap/esm/Card"' has no exported member 'Card'. Did you mean to use 'import Card from "../../../node_modules/react-bootstrap/esm/Card"' instead?
````

**Comment by hisuwh** [comment]
Oh I see its a default export... 🤮 
```tsx
import Card from "react-bootstrap/Card";
```
