### ISSUE TITLE
Form.Check Radio 'value' doesn't work properly

### ISSUE THREAD

**Issue by aikidoshi** [react-bootstrap/react-bootstrap#3467]
Hi there,
I'm creating 3 Form.Check radio buttons on a Redux Form using a custom component built to map an array of options - one for each radio button. Presentation-wise they work fine, but you can't select them because they all end up having whatever value is assigned to the Field as a whole. They each have a different value being the options passed in.

This is the Field on the form using the component RadioField that I wrote::

        <Field
          name="rad"
          label="rad"
          options={["Granted", "Denied", "Other"]}
          component={RadioField}
        />

The component loops through the options building the controls as shown below.

Each radio had its own unique id but they all have the same name and should have different value (being the option) so that they can work out which one is 'checked':

```
const renderRadio = ({
  input,
  label,
  options,
  inline,
  meta: { touched, error, warning },
  ...rest
}) => {
  return (
    <Form.Group
      className="show-grid row"
      controlId={input.name}
    >
      <Col md={2}>
        <Form.Label>{label}</Form.Label>
      </Col>
      <Col md={6}>
        {options.map((o, index) => {
          return <Form.Check
            key={index}
            type="radio"
            id={input.name + index}
            name={input.name}
            label={o}
            value={o}
            inline={inline}
            checked={input.value === o}
            {...input}
            {...rest}
          />
        })}
      </Col>
      <Col md={4}>
        {touched && error && <Form.Control.Feedback type='invalid'>{error}</Form.Control.Feedback>}
        {touched && warning && <Form.Control.Feedback type='invalid'>{warning}</Form.Control.Feedback>}
      </Col>
    </Form.Group>
  );
};

export default renderRadio;
```

Any help most gratefully received.
Regards,
aikidoshi

**Comment by jquense** [comment]
the props are p[assed through the underlying native input, so i don't think there is an issue in react-bootstrap. You might want to check the Formik repo for support help with that library!

**Comment by aikidoshi** [comment]
Hi Jason,

Even the radio buttons on your website (see inline radio section) don't work the way they should. They work more like individual checkboxes except that you can't turn them off once clicked.

Regards,
aikidoshi
________________________________

**Comment by aikidoshi** [comment]
This issue is still not working and I am at a loss as to how to resolve it. It has nothing to do with Formik, I am using Redux-Form 8.2.3 right now.

**Comment by jquense** [comment]
@aikidoshi the examples on the site don't work because the radios don't have a common `name` attribute. Add the same name to each radio and they work

```js
<Form>
  <div className="mb-3">
    <Form.Check name='radios' inline label="1" type='radio' id={`inline-1`} />
    <Form.Check inline name='radios' label="2" type='radio' id={`inline-2`} />
    <Form.Check
      inline
      disabled
      type='radio'
      label="3 (disabled)"
      name='radios'
      id={`inline-3`}
    />
  </div>
</Form>
```

**Comment by aikidoshi** [comment]
@jquense Thanks for the quick response. You're correct that the code you sent works in isolation but with redux-form it does not. I'm trying to get the redux-form Field to work with it as described at the beginning.

**Comment by jquense** [comment]
I don't really know how redux-form works, so I'm not sure how to get it to work. I do know that if redux-form has guidance for using plain html input radios then it will also apply to FormCheck

**Comment by jquense** [comment]
It's already demonstrated the documentation (or will be on the next update). adding a `name` to group radios is just how HTML works, there isn't any additional surprises or logic that react-bootstrap adds here

**Comment by omarish** [comment]
I ran into something similar just now. To get the checkbox working, you have to manually map `Form.Checked.checked` to `field.value` coming from Formik.

```js
export const CheckboxInput = ({ name, controlId, label, ...props }) => {
  return (
    <Form.Group controlId={controlId}>
      <Field name={name}>
        {({ field }) => (
          <Form.Check
            type="checkbox"
            label={label}
            className="text-muted no-highlight"
            {...props}
            {...field}
            checked={field.value}
          />
        )}
      </Field>
    </Form.Group>
  )
}
```
