### ISSUE TITLE
Spacing for buttons in modal-footer

### ISSUE THREAD

**Issue by taion** [react-bootstrap/react-bootstrap#347]
The spacing between the buttons in the `modal-footer` don't match the standard Bootstrap spacing (at least from the demo).

The Bootstrap demo adds a standard text space in addition to the 5px margin between the buttons. The react-bootstrap example odes not do so.

Bootstrap docs:
![image](https://cloud.githubusercontent.com/assets/3112159/5870844/5cc0fb38-a2a3-11e4-8c6d-892c3f0d3d4e.png)

react-bootstrap docs:
![image](https://cloud.githubusercontent.com/assets/3112159/5870856/64cad3da-a2a3-11e4-9bcc-3939fb6c8704.png)

**Comment by mtscout6** [comment]
Which version of Bootstrap are you using?

**Comment by taion** [comment]
This is actually on the docs, not in my use case. Compare the spacing between the buttons in the modal footer between:

http://getbootstrap.com/javascript/#modals
http://react-bootstrap.github.io/components.html#modals

It's not a problem per se, more of a minor inconsistency.

**Comment by mtscout6** [comment]
The docs at getbootstrap.com would be bootstrap version 3.3 and this library is still stuck at 3.2 (See #348 and #330). Hence the question to see if this is really a problem or just something that will be fixed when we update.

**Comment by taion** [comment]
Oh, I wasn't aware of that. It actually isn't a version-specific thing, though. It's really just this guy rearing its head again:

https://github.com/facebook/react/issues/1643

In other words, this JSX from the docs:

```
        <div className="modal-footer">
          <Button>Close</Button>
          <Button bsStyle="primary">Save changes</Button>
        </div>
```

generates the two `Button`s with no space between them, while this HTML:

```
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
```

will actually have that line break between the two `button`s, and lead to the different spacing.

I don't entirely believe that this is a problem per se. It is an inconsistency, though, due to React handling whitespace differently from how the Bootstrap examples are set up.

**Comment by taion** [comment]
Better ref than the issue: http://facebook.github.io/react/blog/2014/02/20/react-v0.9.html#jsx-whitespace

**Comment by mtscout6** [comment]
Ok, that makes perfect sense. I don't think it's worth tackling.

**Comment by mbouadeus** [comment]
How do you do spacing with react-bootstrap in jsx?
