### ISSUE TITLE
Table bordered=false does not disable borders

### ISSUE THREAD

**Issue by dpisklov** [react-bootstrap/react-bootstrap#3470]
Bootstrap has explicit styling for borderless table. If neither  `table-bordered` or `table-borderless` it defaults to semi-bordered version (with horizontal borders dividing header).
There should be a way to use `table-borderless` class. At the moment it's either `table-bordered` or nothing, according to `Table.js`:
```
      bordered && `${bsPrefix}-bordered`,
```

**Comment by taion** [comment]
We'd happily take a PR for this.

**Comment by dpisklov** [comment]
@taion done https://github.com/react-bootstrap/react-bootstrap/pull/3473

**Comment by taion** [comment]
thanks!

**Comment by dpisklov** [comment]
@taion @jquense thanks for a quick turnaround - when can I expect a release with this change included?
