### ISSUE TITLE
How to change toggle element to other than button

### ISSUE THREAD

**Issue by danksch** [react-bootstrap/react-bootstrap#3471]
I was wondering how to show the dropdown menu when clicked on linked text or an icon instead of a button. The documentation says to change the 'as' property of the Dropdown.Toggle. 

I tried it like so
`<Dropdown.Toggle as={CustomToggle}>
                        ...
                    </Dropdown.Toggle>`

where CustomToggle is just a simple functional component returning an 'a':

```
function CustomToggle() {
    return (
        <a>
        </a>
    );
}
```

I also tried to directly set the 'as' prop to "a", but neither of these did the trick. 
What am I missing ?

**Comment by taion** [comment]
Make sure you're using the v1.x beta. The prop is called `component` in earlier releases.
