### ISSUE TITLE
`Form.Control` seems to cause an issue with Enzyme attribute selector.

### ISSUE THREAD

**Issue by rally25rs** [react-bootstrap/react-bootstrap#3474]
This is about as simple a test as I can make:

```
import React from 'react';
import {mount} from 'enzyme';
import {Form} from 'react-bootstrap';

describe('forms', () => {
  it('react-bootstrap', () => {
    const component = mount(<Form.Control type="email" name="email" />);

    console.log(component.html());
    /* log output:
      <input name="email" type="email" class="form-control">
    */
    component.find('[name="email"]').forEach(x => console.log(x.html()));
    /* log output:
      <input name="email" type="email" class="form-control">
      <input name="email" type="email" class="form-control">
      <input name="email" type="email" class="form-control">
      <input name="email" type="email" class="form-control">
    */

    expect(component.find('input')).toHaveLength(1); // PASSES
    expect(component.find('[name="email"]')).toHaveLength(1); // FAILS - expected 1, received 4
  });
});
```

It seems like there are extra elements hanging around that enzyme picks up when using an attribute selector.

If I change `<Form.Control` to `<input` then my tests pass.

Any ideas what might be going on here?

**Comment by x5engine** [comment]
same problem! with meteorjs

**Comment by CallumHemsley** [comment]
Also getting this.. any work arounds for now?

**Comment by nortonwong** [comment]
Enzyme CSS selectors will match React components:

```jsx
component.find('[name="email"]').forEach(wrapper => console.log(wrapper.debug()));

LOG: <FormControl name="email" ... />
LOG: <input name="email" ... />
```

For example, `.find('FormControl[name="email"]')` matches a FormControl based on `displayName`.

The fix is to include `'input'` in your selector, or call [`hostNodes()`](https://airbnb.io/enzyme/docs/api/ShallowWrapper/hostNodes.html) to remove composite components.
```js
expect(component.find('[name="email"]').hostNodes()).to.have.lengthOf(1);
```

**Comment by jquense** [comment]
This is how enzyme works yeah. It's not always ideal but thats what the component tree _looks_ like with custom components. The stack should be shallower now b/c we've mostly switched to hooks, but there will always be at least two components that have `name` prop the wrapper and the DOM component. If you want specific ones you need to be more specific with the selector.
