### ISSUE TITLE
xsHidden (and equivalent breakpoint names) are not supported

### ISSUE THREAD

**Issue by vzaidman** [react-bootstrap/react-bootstrap#3475]
in version 1.0.0-beta.5.

I'll open a PR that implements it if there are no objections (I already created it locally on my machine)

**Comment by jquense** [comment]
I believe we left them out for this version to be consistent with how we tend to treat utility class usage elsewhere. Which is to say we generally recommend you use the classes directly for helper things like display, flex, sizing etc. We do make some exceptions for very common usages but I'm not sure if this fits into that case...

**Comment by kosmiq** [comment]
This was touched upon in #3029. It has been decided that you should simply use the classes from Bootstrap in these cases.
