### ISSUE TITLE
Search in old docs for Bootstrap 3 is broken

### ISSUE THREAD

**Issue by smtchahal** [react-bootstrap/react-bootstrap#3478]
In the [old docs](https://5c507d49471426000887a6a7--react-bootstrap.netlify.com/), typing in something in the search box (e.g. "modal") and then clicking on a search result always leads to v4's docs, rather than the old docs.

**Comment by mxschmitt** [comment]
We are currently using the same search index for Bootstrap 3 and Bootstrap 4. So the search in general should be really weird and always redirect to the v4 docs. Hmm...
I don't see here any solution except to use Google for searching.
