### ISSUE TITLE
Override css modal classes with scss or add custom class

### ISSUE THREAD

**Issue by zverexe** [react-bootstrap/react-bootstrap#3479]
Hi, I'm using Modal component and cannot override modal-content class or add some custom class to that div. I'm using **scss modules**. I cannot find in the docs appropriate way of adding custom components to the Modal except modalClassName

Please not that I'm using react-bootstrap ver 0.32 and bsPrefix doesn't work for me and I cannot override modal-content using scss because of scss modules. Could somebody help?

**Comment by taion** [comment]
use `:global` or the equivalent to interact with global styles when using modules – see the relevant docs for your module system
