### ISSUE TITLE
Modal not closing

### ISSUE THREAD

**Issue by nj167252** [react-bootstrap/react-bootstrap#3480]
I have copied the code directly and the Modal opens nicely onClick but once open the modal does not close.

**Comment by taion** [comment]
Please provide a repro if you think there's a bug here.

**Comment by nj167252** [comment]
I'm not sure there's a bug in the react-bootsrap code, maybe in mine.
`
import React, { Component } from 'react'
import Modal from 'react-bootstrap/Modal'
import Button from 'react-bootstrap/Button'

class FlightLogSummary extends Component {

  constructor(props, context) {
    super(props, context);

    this.handleShow = this.handleShow.bind(this);
    this.handleClose = this.handleClose.bind(this);

    this.state = {
      show: false,
    };
  }

  handleClose() {
    this.setState({ show: false });
  }

  handleShow() {
    this.setState({ show: true });
  }

  render() {
    // console.log(this.props)
    const { flightLog } = this.props

    return (
      <tr onClick={ this.handleShow }>
        <th scope="row">{ flightLog.flightDate }</th>
        <td>{ flightLog.flightRoute }</td>
        <td>{ flightLog.flightAircraft }</td>
        <td className="text-right">{ flightLog.flightTotal }</td>
        <Modal show={this.state.show} onHide={this.handleClose}>
          <Modal.Header closeButton>
            <Modal.Title>Modal heading</Modal.Title>
          </Modal.Header>
          <Modal.Body>Woohoo, you're reading this text in a modal!</Modal.Body>
          <Modal.Footer>
            <Button variant="secondary" onClick={this.handleClose}>
              Close
            </Button>
            <Button variant="primary" onClick={this.handleClose}>
              Save Changes
            </Button>
          </Modal.Footer>
        </Modal>
      </tr>
    )
  }
}

export default FlightLogSummary;
`

**Comment by nj167252** [comment]
What I want to do is create a modal that fires when I click on a row. Then all the data that's in the row displays in the modal. I can get all this to work except for closing the Modal. Here is the file in question:
https://github.com/nj167252/limabravo/blob/master/src/components/flights/FlightLogSummary.js

Regards,

Nick

On Feb 18, 2019, at 18:08, Jimmy Jia <notifications@github.com<mailto:notifications@github.com>> wrote:


Please provide a repro if you think there's a bug here.

**Comment by klk1010** [comment]
What version of react-bootstrap are you using?

**Comment by Tristan-D-19** [comment]
having the same issue copied code from the site directly. I also performed a check to verify if the state is changing to false but still no change.

**Comment by owenday** [comment]
Wrap the Modal with 

<div onClick={e => e.stopPropagation()}>
</div>

It's the same bug as #3105

**Comment by jquense** [comment]
Events bubble up from models, so your onClick is firing twice, first to close when you click the button in the Modal and then again on the `tr` as it bubbles up re-opening the Modal
