### ISSUE TITLE
Form.Label prop typings is missing xs, sm, md, lg, xl properties

### ISSUE THREAD

**Issue by codeandcats** [react-bootstrap/react-bootstrap#3481]
One cannot specify `xs`, `sm`, `md`, `lg`, or `xl` properties on `Form.Label` like in this [example](https://react-bootstrap.github.io/components/forms/#forms-input-Plaintext).

```jsx
  <Form.Group as={Row} controlId="formPlaintextEmail">
    <Form.Label column sm="2">
      Email
    </Form.Label>
    <Col sm="10">
      <Form.Control plaintext readOnly defaultValue="email@example.com" />
    </Col>
  </Form.Group>
```

This is because they are missing from the typings in `FormLabel.d.ts`, which was clearly copied from `Feedback.d.ts`.

```typescript
import * as React from 'react';

import { BsPrefixComponent } from './helpers';

interface FeedbackProps {
  htmlFor?: string;
  column?: boolean;
  innerRef?: React.LegacyRef<this>;
  srOnly?: boolean;
}

declare class Feedback extends BsPrefixComponent<'label', FeedbackProps> {}

export default Feedback;
```

**Comment by jquense** [comment]
Happy to take a PR for this!

**Comment by codeandcats** [comment]
@jquense Thanks. I need this soon so will gladly review it. Also happy to take it on myself if you cannot dedicate time to it immediately.

**Comment by jquense** [comment]
> . Also happy to take it on myself i

Ya that's what i was suggesting :) I don't know when i'd get to it

**Comment by codeandcats** [comment]
Oh sorry I misread your comment. 🤗

Actually I realised I can probably use 
`<Col sm={2} as={Form.Label>...</Col>`.

I’m not sure yet as I’m upgrading a 2 yr old project and working my way through all the breaking changes.

Seems like there might be 2 ways to make a label behave like a column. Should we remove one?

I am wondering whether we need the column property on `Form.Label`

**Comment by moyuanhuang** [comment]
@codeandcats Thanks that works! I noticed that you'd also have to explicitly add the `className="col-form-label"` prop, otherwise the label wouldn't have nice paddings.

<img src="https://user-images.githubusercontent.com/14947870/53308538-07761480-3857-11e9-8333-149862643bd9.png" width="300"/>

<img src="https://user-images.githubusercontent.com/14947870/53308557-25dc1000-3857-11e9-97df-db2cc1dc9d26.png" width="240"/>

**Comment by codeandcats** [comment]
@moyuanhuang thanks good catch re `col-form-label`

**Comment by dalevfenton** [comment]
@jquense I'm not sure how you guys prefer to maintain the typings, but I submitted a PR that pulls in the Column size props to the types for Form.Label
