### ISSUE TITLE
Change click trigger OverlayTrigger 

### ISSUE THREAD

**Issue by mensonones** [react-bootstrap/react-bootstrap#3482]
I have an OverlayTrigger with a PopOver and inside this a DropDown. How to prevent the click trigger from closing the overlay when selecting a DropDown item?. List itens rendered in document body. 

```
<OverlayTrigger
   trigger = "click"
  rootClose
  placement = "bottom"
  overlay = {< Popover title = "Popover bottom" > 
                  {<DropDown / >} < /Popover>} >
		<Button text = "Click" / >
		</OverlayTrigger>
```

**Comment by taion** [comment]
If you need to customize the behavior of the overlay trigger, use `<Overlay>` component directly and control the open/close state yourself.
