### ISSUE TITLE
What bootstrap version should I use?

### ISSUE THREAD

**Issue by aishahsofea** [react-bootstrap/react-bootstrap#3484]
When I hover on the navbar of the page https://react-bootstrap.github.io/getting-started/introduction/ where the version of the react-bootstrap(1.0.0-beta.5) is written, it says this library is compatible with Bootstrap v4.2. But when I installed Bootstrap v4.2, it failed to compile. I got the following warning when I installed Bootstrap with the command `yarn add bootstrap@4.2 react-bootstrap`:

```
[3/4] Linking dependencies...
warning "react-scripts > pnp-webpack-plugin > ts-pnp@1.0.0" has unmet peer dependency "typescript@*".
warning " > bootstrap@4.2.1" has unmet peer dependency "jquery@1.9.1 - 3".
warning " > bootstrap@4.2.1" has unmet peer dependency "popper.js@^1.14.6".
```

It compiles with Bootstrap v3 but my UI just looks weird. It doesn't look very Bootstrap-y. It is as if the CSS is not applied.  Also, I've imported the Bootstrap CSS in my src/index.js

```
import 'bootstrap/dist/css/bootstrap.min.css';
import 'bootstrap/dist/css/bootstrap-theme.min.css';
```

**Comment by jquense** [comment]
`4.2` is correct, the warnings you see are just warnings and not relevant to using in this context, because we don't use the bootstrap css. It would be nice to have a smaller bootstrap package that is just css on npm tho

**Comment by JeremyCarlsten** [comment]
Acccording to the [getting started page](https://react-bootstrap.github.io/getting-started/introduction#stylesheets) they point out to 4.2.1

**Comment by Akai-Shuuichi** [comment]
I use bate version, it's OK. Maybe I haven't met any bug.

**Comment by gamesover** [comment]
but in our project, bootstrap is still 3 and we have no plan moving to 4 so far, since it is such a big movement both for style and code. Can we use react-bootstrap with bootstrap 3?

**Comment by jquense** [comment]
Yes the v0.32.0 version works with bootstrap 3 and is maintained. See the migrating doc on the site for more info

**Comment by gamesover** [comment]
`v0.32.4` version works perfectly. Thank you.
