### ISSUE TITLE
Navbar loses height when hamburger opened, closed and then window is resized.

### ISSUE THREAD

**Issue by martinpsz** [react-bootstrap/react-bootstrap#3486]
Hello,

Noticed an issue where the Navbar loses height when I take the following steps:

- Open Hamburger
- Close Hamburger
- Then resize window in browser.

My code is as follows:

        `<Navbar expand="md">
         <Navbar.Toggle aria-controls="responsive-nav"/>
         <Navbar.Collapse id="responsive-nav">
          <Nav>
            <Nav.Link href="#Home">Home</Nav.Link>
            <Nav.Link href="#About">About</Nav.Link>
            <Nav.Link href="#Projects">Projects</Nav.Link>
            <Nav.Link href="#Blog">Blog</Nav.Link>
            <Nav.Link href="#Contact">Contact</Nav.Link>
          </Nav>
         </Navbar.Collapse>
      </Navbar>`

I have observed this in Chrome and in Firefox (latest versions). I have bootstrap 4.2.1 CDN loaded and the most recent version of react-bootstrap. Any ideas on what I can do to fix this issue? Only way it goes away is when I reload the browser. Thinking it might be a bug.

**Comment by taion** [comment]
dupe https://github.com/react-bootstrap/react-bootstrap/issues/3394
