### ISSUE TITLE
Publish stub type definition to DefinitelyTyped

### ISSUE THREAD

**Issue by aaronbeall** [react-bootstrap/react-bootstrap#3489]
**First of all**: awesome work on the v4/1.0.0 update! It's turned out really great, nothing short of what I expected. :)

See this issue: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/33185

My understanding is now that react-bootstrap ships with its own type definitions (sweet!) and `@latest` points to this version, there should be a [stub definition published to DT](https://github.com/DefinitelyTyped/DefinitelyTyped#removing-a-package).

**Comment by aaronbeall** [comment]
@taion Any thoughts on this? I'd be happy to make the PR on DT if there's agreement on this. Basically:
```
npm run not-needed -- react-bootstrap 1.0.0-beta.0 https://github.com/react-bootstrap/react-bootstrap "React Bootstrap"
```
And see if there are any DT libraries that depend on `react-bootstrap >= 1.0.0-beta.0` and update to depend on `react-bootstrap` instead of `@types/react-bootstrap`

**Comment by jquense** [comment]
sounds good, I don't honestly know a lot how DT works but feel free to do what is considered the best practice

**Comment by kosmiq** [comment]
Types are included for v1 and DT handles types for v3. Further discussion about how it should be handled by DT is handled in their issue. Closing this.

**Comment by aaronbeall** [comment]
@kosmiq What issue?

**Comment by kosmiq** [comment]
> @kosmiq What issue?

Sorry meant this PR https://github.com/DefinitelyTyped/DefinitelyTyped/pull/34025
