### ISSUE TITLE
Documentation for v0.32

### ISSUE THREAD

**Issue by borgdrone7** [react-bootstrap/react-bootstrap#3490]
Hi,

Is there anyway to access documentation online for Bootstrap 3 version. We are in the middle of the project and need the docs. I can download them from Git (react-bootstrap.github.io), but then I would need to setup it to run locally, not even sure how to do it.
How can I find the docs or at least run them locally?

**Comment by jquense** [comment]
ya it's linked in the readme!

**Comment by borgdrone7** [comment]
Thanks, that was fast :+1:
