### ISSUE TITLE
New Issue

### ISSUE THREAD

**Issue by maksim208** [react-bootstrap/react-bootstrap#3492]
![screen shot 2019-02-21 at 8 40 55 pm](https://user-images.githubusercontent.com/47046948/53220424-50d92080-3619-11e9-8182-a8c6263f5d7d.png)
![screen shot 2019-02-21 at 8 41 01 pm](https://user-images.githubusercontent.com/47046948/53220427-533b7a80-3619-11e9-84f5-4c27ed94facc.png)

**Comment by jquense** [comment]
looks like you don't have react-dom installed

**Comment by icfantv** [comment]
Not sure if this is related, but I started getting this when I added react-hot-loader and configured per Dan's instructions for webpack.  Namely, adding the resolve alias for `react-dom` to be `@hot-loader/react-dom`.  I'm still trying to chase it down.

Here's the error:

```
Module not found: Error: Can't resolve 'react-dom' in '/.../node_modules/react-bootstrap/es'
```

**Comment by icfantv** [comment]
Ah.  Yep.  Need to install `@hot-loader/react-dom` as a module dependency.  That fixed it.
