### ISSUE TITLE
React-Bootstrap-Modal Invariant Violation: findComponentRoot()

### ISSUE THREAD

**Issue by sevast1an** [react-bootstrap/react-bootstrap#3493]
hi))) Now i'm helping to transfer a site from plain html/js/css to a react js based site. On this attached page the bottom half is made with React, the top part not, and that's why  i have both modals generated by React and by plain html/js on the same page. 
  When i open a modal from the top part and try to write something in it's inputs I receive the error "Uncaught Invariant Violation: findComponentRoot(..., .0.4.0.0.$=11.0.0.0.0:$2.0): Unable to find element. This probably means the DOM was unexpectedly mutated (e.g., by the browser), usually due to forgetting a <tbody> when using tables, nesting tags like <form>, <p>, or <a>, or using non-SVG elements in an <svg> parent. Try inspecting the child nodes of the element with React ID ``." and I don't know why. 
  When i comment my modal created by react-bootstrap-modal, the top one works without errors. Do you know why ? And how can i solve this issue? If you need some more info just tell me
![screen shot 2019-02-22 at 9 16 58 am](https://user-images.githubusercontent.com/25949591/53226411-95010b00-3683-11e9-9b8e-bc115b467b74.png)

**Comment by taion** [comment]
`react-bootstrap-modal` is a different library. it's not this one.
