### ISSUE TITLE
Validation icons are mis-aligned for Select elements

### ISSUE THREAD

**Issue by Brondahl** [react-bootstrap/react-bootstrap#3495]
See here, my post on SO, with screen shot and demonstration code:
https://stackoverflow.com/questions/54831454/validation-for-select-elements-of-react-bootstrap-are-mis-aligned

It occurred to me, that this would probably be considered a bug, if there ISN'T already built-in work-around for it.
(Plus you guys are more likely to know about it, if there IS a known solution :) )

**Comment by Brondahl** [comment]
If there IS a work-around, then my "Issue" becomes: the docs don't say anything about the workaround for this.

**Comment by taion** [comment]
The feedback isn't guaranteed to render correctly unless you're using `.custom-select`. Though we should probably extend https://github.com/react-bootstrap/react-bootstrap/pull/3343 to support the other custom form inputs as well.
