### ISSUE TITLE
TabPane with unmountOnExit should retain transition

### ISSUE THREAD

**Issue by sisp** [react-bootstrap/react-bootstrap#3497]
I would have expected `TabPane` to retain the transition even when `unmountOnExit` is `true`, but looking at the [the source](https://github.com/react-bootstrap/react-bootstrap/blob/08510be5802874ae975c9fbc851cc2b3d61b16e9/src/TabPane.js#L112) `null` is returned immediately rather than when `onExited` is triggered. Is this intended?

**Comment by jquense** [comment]
It should retain the transition, active isn't toggled to false until the transition calls it's onExited callback, at which point we render null so it's unmounted

**Comment by sisp** [comment]
I can't confirm that the transition is happening and unless I'm missing anything I don't see how it should happen given the source code.

The following [snippet](https://github.com/react-bootstrap/react-bootstrap/blob/08510be5802874ae975c9fbc851cc2b3d61b16e9/src/TabPane.js#L162-L165) shows how the `active` prop is determined from the context:
```js
active:
  props.active == null && key != null
    ? makeEventKey(activeKey) === key
    : props.active,
```
The `<Transition />` component animates the transition when the `active` prop changes. But when `unmountOnExit === true` the `<Transition />` component is not rendered with `active === false` because `null` is returned immediately (see [here](https://github.com/react-bootstrap/react-bootstrap/blob/08510be5802874ae975c9fbc851cc2b3d61b16e9/src/TabPane.js#L112)).

**Comment by jquense** [comment]
Sorry are you saying it is working but you don't understand why or it's not working?

**Comment by sisp** [comment]
It's not working for me and the source code doesn't look like it's doing the right thing either.

**Comment by jquense** [comment]
Ok probably a bug then

**Comment by sisp** [comment]
I've put together a small example based on the [custom tabs layout](https://react-bootstrap.netlify.com/components/tabs/#tabs-custom-layout) example from the docs: https://codesandbox.io/s/xl5n993np4

Change the `unmountOnExit` prop of the `App` component to see the difference and notice that `unmountOnExit === false` prevents animated transitions. (I need to open the preview in a new window in order for the tabs to be clickable - not sure why.)

**Comment by jquense** [comment]
yup you're right, I think that one line should be `!active && !Transition && unmountOnExit`

**Comment by fungjj92** [comment]
Bump! Hi project maintainers. Can we get the proposed fix above in? I can make a PR if you'd like. I actually started, but thought I'd bump this issue first before putting in too much time to accumulate PR detail. Happy to do whatever is most helpful! Thanks.

**Comment by taion** [comment]
We'd be happy to take a PR here.

**Comment by taion** [comment]
fixed in https://github.com/react-bootstrap/react-bootstrap/pull/4312
