### ISSUE TITLE
why was noCaret removed?

### ISSUE THREAD

**Issue by csepulv** [react-bootstrap/react-bootstrap#3499]
As `noCaret` was removed from `Dropdown` (noted in [migrating doc](https://github.com/react-bootstrap/react-bootstrap/blob/master/www/src/pages/migrating.mdx)), what is the best way to remove the caret?

I prefer a way to overriding this on the instance, instead of changing the global style.

Thanks

**Comment by jquense** [comment]
It was removed from bootstrap generally. Or specifically the caret isn't a physical element we can remove it's on a case psuedo selector. You'd need to add a style to hide it via a class or similar

**Comment by jefelewis** [comment]
This worked for me!

```css
.dropdown-toggle::after{
    display: none;
}
```

**Comment by radu-cs** [comment]
Hey there,
you can use:
`bsPrefix='dropdown'`
this will override the class dropdown-toggle getting rid of the caret.

**Comment by DanielFlaum** [comment]
> It was removed from bootstrap generally. Or specifically the caret isn't a physical element we can remove it's on a case psuedo selector. You'd need to add a style to hide it via a class or similar

I'm using Bootstrap 5, but this solution for 4 worked for me: https://stackoverflow.com/questions/38576503/how-to-remove-the-arrow-in-dropdown-in-bootstrap-4/44577512#44577512. They say:

> Simply remove "dropdown-toggle" class from the element. The dropdown will still work if you have the data-toggle attribute

So shouldn't it be possible for the `noCaret` option to be added back by having it control whether the `dropdown-toggle` class is used?
