### ISSUE TITLE
ES6 imports and exports are not completly valid for ES6

### ISSUE THREAD

**Issue by faassen** [react-bootstrap/react-bootstrap#350]
I'm using jspm to import modules the ES6 way. At first I tried this:

```
import {ListGroup, ListGroupItem} from 'react-bootstrap';
```

this resulted in ``undefined`` for both though. Instead I had to use this:

```
import ListGroup from 'react-bootstrap/ListGroup';
import ListGroupItem from 'react-bootstrap/ListGroupItem';
```

I may be getting this entirely wrong as I'm still learning all this, but I thought I'd point it out in case it's an issue on your side.

**Comment by mtscout6** [comment]
Are you still seeing this with the latest version?

**Comment by mtscout6** [comment]
We are now building all our source from ES6 using [babel](http://babeljs.io) so this should work. Are you still seeing this issue?

**Comment by faassen** [comment]
I haven't tried this with jspm for a long time as I switched to webpack. With webpack I don't see this issue, though. I'm okay with closing this issue.

**Comment by zerotacg** [comment]
in index.js [1] you are only exporting an object as default so you can only do

    import bootstrap from "react-bootstrap";
    var {ListGroup, ListGroupItem} = bootstrap; // destructuring
    ListGroup = bootstrap.ListGroup; // alternatively use the exported object directly

if you check what is exported you'll see that there is only a "default" export

    import * as bootstrap from "react-bootstrap";
    console.log( bootstrap );

you can however directly use the correct file

    import ListGroup from "react-bootstrap/lib/ListGroup"; // works on 0.24.0-alpha.1
    import ListGroup from "react-bootstrap/src/ListGroup"; // should work on current version
    console.log( ListGroup );

if index.js [1] would be adjusted to also export each class separately, besides the default, the first import mentioned by @faassen would work.

[1] https://github.com/react-bootstrap/react-bootstrap/blob/master/src/index.js

sry for commenting on an closed issue, just came across the same problems :)

**Comment by mtscout6** [comment]
I do recall seeing somewhere in either some babel documentation or elsewhere that this was an issue. If there is a more current and valid way to export all the component from our index.js I'm all ears. I'm busy with other things at the moment but we gladly take Pull Requests.

**Comment by mtscout6** [comment]
@zerotacg I'm not completely familiar with jspm, were you expecting the `src` folder to be in the npm release? We did remove that not too long ago.

**Comment by taion** [comment]
If we use `es7.exportExtensions` (IMO we should be using all Babel stage 1 transforms at least), we can re-write `index.js` as

```js
export Accordion from './Accordion';
export Affix from './Affix';
// ...
```

That said, the transpiled code from Babel isn't terribly different - you end up with all the properties defined on `exports`, rather than with `module.exports` set to an object. I don't see how that'd meaningfully fix anything, but it might be worth doing anyway.

**Comment by mathieumg** [comment]
You could leverage Lee Byron's https://github.com/leebyron/ecmascript-more-export-from (available as a stage 1 experimental transform in Babel) which would allow you to do:

Well, @taion beat me to the rest so I'll stop here.

**Comment by jquense** [comment]
Had a discusion on the babel Slack about something related to this. the current way of being able to do 
```js
export default {
  Accordion 
}
///
import { Accordion } from 'react-bootstrap'
```

if allowed is a bug, and it is a consequence of the CommonJS interop and not really a valid import  pattern for es6 modules. If some one uses `require()` to import, the destructuring will actually work fin, but using the es6 import it will not.

as @zerotacg said the proper way to export the modules is to import them and then

`export { Accordian, ListGroupItem, ... }`

**Comment by taion** [comment]
On closer inspection, we can't quite do this. Making this change would break anybody who does (using Babel)

```js
import ReactBootstrap from 'react-bootstrap';
```

They'd have to change it to e.g.

```js
import * as ReactBootstrap from 'react-bootstrap';
```

This is a bit of an odd use case, since I don't see why you wouldn't just import from `react-bootstrap/lib/*`, but whatever.

What do you guys think? Is it worth making this change for v0.24?

**Comment by jquense** [comment]
I tend to think that allowing individual imports gives the impression that you are getting modular code, when you are importing everything and then only pulling in the one. I prefer the explicit step by a user for that, plus its an annoying breaking change, grepable, but annoying. I wouldn't think its worth it

**Comment by taion** [comment]
Also a visible breaking change - we'd need to instead do

```js
import * as FormControls from '../src/FormControls';
```

Instead of the current

```
import FormControls from '../src/FormControls';
```

Assuming I make the same change to `src/FormControls/index.js`.

**Comment by mtscout6** [comment]
That would make sense, in that case the `utils/index` would also need this.

**Comment by mtscout6** [comment]
As to the question of worth I do think it's worth ensuring that we comply with ES6 as much as possible. Yes this change should go to the `v0.24.0-rc` branch if it's going to break downstream users. In that case as well is it worth putting in a deprecation warning if we can detect that they are using babel and directly importing any of the index files? Even if the warning is just a note that it will need to be changed in v0.24, or should we just rely on the entry in the changelog to describe this.

**Comment by jquense** [comment]
just to be clearn, the current doesn't not comply with es6, it is a totally valid way to export modules. It won't break, if imported correctly `import Bootstrap from 'react-bootstrap'

**Comment by taion** [comment]
This is only a breaking change to people using ES6 modules. In other words:

```js
import ReactBootstrap from 'react-bootstrap';  // bad
import * as ReactBootstrap from 'react-bootstrap';  // ok
var ReactBootstrap = require('react-bootstrap');  // ok

import FormControls from 'react-bootstrap/FormControls';  // bad
import * as FormControls from 'react-bootstrap/FormControls';  // ok
var FormControls = require('react-bootstrap/FormControls');  // ok
```

**Comment by taion** [comment]
I'm not 100% on this being the right thing to do, but I had the code written, so I sent in the PR.

**Comment by mtscout6** [comment]
If the import destructuring wouldn't work though in pure ES6 does it really comply? For example:

```
import { Alert } from 'react-bootstrap';
```

**Comment by taion** [comment]
It's not destructuring per se, although it's a bit confusing that it looks like it. The default export is just a special named export that's named `default`. So when you do e.g.

```js
import Alert from 'react-bootstrap/lib/Alert';
```

That's just syntactic sugar for

```js
import {default as Alert} from 'react-bootstrap/lib/Alert';
```

There's no opportunity for destructuring here, which is confusing and a bit of a small wart.

**Comment by mtscout6** [comment]
Makes sense, thanks for the clarification.

**Comment by jquense** [comment]
> If the import destructuring wouldn't work though in pure ES6 does it really comply?

sure the we don't export multiple things so it makes no sense to destructure it. just like this which is functionally equivalent to what we have:

```js
var obj = { 
  a: { b: 'hi'. c: 'hi' }
 }
// we don't think that this should work
let { b,c } = obj
```

I will completely admit I am being pedantic about this :) but only because its a breaking change to fix something that isn't technically broken.

**Comment by jquense** [comment]
oops @taion  beat me too it

**Comment by taion** [comment]
Oh, sorry, I misread what you said - it's not strictly compliant if we want people to be able to do

```js
import {Alert} from 'react-bootstrap';
```

But I don't believe we explicitly documented that we supported that syntax anywhere. As transpiled right now,

```js
var {Alert} = require('react-bootstrap');
```

is totally fine, though, and I'd expect any reasonable transpilation to preserve its functionality regardless of whether we use named exports, or whether we default-export a keyed object.

**Comment by mtscout6** [comment]
Do we still need to have `export default { Alert, ... }` so we don't break the users that are using our concatenated build? Since that build uses UMD which will add a global ReactBootstrap variable, which some users are using for quick scaffolding without a build system in place yet. In there case they are doing something like:

```
<ReactBootstrap.Button>I'm a button</ReactBootstrap.Button>
```

**Comment by mtscout6** [comment]
Should we move this discussion to the PR?

**Comment by zerotacg** [comment]
I kind of feel like I set of an avalanche. I didn't mean to say the current way is wrong I merely was giving a possible workaround.
`import ListGroup from "react-bootstrap/lib/ListGroup";` works for me using jspm and the package it downloads.
As for the fix. I'd vote for keeping the current default export along side the extra exports for compatibility.
In the long run I'd say it depends on how developers in general want to use the module syntax.
Is there an advantage of using

    import {Alert} from ...
    <Alert>...</Alert>

over

    import ReactBootstrap from ...
    <ReactBootstrap.Alert></ReactBootstrap.Alert>

well except from the length obviously?

**Comment by AlexKVal** [comment]
Fixed by #824

**Comment by daniel-leibovic** [comment]
I wanted to let you know that I was confused about how to import with ES6 syntax, and I did not find an answer in documentation. Had to parse through this thread to find the answer, so maybe consider adding this to the Getting Started section of your website.

I tried this:
```
import bootstrap from 'react-bootstrap';
import { Button } from bootstrap;
```

but in fact have to do this:
```
import { Button } from 'react-bootstrap';

```

**Comment by AlexKVal** [comment]
@daniel-leibovic thank you for pointing to this out :cherries: 
I've created #1115 issue for this :sparkle:
