### ISSUE TITLE
Spelling mistake in documentation for Alert component

### ISSUE THREAD

**Issue by andrewnystrom** [react-bootstrap/react-bootstrap#3503]
The documentation mentions that you can pass the dismissable prop to the Alert component as noted below:

> Add the dismissable prop to add a functioning dismiss button to the Alert.

I just wanted to note that it should be, "dismissible." 

For consistency, it's possible that the `AlertDismissable` class in `DismissableControlled.js` should be updated to `AlertDismissible`, and further, the file be renamed to `DismissibleControlled.js`.

Thanks!

**Comment by taion** [comment]
thanks – want to send in a quick PR?

**Comment by andrewnystrom** [comment]
@taion -- Happy to submit a PR later today. :)

**Comment by mxschmitt** [comment]
@jquense this issue can be closed right?
