### ISSUE TITLE
Validated Form doesn't honour isValid and isInvalid props

### ISSUE THREAD

**Issue by Brondahl** [react-bootstrap/react-bootstrap#3505]
If I define `<Form validated>`, and then inside that I have `<Form.Control isInvalid={true}>` then it still displays as valid.

Looking briefly at the CSS, it looks like the relevant NotValid classes are being put on the inputs, but the :valid css rules are taking precedence over the .is-invalid css rules, so they don't apply.

IMO this is a bug, but if this is intended behaviour, then I think `<Form validated>` needs a better name and better documentation. I would suggest `<Form useNativeValidation>`, as a first guess?

**Comment by sangregoriopaolo** [comment]
Same, how can one get isValid/isInvalid props to work?

**Comment by gburchfield** [comment]
I am also having this issue and agree that it is a bug.  I can't enable the invalid styles to show with `<Form.Control isValid={false}>` either when I have `<Form validated>`

If this is a CSS precedence issue then this is something that should be corrected in Bootstrap

**Comment by rodrigoyoshida** [comment]
I am facing the same issue here. Since this issue has been opened for about a year and nobody answered, I guess they do not have plans to solve it.

**Comment by kosmiq** [comment]
Is this bug caused by react-bootstrap or by Bootstrap itself? Can you set up a reduced test scenario where you reproduce the issue?

**Comment by jquense** [comment]
There is nothing to solve here. The selectors for native validation take precedence, or the manually ones. They aren't meant to be combined. The manual styles are for use _instead_ of native validation.

If this doesn't seem ideal please open an issue upstream with bootstrap since it's css specific.

**Comment by Brondahl** [comment]
@jquense As per the original Issue:

> [...] if this is intended behaviour, then I think `<Form validated>` needs a better name and better documentation. I would suggest `<Form useNativeValidation>`, as a first guess?

The current tags/options give the appearance that they should be combinable. Naming them differently would solve this confusion.
