### ISSUE TITLE
Class "carousel-item" listed twice per item div

### ISSUE THREAD

**Issue by jokokoloko** [react-bootstrap/react-bootstrap#3508]
The "carousel-item" class is listed twice per item div.

![image](https://user-images.githubusercontent.com/5240653/53549092-29d29100-3ae8-11e9-8d56-d05947aa9b9b.png)

**Comment by taion** [comment]
getting injected from parent as well... i guess it doesn't make sense to go fully context-based here, though

**Comment by bpas247** [comment]
#3508 closes this issue,
