### ISSUE TITLE
Some valid Glyphicon options give console warnings.

### ISSUE THREAD

**Issue by delaneyj** [react-bootstrap/react-bootstrap#351]
For example "piggy-bank" & "sunglasses" are valid (and working entries) for Glyphicon but gives a console warning of ```Warning: Invalid prop `glyph` of value `piggy-bank` supplied to `Glyphicon`, expected one of [...]```

**Comment by mtscout6** [comment]
Does #349 solve this?

**Comment by delaneyj** [comment]
Yes, I'm using the npm version so I'll update when its released, thanks!
