### ISSUE TITLE
react-bootstrap - issue with ie11

### ISSUE THREAD

**Issue by dcp12345678** [react-bootstrap/react-bootstrap#3510]
I'm not able to get react-bootstrap to work with IE11. Here is what I did:

    1. create-react-app test-app, then cd to test-app folder
    2. npm install --save bootstrap
    3. npm install --save react-bootstrap
    4. npm start (application opens in IE11 ok at this point)
    5. Close browser and cancel the npm start operation
    6. Edit App.js and add the following line at the top:
        import Button from 'react-bootstrap/Button';
    7. Run npm start again and open app in IE11. Browser screen is blank.

I checked the javascript Console but did not see any errors.

Any ideas on how to make this work?

**Comment by mxschmitt** [comment]
React does only support the modern Browsers by default: https://facebook.github.io/create-react-app/docs/supported-browsers-features#supported-browsers

So you have to use a Polyfill e.g. this one: https://github.com/facebook/create-react-app/blob/master/packages/react-app-polyfill/README.md

**Comment by dcp12345678** [comment]
Thank you for the help, your suggestion solved the issue.
