### ISSUE TITLE
Overlaytrigger/tooltip positioning problem in a small width target

### ISSUE THREAD

**Issue by MHA15** [react-bootstrap/react-bootstrap#3512]
I have a small button in a toolbar and I had use tooltip on it and it was work on previous version (0.32) but in new version (1.0 beta 5) It's position have problem (showed in picture)
![image in new version](https://user-images.githubusercontent.com/30382711/53681707-9923cd00-3d02-11e9-8c44-11aa1e9908dc.png)

**Comment by taion** [comment]
please post a repro

**Comment by mxschmitt** [comment]
@MHA15 please also try to reproduce it with the official [bootstrap](https://getbootstrap.com/) examples (only divs etc.), so we can exclude `react-bootstrap`. If this is the case, that in the normal version it work's, we can dig more deeper into this issue. But for now we need an example, that we can reproduce it in a repository e.g.

Due there was no response for 12 days, I will close this issue for now. If you have more info, just ping me and I will reopen it. 👍
