### ISSUE TITLE
Console warning: prop bodyContainer

### ISSUE THREAD

**Issue by Laviro** [react-bootstrap/react-bootstrap#3513]
Hi, thanks for the awesome work !!
Getting this console warning:
```
Warning: The prop `bodyContainer` of `TypeaheadContainer(WrappedTypeahead)` is deprecated. Use `positionFixed` instead.
```
I am not using such a prop, any thoughts why does it happen?

Thanks

**Comment by jquense** [comment]
hmm, I can't fine any place we are using it either, i don't think this is related to react-bootstrap

**Comment by Laviro** [comment]
here is the full warning:

![selection_025](https://user-images.githubusercontent.com/26363699/53739617-dde26c00-3e9a-11e9-8a69-e8e5aa763d5f.png)

**Comment by taion** [comment]
i'm pretty sure that's coming from the library that's actually providing those components

**Comment by Laviro** [comment]
From a snapshot test it seem that this prop does come from the component:

![selection_028](https://user-images.githubusercontent.com/26363699/53741509-403d6b80-3e9f-11e9-9da9-65c4b01ea023.png)

**Comment by taion** [comment]
that's not in this library

**Comment by Laviro** [comment]
sorry, wow.. my bad :rofl: 
I was sure I am in `react-bootstrap-typeahead`
I will open an issue to change their name
