### ISSUE TITLE
I use ReactStrict Mode and you have some issues

### ISSUE THREAD

**Issue by AdamKyle** [react-bootstrap/react-bootstrap#3518]
So I am currently using the `OverLay` and `ToolTip` and the following errors with `React.StrictMode` appear:

```js
game.js:18461 Warning: Unsafe lifecycle methods were found within a strict-mode tree:

componentWillReceiveProps: Please update the following components to use static getDerivedStateFromProps instead: WaitForContainer

Learn more about this warning here:
https://fb.me/react-strict-mode-warnings
warningWithoutStack @ game.js:18461
(anonymous) @ game.js:28408
./node_modules/react-dom/cjs/react-dom.development.js.ReactStrictModeWarnings.flushPendingUnsafeLifecycleWarnings @ game.js:28385
commitAllLifeCycles @ game.js:35528
callCallback @ game.js:18104
invokeGuardedCallbackDev @ game.js:18154
invokeGuardedCallback @ game.js:18211
commitRoot @ game.js:35737
completeRoot @ game.js:37189
performWorkOnRoot @ game.js:37144
performWork @ game.js:37019
performAsyncWork @ game.js:36993
flushFirstCallback @ game.js:44595
flushWork @ game.js:44707
./node_modules/scheduler/cjs/scheduler.development.js.channel.port1.onmessage @ game.js:45068
game.js:18461 Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of RefHolder which is inside StrictMode. Instead, add a ref directly to the element you want to reference.

    in div (created by Map)
    in RefHolder (created by OverlayTrigger)
    in OverlayTrigger (created by Map)
    in div (created by Map)
    in div (created by Map)
    in div (created by Map)
    in div (created by Map)
    in div (created by Map)
    in Map (created by CharacterSideDetails)
    in div (created by CharacterSideDetails)
    in CharacterSideDetails (created by Game)
    in div (created by Game)
    in div (created by Game)
    in div (created by Game)
    in Game
    in ConcurrentMode

Learn more about using refs safely here:
https://fb.me/react-strict-mode-find-node
warningWithoutStack @ game.js:18461
findHostInstanceWithWarning @ game.js:37412
findDOMNode @ game.js:37914
OverlayTrigger._this.getTarget @ game.js:15208
getTarget @ game.js:39973
componentDidMount @ game.js:39956
commitLifeCycles @ game.js:34172
commitAllLifeCycles @ game.js:35541
callCallback @ game.js:18104
invokeGuardedCallbackDev @ game.js:18154
invokeGuardedCallback @ game.js:18211
commitRoot @ game.js:35737
completeRoot @ game.js:37189
performWorkOnRoot @ game.js:37144
performWork @ game.js:37019
performAsyncWork @ game.js:36993
flushFirstCallback @ game.js:44595
flushWork @ game.js:44707
./node_modules/scheduler/cjs/scheduler.development.js.channel.port1.onmessage @ game.js:45068
game.js:18461 Warning: Legacy context API has been detected within a strict-mode tree: 

Please update the following components: Transition

Learn more about this warning here:
https://fb.me/react-strict-mode-warnings
warningWithoutStack @ game.js:18461
(anonymous) @ game.js:28572
./node_modules/react-dom/cjs/react-dom.development.js.ReactStrictModeWarnings.flushLegacyContextWarning @ game.js:28562
commitAllLifeCycles @ game.js:35529
callCallback @ game.js:18104
invokeGuardedCallbackDev @ game.js:18154
invokeGuardedCallback @ game.js:18211
commitRoot @ game.js:35737
completeRoot @ game.js:37189
performWorkOnRoot @ game.js:37144
performWork @ game.js:37019
performAsyncWork @ game.js:36993
flushFirstCallback @ game.js:44595
flushWork @ game.js:44707
./node_modules/scheduler/cjs/scheduler.development.js.channel.port1.onmessage @ game.js:45068
game.js:18461 Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of Transition which is inside StrictMode. Instead, add a ref directly to the element you want to reference.

    in div (created by Tooltip)
    in Tooltip (created by Context.Consumer)
    in ForwardRef(Bootstrap(Tooltip)) (created by InnerPopper)
    in Transition (created by Fade)
    in Fade (created by InnerPopper)
    in InnerPopper (created by Context.Consumer)
    in Popper (created by Overlay)
    in WaitForContainer (created by Portal)
    in Portal (created by Overlay)
    in Overlay (created by WaitForContainer)
    in WaitForContainer (created by ForwardRef(withContainer(Overlay)))
    in ForwardRef(withContainer(Overlay)) (created by Overlay)
    in Overlay (created by OverlayTrigger)
    in OverlayTrigger (created by Map)
    in div (created by Map)
    in div (created by Map)
    in div (created by Map)
    in div (created by Map)
    in div (created by Map)
    in Map (created by CharacterSideDetails)
    in div (created by CharacterSideDetails)
    in CharacterSideDetails (created by Game)
    in div (created by Game)
    in div (created by Game)
    in div (created by Game)
    in Game
    in ConcurrentMode

Learn more about using refs safely here:
https://fb.me/react-strict-mode-find-node
```

You might be thinking, these come from your app and your components. But If I take out, in the `map.jsx` component:

```js
renderPortPins() {
    let portPins = [];

    this.state.ports.forEach((port) => {
      portPins.push(
        <OverlayTrigger
          key={port.id}
          placement={'top'}
          overlay={
            <Tooltip id={`tooltip-top`}>
              {port.name}
            </Tooltip>
          }
        >
          <div key={port.id} className="map-port-pin" style={{top: port.y + 'px', left: port.x + 'px'}}></div>
        </OverlayTrigger>
      )
    });

    return portPins
  }
```

Then the errors go away. But I would rather keep the tooltips.

I wouldn't say this is something you have to fix right now, but its something to keep in mind.

**Comment by jquense** [comment]
we'll be using `findDOMNode` for the foreseeable future, due to have no good alternative with refs right now. Will be addressed with it's removal is more pressing or the deprecation stops being opt-in 👍

**Comment by Guria** [comment]
Some components use default `uncontrollable` no hooks version which uses componentWillMount and componentWillReceiveProps

**Comment by makhataibar** [comment]
index.js:1446 Warning: Unsafe lifecycle methods were found within a strict-mode tree:
    in StrictMode (at src/index.jsx:13)

componentWillMount: Please update the following components to use componentDidMount instead: Uncontrolled(Tabs)

componentWillReceiveProps: Please update the following components to use static getDerivedStateFromProps instead: Uncontrolled(Tabs)

Learn more about this warning here:
https://fb.me/react-strict-mode-warnings

**Comment by makhataibar** [comment]
index.js:1446 Warning: Legacy context API has been detected within a strict-mode tree: 
    in StrictMode (at src/index.jsx:13)

Please update the following components: Transition

Learn more about this warning here:
https://fb.me/react-strict-mode-warnings

**Comment by edpike109** [comment]
I think this is a similar issue:
`index.js:1437 Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of Transition which is inside StrictMode. Instead, add a ref directly to the element you want to reference.

    in div (created by Context.Consumer)
    in Transition (created by Collapse)
    in Collapse (created by Context.Consumer)
    in NavbarCollapse (at NavBarTop.js:42)
    in nav (created by Navbar)
    in Navbar (created by Uncontrolled(Navbar))
    in Uncontrolled(Navbar) (created by ForwardRef)
    in ForwardRef (created by Bootstrap(undefined))
    in Bootstrap(undefined) (at NavBarTop.js:25)
    in NavBarTop (created by ConnectFunction)
    in ConnectFunction (at App.js:22)
    in div (at App.js:21)
    in StrictMode (at App.js:20)
    in App (at src/index.js:20)
    in Router (created by ConnectedRouter)
    in ConnectedRouter (created by Context.Consumer)
    in ConnectedRouterWithContext (created by ConnectFunction)
    in ConnectFunction (at src/index.js:19)
    in Provider (at src/index.js:18)

Learn more about using refs safely here:
https://fb.me/react-strict-mode-find-node`

**Comment by lourenci** [comment]
I've the same issues with the `<Modal />`.

**Comment by andrewaedwards** [comment]
Is react-bootstrap < 1.0.0 going to be supported into react 17 or should we be updating to > 1.0.0?

**Comment by achung89** [comment]
Would love an answer to @andrewaedwards question

**Comment by bertho-zero** [comment]
react-bootstrap must update version 0.x and 1.
Enterprises do not necessarily want to migrate from bootstrap 3 to 4.

**Comment by jquense** [comment]
@bertho-zero Enterprises can donate time or money then to help make that happen then! This project is run by volunteers there is no explicit or implied LTS commitment to large companies

**Comment by bertho-zero** [comment]
Enterprises !== large companies and I'm just a developper.

Business or not, still a lot of people use bootstrap 3 and can not migrate at once.

**Comment by taion** [comment]
we did publish a new release in the 0.x series that should work with the newest react versions, btw

**Comment by bertho-zero** [comment]
It is compatible with the latest version but not the next, if we use StrictMode we can quickly see the problems that react-bootstrap can meet.

**Comment by amelspahic** [comment]
> Modal

I have the same problem and the only way I figured it out is to set `animation={false}`. Looks somewhat ugly, but it is what it is. Or create your own Modal :D

**Comment by SakalSo** [comment]
transition={false} works for now

**Comment by stefaneidelloth** [comment]
animation={false} and transition={false} did not work for me. Related SO question:
https://stackoverflow.com/questions/60868969/warning-finddomnode-is-deprecated-in-strictmode-when-using-react-bootstrap-navb
