### ISSUE TITLE
Remove trailing semicolon in the form

### ISSUE THREAD

**Issue by muthusrinivasan-a** [react-bootstrap/react-bootstrap#3520]
[<Form>
  <Form.Row>
    <Col>
      <Form.Control placeholder="First name" />
    </Col>
    <Col>
      <Form.Control placeholder="Last name" />
    </Col>
  </Form.Row>
</Form>;](https://react-bootstrap.github.io/components/forms/)

Not sure why we will have a **;** in the last. Please update the code snippets

**Comment by muthusrinivasan-a** [comment]
Hi Philip,

It is there in most of the form component examples. Observed that it is just updated only in the above example mentioned. Can you please update the other examples too?

ex : Sizing, Plaintext

in the Sizing, I can see only the empty parent element.

**Comment by mxschmitt** [comment]
As mentioned here: https://github.com/react-bootstrap/react-bootstrap/pull/3529#issuecomment-470832914

But if we add `semi: false` it would also cause this issue: https://github.com/prettier/prettier/issues/3196
Maybe there is a workaround for that but nothing found so far.
