### ISSUE TITLE
Blurry text in tooltip

### ISSUE THREAD

**Issue by jamesrichard91** [react-bootstrap/react-bootstrap#3521]
When I use the Overlay and Tooltip as shown, the text is very blurry. I have figured out that the transform that is being used to position the tooltip is causing the issue. I have attached screenshots with the before and after while editing the style in the browser inspector.
```java
                <span
                    className="fa fa-question-circle descriptionIcon"
                    onClick={() => this.setState({ showDescription: !showDescription })}
                    ref={(icon) => {
                        this.target = icon;
                    }}
                />
                <Overlay
                    rootClose
                    placement="top"
                    show={showDescription}
                    onHide={() => this.setState({ showDescription: false })}
                    target={() => this.target}
                    container={this}
                >
                    <Tooltip id="description-tooltip">
                        {description}
                    </Tooltip>
                </Overlay>
```
Original: 
![originalblurrytooltip](https://user-images.githubusercontent.com/12814963/53917948-bb378b00-4033-11e9-8f5c-89b6873b1d1e.png)
![originalelementstyle](https://user-images.githubusercontent.com/12814963/53917949-bbd02180-4033-11e9-9788-35e3b913eb1a.png)

Fixed:
![cleartooltip](https://user-images.githubusercontent.com/12814963/53917946-bb378b00-4033-11e9-8e48-0b6fcbfd0ffd.png)
![modifiedelementstyle](https://user-images.githubusercontent.com/12814963/53917947-bb378b00-4033-11e9-8dd8-6c49aff55adc.png)

**Comment by taion** [comment]
we just match the upstream in using popper here. perhaps you're looking for https://github.com/twbs/bootstrap/issues/22610

**Comment by Alpha-Dolphi** [comment]
I found a solution for anyone still looking for an answer. You just need to replace transform with left and top like so 

if (this.state.opened) {
			const ref = this.tooltipRef.current;

			const tooltip = ref.parentNode.parentNode;

			setTimeout(() => {
				const transform = tooltip.style.getPropertyValue('transform')

				const regex = /translate3d\(([^,]+),\s*([^,]+)/;
				const match = transform.match(regex);

				if (match) {
  					const firstValue = match[1];
  					const secondValue = match[2];

					tooltip.style.transform = "none";
					tooltip.style.left = firstValue;
					tooltip.style.top = secondValue;
				}
			}, 0)
		}
