### ISSUE TITLE
Can NavDropdown be also a link clickable but still able to tabable on keyboard?

### ISSUE THREAD

**Issue by kenlu89** [react-bootstrap/react-bootstrap#3525]

**Comment by kenlu89** [comment]
This is the default bootstrap dropdown navigation. 

` <Navbar bg="light" expand="lg" className="navbar navbar-dark flex-column flex-md-row bg-primary">
      <Navbar.Brand href="#home"></Navbar.Brand>
      <Navbar.Toggle aria-controls="basic-navbar-nav" />
      <Navbar.Collapse id="basic-navbar-nav">
        <Nav bsStyle="tabs" className="mr-auto">
          <Nav.Link href="#home">Home</Nav.Link>
          <Nav.Link href="#link">Link</Nav.Link>
          <NavDropdown title="Dropdown" href="MakeThisAlinkTo?" id="collasible-nav-down">
              <NavDropdown.Item href="#action/3.1">Action</NavDropdown.Item>
              <NavDropdown.Item href="#action/3.2">Another action</NavDropdown.Item>
              <NavDropdown.Item href="#action/3.3">Something</NavDropdown.Item>
              <NavDropdown.Divider />
              <NavDropdown.Item href="#action/3.4">Separated link</NavDropdown.Item>
          </NavDropdown>
        </Nav>
      </Navbar.Collapse>
    </Navbar>  `

**Comment by taion** [comment]
Can you clarify what you mean?

**Comment by kenlu89** [comment]
> Can you clarify what you mean?

This current example the parent dropdown menu item is not linkable. I wanted the parent items of the dropdown menu to also be clickable. Does this make sense?

**Comment by jquense** [comment]
replace `bsStyle` with `variant`

**Comment by TashTenner** [comment]
Hi there, having the same issue that I cannot make <NavDropdown> clickable. Any idea how I can do that? 

see: title="Link2" as={Link} to="/link2"

Thanks!

`<Navbar collapseOnSelect expand="lg" fixed="top">
      <Navbar.Brand as={Link} to="/">Name</Navbar.Brand>
      <Navbar.Toggle aria-controls="responsive-navbar-nav" />
      <Navbar.Collapse id="responsive-navbar-nav">
        <Nav className="ml-auto">
          <Nav.Link eventKey={1} as={Link} to="/link1">Link1</Nav.Link>
          <NavDropdown eventKey={2} title="Link2" as={Link} to="/link2" id="collasible-nav-dropdown">
            <NavDropdown.Item eventKey={2.1} as={Link} to="/link2/a">a</NavDropdown.Item>
            <NavDropdown.Item eventKey={2.2} as={Link} to="/link2/b">b</NavDropdown.Item>
            <NavDropdown.Item eventKey={2.3} as={Link} to="/link2/c">c</NavDropdown.Item>
            <NavDropdown.Item eventKey={2.4} as={Link} to="/link2/d">d</NavDropdown.Item>
          </NavDropdown>
          <Nav.Link eventKey={3} as={Link} to="/link3">Link3</Nav.Link>
        </Nav>
      </Navbar.Collapse>
    </Navbar>`

**Comment by TashTenner** [comment]
Hi there, having the same issue that I cannot make <NavDropdown> clickable. Any idea how I can do that? 

see: title="Link2" as={Link} to="/link2"

Thanks!

<Navbar collapseOnSelect expand="lg" fixed="top">
      <Navbar.Brand as={Link} to="/">Name</Navbar.Brand>
      <Navbar.Toggle aria-controls="responsive-navbar-nav" />
      <Navbar.Collapse id="responsive-navbar-nav">
        <Nav className="ml-auto">
          <Nav.Link eventKey={1} as={Link} to="/link1">Link1</Nav.Link>
          <NavDropdown eventKey={2} title="Link2" as={Link} to="/link2" id="collasible-nav-dropdown">
            <NavDropdown.Item eventKey={2.1} as={Link} to="/link2/a">a</NavDropdown.Item>
            <NavDropdown.Item eventKey={2.2} as={Link} to="/link2/b">b</NavDropdown.Item>
            <NavDropdown.Item eventKey={2.3} as={Link} to="/link2/c">c</NavDropdown.Item>
            <NavDropdown.Item eventKey={2.4} as={Link} to="/link2/d">d</NavDropdown.Item>
          </NavDropdown>
          <Nav.Link eventKey={3} as={Link} to="/link3">Link3</Nav.Link>
        </Nav>
      </Navbar.Collapse>
    </Navbar>

**Comment by TashTenner** [comment]
Hi there, having the same issue that I cannot make <NavDropdown> clickable. Any idea how I can do that? 

see: title="Link2" as={Link} to="/link2"

Thanks!

```
<Navbar collapseOnSelect expand="lg" fixed="top">
      <Navbar.Brand as={Link} to="/">Name</Navbar.Brand>
      <Navbar.Toggle aria-controls="responsive-navbar-nav" />
      <Navbar.Collapse id="responsive-navbar-nav">
        <Nav className="ml-auto">
          <Nav.Link eventKey={1} as={Link} to="/link1">Link1</Nav.Link>
          <NavDropdown eventKey={2} title="Link2" as={Link} to="/link2" id="collasible-nav-dropdown">
            <NavDropdown.Item eventKey={2.1} as={Link} to="/link2/a">a</NavDropdown.Item>
            <NavDropdown.Item eventKey={2.2} as={Link} to="/link2/b">b</NavDropdown.Item>
            <NavDropdown.Item eventKey={2.3} as={Link} to="/link2/c">c</NavDropdown.Item>
            <NavDropdown.Item eventKey={2.4} as={Link} to="/link2/d">d</NavDropdown.Item>
          </NavDropdown>
          <Nav.Link eventKey={3} as={Link} to="/link3">Link3</Nav.Link>
        </Nav>
      </Navbar.Collapse>
    </Navbar>
```

**Comment by TashTenner** [comment]
solved with <SplitButton>

**Comment by prossel** [comment]
Since there is no solution here that I could use, at least for the linkable NavDropdown, here is the solution I found, inspired by the doc https://react-bootstrap.github.io/components/navs/#using-dropdowns 

Please note that I think the click cannot be used both to open the dropdown menu and to navigate to a link. Therefore, this snippet displays a menu (top) with a submenu (Hi) that is always open and which label is a real link to some route.

The "Hi" NavDropdown.Item is neccessary to close the top menu when clicked.

Hope this helps anyone find its way when landing on this old thread.

```
<NavDropdown title="Top menu (toggle-able)" key="top" >
  <Dropdown as={NavItem}>
      <NavDropdown.Item as={Link} to="/hi" >Hi</NavDropdown.Item>
      <Dropdown.Menu {...({ show: true })}>
          <NavDropdown.Item as={Link} to="/hello" key="1">Hello</NavDropdown.Item>
          <NavDropdown.Item as={Link} to="/world" key="2">Hello</NavDropdown.Item>
      </Dropdown.Menu>
  </Dropdown>
</NavDropdown>
```

**Comment by yeecai** [comment]
> replace `bsStyle` with `variant`
Hi, I tried replace the bsStyle in <Nav> tag, but it didnt work, anyone with better solution?

**Comment by kenlu89** [comment]
This is what i did to make it work.

`      <Navbar color="light" light expand="lg">
          <NavbarToggler onClick={toggleNavbar} />
          <Collapse isOpen={!collapsed} navbar>
            <Nav className="ml-auto ynhti-nav" navbar>
              <UncontrolledDropdown nav inNavbar>
                <DropdownToggle href="/curriculum" caret>
                  Curricular Resources
                </DropdownToggle>
                <DropdownMenu left>
                  <DropdownItem href="/curriculum/indexes/">
                    View Topical Index of Units
                  </DropdownItem>
                  <DropdownItem href="/curriculum/units/">
                    View List of Volumes by Year
                  </DropdownItem>
                  <DropdownItem href="/curriculum/referencelists">
                    Reference Lists
                  </DropdownItem>
                </DropdownMenu>
              </UncontrolledDropdown>`

**Comment by aquacalc** [comment]
_Thanks_ @prossel. That works for me.

**Comment by chitalian** [comment]
I found this worked for me

Just add this to your `<DropDown>`
```javascript
onToggle={() => { window.location.href = '/projects'}}
```

In my project I have it like this:

```javascript
      <NavDropdown 
        href="#projects"
        onMouseEnter={() => toggleMenuOpen(true) }
        onMouseLeave={() => toggleMenuOpen(false) }
        onToggle={() => { window.location.href = '/projects'}}
        show={menuOpen} title="Projects" id="collasible-nav-dropdown"
        >

        <NavDropdown.Item href="#action/3.1">Action</NavDropdown.Item>
        <NavDropdown.Item href="#action/3.2">Another action</NavDropdown.Item>
        <NavDropdown.Item href="#action/3.3">Something</NavDropdown.Item>
      </NavDropdown>
```

I hope this helps someone!

Sources:
https://github.com/react-bootstrap/react-bootstrap/issues/4042
https://www.w3schools.com/howto/howto_js_redirect_webpage.asp

**Comment by FLP13** [comment]
@chitalian that does work but the dropdown itself still has an empty href as default, must be a bug?

`<a aria-haspopup="true" aria-expanded="false" id="collasible-nav-dropdown" href="#" class="dropdown-toggle nav-link active" role="button">Top Item</a>`
