### ISSUE TITLE
Empty nodes for tooltips and performance

### ISSUE THREAD

**Issue by SakulK** [react-bootstrap/react-bootstrap#353]
Currently when using a tooltip react-bootstrap creates a div with an empty span for every tooltip in the app. When the number of tooltips is small this is not a problem but when using tooltips a lot it really makes a huge performance issue. Isn't there a way to not create those empty elements? I assume the problem here is the way react works but maybe there is a workaround?

**Comment by SakulK** [comment]
It works basically the same for modals so I guess it's more about how triggers work (OverlayTrigger and ModalTrigger)

**Comment by Simek** [comment]
Additionally in 0.13.2 and 0.13.3 (with many tooltips on site) this issue causes browser to freeze and affect overall performance by heavy CPU usage.

**Comment by itga** [comment]
Same here, React 0.12.2 and React-Bootstrap 0.13.3
Do we have alternative options to popup a dialog on hover event?

**Comment by globexdesigns** [comment]
Same issue here. This approach to creating Overlays is not scalable. My app currently have 1000+ independent items which have a tooltip or popover, and I'm having a lot of issues with render() blocking my rendering for several seconds when React tries to re-render the view.

Is there no way to generate the Overlay container on-demand?

**Comment by mtetlow** [comment]
It looks like there is some layout thrashing going on when there are large numbers of tooltips on elements which are being rendered, at least in my implementation. http://screencast.com/t/z0jGkAHV2 , is a screenshot of what I am seeing when I render several hundred components with tooltips. 

Maybe the solution is not related to the overall count of dom nodes, but more related to figuring out what is tripping the reflow for each dom node addition ( https://github.com/react-bootstrap/react-bootstrap/blob/master/src/OverlayMixin.js#L44 ).

**Comment by mtetlow** [comment]
This is my stab at improving performance for tooltips. It really just resolves the layout thrashing issue I was seeing. https://github.com/react-bootstrap/react-bootstrap/pull/394 . My layouts went from ~4s -> ~900ms with this change.

**Comment by mtetlow** [comment]
Another way I improved performance of initial render of lots of components using tooltips was only rendering the OverlayTrigger component on hover of a parent component... It seems pretty fast. I wonder if something similar to that could be a solution to this issue.

**Comment by globexdesigns** [comment]
@mtetlow Rendering the OverlayTrigger on demand (ie. whatever the appropriate `props.trigger` is set) is what I had in mind too. So that might be on hover, or on click, or on focus, etc...
