### ISSUE TITLE
SplitButton should allow alignRight prop

### ISSUE THREAD

**Issue by ProdigalNerd** [react-bootstrap/react-bootstrap#3531]
The SplitButton component should have the alignRight property.

Since SplitButton makes use of Dropdown.Menu, the alignRight property needs to be able to be passed from the SplitButton to Dropdown.Menu to control the alignment of the menu.

Currently, when using the SplitButton, you can change the direction of the drop down, but you can't change how that menu aligns with the button itself.

**Comment by taion** [comment]
The pass-through gets handled by `<Dropdown>` itself. This is just a missing bit of docs; you can see on the examples site that it actually works fine.

**Comment by kosmiq** [comment]
This is handled by the `<Dropdown>` component. Closing since the docs actually covers this (albeit not with an explicit example).
