### ISSUE TITLE
NavDropdownProps interface has title: string type instead of string | Element

### ISSUE THREAD

**Issue by hamanovich** [react-bootstrap/react-bootstrap#3534]
NavDropdownProps (in node_modules->react-bootstrap->NavDropdown.d.ts) has the following interface:
interface NavDropdownProps {
  id: string;
  **title: string;**
  disabled?: boolean;
  active?: boolean;
  menuRole?: string;
  rootCloseEvent?: 'click' | 'mousedown';
  bsPrefix?: string;
}

However the 'title' property also could not be only a string, but also Element is applicable.
For instance, I want to show gravatar image in nav-link.

The problem is Typescript. With no TS I'm able to add something like so:

<NavDropdown title={(
      <>
        <MediaImage src={auth.user.gravatar} roundedCircle />
        {auth.user.username}
      </>
    )}>...

**Comment by jquense** [comment]
happy to take a PR fixing this !

**Comment by hamanovich** [comment]
Actually the same situation with interface DropdownButtonProps:

```
interface DropdownButtonProps extends PropsFromToggle {
  id: string;
  **title: string;**
  menuRole?: string;
  rootCloseEvent?: 'click' | 'mousedown';
  bsPrefix?: string;
}
```

The property 'title' may be an Element as well.

**Comment by jquense** [comment]
fixed 👍
