### ISSUE TITLE
DropdownButton - react bootstrap not opens in mobile 

### ISSUE THREAD

**Issue by manishankardurai** [react-bootstrap/react-bootstrap#3538]
Clicking on DropdownButton (react-bootstrap), does not open the menu item only on mobile

Example:  <DropdownButton
                  disabled={isNonEditable}
                  title="Change"
                  bsSize="small"
                  bsStyle="primary"
                  id={'dropdown'}
                  key={'change'}
                  pullRight={true}
                >
                  <MenuItem
                    eventKey="3"
                    className={
                      'classname'
                    }
                  >
                    Hello
                  </MenuItem>
                </DropdownButton>

can you please check this and update

**Comment by mxschmitt** [comment]
Please provide us an example e.g. on codesandbox.io and of course which version you are using. :)

**Comment by mani-pyt** [comment]
Version we are using was  "react-bootstrap": "^0.32.1",

**Comment by manishankardurai** [comment]
Version we are using was "react-bootstrap": "^0.32.1",

**Comment by mxschmitt** [comment]
Provide us a minimal example / repository, otherwise we can't reproduce it and we will close the issue.

**Comment by kosmiq** [comment]
Closing since no example has been given for a long time.
