### ISSUE TITLE
Are Bootstrap spinners going to be added?

### ISSUE THREAD

**Issue by LubomirGeorgiev** [react-bootstrap/react-bootstrap#3539]
Do you have any plans on adding [Bootstrap](https://getbootstrap.com/docs/4.3/components/spinners/) spinners as a React component?

**Comment by tjdavey** [comment]
I have just opened a PR with an implementation of Spinners. I would appreciate a review if you're willing to take a look: https://github.com/react-bootstrap/react-bootstrap/pull/3541

**Comment by Lahirutech** [comment]
still not working

**Comment by kosmiq** [comment]
@Lahirutech what do you mean? They seem to be working fine on my end, both in the docs and in a project where I use them.

Can you set up an example at https://codesandbox.io/ and reproduce your issue?
