### ISSUE TITLE
When you open a modalwhen the vertical scrollbar is present, the page's content shifts

### ISSUE THREAD

**Issue by dumbmatter** [react-bootstrap/react-bootstrap#354]
Compare [the "Custom Trigger" demo from React Bootstrap](http://react-bootstrap.github.io/components.html#modals) and [the "Large Modal" or "Small Modal" demo from Bootstrap](http://getbootstrap.com/javascript/#modals-sizes). Notice how in both cases the vertical scrollbar disappears, but only in the React Bootstrap version there is a jarring shift in all the content to adjust for the extra horizontal space available.

Probably related to [this code from Bootstrap's version](https://github.com/twbs/bootstrap/blob/c683e7dea763b19e9bb172c34f74f99b926607e0/js/modal.js#L255-L258).

**Comment by Ofer-Sadgat** [comment]
Also, in chrome, if you have recently downloaded something and have the download bar at the bottom, it doesnt successfully hide the vertical scroll bar.

**Comment by taion** [comment]
Consequence of #321. Need this logic from upstream: https://github.com/twbs/bootstrap/blob/efe2023014ec90f35c0f722af6f3ec7a8eab720e/js/modal.js#L267-L271
