### ISSUE TITLE
Wrong example code blocks in statically built docs pages

### ISSUE THREAD

**Issue by thatzacdavis** [react-bootstrap/react-bootstrap#3540]
On [the introduction page](https://react-bootstrap.github.io/getting-started/introduction/) the code examples that are shown for `Importing` and `Stylesheets` are identical.

I'm assuming that the stylesheets example should be updated to use the CDN as described in the text.

**Comment by jquense** [comment]
this seems to be a gatsby or react bug. The code is correct and if you navigate to the page from another docs page it renders correctly

**Comment by thatzacdavis** [comment]
Yes, I was looking at the docs themselves to try and submit a fix and noticed that the code looks correct.

**Comment by mxschmitt** [comment]
Issue is still reproduceable: 
![image](https://user-images.githubusercontent.com/17984549/54690576-ffda2080-4b21-11e9-9dd1-d877f684a17b.png)
https://react-bootstrap.github.io/getting-started/introduction/

**Comment by jquense** [comment]
likely because the docs haven't been redeployed

**Comment by mxschmitt** [comment]
oh okay, I thought auto deployment is enabled from the `master` branch. So we deploy to Netlify probably after the release right? 👍

**Comment by jquense** [comment]
netlify deploys continuously but the gh-pages site is a manual push

**Comment by jquense** [comment]
siiigh still an issue. I'm really unsure where the bug is, but its super subtle and not in our code.

**Comment by thatzacdavis** [comment]
Yeah, I tried looking into it as well. Pretty bizarre behavior happening here :/

**Comment by mxschmitt** [comment]
Fixed the rendering bug due new deployment to gh-pages.

**Comment by jquense** [comment]
@mxschmitt its not fixed :/

**Comment by corysimmons** [comment]
I'm a firm believer that almost every project on Github should just use GitBook...

**Comment by bpas247** [comment]
Hmm, I can't seem to reproduce this bug anymore. Has it been fixed?

![image](https://user-images.githubusercontent.com/18705892/56236141-c5d73e00-603d-11e9-9c06-2d5302c391be.png)

**Comment by mxschmitt** [comment]
We did a major bump of our Gatsby/mdx dependencies.

@thatzacdavis @bpas247 
Please verify on: https://react-bootstrap.netlify.com/getting-started/introduction/
If the issue is still persistent.

**Comment by mxschmitt** [comment]
Still reproducible on https://react-bootstrap.netlify.com/getting-started/introduction/ 
![image](https://user-images.githubusercontent.com/17984549/60176341-48d2fc80-9816-11e9-88e1-15c0483ef87c.png)

**Comment by jquense** [comment]
I think this is a hydration/SSR bug in particular. The props are _correct_ on the components but wrong when rendered which makes me think this is React bug. I wonder if we could force a rerender perhaps or change the key so it remounts
