### ISSUE TITLE
travis-ci: release via tags

### ISSUE THREAD

**Issue by mxschmitt** [react-bootstrap/react-bootstrap#3546]
Release automatically once a new tag was created / pushed to GitHub: https://docs.travis-ci.com/user/deployment/npm/

I could implement it.

**Comment by taion** [comment]
Hmm, if we're going to set that up, maybe just go all the way to semantic-release?

**Comment by mxschmitt** [comment]
Sounds great, that's definitely better, than make it ourselves.

**Comment by jquense** [comment]
semantic release makes beta versions hard/impossible

**Comment by taion** [comment]
does it really? ugh

**Comment by bpas247** [comment]
Would this be something we would integrate when v1.0 is officially released?

**Comment by taion** [comment]
i'd be in favor of adding semantic release once we hit stable, yeah

**Comment by mxschmitt** [comment]
TravicCI is not used anymore
