### ISSUE TITLE
Discussion: auto dependency bumping via bot

### ISSUE THREAD

**Issue by mxschmitt** [react-bootstrap/react-bootstrap#3547]
In this discussion it should be clarified, if it makes sense to add e.g.:
- https://renovatebot.com
- https://greenkeeper.io
- https://dependabot.com

In my mind, it would be good, because we often bump the dependencies of www or the main package manually and it solves partly some issues.

**Comment by taion** [comment]
We're using Dependabot for a bunch of our other things. Still slowly turning it on more broadly. I'm 👍 on this though.

**Comment by mxschmitt** [comment]
@taion Dependabot looks also quite nice 👍

**Comment by mxschmitt** [comment]
@jquense what do you think? Let's add [dependabot.com](dependabot.com) in my mind.

**Comment by taion** [comment]
i enabled dependabot

**Comment by mxschmitt** [comment]
thx

**Comment by mxschmitt** [comment]
@taion also for www sub directory?

**Comment by taion** [comment]
dependabot is supposed to be smart enough to pick that up automatically... let's see if it figures it out

**Comment by mxschmitt** [comment]
@taion looks like it won't pick the www directroy up:
![image](https://user-images.githubusercontent.com/17984549/55981513-2578c680-5c97-11e9-9b6b-1afcca5fbee6.png)

Please add it manually, thanks!

**Comment by taion** [comment]
gotcha – done, thanks
