### ISSUE TITLE
Leverage React-Bootstap's propTypes in my own components

### ISSUE THREAD

**Issue by casiraghijd** [react-bootstrap/react-bootstrap#3548]
I am currently creating an app that uses this component library.  One our our first use cases was to wrap these components in our component library adding specific styles and behaviors we desire for our UX.  I noticed that the propTypes seem to be  removed from the version of this package I have installed.

This might be my own inexperience with npm dependencies, but is there a way to use a development build when working in a dev mode?  I included a sample wrapping, it would be really nice if there was a way to forward the propTypes from React-Bootstap into my component, so that my users could get the same behaviors when using the component.  Specifically it would be really nice to be warned about missing required props.

```javascript
import React from 'react';
import Overlay from 'react-bootstrap/Overlay';
import styles from './MyOverlay.module.css';
import classNames from 'classnames';
const MyOverlay = React.forwardRef(function MyOverlay(props, ref) {
  const { className, children, variant, ...otherProps } = props;
  // Merge any provided classNames with local component styling
  const classes = classNames(className, styles.my-overlay);
  return (
    <Overlay
      ref={ref}
      className={classes}
      {...otherProps}
    >
      {children}
    </Overlay>
  );
});

MyOverlay.propTypes = Overlay.propTypes;
```

**Comment by taion** [comment]
should we wrap instead of removing? looks like that's recommended for libraries. wouldn't be able to remove the import though.

**Comment by jquense** [comment]
yeah probably. I didn't totally thing that through. the prop-types import itself isn't super bad since the package DCE's itself, but you do have the import overhead. `prop-types-extra` would be here tho
