### ISSUE TITLE
react-router-component

### ISSUE THREAD

**Issue by KeithZhang** [react-bootstrap/react-bootstrap#355]
i see the readme says related module is react-router-bootstrap which is integration with react-router,  but  it really uses react-router-component in your code, though they are very similar,but not one.

**Comment by mtscout6** [comment]
No those are different routers, I have a project at work that is using react-router. Which is why I wrote react-router-bootstrap. The docs for react-bootstrap do use react-router-component, but that is not coupled to the react-bootstrap implementation.
