### ISSUE TITLE
TypeError: external_root_React_commonjs2_react_commonjs_react_amd_react_default.a is undefined react-bootstrap.js:8779:5

### ISSUE THREAD

**Issue by brucem1976** [react-bootstrap/react-bootstrap#3550]
I get the above issue when I run my web app - I have tried CDNs at unpkg and cdnjs so it doesn't seem to be a corrupt react-bootstap file. (current: https://unpkg.com/react-bootstrap@next/dist/react-bootstrap.js)

The error goes on:
```
<anonymous> https://unpkg.com/react-bootstrap@next/dist/react-bootstrap.js:8779
__webpack_require__ https://unpkg.com/react-bootstrap@next/dist/react-bootstrap.js:30 
<anonymous> https://unpkg.com/react-bootstrap@next/dist/react-bootstrap.js:94 
<anonymous> https://unpkg.com/react-bootstrap@next/dist/react-bootstrap.js:11 
webpackUniversalModuleDefinition https://unpkg.com/react-bootstrap@next/dist/react-bootstrap.js:9
<anonymous> https://unpkg.com/react-bootstrap@next/dist/react-bootstrap.js:1 
```

**Comment by mxschmitt** [comment]
Hi, are you using create-react-app? Not sure if it's supported, that the components can be loaded within the browser directly.

**Comment by brucem1976** [comment]
Thanks - yes I am using create-react-app - I removed this this from index.html and all seems to work fine now, thanks
