### ISSUE TITLE
How do I implement Accordion in react bootstrap project

### ISSUE THREAD

**Issue by wmgstar** [react-bootstrap/react-bootstrap#3551]
![Screen Shot 2019-03-17 at 10 13 59 AM](https://user-images.githubusercontent.com/47307975/54495018-72869a00-489d-11e9-88de-2a4dfb79ccf5.png)

![Screen Shot 2019-03-17 at 10 14 42 AM](https://user-images.githubusercontent.com/47307975/54495032-86ca9700-489d-11e9-84c9-8ef439d852f2.png)

**Comment by mxschmitt** [comment]
There is currently a working Pull Request: #3409 by @bpas247. Not sure what the current state of it is, maybe he could give us an update. 👍

**Comment by mxschmitt** [comment]
Closed due duplicate
