### ISSUE TITLE
Spinner doesn't work

### ISSUE THREAD

**Issue by wmgstar** [react-bootstrap/react-bootstrap#3552]
```
import Spinner from 'react-bootstrap/Spinner'

<Spinner animation="border"/>
```
![Screen Shot 2019-03-18 at 6 44 31 AM](https://user-images.githubusercontent.com/47307975/54534337-5fc99f00-4949-11e9-82fb-fd4c9ff15768.png)

![Screen Shot 2019-03-18 at 6 44 47 AM](https://user-images.githubusercontent.com/47307975/54534354-69530700-4949-11e9-8805-b516332a8597.png)

**Comment by mxschmitt** [comment]
The Spinner is not yet integrated into the latest version on npm. For more information check out: #3539.
A new version will be released soon.

**Comment by munroAllie** [comment]
can we reopen this issue until Spinner is released?
