### ISSUE TITLE
Collapse with array.map inside

### ISSUE THREAD

**Issue by vadymrybak** [react-bootstrap/react-bootstrap#3553]
I'm using react-bootstrap v0.32.4. When I implement Collapse component with some iteration inside, then I get warning in the console:

_Warning: Encountered two children with the same key, `{i}`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version._

The code is below:
```
public render() {        
        return (
            <Fragment>
                <p>Filter</p>
                <Button onClick={this.handleCartridgesClick}>Tech Cartridges</Button>
                <Collapse in={this.state.tech_cartridges_open}>
                    <div >
                        {
                            this.props.data.tech_cartridges.map( (tc,i) => <Checkbox key='{i}' title={tc}>{tc}</Checkbox>)
                        }
                    </div>
                </Collapse>
            </Fragment>
        )
    }
```

Seems like Collapse is being rendered twice behind the scene. Anybody knows what this might be?

**Comment by taion** [comment]
you're giving each of your components the same key of literally the string `{i}`

**Comment by vadymrybak** [comment]
omg, i can't believe i made such mistake :D
