### ISSUE TITLE
title is string in DropdownButton.d.ts

### ISSUE THREAD

**Issue by serdaryesilmurat** [react-bootstrap/react-bootstrap#3558]
Type of "title" prop for DropdownButton is defined as string. It should be React.ReactNode (as in TabProps), right?

https://github.com/react-bootstrap/react-bootstrap/blob/v1.0.0-beta.5/types/components/DropdownButton.d.ts

**Comment by mxschmitt** [comment]
LGTM, as defined here via Proptypes: https://github.com/react-bootstrap/react-bootstrap/blob/04184495ce111d9e0a9d100cec8f8b8122015ccf/src/Tab.js#L11

**Comment by serdaryesilmurat** [comment]
My comment is on typings, not the source. Also, not Tab but "**DropdownButton**". Since 1.0.0-beta4 types are bundled inside the package and for DropdownButton, it seems to be incorrect.

**Comment by mxschmitt** [comment]
It's already fixed: https://github.com/react-bootstrap/react-bootstrap/pull/3457

But not released yet.
