### ISSUE TITLE
modal-backdrop has a height of 0px

### ISSUE THREAD

**Issue by lo1tuma** [react-bootstrap/react-bootstrap#356]
In bootstrap 3.3.1 they changed the `modal-backdrop` class and setting the height with javascript instead of css (see https://github.com/twbs/bootstrap/commit/14e5fb04e9bf7c406b799b75b0427522d87a4ccb)

react-bootstrap doesn’t set height of the `modal-backdrop` element so the backdrop is not shown.

**Comment by mtscout6** [comment]
This seems to be related to #330 and #348. This library is still at bootstrap 3.2.0, a problem I do wish to remedy soon. Time permitting of course.

**Comment by vinnymac** [comment]
@mtscout6 I have no gripes with it being at 3.2.0. But it would be nice if the top version that is supported was in the ReadMe. Like in #417.

**Comment by mtscout6** [comment]
@vinnymac Thanks I brought that right in.

**Comment by luisincrespo** [comment]
I know this issue is closed. But I'm using react-bootstrap version 0.27.3 and my modal backdrops have no height, so they don't show.

**Comment by jquense** [comment]
don't use the css from bootstrap 3.3.1 per the solution here

**Comment by luisincrespo** [comment]
Yep I changed the CSS to use Bootstrap 3.3.5 and it worked.

**Comment by luisincrespo** [comment]
Thanks.

**Comment by bes** [comment]
I have this issue with bootstrap less 3.3.8 https://www.npmjs.com/package/bootstrap-less :(
