### ISSUE TITLE
tsx error

### ISSUE THREAD

**Issue by gland2015** [react-bootstrap/react-bootstrap#3561]
in a tsx file:
 import * as  Alert  from "react-bootstrap/Alert";
but when i use 'Alert' component
vscode tip 'JSX element type 'Alert' does not have any construct or call signatures.ts(2604)'
this is why?

use import  { Alert}  from "react-bootstrap" is fine

**Comment by Bartozzz** [comment]
Use the following syntax (without `* as`):

```typescript
import Alert from "react-bootstrap/Alert";
```
