### ISSUE TITLE
Misleading scrollable prop on Modal component

### ISSUE THREAD

**Issue by Bartozzz** [react-bootstrap/react-bootstrap#3565]
Commit https://github.com/react-bootstrap/react-bootstrap/pull/3469/commits/c693c76f965eb99a547bddde68af2640e9e74693 added the `scrollable` prop to `Modal` component ~but it doesn't do anything (see comment https://github.com/react-bootstrap/react-bootstrap/commit/a7e800ed04b35c3a9437f9fac15f2f398cbd2945#r32886739)~. I believe that it should be added to `<Modal.Body />` instead?

**Comment by Bartozzz** [comment]
BTW - added missing `scrollable` prop definition in `<ModalDialog />`. See: https://github.com/react-bootstrap/react-bootstrap/pull/3564

**Comment by jquense** [comment]
> I believe that it should be added to <Modal.Body /> instead?

No the class is in the right place, its just spelt wrong, which is why it doesn't work https://getbootstrap.com/docs/4.3/components/modal/#scrolling-long-content

**Comment by Bartozzz** [comment]
My bad, in fact. https://github.com/react-bootstrap/react-bootstrap/pull/3566 should fix this issue.
