### ISSUE TITLE
Don't use useLayoutEffect in a server environment

### ISSUE THREAD

**Issue by remi2j** [react-bootstrap/react-bootstrap#3569]
I'm using Next JS to provide server-side rendering to my app.

I get the following noisy console log everytime my app compiles:

>Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, useLayoutEffect should only be used in components that render exclusively on the client.

It comes from `ForwardRef` inside `Nav.Link`.

It would be nice if you checked that the environment is a browser before calling `useLayoutEffect`

**Comment by jquense** [comment]
Hmm interesting, didn't know this was a restriction of useLayoutEffect...seems like the sort of thing react should care about

**Comment by mungojam** [comment]
Check out the potential workaround in [this comment](https://github.com/facebook/react/issues/14927#issuecomment-466815232)

**Comment by remi2j** [comment]
> Check out the potential workaround in [this comment](https://github.com/facebook/react/issues/14927#issuecomment-466815232)

You mean a workaround for the library authors right? I don't see where I would put this in my app

**Comment by mungojam** [comment]
> You mean a workaround for the library authors right?

Yeah, I mean for react-bootstrap to implement

**Comment by pesho** [comment]
The warning was augmented in React 16.8.6 to point to the following gist listing workarounds: https://fb.me/react-uselayouteffect-ssr

**Comment by djbotha** [comment]
Replacing `<Nav.Link />` with `<a className="nav-link" />` managed to solve the problem for me.

**Comment by abcd-ca** [comment]
@djbotha 's fix did reduce the error messages but my `Nav.Link` elements were within a `Navbar` which is also throwing those errors.

**Comment by jquense** [comment]
this should be fixed in the latest beta i believe

**Comment by abcd-ca** [comment]
@jquense What makes you say that? The beta release (v1.0.0-beta.6) is what I'm using and was the version that introduced this issue from what I can tell.

**Comment by pesho** [comment]
This is fixed for me in `1.0.0-beta.8`, even though the changelog does not mention anything relevant.

**Comment by abcd-ca** [comment]
yep, fixed now, thanks!

**Comment by lockie** [comment]
I believe the same error is present in `Dropdown` component as of 2.3.1

**Comment by crevulus** [comment]
It's also in `Overlay`. Currently using `^2.6.0`.
