### ISSUE TITLE
nav-tabs width?

### ISSUE THREAD

**Issue by EricWarnke** [react-bootstrap/react-bootstrap#357]
With code like this

```
<TabbedArea defaultActiveKey={1} stacked className="col-md-20">
  <TabPane eventKey={1} tab="User and Password" className="col-md-30"><UserPass/></TabPane>
</TabbedArea>
```

It applies `col-md-20` to both the generated `<nav>` and it's child `<ul>`. This breaks things as the inner `<ul>` is now a fraction of the parent.

How do I make it apply to one or the other?

Visual example of the inner `<ul>` getting squashed because the class is set to it and its parent.
![image](https://cloud.githubusercontent.com/assets/1396469/5980750/e36eb332-a870-11e4-8e8f-ac0e99e34ce9.png)

**Comment by taion** [comment]
This is the same as #422.
