### ISSUE TITLE
Overlay goes outside page(window)

### ISSUE THREAD

**Issue by zverexe** [react-bootstrap/react-bootstrap#3570]
I use react-bootstrap 1.0.0-beta.5 and  I created popover like block using overlay. I have list of horizontal elemnts clicking on which trigger opening overlay. But when I click on first or last element from the list, overlay that opened partly goes outside the website window. How can I fix that?

**Comment by mxschmitt** [comment]
Could you provide us a example on codebox.io or on a GitHub repo?

**Comment by zverexe** [comment]
something like this https://n50zj294jj.codesandbox.io/

**Comment by mxschmitt** [comment]
It seems, that you don't have saved your changes or provided us not the correct URL. I only see an empty parcel application without react-bootstrap etc.

**Comment by zverexe** [comment]
sorry check this https://n50zj294jj.codesandbox.io/  and this is source code https://codesandbox.io/s/n50zj294jj?from-embed

**Comment by zverexe** [comment]
@mxschmitt did you check sandbox?

**Comment by zverexe** [comment]
any updates on this?

**Comment by jquense** [comment]
looks fine to me? 
![image](https://user-images.githubusercontent.com/339286/56221289-f9af6500-6037-11e9-9269-4efcb27abe5e.png)

**Comment by zverexe** [comment]
click on last visible item, item8 for example
http://joxi.ru/1A5PqNLCD4NL02

**Comment by zverexe** [comment]
it is happened only with right side window edge, from the left everything okay

**Comment by jquense** [comment]
That screenshot is the last visible item, using the code-sandbox link you posted: https://n50zj294jj.codesandbox.io/

**Comment by zverexe** [comment]
check my screenshot

**Comment by zverexe** [comment]
![73b6154a79](https://user-images.githubusercontent.com/17533287/56233010-c649f600-608a-11e9-808e-711f0c33cf7b.jpg)

**Comment by mxschmitt** [comment]
I can also reproduce it, that it will go outside the page: 
![image](https://user-images.githubusercontent.com/17984549/56233862-4d47a000-6084-11e9-94af-3af02b1d101e.png)

**Comment by jquense** [comment]
it's not outside if the there is a scrollbar, overlays are positioned absolutely, they will be positioned inside the scroll area if that's the offset parent. If you don't want it inside a scroll area you need to config the overlay to a different container or boundary element. Ya'lls screenshots are cropped too far up so I can't see if the behavior you see is the same as mine or not..

**Comment by zverexe** [comment]
I need them inside scroll area as there is li list which contain this overlay. But why they recognise left window edge but not right too?

**Comment by zverexe** [comment]
yes you used browser scroll but this wasnt what I need. I need them to be relative to windows edge. Scroll area it is the list itself

**Comment by jquense** [comment]
ok, got it now. You need to mess around with the popper.js settings to achieve what you want. here is one example: https://codesandbox.io/s/n03p842v64

https://popper.js.org/popper-documentation.html

**Comment by zverexe** [comment]
your example works but in my case result is the same because I need to have ul {
  position: absolute;
  width: 100%;
  display: flex;
  justify-content: space-between;
} but in your example it position: absolute is commented

**Comment by zverexe** [comment]
I will try tomorrow change styles and let you know

**Comment by zverexe** [comment]
@jquense issue was resolved. Thank you.

**Comment by rajatsonibkn2002** [comment]
@zverexe how did you resolve the issue?
