### ISSUE TITLE
v4: Breadcrumb and Link from react-router-dom produces warning message

### ISSUE THREAD

**Issue by seekerk** [react-bootstrap/react-bootstrap#3572]
package.json:
```
"react-bootstrap": "^1.0.0-beta.6",
"react-router-dom": "^5.0.0",
```
This lines of code produces warning message
```
<Breadcrumb>
    <Breadcrumb.Item as={"div"}><Link to={"/"}>Main</Link></Breadcrumb.Item>
    <Breadcrumb.Item active>Register</Breadcrumb.Item>
</Breadcrumb>
```

> Warning: validateDOMNesting(...): &lt;a&gt; cannot appear as a descendant of &lt;a&gt;.
    in a (created by Context.Consumer)
    in Link (at UserRegisterPage.js:17)
    in a (created by SafeAnchor)
    in SafeAnchor (created by BreadcrumbItem)
    in div (created by BreadcrumbItem)
    in BreadcrumbItem (at UserRegisterPage.js:17)
    in ol (created by Breadcrumb)
    in nav (created by Breadcrumb)
    in Breadcrumb (at UserRegisterPage.js:16)
    ...

**Comment by taion** [comment]
This isn't a valid configuration. Use react-router-bootstrap.

**Comment by marc-ed-raffalli** [comment]
Found this issue when searching for the API to support this. Ended up using the following:
```
<ol className="breadcrumb">
  {
    breadcrumb
      .map((item) => (
        <li key={item.path} className={classNames('breadcrumb-item', {active: item.active})}>
          {item.path ? (<Link to={item.path}>{item.label}</Link>) : item.label}
        </li>
      ))
  }
</ol>
```
