### ISSUE TITLE
IE 11 breaking after PR

### ISSUE THREAD

**Issue by jjustus** [react-bootstrap/react-bootstrap#3573]
A recent [PR 3454](https://github.com/react-bootstrap/react-bootstrap/pull/3454) is causing Beta 6 to break on IE 11 due to the recent transitive dependency on @restart/hooks 0.1.1.  The resulting syntax error is because of the non-es5-compatible JavaScript that includes arrow functions.

**Comment by taion** [comment]
fixing this in https://github.com/react-restart/hooks/pull/1

**Comment by dlpowless** [comment]
This is also the case for @restart/context 2.1.2
