### ISSUE TITLE
Limited variant selection

### ISSUE THREAD

**Issue by AndriySvyryd** [react-bootstrap/react-bootstrap#3574]
Why do the components limit `variant` to only the default bootstrap colors? I've added additional ones to `$theme-colors` and would like to use them in the components too.

**Comment by taion** [comment]
It's the default to work well with stock Bootstrap out of the box. The props are implemented as interfaces exactly so that you can override them as appropriate.

**Comment by AndriySvyryd** [comment]
@taion I may be missing something, but as far as I am aware Typescript doesn't allow to change member type in interfaces. http://www.typescriptlang.org/docs/handbook/declaration-merging.html:

>Non-function members of the interfaces should be unique. If they are not unique, they must be of the same type. The compiler will issue an error if the interfaces both declare a non-function member of the same name, but of different types.
