### ISSUE TITLE
@restart/hooks depends on react "^16.8.0-0"

### ISSUE THREAD

**Issue by MrMikeRodriguez** [react-bootstrap/react-bootstrap#3577]
It looks like these 2 dependencies:
```
"@restart/context": "^2.1.2",
"@restart/hooks": "^0.1.1",
```
were added with https://github.com/react-bootstrap/react-bootstrap/commit/da675dec660bd3b74db72327f7c87331e0b219c9

`@restart/context` is breaking on newer versions, but that is already noted in #3576 

Based on this project yarn.lock for `"@restart/hooks": "^0.1.1"` - which is "0.1.1" - It looks like it has declared a peer dependency on 
```
"react": "^16.8.0-0"
```
 here https://github.com/react-restart/hooks/blob/v0.1.1/package.json#L26

However, the `react-bootstrap` project the peer dependency is declared to be
```
"react": ">=16.3.0"
```
here https://github.com/react-bootstrap/react-bootstrap/blob/v1.0.0-beta.6/package.json#L61-L64

I have been using `"react": 16.4.0"` with `react-bootstrap` for a while now - meeting the peer dependency range.
Now however, I get warnings from `yarn`

```
warning "react-bootstrap > @restart/hooks@0.1.1" has incorrect peer dependency "react@^16.8.0-0"
```

Has the minimum required version of `react` changed for `react-bootstrap`?

**Comment by taion** [comment]
it has, yes. we should bump it here. care to PR?

**Comment by MrMikeRodriguez** [comment]
@taion Thanks for the quick feedback! It looks like you've updated things already. Nice.
