### ISSUE TITLE
How can I grab the value of an input form?

### ISSUE THREAD

**Issue by maketroli** [react-bootstrap/react-bootstrap#3579]
I am attempting to grab the value of an input form on React Bootstrap but the obvious way doesn't seem to be working.

This is the form field component:
```javascript
const FormField = ({
  type,
  label,
  value,
  onChange,
  controlId,
  placeholder,
}) => (
  <Form.Group as={Row} controlId={controlId}>
    <Form.Label column sm={4}>
      {label}
    </Form.Label>
    <Col sm={8}>
      <Form.Control
        type={type}
        value={value}
        onChange={() => onChange(value)}
        placeholder={placeholder}
      />
    </Col>
  </Form.Group>
);
```
And here is the parent where I call that component above:
```javascript
class FormFieldsGroup extends Component {
  state = {
    firstName: '',
  };

  render() { 
   const { firstName } = this.state;
   return (
        <FormField
          type="text"
          label="First Name"
          controlId="firstName"
          placeholder="First Name"
          value={firstName}
          onChange={firstName => this.setState({ firstName })}
        />
   )
  }
}
```

It only returns an empty string.

What can I do to store the value of that input in a local component state?

Really, guys, this is very important and should be in the docs. Like any kind of specification on how to grab the value of an input form properly. I came from this post https://github.com/react-bootstrap/react-bootstrap/issues/2418 where there is still people trying to figure out how to do this in the best way possible.

**Comment by taion** [comment]
That's not the "normal" way and that's not how controlled inputs in React work. See https://reactjs.org/docs/forms.html. The form controls work as transparent pass-throughs to the underlying `<input>`s in these contexts, and take props as normal.

In your example, you're passing back the `value` prop that you're passing in, rather than the event target value.

**Comment by maketroli** [comment]
Yeah. I am getting the value of the inputs with `event.target`, as normal. I just thought there was a React Bootstrap way. Anyways, thanks for your time, @taion.

**Comment by ORESoftware** [comment]
I have the same problem:  https://github.com/react-bootstrap/react-bootstrap/issues/4987
