### ISSUE TITLE
Sticky Navbar

### ISSUE THREAD

**Issue by Cwanyo** [react-bootstrap/react-bootstrap#3582]
When Navbar is set to "Sticky" or styled position as "Sticky", it will hide automatically when the scrolling reach 100% of the page size. Is there a way to remove or disable this functionality?

**Comment by jquense** [comment]
Hi there, any behavior you see is only from native CSS, we don't implement any logc around sticky positioning. That said that behavior doesn't sound normal so you might have some rogue conflicting css or haven't set the right top value for your case
