### ISSUE TITLE
Modal Causing Overlay issues with Popover

### ISSUE THREAD

**Issue by Salinn** [react-bootstrap/react-bootstrap#3591]
Hi,

Our team has finally given sometime to look into why on modals the popover doesn't follow the target when scrolling occurs. We noticed the recommendation to add a container and set that value to this and to add position relative as well which solves the scrolling issue. That solution end up creating a funky looking popover and was wondering if we are doing something else wrong. We [created a codepen](https://codepen.io/salinn/pen/xewBeb?editors=0011) that recreates the issue we are seeing. Any help would be appreciated. 

Expected popover
<img width="456" alt="Screen Shot 2019-04-03 at 11 33 53 AM" src="https://user-images.githubusercontent.com/2657757/55492017-830c7380-5604-11e9-8e15-73740bf8c7ac.png">

Actual popover
<img width="865" alt="Screen Shot 2019-04-03 at 11 33 40 AM" src="https://user-images.githubusercontent.com/2657757/55492006-7d169280-5604-11e9-9c96-6d1c32de7f74.png">

Thanks!

We are using react-bootstrap: 0.32.4

**Comment by Salinn** [comment]
It seems to be an issue with the width of the element, because when we modified the codepen and made it a longer point of contact it worked. Is there anyway to still use the icon and get the width we are expecting? L[onger width codepen](https://codepen.io/salinn/pen/PgZMbJ?editors=0011)

**Comment by jquense** [comment]
The positioning in  `< 1.0.0` is fairly simplistic, you can set the container that the popover is amended to, and it will be absolutely positioned to that element. In this case you want to set it to the element with `overflow: auto` set which is a bit tough to access here.

**Comment by Salinn** [comment]
@jquense that is good to know, but when I was messing around for the last 10 minutes with it I tried adding `overflow: auto` in a number of spots and didn't see it change anything correctly. Happy to keep playing with it just hoping for a tad more direction.

**Comment by jquense** [comment]
there seems like there is magic in the positioning but there isn't really. it's positioned _solely_ via `position: absolute;`, so it will stay stuck to the closes element with `position: relative`, see: https://codepen.io/jquense/pen/wZGvoW

**Comment by kosmiq** [comment]
Closing since no new feedback has been posted for a long time.
