### ISSUE TITLE
Nav - Warning received 'false' for non-boolean attribute 'fill'

### ISSUE THREAD

**Issue by dalevfenton** [react-bootstrap/react-bootstrap#3592]
The Nav component is spreading the fill attribute onto the actual DOM element it creates without picking off the "fill" prop. This is causing the following console error:

<img width="833" alt="Screen Shot 2019-04-03 at 11 37 11 AM" src="https://user-images.githubusercontent.com/16996057/55492462-3ffed000-5605-11e9-840e-567538e61946.png">

**Comment by jquense** [comment]
What version are you using? The current code does not pass fill in

**Comment by mxschmitt** [comment]
Closed due inactivity. Just ping us, then we will reopen it.

**Comment by dnln** [comment]
I'm seeing the same issue with 1.0.0-beta.8. 

For me, it seems to be coming from using styled-components to extend the styles on a `Nav`.

**Comment by dalevfenton** [comment]
@dnln it was an issue with styled components

When I originally tried something like below, I don't remember exactly what the issue was but somehow styled components was causing props to end up where they shouldn't. If you inspect the tree in react dev tools you can see the props ending up on the wrong nodes.
```
const ThemedNav = styled(Nav)` ${ThemedText} `
```

I basically just wrote a tiny wrapper component that fixed the issue but it does feel a bit hacky and the typings may not be perfect:
```
const NavWrapper: React.FunctionComponent<NavProps & React.PropsWithoutRef<JSX.IntrinsicElements['div']>> = (props) => {
    return <Nav {...props} />
}

export const ThemedNav = styled(NavWrapper)`
    ${ThemedText}
`
```

**Comment by dnln** [comment]
@dalevfenton thanks for letting me know. After doing a bit of digging I came across [an answer on the styled-components](https://github.com/styled-components/styled-components/issues/1198#issuecomment-425650423) repo and ended up with:

```js
const MyComponent = styled(({ fill, ...rest }) => <Nav {...rest} />)`
  display: flex;
  align-items: center;
`;
```

Which just strips out the fill prop from `Nav`.
