### ISSUE TITLE
Many components are no longer compatible with styled-components

### ISSUE THREAD

**Issue by nguyenquyhy** [react-bootstrap/react-bootstrap#3595]
In react-bootstrap before version 1.0.0-beta.6, I can use styled-components to augment the style of react-bootstrap's components. For example:
 ```
const StyledCard = styled(Card)`
max-width: 100px;
`
```
which would render into
```<div class="card [class name from styled-component]">...</div>```

However, after upgrading to react-bootstrap 1.0.0-beta.6. It renders into
```<div class="[class name from styled-component]">...</div>```

This same issue also happens to other components such as FormControl.

**Comment by jquense** [comment]
We'd need more info...not much has changed in the latest beta, and components all still accept className

**Comment by nguyenquyhy** [comment]
This issue comes from this change https://github.com/react-bootstrap/react-bootstrap/commit/da675dec660bd3b74db72327f7c87331e0b219c9#diff-fcf0eccbd6ec0e88e8fe1ee47f3e4cd5. 

This is due to the behavior of styled-component on `forwardRef` and `defaultProps.as`: default `as` of `'div'` will get propagated up to `styled(Card)`, and styled-component will render a bare div instead of the Card component (https://github.com/styled-components/styled-components/issues/2325).
```
const defaultProps = {
    as: 'div',
    body: false,	
};
```

Is it possible to change to use as = 'div' in parameter list instead of using defaultProps? I know it is not exactly a bug for react-bootstrap, but I think compatibility with styled-components is quite important for many developers.

I have made an example for this.
https://codesandbox.io/s/lxo3pv1ry9

I can make a PR if you think the change is proper, or please let me know if you have any better idea for this.

**Comment by jquense** [comment]
ah that really sounds like a bug in Styled components. We can maybe work around this in the short term but it seems kinda bad that SC works this way, its surprising

**Comment by nguyenquyhy** [comment]
Yes I would love to see styled-components to change their behavior to be nicer to other libs as this issue would occurs for anyone using default `as` and `forwardRef`.

However, from the linked issue, I don't feel that they are going to care any time soon. I see your comments, and I hope they will now do something about that.

In the mean time I would really appreciate if react-bootstrap could try to circumvent this issue. I would love to continue using the beta and reporting bugs, but this issue would force me to stay on beta5.

**Comment by jquense** [comment]
We can definitely work around it, I will say tho the fastest way to get there would be to put a PR together if you're up for it

**Comment by nguyenquyhy** [comment]
I can create a PR to remove the default as and put that into parameter list if you think that direction is good enough for a workaround. Please let me know if you have other ideas.

**Comment by taion** [comment]
yup, let's do that – i think it's (unfortunately) the only/best option available right now

**Comment by davidretireup** [comment]
I can't move pass beta.5 until this issue is resolved.

**Comment by taion** [comment]
we'd happily take a PR here. i don't think any of the maintainers here actively use styled components.
