### ISSUE TITLE
bsPrefix not applied to all classes

### ISSUE THREAD

**Issue by flyon** [react-bootstrap/react-bootstrap#3597]
When using bsPrefix for example with a Modal only the class of the topmost element is prefixed. 

![image](https://user-images.githubusercontent.com/341567/55683272-7d9a8a80-5970-11e9-8e6d-564b7c33f0f2.png)

I'm trying to integrate react-bootstrap in a framework by building wrappers for each type of component. The existing (S)CSS setup however uses CSS modules, thus prefixing all classnames. 

I try to create a setup so that when my Modal wrapper is used, only the react bootstrap Modal code and the bootstrap Modal scss is included. This is working, however all scss that I include is prefixed by the build. So I add bsPrefix to all react bootstrap components I use: Modal, Modal.Header, Modal.Body etc. This works, however only for the actually prefixed classnames.

**Comment by jquense** [comment]
ModalDialog is it's own component with it's prefix specified. Btw v1 makes this easier bc you can swap out all prefixes at a top level vs component by component

**Comment by flyon** [comment]
@jquense could you tell me where I could find the documentation on "prefixes at a top level"? or how to do it? I did not see this mentioned anywhere. thank you

**Comment by jquense** [comment]
Sure it's here: https://react-bootstrap.github.io/getting-started/theming/

**Comment by bpas247** [comment]
@flyon is there anything else that needs to be done here?

**Comment by kosmiq** [comment]
No new feedback. Closing.

**Comment by ali28729** [comment]
I was reading up on the react-bootstrap documentation for ThemeProvider and this is all i could find.
https://react-bootstrap.netlify.app/getting-started/theming/#custom-styles-prefix

I was wondering if we can define prefixes for all of the elements instead of specifying for each one like here it's done for 'btn'.
<ThemeProvider prefixes={{ btn: 'my-btn' }}>
    <Button variant="primary">My Button</Button>
 </ThemeProvider>

**Comment by kyletsang** [comment]
@ali28729, you can set multiple prefixes like so:

```
<ThemeProvider prefixes={{ btn: 'a', dropdown: 'b', etc: 'c' }}>
```

**Comment by ali28729** [comment]
@kyletsang Yes, thanks for replying. I'm aware of that, but it'd be tedious and harder to maintain if i want to apply it on all of the elements instead of specific ones.
I was wondering if there is a way to do that in this library which i missed.

**Comment by kyletsang** [comment]
When you say "all the elements", are you referring to the same component (like setting the same prefix for multiple `Button`s)?   If so, the prefixes will be automatically applied to all the components you specify prefixes for that's inside the `ThemeProvider` node.  It does this via React context.  If you need to override one of those buttons as a one-off thing, you can specify `bsPrefix` directly on the button and it will ignore the prefix from the `ThemeProvider`.

**Comment by ali28729** [comment]
I mean all bootstrap components by elements e.g. buttons, dropdowns, modals, accordions e.t.c.

I'll be elaborate for context. I'm actually trying to embed a react app into any host website without an iframe, so i have to look out for isolation myself. On some websites the host website's bootstrap modifies the components in my react app. So to overcome that, i was trying to leverage the specificity in bootstrap. 
Now, when i use the prefixes in `ThemeProvider` for, let's say a modal. It only applies it to a few parent divs (e.g. `modal-content`, `modal-dialog`) and not the divs with `modal-header`, `modal-body`, `modal-footer` classes and so on. I can achieve the desired behavior by listing them in the prefixes object too but that'd make a very long list considering the number of bootstrap components i'm using, and one i'll have to make by some hit and trial.

**Comment by kyletsang** [comment]
Ah ok, gotcha - sorry for the misunderstanding.

Unfortunately, listing all the prefixes manually inside ThemeProvider is the only way to do this.  Modal is probably a case where we should fix it to be consistent though.  Something we can revisit in the next major release.
