### ISSUE TITLE
active on DropDown.item and NavDropDown.item is not considered a boolean

### ISSUE THREAD

**Issue by HStokbro** [react-bootstrap/react-bootstrap#3598]
This will result in an error telling you to not use a boolean, but use boolean .toString() instead. But that's just wrong. Active IS a boolean.
```
const boolean = true;
<Dropdown.Item active={boolean}>
     {text}
</Dropdown.Item>
```
(Worked fine in beta-5)

**Comment by jquense** [comment]
the `active` prop is being passed through to the DOM node by accident
