### ISSUE TITLE
Dismissible on alert does not work

### ISSUE THREAD

**Issue by HStokbro** [react-bootstrap/react-bootstrap#3599]
This will show a close (x) icon, but clicking it does nothing. It does not dismiss the alert.
It also does not work in the example on https://react-bootstrap.netlify.com/components/alerts/
```
<Alert variant="danger" dismissible>
{message}
</Alert>
```

**Comment by mxschmitt** [comment]
The `dismissible` property of the Alert only adds a close button to the Alert. You have to manually implement the `onClose` function to hide it.

But in my mind, we can add the hide functionality to the examples, like in the Bootstrap 3 examples: https://5c507d49471426000887a6a7--react-bootstrap.netlify.com/components/alerts/

**Comment by HStokbro** [comment]
Aha.. I did not catch that. Thx.
