### ISSUE TITLE
Add a setValue method to Input components

### ISSUE THREAD

**Issue by nickdaugherty** [react-bootstrap/react-bootstrap#360]
For parity with Input's `getValue()`, it should be possible to set an Input's value in a similar way.

**Comment by lazywei** [comment]
+1

**Comment by vpavkin** [comment]
I don't think it'll be React way. I guss, according to React style, it's cleaner to store input value in the `state` and use this `state.value` in `render` method.

**Comment by lazywei** [comment]
@vpavkin The thing is, we don't have the access to the "input's state". What if I want to clean the input's value after I `getValue`? For now, I can only use `this.refs.someInput.getDOMNode.value = ''`, which is a little tedious.
Assume you are saying that I should have a state, say `inputVal`, and the `input` has the value `this.state.inputVal`. Then yes, I can simply update the `this.state.inputVal` to manipulate the value of the input. However, I think the React way should be having "as less as possible" states. So, if I can use the `input.getValue` and `input.setValue`, I should avoid adding more states to my component.

**Comment by vpavkin** [comment]
@lazywei Good point. But by manipulating input's DOM aren't you introducing a new implicit piece of state? IMHO, it's better to declare it explicitly.
But anyway, some cases may really require a `setValue` API.

**Comment by mtscout6** [comment]
The initial or current value should be set through props. I'd like to stay in line with how React [prescribes](http://facebook.github.io/react/docs/forms.html). Does that not work for you now, or is this a documentation problem? If you look at the code example to the input in the [docs](http://react-bootstrap.github.io/components.html#input) you'll see that value is set via props there.

**Comment by nickdaugherty** [comment]
Not every component will be a Controlled Component which has its value set by a prop - some may be Uncontrolled Components that need occasional programmatic manipulation in response to events.

For example, one could implement an uncontrolled date picker based on a `text` input, with the need to manually set the input's value in response to a clicking a date in a popup, while allowing arbitrary user input and not updating the state on each keypress. The same could be achieved through a Controlled Component of course, but that is not always desired.

**Comment by mtscout6** [comment]
My solution still applies with your example of a Date Picker component. You'd have the parent component of the two handle the coordination of the two. The parent would listen to the event from the DatePicker. In the event handler use `setState` to capture the date selected. Then apply the prop to the input from the state in your render call.

**Comment by nickdaugherty** [comment]
That assumes a Controlled Component - one where React is controls the value via props, and it's not possible for the user to manually enter input without registering a key handler and updating the state for each keypress.

The Date Picker was just an example off the top of my head (and not a great one)...but the point is that not _every_ input will be a Controlled Component for every use-case, so it might be useful to have a method for manual control when using Uncontrolled Components.

**Comment by mtscout6** [comment]
Please provide an example, I am not in favor of this since it is entirely possible through props now. You have to create the Input somewhere, therefore you would be able to pass it props.

**Comment by nickdaugherty** [comment]
I'm ok closing this if it's agreed that using only Controlled Components (those whose value is tied directly to a prop) will be supported.

I do agree that's generally the best approach, though still think there is a use case for `setValue` when using Uncontrolled Components.

**Comment by eranimo** [comment]
There still should be a setValue method

**Comment by taion** [comment]
No, there shouldn't. It's an anti-pattern to use this sort of setter in React when you can just inject a `value` prop.

**Comment by gauravagarwalr** [comment]
@nickdaugherty I guess what you are trying to do, can be achieved by changing the `key` attribute of the element when you are trying to change the `defaultValue`.

**Comment by ORESoftware** [comment]
@gauravagarwalr thanks for that info, I have heard that before, could you provide a link to such a solution with the key attribute?

**Comment by elgs** [comment]
It seems there is no way to set the value of a input field for an uncontrolled field?

**Comment by jquense** [comment]
you can set it the same way you set any uncontrolled input in React

**Comment by elgs** [comment]
My question is about setting value for an uncontrolled input.

**Comment by jquense** [comment]
please see the react documentation on forms for that. it covers the details quite extensively

**Comment by elgs** [comment]
I would not ask the question here if the official docs are helpful, I mean on this topic.

**Comment by elgs** [comment]
Adding a `key` property to the input tag seems to do the trick, however, do I really need to write a random key generator for this problem?

**Comment by elgs** [comment]
Problem solved (worked around) by adding `key={Math.random()}`:

```jsx
<TextField
  key={Math.random()}
  ref={input => this.dataNode.Name = input}
  defaultValue={this.props.dataNode.Name}
  floatingLabelText="Name"
/>
```

**Comment by jquense** [comment]
just control the input in that case. you are actively not using any of the uncontrolled input behavior, use value

**Comment by elgs** [comment]
I believe I should use `value` for `controlled` input. Now I'm using `uncontrolled` input. Adding a `key` property to the input seems to do the trick, though it looks weird.

**Comment by jquense** [comment]
my point is you shouldn't use an uncontrolled input. your example is a perfect illustration of when to use a controlled imput

**Comment by hdpinto** [comment]
FWIW:

I've been able to set the value of an input this way:

```typescript
// ...
this._someInput: HTMLInputElement;

componentWillReceiveProps(nextProps) {
  if (someCondition) {
    this._someInput.value = nextProps.someValue;
  }
}

render() {
  return (
    <input ref={(r) => this._someInput = r} defaultValue={this.props.someValue} />
  )
}
// ...
```

**Comment by MoreBlood** [comment]
> FWIW (and since this thread came up in the top google results for this issue), I've been able to set the value of an uncontrolled input this way (vanilla react):
> 
> ```ts
> // ...
> this._someInput: HTMLInputElement;
> 
> componentWillReceiveProps(nextProps) {
>   if (someCondition) {
>     this._someInput.value = nextProps.someValue;
>   }
> }
> 
> render() {
>   return (
>     <input type="text" ref={(r) => this._someInput = r} defaultValue={this.props.someValue} />
>   );
> }
> // ...
> ```
> 
> May it help other wandering Googlers out there.

your input gets rerender because of arrow function ```ref={(r) => this._someInput = r}```, correct answer is to use key={value}

try not use arrow function inside render function and use early binding for example.
[https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-no-bind.md](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-no-bind.md)
