### ISSUE TITLE
Add link to old docs in the new beta documentation

### ISSUE THREAD

**Issue by bpas247** [react-bootstrap/react-bootstrap#3600]
After answering a lot of questions on our channel on the Reactiflux discord server, the most common question asked is
> where is the link to the old docs (0.32.4)?

Even though the link is in our README, it somehow gets missed a lot. 

We should include a link to these docs in a very obvious place in the latest version of our documentation, possibly in the header component.

**Comment by goyan** [comment]
I was actually expecting the version display to be a version selector, would be neat.
![image](https://user-images.githubusercontent.com/3239422/55758983-2f5cb880-5a50-11e9-85a0-a426914b4fa7.png)

**Comment by jquense** [comment]
Would love this, but haven't had the time to make it happen, if anyone wants to do it go for it 👍

**Comment by evangrim** [comment]
just changing the link text in the readme would help (link from doc sites would also be nice):

<p>Documentation for the latest  <a href="https://5c507d49471426000887a6a7--react-bootstrap.netlify.com/" rel="nofollow">Bootstrap 3 compatible release</a> is also available.</p>
