### ISSUE TITLE
Browser Support - Modal is not supported in Chrome 41

### ISSUE THREAD

**Issue by Ktchan825** [react-bootstrap/react-bootstrap#3620]
Modal Element is not supported in Chrome 41
Google is using chrome 41 for rendering in search engine

**Comment by taion** [comment]
Do you have further details or a repro?

**Comment by mxschmitt** [comment]
I can reproduce it with browserstack. I try to find the cause in 1-2 days, maybe today.

**Comment by mxschmitt** [comment]
![image](https://user-images.githubusercontent.com/17984549/55894910-6c918980-5bbb-11e9-928b-7bd845553138.png)
![image](https://user-images.githubusercontent.com/17984549/55894935-76b38800-5bbb-11e9-9205-bea55693e660.png)

@taion @jquense I think thats caused by the new hooks change.

**Comment by mxschmitt** [comment]
I found the issue. Due the new React Hooks change internally, you need a `Object.assign` polyfill. We recommend this one, which is officially by the React team.
https://github.com/facebook/create-react-app/tree/master/packages/react-app-polyfill

Just load there the `IE11` version at the top of your `index.js`.

```js
import 'react-app-polyfill/ie11';
```

**Comment by mxschmitt** [comment]
Not sure, but we should either definitely add this to the README and docs or add the polyfill in `react-boostrap` itself.

**Comment by taion** [comment]
See https://github.com/react-bootstrap/configs/pull/1.
