### ISSUE TITLE
defaultActiveKey prop missing from Nav types

### ISSUE THREAD

**Issue by cbzehner** [react-bootstrap/react-bootstrap#3623]
The [Nav type definition](https://github.com/react-bootstrap/react-bootstrap/blob/master/types/components/Nav.d.ts) is missing the `defaultActiveKey` property from the [documentation](https://react-bootstrap.netlify.com/components/navs)

Would y'all accept a PR adding this property to the types file?

**Comment by taion** [comment]
Please do so. Thanks!
