### ISSUE TITLE
OverlayTrigger will not show the overlay if its child node is disabled

### ISSUE THREAD

**Issue by benekastah** [react-bootstrap/react-bootstrap#364]
Made a quick jsfiddle demonstrating the issue: http://jsfiddle.net/reactjs/69z2wepo/. You will see that the enabled button shows the tooltip while the disabled button does not.

I think it should be possible (perhaps as an option -- if one exists, I'd love to be made aware of it) to show tooltips on disabled items. A common use case for this would be to add a tooltip to a disabled button explaining to the user why it's disabled.

**Comment by benekastah** [comment]
I guess this is default html behavior (http://stackoverflow.com/questions/18113937/fire-onmouseover-event-when-element-is-disabled).

**Comment by mathieumg** [comment]
> A common use case for this would be to add a tooltip to a disabled button explaining to the user why it's disabled.

I have the same needs! Perhaps it could be a prop to pass to the `OverlayTrigger` so that it wraps its child with an extra div, allowing the tooltip to happen. Something like `allowDisabled`. I'll ask the other contributors if they think this is relevant.

**Comment by mtscout6** [comment]
While this appears to be achievable I'd advocate finding another approach. When something can be clicked by a mouse it should also be able to be reached via the keyboard. Which means it should be tab-able.  That would be odd behavior to tab to a div then to the underlying button. Also, for visual reference seeing a disabled button wouldn't usually have the means to trigger behavior. I'd advocate for a different approach that adheres to better accessibility standards.

**Comment by mathieumg** [comment]
Fair enough, thanks for pitching in!

**Comment by ericgio** [comment]
I ran into this issue as well and agree that there's a valid use case for enabling tooltips on disabled components.

**Comment by pastaclub** [comment]
Sure there is a valid use case, namely the tooltip being there to explain why the component is disabled (e.g. "Please login first to access this feature")

**Comment by jquense** [comment]
folks this isn't a situation where we are intentionally not allowing some behavior on principle. Browsers do not allow this, and there isn't anything reasonable we can do to workaround it

**Comment by pastaclub** [comment]
I have created a react component that provides a work-around: [react-bootstrap-tooltip-button](https://github.com/pastaclub/react-bootstrap-tooltip-button). It uses wrapping `<div>` method, but it also fixes the arising styling problems (in order to display corners and margins correctly, Bootstrap relies on buttons being direct children of button toolbars or button groups or direct siblings of other buttons). My component brings custom CSS to build on Bootstrap's and fix all those issues, so the component behaves really just like you would expect a bootstrap button to behave.
