### ISSUE TITLE
getValue of Input type="radio" works wrong

### ISSUE THREAD

**Issue by deser** [react-bootstrap/react-bootstrap#365]
It returns value of getInputDOMNode() ( return this.getInputDOMNode().value;). In this way getValue returns always the same value of last rendered input not selected.

**Comment by mtscout6** [comment]
Something to be considered when working #342.

**Comment by aabenoja** [comment]
This sounds like it could be resolved with the introduction of a `RadioGroup` to keep track of the selected value.

**Comment by taion** [comment]
For a single radio button, I think it's correct to be consistent with normal `<input>` elements. Although `RadioGroup` is pretty great.
