### ISSUE TITLE
Modal: not working in IE 10

### ISSUE THREAD

**Issue by denisplaster** [react-bootstrap/react-bootstrap#3653]
Modal: still not working in IE 10 with new update.

Has anyone else tested the modal in IE 10? Is twas supposed to be fixed with the v.8 update, but I am getting the same blank screen as before.

**Comment by jquense** [comment]
can you make sure you've deleted your node_modules/package-lock/yarn.lock and have the right version reinstalled?

**Comment by denisplaster** [comment]
Yes, I deleted the node modules and package-lock. reintalled the npm i react-bootstrap and then did a fresh npm install.

**Comment by denisplaster** [comment]
So, I just running an app with just the modal and it is working, so it looks like it's just a bug in my code I need to figure out. Just strange that it does work in IE 11 with my current code.

**Comment by denisplaster** [comment]
I figured out the problem code. I don't think it's anything on my side. It boils down to the class "fixed-top" for me. i had to remove it from the nav and then the modal worked fine. Not sure if there are other bootstrap classes that are breaking the modal, but this one for sure is.

**Comment by brady-vitrano** [comment]
I am having the same issue. The modal will open for me in IE 10 but it will white screen when closing the modal. I am using `react-bootstrap` to render the modal. I copied the HTML for the `<nav>` directly from Bootstrap website. 

As suggested by @denisplaster I removed the class name `fixed-top` from the `nav` element to remedy the issue.

**Comment by Jammar** [comment]
I have tried removing `fixed-top` and this is still an issue for me.

Other people have suggested removing the animation fade (add `animation={false}`) or adding `.modal-open .modal .modal-backdrop {
  display: block!important;
}` but nothing seems to work for me -- still white page
