### ISSUE TITLE
Input field block spaces inside a NavDropdown title using react-bootstrap

### ISSUE THREAD

**Issue by alvaroquezada** [react-bootstrap/react-bootstrap#3658]
I'm a doing a search field inside a nav bar and I need to display the results as a dropdown menu to allow the users to select one of the results. The problem is the Dropmenu blocks the space key event, so my inputs don't allow space. If I write "Hello World", the input displays "HelloWorld" instead.

I'm using `react-bootstrap 0.32.4`

Here is a sipmplificated versión of my field:
```javascript
class SearchField extends React.Component {
  constructor(props) {
    super(props);
    this.state = { text: "" };
  }
  handleChange = e => {
    this.setState({ text: e.target.value });
    /*
    Here is where I need to implement the handling
    of the user input while he writes
    */
  };
  render() {
    const form = (
      <Form>
        <FormGroup>
          <FormControl
            type="text"
            value={this.state.text}
            onChange={this.handleChange}
          />
        </FormGroup>
      </Form>
    );
    return form;
  }
}
```

And a here how it is embedded inside the title of the Dropdown, it works fine with exception of the spaces...

```javascript
class Navigation extends React.Component {
  render() {
    return (
      <Navbar fixedTop fluid>
        <Navbar.Header>
          <Navbar.Brand>TEST</Navbar.Brand>
        </Navbar.Header>
        <Nav>
          <NavDropdown id="m1" title="menu 1">
            <MenuItem>item 1</MenuItem>
            <MenuItem>item 2</MenuItem>
          </NavDropdown>
          <NavDropdown id="m2" title="menu 2">
            <MenuItem>item 3</MenuItem>
            <MenuItem>item 4</MenuItem>
          </NavDropdown>
          <NavDropdown title={<SearchField />}>
            <MenuItem>item 5</MenuItem>
            <MenuItem>Item 6</MenuItem>
          </NavDropdown>
        </Nav>
      </Navbar>
    );
  }
}
```
Here you can try out this code:
https://codesandbox.io/s/ryy3vkmrzo

**Comment by taion** [comment]
It's not the menu. It's the "click" handler on the dropdown toggle button itself. You'll want to render a custom `<Dropdown>` and not use `<NavDropdown>` if you're trying to use an input there and not have it be in an anchor, or else block bubbling on the keyboard event.

**Comment by alvaroquezada** [comment]
Sorry, can you provide me extra help on this, I don't understand what I have to do to achieve a field in the nav bar that displays the results as a menu... the example above works perfect, with the exception of trying to type a space.
