### ISSUE TITLE
npm install throws peerinvalid error

### ISSUE THREAD

**Issue by forceoflight** [react-bootstrap/react-bootstrap#366]
~/repos/react-bootstrap[master*]$ npm install
npm ERR! peerinvalid The package react does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-async@2.0.1 wants react@~0.12.0
npm ERR! peerinvalid Peer react-router-component@0.12.1 wants react@~0.9.0

npm ERR! System Darwin 13.4.0
npm ERR! command "node" "/usr/local/bin/npm" "install"
npm ERR! cwd /Users/<NAME>/repos/react-bootstrap
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.4.3
npm ERR! code EPEERINVALID
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/<NAME>/repos/react-bootstrap/npm-debug.log
npm ERR! not ok code 0

**Comment by mtscout6** [comment]
@forceoflight are you still seeing this? Have you tried running `git clean -dfx` and retry `npm install`?

**Comment by forceoflight** [comment]
Actually issue is in our company proxy. At time when I submitted issue I was modified following dependency.

"react-router-component": "git://github.com/STRML/react-router-component#react-0.12",
=>
"react-router-component": "~0.12",

I need to do that because our proxy does not support git protocol. Would it be possible to get rid of that and use dependency solution I illustrated above?

**Comment by mtscout6** [comment]
I changed the url to the https tagged tarbal pointed at the same commit as the previous branch url was pointing. That should fix your problem.
