### ISSUE TITLE
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

### ISSUE THREAD

**Issue by ivanherve** [react-bootstrap/react-bootstrap#3665]
Hi, I'm trying to import a simple button as here :
```
import React, { Component } from 'react';
import {Button} from 'react-bootstrap';

class About extends Component {
  render() {
    return(
      <div>
        <h1>About Page</h1>
        <Button>Hello</Button>
      </div>
    )
  }
}
export default About;
```
But I get this message:
![image](https://user-images.githubusercontent.com/23102351/56202227-3df83080-604b-11e9-85c8-912c4862e279.png)

I tried to ``yarn upgarde react`` and also ``react-dom`` to their latest versions like I saw on other issues but I still have the same error message.

Here is my package.json:
```
{
  "name": "project",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "react": "^16.8.6",
    "react-bootstrap": "^1.0.0-beta.8",
    "react-dom": "16.2",
    "react-mdl": "^1.11.0",
    "react-router-dom": "4.2.2",
    "react-scripts": "2.1.8"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": [
    ">0.2%",
    "not dead",
    "not ie <= 11",
    "not op_mini all"
  ]
}
```
Well, for this project I'm using also `react-mdl`, does it matter ?

In fact, the ``About`` component is a child component and I'm using ``react-mdl`` in almost all the project

Thank you

**Comment by mxschmitt** [comment]
Please update `react-dom`: https://www.npmjs.com/package/react-dom (16.8.6)

**Comment by ivanherve** [comment]
Aaah thanks @mxschmitt ! Everything is fixed now

**Comment by gaambo** [comment]
is there any information on how this is fixed with an updated react-dom version? i'm trying to use it in a wordpress gutenberg block and there i'm stuck with the react-dom version used by the current gutenberg/wordpress version.

**Comment by victor-enogwe** [comment]
Hello @gaambo try setting `"esModuleInterop": true` on tsconfig.
