### ISSUE TITLE
New beta release

### ISSUE THREAD

**Issue by gurkerl83** [react-bootstrap/react-bootstrap#3666]
Thanks to @bpas247 and @taion accordion, and respective types are available. Is there a chance we see a new beta release anytime soon, so we can test those.

**Comment by jquense** [comment]
They are already released in the latest beta 👍

**Comment by gurkerl83** [comment]
At least the types where not in the release, see https://github.com/react-bootstrap/react-bootstrap/compare/v1.0.0-beta.8...master . I downloaded the compressed version and types are not there as mentioned. Thx.

**Comment by bpas247** [comment]
Accordion types were merged in #3624, Which happened after the beta 8 release bump f4c33137f1c2601d4ff3397b4619fa6705b34742. You might have to wait until beta 9 release to get those types via NPM.

**Comment by persinac** [comment]
Just chiming in to see if beta 9 is out? I'm on #8 and just copied/pasted the Accordion*.d.ts code that @bpas247 and @taion committed. Works great, just curious if there's an eta on beta 9?
