### ISSUE TITLE
0.32 docs?

### ISSUE THREAD

**Issue by createthis** [react-bootstrap/react-bootstrap#3667]
For those of us who cannot just jump to 1.0 immediately, how do you recommend we access the old documentation for 0.32.x? This is causing my team some development grief at the moment.

**Comment by taion** [comment]
see https://github.com/react-bootstrap/react-bootstrap#docs

and the next docs cut will add it to the docs header too

**Comment by createthis** [comment]
Sorry, I'm not sure if that link is new, but I didn't see it a week or so ago. Works great. Thanks!
