### ISSUE TITLE
dropdown menus

### ISSUE THREAD

**Issue by jvillasante** [react-bootstrap/react-bootstrap#368]
I'm using React.bootstrap in combination with react-router and react-router-bootstrap. The problem I'm facing is that when I put a Dropdown on a Navbar, the actions works as expected, but the dropdown keeps open, I would like that when the user clicks a menu from the dropdown, the route kicks and the dropdown goes away. Here's my code, the return clause of the render method:

```javascript
    return (
      <div>
        <Navbar ref="header" className="navbar navbar-default" brand={brand} fixedTop={true} fluid={true} toggleNavKey={1}>
          <Nav className="navbar-left" eventKey={1}>
            <NavItemLink to="dashboard" eventKey={2}>Dashboard</NavItemLink>
            <DropdownButton eventKey={3} title="Admin">
              <MenuItemLink to="users" eventKey="1">Users</MenuItemLink>
              <MenuItemLink to="projects" eventKey="2">Projects</MenuItemLink>
            </DropdownButton>
          </Nav>
        </Navbar>

        <RouteHandler />

        <div className="navbar-footer">
          <div className="container">
            <p className="text-muted">
              <span>some footer text</span>
            </p>
          </div>
        </div>
      </div>
    );
```

**Comment by tjwebb** [comment]
>  but the dropdown keeps open,

+1

**Comment by z-ax** [comment]
+1.

Also, with a `react-mini-router` route is reset to default action when DD is opened - and `onClick` or `onSelect` aren't triggered at all in this case. Not sure yet what's happening.

**Comment by z-ax** [comment]
Seen 15th release, any updates here?

**Comment by wiredprairie** [comment]
@jvillasante - Have you tried to use `onSelect` with the `DropdownButton`? I don't have a working example that is exactly like yours, but I just noticed that the Dropdown closes when I've attached an event handler to `OnSelect`:

    <DropdownButton eventKey={3} title="Admin" onSelect={ this.OnSelected } >

    onSelected: function(e) {
        // doesn't need to have functionality (necessarily) ... just wired up
    }

Internally, a call to `DropdownButton.setDropDownState(false)` is made which will hide the dropdown menu. So, you should be able to call that directly on the DropdownButton instance as well if needed.

**Comment by rapilabs** [comment]
@wiredprairie that solution will close the menu, however the link is not followed due to the default action being prevented: https://github.com/react-bootstrap/react-bootstrap/blob/master/src/MenuItem.jsx#L24

**Comment by rapilabs** [comment]
I've made a patch that simply adds an onSelect prop if a href prop is present and then ignore the e.preventDefault() in the handleClick callback: https://github.com/react-bootstrap/react-bootstrap/pull/411

**Comment by mtscout6** [comment]
Part of #419

**Comment by reduxdj** [comment]
Why is the event undefined in the onSelect Handler?

     handleSelect: (e) ->
      e.preventDefault()

**Comment by mtscout6** [comment]
@reduxdj it's part of a known issue as described in #419. Is getting cleaned up in #526.

**Comment by AlexKVal** [comment]
Superceded by #526

**Comment by barbalex** [comment]
I have this problem too (on version 0.24.3) and it seems extremely basic:

- either you have an onSelect handler on DropdownButton: then links and onClick handlers of menu items don't work
- or you don't have that. Then the Button stays open after klicking a menu item

I must be missing something fundamental. What is the solution to this problem?

**Comment by barbalex** [comment]
o.k, got it to work like this:

    componentDidMount () {
      // this is a bad hack for react-bootstrap not closing the menu on click
      $('#menuBtn a').on('click', function () {
        console.log('click')
        $('#menuBtn .dropdown-toggle').click()
      })
    }

**Comment by showcasefloyd** [comment]
Sorry if this is old, but is there way to keep the menu open if select a MenuItem inside of a DropdownButton. I've tried e.preventDefault inside of my onClick event and it doesn't seem to work.

Thanks so much in advance

**Comment by jmvillavicencio** [comment]
Same problem. Any solution?

**Comment by showcasefloyd** [comment]
No I was able to get it work, with their code.
