### ISSUE TITLE
Add touch support for carousels

### ISSUE THREAD

**Issue by xyzr07** [react-bootstrap/react-bootstrap#3683]

**Comment by taion** [comment]
What do you mean?

**Comment by xyzr07** [comment]
I mean for change slide, I do not click the button in right side or left side, but I can swipe the slide for change next or prev slide

**Comment by taion** [comment]
Okay, apparently upstream shipped this in 4.2: https://github.com/twbs/bootstrap/pull/25776.

**Comment by mxschmitt** [comment]
I will close this here, because you can simply just use Bootstrap 4.2. 👍 
thx to @taion

**Comment by xyzr07** [comment]
> I will close this here, because you can simply just use Bootstrap 4.2. 👍
> thx to @taion

you can give me example ?

**Comment by mxschmitt** [comment]
sure, but depends on how you import the Bootstrap 4 styles into your project. If via a CDN, just use the latest version of that (mostly included into the head tag of your application). If via npm, just update the version in your `package.json`.

**Comment by taion** [comment]
@mxschmitt we need to pull this logic into our JS as well, though

**Comment by Riseley** [comment]
Hi, I tried to import bootstrap-css-only 4.3.1 in index.js, and tried  <Carousel data-touch="true"...> but it doesn't work as mentioned as "you can simply just use Bootstrap 4.2". After looking into the code, as taion mentioned, we may need to pull the JS logic.

**Comment by yasserzubair** [comment]
Hi there, I have update the bootstrap and react-bootstrap to latest, no luck with slide change on swipe. Any updates?

**Comment by taion** [comment]
See the open PR right now. This isn't merged yet, let alone released.

**Comment by hafidzamr** [comment]
can open again? or can tell me tips for touch carousels for desktop view ? for now just work for mobile view or any config for enable touch carousels for desktop view ?

thanks
