### ISSUE TITLE
bs3-dev branch to separate Netlify build

### ISSUE THREAD

**Issue by mxschmitt** [react-bootstrap/react-bootstrap#3684]
Hi,

not sure who has the permissions, but we should maybe add another deployment to Netlify, which will only build the ` bs3-dev` branch to a separate Netlify subdomain. Not sure if something like that is possible. Because currently, we have to change the entire URL to the bootstrap 3 docs on all the places (Readme, Gatsby site) when we update it. (afaik) Like in #3655

**Comment by mxschmitt** [comment]
@jquense maybe you can add me on Netlify so I can adjust it?

**Comment by jquense** [comment]
doesn't look like the free plan allows more users :/ I'm not actually sure how to set this up tho, I guess make a new site?

**Comment by mxschmitt** [comment]
Yep. You can write the support to get the special plan for big Open Source projects: https://www.netlify.com/legal/open-source-policy/

After that we have unlimited users. :)

**Comment by mxschmitt** [comment]
@jquense friendly ping, have you contacted Netlify?

**Comment by jquense** [comment]
hey, sorry no, i've not had any time.

**Comment by mxschmitt** [comment]
@jquense friendly ping, have you contacted Netlify? Or does anybody else have access?

**Comment by mxschmitt** [comment]
@jquense friendly ping, have you contacted Netlify? Or does anybody else have access?

**Comment by jquense** [comment]
thanks for the reminder sent off an email to them

**Comment by mxschmitt** [comment]
@jquense any response? :)

**Comment by jquense** [comment]
@mxschmitt sorry for taking so long to get back to you I've got it set up and invited you to the team 

@react-bootstrap/collaborators If anyone wants netlify access please post the email to invite you with here
