### ISSUE TITLE
Utilize contexts for state

### ISSUE THREAD

**Issue by dcramer** [react-bootstrap/react-bootstrap#369]
I realize contexts are not officially released, but they're used by react-router, and we're now using them and finding great value in them. I think it'd make sense to move a lot of the state passing into context helpers to ensure child nodes can always control things like overlay state.

We did this on a project to resolve an issue with a Dropdown not closing (not apparent why, but it shouldn't really matter): https://github.com/getsentry/sentry/commit/3bbe9e2

Here's what a simple version of this for DropdownLink might look like in practice:

```
var CustomDropdownLink = React.createClass({
  mixins: [BootstrapMixin, DropdownStateMixin],

  childContextTypes: {
    setDropdownState: React.PropTypes.func,
  },

  getChildContext() {
    return {
      setDropdownState: this.setDropdownState,
    };
  },
});

var DropdownContext = {
  contextTypes: {
    setDropdownState: React.PropTypes.func
  },

  setDropdownState() {
    this.context.setDropdownState.apply(arguments);
  }
};

var CustomMenuItem = React.createClass({
  mixins: [DropdownContext],

  handleClick(e) {
    // we can now close the dropdown very easily from any child component
    // without react-bootstrap (hopefully) deciding in advance that we
    // needed to
    this.setDropdownState(false);
  },
});
```

**Comment by mtscout6** [comment]
These seems to couple the dropdown with the CustomeMenuItem which in my mind is unrelated to the dropdown. It may land inside a dropdown, or it may not. In this case using props is preferable to me. I understand that there has been some issues with the current dropdown, which I am hoping to find time to tackle at some point. I don't think contexts will be the right solution though.
