### ISSUE TITLE
Carousels rendering all together vertically.

### ISSUE THREAD

**Issue by gotyet9** [react-bootstrap/react-bootstrap#3691]
I am just trying to render a very very basic straight carousel.

```
<Carousel>
  <Carousel.Item>
    <img
      className="d-block w-100"
      src="holder.js/800x400?text=First slide&bg=373940"
      alt="First slide"
    />
    <Carousel.Caption>
      <h3>First slide label</h3>
      <p>Nulla vitae elit libero, a pharetra augue mollis interdum.</p>
    </Carousel.Caption>
  </Carousel.Item>
  <Carousel.Item>
    <img
      className="d-block w-100"
      src="holder.js/800x400?text=Second slide&bg=282c34"
      alt="Third slide"
    />

    <Carousel.Caption>
      <h3>Second slide label</h3>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
    </Carousel.Caption>
  </Carousel.Item>
  <Carousel.Item>
    <img
      className="d-block w-100"
      src="holder.js/800x400?text=Third slide&bg=20232a"
      alt="Third slide"
    />

    <Carousel.Caption>
      <h3>Third slide label</h3>
      <p>Praesent commodo cursus magna, vel scelerisque nisl consectetur.</p>
    </Carousel.Caption>
  </Carousel.Item>
</Carousel>;
```

But its not even rendering properly. Obviously i might be missing something very silly.
Its rendering all the images all together vertically. Also the indicator are not aligned properly. Is there some css required. If yes from where can i  get it.

Please help me im totally stuck in this issue.
Any help will be really appreciated.

Thanks

**Comment by taion** [comment]
You just need the standard Bootstrap CSS. See https://react-bootstrap.github.io/getting-started/introduction#stylesheets.

**Comment by gotyet9** [comment]
@taion well, i already tried that many many times. Images still remain stacked vertically. 
I placed the latest cdn provided at the very top but still no success.

**Comment by taion** [comment]
Make sure the versions of React-Bootstrap and the Bootstrap CSS that you use match. And then check in your debugger that the classes are defined appropriately.
