### ISSUE TITLE
fold-down menu

### ISSUE THREAD

**Issue by GuoYuefei** [react-bootstrap/react-bootstrap#3695]
The use document for the fold-down menu could not be found
(Vertical menu, submenu embedded in menu area)
Similar to this effect
[https://codepen.io/pen/?&amp;editable=true&amp;editors=001](https://codepen.io/pen/?&amp;editable=true&amp;editors=001)

**Comment by taion** [comment]
That link doesn't work. What's the upstream component here?

**Comment by mxschmitt** [comment]
@GuoYuefei please provide us more information, otherwise we will close this issue.

**Comment by bpas247** [comment]
Gonna go ahead and close this issue for now due to staleness.

@GuoYuefei Feel free to open this issue back up once you have more information to give us 👍
