### ISSUE TITLE
formik example not working properly

### ISSUE THREAD

**Issue by ThomasRoest** [react-bootstrap/react-bootstrap#3711]
This doesn't seem to work like it should. When you type in the username field it immediately validates the other fields as well..

https://react-bootstrap.github.io/components/forms/#forms-validation-libraries

**Comment by jquense** [comment]
its not super intuitive but that's actually just how formik works at the moment

**Comment by ThomasRoest** [comment]
no I don't think it's correct, it should validate if there are any errors and the input is 'touched'
This works for me
`isInvalid={errors.username && touched.username ? true : false}`

**Comment by jquense** [comment]
if you do that then `submit` won't show errors for fields you didn't touch as well which is also not the best

**Comment by jquense** [comment]
and for reference: https://github.com/jaredpalmer/formik/pull/780

**Comment by ThomasRoest** [comment]
> if you do that then hitting the submit button won't show errors for fields you didn't touch as well which is also not the best

It does work on submit as well
