### ISSUE TITLE
Input autocomplete 

### ISSUE THREAD

**Issue by crisward** [react-bootstrap/react-bootstrap#372]
Any chance, on Input, if you could passthrough autocomplete etc... to the input tag..

like 

http://css-tricks.com/snippets/html/autocomplete-off/

Thanks!

**Comment by crisward** [comment]
Sorry, my mistake, this needs to be autoComplete in react... it then works as expected.

**Comment by mtscout6** [comment]
Any props you send that we don't use are just passed along, if that's not what you are seeing let us know. See: https://github.com/react-bootstrap/react-bootstrap/blob/v0.14.0/src/Input.jsx#L112, note the `<input {...this.props}` that's what should pass it along.

**Comment by crisward** [comment]
Just noticed if you do it with autocomplete lowercase, nothing get passed through. Just checked and it seems to be a react thing autocomplete here http://facebook.github.io/react/docs/tags-and-attributes.html is listed as autoComplete.

**Comment by dharkness** [comment]
Passing `autoComplete="username"` ends up with `autocomplete="off"` which is not what I want. Using `autocomplete` displays a console error that it's an invalid property.

```
<Form.Control
    type="text" autoFocus autoComplete="username" required 
    value={username} onChange={e => setUsername(e.target.value)}
/>
```

produces

```
<input 
    autocomplete="off" required="" type="text" id="username" 
    class="form-control" value="..." style="..."
>
```
