### ISSUE TITLE
Ability to disable root close wrapper for Dropdown

### ISSUE THREAD

**Issue by sawyna** [react-bootstrap/react-bootstrap#3723]
I am trying to implement a custom dropdown suitable to our needs as mentioned [here](https://5c507d49471426000887a6a7--react-bootstrap.netlify.com/components/dropdowns/#btn-dropdowns-custom).

The component render looks something like this.

```
<Dropdown
                    id="autocomplete-dropdown"
                    onToggle={this.onToggle}
                    onSelect={this.onSelect}
                    open={this.state.open}
                    defaultOpen={false}
                >

                    <FormGroup bsRole="toggle">
                        <FormControl
                            type="text"
                            value={this.state.searchTerm}
                            placeholder={this.props.placeholder}
                            onChange={this.handleSearchTerm}
                        />
                    </FormGroup>


                    <Dropdown.Menu
                        bsRole="menu"
                    >
                        {this.state.dataToDisplay.map((element) => {
                            return (<MenuItem key={element.unique_id} eventKey={element.id}
                            >{element.description}</MenuItem>);
                        })}
                    </Dropdown.Menu>

                </Dropdown>
```

The problem in question `onToggle` is implemented as follows.

```
onToggle(isOpen, event, metadata) {

        if (metadata.source === 'click' && this.state.open) {
            return;
        }

        this.setState({
            open: isOpen,
        });

        if (!(this.state.open)) {
            this.updateSomethingElse();
        }
    }
```

I want to keep the dropdown open even if someone clicks in the form input.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/11388606/56890540-a2ff4d80-6a71-11e9-9c79-0d91f1a124e7.gif)

With the above implementation, `rootCloseEvent` collides with `onToggle` and overrides my attempt to keep the dropdown open. I had to make something like this to get this to work. 

I had to disable the existing `RootCloseWrapper` by tricking it passing an invalid `rootCloseEvent` and wrap my custom dropdown with a new `RootCloseWrapper`.

```
(
            <RootCloseWrapper
                disabled={!(this.state.open)}
                onRootClose={(event) => {
                    this.onToggle(!(this.state.open), event, { source: 'rootCloseCustom' });
                }}
            >
                <Dropdown
                    id="autocomplete-dropdown"
                    onToggle={this.onToggle}
                    onSelect={this.onSelect}
                    open={this.state.open}
                    defaultOpen={false}
                    rootCloseEvent={''} // This seems to be the only way for now to disable rootclose event in Dropdown
                >

                    <FormGroup bsRole="toggle">
                        <FormControl
                            type="text"
                            value={this.state.searchTerm}
                            placeholder={this.props.placeholder}
                            onChange={this.handleSearchTerm}
                        />
                    </FormGroup>


                    <Dropdown.Menu
                        bsRole="menu"
                    >
                        {this.state.dataToDisplay.map((element) => {
                            return (<MenuItem key={element.unique_id} eventKey={element.id}
                            >{element.description}</MenuItem>);
                        })}
                    </Dropdown.Menu>

                </Dropdown>
            </RootCloseWrapper>
        );
```

It'd be great if the `Dropdown` component can expose a way of controlling the `RootCloseWrapper` it contains.

**Comment by taion** [comment]
Couldn't you accomplish what you want just by checking the `event` in `onToggle` when it is a root close?

**Comment by sawyna** [comment]
That's the point. I cannot control custom toggling in `onToggle` because of the way `RootCloseWrapper` is. If I try to conditionally keep the dropdown open as you said, `RootCloseWrapper` force closes the dropdown as the click is outside the `Dropdown`. That's exactly what happens in the gif.

Because `RootCloseWrapper` is around `Dropdown.Menu` and not `FormGroup`, the `input` field falls outside of `RootCloseWrapper`.

**Comment by taion** [comment]
You can control the open state directly, and use the event to determine whether to toggle it.

**Comment by sawyna** [comment]
You can see from the gif that it doesn't work as the rootclosewrapper is only around dropdown.

**Comment by karisd** [comment]
@sawyna Did you figure this out? I am trying to do the exact same thing.

**Comment by sawyna** [comment]
Yeah, but it's not the cleanest. To disable the internal `rootCloseWrapper`, pass empty string to it. That way it is disabled and you can wrap it with your own `RootCloseWrapper`. See the last part of https://github.com/react-bootstrap/react-bootstrap/issues/3723#issue-438248646 for implementation details.

**Comment by s-stefanov** [comment]
If you want to fix the problem and you are using custom Dropdown toggle, you need to add `className='dropdown-toggle'` and it will not count the input to be outside of the dropdown.
