### ISSUE TITLE
Accordion Component Toggling Question

### ISSUE THREAD

**Issue by andrewnystrom** [react-bootstrap/react-bootstrap#3726]
Hello, 

I noticed that there doesn't seem to be a way to individually toggle `Accordion.Collapse`

If I click on the `Accordion.Toggle` once, the collapse opens as expected. If I click on that same toggle again, nothing happens. My expectation is that the original collapse would close. Is this by design? If not, would you be open to me submitting a PR to introduce this functionality? 

Thank you.

**Comment by jquense** [comment]
I think it should probably close if you click again (upstream does this https://getbootstrap.com/docs/4.3/components/collapse/#accordion-example) for more complicated interactions tho the expectation would be to use `Collapse` directly and manage the state ones self

**Comment by andrewnystrom** [comment]
Yes -- completely agree about the more complicated interactions. I have already identified a solution and will create a PR for review later today. Thanks!

**Comment by bpas247** [comment]
Is this issue still up for grabs? I wouldn't mind working on it if it is.

**Comment by andrewnystrom** [comment]
That would be wonderful; I haven’t had a chance yet. Got slammed with work.
