### ISSUE TITLE
How to reset the form after successful submit ?

### ISSUE THREAD

**Issue by gkumar9** [react-bootstrap/react-bootstrap#3730]

**Comment by mxschmitt** [comment]
Read this: https://reactjs.org/docs/forms.html

Just set the value property to an empty string after your submit. :)

**Comment by gkumar9** [comment]
Actually, I was more concerned about the `form.control.feedback` , because as soon as I set the values to an empty string, the feedback pops up the error thinking it's not how values should be.

**Comment by athimannil** [comment]
@gkumar9 did you find solution for it ?

**Comment by gkumar9** [comment]
no man

**Comment by juanmamig** [comment]
For other people getting the same problem:

> Actually, I was more concerned about the `form.control.feedback` , because as soon as I set the values to an empty string, the feedback pops up the error thinking it's not how values should be.

Just remove the className `was-validated` of boostrap Form component. 
Here is a pseudoCode example:

```
import React, { useRef } from 'react';

  const formRef = useRef(null);

  const handleReset = () => {
    formRef.current.reset();
    formRef.current.classList.remove('was-validated');
  };

const handleSubmit = () => {
// Do stuff here
handleReset();
}

<Form
        ref={formRef}
        validated={validated}
        onSubmit={handleSubmit}
      >
</Form>
```

**Comment by AlejandroWogelman** [comment]
> For other people getting the same problem:
> 
> > Actually, I was more concerned about the `form.control.feedback` , because as soon as I set the values to an empty string, the feedback pops up the error thinking it's not how values should be.
> 
> Just reset the validated attribute on Bootsrap Form.
> Here is a pseudoCode example:
> 
> ```
> import React, { useRef, useState } from 'react';
> const FormComponent = () => {
>   const [validated, setValidated] = useState(false);
>   const formRef = useRef(null);
> 
>   const handleReset = () => {
>     formRef.current.reset();
>     setValidated(false);
>   };
> 
>   const handleSubmit = () => {
>      // Do stuff here
>      // On success or error:
>     setValidated(true);
>     handleReset();
>   }
> 
>    return(
>       <Form ref={formRef}  validated={validated} onSubmit={handleSubmit}>
>         // your form inputs
>       </Form>
>    );
> export default FormComponent;
> }
> ```

Thanks!!!

**Comment by markdost** [comment]
That does work but what about custom validation with `noValidate` on the `<Form noValidate ref={formRef}  validated={validated} onSubmit={handleSubmit}>`?

I am trying to figure out how to handle the form reset:
```
  // Form validation
  const [validated, setValidated] = useState(false);

  // Reset form
  const formRef = useRef();
  const handleReset = () => {
    formRef.current.reset();
    setValidated(false);
  };

  // Thank you Message
  const [thankYouMessage, setThankYouMessage] = useState(false);

  // Form submit handler
  async function handleSubmit(e) {
    e.preventDefault();
    e.stopPropagation();

    const formData = new FormData();

    Array.from(e.currentTarget.elements).forEach((field) => {
      if (!field.name) return;
      formData.append(field.name, field.value);
    });

    await fetch(
      "https://domain.tld/wp-json/contact-form-7/v1/contact-forms/1234/feedback",
      {
        body: formData,
        method: "POST",
      }
    )
      .then((response) => response.json())
      .then((response) => {
        if (response.status === "mail_sent") {
          setThankYouMessage(!thankYouMessage);
        } else if (response.status === "mail_failed") {
          alert("Message failed to send.");
        }
      });

    setValidated(true);
    handleReset();
  }
  ```
  And the form:
  ```
      <div className="shadow rounded p-lg-6 p-3">
      <Form
        noValidate
        ref={formRef}
        validated={validated}
        onSubmit={handleSubmit}
      >
        <Form.Group controlId="your-name">
          <Form.Control
            required
            type="text"
            placeholder="Your name"
            name="your-name"
          />
          <Form.Control.Feedback type="invalid">
            Please enter your name
          </Form.Control.Feedback>
        </Form.Group>
        <Form.Group controlId="your-email">
          <Form.Control
            required
            type="email"
            placeholder="Your email address"
            name="your-email"
          />
          <Form.Control.Feedback type="invalid">
            Please enter your email
          </Form.Control.Feedback>
        </Form.Group>
        <Form.Group controlId="your-message">
          <Form.Control
            as="textarea"
            cols={30}
            rows={6}
            placeholder="Write your message..."
            name="your-message"
          />
        </Form.Group>
        <Button
          type="submit"
          variant="primary"
          size="lg"
          className="w-100"
        >
          Send Message
          <span></span>
        </Button>
      </Form>
      <Alert
        variant="success"
        className={thankYouMessage ? "d-block mt-3 mb-0" : "d-none"}
      >
        Thank you for your message. It has been sent.
      </Alert>
    </div>
    ```

**Comment by devanada** [comment]
> That does work but what about custom validation with `noValidate` on the `<Form noValidate ref={formRef} validated={validated} onSubmit={handleSubmit}>`?
> 
> I am trying to figure out how to handle the form reset:
> 
> ```
>   // Form validation
>   const [validated, setValidated] = useState(false);
> 
>   // Reset form
>   const formRef = useRef();
>   const handleReset = () => {
>     formRef.current.reset();
>     setValidated(false);
>   };
> 
>   // Thank you Message
>   const [thankYouMessage, setThankYouMessage] = useState(false);
> 
>   // Form submit handler
>   async function handleSubmit(e) {
>     e.preventDefault();
>     e.stopPropagation();
> 
>     const formData = new FormData();
> 
>     Array.from(e.currentTarget.elements).forEach((field) => {
>       if (!field.name) return;
>       formData.append(field.name, field.value);
>     });
> 
>     await fetch(
>       "https://domain.tld/wp-json/contact-form-7/v1/contact-forms/1234/feedback",
>       {
>         body: formData,
>         method: "POST",
>       }
>     )
>       .then((response) => response.json())
>       .then((response) => {
>         if (response.status === "mail_sent") {
>           setThankYouMessage(!thankYouMessage);
>         } else if (response.status === "mail_failed") {
>           alert("Message failed to send.");
>         }
>       });
> 
>     setValidated(true);
>     handleReset();
>   }
> ```
> 

You can do something like this
```
async function handleSubmit(e) {
  e.preventDefault();
  const form = e.currentTarget;
  if (form.checkValidity() === false) {
    e.stopPropagation();
    setValidated(true);
  } else {
    const formData = new FormData();

    Array.from(e.currentTarget.elements).forEach((field) => {
      if (!field.name) return;
      formData.append(field.name, field.value);
    });

    await fetch(
      "https://domain.tld/wp-json/contact-form-7/v1/contact-forms/1234/feedback",
      {
        body: formData,
        method: "POST",
      }
    )
      .then((response) => response.json())
      .then((response) => {
        if (response.status === "mail_sent") {
          setValidated(false);
          setThankYouMessage(!thankYouMessage);
        } else if (response.status === "mail_failed") {
          alert("Message failed to send.");
        }
      });
  }
}

```

**Comment by markdost** [comment]
@devanada Thanks that is working perfectly! 
The only thing I had to add was `handleReset();` so the form resets after submitting it.
``` 
  .then((response) => {
    if (response.status === "mail_sent") {
      handleReset();
      setValidated(false);
      setThankYouMessage({ type: "success" });
    } else if (response.status === "mail_failed") {
      alert("Message failed to send.");
    }
  });
```
