### ISSUE TITLE
Isuue with NavBar

### ISSUE THREAD

**Issue by saipopcornapps** [react-bootstrap/react-bootstrap#3734]
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `NavBar`.

CODE:

import Navbar from 'react-bootstrap/Navbar';
import Nav from 'react-bootstrap/Nav';
import NavItem from 'react-bootstrap/NavItem';

<Navbar>
<Navbar.Header>
  <Navbar.Brand>
    {/* <IndexLink to="/home" activeStyle={{color: '#33e0ff'}}>
      <div className={'brand'}/>
    </IndexLink> */}
    </Navbar.Brand>
  <Navbar.Toggle/>
</Navbar.Header>
  <Nav>
    <LinkContainer to="/logout">
      <NavItem eventKey={7} onClick={this.handleLogout}>
        <i className="fa fa-sign-out" aria-hidden="true"></i>
      </NavItem>
    </LinkContainer>
  </Nav>
  <p >Logged in as <strong>{userData.emp_firstname}</strong>.</p>
<Navbar.Collapse eventKey={0}>
  <Nav >
    <LinkContainer to="/home">
      <NavItem eventKey={1}>Home</NavItem>
    </LinkContainer>
    <LinkContainer to="/leaves">
      <NavItem eventKey={1}>Leaves</NavItem>
    </LinkContainer>
    <LinkContainer to="/directory">
      <NavItem eventKey={1}>Directory</NavItem>
    </LinkContainer>
    <LinkContainer to="/holidays">
      <NavItem eventKey={1}>Holidays</NavItem>
    </LinkContainer>
    <LinkContainer to="/it-requests">
      <NavItem eventKey={1}>IT Requests</NavItem>
    </LinkContainer>
  
  </Nav>
</Navbar.Collapse>
</Navbar>

**Comment by jquense** [comment]
what version are you using?

**Comment by saipopcornapps** [comment]
^1.0.0-beta.8

**Comment by bpas247** [comment]
You would need to post more code in order for us to figure out the issue @saipopcornapps. Could you possibly setup a small CodeSandbox example?

**Comment by mxschmitt** [comment]
Closed due inactivity. Feel free to ping us with an interactive example and we'll reopen this.
