### ISSUE TITLE
Glyphicon list is missing menu-hamburger

### ISSUE THREAD

**Issue by lukerandall** [react-bootstrap/react-bootstrap#374]
The list of allowed glyphicons is missing `menu-hamburger`.

**Comment by mtscout6** [comment]
Will be soon [8126c3](https://github.com/cell303/react-bootstrap/commit/8126c3c897598b897f4dfcafcf5d521c76a33b64#diff-a7748843fbda5167d065231e3a2e7a1fR275). I'm planning to make a release later today.

**Comment by lukerandall** [comment]
Thanks!
