### ISSUE TITLE
Modal type file missing scrollable flag

### ISSUE THREAD

**Issue by chrisdusyk-iq** [react-bootstrap/react-bootstrap#3741]
When developing in Typescript, I was trying to create a `Modal`. According to the docs and the prop types, `scrollable` should be a boolean flag on the [component](https://github.com/react-bootstrap/react-bootstrap/blob/master/src/Modal.js#L59), but it's missing from the [type file](https://github.com/react-bootstrap/react-bootstrap/blob/master/types/components/Modal.d.ts#L15).

**Comment by taion** [comment]
We'd be happy to take a PR here.
