### ISSUE TITLE
Implement float classes

### ISSUE THREAD

**Issue by ilanolkies** [react-bootstrap/react-bootstrap#3744]
Toggle a float with a class as shown [here](https://getbootstrap.com/docs/4.0/utilities/float/#classes).

```html
<div class="col float-left">Float left on all viewport sizes</div><br>
<div class="col float-right">Float right on all viewport sizes</div><br>
<div class="col float-none">Don't float on all viewport sizes</div>
```

I would write it like:
```jsx
<Col float='left'>Float left on all viewport sizes</Col><br />
<Col float='right'>Float right on all viewport sizes</Col><br />
<Col>Don't float on all viewport sizes</Col>
```

**Comment by taion** [comment]
We'd be happy to take a PR to add this.

**Comment by pawgrmr** [comment]
@taion @mxschmitt could I have a go at this? I'm new to contributing but would love to give this a go. Thanks!

**Comment by bpas247** [comment]
Should we aim to cover the responsive variations of `float` (e.g. `float-sm-left`)? Or is this something that's already partially covered with the props of `Col`?

**Comment by ilanolkies** [comment]
Okey. I'm trying to implement this feature. This implies rendering a `className` depending on the `float` property of any react-bootstrap component. As Bootstrap says:
>  Toggle floats on any element

This means that all component should be wrapped with an element that implements this feature.

Are you expecting to do this or do you have a differnet solution?

**Comment by bpas247** [comment]
> This means that all component should be wrapped with an element that implements this feature.

I'd imagine it would be appropriate to use a HOC here, although that might require re-writing most (if not all) of the components to accommodate this functionality, if we wanted to add a new HOC.

Maybe we can modify `createBootstrapComponent` to handle the `float` props?

**Comment by bpas247** [comment]
As per [the discussion](https://github.com/react-bootstrap/react-bootstrap/pull/4003#issuecomment-509384780) held in #4003 suggests, the cost of applying this API change seems to outweigh any improvements it would bring. The current workaround for this feature would be:
```jsx
<Col className="float-left">Float left on all viewport sizes</Col><br>
<Col className="float-right">Float right on all viewport sizes</Col><br>
<Col className="float-none">Don't float on all viewport sizes</Col>
```
This seems to be the case for most of the utility features of upstream, so aren't planning on supporting them as of right now, unless the utility feature seems significant enough and/or supporting the feature would bring significant API improvements.

I'll be closing this issue for now :) @ilanolkies feel free to re-open this issue if you feel like you have a strong argument for supporting this feature.
