### ISSUE TITLE
Spinner is not defined

### ISSUE THREAD

**Issue by ussefshahid** [react-bootstrap/react-bootstrap#3752]
`'Spinner' is not defined  react/jsx-no-undef`, 
why Spinner is in the documentation but not defined in the library?

**Comment by mxschmitt** [comment]
Which `react-boostrap` version are you using?

**Comment by ussefshahid** [comment]
> Which `react-bootstrap` version (package.json) are you using?

`1.0.0-beta.5` version

**Comment by mxschmitt** [comment]
`Spinner` was added in `1.0.0-beta.6`see here: https://github.com/react-bootstrap/react-bootstrap/blob/master/CHANGELOG.md#100-beta6-2019-03-21

**Comment by ussefshahid** [comment]
Thanks @mxschmitt
