### ISSUE TITLE
Maybe `react-bootstrap` causes vscode laggy?

### ISSUE THREAD

**Issue by liyuanqiu** [react-bootstrap/react-bootstrap#3766]
## Describe the bug

- If I install `react-bootstrap`, the `VS IntelliCode` will fall into a poor performance(wait a very long time to autocomplete code).
- If I remove `react-bootstrap`, the `VS IntelliCode` will be ok.

## To Reproduce
1. Create a project for testing
```bash
yarn create react-app test-project --typescript
cd test-project
```
2. Try `VS IntelliCode`
- Open this project in vscode
- In any `.ts` file, typing `inte`,  vscode will show code autocompletion very quickly.
3. Install `react-bootstrap`
```bash
yarn add react-bootstrap
```
4. Try `VS IntelliCode`
```typescript
import { Card } from 'react-bootstrap';
...
function MyComponent() {
  return (
    <Card.
  );
}
```
Typing `<Card.` here to wait for vscode's autocompletion, it will take a long time. All the autocompletions in this file will become very laggy.

## Reproducable Example

Minimal example by using [CodeSandbox](https://codesandbox.io).

## Environment (please complete the following information)

- Operating System: Both macOS Mojave and Windows 10
- Browser, Version Chrome 74
- React-Bootstrap Version 1.0.0-beta.8

**Comment by bpas247** [comment]
I'm not able to reproduce this `poor performance` with these steps on a local version of VS code or on the VS code integration on CodeSandbox.

Could you provide a more explicit example?

I'm also not sure if this is something we can necessarily control or fix, IMO.

**Comment by liyuanqiu** [comment]
> I'm not able to reproduce this `poor performance` with these steps on a local version of VS code or on the VS code integration on CodeSandbox.
> 
> Could you provide a more explicit example?
> 
> I'm also not sure if this is something we can necessarily control or fix, IMO.

It is ok on CodeSandbox, just happened in VS Code PC client.

When I found it is laggy, I did a lot of checks, and finally, I found that if I remove the line `import {...} from 'react-bootstrap';` from one source file, this file will not be laggy. I don't believe it is a problem of `react-bootstrap` at first, maybe my environment causes this problem, so I try it in a pure new Windows 10 system, with a newly installed VSCode, but the same problem occurred.

Let's see this example(based on pure CRA):
![image](https://user-images.githubusercontent.com/24999464/57665917-80079880-7630-11e9-9fe9-ded15eff9851.png)
I added three lines(line 2, 9, 10), then try to add an `interface` at line 5. Typing `inter` to wait for VSCode's code autocompletion, it needs about 3-10 seconds on my MacBook Pro 15(Core i7 gen4). But If I removed line 2 `import { Card, Spinner } from 'react-bootstrap';`, everything goes well.

**Comment by polishedwp** [comment]
Actually over the last month, there have been slow intelliscence issues related to typescript. 

[Read here]`https://github.com/Microsoft/vscode/issues/72616`

**Comment by liyuanqiu** [comment]
> Actually over the last month, there have been slow intelliscence issues related to typescript.
> 
> [Read here]`https://github.com/Microsoft/vscode/issues/72616`

From the issue page, I find this comment is helpful:

https://github.com/Microsoft/vscode/issues/72616#issuecomment-485291800

> Downgrading to 1.30.1 solved this for me fyi @keegandonley while this get's sorted out.

I give it a try, problem resolved. So it looks like is a problem of VSCode. Issue closed.
