### ISSUE TITLE
NavItem refs don’t work

### ISSUE THREAD

**Issue by flying-sheep** [react-bootstrap/react-bootstrap#378]
[test here](http://jsbin.com/gomusexihi/12/edit?js,console,output)

basically, this should log `['test0', 'test1', 'test2']` but the object’s `refs` is empty!

**Comment by MarkRunWu** [comment]
Since they`re in the other component, means it can be referenced through that component.

In your case:

``` html
<Nav ref="component_1">  //component 1
     <NavItem ref="test0">  //component 2 ... so on
     </NavItem>
     <NavItem ref="test1">
     </NavItem>
             ....
</Nav>
```
In order to access those refs you want do this:
``` js
  this.refs.component_1.refs
```

**Comment by flying-sheep** [comment]
thanks, didn’t realize that!
