### ISSUE TITLE
Is there a way to make the Modal.Title an `h1`

### ISSUE THREAD

**Issue by asaadmahmood** [react-bootstrap/react-bootstrap#3780]
I have the versions: 0.32.4.
I know in the latest version, we have an `as` property we can give the modal.title to do that, but is there any way I can achieve the same functionality in this older version?

**Comment by mxschmitt** [comment]
Simply use the `componentClass` on your ModalTitle. See here for reference: https://codesandbox.io/embed/o9vprxz556

**Comment by asaadmahmood** [comment]
@mxschmitt Thanks a ton! Also, are there any documents for the old version of React bootstrap preserved anywhere?

**Comment by mxschmitt** [comment]
https://5c507d49471426000887a6a7--react-bootstrap.netlify.com/components/modal/#modals-props-modal-title
