### ISSUE TITLE
Popover is gone when we go from button to popover

### ISSUE THREAD

**Issue by slgauravsharma** [react-bootstrap/react-bootstrap#3791]
Popover is gone when we go from (hover like button) to popover.

it should be visible till we on popover. just like  andt popover hover work
reference link it should work like: -`https://ant.design/components/popover/`
 react-bootstrap version :  "^1.0.0-beta.8"

#HELPPLEASE

![popoverissue](https://user-images.githubusercontent.com/25609444/57778517-d9abb800-7741-11e9-8b43-45602050a06d.png)

eg:-
```
<OverlayTrigger
  overlay={
    <Popover id="popover-contained">
      {likeEmoji.map((e, i) => (
        <span key={i}>{e}</span>
      ))}
    </Popover>
  }
>
  <span className="d-inline-block">
    <div className="ml-2 mr-2" style={{ cursor: "pointer" }}>
      Like
    </div>
  </span>
</OverlayTrigger>;
```

**Comment by taion** [comment]
I don't understand what you're asking for here. Can you clarify?

**Comment by slgauravsharma** [comment]
when i hover to like button, popover is populated it is fine but issue is when i am go to hovered button to tooltip , tooltip is gone (hide).
i want like this functionality check in below link @taion 
hover button example  `https://ant.design/components/popover/`

**Comment by taion** [comment]
You can customize the `trigger` prop on the `<OverlayTrigger>` as needed to control what toggles the overlay.

Otherwise, if the default behaviors are insufficient, use `<Overlay>` directly and control the `show` prop to configure when things show or hide.

**Comment by bdjnk** [comment]
@slgauravsharma Here is how you get the effect you asked for https://codesandbox.io/s/sleepy-goldberg-zthqh?file=/src/App.js

@taion To me maintaining the overlay while moving hover over it seems like the more expected behavior when the overlay content is a `Popover` (or a custom component).
