### ISSUE TITLE
How to set the width of Modal

### ISSUE THREAD

**Issue by mathiz11** [react-bootstrap/react-bootstrap#3794]
Hello,

I can't change the width of my Modal. 
I already read all the issues about this problem but nothing worked.
I followed this link : [React Bootstrap](https://react-bootstrap.github.io/components/modal/#modal-custom-sizing). 
I use **dialogClassName** in my react component :

` <Modal dialogClassName="custom-dialog">...</Modal>`

And in my css, i have this :

`.custom-dialog {
   width: 90%;
}`

Thank you

**Comment by taion** [comment]
Take a look at the actual class applied there: 
![image](https://user-images.githubusercontent.com/3112159/57790602-16a78880-7709-11e9-8bf8-610d37499d29.png)

i.e. you need to override `max-width` as well, if you're following standard TWBS styles.

**Comment by mathiz11** [comment]
Thank you @taion ! 👍 

With your solution, width is always at 100% even if i change it.

The best solution is `.modal-90w { max-width: 90% !important; }`

**Comment by darshana2797** [comment]
Using "react-bootstrap": "^1.0.0-beta.12",

```
.modal-dialog {
    max-width: none;
}
```
This worked for me.

**Comment by sameervk** [comment]
> Using "react-bootstrap": "^1.0.0-beta.12",
> 
> ```
> .modal-dialog {
>     max-width: none;
> }
> ```
> 
> This worked for me.

Thanks @darshana2797 , this worked for me too, and for some reason, not the earlier solutions. 

@taion spent a lot of time to just increase the width. The example on react-bootstrap webpage did not work

**Comment by andi-faizal94** [comment]
Helo, can you explain, how to fix, this?
Some time ,is solution is work, some time this is failed.

**Comment by omkarjninja** [comment]
> Helo, can you explain, how to fix, this? Some time ,is solution is work, some time this is failed.

https://mdbootstrap.com/docs/react/extended/modal-size/
check this link out , Inside <modal >tag write size and give it a attribute i.e 
sm=small md= medium  lg=large xl = extra large

example code - 
<Modal size='xl' show={showProject} onHide={handleClose}>
