### ISSUE TITLE
Cannot find module 'react-bootstrap/Container'

### ISSUE THREAD

**Issue by usmalik78** [react-bootstrap/react-bootstrap#3795]
I am using version 1.0.0-beta.8 of react-bootstrap to do some layout in my app. After installing react-bootstrap, I am trying to import the **Container**, **Row** and **Col** components into my custom component with the following import statements:

```react
import Container from 'react-bootstrap/lib/Container';
import Col from 'react-bootstrap/lib/Col';
import Row from 'react-bootstrap/lib/Row';
```

Only the Container import gives me an error: *Cannot find module ‘react-bootstrap/lib/Container’*

I have checked the *..\MyApp\node_modules\\@types\react-bootstrap\lib* directory and sure enough, there is no type definition file for Container whereas Col & Row have one.

As mentioned in [https://react-bootstrap.github.io/getting-started/introduction/], I would like to not import the entire react-bootstrap library when I just need a component or three. If I change my import statement to the following, it all works:

```react
import { Container, Col, Row } from 'react-bootstrap';
```

I am not sure if I missed something in my setup, although I have uninstalled and installed react-bootstrap couple of times and even blew away the entire npm_module directory once and re-installed everything. Can anyone help explain why I cannot import just the Container component by itself?

**Comment by taion** [comment]
It's `react-bootstrap/Container` now. We dropped the `lib/` in these paths to make things a bit less verbose.

**Comment by taion** [comment]
It's `react-bootstrap/Container` now. We dropped the `lib/` in these paths to make things a bit less verbose.
