### ISSUE TITLE
Event handler types seem to be missing in 1.0.0-beta.8

### ISSUE THREAD

**Issue by statico** [react-bootstrap/react-bootstrap#3797]
## Describe the bug

First, thank you for making this wonderful library.

It seems that event handlers don't have types in 1.0.0-beta.8. When I create a `<Button>` with an `onClick` handler like `event => ...`, and my TypeScript project has `strict` enabled, VS Code shows me an error, `Parameter 'event' implicitly has an 'any' type.ts(7006)`.

## To Reproduce

1. Create a file, `Test.tsx`, like this:

```typescript
import * as React from 'react'
import { Button } from 'react-bootstrap'

export default () => (
  <Button onClick={event => alert('hello, ' + String(event))} />
)
```

2. Run `tsc --jsx react --noEmit --strict components/Test.tsx`
3. See error

## Reproducable Example

https://codesandbox.io/s/condescending-curran-lz9k6

Notice the warning on line 8.

## Expected behavior

I would expect that `onClick` attributes be typed correctly, such as when using `<button onClick={...}>` (the native button component). These are provided via the `@types/react` package: https://www.npmjs.com/package/@types/react

## Screenshots

![image](https://user-images.githubusercontent.com/137158/57814999-7b270f80-772a-11e9-9579-b7a2197398ff.png)

## Environment (please complete the following information)

- Operating System: macOS 10.14.4
- React-Bootstrap Version 1.0.0-beta.8
- TypeScript version 3.4.5

**Comment by bpas247** [comment]
https://github.com/react-bootstrap/react-bootstrap/blob/7bd64defe2d0390397fab6938cc84f1191bc80ec/types/components/Button.d.ts#L32-L34
Hmm, I would think that the declaration here would inherit the type for `onClick`, but it doesn't seem like that's the case. 

Maybe we just need to add an explicit type for `onClick` to `ButtonProps`? Would be happy to take a PR for this.

**Comment by 0xc0d3r** [comment]
@bpas247 I think, adding this `onClick: (event: React.MouseEvent) => void` to `ButtonProps` will resolve the typescript error.

Shall I create a PR?

**Comment by bpas247** [comment]
> @bpas247 I think, adding this `onClick: (event: React.MouseEvent) => void` to `ButtonProps` will resolve the typescript error.
> 
> Shall I create a PR?

That was my initial thought for a possible solution, yeah. I'd say go for it 😃

**Comment by 0xc0d3r** [comment]
@bpas247 I'm unable to push the code. Please add me as a contributor.

**Comment by taion** [comment]
Please fork the repo and submit a PR from your fork. That's the typical contributor flow for most OSS projects on GitHub.

**Comment by taion** [comment]
Is this a limitation to our type inference then? It works if you do `<Button<'button'> onClick={...}>`

**Comment by garyking** [comment]
> Is this a limitation to our type inference then? It works if you do `<Button<'button'> onClick={...}>`

If we are using `onChange` on `Form.Control`, then how do we fix this error?

I tried `<Form.Control<'input'>` but then, for `onChange={(event): void => event.target.value}` I get `Property 'value' does not exist on type 'EventTarget'.`.

**Comment by kyletsang** [comment]
Tested this with TS 3.9.6 using react-bootstrap 1.1.1 and types are resolving properly now.
