### ISSUE TITLE
Navbar Brand isn't clickable

### ISSUE THREAD

**Issue by dioxmio** [react-bootstrap/react-bootstrap#380]
Hi, there's no option to add a click event to the Navbar Brand. I can create a PR and develop the feature if it's not in progress already. Let me know so I can build it :)

**Comment by mathieumg** [comment]
You can pass a React node (formerly renderable) to the brand property, there's an example: https://github.com/my-koop/module.core/blob/master/components/layout/NavBar.jsx#L314

**Comment by mtscout6** [comment]
@dioxmio Did @mathieumg's solution work for you, and would you be ok with closing this issue?

**Comment by josegranja** [comment]
@mtscout6 @mathieumg yes, great solutions :) let me know if you want me to help out sorting any new issues though. Would be glad to contribute and help

**Comment by mtscout6** [comment]
@josegranja We love contributors, feel free to comb issues and provide suggestions. If you see legit bugs don't hesitate to submit pull requests.
