### ISSUE TITLE
Can i import third party components in www/src/examples files?

### ISSUE THREAD

**Issue by xwillmadeit** [react-bootstrap/react-bootstrap#3800]
Sorry to post this question here cause this is not an issue of this library. This repo's www folder is really a great project for writing component doc.  I want to use your super cool gatsby/react-live based website project as an example for writing my own component doc website. Here is the question, can i import a third party component in example folder？I don't know how you import react-bootstrap component in example folder... 

![image](https://user-images.githubusercontent.com/8340253/57844095-f4456600-7801-11e9-8c43-b6b160d91b66.png)

then i can use it like this

![image](https://user-images.githubusercontent.com/8340253/57844125-032c1880-7802-11e9-83eb-e7920c7ed8c6.png)

**Comment by taion** [comment]
Install it as an npm dependency in `www/`.

**Comment by xwillmadeit** [comment]
> Install it as an npm dependency in `www/`.

I can't write any example for it then pass it as the codeText prop to your ReactPlayGround component  for live editting  right?
