### ISSUE TITLE
 Uncaught ReferenceError: ProgressBar is not defined

### ISSUE THREAD

**Issue by nitrox62** [react-bootstrap/react-bootstrap#381]
Hi, everybody
I got this problem when I try to use React-Bootstrap  : Uncaught ReferenceError: ProgressBar is not defined

Here is my source-code http://jsfiddle.net/thomasM62141/7h498t0b/

I have the same issue when I try with require. Anyone should help me to solve the problem ? 

Thanks

**Comment by mathieumg** [comment]
You should leverage the script box in your fiddle. ;) That being said, you try to require react-bootstrap with a relative URL, it won't work on JSFiddle.

**Comment by nitrox62** [comment]
Yes I know that . http://image.noelshack.com/fichiers/2015/07/1424020496-capture-d-ecran-2015-02-15-a-18-13-34.png Here is a screean of what I do . I just follow the "getting started" steps and everything goes wrong.

**Comment by mathieumg** [comment]
Do you have react-boostrap hosted locally under `/react-boostrap/react-boostrap.js`? If you don't, you need to, or you could change the URL to load react-bootstrap off a CDN like you do for the other libraries in that page.

**Comment by nitrox62** [comment]
Yes I have I will try with a CDN .

**Comment by mathieumg** [comment]
Also I'm not sure what the browser version exposes, you might have to do `ReactBootstrap.ProgressBar` to access the component.

**Comment by nitrox62** [comment]
Yes I have found the solution on a antother topic and one friend has made a hack  . 

<script>
        Object.keys(ReactBootstrap).forEach(function (name) {
            window[name] = ReactBootstrap[name];
        });
</script>

I think it could be useful for everyone

**Comment by mtscout6** [comment]
Pushing everything onto the global is a less than ideal solution, one that I would not recommend to everyone. In your particular example you can do:

```
var progressInstance = (
  <ReactBootstrap.ProgressBar now={60} />
);
```

Although the approach I have taken is using CommonJS and ES6 destructuring.

```
var { ProgressBar } = require('react-bootstrap');

var progressInstance = (
  <ProgressBar now={60} />
);
```

In your case since you are just loading the script onto the page you could:

```
var ProgressBar = ReactBootstrap.ProgressBar;

var progressInstance = (
  <ProgressBar now={60} />
);
```
