### ISSUE TITLE
how to disable OverlayTrigger onclick not to show?

### ISSUE THREAD

**Issue by skirankumar7** [react-bootstrap/react-bootstrap#3823]
**How to disable OverlayTrigger onclick not to show ?**

I have a material UI Switch and I have OverlayTrigger which comes onchange of this Switch but when Switch is disabled I want to stop onclick on this switch not show OverlayTrigger.

I can say like how to manually control the show or hide the state of OverlayTrigger even onclick not to show

- Operating System -- windows
- Browser  -- Chrome
- React-Bootstrap Version -- 0.32.4

**Advanced thanks for replies.**

**Comment by taion** [comment]
If you need advanced control of trigger conditions, use `<Overlay>`. Otherwise you can pass in the desired trigger conditions for the `<OverlayTrigger>` as the appropriate prop.
