### ISSUE TITLE
How can I disable pointer effect on button or dropdown?

### ISSUE THREAD

**Issue by jindrichkuba** [react-bootstrap/react-bootstrap#3829]
When I click on button or dropdown, there is pointer effect animation. I would like to have an option to remove this animation.

**Comment by jquense** [comment]
Styles are all from the vanilla bootstrap styles so the same guidance for customizing them works for RB https://getbootstrap.com/docs/4.3/getting-started/theming/

**Comment by jindrichkuba** [comment]
.Ripple {
        display: none;
      }

**Comment by jquense** [comment]
that looks like a material-ui thing
