### ISSUE TITLE
Build issue in netlify, missing bootstrap

### ISSUE THREAD

**Issue by timothydowd** [react-bootstrap/react-bootstrap#3831]
## Describe the bug

When running npm run build and deploying my react project to netlify, the netlify version of my website loses styling...  here is an image of my localhosted version:
http://i.imgur.com/gZoqkY1.png

and here is the link for the netlify version:
https://ncnews-timdowd.netlify.com/

I have ensured to add the relevant stylesheet link in the index.html and added the relevant import into index.js as instructed in the react-bootstrap and bootstrap documentation, not really sure what is going wrong.  I have found that if I remove the line:

import 'bootstrap/dist/css/bootstrap.css'

from my index.js and run locally I get the exact same problem in my local version as I have in my netlify version...

## To Reproduce

1. Go to https://github.com/timothydowd/FE-NC-News
2. Click on 'clone repo'
3. In bash run: 
     git clone https://github.com/timothydowd/FE-NC-News.git
4. Then cd into the repo:
     cd FE2-NC-News/front-end-nc-news/
5. Install dependencies
    npm install
6. Run the "start" script to start the application running locally
    npm start

    Your browser should now be running the front end on a localhost
    To stop running the server use ctrl + c

To make your own build..

1.  Npm run build
2.  Log into netlify and drag and drop build folder into netlify's 'sites' tab, this will deploy the site for you.

## Environment 

- Operating System: ubuntu
- Browser, Version:  Chrome 74.0.3729.131
- React-Bootstrap Version: 1.0.0-beta.8

**Comment by taion** [comment]
Why do you believe this to be an issue with React-Bootstrap?

**Comment by timothydowd** [comment]
Its either an issue with react-bootstrap or an issue with what I'm doing...  Probably the latter, but been trying to fix this for 2 weeks and this is my last port of call

**Comment by timothydowd** [comment]
@taion 

I've fixed the issue and you are right, it wasn't the react-bootstrap that was the issue it was the order create-react-app builds the css in comparison to how it handles css in the dev environment.  And the fact that my css skills are not very good (lol).

**Comment by stephanieraymos** [comment]
How did you solve this? I'm using bootstrap but not with react. Same issue with bootstrap styles not showing on netlify

**Comment by timothydowd** [comment]
> How did you solve this? I'm using bootstrap but not with react. Same issue with bootstrap styles not showing on netlify

Go through your css very carefully and check the css is correct and following best practices.  Try reordering your css also.  It’s a bit of a trial and error thing unfortunately.
