### ISSUE TITLE
Can't type spaces in input or textarea form fields nested inside the Modal element

### ISSUE THREAD

**Issue by colleenpurcell** [react-bootstrap/react-bootstrap#3832]
## Describe the bug

When I nest a form inside the Modal element from the react-modal library, the user input into the input (or text area) field do not allow spaces to be typed. So you can only enter a single word. When you type spaces, they don't register. It's like whitespace is automatically trimmed.

## To Reproduce

1. Go to the form
2. Type "test this" and it will show up as "typethis"

## Reproducable Example

```
import Modal from "react-modal";

<Modal
  isOpen={this.state.modalIsOpen}
  onRequestClose={this.closeModal}
  contentLabel="Example Modal"
  >
  <form
    action="/submit"
    method="POST"
    >
    <textarea
      name="Description"
      id="styled"
      required
      />
   </form>
</Modal>
```

**Comment by taion** [comment]
see https://github.com/react-bootstrap/react-bootstrap/issues/3105

**Comment by Marcellia** [comment]
Thank you! This works like a charm.
