### ISSUE TITLE
Toast not found version  1.0.0-beta.8

### ISSUE THREAD

**Issue by hp8wvvvgnj6asjm7** [react-bootstrap/react-bootstrap#3848]
- 1 import Toast from 'react-bootstrap/Toast'

 - 2 Module not found: Error: Can't resolve 'react-bootstrap/Toast' in 'C:\Users\...

Where is my toast?

**Comment by taion** [comment]
Which version do you have installed?

**Comment by hp8wvvvgnj6asjm7** [comment]
latest...

**Comment by bpas247** [comment]
Okay, but could you post the specific version you are using?

**Comment by hp8wvvvgnj6asjm7** [comment]
**version

1.0.0-beta.8**

**Comment by mxschmitt** [comment]
@bpas247 @taion @hp8wvvvgnj6asjm7 we do not yet have the Toasts component in any release. Added in PR #3685. Let's maybe release a new version?

**Comment by BrianMLi** [comment]
It is out in 1.0.0-beta.9

**Comment by mxschmitt** [comment]
@jquense you forgot to mention the new Toast component in the changelog :/

**Comment by AbednegoTM** [comment]
Am using `"react-bootstrap": "^1.0.0-beta.9"`  still getting : `TypeError: Toast is undefined` is the Toast still unavailable or this a bug.

**Comment by bpas247** [comment]
@AbednegoTM 
>  is the Toast still unavailable or this a bug.

It's probably an issue on your end, since importing `Toast` works just fine in the [CodeSandbox basic example](https://codesandbox.io/s/github/react-bootstrap/code-sandbox-examples/tree/master/basic) (which uses `1.0.0-beta.9` as of this posting).
