### ISSUE TITLE
v0.15.0 no longer have a main.js in the root dir cannot do require("react-bootstrap")

### ISSUE THREAD

**Issue by hokkos** [react-bootstrap/react-bootstrap#385]
Hi,
the v.0.15.0 seem to have totally changed the structure of the code committed on npm, it use to have a main.js that exported all the components; but with v0.15.0 it is a all source release (nothing wrong with that) but the main.js is gone inside tool/cjs/ so I can no longer do require("react-bootstrap")
Is there any way to correct that ?
Thanks.

**Comment by mtscout6** [comment]
v0.15.0 was broken because I needed to add an `.npmignore` file, which I have now fixed in #388. The structure has change, so checkout the new [CHANGELOG.md](https://github.com/react-bootstrap/react-bootstrap/blob/master/CHANGELOG.md) which highlights the changes.
