### ISSUE TITLE
Add documentation for  <Grid fluid />

### ISSUE THREAD

**Issue by ronnross** [react-bootstrap/react-bootstrap#387]
Looking at the Grid component it feels that an unlikely use case is being forced upon someone implementing the grid. When one implements the grid a div is created with either a container or container-fluid class. Maybe I am missing something, but it seems like this would take away the option of someone wanting to put a columns inside of a '.row'. For example, when one needs to role their own nav bar. It seems like the option should be given to the one implementing where the grid should be wrapped in a '.container', '.row', or neither. Maybe a compromise might be to add a prop on grid to allow for row. I know you can wrap columns directly within a <Row>, but I feel you looks some semantic meaning this way. Your thoughts?

**Comment by mtscout6** [comment]
Can you provide some ideal code with expected output to highlight what you are wanting to accomplish? You don't have to use `Grid` to use `Row` or `Column`, though I may not be understanding exactly what it is you're after. At the least if you can provide some expected html output, then we can see what we can do.

**Comment by gustavoschmidt** [comment]
I'm trying to use Grid with 'container-fluid':
<Grid className='container-fluid' />
But Grid automatically adds a 'container' class, overriding the 'container-fluid' behavior.
Did I get something wrong?

**Comment by mathieumg** [comment]
`<Grid fluid />` should do it technically.

**Comment by gustavoschmidt** [comment]
Thanks @mathieumg!
Didn't find this in the documentation.
Should take a better look at the code.

**Comment by mtscout6** [comment]
We should add some documentation on that fluid prop.

**Comment by mathieumg** [comment]
@gustavoschmidt Yeah, sorry for that. Improving documentation regarding properties components accept/expect is something we are working on. For the time being, the only way to know is to look at the code itself.

**Comment by gustavoschmidt** [comment]
@mathieumg Thank you for letting me know!
