### ISSUE TITLE
Cannot find module 'react-bootstrap' since 0.15.0

### ISSUE THREAD

**Issue by davidnorth** [react-bootstrap/react-bootstrap#388]
I downgraded to 0.14.1 and it worked again.

**Comment by lukemcgregor** [comment]
+1

**Comment by pr0digy** [comment]
Looks like you forgot to add a directory... _"main": "lib/main.js"_ doesn't exist.

**Comment by lo1tuma** [comment]
Same here.

**Comment by mtscout6** [comment]
Looks like a kink in our new release process. Looks like I need to add an `.npmignore` file instead of letting npm use the gitignore file. Sorry about this; I'll get a patch out this morning. The good news is this is the beginning of a new release process that should keep this from happening again. See PR #326.

**Comment by mtetlow** [comment]
I am a little confused how this is supposed to work with private forks which are pulled down via npm/package.json. When I am pulling mine down, lots of stuff needed to build the /lib dir is ignored and not pulled down, preventing me from using grunt to build. What do you think the best practice for building using a fork in another project would be? 

Currently the only way I see to build is to strip out Gruntfile.js, /tools, etc from the npmignore. Then I can npm install from another project, and build via grunt after I have pulled the fork down.

**Comment by mtscout6** [comment]
If you are hacking on something to see if it works in your application you can try using [`npm link`](https://docs.npmjs.com/cli/link). If you are needing to have a fork to deploy your application, then force commit the lib folder on your branch. I'd recommend you then tag it and bump the version as opposed to pointing at a branch tar download. For example in your package.json:

```
{
  ...
  dependencies: {
    ...
    react-bootstrap: "https://github.com/mtetlow/react-bootstrap/archive/v0.15.2-alpha.tar.gz"
  }
}
```

**Comment by mtetlow** [comment]
Thanks for taking the time to reply @mtscout6 . I appreciate it.
