### ISSUE TITLE
Increase Test Coverage

### ISSUE THREAD

**Issue by mxschmitt** [react-bootstrap/react-bootstrap#3889]
Current State:
https://codecov.io/gh/react-bootstrap/react-bootstrap/tree/master/src

- [x] https://codecov.io/gh/react-bootstrap/react-bootstrap/src/master/src/BootstrapModalManager.js (checkout: #4206)
- [ ] https://codecov.io/gh/react-bootstrap/react-bootstrap/src/master/src/OverlayTrigger.js (see #4573 for help)
- [ ] https://codecov.io/gh/react-bootstrap/react-bootstrap/src/master/src/Carousel.js
- [ ] https://codecov.io/gh/react-bootstrap/react-bootstrap/src/master/src/Row.js
- [ ] https://codecov.io/gh/react-bootstrap/react-bootstrap/src/master/src/Modal.js
- [x] https://codecov.io/gh/react-bootstrap/react-bootstrap/src/master/src/Toast.js
- [x] https://codecov.io/gh/react-bootstrap/react-bootstrap/src/master/src/Overlay.js
- [x] https://codecov.io/gh/react-bootstrap/react-bootstrap/src/master/src/TabContainer.js
- [x] https://codecov.io/gh/react-bootstrap/react-bootstrap/src/master/src/AbstractNav.js
- [x] https://codecov.io/gh/react-bootstrap/react-bootstrap/src/master/src/Nav.js
- [x] https://codecov.io/gh/react-bootstrap/react-bootstrap/src/master/src/DropdownMenu.js
- [x] https://codecov.io/gh/react-bootstrap/react-bootstrap/src/master/src/InputGroup.js
- [x] https://codecov.io/gh/react-bootstrap/react-bootstrap/src/master/src/PageItem.js
- [x] https://codecov.io/gh/react-bootstrap/react-bootstrap/src/master/src/Tab.js
- [x] https://codecov.io/gh/react-bootstrap/react-bootstrap/src/master/src/Tabs.js
- [x] https://codecov.io/gh/react-bootstrap/react-bootstrap/src/master/src/ToggleButton.js
- [x] https://codecov.io/gh/react-bootstrap/react-bootstrap/src/master/src/ToggleButtonGroup.js
- [x] https://codecov.io/gh/react-bootstrap/react-bootstrap/src/master/src/ListGroupItem.js

**Comment by zdivozzo** [comment]
Hey @mxschmitt ! Hoping to help out with writing some of these tests. Excuse my ignorance, but is there a way to diff my changes with what's currently there in codecov before submitting a PR?
Thanks!
Zack

**Comment by mxschmitt** [comment]
Hey @zdivozzo,

you can simply open `coverage/Chrome 75.0.3770 (Mac OS X 10.14.5)/lcov-report/index.html`. The compare it with the codecov.io version. That's then the graphical version of Istanbul. 👍

**Comment by zdivozzo** [comment]
Submitted a PR with some of the tests, I should have time to do more soon. This is my first PR to an open source project, so let me know anything I can improve on!

**Comment by mxschmitt** [comment]
> Submitted a PR with some of the tests, I should have time to do more soon. This is my first PR to an open source project, so let me know anything I can improve on!

Looks super, you used a good branch name for it. Maybe in the future adjust your commit messages. We use the Style Guideline from Angular in our Organization: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-guidelines

**Comment by zdivozzo** [comment]
Will do, thanks!

**Comment by ShunyaWatanabe** [comment]
Hello. I would love to work on the rest of the test cases. Please let me know if someone else is already working on them!

**Comment by farhang** [comment]
Hi @mxschmitt,  are there any more test cases needed? I guess the state of this issue is not updated at the moment, for example, we have many test cases for the carousel but its checkbox is not checked in this issue.
