### ISSUE TITLE
Add a section in the README for our CodeSandbox examples

### ISSUE THREAD

**Issue by bpas247** [react-bootstrap/react-bootstrap#3890]
## Describe the solution you'd like

There should be a new section to cover our CodeSandbox examples, as it will improve visibility of them. Currently, there is only one CodeSandbox example deployed [here](https://codesandbox.io/s/github/react-bootstrap/code-sandbox-examples/tree/master/basic).

We don't need to explicitly list each example on our README, as that would be redundant, so just a link to the `code-sandbox-examples` [repo](https://github.com/react-bootstrap/code-sandbox-examples) (or a direct link to the README on that repo) should suffice.

We could also consider adding a link on our main website, although I'm not sure how relevant that would be.

**Comment by sarngru** [comment]
@bpas247 There is already `CodeSandbox Examples` section in https://github.com/react-bootstrap/react-bootstrap

![image](https://user-images.githubusercontent.com/9040052/59875241-42ec9f80-936e-11e9-8653-a95188c09c48.png)

**Comment by bpas247** [comment]
@sarngru 
> There is already CodeSandbox Examples section

This issue was opened up before #3914, and it just recently got merged.

Closing this now, special thanks to @bhekanik for getting this done 😃
