### ISSUE TITLE
<Dropdown.Item> Undefined

### ISSUE THREAD

**Issue by Amritpd** [react-bootstrap/react-bootstrap#3894]
## Describe the bug

The issue is simple. The Dropdown.Item component is not defined in the latest version of the npm package it seems... Using <MenuItem> instead resolve the issue. 

## To Reproduce

NA

## Reproducable Example
`import { Dropdown, MenuItem, DropdownButton } from "react-bootstrap";
... // define rest of react component like usual 
<Dropdown>
  <Dropdown.Toggle variant="success" id="dropdown-basic">
    Dropdown Button
  </Dropdown.Toggle>

  <Dropdown.Menu>
    <Dropdown.Item href="#/action-1">Action</Dropdown.Item> // doesn't work 
    <Dropdown.Item href="#/action-2">Another action</Dropdown.Item> // doesnt work
    <Dropdown.Item href="#/action-3">Something else</Dropdown.Item> // doesn't work 
  </Dropdown.Menu>
</Dropdown`

## Expected behavior

Dropdown.Item should have worked right out of the box. 

## Screenshots

Error message that showed up. 
![image](https://user-images.githubusercontent.com/9814488/59325491-41a5dd80-8cb1-11e9-9725-43db6dbf41c5.png)

## Environment (please complete the following information)

NA

**Comment by taion** [comment]
Which version of R-B are you using?

**Comment by Amritpd** [comment]
react-bootstrap@0.32.4 i.e. the version needed for Bootstrap 3. Perhaps I am better off upgrading everything in my app to Bootstrap 4, then I can use R-B v1.0.0.

**Comment by taion** [comment]
It's `<MenuItem>` on the TWBSv3 release line. See the docs there.
