### ISSUE TITLE
Alert Fade is not Configurable

### ISSUE THREAD

**Issue by drewcovi** [react-bootstrap/react-bootstrap#3897]
## Describe the bug
If there is a way to override the Fade setting for Alerts, it doesn't appear to be documented...
Currently no alerts fade in using examples provided.

**Comment by taion** [comment]
see the documentation on the `transition` prop in https://react-bootstrap.github.io/components/alerts/#alert-props

if you need other behavior, you can use your own custom transition around the `<Alert>`

**Comment by drewcovi** [comment]
@taion how would you modify an attribute whose type is an element? Currently the alert doesn’t fade in. Should it?

**Comment by taion** [comment]
That's correct that it doesn't fade in. If you want that, manage the transition yourself. Otherwise, if you just want to customize how it transitions out, do like `<Alert transition={Collapse}>`.

**Comment by drewcovi** [comment]
@taion Appreciate the guidance... I was confused since in React Inspector, there's a Fade element created but it doesn't seem to actually do anything (despite having a `300ms` timeout defined). When defining the transition property as you recommend, I was unable to sort out where to import `Collapse` or `Fade` from. I've installed the react-transition-group dependency, but nothing seems to work.

It does seem like I'm missing something since those elements would need a CSS animation property (not a transition property) when the elements are destroyed and recreated.

**Comment by drewcovi** [comment]
@taion disregard.... I think i sorted out my issue. Thanks for your help.

**Comment by fungjj92** [comment]
@drewcovi Can you talk about your solution? I'm having a similar issue with `Tabs` whereby the `Fade` transition, or a custom one, doesn't seem to do anything.
