### ISSUE TITLE
muted prop does not add text-muted className

### ISSUE THREAD

**Issue by rockchalkwushock** [react-bootstrap/react-bootstrap#3900]
## Describe the bug

It seems that when providing the `muted` prop to `<Form.Text />` the flag does not add the `text-muted` className as intended.

## To Reproduce

Add `<Form.Text muted />`.

## Reproducable Example

https://codesandbox.io/s/crazy-mcnulty-ixpp9

## Expected behavior

When passing the `muted` flag the `text-muted` class should be added to the element.

## Environment (please complete the following information)

- Operating System: `macOS 10.13.6`
- Browser, Version `Chrome 74`
- React-Bootstrap `1.0.0-beta.8`

## Additional context

Problem is present in `beta.8` and looks to be present in `beta.9` as that's what's being used in the codesandbox.

**Comment by taion** [comment]
Seems like a pretty simple bug. Care to make a quick PR?

**Comment by rockchalkwushock** [comment]
@taion I could take a look at it later this evening and submit a PR.

**Comment by taion** [comment]
Thanks!
