### ISSUE TITLE
Focus does not move to the dialog once it is activated.

### ISSUE THREAD

**Issue by mvita11y** [react-bootstrap/react-bootstrap#3922]
## Issue

When a modal dialog is activated, focus is not placed in the dialog. 

## To Reproduce

1. Go to 'https://getbootstrap.com/docs/4.0/components/modal/'
2. Tab to Launch Demo Modal button
3. Press spacebar to activate
4. Focus does not move into dialog

## Reproducable Example

The component live demo. https://getbootstrap.com/docs/4.0/components/modal/

## Expected behavior

When a modal dialog is activated, focus must be moved to the dialog. Where focus is initially placed may vary depending on the dialog’s content, but focusing the dialog itself can provide a consistently predictable user experience.

## Environment (please complete the following information)

Bootstrap 4
macOS
all browsers

**Comment by jquense** [comment]
did you mean to post this on **react** bootstrap? In either case tho both bootstrap and react-bootstrap move the focus to the dialog when opening, you can check the activeElement

![image](https://user-images.githubusercontent.com/339286/59795642-af519b00-92a9-11e9-85b2-60b78b9cda57.png)
