### ISSUE TITLE
Review and update Contribution guidelines

### ISSUE THREAD

**Issue by sarngru** [react-bootstrap/react-bootstrap#3929]
## Describe the bug
Contribution guidelines are very important for new contributors to get familiar with project and get started with helping the project in different ways. Clear and concise guidelines are welcoming and leave a good impression on new contributors. Issues with current guidelines:
* There are two guidelines: [V4-Contributing.md](https://github.com/react-bootstrap/react-bootstrap/blob/master/V4-Contributing.md) and [CONTRIBUTING.md](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md). It would be helpful to combine them into one.
* Update content in the guide so that it provides accurate details. 
* Include section on `Branching` providing details on purpose of various branches and which one should be used as base for PR.  

## To Reproduce
N/A

N/A

## Reproducable Example
N/A

## Expected behavior
Clear and concise contribution guidelines.

**Comment by bpas247** [comment]
I'm thinking 8ea40cfbd06571c8f20c4e87d8d70d451eb0c8aa closes this issue? @sarngru what do you think?
