### ISSUE TITLE
Cannot remove style property from DropdownMenu

### ISSUE THREAD

**Issue by darkalghul** [react-bootstrap/react-bootstrap#3941]
When I render the Dropdown.Menu component it adds some style properties to it, here is the codes that generate

```
<div aria-labelledby="noti" class="dropdown-list right-align dropdown-menu show" x-placement="bottom-start" style="position: absolute; will-change: transform; top: 0px; left: 0px; transform: translate3d(-31px, 70px, 0px);">
   <div class="dropdown-header" role="heading">Centro de Alertas</div>
   <a href="#" class="d-flex align-items-center dropdown-item" role="button">
      <div class="mr-3">
         <div class="icon-circle"><i class="fas fa-envelope-open-text"></i></div>
      </div>
      <div>
         <span>May 18th 2019</span>
         <p>You forgot to pay your medical bill</p>
      </div>
   </a>
</div>
```

I will like to remove the x-placement and style properties but I don't see how can I do that with the props settings.

**Comment by taion** [comment]
Those are more or less necessary to get the dropdown menu to position correctly in many edge cases. They're there for use with Popper. I'm not sure what you're asking for here – we can't just get rid of them without causing at least degraded functionality.

**Comment by jquense** [comment]
I think you can pass usePopper=false and it will degrade to just absolutely positioned drop-down with no logic for placement, but stuff like flip or screen edge detection won't work

**Comment by taion** [comment]
We don't accept that prop here: https://github.com/react-bootstrap/react-bootstrap/blob/f78a53978f81940accb1b04bf36be63cc914def1/src/DropdownMenu.js#L88

**Comment by darkalghul** [comment]
But what if I do not want to use popper, what if I wanted to give it my own style to the dropdown, my own position, how do I change it to be in the position I want?

**Comment by jquense** [comment]
happy to take a PR that passes the option to disable popper through
