### ISSUE TITLE
pluse minus in accordion header

### ISSUE THREAD

**Issue by mockey-jockey** [react-bootstrap/react-bootstrap#3942]
## Is your feature request related to a problem?  NO, It's not my problem it's a common thing.

![image](https://user-images.githubusercontent.com/36475730/59967325-fbb90700-9545-11e9-8396-7fb8647cc459.png)

## Describe the solution you'd like
![image](https://user-images.githubusercontent.com/36475730/59967331-096e8c80-9546-11e9-93d0-67fdbdc48e95.png)

## Describe alternatives you've considered

add the class header too

## Additional context
I don't find any class in header once its collapsed.it only added the class in body.

**Comment by taion** [comment]
This isn't part of the TWBS Accordion, so it's not really fitting here.

If you want this functionality, you can either read the `eventKey` yourself from our `AccordionContext` and use that to drive styling, or else implement things from scratch with the lower-level `Card` API.

**Comment by mockey-jockey** [comment]
import _extends from "@babel/runtime/helpers/esm/extends";
import _objectWithoutPropertiesLoose from "@babel/runtime/helpers/esm/objectWithoutPropertiesLoose";
import React, { useContext } from 'react';
import SelectableContext from './SelectableContext';
import AccordionContext from './AccordionContext';
var AccordionToggle = React.forwardRef(function (_ref, ref) {
  var _ref$as = _ref.as,
      Component = _ref$as === void 0 ? 'button' : _ref$as,
      children = _ref.children,
      eventKey = _ref.eventKey,
      _onClick = _ref.onClick,
      `className = "",`
      props = _objectWithoutPropertiesLoose(_ref, ["as", "children", "eventKey", "onClick",`"className"`]);

  var contextEventKey = useContext(AccordionContext);
  var onSelect = useContext(SelectableContext);
  return React.createElement(Component, _extends({
    ref: ref,
    onClick: function onClick(e) {
      /* 
        Compare the event key in context with the given event key.
        If they are the same, then collapse the component.
      */
      var eventKeyPassed = eventKey === contextEventKey ? null : eventKey;
      onSelect(eventKeyPassed, e);
      if (_onClick) _onClick(e);
    }
  }, props, `{
    className: eventKey === contextEventKey ? 'show' : 'close'
  }`), children);
});
export default AccordionToggle;


above highlighted place only added in accordionToggle.js. can you pls update this way in the component level itself.

Once we did this we can achieve `plus` and `minus` logic. It would help most of the developers.
