### ISSUE TITLE
Nav.Link refreshing page when not supposed to

### ISSUE THREAD

**Issue by vealjoshua** [react-bootstrap/react-bootstrap#3944]
<>
			<Navbar bg='primary' variant='dark'>
				<Navbar.Brand href='/'>Bench Overflow</Navbar.Brand>
				<Nav className='mr-auto'>
					<Nav.Link href='/'>Home</Nav.Link>
					<Nav.Link href='/profile'>Profile</Nav.Link>
				</Nav>
				<Form inline>
					<FormControl type='text' placeholder='Search' className='mr-sm-2' />
					<Button variant='outline-light'>Search</Button>
				</Form>
			</Navbar>
		</>

**Comment by taion** [comment]
By default, links refresh the page when clicked. If you're looking for an SPA, use an appropriate integration, such as react-router-bootstrap.

**Comment by praxiz** [comment]
Old post but for the search engine visitors: 
`import { Link } from 'react-router-dom'`
Then change 
`<Nav.Link href="/"> `
to 
`<Nav.Link as={Link} to="/">`

**Comment by dali0023** [comment]
@praxiz  Thanks! You are correct

**Comment by Xeoncross** [comment]
Thanks @praxiz, I'll try this `Link.tsx` Component:

```
import React from "react";
import { Link } from "react-router-dom";
import { Nav } from "react-bootstrap";

interface linkprops {
  to: string;
  children: React.Component;
}

export default (props: linkprops): React.FC => {
  return (
    <Nav.Link as={Link} to={props.to}>
      {props.children}
    </Nav.Link>
  );
};

```

**Comment by HemantSharmaKsolves** [comment]
Use this method to not to reload page

import { Link } from "react-router-dom";

<Nav.Link as={Link} to="/about">About</Nav.Link>
