### ISSUE TITLE
404 https://unpkg.com/react-dom/umd/react-dom.production.js

### ISSUE THREAD

**Issue by rommik** [react-bootstrap/react-bootstrap#3946]
While doing the tutorial (https://react-bootstrap.github.io/getting-started/introduction), I noticed that 
`https://unpkg.com/react-dom/umd/react-dom.production.js`
and 
`https://unpkg.com/react/umd/react.production.js` redirect to  404 `Cannot find "/umd/react-dom.production.js" in react-dom@16.8.6` and `Cannot find "/umd/react.production.js" in react@16.8.6`

The third link in the tutorial `https://unpkg.com/react-bootstrap@next/dist/react-bootstrap.min.js` works as expected.

**Comment by taion** [comment]
Looks like it should be `react-dom.production.min.js`. Care to send a quick PR to fix?

**Comment by rommik** [comment]
Sure, i’ll do it tomorrow.

**Comment by mxschmitt** [comment]
Integrated in #3956
