### ISSUE TITLE
Center items in a navbar 

### ISSUE THREAD

**Issue by nitrox62** [react-bootstrap/react-bootstrap#395]
Hi everyone , 

Is it possible and how I could do ? 

The items always go on the left . 

Thanks

**Comment by taion** [comment]
Bootstrap only exposes aligning navbar content to left or to right: http://getbootstrap.com/components/#navbar-component-alignment

**Comment by Radivarig** [comment]
Can this be worked around with css?

**Comment by jquense** [comment]
not with classes provided by bootstrap. but I'm sure you can hack something together custom
