### ISSUE TITLE
React-Bootstrap crashing on basic usage “Invalid hook call”

### ISSUE THREAD

**Issue by timgerhard** [react-bootstrap/react-bootstrap#3965]
## Describe the bug

I am unable to use react-bootstrap in my application. Every time I try to import and render a component (from react bootstrap) this exception occurs:

> Uncaught Invariant Violation: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons...

I do not use hooks in my react application. **The web app works fine without react bootstrap!**

## To Reproduce

1. Installed react-bootstrap and bootstrap into an **existing** project with npm install react-bootstrap bootstrap
2. Added Import-Statement in react component import Button from 'react-bootstrap/Button';
3. Added button inside return() of render() function: 
`<Button variant="primary">Primary</Button>`

## Environment (please complete the following information)

- Operating System: Windows
- Browser, Version Chrome 74
- React-Bootstrap Version 1.0.0-beta.8

## Additional context

Package.json file:
```
{
  "name": "sautercopyplanraum",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "wbp": "webpack"
  },
  "keywords": [],
  "author": "Tim Gerhard",
  "license": "ISC",
  "devDependencies": {
    "@babel/core": "^7.4.5",
    "@babel/plugin-proposal-class-properties": "^7.4.4",
    "@babel/plugin-transform-runtime": "^7.4.4",
    "@babel/preset-env": "^7.4.5",
    "@babel/preset-react": "^7.0.0",
    "aspnet-webpack": "^3.0.0",
    "babel-loader": "^8.0.6",
    "css-loader": "^3.0.0",
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
    "style-loader": "^0.23.1",
    "webpack": "^4.35.0",
    "webpack-cli": "^3.3.5",
    "webpack-dev-middleware": "^3.7.0",
    "webpack-hot-middleware": "^2.25.0"
  },
  "dependencies": {
    "@babel/runtime": "^7.4.5",
    "bootstrap": "^4.3.1",
    "core-js": "^3.1.4",
    "moment": "^2.24.0",
    "react-bootstrap": "^1.0.0-beta.9",
    "react-contextmenu": "^2.11.0",
    "react-hint": "^3.2.0",
    "react-moment": "^0.9.2",
    "react-router-dom": "^5.0.1",
    "react-select": "^3.0.4",
    "sweetalert2": "^8.13.0",
    "sweetalert2-react-content": "^1.1.0"
  }
}
```
webpack.config.js
```
const path = require('path');
module.exports = {
    mode: 'development',
    entry: { 'main': ['core-js/fn/promise', 'core-js/stable/object/assign', './wwwroot/src/app.js'] },
    output: {
        path: path.resolve(__dirname, 'wwwroot/dist'),
        filename: 'bundle.js',
        publicPath: 'dist/'
    },
    module: {
        rules: [
            {
                test: /\.(js|jsx)$/,
                exclude: /(node_modules)/,
                resolve: {
                    extensions: [".js", ".jsx"]
                },
                use: {
                    loader: 'babel-loader',
                    options: {
                        presets: ['@babel/preset-react', '@babel/preset-env', {
                            'plugins': ['@babel/plugin-proposal-class-properties',
                                '@babel/plugin-transform-runtime']
                        }]
                    }
                }
            },
            {
                test: /\.css$/,
                use: [
                    { loader: "style-loader" },
                    { loader: "css-loader" }
                ]
            }
        ]
    }
};
```

**Comment by jquense** [comment]
Are you absolutely certain you don't that multiple copies of react or react-dom? That's the answer to this error for 99.999% of cases (anecdotally)

**Comment by timgerhard** [comment]
@jquense running "npm ls react-dom" or "npm ls react" returns only one instance of react, so yes - I am absolutely certain. Plus this error only occurs when I install react-bootstrap and use it in my code. If I don't use it there is no error.

**Comment by jquense** [comment]
those commands don't necessarily tell you what you want. They only tell you what they think is installed from the lock-file not what's actually on disk. If you can put together a repo that contains the issue I could check. Apart from that tho i can't reproduce the issue.

**Comment by yashasx** [comment]
Were you able to resolve this issue? I am having the same problem still.

**Comment by bpas247** [comment]
@timgerhard do you mind writing up a quick CodeSandbox using our [basic example](https://codesandbox.io/s/github/react-bootstrap/code-sandbox-examples/tree/master/basic)?

**Comment by mighty-titan** [comment]
I came across the same problem, updated react to highest version and then react-bootstrap to beta 11 and got this error there where im using redux, but im using version 5 of it in my app...

**Comment by timgerhard** [comment]
@yashasx @mighty-titan i was able to resole the issue - finally.

Apparently I had two instances of react running at the same time. Surprisingly this did not come to my attention until I tried using react-bootstrap.

In my case I installed react via npm while still having the react <script> tag in my master template (obviously resulting in embeding the react code twice). 

So I assume to resolve this issue **try to find the second instance of react in your project**. It could be everywhere.

**Comment by ferisagaragu** [comment]
I don't speek English but..... Detecte que el problema estaba aquí en el package.json 

`{
  "name": "react-fancy-component",
  "version": "0.0.1",
  "description": "",
  "main": "build/index.js",
  "peerDependencies": {},
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "webpack --watch",
    "build": "webpack"
  },
  "author": {
    "name": "Fernando Isaias Garcia Aguirre",
    "email": "ferisagaragu@gmail.com"
  },
  "devDependencies": {
    "babel-cli": "^6.24.1",
    "babel-core": "^6.24.1",
    "babel-loader": "^7.0.0",
    "babel-plugin-transform-object-rest-spread": "^6.23.0",
    "babel-plugin-transform-react-jsx": "^6.24.1",
    "babel-preset-env": "^1.5.1",
    "bootstrap": "^4.3.1",
    "css-loader": "^3.2.0",
    "eslint": "^6.5.1",
    "eslint-config-airbnb": "^18.0.1",
    "eslint-plugin-import": "^2.18.2",
    "eslint-plugin-jsx-a11y": "^6.2.3",
    "eslint-plugin-react": "^7.16.0",
    "eslint-watch": "^6.0.1",
    "react-bootstrap": "^1.0.0-beta.14",
    "style-loader": "^1.0.0",
    "webpack": "^2.7.0",
    "webpack-cli": "^3.3.9"
  }
}
`
en la sección de dependencias estaba react, entonces cuando creaba la librería se compilaba con, otra instancia de react, por eso al correr la aplicación la tomaba doble.

**Comment by alex789** [comment]
I was stuck on this issue for ages but figured out if I installed react (gatsby) using cmd instead of git bash I didn't have the problem. 

I was also getting some weird errors that 'There are multiple modules with names that only differ in casing' so I think maybe bash was installing react more than once with different casing in the path.

This thread tipped me off to it: https://github.com/creativetimofficial/material-kit-react/issues/53

**Comment by hellowhirl** [comment]
I had this error because I had a dependency installed at the top of my project, but I only needed that dependency in my `client` folder. I uninstalled the package at the top level and reinstalled into my `client` folder and then the error message went away. Hope that helps someone!

**Comment by dimaslanjaka** [comment]
same problem here with react, react-dom v17
