### ISSUE TITLE
Fix little typo in https://react-bootstrap.github.io/migrating/

### ISSUE THREAD

**Issue by lc3t35** [react-bootstrap/react-bootstrap#3966]
When migrating, I had this error :

`
Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
`

I've check the documentation in https://react-bootstrap.github.io/migrating/ and have seen why I did not fix it first, there is a little typo that prevent to find InputGroup.Addon is used :

> removed InputGroupButton, and InputGroupAddon
 
should be 

> removed InputGroup.Button, and InputGroup.Addon

Changing InputGroup.Addon as InputGroup.Append fixed my issue.

**Comment by taion** [comment]
Nice catch. Feel free to send in a PR!
