### ISSUE TITLE
ModalTrigger trigger .preventDefault()?

### ISSUE THREAD

**Issue by aforty** [react-bootstrap/react-bootstrap#397]
More of a just a question than anything else. How come by default the ModalTrigger.toggle() method doesn't run preventDefault() on the event? This would prevent the page from navigating to a hash (#) when ModelTrigger is applied to an anchor, such as NavItem.

I'd be happy to make the change and submit a PR but I figure there must be a reason as to why this isn't handled by default.

Example code, where when clicked the page navigates to "#":
```
<BS.Navbar>
  <BS.Nav>
    <BS.ModalTrigger modal={modal}>
      <BS.NavItem>Register or Login</BS.NavItem>
    </BS.ModalTrigger>
  </BS.Nav>
</BS.Navbar>
```

**Comment by aforty** [comment]
Perhaps the "issue" lies with `NavItem` where the `.handleClick()` method only calls `.preventsDefault()` if an `onSelect` handler was provided. Perhaps here `.preventDefault()` should be called if the `href` property is still the default OR an `onSelect` handler is available.

Proposed change:
```
handleClick: function (e) {
  if (this.props.href === '#' || this.props.onSelect) {
    e.preventDefault();
  }

  if (this.props.onSelect && !this.props.disabled) {
    this.props.onSelect(this.props.eventKey, this.props.href, this.props.target);
  }
}
```

Thoughts?

**Comment by joemcbride** [comment]
Kind of related to: https://github.com/react-bootstrap/react-bootstrap/issues/419
