### ISSUE TITLE
Switching tabs with arrow keys runtime error in 0.32.4

### ISSUE THREAD

**Issue by ISlukin** [react-bootstrap/react-bootstrap#3983]
## Describe the bug

In "Nav" that is inside of "Tab.Container", if you pass null or undefined as a child, it breaks switching between tabs with arrow keys.

## To Reproduce

1. Open example
2. Select one of Nav Items
3. Press left or right arrow on the keyboard
4. Open your browser console and see the error

## Reproducable Example

https://codesandbox.io/embed/react-codesandbox-wh8tc

## Screenshot

https://drive.google.com/file/d/1p1CFjq8VHATBdfK60zrECjL6AcxLu6Wc/view?usp=sharing

## Expected behavior

1) Expected active tab to be switched
2) Expected no runtime errors in console

**Comment by kosmiq** [comment]
Is this still an issue in v.0.33.1?

**Comment by kyletsang** [comment]
Closing since bs3 is no longer supported

**Comment by toniton** [comment]
AFAIK, this is still an issue @kyletsang.
