### ISSUE TITLE
collapsibleMixin sets dimension of an element in pixels

### ISSUE THREAD

**Issue by vsolovyov** [react-bootstrap/react-bootstrap#399]
This approach works without problems if a content of the collapsible element changes only on `render` calls. But it also can change without React doing anything. 

For example, when you have an image of unknown dimensions, an `<img />` is rendered, `_updateDimensionAfterRender()` is called, after that browser gets a response with image dimensions and updates layout. And, because the height of my panel is set in pixels in element style, page looks like this (it's an accordion):

![Broken accordion](https://api.monosnap.com/rpc/file/download?id=OW8gDnNg7NEqB86wA7BTTbHkR7ZgZV)

If I reload the page, it renders correctly, because the image is cached by my browser and is immediately rendered with proper height and width.

I managed to work around this by setting `ref`: `<img ref="mainImage" />` and binding to `onload`:

```javascript
    componentDidMount() {
        var image = this.refs.mainImage;
        if (image !== undefined && this.props.onDOMUpdate !== undefined) {
            image.getDOMNode().onload = () => {
                this.props.onDOMUpdate();
            }
        }
    },

    /* parent element that contains collapsible element */
    onDOMUpdate() {
        this.setState({_rerenderHack: !this.state._rerenderHack});
    },
```

It works but I don't like such hacks. Do you have any ideas how to make `collapsibleMixin` more robust to changes of its children elements?

**Comment by joemcbride** [comment]
Looking at the original bootstrap component, it looks like they remove the height style after the animation completes.  We should be able to do the same.

**Comment by joemcbride** [comment]
Kick of animation - https://github.com/twbs/bootstrap/blob/master/js/collapse.js#L93

Remove dimension on complete - https://github.com/twbs/bootstrap/blob/master/js/collapse.js#L81

**Comment by joemcbride** [comment]
Uses https://github.com/twbs/bootstrap/blob/master/js/transition.js for cross browser compatibility and a default timeout.

**Comment by joemcbride** [comment]
So I think we just need to add the style removal to this line of the CollaspableMixin.

https://github.com/react-bootstrap/react-bootstrap/blob/master/src/CollapsableMixin.js#L20
