### ISSUE TITLE
Nav ref does not work.

### ISSUE THREAD

**Issue by winstonewert** [react-bootstrap/react-bootstrap#4012]
Using ref on Nav does not work.

Nav forwards the ref here: 

https://github.com/react-bootstrap/react-bootstrap/blob/master/src/Nav.js#L93

But AbstractNav does not and instead sets up its own ref

https://github.com/react-bootstrap/react-bootstrap/blob/master/src/AbstractNav.js#L129

So the ref set on Nav goes nowhere.

**Comment by bpas247** [comment]
hmm, seems to be working fine in [this example](https://codesandbox.io/s/nav-ref-example-pfv7z).

Either way it's probably more consistent if `AbstractNav` is changed to use `React.forwardRef` (or use one of the utility HOCs mentioned in [this comment](https://github.com/react-bootstrap/react-bootstrap/pull/4003#issuecomment-509384780).

**Comment by winstonewert** [comment]
Ok, I misdiagnosed slightly.

The problem is that the ref gives me the AbstractNav component whereas I actually needed the <ul> DOM component.

**Comment by taion** [comment]
Huh, I don't think there's any good reason we do that. Should we make `<AbstractNav>` also be a ref forwarder?
