### ISSUE TITLE
Circular dependency

### ISSUE THREAD

**Issue by priyankapyt** [react-bootstrap/react-bootstrap#4019]
## Describe the bug
Found using webpack CircularDependencyPlugin ( "circular-dependency-plugin": "^5.2.0" )
Manually looked into Media files and indeed they require each other.

Output:
node_modules/react-bootstrap/es/Media.js -> node_modules/react-bootstrap/es/MediaBody.js -> node_modules/react-bootstrap/es/Media.js

## To Reproduce
Install CircularDependencyPlugin.

Add below code in webpack config plugins array:
`  new CircularDependencyPlugin({
    onStart({ compilation }) {
      console.log('start detecting webpack modules cycles');
    },
    onDetected({ module: webpackModuleRecord, paths, compilation }) {
      compilation.errors.push(new Error(paths.join(' -> ')))
    },
    onEnd({ compilation }) {
      console.log('end detecting webpack modules cycles');
    },
  })`

## Expected behavior
There should be no circular dependency

## Environment (please complete the following information)

- Operating System:  macOS
- React-Bootstrap : 0.32.1

**Comment by mxschmitt** [comment]
Is it still reproducible on React-Bootstrap Version 1?

**Comment by priyankapyt** [comment]
Since version is still in beta, we have not moved to it. Will check & revert back.

**Comment by taion** [comment]
In general, we'd be happy to take a PR for this. This isn't actually a bug, though. This works just fine with the circular dependency.
