### ISSUE TITLE
collapseOnSelect prop is having no effect on responsive collapsed menu.

### ISSUE THREAD

**Issue by laurencefass** [react-bootstrap/react-bootstrap#4021]
collapseOnSelect prop is having no effect on responsive collapsed menu.

`export function CustomNavbar() {
    return (
        <div>
        <Navbar collapseOnSelect fixed="top" expand="lg" variant="light" bg="dark">
          <Navbar.Brand href="#">Syntapse React</Navbar.Brand>
          <Navbar.Toggle aria-controls="basic-navbar-nav" />
          <Navbar.Collapse id="basic-navbar-nav">
                <Nav className="mr-auto">
                    <LinkContainer to="/" activeClassName="active">
                    <NavItem>Home</NavItem>
                    </LinkContainer>
                    <LinkContainer to="/about" activeClassName="active">
                    <NavItem>About</NavItem>
                    </LinkContainer>
                    <LinkContainer to="/examples" activeClassName="active">
                    <NavItem>Examples</NavItem>
                    </LinkContainer>
                    <LinkContainer to="/scrollable" activeClassName="active">
                    <NavItem>Scrollable content</NavItem>
                    </LinkContainer>
                    <LinkContainer to="/news" activeClassName="active">
                    <NavItem>News</NavItem>
                    </LinkContainer>
                </Nav>  
            </Navbar.Collapse>
        </Navbar>

        </div>
    );
}`

thanks

**Comment by taion** [comment]
Can you provide a repo w/a CodePen or equivalent?

**Comment by laurencefass** [comment]
thanks for your reply.

site is http://react.syntapse.co.uk/scrollable

code looks like this:

`            <Navbar collapseOnSelect fixed="top" expand="lg" variant="light" bg="dark">
                <Navbar.Brand href="#">Scrollable menu</Navbar.Brand>
                <Navbar.Toggle aria-controls="basic-navbar-nav" />
                <Navbar.Collapse id="basic-navbar-nav">
                    <Nav className="mr-auto">
                        <LinkContainer to="/" activeClassName="active">
                        <NavItem>Home</NavItem>
                        </LinkContainer>
                        <Scrollspy className="scroll-nav flex-grid" items={ ['section-1', 'section-2', 'section-3', 'section-4', 'section-5'] } currentClassName="is-current">
                            <li><a href="#section-1"><NavItem>section 1</NavItem></a></li>
                            <li><a href="#section-2"><NavItem>section 2</NavItem></a></li>
                            <li><a href="#section-3"><NavItem>section 3</NavItem></a></li>
                            <li><a href="#section-4"><NavItem>section 4</NavItem></a></li>
                            <li><a href="#section-5"><NavItem>section 5</NavItem></a></li>
                        </Scrollspy>
                    </Nav>  
                </Navbar.Collapse>
            </Navbar>  
`

and resulting class looks like this:

`<nav class="navbar navbar-expand-lg navbar-light bg-dark fixed-top"><a href="#" class="navbar-brand">Scrollable menu</a><button aria-controls="basic-navbar-nav" type="button" aria-label="Toggle navigation" class="navbar-toggler"><span class="navbar-toggler-icon"></span></button><div class="navbar-collapse collapse" id="basic-navbar-nav"><div class="mr-auto navbar-nav"><div href="/" class="active nav-item">Home</div><ul class="scroll-nav flex-grid"><li class="is-current"><a href="#section-1"><div class="nav-item">section 1</div></a></li><li class=""><a href="#section-2"><div class="nav-item">section 2</div></a></li><li class=""><a href="#section-3"><div class="nav-item">section 3</div></a></li><li class=""><a href="#section-4"><div class="nav-item">section 4</div></a></li><li class=""><a href="#section-5"><div class="nav-item">section 5</div></a></li></ul></div></div></nav>`

**Comment by taion** [comment]
This is a little bit more than we can easily deal with. Can you isolate a repro that runs in one of the code sandboxes?

**Comment by laurencefass** [comment]
I will try to set this up. It looks as though the "collapseOnSelect" prop is not being translated to a css class.

**Comment by taion** [comment]
It's not supposed to. It only drives JS behavior.

**Comment by laurencefass** [comment]
here is minimal codesandbox demonstrating the issue. https://codesandbox.io/s/bold-boyd-67zuh 

Doesn't scroll properly in the code project view so needs to open in a separate window for scrolling but collapseOnSelect has no effect in any view.

**Comment by taion** [comment]
You need to use something like `<Nav.Link>` or `<Nav.Item>` per our examples, not just standard `<li>` and `<a>` elements.

**Comment by laurencefass** [comment]
<Nav.Link> forces a page reload and not desired.  collapseOnSelect need also work with <Link> elements.
