### ISSUE TITLE
All Modal classes should be options

### ISSUE THREAD

**Issue by hallister** [react-bootstrap/react-bootstrap#404]
`modal-dialog`, `modal-content` and `modal-header` all seem to be hard-coded. This prevents reusing the modal for other components, such as a [sidebar](http://mgcrea.github.io/angular-strap/#/asides#asides). Having a `modalDialogClass`, `modalContentClass`, etc prop would be really simple. I can PR it, but wanted to gauge interest/naming conventions.

**Comment by hallister** [comment]
So after playing with this for a while now, I'm starting to see the problem. It seems that react-bootstrap is *heavily* tied to the CSS markup of the original Bootstrap. This seems odd to me, as it only allows modification of the original components via CSS. So if I want to make a slightly modified modal `Aside`, I have to write it from the ground up because the bsClass for a modal has to be `modal` and can't be `aside`. 

I'm rewriting the components I plan on using using a more "options-oriented" approach, but I can't really PR it against this project since it would break how things are currently done.

**Comment by mtscout6** [comment]
I was not aware of AngularStrap, pretty cool! I like the Aside that it provides. One of the original goals of this library was to target default Bootstrap CSS behavior. With that said though the goal was to allow it to be overridden: https://github.com/react-bootstrap/react-bootstrap/blob/v0.15.1/src/Modal.jsx#L30.

Which was quickly lost: https://github.com/react-bootstrap/react-bootstrap/blob/v0.15.1/src/Modal.jsx#L42

It should not be too difficult to switch out each of the hard ties to modal with the supplied `bsClass` prop, which I'd happily take a PR for.

**Comment by hallister** [comment]
I actually did this two ways.

First, I did took out the hard ties to the class names and passed in configuration options for each class used in the modal. This turned into to some ugly markup, as the custom modal looked like this:

````HTML
<Modal
        key="sidebar"
        title="Navigation"
        className={baseClasses}
        animation={false}
        backdrop={true}
        onRequestHide={this.handleToggle}
        backdropClass="aside-backdrop"
        dialogClass="aside-dialog"
        contentClass="aside-content"
        titleClass="aside-title"
        headerClass="aside-header"
        openClass="aside-open"
        key="sidebar"
        modalStyle={style}
      >
````

That just looks... icky to me. So I ended up making another modification where I broke Modal into several sub-components:

````HTML
<ModalCustom className="aside" backdropClassName="aside-backdrop">
    <ModalDialog className="aside-dialog" contentClassName="aside-content">
        <ModalHeader className="aside-header">{header}</ModalHeader>
        <ModalBody className="aside-body">{body}</ModalBody>
    </ModalDialog>
</ModalCustom>
````

My plan was then to introduce a separate modal component that is just a generic modal, in the vein of:

````HTML
<Modal>
   <ModalHeader>Header</ModalHeader>
   <ModalBody>Body</ModalBody>
</Modal>
````

Where the `<Modal>` is basically going to render a `<ModalCustom><ModalDialog>` with the default Bootstrap classes/options. I haven't completed the last part yet, but that's my direction.

Sorry for the book, but I suppose the main reason I'm explaining this is because I'm willing to PR this once complete if you're interested, but this is a very different way of doing things so I'm not even sure your interested!

**Comment by hallister** [comment]
As an aside: I did consider just using `<Modal>` instead of `<ModalCustom>` and just "checking" if a `<ModalDialog>` exists. But looping through children in `componentDidMount` seemed a little iffy. I'm not sure which of these two ways works better since I'm still somewhat new to react.

**Comment by AlexKVal** [comment]
Just for ref:
https://github.com/react-bootstrap/react-bootstrap/issues/646#issuecomment-121690684
now there is the `modalClassName` property in `Modal.*` subcomponents, that solves this use case.
