### ISSUE TITLE
Make dropdown is shown on hover

### ISSUE THREAD

**Issue by SZharkov** [react-bootstrap/react-bootstrap#4042]
It would be nice dropdown have a feature of being show on hover. This is a usual thing which is requested by almost all my customers and I prefer hover instead of click as well. 
It's possible to get one dropdown to be shown on hover using state. 
But what if I have a lot of dropdowns (in my navbar, for example)?

```
const navbarItem = (item, index) => {
  return (
    <NavDropdown title={item.title}
                 key={index}
                 id={`nav-dropdown-${index}`}>
      <div className={styles.dropdownMenu}>
    
           ....content

      </div>
    </NavDropdown>
  );
};


const Navbar = () => {
  return (
    <div className={styles.navbar}>
      <Container>
        <Nav className={'justify-content-between'}>

          {links.map((item, index) =>
            navbarItem(item, index)
          )}

        </Nav>
      </Container>
    </div>
  );
};
```

**Comment by taion** [comment]
Why not wrap it in another component that itself handles the state management?

**Comment by SZharkov** [comment]
@taion I agree, that's possible. But it would be nice to have such functionality out of the box

**Comment by oliviertassinari** [comment]
Relevant to the feature request: http://markdotto.com/2012/02/27/bootstrap-explained-dropdowns/.

**Comment by alexmuzenhardt** [comment]
@SZharkov maybe it is interesting to give the component an optional prop like "hover" and pass true or false. With that information the component behaves differently based on the given prop. Maybe interesting to implement...

**Comment by jquense** [comment]
This isn't something that is supported upstream, it's messy and not straightforward to implement in a way that is nice for users _generally_ (do you close on hover out? what if you are moving towards the menu?). If folks have specific use cases that warrant this and have thought through their _particular_ behavior it's pretty easy to implement as a wrapper around Dropdown, since `show` is fully controllable.

**Comment by joshcoast** [comment]
@jquense stop being obtuse. You know exactly what they are after.

**Comment by jquense** [comment]
@joshcoast If you continue to interact with folks here with that attitude you'll be banned. Maintainers, here do their best to meet a wide variety of use-cases with a lot of constraints you may not be aware of. If you are unhappy with the level of service you are receiving we'll give you a full refund, fork and move on if you've nothing constructive to add

**Comment by moretalk** [comment]
I know this is closed by the following CSS will do the trick to override the behaviour and show it on hover.

.dropdown:hover .dropdown-menu {
  display: block;
}

**Comment by kibbyd** [comment]
@moretalk LEGEND!

**Comment by daangelov** [comment]
Sorry for commenting a closed issue, but in case anyone lands here, this is a nice functional component that does the trick.

```javascript
import React, {useState} from 'react';
import {Dropdown} from 'react-bootstrap';

export default function HoverControlledDropdown(props) {
    const [isHovered, setIsHovered] = useState(false);
    const [isClicked, setIsClicked] = useState(false);

    return (
        <Dropdown
            {...props}
            onMouseEnter={() => setIsHovered(true)}
            onMouseLeave={() => setIsHovered(false)}
            onToggle={() => setIsClicked(!isClicked)}
            show={isClicked || isHovered}
        />
    );
}
```
