### ISSUE TITLE
holder.js doesn't work in Container/Row/Col

### ISSUE THREAD

**Issue by thorque** [react-bootstrap/react-bootstrap#4043]
## Describe the bug

I am playing around with Meteor and react-bootstrap. Right now I am evaluating the auto layout feature with container, rows and columns. This is really nice but in a column I don't getting the placeholder via holder.js running. Outside of the container it works as expected.

## To Reproduce

I am using this react component:

`import React, { Component } from 'react';
import Container from "react-bootstrap/Container";
import Row from "react-bootstrap/Row";
import Col from "react-bootstrap/Col";

class QuestionsC extends Component {
    render() {
      return (
        <div>
          &lt;h2&gt;Available questions!&lt;/h2&gt;
         &lt;img src="holder.js/180x100"/&gt;&lt;/Col&gt; &lt;!-- This works --&gt;
          &lt;Container&gt;
            &lt;Row&gt;
              &lt;Col&gt; &lt;img src="holder.js/180x100"/&gt;</Col&gt; &lt;!-- This doesn't work --&gt;
            &lt;/Row&gt;
          &lt;/Container&gt;
        &lt;/div>
      );
    }
  }`
## Reproducable Example
see code above

## Environment (please complete the following information)

- Operating System: macOS 10.14.5
- Browser, Version Safari
- React-Bootstrap 1.0.0-beta.9
- Meteor 1.9.3

Do I miss anything?

Thanks in advance
Thorsten

**Comment by taion** [comment]
Can you put this in a CodePen/JSFiddle/&c.?

**Comment by mxschmitt** [comment]
Closed due no response. If you'll add a e.g. Codesandbox example (https://codesandbox.io/s/github/react-bootstrap/code-sandbox-examples/tree/master/basic) feel free to ping me and we will reopen this.
