### ISSUE TITLE
onSelect in TabbedArea disables the tab switch behavior

### ISSUE THREAD

**Issue by dannymk** [react-bootstrap/react-bootstrap#407]
In the following code if I remove the onSelect property in the TabbedArea I get the switch tab behavior (expected), however (with onSelect) the handleSelect code is executed but the tabs do not switch.  Am I missing something or is this a bug?

<pre>
... package.json
  "dependencies": {
    "react": "~0.12.2",
    "react-bootstrap": "^0.15.1"
  }
...

'use strict';

var React = require('react/addons');
var TabPane = require('react-bootstrap').TabPane;
var TabbedArea = require('react-bootstrap').TabbedArea;

var TempApp = React.createClass({
  getInitialState: function(){
     return {
        menus: [
          { key:1, value:"Add content", title:"Add New Contents" },
          { key:2, value:"Find content", title:"Find Contents" }              
        ]
     };
  },
  render: function() {
    var items = this.state.menus.map(
        function(menu,index){
          return (
             &lt;TabPane key={menu.key} eventKey={menu.key} tab={menu.value}&gt; 
                {menu.title}
             &lt;/TabPane&gt;
          );
        }
    );
    return (
      &lt;TabbedArea onSelect={this.handleSelect}&gt;
          {items}
      &lt;/TabbedArea&gt;
    );
  },
  handleSelect: function(selectedKey) {
    console.log("Clicked: " + selectedKey);
  }  
});
React.render(&lt;TempApp /&gt;, document.getElementById('content')); // jshint ignore:line
</pre>

**Comment by manuquentin** [comment]
I'm expecting the same issue, when adding: `onSelect={this.myHandle}` tabs doesn't switch anymore.

**Comment by manuquentin** [comment]
Forget it, I'm to add the `activeKey` props:

```html
 <TabbedArea activeKey={this.state.tabActive} onSelect={this.onChangeTab}>
    <!- ... -->
</TabbedArea>
```

```js
onChangeTab: function(selectedKey) {
    var state = {
        tabActive: selectedKey
    };

   this.setState(state);
}
```

**Comment by dannymk** [comment]
Yes, that works.  Thank you.  I should of paid closer attention to the documentation.
