### ISSUE TITLE
Getting Started CSS Update

### ISSUE THREAD

**Issue by lukejpreston** [react-bootstrap/react-bootstrap#4071]
## Is your feature request related to a problem? Please describe

There are other ways to include bootstrap CSS which could be included in the getting started

## Describe the solution you'd like

Update the docs, something along the lines of:

After running `npm i bootstrap`, and if you are using the webpack css module (default with create-react-app) you can import the CSS using this snippet `import 'bootstrap/dist/css/bootstrap.css'`

**Comment by mxschmitt** [comment]
You mean, that we should also provide an example which will load it via a CDN?

**Comment by lukejpreston** [comment]
You could do that as well

I mean in the [stylesheets docs](https://react-bootstrap.github.io/getting-started/introduction/#stylesheets), in your JS code you can add that line of code and it will bring in the CSS without the need for bringing in a separate stylesheet, either via CDN or local version.

For example

```js
import React from 'react'
import './app.css'
import 'bootstrap/dist/css/bootstrap.css'
import Button from 'react-bootstrap/Button'

const App = () => <div className="App">
  <Button>HELLO</Button>
</div>

export default App
```

You might like to include the advantages of this in the docs:

* consistent bootstrap CSS version and JS version
* single CSS payload vs multiple payloads (resolves, speed and CSS ordering issues)

**Comment by taion** [comment]
Yeah, that sounds like a good idea. Can you draft a quick PR?

Likely also worth noting that the normative way to do this is probably to include the Bootstrap Sass and compile it all yourself, so you can override variables and such locally.

**Comment by jquense** [comment]
Having a few setup examples of patterns (cdn, custom sass, webpack import) here might make an excellent set of codesandboxes as well ;) @bpas247

**Comment by bpas247** [comment]
So what should be explicitly done here to be able to close this issue?

**Comment by taion** [comment]
We should show e.g. using Sass in the "getting started" guide.

**Comment by HenriqueFadoni** [comment]
can I have this issue?

**Comment by bpas247** [comment]
is this a dup of #4578? or vice versa

**Comment by kyletsang** [comment]
Closing since this now exists:

https://react-bootstrap.github.io/getting-started/introduction#stylesheets
