### ISSUE TITLE
Extend react-bootstrap Button

### ISSUE THREAD

**Issue by bsell93** [react-bootstrap/react-bootstrap#4077]
Hello!

I am attempt to extend the props for the react-bootstrap Button class. So far I have failed in my attempts.

Any suggestions on how to get the types/props to behave?

Here is a codesandbox: https://codesandbox.io/s/react-bootstrap-button-extended-vhj5j

Thanks!

**Comment by taion** [comment]
What specifically are you seeing that isn't working?

**Comment by bsell93** [comment]
![image](https://user-images.githubusercontent.com/5335177/61321480-9caf8080-a7d9-11e9-8fd9-7a895d93f9e6.png)
This^

**Comment by taion** [comment]
This is an error in your type definitions. You didn't define an `as` type in `Button.tsx`.

**Comment by bsell93** [comment]
I know that. I am saying I want to inherit the props from the `react-bootstrap/Button` component.

**Comment by bsell93** [comment]
Take note I am extending the button, but the types aren't working
![image](https://user-images.githubusercontent.com/5335177/61323514-2c572e00-a7de-11e9-9d79-f0cfbb50b529.png)

**Comment by bsell93** [comment]
Shouldn't the props of `react-bootstrap/Button` be added to my `IButtonProps` interface if I extend it? Of which, `as` and `disabled` should be a part of.

**Comment by bsell93** [comment]
I had a friend take a look and it seems like he got it working, although somewhat nasty in appearance.

https://codesandbox.io/s/react-bootstrap-button-extended-uwlcp

**Comment by bsell93** [comment]
@taion do you think there may be a better solution?
