### ISSUE TITLE
Keep accordion card expanded

### ISSUE THREAD

**Issue by HoyongJung** [react-bootstrap/react-bootstrap#4078]
Hello! I am new to react and I have a question with Accordion. Is there a way to keep a card expanded? Right now, when I click a header the card expands, and when I click a different header, then the expanded card will collapse and the other card will open. 

However, I want to keep the card expanded until I click again the same header for the card.

Hope my question is making sense!

**Comment by taion** [comment]
Pass in your own `activeKey` prop plus an `onSelect` callback, and implement the logic of your choice in dealing with "selected" events in the `onSelect` callback.

**Comment by HoyongJung** [comment]
Could you give me an example?
