### ISSUE TITLE
collapseOnSelect is not compatable with router <Link> and <NavLink>

### ISSUE THREAD

**Issue by laurencefass** [react-bootstrap/react-bootstrap#4080]
## Describe the bug

collapseOnSelect only works with <Nav.Link> items and not with router <Link> items

## To Reproduce

Take two identical links one as Nav.Link and one as Link

```
                    <Nav.Link key="Home" href="/" activeClassName="active">
                    <NavItem>Home</NavItem>
                    </Nav.Link>
                    <Link key="Home" to="/" activeClassName="active">
                    <NavItem>Home</NavItem>
                    </Link>
```

`<Nav.Link>` selection closes the collapsed menu as expected but reloads the entire page (by design) which is not desired.
`<Link>` loads the correct component according to its route definition, but the collapsed menu does not close on selection.

## Expected behavior

Nav.Link, Link and NavLink should initiate the collapseOnSelect action and close the collasped menu.

## Environment

    "bootstrap": "^4.3.1",
    "jquery": "^1.9.1",
    "react": "^16.8.6",
    "react-bootstrap": "^1.0.0-beta.9",
    "react-devtools": "^3.6.1",
    "react-dom": "^16.8.6",

browser: 

    chrome: Version 75.0.3770.100

## Additional context

related to issue #4021 which was closed with incorrect advice.

**Comment by taion** [comment]
see https://github.com/react-bootstrap/react-router-bootstrap
