### ISSUE TITLE
continuation of #4081. collapseOnSelect not working with anything but Nav.Link (including LinkContainer)

### ISSUE THREAD

**Issue by laurencefass** [react-bootstrap/react-bootstrap#4082]
Perhaps I am not being clear in my problem definition, the issue in #4081 is not that LinkContainer is not working it is that it is incompatible with collapseOnSelect. I believe this is a bug not a Q&A. According to documentation: accepts same parameters as React Router's so I am using it as a direct drop in. apologies if i am misunderstanding application. React Bootstrap collapseOnSelect is not working if it only works with Nav.Link

**Comment by jquense** [comment]
> React Bootstrap collapseOnSelect is not working if it only works with Nav.Link

It is, it only works with you use `Nav.Link` they are the components that implement the behavior.

**Comment by laurencefass** [comment]
Thank you for your reply.

Nav.Link reloads the entire page which is not desired. Jimmy Jia taion suggested that <LinkContainer> may offer a solution but I've yet to get it to work. It certainly has no  effect as a direct replacement for Nav.Link or NavLink.

As Reloading the page for every link selection is not desirable for any SPA navbar I maintain that React Bootstrap's current support only for Nav.Link is a bug in design if not in the code.

thanks

**Comment by laurencefass** [comment]
Would it be possible to extend behaviour of other navbar link types to work as Nav.Link?

**Comment by jquense** [comment]
`collapseOnSelect` was added specifically for SPA navigation, where you change the url but don't do a hard refresh e.g. with react router's Link or LinkContainer. It's meant to mimic exactly the behavior you're describing on normal links. 

> Nav.Link reloads the entire page which is not desired.

That is only true if it's an `<a>` and you let it re-render the page. If you don't want it to re-render the page prevent you can not render `as` an anchor or prevent default onClick. Hopefully that clarifies the functionality, if you are still unhappy with how it works, there are alternative approachse you can take as noted in the `collapseOnSelect` documentation

> Manually controlling expanded via the onSelect callback is recommended instead, for more complex operations that need to be executed after the select event of <Nav> descendants.

You can always collapse the navbar by setting `expanded` to `false` whenever you like and in response to any event you want.

**Comment by vladikz** [comment]
Just put `eventKey="i"` to each `Nav.Link`

**Comment by fthbby** [comment]
> Just put `eventKey="i"` to each `Nav.Link`

this worked, thank you!
