### ISSUE TITLE
Is the useContext(SelectableContext) redundant in Dropdown.js

### ISSUE THREAD

**Issue by betterliyu** [react-bootstrap/react-bootstrap#4095]
I am studying the Dropdown component code to know how it works. I noticed SelectableContext is passed into DropdownItem to execute the selected event handler if the item is selected. 
[<SelectableContext.Provider value={handleSelect}>](https://github.com/react-bootstrap/react-bootstrap/blob/5ee5e56031f2e74c0aef024930ec5bc5d0ccd5bc/src/Dropdown.js#L122). 
It's easy to understand. 
But why we use [const onSelectCtx = useContext(SelectableContext);](https://github.com/react-bootstrap/react-bootstrap/blob/5ee5e56031f2e74c0aef024930ec5bc5d0ccd5bc/src/Dropdown.js#L105) in the Dropdown.js? It may be undefined all the time because there's no context passed into from ancestor components. Shall we delete it? Or any other considerations?

**Comment by jquense** [comment]
It's defined when you place a dropdown in a Nav which provides its own selection context!

**Comment by bpas247** [comment]
Yeah the `SelectableContext` pattern is used a lot in our components, not just Dropdown (AccordionToggle, AbstractNavItem, Navbar, etc). How I have understood using `SelectableContext` is from this https://github.com/react-bootstrap/react-bootstrap/pull/3409#discussion_r271059620:
> if you look at the other use cases, we only use <SelectableContext.Provider> to pass down onSelect, while using a different context to pass down details of the active item. i guess because the latter varies from place to place?

So `SelectableContext` ends up being quite crucial in differentiating the responsibilities of the contexts that are being provided by our Components, so removing it entirely from implementation would not only be a lot of work but it might make how we handle context more confusing in implementation than its probably worth.

**Comment by betterliyu** [comment]
@bpas247  Thank you for your explanation!

**Comment by bpas247** [comment]
> @bpas247 Thank you for your explanation!

No problem 😁 please feel free to re-open this issue (or open a new one) if you have any other questions regarding the internal workings of the library ✌️
