### ISSUE TITLE
Panel-collapse wrong height when body is changed

### ISSUE THREAD

**Issue by iam4x** [react-bootstrap/react-bootstrap#410]
When you add content in the body of the panel, the heigh isn't re-calculated. 

This breaks the layout (a gif is better than explanation):

![gif](http://zippy.gfycat.com/JointThatGreathornedowl.gif)

I have an easy fix, but it adds a little glitch to the animation:

```(css)
.panel-collapse.collapse.in {
  height: 100% !important;
}
```

**Comment by joemcbride** [comment]
This should be fixed when https://github.com/react-bootstrap/react-bootstrap/pull/427 is merged.

**Comment by joemcbride** [comment]
Duplicate of https://github.com/react-bootstrap/react-bootstrap/issues/399
