### ISSUE TITLE
Navbar toggle button changes position when open/closed

### ISSUE THREAD

**Issue by CyberiaResurrection** [react-bootstrap/react-bootstrap#4116]
## Describe the bug

On mobile, when toggling the menu navbar, the toggle button is pushed upwards approximately half its height when the menu is opened.

## To Reproduce

Steps to reproduce the behaviour:

1.  Set browser to device view, with width less than 580 px.
2.  Browse to https://miningskills.com.au
3.  Click toggle button

## Reproducible Example
See https://codesandbox.io/s/code-sandbox-examples-2lr0d for the best I'm able to reproduce it outside the application.  In that example, the toggle bar is jumping left and right - I'm not sure if this is related to my original issue, or something else.

## Expected behaviour

I was expecting the toggle button to remain where it is.

## Screenshots

Un-expanded
![image](https://user-images.githubusercontent.com/9083866/61711406-50df7700-ad97-11e9-8b0a-d768ce8892d2.png)

Expanded
![image](https://user-images.githubusercontent.com/9083866/61711451-6e144580-ad97-11e9-8dfe-2f6d476571f7.png)

## Environment (please complete the following information)

- Operating System: [e.g. macOS]
Pain persists on Windows 10 (by reports) and Fedora 29 (my machine)

- Browser, Version : Google Chrome 75.0.3770.80 (Official Build) (64-bit)
- React-Bootstrap Version : 1.0.0-beta.9

## Additional context

This is running in a Laravel 5.8 application on shared hosting, using vuera for the integration layer (since I've had to integrate Vue and React components).

**Comment by taion** [comment]
Can you reproduce this on our examples page? Otherwise, it's most likely an issue with your specific custom CSS.

**Comment by CyberiaResurrection** [comment]
@taion, thanks for replying so quickly.  I've added a partial repro in the codesandboxio link - or have I missed something?

**Comment by bpas247** [comment]
> On mobile, when toggling the menu navbar, the toggle button is pushed upwards approximately half its height when the menu is opened.

I'm gonna have to agree with taion, this is probably caused by your custom CSS. You can checkout the [Navbar doc examples](https://react-bootstrap.github.io/components/navbar/) to see if you can reproduce the bug there, although I wasn't able to.

> In that example, the toggle bar is jumping left and right - I'm not sure if this is related to my original issue, or something else.

I can't seem to reproduce that bug when I run that CodeSandbox example.

Unexpanded:
![image](https://user-images.githubusercontent.com/18705892/61764160-05c06680-ad8d-11e9-8faf-bd172338a347.png)

Expanded:
![image](https://user-images.githubusercontent.com/18705892/61764189-24bef880-ad8d-11e9-8ff0-7fb0c7779707.png)

**Comment by CyberiaResurrection** [comment]
Thank you both @taion and @bpas247, apologies for the noise.
