### ISSUE TITLE
Request to publish latest changes to NPM

### ISSUE THREAD

**Issue by BitWhites222** [react-bootstrap/react-bootstrap#4123]
## Describe the bug

@bpas247 @taion I required the touch functionality that was added in Carousel component two weeks back, for my library. I just wanted to request/enquire how often are patch versions published to NPM and if there is a release planned sometime soon? Thanks a lot.

**Comment by taion** [comment]
it's in beta 10

**Comment by BitWhites222** [comment]
@taion Thanks much. I bumped up the beta version and the touch is working. Although the direction of slide movement based on swipe seems to be opposite of what I expected, maybe I've implemented it wrong.
 
In this PR in line 245 , https://github.com/react-bootstrap/react-bootstrap/pull/4018/files/dc2e070ee2459e9332cc6f3576bba4d7cbc1b75c
`/*Going left */ if (e.changedTouches[0].screenX < this.state.touchStartX)` 
Should this condition make the slide go right instead of left or is the current flow correct?

Also I wanted to ask a trivial unrelated question, I cannot push my branch to this repo  for making any contribution(tried cloning with both https and ssh). Do I need to take a fork of the repo?

**Comment by taion** [comment]
Yes, you need to fork to submit a PR.

**Comment by bpas247** [comment]
> Also I wanted to ask a trivial unrelated question, I cannot push my branch to this repo for making any contribution(tried cloning with both https and ssh). Do I need to take a fork of the repo?

I would recommend reading up on the traditional flow of [contributing to projects you don’t have write-access to](https://guides.github.com/activities/forking/).
