### ISSUE TITLE
Wrong event.target propagation on button submit issue

### ISSUE THREAD

**Issue by robert-rc2i** [react-bootstrap/react-bootstrap#4126]
## Describe the bug

When using Form control with HTML5 validation (i.e: uncontrolled react input components).  The event.target being propagated when clicking on the submit button is the same as event.currentTarget instead of originating from the button. 

The event.target should reference the <button> element that originated the submit of the form, while the event.currentTarget points to the <form> element as it has the onSubmit listener attached to it.

## To Reproduce

1- Open the code in code sandbox (see link below)
2- Activate the console view in code sandbox
2- Click on the first submit button (HTML) section
2.1- When clicked, a log entry is being produced using the following command:

`console.log("Events:", event.currentTarget === event.target, event.currentTarget, event.target);`

3- You should see a log entry with a false value and both event values being displayed.  One is the form the other the button - **This is the expected behavior**

`Events: false, <form novalidate="" class="">…</form>, <button name="submit" type="submit" class="btn btn-primary" value="submit">Submit</button>`

4- Now click the last submit button  (React-Bootstrap)
5- You should see a log entry with true value and both event values being the same (i.e. a form element) **This is NOT the expected behavior**

`Events: true, <form novalidate="" class="">…</form>,  <form novalidate="" class="">…</form>`

## Reproducible Example

Here is an example in code sandbox: [https://codesandbox.io/embed/distracted-jepsen-uiyqp](https://codesandbox.io/embed/distracted-jepsen-uiyqp)

## Expected behavior

The expected behavior is that `event.target` must refers to the button that submitted the form, so that when I receive the event object, its targets attributes should refers to the following:
1- `event.currentTarget` refers to the `<form>` element, since it has the onSubmit listeners attached to it
2- The `event.target`  refers to the `<button>` element that was clicked.

## Screenshots

Just run the code

## Environment (please complete the following information)

- Operating System: [latest MacOS & Windows 10]
- Browser, Version [Latest Chrome & Firefox]
- React-Bootstrap Version [1.0.0-beta.10]
- React Version [16.8.6]

**Comment by taion** [comment]
Is the behavior different when not using React-Bootstrap components? Or what's the issue within this library specifically?

**Comment by robert-rc2i** [comment]
As stated above, yes.  The behavior is different.  I expect the event.target to refer to the button that was clicked and not the <form> element.

As you can see in the example I render two forms.  One using standard HTML element, whiel the other is making use of react-bootstrap.  The second form (React bootstrap) is not behaving as expected.  I.e. the event.target refers the <form> element instead of the <button> element that was clicked.

**Comment by taion** [comment]
Your example is only doing that because you put an `onClick` handler on your `<form>` rather than an `onSubmit`. If I switch it to an `onSubmit`, the two forms behave the same.

**Comment by robert-rc2i** [comment]
Damn!  Thanks for pointing that out.  After re-working the example, it now indeed provided the same behavior.  I must have read the spec wrong then, as I was under the impression that the current target is the element that the listener is attached to and the target refers to the element that the event originated.  It works for onClick but not for submit apparently.

Thanks!
