### ISSUE TITLE
Modal Is Rendered At The Bottom of the Screen?

### ISSUE THREAD

**Issue by kylemas** [react-bootstrap/react-bootstrap#4127]
## Describe the bug

The Modal is showing at the bottom of the screen for some weird reason onclick. I followed the example for "Launch Demo Modal" yet it doesn't show up as a popup, rather just a portion at the bottom of the screen. 

## Screenshots

<img width="1423" alt="Screen Shot 2019-07-25 at 11 46 30 PM" src="https://user-images.githubusercontent.com/34122775/61931763-7656b700-af36-11e9-9822-7e835a08abf7.png">

## Environment (please complete the following information)

- Operating System: macOS
- React-Bootstrap Version [e.g. 1.0.0-beta.10

`return (
    <div className="App">
      <main className="App-main">
        <NodeView
          root={tree}
          onClick={handleNodeClick}
          selectedNode={selectedNode}
        // render={(item: TreeNode) => NodeView(item, selectedNode === item)}
        />
        <Modal
          show={modalShow}
          onHide={handleClose}
          size="sm"
          aria-labelledby="contained-modal-title-vcenter"
          animation={true}
          centered>
          <Modal.Header closeButton>
            <Modal.Title>Node Control Widget</Modal.Title>
          </Modal.Header>
          <Modal.Body>
            <ControlWidget {...{ selectedNode, resolveNode, closeBranch }} />
          </Modal.Body>
        </Modal>
        <button onClick={handleShow}> Modal </button>
      </main>
    </div>
  )`

**Comment by taion** [comment]
You're missing the CSS for modals.

**Comment by razdahan** [comment]
Hi, I am having the same problem rn,
what do you mean by missing CSS for modals?
and how can I fix it?

**Comment by snehsagarajput** [comment]
I am having the same problem.
**_It is being rendered at the end of the page._**

**Comment by kosmiq** [comment]
Your css/scss setup does not contain the classes needed for the modal. 

How are you adding your css? Are you using bootstrap 4.5.x? How is your css added/included in the project etc.

**Comment by snehsagarajput** [comment]
I have no css code linked to Modal Component as I am using the basic Modal Examples as [React-Bootstrap](https://react-bootstrap.github.io/components/modal/) shown here.
Do I need to add any css?
I am using :   
     "react-cookie": "^4.0.3", and
    "react-router-dom": "^5.2.0",
do they need any other setting for Modal to work perfectly?

**Comment by kosmiq** [comment]
Have you added the bootstrap css? Either via <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

Or
npm i bootstrap?

**Comment by snehsagarajput** [comment]
> Have you added the bootstrap css? Either via `<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">`
> 
> Or
> npm i bootstrap?

npm install react-bootstrap bootstrap

**Comment by kosmiq** [comment]
And you are doing either https://react-bootstrap.github.io/getting-started/introduction#css or the scss version?

**Comment by snehsagarajput** [comment]
> And you are doing either https://react-bootstrap.github.io/getting-started/introduction#css or the scss version?

Thank you so much. I was not importing the css. 


`import 'bootstrap/dist/css/bootstrap.min.css';`


Solved my problem.

**Comment by juan1630** [comment]
Thanks That worked for me too!!
