### ISSUE TITLE
Integrating Navbar Links and NextJS Link Components

### ISSUE THREAD

**Issue by awitherow** [react-bootstrap/react-bootstrap#4131]
Hello, similar to the React Router Bootstrap that has been created, is there any integration for using React Bootstraps Navbar/Nav.Link with the NextJS Link Component?

Thank you!

Austin

**Comment by jquense** [comment]
NextJs already exposes it's `Link` component in a way that makes it easy to wrap our components: `<Link><NavLink>Home</NavLink></Link` it doesn't however seem to expose a way to know if the current route is "active", so you'd have to roll your own version with that I think?

**Comment by awitherow** [comment]
Yep! I realised after some time that just proper nesting within the Link is active. And yeah I have had a little trouble with integrating the `active` tag with string.includes and other methods, have done a sort of `routeMap` approach checking object key/values 👍

**Comment by bennymeier** [comment]
I also had trouble with integrating NextJS Link within the Navbar.
My approach was:
`<Nav.Link as="span"><Link href="/index"><a>Home</a></Link></Nav.Link>`

**Comment by taion** [comment]
You'd probably want `<Nav.Link as={Link}>`

**Comment by blueshark226124** [comment]
```
<Link href="/index" passHref>
    <Nav.Link>Home</Nav.Link>
</Link>
```
You can use the "passHref" prop fo the "Link" component.

**Comment by developerpaddy** [comment]
Hey Friends,

Came Late in the party, but I recently implemented Link in Nexjs as follows
may help someone. If any advancement happens I will post the new one.
Thanks Folks...

```
import Link from 'next/link'
import { withRouter } from 'next/router'
import classNames from 'classnames'

import { Container, Navbar, Nav } from 'react-bootstrap'


export const NavLink = (props) => {

  let className = classNames({
    "nav-link": true,
    "is-active": props.pathname
  })
  return <Link href={props.path}><a className={className}>{props.label}</a></Link>

}

const Header = ({ router: { pathname } }) => (
  <header>
    <div id="wrapper-navbar">
        <Navbar bg="light" expand="lg">
        <Container >
          <Navbar.Brand href="#home">React-Bootstrap</Navbar.Brand>
          <Navbar.Toggle aria-controls="basic-navbar-nav" />
          <Navbar.Collapse id="basic-navbar-nav">
            <Nav className="ml-auto">
              <NavLink path="/" label="Home" pathname/>
              <NavLink path="/about" label="About Us" pathname/>
            </Nav>
          </Navbar.Collapse>
        </Container>
        </Navbar>    
    </div>
  </header>
)

export default withRouter(Header)

```

**Comment by NavizDev** [comment]
`<Link href="/">
          <NavbarBrand href="/">Reporte</NavbarBrand>
</Link>`
i use that.

**Comment by jwandekoken** [comment]
> ```
> <Link href="/index" passHref>
>     <Nav.Link>Home</Nav.Link>
> </Link>
> ```
> 
> You can use the "passHref" prop of the "Link" component.

Best answer.

**Comment by kolloch** [comment]
> ```html
> <Link href="/index" passHref>
>    <Nav.Link>Home</Nav.Link>
> </Link>
> ```

Thanks! It also works with [basePath](https://nextjs.org/docs/api-reference/next.config.js/basepath)

**Comment by BigBrainSmolBoi** [comment]
> > ```
> > <Link href="/index" passHref>
> >     <Nav.Link>Home</Nav.Link>
> > </Link>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > You can use the "passHref" prop of the "Link" component.
> 
> Best solution.

Yes It works but there is still the problem of active styles not being applied on the link by bootstrap

**Comment by FilipHrn** [comment]
> ```
> <Link href="/index" passHref>
>     <Nav.Link>Home</Nav.Link>
> </Link>
> ```
> 
> You can use the "passHref" prop of the "Link" component.

Bless you!

**Comment by devnajam** [comment]
There was a problem of "active" styles not being applied to the active link while using react bootstrap and next link component. I have found the solution to that. 
What you have to do is create a custom Link Component with some extra logic using next/router because Next JS Link component does not provide this out of the box. 

Create a new component Link.js and then paste this code in it. use this Link component instead of the next/Link component.

`import React from 'react'
import Link from 'next/link'
import { useRouter } from 'next/router'

export default ({ href, children }) => {

    const router = useRouter()
    let className = children.props.className || ''
    
    if (router.pathname === href) {
        className = `${className} selected`
    }
    
    return <Link href={href}>{React.cloneElement(children, { className })}</Link>
}
`

Using router object it will check if the  current url is same as href passed to the Link component and based on that active class will be assigned or not

**Comment by bbawj** [comment]
> There was a problem of "active" styles not being applied to the active link while using react bootstrap and next link component. I have found the solution to that. What you have to do is create a custom Link Component with some extra logic using next/router because Next JS Link component does not provide this out of the box.
> 
> Create a new component Link.js and then paste this code in it. use this Link component instead of the next/Link component.
> 
> ```
> import React from 'react'
> import Link from 'next/link'
> import { useRouter } from 'next/router'
> 
> export default ({ href, children }) => {
> 
>     const router = useRouter()
>     let className = children.props.className || ''
>     
>     if (router.pathname === href) {
>         className = `${className} selected`
>     }
>     
>     return <Link href={href}>{React.cloneElement(children, { className })}</Link>
> }
> ```
> 
> Using router object it will check if the current url is same as href passed to the Link component and based on that active class will be assigned or not

You can use the active prop:
```
<Link href="/" passHref>
  <Nav.Link active={currentPath === "/about"}>About us</Nav.Link>
</Link>
```

**Comment by marceloverdijk** [comment]
Does anyone maybe know how to do this with Gatbsy?

**Comment by Mostafa-Hussaini** [comment]
Hi
I am using react-bootstrap in a nextjs app, but there is an issue with the NavDropdown.Item tag, such that clicking the link hard loads the curresponding component or href path, and when I  use the nextjs built-in Link tag, like this, 
`<NavDropdown.Item  ><Link href={link}><>View {text}</></Link> </NavDropdown.Item>`, it does not take the href.
please help.
thanks...

**Comment by TruAmbition** [comment]
@Mostafa-Hussaini i'm having a similar issue, the text is the only thing that activates the next link where as if you use the NavDropdown.Item without Link, the entire "div" is a clickable component. Let me know if you were able to figure anything out on your side.

Cheers

**Comment by jakecyr** [comment]
@TruAmbition I was able to get around it by setting the `as` property on the `NavDropdown.Item` element to a custom `NavItem` component. For example:

```tsx
import Link from 'next/link';
import BootstrapNavItem from 'react-bootstrap/NavItem';
import BootstrapNavDropdown from 'react-bootstrap/NavDropdown';
import servicesList from '../data/servicesList';

const NextNavItem = ({ name, href }) => {
  return (
    <BootstrapNavItem>
      <Link href={href} passHref={true}>
        <a>{name}</a>
      </Link>
    </BootstrapNavItem>
  );
};

export default function ServicesNavItem() {
  return (
    <BootstrapNavDropdown as='li' title='Services'>
      {servicesList.map((service) => (
        <BootstrapNavDropdown.Item
          key={service.name}
          as={() => <NextNavItem name={service.name} href={service.url} />}
        ></BootstrapNavDropdown.Item>
      ))}
    </BootstrapNavDropdown>
  );
}
```

**Comment by JancoKorky** [comment]
Not working anymore with passHref, it will give you `Error: Hydration failed because the initial UI does not match what was rendered on the server.` Another word to `<a> cannot appear as a descendant of <a>.`
Best solution is from @taion 




> You'd probably want `<Nav.Link as={Link}>`

**Comment by refl3ction** [comment]
With Next.js 13 and React 18:

```jsx
// Doesn't work
<Link href="/" passHref>
    <Nav.Link>Home</Nav.Link>
</Link>
```

```jsx
// Works
import Link from "next/link";
import { Container, Nav, Navbar } from "react-bootstrap";

<Nav.Link as={Link} href="/profile">
    Profile
</Nav.Link>
```

**Comment by imageck** [comment]
@refl3ction thanks for testing!

How about a situation where you want to set `as` for the `Link` component and not RB's `Nav.Link`, e.g.:
```jsx
<Link href={{ pathname, query }}
      as={asPath}
      locale={l}
      className="nav-link">
  Home
</Link>
```

**Comment by 77pintu** [comment]
@refl3ction,  Thanks so much below solution worked for me and one more issue resolved now page reloading not happening 
import Link from "next/link";
import { Container, Nav, Navbar } from "react-bootstrap";

<Nav.Link as={Link} href="/profile">
    Profile
</Nav.Link>

**Comment by imageck** [comment]
@77pintu see my above reply. With Next.js 13, the order is reversed, `Nav.Link` should be a child of `Link` which needs both `legacyBehavior` and `passHref` to be specified for this to work.
