### ISSUE TITLE
Incompatible versions:  beta.10 requires uncontrolleble 7.0.0, however react-overlay still 1.2.0 and not compatible with uncontrollable 7.0.0

### ISSUE THREAD

**Issue by vladp** [react-bootstrap/react-bootstrap#4134]
> TypeError: _uncontrollable.default is not a function
> ./node_modules/react-overlays/Dropdown.js
> c:/myapp/node_modules/react-overlays/Dropdown.js:365
> 
>   362 | Dropdown.displayName = 'ReactOverlaysDropdown';
>   363 | Dropdown.propTypes = propTypes;
>   364 | Dropdown.defaultProps = defaultProps;
> > 365 | var UncontrolledDropdown = (0, _uncontrollable.default)(Dropdown, {
>   366 |   show: 'onToggle'
>   367 | });
>   368 | UncontrolledDropdown.Menu = _DropdownMenu.default;

This error appears to be due incompatibility between react-overlay (still 1.2.0) and 
and uncontrollable, wich is required by react-bootstrap to be 7.0.0.

**Comment by taion** [comment]
Why does the version mismatch matter? It's not a peer dependency of either, so having both versions is just fine.

**Comment by vladp** [comment]
In the above error, it appears that react-overlay 1.2.0 code (in Dropdown.js) is expecting
old style imports (eg  _uncontrollable.default) from Uncontrollable module.

However, uncontrollable 7.0.0 is being used by react-overlay 1.2.0 (or at least that's what I am understanding). And that generates the above mentioned error.

I can see that react-overlay's newer code, did user the new style export from Unctrollable,
but that version has not been yet published to Npm.

May be there is an underlying bundling error that incorrectly causes Uncontrollable 7.0.0 to 
bind to react-overlay 1.2.0.  not sure.
In the mean time, I switched back to beta.9 and all back to normal.

**Comment by amarkezic** [comment]
I also have the same problem, but reverting to beta.9 didn't solve this. Are there any updates on this issue ?

**Comment by popa-marius** [comment]
Downgrading worked for me. Be sure to have the exact version in the package.json, otherwise it will automatically install the latest beta if you use the `~` or `^`.
```    "react-bootstrap": "1.0.0-beta.9"```

**Comment by vladp** [comment]
@amarkezic , I am sure downgrading will work. As @popa-marius  had suggested, check your package.json to make sure you are not telling npm to install 'latest' in the 'beta' series.

**Comment by jquense** [comment]
For others, downgrading is not required. If you are receiving this error then something went wrong with your install, I would try nuking node_modules and your lock files and reinstalling. Multiple versions of uncontrollable is fine they aren't peer dependencies

**Comment by popa-marius** [comment]
@jquense I wish it was that simple. I nuked now both the node_modules and the lock file. Then I did an install. Started the server and I still get the same error in the browser console.
```
Dropdown.js:305 Uncaught TypeError: (0 , _uncontrollable.default) is not a function
  | ../node_modules/react-overlays/Dropdown.js | @ | Dropdown.js:305
-- | -- | -- | --
  | __webpack_require__ | @ | bootstrap:726
  | fn | @ | bootstrap:100
  | ../node_modules/react-bootstrap/es/Dropdown.js | @ | Dropdown.js:1
  | __webpack_require__ | @ | bootstrap:726
  | fn | @ | bootstrap:100
  | ../node_modules/react-bootstrap/es/index.js | @ | index.js:1
  | __webpack_require__ | @ | bootstrap:726
  | fn | @ | bootstrap:100


```

**Comment by jquense** [comment]
Something is being installed wrong still, are you forcably flattening node_modules? Npm or yarn should not be installing a version of a dep for a package that is incompatible with it, that's the whole point of specifying valid ranges in those packages package.json files

**Comment by popa-marius** [comment]
I'm not flattening node_modules. All of the project's dependencies are the latest versions available. 
For beta 9 the installed `uncontrollable` version is `6.2.3`.
For beta 10 the installed `uncontrollable` version is `7.0.0`.

`react-overlays` requires `uncontrollable^6.0.0` while `react-bootstrap` requires `uncontrollable^7.0.0`, so I'm not sure how both version could be installed or both conditions met via a standard npm install.

Maybe the dependency tree sheds some light into the `why`:
```
$ npm list uncontrollable
my-app@1.0.0 /my-app
└─┬ react-bootstrap@1.0.0-beta.10
  ├─┬ react-overlays@1.2.0
  │ └── uncontrollable@6.2.3
  └── uncontrollable@7.0.0
```

**Comment by taion** [comment]
But this is exactly what you'd expect, no? npm _does_ support nested dependencies with multiple mismatched versions.

Unless you're e.g. forcibly deduplicating dependencies in your bundler in a very naive way, this dependency layout means that react-overlays will use `uncontrollable@6.2.3`, while React-Bootstrap will use `uncontrollable@7.0.0`.

**Comment by taion** [comment]
In other words, with regard to:

>I'm not sure how both version could be installed or both conditions met via a standard npm install.

That `npm list` is telling you exactly that npm _has_ done so.

**Comment by popa-marius** [comment]
You are correct. There is the `uncontrollable@6.2.3` which is inside the `react-overlays/node_modules/uncontrollable` folder. But for some reason it's not being used alongside the 7 version.

Any idea what could cause that? I would suspect that a setting somewhere might be somehow flattening the node_modules when webpack uses them.

**Comment by taion** [comment]
You'd have to look at your own webpack config. Most likely the dedupe plugin, though.

**Comment by popa-marius** [comment]
I'm not using any form of dedupe. That's the weird part.

**Comment by jquense** [comment]
Do you have any `resolve` settings in your webpack config?

**Comment by vladp** [comment]
@jquense , may be below difference might help to figure out what's wrong:

**While using beta.9**
If I go to ./node_modules/unctrollable and view _requestedBy  entry in its package.json
it shows

```
  "_requiredBy": [
    "/react-bootstrap",
    "/react-overlays"
  ],

```

When using beta.10, however
If I go to ./node_modules/unctrollable and view _requestedBy  entry in its package.json
it shows
```
  "_requiredBy": [
    "/react-bootstrap",
  ],


So for some reason, NPM dependency analysis is thinking uncontrollable is just required by react-bootstrap, and *not* by react-overlay.
Which is why NPM is only downloading uncontrollable 7.x version, and not, additionally its previous version.
Which is, then, probably why, webpack is just bundling the 7.x of uncontrollable module to the usage of react-overlays.. and therefore the error.

**Comment by amitava82** [comment]
I've started getting this error after updating to beta 10. I'm using CRA 2x. Tried nuking node_modules and yarn.lock
```
./node_modules/react-bootstrap/es/Carousel.js
Attempted import error: 'uncontrollable' does not contain a default export (imported as 'uncontrollable').
```

**Comment by amitava82** [comment]
Seems to work after updating Yarn to latest.

**Comment by popa-marius** [comment]
> Do you have any `resolve` settings in your webpack config?

Great question @jquense . That helped me solve the problem.

In short, the previous devs thought it was a good idea to have this in the resolve:
```js
resolve: {
  // ...
  modules: [path.resolve(__dirname, 'node_modules'), 'src'],
}
```
Which pretty much forces a flat level dependency system because it's [an absolute path](https://webpack.js.org/configuration/resolve/#resolvemodules) to the `node_modules` folder. Changing it to a relative folder fixed it for me:
```js
resolve: {
  // ...
  modules: ['src', 'node_modules'],
}
```
Thanks again for the help.

**Comment by vladp** [comment]
@jquense  is right, I have same problem as @popa-marius .
I have webpack resolve to use absolute path, not relative.
However, this is not something we can change.
Our project shares a number of subdirs between web and react-native.
And if we do not tell webpack to use absolute path, it will pull node_modules from the react-native
project, when accessing the files in those shared folders.

I checked beta11, and still same situation.
so I assume we are going have to stay at beta9.

**Comment by GTXPRO** [comment]
I have the same error @vladp 
I fixed the error:
Go to folder project:
`node_modules/react-overlays/Dropdown.js`
on line 16:
`var _uncontrollable = _interopRequireDefault(require("uncontrollable"));`
change to
`var _uncontrollable = _interopRequireDefault(require("uncontrollable").uncontrollable);`

**Comment by vladp** [comment]
I was able to solve the problem I originally reported,
by simply including 
`uncontrollabe: '^6.2'`
I did not need to change how I resolve node_modules (I am using absolute path):
`modules: [fs.realpathSync('./node_modules')]`

I am not really sure why it worked.. but there it is.

**Comment by popa-marius** [comment]
@vladp If you didn't change the resolve, then that might mean you are using the 6.2 version in all the modules. Which might mean that when using something that requires uncontrollable 7 your code might break. Be careful with that solution.

**Comment by ScottyCompton** [comment]
@GTXPRO  so I used your fix and it worked like a charm.  Only problem is, I'm deplolyng my app on Heroku and so it's of course using whatever version I've indicated in package.json (the latest one) so when I deploy, it crashes.  Is there some way to deploy my updated version when Heroku does it's build, instead of what's found out in the latest production release?
