### ISSUE TITLE
TypeError on loading react-bootstrap

### ISSUE THREAD

**Issue by alust** [react-bootstrap/react-bootstrap#4139]
Hi!

Following recommendations in [react-bootstrap introduction](https://react-bootstrap.github.io/getting-started/introduction#browser-globals) I wrote a test html file that is supposed to create a sample react-bootstrap component. However when opening the file in a browser nothing is created and this error is shown in the console
* Firefox - **TypeError: document.body is null  react-bootstrap.min.js:12:3296**
* Chrome - **react-bootstrap.min.js:12 Uncaught TypeError: Cannot read property 'appendChild' of null**

The test file is as follows:
```html
<html lang="en">
 <head>
  <meta charset="utf-8">
  <title>
   test
  </title>
  <script src="https://unpkg.com/react/umd/react.production.min.js" crossorigin>
  </script>
  <script src="https://unpkg.com/react-dom/umd/react-dom.production.min.js" crossorigin>
  </script>
   <script src="https://unpkg.com/react-bootstrap@next/dist/react-bootstrap.min.js" crossorigin>
  </script>
 </head>
 <body>
  <div id="nav"></div>
  <script type="text/babel">
   var Nav = ReactBootstrap.Nav;
   alert('Nav created');
  </script>
 </body>
</html>
```

**Comment by bpas247** [comment]
Could you reproduce this issue in a CodeSandbox repo?

**Comment by alust** [comment]
Pardon my ignorance, I'm new to react. What is CodeSandbox repo?

**Comment by nortonwong** [comment]
Modal.js indirectly calls a DOM helper:
```javascript
// react-bootstrap/Modal
const defaultProps = {
//...
  manager: new BootstrapModalManager(),
};
```

```javascript
// react-overlays/ModalManager
import getScrollbarSize from 'dom-helpers/util/scrollbarSize';
class ModalManager {
  constructor({
//...
    this.scrollbarSize = getScrollbarSize();
  }
```

```javascript
// dom-helpers/util/scrollbarSize
export default function scrollbarSize(recalc) {
//...
      document.body.appendChild(scrollDiv);
```
If react-bootstrap is loaded in the head, the body is null. The easiest workaround is to move the react-bootstrap `<script />` into the body.

**Comment by bpas247** [comment]
> Pardon my ignorance, I'm new to react. What is CodeSandbox repo?

Just a way to setup a live online repository so others don’t have to setup your repository locally.
https://codesandbox.io/

**Comment by alust** [comment]
@nortonwong , the workaround seems to work, thanks!
