### ISSUE TITLE
pullRight doesn't work on Dropdown? 

### ISSUE THREAD

**Issue by schainker** [react-bootstrap/react-bootstrap#414]
On the components site the `SplitButton` with `pullRight` prop does not show an element pulled to the right.  Trying a `DropdownButton` or `SplitButton` with `pullRight` prop also does not look like it works.  

I'm pretty new to react-bootstrap, is there a good example of using pullRight that works?

**Comment by mtscout6** [comment]
The `pullRight` prop there refers to the drop down context menu. It says that the context menu should align to the right of the pull down button.

With `pullRight`:

![](http://f.cl.ly/items/1G1Q1K0i2Z0S0y1R2I42/Image%202015-02-27%20at%207.46.19%20AM.png)

Without `pullRight`, or default behavior is align to the left of the button:

![](http://cl.ly/image/3a0u1b2U3g0N/Image%202015-02-27%20at%207.48.00%20AM.png)

**Comment by schainker** [comment]
Oh now I see it, totally misunderstood the docs. Thanks Matt. I just want
to align the whole drop down menu on the far right side of the page. Not
the same thing! :D
