### ISSUE TITLE
Add a modifier to Accordion.Toggle to easily say if Accordion.Collapse is collapsed

### ISSUE THREAD

**Issue by Simpleqode** [react-bootstrap/react-bootstrap#4140]
First of all, thank you so much for such a wonderful library. Makes converting Bootstrap to React a breeze. I have an accordion with _many_ collapsible items in there. I need to style the Accordion.Toggle component depending on if it's Accordion.Collapse pair is collapsed or not. I know I can listen to a click event and update the state (though I don't want to have a state for every Accordion.Toggle & Collapse pair), but how do I know if it was collapsed from the very beginning (i.e. with `defaultActiveKey`)? Thanks in advance!

**Comment by taion** [comment]
How do you envision the API working here for `<Accordion.Toggle>` to inform you of this?

**Comment by Simpleqode** [comment]
Maybe use `aria` attributes as Bootstrap does for it's togglers?

пн, 29 июл. 2019 г., 23:20 Jimmy Jia <notifications@github.com>:

**Comment by bpas247** [comment]
> Maybe use `aria` attributes as Bootstrap does for its togglers? So we could then use `[aria-expanded="true"] { ... }`

I'm not sure if accessing DOM nodes imperatively like that is a good practice to begin with.

> but how do I know if it was collapsed from the very beginning (i.e. with defaultActiveKey)? 

IMO this is something you can infer with the current API. For example, if you don't pass in a `defaultActiveKey` (or `defaultActiveKey` that doesn't match any `Accordion.Toggle`'s `activeKey`s), then the Accordion will start out [fully collapsed](https://react-bootstrap.github.io/components/accordion/#fully-collapsed-state) from the very beginning.

**Comment by Simpleqode** [comment]
Sorry, I don't understand what you mean. I do pass defaultActiveKey to collapase the Accordion.Collapse that I need (I am working on a non-standard navigation and I need to only expand the collapsible menu that I need). Also I am keen to know what's wrong with styling elements using aria attributes. I am 100% confident this is not going to slow down the rendering if I use it here and there.

**Comment by bpas247** [comment]
> Sorry, I don't understand what you mean.

Well I linked to the example docs that shows how to start the Accordion in a fully-collapsed state, but you could also just pass in an `activeKey` that doesn't match any of the togglers to achieve the same effect.

> Also I am keen to know what's wrong with styling elements using aria attributes. 

There isn't anything wrong with that? I'm not sure where you got that impression from my response, which wasn't about styling at all. My original response was that *accessing the DOM elements imperatively* via their aria attributes is not really a good practice.

So going back to your original use case...
> I need to style the Accordion.Toggle component depending on if it's Accordion.Collapse pair is collapsed or not.

I feel like we could add a new hook to be able to access the current active key, like so:
```js
const currentActiveKey = useAccordionEventKey();
```

Which would make styling the `Accordion.Toggle` component based on if its `Accordion.Collapse` pair is active fairly straightforward:
```jsx
function CustomAccordionToggle(props) {
  const currentActiveKey = useAccordionEventKey();
  return <Accordion.Toggle className={eventKey === currentActiveKey ? 'active' : ''} {...props} />;  
}
```

**Comment by taion** [comment]
We could let the toggle support a functional child, maybe. But, yeah, I don't think that `<CustomAccordionToggle>` is too bad.

**Comment by nbjorling** [comment]
Have anyone found a solution or maybe a workaround? 

I would like to be able to toggle a css class on the accordion header when a accordion is open/closed so I can flip the arrow on the right hand of the text.

<img width="406" alt="Screenshot 2019-12-02 at 15 01 45" src="https://user-images.githubusercontent.com/31563031/69968058-ef37d200-1519-11ea-9a1e-149270f4d947.png">

**Comment by timtucker-dte** [comment]
Have half a workaround, but it seems to break the animations:

Define with the elements backwards:
`
<Accordion className="faq-accordion">
  <Card>
    <Accordion.Collapse eventKey="1" className="faq-answer"><Card.Body>Answer 1</Card.Body></Accordion.Collapse>
    <Accordion.Toggle as={Card.Header} eventKey="1" className="faq-question">Question 1</Accordion.Toggle>
  </Card>
  <Card>
    <Accordion.Collapse eventKey="2" className="faq-answer"><Card.Body>Answer 2</Card.Body></Accordion.Collapse>
    <Accordion.Toggle as={Card.Header} eventKey="2" className="faq-question">Question 2</Accordion.Toggle>
  </Card>
</Accordion>
`

Use flex layout in CSS to reorder them -- since the card body is defined first, we can use an adjacent sibling selector on the card body to style it:
`
.faq-accordion .card {
  display: flex;
  flex-wrap: wrap;
}

.faq-question {
  width: 100%;
  flex-basis: 100%;
  order: 1;
}

.faq-answer {
  width: 100%;
  flex-basis: 100%;
  order: 2;
}

.faq-answer.show + .faq-question {
  background-color: #000000;
  color: #FFFFFF;
}
`

**Comment by diceler** [comment]
I found a workaround for you that might satisfy your need.

You need to create [custom toggle](https://react-bootstrap.github.io/components/accordion/#custom-toggle) and in it make use of Reacts `useContext` using `AccordionContext` in order to get the currently active `eventKey`.

Example:

```js-jsx
import React, {useContext} from 'react';
import AccordionContext from 'react-bootstrap/AccordionContext';
import {useAccordionToggle} from 'react-bootstrap/AccordionToggle';
import classNames from 'classnames';

function MyCustomToggle({eventKey, callback}) {
  const currentEventKey = useContext(AccordionContext); // <-- Will update every time the eventKey changes.
  const toggleOnClick = useAccordionToggle(eventKey, () => {
    callback(eventKey);
  });
  const isCurrentEventKey = currentEventKey === eventKey;

  return (
    <button
      type="button"
      className={classNames('myDefaultStyling', {'myCollapsedStyling': isCurrentEventKey})}
      onClick={toggleOnClick}
    >
      {isCurrentEventKey ? 'Collapse me' : 'Expand me'}
    </button>
  );
}
```

You can use `useContext(AccordionContext);` in this case because `useAccordionToggle` hooks the component onto the context `AccordionToggle` belongs to.

Hope this helps.

**Comment by tai-flywire** [comment]
> I found a workaround for you that might satisfy your need.

Thanks so much for this, @diceler , it works great and isn't hacky at all

**Comment by shabith** [comment]
Thanks @diceler for your solution.

I think this need to go in the doc as well. What do you think @taion

**Comment by taion** [comment]
We'd be happy to take a PR adding an example here.

**Comment by nbjorling** [comment]
> I found a workaround for you that might satisfy your need.

Very much appreciated @diceler. I will try this in the future.

**Comment by bpas247** [comment]
Update on my [previous proposal](https://github.com/react-bootstrap/react-bootstrap/issues/4140#issuecomment-516221675):

I've given this some time to think about it and I feel like adding a custom hook like this isn't going to do anything special for us. What I mean by this is that the implementation of such custom hook would end up looking like this
```js
export function useAccordionEventKey() {
  return useContext(AccordionContext);
}
```
Besides consuming the Accordion context, it's not doing _anything_ else. I feel like this abstraction isn't a helpful enough abstraction for us to officially support as a part of our API, and we should just leave it up to our end users to implement (as shown in @diceler's [example](https://github.com/react-bootstrap/react-bootstrap/issues/4140#issuecomment-604130679)).

With that said, the only actionable item I can think of that's left for this issue is to add this as a recipe to our Accordion docs with an example usage.

**Comment by taion** [comment]
sounds good to me

**Comment by softerboy** [comment]
> I found a workaround for you that might satisfy your need.
That was an acceptable answer! Thanks @diceler

**Comment by RickeyWard** [comment]
https://github.com/react-bootstrap/react-bootstrap/pull/5171

I added an example to the docs based on Diceler's example so more people can find this without having to dig for it. I was trying to solve this problem myself and short of using using render props or introducing multiple context based components this seems like the best solution. Wanted to help out by getting it into the docs.

**Comment by ajoslin103** [comment]
I found this to be much more simple to comprehend

```
function CustomToggle({ children }) {
  const currentEventKey = useContext(AccordionContext);
  const accordionIsExpanded = currentEventKey > 0;
  // console.debug('currentEventKey', currentEventKey);
  return (
    <div>
      {children}
      <FontAwesomeIcon
        icon={accordionIsExpanded ? 'angle-down' : 'angle-right'}
      />
      <ClickForMore> (click for more...)</ClickForMore>
    </div>
  );
}

CustomToggle.propTypes = {
  children: PropTypes.object,
};
```

```
    <Accordion>
      <Card className="my-3">
        <Card.Header>
          <Accordion.Toggle as={Card.Header} eventKey={1}>
            <CustomToggle eventKey={0}>
              <LeftJustify>{firstTraining.theModule.name}</LeftJustify>
            </CustomToggle>
          </Accordion.Toggle>
        </Card.Header>
        <Accordion.Collapse eventKey={1}>
          <Card.Body>
            <Card.Text>{firstTraining.theModule.description}</Card.Text>
          </Card.Body>
        </Accordion.Collapse>
        <Card.Footer className="text-muted">{Registrations}</Card.Footer>
      </Card>
    </Accordion>
```

**Comment by RickeyWard** [comment]
> I found this to be much more simple to comprehend
You're requiring an additional library in the example (font awesome), as well as using a number and number comparison for the event key, which is usually used as a string. Also your example would not correctly verify which of many toggles were open if there were more than one. it only happens to work out because there is one. Accordions support many sections, sort of like tabs.

A simple example has already been merged.

**Comment by ajoslin103** [comment]
Thanks, I wasn't aware of non-numeric eventKeys -- my example is working fine for me in a list of 30 accordions -- just my luck !!  

I was only adding my usage for illustration purposes -- the thing I noticed was that the useContext(AccordionContext) was undefined at first and then alternated between null and the eventKey value

It's back to the docs for me...

**Comment by RickeyWard** [comment]
> Thanks, I wasn't aware of non-numeric eventKeys -- my example is working fine for me in a list of 30 accordions -- just my luck !!
> 
> I was only adding my usage for illustration purposes -- the thing I noticed was that the useContext(AccordionContext) was undefined at first and then alternated between null and the eventKey value
> 
> It's back to the docs for me...

the docs show the eventkey as a number for accordion most likely because the contrived examples have no meaning, **BUT** props are passed using the `eventKey="0"` syntax so javascript treats it like a string. if it was truly be number type it would be `eventKey={0}` as you have done in your example (this is counter to the docs).

```` const currentEventKey = useContext(AccordionContext);
const accordionIsExpanded = currentEventKey > 0;```

I can't imagine this above could be specific to a particular toggle because you use nothing that defines which toggle should match. You're getting the `currentEventKey` of the accordion stack and comparing it to an arbitrary value. in this case `0`. which doesn't define which toggle should match. This same code runs for every toggle so the comparison must include some unique information, such as the `eventKey` associated with the toggle. This is why want you will see in my example (really diceler's example) is `const isCurrentEventKey = currentEventKey === eventKey;` Type here doesn't matter, use a number or a string and you'll still be sure that this specific toggle is associated with the active expanded accordion. (note a feature of the bootstrap accordion is that only one section can be expanded at a time)

**Comment by ajoslin103** [comment]
ah, since my usage is one accordion per card, with many accordions in a list -- rather than many cards in one accordion -- I am able to open as many as I want, and why I couldn't get the event key tow work across cards.

thanks!  always learning !!

**Comment by AndrewSouthpaw** [comment]
@RickeyWard Thanks for the addition to the docs, though I don't seem to find it [on the website](https://react-bootstrap.github.io/components/accordion/) right now... Where should I be looking?

**Comment by RickeyWard** [comment]
I believe the website reflects the current release on npm, you can view the new docs by checking out master and running the docs locally.

**Comment by realLadybug** [comment]
Thank you so much @diceler for the solution and @RickeyWard for adding it to the docs. I would like to suggest a small change to  the documentation: Remove all occurrences of callback and children. It is a very nice way to make a customizable component but it seems like adding a callback and child components to the example in the docs is a level of abstraction, that is not needed there and makes it harder to understand.

`function ContextAwareToggle( eventKey ) {
  const currentEventKey = useContext(AccordionContext);
  const decoratedOnClick = useAccordionToggle( eventKey );
  const isCurrentEventKey = currentEventKey === eventKey;

  return (
    <button
      type="button"
      style={{ backgroundColor: isCurrentEventKey ? 'pink' : 'lavender' }}
      onClick={decoratedOnClick}
    >
    </button>
  );
}`

**Comment by RickeyWard** [comment]
@realLadybug in your example removing `children` leaves you with an empty button. Making the custom toggle not dynamic is not a very helpful example. The entire component save the formatting is 10 lines so Simplifying it further might make it harder for some people to see the big picture.

I wager that most people would prefer a complete example they can rip stuff out of until they break it, than a narrow example they have to figure out how to build up into something useful.

**Comment by bpas247** [comment]
I'm going to go ahead and close this issue for now 🙂 as it looks like there's already an acceptable [answer](https://github.com/react-bootstrap/react-bootstrap/issues/4140#issuecomment-604130679) for this issue.

**Comment by waasifkhaan** [comment]
I'm new to react. what is accordian context here? when i try to import it, react complains that it cannot find the module.

**Comment by kevinvugts** [comment]
> I found a workaround for you that might satisfy your need.
> 
> You need to create [custom toggle](https://react-bootstrap.github.io/components/accordion/#custom-toggle) and in it make use of Reacts `useContext` using `AccordionContext` in order to get the currently active `eventKey`.
> 
> Example:
> 
> ```
> import React, {useContext} from 'react';
> import AccordionContext from 'react-bootstrap/AccordionContext';
> import {useAccordionToggle} from 'react-bootstrap/AccordionToggle';
> import classNames from 'classnames';
> 
> function MyCustomToggle({eventKey, callback}) {
>   const currentEventKey = useContext(AccordionContext); // <-- Will update every time the eventKey changes.
>   const toggleOnClick = useAccordionToggle(eventKey, () => {
>     callback(eventKey);
>   });
>   const isCurrentEventKey = currentEventKey === eventKey;
> 
>   return (
>     <button
>       type="button"
>       className={classNames('myDefaultStyling', {'myCollapsedStyling': isCurrentEventKey})}
>       onClick={toggleOnClick}
>     >
>       {isCurrentEventKey ? 'Collapse me' : 'Expand me'}
>     </button>
>   );
> }
> ```
> 
> You can use `useContext(AccordionContext);` in this case because `useAccordionToggle` hooks the component onto the context `AccordionToggle` belongs to.
> 
> Hope this helps.

Hey @diceler,

I tried to implemented this example in my app but it keeps saying that callback is undefined. I don't receive a callback property in my custom component. I am on the latest versions of bootstrap (4.5.0) and react-bootstrap (1.2.2) What could possibly go wrong?

**Comment by RickeyWard** [comment]
> I'm new to react. what is AccordionContext here? when i try to import it, react complains that it cannot find the module.

import AccordionContext from 'react-bootstrap/AccordionContext';

**Comment by charkour** [comment]
> I'm new to react. what is AccordionContext here? when i try to import it, react complains that it cannot find the module.

I had the same issue. Upgrading the npm package from 1.0.1 to 1.2.2 solved the error for me. @waasifkhaan 
Hope this helps.

**Comment by tlarsonlgdor** [comment]
Thanks for the function. However, in the react-bootstrap documentation, could you please list the imports. There is no way of knowing where they come from without seeing this github page.

**Comment by vivekkupadhyay** [comment]
> className="faq-answer

This. 
I love simple solutions like this.

**Comment by vinu-mp** [comment]
In case someone is stuck with the imports -> AccordionContext, useAccordionToggle

`import React, { useContext } from 'react';
import AccordionContext from 'react-bootstrap/AccordionContext';
import { useAccordionToggle } from 'react-bootstrap/AccordionToggle';

const CustomAccordionToggle = ({ children, eventKey, callback, activeClass}) => {
  const activeEventKey = useContext(AccordionContext);

  const decoratedOnClick = useAccordionToggle(
    eventKey,
    () => callback && callback(eventKey)
  );

  const isCurrentEventKey = activeEventKey === eventKey;

  return (
    <h6
      className={`${isCurrentEventKey ? activeClass : ''}`}
      onClick={decoratedOnClick}
    >
      {children}
    </h6>
  );
};

export default CustomAccordionToggle;`

**Usage**
<CustomAccordionToggle eventKey="title1" activeClass={active}>Title 1</CustomAccordionToggle>
