### ISSUE TITLE
NavDropdown overflowing the screen

### ISSUE THREAD

**Issue by andraantariksa** [react-bootstrap/react-bootstrap#4149]
```
<header style={{ marginBottom: 50, }}>
          <Navbar collapseOnSelect expand="lg" bg="dark" variant="dark">
            <Navbar.Brand>
              <Link to="/" className="navbar-brand">
              {' SEA Pay'}
              </Link>
            </Navbar.Brand>

            <Navbar.Toggle aria-controls="responsive-navbar-nav" />
            <Navbar.Collapse id="responsive-navbar-nav">

              <Nav style={this.showIfLogin(true)} className="ml-auto">
                <NavLink to="/signin" className="nav-link">Signin</NavLink>
                <NavLink to="/signup" className="nav-link">Signup</NavLink>
              </Nav>

              <Nav style={this.showIfLogin(false)} className="ml-auto">
              <NavLink to="/HomeUser" className="nav-link">HomeUser</NavLink>
              <NavLink to="/logout" className="nav-link">Logout</NavLink>
              <NavDropdown title="Dropdown" id="basic-nav-dropdown">
                <NavDropdown.Item href="#action/3.1">Action</NavDropdown.Item>
                <NavDropdown.Item href="#action/3.2">Another action</NavDropdown.Item>
                <NavDropdown.Item href="#action/3.3">Something</NavDropdown.Item>
                <NavDropdown.Divider />
                <NavDropdown.Item href="#action/3.4">Separated link</NavDropdown.Item>
              </NavDropdown>
              </Nav>

            </Navbar.Collapse>
          </Navbar>
        </header>
```

![Overflowing dropdow](http://i.epvpimg.com/Va0Fgab.png)

Is there any way to not making the navdropdown overflowing the screen? Like pulling the items to the left

**Comment by andraantariksa** [comment]
I have solve this issue but I don't know if this the best solution or not

Here's my solution

```
.dropdown-menu {
    right: 0;
    left: auto;
}
```

**Comment by taion** [comment]
see https://react-bootstrap.github.io/components/dropdowns/#menu-alignment, or the `flip` prop

**Comment by harish444** [comment]
> see https://react-bootstrap.github.io/components/dropdowns/#menu-alignment, or the `flip` prop

best answer lots of thanku @taion

**Comment by thokchomrs** [comment]
![rrrrrrrrr](https://user-images.githubusercontent.com/61892955/80646205-ee37ac00-8a89-11ea-8f61-44e90a5e5039.PNG)

github.com/thokchomrs/dropdown-overlap and thokchomrs.github.io/dropdown-overlap  i used position: fixed !important; to the item and work but unfortunatly dropmenu is overlapping with others. And if we remove the sticky feature of top heather bar then everything runs well.

**Comment by chwahajahmad** [comment]
<NavDropdown
            alignRight
            title="Services"
            id="basic-nav-dropdown"
       flip
  >
This will work

**Comment by KanagaDavid** [comment]
Add **alignRight** that will do the work.

`<NavDropdown alignRight>`

**Comment by AleOjeda** [comment]
> <NavDropdown alignRight title="Services" id="basic-nav-dropdown" flip
> 
> > 
> 
> This will work

This works!

**Comment by bbawj** [comment]
<NavDropdown
align="end"
title="Services"
id="basic-nav-dropdown"
flip
>

**Comment by saiffardin** [comment]
> .dropdown-menu {
>     right: 0;
>     left: auto;
> }

worked !! thanks man
