### ISSUE TITLE
FormProps missing attributes

### ISSUE THREAD

**Issue by anddero** [react-bootstrap/react-bootstrap#4150]
Interface `FormProps` in `Form.d.ts` missing important attributes, making extended interfaces broken.

For example, if I make a new form with new props:

```ts
export interface MyFormProps extends FormProps {
    onSubmit(): void;
}
```

I wouldn't be able to use it like this:

```tsx
export default function MyForm({onSubmit, ...formProps}: MyFormProps) {
    return (
        <Form validated={true} onSubmit={e => onSubmit()} {...formProps} />
    );
}
```

Because using my new `MyForm`, I cannot provide children elements to it, or `autoComplete="off'"` or other props which we would expect to be inherited from react-bootstrap's `FormProps`.

**Comment by anddero** [comment]
v1.0.0-beta.10

**Comment by taion** [comment]
The props don't quite work that way, nor should they exactly. Note that `<Form>` itself is templated on the type of the element used for `as`. The relevant props strictly depend on the value of that prop and don't exist in a vacuum like that.
