### ISSUE TITLE
Using react-router <Link> inside <Pagination.Item> or <PageItem>

### ISSUE THREAD

**Issue by cklll** [react-bootstrap/react-bootstrap#4157]
I tried to do this 
```jsx
<Pagination.Item>
  <Link to={url} />
</Pagination.Item>
```
and got
```
Warning: validateDOMNesting(...): <a> cannot appear as a descendant of <a>.
```

Looking at the source code, I cannot change the default HTML tag created by `PageItem`.
https://github.com/react-bootstrap/react-bootstrap/blob/15bfdb09e7aed173cde7bd45e0334e890e67a8fd/src/PageItem.js#L34

Is there a suggested approach to use both of them?

**Comment by taion** [comment]
Use react-router-bootstrap.

**Comment by byers174** [comment]
<Pagination.Item as={Link} to={'/digital/page=1'}>{1}</Pagination.Item>

Would this work?

**Comment by taion** [comment]
possibly not – i think our code will pick it up as a link-less thing

use react-router-bootstrap to do this

**Comment by magnustymoteus** [comment]
Still no solution to this...

**Comment by Stoikiy** [comment]
Im came up with this one.
I Keep developing further not sure that hack will work

` 
 const navigate = useNavigate();

 const goToPage = (pageNumber) => {
    navigate(`/${pageNumber}`)
  }
  
<Pagination.Item onClick={() => goToPage(1)}>
              {1}
 </Pagination.Item>
 `

**Comment by Stoikiy** [comment]
Im came up with this one.
I Keep developing further not sure that hack will work

```js
const navigate = useNavigate();

const goToPage = (pageNumber) => {
    navigate(`/${pageNumber}`)
 }
  
<Pagination.Item onClick={() => goToPage(1)}>
              {1}
</Pagination.Item>
 ```

**Comment by dduehr** [comment]
I wonder why there are currently 4 down votes for taion's suggestion to use react-router-bootstrap?
At least it works for me with react-router-dom 6.17, react-bootstrap 2.9 and react-router-bootstrap 0.26:

```jsx
<Pagination>
  <LinkContainer to="foo">
    <Pagination.Item>Foo</Pagination.Item>
  </LinkContainer>
</Pagination>
```
