### ISSUE TITLE
Nav used for tabs cannot contain NavItem abstractions

### ISSUE THREAD

**Issue by sandorr** [react-bootstrap/react-bootstrap#4158]
## Describe the bug

`Nav` used for tabs cannot contain a custom component which directly returns a `NavItem`.

## To Reproduce

1. Create a component which returns a `NavItem`
2. Use it inside a `Nav` inside a `Tab.Container`
3. See error that the tab is not functional

## Reproducible Example

Minimal example by using [CodeSandbox](https://codesandbox.io/s/code-sandbox-examples-sh557).

## Expected behavior

Tab does not get rendered as a button.

## Environment

- Operating System: macOS Mojave, Windows 10
- Browser, Version Chrome 75
- React-Bootstrap Version 0.32.4

## Additional context

I am trying to avoid redundancy with introducing abstract components which can be reused, since I am generating all sort of tabs (even dropdowns) based on an HTTP response.

**Comment by sandorr** [comment]
I did some research and it seems that props get lost during rendering, since if you put a break point into the render method of `Nav`, you can see that the custom item was successfully found as the active item, but that information will not be available/will be different down in the hierarchy.

**Comment by kyletsang** [comment]
Closing since bs3 is no longer supported
