### ISSUE TITLE
New release for Popover types

### ISSUE THREAD

**Issue by melanahammel** [react-bootstrap/react-bootstrap#4159]
I am working on implementing Popovers in my project. [Examples](https://react-bootstrap.github.io/components/overlays/#popovers) from the react-bootstrap docs use Popover.Title and Popover.Content. 

Types were recently [committed to master](https://github.com/react-bootstrap/react-bootstrap/commit/5c0895d955b40f1d1656e1e772bc767617860a1c) for Popover.Title, PopoverTitle, Popover.Content and PopoverContent.. However, the current release, v1.0.0-beta.10, does not include this commit.

Currently as a workaround, I am relying on the [old Popover type definition](https://github.com/react-bootstrap/react-bootstrap/blob/v1.0.0-beta.10/types/components/Popover.d.ts). What is the timeline for next release so I can use these types?

**Comment by bpas247** [comment]
> What is the timeline for next release so I can use these types?

FWIW we do not typically have a set timeline for releases 🙂

**Comment by melanahammel** [comment]
Is there a possibility to release a patch with the updated TypeScript definitions as the ones needed for the code in the release are not in release, but are in master?

**Comment by taion** [comment]
released beta 13
