### ISSUE TITLE
Always collapsed navbar

### ISSUE THREAD

**Issue by rafalkrupinski** [react-bootstrap/react-bootstrap#4174]
Hi,

Upstream bootstrap supports having a navbar that is always collapsed.
[Example](https://www.codeply.com/go/dvCH985QU0/bootstrap-4-navbar-always-collapsed)

Right now reac-bootstrap navbar only either always expands or expands if the browser window is particular size (xs...xl)

I didn't find a way to make react-bootstrap behave like the upstream in the example linked above.

Could you add support for expand={false} please.

Cheers

**Comment by jquense** [comment]
Expand false or expand null should already work I think. Might need to expand the proptypes

**Comment by rafalkrupinski** [comment]
You're right. I forgot to mention that I'm using typescript. The Navbar expand definition allows neither null nor false, but I've changed it locally and my code works! 

Please don't close this issue yet. I'll send a PR for the type definition adding false value.

**Comment by nakedtoast** [comment]
This should be in the documentation of Navbar, but it isn't (yet). Could you please add a sentence about the expand={false} and what it will be the effect, because I was looking for this feature and the only way to find out it is already implemented was to look into the source code.

**Comment by cmdr-rohit-bang** [comment]
> Expand false or expand null should already work I think. Might need to expand the proptypes

Awesome!! it worked 👍🏻
