### ISSUE TITLE
Add an option to disable “bg” and “variant” class for a navbar 

### ISSUE THREAD

**Issue by NishidaRyu416** [react-bootstrap/react-bootstrap#4187]
## Is your feature request related to a problem? Please describe

When we want to change the background colour of a navbar, we cannot usually achieve it although following the instructions written on the document.

## Describe the solution you'd like
When I tried to put a plain nav tag giving some classes that make it a bootstrap navbar except bg and variant related classes, I could simply change the background colour.
This means we are bothered by those default classes. 
## Describe alternatives you've considered
Nothing
## Additional context
Nothing special

**Comment by taion** [comment]
Just pass in `null` for those props
