### ISSUE TITLE
<FormGroup/> vs <Form.Group/>

### ISSUE THREAD

**Issue by createthis** [react-bootstrap/react-bootstrap#4193]
Your docs are confusing. Is it `<FormGroup/>` or `<Form.Group/>` or both?

<img width="826" alt="Screen Shot 2019-08-06 at 1 44 21 PM" src="https://user-images.githubusercontent.com/1695880/62563273-a9f7e200-b850-11e9-8705-5f653d151a55.png">

**Comment by mxschmitt** [comment]
Actually it's the same: https://github.com/react-bootstrap/react-bootstrap/blob/0d02bf6d279d227f92703520b3e45727bfded3bf/src/Form.js#L80

**Comment by bpas247** [comment]
https://github.com/react-bootstrap/react-bootstrap/blob/f2566365fe0823568b2ee70515d823c05a9ef342/src/index.js#L25-L30
FWIW this is the same for all of the `Form` sub-components, so it's up to your preference if you want to use `<FormGroup />` or `<Form.Group />`.

A lot of our components are organized this way, which we could probably document in the [getting started](https://react-bootstrap.github.io/getting-started/introduction) section of our website.

**Comment by mxschmitt** [comment]
Closed due clarified by @bpas247. I think it's directly clear when some developers would take a look at the actual source code.

**Comment by mikebridge** [comment]
It would have saved me a lot of time debugging a non-issue if this had been documented on the Form page.  I inherited an older version of `react-bootstrap` and couldn't figure out whether the syntax differences were due to my version being deprecated or some other reason.

**Comment by jetamartin** [comment]
FWIW, As a new user to react-bootstrap, I also found this VERY confusing and in my opinion this should be clearly documented somewhere up front in react-bootstrap documentation...maybe I missed it????
