### ISSUE TITLE
Migrate remaining components to forward their refs properly

### ISSUE THREAD

**Issue by bpas247** [react-bootstrap/react-bootstrap#4194]
## Is your feature request related to a problem? Please describe
For examples on how to migrate these components, please read #4031, #4135, and #3992.
## A clear and concise description of what the problem is.
Currently, not all of our components properly forward the passed in `ref` prop to the underlying component. This leads to end-users not being able to access the underlying DOM node (#3923 and #4012).
## Describe the solution you'd like

Migrate the remaining class components to be ref forwarders. The components that need to be migrated are:
- [ ] [Modal](https://github.com/react-bootstrap/react-bootstrap/blob/0d02bf6d279d227f92703520b3e45727bfded3bf/src/Modal.js)
- [x] [DropdownToggle](https://github.com/react-bootstrap/react-bootstrap/blob/89693c7967594d4713149a17aca0993b45373cc0/src/DropdownToggle.js) (#4661)
- [x] [ToggleButton](https://github.com/react-bootstrap/react-bootstrap/blob/7bd64defe2d0390397fab6938cc84f1191bc80ec/src/ToggleButton.js) (#4640)
- [x] [NavDropdown](https://github.com/react-bootstrap/react-bootstrap/blob/04184495ce111d9e0a9d100cec8f8b8122015ccf/src/NavDropdown.js) (#4626)
- [x] [PageItem](https://github.com/react-bootstrap/react-bootstrap/blob/7e0f4c2579ce578c929042c3945a07e2f2e1971c/src/PageItem.js)
- [x] [ToggleButtonGroup](https://github.com/react-bootstrap/react-bootstrap/blob/8dff07dba3c1bccb39abf32192b00a9f8e846a7a/src/ToggleButtonGroup.js) (#4605)
- [x] [Pagination](https://github.com/react-bootstrap/react-bootstrap/blob/04184495ce111d9e0a9d100cec8f8b8122015ccf/src/Pagination.js) (#4593)
- [x] [AbstractNav](https://github.com/react-bootstrap/react-bootstrap/blob/438cdfcd7d6054d0197e97f760df5bc31e46b19c/src/AbstractNav.js) (#4031)
- [x] [ProgressBar](https://github.com/react-bootstrap/react-bootstrap/blob/8179e12692c7682888032b9f22c1bc063ef0a755/src/ProgressBar.js)
- [x] [ResponsiveEmbed](https://github.com/react-bootstrap/react-bootstrap/blob/8179e12692c7682888032b9f22c1bc063ef0a755/src/ResponsiveEmbed.js) (#4595)
- [x] [Navbar](https://github.com/react-bootstrap/react-bootstrap/blob/438cdfcd7d6054d0197e97f760df5bc31e46b19c/src/Navbar.js)
- [x] [Image](https://github.com/react-bootstrap/react-bootstrap/blob/04184495ce111d9e0a9d100cec8f8b8122015ccf/src/Image.js)
- [x] [TabContent](https://github.com/react-bootstrap/react-bootstrap/blob/0f275b9a564552f5e9decf16b7a74ba72ded8147/src/TabContent.js) (#4594)
- [x] [Table](https://github.com/react-bootstrap/react-bootstrap/blob/22e93163cf17cff8df27b30da8fc7a124295cec8/src/Table.js) (#4592)
## Describe alternatives you've considered
So currently we have two different approaches of handling forwarding refs; per-component or through a HOC called [createBootstrapComponent](https://github.com/react-bootstrap/react-bootstrap/blob/f2566365fe0823568b2ee70515d823c05a9ef342/src/ThemeProvider.js#L23-L38). I'm personally unsure about which approach to use for our codebase, but we should plan to choose one approach and stick with it for consistency. IMO we should handle this per-component, as using a HOC here might make the implementation of our codebase more complex than it's worth. This would involve migrating all of the components that use `createBootstrapComponent`, which some of them are included in the above list.

**Comment by hetpatel33** [comment]
Taking up `DropdownToggle`

**Comment by ankurkaushal** [comment]
Can I take on the `Carousel` component if it is still available?

**Comment by mxschmitt** [comment]
Yep @ankurkaushal! Thank you :)

**Comment by with-shrey** [comment]
@mxschmitt Any component remaining to be migrated ?

**Comment by taion** [comment]
I removed Collapse and OverlayTrigger from the list above; they shouldn't actually forward, given that they're wrapping containers.

**Comment by bpas247** [comment]
Should we even migrate the Modal component? It just seems like a very costly migration, and I'm not sure if there's a lot of value we can get out of it.

**Comment by taion** [comment]
hmm, arguably not... what would the ref even be to?

**Comment by bpas247** [comment]
> hmm, arguably not... what would the ref even be to?

Good question, I'm not sure if it would be a reference to anything useful.

I'm going to go ahead and cross that out from the list, which would mark this issue as complete 🎉 

Thank you to everyone who contributed their time for this major migration 😄 all of your continuing support is what makes this library as great as it is!
