### ISSUE TITLE
Navbar dropdowns in collapsed state

### ISSUE THREAD

**Issue by dptoot** [react-bootstrap/react-bootstrap#421]
I have a working dropdown but when navbar collapses the dropdown appears correctly in the toggle menu however it's child MenuItems are obscured.  Is there support for dropdowns in collapsed toggle menus?

**Comment by mtscout6** [comment]
I'm pretty sure this is a bug, it does not work on the updated docs page which showcases such a use case which does not work either.

**Comment by AlexKVal** [comment]
Superceded by #526
