### ISSUE TITLE
Nav assigns className to both <nav> and <ul>

### ISSUE THREAD

**Issue by ironblock** [react-bootstrap/react-bootstrap#422]
I noticed this after updating to 0.13.3, and it seems to still be present in 0.15.1. The spread attribute in Nav's `render()` and `renderUl()` methods both contain the same assignment for className: `React.__spread({},  this.props, {className: joinClasses(this.props.className, classSet(classes))`, which leads to a case where the rendered `<nav>` and `<ul>` elements both have the same classes.

I can work around it with CSS specificity, but I seem to recall that there are some other components that use different props for `className` in their sub-elements - should Nav be set up the same way?

```javascript
<TWBS.Nav stacked className = "app-sidebar primary-nav">
  // ...
</TWBS.Nav>
```

turns into:

![screen shot 2015-02-26 at 8 51 30 pm](https://cloud.githubusercontent.com/assets/5800173/6407645/52ecc170-bdf9-11e4-82f5-57fade74b664.png)

**Comment by mtscout6** [comment]
What if we didn't apply `this.props.className` to the inner `ul`? The direct child of `nav` will always be a `ul` so you will be free to setup CSS via `.some-class > ul`. 

On the flip side though I can see value in only applying a class directly to the ul alone. 

I wonder how well that would play with #362 or if that option would obliterate this ability. @AprilArcus what are your thoughts on this? I haven't played around with React styles enough to really know what's possible yet.

**Comment by ironblock** [comment]
Applying the class only to the `<nav>` would solve my use case pretty well, but I can't vouch for other developers. I feel almost certain that someone will have a use case that requires the ability to modify the `<ul>`'s class.

#362 has other challenges, as vjeux pointed out. Even with some kind of `cx()` syntax, I think there's still a problem of "How do I apply one set of styles to DOM element A, and another set to DOM element B?". As long as A and B are both rendered by the same wrapper component, and they both have to receive style information (inline, className, mixin, et al), wherever that wrapper is called.

So, this would be solvable (potentially) by having the `className` prop apply to the wrapping `<nav>`, and having a `ulClassName` prop that applies to the `<ul>`. I could have sworn that there was some other react-bootstrap component that worked this way - input groups, maybe? In any case, I don't think it does anything to address #362 specifically - that's a much harder problem to solve.

**Comment by zwippie** [comment]
Quite possibly related: I am experiencing this same issue with `className` but also with the `id` attribute set on a `Nav`. The `id` is assigned to both the rendered `nav` and `ul` elements. Version 0.19.1.

**Comment by mtscout6** [comment]
Not the exact same problem but similar since they both occur on the same lines.

https://github.com/react-bootstrap/react-bootstrap/blob/master/src/Nav.js#L54
https://github.com/react-bootstrap/react-bootstrap/blob/master/src/Nav.js#L70

Both those lines apply all the props and classnames to both elements. `id` would definitely occur here as well.

**Comment by web2style** [comment]
I vouch for the possibility to add classes to `<nav>` and `<ul>` individually.

**Comment by jonaskello** [comment]
+1 for adding classes to nav and ul individually. I need this to make the vertical-tabs plug-in to work, it requires the tabs-right class only set to the ul. https://github.com/dbtek/bootstrap-vertical-tabs

**Comment by AlexKVal** [comment]
Guys.. can you please check and comment #933 ?
What do you think about it ?
