### ISSUE TITLE
How do I properly extend React Bootstrap components?

### ISSUE THREAD

**Issue by Simpleqode** [react-bootstrap/react-bootstrap#4224]
Say I have a badge component I want to add sizing for. This is how I currently do it:

```
import React from 'react';
import Badge from 'react-bootstrap/Badge';
import classNames from 'classnames';

const BadgeExtended = props => {
  const {className, size, ...attr} = props;
  const classes = className(
    className,
    size && `badge-${size}`
  );

  return <Badge className={classes} {...attr}>{props.children}</Badge>;
};

export default BadgeExtended;
```
which works OK in most cases. Is that a correct way to do it? Is there a way to extend the original component so that I dind't have to import an extended one, using react-bootstrap/Badge instead?

**Comment by bpas247** [comment]
> Is that a correct way to do it? 
Seems good to me 👍
> Is there a way to extend the original component so that I dind't have to import an extended one, using react-bootstrap/Badge instead?
So you’d want to override a component in our package so that it would default to your component? That seems a bit hacky, and doesn’t seem like too much extra work to just use your own component with its relative import. 

If you think you’re planning on doing this for most of our components then what you could do is abstract our components completely to its own relative directory, such as `./bootstrap`, and then just export your own custom components instead of our components from that directory.

**Comment by Simpleqode** [comment]
@bpas247, thanks for a quick reply! I am working on porting a heavily customized Bootstrap theme to React, that's why I do plan to extend most of your components to add small additional features we have. Couple of addtional questions if you don't mind: 

1. As for the code above, does it make sense to use `forwardRef` to pass the ref down to the original component (similar to the way you do it)? 

2. Also I am a bit confused about how I can add the `as` tag to components that don't have it with this approach? I.e. your Badge component presumes it is always a `span` (it is in Bootstrap so you are 100% right). However, I sometimes use it as a link with its own href, and couldn't get my head around how to achieve this with the approach above without copy pasting and modifying your `rect-bootstrap/Badge` content.

**Comment by bpas247** [comment]
> As for the code above, does it make sense to use forwardRef to pass the ref down to the original component (similar to the way you do it)?

Yes, if you want the end-user of your component to be able to forward refs to the underlying component.

> Also I am a bit confused about how I can add the as tag to components that don't have it with this approach? I.e. your Badge component presumes it is always a span (it is in Bootstrap so you are 100% right). However, I sometimes use it as a link with its own href, and couldn't get my head around how to achieve this with the approach above without copy pasting and modifying your rect-bootstrap/Badge content.

For components that don't have an `as` prop, there isn't really a way to replicate that behavior without copy/pasting our implementation and modifying it from there. Might be worth opening specific issues for components that don't support that prop if it's a reasonable enough use case?

**Comment by Simpleqode** [comment]
Yup, that's what I thought. Thanks for your help!
