### ISSUE TITLE
Add factories like React.DOM

### ISSUE THREAD

**Issue by wmertens** [react-bootstrap/react-bootstrap#423]
For those who prefer plain coffeescript, having to individually create factories or elements is a bit of a pain. It would be nice if there were an equivalent of `React.DOM` so you could write

```coffeescript
React = require 'react'
N = null
B = require 'react-bootstrap/factories'

App = React.createClass
  render: ->
    B.Grid N,
      B.Row N,
        B.Col md:6,
          "Hi"
        B.Col md:6,
          "there"

React.render (React.createElement App), document.body
```

or even

```coffeescript
React = require 'react'
N = null
{Grid, Row, Col} = require 'react-bootstrap/factories'

App = React.createClass
  render: ->
    Grid N,
      Row N,
        Col md:6,
          "Hi"
        Col md:6,
          "there"

React.render (React.createElement App), document.body
```

**Comment by mtscout6** [comment]
Have you seen [coffee-react](https://github.com/jsdf/coffee-react)? Although not a direct port of what you are looking for it's close...

**Comment by mtscout6** [comment]
Perhaps I'm missing something, but doesn't React require you to use the namespace to `React.DOM` as well? Even then since React v0.12 you would have to wrap each DOM function with factories as well: http://facebook.github.io/react/blog/2014/10/28/react-v0.12.html

**Comment by wmertens** [comment]
@mtscout6 I really prefer not writing end tags and weird curly braces...
Yes, React.DOM provides factories, not elements. Check out http://codepen.io/anon/pen/PwRggP?editors=001 to play with a live example.

**Comment by wmertens** [comment]
Here's how React does it, basically call createFactory on all tags when the module is imported... https://github.com/facebook/react/blob/2aeb8a2a6beb00617a4217f7f8284924fa2ad819/src/browser/ReactDOM.js

**Comment by jquense** [comment]
exporting factories or elements is considered [bad practice](http://facebook.github.io/react/blog/2014/10/14/introducing-react-elements.html#anti-pattern-exporting-factories) in the React ecosystem. It would break the module for anyone using JSX witch as part of the compile step, wraps the Component in a `createElement()` (jsx doesn't use React.DOM). If you were going to do this it needs to be as a seperate export from the normal Component Types.

**Comment by wmertens** [comment]
Yes, I'm asking for e.g. 'bootstrap/factories' just like you can require
'react/addons'.

**Comment by tacomanator** [comment]
Working on getting this feature added to react-bootstrap in the pull request mentioned ... in the meantime I put up something temporary: https://github.com/tacomanator/react-bootstrap-factories.

**Comment by wmertens** [comment]
In the mean time, I no longer use factories. I simply do

```
E = React.createElement
B = Bootstrap
...
  E B.Button,
    bsStyle: "large"
    "Hi"
```

It's three more characters but it allows that trailing comma so the next
line can have comma-less attributes, and the code is the same as when jsx
preprocesses it.

So actually, for me this can be closed...

**Comment by AlexKVal** [comment]
Thank you for sharing your experience.
