### ISSUE TITLE
Dropdown.Item eventKey doesn't accept any types but string using typescript

### ISSUE THREAD

**Issue by Tora-Bora** [react-bootstrap/react-bootstrap#4239]
## Describe the bug

I'm migrating from 0.3 version to v1, and there are different types for object which pass to eventKey. After switching to the new version I've got compilation error:

>   TS2326: Types of property 'eventKey' are incompatible.
>   Type '***' is not assignable to type 'string'.

## To Reproduce

1. Using typescript create a DropdownItem whose eventKey is not a String type (e.x. any typed object)
2. Compile
3. See a compilation error

## Expected behavior

eventKey should be 'any' type instead of string

## Environment (please complete the following information)

- Operating System: [e.g. macOS]
- Browser, Version [e.g. Chrome 74]
- React-Bootstrap Version [e.g. 1.0.0-beta.11]

## Additional context

It seems there is an error in DropdownItem.d.ts : there is eventKey?: string; but should be eventKey?: any;

**Comment by taion** [comment]
With the current implementation on v1, it now must be a string.

**Comment by Tora-Bora** [comment]
But in [DropdownItem.js](https://github.com/react-bootstrap/react-bootstrap/blob/756fdc24cfc4662add9f711f618ac543f3848959/src/DropdownItem.js#L28) it's any

**Comment by taion** [comment]
That's a bug, then. It should be string only.

**Comment by Tora-Bora** [comment]
Could I ask the reason of the restriction? It's quite inconvenient. The bypass is to add process onClick for each Dropdown.Item to select something except string.

**Comment by taion** [comment]
These get written out as DOM properties, which can only be strings.
