### ISSUE TITLE
Navbar Uses componentWillMount Still

### ISSUE THREAD

**Issue by WretchedDade** [react-bootstrap/react-bootstrap#4240]
## Describe the bug
I was getting a warnings after setting up some unit tests in my project. After digging in it looks like the Navbar component still uses componentWillMount. It looks like other components are being updated to use the hook form of uncontrollable (useUncontrollable). Are there plans and/or a timeline for Navbar to be updated to no longer depend on the legacy versions of these lifecycle hooks? It's not a pressing issue, just a bit of an eyesore!

## Screenshots

![image](https://user-images.githubusercontent.com/17183431/62909104-43d7f700-bd49-11e9-9709-81c2fa3cf7ff.png)

![image](https://user-images.githubusercontent.com/17183431/62909294-f314ce00-bd49-11e9-98a3-aa7716e80143.png)

**Comment by mxschmitt** [comment]
@WretchedDade which version of react-bootstrap are you using?

**Comment by WretchedDade** [comment]
1.0.0-beta.11

**Comment by Noisycall** [comment]
## Warning received when using Navbar
### React - Bootstrap version 1.0.0-beta11 
### React - 16.9.0
Warning: componentWillMount has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.

* Move code with side effects to componentDidMount, and set initial state in the constructor.
* Rename componentWillMount to UNSAFE_componentWillMount to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: Uncontrolled(Navbar)

**Comment by dons20** [comment]
#4244 should fix this hopefully

**Comment by taion** [comment]
#4244 targets the v3 compat branch. We'd be happy to take a PR addressing v1, though.

That said these warnings are basically innocuous for now.

**Comment by cliffhall** [comment]
@taion Which branch do you need a PR for?
![Screen Shot 2019-08-14 at 3 52 53 PM](https://user-images.githubusercontent.com/871933/63051697-af39da00-beab-11e9-8b6f-c09dc1bdd191.png)

**Comment by taion** [comment]
master

**Comment by WretchedDade** [comment]
Woo! Thanks everyone!
