### ISSUE TITLE
Nav tag in Navbar still cause the browser to crash??

### ISSUE THREAD

**Issue by saher-elgendy** [react-bootstrap/react-bootstrap#4247]
I have opened that issue before but i do not know why it was closed without a solution, 

The problem is that i can not use React-Bootstrap <strong>Navbar</strong> properly as it causes the browser to crash, after testing code i could define the source of the problem , it was the <strong>Nav component</strong> and i have no idea why??

This is the Codesandbox example and it produces the same problem:

https://codesandbox.io/s/charming-architecture-pr0ky

**Comment by taion** [comment]
Your question was already answered in https://github.com/react-bootstrap/react-bootstrap/issues/4171#issuecomment-520948762. Please do not repost the same question here.
