### ISSUE TITLE
Popover support in beta.11

### ISSUE THREAD

**Issue by dgdosen** [react-bootstrap/react-bootstrap#4259]
I'm wanting to use popovers in a typescript app, and when I add support for react-bootstrap popovers, I don't get errors, and the popovers just don't work.  So -  a couple of questions:

- Are users required to build apps using hooks to leverage react-bootstrap Popovers/Tooltips?

- From the docs, and in examining my app's yarn.lock - I can see support for react-popper - but should that work with a typescript app?

- Am I missing something obvious?  It's strange that I'm not even seeing errors.

Thanks for any guidance!

**Comment by taion** [comment]
As far as we know they're fully functional: https://react-bootstrap.github.io/components/overlays/#popovers

**Comment by dgdosen** [comment]
Just making sure - is use of react hooks a requirement?

**Comment by taion** [comment]
You must use a version of React that supports hooks, as we use them internally.

The exposed API for popovers does not involve hooks, though.

**Comment by dgdosen** [comment]
thanks for clarifying.

**Comment by TravnikovRN** [comment]
> You must use a version of React that supports hooks, as we use them internally. 
> The exposed API for popovers does not involve hooks, though.

But on fact it doesn't work without hooks. I've tried to use old fashioned React.createRef () for
`` `<Overlay> <Popover>` `` combo, but in this case Popover placed in top left corner of window.
 After I rewrote component to stateless and 'useRef' hook - Popover immediately took a right place
