### ISSUE TITLE
Carousel indicators have span elements within ol

### ISSUE THREAD

**Issue by lo1tuma** [react-bootstrap/react-bootstrap#426]
Given from the example page from [react-bootstrap](http://react-bootstrap.github.io/components.html#carousels):

This code:
```jsx
var carouselInstance = (
    <Carousel>
      <CarouselItem>
        <img width={900} height={500} alt="900x500" src="/assets/carousel.png"/>
        <div className="carousel-caption">
          <h3>First slide label</h3>
          <p>Nulla vitae elit libero, a pharetra augue mollis interdum.</p>
        </div>
      </CarouselItem>
      <CarouselItem>
        <img width={900} height={500} alt="900x500" src="/assets/carousel.png"/>
        <div className="carousel-caption">
          <h3>Second slide label</h3>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
        </div>
      </CarouselItem>
      <CarouselItem>
        <img width={900} height={500} alt="900x500" src="/assets/carousel.png"/>
        <div className="carousel-caption">
          <h3>Third slide label</h3>
          <p>Praesent commodo cursus magna, vel scelerisque nisl consectetur.</p>
        </div>
      </CarouselItem>
    </Carousel>
  );

React.render(carouselInstance, mountNode);
```

results in the following rendered HTML for the carousel indicators:

```html
      <ol class="carousel-indicators" data-reactid=".26.0">
         <li data-reactid=".26.0.$0"></li>
         <span data-reactid=".26.0.1"> </span>
         <li data-reactid=".26.0.$1" class="active"></li>
         <span data-reactid=".26.0.3"> </span>
         <li data-reactid=".26.0.$2"></li>
         <span data-reactid=".26.0.5"> </span>
      </ol>
```

This is because of the [hack in Carousel.jsx](https://github.com/react-bootstrap/react-bootstrap/blob/f393dcaafdab1918ce2cdf7cdf2c06d0a94fbbef/src/Carousel.jsx#L211-L213) to add a whitespace after each indicator to ensure the correct spacing.
The w3c validator complains about this HTML because a `span` element is not allowed to be a direct children of an `ol` element.

**Comment by mtscout6** [comment]
Would gladly take a pull request to fix that!

**Comment by RafLeszczynski** [comment]
AFAIK to preserve whitespace in JSX and avoid wrapping it with `<span>` it needs to be written in single line. For example:
```JS 
<ol className={tbsUtils.prefix(this.props, 'indicators')}>
    <li>indicator 1</li> <li>indicator 2</li> <li>indicator 3</li>
</ol>
```
This syntax in no possible with array of indicators. 

Possible solutions:
1. add margins on Bootstrap CSS level (not sure if it's possible)
2. add margins in inline styles, for example: `<li key={index} className={className} onClick {this.handleSelect.bind(this, index, null)} style={{margin: '0, 2px'}} />`
3. render indicators as `<ol className={tbsUtils.prefix(this.props, 'indicators')} dangerouslySetInnerHTML={indicatorsMarkup} /> ` 

Personally I'd prefer to avoid option number 3. 

What do you think about this proposals? If any of them is OK I'm happy to submit a pull request.

**Comment by taion** [comment]
There's nothing we can really do about this. And the JSX syntax you have above does the same thing.

There's no sane way to handle this correctly until React properly supports inter-element whitespace.
