### ISSUE TITLE
Error messages question

### ISSUE THREAD

**Issue by KiziKr** [react-bootstrap/react-bootstrap#4261]
Hello, sorry for my bad english I'm french.

This is not bug, this is not request feature, just question.

Is it possible to modify the error messages for each properties of an input with this library without doing js?

Possibility of modifying the message for type, pattern, requirement, max, min etc ?

thank you so much

**Comment by taion** [comment]
Those come from the browser by default. You can use something like React Formal if you want to customize error handling.
