### ISSUE TITLE
Put a link to the github source for each component in the docs

### ISSUE THREAD

**Issue by jeremydmiller** [react-bootstrap/react-bootstrap#428]
Just a suggestion. The quickest way to understand what options a component takes is to just look at the code for that component. A link in the docs to the jsx code in GitHub might be nice.

**Comment by mtscout6** [comment]
Agreed! For consistency sake we should have the url be to the latest tagged release. Since we generate the static docs pages during the now automated release process after the version bump that should work fine. We will just need some mechanics to generate that link based on that version. Shouldn't be difficult though.

**Comment by morlay** [comment]
Hi guys, I start a project to auto generate a doc for react,  <https://github.com/morlay/react-doc>.
not good enough now, and anyone could join me to continue it or any suggestion.

Generated doc json: https://github.com/morlay/react-doc/blob/master/example/docs/result.json
DocUI preview: http://morlay.github.io/react-doc/example/docs/

Thanks.

**Comment by mtscout6** [comment]
@morlay I REALLY like where this is going! Let's discuss this in #431.

**Comment by AlexKVal** [comment]
It will add too many maintanance burden.

The latest [FormControls](https://github.com/react-bootstrap/react-bootstrap/tree/0c61f4634b404171abdea856c17b0e88a9e63a3a/src/FormControls) components refactoring made it plain https://github.com/react-bootstrap/react-bootstrap/issues/825 that problems will arize.
Just imagine how much it has to be done then, with every component split or moving into new folder / namespace. 

(the probability of realizing this issue in reality is 'wontfix')
I'm closing it

**Comment by mathieumg** [comment]
I hadn't seen this issue since I was really busy with school at the time. I believe this could be automated in a way that makes it maintainable.

**Comment by AlexKVal** [comment]
Then you can prove it by starting from a small (but having more priority now) step
fix https://github.com/react-bootstrap/react-bootstrap/issues/825 :stuck_out_tongue_winking_eye: 
Then you'll realize that this `docs + links` has the same 'burden' and is not so simple to automate
as it seems.

**Comment by jquense** [comment]
well we now have some infrastructure for automating some documentation. It wouldn't be two hard to have the `generate-metadata` do it without much trouble or increased maintenance burden.

I think if something makes the docs better, it should be seriously considered, sure it increases maintenance burden, but that, to me, is just part of running a good project.

**Comment by AlexKVal** [comment]
Then:
Pull requests are welcome :wink:

**Comment by Grahack** [comment]
Hi, could someone sum up the work that has to be done here? If I understand this well you want to add links automatically. Is there some docs about the docs generation process?

I only found [the docs section](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md#docs) in CONTRIBUTING.md.

**Comment by taion** [comment]
I don't think we've explicitly documented the docs generation process. The code is in https://github.com/react-bootstrap/react-bootstrap/blob/master/docs/build.js. The best hook is to probably add some sort of link when generating props tables.

**Comment by taion** [comment]
Fixed in https://github.com/react-bootstrap/react-bootstrap/pull/2980
