### ISSUE TITLE
Add HTML5 autofocus prop for inputs

### ISSUE THREAD

**Issue by epeli** [react-bootstrap/react-bootstrap#429]
> This Boolean attribute lets you specify that a form control should have input focus when the page loads, unless the user overrides it, for example by typing in a different control. Only one form element in a document can have the autofocus attribute, which is a Boolean. It cannot be applied if the type attribute is set to hidden (that is, you cannot automatically set focus to a hidden control).

https://developer.mozilla.org/en/docs/Web/HTML/Element/Input

**Comment by mtscout6** [comment]
You can already do this today. Any prop you pass to an Input will get propagated to the underlying html input. If that is not the case please provide a code example demonstrating that it is not working.

**Comment by epeli** [comment]
Uhm. This was a React user error on my behalf. The prop is `autoFocus` not `autofocus`...

**Comment by marisveide** [comment]
`autoFocus` attribute on `Form.Control` seems to get ignored.

Here is the code and the input element doesn't get the focus:
```
<Form>
          <Form.Group controlId="formBasicEmail">
            <Form.Label>Name</Form.Label>
            <Form.Control
              type="text"
              placeholder="Enter your name"
              autoFocus
              autoComplete={''}
              onChange={handleUserChange}
            />
          </Form.Group>
        </Form>
```

**Comment by thanateros** [comment]
@marisveide same issue here. `autoFocus` just plain doesn't work on a Form.Control.

I'd be curious to see an example of how anyone has ever accomplished this.  Been banging my head against this for 2 days.

**Comment by flolege** [comment]
For everyone struggling with that, here is what worked for me:
```
<Form.Control
  autofocus="true"
/>
```

**Comment by omarish** [comment]
I couldn't get this to work for some reason, so I ended up doing this as a workaround:

```ts
  const ref = React.useRef<HTMLInputElement>()

  React.useEffect(() => {
    if (ref && ref.current && isFunction(ref.current.focus) {
      // @ts-ignore
      ref.current.focus()
    }
  }, [ref])
```
