### ISSUE TITLE
Overlay not disappeaing when moved away from target element

### ISSUE THREAD

**Issue by Developer963** [react-bootstrap/react-bootstrap#4293]
When hovering over the element the popover is working as expected, however when hovering onto another element with a popover the previous one remains on the screen.  This seems to be an intermittent problem.

I am setting the OverlayTrigger container to {this}, which may be the reason why as only happened after this syntax amendment. (FYI need a container to ensure the popover is in the correct place)

![Screenshot 2019-08-21 at 13 03 04](https://user-images.githubusercontent.com/39669080/63430475-8fa73200-c414-11e9-96fd-78b30ede077b.png)

**Comment by taion** [comment]
Please provide a repro using a CodePen/CodeSandbox/&c.

**Comment by kosmiq** [comment]
No feedback given after more than 7 days. Closing.
