### ISSUE TITLE
Should Row calculate children's width?

### ISSUE THREAD

**Issue by wmertens** [react-bootstrap/react-bootstrap#430]
Just thinking out loud here, wondering if this is a worthwhile idea:

Since React allows programmatically changing html markup before it is added to the DOM, perhaps the column widths should be optional or even flexbox-like.

Row could add up all the children widths and give an error if they don't add up to 12, or it could take weights per column (default 1) and convert that to 12-column classes. E.g. 3 columns without weights would result in md-4, md-4, md-4.

**Comment by taion** [comment]
It's valid in Bootstrap for the sum of columns not to equal 12, and is in fact demonstrated in the example.

I'm not sure that it makes sense to automatically do flexbox-style calculations here, though. It should be easy enough to just use flexbox directly when that behavior is desired.

What sorts of use case would this address where using flexbox would not be the right thing?

**Comment by wmertens** [comment]
Yes you're right, it's really flexbox that I want. So perhaps this issue
should be about implementing a  flexbox gross but I assume that's not
something you'd want in react-bootstrap?

**Comment by taion** [comment]
I'm not sure what's even necessary to do, though. If you want to build your own grid using flexbox, you can set your own CSS. It wouldn't be Bootstrap's grid system. I've seen some frameworks allow you to use percent-based grids with flexbox underlying it, but ultimately those end up being less powerful than just using flexbox directly.

My personal inclination is that this would be a bit out of scope for React Bootstrap, though if you have a good way of setting something like that up, it might be a good standalone project.

**Comment by wmertens** [comment]
The way angular-material does it is quite nice, wouldn't be hard to
implement in react.

It's not really in scope for me right now though, I might take a stab at it
later sometime in a different project. I'll close.
