### ISSUE TITLE
Please update the following components: Uncontrolled(Navbar)

### ISSUE THREAD

**Issue by freemaths** [react-bootstrap/react-bootstrap#4306]
react-dom.development.js:12029 Warning: componentWillMount has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.

Please update the following components: Uncontrolled(Navbar)

Note: issue #3518 looked to cover this but has been closed with no resolution or advice. Will this be updated? How do we supress the warning in the meantime (without supressing for our own code).

I am getting the above warning after updating react and react-bootstrap to latest versions:

"react": "16.9.0",
 "react-bootstrap": "1.0.0-beta.11",
 "react-dom": "16.9.0",

**Comment by IAmVisco** [comment]
Having the same warning here when using Navbar, would like to see updated version sometime soon.

**Comment by taion** [comment]
This was fixed in beta.12. Though I see now that we forgot to tag that as latest. I just did so.

**Comment by martinnenseth** [comment]
Just updated to beta.12, and I'm not receiving the warning from Navbar anymore. However, I'm getting the exact same warning just for TabContainer.
