### ISSUE TITLE
Investigate use of react-docs for document generation from jsdocs

### ISSUE THREAD

**Issue by mtscout6** [react-bootstrap/react-bootstrap#431]
@morlay Has presented an Idea for generating the docs based on JsDocs in our components. I really like this idea, and would like to track it's discussion here. First presented in #428

**Comment by mtscout6** [comment]
How will this work with multiple examples per component? For example the current [react-bootstrap button docs](http://react-bootstrap.github.io/components.html#buttons) show multiple examples and documentation with various things you can do with buttons. We do this same thing with other components as well.

Is there a way to have things like Mixins land on one page and components on another? @joemcbride and I have talked about adding another docs page specifically for the various Mixins.

Lastly, I know this is primarily based on jsdoc, but how hard would it be to pull the props directly from the [`propTypes`](https://github.com/morlay/react-doc/blob/master/example/components/button/Button.jsx#L31-L40) declaration?

**Comment by morlay** [comment]
For this version it is support the multiple examples.
`@example` and `@exampleFile` can use after `@component`, `@property` and `@method`, then they will be convert to  an item of `[Array] examples`

    @component Button
    @example code here directly
    @exampleFile ./relative/path/to/exampleFile

    @property {String} bsStyle - button style - Use any of the available button style types to quickly create a styled button. Just modify thebsStyle prop.
    @example
    @example 

then the UI will list all the example. there is an example in my another project:

![demo](https://cloud.githubusercontent.com/assets/1667873/6499627/b85050c8-c339-11e4-90a0-9d3bcb19e666.png)

and for a example demo, we will get 

     {
        "requireList": [
              {
                "path": "react",
                "src": "require('react')",
                "dest": "require(\"react\")"
              },
              {
                "path": "/Users/morlay/gitRepo/react-doc/example/components/button/Button.jsx",
                "src": "require('../Button.jsx')",
                "dest": "require(\"/Users/morlay/gitRepo/react-doc/example/components/button/Button.jsx\")"
              }
            ],
      "contents": ""
   }

this will be use for generating a global requireList  https://github.com/morlay/react-doc/blob/master/example/docs/result.jsx to use injecting to ReactPlayground (https://github.com/morlay/react-doc/blob/master/ui/ReactPlayground.jsx#L147). replacing configure all in this file, I try to use the requireList to generate a `globalRequire`, then we can use it by this way.

     React.render(<ReactDoc globalRequire={require('./result.jsx')} info={require('./result.json')} />, document.body);

**Comment by morlay** [comment]
Then the structure of the result.json

    <TAG>: {
         <MODULE>: {
               <NAME>: {
                      tag: 'component',
                      name: 'Button',  // prefer as filename
                      module: 'components/button', // prefer as dirname
                      path: 'path/to/file'  // comment group get from,  so this prop can use for generate the link to github.
                      property: {},
                      method: {
                             hello: {
                                 param: {}
                             }
                      }
             }   
        }
    }


For the `@method`, sometimes, we have to use `ref` to trigger some function in child component,
so I think we need to list the `method` that can use for `ref` way. but now, haven't down for UI views.

**Comment by morlay** [comment]
Then the `propTypes`, I just haven't find a common way to pick the info in code, 
you know, there have too much pre-processor for JavaScript.
If someone use CoffeeScript/TypeScript/ClojureScript, that will be write a lot rule for pick the `propTypes`.
This is one reason I haven't choose the [official jsdoc tool](https://github.com/jsdoc3/jsdoc) and use the comment way for the doc generator - https://github.com/Constellation/doctrine.

Then for the `description` and `example`, keep all in comments may easy to pick.
And seems we have to write twice.

**Comment by joemcbride** [comment]
Overall I think this could work well.  A concern I have is that showing the full api seems a bit "busy" if you're just looking for the basics on how to use a component.  That is one aspect I do not like at all about auto-generated docs.  I think it would be nice to have a way to "just show me the examples".

**Comment by mtscout6** [comment]
If we had some mechanisms in place to fold that extra detail, that may be sufficient.

**Comment by morlay** [comment]
Sure, and this  just depend which doc ui we use. We can easy to filter the info from the `result.json`. 

And we may think about that can doc tag rules cover all.

**Comment by morlay** [comment]
Hi Guy，
React team start the project https://github.com/reactjs/react-docgen which can get props info from `propTypes` for components.

**Comment by mfunkie** [comment]
We've been using react-docgen to build our documentation for [Boomstrap React](https://github.com/BoomTownROI/boomstrap-react) with pretty good success.  Basically, we run babel on all of our code and it is output to a directory (not minified and no comments are removed).  From there, react-docgen is able to parse it and build our json file that our documentation components consume and display in a table on our [doc website](http://boomtownroi.github.io/boomstrap-react/#/docs/Fauxbox).  I'm not 100% sure that it works with es6 class-based components though so if any of those start to creep in it may not work.  It's possible it does work, but I haven't done the investigation.

**Comment by taion** [comment]
Per https://github.com/reactjs/react-docgen/blob/5721795aa52d9019f974b14f1eb1a7cdb43a9d99/README.md#resolver, most likely no support for ES6 classes yet.

**Comment by mtscout6** [comment]
When we do this we will need to do a survey and ensure that all `isRequired` prop type usage is in line with any default values. As per https://github.com/react-bootstrap/react-bootstrap/pull/793#issuecomment-110033775

**Comment by jquense** [comment]
Not super pleased with react-docs structure no es6 classes, one component per module, i spent a weekend building something similiar as a babel plugin. It is mostly just a fun project i did to learn the plugin system but it does work, I use it to generate the [react-formal](http://jquense.github.io/react-formal/docs/#/api) docs

repo here: https://github.com/jquense/react-component-metadata

**Comment by AlexKVal** [comment]
I presume it is resolved now by https://github.com/react-bootstrap/react-bootstrap/pull/887

**Comment by jquense** [comment]
Well #887 gets us some of the way there, but there is plenty of room for improvement for those that wan't to build on it.

**Comment by AlexKVal** [comment]
Yep. There was the issue https://github.com/react-bootstrap/react-bootstrap/issues/716 for it already as it turned out :smile:
