### ISSUE TITLE
Role attribute no longer being set for Tabs nav element 

### ISSUE THREAD

**Issue by jmooserific** [react-bootstrap/react-bootstrap#4313]
## Describe the bug
After upgrading from 1.0.0-beta.10 to 1.0.0-beta.11 (or later), the role attribute is no longer specified for the `nav` element generated by the `Tabs` component. It was set in 1.0.0-beta.10 and earlier.

This is an accessibility issue and is flagged by many accessibility testing tools, like [axe](https://www.deque.com/axe/).

## To Reproduce

1. Use the Tabs component in a React application.
2. View the `nav` element of the resulting HTML.

## Reproducible Example
CodeSandbox example: https://codesandbox.io/s/code-sandbox-examples-nx7n5
(Currently set to 1.0.0-beta.10. Please upgrade the react-bootstrap version to see the role attribute disappear.)

## Expected behavior
The `nav` element should have a `role` attribute of "tablist".

## Screenshots
1.0.0-beta.10:
![Screen Shot 2019-08-22 at 2 13 23 PM](https://user-images.githubusercontent.com/1071856/63539026-22180600-c4e7-11e9-897c-8d2782bbb8d2.png)

1.0.0-beta.11:
![Screen Shot 2019-08-22 at 2 15 04 PM](https://user-images.githubusercontent.com/1071856/63539067-44aa1f00-c4e7-11e9-829c-6d276d6bf527.png)

## Environment (please complete the following information)
- React-Bootstrap Version 1.0.0-beta.11 and later

**Comment by jmooserific** [comment]
Upon [further research](https://getbootstrap.com/docs/4.3/components/navs/#regarding-accessibility), I think it might be more appropriate to create a `div` with `role="tablist"` inside the `nav` element rather than adding that attribute to the `nav`.

**Comment by jquense** [comment]
Hmm not sure what changed to cause this...

**Comment by taion** [comment]
It's a regression due to https://github.com/react-bootstrap/react-bootstrap/pull/4031. We spread out `role` and don't pass it down to `<Component>`.

@jmooserific care to send in a quick PR to fix?

**Comment by taion** [comment]
not sure why the tests didn't catch. perhaps they're matching on a react component instead of a host component now?

**Comment by jmooserific** [comment]
I have created PR #4331 to address this issue. 

Please let me know if it looks okay. Thanks!

**Comment by bpas247** [comment]
#4331 closes this
