### ISSUE TITLE
Vertical navs of tabs variant use horizontal styling

### ISSUE THREAD

**Issue by akhilpai** [react-bootstrap/react-bootstrap#4314]
## Describe the bug

[Vertical navs](https://react-bootstrap.github.io/components/navs/#vertical) of the [tabs variant](https://react-bootstrap.github.io/components/navs/#tabs) use the default horizontal styling. 

## Reproducible Example

https://codesandbox.io/embed/code-sandbox-examples-9f8hc

## Expected behavior

Either there should be a warning in the documentation not to use the tabs nav variant with the flex-column css or there should be a way to define which direction the styling should be applied.

**Comment by jquense** [comment]
Yeah the styles don't support that layout really. I agree that the docs should allude to it at least. It's also unclear in the upstream bootstrap docs as well

**Comment by malsf21** [comment]
This seems like a pretty simple PR, I can handle it. Should I also implement a console-level warning, or just something in the docs?

**Comment by taion** [comment]
Hmm, would it be possible for a Bootstrap theme to implement this sort of styling? If so, an unsilencable warning in code might be a bit much.

**Comment by malsf21** [comment]
Maybe, but I haven't come across one? Basically, the theme has to override `nav-tabs` when it sees `flex-column` applied to the same element. I can just add it to the docs then with no warning!

**Comment by kyletsang** [comment]
Looks like we can close this since docs have been updated with a note regarding vertical tabs
