### ISSUE TITLE
eventKey and key documentation

### ISSUE THREAD

**Issue by RichardLitt** [react-bootstrap/react-bootstrap#432]
The documentation around eventKey and key is confusing or missing, as noted in #320. I would like to make a PR to fix this, but I am unclear on a few areas. 

Is eventKey only used in react-bootstrap, or is it also standard in react? cc @trentgrover-wf

**Comment by trentgrover-wf** [comment]
`eventKey` is a react-bootstrap concept only.  `key` is the standard React concept, but `key` values are no longer available for use within a component, so we had to switch to using a separate explicit value for some use cases (hence the birth of `eventKey`)

**Comment by RichardLitt** [comment]
Ok. Is there a place we can document this, besides here?

**Comment by trentgrover-wf** [comment]
should probably just be documented alongside the relevant component examples (e.g. something to the effect of `DropdownButton has an optional onSelect property...the onSelect function will receive the eventKey value of the selected MenuItem as a parameter...`

**Comment by mtscout6** [comment]
Something to take into account with #419

**Comment by RichardLitt** [comment]
I'm not sure that that is what is best - `eventKey` doesn't only interact with `onSelect`, and it occurs in 21 different examples, not just in `DropdownButton`. There should be a warning somewhere about what `eventKey` is - I don't see where it would go on the Component page, but just including it in `DropdownButton` and then only when dealing with `onSelect` is limiting in scope. 

The Components page is great, but I'm not sure that this sort of thing belongs there - it seems too general. If it does, it should be at the top, somewhere clear to explain what it is. What do you think?

**Comment by mtscout6** [comment]
Should we decide to go with #431 than this gets easy.

**Comment by AlexKVal** [comment]
Superceded by https://github.com/react-bootstrap/react-bootstrap/issues/419
