### ISSUE TITLE
Cannot find modules in /docs on `npm install`

### ISSUE THREAD

**Issue by RichardLitt** [react-bootstrap/react-bootstrap#433]
Fresh clone of the repository at 998febbf10c35f105bfbbbc79678ca166ade796d. 

In `docs/README.md`, it suggests the following:

```sh
$ cd react-bootstrap/docs
$ npm install
```

However, this will not work, as it fails to find the modules `react` and `react-router-component`.

**Comment by trentgrover-wf** [comment]
i think it gets those from the root, so make sure to `npm install` at the project root too

**Comment by RichardLitt** [comment]
Yep. PRed.
