### ISSUE TITLE
Sidebar Hamburger Menu

### ISSUE THREAD

**Issue by Prathapkarumanchi** [react-bootstrap/react-bootstrap#4333]
## Is your feature request related to a problem? Please describe
Is it possible to implement Sidebar Toggle Hamburger menu?

The are so many examples available out there how to achieve sidebar content with toggle hamburger menu. Is this possible with react-bootstrap components?

## Describe the solution you'd like
A sidebar panel that toggles on hamburger menu click.

## Describe alternatives you've considered
https://bootstrapious.com/p/bootstrap-sidebar

Please check all the examples available

## Additional context

![screenshot-bootstrapious com-2019 08 24-23_41_49](https://user-images.githubusercontent.com/53927098/63641252-d2913000-c6c8-11e9-93c8-10643c6be9da.png)

**Comment by bpas247** [comment]
Is this a part of the upstream design specs? I can't seem to find an equivalent of this component in their official docs.

**Comment by taion** [comment]
Yup, not part of upstream TWBS, so shouldn't be here

**Comment by giorgi-m** [comment]
@taion I was also looking for this component. Ah, I see reasoning: since it's not in original bootstrap neither it is in react version. But why limit yourself to components which are only in bootstrap? Maybe you could have a section like "extra" and add new components there? Just a suggestion.

**Comment by kosmiq** [comment]
Seem like off canvas might be a part of bootstrap 5. So that might solve your issue when it's done and released.

**Comment by giorgi-m** [comment]
@kosmiq is this library gonna support bootstrap 5?

**Comment by bpas247** [comment]
>is this library gonna support bootstrap 5?
@giorgi-m 

Absolutely! We have already began discussions on bootstrap v5 support 👍
