### ISSUE TITLE
Purpose of `type` defaultProps in `FormCheckLabel`?

### ISSUE THREAD

**Issue by JeromeDeLeon** [react-bootstrap/react-bootstrap#4335]

**Comment by bpas247** [comment]
> Purpose of `type` prop in `FormCheckLabel`?

`FormCheckLabel` doesn’t have a `type` prop. 
https://react-bootstrap.github.io/components/forms/#form-check-label-props

**Comment by JeromeDeLeon** [comment]
yes you're right but instead in the code you have `defaultProps` that contains `type` with a value of `checkbox`.

**Comment by JeromeDeLeon** [comment]
https://github.com/react-bootstrap/react-bootstrap/blob/ac71788678c04812d442fa8a2ffb60f386ae3ef7/src/FormCheckLabel.js#L24

**Comment by JeromeDeLeon** [comment]
https://github.com/react-bootstrap/react-bootstrap/blob/ac71788678c04812d442fa8a2ffb60f386ae3ef7/src/FormCheckLabel.js#L24-L26

**Comment by taion** [comment]
That looks like a mistake. We'd be happy to take a PR removing it.
