### ISSUE TITLE
OverlayTrigger with trigger="focus" not clickable

### ISSUE THREAD

**Issue by psbanka** [react-bootstrap/react-bootstrap#436]
Thanks for your work on this project! It's really saving a lot of time!

I am trying to create an `OverlayTrigger` using `trigger="focus"`, and it does not seem to have the correct behavior.
If using the pure-bootstrap solution, trying:

```javascript
$('#my-id')
    .popover('destroy')
    .popover({
        html: true,
        content: this.makeMenuDropdownHtml(hiddenMenuObjects),
        title: 'Additional Menu Items',
        trigger: 'focus',
        placement: 'bottom',
        animation: false,
    });
```
This has the correct behavior (namely, that you can click on the menu item, it displays the popover, and if you click anywhere else, the popover is dismissed).

But if I try this with the `react-bootstrap` project using the `OverlayTrigger` in conjunction with the `Popover`, as follows:

```javascript
render: function () {
    if (this.props.hiddenMenuCount === 0) {
        return null;
    }
    let hiddenMenuItems = this.getHiddenMenuItems();
    return (
        <li>
            <OverlayTrigger
                    trigger='focus'
                    placement="bottom"
                    overlay={<Popover title="Additional Menu Items">{hiddenMenuItems}</Popover>}>
                <div>
                    Menu
                    <span className="caret" />
                </div>
            </OverlayTrigger>
        </li>
    );
},
```
The dropdown-menu is not clickable. I have also tried 
`trigger={['click', 'focus']}` with no success. Is this a bug or am I doing this wrong?

Thanks!

**Comment by lukemcgregor** [comment]
The issue (i think) you are having here is that the element you have in the overlaytrigger is not focusable, put a button or a link in there and it should work ok.

**Comment by psbanka** [comment]
Thanks for the feedback, but wrapping in a button or in an anchor tag had no effect on the issue.

**Comment by tauseef-inbetween** [comment]
Facing same problem

**Comment by Compudoctors** [comment]
Facing same problem.

**Comment by AlexKVal** [comment]
Superceded by #855
