### ISSUE TITLE
Please update the following components Unctrolled(TabContainer)

### ISSUE THREAD

**Issue by martinnenseth** [react-bootstrap/react-bootstrap#4368]
## Describe the bug
Closely related to https://github.com/react-bootstrap/react-bootstrap/issues/4306 , this issue is however related to TabContainer and not NavBar.

Using TabContainer creates the following warning:
> backend.js:1 Warning: componentWillMount has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.
> 
> * Move code with side effects to componentDidMount, and set initial state in the constructor.
> * Rename componentWillMount to UNSAFE_componentWillMount to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.
> * Please update the following components: Uncontrolled(TabContainer)

## Expected behavior
No warning caused by using TabContainer.

## Environment 
"react-bootstrap": "^1.0.0-beta.12",
"react-bootstrap": "^1.0.0-beta.12",
 "react-dom": "^16.8.6",

## Additional context

Updated to react bootstrap 1.0.0-beta.12 a couple days ago, and removed the same error for NavBar. Would it be possible to apply the same fix for TabContainer?

**Comment by taion** [comment]
We'd be happy to take a PR for this.

**Comment by ljmerza** [comment]
I also get a warning for `componentWillReceiveProps` in TabController
