### ISSUE TITLE
Drop @react-bootstrap/react-popper?

### ISSUE THREAD

**Issue by proteriax** [react-bootstrap/react-bootstrap#4374]
It seems the dependency @react-bootstrap/react-popper is [not used anywhere in the project](https://github.com/react-bootstrap/react-bootstrap/search?utf8=%E2%9C%93&q=react-popper&type=), has not been updated for a year and pulls in a quite heavy dependency `fbjs`. Anyone has any idea if we can safely remove it?

**Comment by taion** [comment]
Probably a good idea. We've been looking to drop it.

**Comment by taion** [comment]
Happy to take a PR here.
