### ISSUE TITLE
Scroll Modal to the top by means of JavaScript

### ISSUE THREAD

**Issue by ogimihail** [react-bootstrap/react-bootstrap#4378]
I have a form in the modal (very long and it doesn't fit into the browser visibility). When I press 'submit' I need the modal to scroll up automatically. I don't manage to do this by means of React/Native JS. Please give me some advice on how to do this.

**Comment by taion** [comment]
Get a hold of the DOM node and set `scrollTop`. Or use `scrollTop` from `dom-helpers`. This isn't a general-purpose JS support forum, though, so if you have other questions, please check e.g. StackOverflow.
