### ISSUE TITLE
React 16.9.x deprecation warnings with 0.32.4

### ISSUE THREAD

**Issue by lvpro** [react-bootstrap/react-bootstrap#4398]
React 16.9 is now spamming the console with warnings regarding the use of componentWillMount, componentWillReceiveProps, and componentWillUpdate.

Apparently rbs 0.32.4 still uses these in most of the components.  Since seamlessly moving to BS4 is no small feat styling-rule wise, I'm curious .... is there any chance the BS3 based release will be updated to replace these calls to make React happy?

I believe these calls will stop working all together in React 17.

**Comment by jquense** [comment]
I believe someone recently did the work of swapping out for `UNSAFE_` prefixed versions, and we need to release that. In terms of proper migration via switching to gDSFP, that is less likely from the maintainers here, since most (all?) of us are using v4 now. We would happily accept PR's tho!

**Comment by MatthewHerbst** [comment]
@jquense is there anything blocking that release from going out?

**Comment by mturley** [comment]
+1 for releasing the version with `UNSAFE_` prefixes. My team is maintaining a legacy version of our component library that depends on react-bootstrap and bootstrap v3, and we need to support newer React versions. @jquense is there anything we can do to help with that release? Our alternative is to make a copy of the source in-house, which obviously isn't ideal.

**Comment by mxschmitt** [comment]
We also use the v3 variant of react-bootstrap in production and would benefit of a new release.

**Comment by wheeler** [comment]
`UNSAFE_` prefixes were introduced in `react@16.3` so we would need to bump the min version in `package.json`. I'm happy to prepare a PR against the `bs3-dev` branch.

**Comment by taion** [comment]
sounds good

**Comment by wheeler** [comment]
React required version PR here: https://github.com/react-bootstrap/react-bootstrap/pull/4530

**Comment by nortonwong** [comment]
The remaining lifecycle warnings are from the higher-order-component `Uncontrollable`. I've submitted a pull request at https://github.com/jquense/uncontrollable/pull/40 which migrates those usages.

**Comment by nortonwong** [comment]
Opened a `react-overlays` upgrade PR at https://github.com/react-bootstrap/react-bootstrap/pull/4639. Some breaking changes are involved.

**Comment by kimyu92** [comment]
@taion @bpas247 would it be possible to publish an official npm package release v0.32.5 which include changes of https://github.com/react-bootstrap/react-bootstrap/commits/bs3-dev up till c9c298f1a5b941d1b39a595c9a5440a890d8c58f before breaking changes from #4639

**Comment by ElScorxcho** [comment]
@taion With #4760 being merged are there any plans to release a new version anytime soon?

**Comment by taion** [comment]
released v0.33.0

**Comment by abhinavsingi** [comment]
But react-bootstrap@0.33.0 depends on react-overlays older version which is using deprecated methods, so essentially react-bootstrap@0.33.0 is not usable with react@16.9.0.

**Comment by taion** [comment]
it's compatible with newer R-O versions that drop the deprecated methods
