### ISSUE TITLE
Navbar.Toggle component adds wrong 'collapsed' className depending on expanded context state

### ISSUE THREAD

**Issue by mattywong** [react-bootstrap/react-bootstrap#4399]
## Describe the bug

When a Navbar component is expanded, the Navbar.Toggler className is "navbar-toggler collapsed", and when it is collapsed, the className is "navbar-toggler".

Should this not be the inverse? i.e

When expanded:
className="navbar-toggler"

When collapsed
className="navbar-toggler collapsed"

## To Reproduce

1. Go to 'https://react-bootstrap.github.io/components/navbar/'
2. Scroll down to Overview, resize screen to mobile and look at the class attr generated on the navbar toggler whilst expanding and collapsing the nav by clicking the navbar toggler button

## Reproducible Example

https://react-bootstrap.github.io/components/navbar/

## Expected behavior

https://getbootstrap.com/docs/4.3/components/navbar/

## Environment (please complete the following information)

- Operating System: Windows 10

- Browser, Version [e.g. Chrome 74]
Chrome Version 76.0.3809.132 (Official Build) (64-bit)

- React-Bootstrap Version [e.g. 1.0.0-beta.8]
1.0.0-beta.11

## Additional context

We use the collapsed class to do a css transform on the icon depending on the current expanded state (chev up/down etc, css rotation).

Happy to create a pull request for this, seems like an easy fix,

https://github.com/react-bootstrap/react-bootstrap/blob/master/src/NavbarToggle.js

Line 64, change the double bang to single bang

**Current:**
```
...
className={classNames(className, bsPrefix, !!expanded && 'collapsed')}
...
```

**Fix**
```
...
className={classNames(className, bsPrefix, !expanded && 'collapsed')}
...
```

**Comment by taion** [comment]
Yes, please send in a PR.
