### ISSUE TITLE
Horizontal ListGroup

### ISSUE THREAD

**Issue by YurySolovyov** [react-bootstrap/react-bootstrap#4410]
Bootstrap has [Horizontal](https://getbootstrap.com/docs/4.3/components/list-group/#horizontal) ListGroup component, it would be nice to have it exposed as boolean or string (layout="vertical"/"horizontal") prop on the ListGroup component.

**Comment by jquense** [comment]
we'd gladly take a PR adding a `horizontal` prop!

**Comment by malsf21** [comment]
Mind if I take a shot at this with a PR? Should be pretty simple!

**Comment by malsf21** [comment]
Just wanted to update, submitted a PR (#4421).

**Comment by bpas247** [comment]
#4421 closes this.
