### ISSUE TITLE
Nav child that wraps NavItem 'active' prop collision

### ISSUE THREAD

**Issue by bobpace** [react-bootstrap/react-bootstrap#443]
In this example, NavItemLink is the child of Nav that wraps NavItem: 
```html
<Navbar>
  <Nav>
    <NavItemLink to='example'>Example</NavItemLink>
  </Nav>
</Navbar>
```

Nav imposes props onto its children like this:
```javascript
renderNavItem: function (child, index) {
  return cloneWithProps(
    child,
    {
      active: this.getChildActiveProp(child),
      activeKey: this.props.activeKey,
      activeHref: this.props.activeHref,
      onSelect: createChainedFunction(child.props.onSelect, this.props.onSelect),
      ref: child.ref,
      key: child.key ? child.key : index,
      navItem: true
    }
  );
}
```

the 'active' prop is set to be whatever 'getChildActiveProp' says, which looks like this:
```javascript
getChildActiveProp: function (child) {
  if (child.props.active) {
    return true;
  }
  if (this.props.activeKey != null) {
    if (child.props.eventKey == this.props.activeKey) {
      return true;
    }
  }
  if (this.props.activeHref != null) {
    if (child.props.href === this.props.activeHref) {
      return true;
    }
  }
  return child.props.active;
}
```

The problem is that if in NavItemLink's render function we try to set the 'active' prop: 

```javascript
render: function() {
  var isActive = this.isActive(this.props.to, this.props.params, this.props.query);
  return (
    <NavItem
      href={this.getHref()}
      active={isActive}
      onClick={this.handleClick} {... this.props}>
      {this.props.children}
    </NavItem>
  );
}
```

It won't make it to that `getChildActiveProp` function. The 'child' that is passed in is the actual NavItemLink component, which has no active prop resulting in 'active' being set to undefined.

This is now stronger than anything you can specify on NavItem from within NavItemLink's render function and so active will always be undefined.

I am currently working around this with a fork by adding a prop 'isActive' which can override this active prop that is imposed onto the children of Nav, however it may be possible to straighten this out in a different way which would eliminate the need for something like this:
https://github.com/bobpace/react-bootstrap/tree/fixActiveNameCollision

I think this issue may be related:
https://github.com/mtscout6/react-router-bootstrap/issues/14

**Comment by mtscout6** [comment]
Something to take into account when dealing with this bug: http://facebook.github.io/react/blog/#react.cloneelement

**Comment by barbalex** [comment]
I have a nav:

    <Nav id='proj_sidebar_id' className='proj_sidebar affix' activeKey={1}>
      <NavItem eventKey={1}><a href='#apflora'>ApFlora</a></NavItem>
      <NavItem eventKey={2}><a href='#artendb_web'>ArtenDb Web</a></NavItem>
      <NavItem eventKey={3}><a href='#artendb_access'>ArtenDb Access</a></NavItem>
      <NavItem eventKey={4}><a href='#evab_mobile'>evab mobile</a></NavItem>
    </Nav>

it's navitems don't change active state after getting clicked

am I doing something wrong or is this behaviour caused because of this issue?

warning: I'm a bad react noob

**Comment by taion** [comment]
`NavItemLink` in react-router-bootstrap actually deals with this correctly.

If you're re-implementing it, it's on you to figure out how to properly deal with the value of `this.props.active`, in the event that it's defined.
