### ISSUE TITLE
document button default type changed from w3c standard

### ISSUE THREAD

**Issue by morenoh149** [react-bootstrap/react-bootstrap#444]
I see https://github.com/react-bootstrap/react-bootstrap/blob/master/src/Button.jsx#L24 the default type of the button is changed to `button`. The w3c standard specifies `submit` as the default. http://www.w3.org/TR/html401/interact/forms.html#h-17.5 A note should be added to the docs.
Let me know if a PR is welcome.

**Comment by aabenoja** [comment]
Documentation will be added as part of #716.

**Comment by mtscout6** [comment]
I think this is more closely related to #342 and more specifically #626.

Although the location of it will likely be changing as proposed in https://github.com/react-bootstrap/react-bootstrap/pull/674#issuecomment-104298777
