### ISSUE TITLE
Add touchReverse prop to Carousel

### ISSUE THREAD

**Issue by nareg26** [react-bootstrap/react-bootstrap#4445]
## Is your feature request related to a problem?

Yes. #4018 enabled touch support for Carousel, which was awesome. However, it slides the carousel in the same direction as the swipe, which is not intuitive. In other words, to go to the next slide, I need to swipe right at the moment. It should be that I swipe left to go to the next slide.

Example:
https://www.exodus.io/mobile
(there's a carousel up top that appears on small screen widths)
(test with touch-capable device)

## Describe the solution you'd like

Add an additional prop, `touchReverse` or something like that, to give the option to control this. When set to `true` the carousel slides the opposite direction on swipe.

## Describe alternatives you've considered

Turn off default touch functionality on carousels and use a third party touch library.

**Comment by taion** [comment]
we fixed this in https://github.com/react-bootstrap/react-bootstrap/pull/4137 actually

**Comment by taion** [comment]
You're likely getting hit by https://github.com/react-bootstrap/react-bootstrap/issues/4447
