### ISSUE TITLE
Deprecated lifecycles warning in Carousel component

### ISSUE THREAD

**Issue by artjomzab** [react-bootstrap/react-bootstrap#4446]
## Describe the bug

Deprecated lifecycles in the carousel component should be removed. Carousel component should be updated to Hooks.

## Screenshots

![Screenshot 2019-09-10 15 22 08](https://user-images.githubusercontent.com/524580/64617446-c7cfde00-d3de-11e9-9313-ee2735cff5e0.png)

## Environment (please complete the following information)

- Operating System: macOS Mojave 10.14.5
- Browser, Version Chrome 76.0.3809.132
- React-Bootstrap Version 1.0.0-beta.12

**Comment by bpas247** [comment]
Relevant (possibly a dup?) to #4194.

**Comment by Tulean** [comment]
It is not a dup. The thread #4194 resolves only certain components. It does not include the Carousel component.

**Comment by bpas247** [comment]
> It does not include the Carousel component.

I’m not sure what you mean by that, since the Carousel component is on the [list of components that should be migrated|(https://github.com/react-bootstrap/react-bootstrap/issues/4194#issue-477645689) in that thread.

**Comment by Tulean** [comment]
When you check the Carousel component source code, the lifecycle method names have not been changed. That's why it is throwing us the Warning messages.

**Comment by shacco** [comment]
There is any posibility that you can fix that?

thanks you, numbe one react ui

**Comment by taion** [comment]
we updated #4194 to include carousel, so this is now a dupe
