### ISSUE TITLE
Fix https://react-bootstrap.github.io

### ISSUE THREAD

**Issue by taion** [react-bootstrap/react-bootstrap#4447]
For some reason this is pointing at beta 10. The actual current docs are on https://react-bootstrap.netlify.com.

**Comment by bpas247** [comment]
We're currently manually deploying the GitHub pages deployment, right?

**Comment by taion** [comment]
It's supposed to happen as part of the release process. But apparently that broke

**Comment by bpas247** [comment]
what CI/CD tool are we using for deployment?

**Comment by taion** [comment]
in https://github.com/react-bootstrap/react-bootstrap/pull/3427 @jquense made `deploy` and `push-docs` in `www/` push to `github.io`, but AFAICT there's no tooling to automatically run that on publish

are we just missing a postpublish script?
