### ISSUE TITLE
Background-position is not interpreted correctly

### ISSUE THREAD

**Issue by katsar0v** [react-bootstrap/react-bootstrap#4456]
### Describe the bug

I am using a react app with sass and bootstrap. My `index.tsc` includes the following in the header:
```
import React from 'react';
import ReactDOM from 'react-dom';
import 'bootstrap/dist/css/bootstrap.css';
import './sass/index.scss';
```
`package.json` versions:
```
"@types/jest": "24.0.18",
"@types/node": "12.7.2",
"@types/react": "16.9.2",
"@types/react-dom": "16.9.0",
"bootstrap": "^4.3.1",
"react": "^16.9.0",
"react-bootstrap": "^1.0.0-beta.12",
"react-dom": "^16.9.0",
"react-scripts": "3.1.1"
```

This is original css:
![image](https://user-images.githubusercontent.com/7236157/64258631-e0944b80-cf27-11e9-80a2-72bd25e80c63.png)

which looks like this:
![image](https://user-images.githubusercontent.com/7236157/64258677-f43fb200-cf27-11e9-876c-ee1a8c421aa0.png)

Everything looks fine when developing with `npm start`. But if I run `npm run build` I get this css:

![image](https://user-images.githubusercontent.com/7236157/64258728-0883af00-cf28-11e9-96af-2e113ce49dff.png)

which looks like this:

![image](https://user-images.githubusercontent.com/7236157/64258747-10435380-cf28-11e9-97d6-4a0b87addc91.png)

### Did you try recovering your dependencies?

I tried deleting `node_modules/`, but this didn't really help. Is also reproducible on other pc with the same project.

### Which terms did you search for in User Guide?

I followed the guide from https://create-react-app.dev/docs/adding-bootstrap. Tried both importing bootstrap from `index.tsx` or my main sass file.

### Environment

```
npx: installed 91 in 4.726s

Environment Info:

  System:
    OS: Linux 5.0 Ubuntu 18.04.3 LTS (Bionic Beaver)
    CPU: (4) x64 Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
  Binaries:
    Node: 12.7.0 - ~/.nvm/versions/node/v12.7.0/bin/node
    Yarn: 1.17.3 - ~/.nvm/versions/node/v12.7.0/bin/yarn
    npm: 6.10.2 - ~/.nvm/versions/node/v12.7.0/bin/npm
  Browsers:
    Chrome: 76.0.3809.132
    Firefox: 68.0.2
  npmPackages:
    react: ^16.9.0 => 16.9.0 
    react-dom: ^16.9.0 => 16.9.0 
    react-scripts: 3.1.1 => 3.1.1 
  npmGlobalPackages:
    create-react-app: Not Found
```

### Steps to reproduce

(Write your steps here:)

1. Import bootstrap in a react app with typescript and sass using this guide: https://create-react-app.dev/docs/adding-bootstrap
2. Render a form, e.g.:
```
<Form validated={true}>
<Form.Group as={Row} controlId="first_name">
                    <Form.Label column sm="2">First name:</Form.Label>
                    <Col sm="10">
                        <Form.Control name="first_name" type="input" required />
                        <Form.Control.Feedback type="invalid">You first name should contain at least 3 chars.</Form.Control.Feedback>
                    </Col>
                </Form.Group>
</Form>
```

### Expected behavior

I expect the "compiled" css to be 1:1 as the original from the cdn for example.

### Actual behavior

Screenshots already in description.

I posted the issue in react bootstrap - https://github.com/facebook/create-react-app/issues/7639

but I think it belongs here in this repository :)

**Comment by taion** [comment]
React-Bootstrap only deals with the JavaScript bindings. We have nothing to do with your SASS compilation there.

**Comment by katsar0v** [comment]
Then is the official "get started" documentation.. wrong and not working. Okay.
