### ISSUE TITLE
DropdownButton straight up does not work on mobile when in collapseable Nav

### ISSUE THREAD

**Issue by snario** [react-bootstrap/react-bootstrap#446]
Just check the mobile example (the inverse one): http://react-bootstrap.github.io/components.html#navbars

Make the page smaller and try opening the Nav and then the dropdown.

The issue is that `toggleNavKey` in the `Navbar` component accepts the `eventKey` of the `Nav` but cannot also take the `eventKey` of the DropdownButton. If you interchange the two keys you will one will work but not the other every time.

**Comment by joemcbride** [comment]
Possibly related to https://github.com/react-bootstrap/react-bootstrap/issues/322

**Comment by snario** [comment]
Fixed by https://github.com/react-bootstrap/react-bootstrap/pull/400
