### ISSUE TITLE
Carousel Can not support completely

### ISSUE THREAD

**Issue by leogitpro** [react-bootstrap/react-bootstrap#4465]
## Describe the bug

The default Carousel.Item can include a caption for every item.
But the all items can shere one caption use bootstrap natively.
just put Carousel.Caption and Carousel.Item with same level.

like this.
```
<div class="carousel-inner">
    <div calss="carousel-caption">...</div>
    <div calss="carousel-item">item1</div>
    <div calss="carousel-item">item2</div>
</div>
```
That will be keep ccaption not moving when play the carousel items.

But the <Carousel>{items}</Carousel> can not support that construct.
Every item was added class:carousel-item forcedly.

The code:
file: react-bootstrap/Carousel.js
Line: 419
```
return (0, _react.cloneElement)(child, {
          className: (0, _classnames.default)(child.props.className, bsPrefix + "-item", current && currentClasses, previous && prevClasses)
        });
```

Every child on `carousel-inner` was added `bsPrefix + "-item"` forcedly

```
<div class="carousel-inner">
    <div calss="carousel-item carousel-caption">...</div>
    <div calss="carousel-item carousel-item">item1</div>
    <div calss="carousel-item carousel-item">item2</div>
</div>
```
also add double class `carousel-item`.

And the Component: Carousel away has a warning:

Warning: componentWillMount has been renamed, and is not recommended for use.

I pull a request: [#4466 ]

Thanks.

**Comment by taion** [comment]
That's not the markup for carousel captions. See https://react-bootstrap.github.io/components/carousel/#example.
