### ISSUE TITLE
docs for react-bootstrap3 often unavailable(react-bootstrap-v3.netlify.com is down)

### ISSUE THREAD

**Issue by long76** [react-bootstrap/react-bootstrap#4467]
please move `react-bootstrap-v3.netlify.com` to `github.io` thanks!!!

**Comment by mxschmitt** [comment]
@long76 can you please describe the issue in more detail?

**Comment by long76** [comment]
@mxschmitt often when i want see docs for react-bootstrap-v3(*.netlify.com) browser return error `ERR_CONNECTION_RESET`, in `https://react-bootstrap.github.io/` docs available only for v4.

**Comment by mxschmitt** [comment]
> @mxschmitt often when i want see docs for `react-bootstrap-v3`(`*.netlify.com`) browser return error `ERR_CONNECTION_RESET`, in `https://react-bootstrap.github.io/` docs available only for v4.

That seems not be an issue on our side. More a) an issue on your side or b) an issue on Netlify side. But I guess related to the provided error maybe an ISP issue on your side.

**Comment by long76** [comment]
@mxschmitt  i think that it's `netlify.com` side problem. i try it in home, job and study(3 different ISP, maybe problem in country(Russia)). so you can made copy(in zip archive) docs or maybe better solution?

**Comment by long76** [comment]
i try run bs3-dev and get error `ReferenceError: React is not defined`
