### ISSUE TITLE
React components as contents of popover overlays are not persistant

### ISSUE THREAD

**Issue by catskul** [react-bootstrap/react-bootstrap#447]
The elements that serve as the contents for the popovers seem to be regenerated from scratch each time the popover is opened and closed.

As such it's state is wiped out.

Example:
http://jsfiddle.net/zgcqwec1/

There is a work around in saving the state out to json or to server, but current behavior seems odd.

**Comment by mtscout6** [comment]
This is a common issue with React. The solution is to store that state somewhere more durable. This is why Facebook has advocated for something like a Flux architecture. The thing to remember is that React is ONLY the view layer. Other business logic and information that needs to be more persistent requires additional strategies.
