### ISSUE TITLE
Cannot customize the `a` inside `Breadcrumb.Item`

### ISSUE THREAD

**Issue by zhaoyao91** [react-bootstrap/react-bootstrap#4472]
when I write something like this

```
<Breadcrumb.Item as={Link} href={href} active={active}>
  {text}
</Breadcrumb.Item>
```

error occurs to say Link didn't get href prop.

after looking through the source code, I found the `as` prop only applies for `li` component, so I have no way to replace the inside `a` tag with proper router link component.

see https://github.com/react-bootstrap/react-bootstrap/blob/master/src/BreadcrumbItem.js#L38

**Comment by taion** [comment]
Should we add like a `linkAs` prop here?

**Comment by zhaoyao91** [comment]
@taion I am not sure which way fits better into this project. `linkAs` may work well, but is it named properly thought the project? I don't know. Here is how reactstrap do:

https://reactstrap.github.io/components/breadcrumbs/

seems it can receive a `a` tag directly as a child.

**Comment by bpas247** [comment]
@taion 
> Should we add like a `linkAs` prop here?

I think that's most appropriate, looks like how Reactstrap is handling this use case is via [listTag prop](https://github.com/reactstrap/reactstrap/blob/45775c01da58e4e29d752367b43a730258398d78/src/Breadcrumb.js#L8). We'd essentially want to do something similar.

@zhaoyao91 
> I am not sure which way fits better into this project. `linkAs` may work well, but is it named properly thought the project? 

AFAIK we don't really use this pattern anywhere else? I think the naming is fine for now.

**Comment by jebarjonet** [comment]
What we could be doing here is:
```jsx
<Breadcrumb.Item>
  <Link to={url}>
    Test
  </Link>
</Breadcrumb.Item>
```
The problem is [adding a `SafeAnchor`](https://github.com/react-bootstrap/react-bootstrap/blob/master/src/BreadcrumbItem.js#L55) anytime the `Breadcrumb.Item` is not `active`, which feels like a shortcut to putting explicitly a link as child of `Breadcrumb.Item`.

**Comment by webcoderkz** [comment]
Do you plan to fix this?

**Comment by taion** [comment]
we'd be happy to take a PR to fix this

**Comment by jebarjonet** [comment]
@webcoderkz you need to add `active` to `<Breadcrumb.Item>` so it renders a `span` instead of a `a`

**Comment by webcoderkz** [comment]
@jebarjonet sorry, didn't noticed it. Thanks.
@taion How can we improve this? Maybe just remove an `<a>` from `<Breadcrumb.Item>`, because i see no reason to use just a simple link, many people are using react-router-dom.

**Comment by taion** [comment]
as stated, we should accept a `linkAs` prop

**Comment by oscarlofwenhamn** [comment]
I am having a hard time implementing this correctly; I thought the following would work after reading the thread above + #5043, and updating to react-bootstrap v1.2.2, but I keep getting "You must specify the "to" property".

```
<Breadcrumb.Item linkAs={Link} to="/">
  Home
</Breadcrumb.Item>
// Or
<Breadcrumb.Item as={Link} linkAs={Link} to="/">
  Home
</Breadcrumb.Item>
```

I'm obviously getting something wrong, are we still meant to do the `<Breadcrumb.Item active><Link to={url}>...` think to get this to work?

**Comment by kyletsang** [comment]
@oscarlofwenhamn The props for the `linkAs` component are passed using `linkProps`.

**Comment by oscarlofwenhamn** [comment]
@kyletsang Brilliant, thanks. I should have read the [docs](https://react-bootstrap.github.io/components/breadcrumb/#breadcrumb-item-props) more closely, works like a charm!

**Comment by iamajitsharma** [comment]
I was facing same issue as mentioned above. And finally i got solution for my project. 

 <Breadcrumb className="mb-0">
      {pathSegments.map((segment, index) => (
        <Breadcrumb.Item
          key={segment}
          active={index === pathSegments.length - 1}
          title={capitalizedWord(segment)}
          linkProps={{ className: index === 0 ? "text-inherit" : "" }}
          onClick={() => router.push(`/${segment}`)}
        >
          {capitalizedWord(segment)}
        </Breadcrumb.Item>
      ))}
    </Breadcrumb>
