### ISSUE TITLE
Hide carousel-controls if only one item is shown

### ISSUE THREAD

**Issue by markusdanek** [react-bootstrap/react-bootstrap#4477]
I am using the following components to display an image as a carousel:

```
<Carousel>
    <Carousel.Item key={image._id}>
        <AspectImage src={image.dataBase64} />
    </Carousel.Item>
</Carousel>
```

I am using the Carousel component because I am showing often more than five images but sometimes it occurs that only one image is available.

If this is the case, the carousel-controls are not needed and should be hidden.

**Comment by taion** [comment]
Pass in `controls={false}` per the docs.
