### ISSUE TITLE
Switches not working on Tag version v1.0.0-beta.12

### ISSUE THREAD

**Issue by Pulstura** [react-bootstrap/react-bootstrap#4478]
Produces the toggle, but the click functionality doesn't work.

`<Form.Check
    custom
    type="switch"
    id="custom-switch"
    label="Check this switch"
/>`

The documentation suggests the switch should work, but doesn't seem to work on the latest tag.

**Comment by taion** [comment]
Works fine in https://react-bootstrap.netlify.com/components/forms/#forms-custom-switch, which is against beta 12, which is latest.

**Comment by chuckmasucci** [comment]
As far as I can see, the TypeScript type definition file for handling the `type="Switch` is not there.

**Comment by Pulstura** [comment]
@taion On Master Branch the switch component is all there, but from the beta.12 tag it doesn't seem to be there. Also as mentioned from @chuckmasucci.

**Comment by mcverticchio** [comment]
Any update on including this?  I am having the same issues in my project.  Toggle is there, but no click functionality.

**Comment by sshishov** [comment]
Please reopen this issue as people experience the problem still...

**Comment by ChrisLau90** [comment]
I'm using version 1.0.0-beta.14 and this is still not working. I have tried to use `Form.Check type="switch"` as well as `Form.Switch`. The switch is displayed but the onChange function is not being called on click.
