### ISSUE TITLE
UseAccordionToggle for Typescript

### ISSUE THREAD

**Issue by vilianapetkovaIOS** [react-bootstrap/react-bootstrap#4488]
useAccordionToggle is available only for javascript, add also for typescript.

**Comment by taion** [comment]
it's exported in https://github.com/react-bootstrap/react-bootstrap/blob/21e145f366a6926d8089c1d809c88594e1e28540/types/components/AccordionToggle.d.ts#L10 and https://github.com/react-bootstrap/react-bootstrap/blob/21e145f366a6926d8089c1d809c88594e1e28540/types/components/index.d.ts#L32
