### ISSUE TITLE
Unable to set html size attribute on <FormControl as="select">

### ISSUE THREAD

**Issue by twheys** [react-bootstrap/react-bootstrap#4499]
## Describe the bug

The prop `size` on FormControl does not get set on the html element when using `as="select`. It is possible to set `multiple="true"` and use css to set the height, but it is not possible to have a single select that displays the options as a list rather than a dropdown.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#attr-size

## Reproducible Example

https://codesandbox.io/embed/condescending-surf-dvtyr 

## Expected behavior

The size attribute be passed to the html `select` element changing the behavior to a multi-line single value select

## Environment (please complete the following information)

- Operating System: [e.g. macOS]
- Browser, Version [e.g. Chrome 74]
- React-Bootstrap Version [e.g. 1.0.0-beta.8]

**Comment by bpas247** [comment]
That CodeSandbox link looks like a generic vanilla sandbox setup, could you please update it to showcase the issue?

**Comment by artygrand** [comment]
Still nothing fixed?

This 'size' cannot be passed
https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_select_size

**Comment by kosmiq** [comment]
You're welcome to create a pr fixing this. I do not know however how we would handle it with custom-select and the size prop that's already in use (never mind that the styling doesn't exist for this use case I think).

**Comment by artygrand** [comment]
I cannot fix it by myself, I just started using react. selectSize or htmlSize maybe should be translated to native size?

**Comment by kosmiq** [comment]
@jquense @taion I guess we should support this. It works with TWBS: https://codesandbox.io/s/nifty-kapitsa-qfrhx?file=/index.html

Do we call it htmlSize as suggested or something else?

**Comment by jquense** [comment]
htmlSize is fine yeah

**Comment by Exxenoz** [comment]
I need this feature for a project. Would be glad if I don't have to create a hacky workaround. htmlSize sounds just fine. 👍 😄

**Comment by jquense** [comment]
PR's welcome!

**Comment by kosmiq** [comment]
Yeah I haven't had as much time as I thought. I might be able to fix it later this week but we'll see.

Otherwise please do create a pr for it :)

**Comment by kyletsang** [comment]
Closing since `htmlSize` was already added

https://react-bootstrap.github.io/components/forms/#forms-custom-select
