### ISSUE TITLE
Radio Buttons Inside <Dropdown.Item> Do Not Update When State Changes

### ISSUE THREAD

**Issue by x-aaron-moore** [react-bootstrap/react-bootstrap#4501]
## Describe the bug

Clicking radio buttons inside dropdown items updates the active menu item but not the button itself.

## To Reproduce

 1. Click the dropdown button.
 2. Click the word "one" in the dropdown menu.
 3. Click the dropdown button again. Observe the radio next to "one" appears checked.
 4. Click the radio button next to "two" in the dropdown menu.
 5. Click the dropdown button a third time.

## Reproducible Example

I hope JSFiddle is alright. I had already built this reproducible example here before beginning this bug report: https://jsfiddle.net/blendersfun/Ld3zwj0x/15/

## Expected behavior

The radio button next to "two" should appear checked when opening the menu the third time. The old radio button still appears checked.

## Environment

- Operating System: macOS
- Browser: Chrome Version 76.0.3809.132
- React-Bootstrap Version [e.g. 1.0.0-beta.8]

## Additional context

A similar issue is described [here](https://github.com/facebook/react/issues/4930#issuecomment-142414999), however it's difficult to see how this could be a recurrence of the same issue. Also, it's unclear to me at this time whether this should be considered a React bug or a react-bootstrap bug.

**Comment by taion** [comment]
This is a bug in your code. You have a link wrapping an input, and the event on the input isn't propagating up to the link. But really you should just be rendering a `<label>` and putting the event on the input itself.

You'd end up with the same problem even without the dropdown, if you were rendering a bunch of anchors with inputs inside.
