### ISSUE TITLE
Option to copy import statement on click 

### ISSUE THREAD

**Issue by kushmisra** [react-bootstrap/react-bootstrap#4502]
## Feature request
While users go through the documentation and components which they need to use in their projects, they want to quickly copy the import statement. Currently, import statements required are explicitly mentioned but there is no easy way to copy them.

## Solution
 We should add a small icon there clicking to which, will copy the import statements. 

## Additional context
I will like to take up this addition.

**Comment by bpas247** [comment]
closed by #4546
