### ISSUE TITLE
sliding direction of Carousel with 2 items not working properly

### ISSUE THREAD

**Issue by Bang9** [react-bootstrap/react-bootstrap#4504]
## Describe the bug
sliding direction of Carousel with 2 items not working properly
only not working proper when Carousel has 2 items

## To Reproduce
1. make Carousel with 2 items
2. sliding to first item when second item is current

## Reproducible Example
```jsx
<Carousel>
  <Carousel.Item>
    <div style={{width:100, height:100, backgroundColor:'blue'}} />
  </Carousel.Item>
  <Carousel.Item>
    <div style={{width:100, height:100, backgroundColor:'red'}} />
  </Carousel.Item>
</Carousel>
```

## Expected behavior
`first item` -> `second item` : left to right sliding
`second item` -> `first item` : right to left sliding

## Actual behavior
`first item` -> `second item` : left to right sliding
`second item` -> `first item` : left to right sliding

## Environment (please complete the following information)

    "react": "^16.9.0"
    "bootstrap": "^4.3.1"
    "react-bootstrap": "^1.0.0-beta.12"

**Comment by taion** [comment]
gDSFP here needs to account for the explicit direction. it's not doing so right now
