### ISSUE TITLE
auto placement

### ISSUE THREAD

**Issue by stopachka** [react-bootstrap/react-bootstrap#451]
Hey everyone, I saw recently that the placement prop over `OverlayTrigger` only accepts `top`, `bottom`, `left`, or `right`.

Bootstrap also has `auto`, and `{left,top,bottom,right} auto`. Why not include this? (If we want to add this in a pr, let's discuss strategy and I'd be happy to pop one in)

**Comment by mtscout6** [comment]
I assume you are referring to this: http://getbootstrap.com/javascript/#popovers-options.

This would be a welcomed addition.

**Comment by stopachka** [comment]
Cool :). Will try to pop in a diff this weekend.

**Comment by stevenpietzsch** [comment]
Any ideas someone? :)

**Comment by jquense** [comment]
@stopachka ideas for what? You are welcome to submit a PR adding this if you want it :) though now that would go to react-overlays

**Comment by leojh** [comment]
anyone have any tips on how to deal with this problem?

**Comment by jquense** [comment]
>  You are welcome to submit a PR adding this if you want it :) though now that would go to react-overlays

**Comment by leojh** [comment]
In case it may be helpful for anyone, I ended up ditching `Overlay` altogether and doing my own rudimentary one using `RootCloseWrapper` and passing it a calculated left offset into the div so it doesn't go off the screen.

```
<RootCloseWrapper onRootClose={() => this.closeCriteriaForm(criterion)}>
  <div className="popup" style={style}>
    {this.buildComponent()}
  </div>
</RootCloseWrapper>
```

Also, the code to implement `auto` placement would go in `react-overlays/src/utils/overlayPositionUtils.js`

**Comment by isaachinman** [comment]
@jquense Still accepting PRs for this?

**Comment by niknokseyer** [comment]
I'm trying to trace this one as well.

So far here's what I found in the logic of doing the auto placement from *bootstrap.js*:

```
...

var autoToken = /\s?auto?\s?/i
      var autoPlace = autoToken.test(placement)
      if (autoPlace) placement = placement.replace(autoToken, '') || 'top'

...

if (autoPlace) {
        var orgPlacement = placement
        var viewportDim = this.getPosition(this.$viewport)

        placement = placement == 'bottom' && pos.bottom + actualHeight > viewportDim.bottom ? 'top'    :
                    placement == 'top'    && pos.top    - actualHeight < viewportDim.top    ? 'bottom' :
                    placement == 'right'  && pos.right  + actualWidth  > viewportDim.width  ? 'left'   :
                    placement == 'left'   && pos.left   - actualWidth  < viewportDim.left   ? 'right'  :
                    placement

        $tip
          .removeClass(orgPlacement)
          .addClass(placement)
      }

...
```

**Comment by niknokseyer** [comment]
Do you have a fork / pull request on this @isaachinman / @leojh? I can help in testing. @jquense

**Comment by isaachinman** [comment]
@niknokseyer I believe @jquense's point was that any future PR should go to [react-overlays](https://github.com/react-bootstrap/react-overlays).

**Comment by aaronbeall** [comment]
Would love to see this. Solved it in my project using `getBoundingClientRect()` but not generically enough for this library... will the `react-bootstrap` v4 have this?
