### ISSUE TITLE
Reactifying Bootstrap Extensions

### ISSUE THREAD

**Issue by adamdaw** [react-bootstrap/react-bootstrap#452]
Thanks for all the hard work on this! 

I'm looking to implement some bootstrap extensions into my react app and was wondering if there were any tips/guidelines you've found in your work for extending bootstrap extensions into the react framework.

**Comment by mtscout6** [comment]
I'm not sure I entirely understand what it is you are asking for. If you're looking for recommendations on what we've learned you can read the closed issues and pull requests to see the discussion that took place for various parts of this framework. If you're looking for guidance on a specific bootstrap extension than bring it to the table so there is something concrete to talk about.

**Comment by dozoisch** [comment]
This issue is pretty stale, so I'll close it for the time being. Feel free to reopen.
