### ISSUE TITLE
Button: prop type `componentClass` is invalid; React 0.12.0, React-Bootstrap 0.17.0

### ISSUE THREAD

**Issue by AdamKyle** [react-bootstrap/react-bootstrap#454]
Upon loading the page I get:

`Uncaught Error: Invariant Violation: Button: prop type `componentClass` is invalid; it must be a function, usually from React.PropTypes.`

The exact area to look at is:

```js
var Button = React.createClass({displayName: "Button",
  mixins: [BootstrapMixin],

  propTypes: {
    active:   React.PropTypes.bool,
    disabled: React.PropTypes.bool,
    block:    React.PropTypes.bool,
    navItem:    React.PropTypes.bool,
    navDropdown: React.PropTypes.bool,
    componentClass: React.PropTypes.node, // This is invalid.
    href: React.PropTypes.string,
    target: React.PropTypes.string
  },

...
```

The page does not even load because of this error. I do not directly use this Button class any where in my code, I construct my buttons from Twitter Bootstrap it's self, as none of them directly use JavaScript. How ever I do use modals on the page I am trying to load, which do use the Button class:

`<ReactBootstrap.Button onClick={this.props.onRequestHide} className="btn btn danger">Close</ReactBootstrap.Button>`

Which is taken from the [Live Demo](http://react-bootstrap.github.io/components.html#modals) section of the modals documentation.

**Comment by mtscout6** [comment]
We've moved on to React 0.13 as of 0.18.0. Do you still encounter this issue on the latest versions?
