### ISSUE TITLE
Panel with heading problem

### ISSUE THREAD

**Issue by neilyoung** [react-bootstrap/react-bootstrap#4557]
## Describe the bug

I get an error at run time

> Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
> 
> Check the render method of `App`.
> 

## To Reproduce

https://codesandbox.io/s/clever-fire-eez3v

## Expected behavior

Shouldn't give an error I would say, it's basically your sample code (panel with heading) https://react-bootstrap-v3.netlify.com/components/panel/

## Environment (please complete the following information)

 Operating System: macOS
- Browser, Version: Chrome 77, Firefox 69
- React-Bootstrap Version: 0.31.5
- React: 16.8.6 and higher

As far as I know it worked in earlier versions of React (e.g. 16.4.1), but also not in 16.9.0

**Comment by taion** [comment]
The docs are for 0.32.x. The API you're trying to use is not available in 0.31.x.

**Comment by neilyoung** [comment]
Right. Noticed it a minute after writing. Thanks
