### ISSUE TITLE
spread parameter produces a type error ??

### ISSUE THREAD

**Issue by saher-elgendy** [react-bootstrap/react-bootstrap#4558]
This always works for me but for some reason, it does not work in my react-bootstrap component and this is confusing:

Code

```
const ReusableDropdown = ({classes, ...props}) => {
    return(
        <Dropdown>
            <Dropdown.Toggle 
                className={`dropdown-toggler ${classes.toggler}`}
            >
                {props.togglerText}
            </Dropdown.Toggle>
            <Dropdown.Menu 
                className={`dropdown-menu ${classes.menu}`}
            >
                {props.children}
            </Dropdown.Menu>
        </Dropdown>
    );
}
```
Just importing that component produced a type error and react says that the error happens in the component itself not inside the parent component:

```
./src/reusable/dropdown.js
TypeError: Cannot read property 'forEach' of undefined
```
This should work and i am sure the error has no relation to the syntax as it still works in my previous projects??

**Comment by mxschmitt** [comment]
Please try to create a minimal example by using [CodeSandbox](https://codesandbox.io/s/github/react-bootstrap/code-sandbox-examples/tree/master/basic).

**Comment by saher-elgendy** [comment]
it does work well in code sandbox, but it does not work on my machine, i created several demo projects and uninstalled all packages that may affect code, till i reached to the point of a very basic demo project and still the problem exist can i send the folder of the demo project to you?? @mxschmitt

**Comment by saher-elgendy** [comment]
After many hours debugging that seems that there is no errors in react-bootstrap component but the problem is is the newer version of react that cause that type of build errors the solution can be by downgrading to 3.1.1 react-scripts version or by adding that line to package.json:

```
"resolutions": {
    "eslint-loader": "3.0.2"
  }
```

**Comment by bpas247** [comment]
If there are no issues with R-B here, I'm gonna go ahead and close it :)
