### ISSUE TITLE
Dropdown onSelect must be assigned in order for dropdown to close when item is selected

### ISSUE THREAD

**Issue by bdefore** [react-bootstrap/react-bootstrap#456]
Would be nice if this would close after an item is selected by default, similar to Bootstrap behavior. Am I misunderstanding the API? I'm currently working around with an empty anonymous function.

```
<DropdownButton onSelect={->} title="Bar">
  <MenuItem onClick={@onMenuItemClickHandler}>Foo</MenuItem>
</DropdownButton>
```

**Comment by mtscout6** [comment]
Something to consider in #419

**Comment by AlexKVal** [comment]
Superceded by #526 and #419

**Comment by web2style** [comment]
@AlexKVal What "superceded" means? Can't understand.

**Comment by mtscout6** [comment]
It means that this issue will be dealt with in #526

**Comment by web2style** [comment]
@mtscout6 Thank you.
