### ISSUE TITLE
Import react-bootstrap 1.0.0-beta.13 Module not found: Can't resolve 'react-bootstrap'

### ISSUE THREAD

**Issue by xAgustin93** [react-bootstrap/react-bootstrap#4576]
## Describe the bug
When importing react-bootstrap returns the error Module not found: Can't resolve 'react-bootstrap' in the version 1.0.0-beta.13.

In the version 1.0.0-beta.12 everything works well

## To Reproduce
yarn add react-bootstrap

Open react componente and import one componen the react-bootstrap.
import { Container } from "react-bootstrap";

## Reproducible Example

Example in [CodeSandbox](https://codesandbox.io/s/rough-glitter-2fl8d).

**Comment by taion** [comment]
@jquense file-butler appears to not be buttle-ing `index.js`... is there a config option we're missing here?

**Comment by taion** [comment]
FWIW we strongly recommend using imports like

```js
import Foo from 'react-bootstrap/Foo';
```

which should still work

**Comment by xAgustin93** [comment]
Yes taion the imports if they work 
import Foo from 'react-bootstrap/Foo';

but if you want to use more components it's more comfortable to do it the other way
import { Container, Row, Col, Spinner } from 'react-bootstrap';

I think they must work both ways

**Comment by bgok** [comment]
> FWIW we strongly recommend using imports like
> 
> ```js
> import Foo from 'react-bootstrap/Foo';
> ```
> 
> which should still work

Unfortunately, the alternate import format doesn't work either.

**Comment by taion** [comment]
works fine for me: https://codesandbox.io/embed/ecstatic-water-npx6s

**Comment by taion** [comment]
fix released in beta 14
