### ISSUE TITLE
Cover using Sass in "stylesheets" section of "Getting Started" guide

### ISSUE THREAD

**Issue by matthewkwong2** [react-bootstrap/react-bootstrap#4578]
My apologies for posting this as a bug.

Yet I would like to know is there a way to simply customize the theme colour variants (i.e. 'primary', 'secondary', 'success', 'danger', 'warning', 'info', 'dark', 'light', 'link') globally without specifying it for every type of components?

In pure bootstrap, we can do something like this in scss
```Scss
$theme-colors: (
  "primary": #0074d9,
  "danger": #ff4136
);
```

Not sure whether it works the same for `react-bootstrap` since it is reimplemented. Or is there a more elegant way to do so?

Edit:
After scrolling through previous posts, it seems that it is possible to change the theme colours by overriding the `$theme-colors` map in a custom `scss` file and import it in `index.js`. Perhaps it should be mentioned or referenced in the document?  For me, this looks like a common approach to customize the UI.

**Comment by taion** [comment]
R-B only touches the JS, not the CSS. You can do whatever you want to build the CSS. It's orthogonal to your use of R-B.

It could be good to expand the stylesheet section, though. I'll update the issue title accordingly.

**Comment by luisFilipePT** [comment]
Hi guys, hope you don't mind, created a PR for this ☝️ 

Any changes or improvements just let me know

Keep up the amazing work 🎉 🙌

**Comment by kyletsang** [comment]
Closing since this has been added:

https://react-bootstrap.github.io/getting-started/introduction#sass
