### ISSUE TITLE
v0.19.0 CollapsableNav missing in top-level namespace

### ISSUE THREAD

**Issue by yourcelf** [react-bootstrap/react-bootstrap#459]
in v0.18.0, this worked to get a reference to ``CollapsableNav``.

    var CollapsableNav = require("react-bootstrap").CollapsableNav;

in v0.19.0, that value is undefined.  ``CollapsableNav`` is not referenced in ``src/main.js``.

I notice that the specs all use internal paths to retrieve their components.  It might be worth having a test that exercises the namespace as library users are expected to use it, just to make sure the references are maintained.

**Comment by mtscout6** [comment]
Ah, thanks. That was missed when I merged the updates from master to the new ES6 changes. I'll fix that real quick.
