### ISSUE TITLE
Docs should not have any references to "stateless" function components

### ISSUE THREAD

**Issue by bpas247** [react-bootstrap/react-bootstrap#4598]
## Describe the bug

"stateless" function components is an incorrect way to describe function components, so we should omit that terminology from our docs.

## To Reproduce

1. Go to [Overlay Trigger example docs](https://react-bootstrap.github.io/components/overlays/#overlay-trigger)
2. Observe that it describes the component to use as a "stateless function component".

## Expected behavior

We should just omit "stateless" and describe them as "function components".

## Additional context

We might need to look through more of the docs to ensure we aren't using this terminology anywhere else.

**Comment by fr-ser** [comment]
I think this is a good idea. Especially with "hooks" in react, when function component can actually use state...

I looked through the repo but only found two occurrences...

**Comment by taion** [comment]
fixed in #4601
