### ISSUE TITLE
Flux Integration

### ISSUE THREAD

**Issue by itsjms** [react-bootstrap/react-bootstrap#461]
I think it would be great if this was (or could be) easily tied in with Flux. Any thoughts?

**Comment by mtscout6** [comment]
In what ways are you seeing that it does not work with Flux? Or what suggestions do you have? This library is primarily a number of building blocks which I envision would be used by a parent component that would deal with Flux integration.

**Comment by taion** [comment]
Most of the newer Flux libraries use containers to inject props from Stores now, and any of these components can be wrapped in a container. I don't see how there's anything more to be done here, so I'm closing this for now. Please let me know if there's anything I'm missing.
