### ISSUE TITLE
Attempted import error:

### ISSUE THREAD

**Issue by TatsianaMark** [react-bootstrap/react-bootstrap#4610]
./src/components/Layout.js
Attempted import error: 'Container' is not exported from 'react-bootstrap'.

How fixed it?

**Comment by bpas247** [comment]
@TatsianaMark could you reproduce this issue in a [CodeSandbox](https://codesandbox.io/s/github/react-bootstrap/code-sandbox-examples/tree/master/basic)?

**Comment by TatsianaMark** [comment]
https://codesandbox.io/s/react-bootstrap-55z46

**Comment by taion** [comment]
you're trying to import from `bootstrap` in your example, not `react-bootstrap`
