### ISSUE TITLE
Add an About section to the website

### ISSUE THREAD

**Issue by bpas247** [react-bootstrap/react-bootstrap#4624]
## Is your feature request related to a problem? Please describe

It would be nice if we shared a little bit about the team (and our fantastic community of contributors 🎉) that has made this library the way it is :) the [upstream docs](https://getbootstrap.com/docs/4.3/about/overview/) has a good example of what we could include in our own about section.

## Describe the solution you'd like

Add an "About" section to our website. Possible sub-sections include:
- Team (what is our core structure? whom does it consist of?)
- History (where did this all start?)
- Contributors (outside of the internal team, who else is involved?)
- Get involved (where should we be redirecting potential new contributors so that they can start getting involved themselves?)

## Describe alternatives you've considered

Other sub-sections could include:
- Sponsorships (we currently aren't accepting any funding what so ever, but that could change 😉 if it does then we should make it transparent as to where people could send funding).
- External links to libraries within the React Bootstrap ecosystem.

**Comment by Nerocodes** [comment]
Can I be assigned to this? Also, will the information for each of the sections be provided?

**Comment by bpas247** [comment]
> Can I be assigned to this?

sure thing 👍

> Also, will the information for each of the sections be provided?

I would need to hold an internal discussion with the other maintainers regarding the "history" section, but there should be enough information floating around to get started on the rest of the sections 😃 but please feel free to ping me anytime if you have any questions!

**Comment by bpas247** [comment]
#4665 closes this, will open another issue to track the progress of the history section.
