### ISSUE TITLE
OverlayTrigger and parent-based contexts

### ISSUE THREAD

**Issue by taion** [react-bootstrap/react-bootstrap#465]
OverlayTrigger renders the overlay element into a new `<div />`, by default under `document.body`. When used with react-router, the overlay element is no longer a child of the overall router... things. This means that the overlay element does not receive the parent-based router context.

This is currently only causing a warning in React 0.13, so it's not urgent, but it could be a problem down the road for people who want to use components that want to access e.g. router context within an overlay.

**Comment by mtscout6** [comment]
Thanks for opening an issue on this, one of the devs in my shop brought this to my attention last week. I can't say that I have a solution figured out yet.

**Comment by taion** [comment]
The best I can think of is something like this

```jsx
<OverlayTrigger
  overlayHolder={() => this._overlayHolder}
>
  <Button {...} />
</OverlayTrigger>

<OverlayHolder
  ref={component => this._overlayHolder = component}
>
  <Popover {...} />
</OverlayHolder>
```

Where `OverlayHolder` is a size-0 div or something, and `OverlayTrigger` calls `setState` on the `OverlayHolder` to get it to display the overlay element.

**Comment by taion** [comment]
Rather:

```jsx
<OverlayHolder
  ref={component => this._overlayHolder = component}
  overlay={<Popover {...} />}
/>
```

like the current syntax, so it doesn't look like the overlay is getting rendered when it's not active.

This is morally the same as what's happening right now, except (when needed) the user explicitly sets the parent element of the overlay, and has it all be within the React element hierarchy. This is cumbersome enough that I'd only want to use this when I care about preserving context, but I don't see another way to do this, given that you can't actually render anything but the wrapped element in `OverlayTrigger` without breaking formatting.

**Comment by taion** [comment]
On thinking of this again, what I have above is probably just dumb.

What do you think about having `OverlayTrigger` explicitly take a context object to forward down to the rendered overlay?

**Comment by mtscout6** [comment]
That would be simple and worth it. I would not want to document this feature though until React actually "officially" releases context support and documentation.

**Comment by taion** [comment]
Do you think it might be worth exposing a special variant of OverlayTrigger in react-router-bootstrap that forwards the router context? @ryanflorence mentioned that they were working on removing the dependency on context, but it'd be useful to have an at least somewhat-documented way to access router context from popovers.

**Comment by mtscout6** [comment]
For react-router-bootstrap I'd be fine with a wrapper that could do that, or at least a mention in its readme.

**Comment by taion** [comment]
I think the wrapper would be worth adding, because I expect this to be the most common use case. I'll take a stab at this.

**Comment by chrisbianca** [comment]
The other use case I've come up against is react-intl (http://formatjs.io/react/) which relies on the context storing locales, messages and formats to allow internationalization of React apps.

It would be good if this wasn't fixed with just react-router in mind.

**Comment by taion** [comment]
@chrisbianca The undocumented fix in react-bootstrap will not be restricted to react-router. I'm just talking about adding an extra convenience thing in react-router-bootstrap. There's no principled way to do this for react-intl in either library, but nothing will stop you from just passing in context to `OverlayTrigger` (v. using `RouterOverlayTrigger` or whatever that does it for you).

**Comment by taion** [comment]
Looking at the implementation, this is actually really nasty. `childContextTypes` and `contextTypes` are a static properties of component classes, so there isn't a good way to dynamically set them based on e.g. some `contextTypes` prop passed into `OverlayTrigger`.

It's nasty enough that I think this should be a wontfix, and that I should add instead a `PopoverWithRouterContext` (or something better-named) to react-router-bootstrap.

**Comment by taion** [comment]
Thought of a reasonable way to do this.
