### ISSUE TITLE
OverlayTrigger Tooltip dynamical change position depends on viewport

### ISSUE THREAD

**Issue by palaniichukdmytro** [react-bootstrap/react-bootstrap#4652]
I'm using OverlayTrigger, Tooltip from react-bootstrap, and whant to change tooltip position depens on viewport. Because now I have default placement right, but when I test it on iphoneX (375px) it's not working, I suppose cuz of not enough space to render. How to do this automaticaly update on small screen.

For LONGTextLon does not work:

```
const CustomTooltip = ({ placement = 'right', text = null }) => {
    return (
        <OverlayTrigger
            placement={placement}
            popperConfig={{
                modifiers: {
                    // preventOverflow: {
                    //     enabled: true
                    //     // priority: ['top', 'right'],
                    //     // boundariesElement: 'viewport'
                    // }
                }
            }}
            overlay={
                <Tooltip>
                    <div className="tc-text">{text}</div>
                </Tooltip>
            }
        >
                <Icon/>
        </OverlayTrigger>
    );
};
```

Current state: does not change position automativcaly when not enouph space Expected: flip or change position to 'bottom' depends on viewport or space
![Screenshot_3](https://user-images.githubusercontent.com/14881178/66570799-f6281100-eb76-11e9-9ca1-52cc8455ba7a.png)

**Comment by taion** [comment]
set placement to `auto`

**Comment by palaniichukdmytro** [comment]
@taion the `auto` it's not quite what I want, `auto` is unpredictable. I would like to show on right side all time until enough space

**Comment by taion** [comment]
we're just following bootstrap here: https://getbootstrap.com/docs/4.3/components/tooltips/#options

you may be able to opt into deeper popper options yourself, especially with the underlying react-overlays API
