### ISSUE TITLE
How to access to original HTML DOM and property?

### ISSUE THREAD

**Issue by gamesover** [react-bootstrap/react-bootstrap#4667]
This lib works perfectly in most cases. However, in some few cases, I need to access to original html dom elements and/or use jquery to access to properties. How can I do that?

```
<FormGroup controlId="formControlsTextarea" ref={this.ref}>
      <ControlLabel>Textarea</ControlLabel>
      <FormControl componentClass="textarea" placeholder="textarea" />
    </FormGroup>
```
For the above code, `this.ref.current` still give me `FormGroup`, which is react-bootstrap component, not original vanilla html element, so that I can use jquery to access to `prop('selectionStart')` :(

Now, I need to implement a feature that insert some string for cursor location in the textarea. I don't know how to achieve that in react way. Only know how to do that in jquery way.

**Comment by kosmiq** [comment]
No feedback for more than 7 days. Closing.
