### ISSUE TITLE
Integrate with bootlint

### ISSUE THREAD

**Issue by mtscout6** [react-bootstrap/react-bootstrap#468]
https://github.com/twbs/bootlint

No details on how to do this yet, but would be incredibly useful to integrate into our build pipeline at some point.

**Comment by slonoed** [comment]
@mtscout6 maybe just check documentation page with this tool?

**Comment by mtscout6** [comment]
That may get us a lot of benefit though I don't know if it would be complete. Definitely worth looking at at some point.

**Comment by taion** [comment]
I just did a quick check of the components page, and with the default settings, almost all of the errors and warnings were false positives.

We can e.g. add manual checks, but I'm not sure it'd be worth the effort to add this to our build pipeline. We'd spend a lot of effort disable all the checks we didn't need, and I don't recall any instances where we had issues arising from messing this up.

**Comment by taion** [comment]
And it doesn't capture weird things like `nav > nav` that we have right now for `<Navbar>` and `<Nav>`. Plus React 14 checks validity of DOM nesting anyway.

Going to close this out for the time being - will reopen if there are objections.
