### ISSUE TITLE
Feature request: TabbedArea with stacked pills

### ISSUE THREAD

**Issue by sam-perez** [react-bootstrap/react-bootstrap#469]
I was wondering if there is a way to create stacked tabs (tabs using a stacked nav on either the left or the right of the content as opposed to being on top of the content).

If not, are there any plans to include this feature in the future?

**Comment by mtscout6** [comment]
http://react-bootstrap.github.io/components.html#navs See the Stacked section and change the code example on the site to use `bsStyle='tabs'`.

![](http://cl.ly/image/460I180j0v41/Image%202015-04-01%20at%208.19.20%20PM.png)

The styling is off, though bootstrap doesn't show such either: http://getbootstrap.com/components/#nav

**Comment by sam-perez** [comment]
I think there may have been a bit of a miscommunication here, I should have been clearer with my question.

I was talking about the TabbedArea and TabPane components. I'd like to have the nav div that is generated by the TabbedArea to be stacked pills (which you can currently achieve by passing stacked as a prop above as you have shown), but then apply a column width to the nav element containing the tab options and a column width to the tab-content div so that the pills are to the left (or the right) of the tab contents as defined by the TabPanes.

I'm not sure if this is supported by the TabbedArea component after taking a short glance at the code.

**Comment by rkiel** [comment]
We had this exact need.  We modified <TabbedArea> to support 2 optional props: navGrid & paneGrid. For example:

<TabbedArea navGrid={{xs:2,sm:4}} paneGrid={{xs:10,sm:8}} bsStyle='pills' stacked>
  <TabPane tab='Foo'> blah blah </TabPane>
  <TabPane tab='Bar'> blah blah </TabPane>
</TabbedArea>

The result would be the "nav" stuff wrapped in a <div className="col-xs-2 col-sm-4"> and the other generated div would include classname="tab-content col-xs-10 col-sm-8".  Of course, if you leave off the 2 props, then TabbedArea works like it did before.

Would be willing to help by submitting a pull-request.

**Comment by AlexKVal** [comment]
/cc @react-bootstrap/collaborators 
Do we OK with proposed API for this feature `navGrid={{xs:2,sm:4}} paneGrid={{xs:10,sm:8}}` ?
```jsx
<TabbedArea navGrid={{xs:2,sm:4}} paneGrid={{xs:10,sm:8}} bsStyle='pills' stacked>
```
What do you think ?
While I'm working with TabbedArea I may try to implement it, 
or even @rkiel maybe did not lose the wish for making PR yet.

**Comment by taion** [comment]
Superseded by #1111.
