### ISSUE TITLE
Migrate the testing suite to RTL

### ISSUE THREAD

**Issue by bpas247** [react-bootstrap/react-bootstrap#4693]
**Disclaimer** There is nothing wrong with using Enzyme, this issue is not about Enzyme being a "bad" tool to use. On the contrary, we've used Enzyme for a long time and It's done really well for us in the past.

## Is your feature request related to a problem? Please describe

Currently, all of our unit testing is using Enzyme. Enzyme has worked great for us, but here are some reasons as to why we should migrate to RTL:
- Avoid [testing implementation details](https://kentcdodds.com/blog/testing-implementation-details) altogether.
- [React's official docs](https://reactjs.org/docs/testing.html#tools) recommends using RTL.
- Easier for testers to contribute to our testing suite, due to RTL being a more common pattern than Enzyme.
- The React community seems like it's generally migrating over to RTL, so we should join in on the fun 😎 
## Describe the solution you'd like

Migrate our testing suite from Enzyme, to React-Testing-Library. The tests that need to be migrated are:

**Note**: There is a *very* good chance that I might've missed a test file when compiling this list. If there's any test files I'm missing, please let me know 😃 

- [ ] [AccordionSpec](https://github.com/react-bootstrap/react-bootstrap/blob/master/test/AccordionSpec.js)
- [ ] [AccordionToggleSpec](https://github.com/react-bootstrap/react-bootstrap/blob/master/test/AccordionToggleSpec.js)
- [ ] [AlertSpec](https://github.com/react-bootstrap/react-bootstrap/blob/master/test/AlertSpec.js)
- [ ] [BadgeSpec](https://github.com/react-bootstrap/react-bootstrap/blob/master/test/BadgeSpec.js)
- [ ] [BreadcrumbItemSpec](https://github.com/react-bootstrap/react-bootstrap/blob/master/test/BreadcrumbItemSpec.js)
- [ ] [BreadcrumbSpec](https://github.com/react-bootstrap/react-bootstrap/blob/master/test/BreadcrumbSpec.js)
- [ ] [ButtonGroupSpec](https://github.com/react-bootstrap/react-bootstrap/blob/master/test/ButtonGroupSpec.js)
- [ ] [ButtonSpec](https://github.com/react-bootstrap/react-bootstrap/blob/master/test/ButtonSpec.js)
- [ ] [ButtonToolbarSpec](https://github.com/react-bootstrap/react-bootstrap/blob/master/test/ButtonToolbarSpec.js)
- [ ] [CardImgSpec](https://github.com/react-bootstrap/react-bootstrap/blob/master/test/CardImgSpec.js)
- [ ] [CardSpec](https://github.com/react-bootstrap/react-bootstrap/blob/master/test/CardSpec.js)
- [ ] [CarouselCaptionSpec](https://github.com/react-bootstrap/react-bootstrap/blob/master/test/CarouselCaptionSpec.js)
- [ ] [CarouselSpec](https://github.com/react-bootstrap/react-bootstrap/blob/master/test/CarouselSpec.js)
- [ ] [CloseButton](https://github.com/react-bootstrap/react-bootstrap/blob/master/test/CloseButton.js) (this one seems like a special case test, since it's not using Enzyme)
- [ ] [ColSpec](https://github.com/react-bootstrap/react-bootstrap/blob/master/test/ColSpec.js)
- [ ] [CollapseSpec](https://github.com/react-bootstrap/react-bootstrap/blob/master/test/CollapseSpec.js)
- [ ] [ContainerSpec](https://github.com/react-bootstrap/react-bootstrap/blob/master/test/ContainerSpec.js)
- [ ] [DropdownButtonSpec](https://github.com/react-bootstrap/react-bootstrap/blob/master/test/DropdownButtonSpec.js)
- [ ] [DropdownItemSpec](https://github.com/react-bootstrap/react-bootstrap/blob/master/test/DropdownItemSpec.js)
- [ ] [DropdownMenuSpec](https://github.com/react-bootstrap/react-bootstrap/blob/master/test/DropdownMenuSpec.js)
- [ ] [DropdownSpec](https://github.com/react-bootstrap/react-bootstrap/blob/master/test/DropdownSpec.js)
- [ ] [DropdownToggleSpec](https://github.com/react-bootstrap/react-bootstrap/blob/master/test/DropdownToggleSpec.js)
- [ ] [FadeSpec](https://github.com/react-bootstrap/react-bootstrap/blob/master/test/FadeSpec.js)
- [ ] [FeedbackSpec](https://github.com/react-bootstrap/react-bootstrap/blob/master/test/FeedbackSpec.js)
- [ ] [FigureCaptionSpec](https://github.com/react-bootstrap/react-bootstrap/blob/master/test/FigureCaptionSpec.js)
- [ ] [FigureSpec](https://github.com/react-bootstrap/react-bootstrap/blob/master/test/FigureSpec.js)
- [ ] [FormCheckSpec](https://github.com/react-bootstrap/react-bootstrap/blob/master/test/FormCheckSpec.js)
- [ ] [FormControlFeedbackSpec](https://github.com/react-bootstrap/react-bootstrap/blob/master/test/FormControlFeedbackSpec.js)
- [ ] [FormControlSpec](https://github.com/react-bootstrap/react-bootstrap/blob/master/test/FormControlSpec.js)
- [ ] [FormGroupSpec](https://github.com/react-bootstrap/react-bootstrap/blob/master/test/FormGroupSpec.js)
- [ ] [FormLabelSpec](https://github.com/react-bootstrap/react-bootstrap/blob/master/test/FormLabelSpec.js)
- [ ] [FormSpec](https://github.com/react-bootstrap/react-bootstrap/blob/master/test/FormSpec.js)
- [ ] [FormTextSpec](https://github.com/react-bootstrap/react-bootstrap/blob/master/test/FormTextSpec.js)
- [ ] [ImageSpec](https://github.com/react-bootstrap/react-bootstrap/blob/master/test/ImageSpec.js)
- [ ] [InputGroupSpec](https://github.com/react-bootstrap/react-bootstrap/blob/master/test/InputGroupSpec.js)
- [ ] [JumbotronSpec](https://github.com/react-bootstrap/react-bootstrap/blob/master/test/JumbotronSpec.js)
- [ ] [ListGroupItemSpec](https://github.com/react-bootstrap/react-bootstrap/blob/master/test/ListGroupItemSpec.js)
- [ ] [ListGroupSpec](https://github.com/react-bootstrap/react-bootstrap/blob/master/test/ListGroupSpec.js)
- [ ] [MediaBodySpec](https://github.com/react-bootstrap/react-bootstrap/blob/master/test/MediaBodySpec.js)
- [ ] [MediaSpec](https://github.com/react-bootstrap/react-bootstrap/blob/master/test/MediaSpec.js)
- [ ] [ModalBodySpec](https://github.com/react-bootstrap/react-bootstrap/blob/master/test/ModalBodySpec.js)
- [ ] [ModalFooterSpec](https://github.com/react-bootstrap/react-bootstrap/blob/master/test/ModalFooterSpec.js)
- [ ] [ModalHeaderSpec](https://github.com/react-bootstrap/react-bootstrap/blob/master/test/ModalHeaderSpec.js)
- [ ] [ModalSpec](https://github.com/react-bootstrap/react-bootstrap/blob/master/test/ModalSpec.js)
- [ ] [ModalTitleSpec](https://github.com/react-bootstrap/react-bootstrap/blob/master/test/ModalTitleSpec.js)
- [ ] [NavDropdownSpec](https://github.com/react-bootstrap/react-bootstrap/blob/master/test/NavDropdownSpec.js)
- [ ] [NavItemSpec](https://github.com/react-bootstrap/react-bootstrap/blob/master/test/NavItemSpec.js)
- [ ] [NavLinkSpec](https://github.com/react-bootstrap/react-bootstrap/blob/master/test/NavLinkSpec.js)
- [ ] [NavSpec](https://github.com/react-bootstrap/react-bootstrap/blob/master/test/NavSpec.js)
- [ ] [NavbarBrandSpec](https://github.com/react-bootstrap/react-bootstrap/blob/master/test/NavbarBrandSpec.js)
- [ ] [NavbarSpec](https://github.com/react-bootstrap/react-bootstrap/blob/master/test/NavbarSpec.js)
- [ ] [NavbarToggleSpec](https://github.com/react-bootstrap/react-bootstrap/blob/master/test/NavbarToggleSpec.js)
- [ ] [OverlayTriggerSpec](https://github.com/react-bootstrap/react-bootstrap/blob/master/test/OverlayTriggerSpec.js)
- [ ] [PageItemSpec](https://github.com/react-bootstrap/react-bootstrap/blob/master/test/PageItemSpec.js)
- [ ] [PaginationSpec](https://github.com/react-bootstrap/react-bootstrap/blob/master/test/PaginationSpec.js)
- [ ] [PopoverSpec](https://github.com/react-bootstrap/react-bootstrap/blob/master/test/PopoverSpec.js)
- [ ] [ProgressBarSpec](https://github.com/react-bootstrap/react-bootstrap/blob/master/test/ProgressBarSpec.js)
- [ ] [ResponsiveEmbedSpec](https://github.com/react-bootstrap/react-bootstrap/blob/master/test/ResponsiveEmbedSpec.js)
- [ ] [RowSpec](https://github.com/react-bootstrap/react-bootstrap/blob/master/test/RowSpec.js)
- [ ] [SafeAnchorSpec](https://github.com/react-bootstrap/react-bootstrap/blob/master/test/SafeAnchorSpec.js)
- [ ] [SpinnerSpec](https://github.com/react-bootstrap/react-bootstrap/blob/master/test/SpinnerSpec.js)
- [ ] [SplitButtonSpec](https://github.com/react-bootstrap/react-bootstrap/blob/master/test/SplitButtonSpec.js)
- [ ] [TabContainerSpec](https://github.com/react-bootstrap/react-bootstrap/blob/master/test/TabContainerSpec.js)
- [ ] [TabContentSpec](https://github.com/react-bootstrap/react-bootstrap/blob/master/test/TabContentSpec.js)
- [ ] [TabSpec](https://github.com/react-bootstrap/react-bootstrap/blob/master/test/TabSpec.js)
- [ ] [TableSpec](https://github.com/react-bootstrap/react-bootstrap/blob/master/test/TableSpec.js)
- [ ] [TabsSpec](https://github.com/react-bootstrap/react-bootstrap/blob/master/test/TabsSpec.js)
- [ ] [ThemeProviderSpec](https://github.com/react-bootstrap/react-bootstrap/blob/master/test/ThemeProviderSpec.js)
- [ ] [ToastBodySpec](https://github.com/react-bootstrap/react-bootstrap/blob/master/test/ToastBodySpec.js)
- [ ] [ToastHeaderSpec](https://github.com/react-bootstrap/react-bootstrap/blob/master/test/ToastHeaderSpec.js)
- [ ] [ToastSpec](https://github.com/react-bootstrap/react-bootstrap/blob/master/test/ToastSpec.js)
- [ ] [ToggleButtonGroupSpec](https://github.com/react-bootstrap/react-bootstrap/blob/master/test/ToggleButtonGroupSpec.js)
- [ ] [TooltipSpec](https://github.com/react-bootstrap/react-bootstrap/blob/master/test/TooltipSpec.js)
- [ ] [index](https://github.com/react-bootstrap/react-bootstrap/blob/master/test/index.js) (another special case, since the only work that needs to be done here is to add the RTL integration and remove the Enzyme integration after the migration is done). 

## Additional context

Some of the "why" statements were taken from discussions with members of the fabulous community, [Reactiflux](https://www.reactiflux.com/). If you have not heard of them then I highly recommend you join the [Discord server](https://discordapp.com/invite/reactiflux) 😄

**Comment by taion** [comment]
Eh? Looks like the Enzyme recommendation just got dropped silently in https://github.com/reactjs/reactjs.org/pull/2165 with no discussion? That seems... odd.

**Comment by bpas247** [comment]
> Eh? Looks like the Enzyme recommendation just got dropped silently in [reactjs/reactjs.org#2165](https://github.com/reactjs/reactjs.org/pull/2165) with no discussion? That seems... odd.

Does seem strange that they don't even mention Enzyme anymore on the official React docs... Might be omitted to encourage more people to use RTL? 🤔

**Comment by jquense** [comment]
Personally, I'd really prefer we didn't do this. There is no specific benefit to migrating compared to the cost. React's recommendation of RTL is more of a "here is a simple library you can use" not a "this is how we believe you should test react components". Even if React did say that, I don't really think that dogma in test writing is helpful or even all that useful. Not to mention that as a maintainer, and writing of many tests I find RTL frustrating and time consuming to use :P

**Comment by jquense** [comment]
before i sound all negative :). I think that having some tasks around testing for hackoctoberfest and new folks is a great idea! I think it'd be more beneficial if we could come up with things that fill gaps in the existing tests and testing setup, which would have real immediate benefits vs rewriting the same tests in a different library, which map have some second order benefits.

**Comment by bpas247** [comment]
> There is no specific benefit to migrating compared to the cost.

I think the specific benefit of avoiding APIs that are testing implementation details is a compelling enough argument, although I can't say we've had any recent issues surrounding that in the past with our current testing suite.

> Not to mention that as a maintainer, and writer of many tests I find RTL frustrating and time consuming to use :P

Okay, let's just agree to disagree there 😅 since I can't say I've really found any issues when writing tests using RTL (which I can't say the same for Enzyme).

> I think that having some tasks around testing for hackoctoberfest and new folks is a great idea! I think it'd be more beneficial if we could come up with things that fill gaps in the existing tests and testing setup, which would have real immediate benefits vs rewriting the same tests in a different library, which map have some second order benefits.

That's fair, I can remove the Hacktoberfest label from this issue for now until we've had more discussions regarding the actual value of this migration (assuming there is any value).

**Comment by jquense** [comment]
testing implementation details is a function of how one writes tests. It's a helpful guideline certainly but i don't think there is particular value in a testing library that _enforces_ that.  The real difference in RTL and Enzyme is how it encourages you to query for sub components in your component, and I  while I appreciate that it's better to think in terms of a user, I don't think it's all that helpful to markup tests with data-* attributes so that i can find stuff when a css-class or a css selector already works. 

That said in most cases our tests are simple assertions on markup, something that RTL doesn't do (or does via jest dom matchers). The tests would look about the same in both RTL and Enzyme (consider https://github.com/react-bootstrap/react-bootstrap/blob/master/test/CardSpec.js) but for the complex cases like dropdowns, we'd have to do more work to write the same tests which seems like a lose to me.

**Comment by bpas247** [comment]
> The real difference in RTL and Enzyme is how it encourages you to query for sub components in your component, and I while I appreciate that it's better to think in terms of a user, I don't think it's all that helpful to markup tests with data-* attributes so that i can find stuff when a css-class or a css selector already works.

There is actually a way to [query for css selectors](https://github.com/testing-library/dom-testing-library/issues/108#issuecomment-425487305) via good old `querySelector`, and also a way to traverse the DOM nodes via [custom matcher function](https://github.com/testing-library/dom-testing-library/issues/108#issuecomment-511669033), but I think you're absolutely right, this isn't going to make the dev experience of writing tests any easier with RTL.

> That said in most cases our tests are simple assertions on markup, something that RTL doesn't do (or does via jest dom matchers). The tests would look about the same in both RTL and Enzyme (consider https://github.com/react-bootstrap/react-bootstrap/blob/master/test/CardSpec.js) but for the complex cases like dropdowns, we'd have to do more work to write the same tests which seems like a lose to me.

Yeah and to add on to that, this could potentially slow down the development of writing future tests, which seems to outweigh any benefit we get from this migration. Not to mention that we'll probably need to re-write a good portion of the tests when Bootstrap v5 releases anyways, so it doesn't really seem worth our time to completely re-write them now.

I'm gonna go ahead and close this issue for now 😃 as it seems like the cost of this migration significantly outweighs any benefit that could be gained. If anyone feels like they have a compelling enough argument for this migration, please feel free to reply to this thread and if it's compelling enough I'd be more than happy to re-open it ✌️ 

Special thanks to @jquense for clearing things up, definitely appreciate the feedback 🙌
