### ISSUE TITLE
Button size with href doesn't work

### ISSUE THREAD

**Issue by theocerutti** [react-bootstrap/react-bootstrap#4697]
Hello,

When I create a Button with a href and a size='lg' the size is not applied..

`     <Button size='lg' href='#' className='btn-pill' variant='outline-info pill' block>
        Button
      </Button>
`

This example doesn't apply the lg size

**Comment by mxschmitt** [comment]
Have you loaded the Bootstrap CSS styles?

For an interactive example you can take a look here: https://codesandbox.io/s/github/react-bootstrap/code-sandbox-examples/tree/master/basic

**Comment by theocerutti** [comment]
Ohh, I know why there was a bug.. I put a span inside the button..

Sorry :'(
