### ISSUE TITLE
onClick, onSelect ignored for DropdownButton

### ISSUE THREAD

**Issue by acthp** [react-bootstrap/react-bootstrap#470]
Is there a way to be notified when a dropdown is opened? Setting onClick and onSelect appears to have no effect. More generally, is there any documentation of the events emitted by bootstrap components?

**Comment by mtscout6** [comment]
It's on our roadmap to address #419

**Comment by acthp** [comment]
Use case is focusing a text input when it opens, similar to the select2 jquery lib. For the moment I'm able to work around it by binding onMouseUp. Not yet sure if it's reliable across different devices.

**Comment by lo1tuma** [comment]
I was running into the same problem. For my use case I don’t want an `onClick` handler at all, instead the default event handler should redirect to the URL specified in the `href` property of the `DropdownButton`.

**Comment by mtscout6** [comment]
I hadn't looked at select2 jquery till today. I'm thinking that the best solution for something like this would be allowing for a custom dropdown menu component aside from the default. So something like:

```
<DropdownButton>
  <CustomDropdownMenu>
    <MenuItem ... />
    <MenuItem ... />
  </CustomDropdownMenu>
</DropdownButton>
```

Yet still allow for the default `DropdownMenu` when none is provided so the following should also work:

```
<DropdownButton>
  <MenuItem ... />
  <MenuItem ... />
</DropdownButton>
```

The other issue I see is that the components in select2 jquery are all tied to an actual html5 select box under the covers. I'm not quite sure how to solve that problem, some kind of wrapper that links the two together should work relatively easy.

What are your thoughts on this?

**Comment by AlexKVal** [comment]
Superceded by #526 and #419
