### ISSUE TITLE
'.' is bit recognized as an internal or external command while trying to build on Windows

### ISSUE THREAD

**Issue by andrerpena** [react-bootstrap/react-bootstrap#471]
Hello all,

I'm trying to use react-bootstrap. I just downloaded it and I'm trying to build it on Windows.

I just ran:

    npm run build

 Here's the result:

![image](http://i.imgur.com/THT5wCn.png)

Any idea of how to build it on Windows?

**Comment by mtscout6** [comment]
This may be an oversight on my part, when I did my last round of infrastructure upgrades I made use of shell scripts. Have you tried running the commands within git bash?

**Comment by andrerpena** [comment]
Thanks for the ultra fast response. Honestly it boosted my will of trying react-bootstrap.

If by `git bash` you mean `running the build command directly in the cmd`, yes I did.

![image](http://i.imgur.com/5DNANav.png)

Thanks

**Comment by mtscout6** [comment]
No not cmd, when you install git it has the option to install a linux style shell that tends to work with linux style shell scripts. If you open your start menu and type bash you should see it, but it has been a while since I did serious work on windows.

**Comment by mtscout6** [comment]
Just started up my windows vm and I see the same problem in git bash. I don't have time to dig into this tonight, but I'll give this a look over in the morning.

**Comment by andrerpena** [comment]
Thanks @mtscout6 . I didn't know about the bash.
I'm glad you'll fix it. Once this issue is closed I'll try to build react-bootstrap again. Thanks for the good work.

**Comment by mtscout6** [comment]
I've pushed up a [windows-build](https://github.com/react-bootstrap/react-bootstrap/tree/windows-build) branch, which gets past the first issue you were seeing. Unfortunately there's more to deal with. I'm not going to be able to do more today, but I'll see what I can do tomorrow or over the weekend. Keep in mind that that branch is a work in progress and I will force push to it on occasion.

**Comment by andrerpena** [comment]
Thanks again. So I think you would advice me to wait until you actually finish it. It's holiday in Brazil from tomorrow on so I'll only be able to get back to that on Monday.

I really appreciate your attention.

**Comment by andrerpena** [comment]
You don't know how much this project is going to help me if it really works. I'm building a framework for creating line-of-business, data-driven apps on top of ReactJS and BS and I though I'd have to reimplement Bootstrap. My framework is focused on generating the interface automatically based on metadata provided from the server.

Now I'll be able to focus on data-components, like the Autocomplete, Grid, Tree...

**Comment by mtscout6** [comment]
Glad to hear it's helping you out.

We definitely don't want to intentionally exclude the community of developers working with Windows, so this is a huge priority for us. We'll make sure it's working as soon as possible.

**Comment by andrerpena** [comment]
Thanks

**Comment by mtscout6** [comment]
@andrerpena I think i have got your issue fixed on that windows-build branch. I'm working to get a CI setup for it on [appvoyer](https://ci.appveyor.com/project/mtscout6/react-bootstrap) to make sure this never happens again. I'm still working out issues with the CI, but you should be able to work with that branch for the time being.

**Comment by mtscout6** [comment]
The fix in is master.

**Comment by andrerpena** [comment]
I really appreciate that. Thank you.
