### ISSUE TITLE
Size of Prev and Next Paginator icons cannot be changed?

### ISSUE THREAD

**Issue by byers174** [react-bootstrap/react-bootstrap#4716]
Is it possible to change the size of the left and right Prev / Next icons without changing the entire size of the paginator? 

I love the default size but I'm having to rebuild the entire thing using `className="fa fa-chevron-left"` simply because I would like the button icon to be larger

**Comment by taion** [comment]
You can render your own component in place of just the `Prev` and `Next` components, or else pass in different values for `children` for those.

**Comment by byers174** [comment]
Just a note: 

passing a child, say `spanPrev = <my custom span>`

into Pagination.Prev, for example:
`<Pagination.Prev disabled={disablePrev} onClick={handlePrev} children={spanPrev} />`

Results in the spanPrev element being added as a child to the first of the two default spans.. That is to say it **does not** replace them. Perhaps this is intended and I read the documentation / your response wrong?

The rendered html is: 
```
<a class='page-link' ... >
    <span aria-hidden="true">
        <my custom span />
    </span>
    <span class="sr-only">Previous</span>
</a>
```

**Comment by taion** [comment]
Well, the second span is sr-only. It's for a11y in the case that you're just rendering an icon.
