### ISSUE TITLE
Enhancement Request: TabbedArea close buttons on tabs

### ISSUE THREAD

**Issue by mikecargal** [react-bootstrap/react-bootstrap#473]
Allow for the addition of a close button on tabs in a TabbedArea.  Something similar to browser tabs.

**Comment by aabenoja** [comment]
Pull requests are welcome.

**Comment by kmsheng** [comment]
+1 for this thing

**Comment by taion** [comment]
I don't see anything like this in upstream TWBS. Can we do this without custom CSS?

**Comment by taion** [comment]
Actually, the `tab` (soon to be `title`) prop on a `TabPane` (soon to be `Tab`) is actually a component, so you can add whatever custom logic you want there, including a close button.

**Comment by mikecargal** [comment]
Ah, all the examples just provide text for the tab.  Thanks, this was fairly simple with that tidbit of knowledge.

**Comment by k-stasevich** [comment]
+ 1 for this thing [2]
