### ISSUE TITLE
react-bootstrap/Nav not setting 'role' as tablist

### ISSUE THREAD

**Issue by ljmerza** [react-bootstrap/react-bootstrap#4733]
## Describe the bug
Docs for Nav state:

```
ARIA role for the Nav, in the context of a TabContainer, the default will be set to "tablist", but can be overridden by the Nav when set explicitly.
```
https://react-bootstrap.github.io/components/navs/#nav-item-props

But the role is never being applied even when manually specifying

## To Reproduce
Look at DOM structure and you'll see no 'role' applied to the tab container.

## Reproducible Example

Minimal example by using [CodeSandbox](https://codesandbox.io/s/code-sandbox-examples-wjqst?fontsize=14https://codesandbox.io/s/code-sandbox-examples-wjqst).

## Expected behavior

by default the role=tablist should be applied and a can be changed by passing in the role prop into Nav element

## Environment (please complete the following information)

- Operating System: Windows 10
- Browser, Version 77.0.3865.120
- React-Bootstrap Version 1.0.0-beta.14

**Comment by bpas247** [comment]
Seems like a dup of #4313?

**Comment by ljmerza** [comment]
Doesn't look like it was fixed. https://github.com/react-bootstrap/react-bootstrap/pull/4331/files was merged in August which is before beta 14 release but the issue is still present as seen in the example

**Comment by bpas247** [comment]
> in the context of a TabContainer,

You aren't nesting this in a TabContainer component, so it's not going to apply the `tablist` role to the Nav component.
https://codesandbox.io/s/nesting-nav-inside-tab-container-hedh6

**Comment by bpas247** [comment]
I'm gonna go ahead and close this for now 😄 @ljmerza please feel free to reply to this thread if you have any more questions.
