### ISSUE TITLE
'now' attribute in ProgressBar component not showing the progress.

### ISSUE THREAD

**Issue by BakerShoeMaker** [react-bootstrap/react-bootstrap#4741]
I am using the the ProgressBar component and I'm updating the `now` attribute with state. The actual number is updated but the progress bar component color (variant='success') is not updating. Here is the code:
`changeProgressBarWidth = ()=>{
        //Set the width of the progress bar here.
        pb_width++
        this.setState({progressBarStatusWidth: pb_width});
        console.log("changeProgressBarWidth is being called......................................." +pb_width);
    }
 timer.addEventListener('secondsUpdated', ()=>{
this.changeProgressBarWidth();
 });
//In render
<ProgressBar now={this.state.progressBarStatusWidth}  variant="success" />
`
See example. This is a count down clock so the green part should be around 20%
![sdfdfs](https://user-images.githubusercontent.com/8380443/67648211-4c74ae00-f8f2-11e9-8229-5e8b54e25add.PNG)
:

How can I fix this?

**Comment by taion** [comment]
You're most likely missing some CSS. See the examples on https://react-bootstrap.github.io/components/progress/. Otherwise, please provide a runnable repro.
