### ISSUE TITLE
Navbar rendering an uppercase <Nav ...> DOM node

### ISSUE THREAD

**Issue by lukemcgregor** [react-bootstrap/react-bootstrap#475]
This occurs client-side but not server-side (my SSR is probably lowercasing it on render) and causes a checksum mismatch.

lowercase DOM nodes should always be rendered.

**Comment by mtscout6** [comment]
I'd venture to guess that the culprit is: https://github.com/react-bootstrap/react-bootstrap/blob/v0.20.0/src/Navbar.js#L35 Do you agree?

**Comment by lukemcgregor** [comment]
Oh sorry just saw I never commented on this, Yes it does indeed look like the culprit.
