### ISSUE TITLE
Update changelogs to include missing releases

### ISSUE THREAD

**Issue by bpas247** [react-bootstrap/react-bootstrap#4761]
## Is your feature request related to a problem? Please describe

The following beta releases and pre-releases are missing from the changelogs:

- `v1.0.0-beta.13`
- `v1.0.0-beta.14`
- `v0.33.0`

## Describe the solution you'd like

Document these releases in `CHANGELOG.md`:

- [ ] `v1.0.0-beta.13`
- [ ] `v1.0.0-beta.14`

And document this release in `CHANGELOG-pre1.md`:

- [ ] `v0.33.0`

**Comment by mxschmitt** [comment]
@bpas247 they will be auto generated by running this script in the package.json: https://github.com/react-bootstrap/react-bootstrap/blob/master/package.json#L17

**Comment by bpas247** [comment]
> they will be auto generated by running this script in the package.json:

I am mostly documenting this here so we can keep track of when there are disconnects between our releases and what's currently documented in our changelogs 😛

**Comment by bpas247** [comment]
hmm, I wondering if it would be too clever if we could somehow integrate GitHub actions for these.

**Comment by theflash193** [comment]
Hello did you use mxschitt solution ?
If not can you explain me how to actually update the missing release ?

**Comment by WilliamMena** [comment]
Hey, it seems as if this issue was completed in [this commit](https://github.com/react-bootstrap/react-bootstrap/commit/4444bb7623930e9a5bb5c1d4cfc95c28201fa745). It also includes v1.0.0-beta.15

**Comment by taion** [comment]
Thanks!
