### ISSUE TITLE
direction property does nothing

### ISSUE THREAD

**Issue by ri8ika** [react-bootstrap/react-bootstrap#4764]
I am using controlled component for carousel:

```
<Carousel activeIndex={index} direction={direction} onSelect={handleSelect}>
```

And I need to update the direction with some condition. After a lot of tries, I came to know that direction property does nothing. For test case: instead of using direction from state, use static direction:
```
<Carousel activeIndex={index} direction="prev" onSelect={handleSelect}>
```

Expectation: (Clicking on next arrow icon should slide carousel from backwards)
But got same effect as before.

**Comment by taion** [comment]
There isn't really any such prop. If you need to manually trigger a transition with direction, you'll need an imperative ref.

**Comment by ri8ika** [comment]
What's in the example then?
https://react-bootstrap.github.io/components/carousel/

**Comment by taion** [comment]
we should probably remove that; care to send in a PR to docs?

**Comment by ri8ika** [comment]
Not sure how to?

**Comment by indranil-tiwary** [comment]
Hey @mxschmitt. I would love to contribute starting with this. Please assign the task and let me know what to write in place of `direction={direction}` and any other changes you need me to do.
I will setup the repo and start working on it, shall create a PR as soon as I get the suggested changes.
