### ISSUE TITLE
Missing constants after ES6 migration

### ISSUE THREAD

**Issue by mtscout6** [react-bootstrap/react-bootstrap#478]
@trevorr You are correct that constants is now missing from the public api, I missed that when I was transitioning to ES6.

First reported in #306

**Comment by mtscout6** [comment]
Release in 0.20.1! Thanks for reporting this @trevorr.

**Comment by trevorr** [comment]
@mtscout6 Thanks for the quick response. However, doesn't exposing the constants in this way lead to the problem I mentioned in #306, where the accepted styles can't effectively be changed after the rest of the library is initialized. I can now access the constants, but adding custom styles doesn't prevent the warnings.

**Comment by mtscout6** [comment]
@trevorr You are correct that that is a problem and one that needs to be addressed. Can we follow up on this discussion in #440?
