### ISSUE TITLE
Hover Nav displays missing

### ISSUE THREAD

**Issue by theocerutti** [react-bootstrap/react-bootstrap#4780]
Hello,

Nav hover is missing:

```
<Nav variant="tabs" defaultActiveKey="/home">
  <Nav.Item>
    <Nav.Link href="/home">Active</Nav.Link>
  </Nav.Item>
  <Nav.Item>
    <Nav.Link eventKey="link-1">Option 2</Nav.Link>
  </Nav.Item>
  <Nav.Item>
    <Nav.Link eventKey="disabled" disabled>
      Disabled
    </Nav.Link>
  </Nav.Item>
</Nav>
```

![](https://user-images.githubusercontent.com/44285344/68198201-2f289980-ffee-11e9-893b-1b28b511f424.png)

Expected:

![Untitled](https://user-images.githubusercontent.com/44285344/68285386-c60a5a00-00b1-11ea-8380-7d089145d600.png)

As you can see there is no outline selection..

**Comment by kosmiq** [comment]
No new feedback after more than 7 days. Closing.
