### ISSUE TITLE
Carousel hard stop dis-functioning slider transition on first and last item

### ISSUE THREAD

**Issue by ri8ika** [react-bootstrap/react-bootstrap#4781]
I am trying to use carousel with hard stop disabling wrap property.
```
<Carousel wrap={false}>
```
But this hampers slider transition on first and last item.

Here's the demo for the issue:

https://codesandbox.io/s/code-sandbox-examples-xjj7m

Please follow clicking on the next arrow, then you'll see last item appears immediately.
Now follow clicking to prev arrow, then you'll see the first item appears with different transition effect.

It seems first and last item position is set to fixed?!?

This issue appears on latest versions eg. 1.0.0-beta.14. I have tried in 0.33 and it has no issue.

**Comment by taion** [comment]
dupe of https://github.com/react-bootstrap/react-bootstrap/issues/3654

**Comment by ri8ika** [comment]
What's the solution for this? I read linked and related links but not able to fix this issue.
