### ISSUE TITLE
Make assistive technologies ids optional

### ISSUE THREAD

**Issue by gricey432** [react-bootstrap/react-bootstrap#4786]
There have been past issues: #1426, #2446 about an old warning which encouraged you to use the `id` property on components to allow for accessibility. However, now using typescript and the included types, this becomes a compile blocker.

I've personally run into this upgrading from 0.32 to 1.0 (going from the types on definitelytyped to the provided ones here) on a site which I know the user base doesn't require any assistive technologies.

I'd be good if there was a way to opt-out of this requirement.

**Comment by taion** [comment]
Can you locally override the props interfaces to make `id` non-required?

**Comment by gricey432** [comment]
Yeah, you can override them like this:

```typescript
import orig from "react-bootstrap";

declare module "react-bootstrap" {
    export interface PopoverProps extends orig.PopoverProps {
        id?: string | number;
    }
}
```

I guess the issue is that I think this was OK as a warning but seems a bit much to make it an exception if not needed.

**Comment by taion** [comment]
That seems like a semantically appropriate way to state in your project that the `id`s aren't required, then.

**Comment by gricey432** [comment]
So to confirm - not using accessibility *should* be an exception rather than just a warning like it used to be?

**Comment by taion** [comment]
It _was_ a `propTypes` failure before: https://github.com/react-bootstrap/prop-types-extra/blob/779984a9c5a6b3650e70f545017616723592d48c/src/isRequiredForA11y.js#L8-L14
