### ISSUE TITLE
Progress bar is very slow

### ISSUE THREAD

**Issue by hsluoyz** [react-bootstrap/react-bootstrap#4788]
```react
<ProgressBar animated now={this.state.events.length * 2} label={`${this.state.events.length * 2}%`}/>
```

`this.state.events` is an array which will be appended based on mouse move event. But I found there's a huge delay for progress bar to grow. Any way to make it faster?

**Comment by taion** [comment]
This is purely in your code... the progress bar is just a simple component that takes in those numbers

**Comment by alexanderGerbik** [comment]
In order for update to look smooth, progress bar has transition for width update (`--bs-progress-bar-transition`), which makes visual state of progress bar delayed compared to actual state (0.6s was quite noticeable in our case). You might have the same issue.
