### ISSUE TITLE
0.33.0 version,  aria-hidden=true is applied to modal (role="dialog") on open state.

### ISSUE THREAD

**Issue by Romanior** [react-bootstrap/react-bootstrap#4790]
## Describe the bug

0.33 introduced critical a11y error, when opening dialog(modal) `aria-hidden=true` is applied to it.

## To Reproduce

1. Go to https://codesandbox.io/s/serene-chaplygin-xdstw?fontsize=14
2. Click on 'Launch demo modal'
3. Inspect DOM, and find div with role=modal and aria-hidden=true

## Reproducible Example

Minimal example by using [CodeSandbox](https://codesandbox.io/s/serene-chaplygin-xdstw?fontsize=14).

## Expected behavior

Active Dialog(Modal) should not have `aria-hidden=true` attribute

## Screenshots
<img width="1057" alt="Screen Shot 2019-11-10 at 11 41 11" src="https://user-images.githubusercontent.com/490365/68541335-31ed0b00-03af-11ea-95a4-89bbfb79e6b6.png">

## Environment (please complete the following information)

- Operating System: MacOS
- Browser, Version: Chrome 78
- React-Bootstrap Version: 0.33

**Comment by Romanior** [comment]
@taion @AlexKVal @jquense Any reaction on this? Or you stopped maintaining this project? thanks.

**Comment by taion** [comment]
Active development is on the 1.x branch right now. We'd be happy to take PRs to fix any bugs, though.

**Comment by filipkis** [comment]
Actually, this is an issue of `react-overlays` that's been addressed on 2.x branch, but not on 0.9 branch which is the one used here.

**Comment by kyletsang** [comment]
Closing as this is fixed in https://github.com/react-bootstrap/react-overlays/pull/858
