### ISSUE TITLE
'useAccordionToggle' only refers to a type, but is being used as a value here

### ISSUE THREAD

**Issue by zhangyu0218** [react-bootstrap/react-bootstrap#4792]
I found a problem when I introduced the example from the official website
![image](https://user-images.githubusercontent.com/33249149/68557968-83120300-0472-11ea-9619-ee65972c379b.png)

I checked the source code and found that it was indeed a type
![image](https://user-images.githubusercontent.com/33249149/68557992-9c1ab400-0472-11ea-9441-f983e7bdec2a.png)
The version I introduced was "react-bootstrap": "1.0.0-beta.14"

**Comment by taion** [comment]
Ah, we probably shouldn't have declared that as an interface. Feel free to send in a PR to fix.

**Comment by rrriki** [comment]
I left a PR with a fix for this issue: https://github.com/react-bootstrap/react-bootstrap/pull/4814

**Comment by bpas247** [comment]
Looks like the PR to fix this was merged, so I'll be closing this issue now 😄

**Comment by arhtudormorar** [comment]
try this:

```
function CustomToggle({ children, eventKey }: any) {
  // @ts-ignore
  const decoratedOnClick = useAccordionToggle(eventKey, () => console.log('totally custom!'));

  return (
    <button type="button" style={{ backgroundColor: 'pink' }} onClick={decoratedOnClick}>
      {children}
    </button>
  );
}
```
