### ISSUE TITLE
UNSAFE_componentWillReceiveProps and UNSAFE_componentWillMount (0.32.4)

### ISSUE THREAD

**Issue by epavan** [react-bootstrap/react-bootstrap#4805]
Hi guys, is there any plan to fix this in 0.32.4 (Bootstrap 3)?
Thanks.

**Comment by taion** [comment]
Can you clarify?

**Comment by epavan** [comment]
After upgrading to react 16.8.X, there's a warning in devTools console which says that some lifecycle methods are deprecated (componentWillReceiveProps and componentWillMount). I was wondering if there's a plan to upgrade 0.32.4 to avoid them.

**Comment by taion** [comment]
They're fixed in v0.33.x.

**Comment by epavan** [comment]
Which will be released when?

**Comment by taion** [comment]
it's been out for nearly 2 weeks now... https://www.npmjs.com/package/react-bootstrap/v/0.33.0
