### ISSUE TITLE
Getting state of Navbar.Toggle?

### ISSUE THREAD

**Issue by WilsonCWong** [react-bootstrap/react-bootstrap#4806]
Hi,

Is there a way to detect if the toggle is opened or not? Attaching a listener to `onClick` works fine for opening it, but when closing it, the collapse has a bit of a transition before it fully closes so it stops working.

I'm trying to hide my dropdown when it is collapsed. The only other way I can think of is using media queries, but I wanted to know if there's another method I can use because I'd prefer to control it with state.

EDIT: Yeah, I just did it with `display: none` and media queries. If there's a way to do it with state though, I'm all ears.

**Comment by shu-bham** [comment]
You can define a state variable as `showDropdown : false`. Attach a `toggleHandler` method to the Toggle button that will toggle the value of `showDropdown`. Pass `showDropdown` as props to your Dropdown Component and conditionally render it based on value of `showDropdown`.
