### ISSUE TITLE
Stacked Modals Support

### ISSUE THREAD

**Issue by TrustyTexan** [react-bootstrap/react-bootstrap#481]
Thank you for providing such an awesome library, and I'd really like to use it, but one of my use cases is the ability to open a modal from another modal -- so in other words, you would have one modal sitting on top of another with ideally just one backdrop.  Is this possible, and if so how would you suggest I go about implementing this?  Perhaps a CustomTrigger of sorts that manages a modal stack?  I noticed that each modal instance attempts to create its own backdrop; does this preclude having stacked modals?

Thanks!
David

**Comment by janmarek** [comment]
I currently use modals opened from other modals. It works OK when you set z-index of modal and backdrop to the same value.

Only thing I need to be fixed is that Escape key closes all modals, not only the most top one.

If anybody has an idea how to fix the esc key functionality, I would really appreciate that.

**Comment by taion** [comment]
I would wrap the `Modal` with another component that only passes down calls to `props.onRequestHide` when it's the "top" modal shown.

**Comment by AlexKVal** [comment]
I'm closing it. Feel free to reopen if it's still an issue. :sparkle:

**Comment by taion** [comment]
ref #893 - similar issue but more severe.
