### ISSUE TITLE
`Dropdown.Toggle` incorrectly expects `onClick` prop when using a custom element.

### ISSUE THREAD

**Issue by fbessou** [react-bootstrap/react-bootstrap#4819]
## Describe the bug

When using a custom component in a `Dropdown.Toggle`, if the custom element takes an onClick property (which should be the case), the type checker emits an error telling that an `onClick` prop must be provided to `Dropdown.Toggle`. This message is incorrect since it is the responsibility of `Dropdown.Toggle` to call our custom component with the `onClick` prop.

## To Reproduce

1 - Create a component with a required `onClick` prop
2 - Provide it as the `as` prop of a `Dropdown.Toggle`
3 - Type checking doesn't succeed

## Reproducible Example
https://codesandbox.io/s/withered-sky-pd64t?fontsize=14&hidenavigation=1&theme=dark

## Expected behavior

The type of the `Dropdown.Toggle` should not make `onClick` prop necessary when using a custom component with a non-optional `onClick` prop. 

## Environment (please complete the following information)

- Operating System:  Linux
- Browser, Version: Firefox 69
- React-Bootstrap Version: 1.0.0-beta.14

## Note

I think the same kind of error happen with Popovers.

**Comment by fbessou** [comment]
Would be nice to have a way to declare which properties are passed to the custom element by the DropdownToggle.

Currently, the DropdownToggle has the following type:

```ts
declare class DropdownToggle<
  As extends React.ElementType = BsPrefixComponentClass<'button', ButtonProps>
> extends BsPrefixComponent<As, DropdownToggleProps> {}
```

Maybe a solution could be to add a third parameter to `BsPrefixComponent` to specify which props of the custom element should NOT be passed to `Dropdown.Toggle` (as they are already passed by the `DropdownToggle` component).

```ts
declare class DropdownToggle<
  As extends React.ElementType = BsPrefixComponentClass<'button', ButtonProps>
> extends BsPrefixComponent<As, DropdownToggleProps, {onClick: null, className: null}> {}
```

**Comment by adizka** [comment]
Have the same issue:

**Comment by flolege** [comment]
Same here. We basically followed the guide under https://react-bootstrap.github.io/components/dropdowns/#custom-dropdown-components.

We get the same error:
**Uncaught Invariant Violation: DropdownToggle injected a ref to a provided as component that resolved to a component instance instead of a DOM element. Use React.forwardRef to provide the injected ref to the class component as a prop in order to pass it directly to a DOM element**

**Comment by fbessou** [comment]
@adizka, @flolege :  :thinking:  I don't think that your problems are related to this issue.
I suppose that your error occurs at run time, while the error I am mentioning is happening at transpile time during static type checking by typescript. :slightly_smiling_face:

**Comment by flolege** [comment]
@fbessou You are probably right :)

**Comment by BenMorel** [comment]
Any update here? This blocks our build and prevents us from deploying.

**Comment by taion** [comment]
I think something like @fbessou's proposed solution is the right one here. We need to include "what gets passed down" in the types somehow. We'd be happy to take a PR to fix this issue.

**Comment by BenMorel** [comment]
@taion I'm not proficient enough with TS to be able to fix this bug, I'm afraid. Any chance you or another contributor can work on this one?

**Comment by jquense** [comment]
its a type issue, if it's blocking you override the type in your code or cast to `any`, we will get to this eventually but type def issues are low on the priority list, since they are advisory and do not affect the actual code behavior

**Comment by BenMorel** [comment]
> override the type in your code or cast to `any`

Pardon my ignorance, I'm getting started with TypeScript. Could you please explain how you do that in this case?

**Comment by BenMorel** [comment]
OK I managed to fix it by making the `onClick` property of my `CustomDropdownToggle` props optional:

Before:

```
interface Props {
    onClick: Function
    id: string
}
```

After:

```
interface Props {
    onClick?: Function
    id: string
}
```
