### ISSUE TITLE
Add "getting started" kit

### ISSUE THREAD

**Issue by VVE** [react-bootstrap/react-bootstrap#482]
Could you please give simple and full start guide for beginners: installation and usage.

**Comment by JordanTheriault** [comment]
Check out [this](http://react-bootstrap.github.io/getting-started.html) page.

**Comment by VVE** [comment]
I had seen. It seems to me insufficient

**Comment by mtscout6** [comment]
In what ways is it insufficient to you? I'm asking to gain insight as to how to make that documentation better. What would you like to see there?

**Comment by VVE** [comment]
I would like to see something like http://facebook.github.io/react/docs/getting-started.html. 
I read "First add the Bootstrap CSS to your project". I can install Bootstrap completely from the page http://getbootstrap.com/getting-started/, but you advice to install only css. How? 
How should I use "var Alert = require('react-bootstrap/lib/Alert');" statement?
Could You please help me start?

**Comment by dozoisch** [comment]
related: https://github.com/react-bootstrap/react-bootstrap/pull/149

**Comment by jhvanderven** [comment]
I had some difficulty with this myself. In my yeoman skeleton, I first require('react-bootstrap'); Then I realized I needed the actual bootstrap itself as well, so I added that and jquery to my package.json. After much experimenting I finally added the line: require('bootstrap/dist/css/bootstrap.css'); to my main jsx file. I then got errors related to loading that file. Specifically the fonts. I could fix that by adding this to the webpack.config.js:
    {
     test: /\.woff$/, 
     loader: "url-loader?limit=10000&mimetype=application/font-woff" 
   },
    {
     test: /\.woff2$/, 
     loader: "url-loader?limit=10000&mimetype=application/font-woff" 
   },
{ 
  test: /\.ttf$/,  
  loader: "url-loader?limit=10000&mimetype=application/octet-stream" 
},
{ 
  test: /\.eot$/,  
  loader: "file-loader" 
},
{
 test: /\.svg$/,  
 loader: "url-loader?limit=10000&mimetype=image/svg+xml" 
},

These loaders are not installed by default, so you need to add them to package.json too:
  "dependencies": {
    "bootstrap": "*",
    "file-loader": "^0.8.1",
    "url-loader":"*",
    "jquery": "*",
    "normalize.css": "~3.0.3",
    "react": "~0.13.2",
    "react-bootstrap": "*"
  },
Hope this helps.

**Comment by taion** [comment]
It certainly takes a little effort to get Bootstrap working with webpack. However, I think that's beyond the scope of a "getting started" guide.

I don't think the instructions for getting Bootstrap CSS are too complicated, though.

I'd be inclined to close this issue. However, it could be a good idea to link to a good Yeoman template for react-bootstrap + webpack, with the build set up correctly. I'd have that as a separate issue, though.

**Comment by mtscout6** [comment]
:+1: To getting a Yeoman template set up. I'd be open to having one in a separate repo of this organization. Ideally though I think we'd want three templates, one for webpack+npm, browserify+npm, and bower+requirejs. Do I have any takers that would be interested in getting this started? Or are there any existing templates that we could already link to?

**Comment by dozoisch** [comment]
Webkpack npm shouldnt be too long. Most of my project already use that

**Comment by mtscout6** [comment]
@dozoisch Do you want me to create a repo for that?

**Comment by dozoisch** [comment]
@mtscout6 I really don't have the time right now to do it though :(

**Comment by mtscout6** [comment]
:+1:

**Comment by AlexKVal** [comment]
just for refs:
https://www.npmjs.com/package/react-bootstrap-webpack
https://www.npmjs.com/package/react-bootstrap-starter

**Comment by taion** [comment]
Renamed issue because it seems that the missing generators are the main thing to do here.

**Comment by AlexKVal** [comment]
Do we really need this issue open ?
This is actually a feature request and this is not an addition to the codebase,
but another additional project by itself.

--
There are too many projects like `Yeoman` 
and I think that the `R-B` team doesn't have to implement all those use cases. 
What do you think /cc @react-bootstrap/collaborators ?

--
I believe that if there is enough interest for somebody to implement `Yeoman` generator for `R-B`
project, then them always would ask for help and clarifying questions :+1: 

--
I propose to close it :cherries:

**Comment by mathieumg** [comment]
We should probably add it to a non-prioritized backlog, using labels. Having 0 issues as fast as possible is not really an objective, especially since we use HuBoard, just my 2 cents. :cherries:

**Comment by AlexKVal** [comment]
I'm not using `HuBoard` at all :stuck_out_tongue_closed_eyes:

**Comment by taion** [comment]
People don't really use Yeoman any more eh? Maybe just make something like https://github.com/relayjs/relay-starter-kit

**Comment by eddywashere** [comment]
It would be nice to have a jsbin/jsfiddle to quickly see what it's like using this package.

**Comment by eddywashere** [comment]
Example: https://jsbin.com/guhavi/1/edit?js,output

**Comment by dozoisch** [comment]
btw @eddywashere on the components page you can modify any zone that has code in it to try stuff

**Comment by brobey8** [comment]
@eddywashere thanks for that example, I agree that some code examples are needed to show how the internal components should be bound

**Comment by brobey8** [comment]
@jquense yep, my fault for not reading the docs correctly, I also didn't realise that the code snippets were editable!

**Comment by thealjey** [comment]
I'm surprised a non-issue like this is even in the 1.0 milestone.

There's a million ways to include the css into a web page, it's just css (or sass), same as any other.
It's not even a part of this project.

And the React Bootstrap components, are just plain and simple React components, same as any over.
I just don't understand how can someone figure out how to use React in general and still have problems using React Bootstrap.
