### ISSUE TITLE
UNMET PEER DEPENDENCY jquery@1.9.1 - 3

### ISSUE THREAD

**Issue by anujsinghwd** [react-bootstrap/react-bootstrap#4822]
+-- bootstrap@4.3.1  extraneous
+-- deck.gl@7.3.4 
+-- UNMET PEER DEPENDENCY jquery@1.9.1 - 3
+-- nebula.gl@0.16.0 
+-- react-bootstrap@1.0.0-beta.14  extraneous
`-- react-map-gl-draw@0.16.1 

npm WARN optional Skipping failed optional dependency /jest-haste-map/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.9
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.9
npm WARN optional Skipping failed optional dependency /react-scripts/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@2.0.7
npm WARN bootstrap@4.3.1 requires a peer of jquery@1.9.1 - 3 but none was installed.
npm WARN ts-pnp@1.1.4 requires a peer of typescript@* but none was installed.
npm WARN tsutils@3.17.1 requires a peer of typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta but none was installed.

**Comment by taion** [comment]
there's no direct dependency of any sort on jquery here
