### ISSUE TITLE
How to open/close modal without button?

### ISSUE THREAD

**Issue by IgorBabkin** [react-bootstrap/react-bootstrap#484]
I need to open modal programmatically like $(element).modal('show')

**Comment by zandroid** [comment]
Take a look at http://react-bootstrap.github.io/components.html#modals **Custom trigger** example.
After applying of `OverlayMixin` you can open a Modal with help of like this code: `this.setState({ isModalOpen: true })`

**Comment by mtscout6** [comment]
@IgorBabkin Did @zandroid's answer help you out?

**Comment by taion** [comment]
Other than by calling `setState` directly, we should enable this via the same prop as for #611. I'm closing this as a duplicate because the other issue has more discussion on it.
