### ISSUE TITLE
Uncaught Invariant Violation: DropdownToggle injected a ref to a provided as component

### ISSUE THREAD

**Issue by flolege** [react-bootstrap/react-bootstrap#4841]
We basically followed the guide under https://react-bootstrap.github.io/components/dropdowns/#custom-dropdown-components.

We get the this error:
Uncaught Invariant Violation: DropdownToggle injected a ref to a provided as component that resolved to a component instance instead of a DOM element. Use React.forwardRef to provide the injected ref to the class component as a prop in order to pass it directly to a DOM element

**Comment by eG-dev** [comment]
We are running into the same issue at the moment. It came up with the newly released version '1.0.0-beta.15'

**Comment by jquense** [comment]
The error is fairly clear i think folks? Dropdown Toggle and a few others require that their refs resolve to DOM nodes, not component instances. We've not fixed the RB docs ourselves yet to adjust for the change, but it's straightforward. Use `forwardRef()` to put the ref on the DOM node

**Comment by flolege** [comment]
It is really not clear for a React/Javascript Beginner. Could you please provide an example?

**Comment by jquense** [comment]
The docs have been updated to reflect the right way to use custom components: https://react-bootstrap.github.io/components/dropdowns/#custom-dropdown-components

**Comment by derwaldgeist** [comment]
Is there an upgrade guide for different versions of this package? These kind of changes are pretty hard to detect. I stumbled upon it only after a while working with my app, as I needed the dropdown only at a single place.
