### ISSUE TITLE
Container margins

### ISSUE THREAD

**Issue by procarrera** [react-bootstrap/react-bootstrap#4850]
Hello guys,
How can I remove the margins of Container component?
I am trying like this, but didnt work:

```
class App extends Component {
  render() {

    const title = 'ReactJS !';

    return (
        <Container fluid style={{ marginLeft: '0', marginRight: '0px' }}>
          <NavBar title={title} />
          {this.props.children}
        </Container>
    );
  }
}
```

Would be happy if anyone could help me. thanks

**Comment by taion** [comment]
`<Container>` passes through its `style` component to the underlying `<div>`. Check with the React debugger and the inspector to see which styles get applied, and which don't. What you end up rendering there is the same as something like `<div className="container-fluid" style={{ ... }}>` with `style` as specified.
