### ISSUE TITLE
TextArea does not get defaultValue

### ISSUE THREAD

**Issue by rebeccacoltaire** [react-bootstrap/react-bootstrap#4851]
## Describe the bug

When rendering a `Form.Control` as a textarea - `defaultValue` does not insert the value into the textarea control on the screen.

## To Reproduce

I load an object {job} for edit from my database in `useEffect()`. The object is loaded correctly.
1. Any form control on the page that is **not** a textarea gets their details populated correctly by using `defaultValue={job.<field>}`
1. Using a form control with `as='textarea'` and providing the regular `defaultValue={job.description}` does not render the text of `job.description` inside the textarea inpt element, but instead - renders the text of the `placeHolder` attribute.
1. The text in {job.description} does get rendered on the page, inside the `textarea` HTML tags (as is expected with HTML), but the input element itself does not display it.
1. putting `placeHolder={job.description}` renders the job's description inside the element, as the placeHolder text.
1. If using `value` instead of `defaultValue` - the expected content is rendered inside (but it is then a controlled input, which requires `onChange`)
1. If using plain old `<textarea>` with `defaultValue` - the expected content is rendered inside.

```
<Form.Group as={Col} md='5' controlId='job.cs1'>
   <Form.Label>Title</Form.Label>
      <Form.Control
                    required
                    type='text'
                    name='title'
                    placeholder='Title'
                    defaultValue={job.title}
                  />
 </Form.Group>
 <Form.Group as={Col} md='5' controlId='job.cs2'>
    <Form.Label>Description</Form.Label>
    <FormControl
                    required
                    as='textarea'
                    placeholder='description'
                    name='description'
                    defaultValue={job.description}
                  />
</Form.Group>
```
## Screenshots
![image](https://user-images.githubusercontent.com/58018522/69302251-e45d8180-0c7d-11ea-8921-2f597f063ecf.png)

![image](https://user-images.githubusercontent.com/58018522/69302312-140c8980-0c7e-11ea-975d-c644ed45c306.png)

## Environment (please complete the following information)

- Operating System: [Ubuntu 16, also tried Windows 10]
- Browser, Version [Chrome 78 ; FF 70]
- React-Bootstrap Version [1.0.0-beta.14, this also happened with 1.0.0-beta.16]

**Comment by taion** [comment]
I'm not sure what your `<FormControl>` (instead of `<Form.Control>`) there is. In our example playgrounds, using e.g.

```js
<Form.Control as="textarea" rows="3" placeholder="foo" defaultValue="asdf" />
```

behaves exactly as expected.

**Comment by rebeccacoltaire** [comment]
This was a typo. I am sorry. My code has `<Form.Control...`

The example you gave above works for me as well, when I enter the defaultValue as an immediate string, but in my case I am loading an object before rendering the form, and I use `defaultValue={job.description}`

The textarea that gets rendered does not display the content of `job.description` in my case.
If I change the `Form.Control` from `as='textarea'` to `type='text'` - it displays the `{job.description}` content correctly.

Sorry if I weren't clear before :(

**Comment by taion** [comment]
That's just how `defaultValue` works. Changing it after mounting isn't going to do anything.

**Comment by rebeccacoltaire** [comment]
Thanks. I know that. But it works for all of the other inputs on the screen - the textarea is the only one where it doesn't. All the other input elements use `defaultValue` too
