### ISSUE TITLE
Clarifying doubts

### ISSUE THREAD

**Issue by apenab** [react-bootstrap/react-bootstrap#4856]
Hello @jquense, what is your opinion about this [Descendants](https://gist.github.com/ryanflorence/10e9387f633f9d2e6f444a9bddaabf6e).
Do you think this could be an improvement in our component.

**Comment by jquense** [comment]
opinion on what specifically? Some of my thoughts, in tweet size, are here: https://twitter.com/monasticpanic/status/1197684053010518016 In general Ryan has robustly describe the problem. We don't have to do aria-activedescendant preferring roving tab indexes, fo the use-cases in RB and I think we're in a good place for that. It'd be nice if we could avoid `eventKey` but it's a simple enough solution to the problem and works well for now

**Comment by bpas247** [comment]
Is there any action items for this issue? or is it okay to go ahead and close?
