### ISSUE TITLE
Access to form values inside functional component

### ISSUE THREAD

**Issue by leabum** [react-bootstrap/react-bootstrap#4859]
I can't find a way to use refs to access the forms values. In the doc I can't find a description for doing that either. I am sure this works somehow and it's not a bug. In the example-code I took the class approach as an example for handling the refs, but how would I do that with e.g. useRef?

```
import React from "react";
import { Modal, Button, Form, Col, Row } from "react-bootstrap";
import Button from "../button/Button";

export default function NewEventModal(props) {

  const onSubmit = (e) => {
    e.preventDefault();
    console.log(e.target.elements) /*How to get name value?*/
  };

  return (
    <Modal
      {...props}
      size="lg"
      aria-labelledby="contained-modal-title-vcenter"
      centered
    >
      <Form onSubmit={(e) => onSubmit(e)}>
          <Modal.Header closeButton>
            <Modal.Title id="contained-modal-title-vcenter">
              Create Event
            </Modal.Title>
          </Modal.Header>
          <Modal.Body>
            <Form.Group controlId="formGridName">
              <Form.Label>Eventname</Form.Label>
              <Form.Control type="text" placeholder="Input the eventname" inputRef={(ref) => { this.name = ref }}/>
            </Form.Group>
          </Modal.Body>
          <Modal.Footer>
            <Button type="submit" text="Erstellen" />
            <Button onClick={props.onHide} text="Close"/>
          </Modal.Footer>
          </Form>
      </Modal>

  );
}

```

**Comment by jquense** [comment]
The form component is only a presentational component over the native HTML form element, it's not a fully fledged form library. To get form values you can use the appropriate HTML API such as form elements and check each inputs value, control each input yourself tracking its value, or use something like formik if you've more complex cases and don't want to write a lot of boilerplate

**Comment by kosmiq** [comment]
This has been answered with no new feedback for more than 7 days. Closing.
