### ISSUE TITLE
Unable to load CSS in Expo  App

### ISSUE THREAD

**Issue by kirenpillay** [react-bootstrap/react-bootstrap#4867]
## Describe the bug

import 'bootstrap/dist/css/bootstrap.min.css'; in my App.js results in 

` Failed building JavaScript bundle.
Unable to resolve "bootstrap/dist/css/bootstrap.min.css" from  "App.js"`

## To Reproduce

1. Go to 'App.js'
2. Add import 'bootstrap/dist/css/bootstrap.min.css'
3. See error

## Expected behavior
Import should work.
## Environment (please complete the following information)

The file does exist in the node_modules folder.

- Operating System: Ubuntu latest
- Browser, Version Android Emulator
- React-Bootstrap Version [e.g. 1.0.0-beta.8]

**Comment by taion** [comment]
This is a web layout library. It's not meant to work with React Native.
