### ISSUE TITLE
Make documentation about the as prop easy to find

### ISSUE THREAD

**Issue by Rillian-Grant** [react-bootstrap/react-bootstrap#4868]
I am a new user and as soon as I found out about what this does it opened up a whole new set of things I could do with react-bootstrap.

**Comment by bpas247** [comment]
Just to clarify the action items for this issue:
Add a new section to the "Getting Started" page that explains the `as` prop API, why it's useful, and how it can be used (give a basic usage example).

**Comment by Rillian-Grant** [comment]
Yes, it would also be good to see some examples of the HTML that the react components are transformed into for people who have past experience of bootstrap but not using react. I have found it invaluable to be able to transfer my existing bootstrap knowledge to react-bootstrap.

**Comment by bpas247** [comment]
> it would also be good to see some examples of the HTML that the react components are transformed into for people who have past experience of bootstrap but not using react.

That sounds like an entirely separate feature than what this issue describes. You should open a new issue to document that separate feature.

**Comment by devtayls** [comment]
@bpas247, I'm happy to take this issue. Can you assign me to assure we don't duplicate work.

I'm quite familiar with Bootstrap, but not with the react-bootstrap package. Is there a good third party source / example of the "as" api to help someone formulate some good documentation?

**Comment by Alef5750** [comment]
Hi - I'm new to open source. Is this issue already being dealt with or can I take a shot at it?

**Comment by kyletsang** [comment]
> 
> 
> Hi - I'm new to open source. Is this issue already being dealt with or can I take a shot at it?

Feel free to take it. Thanks.

**Comment by devtayls** [comment]
Yes. Sorry I was slow to get back to you. This is absolutely open. I've sat
on it for far too long.

**Comment by yelkar-snehal** [comment]
Hi, I'm new to open source. Is this issue still open for grabs?

**Comment by devtayls** [comment]
Yes, it is.

**Comment by rohanrav** [comment]
Hey!

I made a PR (#6007) that addresses this issue. I am relatively new to open source so please feel free to check it out and give me some feedback!

If you don't feel like looking through the entire PR here is what I changed. In the Getting Started -> Introduction page I added the following:

### 'as' Prop API
With certain React-Bootstrap components you can specify a custom elementType to be passed with the 'as' Prop.

This can be especially useful if you want to combine the functionality and styling of two seperate components into one combined component.

```javascript
<Row className="mx-0">
  <Button as={Col} variant="primary">Button #1</Button>
  <Button as={Col} variant="secondary" className="mx-2">Button #2</Button>
  <Button as={Col} variant="success">Button #3</Button>
</Row>
```
