### ISSUE TITLE
Document recommended way to include glyphicons fonts.

### ISSUE THREAD

**Issue by ronjouch** [react-bootstrap/react-bootstrap#487]
Hello.

I couldn't find documentation on the recommended way to include the `glyphicons` eot/svg/ttf/woff/woff2 font set (in a npm/browserify/gulp project).

I thought I'd just have a gulp task copying the fonts from where it lives in `node_modules` to my `dist/fonts` folder (right?),

* ... but `bootstrap` is a `devDependency` of `react-bootstrap`, so my project depending on just `react-bootstrap` doesn't pull it, and the fonts are nowhere to be found in my `node_modules` folder.
* ... and I could make my app depend on `bootstrap`, but then I have to ensure the version of my direct `bootstrap` dep. matches the version of `react-bootstrap`'s `bootstrap` dependency.

Am I missing something? Should I do something entirely different? I'll be glad to submit a PR on the documentation to clarify this.

**Comment by mtscout6** [comment]
We leave it up to downstream users to determine how they get the bootstrap css and fonts. This is because many folks use custom bootstrap themes. We could state that clearer on the Getting Started page of the docs.

**Comment by dozoisch** [comment]
What I personally do is the second one. React-Bootstrap doesn't really depend on any bootstrap version, unless there are big breaking change in the main lib (which are pretty rare). So I have bootstrap in my deps and I include bootstrap.less in my build.

**Comment by ronjouch** [comment]
Thanks @mtscout6 @dozoisch, that helped. Here's a doc PR hopefully clarifying that.

**Comment by ronjouch** [comment]
My initial pull request was funnily done on my repo (doh), here's a proper one.
