### ISSUE TITLE
Warning: Unknown event handler property

### ISSUE THREAD

**Issue by laviro** [react-bootstrap/react-bootstrap#4872]
After #4865 got in,
my tests started to fail with the following error:
```
console.error node_modules/jest-prop-type-error/index.js:8
    onMouseDownDialog 
        in div (created by CustomModalDialog)
        in CustomModalDialog (created by Modal)
        in Transition (created by Fade)
        in Fade (created by DialogTransition)
        in DialogTransition (created by Modal)
        in RefHolder (created by Modal)
        in div (created by Modal)
        in Portal (created by Modal)
        in Modal (created by Modal)
        in Modal (created by DiffModal)
```
and the warning:
`Warning: Unknown event handler property `%s`. It will be ignored.%s`
maybe it is something about a naming convention, see: https://github.com/styled-components/styled-components/issues/2218#issuecomment-489661463

**Comment by mturley** [comment]
Note: I figured out the source of this issue, and it's not actually caused by react-bootstrap. Explanation here: https://github.com/patternfly/patternfly-react/issues/3364#issuecomment-565645973

This issue can be closed.

**Comment by taion** [comment]
Thanks!
