### ISSUE TITLE
Element Form.Label doesn't have required attribute column

### ISSUE THREAD

**Issue by bohdanz1997** [react-bootstrap/react-bootstrap#4873]
## Describe the bug

Webstorm shows the warning when I use Form.Label in my components without `column` attribute, despite the `column` is optional.

## Expected behavior

IDE shouldn't show the warning.

## Screenshots

![d4ff01ace3](https://user-images.githubusercontent.com/16783277/69960107-569d5400-1511-11ea-914a-fdc41cc8a988.jpg)

## Environment (please complete the following information)

- Operating System: Linux Mint 18.3
- Webstorm, 2019.2.1
- React-Bootstrap Version 1.0.0-beta.12

**Comment by taion** [comment]
Well, it's not actually required, and the type checking passes, so this is a bug in your IDE. We can't do anything about that.
