### ISSUE TITLE
Styled Component overwriting bootstrap class names

### ISSUE THREAD

**Issue by Inayat-C** [react-bootstrap/react-bootstrap#4877]
## Describe the bug

When using `styled-components` to style a Bootstrap component, it overwrites all default class names. For example: 

if i write: 
`<Col sm="6"> <h1> Hello World </h1> </Col>` 

It will render: 
`<div class="col-sm-6"> <h1> Hello World </h1> </div>"`

Which is perfect.

However, if i want to add custom styled to the component via `styled-components`, it will overwrite the bootstrap classnames instead of adding to it.

## Reproducible Example

https://codesandbox.io/s/react-x9e94

**Comment by taion** [comment]
the issue here is you're doing `<StyledCol as="section">`, so it's rendering a `<section>` instead of rendering a `<Col as="section">`. so this is an issue with your code – the R-B component is not getting rendered at all here.

**Comment by Inayat-C** [comment]
Thanks for the reply.

I understand where you're coming from, but shouldn't that still work? The `as` prop is documented in R-B to allow me to use a custom element type for this component.

**Comment by Inayat-C** [comment]
Ok i've figured out the solution. This is what i needed: https://www.styled-components.com/docs/api#forwardedas-prop

Thanks for your time!
