### ISSUE TITLE
Accessibility - NavDropdown created empty aria-labelledby="" attribute

### ISSUE THREAD

**Issue by colinmanuel** [react-bootstrap/react-bootstrap#4878]
When testing accessibility with the browser plugin "SiteImprove", I see a number of errors related to the <NavDropdown> element generating an empty aria-labelledby attr. This error also appears on the react-bootstrap <NavDropdown> documentation page.

One specific error that appears is: **"Aria-labelledby" has incorrect (ID) reference 1.3.1 Info and Relationships**

The generated code on the page is:

```
<div class="dropdown-menu" aria-labelledby=""><span id="dropdownNavLabel">Edit Your
    Pages</span>
  <div class="nav-item"><a href="#" class="dropdown-item">Personal
      Page</a></div>
  <div class="nav-item"><a href="#" class="dropdown-item">Team Page</a>
  </div>
</div>
```

Is this empty aria-labelledby attribute intentional? If so, what is the reasoning behind it? If it's not intentional, is there a simple way to remove it or provide it a value within my code?

Thanks,

Colin

**Comment by jquense** [comment]
are you providing an ID to the toggle? It may be the NavDropdown isn't passthing `id` through correctly as well

**Comment by colinmanuel** [comment]
Yes, I've tried passing an ID and aria-labelledby value through NavDropdown and neither one populates aria-labelledby in the <div class="dropdown-menu"> element. 

Here's the react-bootstrap markup I'm using for NavDropdown:
 ```
  <NavDropdown
                    title="Edit Your Pages"
                    id="navDropdown"
                    className="edit-pages-dropdown"
                    aria-labelledby="dropdownNavLabel"
                  >
```

**Comment by kyletsang** [comment]
I just tried this on 1.3.0 and `aria-labelledby` is there now.  Closing issue.
