### ISSUE TITLE
When I manually swipe from the first slide to the left to the last slide, the animation of the slide switch is not to the left but to the right

### ISSUE THREAD

**Issue by zhangyu0218** [react-bootstrap/react-bootstrap#4879]
When I manually swipe from the first slide to the left to the last slide, the animation of the slide switch is not to the left but to the right。

I think the direction of the slides should be the same as the gesture。

**Comment by zhangyu0218** [comment]
In Carousel

**Comment by taion** [comment]
dupe https://github.com/react-bootstrap/react-bootstrap/issues/3654
