### ISSUE TITLE
Carousel: Unable to wrap controllable Carousel in Link due to SafeAnchor component

### ISSUE THREAD

**Issue by ossiggy** [react-bootstrap/react-bootstrap#4882]
## Describe the bug

When you are trying to wrap a Carousel with controls in a `<Link/>` component, it throws an error since anchor tags can't be children of anchor tags. Could probably be fixed by changing the SafeAnchor to a Button.

## To Reproduce

1. Create a Carousel Component
2. Wrap it in a `<Link/>` component from `react-router-dom`
3. Render the page
4. See error in dev-tools console

## Expected behavior

I did not realize that the `prev` and `next` controls were anchors, so I did not expect the error to be thrown. 

## Screenshots

![Screen Shot 2019-12-07 at 1 42 39 PM](https://user-images.githubusercontent.com/25465032/70379195-86749f00-18f7-11ea-9303-25df40eaaecd.JPG)

## Environment (please complete the following information)

- Operating System: MacOS HighSierra
- Chrome 78.0.3904.108
- React-Bootstrap Version: ^1.0.0-beta.14

**Comment by taion** [comment]
Why are you rendering the entire carousel under an `<a>` anyway?

**Comment by ossiggy** [comment]
I want it to link to a gallery page.

**Comment by taion** [comment]
You should link the individual carousel items, then. The carousel items are supposed to render as `<a>`s, and it's ill-defined to have nested controls within what's already a link.
