### ISSUE TITLE
Form.Label[as="legend"] does not create a legend element

### ISSUE THREAD

**Issue by hguiney** [react-bootstrap/react-bootstrap#4883]
## To Reproduce

1. `import Form from "react-bootstrap/Form";`
2. Render `<Form.Label as="legend" />`

## Reproducible Example

[CodeSandbox](https://codesandbox.io/s/code-sandbox-examples-78kv4?fontsize=14&hidenavigation=1&theme=dark)

## Expected behavior

Renders a `<legend>`.

## Actual behavior

Renders a `<label>`.

## Environment

- Operating System: macOS Catalina 10.15
- Browser, Version: Google Chrome 78.0.3904.108 (Official Build) (64-bit)
- React-Bootstrap Version: 1.0.0-beta.16

## Additional context

Docs show `as="legend"` syntax in Form examples: https://react-bootstrap.github.io/components/forms/

**Comment by taion** [comment]
Looks like `<FormLabel>` doesn't support the `as` prop at all. We'd be happy to take a PR adding support, analogous to how it's done on other components.

**Comment by nbriannl** [comment]
Interested in taking this up 👍

**Comment by taion** [comment]
thanks!
