### ISSUE TITLE
Support for Responsive Containers (Bootstrap 4.4)

### ISSUE THREAD

**Issue by davidjb** [react-bootstrap/react-bootstrap#4884]
## Is your feature request related to a problem? Please describe

Bootstrap 4.4 added responsive containers (https://getbootstrap.com/docs/4.4/layout/overview/#responsive),  with the syntax `.container-{breakpoint}`.

## Describe the solution you'd like

Add support for setting a breakpoint prop on `Container` components, which then sets the resultant `className`.

## Describe alternatives you've considered

A workaround is to use `<div className="container-lg">` and manually create the container.

Using `<Container className="container-lg">` isn't suitable as a solution given how the [classes operate](https://getbootstrap.com/docs/4.4/layout/overview/#containers) (eg it has no effect)

**Comment by taion** [comment]
We'd be happy to take a PR for this!

**Comment by kosmiq** [comment]
@taion this can be closed since the PR has been merged.
