### ISSUE TITLE
Form.Label does not have size prop

### ISSUE THREAD

**Issue by raghavi92** [react-bootstrap/react-bootstrap#4886]
## Describe the bug
I would like to set the size for Form.Control and its corresponding Form.Label components.
While its working as expected for Form.Control prop, Form.Label component does not have a similar size prop. 

## Reproducible Example

Minimal example by using [CodeSandbox](https://codesandbox.io/s/react-bootstrap-3kswo).

## Expected behavior

The size of the label should be applied accordingly.

## Environment (please complete the following information)

- Operating System: [Ubuntu]
- Browser, Version [Chrome 78]
- React-Bootstrap Version [1.0.0-beta.16]

**Comment by taion** [comment]
The `column` prop for `Form.Label` should probably take a size per https://getbootstrap.com/docs/4.3/components/forms/#horizontal-form-label-sizing.

We'd be happy to take a PR for this.

**Comment by raghavi92** [comment]
Thank you. I'll make a PR
