### ISSUE TITLE
Support for row-cols in <Row>

### ISSUE THREAD

**Issue by kosmiq** [react-bootstrap/react-bootstrap#4887]
## Is your feature request related to a problem? Please describe
Bootstrap 4.4 added .row-cols-x classes to the row class (https://getbootstrap.com/docs/4.4/layout/grid/#row-columns)

This would be an awesome addition to react-bootstrap.

## Describe the solution you'd like
I'd imagine something like
`<Row xs={[number]}></Row>`

Thus having a similar usage as <Col> does when defining widths of columns.

The docs would of course need to be updated to reflect this.

## Describe alternatives you've considered
I did briefly consider that it could be set as
`<Row cols={[number]}></Row>`
but then we would need
`<Row cols-xs={[number]}></Row>`
or similar to define breakpoints and that feels less clean.

## Additional context
Bootstrap docs for row-cols: https://getbootstrap.com/docs/4.4/layout/grid/#row-columns

**Comment by taion** [comment]
We'd be happy to take a PR for this. I think e.g. a `colsXs` prop would be pretty reasonable, actually. It'd match what we have for `<Col>`.

**Comment by bcobra** [comment]
When will this be released?

**Comment by kyletsang** [comment]
This is available in 1.0.1:  https://react-bootstrap.github.io/layout/grid/#row-layout-col-sizing

This can be closed
