### ISSUE TITLE
OnCloseRef.current() is not a function

### ISSUE THREAD

**Issue by whyseman** [react-bootstrap/react-bootstrap#4889]
## Describe the bug

Tried to use the toast with autohide prop, it **doesn't** hide after the specified **delay** and it throws `onCloseRef.current is not a function > Toast.js:45` in the browser console.

## To Reproduce

1. Create a Toast component
2. Add the `autohide` prop with `delay` prop
3. Watch the browser console.

## Reproducible Example

```js
const ToastBody = () => (
    <div className={`d-flex justify-content-between ${type === 'success' ? 'toast__notifications__success' : type === 'error' ? 'toast__notifications__error' : type === 'alert' ? 'toast__notifications__alert' : 'toast__notifications__info'}`}>
        <FontAwesomeIcon icon={icon} color='#fff' size='lg' />
        <span className='toast__notifications__text d-flex align-items-center'>{children}</span>
        <span className='toast__notifications__icon' onClick={closeToast}>&times;</span>
    </div>
);

return (
    <Toast className='toast__notifications' delay={duration} show={show} autohide={true} >
        <ToastBody />
    </Toast>
);
```

## Expected behavior

Toast should autohide after specified delay. (`delay={number}`)

## Environment (please complete the following information)

- Operating System: Windows 10 Version 1909
- Browser, Version: Firefox, 71 
- React-Bootstrap Version: 1.0.0-beta.16

**Comment by whyseman** [comment]
Nevermind, it needs the `onClose` attribute on the `<Toast />` component.

**Comment by taion** [comment]
Okay, so this is resolved, then?

**Comment by whyseman** [comment]
@taion I guess it is. I managed to make it work by adding the `onClose` prop and the `onClose` prop changes the state of the `show` prop.
