### ISSUE TITLE
Missing property target for Button

### ISSUE THREAD

**Issue by AHorak** [react-bootstrap/react-bootstrap#4892]
Because Button can act as a link, Button has a href property.
But target is missing.

<Button variant="secondary" href="/relativepath/mydoc.pdf", target="_blank">

**Comment by taion** [comment]
<Button> forwards all props to the underlying component, so what you have already works.

**Comment by AHorak** [comment]
Does not work for me :-(
(TS) No overload matches this call.
  Overload 1 of 2, '(props: Readonly<ReplaceProps<"button", BsPrefixProps<"button"> & ButtonProps>>): Button<"button">', gave the following error.
    Type '{ href: string; target: string; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Button<"button">> & Readonly<ReplaceProps<"button", BsPrefixProps<"button"> & ButtonProps>> & Readonly<...>'.
      Property 'target' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Button<"button">> & Readonly<ReplaceProps<"button", BsPrefixProps<"button"> & ButtonProps>> & Readonly<...>'.
  Overload 2 of 2, '(props: ReplaceProps<"button", BsPrefixProps<"button"> & ButtonProps>, context?: any): Button<"button">', gave the following error.
    Type '{ href: string; target: string; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Button<"button">> & Readonly<ReplaceProps<"button", BsPrefixProps<"button"> & ButtonProps>> & Readonly<...>'.
      Property 'target' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Button<"button">> & Readonly<ReplaceProps<"button", BsPrefixProps<"button"> & ButtonProps>> & Readonly<...>'.

**Comment by taion** [comment]
This looks like a bug in the type definitions, then. The default `as` doesn't account for `<SafeAnchor>`. We'd be happy to take a PR here.

**Comment by AHorak** [comment]
Thank you!
It works, if i do it like that:

<Button as="a" href="https://www.google.com" target="_blank" variant="secondary">
