### ISSUE TITLE
next.js jsx css does not work with components

### ISSUE THREAD

**Issue by Jonofat** [react-bootstrap/react-bootstrap#4894]
I have been trying to style a list group item and couldn't figure out why the styles weren't applying. This is the code:

```
<ListGroup variant="flush">
            <ListGroup.Item>
            Some lorem text
            </ListGroup.Item>
            <style jsx>{`
              .list-group-item {
                background: #343a40 !important;
              }
            `}</style>
</ListGroup>
```

But I found that the css works if I just type the list group item out normally like this:

```
<div className="list-group-item">lorem text</div>
            <style jsx>{`
              .list-group-item {
                background: #343a40 !important;
              }
            `}</style>
```

Is there a way to get the jsx styles to work with the components? If not then there isn't really a point in using React Bootstrap since I am going to have to type out all the bootstrap class names to get the css to apply.

```

**Comment by jquense** [comment]
I don't think any of us know anything about Next's css solution here, but guessing. Next almost certainly hashes the class names in the style tags. In your first example the style that is added is not on `.list-group-item` it ends up being something like `.dgasg0rt32` when compiled. You need to do something like:

<ListGroup variant="flush">
            <ListGroup.Item className="item">
            Some lorem text
            </ListGroup.Item>
            <style jsx>{`
              .item {
                background: #343a40 !important;
              }
            `}</style>
</ListGroup>
```

to add classes just like you would anywhere else. Otherwise you'd be changing a global style not just the style of the element here
