### ISSUE TITLE
Set size in <Form.Control> will resolve duplicated 'form-control` classes.

### ISSUE THREAD

**Issue by waynecw** [react-bootstrap/react-bootstrap#4901]
## Describe the bug

`<Form.Control size='sm'>` will resolve to two `form-control` and `form-control-sm` classes.
```
<input ... class="form-control form-control-sm">
```

`form-control` will overwrite `form-control-sm` settings in Bootstrap.

## To Reproduce

Set `size` in `<Form.Control>`

## Reproducible Example

A quick example in [CodeSandbox](https://codesandbox.io/s/charming-liskov-ulpf7).

## Expected behavior

Only `form-control-sm` is shown in translated `<input>`.

## Screenshots

Please see CodeSandBox above.

## Environment (please complete the following information)

- Operating System: macOS
- Browser, Version: Chrome 79
- React-Bootstrap Version: seen in 1.0.0-beta.8 and 1.0.0-beta.6

## Additional context

I don't mind to fix it but am a newbie to javascript world and need to learn how to fix npm modules.

**Comment by taion** [comment]
The TWBS examples show using e.g. both `.form-control` and `.form-control-sm`: https://getbootstrap.com/docs/4.4/components/forms/#sizing. If you're having issues, then it's more likely with your CSS specifically.
