### ISSUE TITLE
Cannot scroll thru the components list in the documentation/website

### ISSUE THREAD

**Issue by anthonylamark** [react-bootstrap/react-bootstrap#4909]
## Describe the bug

The list of components does not have a scroll bar so you cannot view all the components..

## To Reproduce

1. Go to https://react-bootstrap.github.io/components/alerts
2. The left side of the page has all the components but you cannot scroll to the bottom of the components list.

## Reproducible Example

N/A

## Expected behavior

Be able to scroll thru the list of all the components.

## Environment (please complete the following information)

- Operating System: Windows 10
- Browser, Version Chrome 79
- React-Bootstrap 1.0.0-beta.16

## Additional context

N/A

**Comment by taion** [comment]
dupe https://github.com/react-bootstrap/react-bootstrap/issues/3765
