### ISSUE TITLE
Failed to build on Windows. 'rm' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by andrerpena** [react-bootstrap/react-bootstrap#491]
I'm trying to build on Windows and it fails. 

Error:

    'rm' is not recognized as an internal or external command

Screenshot:

![image](http://i.imgur.com/VZuoDUI.png)

**Comment by mathieumg** [comment]
Following from https://github.com/react-bootstrap/react-bootstrap/issues/471 I think you need to use a shell (Git Bash for example) to get things working properly.

**Comment by AlexKVal** [comment]
Matt @mtscout6 did great job for this project to build on Windows just a few days ago.
My PR is just two final strokes :)
As temporary solution till next release one can change `rm -rf` -> `rimraf` in two files
tools/dist/build.js
tools/lib/build.js

**Comment by mtscout6** [comment]
Fixed by #492
