### ISSUE TITLE
Inactive <ListGroup.Item> nested in active <ListGroup.Item> is invisible

### ISSUE THREAD

**Issue by garrett-gottlieb** [react-bootstrap/react-bootstrap#4911]
Nesting `<ListGroup>`s inside of a `<ListGroup.Item>` isn't supported if the outer item is `active` and the inner item is not.

<img width="274" alt="Screen Shot 2019-12-26 at 1 24 58 PM" src="https://user-images.githubusercontent.com/1219054/71486204-36e10f00-27e3-11ea-92c7-2b2697d6f91c.png">
<img width="260" alt="Screen Shot 2019-12-26 at 1 25 04 PM" src="https://user-images.githubusercontent.com/1219054/71486205-36e10f00-27e3-11ea-91f9-8b06ce563582.png">

**Comment by taion** [comment]
Does this work in upstream TWBS?

**Comment by garrett-gottlieb** [comment]
Not sure what that is but I only used this package.

**Comment by harsh6646** [comment]
My team and I worked on a solution for this here:
https://github.com/react-bootstrap/react-bootstrap/pull/5104

**Comment by kosmiq** [comment]
This is an issue in Bootstrap: https://codesandbox.io/s/nervous-turing-bruhx?file=/index.html

We should probably not solve this on our end

**Comment by harsh6646** [comment]
Hey thanks for the feedback. While it may not be a part of bootstrap this is an opt-in kind of feature. It doesn't break any of the bootstrap stuff, just makes it easier for users as they don't have to explicitly mark every single item.
If this is fine with you I can change this to a class based implemented rather than using a new prop.

**Comment by kosmiq** [comment]
@taion @jquense your call here.

**Comment by taion** [comment]
I don't think we should do anything here. The upstream has no formal support for nested list groups at all, as far as I can tell. Given that, and that this is a CSS issue, it seems reasonable that anybody who wants to use nested list groups should supply their own CSS as appropriate to handle this case.
