### ISSUE TITLE
Enzyme simulate button click not working on Nav.Link

### ISSUE THREAD

**Issue by refayathaque** [react-bootstrap/react-bootstrap#4924]
Hi guys, I'm trying to use Enzyme's [simulate](https://airbnb.io/enzyme/docs/api/ShallowWrapper/simulate.html) function to be able to click on a `Nav.Link` component but can't. I've used this function on the standard html `button` before with the attribute `data-test...` I'm guessing since the `Nav.Link` component is essentially a React component, enzyme will need access to a 'clickable' element within it. I just started working with Enzyme so I do not know much about how to access standard html elements inside React-Bootstrap components. Appreciate the help!

**Comment by taion** [comment]
This doesn't look to be specific to us – the same would apply to any component that indirectly renders a link. Make sure you're properly specifying an `href` or an `onClick` handler as appropriate.

**Comment by refayathaque** [comment]
@taion thank you so much for the guidance. Yes, this wasn't really a bug issue, it was more of a help request. I'll need to poke around more to figure out how to `simulate` a 'click' on what are clearly clickable React-Bootstrap components. I'll look into figuring out if I can access child components of my component rendering the `Nav.Link` component, that way I might be able to access the actual `button` element.
