### ISSUE TITLE
Overlays' target is no longer correctly selected

### ISSUE THREAD

**Issue by sergioadimedia** [react-bootstrap/react-bootstrap#4928]
## Describe the bug
https://github.com/react-bootstrap/react-bootstrap/commit/50a37146cb372fe708efe11815d3ee9f468518ca#r36745060

Due to the change of version of the "react-overlays" package the target is no longer correctly selected. 

Apparently they used to use something like this to get the target html element:
` _reactDom.default.findDOMNode(target)`
Now they use:
`useWaitForDOMRef(props.target); `

NOT working on >= react-bootstrap@1.0.0-beta.14

**Comment by taion** [comment]
This was an intentional breaking change. You need to specify an actual DOM node now, not a React node. See the docs.
