### ISSUE TITLE
Components inside of an OverlayTrigger don't set 'ref'

### ISSUE THREAD

**Issue by johnhaley81** [react-bootstrap/react-bootstrap#493]
I have the following code:

```javascript
<div>
  <OverlayTrigger placement='bottom' trigger='focus' ref='overlay' overlay={<Tooltip>Focused</Tooltip>}>
    <Input ref='input' type='text' />
  </OverlayTrigger>
</div>
```

Now say you're trying to do something with the dom node in `componentDidUpdate`

```javascript
componentDidUpdate: function() {
  var inputNode = this.refs.input; // inputNode === undefined
  inputNode = this.refs.overlay.refs.input; // inputNode === undefined
}
```

Shouldn't the ref be set for the `Input`?

**Comment by mtscout6** [comment]
Related conversation: https://gitter.im/react-bootstrap/react-bootstrap?at=552562d46a9fcf773a6e809b

**Comment by taion** [comment]
This doesn't reproduce for me. `this.refs.input` resolves fine. This was most likely an issue with `cloneWithProps` hijacking `ref`, and the update to use `cloneElement` with React 13.x resolved this as a side effect.
