### ISSUE TITLE
Carousel 'onSlideEnd' not triggered in IE

### ISSUE THREAD

**Issue by JoshuaWarejko** [react-bootstrap/react-bootstrap#4933]
## Describe the bug

When using onSlideEnd on the `<Carousel>` component in Internet Explorer 11, the onSlideEnd method passed through the props is not called.

## To Reproduce

1. Add onSlideEnd handler to `<Carousel>`
2. Click arrow and see that method is never called.

## Expected behavior

The onSlideEnd method should be fired once the carousel finishes transitioning to the next/prev slide.

## Environment (please complete the following information)

- Operating System: Windows 10
- Browser, Version: IE 11
- React-Bootstrap Version: 1.0.0-beta.11

## Additional context

Noticed that inside the transitionEnd.js file in the react-bootstrap package, the `TRANSITION_SUPPORTED` variable is always false for IE and so it runs the `emulateTransitionEnd` method and does not pass the handler through. The handler is what is responsible for calling the onSlideEnd method that you provide.

**Comment by taion** [comment]
We'd be happy to take a PR to address this.

**Comment by JoshuaWarejko** [comment]
@taion So do you guys not intend on fully supporting Internet Explorer then?

**Comment by JoshuaWarejko** [comment]
@taion after further investigation, this issue isn't with react-bootstrap. The issue is in the dom-helpers package. Their `transitionEnd` function is the issue. Thanks anyway.

**Comment by taion** [comment]
as noted, root cause is https://github.com/react-bootstrap/dom-helpers/issues/70

**Comment by kyletsang** [comment]
Tested on IE 11 and the `onSlid` callback works now.

This can be closed.
