### ISSUE TITLE
Attempted import error: 'Glyphicon' is not exported from 'react-bootstrap'.

### ISSUE THREAD

**Issue by Q8root** [react-bootstrap/react-bootstrap#4936]
Trying to use Glyphicon on my project but giving error :-

> ./src/product/vote.js
> Attempted import error: 'Glyphicon' is not exported from 'react-bootstrap'.

Here is my code:-
import React, { Component } from 'react';
import { Glyphicon } from 'react-bootstrap';

```
class Vote extends Component {
  constructor(props){
    super(props);
  }
  }

  render(){
    return (
      <div className="productVote">
      <Glyphicon glyph="star" />

      </div>
    );
  }
}

export default Vote;

```

- Operating System: macOS
- Browser, Chrome
- React-Bootstrap Version : 0.33.1

**Comment by taion** [comment]
Are you sure you don't have one of the v1 betas installed?

**Comment by Q8root** [comment]
> Are you sure you don't have one of the v1 betas installed?

Here is my package.json content :-
```
{
  "name": "ubill",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.3.2",
    "@testing-library/user-event": "^7.1.2",
    "react": "^16.12.0",
    "react-bootstrap": "0.33.1",
    "react-dom": "^16.12.0",
    "react-scripts": "3.3.0"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}

```

**Comment by taion** [comment]
looks like something wrong with your setup. the export is definitely there: https://unpkg.com/browse/react-bootstrap@0.33.1/lib/index.js#L100

**Comment by shreya-bhatnagar** [comment]
> 
> 
> Trying to use Glyphicon on my project but giving error :-
> 
> > ./src/product/vote.js
> > Attempted import error: 'Glyphicon' is not exported from 'react-bootstrap'.
> 
> Here is my code:-
> import React, { Component } from 'react';
> import { Glyphicon } from 'react-bootstrap';
> 
> ```
> class Vote extends Component {
>   constructor(props){
>     super(props);
>   }
>   }
> 
>   render(){
>     return (
>       <div className="productVote">
>       <Glyphicon glyph="star" />
> 
>       </div>
>     );
>   }
> }
> 
> export default Vote;
> ```
> 
>     * Operating System: macOS
> 
>     * Browser, Chrome
> 
>     * React-Bootstrap Version : 0.33.1

hey ,

have you got solution to this ?
I am also facing the same issue:


./src/components/Home.jsx
Attempted import error: 'Glyphicon' is not exported from 'react-bootstrap'.
Error from chokidar (C:\): Error: EBUSY: resource busy or locked, lstat 'C:\hiberfil.sys'
Error from chokidar (C:\): Error: EBUSY: resource busy or locked, lstat 'C:\pagefile.sys'
Error from chokidar (C:\): Error: EBUSY: resource busy or locked, lstat 'C:\swapfile.sys'

**Comment by bedamatta05** [comment]
@shreya-bhatnagar  hey did u solve that? im facing the same issue now.
