### ISSUE TITLE
Eslint `Do not use setState in componentDidMount` warning in docs/src/ComponentsPage.js

### ISSUE THREAD

**Issue by AlexKVal** [react-bootstrap/react-bootstrap#494]
This code [docs/src/ComponentsPage.js#L39](https://github.com/react-bootstrap/react-bootstrap/blob/bfb3e6c02cd80488c4a41962d4fc61eb6ec5afdd/docs/src/ComponentsPage.js#L39)
causes in 'Do not use setState in componentDidMount' warning.

It has to be determined how to refactor it.
For now it will be just muted by 
```javascript
/* eslint react/no-did-mount-set-state: 0 */
```
More about this issue is here #490.

**Comment by AlexKVal** [comment]
It seems legit the use of `setState()` in `componentDidMount()` in this particular case.

`Affix` component needs the `offsetTop` and `offsetBottom` properties to be set
to be able to position itself right place on the page.

Values for them are calculated with use of `domUtils.getOffset()` 
and `domUtils.getComputedStyles()` methods.
This calculation is only possible by using rendered HTML elements.

We gain access to these rendered HTML only in `componentDidMount()` method.

In it the offsets calculation is done. 
Then we have to save somewhere these new values.
It is possible with use of `this.state` or `this._vars` for it.
But at the end we have to re-render `Affix` component with these values set.

Certainly one of approaches is to add new method to `Affix`;
something like `updateOffsets()` in which the component re-renders itself then.

But `React` paradigm is `re-render whole page on every change`.

Therefore in this particular case we can just use `setState()` 
and let the `React` do that all hard work.

In result that's what we have:
`ComponentsPage` renders itself (with `Affix`'s offsets have been set to `null`).
Then using the real DOM, new values for offsets for `Affix` component are calculated.
Re-rendering of `ComponentsPage` is done with new offsets and it happens only once.

Unless it is possible to calculate those offsets before rendering `ComponentsPage`
and without the use of DOM methods, for now it is the only way as far as I can imagine.

I am not an expert in `React`, but in all articles that I've been able to find in Internet about
`React after render calculations`, they are using `setState()` in `componentDidMount()`.
At least for >=0.13 version of `React`.

For that reason I propose to close the Issue as solved.
If somebody will be interested why this warning has been muted, 
they surely can find this post by git `blame`.

**Comment by mtscout6** [comment]
Sounds good to me, we have larger fish to fry anyways.

**Comment by niftylettuce** [comment]
What was the resolution on this?  Why do ESLint errors still get thrown here with this error?  Why does this rule even still exist then?

**Comment by taion** [comment]
They don't get thrown there - the errors are suppressed.

**Comment by cdstanhope** [comment]
These errors aren't suppressed, not using eslint-plugin-react 3.10.0 anyway.
