### ISSUE TITLE
New release with PRs?

### ISSUE THREAD

**Issue by kosmiq** [react-bootstrap/react-bootstrap#4947]
## Is your feature request related to a problem? Please describe
Not really a problem per se. Just a question of when we can expect the next release and what will be included.

## Describe the solution you'd like
Merging of a few PR's and a new release published.

## Describe alternatives you've considered
A new release with less PR's merged.

## Additional context
About to migrate a project to react-bootstrap and would love having a new release with
#4900 
#4884 
and other merged PR's that brings some quality of life improvements :)

**Comment by jquense** [comment]
Yup we are waiting for a 1 or two more PRs to get in first
