### ISSUE TITLE
NavDropdown doesn't render its children as HTML before being clicked once

### ISSUE THREAD

**Issue by jpreynat** [react-bootstrap/react-bootstrap#4954]
## Describe the bug

When using a `NavDropdown` in a `NavBar`, its children don't render as HTML before being clicked.
This is very impeding for website crawlability since all links in the dropdown won't be parsed in the page.

## To Reproduce

```tsx
function NavBar() {
  return (
    <Navbar>
      <Navbar.Collapse>
        <Nav>
          <NavDropdown>
            {/** Will not render before being clicked... */}
            <Nav.Item>
              <Nav.Link href="/a-link">
                A Link
              </Nav.Link>
            </Nav.Item>
           {/** ...until here */}
          </NavDropdown>
        </Nav>
      </Navbar.Collapse>
    </Navbar>
  );
}
```

## Reproducible Example

https://codesandbox.io/s/friendly-davinci-82ws6
Inspect the rendered HTML in the frame **before** clicking on the dropdown toggle.

## Expected behavior

Elements should be rendered but not visible (same as after click).

## Screenshots

![image](https://user-images.githubusercontent.com/7927876/73363501-2839bc00-42a9-11ea-8bb6-56ba837f78ef.png)

## Environment (please complete the following information)

- Operating System: Any
- Browser, Version: Any
- React-Bootstrap Version: Latest (beta.16)

**Comment by taion** [comment]
@jquense should we make this configurable?

**Comment by jpreynat** [comment]
Friendly ping on this issue, since it affects the rendered HTML of our homepage.

**Comment by taion** [comment]
unfortunately i can't really comment on what to do here because i'm not familiar with why we originally did dropdown menus this way. i guess the idea is that we want them e.g. hidden for screen readers, but still rendered such that crawlers see them? it sounds reasonable to me but i can't really comment further as i don't know why we're hiding the menus to start with

**Comment by jpreynat** [comment]
@taion, indeed, this is what I had in mind.
Maybe they were implemented this way to prevent extra-rendering at the initial render, since the elements are always rendered after the initial click.
I understand the logic behind this, but it would be great to at least make this configurable as opt-in.

**Comment by jquense** [comment]
we can make it configurable. We originally did it as an optimization I believe.

**Comment by taion** [comment]
cool! @jpreynat feel free to send in a PR that adds the config option, then

**Comment by kyletsang** [comment]
This can now be configured using the `renderMenuOnMount` prop in 1.0.1. 

https://react-bootstrap.github.io/components/navs/#nav-dropdown-props

Closing issue.
