### ISSUE TITLE
React-bootstrap carousel don't start inside react-visibility-sensor when change interval value dynamically

### ISSUE THREAD

**Issue by pdhung197** [react-bootstrap/react-bootstrap#4956]
I have a problem with React-Bootstrap Carousel component that i am not sure if it is a bug on the library.
I'm using `React-Bootstrap Carousel` component inside `react-visibility-sensor` component, like this:

```
<VisibilitySensor>
	{
		({ isVisible }) => (
			<Carousel
				activeIndex={activeIndex}
				controls={false}
				interval={isVisible ? 3000 : null}
				onSelect={this.handleChangeActiveIndex}
				fade={fade}
			>
				{
					images
				}
			</Carousel>
		)
	}
</VisibilitySensor>
```
When `VisibilitySensor` component's changed, `isVisible` will be changed and interval value will be changed to null (for stop carousel) or 3000.  
But, currently, when VisibilitySensor component's changed, `isVisible` was changed, component was re-render but Carousel not start slide (on `isVisible` is true).  
Is it a bug ? Or is a my mistake.
Thanks.

**Comment by taion** [comment]
Looks like a bug here where we don't support changes to `interval` in that manner.

**Comment by kyletsang** [comment]
Tested this on Chrome and the Carousel now starts/stops when interval is changed to a number/null.

This can be closed.

**Comment by taion** [comment]
thanks!
