### ISSUE TITLE
Missing border-radius for `Form.Control` when preceded with `InputGroup.Prepend`

### ISSUE THREAD

**Issue by francoisrouault** [react-bootstrap/react-bootstrap#4958]
## Describe the bug

Missing border-radius for `Form.Control` when preceded with `InputGroup.Prepend`

## To Reproduce

Go and see `Username` input field in https://react-bootstrap.netlify.com/components/forms/#forms-validation-native

## Reproducible Example

https://codesandbox.io/s/mystifying-shape-0vuhy

## Expected behavior

We should see a right border radius (top and bottom).

## Screenshots

![Capture d’écran 2020-01-31 à 10 01 35](https://user-images.githubusercontent.com/2499356/73529177-89cb6900-4416-11ea-9170-df533e9b59b0.png)

## Environment

- Operating System: macOS 10.15.2
- Browser, Version : Chrome 78.0.3904.108 (Build officiel) (64 bits)
- React-Bootstrap Version : 1.0.0-beta.16

**Comment by edvincandon** [comment]
This is due to the `<Form.Control.Feedback>` colliding with the `.input-group>.form-control:not(:first-child)` css rule.

**Comment by francoisrouault** [comment]
You are right, it is indeed a bootstrap 4.4  CSS issue when adding a `<div class="invalid-feedback">`.

We have the same issue in bootstrap documentation : https://getbootstrap.com/docs/4.4/components/forms/?#custom-styles

<img width="1440" alt="Capture d’écran 2020-02-01 à 11 10 57" src="https://user-images.githubusercontent.com/2499356/73590617-cebdd100-44e4-11ea-8c2d-46f747238946.png">
<img width="1440" alt="Capture d’écran 2020-02-01 à 11 09 45" src="https://user-images.githubusercontent.com/2499356/73590618-cebdd100-44e4-11ea-9531-c9584a811991.png">

**Comment by francoisrouault** [comment]
So I close this issue to open another one in bootstrap repo https://github.com/twbs/bootstrap/issues/30116
