### ISSUE TITLE
Variables access inside map loop cannot be shown in tab horizontally

### ISSUE THREAD

**Issue by Shuhui11** [react-bootstrap/react-bootstrap#4959]
Hi, I want to have my variables displayed in a horizontal tabs. When I mapped my state variables to a tab each, it automatically set the tab in a vertical column. How can I circumvent around this?

![Screenshot 2020-01-31 at 5 46 30 PM](https://user-images.githubusercontent.com/47220371/73529450-adf86b80-4451-11ea-82b7-e0ba16280894.png)

This is the output:
![Screenshot 2020-01-31 at 5 49 31 PM](https://user-images.githubusercontent.com/47220371/73529692-1b0c0100-4452-11ea-9a7f-84be9a5eec6c.png)

While I am looking for something more like:
![Screenshot 2020-01-31 at 5 49 49 PM](https://user-images.githubusercontent.com/47220371/73529722-23643c00-4452-11ea-9606-21073e719bb4.png)

This is the json file which I got my variables from:
![Screenshot 2020-01-31 at 5 51 08 PM](https://user-images.githubusercontent.com/47220371/73529809-4858af00-4452-11ea-9106-f8d07384df82.png)

Thank you.

**Comment by taion** [comment]
This looks like a CSS issue on your side. Note that things look fine here: https://react-bootstrap.github.io/components/tabs/

Make sure that you have the right CSS loaded, and that the version of the CSS you're using matches the version of React-Bootstrap that you have.

**Comment by Shuhui11** [comment]
@taion I'm not quite sure if I get you.

If I were to hard-code it in, it works. 

![Screenshot 2020-02-01 at 11 06 13 AM](https://user-images.githubusercontent.com/47220371/73586214-cf566780-44e4-11ea-915a-bd34edf890c2.png)

I manage to get the tabs in horizontal, so I would think that my CSS is loaded correctly:

![Screenshot 2020-02-01 at 11 05 59 AM](https://user-images.githubusercontent.com/47220371/73586219-d8dfcf80-44e4-11ea-84f4-54050b5accdf.png)

But if I want to map my state variables to a tab each, it is shown vertically by default. So, I am wondering if there is a way to work around this. Thank you.

**Comment by taion** [comment]
You need to have a single `<Tabs>` and then use the map to populate each individual `<Tab>`.
