### ISSUE TITLE
Dead links in documentation.

### ISSUE THREAD

**Issue by EthanDRaymond** [react-bootstrap/react-bootstrap#4962]
## Describe the bug

Links in the documentation to the source of sub-components lead to a 404 error.

## To Reproduce

1. Go to https://react-bootstrap.github.io/components/forms/
2. Scroll down to **Form.Row**
3. Click the 'View Source File' link icon to the right of the header.
4. See 404 error.

## Reproducible Example

https://react-bootstrap.github.io/components/forms/#form-row-props

## Expected behavior

The original source code should be properly linked to.

## Environment (please complete the following information)

- Operating System: Windows 10
- Browser, Version: Chrome 79
- React-Bootstrap Version 1.0.0-beta.16

**Comment by taion** [comment]
I'm not sure what you mean. Clicking on the "#" link works fine for me. https://react-bootstrap.github.io/components/forms/#form-row-props works fine for me too.

**Comment by EthanDRaymond** [comment]
@taion I wan't clear about which link I meant. I updated my description.

**Comment by taion** [comment]
gotcha, fixing in https://github.com/react-bootstrap/react-bootstrap/pull/4969
