### ISSUE TITLE
Does the Dropdown.Toggle id property need to be globally unique?

### ISSUE THREAD

**Issue by BenMorel** [react-bootstrap/react-bootstrap#4971]
First of all I apologize for the support request, but the docs are unclear to me.

The [Dropdown.Toggle](https://react-bootstrap.github.io/components/dropdowns/#dropdown-toggle-props) docs mention that the `id` property is required:

> `id` `required` `string|number` An html id attribute, necessary for assistive technologies, such as screen readers.

What the doc doesn't say is, **does the `id` property need to be globally unique?**

As far as I can tell, only one dropdown instance can appear on the page at any given time. So I would expect that reusing the same id over multiple instances of a component is OK. But I may be mistaken.

Thanks in advance for any clarification!

**Comment by taion** [comment]
This just gets passed through to https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/id. The `id`, however, gets passed to the toggle component itself, and you can have more than one dropdown toggle on the screen at a time, though it would be unusual to have multiple open dropdowns. However, that does mean that you'd want each rendered dropdown toggle to have a different `id`.

**Comment by BenMorel** [comment]
Thank you for the clarification. The fact that it's required has cascading consequences, forcing every instance of Dropdown to have a context from which we can build an id.

> An html id attribute, **necessary for assistive technologies**, such as screen readers.

Is this a requirement that Bootstrap itself enforces?

**Comment by taion** [comment]
no; as noted, it's required for pages to satisfy a11y best practices. things will "work" (but not be accessible) even if you don't specify an `id` at all.

**Comment by BenMorel** [comment]
Thank you. But then why does react-bootstrap enforce the `id`?

**Comment by taion** [comment]
it's not strictly "enforced". we log a dev error if it's not present, but it's not otherwise enforced.
