### ISSUE TITLE
Personalize close Modal in ModalHeader

### ISSUE THREAD

**Issue by kamivrpg** [react-bootstrap/react-bootstrap#4973]
Hi!

I was asking in Discord because i couldn't find the "x" that appears to close the modal element. It appears in DOM but i couldn't find it in the project or the API:
![image](https://user-images.githubusercontent.com/47991397/73978943-edf89c00-48f2-11ea-9ff5-eb296c1516fe.png)
but in the modal is like a prop:
![image](https://user-images.githubusercontent.com/47991397/73979017-0a94d400-48f3-11ea-9cf7-ee6601651e72.png)
I wanted to change it for a font-awesome icon, so will be great could do it anything what we like. Thank you for your attention!

**Comment by taion** [comment]
Enabling the `closeButton` prop just renders a `<CloseButton>`, per https://github.com/react-bootstrap/react-bootstrap/blob/89693c7967594d4713149a17aca0993b45373cc0/src/ModalHeader.js#L64-L66

If you need a non-default close button, then pass that as a child into `<Modal.Header>`.
