### ISSUE TITLE
<Container fluid="[breakpoint]"> not working

### ISSUE THREAD

**Issue by hardnold** [react-bootstrap/react-bootstrap#4974]
## Describe the bug

The documentation states 

> You can set breakpoints for the fluid prop. Setting it to a breakpoint (sm, md, lg, xl) will set the Container as fluid until the specified breakpoint.

see [https://react-bootstrap.netlify.com/layout/grid/#container-fluid](https://react-bootstrap.netlify.com/layout/grid/#container-fluid)

But it doesn't actually take care of the breakpoints, it just decides whether the container will be fluid or not and therfor does not stop "growing" when viewport is larger than the breakpoint

The Problem lies (probably) in the File `Container.d.ts`, where the fluid-prop is defined as boolean
```
import * as React from 'react';

import { BsPrefixComponent } from './helpers';

export interface ContainerProps {
  fluid?: boolean;
}

declare class Container<
  As extends React.ElementType = 'div'
> extends BsPrefixComponent<As, ContainerProps> {}

export default Container;
```

## To Reproduce
use for example `<Container fluid="md"></Container>` and make browser-window wider. Container will always be fluid, even if the viewport width is bigger

## Expected behavior

Container will be fluid until the breakpoint-size and then stays this size if viewport is larger than the breakpoint.

## Environment (please complete the following information)

- Operating System: macOS
- Browser, Version Chrome 79.0.3945.130 (Official Build) (64-bit)
- React-Bootstrap Version 1.0.0-beta.16

**Comment by taion** [comment]
this isn't released yet in beta.16
