### ISSUE TITLE
ProgressBar - apply transition effect only when increasing progress

### ISSUE THREAD

**Issue by seladb** [react-bootstrap/react-bootstrap#4981]
As per my understanding, in the current implementation transition works both when increasing and decreasing the progress. I have a use-case where I slowly increase the progress from 0 to 100, and then I reset the progress back to 0 and increase it slowly again. When resetting from 100 to 0 the progress transitions backwards which is very confusing for my users.

The desired behavior is: transition when (gradually) increasing from 0 to 100, but don't transition when resetting from 100 to 0.

Is this possible with the current implementation?

**Comment by charlieman** [comment]
Here's a trick I use, add this to your css:
```
.progress-bar[aria-valuenow="0"] {
    transition: none;
}
```
When the `now` value changes to 0 the transition is set to none and it immediately disappears. Only works with zero though, if you go from 80 to 30 you still see the transition.

**Comment by taion** [comment]
This isn't really a matter of the JS we offer here, anyway. The animation is implemented with the upstream Bootstrap CSS.

**Comment by seladb** [comment]
Thanks @charlieman that does the trick!

@taion maybe it'd be nice to add this as a prop for the `ProgressBar` component, please let me know what you think
