### ISSUE TITLE
importing react-bootstrap components with typescript for nodejs doesn't work

### ISSUE THREAD

**Issue by flyon** [react-bootstrap/react-bootstrap#4984]
## Describe the bug

According to the documentation we should use

    import Form from "react-bootstrap/Form";

However this gets transformed by typescript to 

    const Form_1 = require("react-bootstrap/Form");

This causes problems when I try to access Form.Group or Form.Label: 

    <Form><Form.Group></Form.Group></Form>

Which compiles to 

     React.createElement(Form_1.default,{},React.createElement(Form_1.default.Group));

This raises an error because `Form_1.default.Group` is undefined.
Group, Label and others have only been exported on the top level, not as properties of the default export.

`Form_.Group` would be defined, but that means I need to import differently.

If I change my import to 

    import * as Form from "react-bootstrap/Form";

to try and get around this, typescript complains  ` Property 'Group' does not exist on type 'typeof import("
C:/[...]/node_modules/react-bootstrap/Form")'.`

**Comment by kosmiq** [comment]
Could give some more info about your setup? I do not seem to face this issue in one of my projects.

A quick test on codesandbox seems to work as well: https://codesandbox.io/s/silent-dream-k8sgp

**Comment by jquense** [comment]
> Group, Label and others have only been exported on the top level, not as properties of the default export.

That isn't true tho? https://github.com/react-bootstrap/react-bootstrap/blob/master/src/Form.js#L79-L87

**Comment by flyon** [comment]
@kosmiq the problem arises when running the compiled code **on nodejs**.

I've made an example setup. I'm not sure where to create a sandbox for nodejs, but its very simple: 

index.tsx 
```
import * as React from "React";
import Form from "react-bootstrap/Form";
var x = <Form><Form.Check></Form.Check></Form>;
export default x;
```

tsconfig.json
```
{
  "compilerOptions": {
    "module": "commonjs",
    "target": "es6",
    "declaration": true,
    "jsx": "react",
    "baseUrl": "./"
  }
}
```
package.json
```
{
  "name": "test",
  "dependencies": {
    "react": "^16.12.0",
    "react-dom": "^16.12.0",
    "react-bootstrap": "^1.0.0-beta.16"
  }
}
```

run:
npm install
tsc
node index.js

output:
`TypeError: Cannot read property 'Check' of undefined    at Object.<anonymous> (C:\...\index.js:5:40)`

Compiled index.js output looks like this:
```
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const React = require("React");
const Form_1 = require("react-bootstrap/Form");
var x = React.createElement(Form_1.default, null,
    React.createElement(Form_1.default.Check, null));
exports.default = x;
```

**Comment by jquense** [comment]
I'm not sure what to say here, the compiled code you've got here is correct, and the compiled bootstrap code matches it: https://unpkg.com/browse/react-bootstrap@1.0.0-beta.17/cjs/Form.js 

any chance you can put together little repository we can try out demonstrating this?

**Comment by kosmiq** [comment]
No feedback for more than 7 days. Closing.
