### ISSUE TITLE
Why is className for <Tab> named tabClassName?

### ISSUE THREAD

**Issue by kosmiq** [react-bootstrap/react-bootstrap#4986]
## Describe the bug

Not sure if it really is a bug. But here goes.
I recently used the the tab functionality and had a need of adding a custom class to a tab. Happily confident that I could use className I set a custom class using that like so:
`<Tab className="class"></Tab>`

But that did not work. So I looked at the code and discovered that tabs uses tabClassName instead of the regular className.

Is there a reason for this? I'd happily create a PR that changes this to className instead to better mimic other components.

## To Reproduce

1. Use <Tab> and place it somewhere
2. Attempt setting custom class for it using className
3. Discover that it does not work
4. Use tabClassName instead
5. Success!

## Expected behavior

Usage of className should add custom classes as most other components do.

**Comment by jquense** [comment]
It's sort of a weird reason. `Tab` isn't a normal component, it abstractly represents both the nav item "tab" and the content of that tab. In other words, `<Tab>` when used, results in _two_ components being rendered, the `NavItem` in the tab list and the `TabPane`. `className` goes to the `TabPane`, and `tabClassName` goes to the NavItem. It's a little weird, and maybe should have been inverted but not sure it's worth breaking at this point

**Comment by kosmiq** [comment]
Ah, thanks for clarifying that. All is good then. :)
