### ISSUE TITLE
Tooltip misplaced on radio input and checkbox

### ISSUE THREAD

**Issue by tw0517tw** [react-bootstrap/react-bootstrap#499]
![radio](https://cloud.githubusercontent.com/assets/1003146/7067363/486cc568-defd-11e4-934c-577e8dc95d44.png)
```
<OverlayTrigger placement='bottom' overlay={<Tooltip><strong>Holy guacamole!</strong> Check this info.</Tooltip>}>
  <Input type="radio" label="from database" />
</Overlay>
```
This one happens when mouse over an radio button. 
I think the tooltip should be placed exactly on the button, not center of the whole input element include label.
Also the tooltip won't show if mouse over the label, I'm not sure if it should show or not.

---

![check](https://cloud.githubusercontent.com/assets/1003146/7067367/4ac6aebe-defd-11e4-8798-91a698b6b2a5.png)
```
<td>
  <OverlayTrigger placement='bottom' overlay={<Tooltip><strong>Holy guacamole!</strong> Check this info.</Tooltip>}>
    <Input type="checkbox" />
  </OverlayTrigger>
</td>
```
This one happens when mouse over an checkbox without label in a table.
The tooltip is misplaced at the center of table cell. Y-axis positioning is also wrong.

**Comment by tw0517tw** [comment]
After taking a look at the source code. I think it's because `OverlayTrigger.calcOverlayPosition()` calculates the height and width from the child node. But a `<Input>` component will produce multiple layers of DOM nodes. So `OverlayTrigger.calcOverlayPosition()` should go deeper into grand-child for height and width offset.

**Comment by frontsideair** [comment]
This affects me too. I'm using a text input as the target to an Overlay element, which is incorrectly placed. I suspect that the origin of the bug is `react-overlays` project.

**Comment by taion** [comment]
We'll be revamping the `<Input>` component eventually – this is just a limitation of the current `Input` API, best recommendation is to use a `standalone` `<Input>` for now and build the form group yourself.
