### ISSUE TITLE
Toast uses opacity 0 instead of display none

### ISSUE THREAD

**Issue by ccornici** [react-bootstrap/react-bootstrap#4991]
## Describe the bug

The React Bootstrap Toast is rendered on the page as hidden, whereas the Actual Bootstrap Toast has display none. This is not only not conforming with the actual bootstrap implementation (of actually having display none when a toast is not displayed, by using the "hide" class on the toast root), but is also very annoying and breaking layouts.

## To Reproduce

1. Go to https://getbootstrap.com/docs/4.4/components/toasts/
2. Inspect a toast html. Then click X to hide the toast.
3. Observe how the toast has the class "hide" now which has display none
4. Do the same on React Bootstrap. Observe the discrepancy.

## Reproducible Example

It's clearly explained above how to reproduce this with those examples

## Expected behavior

Conform to the real bootstrap behavior

## Environment (please complete the following information)

- Operating System: Win 10
- Chrome Version 79.0.3945.130 (Official Build) (64-bit)
- React-Bootstrap Version 1-beta.16

**Comment by taion** [comment]
We'd be happy to take a PR here.

**Comment by Rishika07** [comment]
Hey, Can I take this up?

**Comment by jquense** [comment]
ya go for it 👍

**Comment by VinitSarvade** [comment]
#5015

**Comment by VinitSarvade** [comment]
Hey, I've made the changes for the above issue in this PR: #5015 
Please provide me with any necessary input to improve this and get this successfully merged.

**Comment by VinitSarvade** [comment]
@taion @bpas247: As per the discussions on #5015 , I've raised #5123 with the discussed changes.

**Comment by kyletsang** [comment]
Confirmed on Chrome with RB 1.0.1 that display none is now used instead of opacity
