### ISSUE TITLE
Can't open a new popup window

### ISSUE THREAD

**Issue by kennysmith12** [react-bootstrap/react-bootstrap#4993]
## Describe the bug

Problem opening a new modal

## To Reproduce

I copied the code to open a new popup window from here:
https://react-bootstrap.netlify.com/components/modal/
And when I press the button, it is not opening a new window

## Reproducible Example
1.Create react project
2. copy this code:
```
import React from 'react';
import './App.css';
import {Modal, Button} from 'react-bootstrap'

function MyVerticallyCenteredModal(props) {
  return (
    <Modal
      {...props}
      size="lg"
      aria-labelledby="contained-modal-title-vcenter"
      centered
    >
      <Modal.Header closeButton>
        <Modal.Title id="contained-modal-title-vcenter">
          Modal heading
        </Modal.Title>
      </Modal.Header>
      <Modal.Body>
        <h4>Centered Modal</h4>
        <p>
          Cras mattis consectetur purus sit amet fermentum. Cras justo odio,
          dapibus ac facilisis in, egestas eget quam. Morbi leo risus, porta ac
          consectetur ac, vestibulum at eros.
        </p>
      </Modal.Body>
      <Modal.Footer>
        <Button onClick={props.onHide}>Close</Button>
      </Modal.Footer>
    </Modal>
  );
}

function App() {
  const [modalShow, setModalShow] = React.useState(false);

  return (
    <>
      <Button variant="primary" onClick={() => setModalShow(true)}>
        Launch vertically centered modal
      </Button>

      <MyVerticallyCenteredModal
        show={modalShow}
        onHide={() => setModalShow(false)}
      />
    </>
  );
}

export default App;
```

3. run the program and press the button

## Expected behavior

I expect a new popup window to open

## Screenshots
![image](https://user-images.githubusercontent.com/61227472/74818348-2b075a00-5307-11ea-818f-dec621bb71e2.png)

![image](https://user-images.githubusercontent.com/61227472/74818447-59853500-5307-11ea-8e3a-5afa436085cf.png)

## Environment (please complete the following information)

- Operating System: windows 10
- Browser, Version:  80.0.3987.116
- React-Bootstrap Version :1.0.0-beta.16

**Comment by jquense** [comment]
You also need to include the bootstrap css
