### ISSUE TITLE
Apply dropdown-menu-right class to NavDropdown component.

### ISSUE THREAD

**Issue by bgeels** [react-bootstrap/react-bootstrap#4994]
I am trying to have a `NavDropdown` apply the `dropdown-menu-right` class to the `div.dropdown-menu` element created within the component.

I would have expected this to work but it doesn't.

```
<Nav className="mr-sm-2 dropdown-menu-right">
  <NavDropdown className="dropdown-menu-right" title={<span><i className="fa fa-bars"></i></span>}>
    <NavDropdown.Item href="/example-app/section-a/">Section A</NavDropdown.Item>
    <NavDropdown.Divider />
    <NavDropdown.Item href="/logout">Logout</NavDropdown.Item>
  </NavDropdown>
</Nav>
```

Could be I'm just not applying it correctly, if not could support for this be added? 

Thanks!

**What's happening.**
![reality](https://user-images.githubusercontent.com/4997487/74873512-569d3b00-532d-11ea-9c4b-3adca37ab7d4.png)

**What I'd like to happen.**
![desired](https://user-images.githubusercontent.com/4997487/74873526-5c931c00-532d-11ea-8ce1-34b4c5117314.png)

**Comment by jquense** [comment]
you wouldn't apply the class yourself, add the 'alignRight' class instead

**Comment by bgeels** [comment]
You're quick and correct, thanks!

**Working .jsx:**
```
<Nav className="mr-sm-2">
  <NavDropdown alignRight title={<span><i className="fa fa-bars"></i></span>}>
    <NavDropdown.Item href="/example-app/section-a/">Section A</NavDropdown.Item>
    <NavDropdown.Divider />
    <NavDropdown.Item href="/logout">Logout</NavDropdown.Item>
  </NavDropdown>
</Nav>
```

**Comment by buddhiv** [comment]
> you wouldn't apply the class yourself, add the 'alignRight' prop instead

Thanks, ,this works.!!

**Comment by dermanator** [comment]
> Seems that 'alignRight' is not working in .tsx. :(

I used `align="end"` in .tsx files and it works for me.
