### ISSUE TITLE
  Warning: `NaN` is an invalid value for the `left` css style property.

### ISSUE THREAD

**Issue by FullStackForger** [react-bootstrap/react-bootstrap#4997]
## Describe the bug

Unexpected warning error.

## Reproducible Example

Here is a TS example of self contained test that can reproduce the issue.

```
describe('Testing tooltip', () => {
  it('triggers tooltip hint', async () => {
    const { Tooltip, OverlayTrigger } = bootstrap
    const TestComponent = ({ text, hint }: { text: string; hint: string }) => {
      const overlay = <Tooltip id="test-id">{hint}</Tooltip>

      return (
        <OverlayTrigger placement="bottom" overlay={overlay}>
          <div>{text}</div>
        </OverlayTrigger>
      )
    }
    const text = 'test text'
    const hint = 'test hint'
    const { getByText, queryByText, container } = render(<TestComponent text={text} hint={hint} />)
    expect(getByText(text)).toBeInTheDocument()
    expect(queryByText(hint)).not.toBeInTheDocument()

    fireEvent.mouseOver(container.firstChild as Element)

    await wait(() => {
      expect(getByText(hint)).toBeInTheDocument()
      console.log(getByText(hint).outerHTML)
    })
  })
```

Test passes ok but generates following error.

```
    Warning: `NaN` is an invalid value for the `left` css style property.
        in div (created by Tooltip)
        in div (created by Tooltip)
        in Tooltip (created by Overlay)
        in Transition (created by Fade)
        in Fade (created by Overlay)
        in Overlay (created by Overlay)
        in Overlay (created by OverlayTrigger)
        in OverlayTrigger (created by TestComponent)
        in TestComponent
```
_CodeSandbox_ not applicable

## Expected behaviour

No error or warning should occur.

## Environment (please complete the following information)

- Operating System: [e.g. macOS]
- React-Bootstrap Version: 1.0.0-beta.16
- Test tooling: jest with react testing library

**Comment by taion** [comment]
Can you check if it's the same thing as in https://github.com/react-bootstrap/dom-helpers/pull/22? If so, can you follow up there?

**Comment by FullStackForger** [comment]
@taion Jimmy not sure what exactly are we after in that linked PR? It has been closed long time ago.

**Comment by taion** [comment]
Well, is the `NaN` coming from a jsdom bug? Seems like it's the same problem.

**Comment by FullStackForger** [comment]
I have done a bit of digging and it seems that the issue is caused by popper.js. 
Their `getPopperOffsets()` function called from the `update()` returns invalid styling, eg: 
```
{ width: 0,
      height: 0,
      left: NaN,
      top: NaN,
      position: 'absolute',
      right: NaN,
      bottom: NaN }
```

Haven't worked out if it is jsdom related yet.

**Comment by FullStackForger** [comment]
Can't see why it breaks exactly but went through error stack trace and it would make sense to add simple validation to
https://github.com/react-bootstrap/react-overlays/blob/master/src/usePopper.js#L109

Perhaps destruct only valid props and throw away everything else, eg: `{ left: NaN, top: '' }` or `{ left: NaN, top: NaN}`. Hardcoded it locally to test it but happy to create PR if proposed solution seems reasonable.

**Comment by FullStackForger** [comment]
Actually mocking popper solves the problem.
I have created `stc/__mock__/popper.js.js` file with following code:
```
import PopperJs from 'popper.js'

export default class Popper {
  static placements = PopperJs.placements

  constructor() {
    return {
      destroy: () => {},
      scheduleUpdate: () => {}
    }
  }
}
```

Just for the reference, here is [link](https://github.com/popperjs/popper-core/issues/478#issuecomment-341494703) to a popper issue.

**Comment by taion** [comment]
Okay; is this issue resolved, then?

**Comment by jonahparampara** [comment]
I am also encountering this bug.

**Comment by mhavelka** [comment]
If this is possible to fix, it would be great.

**Comment by kosmiq** [comment]
So this issue is caused by popper when running jest as a test suite, neither of which are in our control. Am I getting this right? :) @taion should we close this?

It might be resolved anyway whenever poppers 2 is merged?

**Comment by FullStackForger** [comment]
@kosmiq  yes you are correct. There is no need to patch it right now. Simple mock I posted is easy enough to deal with this. Hopefully with next popper version we wont have that problem.

**Comment by Dror-Bar** [comment]
I'm not running jest and I'm getting this error from Popover (from react-bootstrap).
I don't understand why a component from your library is "out of your control"?
Did anyone figure out how to fix this issue?

**Comment by adhirchakravarti** [comment]
same here, I get the warning in the browser console (not in jest)

` 'NaN' is an invalid value for the 'top' css style property`


```
Warning: 'NaN' is an invalid value for the 'top' css style property.
    in div (created by ForwardRef)
    in div (created by ForwardRef)
    in ForwardRef (created by PopoverMenu)
    in PopoverMenu (created by Overlay)
    in Transition (created by Fade)
    in Fade (created by Overlay)
    in Overlay (created by Overlay)
    in Overlay (created by OverlayTrigger)
    in OverlayTrigger (created by IconButton)
    in IconButton (created by ReportListItem)
    in div (created by ReportListItem)
    in div (created by ReportListItem)
    in div (created by ReportListItem)
    in div (created by ReportListItem)
    in ReportListItem (created by ReportList)
    in div (created by ReportList)
    in ReportList (created by ReportLandingPage)
    in div (created by ReportLandingPage)
    in div (created by ReportLandingPage)
    in div (created by ReportLandingPage)
    in ReportLandingPage (created by ReportComponent)
    in ReportComponent
    in Provider
```

**Comment by kyletsang** [comment]
For those that are seeing this issue in the browser, please post a full reproducible example.
