### ISSUE TITLE
Basic toast without onClose callback causes type error

### ISSUE THREAD

**Issue by AparnaPrasad** [react-bootstrap/react-bootstrap#4998]
## To Reproduce

1. Go to official [page](https://react-bootstrap.github.io/components/toasts/)
2. Under Basic Click on 'X' in the header
3. Open console
4. Displays a type error

## Reproducible Example

Minimal example by using [CodeSandbox](https://codesandbox.io/s/github/react-bootstrap/code-sandbox-examples/tree/master/basic).
https://codesandbox.io/s/suspicious-margulis-teyxk
## Expected behavior

Should not display type error
## Environment (please complete the following information)

- Operating System: (64-bit), OS: Windows 10 Pro v1903
- Browser Version: Chrome Browser:79.0.3945.88
- React-Bootstrap Version Bootstrap 4.3

## Additional context
It requires an additional check at [line](https://github.com/react-bootstrap/react-bootstrap/blob/eca5373d7d3beaec6abe2a2d380f6d216cad5beb/src/ToastHeader.js#L41)
Would be happy to submit PR :)

**Comment by taion** [comment]
Toasts are always closable, no? What _should_ happen if the user clicks on the "X"? If it's "nothing", then it seems like passing in a no-op callback would be most appropriate?

Is the issue that we haven't marked the prop required?

**Comment by alekpentchev** [comment]
@taion It might be the case. The example provided by @AparnaPrasad shows that ```onClose``` callback is optional. The same for ```show``` attribite. So whenever one is missing there is a problem. Deleting ```onClose``` causes this TypeError because probably the Toaster doesn't know how to behave.

So the question is - should it be required? Or maybe it can stay as optional but then it should close by itself with a default behavior whenever clicked? And ```onClose``` could stay then as a way of customization.

**Comment by AparnaPrasad** [comment]
I agree with @alekpentchev to make onClose handler optional and handling default behavior by itself.  If close button is visible  then it it is expected to close, but we can accept an optional callback to allow customization. I don't think having the close button, without closing is a behavior expected/required. If its not intended to be closed, close button it can be hidden with optional prop closeButton=false.

**Comment by AparnaPrasad** [comment]
So as I see it there are 3 possible ways to fix this error:
1. Handle closing within the component and allow optional callback
2. Make onClose call back required when closeButton props is set to true
3. Add an additional condition at this [line](https://github.com/react-bootstrap/react-bootstrap/blob/eca5373d7d3beaec6abe2a2d380f6d216cad5beb/src/ToastHeader.js#L41), so that if there is a callback its called if not it doesn't error.

**Comment by taion** [comment]
`<Modal>` and `<Alert>` both require the close handler to be defined when rendering a "close" button. We should thus do the same here.

**Comment by AparnaPrasad** [comment]
In the Modal example in the react-bootstrap offical [page ](https://react-bootstrap.github.io/components/modal/) also in this [codepen ](https://codepen.io/apbscodepenio/pen/xxGRNzJ), as you see here that there is no type error caused if I miss out onClose, after debugging a bit, I found the issue is in passing the context prop to the component, as you can see in the screenshot I am attaching; in case of modal, even if I dont pass the onClose method, the onHide function is not undefined, but it is in Toast. 
![modal context inspector](https://user-images.githubusercontent.com/1925970/75121013-6f408480-5690-11ea-8a0a-06540891a726.PNG)
![toast context inspector](https://user-images.githubusercontent.com/1925970/75121014-749dcf00-5690-11ea-8bfa-c65727e5ec18.PNG)
![modal debugger](https://user-images.githubusercontent.com/1925970/75121017-79fb1980-5690-11ea-8d01-f35900727e79.PNG)
![toast debugger](https://user-images.githubusercontent.com/1925970/75121022-88493580-5690-11ea-96e7-507aabe7d150.PNG)

**Comment by taion** [comment]
That's odd. We _should_ require it, no? It shouldn't be possible to just have a broken "close" button...

**Comment by AparnaPrasad** [comment]
Also, what I don't understand is, when is Modal getting its onHide function from even if I don't explicitly pass the callback function

**Comment by VinitSarvade** [comment]
> `<Modal>` and `<Alert>` both require the close handler to be defined when rendering a "close" button. We should thus do the same here.

The `onClose` callback only signals intent from the Toast, one must actually set the `show` prop to `false` for the Toast to close. Having the `onClose` should not be made mandatory is what I feel.

**Comment by kyletsang** [comment]
Handled in #5123
