### ISSUE TITLE
how about Image Component Name replace to  "Img" ?

### ISSUE THREAD

**Issue by digo09** [react-bootstrap/react-bootstrap#5000]
Hi, Sorry, I am not good at English. 

React-bootstrap Component Image is Web API Image Same Name 
When using both together "Type Error" occur

Web API Image
https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/Image

Error Example
https://codesandbox.io/s/confident-framework-q5xj1

**Comment by taion** [comment]
Well, you can import it with whatever name you want. I guess we could consider renaming it, though? I don't feel strongly.

**Comment by mxschmitt** [comment]
@digo09 for example: https://codesandbox.io/s/quizzical-herschel-7fweg

But I think this is not in the ReactBootstrap scope to provide a other naming for that element.

**Comment by kosmiq** [comment]
I think that we should not rename it. As stated by @taion it is simple to import with another name.
Have we reached consensus on that and can close this?

**Comment by mxschmitt** [comment]
Closed because workaround is pretty straightforward.
