### ISSUE TITLE
Get Tab Container activeKey

### ISSUE THREAD

**Issue by gamalielwkr** [react-bootstrap/react-bootstrap#5001]
Hi, I have implemented a custom Tab Layout using Tab Container.
In some cases, I want to check which Tab is active.
Last time I am using `1.0.0-beta.3` version to get the `activeKey` by `ref` to access Tab Container `props`. 
Below is the code:

```
<Tab.Container id="left-tabs-example" defaultActiveKey="first" ref={exampleRef => this.exampleRef = exampleRef}>
  <Row>
    <Col sm={3}>
      <Nav variant="pills" className="flex-column">
        <Nav.Item>
          <Nav.Link eventKey="first">Tab 1</Nav.Link>
        </Nav.Item>
        <Nav.Item>
          <Nav.Link eventKey="second">Tab 2</Nav.Link>
        </Nav.Item>
      </Nav>
    </Col>
    <Col sm={9}>
      <Tab.Content>
        <Tab.Pane eventKey="first">
          <Sonnet />
        </Tab.Pane>
        <Tab.Pane eventKey="second">
          <Sonnet />
        </Tab.Pane>
      </Tab.Content>
    </Col>
  </Row>
</Tab.Container>
```

But when I upgrade the version to `1.0.0-beta.16`, the `ref` contains `undefined` and it says `Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?`

Could anybody solve this issue?
Thank you.

**Comment by taion** [comment]
Manage the `activeKey` state yourself and pass it down to `<Tab.Container>` as the `activeKey` prop.
