### ISSUE TITLE
 Replace the Dropdown Title with cliked child element

### ISSUE THREAD

**Issue by rubimbura** [react-bootstrap/react-bootstrap#5002]
When a child element is clicked I am expecting to replace the Title, so that I see the selected child,
but with This Dropdown a title doesn't change regardless the clicked item.need some help please.

ex: <Dropdown>
         <Dropdown.Toggle>title </Dropdown.Toggle>
         <Dropdown.Menu>
              <Dropdown.Item>one </Dropdown.Item>
              <Dropdown.Item>two </Dropdown.Item>
              <Dropdown.Item>three </Dropdown.Item>
         </Dropdown.Menu>
         </Dropdown>

**Comment by mxschmitt** [comment]
Please provide us a full example on CodeSandbox what you are trying to accomplish. 
https://codesandbox.io/s/github/react-bootstrap/code-sandbox-examples/tree/master/basic

**Comment by rubimbura** [comment]
@mxschmitt Thank you for responding..
What I want to accomplish is the same way select element uses drop-drown but I want to use react-bootstrap in my project.
ex:


<select>
    <option>one</option>
    <option>two</option>
   <option>three</option>
</select>

Here by default the page will display text one, and when a drop-drown is toggled and option two is clicked  text two will replace text one in the display.With react-bootstrap dropdown it doesn't change!

Is there any way I can use

**Comment by taion** [comment]
You can control the `<Dropdown>`'s open state and use the same state property to control the text on the toggle.
