### ISSUE TITLE
Carousel onSlideEnd gets called more than once.

### ISSUE THREAD

**Issue by sirricode** [react-bootstrap/react-bootstrap#5003]
## Describe the bug

I'm trying to use onSlideEnd event of Carousel component but everytime Slide changes callback gets called more and more.

## To Reproduce

1. Create a Carousel
2. Click on previous or next button

## Reproducible Example

Minimal example by using [CodeSandbox](https://codesandbox.io/s/upbeat-mendel-fd97f?fontsize=14&hidenavigation=1&theme=dark).

## Expected behavior

Expected to called once per slide change like onSelect event.

## Screenshots

![image](https://user-images.githubusercontent.com/23503367/75064386-e7277700-54f7-11ea-9b09-cc11c789f18f.png)

![image](https://user-images.githubusercontent.com/23503367/75064216-8730d080-54f7-11ea-852b-6dede32a0d6a.png)

## Environment (please complete the following information)

- Operating System: Windows 7 Ultimate
- Browser, Version: Chrome, 80.0.3987.116
- React-Bootstrap Version 1.0.0-beta.16

**Comment by taion** [comment]
There's a chance this will get fixed by https://github.com/react-bootstrap/react-bootstrap/pull/4917

**Comment by kyletsang** [comment]
Just tried this out and it looks like it's fixed. This can be closed.

**Comment by taion** [comment]
Thanks!
