### ISSUE TITLE
Allow `SplitButton` primary button `type` to be set

### ISSUE THREAD

**Issue by WillJW** [react-bootstrap/react-bootstrap#5008]
## Is your feature request related to a problem? Please describe

Adding a SplitButton as the main submit button on a form, I noticed hitting 'enter' in the form wouldn't submit it. This is because the primary SplitButton button is `type="button"`.

## Describe the solution you'd like

I would like to be able to set the primary button's type.

Example:

```jsx
<SplitButton title="Save" variant="primary" type="submit">
  <Dropdown.Item onClick={this.doSomething}>
    Delete
  </Dropdown.Item>
</SplitButton>
```

**Comment by mxschmitt** [comment]
Closed because it was implemented in #5009
