### ISSUE TITLE
OverlayTrigger forward context

### ISSUE THREAD

**Issue by shablenko-sednor** [react-bootstrap/react-bootstrap#5016]
## Describe the bug
I`m trying to display localized content inside tooltip using react-intl
It depends on some context and throws errors

code is simple, nothing special

```
<OverlayTrigger
                    trigger={["hover", "focus"]}
                    placement="bottom"
                    overlay={
                        <Tooltip id="popover-trigger-focus">
                            <FormattedMessage id="User.Activity.Locked.Items.Tooltip" />
                        </Tooltip>
                    }
                >
                    <Img src={lockIcon} height="25px" alt="" className="lock-icon-top" />
                </OverlayTrigger>
```

![Selection_999(021)](https://user-images.githubusercontent.com/37369710/75546968-7ec62180-5a32-11ea-8b0e-51a8d7823274.png)

## To Reproduce

please see code fragment from above

## Expected behavior

context is forwarded to tooltips children

## Environment (please complete the following information)

- Operating System: any
- Browser, Version any
- React-Bootstrap Version 0.33.1

## Additional context

I saw this issue https://github.com/react-bootstrap/react-bootstrap/issues/465 but I don`t get whether it was fixed or not and how to use that fix

**Comment by taion** [comment]
This should not be an issue on any reasonably recent version of React. What version of React are you on?

**Comment by shablenko-sednor** [comment]
@taion 16.13.0

**Comment by ville-cap** [comment]
Looks like when using the OverlayTrigger the actual Overlay component is created outside the main React component tree and so outside all Context.Providers. I don't see how this could work.

**Comment by kosmiq** [comment]
Does it work if you wrap the FormattedMessage in the tooltip with the IntlProvider component?

```
<OverlayTrigger
	trigger={["hover", "focus"]}
	placement="bottom"
	overlay={
		<Tooltip id="popover-trigger-focus">
			<IntlProvider [...]>
				<FormattedMessage id="User.Activity.Locked.Items.Tooltip" />
			</IntlProvider>
		</Tooltip>
	} >
	<Img src={lockIcon} height="25px" alt="" className="lock-icon-top" />
</OverlayTrigger>
```

**Comment by taion** [comment]
That doesn't seem totally right to me.

Overlays render in portals, so they're not in the component tree, but they're still in the _React_ tree.

Is it possible you somehow have multiple versions of React or React DOM installed?

**Comment by ville-cap** [comment]
> Overlays render in portals, so they're not in the component tree, but they're still in the React tree.

You mean DOM vs React tree? Here's how it shows up in Chrome's dev tools:

![Screenshot 2020-03-13 at 18 03 50](https://user-images.githubusercontent.com/49948297/76639057-26c10c00-6556-11ea-96ca-fc74dfed294f.png)

> Is it possible you somehow have multiple versions of React or React DOM installed?

Re-installed all node modules and searched through the package-lock and did not find multiple versions of either.

**Comment by shablenko-sednor** [comment]
No it does not work, sometimes I have component which are connected to redux stores inside tooltips, I cannot just set another store provider for each tooltip, that won`t work I`ll have multiple store instances which are not connected to each other

**Comment by kosmiq** [comment]
Can you setup something at https://codesandbox.io/ or similar that reproduces the issue? I'm using react-i18next in a project and have no issues using OverlayTriggers :(

**Comment by kosmiq** [comment]
Still not sure what happens here @shablenko-sednor. This is how it looks for me using OverlayTrigger in a real app using react-bootstrap, react, react-dom, redux and more. We're using react-i18next though.

![overlaytrigger](https://user-images.githubusercontent.com/322759/78107311-85f79b00-73f5-11ea-95de-32f879d6eb8f.png)

**Comment by it11ah1** [comment]
I can confirm the problem. It occurs in versions prior to 1.0.0-beta.0. Maybe solved with https://github.com/react-bootstrap/react-bootstrap/pull/3215 ?
Unfortunately I have to keep a Bootstrap v3 compatible version...

**Comment by vhuerta** [comment]
This is happening for me as well, version 0.33.1, is rendering the Overlay at root level and for that reason I'm getting:

```Error: could not find react-redux context value; please ensure the component is wrapped in a <Provider>```

trying to pull a value from redux, my code:

```javascript
<OverlayTrigger
        trigger="click"
        rootClose
        placement="bottom"
        overlay={this._popover()}
        onEnter={this.handleTriggerEnter}
      >
{content}
</OverlayTrigger>
```

devtools:

<img width="734" alt="Screen Shot 2020-10-29 at 18 01 14" src="https://user-images.githubusercontent.com/4644230/97644864-096f7e00-1a11-11eb-88c5-e91d0095213a.png">

**Comment by kyletsang** [comment]
Sounds like a bs3 issue and this is no longer supported.  This should work in later versions
