### ISSUE TITLE
This project has been added to the react-ui-roundup

### ISSUE THREAD

**Issue by dimitropoulos** [react-bootstrap/react-bootstrap#5018]
Hi!

I am making this issue just to let you know that I've included your amazing project in the [react-ui-roundup](https://github.com/dimitropoulos/react-ui-roundup).

For more information see https://github.com/dimitropoulos/react-ui-roundup/issues/2.

Please feel free to close this issue at will - I just wanted to let you know :smile:.

Thanks!

**Comment by jquense** [comment]
Thanks, tho you data seems incomplete or wrong in a few places. React bootstraps css is just normal bootstrap, you should judge it by those resources as well. E.g. bootstrap has an interactive theme builder. 

Also the checkbox icon is customizable, via sass

**Comment by dimitropoulos** [comment]
Thank you for taking a look.  My main concern is misrepresenting your project, for sure.

For a themer (where https://themer.orbit.kiwi/ is a great example), I need a link to one.  Would you mind showing me one you recommend? I don't have a lot of experience with bootstrap, as it turns out, so I'm not sure what you would otherwise recommend.

Re: checkbox icon, thanks for the clarification.  I updated the criteria https://github.com/dimitropoulos/react-ui-roundup/commit/7bbe4b5c3e82bf8a929fed0687edee84049fdac5#diff-663bd1ad6ab29dfad85215534c48a525L87-R144.  I have to admit this feels slightly unfair, but on the other hand if the criteria is opened up to include "you can change it with CSS", then the category loses meaning because you can update pretty much all of them with CSS.  The idea was that there's a built-in way to customize the icon e.g.:
```tsx
<Checkbox icon={<FavoriteBorder />} checkedIcon={<Favorite />} value="checkedH" />
```
from material-ui.
