### ISSUE TITLE
DropdownItem preventDefault or stopPropagation does not stop the Dropdown from closing

### ISSUE THREAD

**Issue by maxcww** [react-bootstrap/react-bootstrap#5019]
Hello, I am pretty new with react and react-bootstrap and am trying to use a Dropdown with DropdownItems or a DropdownButton with DropdownItems where if one clicks on an item inside, the drop down doesn't close itself. I have tried to place almost everywhere a onClick={(e) => e.preventDefault()} or with stopPropagation but to no avail. Is there someone who can help?

At the moment my code looks like this:
```
<Dropdown alignRight>
    <Dropdown.Toggle variant="dark" id="dropdown-basic">
        {navDropDownTitle}
    </Dropdown.Toggle>
    <DropdownMenu>
        <Dropdown.Header className="text-center text-dark">
            {notifications.length} New Notifications
        </Dropdown.Header>
        {notifications.map((notification) =>
            <div key={notification.id}>
                <Dropdown.Divider className="m-1"/>
                <DropdownItem onClick={(e) => e.stopPropagation()}>
                    <Notification notification={notification} onClose={() => handleClose(notification.id)}/>
                </DropdownItem>
            </div>
        )}
    </DropdownMenu>
</Dropdown>
```

**Comment by taion** [comment]
You need to control the `show` state on the dropdown, and use the additional args to `onToggle` as described in https://react-bootstrap.github.io/components/dropdowns/#dropdown-props (esp. source) to control when to show or hide the dropdown.
