### ISSUE TITLE
Allow specifying alternative icon classes in Input and Carousel

### ISSUE THREAD

**Issue by LordSputnik** [react-bootstrap/react-bootstrap#502]
Currently, the icon classes for rendering validation icons in Input components, and for rendering previous and next icons in Carousel components are both hardcoded to use specific glyphicons. It should be possible to select which icon classes to use here, since someone might not like the default icons, or might want to switch over to font-awesome.

So, I think it would be good if it were possible to pass icon settings as properties of the Input and Carousel components, either as class strings (eg. &lt;Input iconSet="glyphicon" successIcon="ok" /&gt;), or as icon components (eg. &lt;Input successIcon=MyOKIconComponent /&gt;) (if that's possible in React).

**Comment by mtscout6** [comment]
I agree that would be nice, PRs Welcome!

**Comment by thetimbanks** [comment]
I was taking a look at making this change and found that Bootstrap has the `glyphicon-chevron-left` and `glyphicon-chevron-right` hard coded in the carousel.less file.

https://github.com/twbs/bootstrap/blob/master/less/carousel.less#L129

I tried adding the `icon-next` and `icon-prev` classes, but the content is overwritten in that file as well to a different icon. 

I scanned the project and couldn't find any examples where the default Bootsrap CSS has been modified/overwritten (which I assume shouldn't be done). Are there any suggestions on how to tackle this?

**Comment by mtscout6** [comment]
I'd imagine that we'd need to expose a means to override these: https://github.com/react-bootstrap/react-bootstrap/blob/v0.22.5/src/Carousel.js#L158-L172

I've been playing around with child components for things like this so we don't end up with a wall of prop configurations. Something similar to https://github.com/react-bootstrap/react-bootstrap/issues/342#issuecomment-99283154 or with what I'm doing in the new dropdown work here: https://github.com/react-bootstrap/react-bootstrap/blob/dropdown-revisited/src/revisited/DropdownButton.js#L99-L116

**Comment by thetimbanks** [comment]
For a component that uses `this.props.children` in many locations, how would you suggest handling a situation where one or more of the children should be handled differently?

For example, in the Carousel component there are CarouselItem children that are used to create the indicators and the slides. If other children are added for custom controls, how should those be ignored? Is it as simple as just removing those children from `this.props.children` inside of a method similar to the example you gave?

**Comment by mtscout6** [comment]
I'm doing so here: https://github.com/react-bootstrap/react-bootstrap/blob/dropdown-revisited/src/revisited/DropdownButton.js#L99-L115. Hopefully that link will work long enough for you to see it, that's on a branch that I'm actively working on. If that link dies let me know and I'll redirect you when you look again.

**Comment by taion** [comment]
The two referenced PRs resolve this issue.

**Comment by harivasista** [comment]
Is there a way now to change or remove the next and prev icons in Carousel ?

**Comment by thetimbanks** [comment]
@harivasista Can you try passing an empty node in? Something like  `<span/>`.

**Comment by taion** [comment]
just pass in `null`

**Comment by harivasista** [comment]
It worked !!! Thanks a lot guys :)
