### ISSUE TITLE
OverlayTrigger does not accept refs anymore and therefore doesn't expose the hide function

### ISSUE THREAD

**Issue by Tirzono** [react-bootstrap/react-bootstrap#5023]
## Describe the bug

Since #4938 it is not possible anymore to pass a `ref` to `OverlayTrigger`. This breaks implementations that uses this `ref` to hide or show the overlay, such as the example below.

## To Reproduce

1. Go to https://codesandbox.io/s/relaxed-faraday-u86ql
2. Click on 'Click me'
3. Click on 'Bar' in the popover (or anything else in the popover)

## Reproducible Example

https://codesandbox.io/s/relaxed-faraday-u86ql

## Expected behavior

`OverlayTrigger` to accept a `ref` that exposes the `hide` method.

## Environment (please complete the following information)

- Linux
- Chrome 74
- React-Bootstrap Version 1.0.0-beta.8

**Comment by taion** [comment]
That wasn't intended as a public API. If you need to control shown state, use `<Overlay>` directly.

**Comment by Tirzono** [comment]
I was already afraid that would be the case. Thank you for your feedback, I'll go for `<Overlay>` directly then.

Keep up the good work by the way, my compliments for the good work.
