### ISSUE TITLE
Is it possible to use collapses independently from accordions?

### ISSUE THREAD

**Issue by igorsantos07** [react-bootstrap/react-bootstrap#5025]
## Is your feature request related to a problem? Please describe

I need multiple collapsible cards to stay open.

## Describe the solution you'd like

My suggestion would be simply to allow `Accordion.Toggle` to not depend on a parent `Accordion`, or maybe bake that behavior in a `Collapse` component.

## Describe alternatives you've considered

```jsx
function Group({ defaultOpen = false }) {
	const [isOpen, toggle] = useState(defaultOpen)
	return <Card>
		<Accordion.Toggle as={Card.Header} onClick={() => toggle(!isOpen)}>
			<img src={isOpen? iconArrowDown : iconArrowRight} alt={isOpen? "Opened" : "Closed"}/>
			Orders
		</Accordion.Toggle>

		<Accordion.Collapse className={isOpen? 'show' : ''}>
			{/* ... */}
		</Accordion.Collapse>
	</Card>
}
```
This causes an error as there's no `onSelect` from the context.

**Comment by igorsantos07** [comment]
I knew it didn't make much sense, but where's the doc on this `Collapse` element? Not even the search showed it! :disappointed:

**Comment by taion** [comment]
https://react-bootstrap.netlify.com/utilities/transitions/#collapse

**Comment by igorsantos07** [comment]
Unexpected place, at least for me. Nonetheless... no results in search :(

![image](https://user-images.githubusercontent.com/532299/75940734-97886a00-5e6c-11ea-93bc-6470ad9f44df.png)

**Comment by igorsantos07** [comment]
@jquense is it possible to fix this through a PR as well? For the second time, I got lost on Collapse usage... This time, trying to figure out how to collapse an alert (instead of fading it). #3897 hinted me in the solution, but definitely documentation is not clear (on what are the available Transition components besides Fade), nor search :)

**Comment by taion** [comment]
i think it's a slightly different question... we'd be happy to take a PR, but the issue is that search doesn't work? or that the entry is hard to find? not that it doesn't work
