### ISSUE TITLE
Make optional or remove OverlayTrigger warning about only having the "hover" trigger

### ISSUE THREAD

**Issue by bbenoist** [react-bootstrap/react-bootstrap#5027]
## Describe the bug

I've declared an `OverlayTrigger` which should **only** show a video thumbnail tooltip when a mouse pointer is hovering an element.
I don't want it to show if the element (e.g. a button) has keyboard focus or if it receives any touch input.

When running with `NODE_ENV` different from `development`, the following warning appears in the console:

> Warning: [react-bootstrap] Specifying only the `"hover"` trigger limits the visibility of the overlay to just mouse users. Consider also including the `"focus"` trigger so that touch and keyboard-only users can see the overlay as well.

## To Reproduce

Just declare an `OverlayTrigger` with only `"hover"` as trigger.

## Reproducible Example

[![Edit unruffled-rhodes-9noow](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/unruffled-rhodes-9noow?fontsize=14&hidenavigation=1&theme=dark)

## Expected behavior

I expect the library to respect my own design choices without polluting the console.
I am aware of mobile and keyboard users but I know what I'm doing and would prefer if the library didn't pollute my console with the same message sent as many times as I use my component.

## Screenshots

![image](https://user-images.githubusercontent.com/2091902/75981664-3fda1500-5ee5-11ea-9e41-69fb0be098a6.png)

## Environment (please complete the following information)

- Operating System: macOS
- Browser Version: Microsoft Edge Version 81.0.416.20 (Official build) Beta (64-bit)
- React-Bootstrap Version 1.0.0-beta.16

## Workaround

Because the code supposes that they are no duplicate values in the `trigger` array, you can trick the code by passing twice the hover trigger in an array. e.g.:

```tsx
  <OverlayTrigger
    placement="right"
    delay={{ show: 250, hide: 400 }}
    overlay={renderTooltip}
    trigger={["hover", "hover"]}
  >
```

But ssshhhttt! Don't tell it to the devs 😜 

## Additional context

I've tried to find a rationale about this warning in the Git history but could only find `Merge tag 'v0.23.7' into v0.24-rc` as commit message on 75c7270a85af46ed1fed8466e15f0127b9b8a2c7 where the warning has been added.

If you ask, I think that this warning should be removed and eventually put in an eslint rule where it would be more controllable.

**Comment by jquense** [comment]
I think the warning is fairly clear about the rationale here. hover only actions are user hostile enough that we feel they at least warrant a dev only warning. You are entitled to ignore it, but i don't think we will remove it, it's not wrong.

**Comment by aaronofleonard** [comment]
But is the appropriate response to that to make it 'dev hostile'?
This is a very general purpose library, it could be useful in a million different apps. And out of all of those, I'm sure a significant number of those would cover a use case like mine: a desktop only intranet web application. Is it really not reasonable to expect people might be working on these kinds of applications?

I think at least the low hanging fruit would be to make the warning appear just once per page. Does the warning really need to appear every single render (which in my case is several hundred times)? I don't even think I'd be seeking out a way to disable it if it only appeared once when the `hover` was detected, but it appearing potentially hundreds or thousands of times is excessive, regardless of how justified it is believed to be.

**Comment by psiservices-pmerriman** [comment]
When I first started using bootstrap, overriding styles and behaviors was pretty easy. Lately, it has been easier on simple controls to just "roll my own" because of things like this. It is a good thing for libraries to notify you about things that the authors deem important. It is another thing to not allow suppression or some other form of acknowledgement that says, "I understand this point, but because of my specific use case, I choose to ignore it, so stop spamming me". Inform, don't dictate.

**Comment by jquense** [comment]
we are informing via a warning that you can ignore. "dictating" would be if we prevented you from doing it entirely, A thing the code *could* do but we don't.
