### ISSUE TITLE
Number support for Form.Control

### ISSUE THREAD

**Issue by deriegle** [react-bootstrap/react-bootstrap#5028]
## Describe the bug

`Form.Control` does not support a number as a value. It is just a wrapper around `input` unless you change `as`.

An `input` element supports numbers as the value in the [React Typescript definition](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts#L2058)

## To Reproduce

Add a new `Form.Control` element and try to use a number as a `value` prop. It will throw type errors.

## Reproducible Example

Minimal example by using [CodeSandbox](https://codesandbox.io/s/quirky-shape-d34t7?fontsize=14&hidenavigation=1&theme=dark).

## Expected behavior

I'd expect it to allow numbers.

**Comment by jquense** [comment]
we'd happily accept a PR to fix the type!

**Comment by deriegle** [comment]
@jquense Great! I'll create a PR to fix this. I just wanted to double check that there wasn't a reason that it wasn't supported.
