### ISSUE TITLE
Getting an error when trying to use react-bootstrap

### ISSUE THREAD

**Issue by shaimo** [react-bootstrap/react-bootstrap#503]
It seems to be related to the fact that FormGroup is using ES6 classes, but I have no clue how to work around this.

```
FormGroup.js:7 Uncaught TypeError: Super expression must either be null or a function, not undefined
FormGroup.js:7 _inherits
FormGroup.js:24 (anonymous function)
FormGroup.js:47 /Users/shaimo-mbp/dev/ruby/test_app/node_modules/react-bootstrap/lib/FormGroup.js.classnames
_prelude.js:1 s
_prelude.js:1 (anonymous function)
Input.js:13 /Users/shaimo-mbp/dev/ruby/test_app/node_modules/react-bootstrap/lib/Input.js../Button
_prelude.js:1 s_prelude.js:1 (anonymous function)
index.js:45 /Users/shaimo-mbp/dev/ruby/test_app/node_modules/react-bootstrap/lib/index.js../Accordion
_prelude.js:1 s
_prelude.js:1 (anonymous function)
_stream_0.js:7 /Users/shaimo-mbp/dev/ruby/test_app/app/assets/javascripts/
_stream_0.js../components/CategoryShow
_prelude.js:1 s
_prelude.js:1 e
_prelude.js:1 (anonymous function)
```

**Comment by mtscout6** [comment]
I first saw this in the gitter room [April 6 2015 8:45 AM](https://gitter.im/react-bootstrap/react-bootstrap?at=55229c1f9fd3a4be579f8237). I don't know why using ES6 classes are causing problems. I'll look into this morning and see what I can figure out.

**Comment by mtscout6** [comment]
@shaimo Are you also using browserify the same as @joelhawksley mentioned in the gitter room?

**Comment by shaimo** [comment]
Yes, also with browserify, and with rails if that matters. Maybe a couple of additional hints:
1) I get an error also when requiring react-router. Similarly it uses ES6 classes.
2) I came across this: http://ctheu.com/2015/02/26/react-server-side-with-es6-syntax/. It explicitly talks about that error claiming it would appear if not using react 0.13 and above (I do use 0.13.1). Also saying something about a "Default" option that is needed and used by Babel when transforming the file (which apparently doesn't take place here).

**Comment by mtscout6** [comment]
So, from what I'm gathering from that post is that I should change

```
class FormGroup extends React.Component {
```

to

```
export default class FormGroup extends React.Component {
```

Is that what you are seeing?

**Comment by shaimo** [comment]
I really don't know. My understanding was that babel or reactify, which translate the file, should already be taking care of that. Initially I thought I was not using reactify/babel correctly, but then I realized I'm using a file which was already been transformed/compiled as part of the distribution...

**Comment by mtscout6** [comment]
Hmm, I'm trying to duplicate this issue. I pushed up the branch [es6-super-bug](https://github.com/react-bootstrap/react-bootstrap/tree/es6-super-bug/test/apps/browserify) With a really simple browserified bundle that merely renders an input to the screen. To run this yourself you should run `npm run build` first to make sure that the lib folder is created with the babel compiled output. Then I ran `browserify index.js -o bundle.js` in that directory. I do not see the bug, am I missing something?

**Comment by shaimo** [comment]
@mtscout6 What do you mean by "I do not see the bug"? The output does include that "default" keyword?
My setup may be a bit different because I'm using rails. I'm new to react and npm and took me a while to manage to get something that works (apparently still not 100% working). I'm using browserify-rails.
BTW, I just updated the npm modules on my system and in src/FormGroup.js I do see ```export default FormGroup;```, while in the dist file (dist/react-bootstrap.js) it appears without "default": ```module.exports = FormGroup;```. Why is that?

**Comment by shaimo** [comment]
@mtscout6 I think I'm starting to get a clue for what's happening. I found that I'm using some npm module (react-star-rating-input) that seems to insist on using older versions of react. I guess this causes my entire project to use the older react version which is incompatible with ES6. Anyway, I guess not a bug with react-bootstrap (nor react-router) after all. Sorry for the trouble and please close the issue. Thanks for your help!
