### ISSUE TITLE
onSubmit and onChange prop typings are broken for form and form control elements

### ISSUE THREAD

**Issue by jeffreymeng** [react-bootstrap/react-bootstrap#5037]
## Describe the bug

If I create a form like below:
```tsx
<Form
        onSubmit={(e) => e.preventDefault()}>
...
</Form>
```
or a form control like below:
```tsx
<Form.Control
      onChange={(e) => setValue(e.target.value)}
/>
```
Typescript will not know the type of the parameter `e`, and thinks that it is implicitly `any`. This doesn't happen if you use a native HTML form e.g. &lt;form> without react bootstrap (see the screenshot below).
You get warned of this error if you enable `noImplicitAny` in the typescript settings.

## To Reproduce

Create any react bootstrap form or form.control like above, and enable the `noImplicitAny` typescript compiler option.

## Reproducible Example

Go to https://codesandbox.io/s/react-bootstrap-bug-demo-bcpnj
Wait about 30 seconds for typescript to compile and typescript will underline the error in red.

## Expected behavior

The type of `e` should be defined in the typings.

## Screenshots

<img width="663" alt="2020-03-11_17-43-51" src="https://user-images.githubusercontent.com/15185258/76476698-1ecf6380-63c0-11ea-9c60-b02d25bbf377.png">

## Environment (please complete the following information)

- Operating System: MacOS
- Typescript Version 3.8.3
- React-Bootstrap Version 1.0.0-beta17

Thank You! React Bootstrap is a great library, and it's awesome that it keeps control of its own types, instead of using third party types.

**Comment by kosmiq** [comment]
@taion @jquense @bpas247 @mxschmitt  I'm not sure how to fix this, but changing the types in whatever ways I can think of does not remove the implicitly: any error.

Using it in a .tsx file reports what I see as the expected type (when I do not specify any type in the onChange):
![Screenshot 2020-03-28 at 01 44 48](https://user-images.githubusercontent.com/322759/77810634-bfe33d00-7095-11ea-81c6-99e083f18bf1.png)

I guess the issues comes from `| undefined`. Is this even solvable with types?

**Comment by taion** [comment]
This comes from how we have the `as` handling set up.

I think TypeScript is potentially inferring some weird type for `As` here. You can get around it by writing `Form<'form'>`.

I wonder if we can set up some overload here or do something to _force_ `As` there to be `'form'` when it's not explicitly specified.

**Comment by kyletsang** [comment]
As of 1.1.1, `onChange` works but `onSubmit` does not.

**Comment by jquense** [comment]
This seems to affect all event handlers.  it's very confusing to me, TS is definitely finding the correct type as evidenced by vscode intellisense giving the correct handler signature, but in practice it's `any` unless you explicitly label it. I'm not sure why that happens but guessing it's related to all the indirection to get the props?
