### ISSUE TITLE
https://react-bootstrap.github.io/ displays beta16 as latest

### ISSUE THREAD

**Issue by kosmiq** [react-bootstrap/react-bootstrap#5039]
## Describe the bug

Visiting: https://react-bootstrap.github.io/ says that beta 16 is the latest release.
Visiting: https://react-bootstrap.netlify.com/ correctly says beta 17 is available

## To Reproduce

Visit https://react-bootstrap.github.io/

## Expected behavior

It should say beta 17.

**Comment by mxschmitt** [comment]
Unfortunately the https://github.com/react-bootstrap/react-bootstrap.github.io needs to be updated manually.
Maybe we should add auto deployment via GitHub Actions or add directly a redirect to the site from Netlify which will be automatically deployed once a change happens on master.

**Comment by jquense** [comment]
let me push an update
