### ISSUE TITLE
Open Modal with animation doesn't work

### ISSUE THREAD

**Issue by softmastx** [react-bootstrap/react-bootstrap#5042]
## Describe the bug

I can't open modal with animation although animation props is set to true
It open and close the Modal the same effect as without animation.

## To Reproduce

<Modal size="md" show={this.state.show} onHide={this.handleClose} animation={true}>

## Expected behavior

Open and close the Modal with a slide and fade animation.

- Operating System: [macOS]
- Browser, Version [Chrome 74]
- React-Bootstrap Version [1.0.0-beta.16]

**Comment by taion** [comment]
This works in our examples: https://react-bootstrap.github.io/components/modal/#modals-live

You may be missing some CSS.

**Comment by softmastx** [comment]
I didn't see any differences when I clicked the Launch Demo Modal Buttons, They just popping up without sliding animation!

**Comment by kosmiq** [comment]
Do you have any prefer reduced motion or other accessibility settings set in your browser?

They work for me on Chrome 80 on MacOS as well as in Safari on IOS.

**Comment by softmastx** [comment]
> Do you have any prefer reduced motion or other accessibility settings set in your browser?
> 
> They work for me on Chrome 80 on MacOS as well as in Safari on IOS.

I've tested on Safari, Chrome and Firefox as well they are the same!

**Comment by kosmiq** [comment]
Did you by any change disable animations in MacOS itself then?

**Comment by softmastx** [comment]
> Did you by any change disable animations in MacOS itself then?

It's working now! 
Turn out that the issue is macOS side.  The Reduce Motion was accidentally set!!
Uncheck reduce motion solved the problem.

Big thanks for you help!!

**Comment by stassilla** [comment]
But it doesnt explain why animation is working in AngularJS for bootstrap modal with this setting turned off.
