### ISSUE TITLE
Keyboard arrows will not work before first click on slide arrows

### ISSUE THREAD

**Issue by vctr90** [react-bootstrap/react-bootstrap#5045]
## Describe the bug

Keyboard arrows will not work on carousel before the first click on any of the slide arrows

## To Reproduce

1. Open the Carousel (Make sure `keyboard` prop y not set to false or not set)
2. Do not click on any arrow of the carousel for the first time
3. Try pressing the keyboard arrows
4. Nothing happens

## Reproducible Example

Minimal example by using [CodeSandbox](https://codesandbox.io/s/elastic-satoshi-e9we8).

## Expected behavior

Keyboard arrows will always work regardless if the user has clicked or not the slide arrows for the first time

## Screenshots

N/A

## Environment (please complete the following information)

- Operating System: Windows 10
- Browser, Version Firefox 74.0, Chrome 80.0
- React-Bootstrap Version 1.0.0-beta.16

## Additional context

N/A

**Comment by taion** [comment]
That's just how it works upstream. Otherwise what would happen if you rendered multiple carousels? If you need different keyboard behavior, you can disable the built-in behavior and add your own.

**Comment by vctr90** [comment]
@taion Thanks for the quick response. I agree and completely understand but there might be a use case where we might need it. What about having a prop to enable this? Of course it would be `false` by default. This way we could have the power to choose whether this might be convenient or not. I have a client (A user that does not know anything about computers) whose first reaction on a gallery was pressing the arrow keys on the keyboard and she was not comfortable with it.

Sorry for reporting it as a bug but if you agree with the use case, would you like me to create a feature request instead?

**Comment by vctr90** [comment]
We could add someting like: enableKeyboardInmediateFocus (default: false)

**Comment by taion** [comment]
Well, the semantics aren't quite well-defined. Do we focus the carousel immediately? Or do we listen to keyboard events globally?

I agree that this is useful, but given that it's not present upstream, there are enough questions that I don't think it's a good fit for the library.

**Comment by redochka** [comment]
A workaround was suggested on https://github.com/kenwheeler/slick/issues/901#issuecomment-254088744 which uses keyboard left/right key events.
Checkout this typescript gist: https://gist.github.com/redochka/f98d993d331a72f82d1e49f6942588de implementing the idea and is working fine here.
