### ISSUE TITLE
feat: Allow for custom variants when using Typescript

### ISSUE THREAD

**Issue by kosmiq** [react-bootstrap/react-bootstrap#5047]
## Is your feature request related to a problem? Please describe

It is currently not easily possible to use the built-in `<Button>` component with a custom `variant` when in a TypeScript environment. There are workarounds for creating your own `<Button>` component that extends the current one.

But with Bootstrap it is easy to create your own variants on things in SCSS by extending the $theme-colors map and have their SCSS magic create buttons etc with whatever you add to the map. It would be nice to easily expose this when using TypeScript without having to create new components.

This also applies for other components that have the "variant" prop.

## Describe the solution you'd like

Using conditional TypeScript props might be a solution for this. Adding a prop called `customVariant` that is a boolean, and if true changes the "variant" to "string" instead of the defined acceptable values.

I'm sure someone can give a better version of the conditional props below and create them in a better way.

## Additional context

This could avoid questions such as #4461 #3693 #3574

I did a quick experiment after some very rudimentary reading about conditional props (added in TS2.8) and created this as a test.

It would of course be up to the user to make sure that they supply a variant that works with their CSS/SCSS setup. We should probably also warn in Button.js that if customVariant is set you are required to supply something to variant.

The below changes to Button.d.ts seems to make this possible:
```
<Button size="lg" variant="primary" />; // reports ok
<Button size="lg" variant="not-defined-variant" />; // reports error that customVariant is not set
<Button size="lg" customVariant variant="not-defined-variant" /> // reports ok and that variant should be a "string";
```

The below changes to Button.d.ts gives us two good things:
- If you set customVariant you can type whatever you like into "variant"
- If you set a variant that is not defined you get a TS error that forces you to set customVariant to fix the error.

**Button.d.ts**
```
interface ButtonPropsRegular {
  active?: boolean;
  block?: boolean;
  customVariant?: boolean;
  variant?:
    | 'primary'
    | 'secondary'
    | 'success'
    | 'danger'
    | 'warning'
    | 'info'
    | 'dark'
    | 'light'
    | 'link'
    | 'outline-primary'
    | 'outline-secondary'
    | 'outline-success'
    | 'outline-danger'
    | 'outline-warning'
    | 'outline-info'
    | 'outline-dark'
    | 'outline-light';
  size?: 'sm' | 'lg';
  type?: 'button' | 'reset' | 'submit';
  href?: string;
  disabled?: boolean;
}

interface ButtonPropsCustom {
  active?: boolean;
  block?: boolean;
  customVariant: boolean;
  variant?: string;
  size?: 'sm' | 'lg';
  type?: 'button' | 'reset' | 'submit';
  href?: string;
  disabled?: boolean;
}

export type ButtonProps = ButtonPropsRegular | ButtonPropsCustom;

declare class Button<
  As extends React.ElementType = 'button'
> extends BsPrefixComponent<As, ButtonProps> {}

export default Button;

```

**Comment by kosmiq** [comment]
@taion @bpas247 @jquense any input here? Do you think this would be a good idea or not?

**Comment by taion** [comment]
Adding a custom prop for just TS is a bit unfortunate \:

Bleh, can users not just, like... re-declare the Button typedef? It's a little clunky, but it does allow some level of type-safety there.

**Comment by kosmiq** [comment]
Alright. We'll add that to the TypeScript section of the docs whenever we get there.
