### ISSUE TITLE
`Dropdown.Toggle` expects `onClick` prop when using a custom element incorrectly

### ISSUE THREAD

**Issue by enkuush-ca** [react-bootstrap/react-bootstrap#5049]
## Describe the bug

When using a custom component in a Dropdown.Toggle, if the custom element takes an onClick property (which should be the case), the type checker emits an error telling that an onClick prop must be provided to Dropdown.Toggle. This message is incorrect since it is the responsibility of Dropdown.Toggle to call our custom component with the onClick prop.

**Comment by taion** [comment]
dupe https://github.com/react-bootstrap/react-bootstrap/issues/4819
