### ISSUE TITLE
Ho to use react-bootstrap with bootstrap v4.3.1?

### ISSUE THREAD

**Issue by rwehresmann** [react-bootstrap/react-bootstrap#5051]
I have a layout built with bootstrap v4.3.1, and I'm implementing it in react now. I would like to use `react-bootstrap`, but there are some styles that aren't matching probably because the bootstrap version is higher.

 Is there any way I can use `react-bootstrap` with bootstrap v4.3.1?

**Comment by taion** [comment]
The v1 betas work just fine with Bootstrap v4
