### ISSUE TITLE
Form.Label - column="sm" or column="lg" generate an error with TypeScript in VSCode

### ISSUE THREAD

**Issue by sylmarch** [react-bootstrap/react-bootstrap#5056]
## Describe the bug

Attributes `column="sm"` and `column="lg"` on `<Form.Label>` generates the following error in VSCode when using TypeScript:

> TypeScript error in /home/sylmarch/workspace/my-project/src/components/MyComponent.tsx(55,53):
> No overload matches this call.
>   Overload 1 of 2, '(props: Readonly<Pick<Pick<DetailedHTMLProps<LabelHTMLAttributes<HTMLLabelElement>, HTMLLabelElement>, "form" | ... 255 more ... | "htmlFor"> & { ...; }, "ref" | ... 255 more ... | "is"> & BsPrefixProps<...> & FormLabelWithColProps> | Readonly<...>): FormLabel', gave the following error.
>     Type 'string' is not assignable to type 'boolean | undefined'.
>   Overload 2 of 2, '(props: ReplaceProps<"label", (BsPrefixProps<"label"> & FormLabelWithColProps) | (BsPrefixProps<"label"> & FormLabelOwnProps)>, context?: any): FormLabel', gave the following error.
>     Type 'string' is not assignable to type 'boolean | undefined'.  TS2769
> 
>     53 |                                 <Form.Group>
>     54 |                                     <Form.Row>
>   > 55 |                                         <Form.Label column="lg" lg={2}>
>        |                                                     ^
>     56 |                                             Large Text
>     57 |     </Form.Label>
>     58 |                                         <Col>

## To Reproduce

Copy the sample code from the documentation (https://react-bootstrap.netlify.com/components/forms/#horizontal-forms-label-sizing) : 

```
<Form.Group>
  <Form.Row>
    <Form.Label column="lg" lg={2}>
      Large Text
    </Form.Label>
    <Col>
      <Form.Control size="lg" type="text" placeholder="Large text" />
    </Col>
  </Form.Row>
  <br />
  <Form.Row>
    <Form.Label column lg={2}>
      Normal Text
    </Form.Label>
    <Col>
      <Form.Control type="text" placeholder="Normal text" />
    </Col>
  </Form.Row>
  <br />
  <Form.Row>
    <Form.Label column="sm" lg={2}>
      Small Text
    </Form.Label>
    <Col>
      <Form.Control size="sm" type="text" placeholder="Small text" />
    </Col>
  </Form.Row>
</Form.Group>
```

## Expected behavior

`column` value can also be a string (`lg` or `sm`).

## Environment (please complete the following information)

- React-Bootstrap Version : 1.0.0-beta.]17
- VSCode Version: 1.42.0
- TypeScript Version: 3.7.5

**Comment by taion** [comment]
ah, we didn't update `FormLabel.d.ts`; care to send in a PR?
