### ISSUE TITLE
Form.File is missing in v1.0.0-beta.17

### ISSUE THREAD

**Issue by wombat86** [react-bootstrap/react-bootstrap#5057]
## Describe the bug

`Form.File` is missing in both code and typings for package version `1.0.0-beta.17`. However, it is present in `master` branch and is mentioned in documentation for version `1.0.0-beta.17`.

## To Reproduce

1. Setup a React/TypeScript project
1. Install npm package `1.0.0-beta.17`
1. Add import: ```import Form from "react-bootstrap/Form";```
1. Create any react component and add ```<Form.File/>``` to TSX.
1. Compile
1. Observe compilation error `TS2339: Property 'File' does not exist on type 'typeof Form'.`

## Expected behavior

* At least the documentation should be updated accordingly to not confuse developers.
* Also, it would be nice to have this feature actually released since it's already in master branch and documentation.

**Comment by kosmiq** [comment]
Where is it mentioned in the current docs? I skimmed through what's published and can't seem to find it?

It is, just like you noticed, coming in the next version. The pr is not that old though and I guess a few more features/Prs will be merged/finished before it comes around.

**Comment by wombat86** [comment]
My bad, I didn't provide a URL. Here it is: https://react-bootstrap.netlify.com/components/forms/#forms-custom.
Providing the screenshot as well:
<img width="1919" alt="https___react-bootstrap_netlify_com_components_forms__forms-custom" src="https://user-images.githubusercontent.com/5948134/77224202-e8d27200-6b6b-11ea-832a-bc79af1b4170.png">

**Comment by kosmiq** [comment]
Huh. I had to run incognito to see it. The docs were added in the same pr as the component itself.

@jquense are the docs automatically from master?

**Comment by taion** [comment]
Netlify auto-deploys from master. It's the "live" docs page, though, and not the "official" one, which is at https://react-bootstrap.github.io/, and correctly omits `<Form.File>` in https://react-bootstrap.github.io/components/forms/.

We should probably add something there indicating that the docs are for `master` and not for the latest release.

**Comment by wombat86** [comment]
@taion tbh I found this URL via Google, so you might get more developers like me who read that "unofficial" page. Perhaps you might want to restrict access to it for public users.

**Comment by mxschmitt** [comment]
Maybe we should add a "if URL ends with `netlify.com` then show a banner at the top right with the text: "current master branch and not guaranteed to be published" or something like that.

**Comment by altwarg** [comment]
@wombat86 just update react-bootstrap to version 1.0.0 (without beta). Works for me (I've used TS)

**Comment by wombat86** [comment]
@altwarg version 1.0.0 was not available at the point when this issue was opened. I believe pretty much that this issue might have caused this version to be actually published though I might be wrong here.
