### ISSUE TITLE
d-sm-block doing the oposite

### ISSUE THREAD

**Issue by annecchini** [react-bootstrap/react-bootstrap#5062]
## Describe the bug

If I try to include a className="d-sm-block" the component show normal on small screens and block on wide screens.

## To Reproduce

I'm using this piece of code:

```
<Dropdown className="d-sm-block" as={ButtonGroup}>
              <Dropdown.Toggle block variant="success" id="dropdown-basic">
                Dropdown Button
              </Dropdown.Toggle>

              <Dropdown.Menu>
                <Dropdown.Item href="#/action-1">Action</Dropdown.Item>
                <Dropdown.Item href="#/action-2">Another action</Dropdown.Item>
                <Dropdown.Item href="#/action-3">Something else</Dropdown.Item>
              </Dropdown.Menu>
</Dropdown>
```
Reduce the screen size and see the problem.

## Reproducible Example

https://codesandbox.io/s/react-bootstrap-d-sm-block-xu9dx

## Expected behavior

block on small screens
inline-block on other screens

**Comment by taion** [comment]
yes, that's what the utility class does: https://getbootstrap.com/docs/4.4/utilities/display/#hiding-elements

more broadly, we don't manage the CSS here. it's in upstream bootstrap.
