### ISSUE TITLE
Bug in OverlayTrigger placement=top

### ISSUE THREAD

**Issue by Hakawa2** [react-bootstrap/react-bootstrap#5069]
- placement=top
![Screenshot_5](https://user-images.githubusercontent.com/18398868/77684623-fc6d4680-6f78-11ea-8d99-f60853e00617.png)

- placement=bottom
![Screenshot_6](https://user-images.githubusercontent.com/18398868/77684629-fd05dd00-6f78-11ea-91c5-219bc8054c0b.png)

- placement=left
![Screenshot_7](https://user-images.githubusercontent.com/18398868/77684630-fd9e7380-6f78-11ea-849c-1d7d120306d9.png)

- Bootstrap version ~1.0.0-beta.9

**Comment by kosmiq** [comment]
Please upgrade your react-bootstrap version. The latest version is 1.0.0 (not beta)

**Comment by Hakawa2** [comment]
- Updated but not resolved

![Screenshot_2](https://user-images.githubusercontent.com/18398868/77701736-bc688c80-6f95-11ea-94a2-3adc4ec310d6.png)

![Screenshot_1](https://user-images.githubusercontent.com/18398868/77701743-becae680-6f95-11ea-950e-e8dff6b8f0c0.png)

**Comment by kosmiq** [comment]
Are you using custom positioning of any elements? We'd probably need to see some code where the error occurs.

Can you create a testcase on https://codesandbox.io/ or similar? The placement works fine in the docs and in my local testing.

**Comment by Hakawa2** [comment]
Yeah, tested in https://codesandbox.io/s/bootstrap-5lxos it worked

Sorry for my terrible English, but i have doubts in some points

- First: Before this monday, this tooltip always worked, in this monday i run my job in jenkins for updated my ambient for testing and boom, this tooltip is broken 

- Second: In my ambient of production i noted whe style inline for tooltip using translated3d, but in my ambient of testing, the same code inline using translate, the version is equals 1.0.0-beta.9, but as said in fist point,my job for update ambient, is delete node_modules, and execute npm run install

**Comment by jquense** [comment]
this does seem like a difference. probably due to the popper upgrade, which might have changed some assumptions...It'd be great if we could narrow down to a very minimal reproduction

**Comment by Coolfeather2** [comment]
Same issue

**Comment by kosmiq** [comment]
@Coolfeather2 we do need an example of when it fails. Can you produce something and put on codesandbox or similar?

**Comment by iqqmuT** [comment]
The bug can be seen in this minimal example:
https://codesandbox.io/s/react-bootstrap-tooltip-bug-jhyrt4?file=/src/App.js

Top tooltip gets a wrong position but bottom tooltip works ok.
![Screenshot from 2022-03-15 11-00-33](https://user-images.githubusercontent.com/490260/158342638-9438cdbd-624a-443b-b17b-9a2a4c09cc8c.jpg)

The bug is visible only when using this CSS:
```css
html {
  position: relative;
}

.content {
  min-height: 100vh;
}
```

**Comment by iqqmuT** [comment]
@kosmiq @kyletsang Should this issue be reopened?

**Comment by kyletsang** [comment]
@iqqmuT, since you changed the position styling in your root, you would need to change the popper positioning strategy as well.  

Try this:
```
<OverlayTrigger popperConfig={{strategy: 'fixed'}} ...>
```

https://popper.js.org/docs/v2/constructors/#strategy

**Comment by iqqmuT** [comment]
@kyletsang Thank you, that works! codesandbox fixed.
