### ISSUE TITLE
Conflicting style options for <Input type="submit" />

### ISSUE THREAD

**Issue by glenjamin** [react-bootstrap/react-bootstrap#507]
When setting `bsStyle="danger"` I get:
> Warning: Failed propType: Invalid prop `bsStyle` of value `danger` supplied to `FormGroup`, expected one of ["success","warning","error"]. Check the render method of `Input`.

When setting `bsStyle="error"` I get:
> Warning: Failed propType: Invalid prop `bsStyle` of value `error` supplied to `Button`, expected one of ["default","primary","success","info","warning","danger","link","inline","tabs","pills"]. Check the render method of `Input`.

**Comment by mtscout6** [comment]
That's definitely a bug.

**Comment by AlexKVal** [comment]
The fix is at #514

**Comment by glenjamin** [comment]
After looking at the changes in #514 it seems like a better fix would be to use a different name than bsStyle for the form validation prop - although this would be have to be done in stages to maintain backwards-compat :(

**Comment by AlexKVal** [comment]
I've done it with API compatibility in mind.

I'm going to give a look if I am able to split the ```<Input />``` into several distinct components as proposed in #342. 
If I decide that I will try to do it, I write about it in that PR.
(unless someone else will do it before me, of course :) )

I think that splitting the component will automatically resolve the issue with `bsStyle` too.

**Comment by mtscout6** [comment]
I agree that splitting the Input component is the better solution. Ideally you would be able to carve out the submit button to it's own component. Change the Input to use that component with a console warning telling downstream users of the deprecation, which we would be able to safely remove later on.

**Comment by AlexKVal** [comment]
Thank you for your hint with console warning about deprecation @mtscout6. :+1:

**Comment by taion** [comment]
Is this complete now that #626 has landed?

**Comment by mtscout6** [comment]
Yes!
