### ISSUE TITLE
Alerts dismiss doesn't trigger hide

### ISSUE THREAD

**Issue by maidul98** [react-bootstrap/react-bootstrap#5070]
<Alert variant="danger" onClose={() => false} dismissible>
        <Alert.Heading>Oh snap! You got an error!</Alert.Heading>
        <p>
          Change this and that and try again. Duis mollis, est non commodo
          luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit.
          Cras mattis consectetur purus sit amet fermentum.
        </p>
</Alert>

It says that onClose triggers the show, so I assume if I set onClose={() => false}, then show should be set to False. But it does nothing. What is wrong?

**Comment by mxschmitt** [comment]
Basically you have to use `onClose` in combination with the `show` attribute to make it [controlled](https://reactjs.org/docs/forms.html#controlled-components).

Example: https://react-bootstrap.netlify.com/components/alerts/#dismissing
