### ISSUE TITLE
Card <p> inside Card.Text throws console error

### ISSUE THREAD

**Issue by SpencerKaiser** [react-bootstrap/react-bootstrap#5071]
## Describe the bug
Nesting a `<p>` within a `<Card.Text>` throws a runtime console error:
`Warning: validateDOMNesting(...): <p> cannot appear as a descendant of <p>.`

## To Reproduce
1. Create a Card
2. Add a Card.Text element
3. Add a `<p>` inside the `<Card.Text>`
4. Review console errors in the browser

## Reproducible Example

I tried creating an example on [CodeSandbox](https://codesandbox.io/s/github/react-bootstrap/code-sandbox-examples/tree/master/basic) but I wasn't able to save a link. Paste the below code into that sandbox and it'll throw the error in console.
``` jsx
import React, { useState } from "react";

import Card from "react-bootstrap/Card";
import Container from "react-bootstrap/Container";

import "./App.css";

const App = () => (
  <Container className="p-3">
    <Card className="mt-3">
      <Card.Body>
        <Card.Title>This should throw a console error</Card.Title>
        <Card.Text>
          <p>This is a paragraph</p>
          <p>This is another paragraph</p>
        </Card.Text>
      </Card.Body>
    </Card>
  </Container>
);

export default App;
```

## Expected behavior
No console errors.

## Environment (please complete the following information)

- Operating System: macOS
- Browser, Version: Safari Version 13.0.5 (15608.5.11)
- React-Bootstrap Version: 1.0.0-beta.17

## Additional context

This bug seems to **only be in Safari**.

**Comment by kosmiq** [comment]
That is because the `<Card.Text>` outputs a `<p>` tag. So it's kind of expected.

From Card.js in the source:
`Card.Text = createWithBsPrefix('card-text', { Component: 'p' });`

You have however either use multitple `<Card.Text>` for each paragraph you need to output  or use <p className="card-text"> if you'd rather do it that way.

**Comment by SpencerKaiser** [comment]
Ah that's a great workaround! Maybe you guys can add an extra `<CardText>` to an example to show that it's possible? I wasn't sure about how to break apart two paragraphs without using a breaking space.

**Comment by taion** [comment]
We can't reliably detect `<p>` inside `<Card.Text>`, but @kosmiq updated the docs

**Comment by SpencerKaiser** [comment]
Cool, thanks @taion!
