### ISSUE TITLE
Accordion toggle/collapse submits the form

### ISSUE THREAD

**Issue by xSAVIKx** [react-bootstrap/react-bootstrap#5072]
## Describe the bug

If the `<Accordion>` component is used inside the form without customizations of the default component, the `button` component is used for both `<Accordion.Collapse>` and `<Accordion.Toggle>`. And by default, a `button` without a specific `type` is treated by the browser as a `submit` button which leads to unintentional submission of the form upon toggling/collapsing the form.

## To Reproduce

1. Open [sandbox](https://codesandbox.io/s/bitter-worker-2gdh7).
2. Enter anything in the input field.
3. Click on Toggle.

## Expected behavior

The toggle/collapse is not submitting the form.

**Comment by kosmiq** [comment]
@taion @jquense should we default the `<Accordion.Toggle>` to `type="button"`? Should be safe and lets us avoid this.

**Comment by mxschmitt** [comment]
> @taion @jquense should we default the `<Accordion.Toggle>` to `type="button"`? Should be safe and lets us avoid this.

ok for me

**Comment by taion** [comment]
yeah, we should make all buttons default to type `button`
