### ISSUE TITLE
Unable to pass in data attribute from onClose dismissible alert

### ISSUE THREAD

**Issue by maidul98** [react-bootstrap/react-bootstrap#5073]
Is there any way to trigger a function on close such that it is able to passes in a custom data attribute on the alert element? Right now, the onClose function can only return true or false. 

For example:
`{submissionsError.map((ob, indexj) =><Alert  data-index-of-error ={index} onClose={fun1} show={show} dismissible variant={obj['type']}>{obj['message']}</Alert>)}
`

where fun1 has access to data-index-of-error?

**Comment by taion** [comment]
If you need additional values, you should close over them in the `onClose` callback. You can also look at the second argument, which is the actual event that triggered the close.
