### ISSUE TITLE
Tooltip has some error in typescript

### ISSUE THREAD

**Issue by xubinshan** [react-bootstrap/react-bootstrap#5074]
![image](https://user-images.githubusercontent.com/6842419/77717125-9fc26800-701a-11ea-8ad5-010d105bd56e.png)

![image](https://user-images.githubusercontent.com/6842419/77717140-a6e97600-701a-11ea-8196-f39dd751a032.png)

## Environment 
- Operating System: [e.g. macOS]
- Browser, Version [e.g. Chrome 80]
- React-Bootstrap Version [e.g. 1.0.0]

**Comment by taion** [comment]
was resolved in https://github.com/react-bootstrap/react-bootstrap/pull/5068
