### ISSUE TITLE
RedirectButton - redirect on click without page reload

### ISSUE THREAD

**Issue by piatkiewicz** [react-bootstrap/react-bootstrap#5077]
Last time i needed to redirect user on button click. Existing `Button` has `href` property, but it causes page to reload after click. So I made `RedirectButton` - maybe somebody will look for it:

```
import React from "react";
import { withRouter } from "react-router-dom";
import { Button } from "react-bootstrap";

const RedirectButton = (props: any) => {
  const redirect = () => props.history.push(props.to);

  return (
    <Button {...props} onClick={redirect}>
      {props.children}
    </Button>
  );
};

export default withRouter(RedirectButton);
```

Usage:
```
<RedirectButton variant="primary" to="/some-route">
    Do stuff
</RedirectButton>
```
Look:
![btn](https://user-images.githubusercontent.com/8793897/77794667-8e09b080-706c-11ea-984b-0eab0f80c27d.jpg)

Or maybe there is some other solution already implemented?

**Comment by mxschmitt** [comment]
Maybe that fits for your use-case: https://github.com/react-bootstrap/react-router-bootstrap
Alternatively try out the Link component by react-router-dom.

**Comment by piatkiewicz** [comment]
Right, there is `LinkContainer` element in react-router-bootstrap specially for that
