### ISSUE TITLE
Dropdown.Item blocks inner onClick

### ISSUE THREAD

**Issue by igorsantos07** [react-bootstrap/react-bootstrap#5082]
## Describe the bug

`Dropdown.Item` seems to have a forced `onClick` property that ignores what's set on the `as` component.

## Reproducible Example

```jsx
const SpecialButton = ({ action, ...props }) => {
  const onClick = () => {
    console.log('extra actions here')
    action()
  }
  return <Button onClick={onClick} {...props}/>
}

<DropdownButton>
  <Dropdown.Item as={SpecialButton} action={() => window.alert('worked')}>Nothing happens</Dropdown.Item>
</DropdownButton>
```

Minimal example by using [CodeSandbox](https://codesandbox.io/s/dropdownitem-inner-onclick-bug-xnkz1).

## Expected behavior

The inner `onClick` should be fired, instead of being hidden by the `Dropdown.Item`'s "empty" `onClick`.

## Environment (please complete the following information)

- Operating System: Linux
- Browser, Version Vivaldi 2.11 / Chromium 80
- React-Bootstrap Version [e.g. 1.0.0-beta.16]

## Additional context

This seems related to #1490, but I see the discussion there is around leaving the Dropdown open. Here I want to have a custom onClick handler defined later. I wonder if this inner handler would need to force bubbling, so the upper component can close the dropdown?

**Comment by kosmiq** [comment]
Using onClick works though, haven't tested action honestly. Does that solve your short-term issue?
https://codesandbox.io/s/dropdownitem-inner-onclick-bug-2byi4

**Comment by taion** [comment]
It's not "empty"; it needs to invoke various parent "select" callbacks.

You can look at the code – if you pass in an `onClick` prop to `Dropdown.Item`, it will merge that callback with the ones it adds.

**Comment by igorsantos07** [comment]
That's why I used quotes - it certainly has its use, but not for the immediate use of who's implementing :)

I understand it would solve if I passed the onClick directly, but if you look at the case I have shown, there's no way to pass that from the inner component - at least not that I can see. Any guidance?

**Comment by igorsantos07** [comment]
@taion, check my question above please :)

**Comment by taion** [comment]
Okay, so the issue is more that your `SpecialButton` is just spreading `{...props}` over its own `onClick`, instead of combining the supplied `onClick` prop with its own click handler.

As in `Dropdown.Item`, you should define an `onClick` handler that both invokes the supplied `onClick` prop _and_ runs your own "handle click" logic: https://github.com/react-bootstrap/react-bootstrap/blob/239580251390cdb8ddeb014d61689a977ef7d3af/src/DropdownItem.js#L86-L93
