### ISSUE TITLE
OverlayTrigger - Property 'rootClose' does not exist on type 'IntrinsicAttributes 

### ISSUE THREAD

**Issue by madushann** [react-bootstrap/react-bootstrap#5083]
We are experiencing a build failure at our Azure build pipeline due to below error. could you please help us to understand the possible issue we are having here.

Error message (build log):
 TypeScript error in /app/EFEnterprise.API.WebApp/Portal/src/components/Shared/NotificationPopover.tsx(15,6):
  Type '{ children: Element; rootClose: boolean; trigger: "click"; key: string; placement: string; overlay: Element; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<OverlayTrigger> & Readonly<OverlayTriggerProps> & Readonly<{ children?: ReactNode; }>'.
    Property 'rootClose' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<OverlayTrigger> & Readonly<OverlayTriggerProps> & Readonly<{ children?: ReactNode; }>'.  TS2322
  
      13 | const NotificationPopover = (props: NotificationPopoverProps) => {
      14 |   return (
    > 15 |     <OverlayTrigger
         |      ^
      16 |       rootClose={true}
      17 |       trigger="click"
      18 |       key="bottom"
  
  
  npm ERR! code ELIFECYCLE
  npm ERR! errno 1
  npm ERR! eformedapi.portal@0.1.0 build: `react-scripts build`
  npm ERR! Exit status 1
  npm ERR! 
  npm ERR! Failed at the eformedapi.portal@0.1.0 build script.
  npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

below it the code:

[NotificationPopover.tsx.txt](https://github.com/react-bootstrap/react-bootstrap/files/4413659/NotificationPopover.tsx.txt)

**Comment by taion** [comment]
works fine for me: https://codesandbox.io/s/serene-taussig-pwvk6

please share a repro in a sandbox/&c. if you're still seeing problems
