### ISSUE TITLE
The `Tab` component is not meant to be rendered!

### ISSUE THREAD

**Issue by mhlmhl** [react-bootstrap/react-bootstrap#5088]
When using 
```
<Tabs>
  <Tab>
  </Tab>
</Tabs>
```
I get this in the browser console:

> Uncaught Error: ReactBootstrap: The `Tab` component is not meant to be rendered! It's an abstract component that is only valid as a direct Child of the `Tabs` Component. For custom tabs components use TabPane and TabsContainer directly

I created an implementation directly based on the documented example at https://react-bootstrap.github.io/components/tabs/#tabs-no-animation.  I get the error shown above.

## Expected behavior

I expect that it should work as documented. The console error message clearly contradicts the example in the official documentation.

(Bitterly: I have been struggling with react-bootstrap for hours now.  I find that the documentation is inadequate and often just plain wrong.)

## Environment (please complete the following information)

- Operating System: Windows 10
- Browser, Version Chrome  80.0.3987.149 (Official Build) (64-bit)
- React-Bootstrap Version 1.0.0

**Comment by taion** [comment]
Do you have a repro that demonstrates this? You can see that it works in our examples, so it's likely something particular to your setup.
