### ISSUE TITLE
Nav not rendered correctly in ParcelJs build: NavbarContext is removed by Nav.Collapse

### ISSUE THREAD

**Issue by mdenburger** [react-bootstrap/react-bootstrap#5089]
## Describe the bug

The `Nav` component is not rendered correctly in the dist output of a [ParcelJs](https://parceljs.org/) project.

## To Reproduce

1. Create a ParcelJs project with React, as described at https://blog.jakoblind.no/react-parcel/. 
2. Create the following `App.jsx`:

```
import React from "react";
import Nav from "react-bootstrap/Nav";
import Navbar from "react-bootstrap/Navbar";
import NavbarContext from "react-bootstrap/NavbarContext";

const App = () => (
  <Navbar bg="primary">
    <Navbar.Toggle />
    <NavbarContext.Consumer>
      {value => console.log("NavbarContext outside Collapse", value)}
    </NavbarContext.Consumer>
    <Navbar.Collapse>
      <NavbarContext.Consumer>
        {value => console.log("NavbarContext inside Collapse", value)}
      </NavbarContext.Consumer>
      <Nav>
        <Nav.Link href="/foo">
          Foo
        </Nav.Link>
        <Nav.Link href="/bar">
          Bar
        </Nav.Link>
      </Nav>
    </Navbar.Collapse>
  </Navbar>
);

export default App;
```

## Reproducible Example

I pushed a minimal ParcelJs project to demonstrate the behavior. Build steps:

    git clone https://github.com/mdenburger/react-bootstrap-nav-issue
    cd react-bootstrap-nav-issue
    yarn build

And open `dist/index.html` in a browser.

## Expected behavior

The navbar should render correctly, but it doesn't: the example links Foo and Bar are not visible because the CSS classes of div rendered by the `Nav` component are not correct.
- Expected: class `navbar-nav`
- Actual: class `nav` 

Cause: the `Nav` component cannot find the `NavbarContext`. It seems that the `Nav.Collapse` component somehow sets the context to `null`, as demonstrated by the `console.log` statements. Outside `Nav.Collapse` the context is correct, but inside `Nav.Collapse` it's null. As a result, the `Nav` component does not realize it's inside a navbar, and does not render the right classes.

Everything does work correctly in ParcelJs' development server (started with `yarn dev` in the example repo). So it seems to be the result of ParcelJs' bundling. Yet I haven't seen this behavior in any other usages of the Context API in my ParcelJs project.

## Environment

- Operating System: Ubuntu
- Browser: Chrome 80
- React-Bootstrap Version: 1.0.0

**Comment by kosmiq** [comment]
Could be related to #5086 ?

**Comment by mdenburger** [comment]
Thanks for the link. It's indeed caused by ParcelJs issue [#3523](https://github.com/parcel-bundler/parcel/issues/3523). The files `esm/AccordionContext.js`, `esm/CardContext.js` and `esm/NavbarContext.js` are identical. Hence ParcelJs 1.x collapses them, which messes up the references. AFAICS there's no solution yet.

**Comment by kosmiq** [comment]
You could try https://github.com/react-bootstrap/react-bootstrap/issues/5086#issuecomment-608418798

**Comment by jquense** [comment]
Let's add a comment to these files to force Parcel to seem them as different? Would that work? anyone want to send a PR?

**Comment by kosmiq** [comment]
I did a test here. Unfortunately adding a (different) comment in each file is not enough. Adding a `const` does solve the issue though.

This does not work:
```
CardContext.js
import React from 'react';

// CardContext fix for https://github.com/parcel-bundler/parcel/issues/3523
export default React.createContext(null);

AccordionContext.js
import React from 'react';

// AccordionContext fix for https://github.com/parcel-bundler/parcel/issues/3523
export default React.createContext(null);

NavbarContext.js
import React from 'react';

// NavbarContext fix for https://github.com/parcel-bundler/parcel/issues/3523
export default React.createContext(null);
```

But this does work, I'm not gonna PR this though :)
```
CardContext.js
import React from 'react';

const CardContextVar = '';
export default React.createContext(null);

AccordionContext.js
import React from 'react';

const AccordionContextVar = '';
export default React.createContext(null);

NavbarContext.js
import React from 'react';

const NavbarContextVar = '';
export default React.createContext(null);
```

**Comment by jquense** [comment]
I wonder if the issue with the comment is the minifier or compiler removing them...maybe we need to use an important `/*! */` comment?

**Comment by jonsa** [comment]
@kosmiq 
Would be possible to make a PR with the following change? It seems to fix the problem for me.
```js
import React from 'react';
const context = React.createContext(null);
context.displayName = 'AccordionContext';
export default context;
```
```js
import React from 'react';
const context = React.createContext(null);
context.displayName = 'CardContext';
export default context
```
```js
import React from 'react';
const context = React.createContext(null);
context.displayName = 'NavbarContext';
export default context;
```

**Comment by jquense** [comment]
yeah lets do it
