### ISSUE TITLE
NavDropdown import documentation

### ISSUE THREAD

**Issue by lopezdp** [react-bootstrap/react-bootstrap#5090]
The documentation at this page for `NavDropdown` says to use an incorrect import statement on this page: 

https://react-bootstrap.github.io/components/navs/

The incorrect import statement shown is `import Nav from 'react-bootstrap/Nav'`

The correct import statement should be:

`import NavDropdown from "react-bootstrap/NavDropdown";`

**Comment by taion** [comment]
Ah, I see we got rid of `<Nav.Dropdown>`. I'd be happy to take a PR to fix this.

**Comment by kosmiq** [comment]
Pr merged. Closing this.
