### ISSUE TITLE
Documentation for older versions (1.0.0-beta.9)

### ISSUE THREAD

**Issue by overide** [react-bootstrap/react-bootstrap#5092]
Hi All,

I'm using version **1.0.0-beta.9** and was trying this example https://react-bootstrap.github.io/components/overlays/#overlays-container but I'm getting errors. I'm not sure of the correct usage of Popover wrt beta.9, so I want beta.9 documentation to figure it out. Where can I find it?

Thanks

**Comment by kosmiq** [comment]
You could clone to desktop and cehckout to the appropriate tag (beta-9 in this case) and run the docs locally.
