### ISSUE TITLE
NavDropdown Component - Add a title to tag a on navdropdown

### ISSUE THREAD

**Issue by darrylsepeda** [react-bootstrap/react-bootstrap#5094]
## Describe the bug
I found that tag a inside navdropdown doesn't have title attribute.
It's better to have control over what title we want to use on that tag a, I know any additional props will be passed down, but current prop title is being used for labeling the menu.

## To Reproduce
Inspect element to any navdropdown component, you will see the tag a doesn't have title attribute at all.

## Expected behavior
Better to add a prop for NavDropdown component to control what title do we want to use in that tag a.
Current prop title on NavDropdown is not pass to the tag a.

## Screenshot
![image](https://user-images.githubusercontent.com/5493333/78501897-3ebc3200-7788-11ea-8d56-5798b659676e.png)

**Comment by taion** [comment]
see https://github.com/react-bootstrap/react-bootstrap/issues/2104 – `<NavDropdown>` doesn't really do anything special. It's just a convenience class for rendering a `<Dropdown>` with a toggle that's a `<NavLink>`. Just use the lower-level components.
