### ISSUE TITLE
In document, script tag can't be self close.

### ISSUE THREAD

**Issue by heroboy** [react-bootstrap/react-bootstrap#5097]
## Describe the bug

1.  `<script>` tag can't be self close'

## To Reproduce

open https://react-bootstrap.github.io/getting-started/introduction/#browser-globals

## Reproducible Example

nothing

## Expected behavior
should be
```
<script src="xxx.js"></script>
```

## Screenshots

nothing

## Environment (please complete the following information)

nothing

## Additional context

nothing

**Comment by taion** [comment]
We'd be happy to take a PR to fix the example.

**Comment by armonkahil** [comment]
I'd be happy to take it.

**Comment by kosmiq** [comment]
Fixed by #5101
