### ISSUE TITLE
The value of a select form can't be changed with ref after a defaultValue is set 

### ISSUE THREAD

**Issue by SKKurz** [react-bootstrap/react-bootstrap#5099]
## Describe the bug

When using `<Form.Control as="select" ...>` with a default value and trying to use the  `ref` to change the value, it doesn't update/change the value 

## To Reproduce

1. Create a react-bootstrap select-form with some options. Give it a default value and a ref to change the value later.
2. Create a react- bootstrap text-field with default value + the same ref as for the select-form
3. Use the ref to create a function which changes the value of the select form and the textfield.
4. Assign the function to a button or a textfield + button if you want to change the value constantly 
5. The value of the select form won't change, but the value of the textfield changes.

## Reproducible Example

I would love to give a code sandbox-example, but it seems like it doesn't want to take my repository :( 

So here is my [repository for testing the bug](https://github.com/SKKurz/rb-select-form-test).

Here is also the code from the App.js if it makes reproducing easier
```react
import React from 'react';
import {Form, Button} from 'react-bootstrap';

class App extends React.Component {
  choice = ['1','2','3'];

  constructor(props) {
    super(props);
    this.setValue = null
    this.state = {
      value: this.choice[0],
    };
  }

  nextChoice = () => {
    const choice_now = this.choice.indexOf(this.state.value);
    const choice_next = this.choice[(choice_now+1) % this.choice.length];
    this.setState({value: choice_next});
    this.setValue.value = this.state.value;
    console.log('Button pressed: Value', this.state.value);
  };

  render() {
    return (
      <div>
      <Button onClick={this.nextChoice}>Next Choice</Button>
      <SelectTest value = {this.state.value} Ref={e => {this.setValue = e}}/>
      </div>
    );
  }
}

const SelectTest = (props) =>{
  return(
    <Form>
        <Form.Group controlId="testSelect">
          <Form.Label>Test Select</Form.Label>
          <Form.Control 
          as="select"
          defaultValue={props.value}
          ref={props.Ref}
          >
            <option value='1'>1</option>
            <option value='2'>2</option>
            <option value='3'>3</option>
          </Form.Control>
        </Form.Group>
        <Form.Group controlId="choiceDisplay">
          <Form.Label>Current Choice</Form.Label>
          <Form.Control
          type="text"
          defaultValue={props.value}
          ref={props.Ref}
          readOnly
          >
          </Form.Control>
        </Form.Group>
      </Form>
  )
};


export default App;
```

## Expected behavior

The value should change even if the defaultValue is set - like the text input 
## Environment (please complete the following information)

- Operating System: MacOS 10.15.4
- Browser, Version: Safari 13.1
- React-Bootstrap Version 1.0.0

**Comment by taion** [comment]
Is this any different if you use a normal `<select>`?

**Comment by SKKurz** [comment]
Well... probably not. At least I can't get it to work. But I can't get the text input to change with normal `<input>` either.

**Comment by taion** [comment]
Sure – in this case, you probably want to use a controlled component, then. If it doesn't work there, it's not supposed to work in R-B.
