### ISSUE TITLE
Implement  ScrollSpy

### ISSUE THREAD

**Issue by stevoland** [react-bootstrap/react-bootstrap#51]
Not sure how this should be implemented so here's some thinking out loud.

Could be a component that takes one or more `Nav`s as children and a `target` CSS selector prop:

```
<ScrollSpy target="body">
    <Nav>
        <NavItem href="#1" key={1}>Item 1</NavItem>
        <NavItem href="#2" key={2}>Item 2</NavItem>
    </Nav>
</ScrollSpy>
```

This would recurse through the nav props finding hrefs, work out which is the closest to the current scroll position then pass `activeHref` prop to `cloneWithProps` nav.

`ScrollSpy` could also be controlled with a `onScrollToItem(href)` callback prop.

Actually this could be built straight into `Nav`: `<Nav scrollTarget="body">...</Nav>`.

Any thoughts?

**Comment by darkyen** [comment]
Is this still under work ?

**Comment by mtscout6** [comment]
We have not started anything on this, if you're up for a PR that adheres to @pieterv's original concept we'd love to have it.

**Comment by AlexKVal** [comment]
Pull requests are welcome :wink:

**Comment by taion** [comment]
I'd really rather not add this to R-B. It seems like you can roll something like this yourself w/e.g. react-waypoint and a top-level context thing.

It seems way to opinionated to make sense here. It's complicated, narrow, and isn't really an encapsulated component.

Are we okay with just not doing this?

**Comment by jquense** [comment]
I am ok with not doing it. Though we should add some documentation to _why_ we aren't in the docs, not that anyone has ever asked for this in recent history

**Comment by anandjaisy** [comment]
> Couple of additional thoughts,
> 
> The current `Nav` component already has the ability to select `NavItem`'s based on a `activeKey` value, but will probably need some modifications to support nested `Nav`'s and the basic nav style.
> 
> The `target` value might be safer to default it to `document.body` then allow DOM elements or React components to be passed through.
> 
> I like the idea of `ScrollSpy` component being split out from the `Nav`.
> 
> I wonder if the sections picked up by the `ScrollSpy` should be react components as well rather than just a div with an `id`, this would allow us to more easily setup a list of elements who's position should be checked on scroll. Something like:
> 
> ```js
> <ScrollSpyNav>
>   <NavItem key="btn">
>     Buttons
>     <Nav>
>       <NavItem key="btn-groups">Button groups</NavItem>
>       <NavItem key="btn-dropdowns">Button dropdowns</NavItem>
>     </Nav>
>   </NavItem>
>   <NavItem key="panels">Panels</NavItem>
> </ScrollSpyNav>
> 
> <ScrollSpySection key="btn">
>   <h2>Buttons!</h2>
>   <p>...</p>
> 
>   <ScrollSpySection key="btn-groups">
>     <h3>Buttons!</h3>
>     <p>...</p>
>   </ScrollSpySection>
>   <ScrollSpySection key="btn-dropdowns">
>     <h3>Buttons!</h3>
>     <p>...</p>
>   </ScrollSpySection>
> </ScrollSpySection>
> 
> <ScrollSpySection key="panels">
>   <h2>Panels!</h2>
>   <p>...</p>
> </ScrollSpySection>
> ```
> 
> I would imagine the `ScrollSpySection` and `ScrollSpyNav` components in the previous example would register with a scroll watcher singleton that actually checks what section is active and scrolls to sections if requested, the singleton will save us from running the same calculations multiple times if multiple `ScrollSpyNav`'s are used. It would be nice as well if the `ScrollSpySection` components could be notified if they are the active section, would be useful to know so you could activate animations or change styles based on this. This will probably require using a `ScrollSpySectionMixin` though to get access to the state.

`Attempted import error: 'ScrollSpySection' is not exported from 'react-bootstrap'.`

How did you import scroolSpySection
