### ISSUE TITLE
Why can't I call a function on the Samples.js file?

### ISSUE THREAD

**Issue by andrerpena** [react-bootstrap/react-bootstrap#510]
Hi all.

When I first saw [the Samples.js file](https://github.com/react-bootstrap/react-bootstrap/blob/master/docs/src/Samples.js) I thought: Why didn't they just export a `load` function like this:

    export default {
        load: function(exampleFileName) { ... }
    }

That would make things really easier because I wouldn't need to mess up with `Samples.js` if I wanted to create another sample.

Then I realized the reason you didn't do it is because file is used in runtime and you don't have `readFileSync` at run time. That is, you need an object filled with strings to be sent to the client.

Fine.

My next thought was: Why didn't they at least encapsulated the `load` function? They wouldn't need to call that `readFileSync` method everytime. Why didn't they do something like this:

    function load(file) { 
          return require('fs').readFileSync(__dirname + '/../examples/' + file, 'utf8')
    };
    export default {
          EditorsTextBoxBasicUsage: load('/../examples/EditorsTextBoxBasicUsage.js'),
    };

Then I did.

The result was very odd, and that's exactly why I'm asking this question.

If I do something like this:

    export default {
          EditorsTextBoxBasicUsage: require('fs').readFileSync(__dirname +   '/../examples/EditorsTextBoxBasicUsage.js', 'utf8'),
    };

Everything works fine and `require('fs').readFileSync` is correctly evaluated to a string in server-side... But If I create a `load` function and run it, the load function is sent to the browser and it crashes saying that `fs` cannot be loaded.

    function load(file) { 
          return require('fs').readFileSync(__dirname + '/../examples/' + file, 'utf8')
    };
    export default {
          EditorsTextBoxBasicUsage: load('/../examples/EditorsTextBoxBasicUsage.js'),
    };

So, can someone explain me why `require('fs').readFileSync` is evaluated in serverside but my `load` is not?

Thanks.

**Comment by mtscout6** [comment]
Webpack is using brfs from the browserify community to replace each `fs.readFileSync` call with the contents of the file referenced. There are ways to do this with Webpack directly that I haven't been able to address yet.

**Comment by andrerpena** [comment]
Thanks for the reply @mtscout6. I'm sorry to keep asking questions. Is there any configuration on react-bootstrap that makes Webpack to replace `fs.readFileSync` or is it out of the box?

**Comment by mtscout6** [comment]
No worries, you've had some good questions lately. The webpack configuration responsible for this is: https://github.com/react-bootstrap/react-bootstrap/blob/v0.20.3/webpack/strategies/docs.js#L37. Although the long term goal that I'd like to eventually adopt is with the webpack raw-loader as mentioned in the webpack docs: http://webpack.github.io/docs/loaders.html#loaders-by-config.

**Comment by andrerpena** [comment]
@mtscout6 I really appreciate your help. Thank you.

**Comment by mtscout6** [comment]
No problem!

**Comment by mtscout6** [comment]
No problem anytime.
