### ISSUE TITLE
Modal Animation wont allow input to auto focus

### ISSUE THREAD

**Issue by sirajtahrawashmen** [react-bootstrap/react-bootstrap#5102]
## Describe the bug

If you have any input with autoFocus property inside a Modal, the input wont be auto focused when the Modal is set to be shown, unless you set the Modal property `animation={false}` 

## Reproducible Example

```    
<Modal
      ref={ModalRef}
      show={isSearchModalOpen}
      onHide={handleClose}
      centered
      animation={false}
    >
      <Modal.Header closeButton>
        <Modal.Title>Quick Search</Modal.Title>
      </Modal.Header>
      <Modal.Body>
        <Form>
          <Form.Group controlId="searchValue">
            <Form.Control
              type="text"
              placeholder="Search..."
              ref={inputRef}
              autoFocus
            />
          </Form.Group>
          <Button variant="primary" type="submit">
            <i className="fa fa-search"></i>
          </Button>
        </Form>
      </Modal.Body>
</Modal>
```

## Expected behavior
Autofocus should work on Inputs even if the animation is set to true on the Modal component

## Environment 
- Operating System: macOS
- Browser, Version Chrome 74
- React-Bootstrap Version 1.0.0

## Additional context

you can manually focus the input using the `onEntered` prop, but there shouldn't be a need to

**Comment by taion** [comment]
Right... looks like this broke at some point. Not sure when. It'd be a bug in https://github.com/react-bootstrap/react-overlays/blob/d0cdd9d5204ef0eaadaca8d616fa2ebd5449f4c1/src/Modal.js#L381-L390, which is supposed to handle this.

**Comment by shaungc-su** [comment]
Experiencing this issue as well, I see people suggesting using `useRef` to grab the input element and call `focus()` on it in `onEnter` prop callback, but feel it bit of an overhead doing that just to achieve auto focus.

> This also works correctly with any Modal children that have the `autoFocus` prop

Looking at the comment of Modal component, looks like `autoFocus` prop on Modal should work well with `autoFocus` on children input components.

I'm guessing perhaps after `show` changed and `this.onShow()` called, at the time of Modal children (and inputs) get mounted, the animation transition hasn't finished yet, so even if autoFocus worked on inputs when they get mounted on Modal, the completion of animation somehow override the focus. But I have to say I'm not familiar with how `react-transition-group` interact with `Modal` here, so I'm not sure if it's an ordering issue.

**Comment by omgoshjosh** [comment]
this appears to be busted for me on react-bootstrap ^0.33.1

**Comment by zgetro** [comment]
for those, who use thirdparty components like [react-power-select](https://github.com/selvagsz/react-power-select) or **N numbers** of hierarchy components in used in model and autofocus is not working on those componet and don't wanted to givup on [react-bootstrap](https://www.npmjs.com/package/react-bootstrap)

you need set `enforceFocus` to `false`. this will fix autofoucs of your component as you expected.

```js
<Modal 
        enforceFocus={false}
``` 

in my case, react-power-select has seachbox to typeahed your Options. user could not able to focus on searchbox. 
some how latest update of model is forcing model to foucs and that is not working for me, 
happy codeing 🙌

**Comment by Thomas-Boi** [comment]
Thank you so much @zgetro . I was trying to render an Overlay with an input inside a Modal. Since the Overlay is added outside the Modal, I couldn't use the input inside. Every click would lose focus right away and so I cannot type. This solution works well
