### ISSUE TITLE
Form.File multiple file upload?

### ISSUE THREAD

**Issue by altwarg** [react-bootstrap/react-bootstrap#5107]
Can anyone explain how to download multiple files from Form.File?
At the moment I can only select 1 file

This aspect is not even mentioned in the  [documentation](https://react-bootstrap.github.io/components/forms/#form-file-props).

**Comment by taion** [comment]
the file input is just a thin wrapper around a normal `<input type="file">`. you'd handle it the same way as there – probably with the `multiple` prop

**Comment by nick4fake** [comment]
There is no "multiple" property in typescript definition
