### ISSUE TITLE
Tooltips with position auto are placed on top of the element

### ISSUE THREAD

**Issue by kosmiq** [react-bootstrap/react-bootstrap#5111]
## Describe the bug

It seems as if tooltips that uses `placement="auto"` are no longer working since popperjs2 upgrade in react-overlays.

There seems to be other issues as well with placements of tooltips. Look at the linked example on the buttons and the headers. :(

## To Reproduce

1. Create a button
2. Wrap it in an overlaytrigger with placement auto
3. Tooltip is rendered inside the button

## Reproducible Example

Example: https://codesandbox.io/s/bold-chaum-4xhmr?file=/src/App.js

## Expected behavior

That tooltips works as in beta 17.

## Screenshots

v1.0.0
![Screenshot 2020-04-14 at 11 50 29](https://user-images.githubusercontent.com/322759/79211205-39c14780-7e46-11ea-89e5-394ac39e17fc.png)
![Screenshot 2020-04-14 at 11 50 34](https://user-images.githubusercontent.com/322759/79211209-3c23a180-7e46-11ea-95e6-662375805b55.png)

beta17
![Screenshot 2020-04-14 at 11 50 47](https://user-images.githubusercontent.com/322759/79211246-4cd41780-7e46-11ea-8d3e-4085f37aa960.png)
![Screenshot 2020-04-14 at 11 50 49](https://user-images.githubusercontent.com/322759/79211254-4fcf0800-7e46-11ea-8e47-c54ad31c2cd3.png)

**Comment by kosmiq** [comment]
@jquense @taion should we revert to PopperJS 1.x?

**Comment by jquense** [comment]
This is less a bug and more a configuration difference i think. the `auto` placement _requires_ the `flip` modifier to be enabled. maybe we should should automatically default it to true when auto placements are picked

**Comment by kosmiq** [comment]
That would probably be a good idea. We should otherwise mention in the docs that `flip` is required when using `placement=auto`
