### ISSUE TITLE
Setting popperConfig on Dropdown Menu has no effect

### ISSUE THREAD

**Issue by BrianDV** [react-bootstrap/react-bootstrap#5115]
## Describe the bug

When adding a `popperConfig` property to the `Dropdown.Menu` component the configurations are not visible on the rendered element.

## To Reproduce

1. `npx create-react-app sandbox`
2. `yarn add react-bootstrap@1.0.0`
3. Use a `Dropdown.Menu` component and set the `popperConfig` property

## Reproducible Example

Working example can be viewed on [CodeSandbox](https://codesandbox.io/s/restless-dust-sg0em?fontsize=14&hidenavigation=1&theme=dark).

## Expected behavior

`Dropdown.Menu` applies the configuration set by the `popperConfig` property.

## Screenshots

![popperConfig](https://user-images.githubusercontent.com/1468439/79297945-7f0c6600-7e94-11ea-9334-835e042fdcda.jpg)

## Environment (please complete the following information)

- Windows 10 / macOS 10.15
- Chrome Version 80.0.3987.163 (Official Build) (64-bit)
- React-Bootstrap 1.0.0

**Comment by taion** [comment]
It looks like the CJS Popper bundle in React-Overlays doesn't include the `offset` modifier. Should it? @jquense

**Comment by kosmiq** [comment]
We should probably include all modifiers since we are referencing popper config object in docs. Or clarify which ones can be used.

**Comment by jquense** [comment]
I don't think we should add them, we don't use them. If users want to use them they should add them themselves. I agree we should document that that tho

**Comment by BrianDV** [comment]
As it stands currently the default Dropdown.Menu implementation throws a warning in the console (based on the margin added to .dropdown-menu). Using offset was my way of circumventing the warning and removing the margin as per the console statement.

My current workaround is to remove the default .dropdown-menu margin-top and override the popper computed CSS with an `!important` flag. Not ideal, but it works.

**Comment by kosmiq** [comment]
@BrianDV the warning is fixed in this PR: https://github.com/react-bootstrap/react-bootstrap/pull/5112

not released in a version yet though, but thought you should know :)

**Comment by BrianDV** [comment]
> @BrianDV the warning is fixed in this PR: #5112
> 
> not released in a version yet though, but thought you should know :)

Awesome thanks!

**Comment by kit-scalyr** [comment]
Hello, I am getting this error. Is this related?
![image](https://user-images.githubusercontent.com/42550263/79956262-c2d31280-8434-11ea-86c2-18fb29e90b8a.png)

I am passing this config to the Overlay component
```
  const popperConfig = {
    modifiers: {
      offset: {
        enabled: true,
        offset: '0, 9px'
      }
    }
  };
```

Will #512 fix the error?

**Comment by jquense** [comment]
Upstream now includes the offset modifier, not sure when that happened...

@kit-scalyr no that won't work, the format for modifiers is wrong, it needs to be an array, check the popper v2 documentation

**Comment by kosmiq** [comment]
This issue is solved since version 1.0.1. Closing.

**Comment by pngo-makershub** [comment]
I'm trying to do exactly this. I'm using version 1.6.1 and offset modifier does not offset the dropdown menu. Could you please elaborate on how this issue was resolved?

**Comment by korydondzila** [comment]
If anyone is still having an issue with this try flipping the numbers in your offset.
Popper uses the concept of skidding and distance, rather than x and y.

https://popper.js.org/docs/v2/modifiers/offset/#offset-1
