### ISSUE TITLE
HelpBlock Component from react-bootstrap 0.30.7 has been removed in latest version 1.0.0. 

### ISSUE THREAD

**Issue by Gayathri91** [react-bootstrap/react-bootstrap#5117]
What is the equivalent component of HelpBlock in latest version

**Comment by Gayathri91** [comment]
HelpBlock Component from react-bootstrap 0.30.7 has been removed in latest version 1.0.0.
What is the equivalent component in latest version?

**Comment by taion** [comment]
See the Bootstrap v4 migration guide.

**Comment by taion** [comment]
https://getbootstrap.com/docs/4.0/migration/
