### ISSUE TITLE
Use html tag in the label of the checkbox

### ISSUE THREAD

**Issue by NimaKaviyani** [react-bootstrap/react-bootstrap#5118]
Is it possible to use HTML tags in the label of the checkbox?

example:
```html
<div class="form-group form-check">
    <input
        type="checkbox"
        class="form-check-input"
        id="exampleCheck"
    />
    <label
        class="form-check-label"
        for="exampleCheck"
    >I agree to the <a href="/terms-of-service">terms of service</a></label>
</div>
```

**Comment by taion** [comment]
As long as you're following the nesting rules, you can put whatever you want there.

**Comment by NimaKaviyani** [comment]
@taion I put the html tag but displayed as text.
It doesn't matter, I use Bootstrap itself.

![image](https://user-images.githubusercontent.com/32512803/79503819-0d284e00-8047-11ea-957f-6aea80e9c481.png)

**Comment by jquense** [comment]
You are probably writing it as a string not a jsx element. Post an example of the problem using the issue template and folks can troubleshoot more

**Comment by TyIsI** [comment]
In case anyone finds this and is wondering. The correct ways to do this is:

```
<Form.Check type="checkbox" label={(<><b>Important bold text:</b>&nbsp;<i>Read more at <a href="https://example.com/more">link title</a></i></>)} />
```

Per OP's example:
```
<div class="form-group form-check">
    <input
        type="checkbox"
        class="form-check-input"
        id="exampleCheck"
    />
    <label
        class="form-check-label"
        for="exampleCheck"
    >(<>I agree to the <a href="/terms-of-service">terms of service</a></>)</label>
</div>
```
