### ISSUE TITLE
Dropdown item on hover not rendered properly in Chromium-based browsers.

### ISSUE THREAD

**Issue by kherge** [react-bootstrap/react-bootstrap#5119]
## Describe the bug

When hovering over an item in a dropdown menu, the background of the item overlaps with the border of the menu. Which side overlaps depends on menu alignment (e.g. `alignRight`).

## To Reproduce

1. Go to https://react-bootstrap.github.io/
2. Click on version dropdown menu.
3. Hover over any item in the menu.
4. Observe the right side of the hovered item.

## Reproducible Example

https://codesandbox.io/s/icy-violet-2mtsp

## Expected behavior

<img width="230" alt="expected" src="https://user-images.githubusercontent.com/9122157/79578122-a6248c80-807a-11ea-8c92-a646f2e6c06e.png">

## Screenshots

<img width="246" alt="actual" src="https://user-images.githubusercontent.com/9122157/79578140-aa50aa00-807a-11ea-8596-54b0d50111d4.png">

## Environment

- Windows 10
- Chrome 81
- Edge 81
- React-Bootstrap 1.0.0

**Comment by taion** [comment]
huh, this is what i'm seeing on chrome 81 on mac:

![image](https://user-images.githubusercontent.com/3112159/79602594-c5420f00-80b8-11ea-99c1-efb304dd38a8.png)

is this windows-specific?

**Comment by kherge** [comment]
I can confirm that I **_do not_** see this behavior on the macOS version of Chrome.

This does appear to be Windows specific.

**Comment by mxschmitt** [comment]
I tried on Chrome, Edge on Windows via Browserstack as well via Chrome and Edge on MacOS. Since I cant reproduce it via that, I would guess that this is either a rendering bug in the browser or a upstream issue on Bootstrap itself.

**Comment by jquense** [comment]
I have seen this sort of visual glitch recently as well, tho not with RB components. My hunch is that it's a newish Chrome bug

**Comment by kosmiq** [comment]
I have seen similar bugs with Bootstrap if you have a few specific things going on, namely:
- Scaling set in Windows for a high resolution screen. Like using a 4k screen on windows with 150 % scaling for readability on your desktop etc
- On top of this setting a negative scaling in your browser as well causing all kinds of havoc with pixels being rounded in strange ways (i.e. 1px not being whole or half pixels but rather 0.7335554 px or similar strange things)
- The negative scaling in the browser used to "fix" the large websites the users experiences after scaling everything in windows.

I've seen it causing borders on outline buttons being invisible on one side and other weirder trings.

Are you using and windows and/or browser scaling?

**Comment by taion** [comment]
Is this happening with upstream Bootstrap, or is it only with React-Bootstrap?

**Comment by kherge** [comment]
@kosmiq, you nailed it. I am using 4K with 150% scaling.

- The issue disappears if I set scaling to 100%.
- The issue also appears upstream on Bootstrap's own website.

Given that this issue is only happening during scaling, this may be a bug in Chromium ([related bug?](https://bugs.chromium.org/p/chromium/issues/detail?id=1014467)). Since this issue does not appear to be specific to this project, I feel that it can be closed.
