### ISSUE TITLE
Issue importing File component

### ISSUE THREAD

**Issue by NimaKaviyani** [react-bootstrap/react-bootstrap#5121]
I saw some issues in using the file component:

When I import use component like this:

```javascrpt
import {Form} from "react-bootstrap";
```
```javascrpt
<Form.File 
    id="custom-file"
    label="Custom file input"
    custom
/>
```
I get the following error:

> Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

When I import use component like this:
```javascrpt
import {FormFile} from "react-bootstrap";
```
```javascrpt
<FormFile 
    id="custom-file"
    label="Custom file input"
    custom
/>
```
I get the following error:
>Attempted import error: 'FormFile' is not exported from 'react-bootstrap'.

But when is user this import:
```javascrpt
import FormFile from "react-bootstrap/FormFile";
```
The component works well.

**react-bootstrap:** 1.0.0;
**next:** 9.2.2

**Comment by mxschmitt** [comment]
Try `Form.File` like shown here: https://react-bootstrap.netlify.app/components/forms/#forms-custom-file

**Comment by NimaKaviyani** [comment]
> Try `Form.File` like shown here: https://react-bootstrap.netlify.app/components/forms/#forms-custom-file
> 
> ```
> import { Form } from 'react-bootstrap';
> ```

It's not work for me:

![image](https://user-images.githubusercontent.com/32512803/79689509-9b304e80-826a-11ea-851c-538f59b2ad30.png)

**Comment by mxschmitt** [comment]
Strange, since its working in this codesandbox example: https://codesandbox.io/s/thirsty-merkle-5ld2g?file=/src/App.js

**Comment by NimaKaviyani** [comment]
> Strange, since its working in this codesandbox example: https://codesandbox.io/s/thirsty-merkle-5ld2g?file=/src/App.js

This problem occurred after updating the react-bootstrap.
I deleted the `node_modules` files and reinstalled the modules, and the problem was solved.

Thank you.
