### ISSUE TITLE
Spinner type 'grow' not rendering on iPhone

### ISSUE THREAD

**Issue by JonathanSidego** [react-bootstrap/react-bootstrap#5130]
## Describe the bug

The "grow" spinner animation is not rendering at all. The border type renders as expected.

## To Reproduce

Go to 'https://react-bootstrap.github.io/components/spinners/' on an iPhone

## Reproducible Example

```<Spinner animation="grow" />```

## Environment (please complete the following information)

Safari, iOS 13.4

**Comment by taion** [comment]
This seems to work for me. I'm using Safari on iOS 13.3. There isn't any particular code in React-Bootstrap that drives that animation, though. It's just a CSS class that we pass down.

**Comment by lopezdp** [comment]
Im having the same issue. Here is my implementation:

```
	<Container
		style={{
			display: "flex",
			justifyContent: "center",
			marginTop: "9rem",
			marginBottom: "9rem",
			padding: "18rem",
		}}
	>
		<Spinner animation="grow" />
	</Container>
```

It works on desktop and not on mobile. No error messages. I am checking on safari on iOS

**Comment by kyletsang** [comment]
@lopezdp, update bootstrap to the latest version. This was a bug in their css.
