### ISSUE TITLE
Autofocus on Form.Control in dropdowns example only works the first time

### ISSUE THREAD

**Issue by kosmiq** [react-bootstrap/react-bootstrap#5133]
## Describe the bug

Visit https://react-bootstrap.github.io/components/dropdowns/#custom-dropdown-components
Click the toggle to open the menu. The Form.Control will be focused. Close the menu and open it again, the Form.Control is not autofocused.

## To Reproduce

1. https://react-bootstrap.github.io/components/dropdowns/#custom-dropdown-components
2. Click the toggle to open the menu, the Form.Control will be focused
3. Close the menu
4. Open the menu again, the Form.Control is not focused automatically.

## Reproducible Example

https://react-bootstrap.github.io/components/dropdowns/#custom-dropdown-components

## Expected behavior

Autofocus on all opens, unless this is by design?

## Environment (please complete the following information)

- Operating System: MacOS 10.15.4
- Browser, Chrome 81.0.4044.113
- React-Bootstrap Version 1.0.1

**Comment by jquense** [comment]
Ya, that's just how browser/react's autofocus works, it focuses when the element mounts. This example is more illustrative of what you can do not ideal UX.
