### ISSUE TITLE
Dropdown not closing

### ISSUE THREAD

**Issue by cihanzengin** [react-bootstrap/react-bootstrap#5136]
Hello, i'm using simply navbar example in my project.  Like on demo, dropdown open when click to dropdown item but it's not closing when trying to click anywhere outside of dropdown. So it's not behave like on demo. What can happened here?

```jsx
<Navbar bg="light" expand="lg">
  <Navbar.Brand href="#home">React-Bootstrap</Navbar.Brand>
  <Navbar.Toggle aria-controls="basic-navbar-nav" />
  <Navbar.Collapse id="basic-navbar-nav">
    <Nav className="mr-auto">
        <Nav.Link href="#home">Home</Nav.Link>
      <Nav.Link href="#link">Link</Nav.Link>
      <NavDropdown title="Dropdown" id="basic-nav-dropdown">
        <NavDropdown.Item href="#action/3.1">Action</NavDropdown.Item>
        <NavDropdown.Item href="#action/3.2">Another action</NavDropdown.Item>
        <NavDropdown.Item href="#action/3.3">Something</NavDropdown.Item>
        <NavDropdown.Divider />
        <NavDropdown.Item href="#action/3.4">Separated link</NavDropdown.Item>
      </NavDropdown>
    </Nav>
    <Form inline>
      <FormControl type="text" placeholder="Search" className="mr-sm-2" />
      <Button variant="outline-success">Search</Button>
    </Form>
  </Navbar.Collapse>
</Navbar>
```

**Comment by taion** [comment]
Please provide a runnable repro here. If it works on our site but not on your setup, it's most likely something wrong in your setup.

**Comment by cihanzengin** [comment]
Unfortunately i can't share the repo because it's a private project. I think i imported everything well. Here is problem on my project somewhere but it's not implement issue. Because i create some new react app and implemented there navbar too and everything worked well. I think in my project some other function or anything blocking this but i can't understand what. On developer console doesn't show anything.

**Comment by taion** [comment]
Right, so see if you can get a repro on a CodePen or CodeSandbox

**Comment by xhudaman** [comment]
I'm having the same issue in a project I'm working on.
A working reproduction of the issue can be seen in the codesandbox [here](https://codesandbox.io/s/navbar-collapse-issue-cxjdc).
Hope this helps!

**Comment by smchinna** [comment]
Can you give me the browser details and it's versions, 
Because it's working fine on the Chrome (Version 80.0.3987.122 )
