### ISSUE TITLE
Typings: Form.Switch missing

### ISSUE THREAD

**Issue by jlost** [react-bootstrap/react-bootstrap#5137]
## Describe the bug

In `Forms.d.ts`, `Switch` is missing from the `Form` interface. 

## To Reproduce

1. Use `react-bootstrap` with TypeScript
2. `import Form from "react-bootstrap/Form";`
3. `<Form.Switch ...`
4. Observe that Form.Switch is not found

## Expected behavior

Form.Switch is found by TypeScript

## Environment

Using `1.0.0` but I can see it's still not there in `1.0.1`

**Comment by taion** [comment]
We'd be happy to take a PR to add this.

**Comment by jlost** [comment]
👍 I'll give this a shot when I have a bit of time.

**Comment by jlost** [comment]
Closed by #5139
