### ISSUE TITLE
Overflow hidden on body element doesn't work on mobile when modal is open

### ISSUE THREAD

**Issue by cichyadam** [react-bootstrap/react-bootstrap#5138]
## Describe the bug

When the modal is open actually does not work on mobile devices.  I tested in on documentation website of modal for bootstrap-modal and react-bootstrap-modal - it does ‘work’ when testing in desktop browser, however not on the mobile in real life

## To Reproduce

Open this link in your mobile browser: 
https://react-bootstrap.netlify.app/components/modal/#modals
Open the live demo modal and try to scroll. Overflow hidden on body obviously does not work on mobile.

## Expected behavior

You should not be able to scroll.

## Environment 

- Operating System: iOS
- Browser : Safari, Chrome

**Comment by taion** [comment]
this is just the upstream behavior. nothing we can do about it here.

**Comment by Sathish7111999** [comment]
> this is just the upstream behavior. nothing we can do about it here.

is the same for android as well 
in android mobile when modal is open body should not scroll
but it is not working as expected 
this is in react
