### ISSUE TITLE
Typescript issue: Property 'show' does not exist on Model

### ISSUE THREAD

**Issue by hansanan** [react-bootstrap/react-bootstrap#5140]
## Describe the bug

This issue is not occurring on local environment. It is happening when trying to deploy the project through Azure DevOps pipeline. Couldn't be able to reproduce this in local environment so far. Even running production build on Local didn't reproduce this. I'll express the issue occurred, through following screenshot. 

package.json

`{
  "name": "#######",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "bootstrap": "^v4.3.1",
    "@fortawesome/fontawesome-svg-core": "^1.2.27",
    "@fortawesome/free-solid-svg-icons": "^5.12.1",
    "@fortawesome/react-fontawesome": "^0.1.8",
    "firebase": "^5.8.5",
    "react": "^v16.8.6",
    "react-arrow": "^2.0.4",
    "react-bootstrap": "^1.0.0-beta.16",
    "react-cookie": "^4.0.1",
    "react-copy-to-clipboard": "^5.0.1",
    "react-dom": "^v16.8.6",
    "react-dropzone": "^10.1.6",
    "react-firebaseui": "^3.1.2",
    "react-html-parser": "^2.0.2",
    "react-icons": "^3.7.0",
    "react-image-lightbox": "^5.1.0",
    "react-lazy-hero": "^2.0.0",
    "react-loader-spinner": "^2.3.0",
    "react-router-bootstrap": "^0.25.0",
    "react-router-dom": "^5.0.0",
    "react-scripts": "^3.0.1",
    "react-scroll": "^1.7.12",
    "rimraf": "^2.6.2",
    "styled-components": "^4.2.0",
    "typescript": "^3.4.5",
    "uuid": "^3.3.2"
  },
  "scripts": {
    "analyze": "npm run build && source-map-explorer build/static/js/2.*",
    "start": "rimraf ./build && react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject",
    "lint": "eslint ./src --ext .tsx --ext .js"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "@types/jest": "^24.0.12",
    "@types/node": "^12.0.0",
    "@types/react": "^16.8.17",
    "@types/react-dom": "^16.8.4",
    "@types/react-router": "^5.0.0",
    "@types/react-router-dom": "^4.3.3",
    "@types/styled-components": "^4.1.14",
    "@types/enzyme": "^3.10.3",
    "enzyme": "^3.10.0",
    "enzyme-adapter-react-16": "^1.14.0",
    "eslint": "^6.6.0",
    "eslint-plugin-react": "^7.13.0",
    "jest-enzyme": "^7.1.0",
    "source-map-explorer": "^1.8.0"
  }
}
`

## Screenshots

![image](https://user-images.githubusercontent.com/56594143/80215837-c34cf280-865a-11ea-823a-7644e43517ab.png)

## Environment

- Operating System: ubuntu-16.04
- React-Bootstrap Version: 1.0.0-beta.16

**Comment by taion** [comment]
we can't really do anything about this without a repro

**Comment by hansanan** [comment]
@taion could you please tell me what kind of information needed?
all the usage of react-bootstrap Modal component is throwing above issue when deploying. Only when deploying. 
Local environment deploying or Local production build doesn't throw this error.

**Comment by kosmiq** [comment]
Hmm not sure whats causing this. Would need more info. I'm using react-bootstrap in a .NET project running in Azure with devops build pipelines etc and we are not facing this issue.

**Comment by taion** [comment]
What version of TypeScript are you on? It might be due to https://github.com/react-bootstrap/react-overlays/issues/808.

**Comment by madushann** [comment]
we are using "typescript": "^3.4.5", what is the version we need to reference here, the thing is this was working till we get this issue for long time. this appeared on the given date suddenly. we had the same issue with Popover and had to remove the component to build the project. for now we temporarily replaced the component till we manage resolve this issue.

**Comment by kosmiq** [comment]
I would guess you need to use at least TypeScript 3.5 since that version introduced Omit into TS.

**Comment by madushann** [comment]
Thank you for the information. I hope 3.4 to 3.5 would be a easy update without any breaking changes. 
appreciate you feedback and will get back with the status

**Comment by kyletsang** [comment]
The minimum TS version required is now 3.8 to take advantage of type exports.  This issue is a bit stale, so please reopen if you still run into this issue.
