### ISSUE TITLE
Editing Overlay Styles

### ISSUE THREAD

**Issue by darthzeran** [react-bootstrap/react-bootstrap#5141]
More of a question, but is there a way to override the Overlay Style inline, or with styled-components, or do I have to make a .scss file at src level to edit it?

**Comment by taion** [comment]
You can generally pass in `className` to any of our components to apply your own styles

**Comment by darthzeran** [comment]
so I can only say `className='new-overlay-styles'`, 

and I cannot pass in `style={{color:'red'}}`
nor wrap it in a  styled component?
