### ISSUE TITLE
Error at show property of Modal in tsx file

### ISSUE THREAD

**Issue by ymihir** [react-bootstrap/react-bootstrap#5142]
I am getting error when I try to use show property for `Modal`. I am creating this in my .tsx file with functional component. If I use `Modal.Dialog` it is showing fine on page. 
Below is my package.json screenshot
![image](https://user-images.githubusercontent.com/7568187/80280268-9f27fa80-86c8-11ea-9457-c0f3ef25faad.png)

Below is my modal code:
```
<Modal show={true} size="lg">
        <Modal.Header closeButton>
          <Modal.Title>Modal heading</Modal.Title>
        </Modal.Header>
        <Modal.Body>Woohoo, you're reading this text in a modal!</Modal.Body>
        <Modal.Footer>
          <Button variant="secondary">Close</Button>
          <Button variant="primary">Save Changes</Button>
        </Modal.Footer>
      </Modal>
```
Below error in terminal:
![image](https://user-images.githubusercontent.com/7568187/80280296-d0082f80-86c8-11ea-9c57-0f6af13e8411.png)

**Comment by taion** [comment]
I'm not seeing this on my side. Can you provide a repro that exhibits this problem?

**Comment by ymihir** [comment]
Not sure. In intellisense also I am not getting show property for <Modal>

**Comment by taion** [comment]
We can't do anything about this if we can't get a repro of the error
