### ISSUE TITLE
Carousel flashes on transition

### ISSUE THREAD

**Issue by adstr123** [react-bootstrap/react-bootstrap#5143]
## Describe the bug

I recently upgraded my version in a production site from `1.0.0-beta-14` to `1.0.0` and noticed this bug appearing. I have a fairly standard `<Carousel/>` transitioning between 4 images and at the moment of transition, it flashes jarringly.

Originally I thought it was just present when `fade` prop is set to `true` but on my minimal example below it occurs even without any `fade` prop. When `fade` is on however, I can see **the preceding image immediately disappears (no opacity transition), but the succeeding image does fade in with a smooth opacity change as expected.**

I don't have time to go back through each version to find out when exactly it appeared, sorry. But I have reverted back to beta-14 and the bug is resolved so it was introduced sometime between then and 1.0.0.

## Reproducible Example

Minimal example by using [CodeSandbox](https://codesandbox.io/s/nifty-star-j2z5c?file=/src/App.js).

## Screen Recording
[Gyazo GIF](https://gyazo.com/054fa710e17a72a96b67fbb1cff13afd)

## Environment

- Operating System: MacOS
- Browser: Safari 13.0 & Firefox Developer Edition 76.0b5
- React-Bootstrap Version: 1.0.0

**Comment by kosmiq** [comment]
Your example does not actually transition between 4 images?

if you actually set it up with Carousel.Item etc it works just fine: https://codesandbox.io/s/admiring-leaf-h2u0q?file=/src/App.js

**Comment by ccoulter-eaglemed** [comment]
https://codesandbox.io/s/dry-shape-ee9l1

This is the codesandbox example he probably meant to put in...

**Comment by kyletsang** [comment]
I can see this on default carousel example with `fade=true`

**Comment by ccoulter-eaglemed** [comment]
This is how I fixed it:
`/* Fix for flickering carousel */                                                      
.carousel-inner .carousel-item {
  opacity: 0;
  top: 0;
  left: 0;
  width: 100%;
  display: block;
  position: absolute;
}
.carousel-inner .carousel-item:first-of-type {
  position: relative;
}
.carousel-inner .active {
  opacity: 1;
}
/* End of fix */
`

**Comment by randima-s** [comment]
I had a similar issue with bootstrap 5.0.2 and react-bootstrap 1.6.1. Current item disappears and makes a white space instead of sliding away with the new item.
I noticed that react is applying a .css style ".carousel-item-left" (or ".carousel-item-right") to the carousel item. But such styles were not there in the bootstrap.css file.
I temporary fixed it by adding those styles (and overriding transition time) to my custom .css file.
```
.carousel-item-next{
  transition: transform 0s ease-in-out;
}

.carousel-item-prev{
    transition: transform 0s ease-in-out;
}
.carousel-item-left {
    transform: translateX(-100%);
}
.carousel-item-right {
    transform: translateX(100%);
}
```
However, still a small white gap appears.

Hoping for a better solution.

**Comment by kyletsang** [comment]
@randima-s use react-bootstrap v2 beta for bootstrap 5.  1.6.1 is meant for bootstrap 4 only.

**Comment by Jcase22** [comment]
> @randima-s use react-bootstrap v2 beta for bootstrap 5. 1.6.1 is meant for bootstrap 4 only.

Updating to bootstrap v2 fixed this issue for me

**Comment by FrancoDelCastillo** [comment]
@ccoulter-eaglemed your solution worked for me! although I have the latest react-bootstrap version (^2.1.1)
