### ISSUE TITLE
Is it possible to specify a ReactBootstrap element as PropType?

### ISSUE THREAD

**Issue by igorsantos07** [react-bootstrap/react-bootstrap#5145]
## Describe the bug

I've created a wrapper component to abstract some structure of my project, sample as follows, but I'm not sure how to propType that. Is it even possible? If it's not, maybe this could become a feature request?

## Reproducible Example

```jsx
const Group = ({ children }) => <ListGroup variant="flush">{children}</ListGroup>
Group.propTypes = {
	children: PropTypes.arrayOf(PropTypes.instanceOf(ListGroup.Item)),
}
```
[Minimal example at CodeSandbox](https://codesandbox.io/s/wizardly-breeze-kumiq?file=/src/App.js). Check the console, you'll see there's an error when the propType points to `ListGroup.Item`, but not when it points to the item wrapper.

**Comment by igorsantos07** [comment]
Hmmm React doesn't seem to work this way. Sorry, I needed a full refresh of the page to notice the "working" code was just spitting a different error.

I'd like to know an opinion anyway, as this _seems_ like a valid case, but I'm not sure if I'm just asking too much of PropTypes...

**Comment by jquense** [comment]
You _can_ do this with propTypes with a custom  one, but it's not a great idea. The best you could assert is that the element.type === is a List.Item but it gets tricky checking for a list of elements. The biggest issue tho is that it prevents component composition by type checking like this. If you creat your own ListItem that wraps the base ListItem the proptype would fail but the children would be valid

**Comment by kyletsang** [comment]
Closing as this is answered
