### ISSUE TITLE
Putting Input text in Tabs prevents the space key

### ISSUE THREAD

**Issue by nasriime** [react-bootstrap/react-bootstrap#5146]
Putting Input text in Tabs prevents the space key, How to override this behavior?

![Screenshot from 2020-04-27 14-02-17](https://user-images.githubusercontent.com/19765279/80370334-33908980-8890-11ea-850b-de5dc028b122.png)

**Comment by taion** [comment]
You might be hitting this in `<AbstractNav>`: https://github.com/react-bootstrap/react-bootstrap/blob/bb7419a17ef78c94ce7f810473dc792801e5626a/src/AbstractNav.js#L102

Try adding a `stopPropagation` to keep the event from reaching there?

Alternatively, it might be a matter of ignoring those keydown events if the actual target was an `<input>`. If so, we'd be happy to take a PR fixing that behavior.

**Comment by nasriime** [comment]
Overriding `onKeyDown` method for input with `stopPropagation` works!, Thank you
