### ISSUE TITLE
All-in TypeScript?

### ISSUE THREAD

**Issue by akx** [react-bootstrap/react-bootstrap#5148]
## Is your feature request related to a problem? Please describe

The TypeScript types being not-quite-perfectly-in-sync with the JavaScript implementation is starting to be a little frustrating.

Could we just go all-in and convert the source to TypeScript? I think the strictness benefits would be worth it.

Downstream, there'd still be the esm/plain-JS modules, of course, for plain-JS consumers.

## Describe the solution you'd like

* Convert all .js to .ts
* Inline the types
* Set up the build pipeline(s) to do the Right Things regarding packaging
* Fix All The Bugs! 😄 

## Additional context

If the project leadership is amenable to this, I'm willing to do at least initial legwork to get things going. I'd rather not, though, if such a PR would never pass.

**Comment by jquense** [comment]
I'm up for it. I feel fairly confident we could type the weird `as` props correctly now (well as good as is possible anyway). What do others think?

Also any setup for TS should be consistent with what we did in react-overlays

**Comment by mxschmitt** [comment]
Thats definitely true.
Also thought about that, should be feasible but requires a lot of typing effort. Maybe we can do it in several iterations to just start with allowJS and then go component by component to have a strict type required codebase in the end.

**Comment by taion** [comment]
We should probably add the TS downlevel stuff?

**Comment by jquense** [comment]
isn't that a compilation target thing vs a type thing? Or does it also downlevel the types for iterators and what not?

**Comment by kosmiq** [comment]
This would be awesome IMO.

**Comment by taion** [comment]
well, whatever we're doing for react-overlays is not quite right: see e.g. the use of `Omit` in https://unpkg.com/browse/react-overlays@3.1.3/esm/Overlay.d.ts

**Comment by akx** [comment]
Well, I'll take these comments as a green light to go ahead and try TypeScript conversion :)

**Comment by akx** [comment]
Hmm... What do you think, should PropTypes be left in though? They could be useful for JS developers, but will be extra headache to keep in sync with TS interfaces.

**Comment by akx** [comment]
Okay, now that #5150 was merged into the `typescript` branch, what's the plan ahead? I honestly think we should just merge it into master and deal with the breakage; otherwise it's just not going to get done, I'm afraid.

cc @jquense

**Comment by jquense** [comment]
As much as it's tempting to just run with it we do need to move carefully RB is used by many many people and we need to do our best to try not to break them, or limit our ability to release bug fixes while getting there. 

First required thing is we need to fix the docs site. I'd also like to publish a pre-release so folks can try it out and report what breaks

**Comment by kyletsang** [comment]
I have a bit of time to help out here. What tasks need to be done other than docs?

**Comment by kyletsang** [comment]
Merged in #5251
