### ISSUE TITLE
More tooltip placement options

### ISSUE THREAD

**Issue by gabrielconstantin** [react-bootstrap/react-bootstrap#515]
I found the tooltip in older version boostrap, the one that had the top-left, top-right, etc, placement options really useful. I would love to be able to use that on the React project that I'm working on.

**Comment by mtscout6** [comment]
Looks like Bootstrap 3.x only supports left, right, top, and left. We are seeking parody with Bootstrap, and I don't believe this even works with straight BS3. Perhaps you should create an issue with them?

**Comment by gabrielconstantin** [comment]
:) I bet you meant parity. Those options where really helpful and it's a pity they decided to downgrade the tooltip like that. Thanks for answering though, maybe I will branch someday to add these myself.

**Comment by mtscout6** [comment]
Yes, parity haha. Sorry for the inconvenience.
