### ISSUE TITLE
Switch issues without a label or ID

### ISSUE THREAD

**Issue by igorsantos07** [react-bootstrap/react-bootstrap#5151]
## Describe the bug
The Switch component behaves a little different from the Check in regards to the `label` and `id` attributes. It doesn't render without the label, and can't be toggled without the id. Both cases work fine with the standard checkbox.

## Reproducible Example

[Minimal example](https://codesandbox.io/s/brave-firefly-g2zzn?file=/src/App.js). I even included aria-label to see if that helped, but no. Passing an empty label is enough, but it should behave like the plain checkbox.

This is also noticeable on the doc live blocks.

**Comment by taion** [comment]
That's just how it works upstream.

Do we just need to fix the types?

**Comment by jquense** [comment]
It probably worth noting or warning about in the component? The underlying issue is that unless to link the link the label to input clicking the label has no effect on the underlying (hidden) checkbox. That's just how HTML works, but we could make that clear somewhere

**Comment by igorsantos07** [comment]
I didn't understand the "upstream" until I went to the Boostrap website to look for the said switches. There's so much time I don't go there, I thought the switch was an addition by this library! :scream: 

It does work that way upstream, but it's a tad easier to understand because all HTML elements are well separated... The switch is appended to the label and defined in the wrapper div, not in the input, so if there's no label, there's no button to render. Given we don't need to provide a label element nor define the wrapper div (and at least I don't usually inspect the HTML generated by React), a notice about this known issue on the doc would be helpful, as @jquense mentioned.

Nonetheless, I guess a PropType setting label as required would be helpful? Not sure if React-Bootstrap could go a step further and "fix" it by defaulting the label to an empty string - if it encapsulates the label element, which is required, it could have a better default as well.

**Comment by jquense** [comment]
Lets make the situation better then! Want to craft a PR @igorsantos07 ?

**Comment by igorsantos07** [comment]
I could! Maybe in the next few weeks when I get rid of a second, time-consuming project :) Might be an interesting adventure into TS.

Nonetheless, I would like your guidance on what to do. Not sure about what's the "react-bootstrap way" on this matter - is it opinionated enough to create an empty label or such, for instance?
