### ISSUE TITLE
Docs Typo: 'Ovelay' > 'Overlay'

### ISSUE THREAD

**Issue by a-qxin** [react-bootstrap/react-bootstrap#5155]
## Describe the bug

Typo 'Ovelay' in docs, Components Overlay API table.

## To Reproduce

1. Go to https://react-bootstrap.github.io/components/overlays/
2. Scroll down to API > Overlay > row 'transition' and col description
4. See error 'Ovelay'

## Expected behavior

'Ovelay' > 'Overlay'

## Screenshot

<img width="915" alt="Screen Shot 2020-05-03 at 4 25 33 PM" src="https://user-images.githubusercontent.com/5442091/80928657-c03cbb00-8d5a-11ea-96d2-cc2300b7992c.png">

**Comment by taion** [comment]
We'd be happy to take a PR to fix this.
