### ISSUE TITLE
Components and/or Documentation for Linking/Jumping Within Same Page

### ISSUE THREAD

**Issue by sithys** [react-bootstrap/react-bootstrap#5158]
## Is your feature request related to a problem? Please describe

I cannot find a way to link to sections within the same page. Using

```
<a href="#id">
<div id="id">
```

doesn't seem to work. Using the HashRouter, such a scheme produces a jarring jump to a blank page.

## Describe the solution you'd like

A documented way of jumping around within the same page.

## Describe alternatives you've considered

I cannot use BrowserRouter because it has incorrect behavior when copying/pasting links. A copied link returns 404 unless you use special web servers with special configurations.

## Additional context

My goal is to make a page that behaves somewhat similar to Wikipedia where you can jump to sub-sections lower in the document.

**Comment by taion** [comment]
I think you opened this in the wrong repo.
