### ISSUE TITLE
Missing modal static backdrop animation

### ISSUE THREAD

**Issue by kyletsang** [react-bootstrap/react-bootstrap#5163]
## Describe the bug

There's an animation missing from a modal with static backdrop when trying to click on the backdrop or by pressing escape when `keyboard` is set to `false`.

See Bootstrap docs for a working example of the animation.
https://getbootstrap.com/docs/4.4/components/modal/#static-backdrop

## To Reproduce

1. Create a modal with `backdrop` set to `static`
2. Click the backdrop or press escape
3. Notice there is no animation

## Reproducible Example

https://codesandbox.io/s/cranky-bas-9m1zh?file=/src/App.js

## Expected behavior

Modal should animate.

## Environment (please complete the following information)

- Operating System: Windows
- Browser, Version: Chrome 81.0.4044.129
- React-Bootstrap Version: 1.0.1

**Comment by taion** [comment]
Oh, that's neat. We'd be happy to take a PR to add this.

**Comment by kyletsang** [comment]
I'll take a look at this one.

**Comment by morticella** [comment]
How can I avoid animation on the backdrop?
