### ISSUE TITLE
Add support to Display property

### ISSUE THREAD

**Issue by miltonmc** [react-bootstrap/react-bootstrap#5164]
## Is your feature request related to a problem? Please describe

I found no elegant way to apply the CSS classes `.d-none .d-sm-block`  on a `<Col />` to hide it on a specific resolution,  and it's possible on original Bootstrap: https://getbootstrap.com/docs/4.4/utilities/display/#hiding-elements.

## Describe the solution you'd like

Since display properties can be virtually applied to any HTML tag, I believe a good approach can be create a component `<Display />` to handle the display properties  and inherit other components from it.
```jsx
<Display d={['none', 'sm-block']} tag="div"></Display>

<Col xs={0} sm={5} md={4} d={['none', 'sm-block']}>
  ...
</Col>
``` 

## Describe alternatives you've considered

It works adding and an extra `div` into the `<Col />`:
```jsx
<Col xs={0} sm={5} md={4}>
  <div className="d-none d-sm-block">
    ...
  </div>
</Col>
``` 

## Additional context

N/A

**Comment by taion** [comment]
Just pass the `className` to the `<Col>`.

**Comment by miltonmc** [comment]
@taion your answer solved my problem for now, thanks for that!

But, it seems  a bit inconsistent to me, cause it is what Bootstrap is about, pass classes to some tag. For instance, the component `<Container >`  is just a `<div class="container">.

I thought the goal of this library was create components that allow its user to setup the Bootstrap into an application just by components composition and a well defined set of properties. I believe that would increase code readability and would be more fail proof, because the options could be restricted.

**Comment by taion** [comment]
well, it's hard to say where components start and utilities begin. is `d-none` something to do with `<Col>`, or is it something applicable everywhere?

we'd be happy to take your input on https://github.com/react-bootstrap/react-bootstrap/issues/5152 where we're continuing to discuss this topic

**Comment by ameshkin** [comment]
I am facing the same issue. Do I need to also add bootstrap as well as react-bootstrap?  Or should I just copy the code with d-none into my css files?  There are several things that are missing in react-bootstrap which are causing problems.
