### ISSUE TITLE
React bootstrap tooltip overlay is not positioned correctly

### ISSUE THREAD

**Issue by nspeedzy** [react-bootstrap/react-bootstrap#5166]
## Description

I have been working with overlays. I had created a simple tooltip using react bootstrap's `Tooltip` class. I have created it in such a way that, whenever the mouse hovers over the button, It shows the tooltip and it's content. But when I take a look at the result, The tooltip is not positioned correctly.

## To Reproduce

1. Created a tooltip using the `Tooltip` class
2. Went to the browser to see the result
3. Discovered that the tooltip is positioned incorrectly

## Reproducible Example

[Sandbox to show the incorrect positioning](https://codesandbox.io/s/fast-feather-kslsq?file=/src/App.js).

## Expected behavior

Expected the tooltip to be positioned next to the button. On the left side of the button

## Screenshots

![tooltip](https://user-images.githubusercontent.com/60068454/81329988-06787e00-90bd-11ea-9786-5d16fa333f57.png)

## Environment (please complete the following information)

- Operating System: Windows
- Browser, Version: Chrome 81
- React-Bootstrap Version: 1.0.1

## Additional context

The same issue occurs with other overlays for me such as popovers.

**Comment by jquense** [comment]
you are using it correctly. you need to spread the injected props through like: 
![image](https://user-images.githubusercontent.com/339286/81336005-829ba300-9076-11ea-9909-83373150ded8.png)

**Comment by nspeedzy** [comment]
@jquense Thanks. You saved my life. I was about to go really mad, you know...

**Comment by Meryldominguez** [comment]
Hi! Im actually having this issue, despite spreading the injected props.
I am working on a Navbar that re-renders based on the 'status' of the 'event' namely 'published','pending', or 'draft'
<img width="1192" alt="Screen Shot 2021-01-10 at 11 20 54 PM" src="https://user-images.githubusercontent.com/67508796/104205488-15ee5a80-53f4-11eb-8b2f-8daf6f685f72.png">

It seems that  if one of the tooltips is triggered when the navbar buttons get re-rendered, I get the placement problem, despite having injected the props.
<img width="1792" alt="Screen Shot 2021-01-11 at 8 42 58 AM" src="https://user-images.githubusercontent.com/67508796/104205511-1c7cd200-53f4-11eb-8d80-c75c5d31ae56.png">
<img width="475" alt="Screen Shot 2021-01-11 at 9 17 59 AM" src="https://user-images.githubusercontent.com/67508796/104205539-23a3e000-53f4-11eb-8f53-20434505198b.png">
<img width="606" alt="Screen Shot 2021-01-11 at 10 03 01 AM" src="https://user-images.githubusercontent.com/67508796/104205612-374f4680-53f4-11eb-960b-2857926a583d.png">

Any help on this @jquense?

**Comment by thepuzzlemaster** [comment]
@Meryldominguez, I just ran into the same problem. In my case, my overlay, was pointing to a `React.FC`, and I had to change it to be `React.forwardRef` in order for the overlay to position correctly. But it worked after I made that change.

**Comment by theraggedflygon** [comment]
Hi @thepuzzlemaster do you happen to have an example of how you were able to fix the issue using `React.forwardRef`? I wrapped the tooltip in the `forwardRef` callback, but am still encountering the issue described above when a component re-renders.

**Comment by thepuzzlemaster** [comment]
> Hi @thepuzzlemaster do you happen to have an example of how you were able to fix the issue using `React.forwardRef`? I wrapped the tooltip in the `forwardRef` callback, but am still encountering the issue described above when a component re-renders.

My implementation is actually kind of complex, because I made a generic version that builds the popover for me with a few React.CloneElement() calls and resting props and such. Are you able to post your code or create a codesandbox repro? Perhaps I can spot your issue that way.

**Comment by philippemiron** [comment]
Hi,

I'm having a similar issue now with bootstrap 5.2.0 and react-bootstrap 2.4.0. I updated the [sandbox](https://codesandbox.io/s/crazy-danilo-8wklic?file=/src/App.js). 

See the following screenshot,

<img width="761" alt="Screen Shot 2022-08-04 at 17 13 13" src="https://user-images.githubusercontent.com/387624/182954039-ea7a1b5e-9a22-4d98-a127-b29e20bf113b.png">
