### ISSUE TITLE
ref type is incorrect, typescript react 

### ISSUE THREAD

**Issue by jjarrett21** [react-bootstrap/react-bootstrap#5167]
## Describe the bug

After updating my packages, the ref type in FormControlProps is wrong/non existent. 

## To Reproduce

1. Upgrade package
2. Look at compilation errors 

## Reproducible Example

No example needed

## Expected behavior

That the FormControlProps have a ref type and not itemRef

## Environment (please complete the following information)

- mac os
- chrome version 81
- react-bootstrap ^1.0.0-beta.16"

**Comment by jquense** [comment]
this doesn't describe what error you are running into. I can't upgrade your project to see what error you are getting

**Comment by jjarrett21** [comment]
The props for FormControl are not correct and they don't have a ref prop that gets passed anywhere

**Comment by jjarrett21** [comment]
Thats the specific error it keeps trying to say itemRef it the only available ref and it's type is string and not React.Ref

**Comment by mxschmitt** [comment]
Can you try to make a reproducible example via CodeSandbox?

You can use this template: https://codesandbox.io/s/github/react-bootstrap/code-sandbox-examples/tree/master/basic-ts

**Comment by jjarrett21** [comment]
Yes I'll make a sandbox

**Comment by jjarrett21** [comment]
Ok this is a sandbox with my issue, afrer updating I had to switch my ref types from innerRef to ItemRef itemRef is incorrect unless I use an any. 

https://codesandbox.io/s/upbeat-kowalevski-w0w70?file=/src/App.tsx

**Comment by jquense** [comment]
@jjarrett21 `itemRef` is a HTML attribute https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/itemref not a react ref. FormControl's accept a `ref` prop, the types used to have an `inputRef` prop but that was incorrect and was fixed. `inputRef` didn't anything, change your code from `inputRef` to `ref`

**Comment by jjarrett21** [comment]
@jquense there isn't a ref type `FormControlProps & InputHTMLAttributes<HTMLInputElement>;` when I use this as my interface.

**Comment by jquense** [comment]
No their isn't on the exported props. It's added by the forward ref type
