### ISSUE TITLE
FormControlProps missing `as` declaration

### ISSUE THREAD

**Issue by toddobryan** [react-bootstrap/react-bootstrap#5170]
## Describe the bug

There's no declaration for `as` in  FormControlProps

## Fix

Add

`as?: 'input' | 'select' | 'textarea' | ???` 

to `types/components/FormControl.d.ts`.

I'm happy to provide a Pull Request, but I don't know what the ??? should be that corresponds to `elementType`.

**Comment by taion** [comment]
It's not meant to be there; `as` takes place via the generic parent type used here, to get proper typing on the other props: https://github.com/react-bootstrap/react-bootstrap/blob/ee2840835925384e7bcfa3df8a14cad199c94c7f/types/components/FormControl.d.ts#L26

**Comment by toddobryan** [comment]
What type should I declare a set of props that I'm planning to use in `Form.Control` as? I need a type or else I need to do `as: 'textarea' as 'textarea'` or else it won't type-check, because the `as` is typed as a generic `string`. In other words, what is the type of a Props object that can be used in a `Form.Control`?

**Comment by taion** [comment]
`React.ComponentProps<Form.Control<...>>`

**Comment by toddobryan** [comment]
TS2713: Cannot access 'Form.Control' because 'Form' is a type, but not a namespace. Did you mean to retrieve the type of the property 'Control' in 'Form' with 'Form["Control"]'?

**Comment by taion** [comment]
`typeof Form.Control` then
