### ISSUE TITLE
Toasts - Stacked Toasts with autohide delays does not work correctly in prod build. 

### ISSUE THREAD

**Issue by murtuzamacdev** [react-bootstrap/react-bootstrap#5173]
I have an array of toast data which I am using to render the stacked toast as mentioned [here](https://react-bootstrap.github.io/components/toasts/#stacking) 

Each of the `<Toast/>` have `autohide=true` with `delay=5000`. 

The problem is when a new `<Toast/>` is added dynamically by pushing a new item in the array, the delay for all the existing `<Toast/>` restarts. 

The expected behavior should be: `<Toast/>` should get hidden after 5 secs of their creation.

Below is my code snippet of my `render()`: 

```jsx
<>  this.toastArray.map((toast) => {
   return <Toast autohide={true} delay={5000} onClose={() => {this.closeToast(toast.id)}}>
                     <Toast.Body>{toast.text}</Toast.Body>
               </Toast>
}) </>
``` 

Interestingly, the issue happens only in prod build, built with`npm run build`. 

It works fine in local dev environment with `npm run start`.

**Comment by taion** [comment]
You need to assign keys to each of your items in the array. This is generally the case when using arrays list this with React.

**Comment by murtuzamacdev** [comment]
Event after adding the key to each items of the array, the issue persist.

**Comment by mxschmitt** [comment]
I could also reproduce this in a small codesandbox: https://codesandbox.io/s/dazzling-bouman-orq3w?file=/src/App.js
