### ISSUE TITLE
ignore rootClose property for custom elements

### ISSUE THREAD

**Issue by arindamINT** [react-bootstrap/react-bootstrap#5176]
**Request:**
In <OverlayTrigger> element rootClose attribute/property is working fine for any other click except the Overlay elements. But I need one feature that will really help full for all developers. Currently I am displaying a mini cart list feature as an overlay popover. There is a delete icon for each item and clicking on that icon I am opening a confirmation modal. But unfortunately whenever I am clicking Yes/Cancel button of the confirmation modal the <OverlayTrigger> element is getting hide due to using rootClose property. But I also need this  rootClose feature on my app.

I am asking to add one more attribute so that user can add a set of element array for which this rootClose feature will not work. Like this below

> <OverlayTrigger
                trigger="click"
                placement="bottom-end"
                onEnter={callCart}
                rootClose={rootCloseMode}
                **rootCloseIgnore=['.header', '#mySection', '.myModal']** ......

**Comment by taion** [comment]
dupe https://github.com/react-bootstrap/react-bootstrap/issues/5175
