### ISSUE TITLE
Error handling for FormCheck when Id is not a string. 

### ISSUE THREAD

**Issue by arvind-girish12** [react-bootstrap/react-bootstrap#5179]
I added the following code to my project

  {Array.isArray(values) &&
          values.length > 0 &&
          values.map((item) => {
            return (
              <Form.Check
                className="f-14 font-weight-medium mb-1"
                checked={values=== item.value}
                custom
                type="checkbox"
                value={item.value}
                id={`${item}${index}`}
                label={`${item.label}`}
                onChange={(e) => {
                  this.handleChange(
                    e.target.checked,
                    e.target.value,
                    index
                  )
                }}
              />
            )
          })}

Even if everything is correct, the small part where item is an object and not a string rejects every onchange since id is no longer a unique string for each formCheck. Would be really helpful if there's an error when an id for a component is not a string.

**Comment by taion** [comment]
when you do

```
`${item}${index}`
```

that's casting it to a string. by the time it gets out of your code, it's already a string

**Comment by arvind-girish12** [comment]
yeah, but it's not unique. So if you have three <FormChecks>  with values and labels as 'a', 'b' and 'c' respectively, you will never be able to change any of the checkbox values after the first assignment if you make the id = {item}

Error handling in such cases would work wonders instead
