### ISSUE TITLE
Modal Dialog ARIA Role & Attributes Applied at Incorrect Level

### ISSUE THREAD

**Issue by kPOWz** [react-bootstrap/react-bootstrap#5180]
## Describe the bug

Accessibility bug on Modal.Dialog where attributes are applied to the incorrect element - one level too high.

## To Reproduce

1. Go to https://react-bootstrap.netlify.app/components/modal/
2. Click on 'Launch demo modal'
3. Open your browser dev tools inspector  (if chrome dev tools can use the Accessibility tab)
4. See `role="dialog"` & `aria-modal="true"` being applied to the overlay/wrapping element rather than the `modal-dialog` element itself
5. See this defined [in the component code](https://github.com/react-bootstrap/react-bootstrap/blob/master/src/Modal.js#L379) - 

## Reproducible Example

A reproducible example is the react-bootstrap component examples linked above in steps to reproduce

## Expected behavior

Follow the [w3.org correct usage](https://www.w3.org/TR/wai-aria-practices/examples/dialog-modal/dialog.html) for `role="dialog"` & `aria-modal="true"` which is to apply to `modal-dialog` element itself rather than overlay/wrapping element.

## Screenshots

<img width="1278" alt="Screen Shot 2020-05-14 at 5 29 53 PM" src="https://user-images.githubusercontent.com/1749783/81992231-a2980d00-9608-11ea-9270-24f25b9fceb1.png">

## Environment (please complete the following information)

- Operating System: all
- Browser, Version all
- React-Bootstrap Version: not sure. seems to have been added in #5132

## Additional context

As a result, `aria-labelledby` is also applied [at the incorrect level](https://github.com/react-bootstrap/react-bootstrap/blob/master/src/Modal.js#L385) and should default to the [Modal.Title text](https://react-bootstrap.netlify.app/components/modal/#modal-title-props)

**Comment by taion** [comment]
cc @jquense i think this is a regression from https://github.com/react-bootstrap/react-bootstrap/pull/5105, then?

**Comment by taion** [comment]
huh? did the problem go away?

**Comment by kosmiq** [comment]
This was brought up over at TWBS as well https://github.com/twbs/bootstrap/issues/30516 and according to them there's no issue with where the aria labels are placed. We are following upstream and placing the aria labels on the same element.

Not sure why kPOWz closed the issue though.
