### ISSUE TITLE
./node_modules/react-overlays/esm/usePopper.js Cannot find module: '@restart/hooks/useSafeState'. Make sure this package is installed.

### ISSUE THREAD

**Issue by jrsenthilk** [react-bootstrap/react-bootstrap#5182]
Unable to find the dependency needed.

Cannot find module: '@restart/hooks/useSafeState'.

## To Reproduce

1. Upgraded to - 
+ react-bootstrap@1.0.1
+ bootstrap@4.5.0

2. Try to build my project - npm run build 

3. Ended with the error above. Unable to install dependency as the npm site for this dependency appears not in service. Is this temporary ?

**Comment by jrsenthilk** [comment]
Managed to install the @restart@hooks .. but now i am getting the error below:

Attempted import error: 'useUncontrolledProp' is not exported from 'uncontrollable'.

**Comment by taion** [comment]
This looks like an issue with your build setup, like you're incorrectly deduplicating dependencies or something. Don't do that.
