### ISSUE TITLE
Reopened: Toasts - Stacked Toasts with autohide delays does not work correctly in prod build.

### ISSUE THREAD

**Issue by murtuzamacdev** [react-bootstrap/react-bootstrap#5183]
I have an array of toast data which I am using to render the stacked toast as mentioned [here](https://react-bootstrap.github.io/components/toasts/#stacking) 

Each of the `<Toast/>` have `autohide=true` with `delay=5000`. 

The problem is when a new `<Toast/>` is added dynamically by pushing a new item in the array, the delay for all the existing `<Toast/>` restarts. 

The expected behavior should be: `<Toast/>` should get hidden after 5 secs of their creation.

Below is my code snippet of my `render()`: 

```jsx
<>  this.toastArray.map((toast) => {
   return <Toast key={toast.id} autohide={true} delay={5000} onClose={() => {this.closeToast(toast.id)}}>
                     <Toast.Body>{toast.text}</Toast.Body>
               </Toast>
}) </>
``` 

Interestingly, the issue happens only in prod build, built with`npm run build`. 

It works fine in local dev environment with `npm run start`. 

I also tried things mentioned in the issue [here](https://github.com/react-bootstrap/react-bootstrap/issues/5173) and updated the code accordingly in this ticket.

**Comment by mxschmitt** [comment]
Lets reopen the other one.
