### ISSUE TITLE
JSX element type 'Modal<"div">' is not a constructor function for JSX elements.

### ISSUE THREAD

**Issue by Lilian1331** [react-bootstrap/react-bootstrap#5185]
After i have upgraded the package to "react-bootstrap": "^1.0.1" from "react-bootstrap": "^1.0.0-beta.9" , it pops me this error.

> JSX element type 'Modal<"div">' is not a constructor function for JSX elements.
  The types returned by 'render()' are incompatible between these types.
    Type 'ReactNode' is not assignable to type 'false | Element'.
      Type 'string' is not assignable to type 'false | Element'.ts(2605)

Below are the code that I used to embed the module:
`{this.state.mode == "SingleItem" && <Modal show={true}>
            <Modal.Body>
              <div className="row justify-content-center">
                <h4>{this.state.showItem["Title"]}</h4>
              </div>
              <div className="row">
                <h4>{this.state.showItem["ShortDescription"]}</h4>
              </div>
            </Modal.Body>
</Modal>}`

Below are the version of my react

> @types/react: 16.7.22

May I know is there config i need to add? Great thanks for any help!

**Comment by taion** [comment]
You should upgrade your version of `@types/react`.
