### ISSUE TITLE
Typescript Error: Type 'FormControl' is not generic.  TS2315

### ISSUE THREAD

**Issue by AHorak** [react-bootstrap/react-bootstrap#5187]
I'm getting this error with the new version i think so.

This worked before:

`export default React.forwardRef<FormControl<ElementType<any>>, FileUploadProps>`

so it looks like `FormControl<ElementType<any>`
is not ok in the context of forwardRef?

**Comment by taion** [comment]
yes; the `FormControl` types are wrong and don't include the generic. we'd be happy to take a PR fixing them: https://github.com/react-bootstrap/react-bootstrap/blob/f846dfbe9b8d85fa9ec8cd3d7e50d1310fd12220/types/components/FormControl.d.ts#L25-L28

**Comment by AHorak** [comment]
I think the problem was introduced by #5067

**Comment by jquense** [comment]
The generic is on the call signature not the interface itself which has been more accurate in practice i think

**Comment by AHorak** [comment]
So what is the recommended workaround now?
