### ISSUE TITLE
Add FormControl.Feedback tooltip variant

### ISSUE THREAD

**Issue by kyletsang** [react-bootstrap/react-bootstrap#5188]
## Is your feature request related to a problem? Please describe

Noticed the FormControl.Feedback was missing the tooltip variant. See official bootstrap docs:
https://getbootstrap.com/docs/4.5/components/forms/#tooltips

## Describe the solution you'd like

I could create a PR for this. Perhaps adding a `tooltip` boolean prop to Feedback that would set the tooltip class if true and original feedback class if false/undefined?

**Comment by jquense** [comment]
oo missed that yeah. Would you like to send a PR adding it?
