### ISSUE TITLE
Got TypeError: type.toUpperCase is not a function when using ButtonToolbar/Button

### ISSUE THREAD

**Issue by agile116** [react-bootstrap/react-bootstrap#519]
Hi 
I got the below error when I tried to use ButtonToolbar and Button, any idea about it?
TypeError: type.toUpperCase is not a function   tagName: type.toUpperCase(),

I'm using browserify and gulp with the two dependencies.
"react": "^0.13.1",    "react-bootstrap": "^0.20.3"

**Comment by MrRoyce** [comment]
I get the same error when I use the contained modal.  Module isOverFlowing.js is looking for a tagName attribute.  This doesnt happen when using the regular, non-contained modal.

`function isBody(node) {
  return node && node.tagName.toLowerCase() === 'body';
}`
