### ISSUE TITLE
`autoFocus` of input field in modal doesn't work unless internal state is used?

### ISSUE THREAD

**Issue by ahri** [react-bootstrap/react-bootstrap#5195]
I'm using redux to control my state, including when a modal should show, as such the modal is added and removed from the DOM via messages resulting in re-renders of the state, meaning I don't need to change the internal state of the component.

With this setup `autoFocus` of elements in the modal doesn't work, which looked like #903 but as that was fixed ages ago (and setting `enforceFocus` made no difference) I assume it's because I'm not transitioning the modal `show` state?

**Comment by kosmiq** [comment]
See #5102

**Comment by ahri** [comment]
Thanks! I hadn't spotted that bug, subscribed :)
