### ISSUE TITLE
Modal lifecycle hooks only fire when animation is used?

### ISSUE THREAD

**Issue by ahri** [react-bootstrap/react-bootstrap#5196]
When using a Modal with `animation=False` `onEntered` doesn't seem to get called - perhaps this is by design and I should be hooking another event?

I should say that I'm not sure this is a bug, I'm more highlighting a surprise in your API.

**Comment by taion** [comment]
yes; `onEntered` is an "animation done playing" hook. if you're not using an animation, then there's no point in such a hook here. when you show the modal, it's shown.
