### ISSUE TITLE
<various things> inside Card.Text throws console errors

### ISSUE THREAD

**Issue by ajoslin103** [react-bootstrap/react-bootstrap#5197]
## Is your feature request related to a problem? Please describe

`Card.Text is rendered as a <p> tag, which has lots of limitations 
`
## Describe the solution you'd like

`Card.Text is rendered as an <article> tag, which has fewer limitations 
`
## Describe alternatives you've considered

Allowing us to specify what kind of tag Card.Text should be rendered as 

## Additional context

I use react-bootstrap a lot, it makes things really easy!

**Comment by jquense** [comment]
you can control what it renders as via the `as` prop, e.g. `<Card.Text as="article">` if that is appropriate

**Comment by ajoslin103** [comment]
thanks !!  that's some fast work !!
