### ISSUE TITLE
Why element name is hierarchy?

### ISSUE THREAD

**Issue by maixuanhan** [react-bootstrap/react-bootstrap#5199]
Why this? (and so many of others?)
```jsx
<Card style={{ width: '18rem' }}>
  <Card.Img variant="top" src="holder.js/100px180" />
  <Card.Body>
    <Card.Title>Card Title</Card.Title>
    <Card.Text>
      Some quick example text to build on the card title and make up the bulk of
      the card's content.
    </Card.Text>
    <Button variant="primary">Go somewhere</Button>
  </Card.Body>
</Card>
```
Is it `Img`, `Body`, `Title`... enough?
This make the source code less readable

**Comment by jquense** [comment]
The names reflect what the components are, i.e. it's a card title not a title. Readablity is mostly a matter of opinion, to me this is more "readable" because it's less ambiguous and harder to misconstrue what a component is without looking at the imports

**Comment by maixuanhan** [comment]
What you are explaining is to make them easier to be used but not readable at all. Your "readable" is in fact "convenience". They are nested elements, each of them has ancestors which are enough to identify what it is. Anyhow, I don't think that this could be changed so fair enough to close the issue.

**Comment by jquense** [comment]
It's really not about being a convenience, if the components were exported independently (and many in RB are) they would still be named CardTitle and CardImg. In the same way drop-down items wouldn't be Item. If you find it hard to read I would encourage you to create a Card.js file in your own project and re export the sub components as Img or Title if that works better for you and your team
