### ISSUE TITLE
Tab in Tabs tree does't appear 

### ISSUE THREAD

**Issue by rodrigofbm** [react-bootstrap/react-bootstrap#5202]
## Environment
- Operating System: macOS Catalina
- Browser, Version: Edge/83.0.478.37 
- React-Bootstrap Version: 1.0.1

My code:

```
<Tabs
            defaultActiveKey="search"
            activeKey={key}
            onSelect={(k) => {
              console.log("clicked 1");
              setIsOpen(false);
              setKey(k);
              setContact(null);
              setSearchContact("");
              setSearchContactResults([]);
            }}
          >
            <SearchResultsTab/>

          </Tabs>
```

```
import React from "react";
import { Tab } from "react-bootstrap";
import { faSearch } from "@fortawesome/free-solid-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";

const SearchResultsTab = ({}) => (
    <Tab eventKey="search" title={<FontAwesomeIcon icon={faSearch} />}>
        <p>Oi</p>
    </Tab>
)

export default SearchResultsTab;
```

If I put 
```
<Tab eventKey="search" title={<FontAwesomeIcon icon={faSearch} />}>
        <p>Oi</p>
    </Tab>
```

directly inside of <Tabs> </Tabs> it work. But I want to use other component file...

**Comment by taion** [comment]
This isn't supported for `<Tabs>`. The parent component needs to actually iterate through its children to read off its properties to work.

You can define your search results tab as a static element, or else as a render function that returns the element (rather than as a React component), or you can use the more powerful API.

**Comment by Ethan-Arrowood** [comment]
What is the "more powerful API" you refer to? I hit this same problem trying to separate some concerns in my Tabs element. (I have multiple tabs and only some of the tabs need to subscribe to a specific context)

**Comment by taion** [comment]
https://react-bootstrap.github.io/components/tabs/#tabs-custom-layout
