### ISSUE TITLE
<Col> outputs column classes without sizing if no span is set in an object breaking responsiveness in some cases

### ISSUE THREAD

**Issue by kosmiq** [react-bootstrap/react-bootstrap#5205]
## Describe the bug

Creating an issue to keep track of this. Will look into it whenever I get around to it. It could be by design, if so do please tell.

## To Reproduce

1. Create a `<Col>`
2. Set two breakpoints using the object style, but omit setting a span for one breakpoint: `<Col xs={{ span: "auto", order: 2 }} lg={{ order: 1 }}>`
3. The outputted html becomes `<div class="col-lg col-auto order-lg-2 order-1">` with no sizing set for `lg` breakpoint.
4. This breaks auto sizing that should be inherited from the smaller breakpoint since `col-lg` has CSS without a specified breakpoint.

## Reproducible Example
https://codesandbox.io/s/bold-night-htu76?file=/src/App.js

Not reproducible per se since in my application `col-lg` hits my div (see screenshot) and breaks the auto-sizing of the col that I want to be inherited from xs breakpoint definition.

However you can see that the `col-lg` class is added even though I only really want the order class to be outputted, but the order-lg-* should be added.

## Expected behavior

Sizing should be inherited from the smaller breakpoint as expected and the "empty" `col-lg` class should not be outputted

## Screenshots

![Screenshot 2020-05-28 at 10 55 33](https://user-images.githubusercontent.com/322759/83121039-1be83300-a0d2-11ea-9a1e-73a4105d107b.png)

## Environment (please complete the following information)

- Operating System: MacOS 10.15.5
- Browser, Version Chrome version 81.0.4044.138 (Official Build) (64-bit)
- React-Bootstrap Version Beta 16 and 1.0.1

## Additional context

For some reason the col-lg class exists in the official bootstrap CSS but does not get active in the example on CodeSandbox?

**Comment by kyletsang** [comment]
Looks like span is defaulted to `true` when it's omitted.  Seems like this should be opt-in if you want to output equal width sizing classes?

https://github.com/react-bootstrap/react-bootstrap/blob/dcbed6d9aa039ae65317f1b7d8d5947c259f011e/src/Col.js#L86

**Comment by kosmiq** [comment]
@taion @jquense do you have a suggestion here? For my own use case I would love to be able to omit span for breakpoints and thus more mimic the behavior if I omit the lg tag altogether, and not get col-lg as class. I would be fine with being able to set span: false to stop output, or span: true if I want it and false is the default.

I'd be happy to create the pr if we decide how to handle it.

**Comment by taion** [comment]
The current default definitely feels weird/wrong.

I guess what I wonder is – can we fix this without calling it a breaking change? If we do consider this a breaking change, then we may not be able to do better than just warn if `span` is omitted...

**Comment by kyletsang** [comment]
When the typescript branch is merged to master, will this be a major version bump?  Perhaps we can make it a breaking change, because default `true` doesn't feel right.

**Comment by taion** [comment]
great point!

**Comment by kyletsang** [comment]
Unfortunately there is no way to remove the `col-${size}` class when using props in object form, so you're stuck with it if you want to use ordering and offsets.  Setting span to false would result in something like `col-md-false` with the current code.

https://github.com/react-bootstrap/react-bootstrap/blob/9e216c2c35af29188f580a53d35aaa896e32ae48/src/Col.js#L93-L96

We could add the ability to use `span: false`?  Although it would be nice to stay consistent (ie. omit span = do not apply `col-${size}`.

What do you think @taion ?

**Comment by taion** [comment]
We should definitely allow doing `span: false`, for now, then. And then change the default for the next breaking change w/the TypeScript stuff

**Comment by kyletsang** [comment]
Actually, I took a second look and passing in `span: null` would work instead of `span: false`. Sorry my bad, I was playing around with this in a TS environment and missed this.

So the only thing to fix here are the docs and TS defs.
