### ISSUE TITLE
Support `for` attribute in labels

### ISSUE THREAD

**Issue by binarykitchen** [react-bootstrap/react-bootstrap#521]
That will enhance accessibility a lot ... thx!

**Comment by mtscout6** [comment]
I agree that we need this. Something to consider in #342.

**Comment by mtscout6** [comment]
By the way PRs are very welcome!

**Comment by apkiernan** [comment]
Taking a look at this, are we talking about `<Label>` supporting the `for` attribute, or the label that is rendered with `<Input>`? If the latter, the `<Input>` component already supports the `for` attribute, which is set automatically to the `id` prop you set on the component.

**Comment by binarykitchen** [comment]
Both cases

**Comment by binarykitchen** [comment]
I would like to be able to manually set the `for` attribute without mentioning an ID, i.E. when `<input>` has nested children.

**Comment by binarykitchen** [comment]
Currently it does not respect the ID of any child inputs

**Comment by mtscout6** [comment]
> I would like to be able to manually set the for attribute without mentioning an ID

What exactly do you see that looking like?

`<label for=???>Label Text</label>`

**Comment by binarykitchen** [comment]
alright, here my use case. i am using a nested child input inside the usual input element:


```cjsx
      <Row>
        <Input
          hasFeedback
          required
          label    = {t("Password")}
          value    = {@state.password}
        >
          <InputPassword
            required
            id           = 'passwordRaw'
            ref          = 'password'
            value        = {@state.password}
            zxcvbn       = {zxcvbn}
          />
        </Input>
      </Row>
```

the first `<input>` is just a wrapper and will display a label. but that label has no `for` attribute.

tried setting the prop `for = 'passwordRaw'` but that didn't work.

hope this explains my problem?

**Comment by mtscout6** [comment]
What is your `InputPassword` component doing that `<Input type='password' />` can't do?

**Comment by binarykitchen** [comment]
Well, I am using `InputPassword  = require('react-ux-password-field')` which comes with more cool stuff we need here for our project.

**Comment by mtscout6** [comment]
In the case of an Input wrapper, this is not implemented. You can submit a PR, but I don't know how this will effect @aabenoja's work on #342 that's he's doing right now.

**Comment by binarykitchen** [comment]
good, we see eye to eye now. there is no rush. should i write a new ticket for that or mention it in #342?

**Comment by mtscout6** [comment]
No need for a new issue, this one explains the problem.

**Comment by dbackeus** [comment]
+1

**Comment by taion** [comment]
Just put the same `id` on both the `Input` and the nested child. That will get you what you want.

**Comment by gtwilliams03** [comment]
@binarykitchen Did you ever get `InputPassword = require('react-ux-password-field')` working with bootstrap?  I am trying to implement it with `react-bootstrap` and it looks like a mess inside a `FormGroup`, even with adding `className='form-control'` to the `InputPassword` component.
