### ISSUE TITLE
Popover> Updating position dynamically example does not work

### ISSUE THREAD

**Issue by AdityaAnand1** [react-bootstrap/react-bootstrap#5213]
I'd like to show a popover on hovering an element. However, upon changing the content of popover or scrolling up or down, popover starts appearing in wrong location.

I thought the fix was in the docs: https://react-bootstrap.github.io/components/overlays/#overlays-dynamic-updates

But running the following **as is**

```
const UpdatingPopover = React.forwardRef(
  ({ popper, children, show: _, ...props }, ref) => {
    useEffect(() => {
      console.log('updating!');
      popper.scheduleUpdate();
    }, [children, popper]);

    return (
      <Popover ref={ref} content {...props}>
        {children}
      </Popover>
    );
  },
);

const longContent = `
  Very long
  Multiline content
  that is engaging and what-not
`;
const shortContent = 'Short and sweet!';

function Example() {
  const [content, setContent] = useState(shortContent);

  useEffect(() => {
    const timerId = setInterval(() => {
      setContent(content === shortContent ? longContent : shortContent);
    }, 3000);

    return () => clearInterval(timerId);
  });

  return (
    <OverlayTrigger
      trigger="click"
      overlay={
        <UpdatingPopover id="popover-contained">{content}</UpdatingPopover>
      }
    >
      <Button>Holy guacamole!</Button>
    </OverlayTrigger>
  );
}

render(<Example />);
```

results in the following error:

![image](https://user-images.githubusercontent.com/13274079/83600915-42ecac00-a58d-11ea-8283-d0392b3859cc.png)

Does the overlay component no longer pass a 'popper' prop? Is there some other way to do this?

Whenever the content of popover changes OR whenever I scroll up or down from initial location, popover remains stuck to it's first initial location and does not actually follow the target anchor element to which it should be glued. How to do this?

**Comment by kyletsang** [comment]
I tested this on the docs site and locally in a new CRA project and it's working.  Can you post the repro on CodeSandbox?

**Comment by kyletsang** [comment]
If this is still an issue, please attach a minimal example on CodeSandbox and reopen.

**Comment by LJuric2604** [comment]
Hi there. This is still an issue. This is the code sample how I managed to work around this problem.
`const UpdatingPopover = React.forwardRef((render, ref) => {
  useEffect(() => {
    render.scheduleUpdate();
  }, [render]);

  return (
    <Popover ref={ref} {...render}>
      {render.children}
    </Popover>
  );
});`

**Comment by mmomtchev** [comment]
@LJuric2604, your example looks very wrong to me - `render` will contain the `props` object and won't have a `scheduleUpdate` function?

**Comment by mmomtchev** [comment]
@kyletsang Do you have an idea for a clean way of updating the popup when `children` is another React component that changes while the reference stays the same? Currently as `children` is not modified, the update is not triggered. Something else than carrying the `scheduleUpdate` function down the hierarchy, which requires to modify every component that can be included in a popup?

**Comment by LJuric2604** [comment]
@mmomtchev, this was just the sample code of quick fix to help if someone stumbles on the same problem as me. As you see in [documentation](https://react-bootstrap.github.io/components/overlays/#overlays-dynamic-updates)  you can call `scheduleUpdate` from `popper `object, but in this older version (can't say if the new version fixed this) `scheduleUpdate` is not inside `popper` object. `render` object can be extracted with `{scheduleUpdate, children, show: _, ...props}` which is different from documentation.

**Comment by kyletsang** [comment]
> @kyletsang Do you have an idea for a clean way of updating the popup when `children` is another React component that changes while the reference stays the same? Currently as `children` is not modified, the update is not triggered. Something else than carrying the `scheduleUpdate` function down the hierarchy, which requires to modify every component that can be included in a popup?

You can probably pass scheduleUpdate down via react context, and whichever component needs to use scheduleUpdate can consume the context there.
