### ISSUE TITLE
Dead link: https://react-bootstrap.github.io/components/popovers/

### ISSUE THREAD

**Issue by AdityaAnand1** [react-bootstrap/react-bootstrap#5214]
Are there any docs for popover? 

https://react-bootstrap.github.io/components/popovers/

The link is dead on the docs website.

**Comment by mxschmitt** [comment]
Where exactly is the link?

Here you find the documentation for popovers: https://react-bootstrap.github.io/components/overlays/#popovers

**Comment by AdityaAnand1** [comment]
![image](https://user-images.githubusercontent.com/13274079/83636073-f623c800-a5c2-11ea-9d0e-6a29f3c39fdd.png)

**Comment by taion** [comment]
Ah, yeah, that shouldn't be there.

**Comment by taion** [comment]
Per https://github.com/react-bootstrap/react-bootstrap/pull/5215#issuecomment-638404342, we should fix the link
