### ISSUE TITLE
[Form] bsPrefix doesn't work with Form

### ISSUE THREAD

**Issue by ko2in** [react-bootstrap/react-bootstrap#5216]
## Describe the bug

When specifying `bsPrefix` to `Form` component. It doesn't generate any string specified with `bsPrefix`, not even the default string `form` as described in [documentation](https://react-bootstrap.github.io/components/forms/#form-props). It's always empty.

## To Reproduce

Run the following snippets:
```
<Form bsPrefix="form p-4">
        <Form.Group controlId="name">
          <Form.Label>
            Name <span className="text-danger">*</span>
          </Form.Label>
          <Form.Control
            type="email"
            placeholder="Your name"
            name="name"
            required
          />
          <Form.Control.Feedback type="invalid" />
        </Form.Group>
        <Form.Group controlId="email">
          <Form.Label>
            E-mail address <span className="text-danger">*</span>
          </Form.Label>
          <Form.Control
            type="email"
            placeholder="Your e-mail"
            name="email"
            required
          />
          <Form.Control.Feedback type="invalid" />
        </Form.Group>
        <Form.Group controlId="company">
          <Form.Label>
            Company <span className="text-danger">*</span>
          </Form.Label>
          <Form.Control
            type="text"
            placeholder="Company"
            name="company"
            required
          />
          <Form.Control.Feedback type="invalid" />
        </Form.Group>
        <Form.Group controlId="phone">
          <Form.Label>
            Phone number <span className="text-danger">*</span>
          </Form.Label>
          <Form.Control
            type="tel"
            placeholder="Company"
            name="phone"
            required
          />
          <Form.Control.Feedback type="invalid" />
        </Form.Group>
        <Button variant="primary" type="submit" block>
          Submit
        </Button>
      </Form>
````

## Reproducible Example

Here's the code sandbox (https://codesandbox.io/s/wandering-wildflower-07lcw).

## Expected behavior

The form should have the base class name `form p-4`. But, the class name is empty.

## Environment

- Operating System: [Ubuntu 18.04]
- Chrome [Version 83.0.4103.61 (Official Build) Built on Ubuntu, running on Ubuntu 18.04 (64-bit)], Firefox [76.0.1 (64-bit), Mozilla Snap for Ubuntu, canonical-002 - 1.0]
- React-Bootstrap Version [^1.0.1]

**Comment by taion** [comment]
These is no base `.form` class in Bootstrap: https://getbootstrap.com/docs/4.5/components/forms/#overview

If you want custom classes, use the `className` prop.

**Comment by ko2in** [comment]
@taion , Does it refer only to other form elements which have bootstrap base class name? If so, the documentation shouldn't mention to use `bsPrefix` for [Form](https://react-bootstrap.github.io/components/forms/#form-props).
