### ISSUE TITLE
When will the onclick event be added back to DropdownButton?

### ISSUE THREAD

**Issue by agile116** [react-bootstrap/react-bootstrap#522]
Hi,
When will the onclick event be added back to DropdownButton?

```js
handleDropdownClick(e) {
  //e.preventDefault();
  this.setDropdownState(!this.state.open);
}
```

**Comment by agile116** [comment]
Any workaround?

**Comment by mtscout6** [comment]
I wasn't aware it was removed. Go ahead and add a PR to re-add it.

**Comment by agile116** [comment]
Sorry, I mean is there an option to propagate the event when we click the DropdownButton? Currently there is no effect after click the button. Below is the suggested change to the core DropdownButton. If this feature couldn't be added, do I have any workaround, override or anything?
handleDropdownClick(e) {
if(preventDefault){
   e.preventDefault();
}
this.setDropdownState(!this.state.open);
}

**Comment by mtscout6** [comment]
Dropdowns are currently a problem for us, the account for nearly 15% of all our issues. I've been stuck at a conference this week, and I do plan to tackle dropdowns soon, it is on the top of my radar. I don't have a definite date, but it will be soonish.

**Comment by AlexKVal** [comment]
Superceded by #526
