### ISSUE TITLE
Modal: 15px padding right on sticky / fixed NavBar

### ISSUE THREAD

**Issue by nikoisonfire** [react-bootstrap/react-bootstrap#5222]
Opening the modal puts an inline style of 15px right padding on the body and sticky or fixed elements. Supposedly this is for scrollbars sake, which, like someone commented [in this issue from 2015](https://github.com/react-bootstrap/react-bootstrap/issues/1077), don't appear on a mac. 

As you can see in this screenshot, this is breaking my layout. I've tried every way of overriding this behavior in runtime but couldn't figure it out. 

![Bildschirmfoto 2020-06-07 um 16 51 53](https://user-images.githubusercontent.com/22169321/83972568-30ea7080-a8e1-11ea-8c7d-2ed31d48b842.png)
![Bildschirmfoto 2020-06-07 um 16 52 33](https://user-images.githubusercontent.com/22169321/83972569-32b43400-a8e1-11ea-8995-68852265b261.png)

Thanks in advance for any help or fixing this bug

**Comment by moh12594** [comment]
Hi @nikoisonfire, as workaround, could you try to pass a prop `manager={}` to `Modal` in order to see if it solves the problem ?

**Comment by kyletsang** [comment]
This should be fixed by #5149.

The margin is not being offset properly for sticky-top elements.

As a workaround, you can subclass BootstrapModalManager and pass that instance through the `manager` prop in Modal

**Comment by nikoisonfire** [comment]
Dosen't seem to work or I am doing something wrong, this is my subclassed instance
![image](https://user-images.githubusercontent.com/22169321/84017943-b6bcf900-a97f-11ea-9623-7fb399214492.png)

**Comment by nikoisonfire** [comment]
Alright, made a quick hotfix by overriding both set and remove style functions

`class SubModalManager extends BootstrapModalManager {
    constructor() {
        super();
    }

    setContainerStyle(containerState, container) {
        return;
    }
    removeContainerStyle(containerState, container) {
        return;
    }
}`

then inject this into the <Modal /> component

`        <Modal show={show} onHide={handleClose} manager={new SubModalManager()}>
`

Hopefully this can help some people who have a similar issue
