### ISSUE TITLE
How to config theme rebuild

### ISSUE THREAD

**Issue by hieusmiths** [react-bootstrap/react-bootstrap#5227]
## Thank to you read this report.
I checked in document i see it.
But i think team shoult make change theme rebuild
It is perfect if team make a example for it.
Thank so much.

**Comment by kyletsang** [comment]
I'm not sure I understand the request here.  Can you clarify what types of examples you are looking for?

**Comment by hieusmiths** [comment]
@kyletsang  Yes, it will like https://ant.design/docs/react/customize-theme

Thank you

**Comment by kyletsang** [comment]
You can find documentation on theming in the core Bootstrap website [here](https://getbootstrap.com/docs/4.5/getting-started/theming/). 

Documentation on how to import your custom sass file is found [here](https://react-bootstrap.github.io/getting-started/introduction/#customize-bootstrap).

**Comment by hieusmiths** [comment]
@kyletsang  Ohh my god, sorry man, i forward to theme section hahaa.
