### ISSUE TITLE
Question - trying to make a MyInput component similar to Input

### ISSUE THREAD

**Issue by aktxyz** [react-bootstrap/react-bootstrap#523]
I have taken the source for the Input component, and only changed the import statements to require as shown below.  The rest of the file matches the existing Input component.

The problem is the FormGroup component does not exist, and looking at the source, FromGroup is defined differently from the other components  (class FormGroup extends React.Component ...).

Any ideas how to get around this?

```
var React = require('react');

var classNames = require('classNames');
var Bootstrap = require('react-bootstrap');
var Button = Bootstrap.Button;
var FormGroup = Bootstrap.FormGroup;

const MyInput = 
    React.createClass({
```

**Comment by mtscout6** [comment]
We did not expose that component to the public api. The discussion for which is in #342. What are you trying to change about `Input` to necessitate a direct copy?

**Comment by dozoisch** [comment]
@aktxyz  I'll close that for the time being. Feel free to reopen!
