### ISSUE TITLE
Modal not focusing the modal Modal.body

### ISSUE THREAD

**Issue by Mrbeyond** [react-bootstrap/react-bootstrap#5233]
Modal not display the body content, the body contents displays below it. As if the zIndex of the modal is greater than that of its body. When the entire page is clicked anywhere, the onHide prop is triggered.
Actually it works fine in development mode but it starts once the app is built for production. Please I really need help with this.

**Comment by jquense** [comment]
seems like you have a CSS issue? It's hard to help without a reproduction

**Comment by Mrbeyond** [comment]
Please what did you mean by reproduction sir?

**Comment by jquense** [comment]
a repro is code that we can run that demonstrates the problem

**Comment by Mrbeyond** [comment]
Ok sir. like codesandbox or repo?

**Comment by jquense** [comment]
like a codesandbox, the issue template outlines the best way to do it
