### ISSUE TITLE
Please use console.warn for warnings (not console.error)

### ISSUE THREAD

**Issue by rally25rs** [react-bootstrap/react-bootstrap#5234]
## Is your feature request related to a problem? Please describe

Currently `console.error` is being used for informational suggestions.

This causes unnecessary spamming of unit test results and in-browser console. For example this is the output for my _passing_ tests:

![image](https://user-images.githubusercontent.com/38535/84381098-7abfa900-abb6-11ea-9d23-c002fe94a744.png)

I keep having people come up to me and tell me their test are failing because they just see a wall of 50 "error" red messages scroll by and freak out 😞 

If the first word of the message is "warning" then `console.warn` seems like a good way to log those 😄 

React was a big culprit for doing this same thing, but they thankfully seem to be starting change over to using `console.warn` now instead of `.error`.

## Describe the solution you'd like

Can we please use `console.warn` for warnings. 🙏 

## Describe alternatives you've considered

I don't want to have to suppress `console.error` during my tests, because legitimate errors need to be logged there.

## Additional context

(see screenshot above)

**Comment by jquense** [comment]
Hi there! We are matching the behavior of react which also uses `console.error` for things that should be addressed (but don't halt execution). In this case these aren't informational suggestions, they are warnings that you have a component misconfigured and they should be fixed.

**Comment by rally25rs** [comment]
> We are matching the behavior of react 

Perfect, then you have justified my argument 😉 
https://github.com/facebook/react/issues/16753

Specifically

```
Some warnings don't actually represent "errors" in practice. They have too high severity. It's not a huge deal in the console. But if you start hooking up the console to richer mechanisms (e.g. an error dialog), the difference becomes more annoying. You want to clearly separate what's broken today from what may break tomorrow.

...

Ideal End State

React codebase just calls console.error for severe warnings (potential bugs), and console.warn for mild warnings (e.g. deprecations). 
```

In this specific "Specifying only the hover..." message, this is not an application bug or something broken or something that will become broken. This is an informational suggestion for a potential usability issue, and even in the React world according to the linked RFC would fall under the "console.warn for mild warnings" bucket.

**Comment by jquense** [comment]
Like I said this is not an informational suggestion, RB considers clear a11y issues "potential bugs" because they are most likely bugs. Having a UI component be broken for keyboard users, touch screens, etc is almost always a problem which is why we log about it. If you intend for that to be the case, then you can and should filter out the warning in your tests.
