### ISSUE TITLE
Docs' Pages' Titles have to be fixed...

### ISSUE THREAD

**Issue by amans199** [react-bootstrap/react-bootstrap#5236]
## Is your feature request related to a problem? Please describe
it just would be great if you changed the titles on the pages of the docs to be equal to the component of the feature instead of showing the URL!!. 

## Describe the solution you'd like
you can use 'react-helmet' to change it dynamically...

![image](https://user-images.githubusercontent.com/29990896/84580858-614b7680-addb-11ea-9c62-0673455a626d.png)

**Comment by taion** [comment]
dupe https://github.com/react-bootstrap/react-bootstrap/issues/4704
