### ISSUE TITLE
I can't define the `name` attributes.

### ISSUE THREAD

**Issue by papac** [react-bootstrap/react-bootstrap#5237]
## Describe the bug

I can't define the `name` attributes.

I use typescript.

## To Reproduce

```
name' is specified more than once, so this usage will be overwritten.
    288 |           <Form.Control
    289 |             type="text"
  > 290 |             name="lastName"
        |             ^
    291 |             placeholder="Eudes"
    292 |             {...formik.getFieldProps("lastName")}
    293 |           />
```

## Environment (please complete the following information)

- Operating System: Windows
- React-Bootstrap Version 1.0.1

**Comment by kyletsang** [comment]
Formik's `getFieldProps` adds the name attribute for you, so you don't need to add it in yourself.
