### ISSUE TITLE
How to collect ServerStyleSheets from  react-bootstrap

### ISSUE THREAD

**Issue by slgauravsharma** [react-bootstrap/react-bootstrap#5242]
HI team react-bootstrap,

I have to implement server side react-bootstrap css just like we collect in material-ui library.
import { ServerStyleSheets } from "@material-ui/core/styles";

**Comment by taion** [comment]
React-Bootstrap doesn't do any styling, so there's nothing specific to import. Just pull in the Bootstrap CSS on the server side.
