### ISSUE TITLE
Ref Forwarding with Callbacks causing TypeScript Errors

### ISSUE THREAD

**Issue by kwasimensah** [react-bootstrap/react-bootstrap#5243]
CodeSandbox Link: https://codesandbox.io/s/interesting-shannon-z5ief?file=/src/App.tsx

This generates type errors because the ref attribute. Its expecting string & (instance: HTMLDivElement|null) => void) (which I'm not sure is possible). 

I'm guessing there's something off with the use of & and types in https://github.com/react-bootstrap/react-bootstrap/blob/master/types/components/helpers.d.ts

**Comment by taion** [comment]
Huh, that's weird. Can you tell where the `string &` there is coming from?

**Comment by kyletsang** [comment]
Try this:

```
const ref = React.createRef<HTMLDivElement & Row>();

<Row ref={ref}>
```

**Comment by kwasimensah** [comment]
> Try this:
> 
> ```
> const ref = React.createRef<HTMLDivElement & Row>();
> 
> <Row ref={ref}>
> ```

This assumes I want to store the ref. I really just want to add listeners to the element and since React.fowardRef supports callback functions, I would expect react-bootstrap to allow them

**Comment by kyletsang** [comment]
You can apply the same typing pattern here as well:

```
<Row
  ref={(element: HTMLDivElement & Row) => {
    console.log("called ref");
  }}
>
```

**Comment by kwasimensah** [comment]
> You can apply the same typing pattern here as well:
> 
> ```
> <Row
>   ref={(element: HTMLDivElement & Row) => {
>     console.log("called ref");
>   }}
> >
> ```

So it really should work with HTMLDivElement | null  or it should be documented that this doesn't interact with React.forwardRef as expected. It looks like it's really close to allowing that. 

I think the bug really is that something in the logic in helpers.d.ts isn't doing the right thing. And it also looks like there isn't any Typescript code coverage per https://github.com/react-bootstrap/react-bootstrap/issues/4717 and https://github.com/react-bootstrap/react-bootstrap/issues/5148

**Comment by kyletsang** [comment]
There is currently a task to convert the codebase to typescript.  This will hopefully resolve these typing issues.

**Comment by kyletsang** [comment]
Ref typing should work properly in 1.1.1 now.

Tested with TS 3.9.6

**Comment by kwasimensah** [comment]
https://codesandbox.io/s/practical-leaf-udtx5?file=/src/App.tsx still shows errors with the latest react-bootstrap

**Comment by kyletsang** [comment]
> 
> 
> https://codesandbox.io/s/practical-leaf-udtx5?file=/src/App.tsx still shows errors with the latest react-bootstrap

I opened the sandbox on firefox and chrome and don't see any errors?

**Comment by kwasimensah** [comment]
I delete the reply. User error on my part (codesandbox seems to require a page refresh to load new versions of dependencies). Thanks for taking care of this!
