### ISSUE TITLE
Dynamically change the interval prop to stop or start auto-slide of the carousel.

### ISSUE THREAD

**Issue by azizurrahmaan** [react-bootstrap/react-bootstrap#5244]
Hello, I was trying to control the interval prop by the state of the element the that holds the carousel. But it seems like the interval prop is used only one time ( of initialization ), and does not affect the carousel to stop from sliding even when null is set to the interval prop afterwards. Can anybody help me how can I dynamically change the behavior (stop sliding / start sliding) of the carousel?

**Comment by taion** [comment]
Changes to the interval will propagate through, so you can just set `interval` to `null` to stop sliding.

**Comment by pulkit1991** [comment]
Can you please update the docs? The behavior of react-bootstrap/Carousel was a bit different from the original bootstrap one.

`<Carousel interval={false}>` 
or
`<Carousel pause={true}>`

doesn't work as per the docs and js src file.

**Comment by kyletsang** [comment]
The docs are correct here.  

`false` is not a valid value for `interval` - use `null` instead
`pause` controls the hover behavior for the carousel and the valid values are `hover` to enable pausing or `false` to disable this behavior.

See: https://react-bootstrap.github.io/components/carousel/#carousel-props
