### ISSUE TITLE
Failed to compile.  ./src/components/Home.jsx Attempted import error: 'Grid' is not exported from 'react-bootstrap'.

### ISSUE THREAD

**Issue by adutias** [react-bootstrap/react-bootstrap#5247]
import React, { Component } from 'react'
import { link } from 'react-router-dom';
import { jumbotron, Grid, Row, Col, Image, Button, Container} from 'react-bootstrap';
import './Home.css';

export default class Home extends Component {
    render() {
        return (
            <Grid>
                <jumbotron>
                    <h2>Welcome to Codelife.io</h2>
                    <p>This is how to </p>
                </jumbotron>
                <link to="/about">
                    <Button bsStyle="primary">About</Button>
                </link>
            </Grid>
        )
    }
}

**Comment by taion** [comment]
in v1, it's `<Container>`, not `<Grid>`
