### ISSUE TITLE
Type definition for BreadcrumbItem doesn't seem to match implementation

### ISSUE THREAD

**Issue by henningeiben** [react-bootstrap/react-bootstrap#5249]
## Describe the bug

While the implementation of the `linkProps` is being describes as "Additional props passed as-is to the underlying link for non-active items" and is declared as `PropTypes.object`, the types are declaring `React.LinkHTMLAttributes<HTMLLinkElement>`. This limits the `link` as being only a `HTMLLinkElement`.

## Expected behavior

If I pass `linkAs={Link}` I would like to specify `linkProps={{to:"/"}}` in order to pass `to:"/"` to the `Link` compontent of `react-router-dom`.

## Environment

- React-Bootstrap Version 1.0.1

## Additional context

When I change

```ts
export interface BreadcrumbItemProps {
  active?: boolean;
  href?: string;
  linkAs?: React.ElementType;
  target?: string;
  title?: React.ReactNode;
  linkProps?: React.LinkHTMLAttributes<HTMLLinkElement>;
}
```
to
```ts
export interface BreadcrumbItemProps {
  active?: boolean;
  href?: string;
  linkAs?: React.ElementType;
  target?: string;
  title?: React.ReactNode;
  linkProps?: any;
}
```
this seems more like the documentation.

**Comment by taion** [comment]
Hmm, it looks like we should probably doubly-template this and do something like `React.ComponentProps<LinkAs>`. Care to send in a PR?

**Comment by henningeiben** [comment]
I would love to - but I'm afraid ... at least currently I don't feel as deep into this. I don't really get, where I should make the adjustment you suggested 😊

And ... I just cloned the repo (for starters) and already fail to run the tests ☹

**Comment by henningeiben** [comment]
Awesome! So ... since this is in the master-branch, this is however not (yet) part of the official build, right? As far as I can tell version 1.1.1 does not include this commit.

**Comment by jquense** [comment]
that's right, it will get into the next release (soon)

**Comment by henningeiben** [comment]
BTW: the 1.2.0 version did solve this issue 😍
