### ISSUE TITLE
Freezing on modal close

### ISSUE THREAD

**Issue by tjirousek** [react-bootstrap/react-bootstrap#5250]
By clicking on close button the whole page is freezing.  There is an demonstration on video: 
https://youtu.be/lbmtsXNN07U

1. Go to: Open modal window (Live demo or Without animation on your page: https://react-bootstrap.github.io/components/modal/)
2. Click on Close button.
3. When the modal is closed then try to scroll page. It really does not work and it freezes for several seconds. 

- Operating System: [Android 10]
- Browser, Version [Chrome 83]
- React-Bootstrap Version [4.5]
- We tested it on these phones: Samsung S20+ and Huawei P30 Pro.

I tested this behavior on iPhone XS and also on older android devices with android 9 and older it seems that everything looks good. (also they have last Chrome 83)

**Comment by TedKoker** [comment]
I tested it on my phone which has android 10 and chrome 83, and it works fine...
Does the bug still occur?

**Comment by Latikeshnikam** [comment]
I don't see this issue anymore. Do we still see the bug?

**Comment by tjirousek** [comment]
Hello, I will test it later day. I let you know ASAP...Thx

čt 1. 10. 2020 v 12:50 odesílatel Latikeshnikam <notifications@github.com>
napsal:

**Comment by kyletsang** [comment]
Seems like this isn't a problem anymore as mentioned above?  Tried this on Android 11 with Chrome and it looks ok.

Will close this for now - please reopen if it's still an issue.
