### ISSUE TITLE
Keep multiple collapse open in accordian

### ISSUE THREAD

**Issue by sanjeeviraj** [react-bootstrap/react-bootstrap#5252]
I am grouping the data and displaying it in accordion collapse, Currently while open of one group others are getting collapsed. I want the card kept open unless toggling it directly. Is there a way to keep multiple collapse open?

**Comment by jquense** [comment]
You can use a collection of `Collapse` components together to get that behavior. The Accordion component doesn't do this, it's designed solely to implement the "one open at a time" behavior, since that requires a bit more manual state managing over using Collapse directly
