### ISSUE TITLE
Can I add Avatars to the components?

### ISSUE THREAD

**Issue by ronaklalwanii** [react-bootstrap/react-bootstrap#5253]
Hi, BootstrapVue has several custom components which are widely used in apps, like **Avatar**.

I was thinking we add some of those components in React Bootstrap too.

I can help you with the Avatar and some others.

Let me know...

**Comment by taion** [comment]
I think we want to limit this to just things that are present in upstream Bootstrap.

**Comment by brightertools** [comment]
I have also started using React.js and moved from using Vue and BootstrapVue, where there are more components and the Table component is more useful than the bootstrap one.

I appreciate the choice to limit react-bootstrap to what is present in bootstrap, this makes sense to keep things focused, however I think there is a great opportunity, given your number of users and supporters to extend this to additional components. These could be kept self contained or optional but some additional or more enhanced ones would be very useful.
