### ISSUE TITLE
Progress bar doesn't show up inside a Row element

### ISSUE THREAD

**Issue by andrewrhansen** [react-bootstrap/react-bootstrap#5254]
React-Bootstrap Progressbar doesn't show up inside of a Row element.  If the parent is a Col, it works.  But not a row.  Given its something that is horizontal, it seems like Row would be the one you'd want it in.

## To Reproduce

You can reproduce pretty easily just using the documentation sandbox: https://react-bootstrap.github.io/components/progress/

In the first example, put <Row> tags around the progress bar.  Then put <Col> tags around it.

## Expected behavior

Progressbar to show up.

**Comment by taion** [comment]
`<Row>`s are meant to hold `<Col>`s. That's their only use in the case of the grid system: https://getbootstrap.com/docs/4.5/layout/grid/

**Comment by andrewrhansen** [comment]
Ah, so you aren't supposed to just have something inside a row then, sorry about that. I'll close this, thanks.
