### ISSUE TITLE
From.Control include HTML Character Entity output

### ISSUE THREAD

**Issue by juunone** [react-bootstrap/react-bootstrap#5255]
## Describe the bug

i have api response string value it's include HTML Character Entity e.g. `&gt;` `&lt;`
than i use in **Form.Control** with value.
when i see that value it's have &#8203;
i dont know where that unicode appear in.
api response don't have any space string and &#8203;
but it's look like this `&gt;&#8203;`

## To Reproduce

1. api call
2. it's response like this 'hello world `&gt;`'
3. i render this value with *Form.Control*
4. See error 'hello world `&gt;&#8203;`'

## Expected behavior

i want to show value api response clearly 'hello world `&gt;`' without &#8203;

## Environment (please complete the following information)

- macOS
- Browser, Version [e.g. Chrome build ver 83.0.4103.106]
- React-Bootstrap Version 1.0.0

## Additional context

i don't know exactly it's Form.Control bug.
but want to advice from this problem.
thank you.

**Comment by kyletsang** [comment]
That's a "zero width space" char and this is not a form control bug.  Check your data source in your API and delete that char.
