### ISSUE TITLE
There's no information on borders, spacing and all normal utilities from normal bootstrap in the react-bootstrap website

### ISSUE THREAD

**Issue by DanielBakas** [react-bootstrap/react-bootstrap#5256]
## Is your feature request related to a problem? Please describe

There's no information on borders, spacing and all normal utilities from normal bootstrap in the react-bootstrap website.

## Describe the solution you'd like

Could you please add some documentation regarding these utilities? Thanks!

## Describe alternatives you've considered

The only alternative I have managed to get to work is to use normal html classes but that just undermines the whole effort of using react.

## Additional context

Nothing else. Thank you.

**Comment by taion** [comment]
This isn't currently part of the API, as these are just CSS classes with no "component"-like behavior. See discussion in https://github.com/react-bootstrap/react-bootstrap/issues/5152, though.
