### ISSUE TITLE
Update Badge.d.ts

### ISSUE THREAD

**Issue by makarkotlov** [react-bootstrap/react-bootstrap#5259]
## Describe the bug

TypeScript error when using "outline-primary", "outline-secondary" etc as variant prop for Badge component

## To Reproduce

1. Try to use "outline-primary" as variant prop for Badge component

## Expected behavior

No TypeScript errors

## Screenshots

![image](https://user-images.githubusercontent.com/32848434/86152029-43cf1a00-bb08-11ea-9a62-98a54b2c941f.png)

## Environment (please complete the following information)

- React-Bootstrap Version 1.0.1

## Additional context

I would've sent a pr if I had permissions. Maybe you should describe how to get permissions for contribution in the docs

**Comment by taion** [comment]
1. This doesn't seem to be a specified variant in https://getbootstrap.com/docs/4.5/components/badge/
2. You don't need special permissions to create a PR; you just make the branch in your fork and PR from there, as with any other repo

But for custom variants, see https://github.com/react-bootstrap/react-bootstrap/issues/4461
