### ISSUE TITLE
Default modal example causes entire app to re-render

### ISSUE THREAD

**Issue by jnmichaud** [react-bootstrap/react-bootstrap#5261]
I'm not sure whether I'm nit-picking, but this is giving me fits (and I'm going to have to figure out a way around it).
I'm not a very experienced react developer, so forgive me if this is off-base somewhere.

The default example given in the documentation (which returns both the modal and the button that activates it in the same return() block) normally causes the entire app to re-render when (as seems best practice) you include the modal at the highest level of the project.

That emphatically will not work for my project.

I can think of a couple ways around this (though I haven't yet explored using them) including using createPortal from reactDOM or possibly just using shouldComponentUpdate.

Can anybody tell me which would be preferred (and is there a better way to approach the problem?)

**Comment by kyletsang** [comment]
You can define your modal anywhere in your components since react-bootstrap uses `createPortal` internally to place the modal on the body.
