### ISSUE TITLE
Failed to compile. Attempted import error.

### ISSUE THREAD

**Issue by samja666** [react-bootstrap/react-bootstrap#5267]
I happened to reinstall my project workspace and I found that react start after npm install throws the below error. 

```
Failed to compile.

./node_modules/react-bootstrap/esm/index.js
Attempted import error: 'AccordionCollapseProps' is not exported from './AccordionCollapse'.
```
react-bootstrap: 1.1.0
bootstrap: 4.5.0

Last I checked was on 2-Jul-2020 and I did not observe this issue. 

I tried to `npm cache clean --force` but was not able to get it resolved.

**Comment by captain-igloo** [comment]
I'm getting a bunch of warnings.  See https://github.com/captain-igloo/react-bootstrap-bug.git .

Version 1.0.0-beta.12 is fine.

**Comment by anthony-zhou** [comment]
It also works if you roll back to react-bootstrap version v1.0.1:
`npm install react-bootstrap@1.0.1`

**Comment by samja666** [comment]
@anthony-zhou i am rolling back to 1.0.0. as i do not observe this issue there.

I am having the exact same issue with 1.0.1 as well
`"react-bootstrap": "^1.0.1"`

**Comment by samja666** [comment]
> It also works if you roll back to react-bootstrap version v1.0.1:
> `npm install react-bootstrap@1.0.1`
> 
> This seems like a problem with react-bootstrap v1.1.0. We're deploying our app with Vercel, so I ended up having to create a yarn.lock file (using `yarn install` and `yarn add react-bootstrap@1.0.1`) in order to successfully roll back the react-bootstrap version on the latest deployment.

@anthony-zhou i am rolling back to 1.0.0. as i do not observe this issue there.

I am having the exact same issue with 1.0.1 as well
"react-bootstrap": "^1.0.1"

**Comment by taion** [comment]
@jquense looks like the `FooProps` imports/exports made it into the compiled CJS code in 1.1.0: https://unpkg.com/browse/react-bootstrap@1.1.0/cjs/index.js

should we swap these out for `import type`/`export type` so TS doesn't do something weird?

**Comment by bennybennett** [comment]
I had the exact same problem, just FYI, same components listed in error. Reverted to v1.0.1 for the time being.

**Comment by peetss** [comment]
I ran into this as well.

**Comment by itasghar786** [comment]
Having the same issue

**Comment by dappsh** [comment]
I have the same issue, fixed by rolling back the version to 1.0.0

**Comment by itasghar786** [comment]
any idea ? I changed it to 1.0.0 still has the error 

Failed to compile
./node_modules/react-bootstrap/esm/index.js
Attempted import error: 'AccordionCollapseProps' is not exported from './AccordionCollapse'.

**Comment by letsgitcracking** [comment]
> any idea ? I changed it to 1.0.0 still has the error
> 
> Failed to compile
> ./node_modules/react-bootstrap/esm/index.js
> Attempted import error: 'AccordionCollapseProps' is not exported from './AccordionCollapse'.

Same problem here.

One thing I noticed though is that my VSCode is displaying the version of react-bootstrap incorrectly in package.json, whereas in notepad it's correct. Might be something to do with VSCode on windows?

**Comment by programmer-sachin-tiwari** [comment]
I also facing the same issue.. what is the solution/?

**Comment by programmer-sachin-tiwari** [comment]
> I happened to reinstall my project workspace and I found that react start after npm install throws the below error.
> 
> ```
> Failed to compile.
> 
> ./node_modules/react-bootstrap/esm/index.js
> Attempted import error: 'AccordionCollapseProps' is not exported from './AccordionCollapse'.
> ```
> 
> react-bootstrap: 1.1.0
> bootstrap: 4.5.0
> 
> Last I checked was on 2-Jul-2020 and I did not observe this issue.
> 
> I tried to `npm cache clean --force` but was not able to get it resolved.

---------------------------------



i was facing the same issue. try to install react-bootstrap@1.0.1 and start server again. It should be work now.

**Comment by yash17a** [comment]
**npm i react-bootstrap@1.0.1 --save** works well.

**Comment by rvmeode-fs** [comment]
uninstalling react-bootstrap then installing it again on v1.0.1 or v1.0.0 works.
`npm uninstall react-bootstrap
npm install react-bootstrap@1.0.1`

**Comment by cvitaa11** [comment]
I'm having the same issue. I tried to downgrade dependency to v 1.0.0-beta.6, 1.0.0 and 1.0.1 but the same error occured every time.

```
Creating an optimized production build...
Failed to compile.

./node_modules/react-bootstrap/esm/index.js
Attempted import error: 'AccordionCollapseProps' is not exported from './AccordionCollapse'.
```

**Comment by sachin8094** [comment]
Tried with different versions v1.0.0 and v1.0.1 and v1.1.0 still getting same error. This error has created big problem for me on the verge of release.

Creating an optimized production build...
Failed to compile.

./node_modules/react-bootstrap/esm/index.js
Attempted import error: 'AccordionCollapseProps' is not exported from './AccordionCollapse'.

**Comment by samja666** [comment]
> Tried with different versions v1.0.0 and v1.0.1 and v1.1.0 still getting same error. This error has created big problem for me on the verge of release.
> 
> Creating an optimized production build...
> Failed to compile.
> 
> ./node_modules/react-bootstrap/esm/index.js
> Attempted import error: 'AccordionCollapseProps' is not exported from './AccordionCollapse'.

@sachin8094 @cvitaa11  v1.0.1 should work fine. Ensure that you have not included the '^' or '~' symbol prefixed to the version number for react-bootstrap in package.json. Then delete the react-bootstrap folder from node_modules. do an npm install again. Then start the server.

**Comment by djnadackal** [comment]
> uninstalling react-bootstrap then installing it again on v1.0.1 or v1.0.0 works.
> `npm uninstall react-bootstrap`
> `npm install react-bootstrap@1.0.1`

This is the Solution

**Comment by letsgitcracking** [comment]
> > uninstalling react-bootstrap then installing it again on v1.0.1 or v1.0.0 works.
> > `npm uninstall react-bootstrap`
> > `npm install react-bootstrap@1.0.1`
> 
> This is the Solution

Thank this solution works for me.
