### ISSUE TITLE
Popover placement is misaligned when using "auto" OverlayTrigger placement, but only for the first time it is opened

### ISSUE THREAD

**Issue by dumbmatter** [react-bootstrap/react-bootstrap#5270]
## Describe the bug

If you have an OverlayTrigger with placement="auto" containing a Popover, then the first time it is displayed, the Popover arrow will be overlapping the target, rather than aligned to the edge as it is with other placements, such as placement="right".

This may be Popover-specific, because the problem does not occur with Tooltips.

## To Reproduce

1. Go to https://codesandbox.io/s/festive-jepsen-pfn07
2. Click on all four buttons
3. Observe that while the two tooltips (bottom two buttons) look identically aligned, the two popovers (top two buttons) do not. Specifically, the second one seems misplaced, overlapping the button too much.
4. Click the 2nd button twice more, closing the popover and opening it again.
5. Observe that now the 2nd popover is correctly aligned, unlike when it was first opened.

## Reproducible Example

Minimal example by using [CodeSandbox](https://codesandbox.io/s/festive-jepsen-pfn07).

## Expected behavior

The first time the placement="auto" popover is opened should look the same as it does the second time. The arrow should not overlap the trigger button.

## Screenshots

Screenshot after step 3, with the second popover misaligned (too far to the left, arrow overlaps the button):

![image](https://user-images.githubusercontent.com/828632/86706275-b6e2ff80-bfe4-11ea-90e7-0d27aa2f09ca.png)

Screenshot after step 5 (clicking the button twice more to close and open the popover again), with the second popover correctly aligned:

![image](https://user-images.githubusercontent.com/828632/86706854-543e3380-bfe5-11ea-8283-b4dd134038d2.png)

## Environment (please complete the following information)

- Operating System: Ubuntu 20.04
- Browser, Version: Chrome 83 and Firefox 78
- React-Bootstrap Version 1.1.0

**Comment by taion** [comment]
@jquense sounds like this is maybe an issue w/the margin calculation?

**Comment by jquense** [comment]
ugh probably

**Comment by ruhci28** [comment]
hye , can i work on this .?

**Comment by dumbmatter** [comment]
This issue is sufficiently annoying to me that I'd be happy to pay someone to fix it, if anyone is interested. No idea what's appropriate, because I don't know how hard it'd be. $200?

Alternatively, I might give it a shot at some point, but I'm sure I'd be much slower at figuring it out than someone familiar with the codebase :)

**Comment by dumbmatter** [comment]
Okay, $500. I'll pay $500 to anyone who fixes this bug.

**Comment by keisha-rw** [comment]
@dumbmatter - This was also driving me nuts.  I didn't fix the bug, but I did find a workaround.  Looking at the Popover component code, I found this line: https://github.com/react-bootstrap/react-bootstrap/blob/master/src/Popover.tsx#L135, which lead me here: https://github.com/twbs/bootstrap/blob/5c32767e0e0dbac2d934bcdee03719a65d3f1187/js/src/popover.js#L28.  With that, I wondered if changing the offset value in the popper config object would help and it does!
My code:
```
...
<OverlayTrigger
      trigger="click"
      placement="auto"
      overlay={popoverContent}
      onToggle={(nextShow) => {
        setIsPopoverOpen(nextShow);
      }}
      show={isPopoverOpen}
      popperConfig={{
        modifiers: [
          {
            name: 'offset',
            options: {
              offset: [10, 12]
            }
          }
        ]
      }}
    >
...
```
After adding that change, I no longer get the weird placement on the first trigger click.  You may need to tweak your offset values depending on your design.  Hopefully this helps!
