### ISSUE TITLE
Pagination.Prev / Pagination.Next complains with missing children in TypeScript

### ISSUE THREAD

**Issue by frankie567** [react-bootstrap/react-bootstrap#5272]
## Describe the bug

When using the `Pagination.Prev` / `Pagination.Next` components on their own, TypeScript complains that `children` prop is missing.

## Reproducible Example

https://codesandbox.io/s/react-typescript-nrdek?file=/src/index.tsx

## Expected behavior

TypeScript should not complain of missing children. This is the standard usage shown in the documentation : https://react-bootstrap.github.io/components/pagination/#pagination-more

## Environment (please complete the following information)

- Operating System: macOS 10.15.5
- Browser, Version : Chrome 83
- React-Bootstrap Version : 1.1.0
- TypeScript : 3.9.6

**Comment by taion** [comment]
We'd be happy to take a PR to fix this. `children` needs to be marked optional there.

**Comment by kyletsang** [comment]
This was fixed in commit 7b4c639314107b76d73fac2203fd38244e9812e2.

It's available in v1.1.1
