### ISSUE TITLE
DropdownButton alignRight property has been removed 

### ISSUE THREAD

**Issue by kwasimensah** [react-bootstrap/react-bootstrap#5278]
Still mentioned it the docs as https://react-bootstrap.github.io/components/dropdowns/#menu-alignment but removed from https://react-bootstrap.github.io/components/dropdowns/#dropdown-button-props

With the typescript rewrite DropdownButton probably needs to be explicit about passing it through to Dropdown

**Comment by scand1sk** [comment]
Also, `className` attribute on DropdownButton is no longer useable with TypeScript.

**Comment by MikeSha** [comment]
Why alignRight was removed?

BTW it still in docs but doesn't work

**Comment by kyletsang** [comment]
> 
> 
> Why alignRight was removed?
> 
> BTW it still in docs but doesn't work

This is fixed and available in 1.2.2
