### ISSUE TITLE
List of inputs of type email?

### ISSUE THREAD

**Issue by binarykitchen** [react-bootstrap/react-bootstrap#528]
How would you create a form element based on this library that can contain 1 to n inputs of type email? I mean, an input where the user can enter 1 to n email addresses?

**Comment by dozoisch** [comment]
How would you do it using plain html? From what I see, you'd have to have a dynamic form that adds input when one input is filled. Or you can use a textarea and let the user fill 1 email per row.

**Comment by binarykitchen** [comment]
ha, easy, use the HTML5 attribute `multiple` ... pretty underestimated:
- http://www.w3.org/TR/html-markup/input.email.html#input.attrs.multiple
- https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input

demo
http://www.wufoo.com/html5/types/1-email.html

can do textarea but using `multiple` is a lot better ... thx!

**Comment by AlexKVal** [comment]
You can do it as well with `miltiple` attribute in `<Input type='email' multiple />` component.

I've just checked:
```js
handleClick: function (e) {
  console.log(this.refs.email.getValue());
  console.log(React.findDOMNode(this.refs.emailHtml).value);
},
...
<Input
  ref='email'
  type='email'
  label='Email Address'
  placeholder='Enter email'
  multiple
/>
<input type='email' multiple ref='emailHtml' />
<Button onClick={this.handleClick}>Check</Button>
```
Then I fill both fields with: `a@a.com, b@b.com, c@c.com`
and in both cases get similar comma separated list of values: `a@a.com,b@b.com,c@c.com`

With ```<Input type='email' miltiple />``` `ReactBoostrap`
creates almost exactly ```<input type='email' multiple />``` HTML.

I hope it will help you.

**Comment by binarykitchen** [comment]
@AlexKVal thanks for your input - that works but I was rather thinking of a list of email fields. We have an use case here with more than 20 email addresses ... having them all on a long, very long one-lined input is not good.

**Comment by mtscout6** [comment]
If you are looking for a separate input per email address you can do something like this:

```
render() {
  let emailInputs = this.props.emails.map((email, index) => <Input type='email' defaultValue={email} key={index} />);

  return (
    <div>{emailInputs}</div>
  );
}
```

In that example I'm envisioning this.props.emails to be an array of emails. If you are wanting more than that than you are probably looking for a custom component that this library does not provide.

**Comment by binarykitchen** [comment]
Thank ... almost but I want a bit more. Will consider a custom component then.
