### ISSUE TITLE
Add Display component

### ISSUE THREAD

**Issue by proohit** [react-bootstrap/react-bootstrap#5280]
## Is your feature request related to a problem? Please describe

I couldn't seem to find a component for the [typography displays ](https://getbootstrap.com/docs/4.5/content/typography/#display-headings). I would have to write an h1 with a className, e.g. display-1.

## Describe the solution you'd like

Maybe a component which has configuration for which display size similar to how material-ui handled such variants:

```js
<Display variant="1">Hello, World!</Display>
```

## Describe alternatives you've considered
Maybe, if that's planned, wrap it inside a common typography component:
```js
<Typography variant="display1">Hello, World!</Typography >
```

or the more react-bootstrap style:
```js
<Typography.Display variant="1">Hello, World!</Typography.Display>
```

That way, maybe other features could be added as well (thinking of reusability).

EDIT: If this is approved and I find some spare time, I'm willing to take this on!

**Comment by taion** [comment]
let's consolidate discussion in https://github.com/react-bootstrap/react-bootstrap/issues/5280, which covers roughly the same space

**Comment by proohit** [comment]
I couldn't seem to find an issue regarding this topic. May you be so kind to update the hyperlink?

**Comment by taion** [comment]
Oops, meant to link to https://github.com/react-bootstrap/react-bootstrap/issues/5152
