### ISSUE TITLE
About Pagination PageItem onClick

### ISSUE THREAD

**Issue by Alexn555** [react-bootstrap/react-bootstrap#5285]
## Describe the bug

v 1.1.0 PageItem Pagination.Next doesn't have now property onClick
in version v 1.0.1 the behaviour is different (Typescript).

## To Reproduce

Put property onClick on PageItem component implementation

## Expected behavior

Should not give error that onClick is undefined property.

- Browser, Version [e.g. Chrome 83]

**Comment by jquense** [comment]
Try upgrading to the lastest

**Comment by kyletsang** [comment]
Dupe of #5277

**Comment by Alexn555** [comment]
Thanks, now works better  v 1.2.2
but for Pagination.Item it doesn't see still onClick
<Pagination.Item key={number} onClick={onChangeCb}>

**Comment by Alexn555** [comment]
<a href="#" onClick={(e: React.MouseEvent): void => { onChangeCb(e); }}>
          <Pagination.Item key={number} active={number === curPage}>
Works with wrapper, so I guess now no problem
