### ISSUE TITLE
Documentation doesn't load from the top level URL

### ISSUE THREAD

**Issue by anied** [react-bootstrap/react-bootstrap#5288]
## Describe the bug

Documentation doesn't load from the top level URL

## To Reproduce

1. Attempt to navigate to [https://react-bootstrap.github.io/](https://react-bootstrap.github.io/).

## Reproducible Example

Page doesn't load-- just a white screen is shown.

## Expected behavior

The documentation loads as normal

## Environment (please complete the following information)

I tested this on and off VPN from my work machine, as well as from my personal phone.  A colleague was able to reproduce as well on their own machine from a separate location.

## Additional context

The documentation homepage can be accessed indirectly.  For instance, if you navigate to the [Components/Alerts docs](https://react-bootstrap.github.io/components/alerts/) and then click the link for "Home" it will load.  However, if you then attempt to refresh on that URL it will fail again.

**Comment by nickmccurdy** [comment]
Is this just a botched deploy? I'm noticing 404s in production, but it runs fine in development. Someone with push/Netlify access could try restarting a build.

**Comment by jquense** [comment]
Very weird. It might be a bad deploy I'll try and restart it when I get a moment

**Comment by dilanustek** [comment]
This link works: react-bootstrap.netlify.app/. I assume this documentation is the same?

**Comment by CALLMELARE** [comment]
Thanks. I thought it was my problem and I blamed my ISP for an hour.

**Comment by jquense** [comment]
should be fixed now

**Comment by anied** [comment]
Thanks @jquense - I just verified that I can access it from the top-level domain now.
