### ISSUE TITLE
Extract mixins into own repository

### ISSUE THREAD

**Issue by khushkaran** [react-bootstrap/react-bootstrap#529]
I noted that in the docs it states:

`CollapsableMixin can be used to create your own components with collapse functionality.`

However, currently all mixins are within the `react-bootstrap` repo, to allow developers to develop custom components, the mixins may be a candidate for their own repo, rather than them having to include the entire `react-bootstrap` repo.

**Comment by mtscout6** [comment]
You are welcome to copy them to a separate module if you want. However, we would like to leave them hear for now to limit our number of dependencies. There's no huge benefit to pulling them out right now.
