### ISSUE TITLE
What changed React-bootstrap 1.0.1 to 1.2.2

### ISSUE THREAD

**Issue by cancng** [react-bootstrap/react-bootstrap#5293]
## Describe the bug
I am using WebStorm and IDE shows to me available components in the React bootstrap. But now react-bootstrap 1.2.2, my IDE does not show to me any suggestion, autocompletion. 

If I use `yarn add react-bootstrap@1.0.1` IDE completion still works. My problem is updated version.

![L4hotAC9ZE](https://user-images.githubusercontent.com/13858549/87301870-fcd62100-c518-11ea-9617-b9774519b387.gif)
![nupyqnwsa0](https://user-images.githubusercontent.com/13858549/87301873-fe074e00-c518-11ea-844b-32ed47fa4bda.gif)

**Comment by taion** [comment]
We rebuilt the package in TypeScript. I don't know what specifically would cause this, though – the package still works, so I'm not sure we can accept this as a bug here.

**Comment by kosmiq** [comment]
Have you tried emptying caches and reloading your IDE? I've been affected by this in VSCode with other packages, and a complete reloade have solved in (Reload window in VSCode, or going into the definitions for the package and have VSCode "rediscover" them)

**Comment by mattywong** [comment]
> We rebuilt the package in TypeScript. I don't know what specifically would cause this, though – the package still works, so I'm not sure we can accept this as a bug here.

We're experiencing the same issues as described by op except for vscode.

I'm not 100% sure what the solution is here, but looking closer in to it it looks like it might have to do with synthetic default imports.

The generated typings

```
// react-bootstrap/esm/Alert.d.ts
import React from 'react';

// changing to below gives us code completion, but we don't want to change every d.ts file
import * as React from 'react';
```

So it looks like currently if we want auto completion, we have to add the allowSyntheticDefaultImport flag in tsconfig.json

```
// tsconfig.json
{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true
  }
}
```

Which also fixes the issue but not sure if it's on the onus of the user to have to set this flag?

**Comment by kyletsang** [comment]
Fixed in v2 alpha
