### ISSUE TITLE
Netlify claims 1.0.1 is the current version

### ISSUE THREAD

**Issue by kosmiq** [react-bootstrap/react-bootstrap#5297]
## Describe the bug

Visit https://react-bootstrap.netlify.app/. Note that it claims to be version 1.0.1 instead of 1.2.2.

## To Reproduce

1. Go to https://react-bootstrap.netlify.app/
2. Note the version number

## Expected behavior

Netlify should output whatever is the latest in master.

## Screenshots

![Screenshot 2020-07-14 at 12 39 08](https://user-images.githubusercontent.com/322759/87416477-0cb03c80-c5cf-11ea-8557-f1c950448886.png)

**Comment by bpas247** [comment]
I went ahead and triggered a manual build to update the netlify deployment, but I'm still not sure why our builds stopped triggering automatically.

**Comment by 3scava1i3r** [comment]
Now we have this rectified so i think this issue should be closed
![image](https://user-images.githubusercontent.com/52003051/88573476-6fd5b080-d05e-11ea-9554-4203ef26497d.png)
