### ISSUE TITLE
Accordion

### ISSUE THREAD

**Issue by anisch** [react-bootstrap/react-bootstrap#5298]
## Describe the bug

Cannot open Accordion.Collapse when eventKey={0}.

## Reproducible Example

https://codesandbox.io/s/react-bootstrat-jjlqg

## Expected behavior

The Accordion.Collapse should open when eventKey={0}. 

## Environment (please complete the following information)
- Windows 10 OS Version 1909 (Build 18363.900)
- Vivaldi | 3.1.1929.45 (Stable channel) (64-Bit); MS-Edge Version 83.0.478.64 (Offizielles Build) (64-Bit)
- React-Bootstrap 1.2.2

**Comment by kyletsang** [comment]
`eventKey` should be a string.
