### ISSUE TITLE
Documentation improving, importing tip is false

### ISSUE THREAD

**Issue by Addeuz** [react-bootstrap/react-bootstrap#5299]
Hello!

I would like to start of by saying that I haven't done a lot of testing about this issue but it is just something I found after reading the [getting started introduction](https://react-bootstrap.netlify.app/getting-started/introduction#importing-components) to react-bootstrap. It says that you should import your stuff by doing the `import Button from 'react-bootstrap/Button';` way rather than the `import { Button } from 'react-bootstrap';` way. I've always done the latter way because I find it more neat to only have one line.

But since I read that the team prefers doing it the first way I decided to check out what the real difference in size was of the two different ways of importing.

And by using the VS Code extension [Import Cost](https://marketplace.visualstudio.com/items?itemName=wix.vscode-import-cost) I found out that importing in a selective way (second) actually became a smaller total size than doing it by importing each submodule way (first).

Check these screenshots out:
![image](https://user-images.githubusercontent.com/12641358/87437588-d2569780-c5ee-11ea-983a-2273308acdc7.png)
Total of 13.1 Kb

![image](https://user-images.githubusercontent.com/12641358/87437664-eac6b200-c5ee-11ea-93a8-97c72b42259b.png)
Total of 17.8 Kb

I know that this is a very small test but it is all that I have time for atm. If someone wants to check it out further that would be great.

The team probably has tried this extensively and found out that in the long run the submodule way might be smaller. But just with these components that I use quite frequently the case was the other way round.

Best,
Andreas

**Comment by jquense** [comment]
Those numbers are misleading because each import size is not taking into account that each import is sharing some common dependencies. Also the main import is likely wrong, or we got lucky with tree shaking bc there is a chance that it's actually importing the entirety of bootstrap not just the Form. It will depend on the bundler you use

**Comment by Addeuz** [comment]
Okay, that makes sense. 

I'm closing the issue now!
