### ISSUE TITLE
How to remove the Arrow icon from Input type='select'?

### ISSUE THREAD

**Issue by agile116** [react-bootstrap/react-bootstrap#530]
How to remove the Arrow icon from Input type='select'? Is that possible to change that icon to a custom one?

**Comment by AlexKVal** [comment]
Did you mean this arrow ? 
On the image Chrome Safari Firefox
![arrow](https://cloud.githubusercontent.com/assets/847572/7202914/653cda20-e51f-11e4-8995-8a8773f66aed.png)

This arrow is added by browser itself when you use 
```
<select></select>
```
element, which is used by `react-bootstrap` in your case 
```
<Input type='select'>.
```

You can read more here https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select

**Comment by agile116** [comment]
Thank you for your reply.

**Comment by mtscout6** [comment]
@agile116 Does that resolve your concern? Do we need to keep this issue open?

**Comment by agile116** [comment]
Please close it. Is there any components that I can use for a simple combobox?

杨小林

**Comment by AlexKVal** [comment]
As far as I know there is only one  `combobox`-like native html element ```<select>```.
But as well you can try to search for you need by the phrase `html combobox like element` in Google.
I hope it will help.

**Comment by agile116** [comment]
Thanks. :)


杨小林

**Comment by msafrin3** [comment]
f*** u all.. there's a solution. 
-webkit-appearance: none

**Comment by DavidCodeRussia** [comment]
For any one who struggle like me last a couple of hours. Trying to remove arrow bottom from <select> which is going out of the box when you use <select> tag. Set the "appearance: none;" on <select> in css and arrow bottom will go away. Source: 
1. https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select
2. https://developer.mozilla.org/en-US/docs/Web/CSS/appearance
