### ISSUE TITLE
Pagination TypeScript typings are missing href

### ISSUE THREAD

**Issue by hueter** [react-bootstrap/react-bootstrap#5300]
## Describe the bug

The pagination components TypeScript typings do not have an `href` despite leveraging `SafeAnchor` under the hood.

```
Property 'href' does not exist on type 'IntrinsicAttributes & PageItemProps'
```

Wrapping the component in an anchor tag gives a validate DOM nesting error from React because an anchor cannot be a child of an anchor. 

## To Reproduce

```
<Pagination.Item href="https://react-bootstrap.github.io/" />
```

## Reproducible Example

https://codesandbox.io/s/vigorous-napier-d7mv0?file=/src/App.tsx

## Expected behavior

Apply the `href` prop to the underlying anchor tag and have the typings reflect that the pagination components are anchors.

## Environment (please complete the following information)

- Operating System: macOS
- Browser, Version: Chrome 84
- React-Bootstrap Version: 1.2.2

**Comment by taion** [comment]
We'd be happy to take a PR for this.
