### ISSUE TITLE
"import 'bootstrap/dist/css/bootstrap.min.css" cannot take effct

### ISSUE THREAD

**Issue by songyuc** [react-bootstrap/react-bootstrap#5303]
## Describe the bug

"import 'bootstrap/dist/css/bootstrap.min.css" cannot take effct in [electron-react-boilerplate](https://github.com/electron-react-boilerplate/electron-react-boilerplate).

## To Reproduce

1. Git clone the [electron-react-boilerplate](https://github.com/electron-react-boilerplate/electron-react-boilerplate);
2. Install Bootstrap using `yarn add react-bootstrap bootstrap`;
3. Change the code of HomePage.tsx as,
```js
import React from 'react';
import 'bootstrap/dist/css/bootstrap.min.css';

export default function HomePage() {
  return (
    <div className="container-fluid">
      <div className="row">
        <div className="col-3 bg-light left-panel">
          <h1>this is the left</h1>
        </div>
        <div className="col-9 bg-primary right-panel">
          <h1>this is the right</h1>
        </div>
      </div>
    </div>
  );
}
```
4. Run as `yarn dev`

5. And the Bootstrap didn't work as,
![图片](https://user-images.githubusercontent.com/27288110/87409564-aee41a80-c5f7-11ea-806a-b1ee57ff7d49.png)

## Reproducible Example

Minimal example by using [CodeSandbox](https://codesandbox.io/s/github/react-bootstrap/code-sandbox-examples/tree/master/basic).

## Expected behavior

I hope to get the result as,
![图片](https://user-images.githubusercontent.com/27288110/87411824-d5f01b80-c5fa-11ea-9096-ee5772399adf.png)

## Environment (please complete the following information)

- Operating System: Windows 10
- Electron
- React-Bootstrap Version 1.2.2

**Comment by taion** [comment]
In your example, you're not even using React-Bootstrap... this doesn't seem relevant to this library.
