### ISSUE TITLE
Add DropdownMenu responsive alignment

### ISSUE THREAD

**Issue by kyletsang** [react-bootstrap/react-bootstrap#5304]
https://getbootstrap.com/docs/4.5/components/dropdowns/#responsive-alignment

Thinking of using these props:

`alignRight`: boolean | 'sm' | 'md' | 'lg' | 'xl'
`alignLeft`: 'sm' | 'md' | 'lg' | 'xl'

cc @react-bootstrap/collaborators

**Comment by jquense** [comment]
maybe something like the responsive props on Col? that way you can't specify bad combos, e.g. `align={{ 'sm': left', lg: 'right' }}` keep alignRight around for back compat?

**Comment by kyletsang** [comment]
> 
> 
> maybe something like the responsive props on Col? that way you can't specify bad combos, e.g. `align={{ 'sm': left', lg: 'right' }}` keep alignRight around for back compat?

Sounds good to me

**Comment by kyletsang** [comment]
Done in #5307
