### ISSUE TITLE
Add .dropdown-item-text support

### ISSUE THREAD

**Issue by kyletsang** [react-bootstrap/react-bootstrap#5306]
https://getbootstrap.com/docs/4.5/components/dropdowns/#menu-items

> You can also create non-interactive dropdown items with .dropdown-item-text.

`text` prop?

cc @react-bootstrap/collaborators

**Comment by taion** [comment]
could also be `Dropdown.Text` or `Dropdown.TextItem`, by analogy with `Dropdown.Divider`? might make the typing slightly cleaner/easier

**Comment by kyletsang** [comment]
Sounds good!  What about `<Dropdown.ItemText>` to be closer to class name?   :p

**Comment by taion** [comment]
oh, interesting. i see that it's e.g. `.dropdown-divider`. maybe the `text` prop does make sense? do you need to do `.dropdown-item .dropdown-item-text` or is it just `.dropdown-item-text`?

... then again we probably don't want the default `<SafeAnchor>` behavior any more anyway.

i dunno on the component name. do whatever you think feels best

**Comment by kyletsang** [comment]
Just a single class for this one `.dropdown-item-text`.  You're right, it's easier to just use `createWithBsPrefix`
