### ISSUE TITLE
Convert all .js to Typescript in www (the frontend docs)

### ISSUE THREAD

**Issue by tanmaylaud** [react-bootstrap/react-bootstrap#5310]
It will great to have all the files in www/src in TypeScript

**Comment by sankita15** [comment]
I have a question here, why there is a need to convert js files to typescript?

**Comment by tanmaylaud** [comment]
@sankita15 , Typescript provides you with rules on the object types and assists the developer in catching bugs/errors early in the development. Javascript alone does not provide that.
Also, it helps the next developer to better understand the codeflow (the control flow of data with data types, the type of value a function can accept , the return types, etc.)

**Comment by sankita15** [comment]
@tanmaylaud  I can pick it up if someone is interested in pairing up with me, as there are lot of files of convert to typescript.
