### ISSUE TITLE
The responsive Table section on the docs ui is not responsive (unless window is too small)

### ISSUE THREAD

**Issue by tanmaylaud** [react-bootstrap/react-bootstrap#5313]
## Describe the bug

When we go to [Docs UI Responsive Table](https://react-bootstrap.github.io/components/table/#table-responsive), we see that the Table example is not responsive unless the window is made too small. This may not be apparent for beginners and new users. Hence, new users may not get to know the beauty of responsive tables

## To Reproduce

1. Go to [Docs UI Responsive Table](https://react-bootstrap.github.io/components/table/#table-responsive)
2. Try to scroll horizontal
3. Not scrollable

## Expected behavior

We need to add more columns to the example ( may be 50 ) to show the power of React Boostrap.

It will good to add more columns to the Table (without making the example code lengthy) so that the Table is responsive

**Comment by kyletsang** [comment]
Resolved by #5314
