### ISSUE TITLE
<Badge> doesn't accept multiple text segments

### ISSUE THREAD

**Issue by glenjamin** [react-bootstrap/react-bootstrap#532]
This is possibly a slightly unusual use-case, but the behaviour is still surprising.

```jsx
<Badge>£10</Badge>
```

Probably similar to #296

**Comment by mtscout6** [comment]
That's an unfortunate bug. Can you submit a PR with some tests for this use case?

**Comment by AlexKVal** [comment]
My two cents into it:

That way
```js
React.createElement(Badge, null, "£10")
```
it's working.

In my trash project which using `browserify`
```jsx
<Badge>£10</Badge>
```
it is also working.

But if I put jsx version straight into `docs/examples/Badge.js` and then
```sh
npm run docs
open http://localhost:4000
```
it doesn't render.

I'll check the state of the issue after I'm finished that I'm already working with,
and if it has no progress yet, I'll try to fix it.

**Comment by glenjamin** [comment]
Eugh, sorry, I screwed up my example. This is the actual failing case (renders empty).

```jsx
<Badge>€{num}</Badge>
```

I'll do a PR with tests and a fix.
