### ISSUE TITLE
Add ability to set individual table column widths/max widths from <th> in table head

### ISSUE THREAD

**Issue by lblair16** [react-bootstrap/react-bootstrap#5320]
## Is your feature request related to a problem? Please describe

I'm unable to set the width of columns from the table head, I need this to be able to format my table consistently.

## Describe the solution you'd like

The ability to add a prop (width, maxWidth, minWidth) to individual th components in a table

## Describe alternatives you've considered

If there is already an alternative way to do this through styling please let me know, I was unable to find an existing solution.

## Additional context

Something similar to this would be useful:
![image](https://user-images.githubusercontent.com/31866368/88196665-75229d80-cc0f-11ea-8546-d6251ff4cdfc.png)

**Comment by jquense** [comment]
not sure what you are asking for here, the `th` elements aren't bootstrap ones, they are HTML tags and can be styled using css or inline styles.

**Comment by lblair16** [comment]
Ah, my mistake. I misread the documentation. Thanks
