### ISSUE TITLE
Not Able to Scroll the Sidenav in the documentation

### ISSUE THREAD

**Issue by deepakgupta191199** [react-bootstrap/react-bootstrap#5323]
## Describe the bug

There is no way to scroll the sidenav of the documentation. I am not able to navigate through all the components section in my normal screen resolution. 

## To Reproduce

1. Go to 'https://react-bootstrap.github.io' on your desktop
2. Click on 'Components'
3. See the SideNav

**Comment by taion** [comment]
duplicate of https://github.com/react-bootstrap/react-bootstrap/issues/3765
