### ISSUE TITLE
DropDown button not applying transform properly in Android WebView. Works fine in mobile browsers.

### ISSUE THREAD

**Issue by MishalValiyakath** [react-bootstrap/react-bootstrap#5325]
When we use the DropDown in NavBar, it opens to the right if there is space on the right and it opens to the left if the screen is smaller and there is no enough space on the right. It works perfectly in a Desktop browser normal mode and Responsive mode. Also, it works fine in all the mobile browsers including Chrome and Safari. However, when I tried to render the same website in a WebView in an Android App, the drop-down tries to render towards the right side always even though there is no enough space, which causes the rest of the content to push towards the left of the screen, as you can see in the screenshot.
![WhatsApp Image 2020-07-24 at 2 39 54 PM](https://user-images.githubusercontent.com/15728918/88397563-05054a80-cdbc-11ea-9b90-191968d3189b.jpeg)

**Comment by MishalValiyakath** [comment]
Adding the menu closed view to set the context of the issue. The WebView is set to match parent width and height.

![WhatsApp Image 2020-07-24 at 2 44 55 PM](https://user-images.githubusercontent.com/15728918/88397783-5b728900-cdbc-11ea-8e17-8ff2ef5c6e47.jpeg)

**Comment by taion** [comment]
Does this work properly with upstream Bootstrap?

**Comment by kyletsang** [comment]
Closed due to inactivity
