### ISSUE TITLE
UI is breaking for me on tooltip.

### ISSUE THREAD

**Issue by syadav214** [react-bootstrap/react-bootstrap#5329]
UI is breaking for me on tooltip.

![image](https://user-images.githubusercontent.com/24729891/88470290-44e14480-cf18-11ea-9c07-e085fd21624d.png)

_Originally posted by @syadav214 in https://github.com/react-bootstrap/react-bootstrap/pull/5316#issuecomment-663928463_

**Comment by jquense** [comment]
Please produce a reproduction of the your issue in codesandbox or similar

**Comment by taion** [comment]
Closing for lack of repro
