### ISSUE TITLE
Problems with loading accordian from react-bootstrap

### ISSUE THREAD

**Issue by jo3005** [react-bootstrap/react-bootstrap#5335]
## Describe the bug

I have implemented the Accordian component but the website won't compile.  The following error is returned: 

./src/components/containers/ItemObject/index.js
Attempted import error: 'Accordian' is not exported from 'react-bootstrap'.

I have tried to clear the cache as in previous error reports and have uploaded to version 1.3.0 of react-bootstrap.  My other dependencies are as follows:
"dependencies": {
    "@fortawesome/fontawesome-svg-core": "^1.2.30",
    "@fortawesome/free-brands-svg-icons": "^5.14.0",
    "@fortawesome/free-regular-svg-icons": "^5.14.0",
    "@fortawesome/free-solid-svg-icons": "^5.14.0",
    "@fortawesome/react-fontawesome": "^0.1.11",
    "bootstrap": "^4.5.0",
    "font-awesome": "^4.7.0",
    "react": "^16.13.1",
    "react-bootstrap": "^1.3.0",
    "react-dom": "^16.13.1",
    "react-fontawesome": "^1.7.1",
    "react-router-dom": "^5.2.0",
    "react-scripts": "3.4.1"
  },

## Reproducible Example

Minimal example by using [CodeSandbox](https://codesandbox.io/s/github/react-bootstrap/code-sandbox-examples/tree/master/basic).

## Expected behavior

Component should be loaded from the library.

## Screenshots
![image](https://user-images.githubusercontent.com/19179916/88625994-6ab74680-d0dc-11ea-9884-666925afdcbc.png)

## Environment (please complete the following information)

- Operating System: Windows 10
- Browser, Version - Multiple browsers
- React-Bootstrap Version 1.3.0

## Other information

Affected components:
[componentst.zip](https://github.com/react-bootstrap/react-bootstrap/files/4986305/componentst.zip)

**Comment by kyletsang** [comment]
You have a typo in `Accordion`.

Use this:
`import Accordion from 'react-bootstrap/Accordion'`
