### ISSUE TITLE
NavDropdown alignRight failing on typescript check

### ISSUE THREAD

**Issue by xiaohong3** [react-bootstrap/react-bootstrap#5339]
## Describe the bug

I updated react-bootstrap from 1.0.1 to 1.3.0, after that my component is failing typescript (3.9.7) checking.
I have a component:
```
<NavDropdown
  title="title"
  id="basic-nav-dropdown"
  alignRight={true}
>
...
</NavDropdown>
```
And it complains on the alignRight property:
`Property 'alignRight' does not exist on type 'IntrinsicAttributes & Pick<Pick<DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>, "slot" | ... 253 more ... | "is"> & { ...; }, "ref" | ... 250 more ... | "is"> & BsPrefixProps<...> & NavDropdownProps & { ...; }'`

I checked types of 1.0.1, the NavDropdown is defined differently (extends from Dropdown component which has alignRight prop).

## Expected behavior

Run-time seems to be working just fine (when you have alignRight the dropdown menu will align correctly).
However, react-scripts build will fail because typescript check failed.
I think the NavDropdown should extends Dropdown's properties in this case?

## Environment (please complete the following information)

- Operating System: Linux mint 20
- Browser, Version Chromium Version 84.0.4147.89
- React-Bootstrap Version 1.3.0

**Comment by taion** [comment]
Makes sense to me. Want to send in a PR?

**Comment by xiaohong3** [comment]
I'd love to.
I checked the [NavDropdown](https://github.com/react-bootstrap/react-bootstrap/blob/master/src/NavDropdown.tsx) component, and find that it extends `BsPrefixPropsWithChildren` but not `Dropdown` (although Dropdown extends BsPrefixPropsWithChildren too).
I am not very familiar with the code, so I need to ask: Is NavDropdown a full extension of Dropdown? Like it should contain all of Dropdown's props and some more

**Comment by xiaohong3** [comment]
Oh sorry, I closed the issue accidentally. Not very familiar with the github community, only use it to see if any of my bugs are reported, this is my first time reporting anything.
I'd love to give it a try.

**Comment by taion** [comment]
It can/should extend all of those interfaces. See e.g. the very similar https://github.com/react-bootstrap/react-bootstrap/blob/521fd9276c17532d382bc4dedd87844894da36dd/src/DropdownButton.tsx#L8-L17
