### ISSUE TITLE
onSubmit on Form is broken

### ISSUE THREAD

**Issue by uicodefr** [react-bootstrap/react-bootstrap#5352]
With the last version, I have the error:
```
Type '(e?: FormEvent<HTMLFormElement> | undefined) => void' is not assignable to type '(event: FormEvent<HTMLElement>) => void'.  TS2322

    165 |               <Formik enableReinitialize onSubmit={this.handleSendSubmit} initialValues={initValues}>
    166 |                 {({ values, errors, handleChange, handleBlur, handleSubmit }) => (
  > 167 |                   <Form className="formMessage" onSubmit={handleSubmit}>
        |                                                 ^
    168 |                     <div className="textZone">
```

My code hasn't changed, I just upgraded react-bootstrap.

I think the bug is related to this issue: [onSubmit and onChange prop typings are broken for form and form control elements #5037](https://github.com/react-bootstrap/react-bootstrap/issues/5037)
After checking the pull request, I think we should replace in the component "Form.tsx":
```
export interface FormProps
  extends React.HTMLAttributes<HTMLElement>
```
By
```
export interface FormProps
  extends React.HTMLAttributes<HTMLFormElement>
```

**Comment by taion** [comment]
Sounds reasonable to me. Want to send in a PR?

**Comment by kyletsang** [comment]
Fixed by #5353

**Comment by andreareginato** [comment]
@taion I've a question. Is there any way to apply the change in master in the current application? I installed the package with the Github master branch code, but it's not working.

@kyletsang is there any chance to have a new version released soon? I would love to help to make this happen, if I can do anything.

**Comment by kyletsang** [comment]
@jquense, when you have time, could you publish a new version?  Thanks :)
