### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by shawnnolanjr** [react-bootstrap/react-bootstrap#5355]
## Describe the bug
After importing
```import { Nav, Navbar, Form, FormControl, Button } from 'react-bootstrap';```

I get the following error,
```
/Users/WebstormProjects/woodys/node_modules/react-bootstrap/esm/index.d.ts
TypeScript error in /Users/WebstormProjects/woodys/node_modules/react-bootstrap/esm/index.d.ts(2,1):
Declaration or statement expected.  TS1128

    1 | export { default as Accordion } from './Accordion';
  > 2 | export type { AccordionProps } from './Accordion';
      | ^
    3 | export { default as AccordionContext } from './AccordionContext';
    4 | export { default as AccordionCollapse } from './AccordionCollapse';
    5 | export type { AccordionCollapseProps } from './AccordionCollapse';
```

## To Reproduce
Just import ```import { Nav, Navbar, Form, FormControl, Button } from 'react-bootstrap';``` and try using ```<Navbar bg="light" variant="light">
					<Navbar.Brand href="#home">Navbar</Navbar.Brand>
					<Nav className="mr-auto">
						<Nav.Link href="#home">Home</Nav.Link>
						<Nav.Link href="#features">Features</Nav.Link>
						<Nav.Link href="#pricing">Pricing</Nav.Link>
					</Nav>
					<Form inline>
						<FormControl type="text" placeholder="Search" className="mr-sm-2"/>
						<Button variant="outline-primary">Search</Button>
					</Form>
				</Navbar>```

## Reproducible Example

Minimal example by using [CodeSandbox](https://codesandbox.io/s/github/react-bootstrap/code-sandbox-examples/tree/master/basic).

## Environment (please complete the following information)

- Operating System: [e.g. macOS]
- Browser, Version [e.g. Chrome 74]
- React-Bootstrap Version [e.g. 1.0.0-beta.8]

**Comment by shawnnolanjr** [comment]
this actually fixed the problem for me... https://github.com/react-bootstrap/react-bootstrap/issues/5281#issuecomment-655757039

**Comment by kyletsang** [comment]
React-Bootstrap needs a minimum version of TS 3.8 for the type exports feature
