### ISSUE TITLE
Prevent OverlayTrigger from fading out when mouse is inside the overlay

### ISSUE THREAD

**Issue by AdityaAnand1** [react-bootstrap/react-bootstrap#5364]
https://react-bootstrap.github.io/components/overlays/

So, right now `delay` prop handles how long until the overlay appears AND how long till it disappears when mouse is outside the triggering component.

These should ideally be two seperate things. My use case is that, I have a bunch of interactable elements within the popover (within OverlayTrigger) and when I go to actually interact with it, the overlay fades away. It doesn't care that the mouse is within the overlay.

Is there a way to fix this?

**Comment by AdityaAnand1** [comment]
Sorry, closed this prematurely when I discovered `delay={{show: 500, hide: 1000}}`, thought it'd solve the problem, but nope.

I would like the popover to forever remain open while the mouse is within the overlay popover. Is there a way to do this?

**Comment by taion** [comment]
If you need to do this, set `container` on the such that it's nested under the triggering element in the DOM, such that mousing over the overlay won't trigger a "mouseleave" event.

**Comment by AdityaAnand1** [comment]
So essentially the `container` prop of the OverlayTrigger should be a child of <OverlayTrigger/>?

This has the side effect of inserting the overlay into child DOM tree, i.e, it gets chopped when overflow is hidden, or expands the scrollbar. Doesn't seem stable.

Can you please point me to an example that demonstrates this? Also, let's keep the issue open until it is solved.
