### ISSUE TITLE
Docs misleading for .navbar-expanded and .form-inline

### ISSUE THREAD

**Issue by abdelrahmantoptal** [react-bootstrap/react-bootstrap#5374]
## Describe the bug
This affects the docs, the flex-wrap is incorrect for xs to md screens

## To Reproduce

1. Go to https://react-bootstrap.github.io/components/navbar/#navbars-colors
2. View the section Color Schemes with screen width less than 1000px
3. See how the navbar not wrapping on xs to md screens, while the form-inline wrapping is causing unpleasant wrapping.

## Expected behavior

It should wrap using breakpoints for flex-{pb}-wrap

## Screenshots
![image](https://user-images.githubusercontent.com/20311318/89723224-bf6b9300-d9f3-11ea-94b2-c00ae3fd413f.png)

## Environment (please complete the following information)

-Viewing docs of version v1.3.0 (Bootstrap 4.5)

## Additional context
I found that .form-inline has `flex-flow: row wrap` and .navbar-expand has `flex-flow: row nowrap`
I could get it looking ok by adding `flex-wrap flex-lg-nowrap` to .navbar-expand, while adding `flex-nowrap flex-lg-wrap` to .form-inline (effectively reversing wrapping for small to medium screens, while keeping the defaults for large to x-large screens

**Comment by taion** [comment]
This happens on https://getbootstrap.com/docs/4.5/components/navbar/ as well – it's just a CSS issue, and is out of scope here.
