### ISSUE TITLE
Question: dynamically style theme in realtime?

### ISSUE THREAD

**Issue by thebarty** [react-bootstrap/react-bootstrap#5377]
Hi guys,

I am writing an web-application, where users can log int. 

I want each user to be able to pick his favourite primary color via a color picker. After picking the css-theme needs to adapt, p.e. change the colours of fonts, buttons, backgrounds, etc.

Any way to do this with react-bootstrap?

**Comment by taion** [comment]
You can use `ThemeProvider` to map component "prefixes" dynamically: https://github.com/react-bootstrap/react-bootstrap/blob/master/src/ThemeProvider.tsx
