### ISSUE TITLE
Nav.Link breaking child input components

### ISSUE THREAD

**Issue by Pacheco95** [react-bootstrap/react-bootstrap#5378]
## Describe the bug

When using the `Nav > Nav.Link` component as a wrapper component, the children input components stopped to work as expected.

## To Reproduce

1. Create a component with this html
```
<Nav>
  <Nav.Link>
    <input type="checkbox" />
  </Nav.Link>
</Nav>
```
2. Trying to tick the checkbox with any success
3. Replace Nav.Link to a single div
4. Trying to tick the checkbox and... voilá... working as it should

The same problem occurs with input type that does not open the select file window and also with datepickers that do not open the popup window to select a date.

## Reproducible Example

Minimal example by using [CodeSandbox](https://codesandbox.io/s/github/react-bootstrap/code-sandbox-examples/tree/master/basic).

## Expected behavior

When using Nav.Link the checkbox should work as expected

## Environment (please complete the following information)

- Operating System:
```
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```
- Browser: Google Chrome Version 84.0.4147.105 (Official Build) (64-bit)
- React-Bootstrap Version ^1.0.1

**Comment by taion** [comment]
Nav.Link is for links; see https://react-bootstrap.github.io/components/navbar/#navbars-form if you're trying to embed inputs inside e.g. navbars

**Comment by taion** [comment]
or use `<Nav.Item>`
