### ISSUE TITLE
Invalid Hook Call Warning

### ISSUE THREAD

**Issue by MenschenToaster** [react-bootstrap/react-bootstrap#5380]
## Describe the bug

Hey,
react Bootstrap is not working for me :(
I am getting "Invalid hook call" errors...

It only throws this error when react-bootstrap is installed.
It works fine without... I am also using Electron and yarn if that matters.

I posted this on the reactiflux discord yesterday but I think I will get a response here more quickly and people on the Internet may find it on GitHub more easily.

I don't know what I should do :(

## To Reproduce

I will just describe what I did to my React electron system.

1. Add react-boostrap via yarn
2. Implement this from the React documentation

```
// Add this in node_modules/react-dom/index.js
window.React1 = require('react');

// Add this in your component file
require('react-dom');
window.React2 = require('react');
console.log(window.React1 === window.React2);
```
It will print out false when react-boostrap is installed

## Expected behavior

It should print true and the react-boostrap elements should render

## Screenshots

http://prntscr.com/tydrqd

## Environment (please complete the following information)

- Operating System: [Windows]
- Browser, Version [Chrome via. Electron]
- React-Bootstrap Version [^1.3.0]

## Additional context

package.json: https://pastebin.com/2WG9qT3i
my .yarnrc:
network-timeout 500000

**Comment by MenschenToaster** [comment]
https://github.com/react-bootstrap/react-bootstrap/issues/3965 This didn't help me btw.

**Comment by MenschenToaster** [comment]
The generated index.html:
`
<!DOCTYPE html>
    <html>
      <head>
        <meta charset="utf-8">
      <title>VirtualClient-Launcher</title><script>require("source-map-support/source-map-support.js").install()</script><link href="styles.css" rel="stylesheet"></head>
      <body>
        <div id="app"></div>
      <script src="renderer.js"></script></body>
    </html>`

**Comment by MenschenToaster** [comment]
My tsconfig.json
```
{
  "compilerOptions": {
    "jsx": "react",
    "noUnusedLocals": false,
    "baseUrl": ".",
    "paths": {
      "@/*": ["src/main/*"],
      "common/*": ["src/common/*"]
    }
  },
  "extends": "./node_modules/electron-webpack/tsconfig-base.json"
}

```

**Comment by jquense** [comment]
you have more than one React or react-dom installed. Even if you are certain that's not it, 99% of the time it's the problem, and isn't always obvious where it is. It may be a bad yarn.lock or bad node_modules, It could be something to do with your Electron setup if you have the common "main" and "app" setup with two node_modules

**Comment by MenschenToaster** [comment]
I dont have two node_modules and i have reseted my yarn.lock and node_modules multiple times.

**Comment by MenschenToaster** [comment]
![Screenshot_3](https://user-images.githubusercontent.com/54715954/90020956-e1de0480-dcb0-11ea-96fa-558c1008e529.png)

As you can see its only one node_modules for all of it.

**Comment by jquense** [comment]
unfortunately i can't really tell anything from screenshots, I was just offering places to look. This is ultimately not a react-bootstrap issue, and not one we can fix, as much as i wish we could. Due to something in your current setup installing RB is causing yarn either intentionally or by error to include another copy of React.

**Comment by MenschenToaster** [comment]
The problem here is that it is also not working on another computer and also switching to npm doesn't change anything.

I would really like to use react-boostrap :(

**Comment by jquense** [comment]
like i said, the issue isn't react-bootstrap, its just the package _currently_ exposing the problem, it's likely to happen with another package down the road. if you want to post your yarn.lock file that's about the best I can do, otherwise my guess is this is an Electron specific issue with React

**Comment by MenschenToaster** [comment]
Here is my yarn.lock: https://pastebin.com/zEUZ0kfS

otherwise my guess is this is an Electron specific issue with React:
that would be strange becouse electron basicly just uses chrome

**Comment by jquense** [comment]
I don't see anything out of order in your yarn.lock, best i can say is to poke around and debug from the warning and see if it gives you a hint where the other instances are coming from

> that would be strange because electron basically just uses chrome

The renderer is chrome but the environment is very different and complex, being a combo of node and chrome and multiple distinct processes.

**Comment by MenschenToaster** [comment]
I don't see anything strange too. I will be switching to reactstrap for now since it is only making problems with this package.
It's sad but I need to make Progress in my Application.

**Comment by jquense** [comment]
good luck!
