### ISSUE TITLE
Modal showing error in console

### ISSUE THREAD

**Issue by byeze** [react-bootstrap/react-bootstrap#5383]
## Describe the bug
I placed a modal that's shown when the user clicks a button. The thing is that when it appears, the console throws this:
![image](https://user-images.githubusercontent.com/7424138/90254403-0ce36800-de19-11ea-99a2-c7e5551c2f7b.png)

## To Reproduce

- Create react app
- Place modal component
- Show it with a button trigger
- Look at the console

## Reproducible Example

Minimal example by using [CodeSandbox](https://codesandbox.io/s/misty-dew-x861w).

## Environment (please complete the following information)

- Operating System: Windows 10
- Browser, Version Edge Chrome 84.0.522.59
- React-Bootstrap Version 1.3.0

**Comment by taion** [comment]
consolidating discussion in https://github.com/react-bootstrap/react-bootstrap/issues/5075
