### ISSUE TITLE
NavDropdownProps doesn't contain props from DropdownProps

### ISSUE THREAD

**Issue by XiNiHa** [react-bootstrap/react-bootstrap#5388]
## Describe the bug

`NavDropdown` contains `show` property(from `Dropdown`). However, `NavDropdownProps` doesn't contain `show` property, results in a false type error. The problem also occurs with all of the `DropdownProps` fields, like `drop`, `flip`, etc.

## To Reproduce

1. Create a component with `NavDropdown` in TS
2. Add `show` property on it
3. Type error occurs

## Expected behavior

There should be no type error. Not only for `show`, but for all of the members of `DropdownProps`

## Environment

- Windows 10, Dev server running inside WSL
- Firefox 79 (btw no problem inside the browser)
- React-Bootstrap 1.3.0

## Additional context

Probably just changing the parent type of `NavDropdownProps` to `DropdownProps` can be a solution

**Comment by taion** [comment]
this was fixed in https://github.com/react-bootstrap/react-bootstrap/pull/5341
