### ISSUE TITLE
v0.13.0 is shown as latest release by GitHub project landing page

### ISSUE THREAD

**Issue by andoks** [react-bootstrap/react-bootstrap#5396]
As seen on image here, GitHub shows the 0.13.0 version as latest. Shouldn't this be 1.3.0?

![image](https://user-images.githubusercontent.com/5228/90885404-d1fda900-e3b1-11ea-97e2-7796213b569c.png)

**Comment by taion** [comment]
weird; i made 1.3.0 a release to mark it as such. i guess we should update the tooling to create GH releases or something.
