### ISSUE TITLE
<DropDown.Item /> eventKey return null to <DropDown /> onSelect for index 0 item

### ISSUE THREAD

**Issue by dighexode** [react-bootstrap/react-bootstrap#5401]
## Describe the bug

We use map() function to render <DropDown.Item />, we passed index into its eventKey property. When clicking the index=0 DropDown.Item, the onSelect handler is receiving null. The other DropDown Item works well, although the eventKey is string, e.g. "1", "2" etc.
I can confirm it works well in version 1.0.1. But now 1.3.0 is returning null in onSelect handler.
Now I have to pass index + 1 into eventKey, then do parseInt(eventKey) - 1 in onSelect handler.

## To Reproduce
Here's the code:

> `<div className={styles['text-font-size']}>
>       <Dropdown
>         onSelect={(eventKey) => {
>           props.onSelected(props.fontSizeList[eventKey].value);
>         }}
>         className={styles['font-size-dropdown']}>
>         <Dropdown.Toggle
>           id="font-size-dropdown"
>           disabled={props.disabled}>
>           <div className={styles['fake-dropdown']}>
>             <div className={styles['left']}>{props.fontSizeList[selectIndex].value}</div>
>             <div className={styles['right']}>
>               <div className={styles['dropdown-arrow']}></div>
>             </div>
>           </div>
>         </Dropdown.Toggle>
>         <Dropdown.Menu className={`${styles['dropdown-content']} ${styles['dropdown-menu']}`} ref={dropdownMenuRef}>
>           {props.fontSizeList.map((fontSize, index) => (
>             <Dropdown.Item eventKey={index} key={fontSize.value} active={fontSize.selected}>
>               {fontSize.value}
>             </Dropdown.Item>
>           ))}
>         </Dropdown.Menu>
>       </Dropdown>
>     </div>`

## Expected behavior

Return "0" for index=0 <DropDown.Item />

## Environment

- React-Bootstrap Version 1.3.0

**Comment by kyletsang** [comment]
`eventKey` is meant to be a string here.  Looks like there's a bug with the prop types setting it as "any".

This was mentioned in #4239

**Comment by dighexode** [comment]
@kyletsang Thank you for your quick reply. So that means if we pass other type of object into eventKey, its behavior is unpredictable, right? I'm just curiously why the number more than 0 could be automatically convert to its string expression, while 0 doesn't work.

**Comment by kyletsang** [comment]
Yeah, best to stick to strings for keys here because the keys that are passed back in the `onSelect` callback are strings.

The code was modified during the typescript migration from `const key = makeEventKey(eventKey, href)` to `const key = makeEventKey(eventKey || null, href)`, so it no longer passes falsy values to `makeEventKey`.  That's why it used to work before in 1.0.1 and not now.

**Comment by kyletsang** [comment]
Hmm, a number of tests for Nav and Dropdown uses numbers for `eventKey` and the docs are inconsistent with the types...

@taion, @jquense, to confirm, `eventKey`s where `SelectableContext` is used should be strings right?  If we were to make proptype and TS type fixes here, it would kinda break the existing behavior like in this issue where 0 doesn't work anymore.

**Comment by jquense** [comment]
The should ideally be strings, but we are messy with them. The specific string requirement came in v1 as a result of needing to serialize eventKeys to data-* attributes in the DOM. Technically any value that serializes neatly to a string is fine, and we should probably make sure we aren't doing loose falsey checks in most places

**Comment by jquense** [comment]
I would consider this a TS regression and fix it to back to v1.0.0 behavior I think. We can get stricter about this in the next major bump
