### ISSUE TITLE
doc: Button doc doesn't document onClick event

### ISSUE THREAD

**Issue by twhitmorenz** [react-bootstrap/react-bootstrap#5405]
## Describe the bug

Hi all! Just a minor documentation suggestion - Button documentation should document onClick event for the normal Button. Nothing is documented and other button types on that same page document onChange, however that doesn't work for Button. Doc could be slightly clearer for new users.

## To Reproduce

1. See https://react-bootstrap.github.io/components/buttons/
2. onClick is not mentioned.
3. onChange is mentioned for other button types.
4. Result:  new users to this good framework may be unnecessarily confused.

## Expected behavior

'Button' API should list the onClick event.

## Environment (please complete the following information)

- React-Bootstrap website version 1.3.0 

## Additional context

React Bootstrap seems to be a good choice so far. My prototypes with it are going well -- I'd tried React Semantic UI initially, but now switched to React Bootstrap (CSS concerns). Thanks guys!

**Comment by kyletsang** [comment]
All the elements should support the standard html attributes and event handlers.  The docs only list custom props specific to the component.  I think anywhere which documents standard html attributes only do so to add additional information, like `id` in form components where it talks about accessibility.

**Comment by twhitmorenz** [comment]
Thanks Kyle. While I would also expect some knowledge of HTML as general background, I would suggest that at least in this case mentioning the most important handler could probably improve clarity/ ease of uptake.

(I would have tried onClick first, but found this snippet "React Bootstrap will prevent any onClick handlers from firing regardless of the rendered element" as the first mention of onClick in the page.. which sounded discouraging of onClick.. and onChange was documented, while onClick wasn't.. so I went and spent time trying to make onChange work.)

Thoughts:

- In principle I would tend to suggest that documenting the most major HTML properties necessary for things to function as they're intended, might often help people.

- I did look at proposing a PR, but found the API documentation is auto-generated from Button.tsx. Making it harder to document major properties exposed by the underlying element, but just passed thru by the React component.

- Possibly it might be conceivable to document an overview & major HTML properties (type, onClick, onChange) at the top of buttons.mdx, between the headline and the examples?  There probably is a genuine documentation gap here. I could possibly try to stump out a PR to this effect if you guys were interested..

I will agree this doesn't seem quite such an easy documentation problem to solve, as it might have appeared at first glance. 
I'm Interested in your thoughts on this.

**Comment by kyletsang** [comment]
I think it's a good idea if it will make things more clear for users.  @taion, @jquense?

**Comment by jaisaichand** [comment]
@kyletsang Has anyone taken this already? or can I add it ?

**Comment by kyletsang** [comment]
@jaisaichand feel free to open a PR
