### ISSUE TITLE
Accordion toggle on click of button in accordion bodybuilding

### ISSUE THREAD

**Issue by selenajosephine** [react-bootstrap/react-bootstrap#5406]
## Describe the bug
 I'm trying to toggle the accordion on button click from within the  accordion body
## To Reproduce

1. Write a wrapper for Accordion.  
2. Use the wrapper and pass a button as a component to the body. 
3. On click of button, toggle the Accordion. 

## Environment (please complete the following information)

- Operating System: [Windows]
- Browser, Version [Chrome @Latest]
- React-Bootstrap Version [1.3 @Latest]

**Comment by kyletsang** [comment]
You can control which card is shown by using the `activeKey` prop in `Accordion`.  Use your button to set that.

Since you are now using the accordion in a controlled manner, you would also have to handle `onSelect` manually to set the correct `activeKey` when toggling the header.
