### ISSUE TITLE
Fade class name on modal while using lower version bootstrap

### ISSUE THREAD

**Issue by gaweki** [react-bootstrap/react-bootstrap#5408]
## Describe the bug

i want to use modal on different bootstrap version for a website

## To Reproduce

1. Open modal
2. Cause i use lower version bootstrap, fade class name make my modal container not show. Although, show class name is added.

## Expected behavior

I want my modal from react-bootstrap can work too while using lower version bootstrap

## Additional context

lower version:
.fade{ opacity: 0}

react-bootstrap: 
.fade{ transitions .....}

i already add container element higher than Modal component, but the container rendered as individual element.

**Comment by kyletsang** [comment]
What version of bootstrap are you trying to use?  If it's v3, then you need to use version 0.33.1 of react-bootstrap: https://react-bootstrap-v3.netlify.app/

**Comment by gaweki** [comment]
yes, version 3. but if still use v3, fade class name removed, the opacity still 0. i don't want remove  fade class name manually.

**Comment by kyletsang** [comment]
Are you sure you're using the right version of **react-bootstrap**?  Bootstrap 3 doesn't use the `.show` class for modals.  The docs example with a contained modal works:  https://react-bootstrap-v3.netlify.app/components/modal/#modals-contained

Can you post a repro on CodeSandbox?

**Comment by gaweki** [comment]
sorry, maybe missinformation, i use react bootstrap with bootstrap 4(default) on a package. but my project exists with bootstrap 3.  i integrate my package into existing project. Than the conflict happen.

**Comment by kyletsang** [comment]
You'll need to use one version of bootstrap here.  Can't mix different versions of the packages together.

**Comment by gaweki** [comment]
and how about my container Modal component is rendered as individual element?

**Comment by jquense** [comment]
Bootstrap (and so also react-bootstrap) is not designed to be used with multiple versions on the same page. This is mostly due to CSS being global and so v3 and v4 conflict with each other
