### ISSUE TITLE
Click on MenuItem doesn't hide the dropdown menu?

### ISSUE THREAD

**Issue by agile116** [react-bootstrap/react-bootstrap#541]
HI All,
I created the following DropdownButton, but the dropdown doesn't get closed when I click either of the MenuItem. What happened?
DropdownButton
  MenuItem>Experts</MenuItem
  MenuItem>White Papers</MenuItem>
  MenuItem id='solution' eventKey='3' onClick={this.props.onSelection}>Solutions</MenuItem>
/DropdownButton

**Comment by AlexKVal** [comment]
It is related to #526.
So for now there is no easy solution only workarounds
Pull requests are welcome of course ;)

**Comment by re6exp** [comment]
For the navbar, this [code](http://stackoverflow.com/a/16680604) works:
```
    componentDidMount() {
        $('.nav a').on('click', function(){
            $(".btn-navbar").click(); //bootstrap 2.x
            $(".navbar-toggle").click(); //bootstrap 3.x by Richard
            this.forceUpdate({});
        });
    }
```
Probably, the workaround for DropdownButton may be achieved by similar way.

**Comment by mtscout6** [comment]
@re6exp By using jQuery click event handlers you bypass React's synthetic event system making it harder to test.

**Comment by barbalex** [comment]
for me this works:

    componentDidMount () {
      // this is a bad hack for react-bootstrap not closing the menu on click
      $('#menuBtn a').on('click', function () {
        console.log('click')
        $('#menuBtn .dropdown-toggle').click()
      })
    }

**Comment by steve-taylor** [comment]
An easy workaround that doesn't require jQuery:

```
<DropdownButton title={buttonTitle} onSelect={() => true}>
```

or if you're still using ES5:

```
<DropdownButton title={buttonTitle} onSelect={function() { return true; }}>
```

**Comment by agile116** [comment]
Thanks


杨小林

**Comment by barbalex** [comment]
nice!

**Comment by zaro** [comment]
Having the same issue with  DropdownButton, just noticed something.

If I open the page where the dropdown is directly ( paste the URL in the browser ), the menu doesn't hide at all, and  

`<DropdownButton title={buttonTitle} onSelect={() => null}>`

doesn't  work.
If I go to the same page by clicking a link in my app everything works as expected with no onSelect handler and no workarounds.

**Comment by alexkb0009** [comment]
Have encountered & addressed (as of v0.30.7) w/ workaround by adding this in my onSelect handler: 
`document.dispatchEvent(new MouseEvent('click'));`

Because dropdown becomes hidden after mouse click anywhere on page, this seems to emulate that decently enough. Issue seems to be that the internal handleClick method of MenuItem seems to call event.preventDefault() before running the onSelect callback/handler which also prevents click event from bubbling up and closing the NavDropdown.

**Comment by natevw** [comment]
@react-bootstrap Why is this issue closed? It seems to be a valid problem, but was not fixed before #526 got closed.

**Comment by jquense** [comment]
I'm not sure what you mean its not fixed. try any of the examples on the docs site and you can see that clocking on a MenuItem does close the dropdown

**Comment by natevw** [comment]
@jquense Indeed, the problem is a bit more subtle — at least in my case it breaks because I'm wrapping MenuItem in a helper component. Filed #2429 with details.

**Comment by dzotos** [comment]
@natevw Got the same problem 👍

**Comment by ChristophAuer** [comment]
I have also this problem. I fixed it by setting the attribute `data-toggle="dropdown"` in the DropdownButton tag.
` <DropdownButton data-toggle="dropdown" ... >
`

**Comment by sungwoncho** [comment]
Adding `data-toggle="dropdown"` to DropdownButton seems to close the dropdown after click. But there is a problem: users have to click the DropdownButton twice to open it after the initial close.

**Comment by jquense** [comment]
If adding `data-toggle` works you are incorrectly also including bootstrap.js don't do that, react-bootstrap reimplements the bootstrap js you are including a TON of extra unused code, and that's probably the problem in the first place

**Comment by im-martijn** [comment]
Right, this issues should be re-eopened. Definitely have this problem too.

**Comment by jquense** [comment]
please provide a repro demostrating the problem, and we'll work on it

**Comment by radziksh** [comment]
@im-martijn for me works workaround given by @alexkb0009.

**Comment by garretttaco** [comment]
For anyone else looking into this, here was my solution.
You add the props `onToggle` and `open` on the dropdown button. The `onToggle` function is a method on your class container that changes the open state to `true` or `false`. This will keep the functionality consistent with how it works out of the box. Then to solve the `MenuItem` closing the dropdown button issue, you add an onClick to the `MenuItem` which calls the same `onToggle` method. This will solve the issue. Hope this helps you to stay in the realm of React and not drift to DOM manipulation with jQuery or other alternatives.

Quick example for the more visual:
```
class DropdownFixed extends Component {
  state = { dropdownIsOpen: false }

  toggleDropdown = () => this.setState({ dropdownIsOpen: !this.state.dropdownIsOpen })

  render {
    return (
      <DropdownButton
        onToggle={toggleDropdown}
        open={dropdownIsOpen}
      >
        <MenuItem onClick={toggleDropdown}>Click me!</MenuItem>
      </DropdownButton>
    )
  }
}
```

**Comment by konekoya** [comment]
@garretttaco Great solution, it works great for me! Thanks a log!

**Comment by natevw** [comment]
This might be buried a bit in my comment above, but I think the main issue comes when you have the MenuItem within a wrapper. Does that match what everyone else is seeing?

What I mean is, unless the MenuItem is a *direct* child of the DropdownButton, you might hit this unless you understand the internals. I wrote up some gory details at https://github.com/react-bootstrap/react-bootstrap/issues/2429 and tried to get a warning in the documentation via https://github.com/react-bootstrap/react-bootstrap/pull/2432, and am still of the opinion that this is an implementation flaw.

To summarize my notes elsewhere, the DropdownButton overrides their `onSelect` handlers before it renders its children. So if your wrapper (child) doesn't call **the DropdownButton's** onSelect handler, the dropdown won't close.

So you either have to call the `onSelect` from your wrapped onSelect handler:

```
let MyMenuItem = ({obj, onSelect:internalOnSelectOverride}) => <MenuItem
  onSelect={ () => { handleSelect(obj); internalOnSelectOverride(); } }
>{obj.name}</MenuItem>
```

Or you need to pass it along to the wrapped menu item, for example here just passing along all props:

```
let MyMenuItem = ({obj, ...props}) => <MenuItem
  {...props}
  onClick={ () => handleSelect(obj) }
>{obj.name}</MenuItem>
```

Is everyone else hitting this with menu item wrappers, or are there other situations where the dropdown won't close?

**Comment by AnechaS** [comment]
my solution, add this code `document.body.click();` in onClick you menu items

<Dropdown.Menu>
  <div onClick={() => { document.body.click() }}>item</div>
<Dropdown.Menu>

**Comment by esbb48** [comment]
Control open/close myself
```

const [isOpen, setIsOpen] = useState(false);
const onToggle = (nextShow, event, metadata) => {
    const isClosingPermitted = metadata.source !== 'select';
    const currentNextShow = nextShow ? true : !isClosingPermitted;
    setIsOpen(currentNextShow);
};

return (
<Dropdown onToggle={onToggle} show={isOpen}>
        <Dropdown.Toggle>
          /* */
        </Dropdown.Toggle>
        <Dropdown.Menu>
        /* */
        </Dropdown.Menu>
);
```

**Comment by devdreamsolution** [comment]
> Control open/close myself
> 
> ```
> const [isOpen, setIsOpen] = useState(false);
> const onToggle = (nextShow, event, metadata) => {
>     const isClosingPermitted = metadata.source !== 'select';
>     const currentNextShow = nextShow ? true : !isClosingPermitted;
>     setIsOpen(currentNextShow);
> };
> 
> return (
> <Dropdown onToggle={onToggle} show={isOpen}>
>         <Dropdown.Toggle>
>           /* */
>         </Dropdown.Toggle>
>         <Dropdown.Menu>
>         /* */
>         </Dropdown.Menu>
> );
> ```

Hello @esbb48 , thanks for your help, your code works well.

**Comment by FAugustoC** [comment]
> my solution, add this code `document.body.click();` in onClick you menu items
> 
> ```js
> <Dropdown.Menu>
>   <div onClick={() => { document.body.click() }}>item</div>
> <Dropdown.Menu>
> ```

Very practical and effective solution thank you.
