### ISSUE TITLE
Feature request :- multi level sidebar menu 

### ISSUE THREAD

**Issue by dropways** [react-bootstrap/react-bootstrap#5413]
![sidebar-template](https://user-images.githubusercontent.com/38377336/91858895-6b1ca180-ec87-11ea-8507-28add2b5d796.gif)

**Comment by jquense** [comment]
Hi there, thanks for the suggestion. We try to match what the base (vanilla) bootstrap offers, so don't add new components that require CSS if they aren't upstream. It does look like bootstrap v5 maybe adding a side panel drawer component that could cover this. For now You can build your own by combining the Accordion component with your own sidebar
