### ISSUE TITLE
Feedback icon is wrongly positioned for Select components

### ISSUE THREAD

**Issue by binarykitchen** [react-bootstrap/react-bootstrap#542]
Currently it is:

```
.form-horizontal .has-feedback .form-control-feedback {
  right: 5px;
}
```

but I think we need a new selector and set this to something like 20px, so that it won't overlap with the other icon the select box comes with.

**Comment by mtscout6** [comment]
Where are we setting that? You provided only css but we defer all css to bootstrap proper. I'm not sure I follow the exact problem.

**Comment by binarykitchen** [comment]
Never mind, I solved it just recently by moving the feedback icon outside of the input element.

But I guess, the problem is still here and is a bootstrap CSS problem itself.
