### ISSUE TITLE
Cannot find module 'react-bootstrap' or its corresponding type declarations. ts(2307)

### ISSUE THREAD

**Issue by Pointotech** [react-bootstrap/react-bootstrap#5420]
## Describe the bug

Error message in TypeScript: Cannot find module 'react-bootstrap' or its corresponding type declarations. ts(2307)

## To Reproduce

1. Add `react-bootstrap` to a project containing TypeScript code.
2. Import something from `react-bootstrap` in a .ts file, such as: `import { Container, Row, Col, Button, Image } from "react-bootstrap"`
3. The TypeScript compiler gives this error message: Cannot find module 'react-bootstrap' or its corresponding type declarations. ts(2307)

## Expected behavior

The types should be imported normally with no error. The library contains type definitions, but there is something wrong with how they're being exported.

## Environment

- Operating System: Ubuntu 20
- Browser not applicable (this is a build error).
- React-Bootstrap Version: 1.3.0

**Comment by kyletsang** [comment]
Did you `npm install`?

**Comment by Pointotech** [comment]
Yes, of course. I can import most libraries, including their types, with no issues. `react`, for example, works fine and has correct types.

Doing this fixed my problem, but of course it's ugly as sin and it's not documented anywhere, so it's not a great solution:

```
import {
  Container,
  Row,
  Col,
  Button,
  Image,
} from "../node_modules/react-bootstrap/esm/index"
```

It seems like the CommonJS stuff is getting in the way of proper EcmaScript module support.

**Comment by kyletsang** [comment]
Can you post your tsconfig here along with the TS version you're running?

**Comment by Pointotech** [comment]
I'm using TypeScript 3.9.7, here's the config:

```
{
  "compilerOptions": {
    "outDir": "./dist/",
    "allowJs": true,
    "checkJs": true,
    "strict": true,
    "jsx": "react",
    "noImplicitAny": true,
    "module": "es2020",
    "target": "es5",
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "downlevelIteration": true
  }
}
```

Changing `module` to "CommonJS" instead of any EcmaScript version also fixed the import type issues (without needing to specify the full path to `node_modules/react-bootstrap/esm/index`), but that seems like a step backward and it seems like ES modules are intended to be supported here.

**Comment by kyletsang** [comment]
I'm running a config that's similar to that in this sandbox:
https://codesandbox.io/s/github/react-bootstrap/code-sandbox-examples/tree/master/basic-ts?file=/tsconfig.json

This is working in a nextjs/create-react-app environment.

It seems like this issue may be related to your project environment/bundler.
