### ISSUE TITLE
NavDropdown still does not inherit props from Dropdown

### ISSUE THREAD

**Issue by rockchalkwushock** [react-bootstrap/react-bootstrap#5424]
## Describe the bug

I have reviewed the issues, #5339 & #5388, surrounding this and the PR, #5341, that was submitted to fix this and it seems as though that code does not exist on the latest release: `1.3.0`.

I looked at the release [documentation](https://github.com/react-bootstrap/react-bootstrap/compare/v1.3.0...master) and the PR & corresponding commits are there; however looking at the source code in my `node_modules` this is not the case. I have verified through my `package.json` and `yarn.lock` that I am in fact using `1.3.0`.

If it helps here is the link to the [tarball](https://registry.yarnpkg.com/react-bootstrap/-/react-bootstrap-1.3.0.tgz#d9dde4ad554e9cd21d1465e8b5e5ef6679cae6a1) that is on the Yarn registry as of the writing of this issue.

## To Reproduce

1. `yarn add react-bootstrap bootstrap`
2. import `NavDropdown`
3. Try to use `alignRight`

## Reproducible Example

[sandbox](https://codesandbox.io/s/rough-forest-3b4gg?file=/src/App.tsx)

## Expected behavior

I would expect `NavDropdown` to inherit the props of `Dropdown` as it is an extension of that API.

## Screenshots

![Screen Shot 2020-09-08 at 22 09 03](https://user-images.githubusercontent.com/19720404/92556927-f1a12800-f21f-11ea-8af5-8f48cd8f2af5.png)

## Environment (please complete the following information)

- Operating System: `macOS 10.15.6`
- Browser, Version `Chrome 85`
- React-Bootstrap Version `1.3.0`

**Comment by kyletsang** [comment]
This fix didn't make it into a release yet.

cc @jquense

**Comment by cchanxzy** [comment]
+1 `Navdropdown` doesn't have the correct props in `1.3.0`, would like to see fix released if it's already been fixed.

**Comment by michalsrutek** [comment]
It has been almost two months, can we get this released? @jquense @taion @kyletsang

**Comment by jquense** [comment]
pushed a release
