### ISSUE TITLE
Is there any way to pass an elementType through spread properties?

### ISSUE THREAD

**Issue by jestrickler** [react-bootstrap/react-bootstrap#5426]
This works to create Nav.Link as react-router-dom Link:
```
<Nav.Link as={Link} to='/'>link</Nav.Link>
```
But this:
```
const props = { as: { Link }, to: '/' }
return (
  <Nav.Link {...props}>link</Nav.Link>
)
```

fails with:
```
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

Check the render method of `ForwardRef`.
```
My Nav.Link is in a component library that doesn't have a dependency on react-router, and I was hoping to pass in the 'as={Link}' from the main app without forcing that dependency onto the library. Is there any way to do this?

**Comment by kyletsang** [comment]
You have a mistake in your props: `Link` is wrapped inside an object.

Try this:
`const props = { as: Link, to: '/' }`

**Comment by jestrickler** [comment]
Thanks!! I had just come back to say the same thing. Somewhat figured out by trial and error, but makes perfect sense now that I see it.
