### ISSUE TITLE
Tabs displaying vertically and applying wrong css class

### ISSUE THREAD

**Issue by alexanderluna** [react-bootstrap/react-bootstrap#5428]
## Describe the bug

I'm rendering tabs inside a modal. The tabs are displayed stacked instead of inline. I compared the css classes applied by the Tabs component and it has a `navbar-nav` class. When I replace it with the `nav` class it displays correctly inline. I was looking at the html in documentation and in the docs it doesn't add a `navbar-nav` class.

## To Reproduce

```
<Modal.Body>
            <Tabs id="controltab" defaultActiveKey="login">
              <Tab eventKey="login" title="Login">
                <Login />
              </Tab>
              <Tab eventKey="signup" title="Signup">
                <Signup />
              </Tab>
            </Tabs>
</Modal.Body>
```

## Screenshots

<img width="495" alt="Screen Shot 2020-09-11 at 16 11 56" src="https://user-images.githubusercontent.com/11302907/92935763-86d33500-f449-11ea-985b-cdf9bf438209.png">
<img width="329" alt="Screen Shot 2020-09-11 at 16 12 18" src="https://user-images.githubusercontent.com/11302907/92935791-92bef700-f449-11ea-831f-39ad901adaf6.png">

## Environment (please complete the following information)

- Operating System: macOS
- Browser, Version: all browsers
- React-Bootstrap Version: 1.3

**Comment by kyletsang** [comment]
It would use the `.navbar-nav` class if it the Tab components are nested under a Navbar.  

You would need to place your modal outside the Navbar in order to render the proper `.nav` class.
