### ISSUE TITLE
How to add a custom bsStyle?

### ISSUE THREAD

**Issue by binarykitchen** [react-bootstrap/react-bootstrap#543]
I would like to add a fourth bsStyle called 'required' but that won't work well at the moment:

```
Warning: Failed propType: Invalid prop `bsStyle` of value `required` supplied to `Input`, expected one of ["success","warning","error"].
```

How can I achieve this best?

**Comment by dozoisch** [comment]
You can just put `className="..."`

**Comment by AlexKVal** [comment]
For now there is no API to add custom style.
There is the hardcoded check for this in `propTypes`.
```js
bsStyle: React.PropTypes.oneOf(['success', 'warning', 'error'])
```

Could you provide us simplified code for such use case ?
So then everybody can discuss it.

Here #306 is related discussion. 
And here #440 is open issue for exactly such questions.

I propose to continue discussion in #440. It serves as agregator.
This issue I'm closing to not have several opened issues about one related theme.

**Comment by binarykitchen** [comment]
Well, the use case is:
- Have a special icon on the right of the input, telling the user that it's required to enter something.
- When entered, bsStyle changes from `required` to either `success`, `warning` or `error`, depending on the validation state.
- When input is removed and is still required, set bsStyle to `required` again.

**Comment by merk** [comment]
So how do you indicate that a required field has an error?

I built a basic Input wrapper to provide support for a "required" attribute/prop:

```js
import cx from 'classnames';
import React from 'react';
import { Input as BaseInput } from 'react-bootstrap';

class Input extends React.Component {
    getValue () {
        return this.refs.input.getValue();
    }

    render () {
        const { required, labelClassName, ...props } = this.props;

        return <BaseInput ref="input"
            labelClassName={cx(labelClassName, { required: required })}
            {...props}
        />;
    }
}
Input.propTypes = {
    required: React.PropTypes.bool
};
Input.defaultProps = {
    required: false
};

export default Input;
```

**Comment by binarykitchen** [comment]
@merk Well, if a required input has an error, then the error display is good enough. It does not make sense to show both states at the same time, telling the user that the input is required and that it has an error.

The required state should be shown only when the input is empty. This to aim best usability. Otherwise the user sees too many signals and feels overwhelmed/stressed when filling out the form.

**Comment by AlexKVal** [comment]
As I see it: you have only 4 states in total.

_default_ one is: `required`
and other three are pretty standard `success`, `warning` or `error` states.

There is _no_ any fifth "neutral" state. Right ?

So if the _default_ one is `required`, then you can just use it as `neutral`.

I mean your component by default has that special icon and if another state arises,
it would be one of those three known and standard: `success`, `warning` or `error`.
As a result you don't need `required` state label for your _default_ state at all.

**Comment by mtscout6** [comment]
`required` would serve better as a separate prop, because something can be in error and still be required. Or it can be a success but still required. Also bsStyle will prepend which ever value you give it with the given component type.

**Comment by AlexKVal** [comment]
I've proposed my solution guided by author's particular case.

As author has mentioned
> It does not make sense to show both states at the same time ...

and
> The required state should be shown only when the input is empty.

Therefore `required` in that particular case is by fact the `default` state and it is not used with any other one at the same moment.
Just like that.

What @mtscout6 proposes is in fact more cross functional and therefore more preferable solution :)

**Comment by mtscout6** [comment]
This is also inline with the provided validation states by bootstrap: http://getbootstrap.com/css/#forms-control-validation

**Comment by binarykitchen** [comment]
You all have good points and I like @AlexKVal s input regarding the neutral state. But it won't work on inputs that aren't required. Not all inputs in a form are required.

This here is the coffee code I just wrote and works like a charm for me:

```coffee
React          = require('react')
ReactBootstrap = require('react-bootstrap')
classNames     = require('classnames')

{ Col, Input } = ReactBootstrap

module.exports = React.createClass(

  getInitialState: ->
    bsStyle: null

  getDefaultProps: ->
    xs:               12
    labelClassName:   'col-xs-2'
    wrapperClassName: 'col-xs-9'

  _getBsStyle: (validity, value) ->
    if (validity)
      if (validity.valid)
        'success'
      else if value
        'error'

  _getWrapperClassName: (value) ->
    if @props.required and !value
      'required'

  _handleChange: (e) ->
    @setState(
      value:   e.target.value
      bsStyle: @_getBsStyle(e.target.validity, e.target.value)
    )

  render: ->
    <Col xs = {@props.xs}>
      <Input
        {...@props}
        hasFeedback
        value            = {@state.value}
        bsStyle          = {@state.bsStyle || @_getBsStyle()}
        onChange         = {@_handleChange}
        wrapperClassName = {classNames(@props.wrapperClassName, @_getWrapperClassName(@state.value))}
      />
    </Col>
)
```

this together with the added SASS style:

```sass
div.required .form-control-feedback {
  @include required-marker();
}
```

**Comment by AlexKVal** [comment]
Thank you for sharing your solution :+1:
