### ISSUE TITLE
Issue with react-bootstrap/carousel -- Clicking on the Carousel indicators, arrows stops the auto looping in iphone

### ISSUE THREAD

**Issue by chandru14** [react-bootstrap/react-bootstrap#5431]
Hi,
The click of arrows stops the auto looping of the carousel.
Steps to reproduce:
1. open the https://react-bootstrap.github.io/components/carousel/ in chrome inspector and select iPhone X mode
2. Click on any of the arrows (prev/next/) or the indicators at the bottom of the carousel - it moves to the slide and then stops the looping.

Any quick help would be appreciated.

**Comment by kyletsang** [comment]
Looks like `pausedOnTouch` is not getting reset due to an early return here:
https://github.com/react-bootstrap/react-bootstrap/blob/6f611c3ac6943ff7437c21bdbfd384b60d7bcc56/src/Carousel.tsx#L474-L476

A single tap anywhere on the carousel would pause it.

**Comment by IsbahAhmed** [comment]
can you tell me how to stop auto looping of carousel?

**Comment by chandru14** [comment]
> can you tell me how to stop auto looping of carousel?

Add the attribute interval and set to null  to the Carousel tag
(you will find it in the https://react-bootstrap.github.io/components/carousel/ 
API section of carousel table)

**Comment by chandru14** [comment]
> Hi,
> The click of arrows stops the auto looping of the carousel.
> Steps to reproduce:
> 
> 1. open the https://react-bootstrap.github.io/components/carousel/ in chrome inspector and select iPhone X mode
> 2. Click on any of the arrows (prev/next/) or the indicators at the bottom of the carousel - it moves to the slide and then stops the looping.
> 
> Any quick help would be appreciated.

Hi,
is the issue fixed?
Can anyone help on this.

**Comment by kyletsang** [comment]
@chandru14, there is an open PR for this at #5435
