### ISSUE TITLE
Collapse not working

### ISSUE THREAD

**Issue by IsbahAhmed** [react-bootstrap/react-bootstrap#5438]
TypeError: Cannot read property 'className' of undefined
Every time i try to use Collapse it shows this error.

**Comment by kyletsang** [comment]
Please provide a reproducible example on CodeSandbox.

**Comment by IsbahAhmed** [comment]
> Please provide a reproducible example on CodeSandbox.

`import React, { useState } from "react";
import { Collapse } from "react-bootstrap";
import NavMenuListItem from "../NavMenuListItem/NavMenuListItem";
import "./MobileNav.css";
const MobileNav = () => {
  const [open, setOpen] = useState(false);
  return (
    <div className="mobile-nav-container 
      ">
      <div className="collapse-wrapper my-5">
        <div className="upper-patti">
          <h4>Menu</h4>
          <i
            className={`fa ${open ? "fa-times" : "fa-bars"}`}
            onClick={() => setOpen((prevValue) => !prevValue)}
          ></i>
        </div>
        <Collapse in={open} className="">
          <div  className="" id="mobile-nav-content">
           <NavMenuListItem subMenu={[]} menuName={"home"} />
            <NavMenuListItem subMenu={[]} menuName={"shop"} />
            <NavMenuListItem
              subMenu={["clothing", "dresses"]}
              menuName={"men"}
            /> 
          </div>
        </Collapse>
      </div>
    </div>
  );
};

export default MobileNav;`

**Comment by kyletsang** [comment]
I only see the import of Collapse, but no usage of it in that example?

**Comment by jquense** [comment]
edited the response to properly fence the code

**Comment by kyletsang** [comment]
Thanks @jquense.

@IsbahAhmed, can you post a complete code sample so we can get a better picture?  Code for NavMenuListItem, version of react-bootstrap etc.

**Comment by brandiqa** [comment]
Am not sure if this is related but when I use <Navbar.Collapse>, the browser window freezes so badly that close doesn't work. Am forced to use the browser's task manager to kill it. Here's a snippet of the code:

```js
const Nav = () => (
  <Navbar bg="light" expand="lg">
    <Navbar.Brand href="#home">React-Bootstrap</Navbar.Brand>
    <Navbar.Toggle aria-controls="basic-navbar-nav" />
    <Navbar.Collapse id="basic-navbar-nav">
      <Nav className="mr-auto"></Nav>
    </Navbar.Collapse>
  </Navbar>
)
```

My `package.json` dependencies:

```js
"dependencies": {
    "bootstrap": "^4.5.2",
    "react": "^16.13.1",
    "react-bootstrap": "^1.3.0",
    "react-dom": "^16.13.1"
  },
"devDependencies": {
    "parcel-bundler": "^1.12.4",
    "prettier": "^2.1.2"
  }
```

I first encountered the problem on Windows 10. Thinking Windows might have some other issue, I switched to Linux(Elementary OS) and the problem showed up again.

**Comment by kyletsang** [comment]
@brandiqa doesn't sound related this this issue.  Sounds like you have a component somewhere that is re-rendering over and over again.  The above example alone doesn't exhibit this behavior.

**Comment by brandiqa** [comment]
@kyletsang I've created a simple codepen example: https://codepen.io/brandiqa/pen/bGeEVwR?editors=0011. There is no other component in use that could cause the re-rendering other than  <Navbar.Collapse>

**Comment by kyletsang** [comment]
Strange - I tried the codepen on Chrome 86.0.4240.75 and Firefox 81.0.2 on Windows 10 and I don't notice any freezing.  I've also added additional code from our docs examples as well and it works.

**Comment by brandiqa** [comment]
Just noted the code wasn't fully saved when I sent you the link. I've tried adding more code and this happened:
![screenshot](https://snipboard.io/dJMP0j.jpg)

Am not exactly sure which component is causing the issue.

**Comment by kyletsang** [comment]
In your example, can you rename your `Nav` component to something else like `Nav2`, then try importing `Nav` from react-bootstrap?  These names conflict.

**Comment by kyletsang** [comment]
This is getting stale, so closing it for now.  @IsbahAhmed, please reopen + attach full code repro if you are still having issues.

**Comment by mattg66** [comment]
I am also facing this issue using the collapse component.

`TypeError: Cannot read property 'className' of undefined`

` 93 |     onExiting: handleExiting
  94 |   }), function (state, innerProps) {
  95 |     return React.cloneElement(children, _extends({}, innerProps, {
> 96 |       className: classNames(className, children.props.className, collapseStyles[state], computedDimension === 'width' && 'width')
  97 |     }));
  98 |   });
  99 | }); // @ts-ignore`

**Comment by kyletsang** [comment]
I suspect this has to do with invalid children... In order to use collapse, you must specify a single child (html element or component) that takes a className.  You can't use a fragment, or multiple children.

If this is not the case **please** provide a fully reproducible example on CodeSandbox.

**Comment by fskhalsa** [comment]
+1 key piece of info right here ^^^.

I had the exact same problem, and putting my multiple child elements into one div was the thing that fixed it for me. Might not hurt to highlight this info a little more prominently in the docs, as it's different than expected behavior in vanilla bootstrap, and the `Cannot read property 'className' of undefined` error message is not particularly helpful. (Currently it's only mentioned briefly in the 'children' row of the API section at the bottom, but seems to me that this couldn't hurt to show up in an alert nearer to the top, like the note about animation smoothness).

Thanks for posting the relevant info for resolving the issue, regardless!!!
