### ISSUE TITLE
Unable to Set Default Active Key (defaultOpen) in Accordion

### ISSUE THREAD

**Issue by selenajosephine** [react-bootstrap/react-bootstrap#5439]
## unable to set default Active key. 

I had followed your suggestions in defect#5406 and have managed to control my Accordion from within the accordion body. Now, however, because I have externalized the activeKey, I am not able to set a default Active key. 

The default Active icon seems to be inverted to me, and I have the accordion in a component, that I reuse everywhere. I want to pass a prop, default open flag and want the accordion to be open/closed on load and function appropriately. 

Please share suggestions. 

Thanks,
Selena

**Comment by kyletsang** [comment]
Since you are using Accordion in a controlled way, you can't use `defaultActiveKey` since that is used when it's uncontrolled.  Your component that is wrapping the Accordion would have to implement the default active key handling.
