### ISSUE TITLE
Use react-select for select boxes

### ISSUE THREAD

**Issue by binarykitchen** [react-bootstrap/react-bootstrap#544]
I think https://github.com/JedWatson/react-select is awesome and should be reused here instead for reinventing the wheel.

**Comment by AlexKVal** [comment]
Thank you. :+1: 
I add this as a reference to aggregate issue #342.

**Comment by mtscout6** [comment]
select input boxes are different than the `DropdownButton` component.

**Comment by mtscout6** [comment]
@binarykitchen I haven't dug into the core of react-select yet, but I wonder how well it plays with the various bootstrap classed that should be applied.

@AlexKVal I oringally though you pointed this at the DropdownButton aggregate issue, sorry about the confusion.

**Comment by binarykitchen** [comment]
Problem is that I use both, react-select and your package in my app. Two same classes for a select box. Not looking good.

**Comment by mtscout6** [comment]
@binarykitchen It's been noted in #342, we will look into it but there's no promises.
