### ISSUE TITLE
Slides created with graphql not activated in carousel

### ISSUE THREAD

**Issue by bartlibert** [react-bootstrap/react-bootstrap#5440]
## Describe the bug

I have created a carousel with some images I load via graphql and gatsby-image-sharp. I see the images are created in the code, but they never get assigned the "active" class. If I manually add an item before and/or after the graphql images, those slides get shown correctly. I also see that in case I put a slide before and after the graphql ones, the first "normal" slide gets shown and when the transaction is started, I get a delay corresponding to the number of generated slides before the next statically created slide is shown again.
When inspecting the site with the react development tools, I see the working slides have a transaction key of ".0" and ".2", while the non-working slides between them have transaction keys of ".1:0:0", ".1:0:1", etc...:

![image](https://user-images.githubusercontent.com/948770/93850344-2d230400-fcae-11ea-88ae-1f9a42056ab8.png)

## To Reproduce

1. Create a carousel with some images loaded via graphql and some hardcoded ones
2. Observe  

## Reproducible Example
I cannot provide an example, as the sandbox does not support graphql as far a I know, the code itself is below.
The actual generated code is on [my test server](https://foo.libert.dev/)

```jsx
import React from "react"
import { Row, Col, Container, Carousel } from "react-bootstrap"
import { graphql } from "gatsby"

import Layout from "../components/layout"
import SEO from "../components/seo"
import Img from "gatsby-image"

const IndexPage = ({ data }) => (
  <Layout pageInfo={{ pageName: `index` }}>
    <SEO title="Home" keywords={[`gatsby`, `react`, `bootstrap`]} />
    <Container className="text-center">
      <Row>
        <Col>
          <Carousel>
            <Carousel.Item>
              <div className="d-block w-100 gatsby-image-wrapper">
              <h1>test</h1>
              </div>
            </Carousel.Item>
            {data.allDirectusSlideshow.edges.map((slideShow) => {
              return slideShow.node.images.map((image) => {
                const sharp = data.allImageSharp.edges.find((imageSharp) => (
                  imageSharp.node.fluid.originalName === image.filename_disk))
                return <>
                  <Carousel.Item key={sharp.node.id}>
                    <h1>Image</h1>
                    <Img fluid={sharp.node.fluid} className="d-block w-100" />
                  </Carousel.Item>
                </>
              })
            })}
            <Carousel.Item>
              <h1>Test 2</h1>
            </Carousel.Item>
          </Carousel>
        </Col>
      </Row>
    </Container>
  </Layout>
)

export const query = graphql`
    query {
      allDirectusSlideshow(filter: {title: {eq: "Voorpagina"}}) {
        edges {
          node {
            title
            images {
              filename_disk
            }
          }
        }
      }
      allImageSharp {
        edges {
          node {
            id
            fluid {
              originalName
              ...GatsbyImageSharpFluid
            }
          }
        }
      }
    }
  `
export default IndexPage
```

## Expected behavior

The images loaded via graphql are shown in the slideshow, just like the normal slides.

## Environment (please complete the following information)

- Operating System: Debian 10, Arch linux and Windows 10
- Browser: Firefox 80,81, Chromium 85
- React-Bootstrap Version : 1.3.0

**Comment by kyletsang** [comment]
I think we're going to need a complete repro before looking into this.

**Comment by bartlibert** [comment]
[This gatsby project](https://github.com/react-bootstrap/react-bootstrap/files/5383299/repro.zip) reproduces the issue without using the directus api. Just run `npm install` and then `gatsby develop` to see the issue.

**Comment by kyletsang** [comment]
Can you try replacing your image list rendering code with this snippet below?  Looks like RB expects the carousel item to be a direct child of the carousel, so react fragments won't work here.

```
{data.allImageSharp.edges.map(sharp => {
  return (
    <Carousel.Item key={sharp.node.id}>
      <h1>Image</h1>
      <Img fluid={sharp.node.fluid} className="d-block w-100" />
    </Carousel.Item>
  )
})}
```

**Comment by bartlibert** [comment]
That fixed it. Thanks for the help, would have never found that one on my own!
