### ISSUE TITLE
Where can I find which version of Bootstrap is run?

### ISSUE THREAD

**Issue by fredy31** [react-bootstrap/react-bootstrap#5441]
## Is your feature request related to a problem? Please describe

Hello, I'm currently looking into starting to dev with React-Bootstrap, but I would like to know. What is the current Bootstrap version that is run via React-Bootstrap?

## Describe alternatives you've considered

I've tried to look through some files I found not much as to what version of Bootstrap is run/loaded.

I would mostly like to know how long does it take for React-Bootstrap to update after a new version of React core is uploaded.

**Comment by jquense** [comment]
its in the navbar on the docs 
![image](https://user-images.githubusercontent.com/339286/93890200-14b7e700-fcb8-11ea-868b-fa067827f126.png)

that is the latest version we have personally tested, new minor versions are likely to work fine tho
