### ISSUE TITLE
Documentation improvement for users who upgraded from RBS <= 0.33 to react-bootstrap >= 1.x

### ISSUE THREAD

**Issue by joe-oli** [react-bootstrap/react-bootstrap#5443]
## Is your feature request related to a problem? 
Documentation improvement for users who were using <0.33 (BS3) and now upgraded to 1.x (BS4);
Few components removed, or no longer retain their original meaning etc.

## Describe the solution you'd like
Better documentation; Specifically mention the alternatives / replacements to use in RBS > 1.x if you were previously using RBS-0.33;

One specific example:
Both NavItem and Nav.Item are used in RBS>1.x; what is the difference?
RBS-0.33 also had a NavItem, how does it relate to the above? (I think it functions differently?)

**Comment by kyletsang** [comment]
Let's consolidate this in #3395.

In response to your example, both NavItem and Nav.Item are the same.  There are several places where react-bootstrap exposes this type of pattern for convenience (see below code):
https://github.com/react-bootstrap/react-bootstrap/blob/1ac7f5071ab81156af72fdac82819332527bb1d6/src/Form.tsx#L101-L108

Have you gone over the migration guide?
https://react-bootstrap.github.io/migrating/
