### ISSUE TITLE
Range Slider Sluggish

### ISSUE THREAD

**Issue by evantrimboli** [react-bootstrap/react-bootstrap#5444]
## Describe the bug

The range slider control feels very sluggish when dragging the thumb.

## To Reproduce

Go to:
https://react-bootstrap.github.io/components/forms/#forms-range

Drag the range slider with the mouse.

Compare this with the native slider:
https://getbootstrap.com/docs/4.1/components/forms/#range-inputs

## Reproducible Example

See: https://react-bootstrap.github.io/components/forms/#forms-range

## Expected behavior

See: https://getbootstrap.com/docs/4.1/components/forms/#range-inputs
## Screenshots

N/A

## Environment (please complete the following information)

- Operating System: Windows
- Browser, Version Chrome 85
- React-Bootstrap Version 1.3.0

**Comment by kyletsang** [comment]
Seems to only happen on the docs site.  I have this in a local project and it's not slow.

**Comment by evantrimboli** [comment]
This no longer seems to be the case.
