### ISSUE TITLE
Accordion Animations

### ISSUE THREAD

**Issue by JCron245** [react-bootstrap/react-bootstrap#5446]
## Describe the bug

I can't tell if the accordion does not support animations or is simply broken? The docs page has no animation with the accordions - and I can't get them working locally. However I see multiple references online of animations working for them.

## Reproducible Example

The docs example shows no animations [Accordion](https://react-bootstrap.github.io/components/accordion/)

## Expected behavior

The accordion has a transition instead of snapping open/close?

## Additional context

I can't tell if this is a bug, intended behavior, or if I am simply supposed to use the collapse element and not the accordion if I want animated behavior?

**Comment by kyletsang** [comment]
The animation does works on the docs page.  Have you tried a different browser?  Did you disable animations anywhere like browser settings or OS settings?

**Comment by JCron245** [comment]
Oh weird! I tried in Chrome and edge (but since its just a fork now of Chrome that doesn't help really ha!)
Let me download FF and see how it looks there. I must have something disabled in Chrome or something... although looking at other component libraries I can definitely see animations being used so I am not super sure what could be causing this!

**Comment by kyletsang** [comment]
It's possible you have something disabled at the OS level.  Bootstrap's css takes advantage of the `prefers-reduced-motion` media query to disable animation if `prefers-reduced-motion` is set to `reduce`:
https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion

Check the section under "User preferences" in the above link and see if any of those options are enabled. 

In Windows 10, there's another option I know of that isn't mentioned in that link above.  You can find it by doing the following:
1. Go to Control Panel\System and Security\System
2. Click "Advanced system settings" on the left hand panel
3. Click "Settings" button under the "Performance" section
5. Look under "Visual Effects" tab
4. Check if "Animate controls and elements inside windows" is enabled

**Comment by JCron245** [comment]
Holy crap you rock! It was the "animate controls and elements inside windows" that needed to be checked.

What exactly is the difference between the animations that react-bootstrap VS other animations I can see on the web? Since it seems only some are stopped with that visual effect checkbox?

**Comment by kyletsang** [comment]
Other libraries where you see working animations aren't using this media query.  It's an opt-in behavior.
