### ISSUE TITLE
What is the use of separate ModalDialog component?

### ISSUE THREAD

**Issue by akshaynaik404** [react-bootstrap/react-bootstrap#5448]
## Is your feature request related to a problem? Please describe

I wanted to create a Modal Dialog asking yes / no type of question. The example given in documentation looked just the solution but turns out it can't be animated. I don't understand the use case when someone would need to use a static ModalDialog component. I can just implement the same thing without using react-bootstrap.

## Describe the solution you'd like
Remove the ModalDialog component from library or if there are some other use cases for this componenet then at least deprioritize it in the documentation. It shouldn't be the first implementation that someone looks into. You can use Modal with animation={false} to demonstrate static Modal.

## Describe alternatives you've considered

I just used normal <Modal>, Modal.Header, etc. components to replicate same modal without using ModalDialog

**Comment by kyletsang** [comment]
`ModalDialog` is used internally within the `Modal` component.  The example shown in the docs is meant to show off the look and feel of the Modal and closely mirrors the docs from upstream Bootstrap.
