### ISSUE TITLE
Is there any way to debug the webpack scripts?

### ISSUE THREAD

**Issue by andrerpena** [react-bootstrap/react-bootstrap#545]
I'm sorry to ask this here, or if the answer is obvious. As soon as I get a response I'll close this issue.

I'm debugging the webpack build scripts from `react-bootstrap`. Is there any way to debug the scripts? I'm using WebStorm 10.

Thanks.

**Comment by mtscout6** [comment]
Which scripts are you concerned with? I've primarily been outputting console log statements for webpack scripts. Either that or unit tests around functions I'm concerned about.

**Comment by andrerpena** [comment]
That would be the Webpack configuration scripts.. There are some logics regarding merging up the config files that I was wondering if I could just set up a WebStorm breakpoint there and debug.

Don't worry.. I'm doing it with console writes.

Thanks again @mtscout6

**Comment by mtscout6** [comment]
No problem
