### ISSUE TITLE
Modal's dialogClassName prop not working

### ISSUE THREAD

**Issue by kikiren** [react-bootstrap/react-bootstrap#5461]
## Describe the bug

I am using the dialogClassName prop to change the width of a Modal to 100vw. The CSS class doesn't change anything, neither does the inline style.

**Comment by kyletsang** [comment]
To change the size of the modal, you would need to modify the element which contains the `.modal-content` class. 

The `contentClassName` prop has been added in #5367, but that's not in any release yet.

**Comment by Joshanity17** [comment]
When will the `contentClassName` #5367 will be release? This is a must feature.

**Comment by kyletsang** [comment]
`contentClassName` is now available in 1.4.0
