### ISSUE TITLE
NavDropdown area background color change

### ISSUE THREAD

**Issue by ShaikhSuf** [react-bootstrap/react-bootstrap#5465]
## Is your feature request related to a problem? Please describe

I don't know if it's a problem or not, but I didn't see a place to add the styles to change the NavDropdown background area. I use the bootstrap for Next.Js React.

## Describe the solution you'd like

I would like to have a hook or prop where we can add the required styles to change the background color of the NavDropdown area. 

## Additional context

![image](https://user-images.githubusercontent.com/56292326/95125563-0337fb80-070a-11eb-8c0e-3228d9b21346.png)

**Comment by kyletsang** [comment]
If you're looking to style the dropdown menu, you'll have to use the more verbose way of declaring the dropdown menu.  NavDropdown currently doesn't have a way of passing `style`/`className` to the dropdown menu within.

```
<Dropdown as={NavItem}>
  <Dropdown.Toggle as={NavLink}>Click to see more…</Dropdown.Toggle>
  <Dropdown.Menu>
    <Dropdown.Item>Hello there!</Dropdown.Item>
  </Dropdown.Menu>
</Dropdown>
```

With this, you can apply the `className` to the dropdown menu.

Note: there is currently a bug with `style` prop being overridden in the dropdown menu in 1.3.0.

**Comment by ShaikhSuf** [comment]
Thank you. It works.
