### ISSUE TITLE
Add docs page for CloseButton component

### ISSUE THREAD

**Issue by davidjb** [react-bootstrap/react-bootstrap#5468]
## Is your feature request related to a problem? Please describe

As per #2623, `CloseButton` is exported publicly but isn't documented in the components list.

## Describe the solution you'd like

A page added to the docs. The component is simple but publishing its API would avoid needing to look up the source code. I'm happy to make this as a PR, just seeking feedback before starting + checking it'll be accepted.

## Describe alternatives you've considered

Reading the source code at https://github.com/react-bootstrap/react-bootstrap/blob/master/src/CloseButton.tsx - not hard, but involves remembering where it is.

## Additional context

N/A

**Comment by kyletsang** [comment]
I think this is a good idea.  It was on my todo list for v5 docs since there are new improvements there.

**Comment by davidjb** [comment]
@kyletsang Thanks 👍  Did you want me to look at a PR or did you have this in hand, given the other improvements happening?

**Comment by kyletsang** [comment]
Sure go for it @davidjb.  Thanks :)

**Comment by davidjb** [comment]
Had a crack at it @kyletsang - I found your already-open PR for adding the changes to the docs for v5 so opened a PR against that branch.  Cherry-pick / merge accordingly :+1: 

Wasn't quite sure how the white variants should be conveyed in an example (e.g. I could have used `exampleClassName` on the Playground component and added `bg-dark` there) but I felt this was clearer.

**Comment by kyletsang** [comment]
Fixed in v2 alpha
