### ISSUE TITLE
Standalone Dropdown Menu is never visible

### ISSUE THREAD

**Issue by jmaheshkumar** [react-bootstrap/react-bootstrap#5475]
https://github.com/react-bootstrap/react-bootstrap/issues/5065

**Comment by jmaheshkumar** [comment]
Is we have any solution for this issue? Can anyone please help me to fix it?

**Comment by kyletsang** [comment]
As mentioned in the other thread, you need to override the styles of the menu by setting the opacity and positioning.  You'll have to do this using classes right now in 1.3.0 because there is currently a bug with setting direct styles in the menu (#5466)

**Comment by jmaheshkumar** [comment]
Thank you @kyletsang .

**Comment by kyletsang** [comment]
Closing as answered
