### ISSUE TITLE
Question: Router-Link and collapseOnSelect

### ISSUE THREAD

**Issue by nyn3x** [react-bootstrap/react-bootstrap#5477]
I know there have already been posts (#4080, #4041, #4082)regarding the use of react-router's link with the collapseOnSelect property of the navar.

Those posts suggest the use of react-router-bootstrap and LinkContainer.

However - I don't really understand why this would be necessary. I have somethink like this:

```typescript
<Navbar
                expand="lg"
                variant="light"
                bg="light"
                className="mb-3 fixed-top"
                collapseOnSelect onSelect={()=>log.debug("On Select 1")}
              >
                <Navbar.Brand as={Link} to="/">
                  Sample App
                </Navbar.Brand>
                <Navbar.Toggle aria-controls="basic-navbar-nav" />
                <Navbar.Collapse id="basic-navbar-nav">
                  <Nav className="mr-auto">
                    {isAuthenticated() && (
                      <>
                        {/* <Nav.Item> */}
                          <Nav.Link as={Link} to="/list" onSelect={()=>log.debug("On Select 2")}>
                            Item 1
                          </Nav.Link>
                          <Link to="/list" onSelect={()=>log.debug("On Select 3")} onClick={()=>log.debug("On Select 4")}>Item 2</Link>
                        {/* </Nav.Item> */}
                        <Nav.Item>
                          <Nav.Link href="/new"  onSelect={()=>log.debug("On Select 5")}>
                            Item 3
                          </Nav.Link>
                        </Nav.Item>
                      </>
                    )}
                  </Nav>
                </Navbar.Collapse>
              </Navbar>
```

For debugging purpose I added some debug-logging - but only "On Select 4" is being logged when "item 1" is clicked, as well as "On Select 5" and "On Select 1" when "item 3" is clicked. So I guess this could be part of the problem. But I don't really understand why "On Select 2" or "On Select 1" are not being fired when "item 1" is clicked.

**Comment by kyletsang** [comment]
Here's the click handler that is used for `NavLink`:
https://github.com/react-bootstrap/react-bootstrap/blob/5a5c3eb6dfc42f8a5f4b11e573f5c4288233d602/src/AbstractNavItem.tsx#L100-L105

`navKey` is derived from `href` or `eventKey`, and since your nav link in "Item 1" does not have any of those, this function returns before hitting `onSelect`.  If you add `eventKey`, you should see your log messages.

**Comment by nyn3x** [comment]
OK, thx - that did the trick - and of course this also made the menu to collapse on select!
