### ISSUE TITLE
Ref forwarding, buttons, and useImperativeHandle()

### ISSUE THREAD

**Issue by SachaG** [react-bootstrap/react-bootstrap#5479]
I'm trying to focus/blur a button on certain events using the `Button` component which it itself encapsulated inside my own `CustomButton` component, but so far I can't get it to work. 

The general pattern is: 

### Form component

```jsx
const MyForm = () => {
  const buttonRef = useRef();
  return (
    <div>
      ...
      <SubmitButton 
        inputRef={buttonRef}
        onClick={() => {
            // do something
            buttonRef.current.blur() // <- not working
        }}
      />
    </div>
  )
};
```

### Custom Button Component

(Should I be using forwardRef() here as well instead of just passing down the ref as the `inputRef` prop? It doesn't seem like it but maybe I got this wrong?)

```js
const BootstrapButton = ({ children,  inputRef}) => 
  <Button ref={inputRef}>{children}</Button>;
```

Although the ref seems set when looking at my components through the React devtools, when I try to call it inside my code it comes up as `{current: null}`. 

The React docs for [useImperativeHandle](https://reactjs.org/docs/hooks-reference.html#useimperativehandle) mention that:

> In this example, a parent component that renders <FancyInput ref={inputRef} /> would be able to call inputRef.current.focus().

However it doesn't seem like React Bootstrap uses `useImperativeHandle()`? Could that be a problem?

**Comment by jquense** [comment]
Can you put a reproduction together we can run?

**Comment by SachaG** [comment]
Yeah sorry for not including one, I didn't have time to make one yet. In the meantime maybe someone will know what I'm doing wrong?

**Comment by kyletsang** [comment]
A code repro would help us here, although this doesn't seem like a react bootstrap problem?  Is your `SubmitButton` passing the `inputRef` down properly?

**Comment by SachaG** [comment]
I have to confess I gave up on this, at least for now, so I probably won't have time to make a repro or narrow down the issue more. I think unless someone else runs into the same problem it's probably ok to close this issue for now?

**Comment by kyletsang** [comment]
Sure, I'll close this for now
