### ISSUE TITLE
printing issues

### ISSUE THREAD

**Issue by ShaMan123** [react-bootstrap/react-bootstrap#5482]
## Describe the bug

`@media print` css query causes trouble when printing web content.
It blocks the possibility to change orientation and it changes the content's size.

## To Reproduce

Open the print dialog. You will notice that the orientation option disappears and the content doesn't fit correctly.

## Expected behavior

**Printing should not be affected by this library.**
All though it can be handled by overriding the css, it is an annoying bug that is extremely hard to trace.

## Environment (please complete the following information)

- Operating System: Windows10
- Browser, Version:  86.0.4240.75
- React-Bootstrap Version: 4.5.3

**Comment by kyletsang** [comment]
You'll need to file this at the [bootstrap github project](https://github.com/twbs/bootstrap/issues).  React-Bootstrap only provides the react implementation of bootstrap and not the css.

**Comment by ShaMan123** [comment]
I took a look at bootstrap and it seems they've decided to dump all print related `css`. Looking at the latest `css`, it seems it's been rolled out already, so it is a matter of updating this library after all.
