### ISSUE TITLE
Auto-Complete component consideration

### ISSUE THREAD

**Issue by IkeAgbasi** [react-bootstrap/react-bootstrap#5483]
Has there been any consideration into adding an Auto-Complete component. A component that allows developers to easily add a drop-down under any text input and maybe part of the api could be a place to put an async api call that will populate the drop-down?

**Comment by jquense** [comment]
Hi there, we don't add components that aren't present in normal bootstrap. There are a  few good third party components tho that work nicely with react-bootstrap. react-widgets, react-autocomplete, react-select, etc
