### ISSUE TITLE
How to close transitions FADE outer click. 

### ISSUE THREAD

**Issue by dropways** [react-bootstrap/react-bootstrap#5484]

**Comment by kyletsang** [comment]
Can you provide more details?  Code repro + more details on what you're trying to do?

**Comment by dropways** [comment]
Hello @kyletsang 

Here is the demo link

https://codesandbox.io/s/react-bootstrap-fade-outside-click-close-ixpyq

i want to use fade like a dropdown.

**Comment by kyletsang** [comment]
You might want to consider using the existing react-bootstrap implementation of `Dropdown` and wrapping the `DropdownMenu` element with `Fade`.  At least this way, all the heavy lifting of the dropdown is done for you.  Use the `onToggle` and `show` props in `Dropdown` to control `Fade`'s `in` prop.

If you want to see how all this works, take a look at react-overlays dropdown implementation as that is used under the hood:
https://github.com/react-bootstrap/react-overlays/blob/master/src/Dropdown.tsx

**Comment by kyletsang** [comment]
Closing as answered
