### ISSUE TITLE
There will be countless ʻaria-describedby` values ​​on the `event.target` element of Overlays.

### ISSUE THREAD

**Issue by simonguo** [react-bootstrap/react-bootstrap#5488]
# How to reproduce?
This problem can be reproduced in the react-bootstrap documentation.
https://react-bootstrap.github.io/components/overlays/#popovers
Click the button that triggers the Popover, and then scroll the page.

![image](https://user-images.githubusercontent.com/1203827/96667181-1f36d080-138b-11eb-8223-8e90917bd4a6.png)

**Comment by distinctdan** [comment]
I came here about this same issue, it also happens on page resize.
