### ISSUE TITLE
Cannot import react-bootstrap in typescript react app

### ISSUE THREAD

**Issue by hitrop** [react-bootstrap/react-bootstrap#5491]
I installed react-bootstrap and the types using:

`npm i react-bootstrap @types/react-bootstrap`

However, I keep getting the following error (even if I dont import anything from react-bootstrap in any of my components):

```
TypeScript error in node_modules/react-bootstrap/esm/index.d.ts(2,1):
Declaration or statement expected.  TS1128

    1 | export { default as Accordion } from './Accordion';
  > 2 | export type { AccordionProps } from './Accordion';
      | ^
    3 | export { default as AccordionContext } from './AccordionContext';
    4 | export { default as AccordionCollapse } from './AccordionCollapse';
    5 | export type { AccordionCollapseProps } from './AccordionCollapse';

```

Am I missing something here?

**Comment by kosmiq** [comment]
You are using a TypeScript version below 3.8.

See:
- https://github.com/react-bootstrap/react-bootstrap/issues/5355
- https://github.com/react-bootstrap/react-bootstrap/issues/5281
