### ISSUE TITLE
force focus nav link

### ISSUE THREAD

**Issue by iamrekas** [react-bootstrap/react-bootstrap#5492]
I look through all code to find that buggy to my for my custom made tab for smaller version that will be using on mobile and i was figure out that i can't prevent in core hard coded force focus. I am already customized some this lib component for extra feature. i think be cool if it will be can be disabled for no extra code only one variable.

https://github.com/react-bootstrap/react-bootstrap/blob/master/src/AbstractNav.tsx#L132

This action.

For this action, then i am going from first to last tab, i will scrolled down force to almost page bottom.

Thank you.

**Comment by kyletsang** [comment]
The focus is only run if there are key presses on the nav elements.  This shouldn't be a problem on mobile?

**Comment by iamrekas** [comment]
i am manage self active element and using with tabs. on mobile version requiring to be like carousel type, so then look at examples in documents, i made that way. but i very strange behaviors saw, that entire window scroll down then it's refocusing. so i my case it must do not refocus element. i am already made fork and within few hours will pull request for this issue, only for ability and new feature for that api for disabling focusing.

**Comment by iamrekas** [comment]
srry, i was tested that focus logic. it's correct. something else is buggy.. then i am going through nav links it's scrolling entire window. look for more details..

**Comment by iamrekas** [comment]
@kyletsang look at this sandbox, maybe it's can help to describe more detailed my issue. 
https://codesandbox.io/s/react-boostrap-test-g3iuh?file=/src/App.js
try scroll into middle and press next/prev buttons and look to it what it will do.

**Comment by kyletsang** [comment]
Looked through the sandbox and can see the window scrolls a little bit after clicking the buttons.  This seems like it's caused by the markup rather than RB.  Try removing the `flex-column` class on the nav - that stops the scrolling at least on my side.
