### ISSUE TITLE
React 17 and overlay components

### ISSUE THREAD

**Issue by tateman74** [react-bootstrap/react-bootstrap#5498]
Hey Guys.

You probably know this by now but React 17 stopped all event propagation at the root node.  That breaks rootClose for any components that have that option.

Might you guys be working on a beta or have something in the works that can fix that?  I know how much it stinks managing your own click handlers on document.  :|

The symptom is that the tooltip node shows for a split second in the inspector and then closes itself.

Thanks,
Steven

**Comment by jquense** [comment]
see: https://github.com/react-bootstrap/react-overlays/pull/880 need to update everything still

**Comment by tateman74** [comment]
Thanks.  I'll go ahead and close this then.  Fixed by commit:
ee0d4e1220a74a2aabe6963e9e97ee43dde6e937
