### ISSUE TITLE
Showing a modal breaks dropdown toggles

### ISSUE THREAD

**Issue by jcreixell** [react-bootstrap/react-bootstrap#5499]
## Describe the bug

Showing and closing a modal in a page containing dropdowns causes the dropdown toggles to stop working. 

## To Reproduce

1. Open a page containing a dropdown button with some items and a hidden modal. Click the button and the dropdown menu is properly displayed.
2. Show the modal (either via button trigger or other means) and close it again, either by a close button or clicking outside of the modal.
3. Click on the dropdown button again. Nothing happens, the items are not shown.

## Reproducible Example

https://codesandbox.io/s/cool-resonance-66jre?file=/src/App.js

## Expected behavior

The dropdown toggle keeps working after showing a modal.

## Environment (please complete the following information)

- Operating System: Linux, Mac
- Browser: Chromium 86, Firefox 82
- React-Bootstrap Version 1.4.0

## Additional context

The problem is best understood with the attached example. I saw somebody else report this problem in StackOverflow but the message was deleted ([cached version](https://webcache.googleusercontent.com/search?q=cache:1QVsPwqITHEJ:https://stackoverflow.com/questions/64529769/react-bootstrap-opening-and-closing-one-modal-breaks-all-dropdown-toggles-on-p+&cd=1&hl=en&ct=clnk&gl=de&client=firefox-b-d)).

If I am doing something wrong, please let me know. Thanks!

**Comment by kyletsang** [comment]
Are you using react v17?  If so, there's currently a known issue: #5409

**Comment by jcreixell** [comment]
I am using react v17.0.1. I can confirm that downgrading to v16.14.0 solves the problem indeed!

**Comment by kyletsang** [comment]
Thanks for confirming.  I'm going to close this issue as a dupe.  Follow the other thread for updates.
