### ISSUE TITLE
Browser console warning about slowness due to prototype modification

### ISSUE THREAD

**Issue by leth** [react-bootstrap/react-bootstrap#550]
Seen in Firefox on our local project, but also [on the docs pages](http://react-bootstrap.github.io/components.html).

>mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create

**Comment by AlexKVal** [comment]
Thank you. Confirmed.
I'll try to investigate it.

**Comment by AlexKVal** [comment]
The culprit is the generated ES5 code for `react-router/ContextWrapper`.
I've found it via specific typo in comments :) `It sovles this ...`
https://github.com/rackt/react-router/blob/master/modules/components/ContextWrapper.js#L3

The bug is the candidate for a new issue in `react-router` project :wink: 

The generated code: (disclaimer: the code copied as is from Firefox console)
this snippet causes warning: `subClass.prototype = Object.create(superClass ...`
```js
/***/ },
/* 71 */
/***/ function(module, exports, __webpack_require__) {

	"use strict";
	
	var _createClass = (function () { function defineProperties(target, props) { for (var key in props) { var prop = props[key]; prop.configurable = true; if (prop.value) prop.writable = true; } Object.defineProperties(target, props); } return function (Constructor, protoProps, staticProps) { if (protoProps) defineProperties(Constructor.prototype, protoProps); if (staticProps) defineProperties(Constructor, staticProps); return Constructor; }; })();
	
	var _inherits = function (subClass, superClass) { if (typeof superClass !== "function" && superClass !== null) { throw new TypeError("Super expression must either be null or a function, not " + typeof superClass); } subClass.prototype = Object.create(superClass && superClass.prototype, { constructor: { value: subClass, enumerable: false, writable: true, configurable: true } }); if (superClass) subClass.__proto__ = superClass; };
	
	var _classCallCheck = function (instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } };
	
	/**
	 * This component is necessary to get around a context warning
	 * present in React 0.13.0. It sovles this by providing a separation
	 * between the "owner" and "parent" contexts.
	 */
	
	var React = __webpack_require__(2);
	
	var ContextWrapper = (function (_React$Component) {
	  function ContextWrapper() {
	    _classCallCheck(this, ContextWrapper);
	
	    if (_React$Component != null) {
	      _React$Component.apply(this, arguments);
	    }
	  }
	
	  _inherits(ContextWrapper, _React$Component);
	
	  _createClass(ContextWrapper, {
	    render: {
	      value: function render() {
	        return this.props.children;
	      }
	    }
	  });
	
	  return ContextWrapper;
	})(React.Component);
	
	module.exports = ContextWrapper;

/***/ },
```

**Comment by leth** [comment]
@AlexKVal Thanks for looking into this! 
Is this code embedded in react-bootstrap, or in react-addons? I don't see anything pulling this into our local project as a dependency.

**Comment by AlexKVal** [comment]
You have mentioned the [react-bootstrap docs pages](http://react-bootstrap.github.io/components.html) and I checked it.
The [components](http://react-bootstrap.github.io/components.html) page in this project uses `react-router` and `babel@5`.
The code I've mentioned have been compiled from those two libraries.
If your project does not use the `react-router` then the problem may be injected by `babel@5` compiled code.

**Comment by iyn** [comment]
So, is there a way to solve this problem? 

It's not caused by `react-router` (see: https://github.com/rackt/react-router/issues/1155). I'm using `babel` to compile ES6 -> ES5, but the warning is shown only when `react-bootstrap` is included.

**Comment by AlexKVal** [comment]
I must apologize for not being clear in my previous posts. :cherries: 

The `react-router` is not the source of the problem. ( it helped to find it though :smile: )

The culprit is this autogenerated line of code.
(I've re-formatted it.)
```js
var _createClass = (function () {
  function defineProperties(target, props) {
    for (var key in props) {
      var prop = props[key];
      prop.configurable = true;
      if (prop.value) prop.writable = true;
    }

    Object.defineProperties(target, props); 
  }

  return function (Constructor, protoProps, staticProps) {
    if (protoProps)  defineProperties(Constructor.prototype, protoProps); // mutating the [[Prototype]]
    if (staticProps) defineProperties(Constructor, staticProps);

    return Constructor;
  };
})();
```

Related issues and answers. 
https://github.com/babel/babel/issues/1099
https://github.com/zloirock/core-js/issues/46

--
And it seems there is no solution with FF at this time.
https://github.com/babel/babel/issues/1466#issuecomment-99752513

**Comment by iyn** [comment]
Thank you for a detailed explanation, much appreciated.

**Comment by brennanerbz** [comment]
Any update on this bug?

**Comment by taion** [comment]
This isn't a bug, and the React Router dependency isn't even part of our release - just the docs page.

**Comment by taion** [comment]
It's an unavoidable side-effect of using Babel's transpilation for classes.
