### ISSUE TITLE
Dropdown component add props to enable Esc key for close.

### ISSUE THREAD

**Issue by M-Husein** [react-bootstrap/react-bootstrap#5505]
## Is your feature request related to a problem? Please describe

I need enabled / disabled Esc key for close Dropdwon Menu.

## Describe the solution you'd like

Maybe props name is:
enableEsc : Boolean

## Additional context

Thanks.

**Comment by kyletsang** [comment]
Dropdowns already support escape key handling.  Did you mean you want to disable it?  This goes against accessibility standards though.

**Comment by M-Husein** [comment]
@kyletsang Thanks for reply :)

Yes I want to control disable / enable Esc key, cause some case I think we need to manually control this behavior.
I know this is goes against accessibility standards, so the default props must be true

example:

<Dropdown 
    esc={false} 
>

**Comment by kyletsang** [comment]
I suppose we could allow custom `onKeyDown` handling here that could allow you to prevent the base dropdown's `onKeyDown` handler from running.  This could also open the door for "printable characters" keyboard support in accessibility:  https://www.w3.org/TR/wai-aria-practices-1.1/examples/listbox/listbox-collapsible.html.

**Comment by M-Husein** [comment]
What do you mean onKeyDown in the Component Dropdown?
If so, that sounds good to me.

Please, add this if you think ok.
Thanks.

**Comment by kyletsang** [comment]
@jquense, would this be the right solution for this?

**Comment by Garz4** [comment]
@kyletsang Hello! I am interested in contributing here.
Do you mean to prevent custom keys to run the `onKeyDown` handler?
i.e.
`<Dropdown preventOnKeyDown="esc" />`

**Comment by kyletsang** [comment]
@Garz4, the solution I'm thinking of is to allow `Dropdown` in react-overlays to accept `onKeyDown` as a prop.  Then in that handler, you can call `preventDefault()` which will stop react-overlay's key handler from running.

**Comment by jquense** [comment]
The pattern to accomplished is to control the `show` prop via `onToggle` and block updates as needed. In this case you can use the source `event` and `metadata` arguments to `onToggle` to determine what triggered the close, and choose to not pass it back to `show` depending on your condition:

```js
handleToggle(nextShow, event, metadata) {
  const isEsc = event.type === 'keydown' && metadata.source === 'rootClose'
  if (!nextShow && isEsc && escDisabled) {
    return
  }
  setShow(nextShow)
}
```

**Comment by kyletsang** [comment]
Just noticed there's an issue where root close in react-overlays is not sending the keyboard event to the toggle handler.  

Looks like this should be resolved in this PR: https://github.com/react-bootstrap/react-overlays/pull/843

**Comment by kyletsang** [comment]
Should be able to handle this behavior with the method @jquense mentioned above using 1.5.2 now.
