### ISSUE TITLE
Modal with FormControl reloads every time onChange triggers and looses focus on input 

### ISSUE THREAD

**Issue by rpsutton** [react-bootstrap/react-bootstrap#5506]
## Describe the bug

I am using a Modal with a simple Form inside of it. The `onChange` function which is used to update the state of the search term becomes out of focus after each character is typed. I assume this is because the Modal is reloading every time `onChange` is called for some reason. 

## To Reproduce

1. Initialize state using hooks like `const [ searchTerm, setSearchTerm] = useState("");`
2. Nest a Form with FormControl within a modal.
2. Pop up the modal and attempt to input text.

## Reproducible Example

https://codesandbox.io/s/modalformissue-rhzix?file=/src/App.js

## Expected behavior

The FormControl's `onChange` method should update searchTerm without losing focus after each input

## Environment

See code sandbox example for environment

**Comment by kyletsang** [comment]
You shouldn't be declaring components within components like that.  Move `FormComponent` and `MyVerticallyCenteredModal` outside `App`.
