### ISSUE TITLE
How to modify Bootstrap variables?

### ISSUE THREAD

**Issue by ferittuncer** [react-bootstrap/react-bootstrap#5509]
How to modify a Bootstrap variable?

Example: 

`$grid-columns: 12 !default;` I want to modify this to: `$grid-columns: 24;` 

I have tried adding an scss override file but it does not work. Overriding this on the preprocessor level does not make any effect because I guess React-Bootstrap compiles to CSS and then imports. So what's the proper way to do this?

**Comment by jquense** [comment]
React bootstrap doesn't do anything with CSS, up to you to import it or build it from sass files. The plain bootstrap docs for theming will work for react bootstrap with no modifications

**Comment by ferittuncer** [comment]
Weird because I couldn't make an scss override file work like explained in Bootstrap documentation. I am going to try to find why then. Thanks.

**Comment by kosmiq** [comment]
I'm going to assume that you use create-react-app here.

So I'm using it in a project setup with CRA. I've added node-sass as a dependency (I'd recommend using dart-sass, but I'm currently unable to in my project for reasons unrelated to Bootstrap).

1. Create app.scss in the assets folder or wherever you like.
2. Create _variables.scss in the same folder
3. Import your _variables.scss file into app.scss:
`@import "variables";`
4. Import bootstrap scss into your app.scss
`@import "~bootstrap/scss/bootstrap";` (or the individual components you need/want: [https://getbootstrap.com/docs/4.5/getting-started/theming/#importing](https://getbootstrap.com/docs/4.5/getting-started/theming/#importing))
(app.scss will look like:
```
@import "variables";
@import "~bootstrap/scss/bootstrap";
```
)
5. Override the variables you need to override in _variables.scss
6. Import app.scss into your app.tsx (`import './assets/scss/app.scss';)`

When you run the application using npm start (or whatever you prefer) the scss will be compiled with your scss variable overrides.

**Comment by ferittuncer** [comment]
Thanks, this worked. @kosmiq 

I think the issue was me not having `bootstrap` installed.
