### ISSUE TITLE
Vertically scrollable table

### ISSUE THREAD

**Issue by zemse** [react-bootstrap/react-bootstrap#5511]
## Is your feature request related to a problem? Please describe

`Table` has a handy flag of `responsive` which makes it horizontally scrollable on smaller devices. But it is difficult to get the Table vertically scrollable given a height.

## Describe the solution you'd like

```jsx
<Table height={500}>

</Table>
```

Adding in a height property makes the table vertically scrollable if it is overflowing.

## Acknoledgements

Thanks to this library and the contributers! Creating sites has become very quick due to having primitives like `Alert`, `Card` in the library.

**Comment by kyletsang** [comment]
You need to wrap the table with another element that contains your `height` and `overflow` style. 

For example:
```
<div style={{ height: '200px', overflowY: 'auto' }}>
  <Table>
    ...
  </Table>
</div> 
```

**Comment by zemse** [comment]
It'd be great if the header stays when users are scrolling. I mean if the `overflow` style is applied to `tbody`, it'd be cool. But presently it requires setting `display: block` on `tbody` which breaks the table's layout.

**Comment by kyletsang** [comment]
Those can be solved with a number of solutions.  I suggest checking StackOverflow for a solution that fits your use case.

**Comment by rsaid99** [comment]
Better but still problematic.  If your header has a border around each cell they scroll away with the rows.  

Given This is a common use case it would be useful if it was supported 'under the hood'.  As of now there is no obvious way to implement this via CSS or inline styles without introducing other anomalies.

**Comment by alsanchez-dev** [comment]
@rsaid99  I built 3 vertical scroll react-bootstrap tables putting them inside a div you rid of this problem. Yes, I had this issue as well but was not a big deal to solve it by using a div to wrap each table.
