### ISSUE TITLE
Need a release script to only publish docs updates

### ISSUE THREAD

**Issue by mtscout6** [react-bootstrap/react-bootstrap#552]
When we find docs typos it would be nice to have that release not bump the version of the library. All the code to programmatically release the docs is there, but it coupled to a full release...

STEPS:
- [ ] update Maintaining about cherry-picking to "new" docs branch
- [x] extract small script for doc release that tags with tag-docs.X
- [ ] Make sure master gets merged in docs when a release is made.

**Comment by dozoisch** [comment]
So what you want basically is just to extract the code that pushes the docs to `react-bootstrap.github.io.git` without the bumping and tagging?

Should we be adding like the `react-bootstrap/react-boostrap.git` commit hash to the version like `v0.20.3 #ea2145` so that we can track the deployed doc version?

**Comment by mtscout6** [comment]
[gitter conversation April 22 2015 12:04 PM](https://gitter.im/react-bootstrap/react-bootstrap?at=5537e290c6d9d4681f88055d)

**Comment by AlexKVal** [comment]
I've noticed that here there is no reference to the issue #547 here.

**Comment by mtscout6** [comment]
That is another problem :wink:

**Comment by mtscout6** [comment]
@dozoisch Correct, I don't want to bump or tag this repo and force us to push an npm, and bower release.

**Comment by dozoisch** [comment]
@mtscout6  Alright the main issue left now is to release only "wanted changes" to the docs.

**Comment by mtscout6** [comment]
Correct, so what i'm thinking is that this may just need to be more of a training issue to use git to cherry-pick the desired updates to a branch that would get tagged and pushed. We can work up documentation for that in the MAINTAINING guide at the root of the repo.

**Comment by dozoisch** [comment]
Make sense.

So steps I see
- [ ] update Maintaining about cherry-picking to "new" docs branch
- [ ] extract small script for doc release that tags with tag-docs.X
- [ ] Make sure master gets merged in docs when a release is made.

**Comment by mtscout6** [comment]
:+1:

**Comment by mtscout6** [comment]
@dozoisch Shall we close this and continue any conversation in that PR?

**Comment by dozoisch** [comment]
Sure
