### ISSUE TITLE
npm ERR! Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by klleroy** [react-bootstrap/react-bootstrap#5520]
## Describe the bug

When installing react-bootstrap via npm I am receiving the following errors...
```
npm WARN ERESOLVE overriding peer dependency
npm ERR! Cannot read property 'length' of undefined

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/[username]/.npm/_logs/2020-11-13T21_37_10_715Z-debug.log
```

## To Reproduce

1. Create Project Dir (mkdir `my-app`)
2. Create React App (`npx create-react-app frontend`)
3. Navigate to install dir (`cd my-app/frontend`)
4. Install (`npm i react-bootstrap`)
5. See error

## Expected behavior

Expectation is that package would be installed.

## Screenshots
![Screen Shot 2020-11-13 at 1 43 07 PM](https://user-images.githubusercontent.com/17477183/99124024-347fd300-25b6-11eb-8a92-1606838a95fe.png)

## Environment (please complete the following information)

- Operating System: [macOS 10.15.7 (19H2)]
- Browser, Version [Brave V1.16.76]
- NPM Version [7.0.10]
- Node Version [15.2.0]
- React-Bootstrap Version [1.4]

## Additional context

I can successfully install other packages such as `react-router-dom` without incident, but am unable to install this particular package.

**Comment by kyletsang** [comment]
Can you try updating your npm to 7.0.11?  This should be fixed there.

https://github.com/npm/cli/releases/tag/v7.0.11

**Comment by klleroy** [comment]
Confirmed that has fixed the issue. Thanks so much for your response!!
