### ISSUE TITLE
OverlayTrigger will break Dropdown

### ISSUE THREAD

**Issue by trueg** [react-bootstrap/react-bootstrap#5522]
When using an OverlayTrigger with a Dropdown triggering the overlay once will break all dropdowns (closed directly after opening). By "all" I mean that not only the one Dropdown stops working but all other dropdowns, too.

See the following Stackoverflow question for a good example: https://stackoverflow.com/questions/64716453/react-bootstrap-triggering-a-popover-seems-to-break-dropdown-components

**Comment by kyletsang** [comment]
Likely the same issue as #5409.  Delete react-overlays from your node_modules folder and run an install again.  The version you are looking for is 4.1.1

**Comment by trueg** [comment]
Yes! Thank you!
