### ISSUE TITLE
Popover - Fading color contrast AXE issues

### ISSUE THREAD

**Issue by vduarteb** [react-bootstrap/react-bootstrap#5525]
## Describe the bug

When opening a popover, and running the AXE tests, there are some issues with the color contrast. After analyzing it for a while, we believe it's due to the animation of the popover, so when running AXE in a non-static way, it takes into account the color contrast while the popover is fading. The issue says that the foreground color is a color that isn't used anywhere in the code, and shows contrast issues with the background color (must be due to the fading)

## To Reproduce
1. Create a popover with a focus trigger
2. Open the popover
3. Run an AXE analysis with the popover opened

## Expected behavior

When running AXE, and having colors on the popover that pass every contrast test, there should be 0 issues.

## Screenshots

<img width="433" alt="Captura de pantalla 2020-11-17 a las 14 47 27" src="https://user-images.githubusercontent.com/47390236/99440949-41b5fe00-28e5-11eb-9b62-a09f5489fbf6.png">
<img width="423" alt="Captura de pantalla 2020-11-17 a las 14 47 38" src="https://user-images.githubusercontent.com/47390236/99440972-48dd0c00-28e5-11eb-9466-be1bfae08455.png">

## Environment (please complete the following information)

- Operating System: macOS
- Browser, Version: Chrome 86
- React-Bootstrap Version: 1.4.0

**Comment by kyletsang** [comment]
You should open an issue in the [bootstrap](https://github.com/twbs/bootstrap) repo.  React-Bootstrap does not handle any of the styling.
