### ISSUE TITLE
Popover - Background element's color not determined AXE issues

### ISSUE THREAD

**Issue by vduarteb** [react-bootstrap/react-bootstrap#5526]
## Describe the bug

When opening a popover, and running the AXE tests, there are some issues with the color contrast, because AXE says that the background color can't be determined due to an overlapping object. Every piece of text that gets covered by the popover sends an issue because as they can't detect the background color, they can't calculate correctly the contrast ratio so the page doesn't pass the AXE tests.

## To Reproduce
1. Create a popover with a focus trigger
2. Open the popover
3. Run an AXE analysis with the popover opened

## Expected behavior

When running AXE, and having colors on the popover that pass every contrast test, there should be 0 issues.

## Screenshots

<img width="423" alt="Captura de pantalla 2020-11-17 a las 14 47 52" src="https://user-images.githubusercontent.com/47390236/99442580-99556900-28e7-11eb-85fb-916f79c20e3b.png">
<img width="432" alt="Captura de pantalla 2020-11-17 a las 14 48 01" src="https://user-images.githubusercontent.com/47390236/99442583-9a869600-28e7-11eb-9a71-f56cbe3e9398.png">

## Environment (please complete the following information)

- Operating System: macOS
- Browser, Version: Chrome 86
- React-Bootstrap Version: 1.4.0

**Comment by kyletsang** [comment]
You should open an issue in the [bootstrap](https://github.com/twbs/bootstrap) repo.  React-Bootstrap does not handle any of the styling.
