### ISSUE TITLE
Document must have one main landmark and a All page content must be contained by landmarks in Axe validator when creating a modal

### ISSUE THREAD

**Issue by jcmontoyar** [react-bootstrap/react-bootstrap#5527]
## Describe the bug

When creating a modal with react bootstrap the axe valitator shows both issues in the title.

## To Reproduce

1. Create any modal or just go to the modal component in the react documentation 
2. Inspect element in google chrome
3. Run axios validator
4. Both issues will appear

## Environment (please complete the following information)

- Operating System: windows 10
- Browser, Version [e.g. Chrome 86]
- React-Bootstrap Version 1.4.0

**Comment by kyletsang** [comment]
Looks like upstream bootstrap has removed `role="document"` from the modal in https://github.com/twbs/bootstrap/issues/30687.  We should do the same here.
