### ISSUE TITLE
CustomToggle button nested under Accordion.collapse will not properly function

### ISSUE THREAD

**Issue by jayacados** [react-bootstrap/react-bootstrap#5528]
## Describe the bug

I upgraded to the newest react-bootstrap version (1.4.0) in my development app and the accordion component breaks. Creating custom toggle, nested under Accordion.collapse and clicking on the custom toggle button will no longer expand/collapse as expected

Out of curiosity, I attempted this in CodeSandBox, using version 1.4.0, strictly with just the Basic Example as seen here: https://react-bootstrap.github.io/components/accordion/#basic-example

The accordion continues to not behave as expected. Console errors show the following:
`Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of Transition which is inside StrictMode. Instead, add a ref directly to the element you want to reference.`

## To Reproduce

1. Install the latest version of react-bootstrap
2. Implement the example from codesandbox
3. View and try clicking the buttons to verify that the collapse/expand button fail

## Reproducible Example

Minimal example by using [CodeSandbox](https://codesandbox.io/s/nervous-darkness-dv130?file=/src/App.js).

## Expected behavior

Accordion to collapse and expand upon button click.

## Environment (please complete the following information)

- Operating System: macOS
- Browser, Version: Chrome 86.0.4240.198 (Official Build) 
- React-Bootstrap Version [1.4.0]

## Additional context

The accordion was working as expected in version 1.0.1

Edit: Revise to proper more details

**Comment by kyletsang** [comment]
If you add the bootstrap css to your code sandbox example, the accordion will work.  The warning you see is just a warning from react-transition-group and won't impact the functionality of the accordion.

**Comment by jayacados** [comment]
Thanks @kyletsang ! perhaps this may be the issue also in the larger app that I'm working on. Any ideas on why moving from `1.0.1` to `1.4.0` may result in breakage? Is it due to the fact that I may also need to include the updated bootstrap css when I did an `npm update` ?

**Comment by kyletsang** [comment]
It shouldn't break from 1.0.1 though.  All of bootstrap's v4 css should just work so you don't need to update those unless you're looking for new features.

Are you able to share a code repro of the accordion from your app?

**Comment by jayacados** [comment]
I'm not able to provide the actual code since it's private, but here is something similiar I'm trying to achieve on code sandbox below:

https://codesandbox.io/s/nervous-darkness-dv130?file=/src/App.js

Essentially, clicking on a button will open the next accordion. It seems to work in code sandbox however. I copied and pasted the exact code from the docs and it doesn't seem to work as well. I also made sure that the bootstrap min css is imported in the root directory, specifically in the sass file

**Comment by kyletsang** [comment]
Hmm let's take a step back here (maybe I'm misunderstanding something in your last response).  Are you trying to make it so that clicking on toggle 1 will expand/collapse the *next* card that's under toggle 2?  Or do you want the behavior to be like in the docs page where the toggle will expand/collapse the card underneath it?

**Comment by jayacados** [comment]
Sorry for the misunderstanding! You are correct. I am trying to implement a behavior where clicking Button 1 will collapse Card 1, but expand what's under Card 2. I've revised my code sand box to look like it here: 
https://codesandbox.io/s/sharp-zhukovsky-6m456?file=/src/App.js

I've successfully implemented this back in 1.0.1 but I'm not sure why this breaks

**Comment by kyletsang** [comment]
Ah ok this makes sense now.

There was a bug where any component inside the `AccordionCollapse` that implements `SelectableContext` (like dropdowns, list groups, navs) would trigger the accordion to collapse inadvertently.  I fixed this in #5201.  This fix would also prevent `AccordionToggle`s from working if nested within the `AccordionCollapse`.  

Sorry about that - I did not anticipate the usage of the accordion toggle within the collapse when making that fix.

Would you be able to change your code to control the `activeKey` in your component?  For example, here's a rough idea:
https://codesandbox.io/s/condescending-goldwasser-jtzeh?file=/src/App.js

**Comment by kyletsang** [comment]
On another side note, there is a proper fix for the accordion context issue in #5517 which is scheduled for the Bootstrap 5 release.  This would allow toggles to work within collapses again

**Comment by jayacados** [comment]
Thanks @kyletsang ! Appreciate the detailed comments. I'll look forward the Bootstrap 5 release in the near future. As for now, I can definitely utilize handler react hooks state to manage the `activeKey` component. Closing this comment for now!
