### ISSUE TITLE
Is it possible to render a Modal to a container el but still apply the overflow/padding styles to the body

### ISSUE THREAD

**Issue by marmite22** [react-bootstrap/react-bootstrap#5535]
## Is your feature request related to a problem? Please describe

My React app is being loaded inside someone elses page. As such I want to render modals from my app into a specific div on the page that I control (preventing interfering with their page layout etc).

When I set the `container` prop on the Modal to render into my div, the code that normally calculates the scrollbar width and applies `padding-left` and `overflow: hidden` to the body element instead applies those styles to my container element.

## Describe the solution you'd like

Is there a way already, or perhaps a change that could be made that would allow the separation of where the modal is rendered from where those styles are applied so that I can render to a container div but still have the styles/scroll blocking applied to the body.

## Describe alternatives you've considered

If it's not possible I suppose I can re-implement the scrollbar width calculation and apply the styles to the body on modal open but I wondered if there was a way of doing this already before I went down that route.

Thanks

**Comment by kyletsang** [comment]
You can control custom behavior like this by passing a custom `ModalManager` using the `manager` prop in `Modal`.  

React-bootstrap extends the `ModalManager` from react-overlays and adds additional bootstrap-specific code.  See both these files for reference:
https://github.com/react-bootstrap/react-overlays/blob/master/src/ModalManager.ts
https://github.com/react-bootstrap/react-bootstrap/blob/master/src/BootstrapModalManager.tsx

**Comment by marmite22** [comment]
Forgive me if I'm making some dumb mistake here but removeContainerStyle is not being called.

Here is my really simple example of extending the ModalManager:
```
import ModalManager from 'react-overlays/ModalManager';
class SubModalManager extends ModalManager {
    setContainerStyle(containerState, container) {
      // this is called
      super.setContainerStyle(containerState, container);
    }
    removeContainerStyle(containerState, container) {
      // this is not called.
      super.removeContainerStyle(containerState, document.body);
    }
}
```

This is what seems to be the issue - The ModalManager class that I’m extending from has a couple of methods - `_proto.add`  and `_proto.remove`.

`add` does `this.modals.push(modal);` when you open a modal (and that seems to work)

When you close the modal it checks `this.modals.indexOf(modal);` and returns if the index is -1.

My problem seems to be if I step through that `remove` method `this.modals` is always an empty array so it never calls my `removeContainerStyle`. 

If I put a breakpoint on either of those lines, I can see that `this` is an instance of my `SubModalManager` that I’m extending. I think I probably need to be using bind or scoping things or something but I'm not exactly sure what I'm doing wrong.

Thanks.

**Comment by kyletsang** [comment]
Hmm, it should work.  I made a sandbox here, so you can check what differences you have in your code:
https://codesandbox.io/s/gracious-worker-kte5r?file=/src/App.js

This example sets a custom background color into the container and also removes the scrollbar from the body.

Hope this helps.

**Comment by marmite22** [comment]
You wonderful human. That example was so useful. It was entirely me being an idiot and I didn't pass the extended manager as a ref - so it was being re-initialised and that's why it was losing the array of modals.

`const managerRef = React.useRef(new SubModalManager());` was the magic!

Everying is working perfectly now, thanks.
