### ISSUE TITLE
Typescript compile break in react 17 project because of conflicting react types

### ISSUE THREAD

**Issue by ceisele-r** [react-bootstrap/react-bootstrap#5541]
## Describe the bug
Currently, several `@types` packages are listed as dependency in `package.json`.

This causes a lot of the following "duplicate identifier" typescript compile errors in our case as our project is using `react` 17 and we have `@types/react:17.0.0` installed in our project:
```
Error: node_modules/@types/react/index.d.ts(2981,14): error TS2300: Duplicate identifier 'LibraryManagedAttributes'.
Error: node_modules/react-bootstrap/node_modules/@types/react/index.d.ts(2982,14): error TS2300: Duplicate identifier 'LibraryManagedAttributes'.
Error: node_modules/react-bootstrap/node_modules/@types/react/index.d.ts(2995,13): error TS2717: Subsequent property declarations must have the same type.  Property 'a' must be of type 'DetailedHTMLProps<AnchorHTMLAttributes<HTMLAnchorElement>, HTMLAnchorElement>', but here has type 'DetailedHTMLProps<AnchorHTMLAttributes<HTMLAnchorElement>, HTMLAnchorElement>'.
Error: node_modules/react-bootstrap/node_modules/@types/react/index.d.ts(2996,13): error TS2717: Subsequent property declarations must have the same type.  Property 'abbr' must be of type 'DetailedHTMLProps<HTMLAttributes<HTMLElement>, HTMLElement>', but here has type 'DetailedHTMLProps<HTMLAttributes<HTMLElement>, HTMLElement>'.
Error: node_modules/react-bootstrap/node_modules/@types/react/index.d.ts(2997,13): error TS2717: Subsequent property declarations must have the same type.  Property 'address' must be of type 'DetailedHTMLProps<HTMLAttributes<HTMLElement>, HTMLElement>', but here has type 'DetailedHTMLProps<HTMLAttributes<HTMLElement>, HTMLElement>'.
Error: node_modules/react-bootstrap/node_modules/@types/react/index.d.ts(2998,13): error TS2717: Subsequent property declarations must have the same type.  Property 'area' must be of type 'DetailedHTMLProps<AreaHTMLAttributes<HTMLAreaElement>, HTMLAreaElement>', but here has type 'DetailedHTMLProps<AreaHTMLAttributes<HTMLAreaElement>, HTMLAreaElement>'.
```

The reason seems to be that the `@types` packages are dependencies in `react-bootstrap` and not "only" devDependencies and therefore the `@types/react:16.9.35` gets installed "by" `react-bootstrap` (in `node_modules/react-bootstrap/node_modules/@types/react`).
Since the typescript compile picks up these types then on top of the locally installed v17.0.0 types (installed in `node_modules/@types/react`), type definitions collide.

## To Reproduce

1. Create a Typescript project with `react` ^17.0.0 and `@types/react` ^17.0.0
2. `npm i react-bootstrap`
3. Typescript compile

## Reproducible Example

Not possible in Code Sandbox.

## Expected behavior

I would expect @types/react to only be a devDependency in `react-bootstrap` because of the following reasons:
Having it as devDependency would mean that `npm i react-bootstrap` in consuming projects would not install `@types/react` because of `react-boostrap`. **This is good because**:
1. Any typescript react project should be able to choose it's own version of `@types/react` by installing `@types/react` in the corresponding version according to the installed react version used in the project without suddenly getting type conflicts because `react-bootstrap` pulls in another version of `@types/react` that conflicts.
2. Vanilla Javascript react projects do not need typedefs at all, hence keeping `@types/react` as dependency in `react-boostrap` just clutters the dependency tree for those projects
(Additionally, `react` itself is only a devDependency (& peer-Dependency) and therefore does not get installed with `react-bootstrap` - so why should the respective types should be a dependency and not a devDependency?)

## Screenshots

N/A

## Environment (please complete the following information)

- Operating System: all
- Browser, Version: Not relevant
- React-Bootstrap Version: 1.4.0

## Additional context

This probably applies to other `@types/` packages installed as dependencies in `react-bootstrap` as well but I am not sure about them. We hit the issue currently only with `@types/react` but my feeling is that most of the other @types also should move to devDependencies.

**Comment by ceisele-r** [comment]
I saw this change was made here https://github.com/react-bootstrap/react-bootstrap/commit/8e30fb88be504928e9f2bf19eaa0d92ec71d1b9e but as written above, I don't think this is quite right as it creates the above mentioned issues that introduce hard dependency constraints on consuming projects.

**Comment by jeremyis** [comment]
I am still seeing this issue. Using React 17 with a fresh install of `react-bootstrap`. 

```

ERROR in [at-loader] ./react/node_modules/@types/react/index.d.ts:2981:14
    TS2300: Duplicate identifier 'LibraryManagedAttributes'.

ERROR in [at-loader] ./react/node_modules/react-bootstrap/node_modules/@types/react/index.d.ts:2982:14
    TS2300: Duplicate identifier 'LibraryManagedAttributes'.

ERROR in [at-loader] ./react/node_modules/react-bootstrap/node_modules/@types/react/index.d.ts:2995:13
    TS2717: Subsequent property declarations must have the same type.  Property 'a' must be of type 'DetailedHTMLProps<AnchorHTMLAttributes<HTMLAnchorElement>, HTMLAnchorElement>', but here has type 'DetailedHTMLProps<AnchorHTMLAttributes<HTMLAnchorElement>, HTMLAnchorElement>'.

ERROR in [at-loader] ./react/node_modules/react-bootstrap/node_modules/@types/react/index.d.ts:2996:13
    TS2717: Subsequent property declarations must have the same type.  Property 'abbr' must be of type 'DetailedHTMLProps<HTMLAttributes<HTMLElement>, HTMLElement>', but here has type 'DetailedHTMLProps<HTMLAttributes<HTMLElement>, HTMLElement>'.
```

**Comment by ceisele-r** [comment]
Also relates to https://github.com/jquense/uncontrollable/issues/49 ad uncontrollable is a dependency of react-bootstrap and locks to `@types/react ^16`
