### ISSUE TITLE
Dropdown Component : Multi Column & Hover option

### ISSUE THREAD

**Issue by Vikraantnegi** [react-bootstrap/react-bootstrap#5546]
I think there should be this feature with Dropdown component, by which we can choose to have multiple columns in dropdown, and have a hover option on dropdown that will help it to open whenever we hover on the button.

I currently need to have two-column dropdown, also I want to have onHover function on the dropdown button so that the show class gets added.

**Comment by marianayap** [comment]
Hello! @Vikraantnegi  Is this issue taken?

**Comment by Vikraantnegi** [comment]
Yep the creator said he made changes.

**Comment by Vikraantnegi** [comment]
I dont think so.

**Comment by marianayap** [comment]
@Vikraantnegi  I'll like to know more about the issue and just to confirm is it in JS with React?

**Comment by Vikraantnegi** [comment]
Yeah its a react library for bootstrap. The Dropdown component doesn't have the appropriate attributes

**Comment by marianayap** [comment]
@Vikraantnegi Great! I'll start working on it

**Comment by jquense** [comment]
@marianayap this isn't something we would add to the library, as it's not part of normal bootstrap.

That said the default drop-down menu is flexible and you can both implement on hover behavior and multiple columns with css outside of the library. This should be handled by users in their apps if needed

**Comment by jquense** [comment]
If you want to contribute to the project we are always happy to have contributions, usually worth starting with big fixes from the issue tracker!

**Comment by kyletsang** [comment]
You should be able to open on hover by manually controlling the `show` prop.  You will also need to handle `onToggle` for cases like clicking outside the dropdown.  As for the multiple columns in the dropdown, use `Row` and `Col` within your dropdown menu.
