### ISSUE TITLE
setCustomValidity() on input

### ISSUE THREAD

**Issue by binarykitchen** [react-bootstrap/react-bootstrap#555]
Would be great if we can set the validity (error message) on the DOM input field instead of calling `setCustomValidity()` on it.

**Comment by binarykitchen** [comment]
How about a new prop of type string for `customValidity`?

**Comment by mtscout6** [comment]
I don't see `setCustomValidity` anywhere in this repo, what exactly are you referring to?

**Comment by binarykitchen** [comment]
you don't know? it's a native JS function you can call in every HTMLInputElement, see https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/HTML5/Constraint_validation

**Comment by mtscout6** [comment]
No I didn't know which is why I asked, thanks for the clarification.

This is not how [Bootstrap](http://getbootstrap.com/css/#forms-control-validation) prescribes validation on components.

**Comment by binarykitchen** [comment]
yeah, i know the bootstrap validation but do not like it because it's not very HTML5 conform ...

**Comment by mtscout6** [comment]
Take it up with Bootstrap then, if you can figure it out with them then it will eventually trickle down here.

**Comment by binarykitchen** [comment]
thanks but i won't because i am pretty sure they will say no ;)

**Comment by mwiley322** [comment]
^ Wow what a wonderful passive-aggressive conversation that was
