### ISSUE TITLE
NavDropdown should support 'as' prop

### ISSUE THREAD

**Issue by mperkh** [react-bootstrap/react-bootstrap#5552]
It would be nice, if NavDropdown supported the 'as' prop, to use it like:

`<NavDropdown title="Dropdown" id="basic-nav-dropdown" as='li'>`

Currently it always results in a `<div>` without an escape hatch. This makes it impossible to create an menu using an unordered list and recreate the menu show here: https://getbootstrap.com/docs/4.5/components/navbar/#supported-content

**Comment by Garz4** [comment]
I would like to work on this issue!
