### ISSUE TITLE
Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

### ISSUE THREAD

**Issue by VladislavYakonyuk** [react-bootstrap/react-bootstrap#5555]
After updating react-bootstrap to 1.4.0 the following error got out

MyComponent.js
```js
class MyComponent extends React.PureComponent {
    render() {
        const { innerRef } = this.props;
        return (
            <Form.Control ref={innerRef} />
        );
    }
}

export dafult React.forwardRef((props: PropsT, ref: any) => {
    <MyComponent innerRef={ref} {...props} />
}
```

Child.js
```js
Class Child extends React.PureComponent {
    inputRef = React.createRef(null);
    
    render() {
        <MyComponent ref={this.inputRef} />
    }
}
```

**Comment by kyletsang** [comment]
Can you post a repro using [CodeSandbox](https://codesandbox.io/s/github/react-bootstrap/code-sandbox-examples/tree/master/basic-ts)?

**Comment by VladislavYakonyuk** [comment]
> Can you post a repro using [CodeSandbox](https://codesandbox.io/s/github/react-bootstrap/code-sandbox-examples/tree/master/basic-ts)?

https://codesandbox.io/s/react-bootstrap-popover-dismiss-forked-e0yok?fontsize=14&hidenavigation=1&theme=dark

**Comment by VladislavYakonyuk** [comment]
This happened after updating react-bootstrap to version 1.4.0

**Comment by kyletsang** [comment]
OverlayTrigger doesn't take refs.  If you're looking to manually toggle the overlay, you need to use the `show` and `onToggle` props.  See docs here for info on props: https://react-bootstrap.github.io/components/overlays/#overlay-trigger-props

**Comment by VladislavYakonyuk** [comment]
> OverlayTrigger doesn't take refs. If you're looking to manually toggle the overlay, you need to use the `show` and `onToggle` props. See docs here for info on props: https://react-bootstrap.github.io/components/overlays/#overlay-trigger-props

Thank you!
