### ISSUE TITLE
when tab transition is set to false then onenter, onentered, onentering is not working

### ISSUE THREAD

**Issue by iamsajithsasi** [react-bootstrap/react-bootstrap#5558]
when tab transition is set to false then onenter, onentered, onentering is not working. Tried all three but nothing worked

[      <Tabs
        id="TabContainer"
        transition={false}
        activeKey={key}
        onSelect={(k) => setKey(k)}
      >
        <Tab eventKey="FAQ's" title="FAQ's" onEntered={() => getData("faq")}>
          <TabBody />
        </Tab>
        <Tab eventKey="Blogs" title="Blogs" onEnter={() => getData("blogs")}>
          <TabBody />
        </Tab>
        <Tab
          eventKey="Quotes & Tips"
          title="Quotes & Tips"
          onEntering={() => getData("quotes")}
        >
          <TabBody />
        </Tab>
      </Tabs>](url)

**Comment by kyletsang** [comment]
The callbacks are only triggered when there's an animation.

See https://react-bootstrap.github.io/components/tabs/#tab-pane-props
> Transition onEnter callback when animation is not false

**Comment by iamsajithsasi** [comment]
> The callbacks are only triggered when there's an animation.
> 
> See https://react-bootstrap.github.io/components/tabs/#tab-pane-props
> 
> > Transition onEnter callback when animation is not false

Thanks @kyletsang
