### ISSUE TITLE
getInputDOMNode() returns null for nested inputs

### ISSUE THREAD

**Issue by binarykitchen** [react-bootstrap/react-bootstrap#556]
Should not return null when an input has been rendered. Weird.

**Comment by binarykitchen** [comment]
It happens when I have Inputs nested.

**Comment by dozoisch** [comment]
please provide the snipet to reproduce!

**Comment by binarykitchen** [comment]
```cjsx
      <Row>
        <Input
          hasFeedback
          required
          ref      = 'password'
          label    = {t("Password")}
          value    = {@state.password}
          validity = {@state.passwordValidity}
        >
          <InputPassword
            required
            value        = {@state.password}
            zxcvbn       = {zxcvbn}
            className    = {@props.className}
            onChange     = {@_handlePasswordChange}
            changeCb     = {@_handleStrengthChange}
            strengthLang = {@props.strengthLang}
          />
        </Input>
      </Row>
```

whereas `InputPassword` is taken from `require('react-ux-password-field')`

Doing a `@refs.password.getInputDOMNode()` here returns null

**Comment by dozoisch** [comment]
Seems like

https://github.com/react-bootstrap/react-bootstrap/blob/master/src/Input.js#L88-L90 is the culprit. maybe it would be possible to set the ref on the children

**Comment by AlexKVal** [comment]
It is an official API for now.
> Use as a wrapper
If type is not set, child element(s) will be rendered instead of an input element.getValue() will not work when used this way.

from here http://react-bootstrap.github.io/components.html#input-wrapper

**Comment by AlexKVal** [comment]
Untill #342
a) workarounds that we can add into docs
b) or a PR with enhancement 
are welcomed :wink:

**Comment by dozoisch** [comment]
I guess that makes sens, you can just set the ref yourself on the child component

**Comment by binarykitchen** [comment]
huh? cannot follow you guys. what's the solution now?

**Comment by mtscout6** [comment]
See: http://react-bootstrap.github.io/components.html#input-wrapper

**Comment by mtscout6** [comment]
Put your ref on `InputPassword` not the root input wrapper.

**Comment by binarykitchen** [comment]
ah, thx
