### ISSUE TITLE
Bootstrap 3 React 17 dropdown won't open

### ISSUE THREAD

**Issue by kyletsang** [react-bootstrap/react-bootstrap#5561]
Creating an issue for people to watch so we don't bug the Bootstrap 4 users with notifications.

v4 fixed issue: #5409

Fix for BS3-compatible react-overlays: https://github.com/react-bootstrap/react-overlays/pull/889

I'll close this when react-overlays gets a release.

@jquense, anything I can do to help you with the release?

**Comment by mdarcemont** [comment]
Thank you for opening this! We'd truly appreciate a new release soon.

**Comment by jquense** [comment]
released as 0.9.3!

@kyletsang should probably put together a plan and warning to users on the v3 docs about when we will stop supporting it. My suggestion is after v5 releases we drop v3 support, It's too much work to juggle 3 different major versions and at some point the upgrade costs for the react bumps are going to be too high as well.

**Comment by mdarcemont** [comment]
Thank you @jquense!

**Comment by kyletsang** [comment]
Thanks for doing this @jquense.  

> My suggestion is after v5 releases we drop v3 support

v5 should be out fairly soon, so this is a good point in time to drop v3 - this RO release will be the last update.  I'll look at adding this to docs somewhere.

**Comment by pastak** [comment]
Thanks for @jquense and reporters 👍

**Comment by smikitky** [comment]
@kyletsang This "last" fix for the 0.x branch (BS3) has not been released yet, right? This is still blocking me from upgrading my project to React 17.

**Comment by kyletsang** [comment]
> 
> 
> @kyletsang This "last" fix for the 0.x branch (BS3) has not been released yet, right? This is still blocking me from upgrading my project to React 17.

It's been released under `react-overlays` v0.9.3 which `react-bootstrap` depends on.  If you update that, you should be good to go.

**Comment by onurarpapay** [comment]
My project has react-bootstrap 1.2.2, but no react-overlays in its packages.json. I tried to install latest react-overlays, but this action didn't solve the problem. Still, after opening and closing a Modal, all my dropdowns stop working.

**Comment by codingstill** [comment]
@onurarpapay  this fix is for 0.x versions of react-bootstrap (Bootstrap 3).
