### ISSUE TITLE
Form.Control multiple select: Deselecting last option?

### ISSUE THREAD

**Issue by JeffStodd** [react-bootstrap/react-bootstrap#5562]
Is it possible to deselect the last selected option?

onChange doesn't fire if you are clicking on the last selected option to try to deselect it. onClick works for this purpose but is incompatible with mobile browsers, at least with my iPhone.

Code is something like this:

`<Form.Control as="select" multiple value={values.symptoms} onChange={this.multiSelectEvent("symptoms")}>
...
`

**Comment by kyletsang** [comment]
I made a sandbox here:
https://codesandbox.io/s/kind-easley-mqcqr?file=/src/App.js

`onChange` works here on both desktop and iPhone on 14.2.

**Comment by JeffStodd** [comment]
> I made a sandbox here:
> https://codesandbox.io/s/kind-easley-mqcqr?file=/src/App.js
> 
> `onChange` works here on both desktop and iPhone on 14.2.

I don't remember the code I had, scrapped it a couple days ago and replaced the multiselect with like 15 checkboxes. Here's my attempted recreation, onChange can't deselect the final item and is really buggy on mobile, onClick is completely bugged on both but I remember having it work on only desktop before I scrapped it.
https://codesandbox.io/s/goofy-black-djq2w?file=/src/App.js:0-2224

Note: I am avoiding shift clicking to be user friendly, especially to "tech illiterate" individuals

**Comment by kyletsang** [comment]
Your sandbox code is mutating the array in the state directly.  Make a copy of the array and use `setState` to update your state instead.

**Comment by JeffStodd** [comment]
> Your sandbox code is mutating the array in the state directly. Make a copy of the array and use `setState` to update your state instead.

Yea that fixes desktop onClick but neither are working for mobile.
https://codesandbox.io/s/goofy-black-djq2w?file=/src/App.js

**Comment by kyletsang** [comment]
Yeah, the normal flow is to use keyboard + mouse controls on desktop and `onChange` would support both desktop/mobile.  You'll probably have to use a combination of both `onChange`, `onClick` (or another handler?) to achieve what you're looking for.  Hard to say without really diving into it.

That aside, this is considered out of scope here, since it isn't a react-bootstrap issue.  StackOverflow might be a better place to get support?
