### ISSUE TITLE
Tab panel disappears when switching tabs quickly

### ISSUE THREAD

**Issue by felixgirault** [react-bootstrap/react-bootstrap#557]
Hello,

I implemented an accessibility layer over TabbedArea, thus adding a way to navigate between tabs with the keyboard.
It works fine, but when I'm switching quickly between tabs, the panels ends up disappearing, probably because of the animation and the associated timers.
It also happens on the regular TabbedArea, when using the mouse to switch tabs, although it is more difficult to reproduce.

You can try it out on your demo page http://react-bootstrap.github.io/components.html#tabs.
It happens on the "uncontrolled" demo, but not on the one with no animations.

**Comment by mtscout6** [comment]
We'd love to have a PR to make those components accessible! I'm having a hard time reproducing this myself, perhaps because I'm not clicking fast enough.

**Comment by dozoisch** [comment]
I've been able to repro, it is indeed really weird! After some clicking, both tab panes get an active of "false" and switching does not make one active anymore.

**Comment by dozoisch** [comment]
It seems like it's caused by the fact that "this.props.animation" stays true on the tabbed area after clicking too fast.

**Comment by felixgirault** [comment]
I'm glad to see that you care about accessibility :)
I'm sorry I don't have time to dig in the code right now, but I'll contribute if I have some time.

**Comment by mtscout6** [comment]
No worries, I've been meaning to put together a 1.0 roadmap documentation which includes Accessibility as a requirement for a 1.0 release. This is the first time I've publicly said that, so I guess I'm on the hook now to draft the 1.0 release documentation :smile:

**Comment by dozoisch** [comment]
**1.0 hype !** :+1:

**Comment by mathieumg** [comment]
> I'm on the hook now to draft the 1.0 release documentation

You are! :smile:

**Comment by mtscout6** [comment]
1.0.0 roadmap is up see #561

**Comment by taion** [comment]
Moved to https://github.com/react-bootstrap/react-bootstrap/issues/1418.

**Comment by haradakunihiko** [comment]
Will this bug be fixed with react-bootstrap@0.2x ? Or should I wait for ver 1.0?

**Comment by taion** [comment]
The tab API revamp fixed it, so next release.

**Comment by mathieumg** [comment]
I imagine next release will be 0.29, just to clarify.

**Comment by haradakunihiko** [comment]
@taion @mathieumg Thanks so much!!
