### ISSUE TITLE
UNSAFE life cycle method has warning at StrictMode

### ISSUE THREAD

**Issue by KhoaVo94** [react-bootstrap/react-bootstrap#5571]
Hi guy,

I am using React Bootstrap v0.33.1 (Bootstrap 3) and when I using Modal and Overlay component, I have these warning in StrictMode (Wrap the app in <React.StrictMode> and start it in development mode):

For Modal warning:
![ASkKp](https://user-images.githubusercontent.com/16128469/102567449-202e7900-4114-11eb-881a-1e8e10a5bcd9.png)

For Overlay warning:
![btNLB](https://user-images.githubusercontent.com/16128469/102567722-b1055480-4114-11eb-9ce8-00c3bbc482f5.png)

I know the issue using lifecycle method without "UNSAFE_" was fixed at v0.33.0 but now I have this new warning.
How I can fix this or any plan to fix this issue on future?

**Comment by kyletsang** [comment]
Unfortunately Bootstrap 3 isn't supported anymore, so there won't be any fixes to this.

**Comment by KhoaVo94** [comment]
> Unfortunately Bootstrap 3 isn't supported anymore, so there won't be any fixes to this.
Thanks for reply, Is that true from react-bootstrap v1.0.0, these components are refactored to functional component so these kind of warning won't happen anymore?

**Comment by jquense** [comment]
That's correct, the current versions for bootstrap v4 don't have the warnings

**Comment by kyletsang** [comment]
Closing since bs3 isn't supported anymore
