### ISSUE TITLE
Confused about the best layout component to use within page body?

### ISSUE THREAD

**Issue by sdzhangtao** [react-bootstrap/react-bootstrap#5572]
## Describe the bug
I feel react bootstrap is rather limited in the page layout area. There seems to be only one Container component that does this, while many other framework has many kinds of page layout components. For example, Chakra UI has Container, Flex, Box, Stack etc etc.

I created a page layout using containers shared by all pages. One container for header, one container for footer, and one container for the page body. However, I am not sure what's the best layout component for layout within the page body. In Chakra UI , there is a Stack component that you could vertically or horizontally stack UI components. With this layout component, I can vertically stack some headlines, paragraphs, form and button groups. Should I use Row and Col component? React Bootstrap doesn't talk much about nested containers, nested Rows etc.

I read through lots of React bootstrap sample and tutorials, however, they are mostly trivival applications.
I would appreciate it very much if anybody can share a decent application that was built using React Bootstrap.
Or if you could share some idea about this shared page layout. A global page layout shared by all pages, just like the page template in old muti-page applications.

Thanks and much appreciate any help.

Tao
## Reproducible Example

Minimal example by using [CodeSandbox](https://codesandbox.io/s/github/react-bootstrap/code-sandbox-examples/tree/master/basic).

## Environment (please complete the following information)

- Operating System: [e.g. macOS]
- Browser, Version [e.g. Chrome 74]
- React-Bootstrap Version [e.g. 1.0.0-beta.8]

**Comment by kyletsang** [comment]
I would suggest taking a look at the layout docs in the Bootstrap docs, specifically [grid](https://getbootstrap.com/docs/4.5/layout/grid/) and [flex utilities](https://getbootstrap.com/docs/4.5/utilities/flex/).  Bootstrap uses flex in their layout and exposes a bunch of convenience utility classes you can use for alignment.  Chakra UI probably abstracts a lot of this away in the above components you mentioned.

As for examples you can take a look at the [themes page](https://themes.getbootstrap.com/) for examples of layouts.  Or do a search for sites built with Bootstrap 4.

**Comment by sdzhangtao** [comment]
Thank you so much for your reply. That's very very helpful, especially with the themes. I think it's very much worth it for the money, could be a jump start for a project.
If you don't mind, can I ask another question?
If my web app is like a wizard of page flow most of the time, I feel it's more like a multi page app. Would use ReactJS the best choice and waste of effort? I do see some template offer two choices, html version and ReactJS version. I feel use ReactJS mostly for building single page app.
Thanks
Tao

**Comment by kyletsang** [comment]
I should also add, if you're comfortable creating themes for bootstrap, take a look at [this page](https://getbootstrap.com/docs/4.5/getting-started/theming/) too.

You can create multiple pages in react by using something like `react-router`.  I find that react is pretty straight-forward to use so it's a good bet for creating your site.

**Comment by sdzhangtao** [comment]
Thanks kyletsang.
That's all I need to know. Thanks for the instructions.

**Comment by kyletsang** [comment]
Cool, I'm going to close this issue now.
