### ISSUE TITLE
Adding margins to a Popover

### ISSUE THREAD

**Issue by ajaypillay** [react-bootstrap/react-bootstrap#5578]
Hi, when I try to add margins to a Popover via CSS, this warning is thrown in the console:
`Popper: CSS "margin" styles cannot be used to apply padding between the popper and its reference element or boundary. To replicate margin, use the `offset` modifier, as well as the `padding` option in the `preventOverflow` and `flip` modifiers.`

I can't seem to figure out exactly how to pass in the ["offset"](https://popper.js.org/docs/v2/modifiers/offset/) prop to a Popover. I understand the Popover has a "popper" prop but I'm not entirely sure how to use that to add in the offset. Thanks!

**Comment by jquense** [comment]
you can pass a popperConfig to the Overlay, or OverlayTrigger, not the Popover component (that is just presentational)
