### ISSUE TITLE
Adding block to Button doesn't change anything

### ISSUE THREAD

**Issue by dnorrstrand** [react-bootstrap/react-bootstrap#5579]
I am making a react component which has two **Button** elements wrapped in **Card** and **Card.Body** with the _block_ attribute added to the end of the **Button** element's tag. This is supposed to make the **Buttons** render as block (fill the entire container width). But both buttons render as inline buttons.

```
import '../css/Authentication.css';
import '../css/Buttons.css';
import React from "react";
import Form from 'react-bootstrap/Form';
import Button from 'react-bootstrap/Button';
import Col from 'react-bootstrap/Col';
import Row from 'react-bootstrap/Row';
import Card from 'react-bootstrap/Card';
import Container from 'react-bootstrap/Container';

function Login() {

    return (
        <Container>
            <h4>Авторизация</h4>
            <Row>
                <Col sm={8}>
                    <Card>
                        <Card.Body>
                            <Form>
                                <Form.Group controlId="formBasicEmail">

                                    <Form.Label>Имя пользователя</Form.Label>
                                    <Form.Control type="email" placeholder="" />
                                </Form.Group>

                                <Form.Group controlId="formBasicPassword">
                                    <Form.Label>Пароль</Form.Label>
                                    <Form.Control type="password" placeholder="Пароль" />
                                </Form.Group>
                                <Button className="my-3" variant="primary" type="submit">Авторизоваться</Button>
                                <Button className="my-3 mx-3" variant="secondary" type="cancel">Отмена</Button>
                            </Form>
                        </Card.Body>
                    </Card>
                </Col>

                <Col sm={4}>
                    <Card>
                        <Card.Body>

                            <Button className="my-3" variant="primary" type="submit" block>G</Button>
                            <Button className="my-3 mx-3" variant="secondary" type="cancel" block>F</Button>

                        </Card.Body>
                    </Card>


                </Col>


            </Row>


        </Container>


    )

};

export default Login;
```
Here is what the buttons render like:

![image](https://user-images.githubusercontent.com/73636189/102941245-e4503680-44ba-11eb-9b7a-5d5a80c82d1e.png)

Is there something I have written wrongly or is it a react bug? Thanks for any assistance.

- Operating System: [W10]
- Browser, Version [Edge Version 87.0.664.66 (Official build) (64-bit)]
- React-Bootstrap Version [1.4.0]

**Comment by kyletsang** [comment]
This is very likely an issue with your css.  Can you inspect the element styles and see if anything is overriding the `.btn-block` class?

**Comment by dnorrstrand** [comment]
Here is what I found:
![image](https://user-images.githubusercontent.com/73636189/102983345-9a943a00-4514-11eb-94ce-910aa4db8edd.png)
nothings seems to be overriding it... I do not have any element styles applied to it, so I was thinking it could be a container inheritance issue but the container doesn't seem to have anything to do with it:
 <Col sm={4}>
Where can I look further?

**Comment by kyletsang** [comment]
Can you post a repro on CodeSandbox?

**Comment by kyletsang** [comment]
Closed due to inactivity

**Comment by donwilson** [comment]
I just came across this same issue. The `block` Button attribute is no longer in react-bootstrap@2.* and since I'm using Bootstrap v4, I needed to downgrade the react-bootstrap library to react-bootstrap@1.6.*.

It might make sense to update the "Installation" notes on older branches (eg https://react-bootstrap-v4.netlify.app/getting-started/introduction/) to reference a related version of react-bootstrap instead of the latest version (as is already the case with the specified bootstrap version).
