### ISSUE TITLE
Broken link ''position utilities'

### ISSUE THREAD

**Issue by Artem3** [react-bootstrap/react-bootstrap#5587]
## Describe the bug

Broken link in the 'Placement' paragraf of the documentation
## To Reproduce

1. Go to 'https://react-bootstrap.github.io/components/navbar/#navbars-placement'
2. Click on 'position utilities' link
3. See 404 error page

## Expected behavior

remove link or make it valid
## Screenshots

![изображение](https://user-images.githubusercontent.com/12259400/103246146-25d55b80-496b-11eb-9ab8-e08842476c82.png)

**Comment by kyletsang** [comment]
Dupe of #5515.  This is fixed in the docs but not yet deployed.

The correct link should be:  https://getbootstrap.com/docs/4.5/utilities/position/
