### ISSUE TITLE
MAINTAINING.md publishers link point to 404

### ISSUE THREAD

**Issue by AlexKVal** [react-bootstrap/react-bootstrap#559]
Fix the [publishers](https://github.com/orgs/react-bootstrap/teams/publishers) link.
Now it points to => github.com/orgs/react-bootstrap/teams/publishers.
Or create team => publishers.
:wink:

**Comment by mtscout6** [comment]
The team exists: https://github.com/orgs/react-bootstrap/teams/publishers

**Comment by mtscout6** [comment]
Do you have to be a member of it to see it?

**Comment by dozoisch** [comment]
I can't see it

**Comment by mathieumg** [comment]
> Do you have to be a member of it to see it?

You do. I believe the only truly public page in that regard is https://github.com/orgs/react-bootstrap/people and collaborators have to opt-in to appear in that list.
