### ISSUE TITLE
Why checkbox not checked in nav.link

### ISSUE THREAD

**Issue by bemulima** [react-bootstrap/react-bootstrap#5595]
I don't honestly know is it a bug or is it a normal. I just created without suspecting simple nav.link with checkbox and checkbox not checked. Here example [link](https://codesandbox.io/s/objective-gould-h757o?file=/src/App.js)
`export default function App() {
  return (
    <Nav>
      <Nav.Item>
        <Nav.Link eventKey={"checkbox1"}>
          <Form.Check type="checkbox" id="checkbox1" /> {"nav link1"}
        </Nav.Link>
      </Nav.Item>
      <Nav.Item>
        <Nav.Link eventKey={"checkbox2"}>
          <Form.Check type="checkbox" id="checkbox2" /> {"nav link2"}
        </Nav.Link>
      </Nav.Item>
      <Nav.Item>
        <Nav.Link eventKey={"checkbox3"}>
          <Form.Check type="checkbox" id="checkbox3" /> {"nav link3"}
        </Nav.Link>
      </Nav.Item>
    </Nav>
  );
}`
Than I tried with useState [link](https://codesandbox.io/s/tyswy?file=/src/App.js), not working also. Is it normal or is it a bug?

Additionaly:
Although checkbox in nav link works on pure html + bootstrap 4 
[https://codesandbox.io/s/determined-chatelet-85llv?file=/index.html](https://codesandbox.io/s/determined-chatelet-85llv?file=/index.html)

**Comment by bemulima** [comment]
if set to nav link parametr "as" then works but link loses styles
`<Nav.Link
          eventKey={"checkbox1"}
          as={(props) => (
            <a {...props}>
              <Form.Check type="checkbox" id="checkbox1" /> {"nav link1"}
            </a>
          )}
        />`

[https://codesandbox.io/s/cocky-field-8jns1?file=/src/App.js:174-385](https://codesandbox.io/s/cocky-field-8jns1?file=/src/App.js:174-385)

**Comment by jquense** [comment]
You aren't getting the the same result because FormCheck doesn't just render a checkbox like you vanilla example v4 example, the apples to apples example would be using `FormCheck.Input`. That said i'm not sure i'd expect this to work anyway, inputs are invalid HTML inside an `<a>` tag.
