### ISSUE TITLE
How to detect if NavBar is currently expanded?

### ISSUE THREAD

**Issue by s2t2** [react-bootstrap/react-bootstrap#5597]
## Describe the bug

An image item in my navbar doesn't display quite as I want it to when the navbar is collapsed, so I was hoping to conditionally style it (apply some padding) in its collapsed state only.

I was able to implement a custom `useState` hook to set and toggle my own `expanded` boolean when the toggle button is clicked (see code below). HOWEVER after the nav is toggled and then the window is resized to its original size - the value doesn't toggle as it needs to in order to reflect the true visible nature of the nav. 

Without going through the trouble of a custom useState toggle (which doesn't seem to work), how can we alternatively detect the current `expanded` state of the `<NavBar>` component? Otherwise, if it is not possible to hook into the `<NavBar>` component, is there a workaround for toggling when the window is resized past the specified breakpoint?

## Reproducible Example

```js

import React, {useState} from 'react'
import {Navbar, Nav, Image} from 'react-bootstrap'

export default function TopNav() {
    const [expanded, setExpanded] = useState(false)

    function overrideToggle() {
        console.log("TOGGLE TRIGGERED...")
        setExpanded(prevExpanded => !prevExpanded)
    }

    return (
        <Navbar bg="light" // controls nav background color
            fixed="top" // keeps nav at top (not necessary when sticky top is set)
            sticky="top" // pushes page below, prevents overlap when expanded
            expand="sm" // collapse when less wide than this breakpoint
            collapseOnSelect // collapse after a nav link has been clicked
            style={{marginBottom:"15px"}}

            // OVERRIDING DEFAULT BEHAVIOR SO WE CAN DETECT CURRENT TOGGLED STATE
            expanded={expanded} // only need to add this when configuring the nav to detect its expanded state
            onToggle={overrideToggle}

        >
            <Navbar.Brand href="/" style={{fontSize:22}}>My Site</Navbar.Brand>

            <Navbar.Toggle aria-controls="basic-navbar-nav" />
            <Navbar.Collapse id="basic-navbar-nav">
                <Nav className="ml-auto">
                    <Nav.Link href="/products">Products</Nav.Link>
                    <Nav.Link href="/about">About</Nav.Link>
                </Nav>

               // this should probably go in the Nav but it causes the other links into an improper vertical alignment
                <Nav.Link href="/profile" style={ expanded ? {paddingLeft:"0px"} : {paddingLeft: "1rem"}}>
                    <Image roundedCircle
                        src="https://some.url.png"
                        alt="user profile"
                        height="35px"
                    />
                </Nav.Link>

            </Navbar.Collapse>
        </Navbar>
    )
}
```

**Comment by ShudhanshuSingh** [comment]
You can add a resize event listener using javascript, and then add a if else condition inside your function to perform the specific task if width<760 or something depending on your choice, in this way you can detect the whether navbar is expanded or not

**Comment by jquense** [comment]
Controlling the `expanded` property like you are is the correct way to do this. You're example may not be working because `onToggle` is assuming that each call should flip the state, `onToggle` is passed the next `expanded` so you can just do `onToggle={next => setExpanded(next)}`. That said you don't need to actually pass expanded back to the navbar if you only care about listening to the value, just adding a `onToggle` and using the value is passes will give you what you need
