### ISSUE TITLE
Accessibility issue for Carousel

### ISSUE THREAD

**Issue by trevlar** [react-bootstrap/react-bootstrap#5599]
When I try to change the carousel to use an unordered list I can change the element type on the main container and the children. Changing the inner container is not possible. In order to make this more accessible, we need the HTML needs to be semantic such as a properly structured unordered list.

For instance when using the following code:
```
<Carousel as="ul">
      {children.map((child) => (
           <Carousel.Item key={child.key} as="li">
                {child}
            </Carousel.Item>
       ))}
</Carousel>
```

It will generate a wrong DOM structure of 
```
<ul class="carousel slide">
    <ol class="carousel-indicators">...</ol>
    <div class="carousel-inner">
        <li class="carousel-item">...</li>
        <li class="carousel-item">...</li>
    </div>
    <a class="carousel-control-prev" role="button>...</a>
    <a class="carousel-control-next" role="button>...</a>
</ul>
```

https://github.com/react-bootstrap/react-bootstrap/blob/e7baccbea6714de94954150febcfa1eab5f7ba43/src/Carousel.tsx#L554

**Comment by kyletsang** [comment]
Is there a particular reason for using `ul` in the carousel?  This might bring along other unwanted list styles you would have to reset anyway?

**Comment by trevlar** [comment]
The idea is that the items in the carousel should be an unordered list. 

Obviously, there isn't a way to make the items a properly semantic unordered list.

**Comment by jquense** [comment]
It's not possible to make this an a `<ul>` or `<ol>` the bootstrap css requires markup that precludes using those elements due to what is allowed to be nested in lists. I'm not sure tho why this is an a11y issue, Carousels don't need to lists to be accessible.

**Comment by trevlar** [comment]
It just made sense to me from a screenreader perspective that they should be an unordered list instead of just a div tag. It's not really taking advantage of semantic HTML. It sounds like this is an issue with bootstrap and not react bootstrap.

I'll close this one out.
