### ISSUE TITLE
v1.4.1 does not correctly publish all subcomponents for import.

### ISSUE THREAD

**Issue by jonestristand** [react-bootstrap/react-bootstrap#5600]
## Describe the bug

Latest build for v.1.4.1 that was uploaded to the npm repository appears to be broken: it does not correctly include the individual imports for each component. Examining react-bootstrap directory inside node_modules shows *ONLY* dist, cjs, and esm folders. The folders for each component, and the package.json that should be inside it, are not present.

## To Reproduce

1. Install v1.4.1 specifically (e.g. "react-bootstrap": "1.4.1" in package.json)
2. Try to import a sub component: e.g. `import Container from "react-bootstrap/Container";`
3. Error on import: Cannot find module 'react-bootstrap/Container' or its corresponding type declarations.

## Expected behavior

Since this is a patch update, there should be no backwards breaking changes.

## Environment (please complete the following information)

- Operating System: macOS
- Browser, Version: Chrome 87
- React-Bootstrap Version: 1.4.1

**Comment by kyletsang** [comment]
Sorry, currently working on this now.  Hoping to get it resolved shortly!

**Comment by kyletsang** [comment]
Try with 1.4.3 on npm
