### ISSUE TITLE
turn off autoplay

### ISSUE THREAD

**Issue by MojoDaHacker** [react-bootstrap/react-bootstrap#5602]
Is there anyway to turn off the autoplay of the slides. There is no initial slide but when I change to the next slide the auto play starts. I know I can download another library for this, but is that really necessary?

**Comment by bpas247** [comment]
Have you tried just setting the `interval` prop to `null`?
> The amount of time to delay between automatically cycling an item. If null, carousel will not automatically cycle.
https://react-bootstrap.github.io/components/carousel/#carousel-props

**Comment by MojoDaHacker** [comment]
oops no I did not, thank you.

**Comment by bpas247** [comment]
I'll close this issue for now but please feel free to re-open (or open a new issue) if you have anymore relevant issues 🙂
