### ISSUE TITLE
onClick property does not exist on Pagination Prev / First / Next / Last (Typescript)

### ISSUE THREAD

**Issue by Mikescops** [react-bootstrap/react-bootstrap#5603]
## Describe the bug

It seems like the bug reported #5277 is back again.
onClick property does not exist on Pagination. Prev / First / Next / Last.

```
Type '{ onClick: () => void; }' is not assignable to type 'IntrinsicAttributes & PageItemProps'.
  Property 'onClick' does not exist on type 'IntrinsicAttributes & PageItemProps'.
```

## To Reproduce

1. Add Pagination Elements
2. Add onClick property

## Reproducible Example

Minimal example : https://codesandbox.io/s/react-typescript-forked-zn2jw?file=/src/index.tsx

## Expected behavior

Should allow onClick like on Pagination.Item.

## Environment 
- Browser FF 84.0.1

- react: 17.0.1
- react-bootstrap: 1.4.3
- react-dom: 17.0.1
- typescript: 4.1.3

**Comment by kyletsang** [comment]
You'll have to add `"allowSyntheticDefaultImports": true` in your tsconfig.
https://codesandbox.io/s/react-typescript-forked-ic874?file=/src/index.tsx

There's a bit more information at #5354.

**Comment by Mikescops** [comment]
Oh thanks a lot, it was hard to find the root cause.

Also it indeed also solves the issues I had with <Tab> and <Tab.Container>, nice catch!
