### ISSUE TITLE
Content Placeholders To Signify Loading

### ISSUE THREAD

**Issue by Gamezordd** [react-bootstrap/react-bootstrap#5607]
## Is your feature request related to a problem? Please describe

I am surprised to find this is not already a component in bootstrap but I think would be a great addition. These placeholders can be seen on multiple websites (Ex: Facebook feed, Instagram desktop feed, etc.).

## Describe the solution you'd like

A simple and extensible component that can be modified to fit various use cases by adjusting height, width, and props like "image" or "number of lines".

## Describe alternatives you've considered

A spinner is a good alternative but a content placeholder has a dynamic "feel" to it hard to match with spinners.

## Additional context

Here is a good example of what I'm talking about on [CodePen
](https://codepen.io/cssninjaStudio/pen/KBoEPz?editors=1100)

This can easily be replicated as a pure React component and functionality can be extended too.

**Comment by jquense** [comment]
This is a neat idea, however our constraints for the project are only to implement things that vanilla bootstrap provides. Since these sort of components (while useful) aren't upstream they'd be out of scope here.

**Comment by kosmiq** [comment]
Totally out of scope here. You can however implement it yourself with a library like https://github.com/dvtng/react-loading-skeleton

**Comment by kyletsang** [comment]
This will be coming to v5 bootstrap in the future.

ref: https://github.com/twbs/bootstrap/pull/31859

**Comment by Gamezordd** [comment]
I see why this is currently out of scope but really hope it does make it into Bootstrap 5. Can't wait to see new components implemented and it will be my pleasure to contribute in some way since react-bootstrap has been my go-to UI library for so long.
