### ISSUE TITLE
Bootstrap v5 release

### ISSUE THREAD

**Issue by zoltanszogyenyi** [react-bootstrap/react-bootstrap#5608]
Hello react-bootstrap team,

I love the library that you're working on. I saw that there's a bs-5 dev branch in the works. Any estimate when it might be finished? I saw it's about 60% done in terms of progress.

Thanks and keep up the great work!

**Comment by kyletsang** [comment]
Progress is going well.  There's a bunch of non-v5 related things to fix as well.  Can't really promise a date for when it's finished though, but we should be able to release a beta not too long after Bootstrap 5 goes stable.  

Any help we can get is welcome!

We can continue this conversation in #5174

**Comment by slimandslam** [comment]
I'm actually on a project right now and need to make a decision soon. Do you think you'll have React Bootstrap with V5 in 6 weeks or less?

**Comment by kyletsang** [comment]
@slimandslam, aiming to release a beta this week.

**Comment by chrys1110** [comment]
Will the migration path be easy from react bootstrap with bs4 to react bootstrap with bs5?

**Comment by kyletsang** [comment]
See https://github.com/react-bootstrap/react-bootstrap/blob/bs5-dev/www/src/pages/migrating.mdx for current list of breaking changes
