### ISSUE TITLE
`popperConfig` changes are not reflected in popper object

### ISSUE THREAD

**Issue by bitonic** [react-bootstrap/react-bootstrap#5611]
## Describe the bug

As far as I can tell, changing the `popperConfig` options on an existing `Overlay` does not cause the underlying popper object to be updated. I _think_ it's because https://github.com/react-bootstrap/react-overlays/blob/745e8a90c20a851b03323eccb18520c302dfdc7f/src/usePopper.ts#L177 is not run when the contents of `popperConfig` change.

## To Reproduce

1. Specify options using `popperConfig`
2. Dynamically update the `popperConfig` options (e.g. by getting them from some state and using `setState`)
3. Witness the tooltip not be updated after the config is.

## Reproducible Example

Minimal example by using [CodeSandbox](https://codesandbox.io/s/react-bootstrap-dynamic-offset-fw76b).

## Expected behavior

The tooltip should move left and right as the offset changes, but it doesn't. Adding ``key={`overlay-${offset}`}`` to the `Overlay` props confirms that if the `Overlay` is unomunted and mounted again the tooltip is positioned correctly. However this has the disadvantage of causing flickers since the tooltip is not updated in place.

Note that using the injected `scheduleUpdate` does not work either, because the popper object still has the old options anyway.

## Environment (please complete the following information)

- Operating System: Linux
- Browser, Version Chrome 97
- React-Bootstrap Version 1.4.3

**Comment by bitonic** [comment]
I just noticed that the comment of that code I linked ( https://github.com/react-bootstrap/react-overlays/blob/745e8a90c20a851b03323eccb18520c302dfdc7f/src/usePopper.ts#L185 ) states:

> intentionally NOT re-running on new modifiers

Presumably this is an optimization, but I think a way to explicitly save the options again on changed modifiers should be given, even if opt-in.

**Comment by kyletsang** [comment]
Going to guess this is for optimization purposes.  @jquense is this correct?

**Comment by jquense** [comment]
it's an optimization, the config being a nested object makes it hard to tell if something important has changed. if we didn't do something tho the hook would re-render in a loop if the user didn't properly memoize it

**Comment by bitonic** [comment]
Even if we do not want to do it automatically, there should be away to force the update, I think. Otherwise in this case there is no way to update it, short of destroying and recreating the tooltip.
