### ISSUE TITLE
'enforceFocus' is not trapping the tab within the modal

### ISSUE THREAD

**Issue by getsetgopi** [react-bootstrap/react-bootstrap#5612]
## Describe the bug

When the modal is open tabbing is moving the focus to browser address bar. Instead of trapping it within the modal

## To Reproduce

try creating a simple modal and check if the tabbing is trapping within the modal

## Reproducible Example

None

## Expected behavior

The tabbing should be trapped within the modal until it's closed.

## Environment (please complete the following information)

- Operating System: Windows 10
- Browser, Version Chrome 87.0.4280.141
- React-Bootstrap Version 1.4.3,
- react 16.14.0,
- bootstrap 4.5.3

**Comment by jquense** [comment]
this is intentional, and how native dialogs work https://mdn.github.io/dom-examples/htmldialogelement-basic/

**Comment by getsetgopi** [comment]
Now I get it. However, the description is very confusing here https://react-bootstrap.github.io/components/modal/

"When true The modal will prevent focus from leaving the Modal while open. Consider leaving the default value here, as it is necessary to make the Modal work well with assistive technologies, such as screen readers."

**As per accessibility compliance. When a modal is open the tabbing should be trapped within the modal until user closes it.**

**Comment by jquense** [comment]
yeah it should probably be clarified 👍  to say that the focus should be limited to the modal when focus is in the window
