### ISSUE TITLE
Horizontal Scrolling in Tabs

### ISSUE THREAD

**Issue by maifeeulasad** [react-bootstrap/react-bootstrap#5614]
## Is your feature request related to a problem? Please describe

Not a problem, it just a feature request.

## Describe the solution you'd like
```
<Tabs onOverflow={"scroll"}>
    ...
</Tabs>
```
## Describe alternatives you've considered

In a `CSS`, I've tried overriding :
```
.nav-tabs nav{
  overflow-y: auto;
}
```
And : 
```
.nav-tabs nav{
  overflow-x: auto;
}
```
In inspector tried different approaches, more is snaps.

Both comes with default scrollbar, which doesn't look good with cool *react-bootstrap*.

## Additional context

The type of tabs we want is like sublime : 

![rsz_screenshot_from_2021-01-20_14-53-10](https://user-images.githubusercontent.com/29339330/105150902-83566580-5b2f-11eb-9e17-79bcd70d0aec.png)

And a relevant snap, I guess : 

![rsz_screenshot_from_2021-01-20_14-58-37](https://user-images.githubusercontent.com/29339330/105151596-5787af80-5b30-11eb-882a-604950912caf.png)

**Comment by kyletsang** [comment]
Navs are styled using flex so you could add the utility class `flex-nowrap` to prevent it from wrapping like in your example.  

See bootstrap's flex utilities for more info:
https://getbootstrap.com/docs/4.6/utilities/flex/
