### ISSUE TITLE
Major issue in React Bootstrap .Still Facing this issue.Warning: Using UNSAFE_componentWillReceiveProps in strict mode is not recommended and may indicate bugs in your code. See https://reactjs.org/link/unsafe-component-lifecycles for details.

### ISSUE THREAD

**Issue by ayushbafna24** [react-bootstrap/react-bootstrap#5615]
## Describe the bug

index.js:1 Warning: Using UNSAFE_componentWillReceiveProps in strict mode is not recommended and may indicate bugs in your code. See https://reactjs.org/link/unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://reactjs.org/link/derived-state

Please update the following components: BootstrapTable, BootstrapTableContainer, DataProvider, PaginationDataProvider, PaginationHandler

**Comment by jquense** [comment]
Those aren't components in react-bootstrap. seems like maybe react-bootstrap-table is the project you want?
