### ISSUE TITLE
Navbar Rotation to act as Sidebar

### ISSUE THREAD

**Issue by m1nty** [react-bootstrap/react-bootstrap#5616]
## Is your feature request related to a problem? Please describe

Navbar feature is fabulous. It would be even more useful if it could seamlessly be switched into a Sidebar by specifying a few parameters. Many individuals have brought this up or have created their own so I think this feature should be standard at this point in time. 

## Describe the solution you'd like

By specifying a variant or altering some CSS, transformations could be used to flip the sidebar by 90 degrees and easily attach it to the left or right side of a web page. 

## Describe alternatives you've considered

An alternative is to create the sidebar manually, but by having the same design, layout and theme as the original Navbar it would look very nice.

**Comment by kyletsang** [comment]
This package is limited to the features implemented in upstream bootstrap.

For a vertical nav alternative, maybe [this](https://react-bootstrap.github.io/components/navs/#vertical) could work?
