### ISSUE TITLE
Is navbar brand href supported?

### ISSUE THREAD

**Issue by lukehorvat** [react-bootstrap/react-bootstrap#562]
Couldn't see it in the docs — is there some way to specify a `href` for a navbar brand? I normally use it as a link back to the "root" of the app.

Something like the following would be nice:

```
<Navbar brand="My App" href="#/">
</Navbar>
```

**Comment by mtscout6** [comment]
Yes you can do something like this:

```
render() {
  let brand = <a href='#'>My App</a>;
  return (
    <Navbar brand={brand}>
      ...
    </Navbar>
  ); 
}
```

We could use some better documentation on this.
