### ISSUE TITLE
Input type text inside <Nav.Link> component does not allow space character

### ISSUE THREAD

**Issue by tariktuzlakovic** [react-bootstrap/react-bootstrap#5623]
## Describe the bug

When `<input type="text" />` is wrapped inside `<Nav.Link>` component, the input field does not register (blocks) space character. This is caused by event bubbling. I had to add onKeyDown method that prevents event bubbling (basically, `e.stopPropagation()`). 

It's not a major bug but still causes inconvenience when handling the input field inside `<Nav.Link>` component.

Anyone encountered similar issue?

## To Reproduce

1. Wrap`<Nav.Link>` inside of `<Nav>` component
2. Add `<input type="text" />` inside of `<Nav.Link>` component
3. Try to hit space character

## Expected behavior

Input should allow space character.

**Comment by kyletsang** [comment]
Don't think text inputs inside anchors are really valid?  The nav link uses the space bar to activate the link for accessibility purposes.
