### ISSUE TITLE
What is the use of cjs, dist, esm ?

### ISSUE THREAD

**Issue by Rajesh-Thiyagarajan** [react-bootstrap/react-bootstrap#5624]
Hi Team

![image](https://user-images.githubusercontent.com/67726510/105693717-0f6ce200-5ece-11eb-94d0-4261d665a1b5.png)

1. What is the use of *.d.ts file and why this file containing in esm and cjs folder ?
2. what is the meaning of esm and cjs ?

**Comment by kyletsang** [comment]
1. These are typescript definition files
2. There are a number of resources on the web about cjs vs esm.  Easier to read that than seeing a summary here.
