### ISSUE TITLE
Tooltip Stays present on hover if cursor leaves towards the tooltip

### ISSUE THREAD

**Issue by samjarman** [react-bootstrap/react-bootstrap#5625]
## Describe the bug
As a user, I hover over an element to show a tooltip. If I then mouse away, with my cursor leaving towards the tooltip, the tooltip stays present and doesn't auto-dismiss

## To Reproduce

Steps to reproduce the behaviour:
#### Working instructions
1.Hover over the emoji
2. Push cursor right, observe auto-dismiss behaviour fail to kick in
3. (Refreshing and pushing cursor left shows correct behaviour)

## Reproducible Example

Minimal example: https://codesandbox.io/s/tooltip-bug-34fdu

## Expected behaviour
The tooltip should dismiss no matter what 

## Screenshots
NA

## Environment (please complete the following information)

- Operating System: Mac
- Browser, Version: Chrome Version 88.0.4324.96 (Official Build) (x86_64)
- React-Bootstrap Version 1.4.3

## Additional context

NA
(but let me know if you need more info)

**Comment by kyletsang** [comment]
You have your `container` set to the same element as your trigger element.  If you remove `container` or set it somewhere else, it should work as expected.

**Comment by samjarman** [comment]
I've tried to remove container being set and it does indeed now work - but I'm still curious as to why. If you have time, I'd love to hear more about why that has that effect. I thought it was required to scroll with the element, but it turns out that's not the case.

**Comment by kyletsang** [comment]
`container` controls where in the DOM, the tooltip is appended to.  Since the tooltip is rendered within the trigger element, hovering the tooltip itself would still satisfy the trigger conditions to show it.
