### ISSUE TITLE
Mistake in the Carousel template

### ISSUE THREAD

**Issue by YashPaste** [react-bootstrap/react-bootstrap#5627]
## Describe the bug

In the Carousel template, **Third slide** is written instead of Second Slide.

## To Reproduce

1. Go to 'React Bootstrap->Getting started->Components->Carousel' or [https://react-bootstrap.github.io/components/carousel/](url)
2. Click on 'Examples'
3. Scroll down to 'First example'
4. See the alt section of the Second example

## Screenshots

![first](https://user-images.githubusercontent.com/49571212/106015741-ca6ec880-60e4-11eb-8830-e03e2aa0ccb3.png)

**Comment by shanwong29** [comment]
May I work on this issue?
