### ISSUE TITLE
Implement the autohide prop for tooltip component like the one reacstrap

### ISSUE THREAD

**Issue by DamianPereira** [react-bootstrap/react-bootstrap#5629]
I currently need a link that sits inside a Tooltip that shows on hover.

I'd like to be able to specify that the tooltip should not be hidden if the user is currently hovering the tooltip.

[reactstrap](https://reactstrap.github.io/components/tooltips/) has this feature on the `autohide` prop, which defaults to true, but can be set to false to stop it from hiding if the mouse is over the tooltip.

![Screenshot from 2021-01-28 15-13-01](https://user-images.githubusercontent.com/17646954/106180663-5c291500-617b-11eb-8a37-2cecce8c4b95.png)

**Comment by kosmiq** [comment]
I'd recommend that you use something like tippyjs  for the at the moment.

**Comment by DamianPereira** [comment]
Can tippy js use bootstrap tooltip styles?

**Comment by kyletsang** [comment]
Here's the reactstrap example but rebuilt using react-bootstrap: 
https://codesandbox.io/s/keen-kirch-8sdv0?file=/src/App.js

This code controls the `show` prop in the overlay and only sets the tooltip to show when it's being hovered.  It then uses the `rootClose` prop to allow clicks outside the tooltip to close it.

You can fine tune this behavior according to your needs.  Check out the docs for the overlay props [here](https://react-bootstrap.github.io/components/overlays/#overlay-props).

**Comment by DamianPereira** [comment]
In the reactstrap version the tooltips gets hidden when mouse leaves the tooltip, but I think I can make it work with onMouseLeave. I think that's enough for my usecase, but a prop would be much easier in the future. Would you accept a PR that implemented this? Or is there no interest in adding props to OverlayTrigger? Feel free to close this if you want to keep OverlayTrigger without that prop.

**Comment by kyletsang** [comment]
I think the idea behind OverlayTrigger was it handles most general use cases for popovers and tooltips.  For more customized use cases such as above, you would have to set up everything manually.  It's a pretty verbose API, but does provide more control than the reactstrap implementation I believe.

Currently, I'd be inclined to leave the API as is right now.
