### ISSUE TITLE
Add --dry-run flag to release tooling

### ISSUE THREAD

**Issue by mtscout6** [react-bootstrap/react-bootstrap#563]
The current release tooling is currently sketchy to test, especially since it's usage is very public in nature. Adding a `--dry-run` flag that simply skips any steps that tag, push, commit, or publish. An additional thing to skip would be the final cleanup that removes temporary folders. This way you can verify that the contents of these temporary folders are as you expect.

Original conversation for this from #547

**Comment by dozoisch** [comment]
I would let the tagging happen so you can check that the tags are okay. Would be nice if it outputted to stdout all the missing 'cleanup' commands. Like

- To remove the tags do `git tag -d TAGNAME`
- clean up x,y,z temps folders once done `rm -rf foldernames`
- etc.

**Comment by mtscout6** [comment]
What if instead for the operations that we skip we send a console.log call with grey coloring. It's easy to forget to remove those tags.

**Comment by mtscout6** [comment]
I'm not too worried about the temp folders hanging around, they are already in the .gitignore, and we remove those folders before we do anything with them.

**Comment by dozoisch** [comment]
Actually, if we can sens alll the commands in grey fo the dry run that be perfect (maybe add a verbose option for that?)

**Comment by mtscout6** [comment]
I can do that as well
