### ISSUE TITLE
disabled over rides required in form validation

### ISSUE THREAD

**Issue by charlesrajesh** [react-bootstrap/react-bootstrap#5637]
## Describe the bug

I have added form validation as per the documentation. I have fields which has both disabled and required selectors(values are autopopulaed from other fields which are non required field).
When i try to validate the form, disable selector is over riding required property. Thus the validation happening is wrong in this case. can someone provide me the reason and solution to overcome it.

**Comment by kyletsang** [comment]
This is normal behavior.  See https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/disabled

> If the disabled attribute is specified on a form control, the element and its form control descendants do not participate in constraint validation.

**Comment by charlesrajesh** [comment]
sorry for the wrong understanding. Thanks a lot for the quick reply!!
