### ISSUE TITLE
Collapse skips animation when collapsing, if custom checkbox is inside, and collapse toggle does not have focus

### ISSUE THREAD

**Issue by thepuzzlemaster** [react-bootstrap/react-bootstrap#5641]
## Describe the bug
Okay, I've got a kind of weird bug here, but I built a full repro. Basically, what I've found is that when a Collapse contains `custom` `<FormCheck/>`, if you just expand/collapse it, it works as expected. If you use the keyboard to interact with the toggle or the `FormCheck` content, it also behaves as expected. If however, you expand the collapse, and then use your mouse to check/uncheck any of the `FormCheck`s inside it, and then collapse the toggle again, it skips the animation. 

It seems like it might be related to the focus somehow though. As if you shift+tab back to the toggle button, so it has focus after clicking on a checkbox, and then click using the mouse, it animates as expected. Without the `custom` prop, it also seems to work fine.

My hunch is that the style which adds the css transition is being removed before the height is set, so it skips the animation entirely? Maybe?

## To Reproduce
1. Go to https://codesandbox.io/s/elastic-dawn-5t0vh
2. Expand the Collapse by clicking on the button.
3. Check or uncheck any of the checkboxes using the mouse
4. Collapse the Collapse by clicking on the button using your mouse.
5. Note that the collapse closes instantly, rather than animating closed.

## Reproducible Example
https://codesandbox.io/s/elastic-dawn-5t0vh

## Expected behavior
I would expect the collapse to animate when collapsing/expanding no matter what kind of content is placed inside it, and no matter how you interact with that content.

## Environment (please complete the following information)
- Operating System: macOS 11.1
- Chrome Version 88.0.4324.146 (Official Build) (x86_64)
- 1.4.0

**Comment by kyletsang** [comment]
@thepuzzlemaster, can you check your codesandbox?  I'm seeing the default template from the codesandbox repo.

**Comment by thepuzzlemaster** [comment]
> @thepuzzlemaster, can you check your codesandbox? I'm seeing the default template from the codesandbox repo.

Ugh. Sorry about that. I thought it was weird that codesandbox warned me before closing the tab that I'd lose my changes.
I recreated the repro (same link), so you should be able to access it now.

Thanks for taking a look!

**Comment by kyletsang** [comment]
Looks like same issue as #5230.  The `addEndListener` within `Collapse` is picking up `transitionend` events on child nodes, so it's causing the collapse to finish animating prematurely.
