### ISSUE TITLE
Navbar is not sticking at the footer.

### ISSUE THREAD

**Issue by fredarend** [react-bootstrap/react-bootstrap#5646]
Is there a problem with the `sticky="bottom"` feature of the navbar?
There is no way to leave it as a footer here.

Here is a gist with an example:
https://gist.github.com/fredarend/5f6c30d600a37faf9e4f983da0133e31

**Comment by kyletsang** [comment]
Looks like `.sticky-bottom` is not a valid class in bootstrap.  Only `.sticky-top` is referenced upstream: https://getbootstrap.com/docs/4.6/components/navbar/#placement.

We should remove this from the code/docs
