### ISSUE TITLE
several events not firing (accordion, button onClick, etc.)

### ISSUE THREAD

**Issue by ppanero** [react-bootstrap/react-bootstrap#5647]
## Describe the bug

When building a react project with webpack, the steps marked in [bootstrap](https://getbootstrap.com/docs/4.0/getting-started/webpack/) and [react-bootstrap](https://react-bootstrap.github.io/getting-started/introduction) are not enough?

The styling displays correctly. However, no action (that requries js?) gets executed. E.g accordions do not work, button onClick never gets triggered, etc.

If the issue is identified I am willing to provide a PR (docs, code, whatever it takes). I am unsure where the exact issue is.

## To Reproduce

1. Go to [CodeSandbox](https://codesandbox.io/s/gifted-firefly-kqmfo).
2. Click on the button or the accordion, nothing happens... (Button should log to console, accordion should hide/show)

## Reproducible Example

Minimal example by using [CodeSandbox](https://codesandbox.io/s/gifted-firefly-kqmfo).

## Expected behavior

Accordions would collapse, buttons would trigger onClick.

## Environment (please complete the following information)

- Operating System: macOS Big Sur
- Browser: Safari, Chrome (latest)
- React-Bootstrap Version 1.4.3

**Comment by kyletsang** [comment]
If you remove react-bootstrap and apply onClick to a regular button element, does that work?

**Comment by ppanero** [comment]
@kyletsang it actually does not... (I edited the codesandbox, you can see it there...). So it seems somehow, something is not getting in the webpack build? However, I can see bootstrap code in the `bundle.js`.

**Comment by ppanero** [comment]
@kyletsang any tips or pointers?

**Comment by kyletsang** [comment]
Sorry for the delay here.  Unfortunately I'm not sure what's happening here.  The console log is in the bundle right?  We do know it's not a RB issue, since it also occurs with native elements.

Have you tried asking in the webpack project?

**Comment by ppanero** [comment]
Webpack issue, managed to make a working example. Sorry for the noise. Closing...
