### ISSUE TITLE
Modal animation dropped when closed in timeout

### ISSUE THREAD

**Issue by gffuma** [react-bootstrap/react-bootstrap#5648]
## Describe the bug

Hi, this is a very very strange bug, (i apologize if maybe isn't related to  `react-bootstrap` itself) if you close a modal (setting `false` the related `show` state) inside a short timeout ~50ms (i don't know if also depends of user's machine) the fade out effect is dropped.

If it can help doesn't happens on Safari.

## To Reproduce

1. Click the "Click Me" button
2. Click the "Good Bye" button

## Reproducible Example

https://codesandbox.io/s/fast-snow-8bztd

## Expected behavior

Fade out animation when closed (as usual without the timeout).

## Environment (please complete the following information)

- Operating System: Mac OS 11.2
- Browser, Version AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.146 Safari/537.36
- Browser, Version Gecko/20100101 Firefox/85.0
- React-Bootstrap Version 1.4.3

**Comment by kyletsang** [comment]
Looks like same underlying cause as #5230
