### ISSUE TITLE
Bootstrap 4.6.0?

### ISSUE THREAD

**Issue by adarnon** [react-bootstrap/react-bootstrap#5650]
Bootstrap 4.6.0 was released about a month ago. I see the update has already been merged into react-boostrap's main branch. When will the next release be deployed?

**Comment by jquense** [comment]
most bootstrap updates don't require an RB update, unless there are new JS features. You can just use the latest bootstrap CSS with any RB v1 release

**Comment by kyletsang** [comment]
1.5.0 has just been released with support for `InputGroup` `hasValidation` from bootstrap 4.6.0
