### ISSUE TITLE
A `ref` set on `Overlay`'s child never gets a value

### ISSUE THREAD

**Issue by thepuzzlemaster** [react-bootstrap/react-bootstrap#5653]
## Describe the bug
It's entirely possible I'm just doing something completely wrong here, but I can't for the life of me figure out what it could be. 
I'm creating a popover, and I'd like to get a ref to that element. But `ref.current` is always null. It works fine in a standalone `Popover` without an `OverlayTrigger`. 

## To Reproduce
1. Create any element with `ref`, that is passed into an `Overlay` as the child.
2. Try to access the ref when the child is rendered to the screen.
Repro here:
https://codesandbox.io/s/optimistic-poincare-ciwh2?file=/src/App.js
The value of `popoverRef.current` from the `Overlay` is always null.

## Expected behavior
I would expect `popoverRef.current` to have a value, once the child has been rendered to the page. I was thinking maybe it had something to do with the timing of the popover rendering, but even with the `onClick` handler, it still logs `null`

## Environment (please complete the following information)
- macOS 11.2.1 (20D74)
- Chrome Version 88.0.4324.150 (Official Build) (x86_64)
- React-Bootstrap Version 1.4.3

## Additional context
I looked through the `OverlayTrigger.tsx` code, and it doesn't look to be doing anything weird to the overlay. 
Thanks for any help here.

**Comment by thepuzzlemaster** [comment]
I took another look at this, this morning. It's the `<Overlay/>` itself, not the `<OverlayTrigger/>` which is causing the issue. Updated the codesandbox to match.

**Comment by thepuzzlemaster** [comment]
Okay, I believe I've tracked down what's happening here, but I haven't fully wrapped my head around it yet.

You can see in [this codesandbox link](https://codesandbox.io/s/elastic-wilson-rx9es?file=/src/App.js) that when you toggle the commented line which assigns the ref, it inversely toggles the component's ability to correctly render the child, and the value of the ref. 
When the ref is set, the element does not position correctly.
When the ref is not set, the element positions correctly.

So it would seem the Overlay is overwriting the ref value to enable the positioning behavior, and that is why the ref is always coming back as null in my initial case.

**Comment by kyletsang** [comment]
You're correct, the overlay is overwriting the ref you have there.  Here are the props coming from `react-overlays` `Overlay`:

https://github.com/react-bootstrap/react-overlays/blob/30b8155cdf5987234dd8e8111cedb118fd053b5a/src/Overlay.tsx#L117-L130

**Comment by thepuzzlemaster** [comment]
Thanks for the confirmation. Is there any way to change this so the ref propagates through? It looks like doing something like this works? I'm not sure how appropriate it would be to include something like that inside the library, vs just doing something like this in my own code?
https://codesandbox.io/s/elastic-wilson-rx9es?file=/src/App.js

I am assuming that's kind of what `useMergedRefs` is doing?

**Comment by kyletsang** [comment]
What you did in that sandbox is the only way to get the ref at the moment.  

It looks like we can change `Overlay` to use `forwardRef` here, but this is considered a breaking change. We can add this for the bootstrap 5 release that's currently in development.

**Comment by thepuzzlemaster** [comment]
Thanks very much for the help and insight. Although not the prettiest, this will unblock me.

Really appreciate all the help.

**Comment by kyletsang** [comment]
Fixed in v2 alpha
