### ISSUE TITLE
Dropdown menu full width of container

### ISSUE THREAD

**Issue by richdear** [react-bootstrap/react-bootstrap#5654]
## Is your feature request related to a problem? Please describe

 Dropdown have to contain many elements so its menu must occupy all available space

## Describe the solution you'd like

Responsive dropdown menu

## Describe alternatives you've considered

Custom dropdown

**Comment by kyletsang** [comment]
You can adjust the width of the dropdown menu as needed using css

**Comment by kyletsang** [comment]
Closing as question has been answered

**Comment by richdear** [comment]
I need dynamic width
