### ISSUE TITLE
popperConfig appears to have an incorrect type definition

### ISSUE THREAD

**Issue by edaqa-uncountable** [react-bootstrap/react-bootstrap#5658]
If I create an `OverlayTrigger` with a `popperConfig` like this:

```
      popperConfig={{
        modifiers: {
          preventOverflow: {
            enabled: false,
          },
        }
      }}
```

TypeScript will produce this error:

```
error TS2322: Type '{ preventOverflow: { enabled: false; }; }' is not assignable to type 'Partial<Modifier<any, any>>[]'.
  Object literal may only specify known properties, and 'preventOverflow' does not exist in type 'Partial<Modifier<any, any>>[]'.
           preventOverflow: {
             enabled: false,
           },
```

I can't figure out where this `Modifier` type is coming from, or how TypeScript has identified this type for `popperConfig`. But it appears to be wrong.

**Comment by kyletsang** [comment]
Modifiers follow the popper v2 format:
https://popper.js.org/docs/v2/modifiers/

Here's an example used in RB for the offset modifier:
https://github.com/react-bootstrap/react-bootstrap/blob/d9f139752ab05eefaf9af8745ccd493ad18d98dd/src/usePopperMarginModifiers.tsx#L51-L72

**Comment by kyletsang** [comment]
Closing as question has been answered
