### ISSUE TITLE
Accordion component doesn't work with collapsing specific rows in a table.

### ISSUE THREAD

**Issue by jeremygottfried** [react-bootstrap/react-bootstrap#5659]
## Describe the bug
Accordion component doesn't work for collapsing specific rows in a table. `Accordion.Collapse` wraps everything in a div which messes up row styles.
## To Reproduce
```jsx
<Accordion as='tbody'>
  <Accordion.Toggle as='tr' eventKey="0">
    <td>Some data</td>
    <td>Some other data</td>
  </Accordion.Toggle>
  <Accordion.Collapse eventKey="0">
    <tr>
      <td>
        Hidden data
      </td>
      <td>
        More hidden data
      </td>
    </tr>
  </Accordion.Collapse>
</Accordion>
```

The code above collapses the row, but the styling for the collapsed row is messed up because it's wrapped in a div. There should be an `as` prop for the `Accordion.Collapse` component.

## Expected behavior
Accordion component is agnostic to the element type it's wrapping.

**Comment by kyletsang** [comment]
Are you able to render a working example using regular bootstrap?  I'm unsure if the collapse works for tables.

**Comment by jeremygottfried** [comment]
It seems like the basic show/hide behavior works, but not the animation.
https://codesandbox.io/s/bootstrap-4-react-hello-world-import-forked-pxwcf?file=/src/index.js

**Comment by kyletsang** [comment]
Yeah I think this is one of the limitations with table elements.  We can't do anything here for it.

**Comment by jeremygottfried** [comment]
Gotcha. I still think an `as` prop on the Collapse component would be helpful. Even if it doesn't include table elements.

**Comment by jeremygottfried** [comment]
Yeah I can work on it this weekend

**Comment by Amanporwal510** [comment]
Hi @kyletsang , Have a look on my PR, i have added "AS" prop in AccordionCollapse Component.
https://github.com/react-bootstrap/react-bootstrap/pull/5991#issue-976682630
