### ISSUE TITLE
error husky

### ISSUE THREAD

**Issue by AnechaS** [react-bootstrap/react-bootstrap#5667]
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! @popperjs/core@2.8.1 postinstall: `husky install .config/husky`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the @popperjs/core@2.8.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/anechakuekharem/.npm/_logs/2021-02-20T19_49_40_966Z-debug.log

**Comment by blabtonic** [comment]
I also get this error when I do an install for react-bootstrap it seems that something in the popperjs core might not be compatible

**Comment by kyletsang** [comment]
This was a problem with popper core 2.8.1, but it should be fixed now in 2.8.2
