### ISSUE TITLE
ToggleButton double render and shallow click.

### ISSUE THREAD

**Issue by FernandoH-G** [react-bootstrap/react-bootstrap#5670]
## Describe the bug

A `ToggleButton` component click will render a click twice, meaning any callback functions in `onClick` will run twice, potentially messing with values assigned/changed. In order to not render a click twice, you seem to need to click its input area, if not, it will be a shallow click. The label seems to cover the actual input zone.

## To Reproduce

1. Declare a `ToggleButton` inside a `ButtonGroup`.  My bug appeared in a map of button groups.
2. Insert an `onClick` callback that `console.log("clicked")`.
3. Click the `ToggleButton`.
3. Open up console.
4. See error: double clicked printing.

## Reproducible Example
There is no styling, but if you click on the label, the last update, you will notice a double render on the console. However, if you click the small radial input, it will show some cards, which is the intended result. A shallow click will not give the intended result.

https://codesandbox.io/s/spring-butterfly-myxo1?fontsize=14&hidenavigation=1&theme=dark

## Expected behavior

I expect that a click anywhere on a `ToggleButton` will render only once.

## Screenshots

Double render in console:
https://i.stack.imgur.com/n4BSo.png

Small input covered by label:
https://i.stack.imgur.com/wNe5q.png

## Environment (please complete the following information)
 
- Operating System: Linux Manjoro KDE kernel 5.10
- Browser, Version: Firefox 84.02
- React-Bootstrap Version 1.5.0

**Comment by kyletsang** [comment]
`ToggleButton` renders a label wrapping an input under the hood.  When you attach an `onClick` to the label, clicking it will also trigger a click on the input, which then bubbles up back to your label, triggering it a second time.

I would suggest passing an `onChange` here if you want to detect changes in the underlying input.
