### ISSUE TITLE
Container breakpoints don't seem to do anything?

### ISSUE THREAD

**Issue by Jonofat** [react-bootstrap/react-bootstrap#5675]
I need a different container size to the standard but but not 100% fluid. So, I saw in the docs I could do this:

`<Container fluid="md"></Container>`

But I have tried with md, sm, lg etc. and they all look exactly the same, nothing changes.

**Comment by kyletsang** [comment]
Setting a breakpoint in `fluid` will make the container 100% width until the specified breakpoint.  If you need a custom width, you can change it via css.

**Comment by oddanderson** [comment]
I am running into this as well. I am attempting to limit the size of the container to the large breakpoint by using

`<Container fluid="lg">`

However, no matter what value I set the fluid prop to, I see no impact on my interface.
