### ISSUE TITLE
Newest CDN link from docs not working. (v4.6.0)

### ISSUE THREAD

**Issue by jaaneh** [react-bootstrap/react-bootstrap#5678]
## Describe the bug
Copy-pasting the latest CDN link from the react-bootstrap docs does not work. This is an issue with the CDN throwing `<Code>AccessDenied</Code>` XML error.

Seems like this might be an issue with Bootstrap link itself. Should probably be switched for the jsdelivr link from their v4.6 docs. [link](https://getbootstrap.com/docs/4.6/getting-started/introduction/#css)

## To Reproduce

1. Copy v4.6.0 CDN link tag from https://react-bootstrap.github.io/getting-started/introduction/#css
3. Insert to head of HTML like usual.
4. Realize everything's broken :(

## Reproducible Example

Example using your own CDN example from [here](https://github.com/react-bootstrap/code-sandbox-examples/blob/master/README.md), but with updated CDN link from docs.

[CodeSandbox](https://codesandbox.io/s/objective-kilby-00c37?file=/public/index.html)

## Expected behavior

React-bootstrap to work as expected.

## Environment (please complete the following information)

- Operating System: Windows
- Browser, Version: Chrome v88.0
- React-Bootstrap Version: v.4.6.0

**Comment by kyletsang** [comment]
Let's use jsdelivr.  Interested in sending a PR?

**Comment by jaaneh** [comment]
> Let's use jsdelivr. Interested in sending a PR?

Sure thing. Opened #5680
