### ISSUE TITLE
Implement openOnHover attribute for DropDownButton

### ISSUE THREAD

**Issue by snario** [react-bootstrap/react-bootstrap#568]
This would be a very nice option to have instead of needing to hack around it -- just being able to say

`<DropDownButton openOnHover ...>...</DropDownButton>`

**Comment by dozoisch** [comment]
I guess that makes sense to have trigger options on the button! 

We could just do something similar to the https://github.com/react-bootstrap/react-bootstrap/blob/master/src/OverlayTrigger.js#L92-L111

Maybe, even extracting a component to make it more reusable!

**Comment by mtscout6** [comment]
I like the idea, I'll consider it in #526.

**Comment by AlexKVal** [comment]
Superceded by #526

**Comment by mtscout6** [comment]
Not resolved in #526

**Comment by taion** [comment]
This feature isn't present upstream and currently goes through a different codepath. We'd consider a PR for this, but I'm going to close this issue for now.
