### ISSUE TITLE
[docs] Page for Popovers component returns 404

### ISSUE THREAD

**Issue by burtek** [react-bootstrap/react-bootstrap#5682]
Selecting Popovers from side menuy while in [components](https://react-bootstrap.github.io/components/alerts/) page, or going directly to the url https://react-bootstrap.github.io/components/popovers/ returns 404

**Comment by kyletsang** [comment]
Same as #5214

Redirect isn't working properly.  Use this link:  https://react-bootstrap.github.io/components/overlays/#popovers

**Comment by burtek** [comment]
@kyletsang thanks. Sorry, I missed that issue while looking if it has been answered earlier
