### ISSUE TITLE
CDN link on React-Bootstrap website does not load

### ISSUE THREAD

**Issue by slimandslam** [react-bootstrap/react-bootstrap#5690]
## Describe the bug

CDN link on website does not work

## To Reproduce

Go here:  https://react-bootstrap.github.io/getting-started/introduction

Add the suggested CDN link to your React index.html file:

```
<link
  rel="stylesheet"
  href="https://maxcdn.bootstrapcdn.com/bootstrap/4.6.0/css/bootstrap.min.css"
  integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l"
  crossorigin="anonymous"
/>
```

It fails to load.

**Comment by kyletsang** [comment]
I updated the site with the new link:

https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css
