### ISSUE TITLE
Change size of dropdown button.

### ISSUE THREAD

**Issue by Nishant-Pall** [react-bootstrap/react-bootstrap#5692]
I'm using Dropdown.toggle for my project and I want to resize the button but I can't find any prop for such styling, please help me out here. Here is the snippet

```
<Dropdown id="myvideo-card-menu-dropdown">
                            <Dropdown.Toggle variant="secondary" id="dropdown-basic">
                                <i className="fa fa-bars"></i>
                            </Dropdown.Toggle>
                            <Dropdown.Menu>
                                <Dropdown.Item href="#/action-1">Action</Dropdown.Item>
                                <Dropdown.Item href="#/action-2">Another action</Dropdown.Item>
                                <Dropdown.Item href="#/action-3">Something else</Dropdown.Item>
                            </Dropdown.Menu>
                        </Dropdown>
```

**Comment by kyletsang** [comment]
`Dropdown.Toggle` renders a `Button` under the hood so you can use the `size` prop.  This prop takes either `sm` or `lg`.  See https://react-bootstrap.github.io/components/buttons/#sizes

The docs could use some improvements here in the API section.

**Comment by Nishant-Pall** [comment]
Thank you for the doc, is there any way I can change it in CSS. I'm not really sure if I know how to change it in my jsx above.

**Comment by kyletsang** [comment]
To change via props:
`<Dropdown.Toggle variant="secondary" id="dropdown-basic" size="sm">`

Or `style` prop:
`<Dropdown.Toggle style={{ padding: '2rem' }} />`

Or css targeting `.dropdown-toggle` or whatever selector you want.

**Comment by Nishant-Pall** [comment]
Oh, that clears it up. Thank you for the demonstration.
