### ISSUE TITLE
propTypes stripped

### ISSUE THREAD

**Issue by ericvergnaud** [react-bootstrap/react-bootstrap#5693]
## Describe the bug

the propTypes static field of components is missing in production builds

## To Reproduce

create a project using react-bootstrap 1.0+
import a component
look at the component propTypes

## Reproducible Example

```
import { Button } from 'react-bootstrap';

console.log(typeof(Button.propTypes)); // => undefined
```

## Expected behavior

The source code for Button.tsx populates the static propTypes field:
line 141: Button.propTypes = propTypes;
I expect the propTypes static field populated in react-bootstrap source code to be present.

Not everybody uses Typescript, so for plain Javascript users, not having propTypes is a concern

## Screenshots

n/a

## Environment (please complete the following information)

- Operating System: [MacOS]
- Browser, Version [Node 14]
- React-Bootstrap Version [1.0.5]

## Additional context

My code needs to generate stuff based on propTypes.
I understand the issue could be intentional i.e. strip metadata in production builds.
Happy to contribute to a solution.

**Comment by ericvergnaud** [comment]
Hi,
I managed to workaround the issue by setting removePropTypes: false in .babelrc (in a local build)
However, this is not sufficient apparently for components generated via createWithBsPrefix
examples: Alert.Heading, Alert.Link, Card.Header, Card.Body...
Any thoughts on how to fix this?

**Comment by jquense** [comment]
so your build was removing the propTypes? the `createWithBsPrefix` components just don't have prop-types, they are generally just wrappers over an HTML element and so have all the same props as them

**Comment by ericvergnaud** [comment]
the standard build removes the propTypes (due to 
```const rmPropTypes = require('babel-plugin-transform-react-remove-prop-types');```
in @react-bootstrap/babel-preset)
I was able to avoid it by setting removePropTypes: false in .babelrc

the createWithBsPrefix components have "as" and "bsPrefix" as props, which are not standard html props
so propTypes should be there I believe
happy to fix the issue with some guidance

**Comment by jquense** [comment]
our config is probably set to remove them (accidentally) then. The other components, do accept those props but they just don't also have propTypes defined for them, so perhaps should.

**Comment by ericvergnaud** [comment]
btw, I'm not sure what the right approach should be re removing propTypes in a library
if the bundle is loaded via url in the webpage then you want propTypes removed
but if you're importing the module in your project, then you don't want them removed
not sure what is the right approach here...
