### ISSUE TITLE
Navbar.Toggle targeting does not work

### ISSUE THREAD

**Issue by VerdonTrigance** [react-bootstrap/react-bootstrap#5694]
## Describe the bug

aria-controls and data-target does nothing to target collapsing elements

## To Reproduce

1. Open it with small screen to collapse navbar
2. Click user icon
3. It opens everything, but not only "navigation-account" control
4. Same with "navigation-links"

## Reproducible Example

https://codesandbox.io/s/sharp-grass-f8eo0?file=/src/App.js

## Expected behavior

I expect independent collapsing like here:
https://www.codeply.com/go/21PmzA2ff3

## Screenshots

![image](https://user-images.githubusercontent.com/12109173/109787157-fec33080-7c1e-11eb-916b-519be3e11773.png)

## Environment (please complete the following information)

look at example

## Additional context

I didn't find any docs in official site, so I opened the issue.

**Comment by kyletsang** [comment]
Unfortunately, the current implementation only supports a single `Navbar.Collapse` because the context is stored within the parent `Navbar`.  `aria-controls` is used for accessibility and `data-target` is only used for regular bootstrap, not react-bootstrap.

Maybe this is something we can improve for the bootstrap 5 release...

**Comment by VerdonTrigance** [comment]
> Unfortunately, the current implementation only supports a single `Navbar.Collapse` because the context is stored within the parent `Navbar`. `aria-controls` is used for accessibility and `data-target` is only used for regular bootstrap, not react-bootstrap.
> 
> Maybe this is something we can improve for the bootstrap 5 release...

ooh, sad to hear that. anyway thanks for reply.
