### ISSUE TITLE
Is there a library to mask input?

### ISSUE THREAD

**Issue by smenshikov** [react-bootstrap/react-bootstrap#5704]
I use `react-hook-form` and `react-bootstrap`. Also, I want to use a library to mask the input. Actually, I have tried using to use the `react-maskedinput` package, but it does not work well, and looks like this package is dead. Maybe someone can suggest a solution?

**Comment by kyletsang** [comment]
Maybe this?
https://www.npmjs.com/package/react-input-mask

This isn't really a react-bootstrap issue though, so you might have better luck asking in reddit or reactiflux discord.
