### ISSUE TITLE
Broken TypeScript types for projects with `allowSyntheticDefaultImports: false`

### ISSUE THREAD

**Issue by burtek** [react-bootstrap/react-bootstrap#5705]
Since `react` has no default export, `import React from 'react'` is a no-op for TS projects with `allowSyntheticDefaultImports: false`. This breaks type declaration files making `React.*`, including `React.PropsWithChildren` types inaccessible:

![image](https://user-images.githubusercontent.com/2940958/110255477-42f26000-7f94-11eb-90e3-4cd9d25c153f.png)

![image](https://user-images.githubusercontent.com/2940958/110255573-bd22e480-7f94-11eb-84d9-2a6a28ea41dc.png)

`react` should be imported in `react-bootstrap` via `import * as React from 'react';` or by using named imports.

**Comment by burtek** [comment]
It works correctly with `import * as React`:

![image](https://user-images.githubusercontent.com/2940958/110255865-3c64e800-7f96-11eb-973a-81dd681c702c.png)

no error here:

![image](https://user-images.githubusercontent.com/2940958/110255872-44248c80-7f96-11eb-8a38-28b4a8e77490.png)

**Comment by kyletsang** [comment]
This will be fixed in v2 for the bootstrap 5 release

**Comment by burtek** [comment]
@kyletsang is there ETA for that release?

**Comment by kyletsang** [comment]
> @kyletsang is there ETA for that release?

Aiming to release a beta this week

**Comment by kyletsang** [comment]
Should be fixed in v2.0.0-alpha.0:
https://github.com/react-bootstrap/react-bootstrap/releases/tag/v2.0.0-alpha.0
