### ISSUE TITLE
Modal cannot appear inside form

### ISSUE THREAD

**Issue by jklingen92** [react-bootstrap/react-bootstrap#5725]
## Is your feature request related to a problem? Please describe
I'm attempting to build a react drop-in component that puts a modal confirmation dialogue into a form. My component has the following structure:

```
export default function ConfirmSubmitModal(props) {
  const [showModal, setShowModal] = useState(false)
  
  return <div>
    <button type="button" onClick={() => setShowModal(true)}>{value}</button>  // Original submit button
    <Modal show={showModal}>
      <Modal.Header></Modal.Header>
      <Modal.Body></Modal.Body>
      <Modal.Footer>
        <button onClick={() => setShowModal(false)}>Cancel</button>
        <input type="submit" name="submit" value="">{value}</button>  // New submit button in Modal
      </Modal.Footer>
    </Modal>
  </div>
}
```
This doesn't work because the compiled Modal is moved to the bottom of the HTML document and no longer exists inside of the form. I'd like to be able to use this component without having to know anything about the form in which it appears.

## Describe the solution you'd like

I'd like a prop added to React Modal that allows you to leave the compiled code where it would naturally occur in the HTML.

EDIT: I'm looking into how the element is positioned. This may be an issue for `react-overlays`.

**Comment by kyletsang** [comment]
Modal does take a `container` prop where you can specify where the modal gets appended to. 

Not sure why it's marked as private though... @jquense?

https://github.com/react-bootstrap/react-bootstrap/blob/00dffcd69cfe0350a77a3037585388298432b32a/src/Modal.tsx#L213-L216

**Comment by jquense** [comment]
`container` on Modal isn't intended to be configurable, the propType  i think is a left over from when we had a HOC that injected it (moved upstream). Bootstrap modals use position `fixed` which really requires that they be close to the top of the document, and vanilla bootstrap basically requires the body be the scrolling container for the modal.

In terms of fixes the form thing. you may want to use the HTML `form` attribute to associate elements outside the form to  your form: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#htmlattrdefform
