### ISSUE TITLE
Toast.onClose: Type omits argument

### ISSUE THREAD

**Issue by fefrei** [react-bootstrap/react-bootstrap#5726]
Using a `Toast` like this...

```tsx
<Toast onClose={((e: React.MouseEvent<HTMLElement>) => {
    e.stopPropagation();
    doSomething();
}) as () => void} onClose={doSomethingElse}>
```

works absolutely fine, i.e. clicking the “×” triggers `onClose`, but not `onClick`, while clicking somewhere else on the toast only triggers `onClick`. For this behavior, the call `e.stopPropagation()` is needed.
However, this use requires the type assertion `as () => void` in there to type correctly, as the type of `onClose` omits the argument: `ToastProps.onClose?: (() => void) | undefined`
Unless I'm doing something wrong here, it looks like the type of `onClose` should be amended.

I'm using version 1.5.2 of `react-bootstrap`.

(I've skipped the remainder of the bug template as this is not a behavioral bug.)

**Comment by kyletsang** [comment]
`onClose` should probably take an optional event param.  It gets called with an event in `ToastHeader` and without an event in `Toast`'s autoclose functionality.

Interested in sending a PR?

**Comment by fefrei** [comment]
I actually briefly looked into the code, but didn't really find my way – that's why this is an issue, not a PR 🙈
