### ISSUE TITLE
React bootstrap carousel automatically grays out a white slide

### ISSUE THREAD

**Issue by michaelhousman** [react-bootstrap/react-bootstrap#5728]
## Describe the bug

It's possible this is user error but I want to display a white slide in a React Bootstrap carousel and it's being automatically grayed out.

I think it grays out the active image because the default coloring for the previous / next buttons is white by default. But I'm changing those so I'd like the carousel to just render my images the way they appear.

## To Reproduce

Nothing needed to produce.  This is default behavior out of the box.

## Reproducible Example

See screenshots below

## Expected behavior

The images are white so I would expect the slide to look the same

## Screenshots

<img width="256" alt="screenshot" src="https://user-images.githubusercontent.com/9331492/111795335-50f18c00-8884-11eb-9815-53aaa8fdeef6.png">

![screenshot](https://user-images.githubusercontent.com/9331492/111795506-7ed6d080-8884-11eb-9178-e65eb14c754e.gif)

## Environment (please complete the following information)

- Operating System: macOS
- Browser, Version: Chrome 88
- React-Bootstrap Version: 1.2.2

## Additional context

I'm a novice with React, Bootstrap, and CSS so it's possible I just don't know how to turn that off.

**Comment by kyletsang** [comment]
Can you post a reproducible example on CodeSandbox?

**Comment by michaelhousman** [comment]
Sure!  Just give me a day to pull that together.

**Comment by michaelhousman** [comment]
@kyletsang -- I'm having problems getting CodeSandbox to render the Carousel properly but here's the code I mocked up that reproduces the issue locally:

https://codesandbox.io/s/little-violet-200ol?file=/src/App.js

Will look into whether I can create a public Github repo in order to deploy.

**Comment by michaelhousman** [comment]
Ugh.  Finally figured out how to render it and I don't see the issue with the images turning gray.  I think that means it's an issue with my local configuration.  Will try to dig in and figure out what's going on.  Sorry for the wild goose chase!

**Comment by kyletsang** [comment]
Thanks for the update.  Going to close this issue as it doesn't look like an RB issue.

**Comment by michaelhousman** [comment]
Yea, okay.  Sorry about the false alarm!
