### ISSUE TITLE
Bug in the Toast Component Section on the Docs Website

### ISSUE THREAD

**Issue by sohamsshah** [react-bootstrap/react-bootstrap#5729]
## Describe the bug

At https://react-bootstrap.github.io/components/toasts/ there is a dismissible toast section. That demonstrates two types of toast dismissals, with Animation and without Animation. In that, when toggled for *with animation* the toast disappears. But when again toggled, due to some reason the Toast Header Image disappears. 

The Video demonstrating this:

![ezgif com-gif-maker](https://user-images.githubusercontent.com/47717492/111860766-d9009000-896f-11eb-9c1b-022c905f4406.gif)

## To Reproduce

1. Go to https://react-bootstrap.github.io/components/toasts/
2. Scroll down to Dismissible Section
3. Click on `Toggle Toast with Animation` (also observe that the Placeholder Image in the Header is visible)
4. See the Toast will be disappeared
4. Again click the `Toggle Toast with Animation` button
5. See the image disappeared.

## Expected behavior

The image must not disappear. 

## Observation
Initially the Image imports the SVG well. src= SVG and data-src = "holder.js/20x20?text=%20"
But when toggled, the data-src = none and src= "holder.js/20x20?text=%20"

While it should be same as before as essentially we are just altering `show` state.

## Environment (please complete the following information)

- Operating System: Windows 10
- Browser, Version: Chrome 86

## Additional context
I am very new as a contributor to React Bootstrap. Was developing my own React component library, so while searching for inspiration from Bootstrap, found this small bug.

Quite intrigued to learn and in contributing to Bootstrap Open Source! Would love to work on this issue, please assist me upon how to get started and will try to resolve this issue ASAP!

**Comment by kyletsang** [comment]
Have a look at the [contributing docs](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

The local setup section in the [readme](https://github.com/react-bootstrap/react-bootstrap#local-setup) should get you started with running a local copy of the docs site.

Thanks!

**Comment by sohamsshah** [comment]
Thanks! Working on it!

**Comment by sohamsshah** [comment]
Hi @kyletsang I suppose this issue is because of importing the image via `src` from `holder.js`. By testing with other images, it turns out that all of those works fine with animation and dismiss events. 

I think a workaround for this will be to download the svg file for all placeholders, put it in asset and then import relatively from there. Though, then there will be issues with UX via LIVE EDITOR.

Let me know your views upon this on how to fix this.

**Comment by kyletsang** [comment]
Currently holderjs is initialized whenever the example codeblock is rendered, but not when there are any DOM changes in the example itself. The toast with animation is remounted when it is shown, but holderjs isn't run, so image doesn't appear properly.  Interestingly, the toast is only unmounted when there is an animation. 

Here's the relevant code for holderjs initialization:
https://github.com/react-bootstrap/react-bootstrap/blob/00dffcd69cfe0350a77a3037585388298432b32a/www/src/components/ReactPlayground.js#L116-L125

We could probably use a mutation observer here to watch for DOM changes?

**Comment by sohamsshah** [comment]
Thanks for taking time to help me resolve my doubt. This makes sense to me :) 
Tho I haven't gotten to use Mutation Observer in React yet, but would love to explore. Is this [Mutation Observer API](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver) you are referring to, or is there something else that is generally used in React? If you can provide some references/code examples (when you are free ofc), it can be helpful for me to resolve this issue :)

**Comment by kyletsang** [comment]
Yeah that’s the one. I haven’t used it myself yet, so can’t really give pointers, sorry.

**Comment by watinha** [comment]
Hey guys,

I verified that the Mutation Observer does fix this issue.

Can I send a PR for this?

**Comment by kyletsang** [comment]
> 
> 
> Hey guys,
> 
> I verified that the Mutation Observer does fix this issue.
> 
> Can I send a PR for this?

Feel free to send a PR.  `useMutationObserver` from `@restart/hooks` might help you here.

**Comment by watinha** [comment]
Just sent PR #5814, in regards to this issue.
