### ISSUE TITLE
Radio group documentation

### ISSUE THREAD

**Issue by davidnewcomb** [react-bootstrap/react-bootstrap#5730]
## Describe the bug

Bug is in documentation

## To Reproduce

Go to the section on radio buttons.

## Additional context

All the documentation treats checkboxes and radio buttons the same. All the examples use radio and checkbox interchangeably.

The problem is that radio buttons are not the same as checkboxes because they have radio groups, and this is not mentioned at all.

I'm currently hunting for how to create a radio group on the wider internet - but I really shouldn't have to.

**Comment by jquense** [comment]
What is the difference you are looking for? Do the examples not demonstrate how to use radio buttons in a group? I'm not sure I understand the concern here. Yes radios are different in use from checkboxes but their API is exactly the same in HTML (aside from type=radio)

**Comment by jquense** [comment]
Ahi see the examples are wrong, they are missing a `name` attribute. You can tie checkboxes and a radios together as a group by giving them the same `name`, note that this an HTML behavior not a react or react bootstrap one

**Comment by davidnewcomb** [comment]
I can see that [Horizontal form](https://react-bootstrap.netlify.app/components/forms/#horizontal-forms) now has a nice radio button example. Thanks.
