### ISSUE TITLE
Popover does not work on mobile browser

### ISSUE THREAD

**Issue by unit-002** [react-bootstrap/react-bootstrap#5731]
## Describe the bug

Popover does not trigger on button click

## Expected behavior

Popover will show on button click

- Operating System: Android
- Browser, Version [Firefox 86.1.1]
- React-Bootstrap Version [1.5.1]

**Comment by kyletsang** [comment]
Examples on popover docs work for me in Android and Firefox 86.1.1

https://react-bootstrap.github.io/components/overlays

Do they work for you?

**Comment by unit-002** [comment]
> 
> 
> Examples on popover docs work for me in Android and Firefox 86.1.1
> 
> https://react-bootstrap.github.io/components/overlays
> 
> Do they work for you?

yeah I just copied the documentation, but I change my layout so I am no longer using the popover since it does not work for me. I used the modal instead.
