### ISSUE TITLE
docs: radio and checkbox examples don't have a 'name' attribute

### ISSUE THREAD

**Issue by jquense** [react-bootstrap/react-bootstrap#5733]
the examples are missing name's so the radio example acts unintuitively if you click more than one radio button in some of the examples

e.g.
https://react-bootstrap.github.io/components/forms/#forms-check-inline

**Comment by manon-pilaud** [comment]
I can do this one

**Comment by jquense** [comment]
awesome!

**Comment by viditrv123** [comment]
I tried solving this issue. Please check commit #5768
