### ISSUE TITLE
Popover target virtual reference

### ISSUE THREAD

**Issue by ShaMan123** [react-bootstrap/react-bootstrap#5737]
Hi,
I was looking into passing a virtual reference to `Popover` `target` prop as described here: [popper.js](https://popper.js.org/react-popper/v2/virtual-elements/).
Can this be achieved?

Thanks for this incredible repo!

**Comment by kyletsang** [comment]
Currently virtual elements are not supported, but there is a PR open for this:
https://github.com/react-bootstrap/react-overlays/pull/887

**Comment by joney-pinkman** [comment]
Can someone recreate a pr to fix the issue?
