### ISSUE TITLE
Allow the Tabs control to have a number eventkey so Typescript enums can be used with it.

### ISSUE THREAD

**Issue by ThatCanadianGuy** [react-bootstrap/react-bootstrap#5739]
## Is your feature request related to a problem? Please describe

After updating my react-bootstrap version and receiving the type files for it, I've found that my tab controls that I had set to have enum eventkey props now fail type check as the enum is a number and the current type in the .d.ts is string or undefined. 

## Describe the solution you'd like

I propose that the type for the eventKey in TabProps (Tab.d.ts) be changed to `eventKey?: string | number;` So that usage similar to 
```
enum AccountTab {
  Properties,
  Permissions,
  Profile
}
<Tabs defaultActiveKey={this.state.activeTab} id="accountTabs">
    <Tab eventKey={AccountTab.Properties} title={"Properties"}>
        [...]
    </Tab>
    <Tab eventKey={AccountTab.Permissions} title={"Properties"}>
        [...]
    </Tab>
    <Tab eventKey={AccountTab.Profile} title={"Properties"}>
        [...]
    </Tab>
</Tabs>
```
can continue to work.

## Describe alternatives you've considered

Alternatively I suppose I could cast my enums to string everywhere to change their value to strings, though it would be a lot of changes to make versus just adding the type support. The control itself works with the proposed change.

## Additional context

N/A

**Comment by kyletsang** [comment]
We fixed this for the v2 bootstrap 5 release. We could backport some of that if needed. Interested in sending a PR?

**Comment by ThatCanadianGuy** [comment]
Sure! I can take a look and submit a PR today. Cheers
