### ISSUE TITLE
Use NODE_ENV var with development mode code

### ISSUE THREAD

**Issue by AlexKVal** [react-bootstrap/react-bootstrap#574]
Beginning is here [gitter](https://gitter.im/react-bootstrap?at=55393a1e1c7f609d3d258a40)

- [ ] Add note to docs about usage of `NODE_ENV` var for development mode code that will be cut / `envified` in production

- [ ] Refactor codebase with using
```js
if (process.env.NODE_ENV === ‘development’) { 
  /* here is the code that will be removed in production /* 
}
```

**Comment by mtscout6** [comment]
This is the same way that React does it, but it should be mentioned that folks using anything other than react-bootstrap.min.js, which we build, will not strip those out.

Downstream users will need to use either `envify` or if they are using webpack to use the `DefinePlugin` I'm not sure of other alternatives that also address this.

**Comment by AlexKVal** [comment]
As it has turned out..
There are no `console` usage in the library (except for tools and tests).
So there is nothing to mark as code only for development mode.
Therefore it doesn't need to add a note into docs about it either.
I'm closing it.

I'm sorry about this hollow PR.

**Comment by mtscout6** [comment]
No worries, thanks for checking it out.
