### ISSUE TITLE
Creating new elements inside Carousel tag places them within carousel-inner

### ISSUE THREAD

**Issue by wleung85** [react-bootstrap/react-bootstrap#5749]
## Describe the bug

I'm trying to create an additional element (an extra button) to the Carousel object but it is placed within the lower carousel-inner div instead of the higher carousel div. 

##  Example

In this example code, I am trying to add an <a> object within the Carousel that will act as another button (on the same level as the indicators and next/prev buttons). 

```js
<Carousel>
  {props.heroItems
    .filter((item) => item.featured === true)
    .map((item) => (
      <Carousel.Item key={item.id}>
        <img 
          className="hero-img d-block w-100"
          src={item.image}
          alt={item.header}
        />
        <Carousel.Caption style={{color: item.color}}>
          <h3>{item.header}</h3>
          {item.caption &&
            <p>{item.caption}</p>
          }
        </Carousel.Caption>
      </Carousel.Item>
    ))
  }
  {/* add new button, not a carousel item */}
  <a role="button" href="#" className="newButtonCSS">New button</a>
</Carousel>
```

Inspecting the elements from the page generated by this code, the new <a> button is placed in the carousel-inner div. As a result, the carousel believes there is one more element than there actually is (and this is reflected in the indicator).
![image](https://user-images.githubusercontent.com/16823748/113187442-ded75a80-9226-11eb-9655-6cc76c7bcc3d.png)

I expect this <a> tag to be placed at the same level as the carousel-inner and carousel-control divs.

Is there a way to add new elements (not changing the prev/next buttons or indicators) to the Carousel?

**Comment by kyletsang** [comment]
Unfortunately no - the `Carousel` component expects all its children to be a `CarouselItem`s.

**Comment by wleung85** [comment]
I see. Then I'll probably have to build a custom carousel component or import one from another library. 
If this were to be enabled in `react-boostrap`, a `Carousel.Inner` component may have to be introduced, or the `Carousel` component becomes smart enough to only place `Carousel.Item`s in carousel-inner. 

Closing ticket.
