### ISSUE TITLE
Sync header and footer active links

### ISSUE THREAD

**Issue by Jonofat** [react-bootstrap/react-bootstrap#5750]
This probably isn't a bug but I don't know how to resolve this. I have a top navbar and navigation in the footer. The top and bottom navs active class work fine independently ie: When I click on a link in the navbar and go to that page, the matching menu item is active and the same goes for the bottom nav.

However, if I click 'contact' in the navbar, the footer menu does not have 'contact' as active, but rather the last item I clicked in the footer nav. How can I get them to sync with eachother so that if I click on 'contact' in the navbar then 'contact' in the footer is also active?

_Note: I am using Next.js Link_

Here is the navbar at the top of the page

```
    <Navbar collapseOnSelect expand="lg" bg="light" sticky="top">
      <Container>
        <Navbar.Brand href="#home">
          <Image src="/logo.png" width={150} height={70}></Image>
        </Navbar.Brand>
        <Navbar.Toggle aria-controls="responsive-navbar-nav" />
        <Navbar.Collapse
          id="responsive-navbar-nav"
          className="justify-content-end"
        >
          <Nav>
            <Link href="/" passHref>
              <Nav.Link>Home</Nav.Link>
            </Link>
            <Link href="/projects" passHref>
              <Nav.Link>Projects</Nav.Link>
            </Link>
            <Link href="/contact" passHref>
              <Nav.Link>Contact Us</Nav.Link>
            </Link>
          </Nav>
        </Navbar.Collapse>
      </Container>
    </Navbar>
```

And the footer

```
    <footer>
      <Container>
        <Row className="d-flex align-items-center">
          <Col md={6}>
            <Image src="/logo.png" width={180} height={93} />
            <p>© </p>
          </Col>
          <Col md={6}>
            <Nav className="justify-content-end">
              <Nav.Item>
                <Link href="/" passHref>
                  <Nav.Link>Home</Nav.Link>
                </Link>
              </Nav.Item>
              <Nav.Item>
                <Link href="/projects" passHref>
                  <Nav.Link>Projects</Nav.Link>
                </Link>
              </Nav.Item>
              <Nav.Item>
                <Link href="/contact" passHref>
                  <Nav.Link>Contact</Nav.Link>
                </Link>
              </Nav.Item>
            </Nav>
          </Col>
        </Row>
      </Container>
    </footer>
```

**Comment by kyletsang** [comment]
NavLinks take an active prop, so you can set that to true based on whatever path you're currently on

**Comment by Jonofat** [comment]
Ah, thanks. So I have that working for the footer now. I did the below which works in that whatever page I go to, the correct footer link is active. This isn't true for the navbar though. If I click 'contact' in the footer for example, 'contact' in the nabber is not active. From the documentation I don't see a way to achieve the same thing as I did with the footer links?

[import { useRouter } from "next/router";

 const router = useRouter();
<Nav className="justify-content-end" activeKey={router.pathname}>](url)

**Comment by kyletsang** [comment]
Ah sorry forgot to mention the `activeKey` prop.  You should be able to set that in your `Nav` and that will correctly highlight the corresponding `NavLink`.  This uses the `href` that's passed into your NavLinks as the key to set the active state.  Try setting this in both your header and footer `Nav` components.
