### ISSUE TITLE
v5 docs: Navbars requires containers

### ISSUE THREAD

**Issue by kyletsang** [react-bootstrap/react-bootstrap#5752]
Navbar-related docs/examples need to be fixed

> All navbars now require a container within. This drastically simplifies spacing requirements and removes the need for extensive CSS overrides we added for responsive containers in v4.

Ref: https://getbootstrap.com/docs/5.0/migration/#navbars

See upstream examples:
https://getbootstrap.com/docs/5.0/components/navbar/

**Comment by bravogeorge** [comment]
Hello, I'm an aspiring technical writer and I would love to contribute in any way I can.

**Comment by kyletsang** [comment]
Thanks @bravogeorge, go for it!

**Comment by bravogeorge** [comment]
@kyletsang Hey, so sorry about that. Yeah, so I was having trouble locating the file to specifically edit when making the commits/pull request and I selected the github icon directly from the link you provided mistakenly thinking that it was the file that would need to be file to edit (🙉 ). 

I think i understand what you were saying about cloning the repository and then editing it locally first. Does
![this](https://user-images.githubusercontent.com/19643078/114108439-f26a6d00-9887-11eb-8b96-8679cc92f066.png) seem like I'm on the right track in terms of how to complete the task? I'd appreciate any advice 🙂

**Comment by kyletsang** [comment]
When you clone the repo, make sure you clone the `bs5-dev` branch - all our v5 work currently sitting there.  I looked through the bootstrap docs and they don't explicitly mention the requirement of the inner container, so maybe we should omit that as well.

I guess the only real task to do here is update the code examples. All the examples in this [link](https://react-bootstrap-v5.netlify.app/components/navbar) will need to be updated to use the `Container` component.  The examples here are pretty much the same as upstream bootstrap, so you can take a look at the corresponding examples and add in the missing bits.

Good luck!

**Comment by bravogeorge** [comment]
Hey @kyletsang I added a pull request for this issue. https://github.com/react-bootstrap/react-bootstrap/pull/5766

Thank you again for all your help! Hope you like the changes.

**Comment by Prince-yohannan** [comment]
can i do this
