### ISSUE TITLE
v5: RTL support

### ISSUE THREAD

**Issue by kyletsang** [react-bootstrap/react-bootstrap#5753]
Ref: https://getbootstrap.com/docs/5.0/migration/#rtl
BS5 Cheatsheet: https://getbootstrap.com/docs/5.0/examples/cheatsheet-rtl/

CSS support should be finished, so all we need now is the JS support.

Here are some components that need updating from a quick glance at bootstrap's source:
- [ ] Dropdown
- [x] Carousel
- [ ] Modal
- [ ] Tooltip

Maybe we should add a setting to `ThemeProvider` for RTL?

Up for discussions here.

**Comment by golota60** [comment]
Hi,

I wanted to pick up `Modal` changes and I've noticed that there *might* be a few more things to change for RTL.
- `dismissible` prop for `Alert` should have close icon aligned to the left
- `Offcanvas` - also close icon should be aligned to the left
- `Toast` - also close icon should be aligned to the left

All of above boil down to `CloseIcon` to be aligned to the left when RTL is true

- `Accordion` - should have the `^` icon aligned fully to the left

Please confirm those, as I've got no experience with RTL 😄

**Comment by kyletsang** [comment]
Those are actually handled by the css, so if you import the `bootstrap.rtl.min.css` instead of the original, you'll see the changes. I think I've gotten all the css bits working already.  Only thing missing is anything JS related.

For the remaining RTL tasks, I think we would need to integrate `@restart/ui` prior to finishing them.  These are the things left to do:

- Modal - Add padding/margin to left side instead of the right when handling scrollbars, and some navbar-related items.  I did the scrollbar handling in the base ModalManager in RUI already.
- Dropdown - Right-align menus by default.  RUI has a new placement API that makes this a bit easier.
- Tooltip - Flip start/end placements.  Actually I think this might not need RUI, but I kinda left it since the other 2 above did.
