### ISSUE TITLE
Styling not applied to Modal close button

### ISSUE THREAD

**Issue by shreyas-jadhav** [react-bootstrap/react-bootstrap#5757]
The close button in `Modal.Header` is showing up as regular html button without any bootstrap styling:

![image](https://user-images.githubusercontent.com/73429007/113500696-b8befc80-953d-11eb-86b4-fb88aedf7f3b.png)

```jsx

<Modal show={show} onHide={handleClose} centered>
              <Modal.Header closeButton>
                <Modal.Title>Fill in your Information First:</Modal.Title>
              </Modal.Header>
              <Modal.Body>
                    //body
              </Modal.Body>
</Modal>
```

## Expected behavior

Show bootstrap styled close button
![image](https://user-images.githubusercontent.com/73429007/113500738-0fc4d180-953e-11eb-86a5-01069e5d9083.png)

## Environment 

- Chrome Version 91.0.4464.4 (Official Build) dev (64-bit)
- React-Bootstrap Version [1.5.2]

**Comment by sohamsshah** [comment]
Can you share a CodeSandbox link for this? Would be helpful

**Comment by kyletsang** [comment]
Closed due to inactivity

**Comment by basvk** [comment]
I have the same issue. See here: https://codesandbox.io/s/morning-sun-ooqld
