### ISSUE TITLE
Form.Control onChange event 

### ISSUE THREAD

**Issue by rawandeheliah** [react-bootstrap/react-bootstrap#5760]
## Description

 in Form.Control OnChange event listener doesn't fire when =>  **selecting all text and then hitting backspace**

## To Reproduce

```
const updateInput = (e) => {
    console.log("changed");
  }
<div>
      <Form.Label htmlFor={props.id}>{props.label}</Form.Label>
        <Form.Control
          type="text"
          id={props.id}
          defaultValue={props.placeholder}
          onChange={(e) => {
            updateInput(e);
          }}
        ></Form.Control>
</div>
```

## Expected behavior
onChange should be triggered .<br>
ps : [when I select part of the text and hit backspace --> onChange event listener is triggered ]

## Environment

- Operating System: [macOS]
- Browser, Version [Chrome , Safari 14]
- React-Bootstrap Version [^1.5.0]

## how I solved this issue to get the app work : 
const updateInput = (e) => {
    console.log("changed");
  }
```
<div>
      <Form.Label htmlFor={props.id}>{props.label}</Form.Label>
        <Form.Control
          type="text"
          id={props.id}
          defaultValue={props.placeholder}
          onChange={(e) => {
            updateInput(e);
          }}
          onSelect={(e) => {
            updateInput(e);
          }}
        ></Form.Control>
</div>
```
however this is just a workaround ,  I still think there is something wrong with onChange event listener  .

**Comment by kyletsang** [comment]
Can you provide a repro on CodeSandbox?

**Comment by kyletsang** [comment]
Closed due to inactivity
