### ISSUE TITLE
React bootstrap modal not work in loop it is show me only first item

### ISSUE THREAD

**Issue by AREEG94FAHAD** [react-bootstrap/react-bootstrap#5762]
I can not now why react bootstrab modal not show me all othere iteam it only first one

**Comment by kyletsang** [comment]
Please follow the [issue template](https://github.com/react-bootstrap/react-bootstrap/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) when reporting issues.  There's a lot of information missing here.

**Comment by kyletsang** [comment]
Closed due to inactivity
