### ISSUE TITLE
Dropdown "drop" prop does not force Menu show below Toggle

### ISSUE THREAD

**Issue by apieceofbart** [react-bootstrap/react-bootstrap#5763]
## Describe the bug

I have Dropdown component that is put inside a container that has `overflow: hidden` set. I have set "drop" prop to "down" but the menu still redners above the toggle.

## Reproducible Example

https://codesandbox.io/s/react-boostrap-dropdown-issue-with-overflow-hidden-issue-c6ee6?file=/src/App.tsx

## Expected behavior

I would like to force dropdown to stay below the toggle. I understand that this is because of the overflow: hidden in the parent and there's no space in the parent to render the whole menu but I would still like to force it. In my app I have a lot of space to render the menu but it would still render above.
If this is not possible then it would be nice to provide that info in docs and propose a workaround - I tried with custom popper config but I couldn't force it, docs don't say much about that.

- React-Bootstrap Version 1.5.2

**Comment by kyletsang** [comment]
I think you can resolve this by rendering the dropdown menu in a portal.  Didn't really test in-depth for side effects, but this should get you started.

See: https://codesandbox.io/s/react-boostrap-dropdown-issue-with-overflow-hidden-issue-forked-tdlji?file=/src/App.tsx

**Comment by apieceofbart** [comment]
@kyletsang  Thanks for the example. I can certainly do that or try some other workarounds but I would expect that react-bootstrap handles that for me - after all it's a workaround for something that drodpdown should handle (according to docs, using drop should be rendered below toggle)

**Comment by jquense** [comment]
if you want to force a position disable `flip` which will turn off the popper flip modifier

**Comment by apieceofbart** [comment]
@jquense  I don't think it changes anything: https://codesandbox.io/s/react-boostrap-dropdown-issue-with-overflow-hidden-issue-c6ee6?file=/src/App.tsx

**Comment by apieceofbart** [comment]
Ah, the `flip` has to be on the Menu, so confusing... thanks it seems to work
