### ISSUE TITLE
Module not found: Can't resolve 'react-bootstrap/Offcanvas'

### ISSUE THREAD

**Issue by thomasmburke** [react-bootstrap/react-bootstrap#5765]
## Describe the bug

Not completely sure if Offcanvas is added to the alpha yet (just looking to confirm), but it appeared to be based off the [project board](https://github.com/react-bootstrap/react-bootstrap/projects/2). I can successfully import and use other `react-bootstrap` components, but Offcanvas is failing to import.

## To Reproduce

Using the code from the [react-bootstrap-v5 docs](https://react-bootstrap-v5.netlify.app/components/offcanvas/#basic-example) with `import Offcanvas from 'react-bootstrap/Offcanvas'` specified at the top of my js file.

I also have the below specified in my index.html
```
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
```

## Expected behavior

I was expecting OffCanvas to be imported properly and allow me to check out what I can do with it.

## Environment (please complete the following information)

- **Operating System:** macOS Big Sur
- **Browser, Version:** Chrome Version 89.0.4389.114
- **React-Bootstrap Version:** 2.0.0-alpha.0

**Comment by LB22** [comment]
I have the same issue on the same version. There are no exports of it to be found inside the npm package, yet it's published in the [docs](https://react-bootstrap-v5.netlify.app/components/offcanvas/).

Please add this! I really need it.

**Comment by kyletsang** [comment]
Currently the docs point to the latest version of the v5 branch, which does contain unreleased code.

I'll release a new alpha with Offcanvas when I get some time later today.

**Comment by kyletsang** [comment]
Published [v2.0.0-alpha.1](https://github.com/react-bootstrap/react-bootstrap/releases/tag/v2.0.0-alpha.1)

**Comment by pradeea** [comment]
Can't resolve 'react-bootstrap/Offcanvas' the offCanvas is not installing .

**Comment by pradeea** [comment]
Can't resolve 'react-bootstrap/Offcanvas' the OffCanvas is not installing   @kyletsang

**Comment by kyletsang** [comment]
> 
> 
> Can't resolve 'react-bootstrap/Offcanvas' the OffCanvas is not installing @kyletsang

@pradeea did you install react-bootstrap v2 beta?

**Comment by pradeea** [comment]
@kyletsang ya i have installed the latest Version of the react-bootstrap it did worked , tq so much

**Comment by Creative-Lee** [comment]
help me.... @kyletsang
how can i update react-bootstrap v2.0.0 T_T
[ npm show react-bootstrap ]  --->  it shows me that the last version is 1.6.1  
I really want to use Offcanvas component.

[ npm install react-bootstrap bootstrap@5.0.2 ]  ----> it only updates bootstrap to V5.0.2   Not a react-bootstrap (still 1.6.1)

plz help newbie......

**Comment by kyletsang** [comment]
@Creative-Lee run `npm install react-bootstrap@next`

**Comment by Creative-Lee** [comment]
@kyletsang 
when I got out of bed, I typed    [ npm install react-bootstrap@next ]

but... react-bootstrap still  V1.6.1 .....

why.... 😥 
I'm sorry I kept asking....... There's no way but to ask you....
google can't help me for 3days

**Comment by kyletsang** [comment]
@Creative-Lee 

You can also try going into package.json and manually changing the version to `2.0.0-beta.4`

Then run npm install

**Comment by Creative-Lee** [comment]
GOD @kyletsang 
you save my life!!!!!!!

**Comment by pradeea** [comment]
@kyletsang why cant we build an seperate community forum  for react-bootstrap users where in that the users of react-bootstrap can interact and have their queries cleared .instead of commenting in the github page what do u think? bcz the react bootstrap community is growing and having an seperate community forum is an added advantage for the users instead of depending on github comments

**Comment by taatiq882** [comment]
Hi, My bootrstrap version is 2.0.0-beta.4 but still offcanvas module not found error is coming.

**Comment by thenoctus** [comment]
npm install react-bootstrap@next bootstrap@5.0.2

I went to the react bootstrap main site and installed the latest above and it solved the issue for me.
