### ISSUE TITLE
Issue with babel  , Typescipt React 17.03

### ISSUE THREAD

**Issue by ausmani** [react-bootstrap/react-bootstrap#5775]
The react-scripts package provided by Create React App requires a dependency:

  "babel-loader": "8.1.0"

 a different version of babel-loader was detected higher up in the tree:

  /var/www/html/projects-ts/node_modules/babel-loader (version: 8.2.2) 

This issue comes after i install react bootstrap however it works fine previously

So my findings is react bootstrap is not compaitable with babel 8.2.2

**Comment by kyletsang** [comment]
I tried this on a newly created CRA project and it works.  `babel-loader` is set to 8.1.0.

Sounds like you have another dependency that's causing the issue for you?

**Comment by kyletsang** [comment]
Closed due to inactivity
