### ISSUE TITLE
Bug with OverlayTrigger warnings 

### ISSUE THREAD

**Issue by NeoRu4** [react-bootstrap/react-bootstrap#5776]
## Describe the bug

Warnings with element props

## To Reproduce

```
import { OverlayTrigger, Tooltip } from 'react-bootstrap'

<OverlayTrigger
      placement={'top'}
      overlay={<Tooltip id={'delete-tooltip'}>delete</Tooltip>}
    >
      // ...some element
    </OverlayTrigger>
```

## Reproducible Example

![image](https://user-images.githubusercontent.com/2778902/115697549-15634980-a37d-11eb-8e94-32dbb553f85b.png)

Problem with element OverlayTrigger warnings in PhpStorm

## Environment (please complete the following information)

- PhpStorm
"react": "^17.0.2",
"react-bootstrap": "^1.5.2",
 "@types/react": "^16.14.5",
 "typescript": "^4.2.3"

**Comment by kyletsang** [comment]
This is a problem with php storm:
https://youtrack.jetbrains.com/issue/WEB-48161

Note: not all of those props are required
