### ISSUE TITLE
Radio button appearing next to ToggleButton component when it shouldn't be

### ISSUE THREAD

**Issue by lblair16** [react-bootstrap/react-bootstrap#5782]
## Describe the bug

I'm using the ToggleButton component as the radio button type and it is no longer working as it should be.

## To Reproduce

You can see the issue on my site here: https://fast-circle-click.herokuapp.com/
You'll just have to create a new account to login if you want to see the issue firsthand (no email required, just enter a username and password)

## Reproducible Example

My code: 
```
<ButtonGroup toggle className="center-items">
                  {levels.map((level, idx) => {
                    if (
                      currAccount.score < level.points &&
                      !currAccount.unlocked
                    ) {
                      return (
                        <OverlayTrigger
                          key={idx}
                          placement="top"
                          overlay={
                            <Tooltip>
                              {currAccount.score}/{level.points} Points
                            </Tooltip>
                          }
                        >
                          <ToggleButton
                            type="radio"
                            variant="secondary"
                            name="radio"
                            value={level.value}
                            checked={currLevel === level.value}
                            onChange={(e) =>
                              setCurrLevel(e.currentTarget.value)
                            }
                            disabled={disabledLevels[level.value]}
                          >
                            {level.name}
                          </ToggleButton>
                        </OverlayTrigger>
                      );
                    } else {
                      return (
                        <ToggleButton
                          key={idx}
                          type="radio"
                          variant="secondary"
                          name="radio"
                          value={level.value}
                          checked={currLevel === level.value}
                          onChange={(e) => setCurrLevel(e.currentTarget.value)}
                          disabled={disabledLevels[level.value]}
                        >
                          {level.name}
                        </ToggleButton>
                      );
                    }
                  })}
                </ButtonGroup>
```

## Screenshots

![image](https://user-images.githubusercontent.com/31866368/115933912-e83a9800-a45d-11eb-961e-f63d899a3a1b.png)

## Environment (please complete the following information)

- Tested on chrome and edge
- React Bootstrap css link: https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css
- React Bootstrap link: https://unpkg.com/react-bootstrap@next/dist/react-bootstrap.min.js

**Comment by kyletsang** [comment]
react-bootstrap@next will install the v2 alpha which is only compatible with bootstrap 5.

Use react-bootstrap@latest

**Comment by DvoeglazovIlya** [comment]
The same problem. Radio and checkbox buttons not working properly.
I have installed the latest versions of react-bootstrap and bootstrap:
"bootstrap": "5.0.2",
"react-bootstrap": "^2.0.0-beta.4",
![image](https://user-images.githubusercontent.com/15049055/129415020-3bdab58c-f29b-4324-af0a-87b81a5fcde0.png)

The code I'm use:
```
const [value, setValue] = useState([1, 3]);
const handleChange = (val) => setValue(val);

<ToggleButtonGroup
  type="checkbox"
  value={value}
  onChange={handleChange}
>
  <ToggleButton id="tbg-btn-1" value={1}>
    Option 1
  </ToggleButton>
  <ToggleButton id="tbg-btn-2" value={2}>
    Option 2
  </ToggleButton>
  <ToggleButton id="tbg-btn-3" value={3}>
    Option 3
  </ToggleButton>
</ToggleButtonGroup>
```
I think html not correct
![image](https://user-images.githubusercontent.com/15049055/129415594-30e8f957-a5e7-4049-8667-33cbd0ec78b2.png)

**Comment by kyletsang** [comment]
@DvoeglazovIlya are you sure you have beta 4 installed?  The code doesn't even produce that HTML

https://github.com/react-bootstrap/react-bootstrap/blob/5bd99640e19e48ca3f6d88dff723b4e06ea4be9d/src/ToggleButton.tsx#L98-L117

**Comment by DvoeglazovIlya** [comment]
@kyletsang, I'm sorry, after restart project or "yarn clear cache". The problem was resolve.
