### ISSUE TITLE
Toast.tsx file Timer is not cleared.

### ISSUE THREAD

**Issue by thisisamardeep** [react-bootstrap/react-bootstrap#5783]
https://github.com/react-bootstrap/react-bootstrap/blob/664d702231379ed920d2d7bf83978a1f4377997c/src/Toast.tsx#L103

looks like we need to clear timer on unmount.

    useEffect(() => {
      // Only reset timer if show or autohide changes.
      autohideTimeout.set(autohideFunc, delayRef.current);

      return () => {
        autohideTimeout.clear(); --> We need to add this line in useeffect.If others are fine i can raise a pr for this.
      }
    }, [autohideTimeout, autohideFunc]);

**Comment by jquense** [comment]
hi thanks for jumping in and helping out. You are right that the timer would need to be cleared on unmount. What you may not see is that the `useTimeout` hook we are making use of here does that for us https://github.com/react-restart/hooks/blob/master/src/useTimeout.ts#L55

**Comment by thisisamardeep** [comment]
yes i saw that  .it is there. still i would suggest to add it here  for clarity in case you are fine with it.i will pick up some other issue .

**Comment by kyletsang** [comment]
Since it's already in the hook, no need to duplicate code.
