### ISSUE TITLE
Cannot adjust modal transition duration

### ISSUE THREAD

**Issue by sebammon** [react-bootstrap/react-bootstrap#5788]
## Describe the bug

I want to adjust the duration of the modal's TRANSITION_DURATION and BACKDROP_TRANSITION_DURATION but this is not possible. I've had a look at the source code and it seems that there two properties on the Modal: `Modal.TRANSITION_DURATION` and `Modal.BACKDROP_TRANSITION_DURATION` but changing them produces no results.

It becomes apparent when you adjust the CSS animation for the `.fade` class to something greater than 300ms, since this is the default value for the `TRANSITION_DURATION`.

## To Reproduce

Have a look at this minimal example [CodeSandbox](https://codesandbox.io/s/pedantic-torvalds-5ller). You will notice that when the Modal opens, the CSS animations work perfectly. However, when the modal is hidden, the Modal unmounts before the animation is complete.

## Expected behavior
I would expect that it is possible to at least change the duration of the TRANSITION_DURATION and BACKDROP_TRANSITION_DURATION property.

## Possible solution

I would be happy to help on this issue. If I'm not mistaken, it may just be a matter of passing the two value to the functions `DialogTransition(...)` and `BackdropTransition(...)`.

**Comment by kyletsang** [comment]
I wonder if it's better to omit the timeout here in the transition since we already use the `addEndListener` handler.  This way, the duration can be controlled directly in the css.

**Comment by sebammon** [comment]
@kyletsang Are you talking about the [animation events](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/animationend_event)? Is it supported enough across browsers?

**Comment by kyletsang** [comment]
> 
> 
> @kyletsang Are you talking about the [animation events](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/animationend_event)? Is it supported enough across browsers?

[Transition end](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/transitionend_event) events.  We already hooked up a handler here:
https://github.com/react-bootstrap/react-bootstrap/blob/master/src/Fade.tsx#L103

`Fade` has a default `timeout` value which I believe is causing the animation to cut out early.  I think we can override the default by passing a null or 0 to `Fade` inside the `DialogTransition`/`BackdropTransition`.

**Comment by sebammon** [comment]
I'm not quite sure I understand how keeping only the end listener will allow the transition to run fully. Maybe I don't fully understand the implementation of the `transitionEndHandler` https://github.com/react-bootstrap/react-bootstrap/blob/master/src/transitionEndListener.ts#L13. What `done` callback is called once the transition is complete?

Either way, I would be happy to work on this issue.

**Comment by kyletsang** [comment]
The done callback will trigger the next state in `react-transition-group`'s `Transition`.

Pasting that code here:

https://github.com/reactjs/react-transition-group/blob/708ebbf965bf61a44e1493cbb80f00a9346527ca/src/Transition.js#L330-L339

It uses both `timeout` and the `addEndListener` if passed.  So in our case, we do have a default timeout of 300ms in `Fade` and that's going to trigger the next state in RTG earlier than the parsed transition time in `transitionEndHandler`.

**Comment by sebammon** [comment]
I have created a PR for this issue. Please could you provide some feedback on any improvements that might be required.
