### ISSUE TITLE
Unnecessary type-definition "@types/classnames" might be no longer required.

### ISSUE THREAD

**Issue by Popescu-PfeifferMarc** [react-bootstrap/react-bootstrap#5789]
After install I got the following npm warning:
```
$ npm i react-bootstrap
npm WARN deprecated @types/classnames@2.3.1: This is a stub types definition. classnames provides its own type definitions, so you do not need this installed.
```
Should I open a pull-request to remove this? Sorry if it's a noob question this is my first "real" issue.

**Comment by kyletsang** [comment]
Looks like the types were bundled in classnames 2.3.0.  Feel free to open a PR to update this.

Thanks!
