### ISSUE TITLE
NavDropdown enforces margin: 0px

### ISSUE THREAD

**Issue by liroliro** [react-bootstrap/react-bootstrap#5793]
Is there a workaround for this? It seems to be in-lined on the HTML-element. 
This can be found in example here: https://react-bootstrap.github.io/components/navbar/

`<div aria-labelledby="basic-nav-dropdown" class="dropdown-menu show" style="margin: 0px">`

**Comment by kyletsang** [comment]
Currently no workaround.

Margin is added here:
https://github.com/react-bootstrap/react-bootstrap/blob/413649b3df0de3ddea20509a3fc243a76920cf3c/src/usePopperMarginModifiers.tsx#L44

We should only set this if popper is used

**Comment by liroliro** [comment]
Okay! Thanks. Hopefully it gets fixed asap.

**Comment by liroliro** [comment]
Found a workaround for now, which involves using !important on the margin-style you want to enforce. But still looking forward to the fix!
