### ISSUE TITLE
NavDropdown alignRight does not allow for breakpoints

### ISSUE THREAD

**Issue by broofa** [react-bootstrap/react-bootstrap#5794]
## Describe the bug

I'd like to be able to constrain the `alignRight` property of NavDropdown's based on breakpoint, much the same way you can do this with other bootstrap properties (e.g. `dropdown-menu-{breakpoint}-right` classes).

Related to #4994 and #3310?

## To Reproduce

Open https://codesandbox.io/s/naughty-ellis-w4zo1 and play with the drop-down at different page widths.

Notice that when the page is narrow and the Toggle element moves to the left, the `alignRight` property no longer makes sense.

## Expected behavior

Applying something like `className="dropdown-menu-sm-right"` works with regular Dropdown components, but does not appear to be possible with NavDropdown's.  I tried `alignRight="sm"`, but that doesn't do anything (other than spit lint errors.)

## Screenshots

When the screen is wide, the alignRight makes sense ...
![image](https://user-images.githubusercontent.com/164050/117155538-8ed54180-ad58-11eb-8a62-02aaafc251e0.png)

But when the screen is narrow, and the dropdown button moves to the left, the dropdown is in the wrong spot...
![image](https://user-images.githubusercontent.com/164050/117155593-9a286d00-ad58-11eb-913c-650b75ca2f2e.png)

## Environment (please complete the following information)

```
$ npx envinfo --system --browsers --npmPackages --binaries
npx: installed 1 in 0.859s

  System:
    OS: macOS 11.1
    CPU: (8) x64 Apple M1
    Memory: 29.52 MB / 16.00 GB
    Shell: 5.1.0 - /usr/local/bin/bash
  Binaries:
    Node: 14.16.1 - ~/.nvm/versions/node/v14.16.1/bin/node
    npm: 6.14.12 - ~/.nvm/versions/node/v14.16.1/bin/npm
  Browsers:
    Chrome: 90.0.4430.93
    Firefox: 88.0
    Safari: 14.0.2
  npmPackages:
    @parcel/babel-plugin-transform-runtime: 2.0.0-nightly.1823 => 2.0.0-nightly.1823
    @types/react-dom: 17.0.3 => 17.0.3
    @types/react-router-dom: 5.1.7 => 5.1.7
    @typescript-eslint/eslint-plugin: 4.20.0 => 4.20.0
    @typescript-eslint/parser: 4.20.0 => 4.20.0
    bootstrap: 4.6.0 => 4.6.0
    eslint: 7.21.0 => 7.21.0
    eslint-config-standard: 16.0.2 => 16.0.2
    eslint-plugin-import: 2.22.1 => 2.22.1
    eslint-plugin-node: 11.1.0 => 11.1.0
    eslint-plugin-promise: 4.3.1 => 4.3.1
    eslint-plugin-react: 7.22.0 => 7.22.0
    fast-levenshtein: 3.0.0 => 3.0.0
    firebase: 8.4.2 => 8.4.2
    firebaseui: 4.8.0 => 4.8.0
    nanoid: 3.1.22 => 3.1.22
    parcel: 2.0.0-beta.1 => 2.0.0-beta.1
    react: ^16.13.1 => 16.14.0
    react-bootstrap: 1.5.2 => 1.5.2
    react-dom: ^16.13.1 => 16.14.0
    react-router-dom: 5.2.0 => 5.2.0
    sass: 1.32.12 => 1.32.12
    typescript: 4.2.3 => 4.2.3
```

**Comment by kyletsang** [comment]
This is something we fixed up in v2 if you're interested in using that.  

Might be able to backport it.

**Comment by broofa** [comment]
Thanks for looking at this.  Having upgraded to `react-bootstrap@next`, I have a couple questions ...


* Is there an upgrade guide of some sort?  (I.e. something that might help answer these other, more specific questions...)
* What's the right incantation for using `alignRight` with breakpoints?  It's not immediately obvious from looking at the source.
* What's the recommended pattern JSX pattern for `FormGroup`s with breakpoints.  I've been using the old pattern that relied on `Col`, but that appears to have broken.

Unrelated to anything:  I noticed that `@types/classnames` module has [been deprecated](https://www.npmjs.com/package/@types/classnames) with a notice saying it should be removed.  (Let me know if you'd like me to create an issue for this.)

**Comment by kyletsang** [comment]
Just realized the `align` changes I mentioned earlier wasn't released yet.  Will push a new alpha tomorrow after I finish up with some other stuff.

Meanwhile, take a look [here](https://react-bootstrap-v5.netlify.app/components/dropdowns/#responsive-alignment) on how to use responsive alignment.  This applies to `NavDropdown`s too.

`classnames` has a PR to remove deprecated types (#5795).

**Comment by kyletsang** [comment]
@broofa 

https://github.com/react-bootstrap/react-bootstrap/releases/tag/v2.0.0-alpha.2

**Comment by broofa** [comment]
Just tested this and it looks like it's working.  Thank you!

breadcrumb for anyone who might follow: Installing the latest alpha (above) and adding `align={{ sm: 'end' }}` worked like a charm.
