### ISSUE TITLE
Border of Get Started Button has margin greater in Mobile mode (320 px) 

### ISSUE THREAD

**Issue by Anmolreshi** [react-bootstrap/react-bootstrap#5797]
I could Modify this ! Shall I send a PR

**Comment by kyletsang** [comment]
Seems fine to me.  Is there an issue this is addressing?

**Comment by Anmolreshi** [comment]
The Button is not fitting the container in 320px . Visit This Link where I have shown the issue of button overflow.
Link : https://drive.google.com/file/d/1gw5R3RA8Qfh1i64qYVEm6YutIIcDiUoH/view?usp=sharing
