### ISSUE TITLE
Copy to clipboard option for codes

### ISSUE THREAD

**Issue by sharunspi** [react-bootstrap/react-bootstrap#5798]
A Copy to clipboard option will be very helful for developers to copy an enture snippet of code.

**Comment by sharunspi** [comment]
I would like to know how the website is made. there is not documentations regrading the development of website.

**Comment by kyletsang** [comment]
There's a bit of info about the docs site here: https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md#documentation

**Comment by sharunspi** [comment]
I got the source code from here [https://github.com/react-bootstrap/react-bootstrap/tree/master/www](https://github.com/react-bootstrap/react-bootstrap/tree/master/www)
