### ISSUE TITLE
Option for Toast to be position: fixed

### ISSUE THREAD

**Issue by IHIutch** [react-bootstrap/react-bootstrap#5799]
Currently, the toast is `position: absolute` by default, but you lose the benefit of the placement when you scroll down the page. Allowing it to be `position: fixed` would keep the positioning regardless of scroll position. (Seems like maybe this just becomes the default, for the option of `absolute`?)

**Comment by kyletsang** [comment]
The styles come from the bootstrap css - we don't add anything extra on our side.

If you're looking to change the position style, you can manually override the styles in your code.

**Comment by IHIutch** [comment]
I actually don't see where position is explicitly defined at all https://github.com/twbs/bootstrap/blob/v5.0.1/scss/_toasts.scss

From what I can tell, it seems like they have it included in their docs as `position: absolute`, but only as a way to illustrate some of the functionality.

The intended use (at least from my perspective) feels like it's meant to be used in combination with `position: fixed`. And anecdotally, I'm not really sure how you'd use it with `position: absolute`, except maybe in very specific circumstances.

**Comment by jp26198926** [comment]
I came across to this thread searching for the solution when you scroll down the page. Thank you for pointing out the `position:fixed` sir, it really helps me :)

`<ToastContainer position="bottom-start" className="position-fixed">`
