### ISSUE TITLE
FadeMixinSpec Inconsistent Failure

### ISSUE THREAD

**Issue by aabenoja** [react-bootstrap/react-bootstrap#581]
Over the weekend I found that the `Should remove the in class for all elements` test in the `FadeMixinSpec` is failing on an off. I have not been able to diagnose the cause of the race condition yet.

**Comment by mtscout6** [comment]
I was seeing this over the weekend as well, thanks for reporting the issue before I did :wink:

**Comment by thetimbanks** [comment]
I saw this inconsistency as well while running the tests for the Popover and Tooltip animation. I only saw it fail once though out of all the times I ran the test suite.

**Comment by jquense** [comment]
should be moot now that #848 is in
