### ISSUE TITLE
Problems extending/theming via CSS while using Typescript

### ISSUE THREAD

**Issue by jessedp** [react-bootstrap/react-bootstrap#5815]
## Describe the bug

Apologies if this is a dupe of a discussion/docs I've missed...

The [Theming and customizing styles](https://react-bootstrap.github.io/getting-started/theming/) suggestions worked wonderfully while I was using plain JS. I could and did, for example, easily add a __xs__ size button by adding `.btn-xs{}` in my CSS.

In converting the project to TS, this stops working because __size__ is defined in [ButtonProps](https://github.com/react-bootstrap/react-bootstrap/blob/master/src/Button.tsx#L21) as `size?: 'sm' | 'lg';`

## To Reproduce
Add a Button to a TS project and use a __size__ other than _sm_ or _lg_.
```
<Button size="xs" variant="secondary" onClick={this.handleClose}>
            Close
 </Button>
```
## Expected behavior

No typescript type def complaints for properties that should be extendable via CSS.

## Environment (please complete the following information)

- Operating System: any
- Browser, Version: any current
- React-Bootstrap Version - 1.6.0

## Additional context
In my mind, the "fix" would be to change that definition to `size?: 'sm' | 'lg' | string;` . That's what was done for the [Variant](https://github.com/react-bootstrap/react-bootstrap/blob/master/src/types.tsx#L1) type, though oddly(?) not for [ButtonVariant](https://github.com/react-bootstrap/react-bootstrap/blob/master/src/types.tsx#L11) or [Color](https://github.com/react-bootstrap/react-bootstrap/blob/master/src/types.tsx#L22). Then `size` in Modal, Spinner, and whatever other properties in the various Components fall under the "should be extendable via CSS".

Using `bsPrefix` technically works, but then I'm making copies of variant/etc styles just to change the Button size which gets gross and messy and is probably in part why it's not recommended.

In the meantime, I'm trying to extend/copy the various components parts I need/want to bring forward my css based customizations to (Button, Spinner, Modal, Dropdown & DropdownToggle so far).

Hopefully I'm missing something easy and obvious here, because the two workarounds I have seem untenable. Happy to submit a PR to get started with what I think should be included in a change if that seems proper.

**Comment by kyletsang** [comment]
Yeah we should probably change it to allow customizations.  Only downside is we lose auto-complete (https://github.com/microsoft/TypeScript/issues/29729), but maybe that's ok?

A workaround is to do `size={'xs' as any}`

**Comment by jessedp** [comment]
I certainly appreciate and feel silly about that workaround, thanks! I was also unaware/hadn't noticed what my suggestion does to auto-complete - tough choice there.

**Comment by hongsiflearn** [comment]
@kyletsang any update for 'allow customizations' ?
