### ISSUE TITLE
Can i use properly react-bootstrap latest version 1.6.0 in bootstrap 5

### ISSUE THREAD

**Issue by MunnyReol** [react-bootstrap/react-bootstrap#5817]
Can i use properly react-bootstrap latest version 1.6.0 in bootstrap 5

If i can't then please update your...

**Comment by kyletsang** [comment]
Use v2 for anything bootstrap 5 related.

https://github.com/react-bootstrap/react-bootstrap/releases/tag/v2.0.0-alpha.2

**Comment by dietergeerts** [comment]
Is there any estimate for when v2 that works with Bootstrap 5 will be fully released? I'm currently needing to decide which version we are gonna use on a project, and if it will be out in the near future, we could use the newer bootstrap version instead. I searched the project, but can't find a goal or estimate.

**Comment by kyletsang** [comment]
Currently using [this](https://github.com/react-bootstrap/react-bootstrap/projects/2) for tracking the tasks.  A large majority of the v5 work is done and I think we're also pretty much done with breaking changes so the next release will be a beta to finish up features + polish. Contributions are welcome to speed up the process.  I'd say a lot of the stuff is fairly stable for usage.  

Also no plans to add new components beyond what is included in Bootstrap already.
