### ISSUE TITLE
Can't hit enter to open link/button dropdown items

### ISSUE THREAD

**Issue by piakaroa** [react-bootstrap/react-bootstrap#5818]
I want to make my app more accessible and keyboard friendly, but I have one problem; I have 1 link and 2 buttons in a dropdown menu, and hitting enter on either of these results in nothing. Any suggestions? Using the mouse button works just fine.

**Comment by jquense** [comment]
Try hitting space? Drop-down items are usually links (anchors), not buttons so enter traditionally doesn't work to activate them. In any case which key works is more related to the HTML you use than the Dropdown

**Comment by piakaroa** [comment]
> Try hitting space? Drop-down items are usually links (anchors), not buttons so enter traditionally doesn't work to activate them. In any case which key works is more related to the HTML you use than the Dropdown

Nope, doesn't work. It works on every other dropdown included in the app, however...

**Comment by jquense** [comment]
you'd need top provide a reproduction then if it's just one dropdown that doesn't work
