### ISSUE TITLE
Badges and pills literally doesn't work

### ISSUE THREAD

**Issue by hrqmonteiro** [react-bootstrap/react-bootstrap#5824]
```
              <Button variant="primary">
                Profile <Badge variant="light">9</Badge>
                <span className="sr-only">unread messages</span>
              </Button>
```

Tried every variation of the badges and pills and none of them are showing correctly:

![2021-05-18_15-35](https://user-images.githubusercontent.com/17055027/118705509-b1eb0100-b7ee-11eb-8ff7-c70537e7e2ac.png)

**Comment by jquense** [comment]
looks like you are missing the necessary CSS, maybe you have a custom Sass build of the bootrastrap css or maybe you're using an incompatible version

**Comment by Karinon** [comment]
Not sure about the react-bootstrap version @hrqmonteiro is using, but I have the same issue with react-bootstrap@2.0.0-beta.0 and Bootstrap 5.

```
<Button variant="primary">
  Profile <Badge variant="light">9</Badge>
  <span className="sr-only">unread messages</span>
</Button>
```

Turned into the following HTML
```
<button type="button" class="btn btn-primary">
  Profile
  <span variant="light" class="badge">9</span>
  <span class="sr-only">unread messages</span>
</button>
```

Shouldn't it be something like this?

```
<button type="button" class="btn btn-primary">
  Profile 
  <span class="badge bg-light text-dark">9</span>
  <span class="sr-only">unread messages</span>
</button>
```

**Comment by kyletsang** [comment]
@Karinon, the props have changed.  See the updated examples in the v5 docs here:
https://react-bootstrap.netlify.app/components/badge/

**Comment by JosephVoid** [comment]
I'm trying to use badges like this:

<Badge bg="warning">Warning</Badge>

But it says " Property 'bg' does not exist on type 'IntrinsicAttributes... "
'variant' exists but it doesn't style anything.

i am using react-bootstrap 1.6.1 and bootstrap 5.0.2

**Comment by kyletsang** [comment]
> 
> 
> I'm trying to use badges like this:
> 
> `<Badge bg="warning">Warning</Badge>`
> 
> But it says " Property 'bg' does not exist on type 'IntrinsicAttributes... "
> 'variant' exists but it doesn't style anything.
> 
> i am using react-bootstrap 1.6.1 and bootstrap 5.0.2

update react-bootstrap to v2 beta.

1.6.1 is not compatible with bootstrap 5

**Comment by JosephVoid** [comment]
@kyletsang it worked, thanks.
