### ISSUE TITLE
Toast background-color

### ISSUE THREAD

**Issue by pistou** [react-bootstrap/react-bootstrap#5825]
It would be great to be abble to configure the `background-color` property of a `<Toast />`

The same solution used in `<Card />` would be great, as such:
```JavaScript
[
  'Primary',
  'Secondary',
  'Success',
  'Danger',
  'Warning',
  'Info',
  'Light',
  'Dark',
].map((variant, idx) => (
  <Toast bg={variant.toLowerCase()} key={idx} />
));
```

**Comment by kyletsang** [comment]
Bootstrap 5 has a color variation in the docs:
https://getbootstrap.com/docs/5.0/components/toasts/#color-schemes

We could add a `bg` prop here for convenience.
