### ISSUE TITLE
Documenatation link for react-bootstrap v2

### ISSUE THREAD

**Issue by 3atharvkurdukar** [react-bootstrap/react-bootstrap#5830]
Guys, I just want to try out the new `react-bootstrap v2-alpha` . I am so excited about it. However, I could not find the link to its documentation page.

I understand that the project is in alpha stage, but still could you please add documentation page?  I am okay with it being incomplete.

**Comment by Brawl345** [comment]
Here: https://react-bootstrap-v5.netlify.app/

I found it on the releases page: https://github.com/react-bootstrap/react-bootstrap/releases/tag/v2.0.0-alpha.0

**Comment by 3atharvkurdukar** [comment]
Thank you very much!
