### ISSUE TITLE
Navbar sticky: bottom

### ISSUE THREAD

**Issue by iiLearner** [react-bootstrap/react-bootstrap#5831]
## Describe the bug

On documentation page (https://react-bootstrap.github.io/components/navbar/) shows `Navbar sticky` has two options: `top` and `bottom`, however in navbar props, only `top` is allowed for `sticky`:
```ts
export interface NavbarProps extends BsPrefixPropsWithChildren {
    variant?: 'light' | 'dark';
    expand?: boolean | 'sm' | 'md' | 'lg' | 'xl';
    bg?: string;
    fixed?: 'top' | 'bottom';
    sticky?: 'top';
    onToggle?: (expanded: boolean) => void;
    onSelect?: SelectCallback;
    collapseOnSelect?: boolean;
    expanded?: boolean;
    role?: string;
}
```
I'm not sure whether the documentation is outdated or `bottom` was removed for some other reason.

## Expected behavior

Expecting `NavbarProps.sticky` to allow `top` and `bottom`

## Environment (please complete the following information)

- Operating System: Windows 10 pro
- Browser, Version: Chrome, latest
- React-Bootstrap Version: 1.6.0 (latest as of now)

**Comment by kyletsang** [comment]
Sticky bottom actually isn't valid and isn't included with the bootstrap css.  Looks like I accidentally messed up the docs with another PR.

**Comment by ken604** [comment]
sticky bottom was removed in Feb 2021 #5656

@kyletsang new doc release required?

**Comment by kyletsang** [comment]
Changes needed in bs4-dev branch
