### ISSUE TITLE
Implement new eslint rule `object-shorthand`

### ISSUE THREAD

**Issue by AlexKVal** [react-bootstrap/react-bootstrap#584]
- [x] When the issue https://github.com/eslint/eslint/issues/2374 is resolved,
- [x] eslint@0.21.0 version with fix is released. 
- [x] Implement new eslint rule `object-shorthand`.
- [x] Wait for issue https://github.com/eslint/eslint/issues/2486 with `es7.objectRestSpread` is resolved
- [x] Wait / find a solution for `object-shorthand` with `es7.objectRestSpread`
- [x] Remove all disabling comments

1 [NavItem.js#L32](https://github.com/react-bootstrap/react-bootstrap/blob/02a8764b196b9268678ded26838a2436a54a2090/src/NavItem.js#L32)
2 [Input.js#L181](https://github.com/react-bootstrap/react-bootstrap/blob/02a8764b196b9268678ded26838a2436a54a2090/src/Input.js#L181)
3 [Button.js#L34](https://github.com/react-bootstrap/react-bootstrap/blob/02a8764b196b9268678ded26838a2436a54a2090/src/Button.js#L34)

ref: http://eslint.org/docs/rules/object-shorthand

**Comment by dozoisch** [comment]
2374 seems to be fixed now!

**Comment by AlexKVal** [comment]
Thank you, Hugo :sparkles: 
I've updated the issue progress.
Now we wait for new version release containing this fix.

**Comment by AlexKVal** [comment]
I've added
`Wait for issue eslint/eslint#2486 with es7.objectRestSpread is resolved`

**Comment by AlexKVal** [comment]
As it was expected `es7.objectRestSpread` rule is experimental and `eslint` doesn't support `es7` yet.
Maybe `babel-eslint` monkeypatching.
It needs additional research.

**Comment by AlexKVal** [comment]
I've done some research on `babel-eslint`.

The babel-eslint "monkeypatching" is not patching any rules.

Therefore it seems the only solution is to comment out those lines for now.
(or write standalone plugin with this rule working with es7, as Ilya Volodin suggests)

As for this PR: 
Maybe tag it as `needs dependency update` ?

**Comment by mtscout6** [comment]
Have you submitted the issue with babel-eslint?

**Comment by AlexKVal** [comment]
It's useless. 
`babel-eslint` is just kind of sugar for AST. That's all.
It has no any connection with any rule evaluation at all.

**Comment by mtscout6** [comment]
Ah, I gotcha :confused:

**Comment by AlexKVal** [comment]
Resolved by https://github.com/react-bootstrap/react-bootstrap/pull/872
and https://github.com/react-bootstrap/react-bootstrap/pull/875
