### ISSUE TITLE
Typescript error in react-bootstrap/esm/NavbarCollapse.d.ts

### ISSUE THREAD

**Issue by JoseSweetTech** [react-bootstrap/react-bootstrap#5841]
## Describe the bug

The console prompts a Typescript error on esm/NavbarCollapse.d.ts when I try to launch my app on my local machine or create a production build.

## To Reproduce

Add react-bootstrap to a project and launch it with npm run start

## Screenshots

![image](https://user-images.githubusercontent.com/78407846/119634081-a8771f80-be12-11eb-8c28-667e7c907e7f.png)

## Environment

- Operating System: Ubuntu
- React-Bootstrap Version "^1.4.0"
- typescript ^4.1.5

## Additional context

I tried to update react-bootstrap to 1.6.0 and typescript to 4.2.4 but I still getting the same error.

**Comment by fazeel-qureshi-mpf** [comment]
facing the same issue. have you figure out the solution?

**Comment by Luukdewaaier** [comment]
Also running into this issue!

**Comment by kyletsang** [comment]
`role` types were changed in `@types/react` that's incompatible with what we currently have:
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/53344

The workaround for now is to downgrade your types version to 16.14.6 and below or 17.0.6 and below

**Comment by poyea** [comment]
The problem is `CollapseProps.role` is a string type. A quick fix would be to omit `role` from `CollapseProps`, that is to replace
```ts
export interface NavbarCollapseProps extends Omit<CollapseProps, 'children'>, React.HTMLAttributes<HTMLDivElement>, BsPrefixProps {
}
```
with
```ts
export interface NavbarCollapseProps extends Omit<CollapseProps, 'children' | 'role'>, React.HTMLAttributes<HTMLDivElement>, BsPrefixProps {
}
```
in `esm/NavbarCollapse.d.ts`.

**Comment by fazeel-qureshi-mpf** [comment]
already having below version i.e. @types/react version 16.8.19
