### ISSUE TITLE
Error while executing tsc command

### ISSUE THREAD

**Issue by manid1998** [react-bootstrap/react-bootstrap#5842]
I am getting the following error while executing tsc command in my project

node_modules/react-bootstrap/esm/NavbarCollapse.d.ts(4,18): error TS2320: Interface 'NavbarCollapseProps' cannot simultaneously extend types 'Omit<CollapseProps, "children">' and 'HTMLAttributes<HTMLDivElement>'.
  Named property 'role' of types 'Omit<CollapseProps, "children">' and 'HTMLAttributes<HTMLDivElement>' are not identical.

**Comment by Luukdewaaier** [comment]
same as #5841
