### ISSUE TITLE
Sub Components for Accordion produces import error

### ISSUE THREAD

**Issue by bajahranks** [react-bootstrap/react-bootstrap#5853]
## Describe the bug

I am getting this error

Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

whenever I add any of the sub-components to the Accordion component. eg. <Accordion.Item> or <Accordion.Header>

## To Reproduce

install react-bootstrap and bootstrap
import {Accordion} from "react-bootstrap"

Add Accordion Component with sub-components

See reproducible for details

## Reproducible Example

https://codesandbox.io/s/modest-frost-4l7mo?file=/src/App.js:25-40

## Expected behavior

Render Accordion

## Environment (please complete the following information)

- Operating System: Windows 10
- Browser, Version Firefox
- React-Bootstrap Version 17.02

**Comment by kyletsang** [comment]
You'll need to use v1 if you want to use Bootstrap 5.  Here's the latest:
https://github.com/react-bootstrap/react-bootstrap/releases/tag/v2.0.0-alpha.2

**Comment by bajahranks** [comment]
Updating to version 2 fixed the issue in the sandbox but I'm still getting the same error on my local machine. Is there something else I need to do? I tried a private browser in case of caching but no luck.

**Comment by bajahranks** [comment]
Nevermind I had to restart the server. strangely....

**Comment by fschenkun22** [comment]
I got the same question too
```import React, { Component } from 'react'
import {Accordion} from 'react-bootstrap'

export default class Lheader extends Component {
    render() {
        return (
            <Accordion>
                <Accordion.Header>Accordion Item #1</Accordion.Header>
            </Accordion>
        )
    }
}
```
Then Error occurred：
×
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `Lheader`.
▶ 21 stack frames were collapsed.
Module.<anonymous>
E:/WWW/react-fw/fw/src/index.js:6
  3 | import App from './App';
  4 | 
  5 | 
> 6 | ReactDOM.render(
  7 | 
  8 |     <App />,
  9 |  
View compiled
