### ISSUE TITLE
Multi item Carsousel

### ISSUE THREAD

**Issue by jdhalmahapatra** [react-bootstrap/react-bootstrap#5857]
Hi,

I am trying to implement multi item carousel using React Boostrap, But I am not able to achieve using <Carousel.item> and the documentation provided. 

I am looking something like [(https://w3js.com/react-multi-carousel)](url)

Can someone please help me here that is it possible to implement the above feature using React Bootstrap?

Thanks in advance.

Regards,
Jyotiraditya

**Comment by kyletsang** [comment]
Bootstrap only supports 1 slide in view at a time.  You can probably create what you're looking for with swiper js.
