### ISSUE TITLE
Custom Dropdown Component: Keyboard Navigation Issue

### ISSUE THREAD

**Issue by 08screasey** [react-bootstrap/react-bootstrap#5861]
I have a setup similar to the custom dropdown component example in the react-bootstrap docs. Since the form control has autofocus enabled the first time the dropdown opens it is focused. However if I use the keyboard arrow keys to move through the dropdown items I can't navigate back up to the input anymore and since it no longer autofocuses I can't find a way to make it accessible. Pressing TAB closes the dropdown and moves to the next feature. 

Link to issue:
https://react-bootstrap.github.io/components/dropdowns/#custom-dropdown-components

![Screenshot (262)](https://user-images.githubusercontent.com/59900275/120649924-93873580-c47d-11eb-9e85-9dba55a0f6e5.png)

In my own design there is also a submit button next to the input which complicates things further, but aside from that the code is more or less identical to the example in the docs.
![Screenshot (263)](https://user-images.githubusercontent.com/59900275/120651341-f6c59780-c47e-11eb-85dc-e9117cb8a23b.png)

**Comment by jquense** [comment]
@kyletsang I think this is fixed restart/ui, not catching the tab correctly. In the meantime I think you can preventPropagation on the even @08screasey to keep the tab from bubbling up
