### ISSUE TITLE
Help needed: FormCheck not toggling from keyboard

### ISSUE THREAD

**Issue by 08screasey** [react-bootstrap/react-bootstrap#5862]
I have a custom checkbox component in my app that I can't seem to find a way to make keyboard accessible.
```
              {['high', 'medium', 'low'].map((val) => (
                <Form.Check key={val} id={`priority.${val}`}>
                  <Form.Check.Input type="checkbox" ref={register} name={`priority.${val}`} onChange={onChange} />
                  <Form.Check.Label>
                    <PriorityCategory type={val} />
                  </Form.Check.Label>
                </Form.Check>
              ))}
```
Since I'm integrating it with React-hook-form I am passing the ref to the register function, but this does not seem to have any impact on the issue. 
Versions:
bootstrap - 4.6.0
react-bootstrap - 1.6.1
On the documentation website it seems that pressing space-bar should trigger the check/uncheck. Any ideas as to what the issue might be?

**Comment by jquense** [comment]
Can you put up a codesandbox demostrating? I would check that your Input and Label are being associated together with `for` and `id`

**Comment by 08screasey** [comment]
@jquense I did and it worked, but it made me realise that the check is set on the "keyup" event, and there was a bug in my code preventing it from executing. Trying to reproduce in the sandbox helped though, so thanks!
