### ISSUE TITLE
Screenshot regression tests.

### ISSUE THREAD

**Issue by AlexKVal** [react-bootstrap/react-bootstrap#587]
It is already not the first time when small visual inconsistencies leak out. 
(because they can be tested only by human for now)

It is clear that my `npm run docs components OK` sure is not enought :smile: 

It seems we need some kind of `image/screen` testing for components.
`screen shot before` and `screen shot after` (by PhantomJS for example) and tool for comparing them.

But also it needs some automation tool to click buttons and fill in fields to check how look of elements change.

And these image comparings need to be done for all testable states
`before` patch and 
`after` patch.

Something like that.

**Comment by AlexKVal** [comment]
ref: https://github.com/Huddle/PhantomCSS

**Comment by taion** [comment]
These guys might have some open source plan when they launch: https://percy.io/

**Comment by sibelius** [comment]
take a look on this: https://github.com/callemall/material-ui/blob/next/test/regressions/test.js

**Comment by taion** [comment]
@sibelius Super cool! Thanks.

**Comment by sibelius** [comment]
this could help: https://github.com/jxnblk/repng

**Comment by Anenth** [comment]
This could be pretty helpful, [Magic Visual Regression](https://www.npmjs.com/package/magic-visual-regression)
I created for css cleanup project. This module just compares the images and gives the report, I can modify it for our needs.

**Comment by haroon-sheikh** [comment]
Has someone started working on this? if not, I'd like to look at integrating wraith https://github.com/BBC-News/wraith

**Comment by taion** [comment]
I don't believe anybody has started working on this.

**Comment by taion** [comment]
This might still be relevant down the road.
