### ISSUE TITLE
Type issue with @types/react@17.0.10

### ISSUE THREAD

**Issue by BCaspari** [react-bootstrap/react-bootstrap#5871]
## Describe the bug

tsc fails with
node_modules/react-bootstrap/esm/NavbarCollapse.d.ts:4:18 - error TS2320: Interface 'NavbarCollapseProps' cannot simultaneously extend types 'Omit<CollapseProps, "children">' and 'HTMLAttributes<HTMLDivElement>'.  Named property 'role' of types 'Omit<CollapseProps, "children">' and 'HTMLAttributes<HTMLDivElement>' are not identical.

## To Reproduce

use react-bootstrap 1.6.0 together with @types/react 17.0.10.
tsc version is 4.2.4

## Expected behavior

tsc should work

**Comment by kyletsang** [comment]
Dupe of #5841.  This is fixed in 1.6.1
