### ISSUE TITLE
NavDropdown with align="end" still left-aligned in NavBar

### ISSUE THREAD

**Issue by jasonjoh** [react-bootstrap/react-bootstrap#5875]
## Describe the bug

Setting `align="end"` on a `NavDropdown` has no effect in a `NavBar`

## To Reproduce

1. Go to https://codesandbox.io/s/festive-bash-qvyot?file=/src/App.js
2. Click on the **User** dropdown item in the nav bar
3. Note that the menu is aligned to the left-hand side of the **User** dropdown

## Reproducible Example

https://codesandbox.io/s/festive-bash-qvyot?file=/src/App.js

## Expected behavior

The menu should be aligned to the right-hand side of the **User** dropdown. Copying the produced HTML and pasting into codeply.com has the correct behavior, which would indicate this is not a Bootstrap issue.

## Screenshots

![image](https://user-images.githubusercontent.com/8966342/121578165-621be600-c9f8-11eb-9d05-31a2f60186d9.png)

## Environment (please complete the following information)

- Operating System: Windows 10
- Browser, Version Edge Insiders Version 92.0.891.1, Chrome 91.0.4472.101
- React-Bootstrap Version 2.0.0-beta.0

## Additional context

The same behavior is seen when using a `Dropdown` as `NavLink` as described here: https://react-bootstrap-v5.netlify.app/components/navs/#using-dropdowns

**Comment by kyletsang** [comment]
Looks like we're missing the `data-bs-popper` attribute in the navbar case.  Interested in sending a PR?
