### ISSUE TITLE
ModalProps not works well in vscode because of [other: string]: any and Omit

### ISSUE THREAD

**Issue by namhong2001** [react-bootstrap/react-bootstrap#5876]
## Describe the bug

Omit uses keyof type operator but when it comes with computed property llike [other: string]: any, then keyof makes everything [x: string]: any.
I don't know it is intended or not in typescript area, but the remained fact is that ModalProps not works well currently, so I suggest if it is ok then how about remove [other: string]: any in ModalProps. I think if there are some missing attributes from bootstrap, then if it should be handled by react-bootstrap then improve, and if it should be handled by library user, then its not here concern. So I think [other: string]: any is not necessary.

## Expected behavior

ModalProps types should works well.

## Environment (please complete the following information)

vscode latest

## Additional context

ref: #5732

**Comment by kyletsang** [comment]
Let's track this in #5732.

For v2, we'll fix when we integrate [@restart/ui](https://github.com/react-restart/ui)
