### ISSUE TITLE
Focus error in Dropdown

### ISSUE THREAD

**Issue by xkomiks** [react-bootstrap/react-bootstrap#5883]
## Describe the bug
If, when navigating with Tab and several `Dropdown` components are located one after another, we get an error
`Cannot read property 'contains' of null`

## To Reproduce

1. Go to [demo](https://codesandbox.io/s/priceless-noether-3l33m?file=/src/App.css)
2. Focus on first Dropdown
3. Keydown Tab

## Reproducible Example

Minimal example by using [CodeSandbox](https://codesandbox.io/s/priceless-noether-3l33m?file=/src/App.css).

## Expected behavior
On pressing Tab, focus just change to another component without error

## Screenshots
Screenshots from sandbox https://i.imgur.com/cHdVnx0.png
Screenshots from project https://i.imgur.com/UPS7Rsg.png

## Environment (please complete the following information)

- Operating System: [Linux]
- Browser, Version Chrome
- React-Bootstrap Version [^1.6.0]

**Comment by golota60** [comment]
Tried to reproduce it, this is what i found:

I downloaded code from codesandbox and ran it locally and everything works normally. 

I thought it might be an issue with codesandbox but there's the same issue on stackblitz(https://stackblitz.com/edit/react-gq3fgy?file=src%2FApp.js) so it might be a thing on their side? I'm not too sure about that though

**Comment by xkomiks** [comment]
@golota60 I do not know how it can be reproduced locally for you, can you try to run this code in Next js app?

**Comment by golota60** [comment]
Thanks for additional info! Can confirm, this reproduces when using next.js
![image](https://user-images.githubusercontent.com/37072867/122351910-eb7a6d80-cf4e-11eb-9a0d-28bdf8296f26.png)

**Comment by jotoh98** [comment]
The source of the error lays in [react-overlays](https://github.com/react-bootstrap/react-overlays): [Dropdown.tsx #281](https://github.com/react-bootstrap/react-overlays/blob/1c8688d215092bf5de33fd3043c538f7e96c6a7b/src/Dropdown.tsx#L281)
`!menuRef.current!.contains(e.target as HTMLElement)`

I'm not sure if the non-null assertion failing should be prevented or if the state of `current` being null is illegal.

**Comment by kyletsang** [comment]
By default, dropdowns do not render the menu until the button toggle is clicked.  So in this case, since there is no menu, the ref isn't valid yet.  We'll need to check if `menuRef.current` exists before calling `contains()`

**Comment by xkomiks** [comment]
@kyletsang When can you fix this?

**Comment by kyletsang** [comment]
@xkomiks 

`react-overlays` 5.1.0 includes the fix for this.  Update the transitive dependency and you're good to go 👍

**Comment by xkomiks** [comment]
Thanks

**Comment by xkomiks** [comment]
It looks like this is not fixed in version 2.0.0-alpha.2

**Comment by golota60** [comment]
Yes, that's because `react-overlays` needs to be updated to atleast `5.1.0`. I think next release should have it 👍
