### ISSUE TITLE
React-easy-crop does not work with Modal

### ISSUE THREAD

**Issue by lapaz17** [react-bootstrap/react-bootstrap#5887]
## Describe the bug

I try to implement zoom-in and crop feature with images by using [this](https://www.npmjs.com/package/react-easy-crop) package. I even opened a [bug report](https://github.com/ricardo-ch/react-easy-crop/issues/269) in that repository but problem is definitely related to modal.
## To Reproduce

Just run the example at my repo.

## Reproducible Example

https://github.com/lapaz17/React-Easy-Crop-webpack-example

## Expected behavior

Image must be shown in full size and croppable.

## Screenshots

[SS: ](https://user-images.githubusercontent.com/39624400/122686033-ca986d80-d217-11eb-8627-2129d0d6a5e4.png)

## Environment (please complete the following information)

- Operating System: Pop-Os 20.04 LTS
- Browser, Version: Chromium Version 83.0.4103.116 (Developer Build)
- React-Bootstrap Version  "1.6.1",

**Comment by kyletsang** [comment]
This is a styling issue. Modals use `position: relative` so you'll need to add your own height to the modal body if you want the cropper to be larger.

**Comment by lapaz17** [comment]
Thanks.
