### ISSUE TITLE
Using Navbar template causes multiple renderer error

### ISSUE THREAD

**Issue by JonathanMSifleet** [react-bootstrap/react-bootstrap#5890]
## Describe the bug
When using the [navbar found here](https://react-bootstrap.github.io/components/navbar/#navbars-overview), I get this message:

> Warning: Detected multiple renderers concurrently rendering the same context provider. This is currently unsupported.

After removing multiple sections the error occurs when "NavDropdown" is used.

[Log](https://pastebin.com/CLigkkVi)

[React Component](https://github.com/JonathanMSifleet/ReactProject/blob/main/client/src/components/shared/Header/Header.tsx)

## To Reproduce

1. Clone project found in React Component
2. Enter "npm i" in terminal
3.  Enter "npm run createSymlinks" in terminal
4.  Enter "npm run deployClientLocally" in terminal

## Expected behavior

Header should render without causing any errors

## Screenshots

![Untitled](https://user-images.githubusercontent.com/41328055/123243212-b5069a80-d4da-11eb-85d4-3d68ef9fbf54.png)
![Untitled2](https://user-images.githubusercontent.com/41328055/123243417-e97a5680-d4da-11eb-88d8-f6e1a2ddd194.png)

## Environment (please complete the following information)

- Operating System: Windows 10
- Browser, Version Chrome 91
- React-Bootstrap Version 1.6.1

**Comment by golota60** [comment]
Hello!

Could you please provide a codesandbox where this issue occurs? I took a stab at it and wasn't able to recreate it https://codesandbox.io/s/restless-snowflake-1gp80?file=/src/App.js

**Comment by JonathanMSifleet** [comment]
I've ended up using mdbreact instead as its somewhat time-sensitive.
