### ISSUE TITLE
ToggleButtonGroup onChange is not working

### ISSUE THREAD

**Issue by Mizan-Rifat** [react-bootstrap/react-bootstrap#5896]
ToggleButtonGroup onChange is not getting called on button clicked.
not even in example page: https://react-bootstrap-v5.netlify.app/components/buttons/#controlled
version : "2.0.0-beta.2"

**Comment by kyletsang** [comment]
Each `ToggleButton` needs a unique id now in bootstrap 5 due to changes in the markup.  The docs example is currently missing that so it doesn't work.

Interested in sending a PR?

**Comment by basantech89** [comment]
@kyletsang I've raised a PR for this - 
[https://github.com/react-bootstrap/react-bootstrap/pull/5900](url)
