### ISSUE TITLE
Form.Select and Form.Range are not defined

### ISSUE THREAD

**Issue by DerekFei** [react-bootstrap/react-bootstrap#5898]
## Describe the bug

Form.Select and Form.Range are not defined in 1.6.0 and 1.6.1  (JS)

## To Reproduce
1. Import Form
2. use From.Select and Form.Range you will get an error

## Reproducible Example

Minimal example by using [CodeSandbox](https://codesandbox.io/s/github/react-bootstrap/code-sandbox-examples/tree/master/basic).

## Expected behavior

They should be defined in Form 

## Screenshots

![image](https://user-images.githubusercontent.com/14947579/123886322-31efa500-d91d-11eb-88fc-3b6730e0dff5.png)

## Environment (please complete the following information)

- Operating System: all
- Browser, Version all
- React-Bootstrap Version 1.6.1

**Comment by kyletsang** [comment]
These components are available in the v2 beta only.  If you want to use the v1 versions of them, they have different syntax and can be found in the docs:  https://react-bootstrap.github.io/components/forms
