### ISSUE TITLE
Offcanvas 'top' placement

### ISSUE THREAD

**Issue by bay-jacewhitten** [react-bootstrap/react-bootstrap#5910]
## Is your feature request related to a problem? Please describe

No - N/A

## Describe the solution you'd like

Add the 'top' option to the offcanvas component as per the Bootstrap docs

## Describe alternatives you've considered

Using custom css until implemented

## Additional context

See docs => https://getbootstrap.com/docs/5.0/components/offcanvas/#placement

**Comment by kyletsang** [comment]
This is available in v2 beta 2:  https://react-bootstrap.netlify.app/components/offcanvas/#placement
