### ISSUE TITLE
Controlled <Form.Select /> component improperly hides the drop-down arrow with Bootstrap 5 (Bootstrap 4 works fine)

### ISSUE THREAD

**Issue by booherbg** [react-bootstrap/react-bootstrap#5913]
## Describe the bug

Can't create a 'standard looking' controlled `<select>` component with the latest react-bootstrap and Bootstrap 5.x, however it works fine with Bootstrap 4.x (see sandbox)

`<Form.Control>` works as expected with `value` and `onChange` props, BUT the CSS has `appearance: none;` which makes the control drop the down arrow (makes the select look more like an input box rather than the user expected drop-down).

## To Reproduce

Try to create a controlled Select component that uses local state. See code sandbox.

## Reproducible Example

https://codesandbox.io/s/stupefied-almeida-dsh5w (Broken w/ Bootstrap 5.0.2)
https://codesandbox.io/s/long-shape-q85k9 (Works w/ Bootstrap 4.6.0)

## Expected behavior

Either allow default `<Form.Select>` to be controlled, or fix `<Form.Control>` so that it shows the drop-down arrow on the right side, similar to how `bootstrap-react` already works with Bootstrap 4.x

## Screenshots

Bootstrap 5 (no drop down arrow):
![image](https://user-images.githubusercontent.com/159698/124826651-aee0d700-df3a-11eb-9785-58d062c8d2fe.png)

Bootstrap 4 (drop down arrow works fine)
![image](https://user-images.githubusercontent.com/159698/124826842-eea7be80-df3a-11eb-943b-ce82c5efe3b8.png)

Everything is identical above *except* the bootstrap version.

## Environment (please complete the following information)

- Operating System: OSX
- Browser, Version: Latest Chrome
- React-Bootstrap Version: 1.6.1
- Bootstrap Version: 5.0.2

## Additional context

Seems to work fine w/ Bootstrap 4.x!

**Comment by booherbg** [comment]
Alternatively, can someone create a working example of a controlled select? I can't get `<Form.Select>` to work properly with `value` and `onChange` props (webpack throws a weird non-descript type error)

**Comment by kyletsang** [comment]
You'll need to upgrade to react-bootstrap v2 beta in order to use Bootstrap 5.  v1.x is not compatible

**Comment by booherbg** [comment]
The same bug exists with v2 beta. I have updated the sandbox project accordingly. 

@kyletsang can we re-open? This bug report is still valid.

**Comment by kyletsang** [comment]
@booherbg, the syntax around the select is now different, you don't use `<Form.Control as="select">` anymore.

See https://react-bootstrap.github.io/components/forms/#forms-select

**Comment by booherbg** [comment]
@kyletsang thank you. That explains it. With the upgrade to the latest react-bootstrap, the syntax works as expected with controlled components. Thanks!
![image](https://user-images.githubusercontent.com/159698/126216407-d3051c2c-ed1d-4510-91e3-6b7bf44c4fdc.png)
