### ISSUE TITLE
Feature to copy code at the click of the button in documentation.

### ISSUE THREAD

**Issue by VibhorJaiswal** [react-bootstrap/react-bootstrap#5914]
As of currently there is no easy way to copy code from the documentation without manually selecting and copy the code.

I would like to contribute this feature by which code can be copied by a single click of a button.

**Comment by kyletsang** [comment]
Sure go for it, thanks!

**Comment by VibhorJaiswal** [comment]
ok! I already started working on it!

**Comment by VibhorJaiswal** [comment]
How do I run it on my local machine? It is giving me this error. 
![image](https://user-images.githubusercontent.com/69683278/125103881-65d78100-e0fa-11eb-84ca-5e14c45ca69b.png)

**Comment by kyletsang** [comment]
> 
> 
> How do I run it on my local machine? It is giving me this error.

https://github.com/react-bootstrap/react-bootstrap#local-setup

`yarn run bootstrap` will install all the deps for the lib + docs site

**Comment by VibhorJaiswal** [comment]
Hey! The code is ready but, Can you please tell where should be the related css?

**Comment by VibhorJaiswal** [comment]
@kyletsang reminder that I have opened a pull request with all the features discussed in this issue. It has passed all the checks and is completely bug free so please review the code.

**Comment by kyletsang** [comment]
@VibhorJaiswal  Sorry a bit tied up with other tasks at the moment.  Will review when I get a chance.
