### ISSUE TITLE
Get list of data currently displayed on screen

### ISSUE THREAD

**Issue by fazeelzama20** [react-bootstrap/react-bootstrap#5915]
## Is your feature request related to a problem? Please describe
I want to know the list of data that is currently displayed on the screen if I am using a react-bootstrap-table.
Of course, there is a prop available for the default data. But that is concise of the whole bunch of data which we will be going to populate inside the table.

**My problem is:** 
Say I am populating the table with 100 data rows with the feature of pagination.
Now say I am on page 1 and the table is showing 10 rows and the rest of the rows will be going to display as I move on further pages.
Here, How can I get these 10 rows of data on page 1 which is currently displaying to the user?

## Describe the solution you'd like
There should be some prop, which gives me on-screen rendered data. No matter the size or page value. Whatever data comes on screen it should give it to me.

**Comment by kyletsang** [comment]
You should post this in the `react-bootstrap-table` github project since that is separate from `react-bootstrap`
