### ISSUE TITLE
Unable to extend `ModalProps` interface in TS

### ISSUE THREAD

**Issue by jkhoffman** [react-bootstrap/react-bootstrap#5916]
## Describe the bug

In my project, I need to extend from the `ModalProps` interface. Unfortunately, I only see the props from the immediate parent (`ModalProps`) but none beyond that (`BaseModalProps` or `TransitionCallbacks`.)

This is due to an interaction between the `Omit` utility type and the index type (`[other: string]: any`) defined on `ModalProps` in `react-overlays`.

I went looking in the code for `react-overlays` and found this:
https://github.com/react-bootstrap/react-overlays/blob/master/src/Modal.tsx#L50-L53

So, apparently, this is a known issue with a fix already provided in `react-overlays`. 

Now, we just need React Bootstrap to import `BaseModalProps` instead of `ModalProps as BaseModalProps` from `react-overlays`.

## To Reproduce

Probably best to look at my CodeSandbox example, below. I added comments to the code, hopefully you'll be able to see the issue quickly.

## Reproducible Example

- https://codesandbox.io/s/condescending-bell-zjz3s?file=/src/components/MyModal.tsx

## Expected behavior

If I extend `ModalProps`, I expect to get _all_ props all the way up the extension hierarchy. Took me a few hours to diagnose the problem. 

## Screenshots

- None, sorry. Hard to show this in a screenshot.

## Environment (please complete the following information)

- Operating System: macOS
- Browser, Version n/a
- React-Bootstrap Version 1.6.1

**Comment by jkhoffman** [comment]
Here's the simplest example I could come up with showing the problem with `Omit` and index types:

```typescript
interface A {
  [other: string]: any;
  apple: string;
  anchor: string;
  anchovy: string;
}

interface B extends Omit<A, 'apple'> {
  banana: string
}

interface C extends B {
  cheese: string;
}

function Test({ ...props }: C) {
  // typeof props = {
  //   [x: string]: any;
  //   [x: number]: any;
  //   cheese: string;
  //   banana: string;
  // } // where are anchor and anchovy??
}
```

**Comment by kyletsang** [comment]
Same as #5732

Fix incoming in #5894

**Comment by jkhoffman** [comment]
Ahh, @kyletsang, I did not notice this was a duplicate issue. Sorry about that, thanks for the fix!

**Comment by Miradorn** [comment]
@kyletsang Hey there and sorry for picking up this old issue. I just ran into the same issue in v2.0.3. Can it be that there is a regression? Should I open a new Issue? Tahnks for your time

**Comment by kyletsang** [comment]
> @kyletsang Hey there and sorry for picking up this old issue. I just ran into the same issue in v2.0.3. Can it be that there is a regression? Should I open a new Issue? Tahnks for your time

Seems like this didn't merge properly for v2.  Need to change

https://github.com/react-bootstrap/react-bootstrap/blob/75487ce35348f6b8e617f4ff75dfb6f5a3743de2/src/Modal.tsx#L15

to

`import BaseModal, { BaseModalProps } from '@restart/ui/Modal';`
