### ISSUE TITLE
Use rc-table instead of html table

### ISSUE THREAD

**Issue by dotamir** [react-bootstrap/react-bootstrap#5925]
## Is your feature request related to a problem?
I'm working a lot with tables in our platform and we were using HTML tables before but since we're using rc-table, I don't have any headaches about tables. I can write them much faster using rc-table. It has a rich API and many features that are hard to implement with HTML tables. Also using this, you don't have to write so much code.

## Describe the solution you'd like

Using [rc-table](https://table-react-component.vercel.app/) we can implement a rich table component.

## Additional context

Take a look at the rc-table and see how complete is that. Lot's of useful API's.

I'm ready to help on this and contribute here if you are agree.

Thoughts and comments are welcome.

**Comment by bay-jacewhitten** [comment]
This is a nice library, and a great suggestion. But from my personal experience I think this choice should be left to the developer and their project in terms of how that table get printed and maintained.

For example I use [react-table](https://react-table.tanstack.com/docs/api/useTable) over other grid libraries for a variable list of personal reasons. Ultimately, for me - when it comes to tables it's about managing the data first, and then I can dress up the presentation after the fact. Thats when I reach for the table component here for the out of box styling and quick props. Being locked into a complete solution like I have in the past, for example react-bootstrap-table-2 which appears to be abandoned at the moment,  has its own caveats and challenges.

**Comment by dotamir** [comment]
@bay-jacewhitten I agree with you, it's best to be on developer's decision. But I've been thinking about Developer experience here. I've been working with `rc-table` for almost 2-years now and haven't had issues with it. It's giving you a rich API to deal with. You can build a table from simple to advanced type in my experience.

I think it's better to give a powerful component instead of a simple one. I know it should be challenging but components should do what they are best at.

**Comment by kyletsang** [comment]
Thanks for the suggestion, but we'll pass.  If the user needs something as rich as rc-table, then they can integrate that themselves and apply the bootstrap styling.
