### ISSUE TITLE
Form Control Validation

### ISSUE THREAD

**Issue by gfiury** [react-bootstrap/react-bootstrap#5927]
## Describe the bug
I'm trying to validate two password controls. The two of them are required and the second one has an additional condition of been an exact match with the first one.

I used the isInvalid property to validate the controls, but the submitting is showing the tick icon and the invalid message at the same time

## To Reproduce
Link showing the example: [validation passwords](https://codesandbox.io/s/lingering-waterfall-18m5l?file=/src/App.js)

1. Go to the link
2. Click on Submit form
3. The tick shows up on both controls but also the require message

## Expected behavior

I expect the controls to call isInvalid function to know if it is invalid and show the invalid message (and not showing the tick).
If this is not the expected behavior, then how can I do this without using Formik?

Thanks

**Comment by kyletsang** [comment]
Remove the `validated` prop from your `Form`.  That's used if you're using HTML5 validation.
