### ISSUE TITLE
Carousel not rendered properly

### ISSUE THREAD

**Issue by fabian-techhighway** [react-bootstrap/react-bootstrap#5929]
If you look at the [Bootstrap Carousel with Indicators](https://getbootstrap.com/docs/5.0/components/carousel/#with-indicators), they clearly mention to add the indicators as button. I think this plugin should follow the same process i.e. render it as **div (carousel-indicators) > button** instead of **ol (carousel-indicators) > li**

Also, please have a look at the indicator parameters. This should not include any indicator parameter while rendering. e.g. **data-bs-target**, **data-bs-slide-to** etc. The reason I'm asking you to include these parameters is because one of the parameter **data-bs-target** has bootstrap CSS rules. e.g.

`.carousel-indicators [data-bs-target] {
    box-sizing: content-box;
    flex: 0 1 auto;
    width: 30px;
    height: 3px;
    padding: 0;
    margin-right: 3px;
    margin-left: 3px;
    text-indent: -999px;
    cursor: pointer;
    background-color: #fff;
    background-clip: padding-box;
    border: 0;
    border-top: 10px solid transparent;
    border-bottom: 10px solid transparent;
    opacity: .5;
    transition: opacity .6s ease;
}
`

**Comment by kyletsang** [comment]
Sounds like you're using react-bootstrap 1.x.  This is not compatible with bootstrap 5.  Please use the 2.x beta instead
