### ISSUE TITLE
Accordion Example in the Docs produces error

### ISSUE THREAD

**Issue by hussnainwithss** [react-bootstrap/react-bootstrap#5930]
## Describe the bug

When i used the example from the docs of creating an Accordion the one with <Accordion.Item> react throws an error.

## To Reproduce

1. Create a simple component
2. copy the first example on the react-bootstrap Accordion component page
3. run application and open in browser

## Reproducible Example

https://codesandbox.io/s/affectionate-chebyshev-fptus?file=/src/App.js

## Expected behavior

Accordion should work and render correctly.

## Screenshots
![image](https://user-images.githubusercontent.com/47157583/125821174-ef7ca12c-6ee6-4178-b1f6-8a9e0dc6d927.png)

## Environment (please complete the following information)

- Operating System: macOS
- Browser, Version  Chrome 91
- React-Bootstrap Version 1.6.1

**Comment by kyletsang** [comment]
This accordion example has new markup that's only available in v2 beta.

For v1, see the docs here: https://react-bootstrap-v4.netlify.app/components/accordion/
