### ISSUE TITLE
Form.Select is NOT working and giving import/export error for rendering

### ISSUE THREAD

**Issue by esrakartal** [react-bootstrap/react-bootstrap#5935]
## Describe the bug

When I used the `<Form.Select>` tag in my project, I received an import/export error for my component. I thought I did a mistake while writing import/export. But, when I deleted everything in my component file and rewrote myself without copypasting, It gave an error on `<Form.Select>` tag. 

## To Reproduce

1. Go to https://react-bootstrap.netlify.app/components/forms/#forms-select
2. Copy and paste a component such as App.js
3. Start the react

## Expected behavior

It should show up the dropdown menu on the page

## Screenshots

<img width="936" alt="Screen Shot 2021-07-18 at 6 43 25 AM" src="https://user-images.githubusercontent.com/57167700/126069960-a6a16c84-3df5-4719-a1ac-d0a33d6fa8c2.png">

## Environment (please complete the following information)

- Operating System: macOS Big Sur 11.4 and also Windows 10
- Browser, Version: Chrome 91.0 and Yandex
- React-Bootstrap Version: v2.0.0-beta.2 (Bootstrap 5.0)

## Additional context

I used `<Form.Control>` tag instead of `Form.Select`, it is working fine.

**Comment by kyletsang** [comment]
What's the react-bootstrap version in your package.json?

**Comment by esrakartal** [comment]
> What's the react-bootstrap version in your package.json?

It is: 
`"react-bootstrap": "^1.6.1"`

**Comment by kyletsang** [comment]
Change that to `2.0.0-beta.2`.  The main docs site is currently referencing the v2 beta release.

**Comment by esrakartal** [comment]
> Change that to `2.0.0-beta.2`. The main docs site is currently referencing the v2 beta release.

Thank you so much. It worked.
