### ISSUE TITLE
Website snippet is missing @next

### ISSUE THREAD

**Issue by FunctionDJ** [react-bootstrap/react-bootstrap#5937]
The ["Installation" segment](https://react-bootstrap.github.io/getting-started/introduction#installation) has a command to install currently incompatible versions of `react-bootstrap` and `bootstrap`, resulting in this `package.json`:
```json
  "dependencies": {
    "bootstrap": "5.0.2",
    "react-bootstrap": "^1.6.1"
  }
```

Since the guide mentions `@next` further down, i assume this is also missing here (since it's 2.0 beta docs for BS5).

**Comment by kyletsang** [comment]
Yeah we should add `@next` there to clear any confusion.  Interested in sending a PR?
