### ISSUE TITLE
`<Form.Check>` and `<Form.Check.Label>` should add `form-check` and `form-label` class automatically.

### ISSUE THREAD

**Issue by Mizan-Rifat** [react-bootstrap/react-bootstrap#5938]
`<Form.Check>` and `<Form.Check.Label>` should add `form-check` and `form-label` class automatically.

https://react-bootstrap-v5.netlify.app/components/forms/#forms-check-api

**Comment by giovannipiller** [comment]
I was about to open a similar issue.
Looks like `<Form.Check>` will only print the class `form-check` if a label is provided:
https://github.com/react-bootstrap/react-bootstrap/blob/47df950afc2777cc3635bfd538c64d90634cec4a/src/FormCheck.tsx#L173

Sometimes it makes sense to not provide a `label`, for example when an aria-label/aria-labelledby is provided in its place.

**Comment by kyletsang** [comment]
So the issue here is that in the custom rendering scenario, the container is missing the `form-check` class?

**Comment by giovannipiller** [comment]
Yes.

As a simple example:
```jsx
<Form.Check />
```

Will produce:
```html
<div class="">
  <input type="checkbox" class="form-check-input">
</div>
```
Which doesn't include the `form-check` class.

----
On the other hand, simply adding a `label`:
```jsx
<Form.Check label="test label" />
```


Will produce:
```html
<div class="form-check">
  <input type="checkbox" class="form-check-input">
  <label title="" class="form-check-label">test label</label>
</div>
```

----

I think that the class `form-check` should be displayed regardless of the presence of `label`.

Reproducible also on 2.0.0-beta-4: https://codesandbox.io/s/zen-silence-7uxg1?file=/src/App.js

**Comment by giovannipiller** [comment]
(Re-reading it, I might have misunderstood the original issue. I can create a separate one if you'd like.)

**Comment by kyletsang** [comment]
@giovannipiller checkboxes without labels don't need the wrapping element with `.form-check`.  This is referenced here: https://getbootstrap.com/docs/5.0/forms/checks-radios/#without-labels

**Comment by giovannipiller** [comment]
@kyletsang thanks!
