### ISSUE TITLE
isInvalid prop doesn't work for a custom component in Form Control

### ISSUE THREAD

**Issue by hpaul-reputation** [react-bootstrap/react-bootstrap#5943]
## Describe the bug

For the code below,
```react
<Form.Group>
  <Form.Control>
    isInvalid
    as={
      forwardRef(() => (<div>Report</div>))
    }
  <Form.Control.Feedback type="invalid">Invalid Report</Form.Control.Feedback>
</Form.Group>
```

The `Feedback` is **not activated** even though the `Form.Control` has the `isInvalid` prop set to true. I've noticed that it only happens if I pass a custom component using `forwardRef()`.

Image of output:
<img width="714" alt="Screen Shot 2021-07-20 at 2 26 19 PM" src="https://user-images.githubusercontent.com/85559065/126383855-6fd9c0c3-b9de-4a62-baac-d1305d3ff8ce.png">

Is there any other way I can pass a custom control component so that the error classes are added to it? 

## To Reproduce

1. Create a form wit ha form control. 
2. Inject a custom component in the form control using the `as` prop.
3. Set the form control to be `invalid by passing `isInvalid` prop
4. Add a invalid `Feedback`
5. You will see that the invalid feedback does not pop up.

## Reproducible Example

Minimal example by using [CodeSandbox](https://codesandbox.io/s/react-bootstrap-demo-forked-5jdpn?file=/src/App.js).

## Environment (please complete the following information)

- Operating System: macOS Big Sur
- Browser, Version: Chrome 91
- React-Bootstrap Version: latest

**Comment by kyletsang** [comment]
Your custom component needs to apply the `className` prop to your element.

**Comment by hpaul-reputation** [comment]
@kyletsang what do you mean?

**Comment by kyletsang** [comment]
In order for your custom component to get styling, react-bootstrap applies classes to the element.  In your case

```
 as={
      forwardRef(() => (<div>Report</div>))
    }
```

this doesn't forward `className` to the element so it won't inherit any styles.

Try:

```
 as={
      forwardRef((props) => (<div {...props}>Report</div>))
    }
```
