### ISSUE TITLE
CardColumns renders a single column

### ISSUE THREAD

**Issue by rkgallaway** [react-bootstrap/react-bootstrap#5944]
### Result

v2.0.0-beta.4 (using Bootstrap 5.0.2) renders a single column.  20 cards were present, all in one column and regardless of card width. neither mention of change in [documentation](https://react-bootstrap.github.io/components/cards/#card-columns), nor property(s) necessary to achieve multiple columns. Docs do show an example of a single column, implying a change to CardColumn (singular column) functionality, which if intentional warrants a Component rename and I propose a multiple-column CardColumns option.

### Expectation

v1.6.1 (Bootstrap 4.6.0) renders 3 columns by default (possibility: card width possibly a factor for column number).  20 cards were also present, divided between the three columns.   [Documentation](https://react-bootstrap-v4.netlify.app/components/cards/#card-columns)  does show an example of 3 columns.

#### Steps to reproduce the behavior:

1. Go to [this sandbox](https://codesandbox.io/s/polished-meadow-jq0fp?file=/package.json)
2. view results
3. notice bootstrap version "5.0.2"
5. change bootstrap version to "4.6.0"
6. See three columns as expected

#### not working:

![image](https://user-images.githubusercontent.com/40313258/126435921-e154f088-0ffb-48ad-8ddc-64eeadc066c8.png)

#### working:

![image](https://user-images.githubusercontent.com/40313258/126435862-075c1a6d-07ce-4464-b7f0-502955b06c84.png)

## Environment

- Operating System: [Catalina Version 10.15.7] 
- Browser, Version [Version 91.0.4472.114 (Official Build) (x86_64)]
- React-Bootstrap Version [v2.0.0-beta.4]
- have reproduced same results with BigSur and WIndows 10 on student machines (unsure of all version specifics)

**Comment by kyletsang** [comment]
Looks like this was removed upstream in favor of a 3rd party component:
https://github.com/twbs/bootstrap/pull/28922
https://getbootstrap.com/docs/5.0/components/card/#masonry

We should remove this component and related docs.

**Comment by Durai46** [comment]
@kyletsang is this issue has still open?

**Comment by kyletsang** [comment]
@Durai46 yes, feel free to take it.  Thanks

**Comment by BlackboardCreative** [comment]
Fwiw, the recommended approach to use Masonry does not work out of the box with react-bootstrap. Columns are equal in height to the largest card in the row. See attached.
<img width="952" alt="Screen Shot 2021-09-07 at 1 28 25 PM" src="https://user-images.githubusercontent.com/976276/132386757-28d1ba9f-b3e2-4153-9f3f-7e12031f28ca.png">
<img width="968" alt="Screen Shot 2021-09-07 at 1 28 41 PM" src="https://user-images.githubusercontent.com/976276/132386700-485383f5-3fc6-4d05-8777-13443c8cb81a.png">
