### ISSUE TITLE
Use of <Form.Select> throws error

### ISSUE THREAD

**Issue by marknorrapscm** [react-bootstrap/react-bootstrap#5945]
## Describe the bug

The `<Form.Select>` component seems to break in whatever circumstance it is used. I cannot find any mention of this being a known bug.

## To Reproduce

1. Create a `<Form.Select>` component inside a `<Form>`
2. See error:

> Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

## Reproducible Example

Reproducible example: https://codesandbox.io/s/affectionate-butterfly-mvrro?file=/src/App.js

If you comment out the `<Form.Select>` the code in the above sandbox works. Leave the select in and it breaks.

## Expected behavior

The select dropdown displays as a normal component.

## Environment (please complete the following information)

- Windows 10
- Chrome Version 91.0.4472.124 (Official Build) (64-bit)
- React-Bootstrap v1.6.1

**Comment by marknorrapscm** [comment]
Got around this by using `<Form.Control as="select">` rather than `<Form.Select>`.

If the select component isn't working the docs ([here](https://react-bootstrap.github.io/components/forms/#forms-select)) should really advise users to use the aforementioned code rather than `<Form.Select>`.

**Comment by kyletsang** [comment]
FormSelect is a v2 component.  You need to select the correct docs for the version you're using from the dropdown in the navbar.
