### ISSUE TITLE
Badges not styling with Bootstrap 5.0.2 and react-bootstrap ^2.0.0-beta.4

### ISSUE THREAD

**Issue by kuhlaid** [react-bootstrap/react-bootstrap#5947]
Test at:
https://codesandbox.io/s/github/react-bootstrap/code-sandbox-examples/tree/master/basic-ts

In the App.tsx file:
Change
```import Jumbotron from 'react-bootstrap/Jumbotron';```
to 
```import Badge from 'react-bootstrap/Badge';```

Change
```
<Jumbotron>
  <h1 className="header">
    Welcome To React-Bootstrap TypeScript Example
  </h1>
</Jumbotron>
```
to 
```<h2><Badge pill variant="success">test badge</Badge></h2>```

At this point you should see a big green badge in the output. Now go into the package.json file and change:
```"bootstrap": "^4.6.0",```
to 
```"bootstrap": "5.0.2",```
and 
```"react-bootstrap": "^1.5.2",```
to 
```"react-bootstrap": "^2.0.0-beta.4",```

The badge text and background turns white.

**Comment by kuhlaid** [comment]
I suppose Badges are pointless with react-bootstrap v2 since you can simply create a badge using a variation of:
```<span className="small p-1 bg-info text-light rounded-pill">test badge</span>```

**Comment by kyletsang** [comment]
Change `variant` prop to `bg`.  It's been renamed in v2 due to upstream changes in the class, but we forgot to add this to the migration guide.
