### ISSUE TITLE
`Pagination.Item` generates valid markup, but links do not work

### ISSUE THREAD

**Issue by jefmsmit** [react-bootstrap/react-bootstrap#5948]
## Describe the bug
I am using `react-bootstrap` 1.6.1, with `react-router-bootstrap` 0.25. I am building a pagination component. My expectation is that I can do the following:

`<Pagination.Item as={Link} to="/mypage?page=2" key={2}>{2}</Pagination.Item>`

This produces the markup I expect:

```
<a class="page-link" role="button" href="/mypage?page=2">2</a>
```

However the link is suppressed. 

Is this expected? Am I suppose to add a specific `onClick` handler? This general pattern works elsewhere with react-router and react-bootstrap, so I am curious why this one is diifferent.

**Comment by kyletsang** [comment]
Can you try adding `href` in addition to `to`?  I believe the underlying `SafeAnchor` component is suppressing the link behavior due to a missing href prop.

**Comment by jefmsmit** [comment]
@kyletsang that fixed it. Thanks so much.

**Comment by kyletsang** [comment]
Thanks for confirming.  Going to close this one in favor of #5951 to track the potential fix.

**Comment by jefmsmit** [comment]
@kyletsang this appears to be causing another issue as mentioned here:
https://github.com/remix-run/react-router/issues/7931#issuecomment-893094830
