### ISSUE TITLE
Warning: findDOMNode is deprecated in StrictMode using Modal component

### ISSUE THREAD

**Issue by Styopchik** [react-bootstrap/react-bootstrap#5952]
## Describe the bug

React-bootstrap version 1.6.1

## To Reproduce
- Use React.StrictMode
- add modal Component to page.
- Click on link to open it
- Warning appears in console

## Reproducible Example

Minimal example by using [CodeSandbox](https://codesandbox.io/s/adoring-snowflake-7m3ef).

**Comment by kyletsang** [comment]
This is fixed in v2 for bootstrap 5.

**Comment by Kepro** [comment]
@kyletsang but we are not going to update whole app to bootstrap 5 just like that... can you please support also BS4???

**Comment by kyletsang** [comment]
> 
> 
> @kyletsang but we are not going to update whole app to bootstrap 5 just like that... can you please support also BS4???

There are breaking changes required to support StrictMode, so that's why it was deferred to react-bootstrap v2 and bootstrap 5.
