### ISSUE TITLE
ARIA role="dialog" must have an accessible label

### ISSUE THREAD

**Issue by dualcyclone** [react-bootstrap/react-bootstrap#5953]
(moved from https://github.com/react-bootstrap/react-overlays/issues/965 & https://github.com/react-bootstrap/react-overlays/issues/964)

## Describe the bug

Related to https://github.com/react-bootstrap/react-overlays/issues/964

Adding any `aria` attributes to the `Modal` adds these to the child DOM element, which means the main parent element still does not have an accessible label.

## To Reproduce

Create a `Modal` and add `aria-label="test"` to it:

```
import Modal from "react-bootstrap/Modal";

...
<Modal
  ...
  aria-label="test"
>
...
```

Observe that the `aria-label` added does not get added to the element with `role="dialog"`, but instead onto its first child.

```
<div role="dialog" aria-modal="true">
    <div aria-label="test">
    ....
    </div>
</div>

```

## Reproducible Example

Minimal example by using [CodeSandbox](https://codesandbox.io/s/old-wave-1xc5v?file=/src/App.js).

## Expected behavior

The main element with `role="dialog"` should have the `aria` attributes added to it.

## Additional context

[MDN - ARIA: dialog role](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/dialog_role)

> However, adding role="dialog" alone is not sufficient to make a dialog accessible. Additionally, the following needs to be done:
>
> The dialog must be properly labeled

**Comment by devceline** [comment]
Put out a PR to hopefully fix this issue [here](https://github.com/react-bootstrap/react-bootstrap/pull/6269)
