### ISSUE TITLE
How to disable keyboard navigation for react bootstrap tabs

### ISSUE THREAD

**Issue by ilyasbelfar** [react-bootstrap/react-bootstrap#5955]
## Describing the problem

React bootstrap tabs are working well but I need to disable keyboard navigations between tabs NavLinks with keyboard arrows, I tried tabIndex but didn't work, So how to do that?

**Comment by kyletsang** [comment]
Try using the `onSelect` prop in tabs.  The callback gets passed the keyboard event so you should be able to detect when the user presses the keyboard arrows.

**Comment by ilyasbelfar** [comment]
> Try using the `onSelect` prop in tabs. The callback gets passed the keyboard event so you should be able to detect when the user presses the keyboard arrows.

any example of what you said, please!

**Comment by ilyasbelfar** [comment]
Thank you a lot, I did it right.
`<TabContainer onSelect={(k, ev) => {
              if (ev.type === 'click') {
                setKey(k);
              }
            }}
            activeKey={key}>`
