### ISSUE TITLE
react-bootstrap v0.28.5 - Custom open state for Dropdown component

### ISSUE THREAD

**Issue by ricebun** [react-bootstrap/react-bootstrap#5957]
This is a long shot as I'm aware that my react-bootstrap version is really old! :)

Is there a way to add custom styles for the open state of a Dropdown component? By default, the Dropdown.Toggle background is grey (see the pic below), and I'd like to change it to another color. 
<img width="192" alt="Screenshot 2021-08-03 at 12 44 05 PM" src="https://user-images.githubusercontent.com/65060295/127962811-2e2d331c-86d7-4b2c-9284-cfd635ce6304.png">

I'm using sass for styling my react components and have been able to customise the styles (except that open state) simply with react classNames like below. I see in the source code and in the browser element tree that there is an "open" rootClass, which I am unable to access for customisation. 

Is there any way I can achieve this? Thank you very much!

Component:
```
<Dropdown className={styles.container}>
    <Dropdown.Toggle className={styles.toggle} noCaret>
      <div className={styles.title}>Title</div>
      <div className={styles.placeholder}>Selection</div>
    </Dropdown.Toggle>
    <Dropdown.Menu>
      <MenuItem eventKey="1" onSelect={(key, e) => onSelect(key, e)}>
        Action
      </MenuItem>
      <MenuItem eventKey="2">Another action</MenuItem>
      <MenuItem eventKey="3">Active Item</MenuItem>
    </Dropdown.Menu>
  </Dropdown>

```

styles.scss:
```
.container {
 display: block;
 width: 100%;
 height: 100%;

 .toggle {
  border: none;
  text-align: start;
  width: 100%;
  padding: 0;

 .title {
  font-size: 13px;
  font-weight: 700;
  margin-bottom: 2px;
 }

 .placeholder {
  font-size: 16px;
 }

 &:hover {
  background: #e4e5e9;
 }
}

**Comment by kyletsang** [comment]
Try creating a style for `.toggle.open` in your css
