### ISSUE TITLE
NavDropdown has no menuVariant prop

### ISSUE THREAD

**Issue by jtrenaud1s** [react-bootstrap/react-bootstrap#5963]
## Describe the bug

Using TypeScript, I get an error stating that menuVariant doesn't appear in the props interface for NavDropdown. I'm using a dark navbar and just want the dropdown to be dark as well.

```
Type '{ children: Element[]; title: string; id: string; menuVariant: string; }' is not assignable to type 'IntrinsicAttributes & Omit<Pick<DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>, "key" | keyof HTMLAttributes<...>> & { ...; }, BsPrefixProps<...> & NavDropdownProps> & BsPrefixProps<...> & NavDropdownProps & { ...; }'.
  Property 'menuVariant' does not exist on type 'IntrinsicAttributes & Omit<Pick<DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>, "key" | keyof HTMLAttributes<...>> & { ...; }, BsPrefixProps<...> & NavDropdownProps> & BsPrefixProps<...> & NavDropdownProps & { ...; }'
```

## To Reproduce

Create react app with `--template typescript`

make a navbar with `variant="dark"`

make a NavDropdown and attempt setting `menuVariant="dark"`

ES/TSLint wont like this.

## Expected behavior

The NavDropdown should have the dark themed color.

## Environment (please complete the following information)

- Operating System: Win 10 + WSL
- Browser Version: Chrome 91.0.4472.114
- React-Bootstrap Version: v2.0.0-beta.4 (Bootstrap 5.0)

## Additional context

Using VSCode.

**Comment by kyletsang** [comment]
Can you provide a repro on CodeSandbox?
