### ISSUE TITLE
Module parse failed

### ISSUE THREAD

**Issue by ELopQ** [react-bootstrap/react-bootstrap#5964]
## Describe the bug

After migration from 1.6.1 to 2.0.0-beta.4 when I try to start the project I get the error:
`./node_modules/react-bootstrap/esm/NavbarBrand.js
Module parse failed: Unexpected token (9:2)
You may need an appropriate loader to handle this file type.
|   className,
|   as,
|   ...props
| }, ref) => {
|   bsPrefix = useBootstrapPrefix(bsPrefix, 'navbar-brand');
 @ ./node_modules/react-bootstrap/esm/index.js 46:0-55`

## To Reproduce

After update the react-bootstrap I just run yarn run start and I have this error in the console with all the modules I use in my project.

## Expected behavior

Load the page and modules as it does in the 1.6.1 version.

## Environment (please complete the following information)

- Operating System: macOs
- Browser, Version: Chrome 91
- React-Bootstrap Version 2.0.0-beta.4

## Additional context

Using react V 16.14.0

**Comment by kyletsang** [comment]
Can you provide a repro on CodeSandbox?

**Comment by ELopQ** [comment]
Seem to be related to:
https://github.com/twbs/bootstrap/issues/33472
 the babel and webpack version, tried with a newer version and it works as expected.
