### ISSUE TITLE
<Collapse> component breaks when it has more than one child element

### ISSUE THREAD

**Issue by elohanlon** [react-bootstrap/react-bootstrap#5966]
## Describe the bug

When you put more than one child JSX element inside of a `<Collapse>` component, it results in an error:

```
Cannot read property 'className' of undefined
```

(See code sandbox example in "Reproducible Example" section for full error.)

## To Reproduce

Put more than one element inside of a `<Collapse>`:

```
const show = false;
<Collapse in={show}>
  <div>This is the first element.</div>
  <div>This is the second element.</div>
</Collapse>
```

## Reproducible Example

https://codesandbox.io/s/collapse-error-example-j320i?file=/src/App.js

## Expected behavior

I was expecting the `<Collapse>` to work even if it had two child elements.  The current `<Collapse>` docs say:

```
If you're noticing choppy animations, and the component that's being collapsed has non-zero margin or padding, try wrapping the contents of your `<Collapse>` inside a node with no margin or padding, like the `<div>` in the example below. This will allow the height to be computed properly, so the animation can proceed smoothly.

- https://react-bootstrap.github.io/utilities/transitions/#collapse
```

But that only seems like a recommendation to wrap the inner content with a `<div>` if you want smoother animations due to margin/padding issues, rather than a stated requirement that you must wrap your content with a single element.

## Environment (please complete the following information)

- Operating System: macOS
- Browser, Version: Chrome 92.0.4515.107
- React-Bootstrap Version: 2.0.0-beta.4

## Additional Info

While testing, I found that if you wrap the `<Collapse>` inner content with a single react fragment, that gets rid of the error, but the collapse functionality breaks:

```
const show = false;
<Collapse in={show}>
  <>
    <div>This is the first element.</div>
    <div>This is the second element.</div>
  </>
</Collapse>
```

This may warrant a separate github issue, but here's a code sandbox example: https://codesandbox.io/s/collapse-error-example-with-fragment-5od8x?file=/src/App.js

If you click the button in that example, you'll see that the `<Collapse>` functionality doesn't work.

**Comment by kyletsang** [comment]
All the transitions (Fade/Collapse) require a single react element as the child.  Fragments can't be used

**Comment by elohanlon** [comment]
Thank you for the answer, @kyletsang.  Is that documented somewhere on the react-bootstrap.github.io documentation site and I just missed it?

**Comment by kyletsang** [comment]
Not explicitly, but we should add it into the props table below to make it more clear.  Interested in sending a PR?

**Comment by elohanlon** [comment]
Glad to!

https://github.com/react-bootstrap/react-bootstrap/pull/5970

**Comment by MaxiSantos** [comment]
It also failed for me when I tried to render just `{children}` thinking I was doing ok by just sending one child . It gave me an error related with `ref`. I solved it by sending
`<div> {children} </div>`
