### ISSUE TITLE
Offcanvas is hidden behind modal-backdrop due to z-index, change to use offcanvas-backdrop

### ISSUE THREAD

**Issue by mattywong** [react-bootstrap/react-bootstrap#5967]
## Describe the bug

It looks like there is a new class for offcanvas specific backdrops, which should now be .offcanvas-backdrop instead of .modal-backdrop (https://github.com/twbs/bootstrap/pull/34149).

.modal-backdrop has a higher z-index (1050) than .offcanvas (1045) by default, and so the offcanvas sidebar is hidden behind the backdrop.

## Reproducible Example

https://codesandbox.io/s/friendly-ride-phnkw

## Environment (please complete the following information)

- Operating System: [e.g. macOS]: Windows
- Browser, Version [e.g. Chrome 74]: Chrome
- React-Bootstrap Version [e.g. 1.0.0-beta.8]: v2 beta 4
- Bootstrap Version: 5.1.0
## Additional context

Looks like changing modalPrefix 2nd arg to 'offcanvas' should do the trick @ https://github.com/react-bootstrap/react-bootstrap/blob/master/src/Offcanvas.tsx#L224, happy to create a pr for this.

**Comment by kyletsang** [comment]
Nice catch.  We can drop modal prefix var since it's only used for the modal-open class.

**Comment by nsi319** [comment]
Hi @kyletsang
Can I work on this issue?

**Comment by kyletsang** [comment]
@nsi319 sure go for it.  Thanks!
