### ISSUE TITLE
can't set id of ListGroup

### ISSUE THREAD

**Issue by randrianov** [react-bootstrap/react-bootstrap#597]
React.createElement(ListGroupItem, {id: '1'}) doesn't set 'id' html attr

**Comment by mtscout6** [comment]
@apkiernan Looks like your commit message missed the last piece of information of the change.

**Comment by apkiernan** [comment]
Yeah will clean that up before submitting the PR.

**Comment by mtscout6** [comment]
:+1:

**Comment by apkiernan** [comment]
Closed #601
