### ISSUE TITLE
Tooltip position not updated when tooltip text is updated using a useState hook

### ISSUE THREAD

**Issue by AnimeAllstar** [react-bootstrap/react-bootstrap#5971]
## Description

I tried to create a button that shows a tooltip when hovered over and changes its text once it is clicked. I updated the text using a useState hook and the text changes, but the position of the tooltip fails to update.

## Reproduce

Use the component below to reproduce.

```
import { useState } from "react";
import { Button, Tooltip, OverlayTrigger } from "react-bootstrap";

const CopyButton = () => {
  const [text, setText] = useState("click here to copy the url");

  const renderTooltip = (props) => <Tooltip {...props}>{text}</Tooltip>;

  return (
    <div className="m-5">
      <OverlayTrigger
        placement="top"
        delay={{ show: 200, hide: 100 }}
        overlay={(props) => renderTooltip({ id: "create-tooltip", ...props })}
      >
        <Button
          variant="outline-primary"
          onClick={() => {
            // data gets copied
            setText("copied");
          }}
        >
          Copy url
        </Button>
      </OverlayTrigger>
    </div>
  );
};

export default CopyButton;

```

## Reproducible Example

Minimal example by using [CodeSandbox](https://codesandbox.io/embed/solitary-wave-nerd3).

## Expected behaviour

I believe that when the text changes, the position of the tooltip should be updated using the new length of the tooltip text.

## Screenshots

![Screenshot (6)](https://user-images.githubusercontent.com/39626451/129453132-02233e17-0d5b-4aac-bccf-e0524beb6a16.png)

## Environment

- Windows 11
- Chrome 92
- v2.0.0-beta.4 (Bootstrap 5.0)

**Comment by jquense** [comment]
this is expected, we don't attempt to update position on every render since it's expensive: https://react-bootstrap.github.io/components/overlays/#overlays-dynamic-updates
