### ISSUE TITLE
Failed to compile error

### ISSUE THREAD

**Issue by Lishenga** [react-bootstrap/react-bootstrap#5975]
Am getting this error when i use the React Boostrap
```sh
Failed to compile.

./node_modules/react-bootstrap/esm/SplitButton.js
Module parse failed: Unexpected token (101:2)
You may need an appropriate loader to handle this file type.
|   renderMenuOnMount,
|   rootCloseEvent,
|   ...props
| }, ref) => /*#__PURE__*/_jsxs(Dropdown, {
|   ref: ref,


```

What could be the issue?

- Operating System: macOS
- Browser, Version: Chrome 74
- React-Bootstrap Version: 2.0.0-beta.4

**Comment by kyletsang** [comment]
Probably an issue with your babel config.  Can you provide a minimal repro on codesandbox?

**Comment by irik77587** [comment]
I am facing same issue. I used the following command to CRA
```
npm init react-app myapp --scripts-version 1.1.5
```

    "bootstrap": "^5.1.3",
    "react": "^17.0.2",
    "react-bootstrap": "^2.0.1",
    "react-dom": "^17.0.2",
    "react-icons": "^4.3.1",
    "react-router": "^6.0.2",
    "react-scripts": "1.1.5"

**Comment by kyletsang** [comment]
@irik77587  react scripts 1.x isn't supported.  Can you upgrade to the latest version?
