### ISSUE TITLE
Modal close button improper class name

### ISSUE THREAD

**Issue by kzha0** [react-bootstrap/react-bootstrap#5976]
## Describe the bug
I'm using react-bootstrap 1.6.1 on a component in Storybook. 

I used the Modal component in my code like so:
```
<Modal show={show} onHide={handleClose}>
        <Modal.Header closeButton>
                 <Modal.Title>Modal heading</Modal.Title>
        </Modal.Header>
        <Modal.Body>Woohoo, you're reading this text in a modal!</Modal.Body>
        <Modal.Footer>
                <Button variant="secondary" onClick={handleClose}>
                        Close
                </Button>
                <Button variant="primary" onClick={handleClose}>
                        Save Changes
                </Button>
        </Modal.Footer>
</Modal>
```
When specifying the `closeButton` prop for the Modal Header, the modal displays the button improperly. The modal only renders the close button with the classname `close` which results in the button looking like so:
![image](https://user-images.githubusercontent.com/81629650/129559439-4d25e0f5-d396-41f5-9c0b-1320868689a6.png)

However, when I tried changing the classname to `btn-close` for the button element from the html document itself, the issue seems to partly resolve (albet with the text improperly positioned this time):
![image](https://user-images.githubusercontent.com/81629650/129559847-99d5a0ad-4db8-41f1-91db-cfcf8256efb2.png)

I also checked out the sample modal from the react-bootstrap Docs (where I got the code from) and saw that it renders the button with the classname `btn-close` too. 
```
<div class="modal-header">
        <div class="modal-title h4">Modal heading</div>
        <button type="button" class="btn-close" aria-label="Close"></button>
</div>
```
![image](https://user-images.githubusercontent.com/81629650/129560296-0f818480-546f-49a5-bcfd-d2a703e6350a.png)

This led me to conclude that there might be an issue with the react-bootstrap library's handling of the class name for the modal's close button.

**Comment by kyletsang** [comment]
If you want to use bootstrap 5, you must use react-bootstrap v2 beta.  1.6.1 is only compatible with bootstrap 4

**Comment by ErichBSchulz** [comment]
For others coming here I was still getting this exact error even after `npm install react-bootstrap@next`

I needed to `npm uninstall react-bootstrap` and then `npm install react-bootstrap@next`.

Then it worked!
