### ISSUE TITLE
ToastContainer will not import from 'react-bootstrap/ToastContainer'

### ISSUE THREAD

**Issue by natashagigcasters** [react-bootstrap/react-bootstrap#5978]
## Describe the bug

Cannot import ToastContainer

## To Reproduce

1. npm install react-bootstrap
2. include the following in your app: import ToastContainer from 'react-bootstrap/ToastContainer';
3. Error: Module not found: Can't resolve 'react-bootstrap/ToastContainer'

## Reproducible Example

import react-bootstrap and then try to import ToastContainer

## Expected behavior

You should be able to import and use ToastContainer, but instead, there is an error.
I have been working with the toaster and am able to import: Toast, ToastHeader, and ToastBody normally, 
but not ToastContainer.

## Environment (please complete the following information)

- Operating System: Linux Mint 20.2 Cinnamon
- Browser, Version: Brave 1.28.105 Chromium: 92.0.4515.131 (Official Build) (64-bit)
- React-Bootstrap Version 5

**Comment by kyletsang** [comment]
You need to install react-bootstrap v2 beta.  This is not available in 1.6.1.

**Comment by natashagigcasters** [comment]
Thank you that worked!
