### ISSUE TITLE
Changing Dropdown.Toggle text via onClick in Dropdown.Item

### ISSUE THREAD

**Issue by jlp-io** [react-bootstrap/react-bootstrap#5979]
Is it possible to modify the Dropdown title in Dropdown.Toggle through an onClick function in Dropdown.Item? Has anyone changed the title from an onClick function inside the dropdown menu?

Here is a code sample:

```
`const place = ['First', 'Second'] 

<Dropdown>
  <Dropdown.Toggle variant="light" id="dropdown-basic">
	{place[0]}
</Dropdown.Toggle>
  <Dropdown.Menu>
  	{this.state.candidates[item].map((item_candidate) =>   
    <Dropdown.Item onClick={handleClick()}>{item_candidate}</Dropdown.Item>
    )}
  </Dropdown.Menu>
</Dropdown>`
```

**Comment by johndzilva** [comment]
you can use onSelect() function to capture the dropdown item value and use setState to change the drop down title
