### ISSUE TITLE
Tabs In Modal Lose Formatting

### ISSUE THREAD

**Issue by gtwilliams03** [react-bootstrap/react-bootstrap#5985]
## Describe the bug

Placement of `<Tabs>` in a `<Modal.Body />` lose the tab formatting.

## To Reproduce

Place:

```
<Tabs activeKey={this.state.selectedTab || 'one'} onSelect={_tab => this.setState({ selectedTab: _tab })}>
    <Tab eventKey='one' title='One'><div><p>Tab: One</p></div></Tab>
    <Tab eventKey='two' title='Two'><div><p>Tab: Two</p></div></Tab>
</Tabs>
```

## Reproducible Example

Result in `<Modal />`:

![image](https://user-images.githubusercontent.com/1564628/130115997-50d2b25a-8f7a-4d08-b7e4-889ca712b509.png)

## Expected behavior

Result in body:

![image](https://user-images.githubusercontent.com/1564628/130115878-2efb1263-e299-412e-b549-92265a0c2d16.png)

## Environment (please complete the following information)

- Operating System: Windows 10
- Browser, Chrome Version 92.0.4515.159
- React-Bootstrap Version 2.0.0

**Comment by gtwilliams03** [comment]
This seems to happen because in the body, the `<Tabs>` component renders as:

```
<ul class="nav nav-tabs" role="tablist">
```

but in the `<Modal.Body />`, the `<Tabs>` component renders with the `navbar-nav` class instead of the `nav` class:

```
<ul class="navbar-nav nav-tabs" role="tablist">
```

Have not figured out why this happens yet.

**Comment by kyletsang** [comment]
Guessing your modal code is inside a navbar.

Can you try setting the prop `navbar={false}` in your `Tabs`?

**Comment by gtwilliams03** [comment]
That did the trick.  Thank you!
