### ISSUE TITLE
How to prevent position changing after scroll at OverlayTrigger and Popover?

### ISSUE THREAD

**Issue by rzorzal** [react-bootstrap/react-bootstrap#5986]
I'm trying to avoid re-position of Popover after a scroll. I tried out container props, modifiers props but everytime it is re-positioning. How can I avoid it ?

Sorry if it wasn't the correct place to ask for this kind of help, but I really tried all solutions.

**Comment by kyletsang** [comment]
Are you referring to the popover flipping to the other side when you scroll?
