### ISSUE TITLE
dropdown-menu inside input-group: inaccurate position translation

### ISSUE THREAD

**Issue by noam-g4** [react-bootstrap/react-bootstrap#5988]
## the bug 

Hi, there's a problem with the ```transform: translation()``` of the dropdown-menu inside of an input-group,
when rendered, **its position is inaccurate relative to its ```DropdownButton```**, until a window ```resize``` or ```scroll``` events are being emitted and then it re-renders itself to the correct position.

## To Reproduce

you can see this in the docs themselves by:

1. Go to [input group buttons](https://react-bootstrap.github.io/components/input-group/#input-group-buttons)
2. Scroll down to *buttons with dropdowns*
3. Click on one of the dropdowns
4. See the error

## Screenshots
![bug](https://user-images.githubusercontent.com/61647608/130355595-b37f4da1-1418-42af-9ceb-7445b0cd4dd8.png)

## Environment

- Operating System: Windows 10
- Browser, Version: [Chrome (& Edge) 92, Firefox 88]
- React-Bootstrap Version 2.0.0-beta.5.1

**Comment by kyletsang** [comment]
Looks like this was reported upstream: https://github.com/popperjs/popper-core/issues/1339

This affects dropdowns with `renderOnMount=true`.  We'll need to call `update` on popper to reposition the menu.
