### ISSUE TITLE
How to render a button as React-Router-Link in beta.6

### ISSUE THREAD

**Issue by philipp985** [react-bootstrap/react-bootstrap#6003]
## Describe the bug

Hello,
I updated from beta.4 to beta.6 and my current implementation of router-link buttons is not working anymore.

Before the update I did
```
import * as React from "react";  
import { Badge, Button } from "react-bootstrap";
import { useTranslation } from "react-i18next";
import { Link } from "react-router-dom";
import { CrmRoutePaths } from "../../crmRoutePaths";
 <Button
            variant="outline-secondary"
            className="ml-2"
            as={Link}
            to={CrmRoutePaths.CustomerDetails.replace(":id", "1")}
          >
            <i className="fas fa-angle-left" title={t("Previous")} />
  </Button>
```

After the update I could ignore the error and it will still work
```
   <Button
            variant="outline-secondary"
            //@ts-expect-error
            as={Link}
            to={CrmRoutePaths.CustomerDetails.replace(":id", "1")}
          >
            <i className="fas fa-angle-right" title={t("Next")} />
   </Button>
```

Is this related to this change?
[https://github.com/react-bootstrap/react-bootstrap/commit/73a559ee345bc4033c66fc97858163a6a200126d#diff-9ea0e3c40430fd17705fc6b4399eecbdc8105bc05f169f53d4de480c526a7933](https://github.com/react-bootstrap/react-bootstrap/commit/73a559ee345bc4033c66fc97858163a6a200126d#diff-9ea0e3c40430fd17705fc6b4399eecbdc8105bc05f169f53d4de480c526a7933)

## Expected behavior

Is there any guidance / info on how to overcome the problem?

## Environment (please complete the following information)

- Operating System: Windows 10
- Browser, Version Chrome 92
- React-Bootstrap Version: beta.6

**Comment by kyletsang** [comment]
The way you're doing it is correct.  We'll need a two-part fix here:
1. Update @restart/ui's button hook prop to allow any react component
2. Update react-bootstrap's types to work with custom components

**Comment by philipp985** [comment]
Thanks for the quick reply. Then I will wait for the fix.

**Comment by kyletsang** [comment]
@philipp985 can you try `<Link component={Button}>...</Link>`?

**Comment by philipp985** [comment]
@kyletsang yes, that works. 
Is this considered to be the preferred way in the future?

**Comment by kyletsang** [comment]
@philipp985 yeah, this is preferred because we need to ensure the right props gets attached to the component based on the tag.

**Comment by wKovacs64** [comment]
React Router v6 is removing the `component` prop:

https://github.com/remix-run/react-router/blob/dev/docs/advanced-guides/migrating-5-to-6.md#remove-link-component-prop

And as they mention in the rationale, I still want `<Link>` to render an `<a>` - I just want it to look like a button (and assuming that's what the OP was doing, too). One option may be to fall back to BS classes like `<Link className="btn btn-outline-secondary">`, but then we're sort of circumventing react-bootstrap I guess? Not sure of the consequences here.
