### ISSUE TITLE
Examples in intro documentation need to be updated.

### ISSUE THREAD

**Issue by kickertw** [react-bootstrap/react-bootstrap#6012]
When selecting v2 from the dropdown, the documentation should point to proper examples using bootstrap v5. The **Examples** section in https://react-bootstrap.github.io/getting-started/introduction/ points to https://github.com/react-bootstrap/code-sandbox-examples/blob/master/README.md where some code examples are using old v4 (e.g. - jumbotron) components.

## Solution 🤷‍♂️
Would be nice to either have code examples in folders segregated by react bootstrap or bootstrap versions. Another alternative would be branches dedicated to specific versions

**Comment by kyletsang** [comment]
We can put all the different examples for bs4 and bs5 into master and separate them in the readme.  PRs welcome

**Comment by Radhesh-Sarma** [comment]
@kyletsang I would like to take this up and make a PR

**Comment by kyletsang** [comment]
@Radhesh-Sarma sure go ahead, thanks!

**Comment by lmcdo** [comment]
Has this been done? I am keen to help

**Comment by kyletsang** [comment]
> Has this been done? I am keen to help

v5 examples were added already.  Feel free to pick up any other issue
