### ISSUE TITLE
Tooltip gives me console errors

### ISSUE THREAD

**Issue by multiwebinc** [react-bootstrap/react-bootstrap#6017]
I'm using react-bootstrap 1.6.1 with the Tooltip component. It is functional, however, I get the following error in the console every time the OverlayTrigger is moused over:

> Popper: modifier "popoverArrowMargins" provided an invalid "fn" property, expected "function" but got "undefined" 
    at https://lacolhost.com:3000/static/js/vendors~main.chunk.js:136717:20
    at Overlay (https://lacolhost.com:3000/static/js/vendors~main.chunk.js:131862:22)
    at OverlayTrigger (https://lacolhost.com:3000/static/js/vendors~main.chunk.js:132001:22)
    at PromoDetailsModal (https://lacolhost.com:3000/static/js/main.chunk.js:10961:3)
    at div
    ...

The following code produces the error:

```jsx
import { OverlayTrigger, Tooltip } from 'react-bootstrap';

const PromoDetailsModal = () => {
  const renderTooltip = props => (
    <Tooltip id="button-tooltip" {...props}>
      Price details
    </Tooltip>
  );

  return (
    <OverlayTrigger overlay={renderTooltip}>
      <h1>Hover for price details</h1>
    </OverlayTrigger>
  );
};

export default PromoDetailsModal;
```

Here is my package.json dependencies in case that is relevant:

```json
{
  "dependencies": {
    "@babel/runtime": "^7.12.5",
    "@fortawesome/fontawesome-svg-core": "^1.2.34",
    "@fortawesome/free-brands-svg-icons": "^5.15.2",
    "@fortawesome/free-regular-svg-icons": "^5.15.2",
    "@fortawesome/free-solid-svg-icons": "^5.15.2",
    "@fortawesome/react-fontawesome": "^0.1.14",
    "@paypal/react-paypal-js": "^7.1.0",
    "@reduxjs/toolkit": "^1.5.0",
    "@styled-icons/crypto": "^10.25.0",
    "@testing-library/jest-dom": "^5.11.9",
    "@testing-library/react": "^12.0.0",
    "@testing-library/user-event": "^13.0.6",
    "@vgs/collect-js": "^0.4.0",
    "bootstrap": "^5.0.2",
    "currency-format": "^1.0.13",
    "formik": "^2.2.6",
    "history": "^5.0.0",
    "i18next": "^20.1.0",
    "i18next-browser-languagedetector": "^6.0.1",
    "i18next-http-backend": "^1.0.21",
    "lodash": "^4.17.21",
    "markdown-react-js": "^1.0.2",
    "moment": "^2.29.1",
    "payment-icons": "^1.2.1",
    "react": "^16.1.1",
    "react-animate-height": "^2.0.23",
    "react-bootstrap": "^1.5.0",
    "react-country-flag": "^2.3.0",
    "react-dates": "^21.8.0",
    "react-dom": "^16.1.1",
    "react-i18next": "^11.8.5",
    "react-image-gallery": "^1.0.8",
    "react-modal": "^3.12.1",
    "react-phone-input-2": "^2.13.9",
    "react-redux": "^7.2.2",
    "react-router-dom": "^6.0.0-beta.0",
    "react-scripts": "^4.0.3",
    "react-select": "^4.1.0",
    "react-select-country-list": "^2.2.3",
    "react-social-login": "^3.4.10",
    "react-social-login-buttons": "^3.1.2",
    "react-with-direction": "^1.3.1",
    "styled-components": "^5.2.1",
    "yup": "^0.32.9"
  }
}
```

**Comment by dingedi** [comment]
Same here

**Comment by TheTakylo** [comment]
Popper: modifier "popoverArrowMargins" provided an invalid "fn" property, expected "function" but got "undefined"

**Comment by alanyong91** [comment]
`"react-bootstrap": "^1.6.1"`
`Popper: modifier "popoverArrowMargins" provided an invalid "fn" property, expected "function" but got "undefined"`

```
<Dropdown>
  <Dropdown.Toggle variant="success" id="dropdown-basic">
    Dropdown Button
  </Dropdown.Toggle>

  <Dropdown.Menu>
    <Dropdown.Item href="#/action-1">Action</Dropdown.Item>
    <Dropdown.Item href="#/action-2">Another action</Dropdown.Item>
    <Dropdown.Item href="#/action-3">Something else</Dropdown.Item>
  </Dropdown.Menu>
</Dropdown>
```

I guess the latest changes cause this error. Previously doesn't have this issue.

**Comment by val1984** [comment]
Same issue with Bootstrap 4, definitely not a Bootstrap issue.

**Comment by kyletsang** [comment]
Will be fixed in next release

**Comment by marekdon** [comment]
Is it fixed for react-bootstrap 1.6.1? I cannot change to version 2, is there any fix planed for 1.6.1?

**Comment by EssDevUi** [comment]
Got this error while using popover Don't know what to do ? please fix 
`<div>  <Nav.Item> 

                            <OverlayTrigger trigger="click" placement="bottom" overlay={ 
                                 <Popover id="popover-basic" className="PopoverBoxShadow">
                                 <Popover.Title as="h3" classNAme="py-2">Choose period</Popover.Title>
                                 <Popover.Content>
                                     <div className="py-2">
                                         <DatePicker selected={this.state.startDate} onChange={date => this.setState({startDate:date})} PlaceholderText="Start time" />
                                     </div>
                                     <div className="py-2">
                                         <DatePicker selected={this.state.endDate} onChange={date => this.setState({endDate:date})} PlaceholderText="End time" />  
                                     </div>
                                     <div className="d-flex justify-content-between align-items-center pt-2">
                                         <Button variant="success" onClick={() => this.setState({
                                             updateTablePeriod:true
                                         })}>Filter</Button>
                                         <Button variant="dark" onClick={() => this.setState({
                                             updateTablePeriod:false
                                         })}>Reset</Button>
                                     </div>
                                 </Popover.Content>
                             </Popover> }>
                                <Nav.Link href="#">
                                    <span className="HeaderLinkText">Select period <BsChevronDown className="ml-2"/></span>
                                </Nav.Link>
                                </OverlayTrigger>
                            </Nav.Item>`

using popover like this : 
 **"react-bootstrap": "^1.5.2",    
 "bootstrap": "^4.6.0",**

**Comment by mametur** [comment]
when will the fix release ?
