### ISSUE TITLE
Cols in offset example are not styled

### ISSUE THREAD

**Issue by Swistek92** [react-bootstrap/react-bootstrap#6025]
some code doesn't run here https://react-bootstrap.netlify.app/layout/grid/#row-layout-col-sizing

https://i.postimg.cc/J0yWhFvG/bug.jpg

**Comment by kyletsang** [comment]
Code actually works, but the cols aren't styled with a background color because the docs expect the `col-*` class to be first.

**Comment by kyletsang** [comment]
Easiest fix is to swap `...classes` with `...spans` here:

https://github.com/react-bootstrap/react-bootstrap/blob/d3cae8d59b89fc93aca6639e45477d9ee147624e/src/Col.tsx#L157
