### ISSUE TITLE
ModalHeaderProps wrapper

### ISSUE THREAD

**Issue by bryantabaird** [react-bootstrap/react-bootstrap#6027]
## Describe the bug

Using the ModalHeaderProps in a ModalHeader wrapper is throwing Typescript errors shown in the screenshot.

Tried following a similar example for the Button component [here](https://github.com/react-bootstrap/react-bootstrap/issues/5013#issuecomment-655032884) (which worked correctly) with no luck.

## To Reproduce

This component reproduces the issue.

```
import React from "react";
import ModalHeader, { ModalHeaderProps } from "react-bootstrap/ModalHeader";

export const MyHeader: React.FC<ModalHeaderProps> = ({ ...props }) => {
  return <ModalHeader {...props}>hi</ModalHeader>;
};
```

It can be "remedied" with changing the `ModalHeaderProps` to `any`:

```
import React from "react";
import ModalHeader, { ModalHeaderProps } from "react-bootstrap/ModalHeader";

export const MyHeader: React.FC<any> = ({ ...props }) => {
  return <ModalHeader {...props}>hi</ModalHeader>;
};
```

Or even changing the types in `node_modules/react-bootstrap/esm/ModalHeader.d.ts` to exclude the `React.RefAttributes<HTMLDivElement>`, i.e. changing this:

`declare const ModalHeader: React.ForwardRefExoticComponent<Pick<ModalHeaderProps, "slot" | "style" | "title" | "bsPrefix" | "className" | "key" ... | ... "onHide"> & React.RefAttributes<HTMLDivElement>>;`

to this:

`declare const ModalHeader: React.ForwardRefExoticComponent<Pick<ModalHeaderProps, "slot" | "style" | "title" | "bsPrefix" | "className" | "key" ... | ... "onHide">>;`

## Expected behavior

Can we safely remove the React.RefAttributes<HTMLDivElement> type check in the ModalHeaderProps? Happy to help contribute, just don't know where to make this change.

## Screenshots

![image](https://user-images.githubusercontent.com/9795404/132760435-f34e4f5d-d9f3-454f-aabc-4084ee9c13e4.png)

**Comment by kyletsang** [comment]
Works for me.  What version of react-bootstrap and typescript are you using?  Can you provide a minimal project repro on code sandbox?
