### ISSUE TITLE
alignRight for NavDropdown does not work in browsers

### ISSUE THREAD

**Issue by mgoldenbe** [react-bootstrap/react-bootstrap#6028]
The [linked example](https://codesandbox.io/s/the-overflow-example-cer9p?file=/src/App.js) works fine in the sandbox, but overflows in all the browsers I tried (Opera, Chrome, Firefox). That is, setting `alignRight` for `NavDropdown` does not seem to have any effect in browsers. I am using `bootstrap` 5.1.1 and `react-bootstrap` 1.6.3.

**Comment by mgoldenbe** [comment]
It is about `right:0` not taking effect. Importing my `styles.css` before importing `react-bootstrap`, with the following, fixes the overflow issue:

```
.dropdown-menu {
  right: 0;
}
```

**Comment by kyletsang** [comment]
Bootstrap 5 isn't compatible with react-bootstrap 1.x
https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility

You need to use react-bootstrap v2 beta

then try

`<NavDropdown align="end">`
