### ISSUE TITLE
react-bootstrap 5 deos not work in reactjs 

### ISSUE THREAD

**Issue by Johnsavadkuhi** [react-bootstrap/react-bootstrap#6032]
hello everyone 

react-bootstrap 5 does not work in reactjs please solve this bug or problem :

error : 

Failed to compile
./node_modules/react-bootstrap/esm/SplitButton.js
Module parse failed: Unexpected token (101:2)
You may need an appropriate loader to handle this file type.
|   renderMenuOnMount,
|   rootCloseEvent,
|   ...props
| }, ref) => /*#__PURE__*/_jsxs(Dropdown, {
|   ref: ref,

**Comment by kyletsang** [comment]
Can you provide a minimum reproduction on code sandbox?

**Comment by Johnsavadkuhi** [comment]
yes @kyletsang 
https://codesandbox.io/s/keen-rain-x78fl

**Comment by Johnsavadkuhi** [comment]
it works on codesandbox  but on my laptop it does not work

**Comment by kyletsang** [comment]
Your sandbox doesn't seem to work.  Anyways can you try updating react-scripts?   1.x is very old and doesn't support react 17

**Comment by Johnsavadkuhi** [comment]
yes i did it

**Comment by Johnsavadkuhi** [comment]
thank it solved the problem  i used npm outdated and the i saw react-script is old and new version was available

**Comment by kyletsang** [comment]
Cool glad to hear

**Comment by dnorrstrand** [comment]
I am having the same problem, although my version of react-scripts is  "react-scripts": "^1.1.5". Can you advise on further troubleshooting steps please?

**Comment by kyletsang** [comment]
@dnorrstrand, update `react-scripts` to the latest version

**Comment by dnorrstrand** [comment]
> @dnorrstrand, update `react-scripts` to the latest version

Thanks, it helped!!

**Comment by TamilB** [comment]
@kyletsang I have same issues withe web pack project can you please help me to resolve that one
