### ISSUE TITLE
Improve documentation for Accordion with other components as body

### ISSUE THREAD

**Issue by antondalgren** [react-bootstrap/react-bootstrap#6036]
## Describe the bug
Using the Accordion component with your own component such as 
```jsx
<Accordion>
  {[1,2,3].map((val) => <MyComponent body={val}/>)}
</Accordion>
```
Where `MyComponent` returns an `<Accordion.Item eventKey="Eventkey">...</Accordion.Item>` causes all `<Accordion.Item/>` to be expanded by default.

To have them collapsed by default, I had to add a property to `MyComponent` called `eventKey`. Like this:

```jsx
<Accordion>
  {[1,2,3].map((val) => <MyComponent body={val} eventKey={val}/>)}
</Accordion>
```

<details>
<summary>MyComponent</summary>
```jsx
<Accordion.Item eventKey={props.eventKey}>
  <Accordion.Header>
    test
  </Accordion.Header>
  <Accordion.Body>
   {props.body}
  </Accordion.Body>
</Accordion.Item>
```

</details>

## Environment (please complete the following information)

- Operating System:  macOS
- Browser, Version Chrome 93
- React-Bootstrap Version 2.0.0-beta.6

## Additional context

Add information on the docs site that `eventKey` is required for the closest child component.

**Comment by kyletsang** [comment]
Seems to work here:

https://codesandbox.io/s/youthful-monad-fjqo9?file=/src/App.js

**Comment by antondalgren** [comment]
> Seems to work here:
> 
> https://codesandbox.io/s/youthful-monad-fjqo9?file=/src/App.js

Yeah, my bad.

Thanks
