### ISSUE TITLE
Can I use it within a page that uses bootstrap 3?  [Question] 

### ISSUE THREAD

**Issue by naiteon** [react-bootstrap/react-bootstrap#6038]
Hi, I want to create a react app inside an existing legacy app that relies heavily on bootstrap 3.
Can I use it within another website (is there some sort of encapsulation) or it would be broken?

**Comment by NoahMLoomis** [comment]
To the best of my knowledge, you can't. I tried in the past implementing Bootstrap 3 and nothing worked

If somebody else can confirm this, I'd appreciate this, this was a while ago
