### ISSUE TITLE
How can I make the carousel indicators always visible?

### ISSUE THREAD

**Issue by alexeyshevin** [react-bootstrap/react-bootstrap#6040]
## Is your feature request related to a problem? Please describe

Hi! Is there any way I can make the carousel's indicator area visible even when the carousel has no elements?

**Comment by kyletsang** [comment]
Indicators are generated based on number of child nodes.  You would have to put at least 1 child in order to show the indicators.  Maybe an empty slide?

**Comment by nishant3721** [comment]
@kyletsang Can I work on it?
