### ISSUE TITLE
Modal not closing.

### ISSUE THREAD

**Issue by trickpattyFH20** [react-bootstrap/react-bootstrap#6053]
After upgrading to 2.0.0-beta.6 I’m seeing an issue with modals being stuck on the page after closing.

Our modals now sometimes do not finish closing, the animation stops halfway, and the modal is stuck and not closable anymore.

No console errors are reported.

**Comment by kyletsang** [comment]
Can you share a repro on code sandbox?

**Comment by trickpattyFH20** [comment]
After further debugging, I reproduced this and discovered the issue was using an incompatible version of Bootstrap.
After upgrading from version 4 to 5 this was resolved. Thanks @kyletsang
