### ISSUE TITLE
Modal's fullscreen prop not working

### ISSUE THREAD

**Issue by Selenestica** [react-bootstrap/react-bootstrap#6054]
## Describe the bug

Adding the fullscreen prop to Modal isn't making the Modal go fullscreen.

## Reproducible Example

Minimal example by using [CodeSandbox](https://codesandbox.io/s/dreamy-panka-9ep6b?file=/src/App.js&resolutionWidth=320&resolutionHeight=675).

## Expected behavior

The modal to be fullscreen.

## Screenshots

This is the example on Code Sandbox. It's also not working on my app. In my app I'm using the latest version of the react-bootstrap package. The Code Sandbox example is using 1.5.2.
![Screen Shot 2021-09-22 at 10 20 28 AM](https://user-images.githubusercontent.com/53917177/134373075-ea7692f5-5bf8-48cc-81a9-8e086d6d37dd.png)

## Environment

- Operating System: macOS M1
- Browser, Version: Chrome v94
- React-Bootstrap Version: 1.5.2 on Code Sandbox. 1.6.3 in my app.

## Additional context

I'm confused because the fullscreen prop seems to be working in the example in the docs. You can run a phone emulator in Chrome [here](https://react-bootstrap.github.io/components/modal/#modal-fullscreen) and see it working. 
I don't see any important difference between the code in my app and the docs. Am I missing something? Doing something wrong? Any help would be greatly appreciated!

**Comment by nishant3721** [comment]
@Selenestica Can I work on it?

**Comment by Selenestica** [comment]
@nishant3721 Absolutely!

**Comment by nishant3721** [comment]
@Selenestica Thanks...I'm on it!

**Comment by nishant3721** [comment]
@Selenestica the fullscreen prop is only available in v5.

**Comment by Selenestica** [comment]
@nishant3721  I see. Do I need to install react-bootstrap version 2.0.0 for that?

**Comment by nishant3721** [comment]
@Selenestica do you have any repo regarding this so that I can make a pull request of my code!?

**Comment by Selenestica** [comment]
@nishant3721 Unfortunately the repo I'm working with is private :(
I did try installing the latest version of react-bootstrap, 1.6.3, as well as 2.0.0-rc.0, but it didn't work on either of those.

**Comment by nishant3721** [comment]
@Selenestica check this one!

`
 const [fullscreen, setFullscreen] = useState(true);
  const [show, setShow] = useState(false);

  function handleShow() {
    setFullscreen(true);
    setShow(true);
  }
`

`
 <Button className="me-2" onClick={() => handleShow()}>
        Full screen
      </Button>
      <Modal show={show} fullscreen={fullscreen} onHide={() => setShow(false)}>
        {/* <Modal.Header closeButton> */}
        {/* <Modal.Title>Modal</Modal.Title> */}
        {/* </Modal.Header> */}
        <Modal.Body>Modal body content</Modal.Body>
      </Modal>
`

If that doesn't work. Maybe you can install the latest version!!
just type the command,

npm install react-bootstrap@next bootstrap@5.1.1

**Comment by nishant3721** [comment]
@Selenestica I'm pretty sure it is a version issue.

**Comment by Selenestica** [comment]
@nishant3721 Yes you're right! I got it to work in the sandbox, but not my app. Not sure why it's not working in the app, but I can probably figure it out from here. Thanks!

**Comment by nishant3721** [comment]
@Selenestica Yeah, That's what make me frustrating 😀
