### ISSUE TITLE
Aw Snap! Chromium errors

### ISSUE THREAD

**Issue by mteam88** [react-bootstrap/react-bootstrap#6056]
Trying to access webpages through virtual machine. Running from gitpod. From chromium, many webpages say the cannot be loaded (chrome aw snap error). Is this because the website cannot be accessed like this? How do I solve this?

**Comment by kyletsang** [comment]
Wrong repo?   VMs can access the internet normally.  If you continue seeing issues, check with a forum dedicated to troubleshooting VMs
