### ISSUE TITLE
Fix #5894 changed behaviour of onExited Event handler (and maybe others)

### ISSUE THREAD

**Issue by haeferer** [react-bootstrap/react-bootstrap#6057]
First, this is cool code and runs very well (since years) !

## Describe the bug

Fix #5894 changed behaviour of onExited Event handler (and maybe others)

Before the callback had NO parameters at all, now the DomElement is returned as the first Parameter
(this activated a bug in our software ;) )

Current Version (unexpected)
```
      const handleExit = (node) => {
        removeStaticModalAnimationRef.current?.();
        onExit?.(node);  // <- set the modal node as event parameter
      };
``` 
Old Version (works as documented)
```
const handleExited = (node, ...args) => {
        onExited?.(...args); 
```

## Expected behavior

onExited should deliver NO parameters (or the parameter should be documented)

```
        onExited?.(); 
```

**Comment by haeferer** [comment]
This is the commit introducing the change

https://github.com/react-bootstrap/react-bootstrap/pull/5894/commits/3fbfb0863c6387057dcb0f6ed01f052ff3fb9ea3

**Comment by kyletsang** [comment]
There was a bug in the previous code that wasn't passing node in the args.  The callback is supposed to follow those from react-transition-group

http://reactcommunity.org/react-transition-group/transition/#Transition-prop-onExited

This is working as intended

**Comment by haeferer** [comment]
Understood,

We will change our code 

Thx for your support


Cu 

Andreas
