### ISSUE TITLE
Browser email validation overwrites custom validation

### ISSUE THREAD

**Issue by Inc-Peter** [react-bootstrap/react-bootstrap#6058]
## Describe the bug

If you try to control the validation of a Form.Control with type="email" the browser validation overwrites any attempt
to handle the validation by a custom function.

## To Reproduce

1. Go to the sandbox example below
2. Enter some text eg. "mail"
3. Click go, see the error
4. Change mail input to mail@mail
5. Validation goes green, but it should not, since isEmailValid is always false

## Reproducible Example

Minimal example by using [CodeSandbox](https://codesandbox.io/s/stoic-lamarr-vzu69?file=/src/App.js).

## Expected behavior

I should be able to control the validation of a email input field, so in this example it should never be valid

## Environment (please complete the following information)

- Operating System: Windows 10
- Browser, Version Chrome 93.0.4577.82
- React-Bootstrap Version 1.6.3

**Comment by kyletsang** [comment]
You'll have to remove `required` to avoid using browser validation since you're looking to use custom validation.

Also, there's two props `isValid` and `isInvalid` that will control the styling for the feedback.  In your case since you're using `<Feedback type="invalid">`, you should use the `isInvalid` prop.

**Comment by kyletsang** [comment]
Remove `validated` prop from `Form`.  I believe that's used for client side validation as well

**Comment by Inc-Peter** [comment]
Thanks again.
But this fails to indicate any error to my other input fields that are controlled by the "required" attribute.
I guess I have to choose between making all my input fields controlled or using basic browser validation then?
Updated sandbox:https://codesandbox.io/s/affectionate-sky-bfdyg?file=/src/App.js
