### ISSUE TITLE
`FormCheck` vs `Form.Check`

### ISSUE THREAD

**Issue by OfirD1** [react-bootstrap/react-bootstrap#6061]
What's the difference between `FormCheck` vs. `Form.Check` components?

I see that the documentation of [Checkboxes and Radios](https://react-bootstrap.github.io/components/forms/#forms-form-check) refers to `FormCheck` on the textual parts, but has `Form.Check` on the code snippets. Why is that?

[For example](https://react-bootstrap.github.io/components/forms/#forms-check-without-labels):

>## Without labels
>When you render a `FormCheck` without a label (no `children`) some additional styling is applied to keep the inputs from collapsing. **Remember to add an `aria-label` when omitting labels!**
>```javascript
> <>
>  <Form.Check aria-label="option 1" />
>  <Form.Check type="radio" aria-label="radio 1" />
> </>
>```

**Comment by kyletsang** [comment]
No difference.  `Form` exports `Check` along with other form components for convenience

https://github.com/react-bootstrap/react-bootstrap/blob/0bb7b428250e4a587f753e8a81e8d7721d789811/src/Form.tsx#L64-L74
