### ISSUE TITLE
Form.Select does not exist

### ISSUE THREAD

**Issue by iiLearner** [react-bootstrap/react-bootstrap#6062]
## Describe the bug

Form.Select does not exist while its on documentation page: 
https://react-bootstrap.github.io/components/forms/#forms-select

## To Reproduce

https://react-bootstrap.github.io/components/forms/#forms-select

## Expected behavior

Form.Select to exist

## Environment (please complete the following information)

- Operating System: [Windows 10]
- Browser, Version [Chrome latest]
- React-Bootstrap Version [1.6.4]

**Comment by aksdevac** [comment]
@iiLearner Hi, its not a bug you are checking v5 (currently a rc version with bootstrap 5 support) documentation, & you have mentioned 1.6.4 version in issue, check this for old v4 doc:
https://react-bootstrap-v4.netlify.app/components/forms/#forms-custom-select

**Comment by iiLearner** [comment]
Hi, @aksdevac, thanks for the clarification however i checked npm and thats the latest version of react bootstrap i found. do i have to download it elsewhere ?

**Comment by kyletsang** [comment]
@iiLearner 

v2 is published as a pre-release on npm.  You can install via `npm install react-bootstrap@next`
