### ISSUE TITLE
Show alignRight as available prop in the Docs

### ISSUE THREAD

**Issue by vanhaaggen** [react-bootstrap/react-bootstrap#6065]
First, much respect for you guys and this amazing projects.

## Is your feature request related to a problem? Please describe

No

## Describe the solution you'd like

Add description of **alignRight** prop into the Dropdown section of the [Docs](https://react-bootstrap.github.io/components/dropdowns/#dropdown-props).

## Describe alternatives you've considered

Adding the description in the Dropdown section or in any section the **alignRight** prop is applicable

**Comment by kyletsang** [comment]
`alignRight` has been removed in 2.0.   See https://react-bootstrap.github.io/migrating/#dropdown
