### ISSUE TITLE
Use variant or respect btn-class on Dropdown.Item

### ISSUE THREAD

**Issue by Lirt** [react-bootstrap/react-bootstrap#6066]
## Describe the bug

It is not possible to use `variant="danger"` in Dropdown.Item (which can act like a button using `as=button`) or to use class `className="btn-danger"` on `Dropdown.Item`, because it is in the end overriden by `.dropdown-item`.

## To Reproduce

In example such as below, in either case if `Dropdown.Item` is used as `<a>` or `<button>` the style in class `btn-danger` is always overriden by `.dropdown-item`. I cannot find a way to make the button to be in `danger` styling.

```jsx
<Dropdown>
  <Dropdown.Toggle id="action-dropdown">
    Pick Action
  </Dropdown.Toggle>
  <Dropdown.Menu>
    <Dropdown.Item className="btn-primary">Update</Dropdown.Item>
    <Dropdown.Item as="button" className="btn-danger">Delete</Dropdown.Item>
  </Dropdown.Menu>
</Dropdown>
```

## Reproducible Example

https://codesandbox.io/s/inspiring-hill-6mq3z

## Expected behavior

There is way to use `danger` or other styles on Dropdown Items.

## Environment (please complete the following information)

- Operating System: Fedora 32
- Browser: Chrome 94.0.4606.61
- React-Bootstrap Version master (code-sandbox)

**Comment by kyletsang** [comment]
You'll need to define your own class here with `!important`, because the dropdown item does have a transparent background color.
