### ISSUE TITLE
Unable to create more than one <Tabs> component.

### ISSUE THREAD

**Issue by risoms** [react-bootstrap/react-bootstrap#6067]
## Describe the bug

When attempting to create two sets of tab components, tabs are controlled across components.

## To Reproduce

To reproduce this, simply attempt to recreate two tab components.
```js
    handleTabSelect(key) {
        this.setState({
            ...this.state,
            tabIdx: key,
        });
    }
    render() {
    <Col md={12}>
        <Tabs className="colorTabs"
              activeKey={this.state.tabIdx}
              onSelect={this.handleTabSelect.bind(this)}
              id="tab1">
            <Tab eventKey={1}>
                <TabContent1 />
            </Tab>
            <Tab eventKey={2}>
                <TabContent2 />
            </Tab>
        </Tabs>
    </Col>
    <Col md={12}>
        <Tabs className="colorTabs"
              activeKey={this.state.tabIdx}
              onSelect={this.handleTabSelect.bind(this)}
              id="tab2">
            <Tab eventKey={1}>
                <TabContent3 />
            </Tab>
            <Tab eventKey={2}>
                <TabContent4 />
            </Tab>
        </Tabs>
    </Col>
    }
```

## Reproducible Example

Minimal example by using [CodeSandbox](https://codesandbox.io/s/github/react-bootstrap/code-sandbox-examples/tree/master/basic).

## Expected behavior

Tabs in a separate component should not be modified, when selecting active tabs.

## Environment (please complete the following information)

- Operating System: macOS
- Browser, Version: Chrome, 93.0.4577.82
- React-Bootstrap Version: 1.0.0

**Comment by kyletsang** [comment]
You are using the same `tabIdx` state to control both tabs.  You need to use a different var for your second tab.
