### ISSUE TITLE
PropTypes of wrapped uncontrollable components to not bubble up

### ISSUE THREAD

**Issue by ericvergnaud** [react-bootstrap/react-bootstrap#6070]
## Describe the bug

PropTypes such as componentClass property of DropdownButton are not visible.
This prevents development tools from doing their job. 

## To Reproduce

1. Go to https://react-bootstrap-v3.netlify.app/components/dropdowns/
2. Scroll down to page bottom
3. 'componentClass' is not in the list of DropdownButton props

## Expected behavior

Since componentClass is a valid PropType inherited from Dropdown, it should show.

## Additional context

It seems the issue relates to the use of uncontrollable.js, which only bubbles up designated PropTypes
Not sure if the fix should take place in uncontrollable.js itself or in its usage.

**Comment by kyletsang** [comment]
Closing since BS3 is no longer supported
