### ISSUE TITLE
Could not find module in path: 'react-bootstrap/Placeholder'

### ISSUE THREAD

**Issue by dkdkwizard** [react-bootstrap/react-bootstrap#6074]
## Describe the bug

Unable to import 'react-bootstrap/Placeholder'

## To Reproduce

1. Simply `import Placeholder from 'react-bootstrap/Placeholder';`

## Reproducible Example

Minimal example by using [CodeSandbox](https://codesandbox.io/s/react-bootstrap-placeholder-issue-jxs7x?file=/src/App.js).

## Environment (please complete the following information)

- Operating System: macOS
- Browser, Version Chrome 94
- React-Bootstrap Version 1.6.4

**Comment by kyletsang** [comment]
You need to use react-bootstrap v2.
