### ISSUE TITLE
Module not found 'react-bootstrap/AccordionButton'

### ISSUE THREAD

**Issue by SiddharthMollaTech** [react-bootstrap/react-bootstrap#6079]
I'm trying to use 'useAccordionButton' hook in React for custom toggle 
but i'm getting ---> Module not found: Can't resolve 'react-bootstrap/AccordionButton'
i'm importing this way ---> import { useAccordionButton } from 'react-bootstrap/AccordionButton';

version is "react-bootstrap": "^1.6.4",

**Comment by kyletsang** [comment]
You need to use react-bootstrap v2, not v1
