### ISSUE TITLE
[Docs?] Toasts - ability to populate and autohide a queue

### ISSUE THREAD

**Issue by peterdutton** [react-bootstrap/react-bootstrap#6098]
I want to be able to write a message to an array, have it displayed in a toast, and then remove it from the array. (I am running version 2.0.0-beta.4.)

I've written some code to do this but it isn't behaving as I had hoped:

```
const [toastMessages, setToastMessages] = useState([{messageText: "Hello from toast", messageDate: "Just now", messageType: "info"}])

function clearToastMessage() {
    console.log('in clearToastMessage');
    // remove the first item in the array
    //
    var tmpToastMessages = toastMessages
    tmpToastMessages.shift()
    setToastMessages(tmpToastMessages)
}
```

Then in my render I have:
```
<ToastContainer>
    {toastMessages.map((item, index) =>
        <Toast key={index} autohide={true} onClose={clearToastMessage}>
            <Toast.Header>
                <span>
                    <small>{item.messageDate}</small>
                </span>
            </Toast.Header>
            <Toast.Body>{item.messageText}</Toast.Body>
        </Toast>
    )}
</ToastContainer>
```

The toast message displays fine, but doesn't autohide. I thought this must be a common use case (i.e. a 'queue' of toasts to push messages to) and thought it could potentially go in the docs? Let me know if you think it's better asked on SO though. Thanks for your help!

**Comment by willd-i2o** [comment]
A custom react hook can provide this functionality quite nicely
