### ISSUE TITLE
[v2.0.0] Button as React Router Dom (v5) Link/NavLink?

### ISSUE THREAD

**Issue by XzaR90** [react-bootstrap/react-bootstrap#6103]
## Describe the bug

I get typescript errors when trying to use Button as Link, there is a closed issue but it does not solve it, #6003.

## To Reproduce

```javascript
        <Link
            to={RouteConstant.accountSettings}
            component={
                <Button variant="primary" className="mb-2">
                    Edit Account
                </Button>
            }
        ></Link>
        
          <Button
              as={NavLink}
              variant="primary"
              className="mb-2 mt-3"
              to={RouteConstant.character}
          >
              My Character
          </Button>
```
And this only work in v6 which is in beta I think.
```javascript
import { FancyPantsLink } from "@fancy-pants/design-system";
import {
  useHref,
  useLinkClickHandler
} from "react-router-dom";

const Link = React.forwardRef(
  (
    {
      onClick,
      replace = false,
      state,
      target,
      to,
      ...rest
    },
    ref
  ) => {
    let href = useHref(to);
    let handleClick = useLinkClickHandler(to, {
      replace,
      state,
      target
    });

    return (
      <FancyPantsLink
        {...rest}
        href={href}
        onClick={event => {
          onClick?.(event);
          if (!event.defaultPrevented) {
            handleClick(event);
          }
        }}
        ref={ref}
        target={target}
      />
    );
  }
);
```

## Expected behavior

A Button as Link/NavLink

## Environment (please complete the following information)
- React-Bootstrap Version [2.0.0]
- React Router 5.3.0

**Comment by XzaR90** [comment]
Well from the solution you mentioned, the variant prop is invalid as it does not exist for the Link at least when using Typescript.

**Comment by kyletsang** [comment]
Looks like there's a bug with `react-router-dom` types.  Link should accept custom props for the component:

https://github.com/remix-run/react-router/blob/78249eb6ce9a28df4691cc61caa0467fed8b7ac0/packages/react-router-dom/modules/Link.js#L100

**Comment by davidebriani** [comment]
It seems the `as` prop of `react-bootstrap/Button` is wrongly typed as `(ElementType<any> & keyof IntrinsicElements) | undefined`.
I reckon the `keyof IntrinsicElements` type comes from '@restart/ui/Button', but this should be added with an union `|` to `ElementType<any>` instead of with `&`.

**Comment by alachaum** [comment]
`react-router-dom` v6 has dropped support for the `component` attribute.

The following works but is not pretty:
```ts
<Button as={Link as any} to={somePath}>
    My Character
</Button>
```

**Comment by martdavidson** [comment]
Yeah this has cost me a bunch of time tonight, glad to find this issue, anyone have updates that aren't an `any` hack?

**Comment by davidebriani** [comment]
@martdavidson I'm afraid we can only replace the type, still better than typing with `any` though:
```tsx
import { ComponentProps } from "react";
import RBButton from "react-bootstrap/Button";

type RBButtonProps = ComponentProps<typeof RBButton>;

type Props = Omit<RBButtonProps, "as"> & {
  as?: "button" | "a" | React.ElementType;
};

const Button = (props: Props) => (
  // @ts-expect-error wrong types
  <RBButton {...props} />
);

export default Button;
```

**Comment by kyletsang** [comment]
See following for examples using React Router v5 and v6:
https://codesandbox.io/s/github/react-bootstrap/code-sandbox-examples/tree/master/ts-react-router-v5
https://codesandbox.io/s/github/react-bootstrap/code-sandbox-examples/tree/master/ts-react-router-v6
