### ISSUE TITLE
Replace 'manual' trigger from OverlayTrigger

### ISSUE THREAD

**Issue by aaronpowell** [react-bootstrap/react-bootstrap#611]
If I set the `trigger` of an `OverlayTrigger` to be `manual` there is no way which I can manually show a popover that is associated with it.

Scenario - I want to show popovers when the user clicks an icon and when validation fails on a page.

**Comment by mtscout6** [comment]
I'd need time to figure out what `manual` is even supposed to allow.

@DJCordhose can you shed any more light aside from refs on what this does? Original PR #221.

**Comment by DJCordhose** [comment]
Manual mode is a way to make a modal shown by calling its API, Like described here herehttp://getbootstrap.com/javascript/

So if you want to show the modal in manual mode you have to call its API. Like 
.modal('show')

**Comment by DJCordhose** [comment]
Right, you just make that call to the jQuery element when validation fails e.g..

**Comment by mtscout6** [comment]
Ok, well that support will likely get removed at some point then in favor of a prop that can manually trigger the modal open and closed. The goal is to not be using Bootstrap's JavaScript in favor of a pure React solution.

**Comment by DJCordhose** [comment]
Agreed, would have proposed something like that. If I had any idea how to get that done with pure react. Do you have  a vision how to do it?

**Comment by mtscout6** [comment]
@DJCordhose I'm pretty sure it would have to do something with this line: https://github.com/react-bootstrap/react-bootstrap/blob/v0.21.2/src/ModalTrigger.js#L38

Basically do a check for some prop value to determine if the modal is visible. If not than defer to the state value.

**Comment by taion** [comment]
We should put this at the level of `OverlayMixin` and use the same logic to drive manual control of `OverlayTrigger` and `ModalTrigger`.

**Comment by jquense** [comment]
https://github.com/react-bootstrap/react-bootstrap/pull/855 removes manual, and lets you manage Overlay state directly, which should address this.
