### ISSUE TITLE
Docs use import Form from "bootstrap-react/Form" instead of import {CheckForm} from "bootstrap-react"

### ISSUE THREAD

**Issue by jaafit** [react-bootstrap/react-bootstrap#6112]
https://react-bootstrap.github.io/components/forms/#form-check-props

The import statement suggested does not work with the latest version.  Instead it's import {FormCheck} from 'react-bootstrap';

**Comment by kyletsang** [comment]
That import is referenced in the doc so you can use `Form.Check` instead of `FormCheck`.  They're the same, it just comes down to preference on how to use it.
