### ISSUE TITLE
Focus on modal dialogs

### ISSUE THREAD

**Issue by ewal** [react-bootstrap/react-bootstrap#612]
It's not currently possible to set the focus on the modal dialog (in an easy way) after it has been opened making it keyboard unfriendly. In Bootstrap, the outer modal container automatically gets focus when opened.

**Comment by mtscout6** [comment]
@ewal We'd love a PR to make that work. It is along the lines of what's needed for Accessibility concerns as per our [1.0.0 Roadmap](https://github.com/react-bootstrap/react-bootstrap/wiki#100-roadmap).

**Comment by AlexKVal** [comment]
Solved by #690
