### ISSUE TITLE
Popover not stay with click element on scroll container 

### ISSUE THREAD

**Issue by madebymt** [react-bootstrap/react-bootstrap#6120]
## Describe the bug

I recreate popover in the [codesandbox](https://codesandbox.io/s/sweet-grothendieck-bwoqu?file=/src/App.js) here, follow the[ documentation code](https://react-bootstrap-v3.netlify.app/components/popovers/#popovers-in-container), the popover show up, but after scroll, the pointer does not align with the button anymore, I tried to pass `container` prop, but still not working. How can I solve this? Thank you.

## To Reproduce

1. Click the button
2. Popover show up
3. Scroll in the container
4. Popover follows the scrolling event instead of element.

![Screen Shot 2021-11-06 at 10 42 56 PM](https://user-images.githubusercontent.com/26178313/140632872-a0915a69-f45a-4ede-9521-456c44f8eb0c.png)

## Reproducible Example

https://codesandbox.io/s/sweet-grothendieck-bwoqu?file=/src/App.js

## Expected behavior
A popover should stay with a button element instead of scrolling container.

![Screen Shot 2021-11-06 at 10 33 06 PM](https://user-images.githubusercontent.com/26178313/140632877-7d503d23-d5f5-4428-8c03-22ae353c26ca.png)
## Environment (please complete the following information)

- Operating System: Catalina 10.15.7 
- Browser, Version  chrome Version 95.0.4638.54 (
- React-Bootstrap Version 0.33.1 (Same frome the documentatiion)

**Comment by kyletsang** [comment]
Bootstrap 3 is not supported anymore.  Would you be able to update to bootstrap 4 or 5?

**Comment by madebymt** [comment]
Can I get a ref from this component? Thanks

**Comment by kyletsang** [comment]
Don't think the bootstrap 3 components passes refs to elements.

**Comment by kyletsang** [comment]
Closing since we no longer support BS3
