### ISSUE TITLE
Black overlay showing up on top of the Offcanvas 

### ISSUE THREAD

**Issue by keyman500** [react-bootstrap/react-bootstrap#6122]
## Describe the bug
In my app an Offcanvas is used to give the user some instructions when the page loads sometimes there is a black overlay that shouldn't be there over the Offcanvas it is removed after clicking anywhere on the screen.

## To Reproduce

1. Trigger Offcanvas using useEffect once at the start of the app

## Screenshots

![MicrosoftTeams-image (5)](https://user-images.githubusercontent.com/60365043/140995977-271514d2-d7b8-46c3-8c09-347da530c89f.png)

## Environment (please complete the following information)

- Operating System: Windows 10
- Chrome, Version 95.0.4638.69 (Official Build) (64-bit)
- React-Bootstrap version: v2.0.2
- bootstrap version 5.1.3

**Comment by kyletsang** [comment]
Are you running the latest version of bootstrap 5?   There was a breaking change in a class they introduced somewhere in 5.0.x.  Updating to the latest should fix this.

**Comment by keyman500** [comment]
Yes i'm using version 5.1.3 of bootstrap

**Comment by kyletsang** [comment]
Can you post a minimum repro on code sandbox?
