### ISSUE TITLE
cannot import react-bootstrap in version 2.0.2

### ISSUE THREAD

**Issue by GregLoring** [react-bootstrap/react-bootstrap#6123]
## Describe the bug

Code + error pair #1
`import foo from 'react-bootstrapt'` produces `Attempted import error: 'react-bootstrap' does not contain a default export`

Code + error pair #2
`import Jumbotron from 'react-bootstrap/Jumbotron';` produces `Module not found: Can't resolve 'react-bootstrap/Jumbotron' in '/home/greg/my-react-bootstrap-2-app/src' `

Code + error pair #3
`import { Jumbotron, Container, Button, Alert } from 'react-bootstrap';` produces `Attempted import error: 'Jumbotron' is not exported from 'react-bootstrap'.`

## To Reproduce

1. replace `"bootstrap": "^4.6.0", "react-bootstrap": "^1.5.2",` with `"bootstrap": "^5.1.3", "react-bootstrap": "^2.0.2",` in package.json
2. `rm -rf node_modules/ package-lock.json`
3. `npm i`
4. `npm start`
5. see compile error like "ModuleNotFoundError: Could not find module in path: 'react-bootstrap/Jumbotron' relative to '/src/App.js'"

## Reproducible Example

Minimal example by using [CodeSandbox](https://codesandbox.io/s/github/react-bootstrap/code-sandbox-examples/tree/master/basic).

Simply replace
```
    "bootstrap": "^4.6.0",
    "react-bootstrap": "^1.5.2",
```
with
```
    "bootstrap": "^5.1.3",
    "react-bootstrap": "^2.0.2",
```
in the package.json, and you'll get
```
ModuleNotFoundError
Could not find module in path: 'react-bootstrap/Jumbotron' relative to '/src/App.js'
```
on https://codesandbox.io/.

## Expected behavior

`import Jumbotron from 'react-bootstrap/Jumbotron'` should work in v 2.0.2

## Environment (please complete the following information)

- Operating System: [Ubuntu on WSL2 in Windows 10]
- Browser, Version [Microsoft Edge Version 95.0.1020.44 (Official build) (64-bit)]
- React-Bootstrap Version [2.0.2]

## Additional context

  I got the same message running locally with each node lts from dubnium (v10) thru gallium (v16)

**Comment by GregLoring** [comment]
My apologies.  I was using the v4 CodeSandbox example.  The `basic-v5` example works just fine.

**Comment by Pragalbhmandaokar** [comment]
Facing the same issue within react-bootstrap: "^2.3.1". Any suggestions?
