### ISSUE TITLE
Property Item does not exist on type Accordion

### ISSUE THREAD

**Issue by jerbear1235** [react-bootstrap/react-bootstrap#6127]
## Describe the bug

When importing the Accordion component as mentioned in the [wiki](https://react-bootstrap.github.io/components/accordion/),
and using the `Accordion.Item` component listed there, I get the error message `Property Item does not exist on type, Accordion`.

Looking at the react-bootstrap folder in node_modules, it looks like there is an exported component called `AccordionItem`, but it is not imported/exported in the default Accordion.js file.

## To Reproduce
1. Install react with `npx create-react-app app --template typescript`
package.json
    "bootstrap": "^4.6.0",
     "react": "^17.0.2",
    "react-bootstrap": "^1.5.2",
    "react-dnd": "^14.0.2",
    "react-dnd-html5-backend": "^14.0.0",
    "react-dom": "^17.0.2",
    "react-router-dom": "^5.2.0",
    "react-scripts": "^4.0.3",

## Reproducible Example
Import Accordion in a file and try to use the `Accordion.Item` component.

## Expected behavior

Your editor / compiler will say Item does not exist.

## Environment (please complete the following information)

- Operating System: macOS
- Browser, Version: N/A
- React-Bootstrap Version 1.5.2

**Comment by kyletsang** [comment]
The docs site you're referencing is for react-bootstrap v2 and bootstrap 5.

See https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility
