### ISSUE TITLE
Remove iosClickHack() from Modal

### ISSUE THREAD

**Issue by AlexKVal** [react-bootstrap/react-bootstrap#613]
iosClickHack()
https://github.com/react-bootstrap/react-bootstrap/blob/master/src/Modal.js#L125
I've checked all related info and patches facebook/react#1169.
I've found out that the patch fixing this problem is not present in v0.13.2 yet. 

But it already is in v0.14-alpha and I've checked that alpha with deleted iosClickHack().
All works fine. Therefore it is only a matter of time when we can remove that hack.

**Comment by taion** [comment]
Fixed by #1153.
