### ISSUE TITLE
OverlayTrigger warnings 

### ISSUE THREAD

**Issue by alexander-gvozd** [react-bootstrap/react-bootstrap#6130]
Pay attention on this problem again.
https://github.com/react-bootstrap/react-bootstrap/issues/5776#issue-864780078

This warnings is not phpstorm problem but bootstrap typescript declaration problem. Can you do something with this?

**Comment by golota60** [comment]
Hi! Could you say why do you think this is different than [this bug in webstorm](https://youtrack.jetbrains.com/issue/WEB-48161) or [this](https://youtrack.jetbrains.com/issue/WEB-40641). Seems like it's a reoccuring issue with WebStorm, but I'm happy to be proven otherwise
