### ISSUE TITLE
Modal closeButton dosen't work on newer versions (v2.0.2)

### ISSUE THREAD

**Issue by BaharYilmaz** [react-bootstrap/react-bootstrap#6133]
## Describe the bug

When I upgrade react-bootstrap to version v2.0.0 or above, closeButton icon look broken in modal header.

## To Reproduce

1. Upgrade react-bootstrap to v2.0.2
2. Restart project
3. Open modal in project
3. See broken close icon in modal header

## Reproducible Example

```
   <Modal
      show={show}
      onHide={onHide}
      aria-labelledby="example-modal-sizes-title-lg"
    >
      <Modal.Header closeButton>
        <Modal.Title id="example-modal-sizes-title-lg">
          Title
        </Modal.Title>
      </Modal.Header>
      <Modal.Body>
        Body
      </Modal.Body>
</Modal>
```

## Screenshots

v2.0.2
<img width="507" alt="Ekran Resmi 2021-11-23 09 34 41" src="https://user-images.githubusercontent.com/48556212/142980224-3d20050f-ea94-43fd-879b-36753c1bbe93.png">

v.1.6.4
<img width="505" alt="Ekran Resmi 2021-11-23 09 34 27" src="https://user-images.githubusercontent.com/48556212/142980222-2daad844-d093-47e1-bb2f-b488f31c9c3f.png">

## Environment

- Operating System: [e.g. macOS]
- Browser, Version [e.g. 96.0.4664.55 ]
- React-Bootstrap Version [e.g. 2.0.2]

## Additional context

When I downgrade react-bootstrap version to v1.6.4 close icon look good in modal.

**Comment by Tejas-Teju** [comment]
I would like to work on this issue please assign it to me, I am new to open source so if anyone can guide me I would be more than happy to contribute

**Comment by kyletsang** [comment]
You need to update bootstrap to v5 if you want to use react-bootstrap v2.  See https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility

**Comment by kyletsang** [comment]
@uragecz can you post a minimal reproducible demo on codesandbox?

**Comment by dr-aiuta** [comment]
I've made the same mixing versions mistake. But here is a quick dirty solution with css @BaharYilmaz :

.```
modal-header .btn-close::before {
  content: "\00D7"; /* Unicode for the multiplication sign (×) */
}
```
