### ISSUE TITLE
Using a dynamic value for the animation property in Modal leaves webpage unusable

### ISSUE THREAD

**Issue by jpCobalt** [react-bootstrap/react-bootstrap#6134]
### Prerequisites

- [X] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [X] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug

Opening a Modal with animation set to false then closing it afterwards with animation set to true causes it to leave an element (`<div class="fade modal-backdrop"></div>`) on the page that makes the webpage unusable (unless you know how to delete the element).

### Expected behavior

When you close a modal regardless of whether animation is set to true or false beforehand or afterwards, it should allow the user to interact with the application/webpage normally afterwards

### To Reproduce

Have a dynamic value set on animation. In my case, we wanted it to have no animation on mobile width (<768) and to have an animation when it goes into desktop width (>=768). Opening it on mobile width then closing on desktop width led me to this

### Reproducible Example

Codesandbox: https://codesandbox.io/s/focused-swanson-ucww3?file=/src/App.js

1. Resize to mobile (< 768)
2. Open modal by clicking button
3. Resize to desktop (>= 768)
4. You shouldn't be able to interact with the button anymore due to leftover <div class="fade modal-backdrop"></div> element

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of React-Bootstrap are you using?

1.6.1

### What version of Bootstrap are you using?

4.6.0

**Comment by kyletsang** [comment]
Your `animation` prop here won't change when you resize your window to desktop.  You would need to implement a resize handler in order to capture changes in the window width, then set that into a state variable so your modal would re-render.
