### ISSUE TITLE
Got error "Uncaught TypeError: (0 , jsx_dev_runtime.jsxDEV) is not a function" with development version

### ISSUE THREAD

**Issue by stonezhong** [react-bootstrap/react-bootstrap#6135]
### Prerequisites

- [x] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [X] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug

With the html below

I got javascript error "react-bootstrap.js:5147 Uncaught TypeError: (0 , jsx_dev_runtime.jsxDEV) is not a function" in Chrome inspect window when using development version.

### Expected behavior

No javascript error.

### To Reproduce

1. Create a html file and put it on a web server. The HTML looks like below:
```html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewpoint" content="with=device, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Test</title>

    <link rel="stylesheet" href="https://unpkg.com/bootstrap@5.1.3/dist/css/bootstrap.css">
    <script src="https://unpkg.com/react/umd/react.development.js" crossorigin></script>
    <script src="https://unpkg.com/react-dom/umd/react-dom.development.js" crossorigin></script>
    <script src="https://unpkg.com/react-bootstrap@2.0.0/dist/react-bootstrap.js" crossorigin></script>
</head>

<body>
    <div id='app'></div>
</body>
</html>
```

2. Browse it using Google Chrome (I am using version: 96.0.4664.45 (Official Build) (64-bit)), open "inspect" window
3. You see error "react-bootstrap.js:5147 Uncaught TypeError: (0 , jsx_dev_runtime.jsxDEV) is not a function"
![Screenshot from 2021-11-25 05-47-17](https://user-images.githubusercontent.com/6948506/143452874-d743d269-e109-4164-9762-fc2258a0bed3.png)

### Reproducible Example

With the sample html, it is very easy to reproduce.

### Screenshots

![Screenshot from 2021-11-25 05-47-17](https://user-images.githubusercontent.com/6948506/143452948-61128452-0e6b-4724-a337-56daaf8543a6.png)

### What operating system(s) are you seeing the problem on?

Linux

### What browser(s) are you seeing the problem on?

Chrome

### What version of React-Bootstrap are you using?

2.0.0 (same error with 2.0.2)

### What version of Bootstrap are you using?

5.1.3

**Comment by golota60** [comment]
Seems like it's a babel issue. In the meantime you can replace 
```html
<script src="https://unpkg.com/react-bootstrap@2.0.0/dist/react-bootstrap.js" crossorigin></script>
```
 with the minified version
 ```html
<script src="https://unpkg.com/react-bootstrap@2.0.0/dist/react-bootstrap.min.js" crossorigin></script>
 ```

**Comment by stonezhong** [comment]
Yeah, minified version looks good

**Comment by jmfrancois** [comment]
still true, I reproduce this with https://unpkg.com/react-bootstrap@2.2.1/dist/react-bootstrap.min.js

**Comment by sumanth-chippagiri** [comment]
Thank you @golota60 . minified version saved me
