### ISSUE TITLE
Resizing component?

### ISSUE THREAD

**Issue by vymao** [react-bootstrap/react-bootstrap#6138]
Hello, 

I am trying to style a simple web page using react-bootstrap. I added some components (a `Form` and a `Button`), but currently they are sized too wide: 
```
    <div id='Main'>
        {this.state.statusElement}
        <Form.Group controlId="formFile" className="mb-3" onChange={this.onFileChange.bind(this)} required>
            <Form.Label>Test Data</Form.Label>
            <Form.Control type="file" />
        </Form.Group>
        <Button variant="outline-primary" onClick={this.onSubmit.bind(this)} >Upload</Button>{' '}
    </div>
```
![image](https://user-images.githubusercontent.com/18024303/143798086-84e5dffd-463c-467f-a9f3-68be07906563.png)

I would like to shrink these components (primarily shorten the width), but I'm not sure how. Is there a recommended way?

**Comment by kyletsang** [comment]
Depending on your needs, you can use a grid for this (see https://react-bootstrap.github.io/layout/grid/) or add your own css to the form element to set the width to whatever you want.
