### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by mnai01** [react-bootstrap/react-bootstrap#6140]
### Prerequisites

- [X] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [X] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug

Collapse timeout only goes up to 300 max

### Expected behavior

timeout with any number value should convert to ms, therefore if i put timeout={5000} it should be a 5sec transition

### Reproducible Example

https://codesandbox.io/s/react-bootstrap-collapse-forked-kscsn?file=/src/App.js

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of React-Bootstrap are you using?

2.0.2

### What version of Bootstrap are you using?

5.1.3

**Comment by aksdevac** [comment]
that duration just adds/removes css classes based on received events from https://reactcommunity.org/react-transition-group/transition, in '.collapsing' class transition duration is set to _.35s_ in bootstrap 5 css so it will animate only for _.35s_.

**Comment by mnai01** [comment]
> that duration just adds/removes css classes based on received events from https://reactcommunity.org/react-transition-group/transition, in '.collapsing' class transition duration is set to _.35s_ in bootstrap 5 css so it will animate only for _.35s_.

So you're saying it can only animate for .35s no faster or slower?

**Comment by aksdevac** [comment]
@mnai01  yes but may be you can modify it by changing bootstrap's sass variable for this:
See this: https://getbootstrap.com/docs/5.1/components/collapse/#variables

**Comment by mnai01** [comment]
> @mnai01  yes but may be you can modify it by changing bootstrap's sass variable for this:
> See this: https://getbootstrap.com/docs/5.1/components/collapse/#variables

Interesting, I don't think this is correct as timeout clearly accepts a number based on ms to set the transition speed. In my example via sandbox you can modify the value your self and see how it speeds up if you put 10 and slows down if u put 300. I will look into the sass variables though, thank you.

**Comment by moterink** [comment]
I have experienced this issue as well, my workaround was setting transition manually on the `.collapsing` class. However since there is a timeout attribute on the Collapse component, this should not be necessary. I also think this is a bug and should be fixed in react-bootstrap rather than manually overriding with custom styles.

**Comment by kyletsang** [comment]
Normally, the animation duration should be controlled via the css.  I believe the `timeout` prop is there as a fallback in case browser events aren't triggered.  As @aksdevac mentioned, Transition is used to trigger the different Bootstrap classes in the animation state.

**Comment by moterink** [comment]
Alright I see, thanks for the clarification @kyletsang 👍
