### ISSUE TITLE
Docs: missing defaultActiveKey in Nav

### ISSUE THREAD

**Issue by vitpankin** [react-bootstrap/react-bootstrap#6141]
### Prerequisites

- [X] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [X] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug

Missing defaultActiveKey in Navs section in Docs

### Reproducible Example

Just check it out

### What version of React-Bootstrap are you using?

2.0.0

### What version of Bootstrap are you using?

5.1.3

**Comment by Aayushadh** [comment]
I want to work on this issue. But I am not able to understand, how can I modify, `Nav.mdx` file.

**Comment by Aayushadh** [comment]
Why we Nav page as `Nav.mdx` not `Nav.js` ?

**Comment by kyletsang** [comment]
Adding this to Nav's proptypes is enough for the docs to auto-generate the content.  The jsdoc comment above the proptypes is what appears in the docs.

**Comment by kolism** [comment]
I would like to pickup this issue, if you could assign it to me. 
I have read through the contribution guidelines and will publish a PR shortly. 
Thanks
