### ISSUE TITLE
<Button as={Link} to='/' disabled /> requires "href" prop for "disabled" prop to working properly

### ISSUE THREAD

**Issue by Kris-Simpson** [react-bootstrap/react-bootstrap#6142]
### Prerequisites

- [X] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [X] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug

Actually title says it all. When trying to create Button component with **as={Link}** property it requires me to add unnecessary **href='/'** property in order to **disabled** prop working properly. In case of not adding **href** to the component, button will be disabled but without **disabled** class added to it.

### Expected behavior

Button component properly disabled with **disabled** class name added.

### Reproducible Example

1. Bugged button `<Button as={Link}  to="/" disabled>Not fully disabled button</Button>`
2. Working button `<Button as={Link}  to="/" href="/" disabled>Disabled button</Button>`

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Firefox

### What version of React-Bootstrap are you using?

2.0.3

### What version of Bootstrap are you using?

5.1.3

**Comment by jquense** [comment]
`as` on Button is not really intended for the Link case, you should do it the other way around `<Link component={Button} ...>`
