### ISSUE TITLE
RTL Sass Support

### ISSUE THREAD

**Issue by Mehran91z** [react-bootstrap/react-bootstrap#6144]
### Prerequisites

- [X] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [X] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug

According to [your RTL](https://react-bootstrap.github.io/getting-started/rtl/) and [Bootstrap.v5 RTL](https://getbootstrap.com/docs/5.0/getting-started/rtl/) documentation, we need to use bootstrap flexible class like `ps-*`, `me-*`, etc. for having same class in both RTL and LTR document and this will auto compile RTL styles with `RTLCSS` package to make proper output for each one (ps = padding-end: padding-right for RTL and padding-left for LTR).
But it's not working as expected and therefore we don't want to import `bootstrap-rtl.css` in project as we are using Sass version of it.
Should we use any extra package like `RTLCSS` or `postcss` in our React/Nextjs project?

### Expected behavior

In Codesandbox below we should get `padding-right` when we are in RTL document and get `padding-left` in LTR document by using `ps-4` class there.

### To Reproduce

1. Run Codesandbox below
2. Look at the main `div` that has `ps-5` class in `index.js`
3. This got wrong padding according to RTL document. (it should be `padding-right` for RTL)

### Reproducible Example

[CodeSandbox](https://codesandbox.io/s/cocky-bassi-8q7dm) here.

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of React-Bootstrap are you using?

2.0.3

### What version of Bootstrap are you using?

5.1.3

**Comment by kyletsang** [comment]
From my understanding of the bootstrap docs, the sass files aren't actually RTL ready until you compile it using RTLCSS.  You would have to make your sass modifications, then compile it into your own css file to consume.

If you have any further questions or concerns regarding the css, you should bring it up in the [bootstrap github page](https://github.com/twbs/bootstrap).
