### ISSUE TITLE
Add transition callbacks for Toast

### ISSUE THREAD

**Issue by totembe** [react-bootstrap/react-bootstrap#6152]
### Is your feature request related to a problem? Please describe

After toast animation completion, I want to run some cleaning functions, like removing data from redux state. In my scenaroio this state also controls what toasters would be displayed. So if i remove my data from state, toaster will be closed immediately without animation. 

### Describe the solution you'd like

onHidden event which is called after transition completed would solve this problem.

**Comment by spigelli** [comment]
@totembe Submitted a pr to try and add this functionality, can you verify this is the behavior you were describing?

**Comment by totembe** [comment]
yes
