### ISSUE TITLE
Switch tests to @testing-library

### ISSUE THREAD

**Issue by kyletsang** [react-bootstrap/react-bootstrap#6156]
To future proof our tests for new React releases, we should probably switch away from enzyme.  Need to convert all tests over to RTL and typescript.

Help would be appreciated here.

If you take on one of the test files, please leave a comment here so there's no overlap.

- [x] AccordionButton - @VibhorJaiswal 
- [x] Accordion
- [x] Alert - @Sanchitverma78
- [x] Badge
- [x] BootstrapModalManager
- [x] BreadcrumItem
- [x] Breadcrumb
- [x] ButtonGroup
- [x] Button
- [x] ButtonToolbar
- [x] CardImg
- [x] Card - @jayeclark
- [x] CarouselCaption
- [x] Carousel
- [x] CloseButton
- [x] Collapse
- [x] Col
- [x] Container
- [x] createChainedFunction
- [x] createUtilityClasses
- [x] DropdownButton
- [x] DropdownItem
- [x] DropdownMenu
- [x] Dropdown
- [x] DropdownToggle
- [x] Fade
- [x] Feedback
- [x] FigureCaption
- [x] Figure
- [x] FloatingLabel
- [x] FormCheck
- [x] FormControlFeedback
- [x] FormControl
- [x] FormGroup
- [x] FormLabel
- [x] FormRange
- [x] FormSelect
- [x] Form
- [x] FormText
- [x] helpers
- [x] Image
- [x] InputGroup
- [x] ListGroupItem
- [x] ListGroup
- [x] ModalBody
- [x] ModalFooter
- [x] ModalHeader
- [x] Modal
- [x] ModalTitle
- [x] NavbarBrand
- [x] NavbarOffcanvas 
- [x] Navbar
- [x] NavbarToggle
- [x] NavDropdown
- [x] NavItem
- [x] NavLink
- [x] Nav
- [x] Offcanvas
- [x] Overlay
- [x] OverlayTrigger
- [x] PageItem
- [x] Pagination
- [x] PlaceholderButton
- [x] Placeholder
- [x] Popover
- [x] ProgressBar
- [x] Ratio
- [x] Row
- [x] Spinner
- [x] SplitButton
- [x] Stack
- [x] TabContent
- [x] Table
- [x] Tabs
- [x] ThemeProvider
- [x] ToastBody
- [x] ToastContainer
- [x] ToastHeader
- [x] Toast
- [x] ToggleButtonGroup
- [x] Tooltip
- [x] useOverlayOffset

**Comment by VibhorJaiswal** [comment]
I would like to do for AccordionButtonSpec.js.

**Comment by Sanchitverma78** [comment]
Ill take AlertSpec.js

**Comment by jayeclark** [comment]
@kyletsang I'd love to work on this issue. I did a quick test refactoring of the Card component test and it seemed to go fairly smoothly (will open a draft PR shortly for a reality check), so I'd be happy to take on a fairly large handful of these if you'd like.

**Comment by kyletsang** [comment]
> @kyletsang I'd love to work on this issue. I did a quick test refactoring of the Card component test and it seemed to go fairly smoothly (will open a draft PR shortly for a reality check), so I'd be happy to take on a fairly large handful of these if you'd like.

That would be great!  Thanks!

**Comment by marcalexiei** [comment]
I'll take `Badge` and `Breadcrumb`

**Comment by marcalexiei** [comment]
I'll continue with `ButtonGroup`, `Button` and `ButtonToolbar`

**Comment by marcalexiei** [comment]
Working on `Carousel` and `CarouselCaption`

**Comment by marcalexiei** [comment]
Start on `Collapse` and `Fade`

**Comment by pamrulla** [comment]
I would like to work on `Form`

**Comment by VibhorJaiswal** [comment]
I'll continue with  `FigureCaption`.

**Comment by pamrulla** [comment]
I will continue with `FormCheck`, `FormControlFeedback`, `FormControl`, `FormGroup`, `FormLabel`, `FormRange`, `FormSelect`, and  `FormText`

**Comment by AhamedFrontEndDeveloper** [comment]
Will help with `Modal`

**Comment by Sanchitverma78** [comment]
I'll take `image`

**Comment by marcalexiei** [comment]
I'll will start with `Accordion`

**Comment by VibhorJaiswal** [comment]
I'll take `ModalBody`, `ModalFooter`, `ModalHeader` and `ModalTitle`.

**Comment by marcalexiei** [comment]
I'll finish with what is left:
- `Feedback`
- `Figure`
- `FloatingLabel`
- `InputGroup`
- `ListGroupItem`
- `ListGroup`

**Comment by kyletsang** [comment]
We're finally done!   Thank you all for helping out in migrating these tests!
