### ISSUE TITLE
Feature: "Back to top" option in docs.

### ISSUE THREAD

**Issue by VibhorJaiswal** [react-bootstrap/react-bootstrap#6159]
### Is your feature request related to a problem? Please describe

Whenever a user has to go to the top of the page, they have to do it manually.

### Describe the solution you'd like

I would like to add a "Back to top" button which can directly scroll the page to the top.

**Comment by kyletsang** [comment]
I'm thinking of switching over docs to docusaurus which does have this feature built in.

**Comment by VibhorJaiswal** [comment]
@kyletsang ok.
