### ISSUE TITLE
Import Collapse styling

### ISSUE THREAD

**Issue by jakobjyberg** [react-bootstrap/react-bootstrap#6160]
Hi, 

I'm using the collapse component and I import only the sass styles I need. However I get an error that some class is undefined so I assume that some more styles needs to be imported? Which is needed for collapse component to work properly?

`@import "../node_modules/bootstrap/scss/functions";
@import "../node_modules/bootstrap/scss/variables";
@import "../node_modules/bootstrap/scss/mixins";
@import "../node_modules/bootstrap/scss/utilities";
@import "../node_modules/bootstrap/scss/utilities/api";
@import "../node_modules/bootstrap/scss/transitions";`

The error message:
`Error in function children in ./node_modules/react-bootstrap/esm/Collapse.js:85
Cannot read properties of undefined (reading 'className')

./node_modules/react-bootstrap/esm/Collapse.js:85
Open in Editor
  83 |     childRef: children.ref,
  84 |     children: (state, innerProps) => /*#__PURE__*/React.cloneElement(children, { ...innerProps,
> 85 |       className: classNames(className, children.props.className, collapseStyles[state], computedDimension === 'width' && 'collapse-horizontal')
     |                           ^
  86 |     })
  87 |   });
  88 | }); // @ts-ignore`

Thanks in advance!

**Comment by kyletsang** [comment]
The error you see is a javascript error.  Did you use an element as a child inside `Collapse`?

See https://react-bootstrap.github.io/utilities/transitions/#basic-example

**Comment by jakobjyberg** [comment]
Thanks I solved it by changing the fragment tag to div.
