### ISSUE TITLE
Modal with animation on stays hidden in certain cases

### ISSUE THREAD

**Issue by phev8** [react-bootstrap/react-bootstrap#6168]
### Prerequisites

- [X] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [X] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug

We are using react-bootstrap in an application together with react-router-dom, where content of the page is generated based  on a dynamically loaded JSON file.

The issue is, that whenever a modal should be opened with animation on, meanwhile some content is being downloaded and rendered for an other component, only the backdrop appears and the dialog not. By inspecting the error cases, the only difference on the resulting DOM is that `style="display: block;"` won't be attached to the modal's div in these cases. 

In our application the issue only happens the first time a page is visited, next time the browser is using the cached route, and the modal also behaves as it should. Turning off the animation results in the correct behaviour, so it sounds like due to other processes somehow the end of the animation is not detected/triggered?

### Expected behavior

The modal should appear, with the backdrop behind. Instead, only the backdrop is visible (and also functional). In the DOM, the `style="display: block;"` should be added at the end of the animation, but is missing.

### Reproducible Example

https://github.com/coneno/case-web-app-core/commit/56c926895446d40af599d9d78110744d0e171725

Using `yarn storybook` command a local preview starts. In the `Participant app/Example1` using the navigation menu, the issue happens every time when a page opened first.

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome, Safari

### What version of React-Bootstrap are you using?

2.1.0

### What version of Bootstrap are you using?

5.1.3

**Comment by phev8** [comment]
Ok, the mentioned repo is not perfect to reproduce the issue, because it doesn't open the dialog automatically on navigation , only if logged in... If necessary, I can create a commit just to reproduce the error, let me know please if that would be helpful.

**Comment by phev8** [comment]
Might be related to issue #6153 ?

**Comment by kyletsang** [comment]
> Ok, the mentioned repo is not perfect to reproduce the issue, because it doesn't open the dialog automatically on navigation , only if logged in... If necessary, I can create a commit just to reproduce the error, let me know please if that would be helpful.

Can you please add this change?

**Comment by phev8** [comment]
https://github.com/coneno/case-web-app-core/commit/223045de8ac9a0aeb791a1b175678b37c48289b0

I made this change here, so now the app would try to open a modal at every click on a navbar item. At first visit of a page the model does not appear (only the backdrop), on every further visit, it works as expected. Issue only happening if animation is used on the modal. 

> Using yarn storybook command a local preview starts. In the Participant app/Example1 using the navigation menu, the issue happens every time when a page opened first.

**Comment by kyletsang** [comment]
@phev8 where can I enable animations on the modal?  I don't see any knobs or props I can modify on the dialog.

**Comment by phev8** [comment]
They are enabled now globally (wrapped into a react component that is included in react lib of our own and imported here). 
I am thinking right now, how to make a smaller example to reproduce... Problem is, I am not sure yet what might cause the issue - e.g. if a simple timeout based simulation for the loading would be enough, or it's rather on. deeper level, where react-router-dom (or some other parts), prevent react-bootstrap to attach the right styling attribute - or somehow the method that should attach it is not triggered at the right time.
I only tested so far on macOS with Chrome and Safari, and surpirsingly this time it is consistent behaviour across. 

https://user-images.githubusercontent.com/13927969/147979162-55628877-dde9-4907-be11-004212be2561.mov

**Comment by kyletsang** [comment]
Thanks, can confirm I see the behavior.  Interestingly, I'm not getting animations on Windows, but I can see it on a mac.

**Comment by phev8** [comment]
Not sure if relevant, but here is the component that is used for the modal:
https://github.com/coneno/case-web-ui/blob/next/src/components/dialogs/Dialog.tsx
(In the demo up without the `animation={false}`)

This is bundled using rollup and imported in the above mentioned repo, where depending on the redux state, we change the "open" flag for some dialogs.

**Comment by kyletsang** [comment]
Looks like the `display: block` style isn't persisting, but I haven't determined why yet.  This is normally set here:

https://github.com/react-bootstrap/react-bootstrap/blob/9345f1c3ed4c3d9575621b4178a3c8417f4131fa/src/Modal.tsx#L400-L403

This issue could be worked around by running that same block inside the `onEntered` callback, however you would lose the animation in this one scenario.

**Comment by phev8** [comment]
Could it be that due to some other processes triggered in the useEffect and animation started, the `node` is not set yet?
