### ISSUE TITLE
Input addonBefore does not allow setting hidden-xs on input-group-addon

### ISSUE THREAD

**Issue by cymen** [react-bootstrap/react-bootstrap#617]
Say I have a modal that has been customized to look like this:

![screen shot 2015-05-05 at 11 50 47 am](https://cloud.githubusercontent.com/assets/121034/7480366/05a00e82-f31d-11e4-98f0-8039d1b19d97.png)

When the screen is shrunk down, I want the addonBefore to disappear. So in regular bootstrap, the input-group-addon would have the `hidden-xs` class applied. But react-bootstrap does not expose a way to set it on the input-group-addon div that it wraps around the addonBefore property.

**Comment by cymen** [comment]
I'd be happy to do a PR to fix this but I'm not sure how to fix it cleanly. If I was to go the most direct route, I would add to Input these properties:

addonAfterClassName
addonBeforeClassName
buttonBeforeClassName
buttonAfterClassName

Or it could be more like:

addonAfterProperties
addonBeforeProperties
buttonBeforeProperties
buttonAfterProperties

Or maybe the option to customize the input-group-addon with say:

addonAfterInputGroup
...

Any preferences?

**Comment by cymen** [comment]
I'm temporarily working around this issue with an ugly hack:

```javascript
  componentDidMount: function() {
    // TODO work around for https://github.com/react-bootstrap/react-bootstrap/issues/617
    this.getDOMNode().getElementsByClassName('input-group-addon')[0].className += ' hidden-xs';
  },
```

**Comment by aabenoja** [comment]
Related to #342.

**Comment by aabenoja** [comment]
@cymen What are you passing in to `addonBefore` exactly?

**Comment by dozoisch** [comment]
piece of code in question

https://github.com/react-bootstrap/react-bootstrap/blob/master/src/Input.js#L53-L57

**Comment by cymen** [comment]
My usage looks like this:

```javascript

  renderPrefix: function() {
    return (
      <span className="hidden-xs">
        <i className="fa fa-search"></i> Keywords
      </span>
    );
  },

  renderButton: function() {
    return <Button bsStyle="primary" onClick={this.onFilterApply}>Search</Button>;
  },

  render: function() {
    return (
      <Modal
        className="keyword-filter-modal"
        onRequestHide={this.props.onFilterHideRequest}>

        <div className="keyword-filter">
          <Input
            addonBefore={this.renderPrefix()}
            buttonAfter={this.renderButton()}
            bsSize="large"
            type="text"
            placeholder="Internet of things"
            value={}
            onChange={this.onChange}
          />
        </div>

      </Modal>
    );
  }

```

`renderPrefix` has the `hidden-xs` class on the span it is rendering but it needs to be on the parent container that `Input` is rendering.

**Comment by cymen** [comment]
The code @dozoisch linked to is it of course... Instead of:

```html
<span className="input-group-addon" key="addonBefore">
```

I want:

```html
<span className="input-group-addon hidden-xs" key="addonBefore">
```

**Comment by aabenoja** [comment]
@cymen Got it reproduced on my end. I'm in the middle of working on a new `InputWrapper`, so I'll include a fix for this issue with it. Good find. :+1:

**Comment by cymen** [comment]
@aabenoja Thanks. I opened a PR with a very general solution. I think native bootstrap is more composable and that react-bootstrap is trying to do too much sometimes to make composing easy. I think this approach is great until it isn't -- so I suggest we take that approach but leave the doors open to more customization.

**Comment by mtscout6** [comment]
@cymen We agree that the `Input` component is indeed doing too much, which is why we are trying to simplify them.

**Comment by cymen** [comment]
@mtscout6 :+1: I'm starting to piece together the prior issues. I'll keep reading. That is great to hear and thanks for giving context!

**Comment by mtscout6** [comment]
@cymen See issue #342

**Comment by taion** [comment]
Let's just fold this into #342.
