### ISSUE TITLE
timeout prop not work then 300 

### ISSUE THREAD

**Issue by adminwp** [react-bootstrap/react-bootstrap#6171]
### Prerequisites

- [X] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [X] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug

Are timeout accepts last value 300 ?

I need 800 value for timeout value

### Reproducible Example

https://codesandbox.io/s/stoic-mclaren-dm2zf?file=/src/App.js

### Screenshots

https://iili.io/YwYeJ2.png

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of React-Bootstrap are you using?

2.0.3

### What version of Bootstrap are you using?

5.1.3

**Comment by kyletsang** [comment]
You'll need to adjust the duration in the css to change animation duration.  The timeout prop is a fallback to make sure callbacks are triggered if events aren't triggered

> Duration of the collapse animation in milliseconds, to ensure that finishing callbacks are fired even if the original browser transition end events are canceled
