### ISSUE TITLE
alwaysOpen property not found

### ISSUE THREAD

**Issue by pnkflydgr** [react-bootstrap/react-bootstrap#6174]
### Prerequisites

- [X] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [X] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug

I'm getting a property does not exist error when trying to use alwaysOpen. 

I'm using the following packages:
   "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "bootstrap": "^5.1.3",
    "react-bootstrap": "^2.1.0",

### Expected behavior

I expect the property to work as described here: https://react-bootstrap.netlify.app/components/accordion/#always-open

### To Reproduce

1.  go to sandbox --> [CodeSandbox](https://codesandbox.io/s/github/react-bootstrap/code-sandbox-examples/tree/master/basic)
2. navigate to basic-ts-v5 > src > App.tsx
3. add an Accordion component and give it a property of alwaysOpen
4. the error will pop up

### Reproducible Example

[example](https://codesandbox.io/s/competent-newton-zbyie?file=/basic-ts-v5/src/App.tsx)

### Screenshots

![image](https://user-images.githubusercontent.com/13042290/148424438-a8bcb7e5-ecb9-4a3a-8a35-92c612f6eee2.png)

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome, Microsoft Edge

### What version of React-Bootstrap are you using?

2.1.0

### What version of Bootstrap are you using?

5.1.3

**Comment by golota60** [comment]
couldn't repro it just now - react-bootstrap `2.1.0` has the newest `alwaysOpen` property(see screenshot). it seems like it might be a local caching issue or vscode not picking up on types - try `rm -rf node_modules`, next either `npm` or `yarn`(depending on what you use) and then restarting your IDE. VSCode is sometimes slow picking up on new types. 

![image](https://user-images.githubusercontent.com/37072867/148432025-3280f998-b577-4846-a91f-edc766c9d4fa.png)

**Comment by pnkflydgr** [comment]
That fixed it actually.  Thanks!

What's weird is I got the same error in the react-bootstrap CodeSandbox as well:
![image](https://user-images.githubusercontent.com/13042290/148434868-dc5aa505-3648-47cc-a4b4-1d8bcd4a79a3.png)

All's well that ends well though.  Thanks again.

**Comment by pnkflydgr** [comment]
Just to be clear... what worked is:
- rm -r node_modules
- npm i
