### ISSUE TITLE
<Overlay> not respecting its boundary

### ISSUE THREAD

**Issue by WouterrV** [react-bootstrap/react-bootstrap#6190]
### Prerequisites

- [X] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [X] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug

Hello lovely people,

The `Overlay` from React-bootstrap uses Popper, and you can pass options to Popper via a `popperConfig`-prop.

I've tried to use that to prevent the `Overlay` from going off-screen, but I can't get it to work. Not sure if this is a problem with React-bootstrap or with Popper, but there seems to be something going amiss with the Popper-integration, looking at the DOM of the Overlay element I see this: `arrowprops="[object Object]"`

Maybe that is related.

The offset is to show that the config is being passed to Popper.

### Reproducible Example

https://codesandbox.io/s/popper-overflowing-8ttjh?file=/src/App.tsx

### What version of React-Bootstrap are you using?

1.6.4

### What version of Bootstrap are you using?

the one imported by react-bootstrap

**Comment by kyletsang** [comment]
`Overlay` passes additional props that you need to forward along to your actual overlay component.  The props are defined here:

https://github.com/react-bootstrap/react-bootstrap/blob/ec35a81d114e98b6f647980380858ebca31320af/src/Overlay.tsx#L17-L33

Take a look at the `Tooltip` or `Popover` component as an example on how to consume this.

**Comment by WouterrV** [comment]
Oh that's even in the docs, can't believe I missed that. I implemented it, the warnings in the console are gone, yet the Tooltip is still overflowing: https://codesandbox.io/s/popper-overflowing-8ttjh?file=/src/App.tsx

**Comment by kyletsang** [comment]
Check this sandbox and try comparing the overlay after pressing the "boundary" button.  

https://codesandbox.io/s/popper-overflowing-forked-pz1k9?file=/src/App.tsx

Seems to work except in the case where placement is left/top.  Looks like if there isn't enough space to show the overlay in that placement, it'll overflow the boundary.  Not sure if this is intended though, since I don't really use this option.  If you have any questions about the modifier, the popper repo would be a better place for support.

**Comment by WouterrV** [comment]
Thanks!! That's good enough for me, your codesandbox gives a very clear example, turns out setting placement (and maybe flip? don't understand it completely) is necessary for not having an overflow.
