### ISSUE TITLE
Using a Form.Control in an Offcanvas Does Not Allow Spaces

### ISSUE THREAD

**Issue by Jordan9232** [react-bootstrap/react-bootstrap#6192]
### Prerequisites

- [X] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [X] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug

When using a `<Form.Control>` inside a `<Offcanvas>` space characters do not seem to register. Entering something such as "Hard Hat" would render "HardHat" in the input.

### Expected behavior

Entering a space should register. Entering "Hard Hat" should render "Hard Hat" in the input instead of "HardHat".

### To Reproduce

Enter some text with a space in the input

### Reproducible Example

```
<Offcanvas backdrop={false} keyboard={false} placement="end" scroll>
  <Offcanvas.Header closeButton>
    <Offcanvas.Title>Products</Offcanvas.Title>
  </Offcanvas.Header>
  <Offcanvas.Body>
    <Form.Group controlId="search">
      <Form.Label>Search</Form.Label>
      <Form.Control />
    </Form.Group>
  </Offcanvas.Body>
</Offcanvas>
```

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Firefox

### What version of React-Bootstrap are you using?

2.1.1

### What version of Bootstrap are you using?

5.1.3

### Additional context

As a temporary workaround I was able to surround the Header and Body with a div with a `e.stopPropagation()` on `onKeyDown` like this to allow spaces:

```
<Offcanvas backdrop={false} keyboard={false} placement="end" scroll>
  <div onKeyDown={e => e.stopPropagation()}>
    <Offcanvas.Header closeButton>
      <Offcanvas.Title>Products</Offcanvas.Title>
    </Offcanvas.Header>
    <Offcanvas.Body>
      <Form.Group controlId="search">
        <Form.Label>Search</Form.Label>
        <Form.Control />
      </Form.Group>
    </Offcanvas.Body>
  </div>
</Offcanvas>
```

**Comment by golota60** [comment]
Hey, I've just used your example in the [codesandbox example](https://codesandbox.io/s/summer-dust-sou07?file=/src/App.tsx) and everything seems to be working. Could you provide a codesandbox example where this issue occurs?

**Comment by Jordan9232** [comment]
Okay I found that it only seems to happen when the button you use to activate it is a `<NavDropdown.Item>`. I have created a sandbox where this is reproducible [here](https://codesandbox.io/s/great-chebyshev-60ori?file=/src/App.tsx).

**Comment by Jordan9232** [comment]
I've tested the same scenario in google chrome and it seems to work fine on there. May just be an issue with Firefox.

**Comment by kyletsang** [comment]
Can you try moving the Offcanvas out of the dropdown item?  I believe that although the offcanvas is rendered in an element that's outside the dropdown, the events will still propagate to the dropdown due to how react handles it.

**Comment by Jordan9232** [comment]
Yeah I've moved the offcanvas outside of the dropdown to fix the issues. Weird that that works in Chrome but not firefox though. I'd say you can probably just close this.

**Comment by kyletsang** [comment]
Thanks for confirming 👍
