### ISSUE TITLE
Bug: OverlayTrigger + custom component = Warning: Function components cannot be given refs

### ISSUE THREAD

**Issue by alexandernst** [react-bootstrap/react-bootstrap#6194]
### Prerequisites

- [X] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [X] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug

I'm trying to use the `OverlayTrigger` component by copying the code of one of the demos at https://react-bootstrap.github.io/components/overlays/#tooltips .

If I pass a `<Button>` component as a child to the `OverlayTrigger` component, the tooltip shows as expected, but if I pass a custom component (a component that just returns a simple div), I get this warning:

```
Warning: Function components cannot be given refs. Attempts to access this ref will fail.
Did you mean to use React.forwardRef()?

Check the render method of `OverlayTrigger`.
```

### Expected behavior

I should be able to pass any components to `OverlayTrigger`.

### To Reproduce

Open the repro example I made.

### Reproducible Example

https://codesandbox.io/s/distracted-robinson-kded3?file=/src/App.js

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome

### What version of React-Bootstrap are you using?

2.1.1

### What version of Bootstrap are you using?

5.1.3

**Comment by alexandernst** [comment]
I think the docs tried to cover this, but I don't quite understand the intended usage.

![React-Bootstrap_·_React-Bootstrap_Documentation](https://user-images.githubusercontent.com/89727/149660238-2559f879-6c82-4f12-83e9-54176571f3e8.png)

**Comment by alexandernst** [comment]
I found the answer. The component that is being passed to `OverlayTrigger` should be wrapped in `forwardRef`.

**Comment by GaylordP** [comment]
Hello @alexandernst ,

I have same problem.
I always get this error when I use OverlayTrigger and despite a lot of research, I can't find a solution.

> Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

Can you post your solution ?
Thanks :)

**Comment by alexandernst** [comment]
![Cursor_y_NodeSettings_jsx_—_pipeline-builder](https://user-images.githubusercontent.com/89727/184194130-78f32248-f3be-4301-bf25-146d8113ec53.png)

@GaylordP ^ I hope this helps

**Comment by GaylordP** [comment]
Thank you very much for these details :)

**Comment by isabellachen** [comment]
The documentation of OverlayTrigger provides a out of the box example: [Customizing trigger behaviour](https://react-bootstrap.netlify.app/docs/components/overlays/#customizing-trigger-behavior).

```js
import Button from 'react-bootstrap/Button';
import Image from 'react-bootstrap/Image';
import OverlayTrigger from 'react-bootstrap/OverlayTrigger';

function TriggerRendererProp() {
  return (
    <OverlayTrigger
      placement="bottom"
      overlay={<Tooltip id="button-tooltip-2">Check out this avatar</Tooltip>}
    >
      {({ ref, ...triggerHandler }) => (
        <Button
          variant="light"
          {...triggerHandler}
          className="d-inline-flex align-items-center"
        >
          <Image
            ref={ref}
            roundedCircle
            src="holder.js/20x20?text=J&bg=28a745&fg=FFF"
          />
          <span className="ms-1">Hover to see</span>
        </Button>
      )}
    </OverlayTrigger>
  );
}

export default TriggerRendererProp;
```
