### ISSUE TITLE
Custom dropdown popperConfig={{ strategy: "fixed" }} works differently than expected.

### ISSUE THREAD

**Issue by whitefes** [react-bootstrap/react-bootstrap#6203]
### Prerequisites

- [X] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [X] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug

I want use popperConfig(strategy: "fixed" ) option in custom dropdown.
but It works differently than expected in v2.1.1(bootstrap 5.1)
The dropdown menu appears in the upper left corner of the screen.

<img width="2029" alt="스크린샷 2022-01-24 오후 12 21 09" src="https://user-images.githubusercontent.com/6138575/150716895-34668d6b-da0a-48b3-b6fb-fc00450ffabf.png">

### Expected behavior

The dropdown menu appears in the under of the Custom Toggle(Anchor). v1.6.1(Bootstrap 4)

<img width="2359" alt="스크린샷 2022-01-24 오후 12 26 51" src="https://user-images.githubusercontent.com/6138575/150717306-51b7a6d0-9949-4239-b28e-f415bd3345fb.png">

### To Reproduce

1. Go to react-bootstrap 
2. Dropdown
3. Custom Dropdown Components Example
4. add popperConfig={{ strategy: "fixed" }}  in Dropdown.Menu 

### Reproducible Example

```javascript
// The forwardRef is important!!
// Dropdown needs access to the DOM node in order to position the Menu
const CustomToggle = React.forwardRef(({ children, onClick }, ref) => (
  <a
    href=""
    ref={ref}
    onClick={(e) => {
      e.preventDefault();
      onClick(e);
    }}
  >
    {children}
    &#x25bc;
  </a>
));

// forwardRef again here!
// Dropdown needs access to the DOM of the Menu to measure it
const CustomMenu = React.forwardRef(
  ({ children, style, className, 'aria-labelledby': labeledBy }, ref) => {
    const [value, setValue] = useState('');

    return (
      <div
        ref={ref}
        style={style}
        className={className}
        aria-labelledby={labeledBy}
      >
        <FormControl
          autoFocus
          className="mx-3 my-2 w-auto"
          placeholder="Type to filter..."
          onChange={(e) => setValue(e.target.value)}
          value={value}
        />
        <ul className="list-unstyled">
          {React.Children.toArray(children).filter(
            (child) =>
              !value || child.props.children.toLowerCase().startsWith(value),
          )}
        </ul>
      </div>
    );
  },
);

render(
  <Dropdown>
    <Dropdown.Toggle as={CustomToggle} id="dropdown-custom-components">
      Custom toggle
    </Dropdown.Toggle>

    <Dropdown.Menu as={CustomMenu} popperConfig={{ strategy: "fixed" }}>
      <Dropdown.Item eventKey="1">Red</Dropdown.Item>
      <Dropdown.Item eventKey="2">Blue</Dropdown.Item>
      <Dropdown.Item eventKey="3" active>
        Orange
      </Dropdown.Item>
      <Dropdown.Item eventKey="1">Red-Orange</Dropdown.Item>
    </Dropdown.Menu>
  </Dropdown>,
);
```

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome

### What version of React-Bootstrap are you using?

2.1.1

### What version of Bootstrap are you using?

5.1.3

**Comment by kyletsang** [comment]
The initial rendered position is wrong, but once you scroll, it corrects itself.

As a workaround try adding `renderOnMount` to the dropdown menu.

**Comment by moisesmissecart** [comment]
> La posición inicial renderizada es incorrecta, pero una vez que se desplaza, se corrige a sí misma.
> 
> Como solución alternativa, intente agregar al menú desplegable.`renderOnMount`

this work for me

**Comment by Godwin9911** [comment]
> The initial rendered position is wrong, but once you scroll, it corrects itself.
> 
> As a workaround try adding `renderOnMount` to the dropdown menu.

This worked for me

**Comment by Chandan4862** [comment]
renderOnMount not working, any other solution?

**Comment by Douten** [comment]
RenderOnMount was causing weird issues for me. Since it fixes itself when scrolling I did this instead.
```
  const popperConfig = {
    strategy: "fixed",
    onFirstUpdate: () => window.dispatchEvent(new CustomEvent('scroll')),
  }
```
https://popper.js.org/docs/v2/lifecycle/#hook-into-the-lifecycle

**Comment by FonTain1991** [comment]
not working
