### ISSUE TITLE
When a tooltip is visible and you start scrolling, the tooltip appears above other elements.

### ISSUE THREAD

**Issue by HannesWylaers** [react-bootstrap/react-bootstrap#6209]
### Prerequisites

- [X] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [X] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug

When a tooltip appears within a container and you start scrolling the container away, the tooltip appears above any other elements on the page.

### Expected behavior

When a tooltip appears within a container and you start scrolling the container, the tooltip should only be visible within the container and not appear above any other elements on the page.

### To Reproduce

1: Go to https://react-bootstrap.github.io/components/overlays/#examples
2: Go to example of _'You can pass the Overlay injected props directly to the Tooltip component.'_ and click on the button to show the tooltip.  
3: Start scrolling the entire page.
4: When you scroll the button with the tooltip away, the tooltip appears above the header

### Reproducible Example

The issue is visible on the website, see https://react-bootstrap.github.io/components/overlays/#examples.

### Screenshots
![tooltip issue](https://user-images.githubusercontent.com/15179013/151430956-186c97f4-f3a6-4429-8e99-d391409e1522.gif)

![tooltip issue_B](https://user-images.githubusercontent.com/15179013/151431554-31d1f33a-469b-4c73-b969-ff212c426ba5.gif)

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome

### What version of React-Bootstrap are you using?

The issue is visible on the website

### What version of Bootstrap are you using?

The issue is visible on the website

### Additional context

If I apply 'z-index: 0;' to '.tooltip', the issue seems to be fixed.

**Comment by golota60** [comment]
Hi! According to bootstrap styling it is expected to work like that. `tooltip` class applies `z-index: 1080` by default. You can change this by adjusting `$zindex-tooltip` scss variable
https://getbootstrap.com/docs/5.1/components/tooltips/

**Comment by watinha** [comment]
Hello everyone! In this case, would it make sense to increase the z-index of the header of the docs webpage, so that the tooltips do not hover it?

**Comment by HannesWylaers** [comment]
FYI: increasing the z-index of the header isn't really solving this issue.
Instead, it increases other unwanted side effect e.g. when opening a modal, the modal appears under the header.
See the examples on https://react-bootstrap.github.io/components/modal/.

Since I see similar issues at bootstrap side, I guess this issue isn't coming from react-bootstrap.
I left a comment on a similar issue, see https://github.com/twbs/bootstrap/issues/35202#issuecomment-1067222357

**Comment by kyletsang** [comment]
Forgot about the modal being affected by this.  I'll revert the change on the docs.
