### ISSUE TITLE
Missing export for ModalHeader

### ISSUE THREAD

**Issue by sdumjahn** [react-bootstrap/react-bootstrap#6226]
### Prerequisites

- [X] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [X] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug

The export of `ModalHeader` is missing in `src/index.tsx`.

### Expected behavior

The component `ModalHeader` is exported like the other components from the Modal (e.g. ModalTitle, ModalFooter, ...)

### To Reproduce

You get an error when importing the component:

```js
import { Modal, ModalBody, ModalFooter, ModalHeader, ModalTitle } from 'react-bootstrap';

...
```

### Reproducible Example

```js

import React from 'react';
import { Button, Modal, ModalBody, ModalFooter, ModalHeader, ModalTitle } from 'react-bootstrap';

export const TestComponent = () => {
   return (
       <Modal show>
          <ModalHeader closeButton>
             <ModalTitle>Title</ModalTitle>
          </ModalHeader>

          <ModalBody>The Body</ModalBody>

          <ModalFooter className="bg-light">
             <Button variant="outline-link">
                Close
             </Button>
          </ModalFooter>
       </Modal>
   );
};
```

### What operating system(s) are you seeing the problem on?

macOS

### What version of React-Bootstrap are you using?

2.1.2

### What version of Bootstrap are you using?

5.1

**Comment by VibhorJaiswal** [comment]
It is exported like this in `src/Modal.tsx`

![image](https://user-images.githubusercontent.com/69683278/151996646-44a174e3-55e1-444c-9145-e22fb8bfc7a3.png)

So, according to documentation you can use

`<Modal.Header closeButton>
    <Modal.Title>Modal title</Modal.Title>
  </Modal.Header>
`

**Comment by kyletsang** [comment]
We should add this since others are exposed from the index.  PRs are welcome

**Comment by VibhorJaiswal** [comment]
I would like to work on it.
