### ISSUE TITLE
Question: How to implement offcanvas on selected breakpoint?

### ISSUE THREAD

**Issue by graydirt** [react-bootstrap/react-bootstrap#6227]
I did the navbar offcanvas across all breakpoints using the attribute expand={false} like the image below.
![image](https://user-images.githubusercontent.com/1822445/152101253-f6799ddf-4bb5-44ad-8b70-d0e296d3e9d5.png)

However i want the navbar items to be like the normal navigation on (min-width: 992px) OR expand="lg" like the image below. Im using reactrouter v6 and react-bootstrap.
![image](https://user-images.githubusercontent.com/1822445/152101288-0d105043-6ce3-494b-ab88-d54a6ce1d4a5.png)

Below is my code and also here is the complete sandbox code [https://codesandbox.io/](https://codesandbox.io/s/react-router-bootstrap-offcanvas-menu-1tx0n).

![image](https://user-images.githubusercontent.com/1822445/152104999-dfd84bae-b5aa-4f05-b27b-6563a9ac074b.png)

**Comment by golota60** [comment]
Hi, issues aren't the place to get technical support - please try [react-bootstrap tag on stackoverflow](https://stackoverflow.com/questions/tagged/react-bootstrap) or ask in [reactiflux discord](https://discord.com/invite/AKfs9vpvRW)
