### ISSUE TITLE
ModalTitle is created with the h4 className, Bootstrap documentation uses h5 html tag.

### ISSUE THREAD

**Issue by KyButler** [react-bootstrap/react-bootstrap#6229]
### Prerequisites

- [X] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [X] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug

ModalTitle in react-bootstrap renders as:

```jsx
<div class="modal-title h4">Modal title</div>
```

However, bootstrap documentation [here](https://getbootstrap.com/docs/5.1/components/modal/#modal-components) dictates it can be:

```jsx
<h5 class="modal-title">Modal title</h5>
```

1) Shouldn't react-bootstrap be using h5, not h4?
2) Shouldn't react-bootstrap be using the h5 (or h4) tag, not div tag, then not have to worry about the className?

### Expected behavior

I expect ModalTitle to render as:
```jsx
<h5 class="modal-title">Modal title</h5>
```

### To Reproduce

Create a 
```jsx 
<Modal.Title>
```

### Reproducible Example

```jsx
import React from 'react';

import Modal from 'react-bootstrap/Modal';
import Container from 'react-bootstrap/Container';

import './App.css';

const App = () => (
  <Container className="p-3">
    <Modal.Dialog>
      <Modal.Header>
        <Modal.Title>Modal title</Modal.Title>
      </Modal.Header>
    </Modal.Dialog>
  </Container>
);

export default App;
```

### Screenshots

[React-Bootstrap Documentation](https://react-bootstrap.github.io/components/modal/#static-markup)
![image](https://user-images.githubusercontent.com/12141121/152261970-204ecbab-2243-4454-8314-ee27b0713853.png)

[Bootstrap Documentation](https://react-bootstrap.github.io/components/modal/#static-markup)
![image](https://user-images.githubusercontent.com/12141121/152262018-bd12bdfb-fff2-4d53-93c6-bdaddceddad3.png)

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome

### What version of React-Bootstrap are you using?

2.1.2

### What version of Bootstrap are you using?

5.1.3

**Comment by pamrulla** [comment]
@KyButler It is not a bug but expected behaviour as per the [react-bootstrap documentation](https://react-bootstrap.github.io/components/modal/#modal-title-props)

The current behaviour is default behaviour. To change the tag please use `as` prop.

`<Modal.Title as="h5">Modal title</Modal.Title>`

Also, bootstrap documentation does not force us to use `h5` tag, you can use any tag
