### ISSUE TITLE
Change local docs run to use webpack-dev-server instead of webpack-dev-middleware

### ISSUE THREAD

**Issue by mtscout6** [react-bootstrap/react-bootstrap#623]
The command `npm run docs` is supposed to watch for file changes and reload/recompile everything necessary. For any of the modules that are loaded server side this is not the case, which is problematic with the isomorphic approach we have been trying. What we need to do is use the webpack-dev-server and proxy to a server back-end that gets reloaded with either supervisor or nodemon.

**Comment by AlexKVal** [comment]
I'm trying to untangle it, but no promises.
I won't assign myself, because I'm not sure about 
amount of time it gets me to comprehend and refactor it all. 

But anyway I'm very interested to understand it once and for all.
All branches of the chain :smile:
