### ISSUE TITLE
Better Ads placement.

### ISSUE THREAD

**Issue by VibhorJaiswal** [react-bootstrap/react-bootstrap#6237]
### Is your feature request related to a problem? Please describe

As of now the ads are shown like this 
![image](https://user-images.githubusercontent.com/69683278/153007285-42bb3696-2ecf-4dd3-8c22-df841fced4f4.png)

which hides the components menu.

### Describe the solution you'd like

In majority of the components, there is enough space in the table of contents(on right side).
![image](https://user-images.githubusercontent.com/69683278/153006844-d5a3e6b6-fc03-45ca-9d16-18bb8a2bc9d6.png)

So, I think it would be a better place for ad placement.

**Comment by kyletsang** [comment]
The ads don't actually overlap the components menu - it's positioned right below it using flex.  You can still scroll through the sidebar to find the component link you need.

**Comment by VibhorJaiswal** [comment]
@kyletsang Yes, you are technically right but what I am saying is that there is enough free space on the right side to place that ad which will give the component menu more visibility.
