### ISSUE TITLE
Change labels in Upload file form

### ISSUE THREAD

**Issue by olga-gchak** [react-bootstrap/react-bootstrap#6245]
### Prerequisites

- [X] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [X] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug

Hello!

Is it possible to replace the default labels on Upload file form, like it was possible in 1.6.4 version react-bootstrap by using data-browse and label props?

### Reproducible Example

![image](https://user-images.githubusercontent.com/67831961/153854101-c089731a-d345-408d-818b-288a8eabe638.png)

### Screenshots

![image](https://user-images.githubusercontent.com/67831961/153851569-b1c3c520-0191-49b8-a786-3e3bb33116a8.png)

### What version of React-Bootstrap are you using?

5.1

### What version of Bootstrap are you using?

2.1.2

**Comment by kyletsang** [comment]
Bootstrap has changed the way the file input is rendered so it's not the same as the one in BS4.  Here's a SO link with the same question:  https://stackoverflow.com/questions/65770908/how-to-change-choose-file-text-using-bootstrap-5
