### ISSUE TITLE
Popover positionLeft and arrowOffSetTop is overwrite each other

### ISSUE THREAD

**Issue by madebymt** [react-bootstrap/react-bootstrap#6246]
OK I have an issue need to update the arrow position and container of the popover, I saw another issue in #1640, #1066

I have custom popover so I will have the prop for positionLeft an arrowOffSetLeft to update poistion.

This case `positionLeft` is not working` , but  arrowOffsetTop does change.
```
let Mypopover = (props) =>{
  return <Popover {...props} placementLeft={'130%'} arrowOffsetTop={props.arrowOffsetTop +10}>
}
```

So I change it to be like this, but this one will overwrite the arrow position, so the popover is open I can't see the arrow anymore.

```
let Mypopover = (props) =>{

const outerStyle={
   ...props.style
   left: props.arrowOffsetLeft
}
  return <Popover {...props}  arrowOffsetTop={props.arrowOffsetTop +10} style={}>
}
```

I also check the source code from the document [here](https://github.com/react-bootstrap/react-bootstrap/blob/v0.33.1/src/Popover.js#L81). it looks like I should be able pass positionLeft without update arrowPosition

Can someone help me how to fix this issue without overwriting each other? I need to update **positionLeft and arrowOffSetTop both**. Thanks!

----

version:  0.33.1 (I know it's old, but my workplace still use this version)
React: 16.9
codeSandbox: https://codesandbox.io/s/hardcore-worker-lpcsd?file=/src/App.js

**Comment by kyletsang** [comment]
If you're just looking to offset the entire popover along with the arrow, it should be enough to use `positionLeft` and `positionTop`

See https://codesandbox.io/s/sleepy-fog-v6p1su?file=/src/App.js
