### ISSUE TITLE
How to use custom breakpoints in components and types?

### ISSUE THREAD

**Issue by nandastone** [react-bootstrap/react-bootstrap#6247]
I have customised the breakpoints available in the Bootstrap, and would like components such as `<Col />` and `<Container />` to accept the new breakpoint values.

The breakpoints can be customised in Bootstrap SASS via the `$grid-breakpoints` SASS variable. For example:

```
$grid-breakpoints: (
  xs: 0,
  sm: 576px,
  md: 768px,
  lg: 992px,
  xl: 1200px,
  xxl: 1400px,
  // -- New breakpoint!
  xxxl: 1600px,
);
```

Result:

![CleanShot 2022-02-15 at 10 48 12](https://user-images.githubusercontent.com/199204/153971483-f4b32ef9-5c96-4d72-9fb3-37758de02302.png)

**Comment by kyletsang** [comment]
We'll probably have to loosen the types for breakpoints to allow for custom ones.  What version of bootstrap are you using?

**Comment by nandastone** [comment]
Bootstrap version 5.1.3.
