### ISSUE TITLE
Setting React Bootstrap  activeIndex freezes all further carousel navigation

### ISSUE THREAD

**Issue by laurencefass** [react-bootstrap/react-bootstrap#6262]
### Prerequisites

- [X] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [X] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug

Reference documentation: https://react-bootstrap.github.io/components/carousel/

When I load my page I want to set an initial index for the carousel slide and then allow the user to continue navigation through carousel slides. This doesnt work because if I set activeIndex on the props I am then unable to navigate to further slides as all navigation controls are disabled. Setting activeIndex appears to fix the slide to the value set. 

I dont think this is correct: under normal operation (i.e. activeIndex not explicitly set) the carousel loads the default slide 0 and it does not freeze the carousel slide at 0. Likewise I can see no reason why setting the activeIndex to a non-default value should freeze the carousel.

### Expected behavior

Setting <Carousel activeIndex> to a non-default value should not freeze navigation on the carousel. I was expecting it to set the initial value and then allowing normal navigation.

### Reproducible Example

This is a minimal example exactly demonstrating the issue.

https://codesandbox.io/s/react-bootstrap-carousel-active-index-shoi7e

Note Carousel settings....

    <Carousel interval={null} activeIndex={1}>
     {items}
    </Carousel>

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of React-Bootstrap are you using?

2.1.0

### What version of Bootstrap are you using?

5.1.3

**Comment by kyletsang** [comment]
Use `defaultActiveIndex` instead of `activeIndex`.  The "default" prop is used for uncontrolled components.

I noticed this is missing in the docs and should be added.  PRs welcome.

**Comment by laurencefass** [comment]
Thanks I have tried defaultActiveIndex which has enabled navigation but for reasons I dont understand I cant set the activeIndex from an effect only when I initialise the component. Has this got something to do with controlled/uncontrolled components? I forked the other sandbox. See line 31. The Carousel is not responding to this change.
https://codesandbox.io/s/react-bootstrap-carousel-defautlativeindex-f3x54f

Thank you.

**Comment by laurencefass** [comment]
apologies for repeating the comment I kind of mixed up two issues into one... 

i have discovered that activeIndex wont work on its own it needs the feedback loop from onSelect event to feedback in the change. This is not entirely intuitive and I dont think works entirely in harmony with the react "re-render when props change" idea but this is no longer an issue for me. Thanks for your time and consideration.

**Comment by jquense** [comment]
> I dont think works entirely in harmony with the react "re-render when props change" idea but this is no longer an issue for me. Thanks for your time and consideration.

For some context, this is actually an idiomatic React pattern. It mirrors how how `input`s work in React, where providing `value` requires an `onChange` this enables a top down data flow, that prevents children components from "de syncing" their state with what their parent components think is the right state.
