### ISSUE TITLE
Toast onClose fire automatically callback when mount

### ISSUE THREAD

**Issue by mredodos** [react-bootstrap/react-bootstrap#6268]
### Prerequisites

- [X] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [X] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug

hi, when i add in onClose  attribute a specific callback, when the component mount the callback is fired automatically.

 <Toast className="d-inline-block m-1" bg={(msgs.var) ? msgs.var.toLowerCase() : "info"} key={index} onClose={closeSpecificToast(index)} show={showFlashMessage} animation={true} ref={wrapperRef}>

if i write this all work as expected 

<Toast className="d-inline-block m-1" bg={(msgs.var) ? msgs.var.toLowerCase() : "info"} key={index} onClose={(index) => appDispatch({ type: "closeFlashMessages", id: index})} show={showFlashMessage} animation={true} ref={wrapperRef}>

how can i solve this ? 

### Expected behavior

callback should not start automatically if the component is mounted

##

### What version of React-Bootstrap are you using?

last

### What version of Bootstrap are you using?

last

**Comment by kyletsang** [comment]
Seems like you have a typo

```
onClose={closeSpecificToast(index)}
```

should be this?
```
onClose={() => closeSpecificToast(index)}
```

**Comment by mredodos** [comment]
why this not work ?onClose={closeSpecificToast(index)}
