### ISSUE TITLE
submenus

### ISSUE THREAD

**Issue by acthp** [react-bootstrap/react-bootstrap#627]
Are there any examples using dropdown-submenu?

**Comment by acthp** [comment]
Ah, I see they were removed from bootstrap. Not sure what the alternative is.

**Comment by harshayburadkar** [comment]
Were you able to get a good alternative? I am also looking for a way to do submenus, have you found anything that works similarly.

**Comment by acthp** [comment]
@harshayburadkar No.

**Comment by harshayburadkar** [comment]
Oh, I actually got one after posting here. So if anyone is looking, this one works. 
react-menu-list
https://github.com/StreakYC/react-menu-list

You need to add your styling and documentation is decent.
