### ISSUE TITLE
Docs typo at react-bootstrap

### ISSUE THREAD

**Issue by jongjunpark** [react-bootstrap/react-bootstrap#6270]
### Prerequisites

- [X] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [X] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug

Docs typo at react-bootstrap. this can be find in red circle area of the attached image.

`defaultActiveindex` props not working. it is camel-case typo.

### Reproducible Example

have to change it to `defaultActiveIndex`. it is working very well.

### Screenshots

![image](https://user-images.githubusercontent.com/60080679/158091554-5882536e-0e0d-4fd8-a7bf-981a8f8fa414.png)

### What version of React-Bootstrap are you using?

latest version

### What version of Bootstrap are you using?

latest version

**Comment by werner33** [comment]
I opened a PR for this issue here: https://github.com/react-bootstrap/react-bootstrap/pull/6271
