### ISSUE TITLE
Overlay placement position doesn't work as intended if the placement contains top, bottom, bottom-start, etc but works fine if the placement is left or right.

### ISSUE THREAD

**Issue by BozhidarKabzamalovMM** [react-bootstrap/react-bootstrap#6272]
### Prerequisites

- [X] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [X] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug

I had to upgrade a project's dependencies which included Bootstrap v4 to v5 and React-Bootstrap v1 to v2. After upgrading, I noticed that every overlay that had placement position containing top, bottom, bottom-start, etc was not working correctly and the tooltip was way out of position. After being unable to figure out what was going on, I went to the documentation hoping to find any clues as to why this may be happening. This is when I noticed that the Overlay example also breaks, albeit in a different way, if I change the placement to top, bottom, bottom-start, etc. It DOESN'T break if the placement is left or right.

Then I decided to create a codesandbox in which I copied and pasted the example - https://codesandbox.io/s/heuristic-chaplygin-kqporr?file=/src/App.js . Seeing as the issue was also happening here, I ruled out that the issue might be caused by anything inside my project, since even happens on the example. Interestingly the tooltip changes its position to the correct one if the user resizes their browser.

### Expected behavior

I expect that the placement of the tooltip would be right beneat the button if the placement is set to bottom-start, but that's not the case.

### To Reproduce

1. Go to https://codesandbox.io/s/heuristic-chaplygin-kqporr?file=/src/App.js
2. Click the button -> the tooltip appears but its placement is wrong
3. Resize browser -> the tooltip placement fixes to what its supposed to be
4. Refresh the page and click the button again -> the tooltip appears with wrong placement again
5. Click the button again -> the tooltip disappears and you can see it flicker under the button with the correct placement for a brief moment

### Reproducible Example

https://codesandbox.io/s/heuristic-chaplygin-kqporr?file=/src/App.js

### What operating system(s) are you seeing the problem on?

Windows, macOS, Linux

### What browser(s) are you seeing the problem on?

Chrome, Safari, Firefox, Microsoft Edge, Opera

### What version of React-Bootstrap are you using?

2.2.1

### What version of Bootstrap are you using?

5.1.3

**Comment by BozhidarKabzamalovMM** [comment]
> For your custom overlay, try adding the style `position: absolute`.

On the Overlay or the PickerValues component that appears on click?

            <Overlay target={pickerRef.current} show={isOpen} placement={overlayPlacement}>
                {(props) => (
                    <PickerValues {...props}>
                        {colors.map((color) => (
                            <Color
                                key={color}
                                $color={baseColors[color]}
                                onClick={() => {
                                    onSelect(color);
                                    setSelectedColor(baseColors[color]);
                                    setIsOpen(false);
                                }}
                            />
                        ))}
                    </PickerValues>
                )}
            </Overlay>

**Comment by kyletsang** [comment]
Apply it to PickerValues

For example, using the sandbox you posted above:

```
          <div
            {...props}
            style={{
              position: 'absolute',
              backgroundColor: "rgba(255, 100, 100, 0.85)",
              padding: "2px 10px",
              color: "white",
              borderRadius: 3,
              ...props.style
            }}
          >
            Simple tooltip
          </div>
```
