### ISSUE TITLE
Manually opening an Accordion item, but still keeping control

### ISSUE THREAD

**Issue by cgarrovillo** [react-bootstrap/react-bootstrap#6279]
If I use `activeKey`, I lose all functionality of the accordion itself, and need to handle each and every `onClick` of `Accordion.Header`s myself.

How do I manually open an Accordion open, but keep the same functionality?

**Comment by kyletsang** [comment]
Use the `activeKey` along with `onSelect` in `Accordion`.  This also covers the headers so you don't need to implement individual `onClick`s
