### ISSUE TITLE
Discussion: Admin Dashboard Templates

### ISSUE THREAD

**Issue by MGatner** [react-bootstrap/react-bootstrap#6289]
Can anyone recommend resources for finding opinionated templates built with `react-bootstrap`? The library name is generic enough that it is near impossible to find templates that are actually downstream, and popular enough that sorting through the Dependencies tab is the old needle-in-a-haystack.

**Comment by jquense** [comment]
in general for themes that are CSS only (e.g. no new javascript) any bootstrap theme should work

**Comment by gordonk** [comment]
latest versions of https://appstack-react.bootlab.io uses react-bootstrap & bootstrap 5

develop license is about $60 and worth every penny

I'm not associated, just a customer.

**Comment by jacksonkeating** [comment]
Thanks @MGatner for asking this question. I’m looking forward to seeing some additional replies. 

I’ve been really struggling with trying to find a template recently as well.

**Comment by MGatner** [comment]
We went with [Volt](https://demo.themesberg.com/volt-react-dashboard/#/dashboard/overview). Their free version is very feature-generous and the team was very easy to talk with when we wanted to upgrade.
