### ISSUE TITLE
Specifying props for nested anchor components

### ISSUE THREAD

**Issue by derflocki** [react-bootstrap/react-bootstrap#629]
Edited (14 aug 2015):
These look to be the components that currently lack this feature:

- [x] `MenuItem`
- [ ] `NavItem`
- [ ] `PageItem`
- [ ] `Pagination`

--
The MenuItem currently only passes a few props (`href`, `target`, `title`) to the containing `<a>`, the bulk is applied to the `<li>`. I suggest passing the props `download`, `media`, `ping`, `rel`, `type` (I'm specifically trying to add the `download`-attribute) to the `<a>`.

What do you think?

**Comment by mtscout6** [comment]
Related to #526 

I hadn't though about that, but this sounds reasonable.

**Comment by AlexKVal** [comment]
The same `bad API` problem as in https://github.com/react-bootstrap/react-bootstrap/pull/764

I propose to resolve these both issues by just adding `propsForAnchor` "multi-property" ?

What do you think guys ?
@react-bootstrap/collaborators

**Comment by chrisvfritz** [comment]
I'd personally love a `propsForAnchor`. Then there's no need to pass a huge list of props, which could never be sufficient anyway, because data attributes would be excluded.

**Comment by taion** [comment]
Or `anchorProps`? I like being able to save typing for the commonly-used props, though.

**Comment by chrisvfritz** [comment]
:+1: for anchorProps. While I also like saving typing in general, I also worry that implicitly passing props to different components might get tricky. For example, in a component containing a SafeAnchor where you're also allowed to change the element type, a user might change it to something where props normally only passed to the anchor would be valid. While it saved users typing, I worry that it could be a source of bugs and a maintenance headache for maintainers. This way, we also don't have to deal with scoping the names of *some* props, like linkId.

**Comment by taion** [comment]
These look to be the components that currently lack this feature:

- [ ] `MenuItem`
- [ ] `NavItem`
- [ ] `PageItem`
- [ ] `Pagination`
- [ ] `SubNav` (what is this? it's not documented and I only see it in use in our docs)

**Comment by AlexKVal** [comment]
@taion I've moved your list to the first message for this:
<img width="936" alt="screen shot 2015-08-14 at 11 22 51 am" src="https://cloud.githubusercontent.com/assets/847572/9270006/e6c13064-4276-11e5-8121-8323beae7e2e.png">

**Comment by legomind** [comment]
Any status on this? I am really needing style prop for the anchor element in the NavItem

**Comment by illing2005** [comment]
Any updates here?
Would be great, if one can add a href attribute to the pagination buttons.

**Comment by taion** [comment]
We accept PRs.

**Comment by taion** [comment]
Okay, so let's be consistent here.

Which props should be top-level props that get directly forwarded to the `<a>`? Which should be spread from `anchorProps`?

**Comment by taion** [comment]
Let's handle this the way `<MenuItem>` does. Instead of spreading everything onto the `<li>`, spread only `className` and `style` there, while spreading the rest of the props onto the anchor.

**Comment by taion** [comment]
This doesn't make any sense for `<Pagination>`. I'll handle it for `<PaginationButton>` though.

**Comment by taion** [comment]
Fix is on https://github.com/taion/react-bootstrap/tree/anchorProps. Will PR after we merge https://github.com/react-bootstrap/react-bootstrap/pull/1756.

**Comment by taion** [comment]
Fixed by #1801.

**Comment by Deelux** [comment]
Did this get added? I am trying to add props to my navigation so I can make it display a name based on the current state. Is that now possible?

**Comment by jquense** [comment]
all extra props are passed to the anchor by default now

**Comment by Deelux** [comment]
From where? I tried just passing it to the parent but that didn't work. Should I pass them to nav? or to which element?

**Comment by jquense** [comment]
the NavItem, check out #1801 for the details

**Comment by borodean** [comment]
It's impossible to pass `className` and `style` to the anchor thought. I'd be happy to make a PR, but I'm not sure about the preferable implementation approach.

**Comment by taion** [comment]
Why do you need to? Just use a nested selector on `.foo a` or `.foo > a`.

**Comment by borodean** [comment]
@taion in my particular case there is a third-party Bootstrap theme that relies on `.page-link` elements having an additional special class when they contain an icon. Right now to provide it, I have to either modify that theme (which will become a mess when updates to it are published) or do the render hijacking of the `PageItem` component to allow anchor classes to be set.

**Comment by taion** [comment]
If you want to add some sort of `anchorProps` PR, we'd accept it per the original issue spec.

Note that the current (TWBS v4 compatible) API no longer has these issues because of the way the components are laid out.
