### ISSUE TITLE
Wrap every other Pagination sub-components with React.forwardRef

### ISSUE THREAD

**Issue by borzaka** [react-bootstrap/react-bootstrap#6295]
### Is your feature request related to a problem? Please describe

I'am using React with Next.js and I tried to implement the [Pagination](https://react-bootstrap.netlify.app/components/pagination/#pagination) component with Next.js's [Link](https://nextjs.org/docs/api-reference/next/link). Everything worked fine, until I started to use the `First`/`Prev`/`Next`/`Last` sub-components.

The following error appeared in the console:
`Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?
`

My original code with error:
```
<Link
  href={createHref(page + 1)}
  shallow={true}
  passHref={true}
  key="page_next"
>
  <Pagination.Next disabled={!(page < maxPage && moreThanOnePage)} />
</Link>
```

I ended up using like this, which fixes the issue, but not so convenient:
```
<Link
  href={createHref(page + 1)}
  shallow={true}
  passHref={true}
  key="page_next"
>
  <Pagination.Item disabled={!(page < maxPage && moreThanOnePage)}>
    <span aria-hidden="true">›</span>
    <span className="visually-hidden">Next</span>
  </Pagination.Item>
</Link>
```

### Describe the solution you'd like

Wrap also the `First`/`Prev`/`Next`/`Last` sub-components with [React.forwardRef](https://reactjs.org/docs/react-api.html#reactforwardref)
Also consider wrapping the `Ellipsis` as well, but I couldn't figure out its real purpose :)

### Additional context

From Next.js docs:
- [If the child is a functional component](https://nextjs.org/docs/api-reference/next/link#if-the-child-is-a-functional-component)

**Comment by golota60** [comment]
Hi! Thanks for the issue - the solution you described should be alright, created a PR implementing it

cc @kyletsang
