### ISSUE TITLE
OverlayTrigger not working in React 18 StrictMode

### ISSUE THREAD

**Issue by wKovacs64** [react-bootstrap/react-bootstrap#6296]
### Prerequisites

- [X] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [X] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug

OverlayTrigger does not appear to work in React 18 [StrictMode](https://reactjs.org/docs/strict-mode.html). Nothing happens when the overlay would normally be triggered.

### Expected behavior

OverlayTrigger would behave normally in StrictMode.

### To Reproduce

1. Wrap the appropriate branch of your component tree in `React.StrictMode`
2. Render an `OverlayTrigger`
3. Observe it not working

### Reproducible Example

https://codesandbox.io/s/react-bootstrap-overlaytrigger-react-18-uo5xhc?file=/src/App.js

### What operating system(s) are you seeing the problem on?

Windows, macOS

### What browser(s) are you seeing the problem on?

Chrome, Firefox

### What version of React-Bootstrap are you using?

2.2.2

### What version of Bootstrap are you using?

5.1.3

### Additional context

react@18.0.0
react-dom@18.0.0

**Comment by kyletsang** [comment]
Same root cause as #6284

Will release a new version shortly

**Comment by kyletsang** [comment]
Released in v2.2.3
