### ISSUE TITLE
Remove `@types/*` from dependencies

### ISSUE THREAD

**Issue by gmukul01** [react-bootstrap/react-bootstrap#6299]
### Prerequisites

- [X] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [X] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug

`@types/*` being added in `dependencies` instead of `devDependencies`.

### Expected behavior

`@types/*` should be added in `devDependencies`

### Reproducible Example

There are no steps to reproduce it.

### What version of React-Bootstrap are you using?

2.2.2

### What version of Bootstrap are you using?

5.1.3

**Comment by jquense** [comment]
Types are supposed to be in dependencies because they need to be installed when some one installs the package. Other wise typescript will not be able to correctly typecheck when you use react-bootstap

**Comment by kyletsang** [comment]
The react types should've been deduped if you already have it in declared in your project package.json?  It shouldn't have installed a copy of the react 18 types.

Can you try this command in your project?  `npm ls @types/react`

**Comment by gmukul01** [comment]
@kyletsang This is the result of `npm ls @types/react`.  I have also fixed the version of `@types/react` to `17`.  

<img width="361" alt="image" src="https://user-images.githubusercontent.com/3636885/163799317-fb812f07-946f-4142-8557-2bb6ef3e5d89.png">

**Comment by golota60** [comment]
related: https://github.com/facebook/react/issues/24304#issuecomment-1094565891

>Declaring @types/react as an (optional) peer dependency is the correct solution.

 [here's](https://github.com/mui/material-ui/blob/564de537968e3f42d21b3ac2c85db81559566ba5/packages/mui-base/package.json#L44) how MUI does it cc @kyletsang

**Comment by kyletsang** [comment]
Optional peer deps is the correct approach.  I think we've tried adding this in the past but most people were still on versions of npm that doesn't support this.  It's been long enough now, so I've opened #6303 to properly clean this up.
