### ISSUE TITLE
Module '"react-bootstrap"' has no exported member 'CardHeader'

### ISSUE THREAD

**Issue by silvioprog** [react-bootstrap/react-bootstrap#6304]
### Prerequisites

- [X] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [X] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug

I am trying to use `CardHeader`, but it seems not exported.

### Expected behavior

Should allow to use `CardHeader`, since it is a useful component.

### To Reproduce

Just try to declare a `CardHeader` component as:

```ts
import { CardHeader } from 'react-bootstrap';
```

### What version of React-Bootstrap are you using?

Latest stable

### What version of Bootstrap are you using?

Latest stable

### Additional context

Error: `Module '"react-bootstrap"' has no exported member 'CardHeader'`

**Comment by golota60** [comment]
Hi! Thanks for the issue 😄 
`Card.Header` is a part of and should be used inside a `Card` component, like this:
```ts
<Card>
  <Card.Header>Title</Card.Header>
  {/*...*/}
</Card>
```
[docs](https://react-bootstrap.github.io/components/cards/#header-and-footer)
What's the use case for importing `CardHeader` by itself?

**Comment by silvioprog** [comment]
Oh, thanks a lot for helping. And I am sorry, I was trying to use the component trusting only in the code completion, without visiting  the documentation. 🤦‍♂️

Thank you once again and sorry for noising! 😅
