### ISSUE TITLE
Form.Control maxLength property is ignored on mobile.

### ISSUE THREAD

**Issue by yianniw** [react-bootstrap/react-bootstrap#6307]
### Prerequisites

- [X] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [X] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug

On Desktop it works fine, but on my Android I'm able to go over the field length.

### Reproducible Example

<Form.Control type="text" maxLength="16" />

### What operating system(s) are you seeing the problem on?

Android

### What browser(s) are you seeing the problem on?

Chrome, Firefox, Microsoft Edge

### What version of React-Bootstrap are you using?

2.2.3

### What version of Bootstrap are you using?

5.1.3

**Comment by kyletsang** [comment]
We forward all props to the underlying input element, so this is a bug with the mobile browser on your android device.  This isn't a bug with react-bootstrap.
