### ISSUE TITLE
Using arrow keys on Dropdown menu throws error

### ISSUE THREAD

**Issue by andrej-ilic** [react-bootstrap/react-bootstrap#6308]
### Prerequisites

- [X] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [X] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug

When using arrow keys to go through a dropdown menu an error gets thrown.

### To Reproduce

1. Create Dropdown menu (or open example)
2. Click on dropdown button to show menu
3. Press up/down arrow key - first dropdown item is highlighted
4. Press up/down arrow key again
5. Error "Cannot read properties of undefined (reading 'nextElementSibling')" is thrown

### Reproducible Example

https://codesandbox.io/s/react-bootstra-dropdown-bug-c7sjcc

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of React-Bootstrap are you using?

2.2.3

### What version of Bootstrap are you using?

5.1.3

**Comment by kyletsang** [comment]
Remove the bootstrap JS from your index.html and this should work.  React-bootstrap is a replacement for the bootstrap JS so you don't need it.
