### ISSUE TITLE
Navbar Offcanvas not showing nav items with `expand` prop

### ISSUE THREAD

**Issue by GanjiyevR** [react-bootstrap/react-bootstrap#6309]
### Prerequisites

- [X] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [X] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug

The offcanvas navbar component found here https://react-bootstrap.github.io/components/navbar/#offcanvas is very similar to the one found in regular bootstrap - and I've tried to make this one function like the one in regular bootstrap, so once your window is at a certain size (expand="lg"), so 992px, the navbar will then collapse into its offcanvas format, rather than appearing as a normal navbar - but instead the normal navbar doesn't appear, instead disappearing and leaving me with just a gray bar.

### Expected behavior

I expected the navbar to function like so:

https://getbootstrap.com/docs/5.1/examples/offcanvas-navbar/#

### To Reproduce

1. Go to https://react-bootstrap.github.io/components/navbar/#offcanvas
2. Replicate the code
3. Change "expand={false}" to expand="lg"
4. Note that the navbar doesn't function as original bootstrap intended.

### Reproducible Example

https://react-bootstrap.github.io/components/navbar/#offcanvas

### Screenshots

![Collapsed](https://user-images.githubusercontent.com/96064338/164889902-2c69c089-c60e-43b7-829f-0180fb152988.png)

![Non Collapsed](https://user-images.githubusercontent.com/96064338/164889907-c51c9047-84ca-4a03-863b-c55eca740e9b.png)

Note that until it is collapsed, nothing appears on the navbar besides the brand, which is outside of the offcanvas.

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of React-Bootstrap are you using?

2.3.0

### What version of Bootstrap are you using?

5.1.3

**Comment by jacknugent** [comment]
I see the same issue. I created a [simple repo using Create React App](https://github.com/jacknugent/react-bootstra-bug/blob/main/src/App.tsx) to recreate the error. You should be able to see for yourself just by running `npm install`, `npm start`, then making your screen past the `lg` size:

<img width="1053" alt="image" src="https://user-images.githubusercontent.com/31449177/164914930-2ca59271-1cdf-4191-8d5f-cde903b50804.png">

**Comment by kyletsang** [comment]
Looks like the example at https://getbootstrap.com/docs/5.1/examples/offcanvas-navbar is a different example than the one in https://getbootstrap.com/docs/5.1/components/navbar/?#offcanvas

The bug with the existing implementation is that the offcanvas is only rendered when toggled via button.  We need to always render it in the navbar container.

**Comment by GanjiyevR** [comment]
> Looks like the example at https://getbootstrap.com/docs/5.1/examples/offcanvas-navbar is a different example than the one in https://getbootstrap.com/docs/5.1/components/navbar/?#offcanvas
> 
> The bug with the existing implementation is that the offcanvas is only rendered when toggled via button. We need to always render it in the navbar container.

Wouldn't that be under the bit below? This bit in particular - https://i.imgur.com/5bhVoAW.png
