### ISSUE TITLE
Do not add `position-absolute` if `className` has `position-*`

### ISSUE THREAD

**Issue by tkesgar** [react-bootstrap/react-bootstrap#6315]
### Is your feature request related to a problem? Please describe

ToastContainer hard-codes `position-absolute` utility class, making it impossible to replace it with `position-fixed`:

```jsx
    return (
      <Component
        ref={ref}
        {...props}
        className={classNames(
          bsPrefix,
          position && `position-absolute ${positionClasses[position]}`,
          className,
        )}
      />
    );
```

Code: https://github.com/react-bootstrap/react-bootstrap/blob/master/src/ToastContainer.tsx#L81

https://github.com/react-bootstrap/react-bootstrap/issues/5799 is relevant; I'd like to know if there is a preferred solution for this.

### Describe the solution you'd like

Check the `className` to see if there are any `position-*` classes:

```jsx
      <Component
        ref={ref}
        {...props}
        className={classNames(
          bsPrefix,
          position && `${classNameHasPosition ? '' : 'position-absolute'} ${positionClasses[position]}`,
          className,
        )}
      />
```

This seems to be the most backward-compatible approach. The most difficult part would be to define `classNameHasPosition`, because `className` has a very flexible type (can be strings, array, etc.).

#### Add a new prop that defaults to `absolute` if `position` is provided

```jsx
<ToastContainer position="bottom-center" anchoring="fixed">
```

This change should be backward-compatible and relatively easier to implement than the solution above. However, I am not sure about the new property name 🙃 

#### Extend the possible values for `position`

```jsx
<ToastContainer position="absolute-bottom-center">
<ToastContainer position="fixed-bottom-center">
```

While this change should be backward-compatible, the enumeration will increase the component size. 

#### Do nothing; let users add `position-fixed` class

```jsx
<ToastContainer position="bottom-center" className="position-fixed">
```

This is suggested in https://github.com/react-bootstrap/react-bootstrap/issues/5799.

I tested and it seems to work on Chrome; however, I am not sure if this is correct because [class order in HTML does not seem to be relevant](https://stackoverflow.com/questions/15670631/does-the-order-of-classes-listed-on-an-item-affect-the-css).

#### Remove `position` prop entirely, force users to use the Bootstrap utility classes

```jsx
<ToastContainer className="position-fixed bottom-0 start-50 translate-middle-x">
```

This breaks existing `ToastContainer` usage. However, this will make the component simpler and removes dependency to Bootstrap utility class.

### Additional context

The current workaround is to not use `position` prop and directly uses the relevant Bootstrap utility classes:

```jsx
<ToastContainer className="position-fixed bottom-0 start-50 translate-middle-x">
```

If I have the solution, I think I can submit a PR for this.

**Comment by kyletsang** [comment]
Hmm, I suppose we could go with a prop called `containerPosition` that defaults to `absolute`, but the naming is a bit unfortunate and might cause some confusion.  It's probably ok as long as the docs are clear though.
