### ISSUE TITLE
Dropdown's onToggle documentation about callback parameters are wrong (type is not assignable to type error)

### ISSUE THREAD

**Issue by borzaka** [react-bootstrap/react-bootstrap#6318]
### Prerequisites

- [X] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [X] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug

The Dropdown's `onToggle` callback function has different parameters in the [docs](https://react-bootstrap.github.io/components/dropdowns/#api).

**Docs:**
```js
function(
  isOpen: boolean,
  event: SyntheticEvent,
  metadata: {
    source: 'select' | 'click' | 'rootClose' | 'keydown'
  }
): void
```

**DropdownProps:**
```js
function(
  nextShow: boolean,
  meta: ToggleMetadata,
): void
```

My IDE (PhpStorm) on the `onToggle` attribute says:
> TS2322: Type '(isOpen: any, event: any, metadata: any) => void' is not assignable to type '(nextShow: boolean, meta: ToggleMetadata) => void'.

### Expected behavior

No type error on the `onToggle` event when used correctly from the official docs.

### Reproducible Example

```js
const ExampleDropdown = () => {
  const [show, setShow] = useState(true);

  return (
    <Dropdown
      show={show}
      onToggle={(isOpen, event, metadata) => {
        setShow(isOpen);
      }}
    >
      <Dropdown.Toggle variant="success" id="dropdown-basic">
        Dropdown Button
      </Dropdown.Toggle>

      <Dropdown.Menu>
        <Dropdown.Item href="#/action-1">Action</Dropdown.Item>
        <Dropdown.Item href="#/action-2">Another action</Dropdown.Item>
        <Dropdown.Item href="#/action-3">Something else</Dropdown.Item>
      </Dropdown.Menu>
    </Dropdown>
  );
};
```

### Screenshots

![image](https://user-images.githubusercontent.com/1230402/166295568-1a601946-be95-45be-ac73-00343430fa5c.png)

### What operating system(s) are you seeing the problem on?

macOS, Linux

### What browser(s) are you seeing the problem on?

Chrome

### What version of React-Bootstrap are you using?

2.3.1

### What version of Bootstrap are you using?

5.1.3

**Comment by kyletsang** [comment]
The TS types are the correct one.  We need to update the docs to reflect that.  Interested in opening a PR?
