### ISSUE TITLE
react-native support ? 

### ISSUE THREAD

**Issue by mydearxym** [react-bootstrap/react-bootstrap#632]
amazing work!
is those component support react-native?

**Comment by mtscout6** [comment]
I have not tested them on mobile, nor has that been my focus yet. If you can get it to work, we'd be interested in any added documentation necessary to make it work.

**Comment by taion** [comment]
What does "support react-native" mean in this context? I thought the main motivation there was to render with native components, rather than the HTML/CSS-based components here.

**Comment by mtscout6** [comment]
I honestly don't know anything about react-native so I'll defer to folks that know about it for now.

**Comment by taion** [comment]
It's like React, but rendering to native iOS (for now, Android support coming later) components in the context of a native app. I don't think this is relevant - certainly you could use React Bootstrap components within a WebView in a native app, but actual native components themselves are not a relevant target.

I'm going to flag this as invalid and close for now, but please let me know if I've made an error.

**Comment by dozoisch** [comment]
@taion No you are right, it doesn't make sense in a native env, because bootstrap doesn't exist at all as of right now. Maybe that could be a new lib under react-bootstrap to try and port some of the components like layouts, inputs to native.

**Comment by AlexKVal** [comment]
@dozoisch said it right. 
It has to be another one, standalone project to support react-native,
because of totally different concerns. (`browser` vs `native GUI`)

**Comment by mydearxym** [comment]
maybe use webView inside react-native is the better choice~
