### ISSUE TITLE
Dropdown.Menu does not close properly if it contains 'd-grid' in className

### ISSUE THREAD

**Issue by MinHuang-TW** [react-bootstrap/react-bootstrap#6324]
### Prerequisites

- [X] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [X] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug

This issue occurred after upgrading both bootstrap and react-bootstrap to the latest versions

### Reproducible Example

https://codesandbox.io/s/focused-sound-q9hi38?file=/src/App.js

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome

### What version of React-Bootstrap are you using?

2.3.1

### What version of Bootstrap are you using?

5.1.3

**Comment by andrewdetorres** [comment]
Hi @MinHuang-TW,

When the dropdown menu is `show` the dropdown menu has a `display: block` from the `show` class. When you added the `d-grid` class, this was adding a `display: grid` that was causing the menu to be shown at all times.

I've attached a new codesandbox to demonstrate how to conditionally apply this class. You can see the example dropdown as 'Custom with d-grid':
https://codesandbox.io/s/cool-frost-4es9t9

**Comment by MinHuang-TW** [comment]
> Hi @MinHuang-TW,
> 
> When the dropdown menu is `show` the dropdown menu has a `display: block` from the `show` class. When you added the `d-grid` class, this was adding a `display: grid` that was causing the menu to be shown at all times.
> 
> I've attached a new codesandbox to demonstrate how to conditionally apply this class. You can see the example dropdown as 'Custom with d-grid': https://codesandbox.io/s/cool-frost-4es9t9

The solution works as expected, thank you @andrewdetorres !
