### ISSUE TITLE
Sometimes React Bootstrap doesn't style components without CDN 

### ISSUE THREAD

**Issue by nnabicse** [react-bootstrap/react-bootstrap#6326]
React bootstrap doesn't works with installed package. Then we have to use the cdn which is sometimes slow.

**Comment by golota60** [comment]
Hi! Please create an issue using a [issue template](https://github.com/react-bootstrap/react-bootstrap/blob/master/.github/ISSUE_TEMPLATE/bug_report.yml), so that we have enough context and information about your problem - there's currently not enough information to help you out - thanks!
