### ISSUE TITLE
Dropdown menu is not visible

### ISSUE THREAD

**Issue by Chris55** [react-bootstrap/react-bootstrap#6328]
### Prerequisites

- [X] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [X] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug

Looks like Dropdown is not working as expected.

Nothing happens when I click on the button.

### Expected behavior

A click on DropDown  Button should open a menu, but nothing happens.

### To Reproduce

I'm using demo code from [here](https://react-bootstrap-v4.netlify.app/components/dropdowns/#single-button-dropdowns)

### Reproducible Example

full example [here](https://codesandbox.io/s/dropdown-not-working-6g8rv0)

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome

### What version of React-Bootstrap are you using?

1.6.4

### What version of Bootstrap are you using?

4.6.1

**Comment by kyletsang** [comment]
This is an issue with React 18.  As a workaround, disable strict mode until we can get a patch out.

**Comment by kyletsang** [comment]
Fixed in 1.6.5
