### ISSUE TITLE
Form.File:  Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

### ISSUE THREAD

**Issue by Maverick23** [react-bootstrap/react-bootstrap#6332]
### Prerequisites

- [X] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [X] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug

When using <Form.File> getting the below error :
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
This was working in pervious version, tested it with ^1.3.0. 
Please note that Form is imported and other file Form.Group, Form.Label etc are working fine.

### To Reproduce

include <Form.File> in the code .

### Reproducible Example

import {Form} from "react-bootstrap";

function randomName () {

return(<> <Form.File></Form.File></>)
}

export default  randomName

### Screenshots

![image](https://user-images.githubusercontent.com/2720929/167897298-506af4a6-e179-4fea-973c-2a9d42ad3030.png)

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of React-Bootstrap are you using?

2.3.0

### What version of Bootstrap are you using?

NA

### Additional context

--

**Comment by kyletsang** [comment]
Please read the release notes when updating to major releases as they do contain breaking changes

https://react-bootstrap.github.io/migrating/#formfile
