### ISSUE TITLE
Feature

### ISSUE THREAD

**Issue by alsanchez-dev** [react-bootstrap/react-bootstrap#6339]
### Is your feature request related to a problem? Please describe

Table row when adding a new item by a user action 

### Describe the solution you'd like

I'd want to implement animation on each new row when a user adds a new item, so that is visible that a new item has been added to the table. Is this possible with react-bootstrap tables?

### Describe alternatives you've considered

CSS animations

**Comment by alsanchez-dev** [comment]
I'm considering using 
```
<Collapse in={open}>
    <tr></tr>
</Collapse>
```

And a setTimeout to expand it, any ideas on how to make it work?

**Comment by alsanchez-dev** [comment]
Any heads up on this issue?

**Comment by kyletsang** [comment]
This question is best suited for Stackoverflow or discord.  See https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md#issues

**Comment by alsanchez-dev** [comment]
It's ok, I already solved it myself, in case somebody else asks in the future I did it by using CSS key frames to style a new row that I detect by knowing the time from the creation of the new row from the backend so it is a less than 20 seconds ago I add a class that has been animated.
