### ISSUE TITLE
Offcanvas form clearing on setShow(false)/handleClose

### ISSUE THREAD

**Issue by nathanjfield** [react-bootstrap/react-bootstrap#6341]
### Prerequisites

- [X] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [X] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug

I have a simple form within an Offcanvas component. I am handling the submission of the form and preventing default actions through `preventDefault()`. I have also set the 'scroll' option to true, and 'backdrop' to false, so that I can verify that submitting the form does not clear the contents.

For some reason when the Offcanvas is closed (via the 'ESC' key, close button, or any other method) the form itself is cleared. I would like the form to retain its selections/properties when the offcanvas is not visible. I cannot see why would be happening according to the documentation

### Expected behavior

I would expect the form to stay populated unless cleared.

### Reproducible Example

```
const [show, setShow] = useState(false);
const handleClose = () => setShow(false);
const handleShow = () => setShow(true);

const onFormSubmit = e => {
  e.preventDefault()
  e.stopPropagation();
}

<Button variant="secondary" onClick={handleShow}>
More Filters
</Button>

<Offcanvas show={show} onHide={handleClose} scroll={true} backdrop={false}>
  <Offcanvas.Header closeButton>
    <Offcanvas.Title>Filters</Offcanvas.Title>
  </Offcanvas.Header>
<Offcanvas.Body>
  <Form id="filterForm" onSubmit={onFormSubmit}>
  <Button variant="primary" type="submit" >
      Apply
  </Button>
  <br /><br />

    <h6>Department</h6>
        <Form.Check name={'dept'} label={'Department1'} value={"department = 'Department 1'"} />
        <Form.Check name={'dept'} label={'Department2'} value={"department = 'Department 2'"} />
        ))}
  <br />
  </Form>
</Offcanvas.Body>
</Offcanvas>
```

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Microsoft Edge

### What version of React-Bootstrap are you using?

2.4.0

### What version of Bootstrap are you using?

5.2.0-beta1 and 5.1.3

**Comment by kyletsang** [comment]
Offcanvas is unmounted when it's hidden.  You'll want to use controlled components, so for your checkboxes you need to provide the `checked` prop to set the state.

**Comment by mnovio** [comment]
And how would it be done, for example, with the code of nathanjfield? I have exactly the same problem

**Comment by nathanjfield** [comment]
I can't think that controlled components will work for me as the checkboxes are generated dynamically.

```
{equipmentInfo.map((equipment, key) => (
                      // eslint-disable-next-line
                      <Form.Check name={"equip"} label={equipment.equipment} value={"equipment = " + "'" + equipment.equipment + "'"} />
))}
```

**Comment by kyletsang** [comment]
Even if your checkboxes are generated dynamically, you can still hold the check state outside of the Offcanvas

For example:
https://codesandbox.io/s/focused-glade-1t9m5d?file=/src/App.js

**Comment by mistek131995** [comment]
And if I can't store the state outside?
