### ISSUE TITLE
NPM warning ERESOLVE overriding peer dependency

### ISSUE THREAD

**Issue by IntroJoul** [react-bootstrap/react-bootstrap#6349]
### Prerequisites

- [x] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [X] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug

When installing react-bootstrap and bootstrap, NPM warns about an overriding peer dependency as seen in the screenshot

### Expected behavior

No warns

### To Reproduce

1. Run `npx create-react-app my-app` in an empty folder
2. `cd my-app`
3. Run `npm install react-bootstrap bootstrap`

### Reproducible Example

Cannot provide

### Screenshots

![image](https://user-images.githubusercontent.com/83115888/169704435-408c4010-38f6-4fbb-bd05-46269b4ceca1.png)

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Firefox

### What version of React-Bootstrap are you using?

2.4.0

### What version of Bootstrap are you using?

5.1.3

### Additional context

Using react@18.1.0

**Comment by kyletsang** [comment]
Need to upgrade `@react-aria/ssr` to a version that's compatible with react 18
