### ISSUE TITLE
Module not found: Can't resolve 'react-bootstrap/Container

### ISSUE THREAD

**Issue by ks1990cn** [react-bootstrap/react-bootstrap#6350]
### Prerequisites

- [X] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [X] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug

I am working on ASP .net Core with React application.

I've already installed & verified react-bootstrap.

I'm unable to find any solution for this: **Module not found: Can't resolve 'react-bootstrap/Container'**

Following is working fine for me
import { Row, Col, Grid } from 'react-bootstrap'

Please find attached screenshot.

Please let me know in case i'm using wrong version

### Reproducible Example

1.) Create React application with asp .net core in Visual studio 2019.
2.) Create own functional component
3.) try importing Container from react-bootstrap/Container
4.) Run application

### Screenshots

![Versions](https://user-images.githubusercontent.com/29522704/169888894-c0374b38-4599-4ade-bf33-4716a0edbf94.PNG)
![ContainerModuleNotFound](https://user-images.githubusercontent.com/29522704/169888911-ea08af9a-df09-461a-970a-80fe9e205393.PNG)

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of React-Bootstrap are you using?

0.31.5

### What version of Bootstrap are you using?

3.4.1

**Comment by kyletsang** [comment]
You're trying to use a component from Bootstrap 4 and above.

Bootstrap 3 docs are here:
https://react-bootstrap-v3.netlify.app/

I don't recommend starting a new project with it though since it's very old and no longer maintained.

**Comment by ks1990cn** [comment]
Thank you, upgrading to latest helped me!
