### ISSUE TITLE
Bug- Carousel breaks when changing Carousel.item's mid slide transition

### ISSUE THREAD

**Issue by dsaisho** [react-bootstrap/react-bootstrap#6352]
### Prerequisites

- [X] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [X] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug
(check gif in screenshots section)
When the carousel is transitioning from one slide to another, if another entry from a dataset is chosen before the slide finishes its transition, the new images are rendered, but controls/timer are broken, so the carousel is not slidable any more (manually or automatically).

More details and code example here:
https://stackoverflow.com/questions/72357593/react-bootstrap-carousel-breaks-when-changing-content-during-transition

### Expected behavior

the new dataset loads new Carousel.item's and the carousel is able to transition between slides.

### To Reproduce

Replicate- https://codesandbox.io/s/frosty-night-yckxro (thanks to @IgorGonak)

onload, immediately click the down arrow on the dropdown to expose options, mouse over option b, wait for transition to happen, click b rite in the middle of the transition. observe controls wont work for the 'b' dataset

### Reproducible Example

Replicate- https://codesandbox.io/s/frosty-night-yckxro (thanks to @IgorGonak)

onload, immediately click the down arrow on the dropdown to expose options, mouse over option b, wait for transition to happen, click b rite in the middle of the transition. observe controls wont work for the 'b' dataset

### Screenshots
https://www.saishostaging.com/assets/react-bootstra-carousel-broken.gif

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of React-Bootstrap are you using?

latest

### What version of Bootstrap are you using?

latest

### Additional context

everything works if there is no transition animation.

**Comment by kyletsang** [comment]
Looks like the issue is the `isSliding` bool isn't reset because the children change before the `onEntered` callback is triggered.

https://github.com/react-bootstrap/react-bootstrap/blob/dd4191190b118840351f5cd8e20ccc7add3e98a8/src/Carousel.tsx#L389

This would prevent the `previous` and `next` funcs from being triggered due to this condition:
https://github.com/react-bootstrap/react-bootstrap/blob/dd4191190b118840351f5cd8e20ccc7add3e98a8/src/Carousel.tsx#L327

**Comment by kyletsang** [comment]
Don't think there's much we could really do here.  Since your app knows when the carousel contents will change, it's probably better for you to reset the carousel component on your side.

Can you add `key={activeFish.name}` to your `Carousel` and try reproducing the issue?

For ex:
```
<Carousel
  key={activeFish.name}
>
```

**Comment by dsaisho** [comment]
> Don't think there's much we could really do here. Since your app knows when the carousel contents will change, it's probably better for you to reset the carousel component on your side.
> 
> Can you add `key={activeFish.name}` to your `Carousel` and try reproducing the issue?
> 
> For ex:
> 
> ```
> <Carousel
>   key={activeFish.name}
> >
> ```

ah that was one of the first things I tried with no success :(

**Comment by kyletsang** [comment]
Try this sandbox:
https://codesandbox.io/s/stupefied-kirch-z416ph

I can control the carousel after changing the children mid slide

**Comment by dsaisho** [comment]
> Try this sandbox: https://codesandbox.io/s/stupefied-kirch-z416ph
> 
> I can control the carousel after changing the children mid slide

Yo! that did it, shoot, I must have set with a non dynamic key when I first tried.  thanks again for putting more time into this(and sorry u had to due to my incompetency), u da man!

**Comment by enix79** [comment]
Hello @kyletsang and thank you for your help! It's working, but can you explain why? In another sandbox I tried to rerender the whole carousel when data changes, but the bug was still there. My understanding is that the whole component should be recreated:
```

const renderCarousel = useCallback(() => {
    console.log("render carousel");
    return (
      <Carousel
        interval={2000}
        style={{ height: 200, width: 300 }}
      >
        {activeFish["Image Gallery"].map((img) => {
          return (
            <Carousel.Item key={img.title}>
              <img className="d-block w-100" src={img.src} alt={img.alt} />
              <Carousel.Caption>{img.title}</Carousel.Caption>
            </Carousel.Item>
          );
        })}
      </Carousel>
    );
  }, [activeFish]);
```
Why is react still "caching" component here, but not when you use key prop?
 

https://codesandbox.io/s/hungry-danilo-ub7jwv

**Comment by kyletsang** [comment]
@enix79 , react is responsible for diffing the previous render result and the incoming result during the reconciliation phase.  You can read more about it here: https://reactjs.org/docs/reconciliation.html

There's a special case where if a key is provided, react ends up unmounting the previous instance and mounting a new one.
