### ISSUE TITLE
Feature Request: Sortable table columns

### ISSUE THREAD

**Issue by ryanmcalpine** [react-bootstrap/react-bootstrap#6355]
### Is your feature request related to a problem? Please describe

I've been trying to work out a solution for sorting a react-bootstrap table by clicking on the column header, but the only relevant StackOverflow post I found suggests using a different library, react-bootstrap-table, instead. I use react-bootstrap all throughout this project though (including for unsorted tables on a number of other pages), and I'd rather not have to refactor this page to use a different library for its tables than the rest of the application.

I searched the Issues here on github and it seems the last time this feature was requested was in 2015, so I figured I should ask again and make it known that there are still users who would like to see this implemented!

### Describe the solution you'd like

Ideally I would love for a simple `sort=true` option for the `<th>` tag, similar to [how it's done in the react-bootsrtap-table2 library](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/basic-sort.html).

### Additional context

It definitely feels odd to be asking for a feature that already exists in a similar library, but react-bootstrap does so much more than just tables and it's already being used throughout the twenty-something other pages of this application, so it would be really nice if I could just continue using react-bootstrap tables as I have been rather than refactoring all my tables to use a separate library just for one additional feature.

Thanks for taking the time to read my request!

**Comment by jquense** [comment]
Hi there thanks for the request. The goal of RB is to match what plain bootstrap others in terms of features and components. Something like this is outside the scope of the presentational table components which are simple wrappers around html elements. If you'd like use the RB table component and enhance it with more features I'd recommend pairing it with `react-table` or if you just need sorting it's pretty straightforward to build on top of the components without new dependencies
