### ISSUE TITLE
DropdownButton 

### ISSUE THREAD

**Issue by PurrBiscuit** [react-bootstrap/react-bootstrap#6356]
### Prerequisites

- [X] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [X] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug

Adding a class to the `DropdownButton` component doesn't seem to apply anything to the actual button rendered in the DOM.  For example, this:

```javascript
  <DropdownButton
    className="mt-2"
  >
    ...
  </DropdownButton>
```

Results in this `<button>` element being rendered (without the `mt-2` class):

```html
<button class="dropdown-toggle btn btn-primary" type="button" aria-expanded="false">
</button>
```

### Expected behavior

I would expect the `<button>` element to have the `mt-2` class applied to it, like:

```html
<button class="dropdown-toggle btn btn-primary mt-2" type="button" aria-expanded="false">
</button>
```

### To Reproduce

Apply the `className` prop to the `DropdownButton` component.

```javascript
  <DropdownButton
    className="mt-2"
  >
    ...
  </DropdownButton>
```

### Reproducible Example

```javascript
  <DropdownButton
    className="mt-2"
  >
    ...
  </DropdownButton>
```

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Firefox

### What version of React-Bootstrap are you using?

2.1.2

### What version of Bootstrap are you using?

5.1.3

**Comment by kyletsang** [comment]
DropdownButton is a shorthand for writing the example shown here:  https://react-bootstrap.github.io/components/dropdowns/#single-button-dropdowns

The class that you pass actually gets rendered on the `<div class="dropdown">` element.  If you're looking to pass the class to the toggle, you'll need to write the full form like in the link above, then pass class to the DropdownToggle.
