### ISSUE TITLE
Navbar.Offcanvas break SSR (hydration error) after v2.3.1

### ISSUE THREAD

**Issue by Yizhachok** [react-bootstrap/react-bootstrap#6359]
### Prerequisites

- [X] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [X] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug

After https://github.com/react-bootstrap/react-bootstrap/pull/6310 fix (v2.3.1) SSR rendering is broken and throw an error when trying to use NavbarOffcanvas https://react-bootstrap.github.io/components/navbar/#offcanvas . On version 2.3.0 everything is working.

### Expected behavior

No hydration error.

### To Reproduce

`npm start`

### Reproducible Example

https://github.com/Yizhachok/react-bootstrap-offcanvas-bug

### Screenshots

<img width="812" alt="image" src="https://user-images.githubusercontent.com/1171048/170835017-a5b4f1a6-d853-4f50-8c2a-11ac1f78d59e.png">
<img width="1042" alt="image" src="https://user-images.githubusercontent.com/1171048/170835788-ed30b641-92c4-455e-bbcd-1cf9db0dc6af.png">

### What version of React-Bootstrap are you using?

2.4.0

### What version of Bootstrap are you using?

5.1.3

### Additional context

If screen on device is smaller than breakpoint to show canvas we have no error if bigger error throws. I think problem in initial calculation of breakpoint size.

**Comment by neelhabib** [comment]
I am facing the same issue. However after building the app, there is now error. Please resolve.
