### ISSUE TITLE
Accordion.Item as='details' doesn't work properly

### ISSUE THREAD

**Issue by YaBoiBreezy** [react-bootstrap/react-bootstrap#6372]
### Prerequisites

- [X] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [X] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug

Accordion.Item as='details' doesn't work, the details tag operates independently of the accordion tab instead of meshing properly. You need to open the details tab and click the accordion button to see the tab, the buttons are mutually exclusive but the details tabs are all independent of each other so you can open multiple simultaneously.

edit: I think this may be a feature request, not a bug. I can't figure out how to change the label, sorry about that
Feature request: make Accordion.item have special handlers for details elements

### Expected behavior

An accordion that is styled like a column of details elements

### Reproducible Example
```
<Accordion>
  <Accordion.Item eventKey="k" as="details">
    <Accordion.Header as="summary">t</Accordion.Header>
    <Accordion.Body>c</Accordion.Body>
  </Accordion.Item>
</Accordion>
```

### What version of React-Bootstrap are you using?

2.1.1

### What version of Bootstrap are you using?

IDK

**Comment by YaBoiBreezy** [comment]
If someone does add this feature, I think the code is something like
```
if (as==='details){
{panels.map((item) => (
              <details
                open={item.id === openID}
                id={item.id}
                onToggle={(e) => {
                  if ((e.target as HTMLDetailsElement).open) {
                    setOpenID((e.target as Element).id);
                  }
                }}}

**Comment by kyletsang** [comment]
The accordion html needs to follow a specific structure.  You're probably better off rolling your own component if you want to use `details`
