### ISSUE TITLE
Modal backdrop is behind modal div, so cursor styles on backdrop dont work

### ISSUE THREAD

**Issue by YaBoiBreezy** [react-bootstrap/react-bootstrap#6373]
### Is your feature request related to a problem? Please describe

I'm using a modal as a lightbox and want a custom cursor to appear whenever the cursor leaves the modal, indicating that you can click to close it. However when I hook the css up via Modal backdropClassName it gets applied to a div that is a sibling of the main modal (class=modal), and since the background has a smaller z-index the cursor doesn't change.

### Describe the solution you'd like

cursor styles on the backdrop div to apply whenever the cursor is outside of the modal

### Describe alternatives you've considered

I was able to make it work by applying the cursor css to Modal, then overriding it in Modal.Body, but this should still be implemented somehow

**Comment by kyletsang** [comment]
Since this suggestion is for the css, consider opening this as a suggestion in Bootstrap's repo:  https://github.com/twbs/bootstrap

We only deal with the react implementation here and not styling.
