### ISSUE TITLE
Collapse

### ISSUE THREAD

**Issue by ldavidsp** [react-bootstrap/react-bootstrap#6375]
How can I implement this I see that there is no documentation on this topic https://getbootstrap.com/docs/5.2/components/collapse/

**Comment by jquense** [comment]
Did you search the documentation? There is a Collapse component with docs

**Comment by jbalatero** [comment]
There is no docs for the collapse component currently.

**Comment by jbalatero** [comment]
Actually, Just found this: https://github.com/react-bootstrap/react-bootstrap/blob/master/www/src/examples/Collapse.js
