### ISSUE TITLE
Feature: Allow setting `fill` for `<Tabs>` as it's possible for `<Nav>`

### ISSUE THREAD

**Issue by AgainPsychoX** [react-bootstrap/react-bootstrap#6382]
### Is your feature request related to a problem? Please describe

Allow setting `fill` for `<Tabs>` as it's possible for `<Nav>`

`<Nav>` itself has:

<html>
<body>

Name | Type | Default | Description
-- | -- | -- | --
fill | boolean | false | Have all NavItems proportionately fill all available width.
justify | boolean | false | Have all NavItems evenly fill all available width.
navbar | boolean |   | Apply styling an alignment for use in a Navbar. This prop will be set automatically when the Nav is used inside a Navbar.

</body>
</html>

which would be ncie to be possible to pass to the `<Tabs>` which uses the `<Nav>` inside anyway.

### Describe the solution you'd like

Either add those few fields directly to `<Tabs>`, or make some proxy pass attribute, like `tabAttrs` is for `<Tab>`.

**Comment by kyletsang** [comment]
Looks like it's just a matter of updating the types to extend from `NavProps`

**Comment by mateusbw** [comment]
Hello @kyletsang ! Can i work on this one?

**Comment by kyletsang** [comment]
@mateusbw sure go for it, thanks!
