### ISSUE TITLE
Adding classes to nav-tabs

### ISSUE THREAD

**Issue by web2style** [react-bootstrap/react-bootstrap#639]
I'm using the tabs component and I want to add a class to it. If I do so:
```
<TabbedArea className="text-center dashed">
```
it adds these classes to both `<nav>` and `<ul class="nav nav-tabs">` elements. So the output is the following:

```
<nav class="text-center dashed">
    <ul class="text-center dashed nav nav-tabs">...</ul>
</nav>
```

Looks like a bug. It should add the classes to only one element, in my case it is `<ul>`. But I think it is better to have possibility to add classes to both elements individually.

**Comment by taion** [comment]
This is the same as #422.
