### ISSUE TITLE
Modal event handlers: Include event

### ISSUE THREAD

**Issue by derwaldgeist** [react-bootstrap/react-bootstrap#6401]
### Is your feature request related to a problem? Please describe

Our modal is embedded in a component that itself has an `onClick` handler. To prevent triggering this, we would like to stop event propagation if the modal is being closed. But `onHide` does not deliver any event.

### Describe the solution you'd like

All modal event handler calls should contain the triggering event.

### Describe alternatives you've considered

Yes, I could place my modal outside of the component. But that makes it a bit cumbersome.

**Comment by kyletsang** [comment]
Can you post a code example of what your component looks like?
