### ISSUE TITLE
Bug <Container> issue with <Navbar> 

### ISSUE THREAD

**Issue by thunt4jr** [react-bootstrap/react-bootstrap#6404]
### Prerequisites

- [X] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [X] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug

<Container> issue keeps causing <Nav.Link> to redirect the url to 404 error page. 

### Expected behavior

direct to proper link

### To Reproduce

      <Navbar variant='dark' fixed='top' collapseOnSelect expand='lg'>
        <Container>
          <Navbar.Brand href='/'>
            <img alt='' src={logo} width={"75"} height={"75"} />
          </Navbar.Brand>
          <Navbar.Toggle aria-controls='basic-navbar-nav' />
          <Navbar.Collapse id='basic-navbar-nav'>
            <Nav className="m-auto">
              <Nav.Item>
                <Nav.Link href='/artificial-reefs'>Artificial Reefs</Nav.Link>
              </Nav.Item>
              <Nav.Item>
                <Nav.Link href='/marine-ecosystems'>Marine EcoSystems</Nav.Link>
              </Nav.Item>
              <Nav.Item>
                <Nav.Link href='/photos-videos'>Photos & Videos</Nav.Link>
              </Nav.Item>
              <Nav.Item>
                <Nav.Link href='#contact'>Contact</Nav.Link>
              </Nav.Item>
            </Nav>
          </Navbar.Collapse>
        </Container>
      </Navbar>
Publish and Push to Git so it will go to Netlify 

### Reproducible Example

import React from "react";
import { Container, Nav, Navbar } from "react-bootstrap";
import logo from "../../../images/reefmaker.png";

export const TopMenuDark = () => {
  return (
    <>
      <Navbar variant='dark' fixed='top' collapseOnSelect expand='lg'>
        <Container>
          <Navbar.Brand href='/'>
            <img alt='' src={logo} width={"75"} height={"75"} />
          </Navbar.Brand>
          <Navbar.Toggle aria-controls='basic-navbar-nav' />
          <Navbar.Collapse id='basic-navbar-nav'>
            <Nav className="m-auto">
              <Nav.Item>
                <Nav.Link href='/artificial-reefs'>Artificial Reefs</Nav.Link>
              </Nav.Item>
              <Nav.Item>
                <Nav.Link href='/marine-ecosystems'>Marine EcoSystems</Nav.Link>
              </Nav.Item>
              <Nav.Item>
                <Nav.Link href='/photos-videos'>Photos & Videos</Nav.Link>
              </Nav.Item>
              <Nav.Item>
                <Nav.Link href='#contact'>Contact</Nav.Link>
              </Nav.Item>
            </Nav>
          </Navbar.Collapse>
        </Container>
      </Navbar>
    </>
  );
};

### Screenshots

![Screenshot_1](https://user-images.githubusercontent.com/13003749/180051260-05216ff9-5f4c-478f-a186-d30f9dc693a9.png)
![Screenshot_2](https://user-images.githubusercontent.com/13003749/180051265-890f0111-cc6c-4d0c-8e73-df6b26ac9536.png)

### What operating system(s) are you seeing the problem on?

Windows, Android

### What browser(s) are you seeing the problem on?

Chrome, Firefox

### What version of React-Bootstrap are you using?

2.4.0

### What version of Bootstrap are you using?

5.2.0

**Comment by kyletsang** [comment]
This sounds like an site error where the page /artificial-reefs doesn't exist.

**Comment by thunt4jr** [comment]
It is doing that for every top link on the top Navbar. When I remove the
<Container> then it works fine.



Thanks,

**Comment by thunt4jr** [comment]
`    <>
    <Navbar fixed="top">
      <Container>
        <Navbar.Brand href="/">
          <img alt="" src={logo} height="45" />
        </Navbar.Brand>
        <Nav className="m-auto">
        <Nav.Item>
          <Nav.Link href="/artificial-reefs">Artificial Reefs</Nav.Link>
        </Nav.Item>
        <Nav.Item>
          <Nav.Link href="/marine-ecosystems">Marine EcoSystems</Nav.Link>
        </Nav.Item>
        <Nav.Item>
          <Nav.Link href="/photos-videos">Photos & Videos</Nav.Link>
        </Nav.Item>
        <Nav.Item>
          <Nav.Link href="#contact">Contact</Nav.Link>
        </Nav.Item>
        </Nav>
      </Container>
    </Navbar>
    </>`

**Comment by thunt4jr** [comment]
```
    <>
    <Navbar fixed="top">
      <Container>
        <Navbar.Brand href="/">
          <img alt="" src={logo} height="45" />
        </Navbar.Brand>
        <Nav className="m-auto">
        <Nav.Item>
          <Nav.Link href="/artificial-reefs">Artificial Reefs</Nav.Link>
        </Nav.Item>
        <Nav.Item>
          <Nav.Link href="/marine-ecosystems">Marine EcoSystems</Nav.Link>
        </Nav.Item>
        <Nav.Item>
          <Nav.Link href="/photos-videos">Photos & Videos</Nav.Link>
        </Nav.Item>
        <Nav.Item>
          <Nav.Link href="#contact">Contact</Nav.Link>
        </Nav.Item>
        </Nav>
      </Container>
    </Navbar>
    </>
```

**Comment by thunt4jr** [comment]
This works on localhost:3000 but not on Netlify. 
But the footer works fine as <a></a>

**Comment by thunt4jr** [comment]
react-router-dom issue with Netlify and requires to have _redirects file in the public folder with ```/* /index.html 200```
This issue is fixed.
