### ISSUE TITLE
Update react and types

### ISSUE THREAD

**Issue by jeevasusej** [react-bootstrap/react-bootstrap#6406]
I thought to add some additional function for accordion. But when I build the application I am getting the following exception and noticed that the react and some packages are outdated. 
Please update 

![image](https://user-images.githubusercontent.com/19813131/180367130-b115f2c7-9818-476c-ab62-a54c52cbea1a.png)

**Comment by kyletsang** [comment]
`ForwardedRef` is in the installed types.  Try `yarn bootstrap` again to reinstall
