### ISSUE TITLE
[2.5.0 beta1] Offcanvas body mounted twice

### ISSUE THREAD

**Issue by afrz** [react-bootstrap/react-bootstrap#6411]
### Prerequisites

- [X] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [X] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug

Hello,

I notice a breaking change using **react-bootstrap@2.5.0-beta.1** 

A component used in an Offcanvas body is :
- mounted at initial render (standard case)
- then unmounted & remounted again (why ?)

Such behavior (unmounting/remounting step) does not happen using **react-bootstrap@2.4.0**

It does not seems to come from React Strict Mode (see reproducible sample)

### Expected behavior

No unmounting/remounting is expected during initial render.

### To Reproduce

1. Go to [codesandbox.io](https://codesandbox.io/s/determined-rain-11d3ok?file=/src/App.js)
2. Check console
3. You should see "mount/unmount/mount" message (only 1 mount is expected)

### Reproducible Example

https://codesandbox.io/s/determined-rain-11d3ok?file=/src/App.js

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of React-Bootstrap are you using?

2.5.0-beta.1

### What version of Bootstrap are you using?

5.1.3

**Comment by kyletsang** [comment]
Thanks for flagging.  This is due to the responsive behavior we added in the beta.  We should be able to restore the original behavior if `responsive` is not used.  

I think ultimately, I'll need to rework the Offcanvas in the next major version.
