### ISSUE TITLE
Missing type `md` in ModalProps size

### ISSUE THREAD

**Issue by AscendingEagle** [react-bootstrap/react-bootstrap#6412]
### Prerequisites

- [X] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [X] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug

The interface `ModalProps` has the incorrect size type:
`size?: 'sm' | 'lg' | 'xl';`

`md` is missing in the definition but works as expected if passed in.

### Expected behavior

The type should be:
`size?: 'sm' | 'md' | 'lg' | 'xl';`

### Reproducible Example

```
function test() {
  return <Modal size='md'>
    <Modal.Header />
    <Modal.Body></Modal.Body>
  </Modal>
}
```

### Screenshots

![image](https://user-images.githubusercontent.com/41471114/181306498-36475b6c-9a72-4969-a0c2-3628f0afe6ef.png)

### What version of React-Bootstrap are you using?

2.5.0-beta.1

### What version of Bootstrap are you using?

5.2.0-beta1

**Comment by kyletsang** [comment]
By default the modal renders as "medium" and there is no corresponding class to it, so that's why `md` isn't an explicit option
