### ISSUE TITLE
Using Nav.Link with "href" prop cause blinking pages instead of "to" prop

### ISSUE THREAD

**Issue by Yvres-Vreucheu** [react-bootstrap/react-bootstrap#6413]
### Is your feature request related to a problem? Please describe

I have a header with several items inside and i use React bootstrap "Nav.Link" for designing it with the "href" property (e.g `<Nav.Link href="/home">Active</Nav.Link>).`
When i click on my links, it always blinks to a white page before rendering the content. When i use "Link" from react-router (e.g `<Link to="/about">About</Link>`) there is no blink. I can redesign my header without bootstrap but it's a pain ......

### Describe the solution you'd like

Using Nav.Link with "to" prop or without this blink effect

**Comment by kyletsang** [comment]
You can use custom link components with react router dom:
https://reactrouter.com/docs/en/v6/examples/custom-link

Or alternatively check out react-router-bootstrap
