### ISSUE TITLE
React-transition-group not found in node modules of react-bootstrap files

### ISSUE THREAD

**Issue by Faizan-Khalid99** [react-bootstrap/react-bootstrap#6414]
`Failed to compile,
Module not found: Error: Can't resolve 'react-transition-group/Transition' in 'C:\Users\user\whoDunItCats-frontend\node_modules\react-bootstrap\esm'
ERROR in •/node_modules/react-bootstrap/esm/Collapse.js4:6-87
Module not found: Error: Can't resolve 'react-transition-group/Transition' in 'C:\Users\user WhoDunItCats-frontend\ node codules\react-bootstraplesm'
ERROR in •/node_modules/react-bootstrap/esm/Fade.js4:0-70
Module not found: Error: Can't resolve 'react-transition-group/Transition' in 'C: Users\user WhoDunItCats-frontend\node_rodules\react-bootstrap\esm'
ERROR in ./node_modules/react-bootstrap/esm/OffcanvasToggling.js3:0-79
Module not found: Error: Can't resolve 'react-transition-group/Transition' in 'C:\Users\userWWhoDunItCats-frontend\node_rodules\react-bootstraplesm'
ERROR in ./node_modules/react-bootstrap/esm/ToastFade.js2:6-70
Module not found: Error: Can't resolve 'react-transition-group/Transition' in 'C: \Users\user
inItCats-frontend\node_rodules\react-bootstraplesm'
ERROR in ./node_modules/react-bootstrap/esm/Transitionkrapper.js2:8-59
Module not found: Error: Can't resolve 'react-transition-group/Transition' in 'C: \Users\user\WhoDunItCats-frontend\node_modules\react-bootstrap\esm'
webpack compiled with 5 errors
7`

It is in files of react-bootstrap/esm

**Comment by Faizan-Khalid99** [comment]
![image](https://user-images.githubusercontent.com/86584248/181919505-6aeb272c-41aa-4dac-b106-ace1f989c538.png

**Comment by wik-z** [comment]
same error here

**Comment by Faizan-Khalid99** [comment]
The issue is in react-transition-group v4.4.3. It ends up empty, Once that is solved it will work again. So, for now the solution is @wik-z  to just run ` npm install react-transition-group@4.4.2 `

**Comment by faizy99** [comment]
UPDATE: react-transition-group@4.4.4 or the latest version has fixed the missing files bug

**Comment by Faizan-Khalid99** [comment]
UPDATE: the latest version has fixed the missing files. Just delete your node modules and lock files and install every dependency once again.
