### ISSUE TITLE
Bug Offcanvas or Offcanvas example not working

### ISSUE THREAD

**Issue by charitygrace** [react-bootstrap/react-bootstrap#6417]
### Prerequisites

- [X] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [X] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug

I have implemented your Offcanvas responsive code exactly as described in the docs using a forked version of your basic sandbox example: see https://codesandbox.io/s/adoring-lumiere-pg0hqp for the responsive offcanvas implementation trial

The offcanvas body does not show at larger widths as occurs in your documentation and is supposed to happen.

### Expected behavior

Offcanvas body should show inline at larger widths, but does not.

### To Reproduce

implement responsive offcanvas example: https://react-bootstrap.netlify.app/components/offcanvas/#responsive

### Reproducible Example

https://codesandbox.io/s/adoring-lumiere-pg0hqp

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome

### What version of React-Bootstrap are you using?

2.0.0

### What version of Bootstrap are you using?

5.1.3

**Comment by kyletsang** [comment]
Responsive offcanvas requires bootstrap 5.2 and react-bootstrap 2.5.0 beta
