### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by myas92** [react-bootstrap/react-bootstrap#6418]
### Prerequisites

- [X] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [X] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug

I want to create a mega menu, according to the tutorial, I can change the styles of components with [variant](https://react-bootstrap.github.io/getting-started/theming/) property

so, I used to [navbar](https://react-bootstrap.github.io/components/navbar/) component to create a mega menu.

I want to change the `dropdown's` style like this component in `navbar`, not `nav`

![dropdown](https://user-images.githubusercontent.com/10220082/182297955-ca3de0d8-2f5a-4cf9-8a15-4ba1b7308ac6.png)

When I want to change `dropdown's` style, I have to change `.dropdown-menu` directly like the code below:
```
.dropdown-menu {
  padding: 1em;
}
```
Is there any way to change the `dropdown's` style in the `dropdown` menu of `navbar` with the `variant` property?

### Reproducible Example

It's my code to create a mega menu
```html
<Container style={{ padding: 0 }}>
<Navbar
  collapseOnSelect
  expand="md"
  style={{ paddingLeft: 0, paddingRight: 0 }}
>
  <Navbar.Collapse id="basic-navbar-nav navbar-collapse">
    <Nav className="ms-auto mt-3">
      <NavDropdown
        className="pe-2 py-2 align-text-top"
        style={{backgroundColor: "red"}}
        title="Integrations"
        id="basic-nav-dropdown"
      >

        <Container className="integrationsNav pt-0 mt-0" style={{backgroundColor: "lightblue", margin: 0, padding:0 }}>
          <Row>
            <Col xs="12" md="6" className="text-start">
              <Dropdown.Header>
                <FontAwesomeIcon
                  color="black"
                  icon={"arrow-down"}
                  size="1x"
                  className="pe-1"
                />{" "}
                Sources
              </Dropdown.Header>
              <Dropdown.Item>
                <Link href="/integrations/sources/snowflake" passHref>
                  <Nav.Link>Snowflake Integration</Nav.Link>
                </Link>
              </Dropdown.Item >
              <Dropdown.Item>
                <Link href="/integrations/sources/postgres" passHref>
                  <Nav.Link>Postgres Integration</Nav.Link>
                </Link>
              </Dropdown.Item>
              <Dropdown.Divider className="d-lg-none" />
            </Col>

            <Col xs="12" md="6" className="text-start">
              <Dropdown.Header>
                <FontAwesomeIcon
                  color="black"
                  icon={"arrow-up"}
                  size="1x"
                  className="pe-1"
                />{" "}
                Destinations
              </Dropdown.Header>
              <Dropdown.Item>
                <Link
                  href="/integrations/destinations/salesforce"
                  passHref
                >
                  <Nav.Link>Salesforce Data Integration</Nav.Link>
                </Link>
              </Dropdown.Item>
            </Col>
          </Row>
        </Container>
      </NavDropdown>

      <div className="nav-link">
        <Link href="/pricing" passHref>
          <Nav.Link> Pricing</Nav.Link>
        </Link>
      </div>
    </Nav>
  </Navbar.Collapse>
</Navbar>
```

### What version of React-Bootstrap are you using?

2.4.0

### What version of Bootstrap are you using?

5.2.0

**Comment by kyletsang** [comment]
You would have to modify your css directly for the customization you're thinking of.  Variant/sizes in that doc link refers to generating custom classes like `btn-xxl` or `btn-mycolorname`, etc and passing the appropriate value to the component prop.
