### ISSUE TITLE
Modal Aria Description applied to the wrong element

### ISSUE THREAD

**Issue by jussiq** [react-bootstrap/react-bootstrap#6421]
### Prerequisites

- [X] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [X] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug

The modal component produces a dialog where the aria-describedby -attribute gets applied to a wrong element. 

### Expected behavior

aria-describedby -attribute is applied to the dialog at the same level with aria-labelledby

### To Reproduce

1. Go to vertically centered modal (BS4) https://react-bootstrap-v4.netlify.app/components/modal/#modal-vertically-centered
2. Add attribute to Modal-element source: aria-describedby="contained-modal-content-vcenter"
3. Add corresponding id to Modal.Body: <Modal.Body id="contained-modal-content-vcenter">
4. Launch the modal
5. Inspect the HTML-source and notice that aria-describedby is set at different level compared to aria-labelledby

### Reproducible Example

1. Go to vertically centered modal (BS4) https://react-bootstrap-v4.netlify.app/components/modal/#modal-vertically-centered
2. Add attribute to Modal-element source: aria-describedby="contained-modal-content-vcenter"
3. Add corresponding id to Modal.Body: <Modal.Body id="contained-modal-content-vcenter">
4. Launch the modal
5. Inspect the HTML-source and notice that aria-describedby is set at different level compared to aria-labelledby

### What operating system(s) are you seeing the problem on?

Windows, macOS, Linux

### What browser(s) are you seeing the problem on?

Chrome
Firefox

### What version of React-Bootstrap are you using?

1.6.5

### What version of Bootstrap are you using?

4.6.1

### Additional context

With the latest version this works as expected (can be similarly reproduced at https://react-bootstrap.netlify.app/components/modal/#modal-vertically-centered) but 1.X.X should be still maintained

**Comment by jussiq** [comment]
Screen shot of combining steps 2, 3 and 5 numbered
![Screenshot from 2022-08-03 12-42-21](https://user-images.githubusercontent.com/35757761/182583656-afbd664d-a5aa-42c9-a845-f803f93a2a09.png)

**Comment by kyletsang** [comment]
Should backport https://github.com/react-bootstrap/react-bootstrap/commit/48f7c078d07af5f9266923ef04c3e85a836dcfa9 and https://github.com/react-bootstrap/react-bootstrap/commit/93a8a0ef29409293dd69fad5873ad791634b3ed1

**Comment by kyletsang** [comment]
Fixed in #6422
