### ISSUE TITLE
onChange event being triggered twice when input decimal for number type Form.control

### ISSUE THREAD

**Issue by xiaotaozi1127** [react-bootstrap/react-bootstrap#6423]
### Prerequisites

- [X] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [X] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug

onChange event being triggered twice when input decimal for **number** type Form.control.
for example, when i input 3.5 in the number, onChange events will be triggered twice. 
first time, event.target.value is 3
second time, event.target.value is 3.5

### Expected behavior

onChange event should be triggered one time with the final decimal value 3.5. 

### To Reproduce

run npm start, and then input any decimal value in the input box. for example: 3.5
we will print log and display the target value in onChange event.
You will see 2 logs are printed.
first time, target value is 3; 
second time, target value is 3.5

### Reproducible Example

import React from "react";

import Form from "react-bootstrap/Form";

import "./App.css";

const handleChange = (event) => {
  let targetValue = event.target.value;
  //when i type 3.5, it will be triggered twice, first time value is 3, second time value is 3.5.
  console.log("target value=" + targetValue);
};

const App = () => (
    <Form.Control type="number" defaultValue={0} onChange={handleChange} />
);

export default App;

### Screenshots

<img width="210" alt="image" src="https://user-images.githubusercontent.com/4277354/183243364-735ea03c-bdea-44f9-8aa4-bc395158a181.png">

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome

### What version of React-Bootstrap are you using?

2.5.0

### What version of Bootstrap are you using?

5.2.0

**Comment by kyletsang** [comment]
This is actually an expected behavior in react.  See https://reactjs.org/docs/dom-elements.html#onchange
