### ISSUE TITLE
Hamburger hook

### ISSUE THREAD

**Issue by gilles-hemmerle** [react-bootstrap/react-bootstrap#6427]
### Is your feature request related to a problem? Please describe

Currently on mobile, when we click a menu entry in the Nav, it closes the hamburger and display the new page, which is correct.
Now if we click a menu entry which leads to the same url than currently browsing (example `<Link to="/page1" />` when you are already displaying "/page1") , the hamburger won't close,

### Describe the solution you'd like

Some people want to keep this behaviour so I wouldn't change this behaviour by default.

Although I see 2 main approaches:

1. Create a `useNav` hook which exposes a `toggle()` function which allows to programatically change the nav menu state (show / hide)
2. Create a new property of the `Nav` component with for example `forceCloseOnBrowsingSameUrl` or something like this

### Describe alternatives you've considered
```tsx
 <Link to="/staking" className="btn btn-outline-primary" onClick={toggleHamburger}>
    Stake / Unstake
  </Link>
```
```tsx
  const toggleHamburger = () => {
    const toggler: any = document.querySelector('.Header .navbar-toggler-icon');
    if (toggler) {
      toggler.click();
    }
  };
```

**Comment by itsPrajapat** [comment]
Hello I want to work on this issue could you please help me to setup this project I am getting some error. Please help me Thanks

**Comment by fguzmang23** [comment]
I'd make use of the `expanded` and `onToggle` props `Navbar` has. attach a `onClickHandler` to every NavLink and with the help of a state var toggle/untoggle the hamburguer menu when on mobile..

import React, { useState } from 'react'
import Container from 'react-bootstrap/Container'
import { NavLink } from 'react-router-dom'
import Nav from 'react-bootstrap/Nav'
import Navbar from 'react-bootstrap/Navbar'

```
function Playing2() {
  const [expanded, setExpanded] = useState(false)

  const onClickHandler = () => {
    setExpanded(false)
  }

  const onToggle = (controls) => {
    setExpanded(controls)
  }

  return (
    <Navbar bg="light" expand="lg" collapseOnSelect expanded={expanded} onToggle={onToggle}>
      <Container>
        <Navbar.Brand href="#home">React-Bootstrap</Navbar.Brand>
        <Navbar.Toggle aria-controls="basic-navbar-nav" />
        <Navbar.Collapse id="basic-navbar-nav">
          <Nav className="me-auto">
            <NavLink to="/create-user" onClick={onClickHandler}>Create user</NavLink>
            <NavLink to="/create-post" onClick={onClickHandler}>Create post </NavLink>
            <NavLink to="/users" onClick={onClickHandler}> Users </NavLink>
          </Nav>
        </Navbar.Collapse>
      </Container>
    </Navbar>
  )
}

export default Playing2
```
