### ISSUE TITLE
Feature

### ISSUE THREAD

**Issue by erzuber** [react-bootstrap/react-bootstrap#6429]
### Is your feature request related to a problem? Please describe

Warning: React does not recognize the `ollapseOnSelect` prop on a DOM

### Describe the solution you'd like

remove collapseOnSelect from one of example of navbar

**Comment by kyletsang** [comment]
`collapseOnSelect` is a valid prop in Navbar and is not passed to the element.  Based on that warning above... do you have a typo in your prop (missing the c)?

**Comment by erzuber** [comment]
I checked and found c missing. but don't know how that is missed. because i just copy code from "https://react-bootstrap.github.io/components/navbar/" and edit for my requirement.  
really sorry for my silly mistake.
