### ISSUE TITLE
As prop uncomplete examples

### ISSUE THREAD

**Issue by Chris-titsus010** [react-bootstrap/react-bootstrap#6430]
This issue concerns the [as prop](https://react-bootstrap.github.io/getting-started/introduction/#as-prop-api) section of the doc.

> If you want to keep all the styling of a particular React-Bootstrap component but switch the component that is finally rendered (<ins>whether it's a different React-Bootstrap component</ins>, a different custom component, or a different HTML tag) you can use the `as` prop to do so.

It is said that we can pass a React-Bootstrap component, but the only example uses a regular html tag.

I suggest adding an example where a React-Bootstrap component is passed to the `as` prop since the way to do so is not straightforward in my opinion.

**Comment by kyletsang** [comment]
PRs welcome

**Comment by Shannon26** [comment]
Hi @kyletsang, Is the issue resolved?
As a beginner in Open Source Contribution, I'd want to take this on.

**Comment by kyletsang** [comment]
@Shannon26 feel free to take this one.  Thanks!

**Comment by Shannon26** [comment]
@kyletsang  we can close this issue now.
