### ISSUE TITLE
Adding non JSX Elements after migrating to version 2

### ISSUE THREAD

**Issue by Elwazer007** [react-bootstrap/react-bootstrap#6431]
### Prerequisites

- [X] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [X] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug

Can't use `react-bootstrap-icons` after migrating to version 2 of `react-bootstrap` , adding any element whose type is not JSX isn't allowed there , error message is 
```
'Download' cannot be used as a JSX component.
  Its element type 'ReactElement<any, any> | Component<Props, any, any> | null' is not a valid JSX element.ts(2786)

```

Download is simply an icon imported from `react-bootstrap-icons` like `import {Download} from 'react-bootstrap-icons` 

### Reproducible Example

```

 import {
  Download,
} from 'react-bootstrap-icons';

import {
  Button,
} from 'react-bootstrap';

const myComponent = () =>{
return (
  <Button>

       <Download/>
  </Button>

);
}

```

### What version of React-Bootstrap are you using?

2.0.0

### What version of Bootstrap are you using?

4.5.2

**Comment by kyletsang** [comment]
See https://github.com/ismamz/react-bootstrap-icons/issues/39 in react-bootstrap-icons repo.
