### ISSUE TITLE
OverlayTrigger causes LinkContainer to break

### ISSUE THREAD

**Issue by jonwgeorge** [react-bootstrap/react-bootstrap#6435]
### Prerequisites

- [X] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [X] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug

When placing OverlayTrigger inside a LinkContainer, my anchor tags href gets overridden as '#'.

### Reproducible Example

```
<LinkContainer to="/utils/dhcp">
  <OverlayTrigger
  key='opt43'
  placement='right'
  style={{}}
  overlay={
    <Tooltip id='tooltip-dhcp'>
      Tool for generating DHCP option 43 hex strings
    </Tooltip>
  }
  >
    <Nav.Link>DHCP Helper</Nav.Link>
  </OverlayTrigger>
</LinkContainer>
```

### What operating system(s) are you seeing the problem on?

Windows, macOS

### What browser(s) are you seeing the problem on?

Chrome, Safari, Firefox, Microsoft Edge

### What version of React-Bootstrap are you using?

2.5.0

### What version of Bootstrap are you using?

5.2.0

**Comment by Shannon26** [comment]
@jonwgeorge This may be due to you have a `<Nav.Link>` this component takes in `href` like `<Nav.Link href="/home">` if you do not pass href it defaults to `#`

**Comment by jonwgeorge** [comment]
Yeah, this is because I have the `<LinkContainer>` doing the routing along with react-bootstrap-router. Normally the `href` doesn't even come through. If I add an `href` I get a page reload when the link is clicked which isn't the behavior I would prefer.

**Comment by jonwgeorge** [comment]
Okay.. So after digging, if I just use `<Link>` with the same props it works. Not sure why `<LinkContainer>` doesn't work.
