### ISSUE TITLE
Purgecss is removing react-bootstrap styles from project

### ISSUE THREAD

**Issue by devhiko** [react-bootstrap/react-bootstrap#6436]
### Prerequisites

- [X] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [X] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug

As a optimization step purgecss with projects that styled with react-bootstrap, purgecss is removing react-bootstrap styles from project

### Expected behavior

When i use postcss.config.js as default, purgecss command is removing my react-bootstrap styles. it should not to do this.

### To Reproduce

1. `npm i react-bootstrap` at any project
2. make a styles to components like `className={styles.sampleclass}`
3. add this `postcss.config.js` at root directory: 
```
module.exports = {
  plugins: [
    "postcss-flexbugs-fixes",
    [
      "postcss-preset-env",
      {
        autoprefixer: {
          flexbox: "no-2009",
        },
        stage: 3,
        features: {
          "custom-properties": false,
        },
      },
    ],
    [
      "@fullhuman/postcss-purgecss",
      {
        content: ["./pages/**/*.{js,jsx,ts,tsx}", "./components/**/*.{js,jsx,ts,tsx}"],
        defaultExtractor: (content) => content.match(/[\w-/:]+(?<!:)/g) || [],
        safelist: ["html", "body"],
      },
    ],
  ],
};
```
4. run` npm run build` at terminal
5. when you deploy your styles will gone (some of them related with react-bootstrap)

### Reproducible Example

```
module.exports = {
  plugins: [
    "postcss-flexbugs-fixes",
    [
      "postcss-preset-env",
      {
        autoprefixer: {
          flexbox: "no-2009",
        },
        stage: 3,
        features: {
          "custom-properties": false,
        },
      },
    ],
    [
      "@fullhuman/postcss-purgecss",
      {
        content: ["./pages/**/*.{js,jsx,ts,tsx}", "./components/**/*.{js,jsx,ts,tsx}"],
        defaultExtractor: (content) => content.match(/[\w-/:]+(?<!:)/g) || [],
        safelist: ["html", "body"],
      },
    ],
  ],
};
```

### Screenshots

At left styles is gone, at it must be like at right. 
![a](https://user-images.githubusercontent.com/99843102/187927516-66626b50-166d-49ed-a6dd-e73795224828.png)

### What operating system(s) are you seeing the problem on?

Windows, Android

### What browser(s) are you seeing the problem on?

Chrome, Firefox, Microsoft Edge

### What version of React-Bootstrap are you using?

2.5.0

### What version of Bootstrap are you using?

5.2.0

### Additional context

It seems to be inherital. Maybe there is a fix going well purgecss with react-bootstrap, thanks.

**Comment by jquense** [comment]
PurgeCSS removes based on finding classes in source code text, so you need to point it at all the source code, including node_modules which is where the RB components are.

**Comment by devhiko** [comment]
so, how can i do that.

**Comment by jquense** [comment]
Update your content array. This isn't a RB issue it's a purge css one, and affects any dependency with styles. I would recommend checking their resources for getting support

**Comment by devhiko** [comment]
I tried content and safelist arrays to add node_modules/react-bootstrap but i noticed there is no file under /react-bootstrap except component folders but they are empty too. Here is ss. And there is a problem too, i searched deeply for purgecss and react-bootstrap there is a thoughts about they are not working well with each other. Unfortunately there is a single option to seems me only using react-bootstrap with no postcss config cuz i love react-bootstrap components and philosophy.   Windows için Posta ile gönderildi Kimden: Jason QuenseGönderilme: 1 Eylül 2022 Perşembe 17:07Kime: react-bootstrap/react-bootstrapBilgi: Hikmet; AuthorKonu: Re: [react-bootstrap/react-bootstrap] Purgecss is removing react-bootstrap styles from project (Issue #6436) Update your content array. This isn't a RB issue it's a purge css one, and affects any dependency with styles. I would recommend checking their resources for getting support—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
