### ISSUE TITLE
`Modal` doesn't have `show` class when `animation={false}`

### ISSUE THREAD

**Issue by skadermen** [react-bootstrap/react-bootstrap#6439]
### Prerequisites

- [X] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [X] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug

`.modal` element has no `show` class if `<Modal>` component has `animation={false}`.

### Expected behavior

`.modal` element has class `show` all the time Modal component is opened

### To Reproduce

1. Go to https://react-bootstrap.github.io/components/modal/#live-demo
2. Click `Launch demo modal` and check that `.modal` element has class `show`
3. Close the modal, scroll down bit to "Without Animation" example and click `Launch demo modal` there
4. Check that this `.modal` has no `show` class

### Reproducible Example

Example taken from the official documentation page

```
import React, { useState } from 'react';
import Button from 'react-bootstrap/Button';
import Modal from 'react-bootstrap/Modal';

function Example() {
  const [show, setShow] = useState(false);

  const handleClose = () => setShow(false);
  const handleShow = () => setShow(true);

  return (
    <>
      <Button variant="primary" onClick={handleShow}>
        Launch demo modal
      </Button>

      <Modal show={show} onHide={handleClose} animation={false}>
        <Modal.Header closeButton>
          <Modal.Title>Modal heading</Modal.Title>
        </Modal.Header>
        <Modal.Body>Woohoo, you're reading this text in a modal!</Modal.Body>
        <Modal.Footer>
          <Button variant="secondary" onClick={handleClose}>
            Close
          </Button>
          <Button variant="primary" onClick={handleClose}>
            Save Changes
          </Button>
        </Modal.Footer>
      </Modal>
    </>
  );
}

render(<Example />);
```

### Screenshots

![image](https://user-images.githubusercontent.com/1066971/188919061-e38795ab-af51-4618-b6a1-66736f413c09.png)

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome, Firefox

### What version of React-Bootstrap are you using?

2.4.0

### What version of Bootstrap are you using?

5.1.3

### Additional context

It's reproducible right on the official documentation page with - I assume - `bootstrap v5.2` and `react-bootstrap v2.5.0`

**Comment by golota60** [comment]
hi, nice catch! will post a pr fixing this shortly
