### ISSUE TITLE
Feature Form Select for multiple selections

### ISSUE THREAD

**Issue by cmprojectcm** [react-bootstrap/react-bootstrap#6444]
### Is your feature request related to a problem? Please describe

It is not actually a problem.

Form -> Select, indeed has option to specify for multiple selection, however it's use is not helpfull and not effective for a pro UI,

The only way you can select the multiple values is just by using the **ctrl + mouse click**, which is not helpful neither effective for a normal UI user.

The only **problem** I've noticed is that defaultValues is not working at all.

### Describe the solution you'd like

It would be nice to add more options and features to that element. 

For example, fieelds selection should be done by just using mouse click, and to deselect to just mouse click again.

Also select-all and deselect-all aptions should be created.

And finally resolve the issue of deafultValues, which is not working

**Comment by jquense** [comment]
The inputs we provide we just styled native ones, this is by design, and it's outside the scope of the library to add more complicated interactions. You can combine components to make richer interactions yourself or use some of the many other libraries (react-widgets, react-select, etc) for this. thanks!

**Comment by cmprojectcm** [comment]
> The inputs we provide we just styled native ones, this is by design, and it's outside the scope of the library to add more complicated interactions. You can combine components to make richer interactions yourself or use some of the many other libraries (react-widgets, react-select, etc) for this. thanks!

what about defaultValues, which is not working
