### ISSUE TITLE
[v4] Broken link to Open Iconic site

### ISSUE THREAD

**Issue by coliff** [react-bootstrap/react-bootstrap#6448]
### Prerequisites

- [X] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [X] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug

On the page: https://react-bootstrap-v4.netlify.app/components/forms/?#forms-custom-checkboxes-and-radios the link to Open Iconic is dead. 

### Expected behavior

I suggest it is changed to GitHub instead: https://github.com/iconic/open-iconic

### To Reproduce

1. Go to https://react-bootstrap-v4.netlify.app/components/forms/?#forms-custom-checkboxes-and-radios
2. Click on Open Iconic link

### Reproducible Example

see above

### What operating system(s) are you seeing the problem on?

Windows

### What version of React-Bootstrap are you using?

4.x

### What version of Bootstrap are you using?

4.x

**Comment by golota60** [comment]
hi! nice catch! will create a pr shortly
