### ISSUE TITLE
Overlay onHide is not called even if rootClose is true when an element with stopPropagation is clicked.

### ISSUE THREAD

**Issue by endritseatbelt** [react-bootstrap/react-bootstrap#6452]
### Prerequisites

- [X] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [X] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug

I have an Overlay with rootClose and onHide props, when I click on another element that has a onClick event which calls to e.stopPropagation, the onHide doesn't fire.

### Expected behavior

Overlay should fire onHide whenever you click outside the overlay if the rootClose prop is true.

### To Reproduce

1. Have an Overlay component with rootClose and onHide props
2. Click a button or another element whose onClick calls to e.stopPropagation();

### Reproducible Example

https://codesandbox.io/s/awesome-microservice-j48lwf?file=/src/SimplePrompt.js

### Screenshots

![image](https://user-images.githubusercontent.com/89905919/192841366-316320be-893d-4842-8b67-d95c680b78af.png)

### What operating system(s) are you seeing the problem on?

Windows, Linux

### What browser(s) are you seeing the problem on?

Chrome, Safari, Firefox, Microsoft Edge, Opera

### What version of React-Bootstrap are you using?

1.6.6

### What version of Bootstrap are you using?

4.6.2

### Additional context

We were using react-bootstrap 0.33 until recently we migrated to react-bootstrap 1.6.6. Noticed this problem after our component
SimplePrompt which renders a button that triggers a state to whether show or hide  the overlay caused for the overlay to not be closed if clicked on the button of another SimplePrompt. We usually use this component on lists of data to prompt the user when they want to delete something. In the reproducible example link  used this component to provide an example.

**Comment by mazid1** [comment]
I can assure that, it is not a direct bug of this repository. Under the hood it uses [Overlay](https://react-restart.github.io/ui/Overlay) component from [react-restart/ui](https://github.com/react-restart/ui). That component itself has this bug.

[Overlay | restart/ui](https://react-restart.github.io/ui/Overlay#animations) this documentation has an editable code section. You can try pasting below code there to test this bug.

```js
function Fade({ children, ...props }) {
  return (
    <Transition
      {...props}
      timeout={300}
      onEnter={(node) => {
        // trigger a reflow
        node.offsetWidth;
      }}
    >
      {(status, innerProps) =>
        React.cloneElement(children, {
          ...innerProps,
          className: clsx(
            "transition-opacity duration-300",
            status === "entering" || status === "entered"
              ? "opacity-1"
              : "opacity-0"
          ),
        })
      }
    </Transition>
  );
}

function Example() {
  const ref = useRef(null);
  const [show, setShow] = useState(false);
  const [showP, setShowP] = useState(false);
    
  return (
  <>
    <div>
      <a
        ref={ref}
        href="#home"
        onClick={() => setShow(true)}
        //onMouseLeave={() => setShow(false)}
      >
        click me to open tooltip
      </a>
      <Overlay
        show={show}
        target={ref}
        offset={[0, 8]}
        transition={Fade}
        placement="top"
        rootClose
        onHide={() => setShow(false)}
      >
        {(props, { arrowProps, popper }) => (
          <Tooltip
            {...props}
            arrowProps={arrowProps}
            popper={popper}
          >
            I am a tooltip
          </Tooltip>
        )}
      </Overlay>
    </div>
    <hr style={{margin: "20px 0"}}/>
    <div>
      <button
        style={{border: "1px solid skyblue", padding: "5px"}}
        onClick={(e) => {
          e.stopPropagation();
          setShowP(!showP);
        }}
      >Clicking me will not hide tooltip</button>
      {showP && <p>button clicked!</p>}
    </div>
    </>
  );
}
```

**Comment by jquense** [comment]
This isn't really a bug, but a consequence of how stopPropagation works. IF you block the event there isn't anything we can do.

**Comment by endritseatbelt** [comment]
@jquense I am just surprised how it was working in version 0.33
