### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by redimongo** [react-bootstrap/react-bootstrap#6464]
### Prerequisites

- [X] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [X] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug

Seems to be an error on line 72 of Col and line 21 on Row.

```
If you want to write it to the DOM, pass a string instead: item="true" or item={value.toString()}.
    at div
    at /Users/russellharrower/Node_Projects/DRN1Git/node_modules/react-bootstrap/cjs/Col.js:72:8
    at div
    at /Users/russellharrower/Node_Projects/DRN1Git/node_modules/react-bootstrap/cjs/Row.js:21:3
    at div
    at /Users/russellharrower/Node_Projects/DRN1Git/node_modules/react-bootstrap/cjs/Container.js:24:3
    at div
    at Home (webpack-internal:///./pages/index.js:55:17)
    at main
```

### Reproducible Example

install react-bootstrap and run - I think.

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Safari

### What version of React-Bootstrap are you using?

2.5.0

### What version of Bootstrap are you using?

5.2.1

**Comment by golota60** [comment]
Hey - could you post markup you used to achieve this or [post a codesandbox link](https://github.com/react-bootstrap/code-sandbox-examples)? Everything seems to be working on our part([docs with those components are working okay](https://react-bootstrap.github.io/components/table/))

**Comment by kyletsang** [comment]
Looks like you're trying to add an invalid prop called `item` to the component.  Check the docs for correct usage:
https://react-bootstrap.github.io/layout/grid/

**Comment by redimongo** [comment]
Yes but I can't find it. If I have put item somewhere where is it as it's not telling me which page (js) it is in. 

I have like 40 files all doing different things.

**Comment by kyletsang** [comment]
Look at the callstack for the error, it should show where you are calling the react bootstrap components:

```
 at Home (webpack-internal:///./pages/index.js:55:17)
```
