### ISSUE TITLE
missplaced semicolon in button group documentation

### ISSUE THREAD

**Issue by chcoomilk** [react-bootstrap/react-bootstrap#6467]
### Prerequisites

- [X] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [X] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug

I found a visual bug on the bottom of the button group page. I tried going into the source code and the page's mdx template, but found nothing out of the ordinary

![image](https://user-images.githubusercontent.com/66551661/195993537-f224f8dd-f1b7-47f2-b442-2cb23e8f0fbe.png)

### Expected behavior

no semicolon, consistent with the other pages

### To Reproduce

Scroll down and hit rock bottom, you can find the semicolon there [here](https://react-bootstrap.github.io/components/button-group/)

### Reproducible Example

Go to [https://react-bootstrap.github.io/components/button-group/#button-toolbar-props](https://react-bootstrap.github.io/components/button-group/#button-toolbar-props)

### Screenshots

![image](https://user-images.githubusercontent.com/66551661/195993537-f224f8dd-f1b7-47f2-b442-2cb23e8f0fbe.png)

### What version of React-Bootstrap are you using?

2.5.0

### What version of Bootstrap are you using?

5

### Additional context

I'm starting to think this is not where I'm supposed to post any documentation issue.

**Comment by kyletsang** [comment]
Fixed now.  Thanks!

**Comment by kangetsu121** [comment]
I think it is fixed by [25d5c9a](https://github.com/react-bootstrap/react-bootstrap/pull/6463/commits/25d5c9ab2bb278cbc430cf55a6a2775e088847cc) of #6463 , thank you.
