### ISSUE TITLE
Validation props "isInvalid" and "isValid" not present on InputGroup

### ISSUE THREAD

**Issue by shozibabbas** [react-bootstrap/react-bootstrap#6469]
### Prerequisites

- [x] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [X] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug

Version: [v2.5.0 (Bootstrap 5.2)](https://react-bootstrap.github.io/forms/input-group/#)
InputGroup does not have isValid and isInvalid props for custom validation

### Expected behavior

InputGroup should allow user to add isValid and isInvalid props so that the default bootstrap validation system can be used.

### To Reproduce

```js
<InputGroup
    isInvalid={true} // this does not work
    isValid={false} // this does not work
>
...
</InputGroup>
```

### Reproducible Example

[https://codesandbox.io/s/icy-tree-ge21s2?file=/src/App.js](url)

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome

### What version of React-Bootstrap are you using?

2.5.0

### What version of Bootstrap are you using?

5.2

**Comment by kyletsang** [comment]
Check out the docs for input group validation:
https://react-bootstrap.github.io/forms/validation/#input-group-validation

**Comment by shozibabbas** [comment]
I did try this. But the div with the class "invalid-feedback" does not become visible.
According to the original bootstrap documentation, it only becomes visible once the "is-invalid" class is assigned to the form control.
