### ISSUE TITLE
ButtonGroup as radio buttons

### ISSUE THREAD

**Issue by jmwyrwas** [react-bootstrap/react-bootstrap#647]
I'm trying to make a group of `Button`s into a radio button set. I can easily do this with bootstrap with `<input type="radio">` elements, but can't figure out how to do this with react-bootstrap. The following code allows the user to select every button, instead of just one.

 JS:
  
    const operationButtons = (    
      <ButtonGroup>
        <Button active>Radio 1</Button>
        <Button>Radio 2</Button>
      </ButtonGroup>
    );

    React.render(operationButtons, document.getElementById('operationButtonsDiv'));

HTML:

    <div name="operationButtonsDiv" id="operationButtonsDiv" data-toggle="buttons"/>

**Comment by mtscout6** [comment]
Something like this will be easier to consider once #342 is complete.

**Comment by AlexKVal** [comment]
Superceded by https://github.com/react-bootstrap/react-bootstrap/issues/342#issuecomment-87075255
