### ISSUE TITLE
ThemeProvider.tsx performs shallow clone of 'prefixes'

### ISSUE THREAD

**Issue by anton6** [react-bootstrap/react-bootstrap#6470]
### Prerequisites

- [X] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [X] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug

I am trying to use ThemeProvider with a Proxy to prepend a custom prefix to all react-bootstrap components.

Instead of a creating a prefixes object and manually listing out all possible react-components class names, I just wanted to use a proxy which when accessed via a simple getter would return a prefix + the class name used to access the proxy.

When trying to do this I noticed that in `ThemeProvider.tsx` there is a line of code https://github.com/react-bootstrap/react-bootstrap/blob/c4b15a3bdb2f4f9ade1fcf46008543e87959d75e/src/ThemeProvider.tsx#L35 which performs a shallow clone of the passed in `prefixes` prop. In my case this ends up stripping away the Proxy and ends up with a simple empty object.

What is the purpose of this shallow clone step? Would it be possible to avoid it?

Is there another way to target all react-bootstrap component class names to prepend a custom prefix instead of manually writing them all out in the `prefixes` prop?

### Expected behavior

If proxy is passed to the `prefixes` prop it should remain a proxy.

### Reproducible Example

Simple proxy I was trying to use to target all class names to prepend custom prefix:

```
const prefixes = new Proxy({}, {
    get(_, prop) {
        return `custom-${prop}`;
    }
});

prefixes["btn"]

> 'custom-btn'
```

### What version of React-Bootstrap are you using?

2.5.0

### What version of Bootstrap are you using?

5.2.2

**Comment by jquense** [comment]
There isn't another option ATM, this is an escape hatch so while it's inconvenient you really only need to do it once, which i think is worth the simpler implementation here
