### ISSUE TITLE
Unable to control switch state

### ISSUE THREAD

**Issue by Paveldeg** [react-bootstrap/react-bootstrap#6471]
### Prerequisites

- [X] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [X] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug

Having Form.Check as a switch and setting its state using "checked" or "defaultChecked" attribute unable to change it's visible state. 

### Expected behavior

Setting "checked" or "defaultChecked" to false should change switch state to "off", and vice versa.

### To Reproduce

`<Form.Check 
        type="switch"
        id="custom-switch-1"
        label="switch"
        defaultChecked={props.getState()}
        onChange={sw => { console.log("checked=" + sw.target.checked); sw.target.checked? props.start() : props.stop() }}
      />      
    </Form>
.
.
setState= (val) => {
  this.setState({state: val});
}
`

### Reproducible Example

`<Form.Check 
        type="switch"
        id="custom-switch-1"
        label="switch"
        defaultChecked={props.getState()}
        onChange={sw => { console.log("checked=" + sw.target.checked); sw.target.checked? props.start() : props.stop() }}
      />      
    </Form>
.
.
setState = (val) => {
    this.setState({state: val});
}
`

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Firefox

### What version of React-Bootstrap are you using?

2.1.2

### What version of Bootstrap are you using?

5.1.3

### Additional context

setState() function from example code is called by parent component.

**Comment by theJsTsGuy** [comment]
Please share a reproducible repo, or code in [Code Sand Box](https://codesandbox.io/s/new)
