### ISSUE TITLE
Why not provide control power like lock scroll and destroy on close

### ISSUE THREAD

**Issue by weihuQAQ** [react-bootstrap/react-bootstrap#6476]
### Is your feature request related to a problem? Please describe

The Dialog of most UI component libraries I use provides very rich props, but it seems that there are few real bootstraps. For example, I want to keep the closed dom and scroll lock

### Describe the solution you'd like

More detailed props are required to control my components, rather than being static

**Comment by kyletsang** [comment]
The modal does accept a `manager` prop where you can pass in a custom ModalManager.  You can extend the one from react-bootstrap [here](https://github.com/react-bootstrap/react-bootstrap/blob/master/src/BootstrapModalManager.tsx) and override whatever function you need.  Does this solve your issue?
