### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by andi-faizal94** [react-bootstrap/react-bootstrap#6489]
### Prerequisites

- [X] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [X] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug

Bug In React-bootstrap: "^1.5.1",

I use bootstrap version 1.5.1 to create a dynamic form in my project.
when i use :

1.Example:

`<Form.Row>
        <Form.Group as={Col}>
          <Form.Label>Payment *</Form.Label>
          <Form.Control
            name='value'
            value={value}
            onChange={(event) => {
              onChangeClinic(event.target.value);
            }}
            as='select'
          >
            {options.map((option, index) => (
              <option key={option.id} value={option.name}>
                {option.name}
              </option>
            ))}
          </Form.Control>
        </Form.Group>
        <Form.Grup className='text-center' as={Col}>
          <Button variant='danger' onClick={() => removeFields(id)}>
            X
          </Button>
        </Form.Grup>
      </Form.Row>`
      
      
      I'm get :
      
![Screen Shot 2022-11-12 at 14 19 50](https://user-images.githubusercontent.com/75654156/201462816-f0fe6f7c-2579-4a2a-8c7f-9464dd36d298.png)

I Solved this problem ,with change my code:

2.Example 

`<Form.Row>
        <Form.Group as={Col}>
          <Form.Label>Payment *</Form.Label>
          <Form.Control
            as='select'
            value={value}
            onChange={(e) => {
              onChangeClinic(e.target.value);
            }}
          >
            <option>Pilih nama klinik</option>
            {options.map((option, index) => (
              <option key={option.id} value={option.name}>
                {option.name}
              </option>
            ))}
          </Form.Control>
        </Form.Group>
        <Button variant='danger' onClick={() => removeFields(id)}>
          X
        </Button>
      </Form.Row>`
      
      
      I Don't why with my code on example number 1 ,why my code error.
      Can help me to explaining my code in example number 1, get error.

    
      
      
      

### Reproducible Example

`<Form.Row>
        <Form.Group as={Col}>
          <Form.Label>Payment *</Form.Label>
          <Form.Control
            name='value'
            value={value}
            onChange={(event) => {
              onChangeClinic(event.target.value);
            }}
            as='select'
          >
            {options.map((option, index) => (
              <option key={option.id} value={option.name}>
                {option.name}
              </option>
            ))}
          </Form.Control>
        </Form.Group>
        <Form.Grup className='text-center' as={Col}>
          <Button variant='danger' onClick={() => removeFields(id)}>
            X
          </Button>
        </Form.Grup>
      </Form.Row>`

### Screenshots

![Uploading Screen Shot 2022-11-12 at 14.19.50.png…]()

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome

### What version of React-Bootstrap are you using?

1.5.1

### What version of Bootstrap are you using?

4.6

**Comment by kyletsang** [comment]
You have a typo in example 1 `Form.Grup`
