### ISSUE TITLE
Masked Input

### ISSUE THREAD

**Issue by lifehackett** [react-bootstrap/react-bootstrap#649]
Does your input component support input masks? I didn't see support for it but I may have missed something.  If not, is this something you plan on adding?

**Comment by dozoisch** [comment]
Beside putting a native type of input that does what you want (eg: input type:email), you can always put an onChange event on the input and implement the mask yourself!

**Comment by dozoisch** [comment]
I'll close that for the time being, let us know if you have any problem and feel free to reopen.

**Comment by lifehackett** [comment]
Just because there can be confusion around the term, I'm referring to this http://en.wikipedia.org/wiki/Input_mask

I don't believe HTML5 input types support input masks.  In my use case it would be `type="tel"`.  The pattern attribute enables validation but doesn't really do input masking.

The onChange event should get me what I need.  Thanks for your response.

**Comment by taion** [comment]
I think native support for masked input patterns is a bit out of scope. It'd be worth checking if our `Input` components interoperate (or can be made to interoperate) with existing masked input packages, though.

**Comment by appsciences** [comment]
All the React masking packages I could find rely on custom input component which would be incompatible with React Bootstrap. Since this package introduces a custom Input component there is an opportunity to seamlessly 'plug-in' something like this https://github.com/borbit/react-mask-mixin. I hope I can find time to implement this.

**Comment by schneidmaster** [comment]
Sorry for bumping an old thread, but for future folks who find this, I just created a custom component to extend react-bootstrap's `Input` and render a `MaskedInput`:

```javascript
import React            from 'react';
import classNames       from 'classnames';
import { Input }        from 'react-bootstrap';
import MaskedInputField from 'react-maskedinput';

export class MaskedInput extends Input {
  renderInput() {
    const className = this.isCheckboxOrRadio() || this.isFile() ? '' : 'form-control';
    return <MaskedInputField {...this.props} className={classNames(this.props.className, className)} ref="input" key="input" />;
  }
}

export default MaskedInput;
```

Works out of the box since all the special props that `MaskedInput` accepts just get passed through `{...this.props}`.
