### ISSUE TITLE
Static Markup Modals Broken

### ISSUE THREAD

**Issue by wfjake** [react-bootstrap/react-bootstrap#6491]
### Prerequisites

- [X] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [X] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug

Since at least version 2.5.0, static markup modals are broken. The content is still rendered, but the modal is missing.

Compare https://react-bootstrap-v4.netlify.app/components/modal/#modals-static to https://react-bootstrap.netlify.app/components/modal/#static-markup and you will notice that the latest static markup modal is not rendering correctly. (I would've compared against other versions of 2.x but I can't find previous versions of the docs anywhere)

### Reproducible Example

The latest docs with an example for static markup modals is broken: https://react-bootstrap.netlify.app/components/modal/#static-markup

### Screenshots

Bootstrap 4 (1.6.6 docs)
![v4](https://user-images.githubusercontent.com/118236421/201814316-efd65c7e-650c-482d-9433-c6a694cdbebc.png)

Bootstrap 5 (2.6.0 docs)
![v5](https://user-images.githubusercontent.com/118236421/201814386-57057931-a1eb-4379-bc2e-64f79a1d961f.png)

### What operating system(s) are you seeing the problem on?

Android, Linux

### What browser(s) are you seeing the problem on?

Firefox

### What version of React-Bootstrap are you using?

2.6.0

### What version of Bootstrap are you using?

5.2.2

**Comment by wfjake** [comment]
Hey @kyletsang, thank you for taking the time to investigate this. I'm uncertain about the fix applied to the docs - it seems to be applying a band-aid rather than solving the root cause. Previously, the example had worked in 2.x, but now we need to port our code for the upgrade from say 2.3.1 to 2.6 with that added <div> tag in order for them to work again? I don't mean this in a confrontational way - just seeking clarification. Thanks again.

**Comment by kyletsang** [comment]
Bootstrap 5 uses css variables, which are defined at the root `.modal` class whereas bootstrap 4 does not.  This is the reason why it broke in the latest documentation.  The static modal example is there to show what the modal looks like without needing to trigger it on the page.  Modals are usually used with the `Modal` component and this docs bug doesn't affect it.

**Comment by wfjake** [comment]
Ah, okay. That makes sense. Thank you!
