### ISSUE TITLE
indeterminate checkbox support

### ISSUE THREAD

**Issue by nicko-winner** [react-bootstrap/react-bootstrap#6497]
### Is your feature request related to a problem? Please describe

Checkbox does not seem to support intermediate states documents in bootstrap.
<img width="843" alt="2022-11-16_12-38-13" src="https://user-images.githubusercontent.com/35456401/202253288-fc2e8938-f7f9-451a-84e9-465c166cf8a6.png">

related documentation:
https://getbootstrap.com/docs/5.0/forms/checks-radios/#indeterminate

Example of how it could be implemented in React:
https://www.robinwieruch.de/react-checkbox-indeterminate/

### Describe the solution you'd like

support for intermediate checkboxes

### Describe alternatives you've considered

Building a customer wrapper around the bootstrap component to support this using the input ref.

**Comment by jquense** [comment]
This is more of a React issue than a RB one. You can set `indeterminate` on the FormCheck, but there isn't an prop because React doesn't support a declarative version of this: https://github.com/facebook/react/issues/1798
