### ISSUE TITLE
Cannot use ref within modal

### ISSUE THREAD

**Issue by leth** [react-bootstrap/react-bootstrap#650]
I get the following error when trying to use a ref within a `ModalTrigger`:

`Uncaught Error: Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. This usually means that you're trying to add a ref to a component that doesn't have an owner (that is, was not created inside of another component's `render` method). Try rendering this component inside of a new top-level component which will hold the ref.`

```
  MyModal = React.createClass
    render: () ->
      <Modal bsStyle='primary' title='Modal heading' animation={false}>
        <div className='modal-body'>
          <span ref="zoinks">crikey</span>
        </div>
        <div className='modal-footer'>
          <Button onClick={@onRequestHide}>Close</Button>
        </div>
      </Modal>

  MyElem: React.createClass
     render: () ->
      <ModalTrigger modal={<MyModal />}>
        <Button bsStyle='primary' bsSize='large'>Launch demo modal</Button>
      </ModalTrigger>
```

Bug #223 looks similar, but I can't see what the solution is.
Is it that you must implement your own version of `ModalTrigger` if you need a ref to something within the overlay?

**Comment by taion** [comment]
The error you get looks like what was in #223. The code you gave works fine for me. As long as you define the thing holding the `ref` as its own component (as you did above with `MyModal`), rather than defining it in some `renderModal` method within the e.g. `MyElem` component, things should work.

**Comment by leth** [comment]
Thanks for the advice, I took a deeper look at our setup and found the problem.
We're using requirejs, and we were depending on `react-with-addons` and `react-bootstrap`, Something also included `react`, possibly `react-bootstrap`.

Changing our dependency to `react` has prevented the double include and fixed the error!

Now I need to just work out how to get hold of the react addons for the cases where we do need them, without breaking everything else.
