### ISSUE TITLE
Invisible Offcanvas stays in DOM after closing and blocks body scroll occasionally 

### ISSUE THREAD

**Issue by goliney** [react-bootstrap/react-bootstrap#6504]
### Prerequisites

- [X] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [X] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug

Sometimes, when I close offcanvas, it disappears from the screen but the DOM still have remnants of it, including `div.offcanvas-backdrop`:
<img width="1611" alt="image" src="https://user-images.githubusercontent.com/2017344/203657424-37f3448f-dbec-46e5-a17a-6ce8d964e840.png">

It blocks the scroll on body and any interaction with the page.

### Expected behavior

The Offcanvas is removed from DOM and backdrop doesn't block the UI.

### Reproducible Example

N/A

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome

### What version of React-Bootstrap are you using?

^2.5.0-beta.1

### What version of Bootstrap are you using?

5.1.3

**Comment by kyletsang** [comment]
Can you provide a minimal repro on codesandbox?

**Comment by goliney** [comment]
@kyletsang I wish I could, but the problem I'm having happens randomly and I haven't figured out concrete steps to reproduce. Thus I didn't provide a sandbox. If it helps, here's the [staging environment](https://staging.shortage.global) that I get the issue on. But again, I don't have stable steps to reproduce, except only use the cart sidebar extensively.
