### ISSUE TITLE
DropdownToggle button missing "show" bootstrap class

### ISSUE THREAD

**Issue by BrianUribe6** [react-bootstrap/react-bootstrap#6507]
### Prerequisites

- [X] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [X] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug

The hover effect is not staying on, when the dropdown button  is clicked, and its menu is on the expanded state.

### Expected behavior

It should behave similar to this: 

[Bootstrap Docs](https://getbootstrap.com/docs/5.2/components/dropdowns/#single-button)

When the button is clicked it adds the "show" class to the button itself, and removes it when the dropdown menu is not active.

### To Reproduce

1. Click a dropdown button. hover effect is correctly applied.
2. With the menu now expanded, move your cursor away.
3. You will notice that the "active/hover" effects is now gone. Unlike regular bootstrap dropdown toggles.

### Reproducible Example

https://react-bootstrap.netlify.app/components/dropdowns/#single-button-dropdowns

### What operating system(s) are you seeing the problem on?

Windows, Linux

### What browser(s) are you seeing the problem on?

Microsoft Edge, Opera

### What version of React-Bootstrap are you using?

2.6

### What version of Bootstrap are you using?

5.2

**Comment by jquense** [comment]
Looks like they changed how the markup is supposed to work here at some point? Instead of putting `show` on the wrapping element it puts it on both the toggle and menu directly

**Comment by BrianUribe6** [comment]
> Looks like they changed how the markup is supposed to work here at some point? Instead of putting `show` on the wrapping element it puts it on both the toggle and menu directly

That seems to be the case.
