### ISSUE TITLE
Proposal: Switch to docusaurus for docs site

### ISSUE THREAD

**Issue by jquense** [react-bootstrap/react-bootstrap#6510]
It's better suited for this sort of thing, allows versioning and i18n, and supports the same sort of codeblocks, and react-metadata (b/c of plugins i wrote).

Downsides are that it's a bit harder to get a lot of these benefits if we want to build our own theme using react-bootstrap (It's generally my position that UI libraries should dogfood their own things).

**Comment by kyletsang** [comment]
I looked into this a while back during the beta, but decided to push it off until v2 went stable.  I agree, this is definitely something we should do.
