### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by zidinberu** [react-bootstrap/react-bootstrap#6520]
### Prerequisites

- [X] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [X] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug

Remove all fool language from the documentations.

Eg: 'Holy guacamole' in https://react-bootstrap.netlify.app/components/overlays/#popovers

It's very offensive to me and I am sure to many.

The developers/contributors should keep their supposedly 'funny' language in their home, and use professional wording that's appropriate to people from all walks of life.

### Reproducible Example

'Holy guacamole' in https://react-bootstrap.netlify.app/components/overlays/#popovers

### What version of React-Bootstrap are you using?

2.7.0

### What version of Bootstrap are you using?

5.2

**Comment by jquense** [comment]
Your complaint here is that you don't like goofy language in the free open source library you are using?
