### ISSUE TITLE
Badge: Control transparency

### ISSUE THREAD

**Issue by hjyangchoi** [react-bootstrap/react-bootstrap#6521]
### Is your feature request related to a problem? Please describe

no problem actually. 
Badge works really well. but it would be really good to add some more design..

### Describe the solution you'd like

I think it would be good to add one more props about transparency.

### Additional context

Is there any way to control transparency of Badge that I didn't find, please let me know.

**Comment by kyletsang** [comment]
The component follow the colors from the bootstrap theme colors by default.  If you're looking to add some transparency, you can pass in any custom class or style you want.
