### ISSUE TITLE
`bootstrap modal` rendered slow and laggy on Chrome

### ISSUE THREAD

**Issue by Qingkui9** [react-bootstrap/react-bootstrap#6522]
### Prerequisites

- [X] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [X] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug

Component with `bootstrap modal` being used is rendered slow and laggy on Chrome but works smoothly on Safari.  Do you have any idea why or is this a bug?

### Expected behavior

`bootstrap modal` works the same on all major browsers.

### Reproducible Example

Will provide later.

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome

### What version of React-Bootstrap are you using?

5.2.3

### What version of Bootstrap are you using?

5.2.3

**Comment by kyletsang** [comment]
Looks ok to me.  I've tested the ones on the docs page:
https://react-bootstrap.github.io/components/modal/

**Comment by Qingkui9** [comment]
Thanks. We have more findings. 

![image](https://user-images.githubusercontent.com/15327444/210398800-446244f9-474b-4300-9917-7e0b3eed823c.png)

It works pretty well with `hardware acceleration` enabled on Chrome but slow and laggy with this option disabled.

**Comment by kyletsang** [comment]
This is an issue with the browser/hardware combination then.  Check that you have the latest drivers installed. That may fix this.
