### ISSUE TITLE
Issue displaying placeholder images in component examples

### ISSUE THREAD

**Issue by KCrandall6** [react-bootstrap/react-bootstrap#6523]
### Prerequisites

- [X] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [X] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug

There seems to maybe be a problem displaying the example components provided in the docs that use placeholder images. All areas of the example components seem to work just fine, except the placeholder images. I came across this when trying to display a Carousel component. I copied and pasted from the docs the first [Carousel component](https://react-bootstrap.github.io/components/carousel/) example, UncontrolledExample, and realized the image placeholder shown in the example did not display. I then tried to copy and paste the first [Card component](https://react-bootstrap.github.io/components/cards/) example, BasicExample, and the same thing happened. 

I suspect that it might have something to do with the holder.js placeholder image, because when I replaced the src with another image it worked fine.

Is there something additional I need to do to display the placeholder images from the example components? 

Here is a screen shot of the problem and a [codesandbox link](https://codesandbox.io/s/carousel-example-v0918x?file=/src/BasicExample.jsx) I created showing the problem.
![Screen Shot 2022-12-28 at 2 19 46 PM](https://user-images.githubusercontent.com/73909369/209873267-bb652058-91e0-45fb-a068-bb236ce02101.png)

### Reproducible Example

[codesandbox link](https://codesandbox.io/s/carousel-example-v0918x?file=/src/BasicExample.jsx)

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome

### What version of React-Bootstrap are you using?

2.7.0

### What version of Bootstrap are you using?

5.2.3

**Comment by JustinTime42** [comment]
Your sandbox link isn't working because it isn't importing the holder.js file. If you paste in "https://unpkg.com/holderjs" under 'External resources' it will work fine. 
Similarly, in your website, you'll need to have `<script src="https://unpkg.com/holderjs"></script>` in your `index.html`.

**Comment by KCrandall6** [comment]
awesome, thanks!
