### ISSUE TITLE
React bootstrap NavBar `href` breaks my all React contexts. How to prevent states data loss?

### ISSUE THREAD

**Issue by m21tomas** [react-bootstrap/react-bootstrap#6524]
### Prerequisites

- [X] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [ ] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [x] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug

I wanted to create good looking NavBar using your react-bootstrap/Navbar. But it does not work as I expected. It not only navigates to href defined path but it also refreshes  application. I want to ask you to change behaviour of the Navbar not to refresh the app. For example `<NavLink className="nav-link" to={"/Home"}>Home</NavLink>` does not refresh the page.
Or you can provide some options to choose whether refresh or not.

Story:

I am using:
```
import Nav from 'react-bootstrap/Nav';
import Navbar from 'react-bootstrap/Navbar';
```
and as soon as I press Navbar Brand or any Nav link the website is navigating to the URI page and refreshing. And I loose  contexts and states. Is there a way to prevent such data loss?

Here is code fragment of UserNavBar:
```jsx
    //...
return (
            <Navbar bg="light" expand="lg">

                <Navbar.Brand href={ "/home"}><img
                    className="ps-3 nav-img"
                    src={logo}
                    alt="logotipas"
                    loading="lazy" /></Navbar.Brand>
                <Navbar.Toggle aria-controls="basic-navbar-nav" />
                <Navbar.Collapse id="basic-navbar-nav">
                    <Nav className="me-auto">
                        <Nav.Link href={"/home"}>Home</Nav.Link>
    //...
```
`href={"/home"}` has the same URI that is defined in the router in the App.js component.
I have React Router that wraps all my components:
```jsx
function App() {
  const [state, dispatch] = useReducer(reducer, initState);
  const [canteenState, setCanteenState] = useState([]);
  const [cartState, setCartState] = useState(0);
    if (state.isAuthenticated) {
    switch (state.role) {
  //...
        case "USER":
        return (
          <AuthContext.Provider value={{ state, dispatch }}>
            <CommonErrorHandler>
              <div className="container-fluid px-0">
                <CartContext.Provider value={{ cartState, setCartState }}>
                  <UserNavBar>
                    <Switch>
                      <Route exact path="/" component={UserHomeContainer} />
                      <Route exact path="/home" component={UserHomeContainer} />
                      <Route exact path="/canteen/:id" component={ChosenCanteen} />

                      <Route path="*" component={NotFound} />
                    </Switch>
                  </UserNavBar>
                </CartContext.Provider>
              </div>
            </CommonErrorHandler>
          </AuthContext.Provider>
        );
  //...
```
In Navbar `<Nav.Link href={"/home"}>Home</Nav.Link>` is the same like in Router: `<Route exact path="/home" component={UserHomeContainer} />`
It navigates to the component. But it also refreshes the page. And I lose states and contexts. Am I doing something wrong or is it default behavior of the react bootstrap Navbar?
Or maybe I should not use the `href`?
But in this Navbar it is the only way to define link.
Maybe I should not use `react-bootstrap/Navbar` ?
How to solve the problem? How to save:
```jsx
const { state } = React.useContext(AuthContext);
const {cartState} = React.useContext(CartContext);
```

-----
Due to react-bootstrap/Navbar bad bahaviour I did custom Navbar using default html tags and `NavLink`. NavLink - `import { NavLink } from "react-router-dom";` - seems to be working properly and navigates to URI without refreshing everything.

### Expected behavior

I expected that it will navigate to URI and won't refresh

### To Reproduce

1. Go to [Bad example](https://codesandbox.io/s/friendly-wu-8sc3d3-bad-example001-8sc3d3)
2. As soon as it loads notice upper navbar and cart status in the upper right corner there is. At the beginning it has 0 elements.
3. Now press card `Review` button and proceed to ChosenCanteen.jsx component.
4. There are tables with products. Add some different products to cart. In Navbar upper right corner notice cart status. It is increasing with each product you add to cart. 
5. When you decided that it is enough press Navbar `Home` link. Or press Navbar image.
6. Notice that the app navigated to the right URI and refreshed. Loading was a bit longer with a quick whitescreen. Notice how cart status is now 0 again.

### Reproducible Example

I have copied code and changed it a bit to fit for codesandbox.io. I have bad and good examples for you devs to test:

1. [Bad example](https://codesandbox.io/s/friendly-wu-8sc3d3-bad-example001-8sc3d3)
2. [Good example](https://codesandbox.io/s/friendly-wu-9sc4d4-good-example-forked-cld9ic)
Just press and check it. Check App.js and UserNavBar.jsx in components directory.  In UserNavBar.jsx there is a code from 
```
import Nav from 'react-bootstrap/Nav';
import Navbar from 'react-bootstrap/Navbar';
```
As soon as it loads notice upper navbar and cart status in the upper right corner there is. At the beginning it has 0 elements.
Now press card button and proceed to ChosenCanteen.jsx component. There are tables with products. Add some different products to cart. Notice upper right cart status. It is increasing with each product add to cart. 
When you decided that it is enough press Navbar Home button. Or press Navbar image.
In bad example the website will navigate to URI and refresh everything. Notice how cart status is now 0 again.
In good example when you press Home Navbar link the app navigates to UserHomeContainer.jsx and it still saves cart status. It has the same amount of products you have added before.

This is what I want you to fix in:
```
import Nav from 'react-bootstrap/Nav';
import Navbar from 'react-bootstrap/Navbar';
```
So it would work like NavLink. Otherwise I cannot work with react-bootstrap/ Navbar and Nav.

### Screenshots

Before adding to cart:
![image](https://user-images.githubusercontent.com/94525145/209864128-d3c951fa-098c-43b0-bc02-3d8db03d64d1.png)

After adding one more product to cart:
![image](https://user-images.githubusercontent.com/94525145/209864219-9e24cb99-ee2d-4e67-8165-9a4329e51453.png)

After pressing Home in Navbar:
![image](https://user-images.githubusercontent.com/94525145/209864284-bcc83a6a-e0ec-4997-8698-f64904e932c0.png)

**NOTE:** In screenshots you have the same amount of items in cart, but user data username is missing the `user@user.lt`
Which is part of `AuthContext`. In codesandbox I did it a bit differently. I used context for the cart to be lose.

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Microsoft Edge

### What version of React-Bootstrap are you using?

^2.5.0

### What version of Bootstrap are you using?

5.1.3

**Comment by kyletsang** [comment]
NavLinks just render anchors under the hood.  You'll need to integrate the react router components/hooks with the react-bootstrap components.  The [code sandbox examples repo](https://github.com/react-bootstrap/code-sandbox-examples) has a number of examples.

Here's an example using RR v6:
https://github.com/react-bootstrap/code-sandbox-examples/blob/master/ts-react-router-v6/src/ButtonLink.tsx
