### ISSUE TITLE
Docs: link navigation doesn't work properly

### ISSUE THREAD

**Issue by teaca-sebastian** [react-bootstrap/react-bootstrap#6528]
### Prerequisites

- [X] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [X] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug

![image](https://user-images.githubusercontent.com/120113707/210701582-f94ac239-3c71-4a8f-bb8a-ff7d8d761129.png)

The "sticky top" anchor in in https://react-bootstrap.github.io/components/navbar/#overview navigates to the path `/#undefined` which doesn't change anything (basically its an anchor tag linked to nothing):

https://react-bootstrap.github.io/components/navbar/#undefined

IMO the "Sticky top" anchor should be removed and let "Placement" without any sub-anchor, since it is already a section that fits alone one one's screen:

![image](https://user-images.githubusercontent.com/120113707/210701925-c5680f3f-5515-4fe2-ae56-222f299708f8.png)

### Expected behavior

Expected clicking on the link would navigate me to the specific section

### To Reproduce

1. go to https://react-bootstrap.github.io/components/navbar/#overview
2. click on "Sticky top" in the nav
3. doesn't redirect

### Reproducible Example

see above

### Screenshots

see above

### What version of React-Bootstrap are you using?

2.7.0

### What version of Bootstrap are you using?

5.2

### Additional context

all above

**Comment by thrilok** [comment]
I think what you mentioned is correct. If you look at the previous versions, there is no Sticky Top item.
