### ISSUE TITLE
Modal re-render itself and looses focus on input change

### ISSUE THREAD

**Issue by maan56** [react-bootstrap/react-bootstrap#6529]
### Prerequisites

- [X] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [X] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug

When I change input values, modal re-render and loose focus on input.

### Expected behavior

It should behave normal as form input behaves without react-bootstrap Modal.

### To Reproduce

1. Click on "See Variations" Button in price column. (Modal window will open)
2. Click on "Edit" Button.
3. Change Input value. (Here you can see its behaviour)

### Reproducible Example

You can see code here,
[https://codesandbox.io/s/react-bootstrap-modal-issue-reproduction-dmjvud?file=/src/Products.js](url)

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome, Safari

### What version of React-Bootstrap are you using?

2.7.0

### What version of Bootstrap are you using?

5.2.3

**Comment by kyletsang** [comment]
You shouldn't be using `uuid()` to create react keys.  This is generating different keys for each re-render which is causing that element and its children to destroyed/recreated.

The keys should be derived from your array data and must be unique.  Consider using the slug.

**Comment by maan56** [comment]
> You shouldn't be using `uuid()` to create react keys. This is generating different keys for each re-render which is causing that element and its children to destroyed/recreated.
> 
> The keys should be derived from your array data and must be unique. Consider using the slug.

Thank You, It worked.
