### ISSUE TITLE
Collapse: width style prop lost when collapse and expand

### ISSUE THREAD

**Issue by gamecss** [react-bootstrap/react-bootstrap#6531]
### Prerequisites

- [X] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [X] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug

When a Collapse have a children with width style prop, collapse and expand, the width style prop will lost.

### Expected behavior

width style prop keep

### To Reproduce

1. Collapse
2. Expand

### Reproducible Example

[Codesandbox](https://codesandbox.io/s/romantic-mahavira-6k5ogh?file=/src/App.js)

### What operating system(s) are you seeing the problem on?

Linux

### What browser(s) are you seeing the problem on?

Chrome

### What version of React-Bootstrap are you using?

2.7.0

### What version of Bootstrap are you using?

5.2.3

**Comment by kyletsang** [comment]
Try wrapping your `p` with a `div`

**Comment by gamecss** [comment]
Thanks, it's working now.
