### ISSUE TITLE
Accessibility bug in accordion component 

### ISSUE THREAD

**Issue by marishkaSunrise** [react-bootstrap/react-bootstrap#6536]
### Prerequisites

- [X] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [X] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug

Accordion component has not fully implemented accessibility attributes required by WCAG &
ADA. 

### Expected behavior

Requirements: https://www.w3.org/WAI/ARIA/apg/example-index/accordion/accordion

In React Accordion component with alwaysOpen feature on  child Accordion.Button component has aria-expanded attribute  set to false for all conditions.

Required:  set to true aria-expanded  when the Accordion panel is expanded, otherwise set to false.

Accordion Bootstrap Component  https://react-bootstrap.github.io/components/accordion/

### Reproducible Example

```
import Accordion from 'react-bootstrap/Accordion';

function AlwaysOpenExample() {
  return (
    <Accordion defaultActiveKey={['0']} alwaysOpen>
      <Accordion.Item eventKey="0">
        <Accordion.Header>Accordion Item #1</Accordion.Header>
        <Accordion.Body>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
          eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad
          minim veniam, quis nostrud exercitation ullamco laboris nisi ut
          aliquip ex ea commodo consequat. Duis aute irure dolor in
          reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla
          pariatur. Excepteur sint occaecat cupidatat non proident, sunt in
          culpa qui officia deserunt mollit anim id est laborum.
        </Accordion.Body>
      </Accordion.Item>
      <Accordion.Item eventKey="1">
        <Accordion.Header>Accordion Item #2</Accordion.Header>
        <Accordion.Body>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
          eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad
          minim veniam, quis nostrud exercitation ullamco laboris nisi ut
          aliquip ex ea commodo consequat. Duis aute irure dolor in
          reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla
          pariatur. Excepteur sint occaecat cupidatat non proident, sunt in
          culpa qui officia deserunt mollit anim id est laborum.
        </Accordion.Body>
      </Accordion.Item>
    </Accordion>
  );
}

export default AlwaysOpenExample;
```

### What version of React-Bootstrap are you using?

2.7.0

### What version of Bootstrap are you using?

5.2.3

**Comment by Bishopukpai** [comment]
Hy can I get the component where the error is

**Comment by marishkaSunrise** [comment]
> Hy can I get the component where the error is

AccordionButton
