### ISSUE TITLE
Type error: Form, Form.Group don't accept multiple children

### ISSUE THREAD

**Issue by neongreen** [react-bootstrap/react-bootstrap#6538]
### Prerequisites

- [X] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [X] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug

Code like this fails to typecheck with `react-bootstrap` 2.7.0, `react` 18.2.0, `@types/react` 18.0.27

```tsx
              <B.Form onSubmit={formik.handleSubmit}>
                <B.Form.Group className="mb-3">
                  <B.Form.Label>Card to move into</B.Form.Label>
                  ... other components ...
                </B.Form.Group>
                <B.Form.Group ...>
                  ...
                </B.Form.Group>
              </B.Form>
```

Specifically, both B.Form and B.Form.Group complain:

```
This JSX tag's 'children' prop expects a single child of type 'ReactNode'
but multiple children were provided.
```

### Expected behavior

Passing several components without wrapping them into a fragment should be fine. It worked before upgrading `react` and `typescript`.

### Reproducible Example

-

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Safari

### What version of React-Bootstrap are you using?

2.7.0

### What version of Bootstrap are you using?

5.1.3

**Comment by jquense** [comment]
Seems like you may have an issue with your react types, maybe multiple version of them installed at once. `ReactNode` is the correct type and accepts multiple children

**Comment by neongreen** [comment]
Turns out the error was due to `ts-pattern`, and was sort of misleading. The true error is not "multiple children" but rather "can't assign X to ReactNode". Repro: https://stackblitz.com/edit/react-ts-1aj4xd?file=App.tsx

Closing since it's not a react-bootstrap issue.
