### ISSUE TITLE
Comments are ignored when inserted inside react-bootstrap elements

### ISSUE THREAD

**Issue by sahlouls** [react-bootstrap/react-bootstrap#654]
Hi,

Here the following snippet that will display 3 buttons. The comment will be ignored

![image](https://cloud.githubusercontent.com/assets/3117988/7613412/e2024240-f990-11e4-9048-6d64d7bb9bce.png)

Regards,

**Comment by mtscout6** [comment]
This is a limitation of JSX, see: https://facebook.github.io/react/docs/jsx-in-depth.html#comments

**Comment by sahlouls** [comment]
Thanks , Good catch ;)  

Regards,
