### ISSUE TITLE
Remove defaultProps for React 18.3.0

### ISSUE THREAD

**Issue by omermecitoglu** [react-bootstrap/react-bootstrap#6547]
### Is your feature request related to a problem? Please describe

`Warning: OverlayTrigger: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.`

I started seeing this warning which is related to https://github.com/facebook/react/pull/16210

### Describe the solution you'd like

Using JavaScript default parameters instead of defaultProps

**Comment by kyletsang** [comment]
We'll take a look at this after we merge the [docusaurus PR](https://github.com/react-bootstrap/react-bootstrap/pull/6553).  We need to ensure the documentation is generated properly after the default props changes.

**Comment by michal-th** [comment]
Is there any update on this @kyletsang ?

**Comment by cb-eli** [comment]
Would this fix be available for react-bootstrap version 1.x (bootstrap 4.x)?

**Comment by kyletsang** [comment]
> Would this fix be available for react-bootstrap version 1.x (bootstrap 4.x)?

Unfortunately no, since that requires a heavy lift in updating RB as well as the underlying deps like `react-overlays`.  There's also other React 19 changes, that we aren't fully compatible with yet
