### ISSUE TITLE
Bug Pagination won't allow variant color

### ISSUE THREAD

**Issue by redimongo** [react-bootstrap/react-bootstrap#6558]
### Prerequisites

- [X] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [X] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug

Change color of pagination to red. There is no Documentation on how to achieve this.

https://react-bootstrap.github.io/components/pagination/

### Reproducible Example

I created a pagination that should be red

```
<Pagination variant="danger" className="justify-content-center">
            {Array(Math.ceil(asArray.length / itemsPerPage))
              .fill()
              .map((_, index) => (
                <Pagination.Item
                  key={index}
                  active={index + 1 === currentPage}
                  onClick={() => {paginate(index + 1), window.scrollTo({ top: 0, behavior: "smooth" });}}
                >
                  {index + 1}
                </Pagination.Item>
              ))}
          </Pagination>
```

### What version of React-Bootstrap are you using?

2.5.0

### What version of Bootstrap are you using?

5.2.1

**Comment by kyletsang** [comment]
`variant` is not an accepted prop for `Pagination`

We generally support styling according to upstream Bootstrap.  They have no variants in their documentation: https://getbootstrap.com/docs/5.3/components/pagination/

If you're looking to customize your components, you can override it via css or the style prop
