### ISSUE TITLE
Text overlay issue

### ISSUE THREAD

**Issue by arvindlogistic** [react-bootstrap/react-bootstrap#6565]
Hello sir,
when i type on text area and scroll text is overlay on label. plz check below link 
https://react-bootstrap.netlify.app/forms/floating-labels/#textareas

**Comment by wolffman122** [comment]
Think he is referring to this happening.
![image](https://user-images.githubusercontent.com/19178872/227574624-36541fab-fa71-4eea-a3e5-e20a4abc813b.png)

**Comment by kyletsang** [comment]
This is an issue upstream in the css:
https://github.com/twbs/bootstrap/issues/37539

**Comment by kyletsang** [comment]
Fixed upstream in 5.3.0
