### ISSUE TITLE
Collapse does not support multiple children

### ISSUE THREAD

**Issue by andreynovikov** [react-bootstrap/react-bootstrap#6570]
Original bootstrap collapse nicely supports multiple children, but React Collapse doesn't:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'className')
    at children (Collapse.js:99:94)
```
Looks like it's this line:
https://github.com/react-bootstrap/react-bootstrap/blob/e969b7e63f1cba850a668c714313d9b0ce251064/src/Collapse.tsx#L243

Wrapping all `Collapse` children in extra `div` fixes the problem but it doesn't look like a nice solution.

**Comment by jquense** [comment]
We are the same as original bootstrap the difference is Collapse doesn't render any component by default, which is why you need to provide one as the only child. This is equivalent to upstream bootstrap where you have to say one element is the collapse and then put children in it.
