### ISSUE TITLE
Form Validation not working with FloatingLabel

### ISSUE THREAD

**Issue by wdh2100** [react-bootstrap/react-bootstrap#6572]
### Prerequisites

- [X] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [X] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug

If floatinglabel is used, feedback to floatinglabel does not work.

### Expected behavior

Show labels, and see feedback

### Reproducible Example

```jsx
      <InputGroup className="mb-3">
        <InputGroup.Text id="basic-addon1">@</InputGroup.Text>
        <FloatingLabel
           controlId="Username"
           label="Username"
         >
           <Form.Control
             placeholder="Username"
             aria-label="Username"
             aria-describedby="basic-addon1"
           />
       </FloatingLabel>
   <Form.Control.Feedback type="invalid">
            Please provide a valid city.
          </Form.Control.Feedback>
      </InputGroup>
```

### What operating system(s) are you seeing the problem on?

Windows, Linux

### What browser(s) are you seeing the problem on?

Chrome, Firefox

### What version of React-Bootstrap are you using?

2.8.2

### What version of Bootstrap are you using?

5.1.3

**Comment by khanahmar** [comment]
Hey i am new to open source can you please tell me a little more or how to fix this

**Comment by wdh2100** [comment]
> Hey i am new to open source can you please tell me a little more or how to fix this

Thank you for answer.

This problem occurs when Floating and Form.Control(with validation) are combined.

If validation is performed with Form.control(input text) and floatingLabel applied, abnormal operation occurs.

In the example below, an error message is output under the input when validation is running, but it works abnormally when the above combination is used.
https://react-bootstrap.github.io/forms/validation/

**Comment by yushanwebdev** [comment]
I will check this issue
