### ISSUE TITLE
Feature: Implement stacked toasts

### ISSUE THREAD

**Issue by alexandernst** [react-bootstrap/react-bootstrap#6575]
### Is your feature request related to a problem? Please describe

Emitting multiple toasts ends up filling the user's screen space. A way to group (stack) all the toasts will improve the UX.

### Describe the solution you'd like

I'd like toasts to be stacked. Visual example:

![160688000-1d01d949-d9e1-41f4-858c-f5c9a33b901d](https://user-images.githubusercontent.com/89727/229371184-b4803564-857c-493d-b6c9-757f46b47573.gif)

**Comment by kyletsang** [comment]
All css features should be requested in Bootstrap's repo: https://github.com/twbs/bootstrap

**Comment by alexandernst** [comment]
I just opened a FR here: https://github.com/twbs/bootstrap/issues/38424
