### ISSUE TITLE
Hamburger icon for narrow displays wrongly rendered transparent (Gatsby site)

### ISSUE THREAD

**Issue by lukwe** [react-bootstrap/react-bootstrap#6577]
This is happening on a Gatsby site, using React Bootstrap and Sass variables .
The issue surfaced after upgrading to Gatsby 5 and all its dependencies from a very old 2.something.

Please see http://www.bo.ingv.it and shrink the width..

the navbar-toggler-icon gets displayed transparently instead of white. 

I tried overwriting it with developers-tools but neither adding the color in the css navbar-toggler-icon class, nor  editing it in the swg used in the 'background-image: var(--bs-navbar-toggler-icon-bg);' works, the overall html structure generated from the  <navbar> component looks fine to me.

any help ?!

Thanks, ciao

**Comment by zivnadel** [comment]
Did you fix it? For me, it is not transparent but black. Changing the sass variables fixes this to me (`--bs-navbar-toggler-border-color` and the stroke of the svg in `--bs-navbar-toggler-icon-bg`)

<div>
<img src="https://user-images.githubusercontent.com/52624380/230783827-e455d7bc-d228-4d70-9996-ef0e07317140.png" /> --->
<img src="https://user-images.githubusercontent.com/52624380/230784130-812dbacc-b53a-47b2-bb9d-7f1e9362741e.png"/>
</div>
