### ISSUE TITLE
Feature - Enhancement

### ISSUE THREAD

**Issue by wmcrank4** [react-bootstrap/react-bootstrap#6581]
### Is your feature request related to a problem? Please describe

Bootstrap Select is missing "live-search".

### Describe the solution you'd like

Add live-search feature to React-Bootstrap 

### Describe alternatives you've considered

Other libraries

**Comment by jquense** [comment]
Thanks for the suggestion but as a rule we match what vanilla bootstrap offers and don't extend past that in terms of new components.
