### ISSUE TITLE
Bug :autoClose about Dropdown and stopPropagation

### ISSUE THREAD

**Issue by peipei818** [react-bootstrap/react-bootstrap#6586]
### Prerequisites

- [X] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [X] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug

The e.stopPropagation() event will not affect autoClose about NavDropdown in react version16, but it will affect autoClose about NavDropdown in react version17. I think it's about the event delegation change when react is upgraded.

### Reproducible Example

```
<Navbar.Collapse onClick={()=>setCollapseOpen(false)}>
   <div. onClick={(e) => e.stopPropagation()}>
       <Nav>
            <NavDropdown>...</NavDropdown>
            <NavDropdown>...</NavDropdown>
       </Nav>
   </div>
</Navbar.Collapse>
```

### What version of React-Bootstrap are you using?

2.5.0

### What version of Bootstrap are you using?

5.2.0

**Comment by kyletsang** [comment]
What's the question here?  What are you trying to achieve?
