### ISSUE TITLE
Bug: dependency now requires React 17

### ISSUE THREAD

**Issue by walliby** [react-bootstrap/react-bootstrap#6589]
### Prerequisites

- [X] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [X] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug

`restart/ui` just did a release to 1.6.2 which now requires React 18: https://github.com/react-restart/ui/releases/tag/v1.6.2
So react-bootstrap now has dependency conflicts in React below 18. Can the dependency be changed from 

"@restart/ui": "^1.4.1",

to

"@restart/ui": "1.4.1",

### Reproducible Example

n/a

### Screenshots

![Screenshot 2023-04-14 at 3 22 22 PM](https://user-images.githubusercontent.com/5349341/232137248-37184ca7-4e9d-44f4-bdd2-4608cbaefc59.png)

### What operating system(s) are you seeing the problem on?

macOS

### What version of React-Bootstrap are you using?

2.7.3

### What version of Bootstrap are you using?

5.2.3

**Comment by kyletsang** [comment]
Sorry missed the breaking changes in peer deps with `uncontrollable`.  I'll fix this later tonight
