### ISSUE TITLE
Tabs

### ISSUE THREAD

**Issue by rwb196884** [react-bootstrap/react-bootstrap#6595]
### Is your feature request related to a problem? Please describe

How do you make tabs?

In the documentation the tab content goes inside the `Tab` tag, but when I do this the tab contents don't appear.

### Describe the solution you'd like

Documentation that isn't incomplete.

### Describe alternatives you've considered

Angular.

**Comment by jquense** [comment]
Hey @rwb196884 if you want help you need to provide enough information that someone can help you. "It doesn't work for me" with no additional info, code, or context isn't actionable. We can't guess what you might have done or tried, especially when the documentation and other examples work fine. Please have some respect for folks time (that they spend free of charge) when asking for help thanks
