### ISSUE TITLE
Bug: Navigating through Dropdown.Item under Dropdown.Menu error

### ISSUE THREAD

**Issue by OWamsley** [react-bootstrap/react-bootstrap#6598]
### Prerequisites

- [X] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [X] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug

I create a list of <Dropdown.Item> components under a <Dropdown.Menu> component. This Dropdown menu should only appear when there are valid 'options' to display under a text box. If I tab to the dropdown menu once rendered, and try to use the arrow keys to navigate through the list, I get the following error.

caught TypeError: Cannot read properties of undefined (reading 'parentNode')

However, when trying to reproduce this error in code sandbox, it works fine. You can hit tab after the textbox and then use the error keys to navigate through the list. The issue 

 ```
const renderOptions = () => {
        if (textValue === '') {
            return;
        }

        const validOptionsList = options
            .filter((option) => {
                if (option.toLowerCase().trim().includes(textValue.toLowerCase().trim())) {
                    return (option);
                }
            })
            .map((option) =>
                <Dropdown.Item
                onClick={() => handleClick(option)}>
                    {option}
                </Dropdown.Item>);

        if (validOptionsList.length === 0) {
            return;
        }

        return (
            <div>
                <Dropdown>
                <Dropdown.Menu style={{width: textInputRef?.current?.clientWidth}}
                               show={validOptionsList.length > 0}>
                    {validOptionsList}
                </Dropdown.Menu>
                </Dropdown>
            </div>)
    }

 return (
        <div>
            <Form.Control
                style={{width: width}}
                ref={textInputRef}
                type={'text'}
                placeholder={placeHolder}
                onChange={e => setTextValue(e.target.value)}
                value={textValue}
                maxLength={255}
            />
            {renderOptions()}
        </div>
    )
```

### Expected behavior

I expect that if I hit 'Tab' to get to this component, and use the arrow keys, I should be able to navigate up and down the list of components. 

### Reproducible Example

CodeSandbox Link : https://codesandbox.io/s/awesome-haslett-jtcqqo

The error is not reproducible here. See the attached screenshot to see the error, and the part of code that it points to (line 97 of Dropdown.js)

### Screenshots

![image](https://user-images.githubusercontent.com/47764303/232558289-09abfe96-3961-419c-b938-1504951f2c49.png)

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of React-Bootstrap are you using?

2.7.2

### What version of Bootstrap are you using?

5.2.3

**Comment by OWamsley** [comment]
II believe that I am importing from react-bootstrap. Here is the import commands for my component.

![image](https://user-images.githubusercontent.com/47764303/232587000-145890a6-f335-4438-8348-f6811b126ccd.png)

**Comment by kyletsang** [comment]
Our code doesn't integrate with vanilla bootstrap JS at all, so that must be coming from somewhere in your project.  Since the error doesn't occur in the codesandbox, there's not much we can do.

**Comment by OWamsley** [comment]
It turns out that we left an artifact from changing to react bootstrap. 
https://getbootstrap.com/docs/3.3/getting-started/
On that bootstrap documentation page under 'Basic Template' you can see where we got to put 
`<script src="js/bootstrap.min.js"></script>`
if anyone is ever curious. Once we deleted this, we stopped running into this error. 

Thanks for pointing us in the right direction!
