### ISSUE TITLE
How to replay the Form.Control

### ISSUE THREAD

**Issue by weskerjiang** [react-bootstrap/react-bootstrap#6599]
### Is your feature request related to a problem? Please describe

no

### Describe the solution you'd like

I've found Form.Control has a property "as",it can be input,select.May i change it the my own components like calendar,tree-view or something else.how to do this?thanks

**Comment by kyletsang** [comment]
You can put whatever component you want under `as`, but form control was meant for HTML `<input>`s.  Putting something as complex as a calendar or tree-view isn't really supported
