### ISSUE TITLE
Error poper.js 

### ISSUE THREAD

**Issue by sheggietyn** [react-bootstrap/react-bootstrap#6604]
### Prerequisites

- [X] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [X] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug

ERROR in ./node_modules/@popperjs/core/lib/popper-base.js 3:0-57
export 'detectOverflow' (reexported as 'detectOverflow') was not found in './createPopper.js' (possible exports: createPopper, popperGenerator)
ERROR in ./node_modules/prop-types/node_modules/react-is/index.js
Module build failed (from ./node_modules/source-map-loader/dist/cjs.js):

### Reproducible Example

ERROR in ./node_modules/@popperjs/core/lib/popper-base.js 3:0-57
export 'detectOverflow' (reexported as 'detectOverflow') was not found in './createPopper.js' (possible exports: createPopper, popperGenerator)
ERROR in ./node_modules/prop-types/node_modules/react-is/index.js
Module build failed (from ./node_modules/source-map-loader/dist/cjs.js):

### What version of React-Bootstrap are you using?

latest version 

### What version of Bootstrap are you using?

i removed bootstrap since i installed react bootstrap

**Comment by kyletsang** [comment]
Can you post a minimal code repro on code sandbox?
