### ISSUE TITLE
Alert's close button hides alert, even if onClose handler keeps it visible

### ISSUE THREAD

**Issue by miguelgrinberg** [react-bootstrap/react-bootstrap#6640]
### Prerequisites

- [X] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [X] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug

Starting with release 2.7.3, the close button in the `Alert` component automatically sets the `show` prop to `false` when the prop isn't explicitly given in the component declaration. This happens regardless of what the `onClose` handler does, or if it is defined or not. In versions up to 2.7.2 this was not the case.

### Expected behavior

The `show` prop of the component will remain with the same value unless explicitly changed in the `onClose` handler.

### To Reproduce

You can use the live editor in the [Dismissing](https://react-bootstrap.github.io/docs/components/alerts/#dismissing) section of the Alert docs. Just change the `onClose` handler as follows to force the alert to stay visible:

```jsx
<Alert variant="danger" onClose={() => setShow(true)} dismissible>
```

Note how the alert disappears anyway, as the visible state of the component appears to automatically change to `false`.

To keep the alert visible after clicking the close button, the `show` prop needs to be set explicitly:

```jsx
<Alert show={show} variant="danger" onClose={() => setShow(true)} dismissible>
```

### Reproducible Example

https://codesandbox.io/s/dazzling-dawn-pg63sp?file=/src/App.js

### What operating system(s) are you seeing the problem on?

Linux

### What browser(s) are you seeing the problem on?

Chrome, Firefox

### What version of React-Bootstrap are you using?

2.8.0

### What version of Bootstrap are you using?

5.3.0

**Comment by jquense** [comment]
That's correct, you need to pass the state to the  Alert via the show prop, so it knows you are "controlling" it.
