### ISSUE TITLE
Toast don't close

### ISSUE THREAD

**Issue by NaturelLaurent** [react-bootstrap/react-bootstrap#6641]
### Prerequisites

- [X] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [X] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug

The toats can't close because the attribut data-dismiss="toast" doesn't work with bootstrap 5

how resolve it?
the toasts close need 
data-bs-dismiss="toast"

so you need to add in the header closeButton={false} and and a button with data-bs-dismiss

                <Toast.Header closeButton={false}>
                    <button type="button" className="btn-close ms-auto" data-bs-dismiss="toast" aria-label="Close"></button>
                </Toast.Header>

### Expected behavior

The toats can't close

### Reproducible Example

https://react-bootstrap.netlify.app/docs/components/toasts

### What operating system(s) are you seeing the problem on?

Windows, macOS

### What browser(s) are you seeing the problem on?

Chrome

### What version of React-Bootstrap are you using?

2.8.0

### What version of Bootstrap are you using?

5.3.0

**Comment by jquense** [comment]
Closing is a matter of not rendering the toast anymore, that's up to you the consumer. Controlling the rendering as function of state is the more "react-y" Api. The docs demonstrate a few exa.ples where toasts are closeable
