### ISSUE TITLE
React-bootstrap progress bar is not accepting variant both statically and dynamically

### ISSUE THREAD

**Issue by bhaveshkumar96** [react-bootstrap/react-bootstrap#6644]
### Prerequisites

- [X] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [X] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug

when i am using react bootstrap progress bar its not accepting the variant i am providing through dynamic variables and also statically, i searched also but i didn't get any update

### Reproducible Example

nolink

### Screenshots

![boot](https://github.com/react-bootstrap/react-bootstrap/assets/110034571/ee18e6f4-a428-4dc5-8ef6-ed240f1ef8d7)

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of React-Bootstrap are you using?

2.8.0

### What version of Bootstrap are you using?

2.8.0

### Additional context

              <ProgressBar label={`${progress}%`} style={{ height: "3px", backgroundColor: "#F2F2F2" }} striped variant={variant} max={100} now={progress} />

**Comment by kyletsang** [comment]
Works fine on the site:
https://react-bootstrap.github.io/docs/components/progress

Compare your code to the examples there
