### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by maniac-0s** [react-bootstrap/react-bootstrap#6649]
### Prerequisites

- [X] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [X] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug

I have an older react app that uses react-bootstrap for some UI elements. The app runs life for two years already but now I need to update everything and add some new features.

I managed to update the app so far that the app now runs with React 18 but as soon as I include the component that contains react-bootstrap elements, the whole thing crashes with the following error

```
Warning: React.jsx: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: null.

Check the render method of `TabPane`.
./node_modules/react-bootstrap/esm/TabPane.js/TabPane<@http://localhost:3000/static/js/bundle.js:71853:7
div
./node_modules/react-bootstrap/esm/createWithBsPrefix.js/createWithBsPrefix/BsComponent<@http://localhost:3000/static/js/bundle.js:72135:9
Tabs@http://localhost:3000/static/js/bundle.js:12676:7
TabContainer@http://localhost:3000/static/js/bundle.js:71789:7
div
div
ContextProvider@http://localhost:3000/static/js/bundle.js:6791:21
App@http://localhost:3000/static/js/bundle.js:65:74

Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: null.

Check the render method of `TabPane`.
    React 15
    workLoop scheduler.development.js:266
    flushWork scheduler.development.js:239
    performWorkUntilDeadline scheduler.development.js:533

```
TabPane is used like

```
 <Tab.Container defaultActiveKey="text" transition={transition? null: false}>
                        <Tab.Pane eventKey="text">
                          <TextButton />
                        </Tab.Pane>
                        <Tab.Pane eventKey="settings" className="toolbar-settings-content">
                          <strong>Area</strong>
                          <form onSubmit={handleFormSubmit}>
                          {/* ... */}
                         </form>
                        </Tab.Pane>
</Tab.container>
```

### Reproducible Example

//

### What version of React-Bootstrap are you using?

2.8.0

### What version of Bootstrap are you using?

5.3.0

### Additional context

"react": "^18.2.0",

**Comment by kyletsang** [comment]
`transition` should be either `false` or a component.  Don't pass `null` in there
