### ISSUE TITLE
FormSelect defaultValue cannot be set from state variable

### ISSUE THREAD

**Issue by silme** [react-bootstrap/react-bootstrap#6650]
### Prerequisites

- [X] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [X] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug

FormSelect defaultValue cannot be set from state variable

### Reproducible Example

https://codesandbox.io/s/priceless-bhabha-778ltg?file=/src/App.tsx

### What version of React-Bootstrap are you using?

2.8.0

### What version of Bootstrap are you using?

5.2.3

### Additional context

Setting `defaultValue` property of `FormSelect` using a state variable has no effect.
[failing example](https://codesandbox.io/s/priceless-bhabha-778ltg?file=/src/App.tsx)

Setting `defaultValue` property using literals works.
[working example](https://codesandbox.io/s/smoosh-dawn-38tfg?file=/src/App.tsx)

Am I missing something here? There is a workaround by using `value` + `onChange()` instead of `defaultValue`, but in my opinion is not ideal (requires re-rendering).

**Comment by kyletsang** [comment]
Controlled inputs should always be using `value` + `onChange`.  Re-renders are expected and are normal in react 

`defaultValue` is only used during initialization
