### ISSUE TITLE
Help: Possibility to place custom close button outside of modal content

### ISSUE THREAD

**Issue by levipadre** [react-bootstrap/react-bootstrap#6653]
I have a custom close button in a modal. I would like to know if there is a way to place the button outside of the `.modal-dialog`, but still within the `.modal`?

This is my code:
```
<Modal
                show={show}
                onHide={handleClose}
                onEntering={handleShow}
                backdrop="static"
                keyboard={false}
                centered
                size='xl'
            >

                <Button variant='link' className={`menu-icon menu-close rounded-0 border-0 position-fixed ${show ? 'd-block open' : 'd-none'}`} role='button' aria-label='Close button' onClick={handleClose} style={{ zIndex: 1056 }}>
                    <span></span>
                    <span></span>
                    <span></span>
                    <span></span>
                </Button>

                <Modal.Header className='pt-0'>
                    <Modal.Title as='h5' className='text-uppercase text-white display-1 text-opacity-25'>Menu</Modal.Title>
                </Modal.Header>

                <Modal.Body>
                    <Nav as='ul' className='d-block'>
                        {MENU.map((item: any) => {
                            return (
                                <Nav.Item as='li' key={item.id}>
                                    <Nav.Link as={Link} href={item.url} className='px-0'>
                                        <span className='h2 text-uppercase'>
                                            {item.title}
                                        </span>
                                    </Nav.Link>
                                </Nav.Item>
                            );
                        })}
                    </Nav>
                </Modal.Body>
            </Modal>
```

Any help or suggestion would be appreciated.

**Comment by Magesh-sam** [comment]
the code is working completely fine and the close button is inside the modal. 
![image](https://github.com/react-bootstrap/react-bootstrap/assets/41033755/42f88a8b-9ef9-4bd5-b63b-3b46a0d6c940)


if you are expecting any thing else please give more detail or share a desired design for the modal.

**Comment by jquense** [comment]
Thanks @Magesh-sam  but they're saying they want the close button outside the modal. @levipadre  you can use custom css for this

**Comment by levipadre** [comment]
Thanks. I asked if I can place outside of the .modal-dialog, but still within the .modal

**Comment by Magesh-sam** [comment]
My bad I didn't check the issue properly. You can use relative layout with modal and use absolute positioning for the button.
![image](https://github.com/react-bootstrap/react-bootstrap/assets/41033755/d269a723-bb25-4741-81ca-d3e6c7fd4313)

I've used the relative position for modal head and absolute for button and removed the fixed position from your code

```html
       <Modal.Header className='pt-0'   style={{position:'relative'}}>
                    <Modal.Title as='h5' className='text-uppercase text-white display-1 text-opacity-25'>Menu</Modal.Title>
                    <Button variant='danger' style={{position:'absolute',top:'-50px',right:'5px'}}   className={`menu-icon menu-close rounded-0 border-0 ${show ? 'd-block open' : 'd-none'}`} role='button' aria-label='Close button' onClick={handleClose} >
                   close modal
                    </Button>
        </Modal.Header>

```

**Comment by levipadre** [comment]
Thanks, @Magesh-sam, but I don't need CSS solution in my case.

**Comment by jquense** [comment]
Why doesn't a css solution work? There isn't another way to do this, you'd have to write a custom modal using the base component

**Comment by Magesh-sam** [comment]
fixed position is relative to the viewport and absolute is relative to the container block  that's the problem you're facing. if you use absolute position everything will be fine

**Comment by levipadre** [comment]
Thank you, but absolute position won't work for me. The close button can't move if the modal scrolls.
@jquense you mentioned custom modal from base component. Can you give me a direction for this?

**Comment by levipadre** [comment]
I still need this, the problems are the following:
- if I use `absolute` position for the close button, it will scroll with the modal if it's too long
- if I use `fixed` position,  it places to the right position, but it jumps (first shows inside the modal content, then moves)
- if I move outside of the modal, it's in the right position immediately, but it won't be accessible by using tabs, which is crucial

**Comment by akshayantony55** [comment]
Please provide a mockup of how you want this. @levipadre

**Comment by levipadre** [comment]
I created a mockup: https://codesandbox.io/s/damp-shadow-n433jl

**Comment by Magesh-sam** [comment]
@levipadre if you can use bootstrap 5 use that. the modal already has a built in close button. i saw your mockup you are using bootstrap 4

modal in bootstrap 5
https://codesandbox.io/s/modest-zeh-w5c2wf?file=/src/App.js

**Comment by levipadre** [comment]
Sorry, but you are missing the point @Magesh-sam . It dooesn't matter if it's Bootstrap 4 or 5. I just copied a codesandbox code from before. But here it is your code: https://codesandbox.io/s/agitated-robinson-hy9r6p where I just `changed .btn-close` to fixed position.

**Comment by jquense** [comment]
@levipadre if you can't achieve it vis CSS then it isn't possible with the react-boostrap components, or really with the upstream design. You can take a look at the source code here for at how we implement the Modal using the upstream `@restart/ui` library, fork it and tweak the component as needed in your app. The specifics of how to achieve that are really outside the scope of this project though!
