### ISSUE TITLE
Glitchy Webpage Bug

### ISSUE THREAD

**Issue by osamakawish** [react-bootstrap/react-bootstrap#6660]
### Prerequisites

- [X] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [X] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug

Not a bug with react-bootstrap itself, I don't think, though it may be. But the official webpage for carousels [here](https://react-bootstrap.netlify.app/docs/components/carousel) gets very glitchy any time I try to change the slide for carousels. It may be my computer, but I tested on different browsers as well as private mode. So I'm just posting this issue just in case.

### Expected behavior

No glitch.

### To Reproduce

1. Go to [this page](https://react-bootstrap.netlify.app/docs/components/carousel)
2. Click on left or right slide button.
3. Observe glitch if it occurs.

### Reproducible Example

https://react-bootstrap.netlify.app/docs/components/carousel

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome, Microsoft Edge

### What version of React-Bootstrap are you using?

0.0.0

### What version of Bootstrap are you using?

0.0.0

### Additional context

This again, isn't necessarily directly an issue with React-Bootstrap, but the website for its docs.

**Comment by kyletsang** [comment]
Thanks for reporting.  Looks like there's issues with the minification of the css files in the production bundle.  Animations are fine in dev mode.
