### ISSUE TITLE
'Forms' Section missing from Navbar component documentation

### ISSUE THREAD

**Issue by cyberkitsune** [react-bootstrap/react-bootstrap#6665]
### Prerequisites

- [X] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [X] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug

When browsing to https://react-bootstrap.github.io/docs/components/navbar/#forms the documentation for embeding Form components in a navbar is missing.

### Expected behavior

I expect the 'Forms' section in the Navbar documentation to not be empty.

### To Reproduce

1. Browse to https://react-bootstrap.github.io/docs/components/navbar/#forms
2. Observe

### Reproducible Example

https://react-bootstrap.github.io/docs/components/navbar/#forms

### What version of React-Bootstrap are you using?

2.8.0

### What version of Bootstrap are you using?

latest

**Comment by yelwinsoe** [comment]
Can i work on this?
