### ISSUE TITLE
Bug ReactDOM.createPortal incompatibilities 

### ISSUE THREAD

**Issue by konapaz** [react-bootstrap/react-bootstrap#6670]
### Prerequisites

- [X] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [X] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug

Using Modal in ReactDOM.createPortal not append the modal into specified parent but always in body DOM, so it cannot be used a custom styling that is specified in parent sass/css and its components 

package.json

"react": "^18.2.0",
"react-dom": "^18.2.0",
"react-bootstrap": "^2.8.0",

### Reproducible Example

not a link 

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of React-Bootstrap are you using?

2.8.0

### What version of Bootstrap are you using?

5.3.0

**Comment by jquense** [comment]
Do you have a reproduction?

**Comment by konapaz** [comment]
> 

I solved this issue by add a prop in Modal

container={document.getElementById("my-element-id")}
