### ISSUE TITLE
Bug - Select default value cannot be set with props

### ISSUE THREAD

**Issue by ValeLouvet** [react-bootstrap/react-bootstrap#6677]
### Prerequisites

- [X] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [X] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug

Both defaultValue and value from Select and CheckBox are not working with change of state.

### Expected behavior

The defaultValue property should work properly.

Same as the following example:
https://codesandbox.io/s/smoosh-dawn-38tfg?file=/src/App.tsx

### Reproducible Example

https://codesandbox.io/s/polished-paper-rr66zj
https://codesandbox.io/s/distracted-moore-jq8dv4

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of React-Bootstrap are you using?

2.8.0

### What version of Bootstrap are you using?

5.3.1

**Comment by kyletsang** [comment]
If you're looking for a controlled input, you should be using both `value` and `onChange`.  Default value is meant for uncontrolled inputs.

**Comment by ValeLouvet** [comment]
Please take a look at both reproduction.
Neither defaultValue nor value are working.

**Comment by ValeLouvet** [comment]
> If you're looking for a controlled input, you should be using both `value` and `onChange`. Default value is meant for uncontrolled inputs.

Please take a look at both reproduction.
Neither defaultValue nor value are working.

**Comment by kyletsang** [comment]
Did you paste the right sandbox?  Both repros show controlled inputs and it works fine?

Take a look at this sandbox, it works fine:
https://codesandbox.io/s/tender-black-4ndztf?file=/src/App.tsx

**Comment by ValeLouvet** [comment]
> Did you paste the right sandbox? Both repros show controlled inputs and it works fine?
> 
> Take a look at this sandbox, it works fine: https://codesandbox.io/s/tender-black-4ndztf?file=/src/App.tsx

My issue is not related to controlled and uncontrolled inputs.
It is related to using props to initialize those values.
As described in both my sandbox links, as soon as I use props to initialize, it does not re-render.
For controlled inputs, this is the issue described here.
https://stackoverflow.com/questions/58818727/react-usestate-not-setting-initial-value
For uncontrolled inputs, this issue is the same. No re-render of the component due to a change of state of the props by the parent.

**Comment by kyletsang** [comment]
In your first sandbox:
https://codesandbox.io/s/polished-paper-rr66zj

You have a default value of 0 initialized in your state, which is passed down to `AppRoot` and in there, is passed to `defaultValue`.  `defaultValue` is only used on the first render, so your update inside the `useEffect` isn't going to change anything.

In your second sandbox:
https://codesandbox.io/s/distracted-moore-jq8dv4

You have a default value of 0 initialized in your state, which is passed down to `AppRoot` and in there, is used as the initialization param to the `tmpValue` state.  After the first render, it's not going to use that again so that's why your `setValue` call inside the `useEffect` does nothing.

The stackoverflow answer you posted has a good explanation about this already.  The way you're using the "tmp value state" is an anti pattern.  You should just use the value in your top level `App` component instead of trying to copy it inside `AppRoot`.

**Comment by ValeLouvet** [comment]
> In your first sandbox: https://codesandbox.io/s/polished-paper-rr66zj
> 
> You have a default value of 0 initialized in your state, which is passed down to `AppRoot` and in there, is passed to `defaultValue`. `defaultValue` is only used on the first render, so your update inside the `useEffect` isn't going to change anything.
> 
> In your second sandbox: https://codesandbox.io/s/distracted-moore-jq8dv4
> 
> You have a default value of 0 initialized in your state, which is passed down to `AppRoot` and in there, is used as the initialization param to the `tmpValue` state. After the first render, it's not going to use that again so that's why your `setValue` call inside the `useEffect` does nothing.
> 
> The stackoverflow answer you posted has a good explanation about this already. The way you're using the "tmp value state" is an anti pattern. You should just use the value in your top level `App` component instead of trying to copy it inside `AppRoot`.

I don't use the anti pattern on the child component where the bug is occuring.
I use it as an example of change of state on the parent.
My actual code is querying an API to change the state in the parent to initialize a complex object.
The child component is a partial part of this object that should be re-render when parent state is modified.
This is working for input but not for select and checkbox.
