### ISSUE TITLE
[deps] Check for breaking changes in Dependency Updates

### ISSUE THREAD

**Issue by gerpetto** [react-bootstrap/react-bootstrap#6681]
### Is your feature request related to a problem? Please describe

We noticed there were quite a number of Dependabot's PRs open. We ran Adaptly on one of them to help you catch breaking changes in these new versions. Our tool goes through the changelogs of the new versions and reports the breaking changes with a comment in the PR.

You can see two examples here:
- https://github.com/react-bootstrap/react-bootstrap/pull/6664
- https://github.com/react-bootstrap/react-bootstrap/pull/6676

### Describe the solution you'd like

If you want to give it a try: https://github.com/marketplace/adaptly
It's completely free and plug-and-play since you are already using Dependabot.

We would love to hear your feedback! : )

**Comment by kyletsang** [comment]
Sorry, we'll pass on this
