### ISSUE TITLE
Problem with `yarn start` script

### ISSUE THREAD

**Issue by kenedyolisi** [react-bootstrap/react-bootstrap#6683]
I have forked the project and downloaded it locally on PC.
Ran yarn bootstrap to install dependencies.
Now running `yarn start` in root directory gives me this error:
`Internal Error: ENOENT: no such file or directory, lstat 'D:\projects\react_bootstrap_fork\www\www`
👇
![image](https://github.com/react-bootstrap/react-bootstrap/assets/66219869/7c47601f-3332-406b-a8cb-cefdd108793b)

Any help!

**Comment by kyletsang** [comment]
Are you sure you cloned it properly?  There's only supposed to be one www folder in the repo
