### ISSUE TITLE
Cannot read properties of null (reading 'useContext') while rendering Button component.

### ISSUE THREAD

**Issue by reactslayer** [react-bootstrap/react-bootstrap#6702]
I am trying to use Button from react-bootstrap. My react version is 18.2.0 . 
`<div className="App">`
    `  <Button as="a" variant="primary">`
    `     Button as link`
     ` </Button>`
`</div>`
I get an error **Cannot read properties of null (reading 'useContext')**
I got an error **Cannot read properties of null (reading useState) ** when I tried using Modal. 
I am new to react and react-bootstrap.
 **_What Is going on?_**

**Comment by GaneshKumar932** [comment]
We may need more info on this @reactslayer. Could you please give some steps to reproduce this issue.
