### ISSUE TITLE
Is there a way to pass a custom element to DropdownButton?

### ISSUE THREAD

**Issue by ilmattodel93** [react-bootstrap/react-bootstrap#671]
First of all thanks for your library!
What I would like to achieve is the possibility to have the third item have the icon as the first two does.

            <Navbar inverse staticTop toggleNavKey={0}>
                <CollapsibleNav eventKey={0}>
                    <Nav navbar eventKey={0}>
                        <NavItem eventKey={1} to="auth" className="with-icon">
                            <span className="icon fa fa-user"></span>    
                            <span>Accedi</span>
                        </NavItem>
                        <NavItemLink eventKey={2} to="root" className="with-icon">
                            <span className="icon fa fa-home"></span>    
                            <span>Home</span>
                        </NavItem>
                        <DropdownButton eventKey={3} title='Dropdown'>
                            <MenuItem eventKey='1'>Action</MenuItem>
                            <MenuItem eventKey='2'>Another action</MenuItem>
                            <MenuItem eventKey='3'>Something else here</MenuItem>
                            <MenuItem divider />
                            <MenuItem eventKey='4'>Separated link</MenuItem>
                        </DropdownButton>
                    </Nav>
                    <Nav navbar right eventKey={4}>
                        <DropdownButton eventKey={5} title="User">
                            <MenuItem eventKey='1'>Action</MenuItem>
                            <MenuItem eventKey='2'>Another action</MenuItem>
                            <MenuItem eventKey='3'>Something else here</MenuItem>
                            <MenuItem divider />
                            <MenuItem eventKey='4'>Separated link</MenuItem>
                        </DropdownButton>
                    </Nav>
                </CollapsibleNav>
            </Navbar>

**Comment by mtscout6** [comment]
Yes the title prop can take a react element:

```
let title = <span className='herpa derpa'>blah</span>;

return (
  <DropdownButton title={title}>
    ...
  </DropdownButton>
);

**Comment by rkhayat** [comment]
While this is old, and closed, my outcome is a little different.


```
var myVar = "Clicked :";
let title = myVar +  <span className='herpa derpa'>blah</span>;

return (
  <DropdownButton title={title}>
    ...
  </DropdownButton>
);
```


The code above puts "Clicked : [object object]" on the dropdown, is there a way around this?

**Comment by jquense** [comment]
you aren't using jsx correctly;

`<span>{"Clicked : " } <span className='herpa derpa'>blah</span></span>`

**Comment by rkhayat** [comment]
Thanks, stupid mistake :+1
