### ISSUE TITLE
Dropdown.Toggle does not work correctly when using mousedown as rootCloseEvent

### ISSUE THREAD

**Issue by Fyers** [react-bootstrap/react-bootstrap#6712]
### Prerequisites

- [X] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [X] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug

This was already reported back in 2018 (https://github.com/react-bootstrap/react-bootstrap/issues/3196) and is still an issue.

Just create a dropdown with the `rootCloseEvent="mousedown"`. When tyring to close the dropdown with the toggle button the dropdown will flicker since it is hidden on mousedown but is being shown on onClick due to the logic in the toggle.

`mousedown` is in some circumstances essential to the functionality over the `click` rootCloseEvent.
For example I have a Drag&Drop Grabber to move the object where the dropdown lives. There will be no onClick event since I am dragging the item but I do want the dropdown to close when I drag the item.

```
<Dropdown>
    <Dropdown.Toggle variant="success" id="dropdown-basic">
        Dropdown Button
    </Dropdown.Toggle>

    <Dropdown.Menu rootCloseEvent="mousedown">
        <Dropdown.Item href="#/action-1">Action</Dropdown.Item>
        <Dropdown.Item href="#/action-2">Another action</Dropdown.Item>
        <Dropdown.Item href="#/action-3">Something else</Dropdown.Item>
    </Dropdown.Menu>
</Dropdown>
```

### Expected behavior

The toggle should support any valid `rootCloseEvent` as you would expect or the `mousedown` rootCloseEvent should be removed since its only supported for hiding and not showing.

### Reproducible Example

https://codesandbox.io/s/xenodochial-frost-69cl6x

### What version of React-Bootstrap are you using?

2.9.0

### What version of Bootstrap are you using?

5.3.2

**Comment by mvaibhav77** [comment]
Hey @Fyers, Is there any reason you are using the mouse down event instead of the mouse up or click event? I think the default click event is firing up which opens the dropdown menu. I suggest not using the mouse-down event to close the menu.

**Comment by Fyers** [comment]
> Hey @Fyers, Is there any reason you are using the mouse down event instead of the mouse up or click event? I think the default click event is firing up which opens the dropdown menu. I suggest not using the mouse-down event to close the menu.

In my situation this wont work since - as stated - I have a Drag & Drop Grabber visible in the same context. If I open the Dropdown and then start dragging the element the drop down would still be visible since the onClick will not fire when I am dragging since I dont let go of the mouse.

I know I can work arround this with an own logic which will handle all this but then I would need to implement a workaround but the control specifically support mouseDown event so this should work as u would expect it to, or the mouseDown support should be removed.

**Comment by mvaibhav77** [comment]
Hi @Fyers, Now I understand what is happening here. The rootCloseEvent should work when we click or mouse down outside of the dropdown menu. As stated in here:-
DropdownMenu.tsx
```tsx
 /**
   * Which event when fired outside the component will cause it to be closed
   *
   * *Note: For custom dropdown components, you will have to pass the
   * `rootCloseEvent` to `<RootCloseWrapper>` in your custom dropdown menu
   * component ([similarly to how it is implemented in `<Dropdown.Menu>`](https://github.com/react-bootstrap/react-bootstrap/blob/v0.31.5/src/DropdownMenu.js#L115-L119)).*
   */
  rootCloseEvent: PropTypes.oneOf(['click', 'mousedown']),
```
But the close function is also triggered when we click the dropdown button. So that is creating a conflict, I think this issue is worth looking into. I will try to solve this as soon as possible.

**Comment by mvaibhav77** [comment]
@Fyers, Can you take a look at the PR to confirm the issue is resolved.

**Comment by Fyers** [comment]
@mvaibhav77 can confirm fix via deployed preview.

**Comment by mvaibhav77** [comment]
> @mvaibhav77 can confirm fix via deployed preview.

@Fyers Go to the PR, there is the netlify preview you can run. If something is still creating probelms then tell me.

**Comment by Fyers** [comment]
> > @mvaibhav77 can confirm fix via deployed preview.
> 
> @Fyers Go to the PR, there is the netlify preview you can run. If something is still creating probelms then tell me.

Yeah thats what I meant. The fix works 👍
