### ISSUE TITLE
The dropdown menu will be displayed in the upper left corner of the screen when I use onToggle

### ISSUE THREAD

**Issue by Louise-Huang** [react-bootstrap/react-bootstrap#6716]
### Prerequisites

- [X] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [X] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug

When I use normal `Dropdown.Toggle` and `Dropdown.Menu`, the dropdown menu can be displayed in the normal position, but occasionally it goes to the upper left of the screen. When I add `onToggle` and `show` to Dropdown, the dropdown menu will only be displayed in the upper left corner of the screen. I need to capture the moment when the dropdown menu is closed, so I need to use `show` and `onToggle` to control the dropdown menu switch.

### Expected behavior

The dropdown menu should appear below toggle button.

### Reproducible Example

https://codesandbox.io/s/silent-voice-fns8nd?file=/src/DragDropDown.jsx

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome, Microsoft Edge

### What version of React-Bootstrap are you using?

^2.9.1

### What version of Bootstrap are you using?

^5.3.2

**Comment by ShaneUP1** [comment]
I'm having this same issue. What I've noticed is that if I don't include a local state change then the menu stays where it should, but I'm in a similar position where I need to manually control the 'show' prop. I think something is happening when the local state changes where the menu is losing it's reference node..

**Comment by kyletsang** [comment]
The sandbox is using bootstrap 3 and the version of the bug report is using 4.6.1

react-bootstrap v2 only works with bootstrap 5.  See compatibility chart here:
https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility

Could you try again using the correct matched versions of bootstrap and react-bootstrap?

**Comment by ShaneUP1** [comment]
Here's a sandbox with the correct compatibilities and the same issue:
https://codesandbox.io/s/ecstatic-frost-ztry6z?file=/src/AddUsers.tsx

**Comment by Louise-Huang** [comment]
@kyletsang Sorry for writing the wrong version. I tried using bootstrap v5.3.2 and react-bootstrap v2.9.0 but still the same result.

**Comment by Louise-Huang** [comment]
@ShaneUP1 You are right! Thanks for the discovery! But I need to know the timing of menu switching through a local state, so I used `show` and `onToggle`....

**Comment by Louise-Huang** [comment]
@ShaneUP1 Anyway thanks for letting me know what the problem was. Let's find a solution together!😄

**Comment by shashi2290** [comment]
Reproducible Example
https://codesandbox.io/s/silent-voice-fns8nd?file=/src/DragDropDown.jsx


solution
[https://codesandbox.io/s/wizardly-poincare-knzqyq?file=/src/DragDropDown.jsx](url)

**Comment by ShaneUP1** [comment]
I don't think this is a valid solution. You're using styles to manually place the menu on the screen, so it's not using the forwardRef at all. I also don't think the ref's you're setting are actually doing anything.

Something is going on with the forwardRef in this component. My hunch is that it's coming back undefined and so the menu just gets rendered at 0,0. It's the same reason that using the 'drop' prop that determines which direction the menu is opened up doesn't really work. In this example it doesn't work at all either.

**Comment by ShaneUP1** [comment]
There are some major things going wrong with this component. Even on the demo page around the 'drop' direction stuff it the demo doesn't act accordingly. 

Here I clicked drop end:
![image](https://github.com/react-bootstrap/react-bootstrap/assets/64820882/e11223cd-e97c-4e13-9f95-d1f388b75847)

And here I clicked drop start:
![image](https://github.com/react-bootstrap/react-bootstrap/assets/64820882/7559cddf-130a-4c69-a164-8183879dc6db)

They're the same?

**Comment by kyletsang** [comment]
Sorry missed this before, but the toggle component should not be defined in a render body of another component.  This will cause issues.  

I forked the sandbox with the corrected code here:
https://codesandbox.io/s/awesome-sunset-njz6df?file=/src/customToggle1.tsx

**Comment by ShaneUP1** [comment]
Yep, you're right. A friend pointed that out to me this past weekend and I forgot to update here. I solved it by wrapping the toggle component in a useMemo.

**Comment by Louise-Huang** [comment]
@kyletsang You're right! I solved this problem by moving `customToggle` outside the component that renders the body. Thank you so much.
