### ISSUE TITLE
cannot be used as a JSX component.  Its type is not a valid JSX element type.

### ISSUE THREAD

**Issue by Inplex-sys** [react-bootstrap/react-bootstrap#6717]
### Prerequisites

- [X] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [X] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug

Since the v2.9 i'm have this issue for each ReactBoostrap Component that i'm using:
```
'Tab.Content' cannot be used as a JSX component.
  Its type 'BsPrefixRefForwardingComponent<"div", TabContentProps>' is not a valid JSX element type.
    Type 'BsPrefixRefForwardingComponent<"div", TabContentProps>' is not assignable to type '(props: any, deprecatedLegacyContext?: any) => ReactNode'.
      Type 'ReactElement<any, string | JSXElementConstructor<any>> | null' is not assignable to type 'ReactNode'
```

The App is working well on the browser, but thoses errors are still annoying me

### Expected behavior

Not having this error showing in my IDE

### To Reproduce

1. Setup a Vite App (TSX) with Bun
2. Install ReactBootsrap/Bootsrap
3. Try to use a react component

### Reproducible Example

None

### Screenshots

![image](https://github.com/react-bootstrap/react-bootstrap/assets/69421356/47d2210d-64e9-44b0-92d0-ccfc474ff08e)

### What operating system(s) are you seeing the problem on?

Linux

### What browser(s) are you seeing the problem on?

Firefox

### What version of React-Bootstrap are you using?

2.9.1

### What version of Bootstrap are you using?

5.3

**Comment by kyletsang** [comment]
What version of react and `@types/react` are you using?  I can't reproduce this on my local vite project

**Comment by Inplex-sys** [comment]
```json
{
  "name": "react-app",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "tsc && vite build",
    "lint": "eslint . --ext ts,tsx --report-unused-disable-directives --max-warnings 0",
    "preview": "vite preview"
  },
  "dependencies": {
    "chart.js": "^4.4.0",
    "react": "^18.2.0",
    "react-bootstrap": "^2.9.0",
    "react-chartjs-2": "^5.2.0",
    "react-dom": "^18.2.0",
    "react-hook-form": "^7.47.0",
    "react-range": "^1.8.14",
    "react-router-dom": "^6.16.0",
    "react-text-transition": "^3.1.0"
  },
  "devDependencies": {
    "@types/react": "^18.2.15",
    "@types/react-dom": "^18.2.7",
    "@typescript-eslint/eslint-plugin": "^6.0.0",
    "@typescript-eslint/parser": "^6.0.0",
    "@vitejs/plugin-react-swc": "^3.3.2",
    "eslint": "^8.45.0",
    "eslint-plugin-react-hooks": "^4.6.0",
    "eslint-plugin-react-refresh": "^0.4.3",
    "typescript": "^5.0.2",
    "vite": "^4.4.5"
  }
}
```

**Comment by kyletsang** [comment]
I tried the specific versions in the package.json and still can't repro.  We would need a complete repro to be able to debug.

**Comment by lytieuphong** [comment]
I downgrade to 18.2 then it resolved.

```json
    "@types/react": "^18.2.37",
    "@types/react-dom": "^18.2.15",
```

**Comment by keverw** [comment]
Interesting, I just spent the day running into the same issue and just wen though commenting and uncommenting until I narrowed it down to react-bootstrap... but not sure what the root cause is. Feel like downgrading is ok temporality but worried if any long term issues with one of the tools or libraries. So a little indecisive

**Comment by Jarred-Sumner** [comment]
When you run into bugs with Bun and it works in Node, that's a bug that Bun is responsible for fixing. We don't want to make life harder for library maintainers. Please file issues like this in Bun's repository instead

**Comment by skashi** [comment]
This worked for me:
https://github.com/react-bootstrap/react-bootstrap/issues/6819#issuecomment-2185599914

**Comment by LuthGom** [comment]
> I downgrade to 18.2 then it resolved.
> 
> ```json
>     "@types/react": "^18.2.37",
>     "@types/react-dom": "^18.2.15",
> ```

Thank you so much! I was having that issue and your comment just save my day!! My project came back working!!
