### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by Rod-T** [react-bootstrap/react-bootstrap#6718]
I'm getting the following error and I have no idea what it could be? I'm on version 0.32.4 for reference

../node_modules/react-bootstrap/esm/TabContent.js
Module parse failed: Unexpected token (11:2)
You may need an appropriate loader to handle this file type.
|   bsPrefix,
|   as: Component = 'div',
|   ...props
| }, ref) => {
|   bsPrefix = useBootstrapPrefix(bsPrefix, 'tab-content');

**Comment by kyletsang** [comment]
Sounds like you didn't configure babel properly.  Check your config.  

BTW 0.32.4 is quite old now and unsupported
