### ISSUE TITLE
Support for onSearch event handler

### ISSUE THREAD

**Issue by ptahchiev** [react-bootstrap/react-bootstrap#6727]
### Prerequisites

- [X] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [X] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug

Hello,

I want to have input of type search and I want to handle the onsearch events

https://www.w3schools.com/jsref/event_onsearch.asp

but it seems like it is impossible now.

I get this instead:
```
bundle.js:153807 Warning: Unknown event handler property `onsearch`. It will be ignored.
    at input
    at http://localhost:3000/static/js/bundle.js:143591:3
    at div
    at http://localhost:3000/static/js/bundle.js:144041:3
    at div
    at http://localhost:3000/static/js/bundle.js:142291:8
```

### Reproducible Example

https://f54m2.csb.app/

### What version of React-Bootstrap are you using?

2.7.4

### What version of Bootstrap are you using?

5.3.2

**Comment by jquense** [comment]
This is not a RB issue, it's React, react-dom doesn't support this event
