### ISSUE TITLE
Range slider light mode support

### ISSUE THREAD

**Issue by Rolv-Apneseth** [react-bootstrap/react-bootstrap#6736]
### Prerequisites

- [X] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [X] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug

As you can hopefully see from the below screenshots, the range slider doesn't seem to support light mode? Or at least the track colour doesn't look the best as I can barely see it. It looks fine in dark mode though.

Would it be possible for this to use a better colour by default?

### Reproducible Example

https://react-bootstrap.netlify.app/docs/forms/range/

### Screenshots

![range_light_mode](https://github.com/react-bootstrap/react-bootstrap/assets/69486699/3c2bbed6-c6a6-4840-b6a4-c07b5ad181ae)
![range_dark_mode](https://github.com/react-bootstrap/react-bootstrap/assets/69486699/dfe85217-5dc8-414c-887a-d536ebebc13f)

### What operating system(s) are you seeing the problem on?

Linux

### What browser(s) are you seeing the problem on?

Chrome, Firefox

### What version of React-Bootstrap are you using?

2.9.1

### What version of Bootstrap are you using?

5.3.2

**Comment by kyletsang** [comment]
This is actually a docs issue due to conflicting styles with bootstrap and docusaurus.  The slider in light mode will work fine in your app

**Comment by Rolv-Apneseth** [comment]
I was actually having this in app, but noticed the same thing in the docs so assumed that was a better example. Thanks though I'll have a look if I'm also having some kind of conflict.
