### ISSUE TITLE
Add a Timeline component.

### ISSUE THREAD

**Issue by Abhith-S** [react-bootstrap/react-bootstrap#6740]
### Is your feature request related to a problem? Please describe

There is no timeline component available naively in react bootstrap. This is component is available in mdbootstrap and also materialUI. 

example of component to be created : 

![timeline](https://github.com/react-bootstrap/react-bootstrap/assets/75518181/fe3d903c-81da-451b-a5e6-b4bfbd52051c)

### Describe the solution you'd like

Mdbootstrap has a timeline component with different styles. It will be beneficial if react-bootstrap can replicate it.

link to mdbootstrap timeline - https://mdbootstrap.com/docs/standard/extended/timeline/

**Comment by jquense** [comment]
react-bootstrap only implements components that exist in the normal bootstrap library, so something like this, while cool, is out of scope.
