### ISSUE TITLE
[Question] Is it possible to center the React Bootsrap ProgressBar's label?

### ISSUE THREAD

**Issue by GuiRodriguero** [react-bootstrap/react-bootstrap#6741]
I'm working with React-Bootsrap ProgressBar and I notice the component aligns its label based on its value:
![image](https://github.com/react-bootstrap/react-bootstrap/assets/50684900/4868804d-67d0-4f74-a6d0-e815f3f77492)
I was wondering if it was possible to center the label regardless its value, like this (random example):
![image](https://github.com/react-bootstrap/react-bootstrap/assets/50684900/32f8dd12-e162-4773-b5ec-67141c9f3317)

My component:
`<ProgressBar
    now={....}
    label={....}
    className={....}
/>`

Result on browser dev tools:
```
<div class="..... progress">
    <div role="progressbar" class="progress-bar" aria-valuenow="40" aria-valuemin="0" aria-    valuemax="100">
        dummy
    </div>
</div>
```

I tried styling the progress and progress-bar classes, but I couldn't style the text inside. I also tried to use ::after on CSS, but ended up with the same problem - **I can't get access to the label value.** 

Is there a way to do this using React Bootstrap Progress Bar?

**Comment by kyletsang** [comment]
Unfortunately not at this time since the text is placed within the progress bar itself rather than the container

**Comment by GuiRodriguero** [comment]
Thanks for you answer. Can you tell me if there is any plans or intention to solve this?

**Comment by kyletsang** [comment]
There won't be any out of the box solutions for now since we just follow the markup that vanilla bootstrap uses in their progress bars, however this component is a bit flexible where you can add in any child div and that will render as is.

See below example, this should center a div within the progress bar.
```
<ProgressBar className="position-relative">
  <div className="position-absolute d-flex justify-content-center w-100 text-danger">25%</div>
  <ProgressBar striped variant="success" now={25} key={1} />
</ProgressBar>
```
