### ISSUE TITLE
Button is not responsive inside the MODAL

### ISSUE THREAD

**Issue by KingNelx** [react-bootstrap/react-bootstrap#6755]
### Prerequisites

- [X] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [X] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug

Hi, tried it on chrome and brave but the Button is very unresponsive. I really don't know why. But when i copy the whole FORM into new component (no modal included) it works.

### Expected behavior

I was hoping i can add a new record (The Form inside the MODAL)

### Reproducible Example

N/A

### What version of React-Bootstrap are you using?

5

### What version of Bootstrap are you using?

5

**Comment by kyletsang** [comment]
Can you clarify what is "unresponsive"?   Also we require reproducible code if you need support.  Please use code sandbox.

**Comment by KingNelx** [comment]
hi this is my first time opening an issue, whats the use of sandbox?
