### ISSUE TITLE
defaultActiveKey and alwaysOpen not working properly at the same time

### ISSUE THREAD

**Issue by AmanDevUI** [react-bootstrap/react-bootstrap#6757]
### Prerequisites

- [X] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [X] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug

I'm working with accordion but i found a bug is that when defaultActiveKey and alwaysOpen prop are added in Accordion, for the first time it will not work properly and give unwanted behavior. If the defaultActiveKey is set to 0 and also add the alwaysOpen prop, when click on the first item it doesn't close at the first time, for second time it'll colse. And if you click on the second item, first item wil be close but the behaviour of alwaysOpen is set the item always open if it is not collapsed.

### Reproducible Example

https://codesandbox.io/p/sandbox/angry-fire-79trc2?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clpuypm8500062v6kobqu290y%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clpuypm8500022v6kcde7o2xv%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clpuypm8500032v6k94k4mskj%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clpuypm8500052v6kaz3dcbjp%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clpuypm8500022v6kcde7o2xv%2522%253A%257B%2522id%2522%253A%2522clpuypm8500022v6kcde7o2xv%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clpuypm8500052v6kaz3dcbjp%2522%253A%257B%2522id%2522%253A%2522clpuypm8500052v6kaz3dcbjp%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clpuypm8500042v6kvgcr0wdk%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clpuypm8500042v6kvgcr0wdk%2522%257D%252C%2522clpuypm8500032v6k94k4mskj%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clpuypm8500032v6k94k4mskj%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### What version of React-Bootstrap are you using?

2.10.0

### What version of Bootstrap are you using?

5.3.2

**Comment by kyletsang** [comment]
When you use `alwaysOpen`, the values for `defaultActiveKey` and `activeKey` should be arrays.
