### ISSUE TITLE
Tabs Component doesn't pass id attribute to underlying element

### ISSUE THREAD

**Issue by ctgbarcalow** [react-bootstrap/react-bootstrap#6766]
### Prerequisites

- [X] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [X] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug

<Tabs /> component accepts id as an attribute but does not pass it to the underlying element.

### Expected behavior

Given the following code, I would expect that when the ul element is returned, the id would be present.
```
<Tabs id="my-tabs">
...
</Tabs>
```

### To Reproduce

Create a project with a <Tabs> component. Give it an id and "inspect" the source.

### Reproducible Example

https://codesandbox.io/p/sandbox/react-bootstrap-tabs-id-bug-8ddkmw?file=%2Fsrc%2FApp.tsx%3A16%2C1

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of React-Bootstrap are you using?

2.1

### What version of Bootstrap are you using?

N/A

**Comment by duyguca** [comment]
https://github.com/react-bootstrap/react-bootstrap/pull/6767

**Comment by Ankitchaudharyy** [comment]
I can work on this issue. Please assign it to me.
