### ISSUE TITLE
React Bootstrap doesn't let me set background color

### ISSUE THREAD

**Issue by reinaldofox** [react-bootstrap/react-bootstrap#6770]
### Prerequisites

- [X] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [X] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug

In my React app the tables suddenly started to appear with a background that I didn't define.
![white-table](https://github.com/react-bootstrap/react-bootstrap/assets/1627337/6a58b38f-460b-42b5-b459-8c754c626703)

I researched and discovered that Bootstrap automatically defines a Light theme, so much so that when I define <html " data-bs-theme="dark"> the tables become dark.
It turns out that I don't want either Dark or Light, I want to define my backgrounds and even overwriting the rule doesn't work.

Hor the table should look like:
![tabela-estilizada](https://github.com/react-bootstrap/react-bootstrap/assets/1627337/03b69c06-a76b-48fc-b01a-5abdcbac8bed)

Maybe it's something silly, but I'm racking my brain and this nonsense is making me mad.

### Reproducible Example

without reprodution

### What operating system(s) are you seeing the problem on?

Linux

### What browser(s) are you seeing the problem on?

Chrome

### What version of React-Bootstrap are you using?

2.10.1

### What version of Bootstrap are you using?

5.3.3

**Comment by kyletsang** [comment]
We actually don't handle the styling of the components in this repo.  Can you please file this issue over at https://github.com/twbs/bootstrap/issues?
