### ISSUE TITLE
Bug: OverlayTrigger doesn't hide after modal close.

### ISSUE THREAD

**Issue by lwl5219** [react-bootstrap/react-bootstrap#6771]
### Prerequisites

- [x] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [X] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug

A popover for a button is triggered by hover. The OverlayTrigger always shows if the modal closes even I move cursor to other places.

### Expected behavior

The OverlayTrigger always be hidden if the modal closes.

### To Reproduce

1. Move cursor to the "Show Save View" button. You will see the popover with the content "Save View"
2. Click the button
3. Click the close icon or the save button
4. The popover doesn't hide even when you move cursor to other places.

### Reproducible Example

https://codesandbox.io/p/sandbox/bootstrap-react-overlaytrigger-8zskrq

### Screenshots

![Bootstrap-React-Overlay](https://github.com/react-bootstrap/react-bootstrap/assets/4666735/3b8c5949-cc35-4bad-9c8e-c2dac71e0653)

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome, Microsoft Edge

### What version of React-Bootstrap are you using?

2.6.0

### What version of Bootstrap are you using?

5.2.2

**Comment by ParthSatasiya** [comment]
This is not a bug, because after closing the modal browser focus on the last selected element. so in your case, your last active element is the button. so that's why overlay is displayed.

you can verify this by firing the script in the console.
`setTimeout(() => console.log(document.activeElement), 10000);`

After firing it please open the modal quickly and close it within 10 seconds. now wait for the console. you can see the activeElement button.

I also found the solution to prevent this type of behavior. Just added `event.target.blur()` in the click event. Please check the code below: 

```javascript
const ModalTrigger = () => {
  const [show, setShow] = useState(false);

  return (
    <>
      <OverlayTrigger
        overlay={
          <Popover>
            <Popover.Body>Save View</Popover.Body>
          </Popover>
        }
      >
        <button
          type="button"
          className="btn btn-outline-secondary me-2"
          onClick={(event) => {
            event.target.blur(); // Added Code
            setShow(true);
          }}
        >
          <i className="fa-solid fa-camera"></i>Show Save View
        </button>
      </OverlayTrigger>
      <SaveViewModal show={show} onHide={() => setShow(false)} />
    </>
  );
};
``` 

https://github.com/react-bootstrap/react-bootstrap/assets/31753548/75ac0daf-089c-4841-a4fa-61cbe15868a8

**Comment by lwl5219** [comment]
Thanks @ParthSatasiya. 
Your idea is a workaround and inspires me. The **hover** action is triggered by the `onMouseEnter` and `onMouseLeave` events. The **focus** action is triggered by the `onFocus` and `onBlur` events. I checked the documentation, the default value of the trigger is `['hover', 'focus']`. The popover persists due to the button is still focused, even though the mouse has left. So the below code works

```javascript
const ModalTrigger = () => {
  const [show, setShow] = useState(false);

  return (
    <>
      <OverlayTrigger
        trigger="hover" 
        overlay={
          <Popover>
            <Popover.Body>Save View</Popover.Body>
          </Popover>
        }
      >
        <button
          type="button"
          className="btn btn-outline-secondary me-2"
          onClick={(event) => {
            setShow(true);
          }}
        >
          <i className="fa-solid fa-camera"></i>Show Save View
        </button>
      </OverlayTrigger>
      <SaveViewModal show={show} onHide={() => setShow(false)} />
    </>
  );
};
```

**Comment by gugu-lee** [comment]
i download this project ,but on my computer,it do not work. i test is on nodejs v21 and v14.

**Comment by gugu-lee** [comment]
i know how resolve it:

{
show?<Modal />:null
}

**Comment by lwl5219** [comment]
> i know how resolve it:
> 
> { show?<Modal />:null }

Here is the documentation link: [overlaytrigger](https://react-bootstrap.github.io/docs/components/overlays#overlaytrigger-1)

The default value of the **trigger** is `['hover', 'focus']`. I replaced it with `["hover", "click"]`.
