### ISSUE TITLE
Rendering children (Accordion)

### ISSUE THREAD

**Issue by ravi-github** [react-bootstrap/react-bootstrap#6772]
Hey,

Really great work !! Very useful to the community ! 

Just a curiosity question ! Am very curious as to how are children being rendered in say AccordionItem || AccordionHeader ? 

I do not see the normal { children } render . 

Will be helpful to the open source community to understand how this works !!

Thanks,
Ravi.

**Comment by jquense** [comment]
`children` is spread into the component via `{...props}`
