### ISSUE TITLE
Modal component stop working when closed

### ISSUE THREAD

**Issue by GianlucaStudioAlive** [react-bootstrap/react-bootstrap#6778]
### Prerequisites

- [X] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [X] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug

Hello everyone, last night i started i new project using nextjs 14.1.19 and what happened is when i load the main page, i have a button to open a modal , the modal opening fine but when i.m closing it, it seems like it just get an opacity:0 rule but it wont let me click anymore on my page, the page won't scroll too it seemes like the modal is stucked but invisible.
than i try te replace the entire page only with your Modal component and stil not working. I've trieed on others website i made with previous version of nextjs and is working fine. i apologize for my bad english and i'm here in case you need more descripotion. 
many thanks to all
J.

### Reproducible Example

dont have a link

### What version of React-Bootstrap are you using?

2.10.1

### What version of Bootstrap are you using?

5.3.3.

**Comment by kyletsang** [comment]
Can you post some code or post a link to a reproducible example on github?

**Comment by GianlucaStudioAlive** [comment]
"use client";
import { useState } from "react";
import {Button}from "react-bootstrap";
import {Modal} from "react-bootstrap";

function Example() {
  const [show, setShow] = useState(false);

  const handleClose = () => setShow(false);
  const handleShow = () => setShow(true);

  return (
    <>
      <Button variant="primary" onClick={handleShow}>
        Launch demo modal
      </Button>

      <Modal show={show} onHide={handleClose} animation={false}>
        <Modal.Header closeButton>
          <Modal.Title>Modal heading</Modal.Title>
        </Modal.Header>
        <Modal.Body>Woohoo, you are reading this text in a modal!</Modal.Body>
        <Modal.Footer>
          <Button variant="secondary" onClick={handleClose}>
            Close
          </Button>
          <Button variant="primary" onClick={handleClose}>
            Save Changes
          </Button>
        </Modal.Footer>
      </Modal>
    </>
  );
}

export default Example;
this is the code i get form the bootstrap library.. it seems like not working on the latest version of nextjs. I asked a frined of mine too to try it on his computer and he got the same issue.
to install the bootstrap library i used npm install react-bootstrap bootstrap and than i added @import 'bootstrap/dist/css/bootstrap.min.css'; to the global css file.. 
many thanks for ur responde
J.

**Comment by kyletsang** [comment]
Sorry inadvertently broke this upstream.  Will cut a new release today

**Comment by kyletsang** [comment]
Fixed in v2.10.2

**Comment by radar** [comment]
We just bumped into this as well. Thank you for getting a fix together so quickly!

**Comment by GianlucaStudioAlive** [comment]
thank you so much now working fine !
