### ISSUE TITLE
ESC and Up/Down in Dropdown doesn't work when using the native Bootstrap

### ISSUE THREAD

**Issue by zhaoyu1999** [react-bootstrap/react-bootstrap#6790]
### Prerequisites

- [X] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [X] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug

Not sure if this is a bug or not. My app has some legacy pages that still use jQuery, so I have to reference the native Bootstrap library and react-bootstrap on the same page. When pressing ESC or Up/Down, the "undefined" error happens.

### Expected behavior

The ESC and Up/Down should work

### To Reproduce

- Open the dropdown menu.
- Focus on the input.
- Press ESC.

### Reproducible Example

https://codesandbox.io/p/sandbox/nostalgic-framework-xst2hm

### Screenshots

![dropdown](https://github.com/react-bootstrap/react-bootstrap/assets/1793554/01fa1554-8313-4eab-b6f1-e0b271a89db8)

### What operating system(s) are you seeing the problem on?

Windows, Linux

### What browser(s) are you seeing the problem on?

Chrome, Microsoft Edge

### What version of React-Bootstrap are you using?

2.10.2

### What version of Bootstrap are you using?

5.3.2

### Additional context

Note that I reference native bootstrap in the HTML.
![image](https://github.com/react-bootstrap/react-bootstrap/assets/1793554/048a49e6-1b88-4d62-af5c-e6b6af16c357)

**Comment by kyletsang** [comment]
Yeah this is a conflict between react-bootstrap and regular bootstrap.  Bootstrap's JS assumes certain data attributes and elements exist in the DOM during init.

This might be fixed by forcing the react components to mimic what bootstrap expects.  Can you try adding `data-bs-toggle="dropdown"` to the `Dropdown.Toggle` and `renderOnMount` to the `Dropdown.Menu`?

Like this:

```
    <Dropdown>
      <Dropdown.Toggle variant="success" id="dropdown-basic" data-bs-toggle"dropdown">
        Dropdown Button
      </Dropdown.Toggle>

      <Dropdown.Menu renderOnMount>
        <input type="text" />
        <Dropdown.Item href="#/action-1">Action</Dropdown.Item>
        <Dropdown.Item href="#/action-2">Another action</Dropdown.Item>
        <Dropdown.Item href="#/action-3">Something else</Dropdown.Item>
      </Dropdown.Menu>
    </Dropdown>
```

**Comment by zhaoyu1999** [comment]
Hi Kyletsang,

Yes, adding `data-bs-toggle` and `renderOnMount` works for me. Thanks!!!
