### ISSUE TITLE
EventKey in callback function onSelect of Tabs component does not match type of EventKey given to an individual Tab component

### ISSUE THREAD

**Issue by Joshlha** [react-bootstrap/react-bootstrap#6795]
### Prerequisites

- [X] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [X] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug

A `Tab`'s `eventKey` react property is specified as having type `string | number`.
![image](https://github.com/freeranger/react-bootstrap-tabs/assets/43594988/96112ede-ab62-4c6d-be80-6c92fa2b4e41)
![image](https://github.com/freeranger/react-bootstrap-tabs/assets/43594988/ac62d35c-628d-4998-ac44-2979b94a1bd4)

But the callback function for the `Tabs`'s `onSelect` specifies the `eventKey` argument as having type `string | null`
![image](https://github.com/freeranger/react-bootstrap-tabs/assets/43594988/5fc4e6d0-9b7d-47e7-95c6-28cd4bdf1c4a)

This means that you need to do some manual type conversion or checking to properly handle `eventKey`s which are `number`s.

Example where setting a `Tab`'s `eventKey` to a number:
![image](https://github.com/freeranger/react-bootstrap-tabs/assets/43594988/d900798b-74b2-4a9a-942e-2a23ee3045d3)

And getting an error when trying to compare it to a number, or do any sort of numeric operation:
![image](https://github.com/freeranger/react-bootstrap-tabs/assets/43594988/eaa01c10-f154-47b7-a11e-77e6e3385b79)

I'm not sure if this is an issure with the underlying library used ([react-restart](https://github.com/react-restart/ui)) or if it's the way the `Tabs` component is implemented using this library, so I'm starting here.

### Expected behavior

The `eventKey` parameter in  the `onSelect` callback function in `Tabs` should match the type of the `eventKey` property in the `Tab` component

### To Reproduce

1. Create a `Tabs` component
2. Create a `Tab` component and set the `eventKey` to a number
3. Create an `onSelect` callback function and try to do a numeric operation with the `eventKey` argument

### Reproducible Example

https://codesandbox.io/p/sandbox/reverent-chatterjee-3m7dyw?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cluvkb0190006356h7cb5pfzn%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cluvkb0180002356hm7bq8omc%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cluvkb0180003356hcnryqxu9%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cluvkb0180005356h0v5bic7u%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cluvkb0180002356hm7bq8omc%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cluvkb0180001356h0wcu504h%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522cluvkb0180002356hm7bq8omc%2522%252C%2522activeTabId%2522%253A%2522cluvkb0180001356h0wcu504h%2522%257D%252C%2522cluvkb0180005356h0v5bic7u%2522%253A%257B%2522id%2522%253A%2522cluvkb0180005356h0v5bic7u%2522%252C%2522activeTabId%2522%253A%2522cluvl0mmy001n356hxefyc9b1%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522id%2522%253A%2522cluvl0mmy001n356hxefyc9b1%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522cluvkb0180003356hcnryqxu9%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cluvkb0180003356hcnryqxu9%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### What version of React-Bootstrap are you using?

2.10.2

### What version of Bootstrap are you using?

5.3.3

**Comment by jquense** [comment]
The type is correct. Event types are stringified bc they are added to data attributes on the dom node. The event handler only has the strong version. If you want consistent types here I'd recommend using only strings
