### ISSUE TITLE
Too strict version of classnames in bower.json

### ISSUE THREAD

**Issue by kirill-konshin** [react-bootstrap/react-bootstrap#680]
```
"classnames": "1.1.4"
```

Classnames is now 2.x, so version has to be updated/made less strict.

**Comment by taion** [comment]
Oops. We also don't have classnames listed as a Bower dep at all for react-router-bootstrap, because it's bundled into the distributed file. I wasn't thinking of AMD users at the time.

**Comment by kirill-konshin** [comment]
We've got much biger issues with AMD now... unfortunately...

This particular one can be resolved by manually entering version `2.*` and adding the following to project's `bower.json`:

```json
{
  "resolutions": {
    "classnames": "2.*"
  }
}
```
