### ISSUE TITLE
Bug: Can't render Card without 'use client' directive, NextJS 14

### ISSUE THREAD

**Issue by artemsnite** [react-bootstrap/react-bootstrap#6804]
### Prerequisites

- [X] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [X] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [x] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug

When I remove 'use client' from start of the file, I get an error below:

Unhandled Runtime Error
Error: Could not find the module "C:\Users\xx\programming\next-ts-test\node_modules\react-bootstrap\esm\Card.js#default#Body" in the React Client Manifest. This is probably a bug in the React Server Components bundler.

### Expected behavior

I expect no errors to be occured.

### To Reproduce

1. Remove 'use client' directive from page.tsx
2. Get an error

### Reproducible Example

Can't use NextJS on CodeSandbox

### What version of React-Bootstrap are you using?

2.10.2

### What version of Bootstrap are you using?

5.3.3

**Comment by borzaka** [comment]
Import the [Card body](https://react-bootstrap.netlify.app/docs/components/cards#cardbody) like this: `import CardBody from 'react-bootstrap/CardBody'`

And use like this: `<CardBody></CardBody>`

You can't use components with dot in it's name on the server side. It's some kind of bug. You can search it up.
But many React Bootstrap components has an alternative name, like the `CardBody`.

**Comment by artemsnite** [comment]
Thank you for explaining! Haven't known about that🤔
