### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by fyy623** [react-bootstrap/react-bootstrap#6812]
### Prerequisites

- [X] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [X] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug

i'm using the exact code from https://react-bootstrap.netlify.app/docs/components/carousel/ but having problem importing `ExampleCarouselImage `, as the error says `Cannot find module 'components/ExampleCarouselImage' or its corresponding type declarations.ts(2307)
`. 

is this an actual package or just a dummy?

```
import Carousel from 'react-bootstrap/Carousel';
import ExampleCarouselImage from 'components/ExampleCarouselImage';

function UncontrolledExample() {
  return (
    <Carousel>
      <Carousel.Item>
        <ExampleCarouselImage text="First slide" />
        <Carousel.Caption>
          <h3>First slide label</h3>
          <p>Nulla vitae elit libero, a pharetra augue mollis interdum.</p>
        </Carousel.Caption>
      </Carousel.Item>
      <Carousel.Item>
        <ExampleCarouselImage text="Second slide" />
        <Carousel.Caption>
          <h3>Second slide label</h3>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
        </Carousel.Caption>
      </Carousel.Item>
      <Carousel.Item>
        <ExampleCarouselImage text="Third slide" />
        <Carousel.Caption>
          <h3>Third slide label</h3>
          <p>
            Praesent commodo cursus magna, vel scelerisque nisl consectetur.
          </p>
        </Carousel.Caption>
      </Carousel.Item>
    </Carousel>
  );
}

export default UncontrolledExample;
```

### Expected behavior

the sample code should run by itself

### To Reproduce

ExampleCarouselImage 

### Reproducible Example

https://codesandbox.io/p/sandbox/wizardly-kirch-5n3d5n

### What version of React-Bootstrap are you using?

2.10.2

### What version of Bootstrap are you using?

5.3.3

**Comment by kyletsang** [comment]
This is a sample component used in the carousel.

Here's the source code:
https://github.com/react-bootstrap/react-bootstrap/blob/master/www/src/components/ExampleCarouselImage.tsx
