### ISSUE TITLE
"npm install react-bootstrap" fails

### ISSUE THREAD

**Issue by sigmarsson** [react-bootstrap/react-bootstrap#6814]
### Prerequisites

- [X] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [X] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug

Installation failed :
`npm install react-bootstrap`
[2024-06-17T21_12_27_137Z-eresolve-report.txt](https://github.com/user-attachments/files/15887261/2024-06-17T21_12_27_137Z-eresolve-report.txt)

Having these packages : 

```
{
  "private": true,
  "dependencies": {
    "@fortawesome/fontawesome-svg-core": "^6.5.2",
    "@fortawesome/free-brands-svg-icons": "^6.5.2",
    "@fortawesome/free-regular-svg-icons": "^6.5.2",
    "@fortawesome/free-solid-svg-icons": "^6.5.2",
    "@fortawesome/react-fontawesome": "^0.2.0",
    "@radix-ui/colors": "^3.0.0",
    "@radix-ui/react-accordion": "^1.1.2",
    "@radix-ui/react-checkbox": "^1.0.4",
    "@radix-ui/react-collapsible": "^1.0.3",
    "@radix-ui/react-dialog": "^1.0.5",
    "@radix-ui/react-form": "^0.0.3",
    "@radix-ui/react-hover-card": "^1.0.7",
    "@radix-ui/react-icons": "^1.3.0",
    "@radix-ui/react-popover": "^1.0.7",
    "@radix-ui/react-separator": "^1.0.3",
    "@radix-ui/react-toast": "^1.1.5",
    "@radix-ui/react-toggle": "^1.0.3",
    "@react-email/components": "^0.0.17",
    "@react-email/render": "^0.0.13",
    "@testing-library/jest-dom": "^5.16.5",
    "@testing-library/react": "^13.4.0",
    "@testing-library/user-event": "^14.4.3",
    "@types/react": "^18.3.3",
    "@types/react-dom": "^18.3.0",
    "@typescript-eslint/eslint-plugin": "^7.12.0",
    "@vercel/analytics": "^1.2.2",
    "bootstrap": "^5.3.3",
    "classnames": "^2.5.1",
    "clsx": "^2.1.1",
    "next": "^14.2.3",
    "react": "^18.3.1",
    "react-bootstrap": "^2.10.2",
    "react-burger-menu": "^3.0.9",
    "react-dom": "^18.3.1",
    "react-email": "^2.1.2",
    "react-router-dom": "^6.22.3",
    "react-scripts": "^5.0.1",
    "react-transition-group": "^4.4.5",
    "resend": "^3.2.0",
    "typescript": "5.1.6",
    "web-vitals": "^3.0.4"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "@typescript-eslint/parser": "^7.12.0",
    "eslint-plugin-react": "^7.34.2",
    "globals": "^15.4.0",
    "tailwindcss": "^3.4.3",
    "typescript-eslint": "^7.12.0",
    "zod-form-data": "^2.0.2"
  }
}

```

### Reproducible Example

package.json is included 

### What version of React-Bootstrap are you using?

Trying to install the latest.

### What version of Bootstrap are you using?

Latest :  npm install react-bootstrap bootstrap

**Comment by ravikant-diwakar** [comment]
The issue seems to be a dependency conflict between react and react-bootstrap. The react-bootstrap package requires a specific version range of react that doesn't match the version installed in my project.

Solution
I was able to resolve this issue by using the --legacy-peer-deps flag with the npm install command. here is the command that worked for me......

npm install react-bootstrap --legacy-peer-deps

**Comment by kyletsang** [comment]
react-bootstrap should be compatible with react 16 and above.  Just tested on a fresh project and no issues.
