### ISSUE TITLE
"Component"  cannot be used as a JSX component. Its return type 'ReactNode' is not a valid JSX element.

### ISSUE THREAD

**Issue by akshay-mai** [react-bootstrap/react-bootstrap#6815]
### Prerequisites

- [X] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [X] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug

since morning i have getting this issue for all react-bootstrap component  in my react project when i was trying to create production build for my react app.i have not an change any version in my package.json file.
-----------------------------------------------------------------------------------------------------------------------
'Accordion.Item' cannot be used as a JSX component.
 Its return type 'ReactNode' is not a valid JSX element.
  return (

   <Accordion.Item eventKey={eventKey} className="accordion-item-main">
     ^^^^^^^^^^^^^^
      <Accordion.Header
       className="accordion-item-header">
      {title}

### Expected behavior

should not give typescript error.

### To Reproduce

replicate my environment
 
1. npx create-react-app test --template typescript
2. delete node_modules and pack-lock.json
3. change all  pack.json file and tsconfig.json file (mention below)
4. in App.js add <Container></Container> or any react-bootstrap component
5. npm run build

-----------------------------------------------------------------------------------------------------------------
package.json
------------------------------------------------------------------------------------------------------------------
{
  "name": "test",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@testing-library/jest-dom": "^5.17.0",
    "@testing-library/react": "^13.4.0",
    "@testing-library/user-event": "^13.5.0",
    "@types/jest": "^27.5.2",
    "@types/node": "^16.18.85",
    "@types/react": "^18.2.60",
    "@types/react-dom": "^18.2.19",
    "@types/react-star-ratings": "^2.3.3",
    "axios": "^1.6.7",
    "bootstrap": "^5.3.3",
    "formik": "^2.4.5",
    "moment": "^2.30.1",
    "react": "^18.2.0",
    "react-bootstrap": "^2.10.1",
    "react-datepicker": "^6.6.0",
    "react-dom": "^18.2.0",
    "react-router-dom": "^6.22.2",
    "react-scripts": "5.0.1",
    "react-star-ratings": "^2.3.0",
    "react18-input-otp": "^1.1.4",
    "sass": "^1.71.1",
    "typescript": "^4.9.5",
    "web-vitals": "^2.1.4",
    "yup": "^1.3.3"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject",
    "generate-env": "node generate-env.ts"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "@types/react-datepicker": "^6.2.0"
  }
}

----------------------------------------------------------------------------------------------------
tsconfig.js
----------------------------------------------------------------------------------------------------

{
  "compilerOptions": {
    "target": "es5",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noFallthroughCasesInSwitch": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx"
  },
  "include": [
    "src"
  ]
}

### Reproducible Example

none

### Screenshots

![image](https://github.com/react-bootstrap/react-bootstrap/assets/171779092/36149ec7-c87b-4ebd-b4dc-5593b9c2fc1c)

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of React-Bootstrap are you using?

2.10.1

### What version of Bootstrap are you using?

5.3.3

### Additional context

I have already try previios soutions lik downgrade types/react and types/react-dom version [https://github.com/react-bootstrap/react-bootstrap/issues/6717](url)

**Comment by narayn92** [comment]
Facing same issue for all react-bootstrap component imports

**Comment by akshay-mai** [comment]
I  guess @kyletsang  push some dependance  changes 20hr ago after that we are facing this issue .  🥹

**Comment by narayn92** [comment]
> I guess @kyletsang push some dependance changes 20hr ago after that we are facing this issue . 🥹

Yes the older versions are working

**Comment by akshay-mai** [comment]
> > I guess @kyletsang push some dependance changes 20hr ago after that we are facing this issue . 🥹
> 
> Yes the older versions are working

which one please share version of these library i will try on my local 
react-bootstrap
bootstrap
types/react
types/react-dom

**Comment by narayn92** [comment]
> > > I guess @kyletsang push some dependance changes 20hr ago after that we are facing this issue . 🥹
> > 
> > 
> > Yes the older versions are working
> 
> @narayn92 which one please share version of these library i will try on my local react-bootstrap bootstrap types/react types/react-dom

You have mentioned react-bootstrap": "^2.10.1", which will install 2.10.3 which is latest. Better stick to the prior version react-bootstrap": "2.10.1"

**Comment by akshay-mai** [comment]
> > > > I guess @kyletsang push some dependance changes 20hr ago after that we are facing this issue . 🥹
> > > 
> > > 
> > > Yes the older versions are working
> > 
> > 
> > @narayn92 which one please share version of these library i will try on my local react-bootstrap bootstrap types/react types/react-dom
> 
> You have mentioned react-bootstrap": "^2.10.1", which will install 2.10.3 which is latest. Better stick to the prior version react-bootstrap": "2.10.1"

it's wokring thanks @narayn92

**Comment by denysonique** [comment]
reopening, as the issue is still present in the latest version.
