### ISSUE TITLE
TS2786: '<Any Bootstrap Component>' cannot be used as a JSX component.

### ISSUE THREAD

**Issue by jonathan-meyer** [react-bootstrap/react-bootstrap#6819]
### Prerequisites

- [X] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [X] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug

v2.10.3 of react-boostrap does not work with Typescript. Every react-bootstrap component throws a `TS2796` error when compiled. 

### Expected behavior

it should compile with out errors. 

### To Reproduce

1. create a project with `npx create-react-app my-app --template typescript`
2. add react-bootstrap `npm add bootstrap react-bootstrap`
3. use a react-bootstrap component.
```
import { Alert, Container } from "react-bootstrap";
import "./App.css";

function App() {
  return (
    <Container>
      <Alert>Hello World</Alert>
    </Container>
  );
}

export default App;
```
4. run `npm run start`

![image](https://github.com/react-bootstrap/react-bootstrap/assets/20321382/7e39a1ae-11f4-40e2-9b58-2504af6a8bd3)
 

### Reproducible Example

[Codesandbox Example](https://codesandbox.io/p/sandbox/react-bootstrap-error-zf74n7?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clxrih93o00063b6qsrhnxyss%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clxrih93n00023b6qtoby2jxd%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clxrih93n00033b6qwxyqnatq%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clxrih93o00053b6qqjo2e4m4%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B60.444963137907045%252C39.555036862092955%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clxrih93n00023b6qtoby2jxd%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxrih93n00013b6q2daq3b7j%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.tsx%2522%257D%255D%252C%2522id%2522%253A%2522clxrih93n00023b6qtoby2jxd%2522%252C%2522activeTabId%2522%253A%2522clxrih93n00013b6q2daq3b7j%2522%257D%252C%2522clxrih93o00053b6qqjo2e4m4%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxrih93o00043b6qn07ab1a2%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clxrih93o00053b6qqjo2e4m4%2522%252C%2522activeTabId%2522%253A%2522clxrih93o00043b6qn07ab1a2%2522%257D%252C%2522clxrih93n00033b6qwxyqnatq%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clxrih93n00033b6qwxyqnatq%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A23.27285921625544%257D)

### Screenshots

v2.10.3 is broken.
![image](https://github.com/react-bootstrap/react-bootstrap/assets/20321382/1cbec71c-ee70-485d-9923-aaceaaa2a2dc)
v2.10.2 works fine!
![image](https://github.com/react-bootstrap/react-bootstrap/assets/20321382/fd15e91b-01e5-41ab-98e0-de1cc9ec6fe4)

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome

### What version of React-Bootstrap are you using?

2.10.3

### What version of Bootstrap are you using?

5.3.3

**Comment by bherila** [comment]
Agree. 2.10.2 works fine. 2.10.3 does not.

**Comment by imamasurya** [comment]
i think it comes from this commit [src/helpers.ts](https://github.com/react-bootstrap/react-bootstrap/commit/78c22ee8014a9090aedfb4e5093cfe3c7f1db9d6#diff-ca5696b367d474e785317cb7a0d9853fef5729387ab8d0fab4c46268c03aae99)

**Comment by pooja-sahani-simform** [comment]
I'm facing this issues with even version 2.10.2 as well. 

`ERROR in src/pages/Home/Upsells/Cart/UpsellCartButton.tsx:30:18
TS2786: 'Button' cannot be used as a JSX component.
  Its return type 'ReactNode' is not a valid JSX element.
    28 |             <div className='upsell-cart-button'>
    29 |                 <span className='count'>0</span>
  > 30 |                 <Button className='cart-button' onClick={this.onCartClick}>
       |                  ^^^^^^
    31 |                     <i className='fa-solid fa-cart-shopping'></i>
    32 |                 </Button>
    33 |             </div>
`

**Comment by nino-joy** [comment]
Facing the same issue here.

```
TS2786: 'Form.Group' cannot be used as a JSX component.
  Its return type 'ReactNode' is not a valid JSX element.
    Type 'undefined' is not assignable to type 'Element | null'.
    72 |       </div>
    73 |       <form onSubmit={handleSubmit(onSubmit)} className='pt-2'>
  > 74 |         <Form.Group controlId='email' className='auth__input-group'>
       |          ^^^^^^^^^^
```

**Comment by mpvazquez** [comment]
Also faced the same issue / errors shown above. We could reproduce in version 2.10.3, but could not in 2.10.2, so we locked the version and resolved our build issues.

**Comment by bherila** [comment]
Thank you so much @kyletsang  for the fix 🤩🤩🤩
