### ISSUE TITLE
Feature: Add possibility for multiple buttons in Modal.Header

### ISSUE THREAD

**Issue by AHorak** [react-bootstrap/react-bootstrap#6824]
### Is your feature request related to a problem? Please describe

I would like to add onother button to switch fullscreen of dialogs 

### Describe the solution you'd like

Solution1:
Maximize Option like "closeButton" use "maximizeButton" in ModalHeader
Solution 2:
Possibility to add multiple right aligned buttons to ModalHeader

**Comment by kyletsang** [comment]
You can customize the header by passing additional children to it.  For example:

```
        <Modal.Header>
          <Modal.Title>Modal heading</Modal.Title>
          <div className="d-flex gap-2">
            <Button>1</Button>
            <Button>2</Button>
          </div>
        </Modal.Header>
```
