### ISSUE TITLE
 Can't resolve '@restart/ui/Anchor'

### ISSUE THREAD

**Issue by PatrickSandovalS** [react-bootstrap/react-bootstrap#6835]
### Prerequisites

- [X] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [X] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug

When I try to execute the build of my react application with create-react-app I get the following error: 
Failed to compile.

Module not found: Error: Can't resolve '@restart/ui/Anchor' in '/home/user/dev/project_name/node_modules/react-bootstrap/esm'.

my dependencies are:

      "react-bootstrap": '2.10.4'.
      "bootstrap": "5.2.0"
      "@types/bootstrap": "5.2.3"

### Reproducible Example

is private project

### Screenshots

![Untitled design](https://github.com/user-attachments/assets/6b3aa3b3-bd02-4f70-88d4-658a7fa4ebf9)
![image](https://github.com/user-attachments/assets/092434b5-3cfa-4be8-98c6-468d45586da4)
![image](https://github.com/user-attachments/assets/8a70fb20-5a27-4ab4-995e-c76aa81eaf43)

### What version of React-Bootstrap are you using?

2.10.4

### What version of Bootstrap are you using?

5.2.0

**Comment by waqas-ep** [comment]
I'm facing the same issue. I can't proceed

**Comment by lzfelipe** [comment]
i'm also encountering the same error.

**Comment by kyletsang** [comment]
Issue caused by underlying dependency.  Can you remove package lock/node_modules folder and reinstall?

**Comment by smumair-ephlux** [comment]
The restart/ui have just pushed an update a couple of hours back in which they have moved the components from restart/ui to restart/ui/lib. Due to this boostrap is unable to find the modules.

Until bootstrap provides an update, you can install an older version of restart/ui by executing following command
npm i @restart/ui@1.6.9

**Comment by kyletsang** [comment]
I've released a new version of `@restart/ui` that fixes this, so just follow the below steps if you're having issues.

> Issue caused by underlying dependency. Can you remove package lock/node_modules folder and reinstall?

**Comment by PatrickSandovalS** [comment]
Thank you, it works!
