### ISSUE TITLE
OverlayTrigger with rootClose and click trigger requires 2 clicks outside of overlay if scrollable content was previously focused

### ISSUE THREAD

**Issue by deldreth** [react-bootstrap/react-bootstrap#6836]
### Prerequisites

- [X] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [X] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug

If the overlay within a click triggered OverlayTrigger contains a scrollable content and the scroll bar has been clicked the overlay requires 2 root clicks to dismiss. 

### Expected behavior

The overlay should dismiss on 1 click if rootClose is true regardless of interaction with content of the overlay.

### To Reproduce

1. Within the reproducible example click the OverlayTrigger button
2. Within the overlay click the scrollbar
3. Click outside of the overlay (not the trigger)

### Reproducible Example

https://codesandbox.io/p/sandbox/nostalgic-minsky-s38w7n

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of React-Bootstrap are you using?

2.10.4

### What version of Bootstrap are you using?

5.3

**Comment by edlerd** [comment]
Opened a PR to the upstream library. Once upstream merges this and emits a new version, a local update of react-restart/ui should fix this bug.

**Comment by edlerd** [comment]
Turns out we don't need an upstream change, but can use a different close trigger of mouse up to fix this. See linked PR #6862
