### ISSUE TITLE
See all search results Bug

### ISSUE THREAD

**Issue by MatthewElson** [react-bootstrap/react-bootstrap#6838]
### Prerequisites

- [X] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [X] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug

The "see all" search doesn't work.
I searched 'example' using the search at the top right of the website. What I was looking for wasn't there.  I clicked the link [See all 89 results](https://react-bootstrap.netlify.app/search?q=example). That page said "No results were found" and it seems no matter the text no results are returned.

### Expected behavior

I should see all the 89 results and if I change the search text I should see those results.

### To Reproduce

1. Search 'example' using the search at the top right of the website. 
2. Clicked the link [See all 89 results](https://react-bootstrap.netlify.app/search?q=example). 
3. Search any text in the 'Search the documentation' search box.

### Reproducible Example

Not a coding thing, see search results at https://react-bootstrap.netlify.app/search?q=example

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome, Firefox

### What version of React-Bootstrap are you using?

v2.10.4 (Bootstrap 5)

### What version of Bootstrap are you using?

5

**Comment by kalyan90** [comment]
Hi, I would like to contribute to this issue.
