### ISSUE TITLE
gapping in button is incorrect

### ISSUE THREAD

**Issue by youngs01** [react-bootstrap/react-bootstrap#6840]
### Is your feature request related to a problem? Please describe

Its is an small but a catchy problem in the dropdown section in components .which as a frontend developer is  making me annoying as you can see in the screenshot . There is no gap between the dropdown button.
![Screenshot 2024-08-30 231647](https://github.com/user-attachments/assets/5cb4c957-414a-4bf0-8947-8917f833d5a6)

### Describe the solution you'd like

![Screenshot 2024-08-30 232052](https://github.com/user-attachments/assets/c6c8dca7-17b1-434f-8fae-1e538c57a980)

**Comment by youngs01** [comment]
pardon me to write such a small content as its a small problem . And can i correct the issue .

**Comment by Gopakuma** [comment]
Hello,
Are you working on this issue? @youngs01

**Comment by tejodeepmitraroy** [comment]
I want to work on this issue?

**Comment by alfaarghya** [comment]
I tried to fix this gaping issue. Here is the PR #6847

**Comment by youngs01** [comment]
> Hello, Are you working on this issue? @youngs01

Nah ,
sorry for late reply
