### ISSUE TITLE
Can't install with React 19

### ISSUE THREAD

**Issue by mzerres** [react-bootstrap/react-bootstrap#6850]
### Prerequisites

- [X] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [X] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug

`npm i react-bootstrap bootstrap`

This error is thrown:

```
npm error code ERESOLVE
npm error ERESOLVE unable to resolve dependency tree
npm error
npm error While resolving: learn-react@0.1.0
npm error Found: react@19.0.0-rc-02c0e824-20241028
npm error node_modules/react
npm error   react@"19.0.0-rc-02c0e824-20241028" from the root project
npm error
npm error Could not resolve dependency:
npm error peer react@">=16.14.0" from react-bootstrap@2.10.5
npm error node_modules/react-bootstrap
npm error   react-bootstrap@"*" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
```

### Reproducible Example

https://codesandbox.io/p/sandbox/focused-kate-vtyxnz

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome

### What version of React-Bootstrap are you using?

2.10.5

### What version of Bootstrap are you using?

5.3

### Additional context

React.js: Version 19
Next.js: Version 15

**Comment by masoncfrancis** [comment]
Curious to hear what the progress is on this? I've just been using `npm i --legacy-peer-deps` while I've been waiting for this to get implemented.

**Comment by kyletsang** [comment]
This should work without `--legacy-peer-deps` as long as you use react 19 stable.  The peer deps range covers it.

There's another bug related to typescript when using `skipLibCheck=false`, but I'll look at that when I get time
