### ISSUE TITLE
Documentation - Toast

### ISSUE THREAD

**Issue by christopherreay** [react-bootstrap/react-bootstrap#6881]
### Prerequisites

- [X] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [X] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug

https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue+is%3Aopen+toast

event documentation for Exit events cannot be right.
All of them say when "animated not false"

 probably onExit is meant to apply to "animated is false".
 
 Is there an event that is supposed to fire regardless of the value of animated? 

### Expected behavior

n/a

### To Reproduce

https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue+is%3Aopen+toast

### Reproducible Example

n/a

### Screenshots

n/a

### What operating system(s) are you seeing the problem on?

Linux

### What browser(s) are you seeing the problem on?

Chrome

### What version of React-Bootstrap are you using?

n/a

### What version of Bootstrap are you using?

5.3? I think? 

### Additional context

thank you!

**Comment by kyletsang** [comment]
Transition callbacks are only fired when there `animation=true` like you observed.  By setting `show=false`, you can use that as your indicator of when the toast has "exited"
