### ISSUE TITLE
SURVEY: Should we still support IE8? (WE NEED FEEDBACK)

### ISSUE THREAD

**Issue by AlexKVal** [react-bootstrap/react-bootstrap#692]
Honestly I propose to abandon IE8 support.

The library becomes more and more complicated and it is already using ES6 (and JSX+ES7) code,
that is hard to make work in IE8.

More and more other projects drop IE8 maintenance burden because - honestly at 2015 - there is no value in it.

However if there is enough interest to support and maintain code for IE8,
here are my notes:

[npm run ie8](https://github.com/react-bootstrap/react-bootstrap/blob/7ab2faa3e64799ccdf91577b5e0cf451c1696e0a/package.json#L19) command doesn't work because of
`Error: Cannot find module 'webpack-dev-middleware'`

Some files like [ie8/package.json](https://github.com/react-bootstrap/react-bootstrap/blob/804c24a33f390166a89276f68772fa64b1510ba8/ie8/package.json)
are not used at all. (at least since `grunt => npm scripts`)

For those who are interested here is [The Inception](https://github.com/react-bootstrap/react-bootstrap/pull/121) (it's not the famous movie :smile: )

Additional benefit - if we drop IE8 support - we can easier remove jQuery dependency.

**Comment by krzysiek1507** [comment]
+1 for drop IE8 support ;)

**Comment by mtscout6** [comment]
:+1: I too am in favor of this as my company has not supported IE8 for over a year, without much grumbling from our customers. Many of which are corporate entities.

With that said though seeing as we are marrying both React and Bootstrap, and both support IE8:

- https://facebook.github.io/react/docs/working-with-the-browser.html#browser-support-and-polyfills
- http://getbootstrap.com/getting-started/#support-ie8-ie9

The real question would come down to who's using this and who cares that it's still supported?

**Comment by mtscout6** [comment]
CC'ing All past contributors for more feedback on this.

/cc @stevoland
@pieterv
@taion
@trentgrover-wf
@dozoisch
@apkiernan
@stereosteve
@teloo
@aabenoja
@aforty
@brainary
@smbecker
@jquense
@kellec
@mfunkie
@cymen
@RichardLitt
@defrex
@zeroedin-bill
@tacomanator
@glenjamin
@liamcmitchell
@chollier
@KnisterPeter
@martijnvermaat
@mattly
@computmaxer
@tracker1
@ronjouch
@sahat
@stefanfisk
@stevie-mayhew
@thetimbanks
@kroepke
@amarant
@bobpace
@cassus
@cvrebert
@cdock1029
@limscoder
@davidbgk
@dkastner
@EricWarnke
@cell303
@lipsmack
@yeojz
@hcarvalhoalves
@thehuey
@justjake
@jamesakers
@time4tea
@JamesTrigg
@jeroencoumans
@jingchan
@joemcbride
@jonasoberschweiber
@odetown
@lucasfrey
@lo1tuma
@mathieumg
@gldnspud
@heydiplo
@raine
@randylien
@rtsao
@scottwoodall
@gitter-badger
@traviscooper
@vinnymac
@YannPl
@alasdaircs
@lilaja
@mgechev
@mtetlow
@DJCordhose
@skv-headless
@staeff

**Comment by stefanfisk** [comment]
for the last year or so, after showing customer their own visitors stats, none have wanted to pay for the extra work required for IE8 support, so I'd say drop it if there's any reason whatsoever.

**Comment by aforty** [comment]
I just spent a few minutes writing a few reasons for keeping it but... +1 for dropping support.

**Comment by mathieumg** [comment]
> we are marrying both React and Bootstrap, and both support IE8

I came here to point that out, glad you already did! I personally am not adamant about keeping it. However, if we were to, do we have an outline of the implications other than the lost benefits mentioned in @AlexKVal 's post?

**Comment by glenjamin** [comment]
It's not in my support grid at work, so not something I'm bothered about.

**Comment by mattly** [comment]
I hope to never use bootstrap again. Please do not ping me for future issues.

**Comment by tacomanator** [comment]
+1 for dropping, with the following rationale:

1. Apparently [it will be dropped in Bootstrap 4](http://www.infoq.com/news/2014/11/bootstrap-4-drops-ie8) anyway.
2. I guess that a vast majority of projects using react-bootstrap are not built with IE8 in mind.
3. If desired someone could maintain it as a fork, which need not keep support up-to-date with each and every release of react-bootstrap core (could be batched).

**Comment by martijnvermaat** [comment]
+1 for dropping

**Comment by jquense** [comment]
While I don't personally or professionally need ie8 support I think that as long as either React or Bootstrap support it then react-bootstrap should as well. My experience supporting ie8 in react component libraries ([react-widgets](https://github.com/jquense/react-widgets)) is that React makes supporting ie8 fairly simple, and has only added a _bit_ of code overall. The main areas being cases where you need to circumvent the react event system, and style/position issues.

I would think that unless there is a reasonable incentive not too (lots of extra bytes, not feasible, time cost, etc) we should keep ie8 support, even if it is only in a "we don't test super strongly but will fix reported bugs in ie8" capacity. That being said IE8 testing is a huge pain and if maintaining it is gonna be a burden on the maintainers, I'd much prefer that time be spent elsewhere :)

**Comment by mfunkie** [comment]
I'm okay with dropping IE8 as we don't even support IE9 in our internal CRM where we use React Bootstrap.

There is something to be said for IE8 support being in parity with React itself though.

**Comment by luisrudge** [comment]
:+1: for dropping support.

**Comment by thetimbanks** [comment]
+1 for dropping IE8 support due to support being dropped in BS4 and
Microsoft dropping support.

**Comment by taion** [comment]
My thoughts match @jquense. I have no need to support IE8 for any reason, but as long as both upstreams support it and it's a relatively small amount of work, then I think it makes sense to retain some (potentially somewhat degraded) support, to the extent that it doesn't get in the way too badly.

**Comment by stereosteve** [comment]
I did some of the initial work adding IE8 support, but we ended up not using react-bootstrap at work, so :+1: for dropping.

**Comment by sahat** [comment]
I would just drop it and not bother with IE8.

**Comment by thehuey** [comment]
[image: Inline image 1]

**Comment by dbackeus** [comment]
+1 to drop

**Comment by stevie-mayhew** [comment]
I think that we have to support it while the upstream supports it. In saying that, this may just be the case of only *fixing* issues which are reported rather than actively maintaining and testing for IE8.

Once one of the upstreams no longer support IE8 or Microsoft drops IE8 support then I am all for it. In saying that, we do not support IE8 by default either.

**Comment by RichardLitt** [comment]
Drop it.

On Tue, May 19, 2015 at 2:15 AM, Stevie Mayhew <notifications@github.com>
wrote:

> I think that we have to support it while the upstream supports it. In
> saying that, this may just be the case of only *fixing* issues which are
> reported rather than actively maintaining and testing for IE8.
>
> Once one of the upstreams no longer support IE8 or Microsoft drops IE8
> support then I am all for it. In saying that, we do not support IE8 by
> default either.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/react-bootstrap/react-bootstrap/issues/692#issuecomment-103179738>
> .
>



-- 
Richard | @richlitt <https://twitter.com/richlitt> | burntfen.com
<http://www.burntfen.com>

**Comment by KnisterPeter** [comment]
+1 for dropping from me too

**Comment by teloo** [comment]
+1 for dropping support.

**Comment by kroepke** [comment]
Our product never actually worked on IE8, so we are more than fine with dropping it :+1:

**Comment by zeroedin-bill** [comment]
I have a few very large institutional clients on one of our main apps that are still in the process of phasing out IE8, so I do still need to support it.

**Comment by tracker1** [comment]
+1 to drop ... it's time for it to die (about 0.5% of our users).

**Comment by tacomanator** [comment]
Another point I just thought about. As I understand it dropping IE8 support will only affect a small number of features provided by Bootstrap. Furthermore, even if those features are technically "broken" it doesn't necessarily mean the resulting site is completely unusable. I think it's important to make this distinction for some people that may be on the fence.

**Comment by yeojz** [comment]
+1 for dropping it, mainly due to the fact that Bootstrap 4 is moving in that direction.

Maybe affected components can be moved out of the "core" library into a separate "support" library if IE8 support is still needed. But this will probably be too time consuming.

Personally though, haven't really had IE8 requirements recently.

**Comment by pedroteixeira** [comment]
Currently, most projects have to support only >=IE9.
is there any jQuery dependency? wasn't aware.. (it's not in package.json for instance)

Nevetherless, what feature you think would break in IE8 that cannot be solved with shims/polyfills? I think breaking direct/source-code support is fine, but it would be nice to point others in the docs which features (hence polyfills) are assumed/required from browser.

**Comment by thealjey** [comment]
+1 to drop support for the dreaded IE8

**Comment by mtscout6** [comment]
I wanted to thank all of you for your feedback it has been most appreciated.

I’m leaning towards the suggestions by a few of you to only support IE8 so far as folks submit PRs to fix it. However, it should be warned that Bootstrap is planning to drop support for IE8 when they drop v4 on us as stated in http://blog.getbootstrap.com/2014/10/29/bootstrap-3-3-0-released/#onward-to-bootstrap-4. I’m thinking that inline with what the Bootstrap team is doing we will likely plan to still provide some limited support for Bootstrap 3.x once 4.0 is out and while we adjust to whatever breaking changes they throw at us.

With that said though I think any IE8 debugging can happen within the confines of our existing docs infrastructure, so I'd propose that we remove the `ie8/` folder from our repo.

Also going forward if we notice any code that is IE8 specific we should mark it with a comment like `// Only for IE8` that we we can easily know what can be removed when we start the Bootstrap v4 migration.
