### ISSUE TITLE
Expand Panel when child is invalid

### ISSUE THREAD

**Issue by jmwyrwas** [react-bootstrap/react-bootstrap#694]
I'm trying to expand a panel if a child component has an error when the form is submitted. Is there a recommended approach to do this? Issue #190 mentions `expanded` but doesn't go into much detail.

If I set the expanded property from a function, e.g. `<Panel collapsable expanded={this.handleExpand()} />`, the click event doesn't work because expanded is only getting its state from the function. Is there a way to add both sets of functionality?

My other approach was `panel.handleToggle()`, however, if the panel is already open, then it erroneously closes.

**Comment by mtscout6** [comment]
So long as your `handleExpand` function is pulling from either `this.state` or `this.props` then you should be fine. This is a React idiom that dictates when your components render call is invoked. If I'm not answering your question enough then can you supply more code in your example.

**Comment by dozoisch** [comment]
You could always provide an  `onSelect` and have it set an expended state on your component.

The function handleExpand can then check both the current state (from the on select) and the current state its getting from the function.

**Comment by mtscout6** [comment]
@jmwyrwas I'm going to close this, if you continue to run into problems re-open as necessary.
