### ISSUE TITLE
Make `webpack.config` for `npm run build` based on the bower dependencies.

### ISSUE THREAD

**Issue by AlexKVal** [react-bootstrap/react-bootstrap#707]
- [ ] build webpack config file for `npm run build` based on the bower dependencies. Since we are missing classnames at the moment.
- [x] Add to `getting started` explanation about `classnames` dependency for those using no dependency manager

[inception](https://github.com/react-bootstrap/react-bootstrap/pull/691#discussion_r30512146)

**Comment by AlexKVal** [comment]
@mtscout6 Have I formulated it right ?

**Comment by mtscout6** [comment]
Sounds about right to me.

**Comment by taion** [comment]
The latter point above goes away if we go forward with #693.

**Comment by AlexKVal** [comment]
I'm closing it because now bower config is in sync with package.json
and #693 has been accepted.
