### ISSUE TITLE
Document supported props for components

### ISSUE THREAD

**Issue by apkiernan** [react-bootstrap/react-bootstrap#716]
The supported props for each component and their `propTypes` need to be documented.

**Comment by AlexKVal** [comment]
https://github.com/react-bootstrap/react-bootstrap/pull/887 gave it a good foundation.
Huge thanks @jquense for shifting from zero point all this. :cherries: 

And of course to all
Pull requests are welcome :wink:

**Comment by taion** [comment]
I think this is actually resolved by #887.
