### ISSUE TITLE
Modals can't be used with server side rendering

### ISSUE THREAD

**Issue by maxmalov** [react-bootstrap/react-bootstrap#717]
Modal#render method uses `document` reference at [L46](https://github.com/react-bootstrap/react-bootstrap/blob/master/src/Modal.js#L46) and [L78](https://github.com/react-bootstrap/react-bootstrap/blob/master/src/Modal.js#L78), so `React.renderToString` stucks and throws an error.

I see that this `in` class is used by `FadeInMixin` as well as `document.querySelectorAll`? Is it possible to move `document` reference somewhere else out of `render` method?

**Comment by mtscout6** [comment]
Ick, that is less than ideal. We'd love a PR to fix that up.

**Comment by aabenoja** [comment]
Fixed by #719
