### ISSUE TITLE
Investigate means to run tests that can run in both server and client side scenarios

### ISSUE THREAD

**Issue by mtscout6** [react-bootstrap/react-bootstrap#720]
#719 Proposes an interesting idea of testing components in both the browser and in Node. I like the idea, though I wonder if there is a way we can do this by leveraging many of the tests that are already written.

I envision this being possible my excluding some tests from the Node only run by use of a `process.env.BROWSER` flag which Webpack can set to true when running with Karma.

**Comment by maxmalov** [comment]
One more interesting issue is to test that component rendering in the browser will pick up string markup from the server without warnings, in other words the resulting markup should be the same on the server and in the browser.

**Comment by mtscout6** [comment]
Interesting, I had not considered any kind of testing for that. Do you have any proposals on how to achieve this? Preferably keeping inline with the aforementioned goal of leveraging as many of the existing tests as possible.

**Comment by maxmalov** [comment]
Unfortunately I don't have any experience in that kind of testing, so below are only my thoughts on how to achieve this.

I was thinking that this is only kind of tests needed for Node. You cannot achieve that component will be fully compatible with it, and as far as I know only rendering can be achieved on the server (including component instantiation). So only [mounting phase](https://pbs.twimg.com/media/B-G3_T8CcAAmTHV.jpg:large) could be covered for Node environment.

A tiny little dev server can be created to return component rendered string and setup `karma` to proxy it. It should reduce amount of Node test usecases, ideally Node tests should assert only possibility to render component without errors, the rest part will be checked in the browser.

For browser tests render helper (like `renderIntoDocument`) could be created:

```js
function renderIntoElement(instance, elementMarkup) {
  if (!elementMarkup) {
    return ReactTestUtils.renderIntoDocument(instance);
  }

  const componentNode = createDetached(elementMarkup); // creates detached dom node by string markup
  const mountNode = document.createElement('div');
  mountNode.appendChild(componentNode);
  return React.render(instance, mountNode);
}
```
This should allow to reuse as many of the existing tests as possible:

```js
it('should do smth with component', () => {
  const element = (
    <Foo className='cool-class'>
      <Bar />
    </Foo>
  );
  const markup = renderOnTheServer(element);
  renderIntoElement(element, markup);

  // do usual testing asserts
});
```

Still there is an open question how to render any component on the server in this schema.

**Comment by mtscout6** [comment]
That's pretty close to the idea that I was thinking about. We can write a very small express server that could serve this data, which we would need to launch in a separate process from karma.

The call to `renderOnServer` function would need to return an ES6 Promise since it would be async. Since we would have to make the network request there's no way around it being async.

Also the element would need to be a string that gets `eval`'d since we can't serialize functions to send to the server. We can serialize a string though and then `eval` it similar to how we do so with the `ReactPlayground` component in the docs today.

One additional issue is that I'd advocate that this:

```
const markup = renderOnTheServer(element);
renderIntoElement(element, markup);
```

Became this:

```
const markup = renderOnTheServer(element);
```

where the `renderOnTheServer` call also did the validation that `renderIntoElement` is proposing. This would DRY up a fairly repeated process in many tests.

**Comment by maxmalov** [comment]
> The call to renderOnServer function would need to return an ES6 Promise since it would be async. Since we would have to make the network request there's no way around it being async.

Sure it should be async. What about es6 generators?

**Comment by mtscout6** [comment]
They are supported by Babel by default so :+1:, though I don't know if Mocha supports this.

**Comment by maxmalov** [comment]
https://www.npmjs.com/package/co-mocha seems reasonable and pretty simple

**Comment by AlexKVal** [comment]
I propose to close this issue.

It seems it is not so simple to implement. There are a lot of `big fish to fry` besides that issue.

And I believe that probability of someone will concider it is worth to implement 
at this stage of project tends to zero.
Kind of `wontfix`.

Feel free to reopen with additional arguments :stuck_out_tongue_winking_eye:
