### ISSUE TITLE
Tooltips and Popovers not appearing when left/right aligned

### ISSUE THREAD

**Issue by Danita** [react-bootstrap/react-bootstrap#724]
In the documentation, at http://react-bootstrap.github.io/components.html#tooltips you can hover over the first and last Tooltip examples and they do not appear. Same thing clicking on the first and last examples for the Popover component.

**Comment by taion** [comment]
Works for me. What browser are you on?

**Comment by Danita** [comment]
Firefox 38.0.1 on Windows 7x64. Now that you mention it, it works perfectly in Chrome. Cannot test on IE because I uninstalled it.

**Comment by Danita** [comment]
Plain vanilla Bootstrap tooltips and popovers work OK on both browsers for me.

**Comment by taion** [comment]
Got it, does indeed look like I messed something up for FF. Will take a look in a bit.

**Comment by Danita** [comment]
You rock :smile:
