### ISSUE TITLE
CollapsibleNav module exports multiple variables causing React TypeError

### ISSUE THREAD

**Issue by jchapple** [react-bootstrap/react-bootstrap#731]
Hello. Thank you for this very cool and useful library! I have a question if you wouldn't mind.

The change introduced in the following commit: https://github.com/react-bootstrap/react-bootstrap/commit/2b8dc5fb3ea46de84a7f56c91831c85cd9232aa2#diff-c5a88cb9e192df4b2a4e2ed9a0a18884R123 seems to break the `CollapsibleNav` component as I am using it.

I have the following code:
```javascript
var Nav = require( 'react-bootstrap/lib/Nav' );
var NavItem = require( 'react-bootstrap/lib/NavItem' );
var Navbar = require( 'react-bootstrap/lib/Navbar' );
var DropdownButton = require( 'react-bootstrap/lib/DropdownButton' );
var MenuItem = require( 'react-bootstrap/lib/MenuItem' );
var CollapsibleNav = require( 'react-bootstrap/lib/CollapsibleNav' );

var RootNav = React.createClass( {
	render: function() {
		return (
			<Navbar brand={<a href="/">Jiggle.io</a>} inverse staticTop toggleNavKey={0}>
			  <CollapsibleNav eventKey={0}>
			     <Nav navbar>
			        <NavItem eventKey={1} href='#'>Link</NavItem>
			        <NavItem eventKey={2} href='#'>Link <span className="navbar-new">2</span></NavItem>
			     </Nav>
			     <Nav navbar right>
			        <NavItem eventKey={1} href='#'>Link Right</NavItem>
			        <NavItem eventKey={2} href='#'>Link Right</NavItem>
			        <DropdownButton eventKey={3} title='Dropdown'>
			          <MenuItem eventKey='1'>Action</MenuItem>
			          <MenuItem eventKey='2'>Another action</MenuItem>
			          <MenuItem eventKey='3'>Something else here</MenuItem>
			          <MenuItem divider />
			          <MenuItem eventKey='4'>Separated link</MenuItem>
			        </DropdownButton>
			     </Nav>
			  </CollapsibleNav>
			</Navbar>
		);
	}
} );

module.exports = RootNav;
```

When mounted by React, this results in the error `TypeError: type.toUpperCase is not a function`. I believe that this is because React is trying to determine the type of component `CollapsibleNav`, but cannot resolve this as the module exports two variables, resulting in an object like this

![react-debug](https://cloud.githubusercontent.com/assets/5153746/7812658/4f9d728c-03ac-11e5-84ad-773df76e963b.png)

Forgive me if I have misunderstood something, as I am fairly new to Node, however, I am wondering why the export statements for `CollapsibleNav` differ in this way, as it is not how other components have been handled. I can see the benefit of exporting the component 'spec' along with the React component as this allows for extendibility, however, it requires me to change my `require` statement to something like the following for out-of-the-box use:

```javascript
var CollapsibleNav = require( 'react-bootstrap/lib/CollapsibleNav' ).default;
```

I am using Browserify, and wondering if perhaps it handles multiple module exports in an unconventional manner?

Any help would be greatly appreciated!

**Comment by AlexKVal** [comment]
> why the export statements for CollapsibleNav differ in this way

It was `Collaps_a_bleNav` component => and now it is `Collaps_i_bleNav` https://github.com/react-bootstrap/react-bootstrap/issues/425 
It is because `Collaps_a_bleNav` has been deprecated and it was achieved through exporting `spec`.

`Browserify` is not the cause of it. The `Webpack` also does it.
I believe the issue lays somewhere near `babel` ES6 `import` + `classes` + `React`.
It needs more time to investigate. I'll try to figure out a solution.

**Comment by AlexKVal** [comment]
Just for ref:
```js
var CollapsibleNav = require( 'react-bootstrap' ).CollapsibleNav;
```
also works fine.

I'm investigating further.

**Comment by mtscout6** [comment]
@AlexKVal I think that the fix would be to change it to:

```
const CollapsibleNav = React.createClass(specCollapsibleNav);
 
CollapsibleNav.specCollapsibleNav;
export default CollapsibleNav;
```

**Comment by AlexKVal** [comment]
It is simplest and fast hack :+1: 
I'll make it like this and check. Then push PR.

**Comment by taion** [comment]
One subtlety of the `import {name} from '<module>'` syntax is that it can only import things that are actually `export`ed, rather than properties of the default export. But Babel only sets `module.exports` if you only have a single `export default`. I think this is the only thing you can do that works, short of putting `specCollapsibleNav` in a separate module.

**Comment by AlexKVal** [comment]
I believe Matt means this:
```js
// collaps_i_ble
const CollapsibleNav = React.createClass(specCollapsibleNav);

CollapsibleNav._spec = specCollapsibleNav;
export default CollapsibleNav;
```
```js
// collaps_a_ble
import CollapsibleNav from './CollapsibleNav';

const specCollapsableNav = assign({}, CollapsibleNav._spec, {
...
```
I've done like this and it throws new error in dev-console:
```
Uncaught Error: Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. 
This usually means that you're trying to add a ref to a component that doesn't have an owner 
(that is, was not created inside of another component's `render` method). 
Try rendering this component inside of a new top-level component which will hold the ref.
```
And it is gone if I strip out test snippet to this:
```js
var App = React.createClass( {
  render: function() {
    return (
      <Navbar brand={<a href="/">Jiggle.io</a>} inverse staticTop toggleNavKey={0}>
        <CollapsibleNav eventKey={0}>
        </CollapsibleNav>
      </Navbar>
    );
  }
} );
```
I have no clue what's going on. 
Searching further.

**Comment by AlexKVal** [comment]
Update:
the `...Invariant Violation...` error is not connected with the line
```js
...
CollapsibleNav._spec = specCollapsibleNav;
```
I remove it and error still exists.

**Comment by mtscout6** [comment]
@AlexKVal You are correct, I fired off that suggestion too quick.

**Comment by AlexKVal** [comment]
Just for refs:
`Uncaught Error: Invariant Violation: addComponentAsRefTo(...):` error is caused by
my local tools setup + `npm link` usage.

This comment helped me to find it out: https://github.com/react-bootstrap/react-bootstrap/issues/650#event-303245596

**Comment by AlexKVal** [comment]
@jchapple #734 has to fix your problem now :cherries:

**Comment by jchapple** [comment]
Thanks very much for looking into this! :+1:
