### ISSUE TITLE
modal fades out on update

### ISSUE THREAD

**Issue by mrsln** [react-bootstrap/react-bootstrap#741]
I think I ran into an issue.

When I'm setting a new state in the component which has Modal in its render method, the window fades out. It looks like that Modal [sets](https://github.com/react-bootstrap/react-bootstrap/blob/master/src/Modal.js#L45) the css class 'fade' if there should be an animation, but FadeMixin is [adding] (https://github.com/react-bootstrap/react-bootstrap/blob/master/src/FadeMixin.js#L55) the 'in' class only on componentDidMount. That why Modal ends up with the 'fade' class, but doesn't have the 'in' class after an update.

Also, regardless the issue, it seems that the line of code I mentioned has different style on defining object keys (with and without apostrophe).

*I'm sorry for my runglish ;)*

**Comment by taion** [comment]
Do you have an example of what causes this? This works fine in the live `ModalTrigger` demo:

```jsx
const MyModal = React.createClass({
  getInitialState() {
    return {a: 'a'}
  },
  
  render() {
    return (
      <Modal {...this.props} title='Modal heading'>
        <div className='modal-body'>
          {this.state.a}
        </div>
      </Modal>
    );
  },
  
  componentDidMount() {
    setTimeout(() => this.setState({a: 'b'}), 1000);
  }
});

const overlayTriggerInstance = (
  <ModalTrigger modal={<MyModal />}>
    <Button bsStyle='primary' bsSize='large'>Launch demo modal</Button>
  </ModalTrigger>
);

React.render(overlayTriggerInstance, mountNode);
```

**Comment by mrsln** [comment]
I'm a bit busy right now, I think I'll look into it the next week. By the way, I used OverlayMixin and I have wrapped a class in renderOverlay in order to pass the context for react-router.

**Comment by taion** [comment]
1. You should be using `ModalTrigger` with `Modal`s, not `OverlayTrigger`
2. Triggers-with-context-wrappers that work with react-router are available in react-router-bootstrap (`RouterOverlayTrigger` and `RouterModalTrigger`)

**Comment by AlexKVal** [comment]
I'm closing it. Feel free to reopen if it's still an issue. :sparkle:
