### ISSUE TITLE
Method call typo on the CollapsibleMixing example in the 'Show Code' section

### ISSUE THREAD

**Issue by mysticx** [react-bootstrap/react-bootstrap#742]
When you review the CollapsibleMixin example at [http://react-bootstrap.github.io/components.html#panels-collapsible] (http://react-bootstrap.github.io/components.html#panels-collapsible) in the Show Code section you have this line:

```javascript
let styles = this.getCollapsibleClassSet();
```

And there is a typo. The method called is this.getCollaps**a**bleClassSet, not this.getCollaps**i**bleClassSet();

I know it's a very minor typo issue and I feel kind of uneasy bothering you, but I just copy-pasted that example and modified it for my needs and had an exception :( and I just want to spare other people figuring out what went wrong and was it the mixin that wasn't working and etc.

**Comment by mtscout6** [comment]
Collapsable was a misspelling that has been fixed behind a deprecation warning. Since It has been deprecated for some time now the old spelling was removed yesterday in #735. I do not see any `getCollapsableClassSet` declarations in the current code base which is what I'd expect.
