### ISSUE TITLE
expose utils

### ISSUE THREAD

**Issue by tomatau** [react-bootstrap/react-bootstrap#743]
Seems many of the utils files contain useful functionality, e.g.

https://github.com/react-bootstrap/react-bootstrap/blob/master/src/utils/domUtils.js
https://github.com/react-bootstrap/react-bootstrap/blob/master/src/utils/createChainedFunction.js
https://github.com/react-bootstrap/react-bootstrap/blob/master/src/utils/EventListener.js

Currently I'm requiring them directly:
```
const domUtils = require('react-bootstrap/src/utils/domUtils')
```

but this feels vulnerable to change.

It would be nice if these were exposed through your `index.js` to avoid duplicating functionality in projects or link to to third party implementations.

**Comment by mtscout6** [comment]
You appear to be using ES6, and we do just transpile our src dir to the lib directory. You should be able to use:

`import domUtils from 'react-bootstrap/lib/utils/domUtils';`

I'd be open to adding a namespaced `Utils` object to the public api which exposed some of these things. The exception being anything copied from React like the `EventListener`. I've said this before but I'd rather we removed those from our library and just pull them from React. Though we can't remove them util we do #693.

If you're up to it go ahead and put together a PR that sets up the namespace. This would be done in a similar fashion as the `FormControls` namespace.

**Comment by mathieumg** [comment]
I know it's a lot more work and effort to maintain, but I was thinking that perhaps any original utility (that wasn't copied from somewhere else or that isn't available in another way) could be released independently on npm? A bit like Lo-Dash have decided to do with the 3.x release and like Express/Connect do it with their middlewares starting with the 4.x release.

For instance, I'd love to be able to use the newly added https://github.com/react-bootstrap/react-bootstrap/blob/master/src/utils/CustomPropTypes.js in a different React project that is independent of react-bootstrap.

If there is interest, I'd be ready to help with this.

**Comment by mtscout6** [comment]
[__External Conversation__](https://gitter.im/react-bootstrap/react-bootstrap?at=5565db48dacb05b3394a1b3a)

**Comment by taion** [comment]
I brought that up on Gitter specifically because it wasn't directly related to this discussion :p

**Comment by tomatau** [comment]
Yes as said in my OP, either:
- expose through the index (via a Utils namespace or whatever)
- third party dependencies.

Both have merits, I would prefer the third party dependencies (library) -- but there's more potential for slight duplication when multiple versions conflict for a larger project, etc...

@mtscout6 thanks, I have already used both `src` and `lib` depending on the project... that code just happened to be copied from a project where some of our libraries are compiled internally. It's nice that both are available and not just lib. Point still stands that requiring the lib folder directly could be vulnerable to change.

**Comment by taion** [comment]
I disagree with this statement:

>Point still stands that requiring the lib folder directly could be vulnerable to change.

We explicitly encourage importing components from `lib/` to avoid pulling in unnecessary dependencies. The structure there is not going to break unless there's a very good reason.

**Comment by tomatau** [comment]
@taion 
To quote yourself
> I'd strongly prefer that `createContextWrapper` not be exposed because it's not meant to be public.

If it's not meant to be public then how are you encouraging importing components from lib? This is a contradiction.

If something is intended to be consumed it should be exposed or documented - being neither - it feels that there is more vulnerability to change... The location of these files even changed not too long back and IIRC it wasn't a major release.

**Comment by taion** [comment]
You can import whatever you want from `lib/` - you can even import something like `InputBase` even though you really shouldn't. Can't really hide these imports anyway.

It's explicitly encouraged in the "Getting Started" guide to use imports from `lib/`, though - http://react-bootstrap.github.io/getting-started.html - otherwise you're potentially pulling in a lot more than you need to.

**Comment by tomatau** [comment]
My typo and misunderstanding!  I was talking about pulling out of `utils` being the potential risk, not lib... despite what my comment might look like.

**Comment by AlexKVal** [comment]
Closed by https://github.com/react-bootstrap/react-bootstrap/pull/768
