### ISSUE TITLE
InvariantViolation for Overlay Trigger for v0.23.0

### ISSUE THREAD

**Issue by glifchits** [react-bootstrap/react-bootstrap#749]
I upgraded to React Bootstrap 0.23.0 and moused over a component with an `OverlayTrigger` on it. I got the following error:

```
Invariant Violation: Element appears to be neither ReactComponent nor DOMNode (keys: )
```

I haven't digged into this library too deeply, but from the stacktrace it looks like the overlay trigger is getting `body` as its container node, then eventually calls `React.findDOMNode(body)` and this invokes the `InvariantViolation` for some reason because `body.render !== 'function'`, and React asserts that this is neither an HTMLComponent nor a DOMNode.

Without changing any code, **I downgraded to v0.22.6 and it worked again**. Is this a regression or is there some code I have to change?

**Comment by taion** [comment]
There was a small change to `OverlayTrigger` that looks like it only landed in v0.23.0. What browser are you on?

**Comment by glifchits** [comment]
I was testing on Chrome v43 (unless an update happened since yesterday)

**Comment by glifchits** [comment]
Upgraded to 0.23.0 again and stepped through the OverlayTrigger render. It seems to work again -- not sure where I went wrong yesterday. Sorry about the false alarm!

**Comment by taion** [comment]
Maybe an old version of React or something? `React.findDOMNode` should work on DOM nodes.

**Comment by mtscout6** [comment]
Continued discussion here: https://reactiflux.slack.com/archives/react-bootstrap/p1433454147000003

**Comment by mtscout6** [comment]
Did a hangout with @glifchits though I wasn't able to see what would be causing it off hand. He is using the `OverlayTrigger` with the `hover` trigger which we don't explicitly have unit tests over. @glifchits Said he'd give a shot at writing a failing unit test in react-bootstrap.

Looking at it one more time @glifchits we don't have any tests when the trigger is focused either which follows many of the same mechanics as the hover. Writing a test against hover may be easier to do. An example of some hover tests can be seen at: https://github.com/react-bootstrap/react-bootstrap/blob/dropdown-revisited/test/revisited/DropdownButtonSpec.js#L351-L433

**Comment by taion** [comment]
w/r/t debugging, in case you missed it, from Slack:

taion [18:41]
if this is failing with `body` passed in, that suggests it's failing this check https://github.com/facebook/react/blob/52752446760dee0bc7232b4146f5a309ac57f065/src/renderers/dom/client/findDOMNode.js#L48-L50 (edited)

taion [18:42]
which is here: https://github.com/facebook/react/blob/52752446760dee0bc7232b4146f5a309ac57f065/src/shared/vendor/core/dom/isNode.js

taion [18:42]
it sounds like you're using a non-minified react build, so i'd set a breakpoint in the isNode function

taion [18:43]
err, at the spot of the failure

taion [18:43]
if possible

taion [18:44]18:44
what you should see happen is that you should hit the forward branch on the ternary

**Comment by glifchits** [comment]
Finally found the issue. Its unrelated to react-bootstrap.

We have an old JS lib lying around that defined `Node` as a global function, overriding the browser implementation. React internals (the [`isNode`](https://github.com/facebook/react/blob/52752446760dee0bc7232b4146f5a309ac57f065/src/shared/vendor/core/dom/isNode.js) function) uses the browser `Node` to determine whether something is a DOM node, but this stupid other function got in the way. Specifically `object instanceof Node` returned false.

Not sure why this happened today and for everyone on our team at once... but this seems to be the issue. @mtscout6 and @taion I can't thank you enough for trying to help me out! Very sorry to make a fuss out of this.

**Comment by taion** [comment]
Can you share what lib this is? That's bizarre behavior.

**Comment by mtscout6** [comment]
No problem glad you found the issue.

**Comment by glifchits** [comment]
This is the offending file: https://github.com/pyalot/webgl-heatmap/blob/master/webgl-heatmap.js

I just wrapped all of the code in an IIFE to make sure it doesn't define stuff on the global scope, and problem solved.
