### ISSUE TITLE
Error during npm run build

### ISSUE THREAD

**Issue by lyf78062919** [react-bootstrap/react-bootstrap#754]
[31mError: Command failed: ��ʱ��Ӧ�� <<��
 `babel  --out-file D:\www\javascript\temp\react-bootstrap\lib\factories\index.js <<EOF
 
import Accordion from './Accordion';

import Affix from './Affix';

import Alert from './Alert';

import Badge from './Badge';

import Button from './Button';

import ButtonGroup from './ButtonGroup';

import ButtonInput from './ButtonInput';

import ButtonToolbar from './ButtonToolbar';

import CollapsibleNav from './CollapsibleNav';

import Carousel from './Carousel';

import CarouselItem from './CarouselItem';

import Col from './Col';

import DropdownButton from './DropdownButton';

import DropdownMenu from './DropdownMenu';

import Glyphicon from './Glyphicon';

import Grid from './Grid';

import Input from './Input';

import Interpolate from './Interpolate';

import Jumbotron from './Jumbotron';

import Label from './Label';

import ListGroup from './ListGroup';

import ListGroupItem from './ListGroupItem';

import MenuItem from './MenuItem';

import Modal from './Modal';

import Nav from './Nav';

import Navbar from './Navbar';

import NavItem from './NavItem';

import ModalTrigger from './ModalTrigger';

import OverlayTrigger from './OverlayTrigger';

import PageHeader from './PageHeader';

import Panel from './Panel';

import PanelGroup from './PanelGroup';

import PageItem from './PageItem';

import Pager from './Pager';

import Popover from './Popover';

import ProgressBar from './ProgressBar';

import Row from './Row';

import SplitButton from './SplitButton';

import SubNav from './SubNav';

import TabbedArea from './TabbedArea';

import Table from './Table';

import TabPane from './TabPane';

import Thumbnail from './Thumbnail';

import Tooltip from './Tooltip';

import Well from './Well';

export default {

  Accordion,

  Affix,

  Alert,

  Badge,

  Button,

  ButtonGroup,

  ButtonInput,

  ButtonToolbar,

  CollapsibleNav,

  Carousel,

  CarouselItem,

  Col,

  DropdownButton,

  DropdownMenu,

  Glyphicon,

  Grid,

  Input,

  Interpolate,

  Jumbotron,

  Label,

  ListGroup,

  ListGroupItem,

  MenuItem,

  Modal,

  Nav,

  Navbar,

  NavItem,

  ModalTrigger,

  OverlayTrigger,

  PageHeader,

  Panel,

  PanelGroup,

  PageItem,

  Pager,

  Popover,

  ProgressBar,

  Row,

  SplitButton,

  SubNav,

  TabbedArea,

  Table,

  TabPane,

  Thumbnail,

  Tooltip,

  Well,

}
` (exited with error code 1)[39m
[31mError: Command failed: ��ʱ��Ӧ�� <<��
 `babel  --out-file D:\www\javascript\temp\react-bootstrap\lib\factories\index.js <<EOF
 
import Accordion from './Accordion';

import Affix from './Affix';

import Alert from './Alert';

import Badge from './Badge';

import Button from './Button';

import ButtonGroup from './ButtonGroup';

import ButtonInput from './ButtonInput';

import ButtonToolbar from './ButtonToolbar';

import CollapsibleNav from './CollapsibleNav';

import Carousel from './Carousel';

import CarouselItem from './CarouselItem';

import Col from './Col';

import DropdownButton from './DropdownButton';

import DropdownMenu from './DropdownMenu';

import Glyphicon from './Glyphicon';

import Grid from './Grid';

import Input from './Input';

import Interpolate from './Interpolate';

import Jumbotron from './Jumbotron';

import Label from './Label';

import ListGroup from './ListGroup';

import ListGroupItem from './ListGroupItem';

import MenuItem from './MenuItem';

import Modal from './Modal';

import Nav from './Nav';

import Navbar from './Navbar';

import NavItem from './NavItem';

import ModalTrigger from './ModalTrigger';

import OverlayTrigger from './OverlayTrigger';

import PageHeader from './PageHeader';

import Panel from './Panel';

import PanelGroup from './PanelGroup';

import PageItem from './PageItem';

import Pager from './Pager';

import Popover from './Popover';

import ProgressBar from './ProgressBar';

import Row from './Row';

import SplitButton from './SplitButton';

import SubNav from './SubNav';

import TabbedArea from './TabbedArea';

import Table from './Table';

import TabPane from './TabPane';

import Thumbnail from './Thumbnail';

import Tooltip from './Tooltip';

import Well from './Well';

export default {

  Accordion,

  Affix,

  Alert,

  Badge,

  Button,

  ButtonGroup,

  ButtonInput,

  ButtonToolbar,

  CollapsibleNav,

  Carousel,

  CarouselItem,

  Col,

  DropdownButton,

  DropdownMenu,

  Glyphicon,

  Grid,

  Input,

  Interpolate,

  Jumbotron,

  Label,

  ListGroup,

  ListGroupItem,

  MenuItem,

  Modal,

  Nav,

  Navbar,

  NavItem,

  ModalTrigger,

  OverlayTrigger,

  PageHeader,

  Panel,

  PanelGroup,

  PageItem,

  Pager,

  Popover,

  ProgressBar,

  Row,

  SplitButton,

  SubNav,

  TabbedArea,

  Table,

  TabPane,

  Thumbnail,

  Tooltip,

  Well,

}
` (exited with error code 1)
    at ChildProcess.exithandler (child_process.js:647:15)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at maybeClose (child_process.js:753:16)
    at Socket.<anonymous> (child_process.js:966:11)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Pipe.close (net.js:465:12)[39m

npm ERR! Windows_NT 6.2.9200
npm ERR! argv "D:\\bin\\nodejs\\\\node.exe" "D:\\bin\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v0.10.28
npm ERR! npm  v2.11.0
npm ERR! code ELIFECYCLE
npm ERR! react-bootstrap@0.23.0 build: `babel-node tools/build-cli.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-bootstrap@0.23.0 build script 'babel-node tools/build-cli.js'.
npm ERR! This is most likely a problem with the react-bootstrap package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel-node tools/build-cli.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls react-bootstrap
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\www\javascript\temp\react-bootstrap\npm-debug.log

**Comment by mtscout6** [comment]
Oh Windows how I adore you...

I can confirm that when I fire up my windows VM I'm getting the same error.

This is the offending line: https://github.com/react-bootstrap/react-bootstrap/blob/v0.23.0/tools/generateFactories.js#L16

@tacomanator Any ideas on how to make this work on windows?

**Comment by mathieumg** [comment]
I was with @cellule yesterday and we discovered this issue, he worked around it by replacing that line with:

```js
return exec(`cat ${content} | babel ${babelOptions} --out-file ${outpath}`);
```

however there was another unrelated issue after that. I know he intends to submit a PR about it soon, perhaps today.

**Comment by mtscout6** [comment]
Fantastic, I also had an internal team member hit this a few days ago. He was going to give it a shot today, please let me know if you need any help.

**Comment by Cellule** [comment]
Actually the line was 
```js
return exec(`echo "${content}" | babel ${babelOptions} --out-file ${outpath}`);
``` 
using `echo` and not `cat`

**Comment by mtscout6** [comment]
@cellule I was told by @mathieumg that you may be interested in attempting to tackle #756. If you are interested, I can't tell you how much I'd appreciate it.

**Comment by mathieumg** [comment]
@Cellule Sorry, I wasn't sure anymore if `${content}` was the content itself or the filename of the content. Thanks for pointing it out.

**Comment by tacomanator** [comment]
@Cellule let me know if you need help with the other issue that came up, or need help in testing your pull request on *nix once you have it ready.

**Comment by mtscout6** [comment]
The *nix should be fine since it passes on Travis CI. The real problem is Windows since we don't have an active CI solution for that environment yet.

**Comment by AlexKVal** [comment]
> return exec(`echo "${content}" | babel ${babelOptions} --out-file ${outpath}`);

`echo "${content}"` doesn't work.
`content` contains `'` and `"` etc.

It throws error which is choked somewhere by tools and
as a result after `npm run build` 
`lib/factories` and `amd/lib/factories` folders are empty 
and then the `require()` here [FactoriesSpec.js#L13](https://github.com/AlexKVal/react-bootstrap/blob/1e4cd180ca1569e183fc41d0f3dd37a5f5c700f6/test/FactoriesSpec.js#L13) cannot find any file, 
but this other error also magically chocked somewhere in `karma`
and in console we get only bare
```
SCRIPT ERROR
```

Tomorrow I'll try to continue, but no guaranties.

**Comment by mtscout6** [comment]
It may make sense then to write that to a temporary file.

**Comment by Cellule** [comment]
I tried to transform using the babel api and it worked, but with a few downsides.
```js
  let generateCompiledFile = function (file, content) {
    let outpath = path.join(destination, `${file}.js`);
    let result = babel.transform(content, babelOptions);
    mkdirp.sync(destination);
    fsp.writeFile(outpath, result.code);
  };
```
- `babelOptions` must be an object and not a string which is a problem only at `amd/build.js`. 
- You have to create manually directories and write the result to file.

I wanted to make all babel transform using the api, but I ran into something weird where babel throw an error on 
```
D:\Projects\react-bootstrap\src\Button.js => D:\Projects\react-bootstrap\amd\lib\src\Button.js
SyntaxError: unknown: Unexpected token (34:6)
SyntaxError: unknown: Unexpected token (34:6)
  32 |       active: this.props.active,
  33 |       'btn-block': this.props.block,
> 34 |       ...classes // eslint-disable-line object-shorthand
     |       ^
  35 |     };
  36 |
  37 |     if (this.props.navItem) {
```

**Comment by mathieumg** [comment]
It's as though this setting wasn't considered: https://github.com/react-bootstrap/react-bootstrap/blob/master/.babelrc#L3

When providing `babelOptions` to the API, does Babel ignore the `.babelrc`?

**Comment by Cellule** [comment]
@mathieumg you sir are very right :)

**Comment by lyf78062919** [comment]
This is my solution, but it's very inefficient.

```javascript
    return fsp.writeFile(outpath + '_temp', content)
        .then(() => exec(`babel ${babelOptions} --out-file ${outpath} ${outpath}_temp`)
          .then(() => fsp.remove(outpath + '_temp'))
        );
```
