### ISSUE TITLE
Add documentation for Buttons within a Navbar

### ISSUE THREAD

**Issue by aphillipo** [react-bootstrap/react-bootstrap#770]
Hi there,

Seems that button items that are within a navbar should probably automatically get navbar button?  Or maybe there is a way to specify it on the button?

Thanks,

Andy.

**Comment by mtscout6** [comment]
You should be able to using the `navItem` prop.

**Comment by aphillipo** [comment]
I just ended up setting className and it seemed to merge them all together.

**Comment by jonaskello** [comment]
@aphillipo Could you give an example of your solution? I am trying to put a button inside a navbar and have tried combinations of navItem prop and adding className 'btn-navbar' but have found nothing that works yet...

**Comment by aphillipo** [comment]
I'll have a look at the code... this was a while ago.

**Comment by aphillipo** [comment]
Okay so I'm using react-router-bootstrap for these links (rather than react-bootstrap on it's own) as follows:

    var ReactRouterBootstrap = require('react-router-bootstrap')
        , NavItemLink = ReactRouterBootstrap.NavItemLink
        , ButtonLink = ReactRouterBootstrap.ButtonLink;

    var ReactBootstrap = require('react-bootstrap')
        , ButtonToolbar = ReactBootstrap.ButtonToolbar

Then:

    <ButtonToolbar collapseable>
        <ButtonLink bsStyle="primary" className="navbar-btn" to="new_project" title="A collection of Tests">
            <Glyphicon glyph="plus"/> New Project
        </ButtonLink>
    </ButtonToolbar>;

**Comment by aphillipo** [comment]
Looks to me that it should work fine with react-bootstrap in the code... What is the issue you are having?

**Comment by aphillipo** [comment]
To finish this up the Navbar looks like this, where {toolbar} is the above code.

    <Navbar inverse fixedTop fluid>
        <div className="navbar-header">
         SITE NAME
        </div>
        {toolbar}
    </Navbar>

**Comment by jonaskello** [comment]
Thanks a  bunch for the code example, it really helped! My issue turned out to be very simple, I added the className prop as you suggested but used "btn-navbar" instead of "navbar-btn" (Doh! :-)). Still I think we should not have to add the className prop manually like that. Could it not be added automatically if the navItem prop is set to true?

**Comment by aphillipo** [comment]
Cool, maybe it could be inferred, but I'm not sure if it should be in this bug... Tempted to close it unless you want to provide them with a pull request?

**Comment by jonaskello** [comment]
If it will not infer the needed class, I think it would be helpful if the docs pointed out that you have to add it manually. I guess that is what this issue is about. So maybe keep it open until the docs are updated (or they change it to infer automatically)?

**Comment by taion** [comment]
Sounds like this was resolved.

**Comment by DaoHuyTuan** [comment]
really i don't know how to use bootstrap guys . very hard to handle this can some show me video or code pls , i'm stuck with react bootstrap 3 days

**Comment by daveyx** [comment]
i think it is better to learn raw bootstrap first, before deal with react-bootstrap...
@DaoHuyTuan have a look on my page, super easy react-bootstrap integration:
https://github.com/daveyx/chiangrai-trip
