### ISSUE TITLE
ignore .babel-cache on npm publish

### ISSUE THREAD

**Issue by jprichardson** [react-bootstrap/react-bootstrap#773]
Just installed `0.23.0`. I noticed that it included `react-bootstrap/.babel-cache/`. Would you add this to `.npmignore`?

**Comment by jprichardson** [comment]
Probably related: https://github.com/react-bootstrap/react-bootstrap/pull/744

**Comment by taion** [comment]
I thought the point of #744 was that we whitelisted things to publish rather than blacklisting things not to publish.

**Comment by mtscout6** [comment]
Agreed, we haven't published since #744 which is why you're still seeing it.

**Comment by AlexKVal** [comment]
Now with 0.23 it has gone.
