### ISSUE TITLE
demo page is broken

### ISSUE THREAD

**Issue by luisrudge** [react-bootstrap/react-bootstrap#779]
No component is rendering

![image](https://cloud.githubusercontent.com/assets/941075/7943835/8b044594-093d-11e5-8270-2221edf7ba69.png)

**Comment by mtscout6** [comment]
Blast, cause by #777

**Comment by mtscout6** [comment]
I published a fix they should be working now.

**Comment by luisrudge** [comment]
thanks!

**Comment by mtscout6** [comment]
No thank you for reporting the issue quickly.
