### ISSUE TITLE
Carousel in Modal

### ISSUE THREAD

**Issue by robhuzzey** [react-bootstrap/react-bootstrap#781]
When using a Carousel inside a modal, the images do not display:

```js
<Modal {...this.props}>
  <div className='modal-body'>
    <small onClick={this.props.onRequestHide}>Close X</small>
    
    <TabbedArea defaultActiveKey={1}>
      <TabPane eventKey={1} tab='One'>Content 1</TabPane>
      <TabPane eventKey={2} tab='Two'>
        <Carousel>
          <CarouselItem>
            <img width={900} height={500} alt='900x500' src='http://www.vetprofessionals.com/catprofessional/images/home-cat.jpg' />
            <img width={900} height={500} alt='900x500' src='http://www.nose2tail.co.uk/cat-matlock-derbyshire.jpg' />
            <img width={900} height={500} alt='900x500' src='http://i.huffpost.com/gen/964776/images/o-CATS-KILL-BILLIONS-facebook.jpg' />
          </CarouselItem>
        </Carousel>
      </TabPane>
      <TabPane eventKey={3} tab='Three'>Content 3</TabPane>
    </TabbedArea>

  </div>
</Modal>
```

We've found a fix for now by forcing the z-index but it doesn't feel like the right solution:
```
.modal .carousel-inner .item {
	z-index: 0
}
```

**Comment by mtscout6** [comment]
We are just using Bootstrap's CSS so I'm inclined to think that this is a bug with Bootstrap. I don't see anything alarming on our end. Unless you are able to get this to work with vanilla Bootstrap. If the later is the case if you could demonstrate the vanilla Bootstrap solution then we can figure out a solution. Can you give that a try and let us know what you see?

**Comment by AlexKVal** [comment]
I'm closing it. Feel free to reopen if it's still an issue. :sparkle:
