### ISSUE TITLE
Move the CustomPropTypes utilities to their own repository

### ISSUE THREAD

**Issue by mathieumg** [react-bootstrap/react-bootstrap#782]
Following the discussion in https://github.com/react-bootstrap/react-bootstrap/pull/745#issuecomment-106202740, expose the utilities in https://github.com/react-bootstrap/react-bootstrap/blob/master/src/utils/CustomPropTypes.js as their own repository/npm package: https://github.com/react-bootstrap/react-prop-types 

The rationale is that it covers many relevant use cases outside of React-Bootstrap itself, so developers might want to take advantage of it on its own.

The repository will have its own build and test steps, but the setup shouldn't be anywhere as complex as React-Bootstrap's.

**Comment by AlexKVal** [comment]
:+1:

**Comment by AlexKVal** [comment]
Superceded by #937 :stuck_out_tongue_winking_eye:
