### ISSUE TITLE
OverlayMixin with container: Uncaught NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

### ISSUE THREAD

**Issue by mtetlow** [react-bootstrap/react-bootstrap#784]
I'm having an issue with using the `container` prop to my tooltip and modal overlays. I want to make the `container` prop the root app component of my react app (the container for the entire app), I am using props to pass down a ref to the app component and using that in sub components which need a `container` prop set. This works fine on the initial render, however when I make a large change to the app's viewstate and some overlay triggers unmount, I get: Uncaught NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

The error is coming from this line: https://github.com/react-bootstrap/react-bootstrap/blob/master/src/OverlayMixin.js#L14

When I set a breakpoint on that line I can see that the _overlayTarget and the getContainerDOMNode() seem to be out of sync: http://screencast.com/t/2i7xgSwFdp . Resulting in the failure to remove the node error above.

After debugging for a little while I noticed that on the first render is undefined, because there is no ref generated yet. If I do not render the overlay triggers until there is a defined container prop being passed down... I do not have this issue. It seems like if the container prop changes it should shuffle the component around, or at least figure out where it is mounted to remove it.

I currently have a fix that essentially waits to render overlay triggers until after the first render of the container element, but would welcome any other ideas.

**Comment by mtscout6** [comment]
This is an area that we have not yet fleshed out. As can be seen on our docs the Modal demo has TODOs for Tooltips and Popovers. If you have a solution that works that you could contribute to the docs then we'd all have some code to review for this. I know there was another issue that came up a few weeks ago about this but I can't seem to find it now.

**Comment by taion** [comment]
This has all been re-written since.

**Comment by baiyulong** [comment]
I have the same problem. Is it resolved?

**Comment by jquense** [comment]
This mixin was removed 2 years ago, so yeah.

**Comment by klaxitvrni** [comment]
@mtetlow What was your workaround. Could you share that code?
