### ISSUE TITLE
Default autocomplete to 'off' for password inputs

### ISSUE THREAD

**Issue by binarykitchen** [react-bootstrap/react-bootstrap#804]
This for security. And secondly I couldn't set the props `autocomplete = 'off'` - it had no effect.

**Comment by mathieumg** [comment]
Isn't it `autoComplete` since this is React?

**Comment by binarykitchen** [comment]
`autoComplete = 'off'` doesn't work either

**Comment by mathieumg** [comment]
Does it work properly when you do it without React? This might be related: https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion#The_autocomplete_attribute_and_login_fields

**Comment by binarykitchen** [comment]
honestly, it doesn't matter. `autocomplete` is a HTML5 conform attribute and it should be there. why is react-bootstrap's Input element letting it through in the render()?

**Comment by binarykitchen** [comment]
ah, never mind, i found the bug on my side - sorry about the distraction

**Comment by Bob1993** [comment]
Yeah, you can use `autoComplete = 'off'` and it will be delivered into `<input />`. Finally, it should work fine unless your browser doesn't support `autocomponent='off'`...

**Comment by conor909** [comment]
I have the same issue, this doesnt work 
`<Form.Control autoComplete='off' name='email' type='email' placeholder='Enter email' onChange={handleInputChange} />`

**Comment by TippyLion28** [comment]
Can't get it to work either

**Comment by jquense** [comment]
browsers (mainly chrome) ignore `autocomplete` for passwords and some other common input types. There is very little anyone can do to alter the behavior

**Comment by kosmiq** [comment]
If you need to disable autocomplete and have Chrome actually respect it, try setting
`autocomplete="new-password"`

More here: https://www.chromium.org/developers/design-documents/form-styles-that-chromium-understands
