### ISSUE TITLE
How to make a modal window on the React, using the coffeescript

### ISSUE THREAD

**Issue by 13ga1ka** [react-bootstrap/react-bootstrap#805]
Good day! 
The question arose as to create a modal window on the React, using the preprocessor coffeescript. There is a component of a menu where you press the button to open modal window.

Enclose a component code below:

{div} = React.DOM

testModalComponent = React.createClass
   getInitialState: ()->
    {
      modalShow: false,
    }

  openModal: ->
    @setState
      modalShow: true

  render: ->
    div className: 'click-me', onClick: @openModal, 'Open modal window'
    if @state.modalShow
      div className: 'test-class'
         ReactBootstrap.Modal ????

**Comment by mtscout6** [comment]
This is described in the docs at http://react-bootstrap.github.io/components.html#modals-live.

There's also documentation for a custom trigger at http://react-bootstrap.github.io/components.html#modals-custom.

Checkout the code examples, they are written in ES6 JavaScript but shouldn't be too difficult to convert to CoffeeScript.
