### ISSUE TITLE
OverlayTrigger or Tooltip onExit prop?

### ISSUE THREAD

**Issue by aphillipo** [react-bootstrap/react-bootstrap#806]
Hi there!

Thanks, loads for this amazing module.  Would be great to have onExit added to Tooltip and/or OverlayTrigger.  Yes, I can add this myself, but it seems less clean (especially if you factor in delays).

Ta,

Andy.

**Comment by mtscout6** [comment]
Sounds reasonable to add. We take pull requests!

**Comment by taion** [comment]
FWIW, I'd perhaps combine it with the `onRequestHide` prop injected by the `OverlayTrigger` into the overlay.

**Comment by mtscout6** [comment]
So this is interesting since I see those as two different events. One is a pre-exit and the other is post-exit. Both have value.

**Comment by taion** [comment]
Oh - you mean e.g. have a separate `onHide` that explicitly gets chained after `OverlayTrigger#hide`? Makes sense.

**Comment by wuct** [comment]
+1 for this feature!
Hi @taion, are you working on this feature? Should I implement it and create a PR?

**Comment by taion** [comment]
I am not. I think #855 might address this.

**Comment by jquense** [comment]
that PR and #848  i think will give use really finely grained callbacks

**Comment by wuct** [comment]
@jquense @taion Thanks for your great work! New Overlays APIs look great.

**Comment by AlexKVal** [comment]
#855 and #848 are already landed in codebase.
