### ISSUE TITLE
OverlayTrigger, Popover and positioning

### ISSUE THREAD

**Issue by marcojahn** [react-bootstrap/react-bootstrap#816]
Hi,
using an OverlayTrigger with a Popover within a Navbar works fine except repositioning the element.

The code I am using
```
<OverlayTrigger trigger='hover' placement='top' overlay={<Popover title='Messages'>more text</Popover>}>
    <NavItem eventKey={1} href='#'>Message box <Label bsStyle="primary">42</Label></NavItem>
</OverlayTrigger>
```

But it seems that providing a positionTop={50} or positionTop={-50} is not handed over to the Popover.
I've tried setting it on both OverlayTrigger and Popover. But none works.

The value of this.props.positionTop in Popover.js render() is always "null"

Any tips on how this must be used to work ?

Kind regards

**Comment by taion** [comment]
Ref #811, which will change how most of this works anyway.

FWIW you're not really supposed to be setting those props manually - `OverlayTrigger` will override them anyway.

**Comment by AlexKVal** [comment]
Superceded by #855
