### ISSUE TITLE
Checkbox is hard to click

### ISSUE THREAD

**Issue by nlhkh** [react-bootstrap/react-bootstrap#818]
When using Input instead of the default input, the checkbox is very hard to toggle.

**Comment by taion** [comment]
This is just the standard Bootstrap checkbox. Is there a difference between the one here and the one in vanilla Bootstrap?

**Comment by mtscout6** [comment]
How do you mean? What would you expect to be available? Please provide more detail perhaps a code example. Is it our code API you are talking about?

**Comment by dozoisch** [comment]
@nlhkh Any update on this or can we close it?

**Comment by nlhkh** [comment]
I cannot reproduce this. Perhaps it was something wrong in my css. Please close this.

**Comment by dozoisch** [comment]
@nlhkh No worries! Better log something that is a false positive, than miss it!
