### ISSUE TITLE
Use uncontrollable where appropriate

### ISSUE THREAD

**Issue by mtscout6** [react-bootstrap/react-bootstrap#820]
There has been some discussion as of late regarding the [uncontrollable](https://github.com/jquense/uncontrollable) library to manage component state for things like open/onToggle, and value/onChange. Some things we need to know before we can make a well educated decision:
- Which Components will work with it
- Which events/state in each of those components would it control
- How will that work with the existing props that serve as events in these components as the signature would change. (Use of return value is important with uncontrollable)

Once the survey is complete then we can decide on any action plan necessary.

**Comment by jquense** [comment]
Initial list of Components that already have some logic for this embedded
- Carousal
  - `activeIndex` -> `onSelect`, (supports `defaultActiveIndex`)
- CollapsibleMixin
  - `expanded` -> [no callback], (supports `defaultExpanded`)
- CollapsableNav -> CollapsibleMixin
- DropdownButton?
- Navbar
  - `navExpanded` -> `onToggle` (no value passed), (supports `defaultNavExpanded`)
- Panel -> CollapsibleMixin (adds `onSelect`, passes event and key)
- PanelGroup
  - `activeKey` -> `onSelect`, supports default
- TabbedArea
  - `activeKey` -> `onSelect`, supports default
- Overlays? depens on what the API stabilizes too, but `show` -> `onHide`

List of Components that probably could/should support uncontrolled props, but don't.

- ListGroup? items have an `active` prop and `onClick`
- Things using MenuItem?
- Pagination: `activePage` -> `onSelect`


In cases where there is a simple prop, and a handler that passes back the value you could add in something like uncontrollable without any api changes, and remove a bunch of code. At least a few of these, could be made more consistent by eitehr passing the value (Navbar) or reordering the arguments (Panel). I am not sure what

A few Components do not have sufficient logic in them for their current functionalities. Changes need to be properly propagated to either state or props, with logic like:
```js
  shouldComponentUpdate() {
    return !this._isChanging;  // Defer any updates to this component during the `onSelect` handler.
  },

  handleSelect(e, key) {
    e.preventDefault();

    if (this.props.onSelect) {
      this._isChanging = true;
      this.props.onSelect(key);
      this._isChanging = false;
    }

    this.setState({
      activeKey: key
    });
  }
```

but they may just update both, causing unnecessary (and in edge cases, bug inducing) updates. The above code is a pretty good indication of how much code you actually need to do this pattern properly, so its a bit more work than just making sure to check state or props when you want to read the value.

**Comment by taion** [comment]
ref #1148

**Comment by taion** [comment]
Updated issue title to reflect reality.

**Comment by taion** [comment]
I think we're down to just `<Carousel>` now.

**Comment by Inlesco** [comment]
Are there any plans to finish up the `Carousel` comp?

I'd be glad to take on this and dive deeper into the RBS codebase whenever I've got some time on my hands.

**Comment by jquense** [comment]
no specific plans if you want to jump in go for it 👍
