### ISSUE TITLE
Touch support

### ISSUE THREAD

**Issue by jareware** [react-bootstrap/react-bootstrap#831]
Do you have a preferred method for supporting touch events, e.g. [react-tap-event-plugin](https://github.com/zilverline/react-tap-event-plugin)? Clicking through [the demos](http://react-bootstrap.github.io/components.html) on a touch device affected by the delay feels sluggish.

(Sorry if this has been discussed already, couldn't find an issue at least)

**Comment by mtscout6** [comment]
Looking at the README for that project it looks like anyone using our library can leverage that today if they want as it's a globally applied handler. Are you solely proposing that we add this to our docs site?

**Comment by jareware** [comment]
More just asking whether you know of people successfully using something with `react-bootstrap` for fast-clicks. :) Touch support in React is a bit of a mess... But I agree, looks like you can use anything with your lib, and you don't have anything touch-specific built in. Goodie!

Also adding fast-clicks to the demo site might be a really good idea, as it's currently slightly off-putting to browse on a touch device (one which doesn't remove the delay automatically when possible; some newer ones do).

**Comment by dozoisch** [comment]
@mtscout6 maybe we could do like [material-ui get started](http://material-ui.com/#/get-started) and recommend something.

>  # React-Tap-Event-Plugin

> Some components use react-tap-event-plugin to listen for touch events. This dependency is temporary and will go away once react v1.0 is released. Until then, be sure to inject this plugin at the start of your app.

**Comment by mtscout6** [comment]
None of our components explicitly use it so the verbiage would need to change, but I'd be ok with that on the Getting Started page.

**Comment by mathieumg** [comment]
> Also adding fast-clicks to the demo site

I don't have anything against it, but I'm worried users wouldn't understand why they don't get the same performance in the demo site and with their code. :+1: +1 for the mention in getting started.

**Comment by taion** [comment]
That Material UI thing is actually because they internally use tap events.

I think tap events in general are a bit out of scope here - if an R-B user wants to use them, there's more implications than just adding a bit of support and docs to R-B.

I'm going to close this issue for now, but we can re-open this if we think there's a better way forward.
