### ISSUE TITLE
MeteorJS Support

### ISSUE THREAD

**Issue by mtscout6** [react-bootstrap/react-bootstrap#837]
It looks like @firfi has been maintaining a fork of this project which is getting published to [Atmosphere](https://atmospherejs.com/) which is the MeteorJS package manager. I'm not entirely familiar with Meteor nor to I really know how much support for this from the core team is wanted or needed. My initial thought is that something like this could be built into the build and release pipeline if there truly is a need for it.

In my initial look at @firfi's fork the minimal needed for this package to be defined is:

- `package.js` File at the repo root
- commited dist folder to project
- `METEOR.md` which is basically the README.

What strikes me about this is that 90% of this is already in the Bower release, and in general I'd think could be added to that release seeing as I'd prefer not to commit the dist folder to the project. (@ferefrer I'm thinking that may be the issue you are seeing in firfi/meteor-react-bootstrap#1 as you just merged our latest master, but we don't commit the dist folder)

Granted there is a lot I do not know about MeteorJS. Should this be desired we could use support from some folks that actively use it to make sure that deployment pipeline is sound.

Reading through more docs I'm also seeing this: http://docs.meteor.com/#/full/Npm-require is that also a viable alternative? If not why not? If so, then we should add some documentation for such.

**Comment by Firfi** [comment]
Some notes:

Last time I checked npm-require didn't worked for frontend.

METEOR.md is not necessary, it is just reminder for myself.

One thing that concerns me most is how meteor works with assigning the global (see https://github.com/Firfi/meteor-react-bootstrap/blob/master/dist/react-bootstrap.js#L14, and also first and last lines)

**Comment by Firfi** [comment]
Also as far as I know Meteor team is working on new build system, (https://github.com/meteor/meteor/issues/4384#issuecomment-103667060) that may or may not address this issue.

**Comment by mtscout6** [comment]
As far as your hack is concerned that's what UMD is supposed to be solving for you. You are pulling React off the global and changing the `this` that's in scope. If AMD or CommonJS is not identified than that is exactly what should happen with UMD, there should be no need for that hack.

Thanks for the enlightenment about npm-require.

I still think that by adding some more files to the bower release and pointing at that repo will be the way to go for this.

**Comment by Firfi** [comment]
@mtscout6 This task moved me towards investigating possibilities once more and it seems that this guy https://github.com/elidoran/cosmos-browserify/ did the great job making browserify working in Meteor. I substituted all my react-involved packages with this and it works well so far. 

Therefore, most probably we won't need special meteor version anymore.

**Comment by mtscout6** [comment]
Perfect! Are you using the npm release? Or do you did you do anything special to make this work? That would be useful to know for others seeking a solution.

**Comment by Firfi** [comment]
Just an npm release. It is done the same way it is done in their example.

1) Create local package

a) Set up npm dependency in package.js

b) global-assign require() result in your *.browserify.js file in this
local package

c) export this assigned var in package.js

2) don't forget to add this local package in your meteor app (meteor add
...package name..., or just put it into .meteor/packages)

So it basically works with react-bootstrap too. I can make an example later.

2015-06-16 1:54 GMT+03:00 Matt Smith <notifications@github.com>:

**Comment by Firfi** [comment]
Some guide written http://www.loskutoff.com/blog/making-browserify-dot-js-working-with-meteor-application/

**Comment by AlexKVal** [comment]
I'm closing it.
If somebody writes some day a topic / article / documentation about MeteorsJS integration
and wants a link to it, fell free to make PR :+1:

**Comment by colvint** [comment]
Exporting `ReactBootstrap` to the `client` is trivial thanks to the `cosmos:browserify` Meteor package. 

Here's an example: https://github.com/colvint/react-bootstrap

Note: the Meteor Development Group (MDG) follows this same approach in exporting `React` to the `client`.

**Comment by AlexKVal** [comment]
Thank you @colvint :+1: 
:cherries:
