### ISSUE TITLE
Do not use Babel cache for release build

### ISSUE THREAD

**Issue by taion** [react-bootstrap/react-bootstrap#840]
Changes to e.g. `.babelrc` do not invalidate `babel-loader`'s cache. I don't think it's too onerous to require developers messing with Babel settings to clear the cache themselves, but we should make sure we either `rimraf` the cache in the publish script or bypass the cache when building for release, just to guarantee correctness.

**Comment by mtscout6** [comment]
Closed by #843

**Comment by taion** [comment]
That said, this fix is only temporary - I feel that the code in #843 is fairly fragile, and I'd be much happier when we can use babel/babel-loader#62.

**Comment by mathieumg** [comment]
> I'd be much happier when we can use babel/babel-loader#62.

https://github.com/babel/babel-loader/issues/62#issuecomment-115338014 :tada:
