### ISSUE TITLE
Components page jumps to modal after loading

### ISSUE THREAD

**Issue by taion** [react-bootstrap/react-bootstrap#842]
As a consequence of https://github.com/react-bootstrap/react-bootstrap/commit/5313abe35b26e10240a2cc3d55d8c68d16f89c14, the components page jumps to the static modal as soon as it finishes loading. This is a bit annoying.

**Comment by jquense** [comment]
I think we can integrate that change with the newly merged `enforceFocus` prop from #810

**Comment by taion** [comment]
Oh, didn't see that #810 just got merged. Not sure if this still applies then. Worth checking - it's annoying and confusing to see the main docs page do that jump.

**Comment by jquense** [comment]
I think it still applies, but at least now we have the means to fix it. I will PR something when I get a moment

**Comment by AlexKVal** [comment]
```js
componentDidMount() {
...
this.focusModalContent(); // this
```
[this line](https://github.com/react-bootstrap/react-bootstrap/blob/5313abe35b26e10240a2cc3d55d8c68d16f89c14/src/Modal.js#L129) is the "culprit"

We should re-write the Modal example (to show only after clicking to some button) or add some prop that would allow us to disable this 'auto-focusing'.

**Comment by AlexKVal** [comment]
@jquense you are fast :smile:  with a crying baby :umbrella:

**Comment by jquense** [comment]
hehe i had a break where the baby was happy, so why not :)

**Comment by jquense** [comment]
should be fixed in last release
