### ISSUE TITLE
Uncaught TypeError: Cannot read property 'appendChild' of null

### ISSUE THREAD

**Issue by binarykitchen** [react-bootstrap/react-bootstrap#849]
Happens with your latest version 0.23.4 but didn't earlier.

Thrown at line `document.body.appendChild(scrollDiv);` in

```js
	if (_utilsDomUtils2['default'].canUseDom) {
	  var scrollDiv = document.createElement('div');

	  scrollDiv.style.position = 'absolute';
	  scrollDiv.style.top = '-9999px';
	  scrollDiv.style.width = '50px';
	  scrollDiv.style.height = '50px';
	  scrollDiv.style.overflow = 'scroll';

	  document.body.appendChild(scrollDiv);

	  scrollbarSize = scrollDiv.offsetWidth - scrollDiv.clientWidth;

	  document.body.removeChild(scrollDiv);
	  scrollDiv = null;
	}
```

**Comment by dozoisch** [comment]
In what environnement are you? What Browser? Where does it happen?

**Comment by jquense** [comment]
this is probably because bootstrap or your bundle is being loaded in the head of your html, scripts should come after the body tag to avoid this. 

from our end if there is a good reason to load scripts in the head we can lazily make that check :/

**Comment by binarykitchen** [comment]
Latest Google Chrome, run by Selenium on Ubuntu 15.40

**Comment by mtscout6** [comment]
@jquense I think resolving that lazily is the better way to go. I frequently put my scripts in the head with the async attribute to get them downloading quicker. Granted for the older IE browser's we fallback to a DOM Ready check before bootstrapping.

**Comment by monodelic** [comment]
Guys, seems to be i have same problems with 1.0.5. and moving ' = javascript_pack_tag "application" ' into <body> is solving the problem. Could you please fix it?

**Comment by volkanunsal** [comment]
I'm having the same issue.

**Comment by volkanunsal** [comment]
Loading js at the end of the file is not solution for me because I use a css-in-js library. If the js is not loaded in the header, the page looks broken for a split second.

**Comment by KODerFunk** [comment]
HeY! Common! Realy!
