### ISSUE TITLE
Allow hovering over popover when trigger is hover

### ISSUE THREAD

**Issue by datpham23** [react-bootstrap/react-bootstrap#850]
Hi,

Is there any way to allow popovers with the trigger 'hover' to stay open as long as you're hovering the trigger or the popover?

**Comment by taion** [comment]
Not at the moment. The `hover` trigger is really meant more for tooltips.

**Comment by jquense** [comment]
this seems out of scope for the OverlayTrigger...but should be possible under the new API (#811) in some form or another.

**Comment by AlexKVal** [comment]
Superceded by #855

**Comment by mmahalwy** [comment]
any update on this?

**Comment by jquense** [comment]
the update is that you can make whatever behavior you'd like using the Overlay component, we aren't directly supporting this use case

**Comment by lou** [comment]
I had the same issue so I did this little component to handle it.
It work just fine for my use case.
https://gist.github.com/lou/571b7c0e7797860d6c555a9fdc0496f9

**Comment by guruwanabe** [comment]
> the update is that you can make whatever behavior you'd like using the Overlay component, we aren't directly supporting this use case

Seems rather odd to me that a simple use case like this is not supported. Yes we can achieve it with custom overlays, but it should be easier to just integrate as a prop to OverlayTrigger something like 'persistShow' instead of building a custom component.
