### ISSUE TITLE
Using react-bootstrap Modal with Flux 

### ISSUE THREAD

**Issue by amunda** [react-bootstrap/react-bootstrap#862]
I am noticing an issue when using react-bootstrap Modal with Flux. The problem is that i am showing a list of items and each item has a ModalTrigger and each Modal object passed to ModalTrigger is listening to Flux store. So on a page where there are 25 items, it creates 25 new Modal components and each gets registered to a Store

This causes the warning " (node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit."

I can fix this by increasing the limit but was wondering is this the expected way to use Modal with Flux? You create a Modal for each trigger and make each modal to listen to store for data updates?

This also has a side effect of all these object being called when only one modal is clicked.

Let me know your thoughts

Thanks

**Comment by taion** [comment]
Why are you connecting the stores to the modal triggers? Are you using that store to manage which modals are shown?

**Comment by amunda** [comment]
Well. Each modal needs to get a different data and the data is fetched from server. So here is the workflow

User does the search -> we show 25 items -> each item has a link to show status in the modal -> status is fetched from server -> when user clicks the link -> we fetch the data from server update the store and store notifies the Modal to update its view.

Problem is this way all 25 modals gets the notification and the rendering happens for each of them.

**Comment by taion** [comment]
Why not connect the Modals to the stores rather than the ModalTriggers?

**Comment by amunda** [comment]
Oh sorry, yes thats where the problem was, we were assuming that trigger will also create Modal but it only does when you click it and make sense to put store listeners there.

Thanks for your help!
