### ISSUE TITLE
Official two-release deprecation policy before 1.0.0

### ISSUE THREAD

**Issue by taion** [react-bootstrap/react-bootstrap#863]
What do you all think about instituting an official two-release deprecation policy before 1.0.0, akin to upstream React?

For example, we are currently at v0.23. If we want to remove a feature, we won't add a deprecation warning until v0.24, and we won't actually remove the feature until v0.25, barring absolute necessity.

This is more strict than what we currently have, but is in line with what React does.

**Comment by dozoisch** [comment]
I'm fine with that!

Though I could see it where we could even add the deprecation earlier like next patch release to give feedback earlier.

**Comment by mathieumg** [comment]
Good with me too, I don't have a strong opinion on whether deprecation notices start at patch versions or "minor" version (major for all intents and purposes, pre-1.0).

**Comment by taion** [comment]
I feel that the nice thing about not doing deprecation for patch-level changes is that if I'm using e.g. `^0.23.4`, I'd rather not start getting deprecation warnings for patch-level updates, in case I'm e.g. asserting that my code doesn't throw any warnings in tests.

**Comment by dozoisch** [comment]
Ah that makes sense

**Comment by mtscout6** [comment]
I'm generally fine with the idea, though if we do this it would make sense to maintain both a `v0.<x+1>-rc` branch and a `v0.<x+2>-rc` branch as well so we can be pushing those changes and keep ourselves from constantly needing to go back to an old decision a few weeks down the line.

I'd also like to keep those changes available on npm as soon as possible similar to what we are doing now with our pre-release for v0.24. If we do this I'd propose that we make `v0.x+1` the beta release and `v0.x+2` the alpha. Thus allowing those that submit PRs to get the changes as soon as possible through pre-releases. The good thing is that our release scripts already do this with little headache.

**Comment by dozoisch** [comment]
@mtscout6 sounds good

**Comment by taion** [comment]
Not sure yet where to submit the PR against. The wording I'd like to see would be, in README:

>Prior to the 1.0.0 release, breaking changes should result in a Minor version bump.

to

>Prior to the 1.0.0 release, deprecations or breaking changes should result in a Minor version bump.

And in MAINTAINING:

>In an effort to reduce the frequency with which we introduce breaking changes we should do our best to first push deprecation warnings in a Minor or Patch release.

to

>In an effort to reduce the frequency with which we introduce breaking changes we should do our best to first push deprecation warnings in a Minor release.

**Comment by mtscout6** [comment]
That sounds reasonable to me, I'd like to start this once the v0.24 release is out since it violates some of the ideas presented here. So with that let's push that change to the v0.24-rc branch.

**Comment by AlexKVal** [comment]
Realized in #898
