### ISSUE TITLE
importing components from lib

### ISSUE THREAD

**Issue by bsr203** [react-bootstrap/react-bootstrap#868]
Hello,
I am wrapping some of the components from [react-bootstrap][1] along with my custom components. But, I have issue with properly packaging it all with webpack.

say, I want to use the `Accordion` component. The code in npm module (when I `install with npm i react-bootstrap`) at node_modules/react-bootstrap/lib/Accordion.js is given below. The problem is the statement 

     `var _PanelGroup = require('./PanelGroup');`

this is failed to resolve, once I bundle it and use like

```
    let Accordion = require('react-bootstrap/lib/Accordion');
    ....
    export {
      Accordion,
      ....
    }
```
I have `react-bootstrap` in dependencies and installs wherever I installs this custom package. But, fail to resolve this relative import.

I could make this work by importing it from the dist version like

  `  import { Accordion } from 'react-bootstrap/dist/react-bootstrap';`

but that means, the entire dist file (dist/react-bootstrap.js) is included. Which I don't need.

can you tell me how to import just selected components into my package?

```
    'use strict';
    
    Object.defineProperty(exports, '__esModule', {
      value: true
    });
    
    var _extends = Object.assign || function (target) { for (var i = 1; i < arguments.length; i++) { var source = arguments[i]; for (var key in source) { if (Object.prototype.hasOwnProperty.call(source, key)) { target[key] = source[key]; } } } return target; };
    
    function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { 'default': obj }; }
    
    var _react = require('react');
    
    var _react2 = _interopRequireDefault(_react);
    
    var _PanelGroup = require('./PanelGroup');
    
    var _PanelGroup2 = _interopRequireDefault(_PanelGroup);
    
    var Accordion = _react2['default'].createClass({
      displayName: 'Accordion',
    
      render: function render() {
        return _react2['default'].createElement(
          _PanelGroup2['default'],
          _extends({}, this.props, { accordion: true }),
          this.props.children
        );
      }
    });
    
    exports['default'] = Accordion;
    module.exports = exports['default'];
```
  [1]: https://github.com/react-bootstrap/react-bootstrap

**Comment by mtscout6** [comment]
Can you provide the exact error message you are getting?

**Comment by bsr203** [comment]
I close it now as I couldn't reproduce now. Will open if encounter again. thanks for helping out.
