### ISSUE TITLE
Do I need extra files except react-bootstrap? For instance css files?

### ISSUE THREAD

**Issue by SudoPlz** [react-bootstrap/react-bootstrap#870]
Hello, it might seem obvious to others, but since I'm currently learning, I'd love to know wether I need any extra files to make bootstrap work. 
All I did till now was `npm install react-bootstrap`. Do I need to download bootstrap css from their site and place it somewhere in my project?

The reason I'm asking is because I'm currently using this `navbar`
```javascript
<Navbar brand='React-Bootstrap' toggleNavKey={0}>
        <CollapsibleNav eventKey={0}> {/* This is the eventKey referenced */}
            <Nav navbar>
                <NavItem eventKey={1} href='#'>Link</NavItem>
                <NavItem eventKey={2} href='#'>Link</NavItem>
                <DropdownButton eventKey={3} title='Dropdown'>
                    <MenuItem eventKey='1'>Action</MenuItem>
                    <MenuItem eventKey='2'>Another action</MenuItem>
                    <MenuItem eventKey='3'>Something else here</MenuItem>
                    <MenuItem divider />
                    <MenuItem eventKey='4'>Separated link</MenuItem>
                </DropdownButton>
            </Nav>
            <Nav navbar right>
                <NavItem eventKey={1} href='#'>Link Right</NavItem>
                <NavItem eventKey={2} href='#'>Link Right</NavItem>
            </Nav>
        </CollapsibleNav>
    </Navbar>
```
and there are no colours or anything, just a list of text :
![screen shot 2015-06-20 at 9 42 55 pm](https://cloud.githubusercontent.com/assets/3070948/8268649/5d9ca3b0-1795-11e5-8247-05a8fd59afa6.png)

Thank you..!

**Comment by mathieumg** [comment]
You do! See: https://react-bootstrap.github.io/getting-started.html

> Because many folks use custom Bootstrap themes, we do not directly depend on Bootstrap. It is up to you to to determine how you get and link to the Bootstrap CSS and fonts.
