### ISSUE TITLE
Modal not working

### ISSUE THREAD

**Issue by rahul1346** [react-bootstrap/react-bootstrap#876]
I am trying to get a modal to popup when Login is clicked but nothing populates.

Im using the 'react-bootstrap' library.

Here is the code:
```js
var React  = require('react');
var Modal = require('react-bootstrap');

var Login = React.createClass({
  render: function() {
    return (
    <div className='static-modal'>
        <Modal title='Modal title'
          enforceFocus={false}
          backdrop={false}
          animation={false}
          container={mountNode}
          onRequestHide={function() {}}>
          <div className='modal-body'>
            One fine body...
          </div>
          <div className='modal-footer'>
            <Button>Close</Button>
            <Button bsStyle='primary'>Save changes</Button>
          </div>
        </Modal>
      </div>
    );
  }
});


module.exports = Login;
```
Any idea why it's not rendering? What does MountNode have to be passed as?

FYI, I am also using react router to route thru the components.

**Comment by jquense** [comment]
Hi there, could you fix the code formating on your issue? it's a bit hard to tell what's going on. you can wrap code snippets in three back ticks ` ```` `

**Comment by rahul1346** [comment]
Fixed it sorry about that.

I am just trying to get a modal to populate when login is clicked so that I can have a user authenticate.

**Comment by jquense** [comment]
great thanks. right now the modal is just the plain markup you need to also combine it with a ModalTrigger component to actually show or hide it. You can also make use of the OverlayMixin as well. check out the code examples in the documentation site for specifics

**Comment by rahul1346** [comment]
Thanks but the code does not show how to get the modal to work as it is just markup for example:

When doing the following:

```
var React = require('react');
var ReactBootstrap = require('react-bootstrap');
var Button = ReactBootstrap.Button
var ModalTrigger = ReactBootstrap.ModalTrigger;

const MyModal = React.createClass({
  render() {
    return (
      <Modal {...this.props} title='Modal heading' animation={false}>
        <div className='modal-body'>
          <h4>Text in a modal</h4>
          <p>Duis mollis, est non commodo luctus, nisi erat porttitor ligula.</p>

          <h4>Popover in a modal</h4>
          <p>TODO</p>

          <h4>Tooltips in a modal</h4>
          <p>TODO</p>

          <hr />

          <h4>Overflowing text to show scroll behavior</h4>
          <p>Cras mattis consectetur purus sit amet fermentum. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Morbi leo risus, porta ac consectetur ac, vestibulum at eros.</p>
          <p>Praesent commodo cursus magna, vel scelerisque nisl consectetur et. Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor.</p>
          <p>Aenean lacinia bibendum nulla sed consectetur. Praesent commodo cursus magna, vel scelerisque nisl consectetur et. Donec sed odio dui. Donec ullamcorper nulla non metus auctor fringilla.</p>
          <p>Cras mattis consectetur purus sit amet fermentum. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Morbi leo risus, porta ac consectetur ac, vestibulum at eros.</p>
          <p>Praesent commodo cursus magna, vel scelerisque nisl consectetur et. Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor.</p>
          <p>Aenean lacinia bibendum nulla sed consectetur. Praesent commodo cursus magna, vel scelerisque nisl consectetur et. Donec sed odio dui. Donec ullamcorper nulla non metus auctor fringilla.</p>
          <p>Cras mattis consectetur purus sit amet fermentum. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Morbi leo risus, porta ac consectetur ac, vestibulum at eros.</p>
          <p>Praesent commodo cursus magna, vel scelerisque nisl consectetur et. Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor.</p>
          <p>Aenean lacinia bibendum nulla sed consectetur. Praesent commodo cursus magna, vel scelerisque nisl consectetur et. Donec sed odio dui. Donec ullamcorper nulla non metus auctor fringilla.</p>
        </div>
        <div className='modal-footer'>
          <Button onClick={this.props.onRequestHide}>Close</Button>
        </div>
      </Modal>
    );
  }
});

const overlayTriggerInstance = (
  <ModalTrigger modal={<MyModal />}>
    <Button bsStyle='primary' bsSize='large'>Launch demo modal</Button>
  </ModalTrigger>
);

module.exports = overlayTriggerInstance;
```
I get the following error:

Uncaught TypeError: type.toUpperCase is not a function


What am I doing wrong/?

**Comment by jquense** [comment]
it doesn't look like you imported the Modal component in your example. that cryptic error is React saying some Component actually wasn't defined.  you need to do `var Modal = ReactBootstrap.Modal` as well

**Comment by rahul1346** [comment]
Yea, still getting same error unfortunately...

**Comment by jquense** [comment]
you shouldn't be exporting an instance of the modal trigger. just export the modal class (MyModal)  and in the component you want to open the modal with use the modal trigger in the render() method.

**Comment by rahul1346** [comment]
Thanks for all the help, Jason. Perhaps its my knowledge of React then, but I just tried to use the OverlayMixin instead of the ModalTrigger

```
var React = require('react');
var ReactBootstrap = require('react-bootstrap');
var Modal = ReactBootstrap.Modal;
var Button = ReactBootstrap.Button;
var OverlayMixin = ReactBootstrap.OverlayMixin;

const MyModal = React.createClass({
  mixins: [OverlayMixin],

  getInitialState() {
    return {
      isModalOpen: false
    };
  },

  handleToggle() {
    this.setState({
      isModalOpen: !this.state.isModalOpen
    });
  },

  render: function () {
    return (
      this.handleToggle()
    );
  },

  // This is called by the `OverlayMixin` when this component
  // is mounted or updated and the return value is appended to the body.
  renderOverlay() {
    if (!this.state.isModalOpen) {
      return <span/>;
    }

    return (
      <Modal title='Modal heading' onRequestHide={this.handleToggle}>
        <div className='modal-body'>
          This modal is controlled by our custom trigger component.
        </div>
        <div className='modal-footer'>
          <Button onClick={this.handleToggle}>Close</Button>
        </div>
      </Modal>
    );
  }
});


module.exports = MyModal;
```

Now I get the error:
```
Uncaught Error: Invariant Violation: setState(...): Cannot update during an existing state transition (such as within `render`). Render methods should be a pure function of props and state.
```

All I am trying to do is get the modal to populate when the Login tab is clicked in the navbar. When the user authenticates through the modal, it just returns them to wherever they were before in the session.

**Comment by jquense** [comment]
It seems like you might want to spend some time learning how the Component system, and api work in React before jumping in and using a third party library. The errors you are posting are indicative of not quite understanding how to use React, which is fine :), but the best solution is probably to sit and study React a bit more first.

In any case here is a code sample of how you us the modal. Anything that goes inside the ModalTrigger, (like a button) will act as the trigger to open the Modal that you provide the trigger.

#### Modal Component
```js
var React = require('react');
var ReactBootstrap = require('react-bootstrap');
var Button = ReactBootstrap.Button
var Modal = ReactBootstrap.Modal;

const LoginModal= React.createClass({
  render() {
    return (
      <Modal {...this.props} title='Modal heading' animation={false}>
        ...login form goes here
        </div>
        <div className='modal-footer'>
          <Button onClick={this.props.onRequestHide}>Close</Button>
        </div>
      </Modal>
    );
  }
});

module.exports = LoginModal
```
#### You can use that Modal Component in other components
```js
var React = require('react');
var ReactBootstrap = require('react-bootstrap');
var ModalTrigger = ReactBootstrap.ModalTrigger;
var Button = ReactBootstrap.Button
var LoginModal = require('./LoginModal')

var ComponentThatOpensTheModal = React.createClass({
  render(){
     return (
       <ModalTrigger modal={<LoginModal/>}>
         <Button bsStyle='primary'>Open login Form</Button>
       </ModalTrigger>
     )
  }
});

**Comment by rahul1346** [comment]
Thanks again --

I think i've almost got it! I'm able to render the modal right when login is clicked and it overlays the app, but now when I press the close button I get following error:

```Uncaught Error: Invariant Violation: React.render(): Invalid component element.```

Here is my LoginModal component:

```
var React = require('react');
var ReactBootstrap = require('react-bootstrap');
var Button = ReactBootstrap.Button;
var Modal = ReactBootstrap.Modal;
var OverlayMixin = ReactBootstrap.OverlayMixin;

// Our custom component is managing whether the Modal is visible
const LoginModal = React.createClass({
  mixins: [OverlayMixin],

  getInitialState() {
    return {
      isModalOpen: false
    };
  },

  handleToggle() {
    this.setState({
      isModalOpen: !this.state.isModalOpen
    });
  },

  render: function () {

    return (
      <Modal title='Modal heading' onRequestHide={this.handleToggle}>
        <div className='modal-body'>
          This modal is controlled by our custom trigger component.
        </div>
        <div className='modal-footer'>
          <Button onClick={this.handleToggle}>Close</Button>
        </div>
      </Modal>
    );
  },

  // This is called by the `OverlayMixin` when this component
  // is mounted or updated and the return value is appended to the body.
  renderOverlay() {
    if (!this.state.isModalOpen) {
      return <span/>;
    }
  }
});

module.exports = LoginModal
```

**Comment by rahul1346** [comment]
Ahhh -- I think I kind of fixed it with componentDidMount, but it's still not doing what I want it to.

The modal populates when I click "Login" but how do I get the page the app was originally on to populate instead of the filler <div>test</div>?

Also, after I close the modal, and click on it again it wont populate, I have to go to another tab and then select login again to get it to populate -- bug or am I doiong something wrong?

Heres the code again:
```
var React = require('react');
var ReactBootstrap = require('react-bootstrap');
var Button = ReactBootstrap.Button;
var Modal = ReactBootstrap.Modal;
var OverlayMixin = ReactBootstrap.OverlayMixin;
var App = require('./App.js');

// Our custom component is managing whether the Modal is visible
const LoginModal = React.createClass({
  mixins: [OverlayMixin],

  handleToggle: function () {
    this.setState({
      isModalOpen: !this.state.isModalOpen
    });
  },

  getInitialState: function() {
    return {
      isModalOpen: false
    };
  },

  componentDidMount: function() {
    this.handleToggle();
  },

  render: function () {
      return (
        <div> test </div>
      );
    },

    // This is called by the `OverlayMixin` when this component
    // is mounted or updated and the return value is appended to the body.
    renderOverlay() {
      if (!this.state.isModalOpen) {
        return <span/>;
      }

      return (
        <Modal title='Modal heading' onRequestHide={this.handleToggle}>
          <div className='modal-body'>
            This modal is controlled by our custom trigger component.
          </div>
          <div className='modal-footer'>
            <Button onClick={this.handleToggle}>Close</Button>
          </div>
        </Modal>
      );
    }
});

module.exports = LoginModal
```

**Comment by aabenoja** [comment]
@rahul1346 I dropped your `LoginModal` into the playground in our docs and I'm not seeing the `Invariant` error you are seeing with and without a `ModalTrigger`.

**Comment by aabenoja** [comment]
Wrong button, sorry :disappointed:

**Comment by rahul1346** [comment]
I am no longer getting the Invariant error. It was due to me changing the renderOverlay to be returned in the render method.

Now i'm having an issue with the current view in the session not populating when the Login button is clicked and the modal populates.

**Comment by aabenoja** [comment]
@rahul1346 Sorry, didn't see your latest post. Playing around with your changes right now.

**Comment by aabenoja** [comment]
@rahul1346 Are you using `ModalTrigger`? If so, controlling the visibility with `isModalOpen` seems unnecessary.

**Comment by rahul1346** [comment]
I am not using ModalTrigger? Should I use that instead? Do they not do the same thing?

I am using react-router to rout the views.

**Comment by aabenoja** [comment]
If you use the `ModalTrigger` for your login button you would not have to handle the modal visibility, as per @jquense's suggestion above. It is much like [this live example from the docs](http://react-bootstrap.github.io/components.html#modals-live). The demo works fine with `react-router`.

Is there a reason to roll your own visibility handling?

**Comment by rahul1346** [comment]
So when I use the ModalTrigger component like so:

```
var React = require('react');
var ReactBootstrap = require('react-bootstrap');
var Button = ReactBootstrap.Button;
var Modal = ReactBootstrap.Modal;
var ModalTrigger = ReactBootstrap.ModalTrigger;

// Our custom component is managing whether the Modal is visible
const LoginModal = React.createClass({

  render: function() {
      return (
        <Modal {...this.props} title='Modal heading' animation={false}>
          <div className='modal-body'>
            <h4>Text in a modal</h4>
            <p>Duis mollis, est non commodo luctus, nisi erat porttitor ligula.</p>

            <h4>Popover in a modal</h4>
            <p>TODO</p>

            <h4>Tooltips in a modal</h4>
            <p>TODO</p>

            <hr />

            <h4>Overflowing text to show scroll behavior</h4>
            <p>Cras mattis consectetur purus sit amet fermentum. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Morbi leo risus, porta ac consectetur ac, vestibulum at eros.</p>
            <p>Praesent commodo cursus magna, vel scelerisque nisl consectetur et. Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor.</p>
            <p>Aenean lacinia bibendum nulla sed consectetur. Praesent commodo cursus magna, vel scelerisque nisl consectetur et. Donec sed odio dui. Donec ullamcorper nulla non metus auctor fringilla.</p>
            <p>Cras mattis consectetur purus sit amet fermentum. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Morbi leo risus, porta ac consectetur ac, vestibulum at eros.</p>
            <p>Praesent commodo cursus magna, vel scelerisque nisl consectetur et. Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor.</p>
            <p>Aenean lacinia bibendum nulla sed consectetur. Praesent commodo cursus magna, vel scelerisque nisl consectetur et. Donec sed odio dui. Donec ullamcorper nulla non metus auctor fringilla.</p>
            <p>Cras mattis consectetur purus sit amet fermentum. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Morbi leo risus, porta ac consectetur ac, vestibulum at eros.</p>
            <p>Praesent commodo cursus magna, vel scelerisque nisl consectetur et. Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor.</p>
            <p>Aenean lacinia bibendum nulla sed consectetur. Praesent commodo cursus magna, vel scelerisque nisl consectetur et. Donec sed odio dui. Donec ullamcorper nulla non metus auctor fringilla.</p>
          </div>
          <div className='modal-footer'>
            <Button onClick={this.props.onRequestHide}>Close</Button>
          </div>
        </Modal>
      );
    }
});

const overlayTriggerInstance = (
  <ModalTrigger modal={<LoginModal />}>
    <Button bsStyle='primary' bsSize='large'>Launch demo modal</Button>
  </ModalTrigger>
);

module.exports = LoginModal
```

I get the following:
```
Warning: Failed propType: Required prop `onRequestHide` was not specified in `Modal`. Check the render method of `LoginModal`.
3main.js:11012 Uncaught TypeError: this.props.onRequestHide is not a function
```

Where is  onRequestHide being passed from?

**Comment by aabenoja** [comment]
`ModalTrigger` passes its hide function to `Modal`, as seen [here on line 50](https://github.com/react-bootstrap/react-bootstrap/blob/f57243d5bab29a71c83d69f79a784849a9aa4b51/src/ModalTrigger.js#L50). Copy-pasting your `LoginModal` and `OverlayInstance` directly into the playground in our docs does not give me any error.

**Comment by AlexKVal** [comment]
I'm closing this.
Feel free to re-open it if you still have problems with the React-Bootstrap library.

**Comment by jareware** [comment]
I'm seeing the `Uncaught TypeError: Cannot read property 'toUpperCase' of undefined` error as well, and I've copy-pasted [this example](http://react-bootstrap.github.io/components.html#modals-live) from the docs to the letter. I'm on `react@0.13.3`, which matches your package.json devDeps.

Vote to re-open.

**Comment by aabenoja** [comment]
@jareware You're also on `v0.24.X`, yes?

**Comment by jareware** [comment]
@aabenoja hmm, as it turns out I'm on `0.23.4`, so I have no right to complain. Sorry about the noise, I'll try the latest!

**Comment by muraveill** [comment]
With react-bootstrap 0.25.2 I am also getting the same 

    Warning: Failed propType: Required prop 'onRequestHide' was not specified in 'Modal'. Check the render method of 'LoginModal'. 
    TypeError: this.props.onRequestHide is not a function`

The trigger:

    <ModalTrigger modal={<MyModal/>}>
                <a>...</a>
    </ModalTrigger>

The modal:

    var MyModal = React.createClass({
        render: function () {
            return (
                <Modal title='1234'>
                    <div className='modal-body'> ... </div>
                    <div className='modal-footer'>
                      <Button onClick={this.props.onRequestHide}>Close</Button>
                    </div>
                </Modal>
            );
        },
    });

(If I remove the button the error persists, as it is an internal call to the same function).
What is wrong ?

**Comment by jquense** [comment]
There is something weird with what is actually installed

there is no ModalTrigger component in 0.25 anymore.

**Comment by muraveill** [comment]
Do you mean it is not usable at the moment ?
This new version, according to the current docs and without the ModalTrigger, still complains about `onRequestHide`:

    var MyModalTrigger = React.createClass({
        getInitialState() {
            return { showModal: false };
        },
        close() {
            this.setState({ showModal: false });
        },
        open() {
            this.setState({ showModal: true });
        },

        render: function () {
            return (
            <div>
                <a  onClick={this.open}>...</a>
                <Modal>
                    <Modal.Header>"asdfasdf"</Modal.header>
                    <Modal.Body>"ffffffff"</Modal.Body>
                    <Modal.Footer>
                      <Button onClick={this.close}>Close</Button>
                    </Modal.Footer>
                </Modal>
            </div>
            );
        },
    });

Actually I get more errors now:

    Warning: React.createElement: type should not be null or undefined. It should be a string (for DOM elements) or a ReactClass (for composite components).
    (3x, for Header, Body, Footer)
    Warning: Failed propType: Required prop `onRequestHide` was not specified in `Modal`. Check the render method of `InspectSamplesModal`.
    Warning: Only functions or strings can be mounted as React components.
    (x2)
    (and then the usual React errors that don't tell you anything useful)

**Comment by jquense** [comment]
No I mean that [ModalTrigger is no longer part of react-bootstrap at all](https://github.com/react-bootstrap/react-bootstrap/tree/v0.25.2/src). If the version you are using has a ModalTrigger then you can't be on version 0.25.2, that is why you get those errors for the Body, Header, etc components, because tehy don't exist. Your install is most likely __stale__ you should remove it completely and reinstall

**Comment by muraveill** [comment]
$ npm uninstall react-bootstrap -g
    unbuild react-bootstrap@0.25.2
    $ npm uninstall react-bootstrap
    unbuild react-bootstrap@0.25.2
    $ npm install react-bootstrap@latest --save
    react-bootstrap@0.25.2 node_modules/react-bootstrap

Same errors.
