### ISSUE TITLE
Add componentClass property to Jumbotron

### ISSUE THREAD

**Issue by lo1tuma** [react-bootstrap/react-bootstrap#878]
Hi,

I would like to see the `componentClass` also in the `Jumbotron` component, to be able to use something different than a `div`.

**Comment by mtscout6** [comment]
Can you provide a little more context as to why you want a different componentClass there? I ask because the existing Jumbotron is following the same standard as documented by Bootstrap at http://getbootstrap.com/components/#jumbotron

**Comment by lo1tuma** [comment]
I would like to use a `section` instead of a `div`.

The bootstrap documentation says nothing about in which tag-combination the `.jumbotron` class can be used. I’m a bit confused: do you only support tag names which are also shown in code examples in the bootstrap documentation?

**Comment by mtscout6** [comment]
Not necessarily I'm mainly trying to understand what exactly is needed. In this case I can see how a section is a reasonable alternative. If you want to draft a PR for this and default it to div that'd be ok.

**Comment by lo1tuma** [comment]
Sure, I’ll make a PR soon.

Thanks.

**Comment by mtscout6** [comment]
Closed by #879
