### ISSUE TITLE
Remove isRequired flag from props with a default value defined

### ISSUE THREAD

**Issue by mtscout6** [react-bootstrap/react-bootstrap#883]
per https://github.com/react-bootstrap/react-bootstrap/pull/879#issuecomment-114482449

/cc @jquense

**Comment by AlexKVal** [comment]
I can tackle with both: this and https://github.com/react-bootstrap/react-bootstrap/issues/884 (will do it as 1.)

If nobody begin with it already ?

**Comment by mtscout6** [comment]
No one's assigned to it yet!

**Comment by AlexKVal** [comment]
You wrote `/cc @jquense` so I thought he will do it.

I'm taking two.
