### ISSUE TITLE
Correct the propTypes for componentClasses that are using node currently.

### ISSUE THREAD

**Issue by mtscout6** [react-bootstrap/react-bootstrap#884]
per https://github.com/react-bootstrap/react-bootstrap/pull/879#issuecomment-114482449

Two options:

1. Add `ComponentClass` property to `CustomPropTypes` and use that everywhere that we use node for `componentClass` now.
2. Use `PropTypes.oneOf([PropTypes.string, PropTypes.func])` everywhere that we use node for `componentClass` now.

I prefer option 1.

/cc @jquense

**Comment by jquense** [comment]
I like option 1 two,  since it's really just option 2 but with the possibility for better errors. we can snag the one I use in React widgets if that's helpful.

**Comment by AlexKVal** [comment]
I'll shamelessly borrow your code :smiling_imp:

**Comment by mtscout6** [comment]
Another good reason to get that react-prop-types repo up and running if it's used in more projects. :wink:

**Comment by mtscout6** [comment]
Ah #782 forgot there was still an open issue for that.
