### ISSUE TITLE
Maximum call stack size exceeded error when I'm trying to create Modal using ModalTrigger in another Modal

### ISSUE THREAD

**Issue by limpbrains** [react-bootstrap/react-bootstrap#893]
Works fine on 0.23.3 version
https://jsfiddle.net/x9pzkz67/5/
```javascript
var Modal = ReactBootstrap.Modal;
var ModalTrigger = ReactBootstrap.ModalTrigger;
var Button = ReactBootstrap.Button;


var Modal2 = React.createClass({
  render: function() {
    return (
      <Modal title='Modal2' animation={false}>
          modal2
      </Modal>
    )
  }
});

var Modal1 = React.createClass({
  render: function() {
    return (
      <Modal title='Modal1' animation={false}>
          <ModalTrigger modal={<Modal2 />}>
              <Button>show modal2</Button>
          </ModalTrigger>
      </Modal>
    )
  }
});

var Hello = React.createClass({
    render: function() {
        return (
            <div>
                <ModalTrigger modal={<Modal1 />}>
                  <Button>modal1</Button>
                </ModalTrigger>
            </div>
        );
    }
});
 
React.render(<Hello name="World" />, document.getElementById('container'));
```

**Comment by jquense** [comment]
stackable modals is not supported by bootstrap by default, so have two open at the same time is creating a loop where they are each trying to maintain focus on themselves.

You can try to workaround this by setting `enforceFocus` prop on the bottom Modal to `false`.

On our end we should probably try and prevent it from breaking at least, bootstrap does this, by making use of jquery event namespaces which we don't have, so its a bit tricky (and why its not there now)

**Comment by AlexKVal** [comment]
For those who will tackle with this
For refs: https://github.com/react-bootstrap/react-bootstrap/issues/903#issuecomment-115866059

**Comment by AlexKVal** [comment]
Pull requests are welcome :wink:
