### ISSUE TITLE
React-Bootstrap video tutorial from easydevtuts

### ISSUE THREAD

**Issue by AlexKVal** [react-bootstrap/react-bootstrap#907]
It seems this guy is filling out gaps with tutorials for R-B :+1: 
http://easydevtuts.com/react-bootstrap-tutorial/
https://www.youtube.com/watch?v=Ob6xHzmTpig 1
https://www.youtube.com/watch?v=AmjUwPbnAjk 2
https://www.youtube.com/watch?v=68R49mrRjS4 3
https://www.youtube.com/watch?v=ZHU95MQDMZ4 4

I propose to add a link to this tutorial to the Readme, Starting and Intro pages.

**Comment by yordis** [comment]
:+1: Thanks
