### ISSUE TITLE
Put npm version in AppVeyor back to "latest" when 2.12.1 is released

### ISSUE THREAD

**Issue by AlexKVal** [react-bootstrap/react-bootstrap#911]
https://github.com/react-bootstrap/react-bootstrap/pull/910

**Comment by jquense** [comment]
should be released no? I have 2.12.1 installed on my machine from npm

**Comment by mathieumg** [comment]
Doesn't seem like it's been published? https://www.npmjs.com/package/npm It's tagged as a prerelease on GitHub as well.

**Comment by jquense** [comment]
its definitely published ...`npm i -g npm@2.12.1` worked for me just fine. It may not be tagged as latest tho...

**Comment by mathieumg** [comment]
Oh, yeah. And the npm website probably shows the version tagged as latest as well.
