### ISSUE TITLE
Modal controlled by 'svg' element, when closing gets "no method 'focus'" error from 'restoreLastFocus()'

### ISSUE THREAD

**Issue by felix-d** [react-bootstrap/react-bootstrap#917]
Updated **react-bootstrap** from `^0.22.6` to `^0.23.5` and now get this error.

     TypeError: Object [ DIV#Test.Test.modal.fade ] has no method 'focus'
        at focusModalContent (node_modules/react-bootstrap/lib/Modal.js:314:20)

**Comment by jquense** [comment]
Hi here,

can you provide a bit more context here for what you are doing and what the code looks like that triggers this error?

**Comment by oosthoek** [comment]
Hello,

I also have this same error.  i am using IE11, which does not support .focus() on svg elements.

**Comment by jquense** [comment]
I still don't really have enough info here...the original error posted is of the bootstrap controlled div not having a focus method, which is really odd b/c divs have focus methods. @oosthoek I am not sure where svg is coming from the modal doesn't render any svg elements, so you might be having a different error.

**Comment by oosthoek** [comment]
I'm sorry I'll be more specific.  I have a svg element and when you click on it it opens a modal. when i try to close the modal i get the error from above which is from the restoreLastFocus function in Modal.js.  this function calls .focus() on the element that had the focus before hand.  I was able to temporarily fix this problem by setting the focus to a non svg element before i open the modal.

Hope that was more clear.

**Comment by jquense** [comment]
Ok that makes more sense, definitely a bug.
