### ISSUE TITLE
textarea's value change to old value when the modal hide.

### ISSUE THREAD

**Issue by snadn** [react-bootstrap/react-bootstrap#920]
I have a textarea in a modal. if the default value is `a` and i change it to `b`.when the modal hide,the value of textarea become to `a`.

I found that in 'FadeMixin.js', it use `.cloneNode(true)` to get a mirror element, but textarea can not get the new value by this.

**Comment by dozoisch** [comment]
Is your input controlled or not? Can you share a snippet that shows that issue?

**Comment by AlexKVal** [comment]
Superceded by #921

**Comment by Vyprichenko** [comment]
Seems to me I have quite similar issue: for some reason form in modal is recreated (getInitialState method is called) every time when modal is reopened.
Here is an example: http://jsfiddle.net/v5wzkr7e/6/

**Comment by jquense** [comment]
that makes  actually makes sense because the modal unmounts and mounts its content on show and hide.

**Comment by Vyprichenko** [comment]
Unfortunately it makes almost impossible to place components with complex forms in modals, because user will loss all input on casual close.
I see that I'll have to store my form's and modal's states both in common parent, but initially I intended to keep them separated.

**Comment by jquense** [comment]
I mean that's just sort of how modals work... if you want to avoid casual closes, then set the backdrop to static and check if the form has been saved before allowing it to be closed. similar to avoiding accidental page navigations. that's the better UX pattern anyway :)

**Comment by Vyprichenko** [comment]
I've ended up with combined modal + form component containing state of it's children, which probably is better solution in terms of React: http://jsfiddle.net/v5wzkr7e/8/

Real form is quite big and it doesn't have to be filled at once — user is free to work with another parts of page and then go back to the form. I don't have any other reasons to interfere in user's interaction with such a pretty Modal, which is so exciting to open and close  : )

Also static backdrop can be useful in another conditions, thank you.

**Comment by taion** [comment]
Yes, that's about the right approach for persistence - something Flux-like or whatever.
