### ISSUE TITLE
Show icon for DropdownButton 

### ISSUE THREAD

**Issue by bachirelkhoury** [react-bootstrap/react-bootstrap#928]
Is there any way we can use icons with the DropdownButton & MenuItem?
Trying to make this code:

    <DropdownButton eventKey={3} title='Dropdown'>
        <MenuItem eventKey='1'>Action</MenuItem>
        <MenuItem eventKey='2'>Another action</MenuItem>
        <MenuItem eventKey='3'>Something else here</MenuItem>
        <MenuItem divider />
        <MenuItem eventKey='4'>Separated link</MenuItem>
      </DropdownButton>

look like this (taken from sb-admin-2 dashboard template):
![screen shot 2015-07-01 at 2 50 49 pm](https://cloud.githubusercontent.com/assets/186698/8447783/76c5c730-2001-11e5-8604-6a80d5c2f23a.png)

code for that:

    <li className="dropdown">
      <a className="dropdown-toggle" data-toggle="dropdown" href="#">
          <i className="fa fa-user fa-fw"></i> <i className="fa fa-caret-down"></i>
      </a>
      <ul className="dropdown-menu dropdown-user">
          <li><a href="#"><i className="fa fa-user fa-fw"></i> User Profile</a>
          </li>
          <li><a href="#"><i className="fa fa-gear fa-fw"></i> Settings</a>
          </li>
          <li className="divider"></li>
          <li><a href="login.html"><i className="fa fa-sign-out fa-fw"></i> Logout</a>
          </li>
      </ul>
    </li>

**Comment by bachirelkhoury** [comment]
Icons do work inside MenuItem, question is how to show an icon to the DropdownButton?

    <Navbar brand='React-Bootstrap'>
          <Nav right eventKey={0}>
            <NavItem eventKey={1} href='#'><i className="fa fa-envelope fa-fw"></i>Link</NavItem>
            <NavItem eventKey={2} href='#'>Link</NavItem>
            <DropdownButton eventKey={3} title='Bootstrap'>
              <MenuItem eventKey='1'><i className="fa fa-envelope fa-fw"></i> User Profile</MenuItem>
              <MenuItem eventKey='2'><i className="fa fa-gear fa-fw"></i> Settings</MenuItem>
              <MenuItem divider />
              <MenuItem eventKey='3'><i className="fa fa-sign-out fa-fw"></i> Logout</MenuItem>
            </DropdownButton>
          </Nav>
        </Navbar>

![screen shot 2015-07-01 at 3 14 30 pm](https://cloud.githubusercontent.com/assets/186698/8447957/eef1863e-2003-11e5-8ffb-3b6891c7db73.png)

**Comment by mathieumg** [comment]
`title` accepts any React `node`:

```js
<Navbar brand='React-Bootstrap'>
  <Nav right eventKey={0}>
    <NavItem eventKey={1} href='#'><i className="fa fa-envelope fa-fw"></i>Link</NavItem>
    <NavItem eventKey={2} href='#'>Link</NavItem>
    <DropdownButton 
      eventKey={3} 
      title={
        <span><i className="fa fa-user fa-fw"></i> Bootstrap</span>
      }
    >
      <MenuItem eventKey='1'><i className="fa fa-envelope fa-fw"></i> User Profile</MenuItem>
      <MenuItem eventKey='2'><i className="fa fa-gear fa-fw"></i> Settings</MenuItem>
      <MenuItem divider />
      <MenuItem eventKey='3'><i className="fa fa-sign-out fa-fw"></i> Logout</MenuItem>
    </DropdownButton>
  </Nav>
</Navbar>
```

**Comment by bachirelkhoury** [comment]
YES!!! thanks @mathieumg !!

**Comment by bennidi** [comment]
Great! This comes in very handy. I would have missed this entirely if it were not for this issue. I was looking at NavDropdown and did not understand that it seems to be an alias to DropDownButton? Anyways, NavDropdown props table seems to be missing in documentation. Would be great to have a hint there.

**Comment by seminull** [comment]
I'm getting the good old unknown props message now from this, any workarounds?

>  Unknown props `activeKey`, `activeHref` on <button> tag. Remove these props from the element.

**Comment by vincent714** [comment]
@mathieumg thanks. this way works for me.

**Comment by pierre-H** [comment]
With TypeScripts the NavDropdown  title is defined as `string | undefined` but I don't know where to edit it.
It's from @types/react-bootstrap

**Comment by kunal-mandalia** [comment]
> title accepts any React node

needs to be in docs! If nobody else jumps on it I might send a pr when I get time later

**Comment by taion** [comment]
It is in the docs just fine:

![image](https://cloud.githubusercontent.com/assets/3112159/22177530/c62c59e4-dfed-11e6-8349-3bf1eb0f8405.png)

**Comment by kunal-mandalia** [comment]
@taion you're right for Dropdown, I didn't see NavDropdown in the docs which is what I'm using, so note to anyone else using NavDropdown you can provide a react node as title to it too.

**Comment by RainbowRambo** [comment]
Curious how to change the dropdown icon when it is clicked. I dont know where to put the ternary operator to change the icon S: because the title only has title 
`
<NavDropdown eventKey={3} title="Dropdown" id="basic-nav-dropdown">
          ...
          </NavDropdown>`

**Comment by Khushi24699** [comment]
> Curious how to change the dropdown icon when it is clicked. I dont know where to put the ternary operator to change the icon S: because the title only has title
> ` <NavDropdown eventKey={3} title="Dropdown" id="basic-nav-dropdown"> ... </NavDropdown>`

please share the solution for this if you got one

**Comment by presencewebdesign** [comment]
Can do it like this with react icons

import { BsTools } from "react-icons/bs"

<NavDropdown
              title={
                <span>
                  <BsGrid size="25" /> Items
                </span>
              }
            >

**Comment by xxio0014** [comment]
First, dispaly none for the origin css style like below
.dropdown-toggle::after{
    display: none;
}.
Then, enclose an object as title property, below.
<NavDropdown title={<>Fauna Search <FontAwesomeIcon icon={faCaretDown} flip /></> } />
I am using FontAwesome icon, I use a <></> to enclose the title.

**Comment by xxio0014** [comment]
First, dispaly none for the origin css style like below
.dropdown-toggle::after{
display: none;
}.
Then, enclose an object as title property, below.
 <NavDropdown title={<>Fauna Search <FontAwesomeIcon icon={faCaretDown} flip /></> >
I am using FontAwesome icon, I use a <></> to enclose the title.
