### ISSUE TITLE
How to collapse the CollabibleNav after click?

### ISSUE THREAD

**Issue by barrystaes** [react-bootstrap/react-bootstrap#934]
The CollapsibleNav element shows a nice responsive menu, phones get the hamburger button to expand it to a vertical menu list.
But after clicking an item in that list, it does not collapse back to a hamburger button.

This is my code:
```js
return (
  <Navbar brand={logo} toggleNavKey={0} fluid inverse fixedTop>

    <CollapsibleNav eventKey={0}>
      {loggedin ?
        <Nav navbar>
          <NavItemLink eventKey={1} to="dashboard"><Glyphicon glyph="dashboard"/> Displays</NavItemLink>
          <NavItemLink eventKey={2} to="book"><Glyphicon glyph="book"/> Books</NavItemLink>
          <NavItemLink eventKey={3} to="film"><Glyphicon glyph="film"/> Movies</NavItemLink>
        </Nav>
      : null}
      {loggedin ?
        <Nav navbar right>
          {projectsDropdown}
          <NavItemLink eventKey={4} to="me"><Glyphicon glyph="user"/> {username}</NavItemLink>
        </Nav>
      :
        <Nav navbar right>
          <NavItemLink eventKey={5} to="login"><Glyphicon glyph="user"/> Login</NavItemLink>
        </Nav>
      }

    </CollapsibleNav>
  </Navbar>
);
```

I tried looking at how the react-bootstrap website (its built in React) does this with Chrome Inspector, but it turns out it does not use `CollapsibleNav` and perhaps just happens to work because of the page reload..

How to do this?

**Comment by AlexKVal** [comment]
The problem is in that on the http://react-bootstrap.github.io/components.html#navbars
`Mobile Friendly (Multiple Nav Components)` section
there `<DropdownButton />` used.

Alas, it's notorious with its problems list: :sweat: 
https://github.com/react-bootstrap/react-bootstrap/issues/526 and is in progress of fixing. :sparkle: 

:cherries:

**Comment by barrystaes** [comment]
For posterity - a workaround was posted here: https://github.com/react-bootstrap/react-router-bootstrap/issues/112#issuecomment-142599003

**Comment by MichelFloyd** [comment]
For future visitors, you can skip all the annoying workarounds by just specifying `<Navbar collapseOnSelect>`

**Comment by barrystaes** [comment]
@MichelFloyd Thanks. To add on that, `collapseOnSelect` that should work in [react-bootstrap 0.30.6](https://github.com/react-bootstrap/react-bootstrap/blob/master/CHANGELOG.md#v0306) and up.

**Comment by CoreyWarren** [comment]
> For future visitors, you can skip all the annoying workarounds by just specifying `<Navbar collapseOnSelect>`

Awesome. Still need to figure out how to handle onClick events with the Dropdown Menu, but at least this issue is solved.
