### ISSUE TITLE
Coveralls dropped from 82% > 78%

### ISSUE THREAD

**Issue by AlexKVal** [react-bootstrap/react-bootstrap#936]
https://coveralls.io/r/react-bootstrap/react-bootstrap
I'm not sure that it is an issue, but just wanted to point out.

<img width="814" alt="screen shot 2015-07-03 at 7 35 48 pm" src="https://cloud.githubusercontent.com/assets/847572/8502845/98f266c4-21be-11e5-867e-d58a1de4e702.png">

here is the downgrade
<img width="811" alt="he" src="https://cloud.githubusercontent.com/assets/847572/8502849/a2f5c2ec-21be-11e5-8298-ddc8934905b1.png">

**Comment by krzysiek1507** [comment]
@AlexKVal [here](https://coveralls.io/r/react-bootstrap/react-bootstrap?branch=master&page=2) build 1878

**Comment by AlexKVal** [comment]
Thank you @krzysiek1507. 
I just wanted to save screenshot because after some builds / commits, this link becomes wrong.
