### ISSUE TITLE
Use CustomPropTypes from react-prop-types

### ISSUE THREAD

**Issue by AlexKVal** [react-bootstrap/react-bootstrap#937]
https://github.com/react-bootstrap/react-prop-types

I'm on it, but before `react-prop-types` has to be released on npmjs.

--
backport [new custom validators](https://github.com/react-bootstrap/react-bootstrap/pull/1096/files#diff-6e40506f419cfbb5c93d15e804cc90fdR47) `requiredRoles(...roles)` and `exclusiveRoles(...roles)`

Update: `requiredRoles` `exclusiveRoles` are specific for `R-B` project. (e.g. `bsRole` property), hence it is not necessary to backport them.

**Comment by AlexKVal** [comment]
Because now `utils/CustomPropTypes` is public API [src/utils/index.js#L10](https://github.com/react-bootstrap/react-bootstrap/blob/d105749b0a48fdb8976405f6e0648e85c286d788/src/utils/index.js#L10)
it seems it needs to be first deprecated in 0.24 and only in 0.25 it can be removed and https://github.com/react-bootstrap/react-prop-types could be used instead.
Right ?

**Comment by mtscout6** [comment]
My understanding of the new rule: https://github.com/react-bootstrap/react-bootstrap/blob/v0.24-rc/CONTRIBUTING.md#breaking-changes

The deprecation warning should not land till 0.25, and the removal in 0.26. So essentially patch releases should just be bug fixes and new features. So from what I understand our users would not see new deprecation warnings until the next minor release.

**Comment by taion** [comment]
On second thought, it might make sense to defer that rule - it's actually a decent amount of work to merge in and validate a bunch of changes, quite a lot more than I thought it'd be. Maybe just quietly delete that part until/unless we get better at releasing minor versions more quickly.

**Comment by mtscout6** [comment]
I think that as we start following that on weeks with active development we could push for a minor release every two weeks. Instead of holding off for so long.

**Comment by mtscout6** [comment]
Lean on the fact that Semver describes what's happening. If we reach a minor version over 150 (arbitrary number) before we release 1.0.0 I don't think it matters.

**Comment by AlexKVal** [comment]
Let's continue this in gitter for maintainters.

**Comment by AlexKVal** [comment]
Updated topic about backporting new custom validators introduced in #1096
Just not to forget.

**Comment by AlexKVal** [comment]
This is resolved by #1223
