### ISSUE TITLE
Close an overlay/popover from within

### ISSUE THREAD

**Issue by bsr203** [react-bootstrap/react-bootstrap#938]
Hello,
I have been waiting for the overhaul of overlays to land, but still couldn't make below to work.

I am in need of displaying some data in a popover when clicking on a table cell ([fixed data table](https://github.com/facebook/fixed-data-table))

this works beautifully like in this [fiddle ](https://jsfiddle.net/7gqj6zgz/3/)

Now, I need to cancel this popover/overlay through a button inside this popover. As my understanding, this may not be possible with `OverlayTrigger` hence I tried using `Overlay`. But the issue is positioning. As I see, the overlay is position based on the parent and [may not be able to show the full overlay with fixed position alone as the overlay is limited to the size of the cell](https://css-tricks.com/almanac/properties/z/z-index/). In my local setup, I can see the popover hides behind the cell.

so, I may have to make use of new utils/Position component, which make use of `overlayPositionUtils` to position the overlay if it is not attached to the parent (may be to document.body). I couldn't get it to work in the fiddle http://jsfiddle.net/7gqj6zgz/2/ .

so, the requirement is a popover which can be cancelled from a button inside.`rootClose` is not enough as I need to programmatically able to close this (may be through props). A `modal` may work if I can position like a popover just below the target.

what is the best way to do this?

thanks.

cc @jquense

**Comment by taion** [comment]
`onRequestHide` (function) gets injected as a prop into the `Popover`. Just call it to hide the popover from within.

**Comment by bsr203** [comment]
I couldn't this prop injected. Can you please make it work in this fiddle

https://jsfiddle.net/7gqj6zgz/4/

**Comment by AlexKVal** [comment]
As I can see this is not a trivial task and needs an expert to find out a solution.
It seems @jquense and @taion are ones who know well `Overlay` and `OverlayTrigger` mechanic.

**Comment by jquense** [comment]
Here is how I would do it, not knowing anything about FixedDataTable: https://jsfiddle.net/7gqj6zgz/5/

**Comment by AlexKVal** [comment]
Cool. :sparkle: 
@bsr203 does it help you ?

**Comment by bsr203** [comment]
Thanks guys for all the help. I thought `container` was a requirement, and caused my overlay to be contained within it. @jquense looks great, and working in the fiddle. thanks a ton.
