### ISSUE TITLE
Formatting issue with component wrapping DropdownButton

### ISSUE THREAD

**Issue by pealmeid** [react-bootstrap/react-bootstrap#943]
I am trying to create a component that wraps a `DropdownButton`:

    class MyDropdown extends React.Component {
    	render() {
            return(
        		<DropdownButton title='My Dropdown'>
        			<MenuItem>Action</MenuItem>
		        </DropdownButton>
    		);
    	}
    }

However, when I use it inside a `Navbar` it doesn’t render using the same CSS formatting as a “regular” `DropdownButton`.

The code below displays a “regular” `DropdownButton` alongside a `MyDropdown`. The difference between the two components can be seen [here][1]:

    class MyHeader extends React.Component {
	    render() {
		    return(
        		<Navbar brand='Example' fixedTop fluid>
	        		<Nav>
		        		<NavItem href='#'>Link</NavItem>
    			    	<DropdownButton title='Dropdown'>
    	    				<MenuItem>Action #1.1</MenuItem>
         				</DropdownButton>
        				<MyDropdown />
        			</Nav>
        		</Navbar>
    		);
    	}
    }

----------
Is this a bug/issue, or am I doing something wrong? What’s the recommended way to wrap a `DropdownButton` so this doesn’t happen?

Thanks in advance.

  [1]: http://i.stack.imgur.com/fh1n4.jpg

**Comment by AlexKVal** [comment]
We definitely need the `DropdownButton` fixed :smile: https://github.com/react-bootstrap/react-bootstrap/issues/526

**Comment by pealmeid** [comment]
This might help someone else: I discovered a workaround (or maybe an undocumented feature) for my issue. If I add a `navItem='true'` attribute to the `DropdownButton` and wrap it inside a `<li className='dropdown'>` it renders as expected:

    class MyDropdown extends React.Component {
	    render() {
		    return(
    		    <li className='dropdown'>
			    <DropdownButton title='My Dropdown' navItem='true'>
				    <MenuItem>Action #2.1</MenuItem>
   			    </DropdownButton>
		    </li>
		    );
	    }
    }

Regards.

**Comment by AlexKVal** [comment]
Thank you @pealmeid for sharing workaround :cherries: 

@mtscout6 should we add this solution as ref to 526 ?

**Comment by mtscout6** [comment]
It's something I've already accounted for in #526, I just need to finish up work on the SplitButton and update docs then I'll be done with it.
