### ISSUE TITLE
asterisk and plus glyphicons not rendering

### ISSUE THREAD

**Issue by goffreder** [react-bootstrap/react-bootstrap#944]
It looks like asterisk and plus glyphicons are not rendering properly:

![schermata 2015-07-06 alle 11 27 14](https://cloud.githubusercontent.com/assets/156642/8519296/03d2cb0e-23d2-11e5-86e7-42e98638a9fe.png)

Those two are the only icons that have problems, with all other icons I've tried everything was ok. This is my code:
```jsx
<Button>
    <Glyphicon glyph="asterisk" />{" "}
    asterisk
</Button>{" "}
<Button>
    <Glyphicon glyph="plus" />{" "}
    plus
</Button>{" "}
<Button>
    <Glyphicon glyph="euro" />{" "}
    euro
</Button>{" "}
<Button>
    <Glyphicon glyph="eur" />{" "}
    eur
</Button>{" "}
<Button>
    <Glyphicon glyph="minus" />{" "}
    minus
</Button>
```

Am I missing something?

**Comment by taion** [comment]
I'm not seeing any issues here. It works fine on the component page playground for me. Are you using a correct version of Glyphicons?

**Comment by AlexKVal** [comment]
There is no bug in the current version of R-B. I'm closing it. :sparkle: 

If you still have the issue, please post steps to reproduce your problem and we will re-open it.
:cherries:
