### ISSUE TITLE
Bug with docs-props generation

### ISSUE THREAD

**Issue by AlexKVal** [react-bootstrap/react-bootstrap#948]
With #947
I've hit into this bug:
<img width="877" alt="screen shot 2015-07-06 at 6 25 29 pm" src="https://cloud.githubusercontent.com/assets/847572/8526079/0bab4d8e-240d-11e5-9d84-edc2e1950a8e.png">

**Comment by jquense** [comment]
do you have any idea if its a bug in the scripts in this repo, or if its coming out of `react-component-metadata` module wrong?

**Comment by AlexKVal** [comment]
I can take a look into this but it is not today already.
My appointer said just now that it is the end of the working day for me :smile:

**Comment by taion** [comment]
I'm not seeing this in the generated docs. Something random?

**Comment by jquense** [comment]
if we are lucky it was a bug in the parser I fixed inadvertently :P

**Comment by AlexKVal** [comment]
You can see even on the site: http://react-bootstrap.github.io/components.html#grids-props-col
<img width="742" alt="screen shot 2015-08-11 at 6 07 06 pm" src="https://cloud.githubusercontent.com/assets/847572/9201081/d9c5f450-4053-11e5-99ee-22e9cecc08cf.png">

@jquense sorry :stuck_out_tongue_winking_eye:

**Comment by jquense** [comment]
hmm that seems like it might be a bug much deeper, babel seems to be reporting the wrong start/end col for the source file so its slicing the wrong 5 chars from the raw source string...I don't seem to be able to recreate this tho in the project itself.

**Comment by taion** [comment]
Still broken.

**Comment by taion** [comment]
The bug's probably still there, but the problem went away... probably because we now use `defaultPropDescriptions` for `componentClass`.
