### ISSUE TITLE
Missing support for Button sizes

### ISSUE THREAD

**Issue by chrisvfritz** [react-bootstrap/react-bootstrap#952]
[Bootstrap supports button sizes](http://getbootstrap.com/css/#buttons-sizes), but the Button component doesn't. Can we add a `bsSize` prop?

**Comment by jquense** [comment]
I think you may have jsut missed it in the docs, or maybe I am misunderstanding. Here are the docs for button sizes: http://react-bootstrap.github.io/components.html#buttons-sizes

**Comment by chrisvfritz** [comment]
Ahh, when I tried `bsSize` with "xs" and it didn't work, I went straight to the source of `Button` and didn't see "bsSize" or "xs" anywhere, so assumed it was unimplemented. I'll close this, but I definitely don't like the changed names of Bootstrap's sizes. While I'm generally in favor of clearer, longer names, this inconsistency seems like it would only trip people up, so that they *have* to make a trip to the docs.
