### ISSUE TITLE
Modal custom close button

### ISSUE THREAD

**Issue by BurntCaramel** [react-bootstrap/react-bootstrap#956]
It would be great to be able to use a custom close button for Modal instead of being forced to use this markup:
```
<button type="button" className="close" aria-hidden="true" onClick={this.props.onRequestHide}>&times;</button>
```

Possibly closeButton could accept both a boolean and a react component? Or whatever API is elegant.

**Comment by AlexKVal** [comment]
For those who wish to tackle with it: 
it's here [src/ModalHeader.js#L14](https://github.com/react-bootstrap/react-bootstrap/blob/27d3e5d6e7ea0714ac317b7d851cc87cbea6bebc/src/ModalHeader.js#L14)

--
We are working on getting through the backlogged tickets, but are short on time. 
If anyone is interested and would like to help out we are very open to pull requests :sparkle:

**Comment by BurntCaramel** [comment]
I can give it a go. What do you think an elegant API should be? Could the *closeButton* prop be both a boolean and react element? Or would they need to be separate?

**Comment by BurntCaramel** [comment]
Or maybe a *closeButtonContent* prop could be added – the button itself is fine, it’s just the <span> inside that would be nice to customise. Although the marginTop on the <button> is a bit funky.

**Comment by jquense** [comment]
I think your thought of doing a bool or element would work great. it also may just be better to pull it out of the header component completely and add a Modal.Close like Modal.Title. give whatever a shot and people can weigh in :)

**Comment by taion** [comment]
:+1: to either bool or element for the same prop.

**Comment by BurntCaramel** [comment]
I have created a pull request: #979

**Comment by hedgerh** [comment]
Resolved https://github.com/react-bootstrap/react-bootstrap/pull/979 ?

**Comment by taion** [comment]
@hedgerh Thanks! Per #979 this is now resolved.
