### ISSUE TITLE
Setting TabbedArea 'id' prop results in id used multiple times in output markup

### ISSUE THREAD

**Issue by michaeljones** [react-bootstrap/react-bootstrap#957]
### Steps to reproduce:
1. Use `TabbedArea` component with `id` set:

    ```
        var tabArea = (
                <TabbedArea
                    id="analytics-tabs">
                    {tabPanes}
                </TabbedArea>
            );
    ```
2. Examine output HTML

### Expected result:

The `id` value is only used for one element in the HTML.

### Actual result:

The `id` value appears on a `nav` element, a `ul` element and the `div.tab-content` element.

### Notes

I am trying to apply particular styles to the tab-content part of a TabbedArea setup. I'd like to introduce a custom class to target it more specifically but I can't see a way to achieve but it seems to be possible to set the 'id' for the TabbedArea but this hasn't behaved as I expected.

I am not a CSS expert but I think ids should only appear once. Sorry if I'm wrong on that. Even if I am it might be worth having suffixes or something to help distinguish between the various elements.

Loving the project,
Michael

**Comment by jquense** [comment]
what version are you using? this was fixed recently I believe

**Comment by michaeljones** [comment]
I am sorry. You are right. I was on 0.23.3. I've updated and it works as I expected.

Sorry the trouble!
Michael

**Comment by AlexKVal** [comment]
Anyway @michaeljones thank you for such lovely written issue with steps to reproduce :+1:  :cherries:
