### ISSUE TITLE
Unexpected Popover dismissal animation position if the component is not the first child in the DOM tree

### ISSUE THREAD

**Issue by hwen3** [react-bootstrap/react-bootstrap#958]
So what I have is the Reactbootstrap's demo code:
```js
    const Example = React.createClass({
      getInitialState(){
        return { show: true };
      },
      toggle(){
        this.setState({ show: !this.state.show });
      },
      render(){
        return (
          <div style={{position: 'relative' }}>
            <button ref='target' onClick={this.toggle}>
              I am an Overlay target
            </button>

            <Overlay
              show={this.state.show}
              onHide={() => this.setState({ show: false })}
              placement="bottom"
  	      rootClose={true}
              container={this}
              target={ () => React.findDOMNode(this.refs.target)}>
              <Popover title='Popover bottom'>
                <strong>Holy guacamole!</strong> Check this info.
              </Popover>
            </Overlay>
          </div>
        );
      }
    });
```
and my main app render looks like this:
```js
    render() {
        return (
           <div>
            <button />
            <Example />
           </div>);
    }
```
once the Overlay's show prop changes from true to false, it first disappear, then the Popovers's fadeout animation occurs. However, the position of the Popover is shifted unexpectedly. See below:

![Alt Text](http://i.imgur.com/w38g3S6.gif)

**Comment by taion** [comment]
Hmm, with your code, I'm actually seeing something different, where the fade-out animation doesn't play at all, which seems incorrect. @jquense ?

**Comment by jquense** [comment]
im not sure it may be due to a few of the typos in the Position Component which were fixed recently (unreleased).

**Comment by AlexKVal** [comment]
I reproduced your example on our docs-site playground here
http://react-bootstrap.github.io/components.html#popovers-in-container
and it works fine :sparkle: 
<img width="488" alt="screen shot 2015-07-12 at 2 52 37 pm" src="https://cloud.githubusercontent.com/assets/847572/8637662/1490c65c-28a6-11e5-8556-e7410df0fd6c.png">


You can copy / past the following snippet of the code there and check it too.
```js
class Example extends React.Component {
  constructor(props, context){
    super(props, context);
    this.state = { show: false };
  }
  render(){

    return (
      <ButtonToolbar>
        <Button
          bsStyle='default'
          onClick={e => this.setState({ target: e.target, show: !this.state.show })}
        >
          Holy guacamole!
        </Button>

        <Overlay
          show={this.state.show}
          target={()=> React.findDOMNode(this.state.target)}
          placement='bottom'
          container={mountNode}
          containerPadding={20}
        >
          <Popover title='Popover bottom'>
            <strong>Holy guacamole!</strong> Check this info.
          </Popover>
        </Overlay>
      </ButtonToolbar>
    );
  }
}

const Test = React.createClass({
  render(){
    return (
      <div>
        <button>testing</button>
        <Example />
      </div>
    );
  }
});

React.render(<Test/>, mountNode);
```

The docs-site uses the latest code-base from `master` branch.
It seems your problem can be in connection with some late fixes
as @jquense has noted.

@hwen3 Could you check please your case with the latest version from `master` branch ?

**Comment by hwen3** [comment]
Hey Alex, thanks for the reply. Regarding your code, i see that you are setting mountNode as the container for the overlay which I am unsure of how to go about it with my code since my renders are all in different files. What I would like to know is what happens if you set the container to be "this" instead. I would like to wait for react-bootstrap to be updated on npm first. But, I can try to load the lastest master branch code if necessary.

**Comment by jquense** [comment]
if you set container to 'this' it will use the DOM node of that Component. eg. `findDOMNode(this)`

**Comment by hwen3** [comment]
Right. But is that similar to how Alex used mountNode?

**Comment by jquense** [comment]
yeah it is. in general tho there is no need to set container, it will just use the document body by default which is probably the safest option unless you need the pop to be appended to a different container.

**Comment by hwen3** [comment]
Ah ok thanks for the info. If that's the case then it most likely is fixed. I'll close it issue once I get a chance to verify it.

**Comment by hwen3** [comment]
verified fixed in 0.23.7

**Comment by taion** [comment]
Do you have a repro that exhibits this problem on one of the code playgrounds in the component page?

We've also refactored how transitions and positioning works in v0.24 pretty heavily, so worth checking to see if anything has changed against the newest release.

**Comment by AlexKVal** [comment]
@hwen3 if you still expirience this problem with the latest version, feel free to reopen :cherries:
