### ISSUE TITLE
ButtonInput fails with 'Uncaught TypeError'

### ISSUE THREAD

**Issue by pealmeid** [react-bootstrap/react-bootstrap#959]
I'm getting the following warning/errors whenever I try to use `ButtonInput`:

![error](https://cloud.githubusercontent.com/assets/6384219/8557245/6ffcb08c-24d2-11e5-94db-b122b38f56e9.jpg)

It's happening even if I try to render a very simple form. Code below:

	var React = require('react');
	var ReactBootstrap = require('react-bootstrap');

	var Input = ReactBootstrap.Input;
	var ButtonInput = ReactBootstrap.ButtonInput;

	const MyForm = React.createClass({
	  render() {
		return (
		<form>
		  <Input type="text" />
		  <ButtonInput type="submit">Submit</ButtonInput>
		</form>
		);
	  }
	});

	React.render(<MyForm />, document.getElementById('issue-test'));

Thanks.

**Comment by pealmeid** [comment]
Also, please note that same code works when used on the Components documentation page:

![react](https://cloud.githubusercontent.com/assets/6384219/8557708/85895fb0-24d5-11e5-8351-7e6eb089043f.jpg)

**Comment by dozoisch** [comment]
Just by curiosity, can you do a 

```
console.log('Inputs:', Input, ButtonInput);
```

right after the two var statements? 

It seems like the import is somewhat failing

**Comment by pealmeid** [comment]
Thanks for the quick reply, @dozoisch. See output below:

![react-02](https://cloud.githubusercontent.com/assets/6384219/8558034/ef5a2f30-24d7-11e5-8c27-8df5090a1949.jpg)

**Comment by dozoisch** [comment]
Humm ButtonInput is undefined... Let me try to see if I can find out why.

**Comment by pealmeid** [comment]
I'm running `react@0.13.3` and `react-bootstrap@0.21.2`, installed with `npm install`.
My `package.json` file is below:

    {
      "name": "react-issue",
      "version": "1.0.0",
      "description": "Test of react issue",
      "main": "webpack.config.js",
      "scripts": {
        "test": "echo \"Error: no test specified\" && exit 1"
      },
      "author": "Pedro Almeida",
      "license": "MIT",
      "dependencies": {
        "bootstrap": "^3.3.4",
        "react": "^0.13.1",
        "react-bootstrap": "^0.21.2"
      },
      "devDependencies": {
        "jsx-loader": "^0.13.1"
      }
    }

Thanks for the assistance.

**Comment by pealmeid** [comment]
Updating the `package,json` file to the latest version of `react` and `react-bootstrap` solved the issue. I has understood (incorrectly, it turns out) that `npm install` would always pull the latest version. In any case, thanks a lot to @dozoisch for his assistance.

**Comment by AlexKVal** [comment]
@pealmeid just a hint that I've learned too:
```sh
> npm up
> npm outdated
```
will show you which dependencies you have to update manually when there are newer versions :wink: 
I hope this would help you too :cherries:

**Comment by pealmeid** [comment]
Thanks for the tip @AlexKVal!
