### ISSUE TITLE
`Ref` problem 

### ISSUE THREAD

**Issue by danyaljj** [react-bootstrap/react-bootstrap#965]
I am trying to access a `DropdownButton` via `ref="dropDownRef"`: 
```
<DropdownButton ref="dropDownRef" bsStyle="primary" title="Test" onSelect={this.onSelect}>
```
I tried `React.findDOMNode(this.refs.dropDownRef).value` and `this.refs.dropDownRef.getDOMNode().value` and none of these work. Any idea what is the problem? 

Here is the actual code:
https://jsfiddle.net/danyaljj/gohopfz8/1/

**Comment by pealmeid** [comment]
I'm relatively new to react-bootstrap, but my understanding is that `onSelect` is only fired when you select  text (i.e. click & drag across a text field) so it can only be used with the `<text>` and `<textarea>` tags. I know it's not a solution, but I hope it helps. Regards.

**Comment by danyaljj** [comment]
`onSelect` gets fired for sure. Since the following shows output: 
```
onSelect(key) {
        //var a = React.findDOMNode(this.refs.dropDownRef).value // NOT WORKING 
        //var a = this.refs.dropDownRef.getDOMNode().value; // NOT WORKING 
        var a =  1  // WORKING! 
        this.setState({ key: a });
    },
```

**Comment by dozoisch** [comment]
That's because a dropdown is not an input. It has no value. 

You get the key passed directly in the onSelect function as an argument.

```
    onSelect(key) {
        this.setState({ key });
    },
```

Seems to do what you want.

https://jsfiddle.net/gohopfz8/2/

**Comment by pealmeid** [comment]
I made it work with

    onSelect(key) {
        this.setState({ key: key });
    }

but @dozoisch's solution seems more elegant.

I didn't know that syntax was acceptable for setting `state` values, great tip!

**Comment by dozoisch** [comment]
@pealmeid It's the exact same, it's just that this what I posed uses [ES6 Ehanced Object Literals](https://babeljs.io/docs/learn-es2015/#enhanced-object-literals)

**Comment by danyaljj** [comment]
@dozoisch  @pealmeid   The question is how to use `refs, not how to handle Select. Why did you close this?

**Comment by dozoisch** [comment]
@danyaljj Oh sorry thought that was answered.

You can access the refs just like normally.

```
console.log(this.refs.dropDownRef); // returns the object.
```


https://jsfiddle.net/gohopfz8/7/

**Comment by pealmeid** [comment]
@danyaljj you were doing it right. Your error was not in the way you used the `ref`, but rather in trying to use the element's `value`, which (as @dozoisch explained) does not apply to a dropdown.

**Comment by danyaljj** [comment]
@pealmeid  ah yeah just noticed it. Thanks for the clarification! 
Thanks @dozoisch!
