### ISSUE TITLE
Missing Typeahead

### ISSUE THREAD

**Issue by Nomeasmo** [react-bootstrap/react-bootstrap#967]
I cannot find it in the current implementation and I also didn't find it tagged to a milestone.

**Comment by jquense** [comment]
Hi there,

Typahead was removed from Bootstrap in version 3.0. Since react-bootstrap tracks Bootstrap 3 there are no plans to add a typehead component. 

There are a few really good typeahead react components already out there though you can check out: http://react.parts/web

**Comment by Nomeasmo** [comment]
Thanks, wasn't aware
