### ISSUE TITLE
Stripes aren't added to nested progress bars

### ISSUE THREAD

**Issue by noam-c** [react-bootstrap/react-bootstrap#968]
If you change the Stacked example in the [Progress Bars component docs](http://react-bootstrap.github.io/components.html#progress) to:
```
const progressInstance = (
  <ProgressBar>
    <ProgressBar bsStyle='success' now={35} striped key={1} />
    <ProgressBar bsStyle='warning' now={20} striped key={2} />
    <ProgressBar bsStyle='danger' now={10} striped key={3} />
  </ProgressBar>
);

React.render(progressInstance, mountNode);
```

then stripes do not appear on the bars:
![screen shot 2015-07-09 at 3 19 00 pm](https://cloud.githubusercontent.com/assets/1154988/8608264/060a289e-264e-11e5-9fd8-debc09309da0.png)

However, if you make the outer `ProgressBar` striped, like so:
```
const progressInstance = (
  <ProgressBar striped>
    <ProgressBar bsStyle='success' now={35} key={1} />
    <ProgressBar bsStyle='warning' now={20} key={2} />
    <ProgressBar bsStyle='danger' now={10} key={3} />
  </ProgressBar>
);

React.render(progressInstance, mountNode);
```

Then all of the stacked bars receive stripes:
![screen shot 2015-07-09 at 3 19 18 pm](https://cloud.githubusercontent.com/assets/1154988/8608267/0c4a0742-264e-11e5-9796-ffabb560f41e.png)

This is happening because the code that determines whether or not the `progress-bar-striped` class will be added is only run for parent `ProgressBar` components. This code is located [here](https://github.com/react-bootstrap/react-bootstrap/blob/master/src/ProgressBar.js#L49). Because the `active` class is also applied here, the same issue occurs for the `active` property.

**Comment by AlexKVal** [comment]
@noam-c could you take a look to #975 ? :sparkle:

**Comment by noam-c** [comment]
@AlexKVal I took a look at the PR and it looked like a clean change to me as well! Thanks for jumping on this so quickly!

**Comment by AlexKVal** [comment]
Thank you :blush:
