### ISSUE TITLE
Enhance prop docs generation for repeated properties

### ISSUE THREAD

**Issue by AlexKVal** [react-bootstrap/react-bootstrap#977]
start: https://github.com/react-bootstrap/react-bootstrap/pull/974#issuecomment-120647630

> @jquense the most obvious solution I can think of just to have an object holding default messages somewhere that the prop table can read from if the desc is empty.

**Comment by taion** [comment]
Handled by https://github.com/react-bootstrap/react-bootstrap/blob/v0.28.0/docs/src/defaultPropDescriptions.js now.
