### ISSUE TITLE
refs inside the Modal is unavaliable

### ISSUE THREAD

**Issue by roadmanfong** [react-bootstrap/react-bootstrap#980]
At version 0.23.7, 
When I tried to set `ref` to specific component inside `Modal`.
It seems unavailable even after it rendered.

```jsx
import React from 'react';

import {
  Button,
  Modal
} from 'react-bootstrap';

const Example = React.createClass({

  getInitialState(){
    return { showModal: false };
  },

  close(){
    this.setState({ showModal: false });
  },

  open(){
    this.setState({ showModal: true });
    console.log(this.refs); // only shows referenceA
  },

  render() {

    return (
      <div>
        <Button
          bsStyle='primary'
          bsSize='large'
          onClick={this.open}
        >
          Launch demo modal
        </Button>
        <div ref='referenceA'/>

        <Modal show={this.state.showModal} onHide={this.close}>
          <div ref='referenceB'/>
          <Modal.Body>
            <h4 ref='referenceC'>Text in a modal</h4>
          </Modal.Body>
        </Modal>
      </div>
    );
  }
});

export default Example;
```

**Comment by jquense** [comment]
you are checking the ref immediately after calling setState which can be asynchronous. Likely the ref is empty because the modal has actually mounted yet. place the check in timeout or maybe in the callback of the setState call and it should be there

**Comment by roadmanfong** [comment]
ok I see, thanks for answering

**Comment by mtando** [comment]
I'm having exact issue, I added timeout after setState call but still, ref inside the modal can't be found... Can you share some tips @roadmanfong ? thanks!

**Comment by anil1712** [comment]
Hi Guys, 
Is anyone found any solution for this issue? 
I am getting the same problem.

**Comment by dozoisch** [comment]
What happens when using function refs? This should work properly.

**Comment by anil1712** [comment]
Hi @dozoisch 
I am getting below exception in browser console
```
Error: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded
```
Thanks
