### ISSUE TITLE
Modal hide is delayed when Modal contains TabPanes

### ISSUE THREAD

**Issue by schutterp** [react-bootstrap/react-bootstrap#982]
Added a TabbedArea component and TabPane components to a Modal and noticed a delay when the modal is closed.

RC: It appears the TabPane component unconditionally adds the `fade` class during render and unmounting the Modal calls the FadeMixin componentWillUnmount method which finds the fade class on the tabpane and thus delays removal of the modal.

**Comment by jquense** [comment]
should be fixed when #848 is merged I believe
