### ISSUE TITLE
Works with React 0.14?

### ISSUE THREAD

**Issue by justin808** [react-bootstrap/react-bootstrap#985]
Has anybody tried react-bootstrap with:

https://facebook.github.io/react/blog/2015/07/03/react-v0.14-beta-1.html

**Comment by mtscout6** [comment]
I haven't, though I don't know about the other collaborators. We do have a [React 0.14](https://github.com/react-bootstrap/react-bootstrap/milestones/React%200.14.0) Milestone where we plan to track that. If you'd like to tackle it we could create a `react-0.14` branch to which you could submit PRs. I doubt we'd bring those changes into master until the actual release for 0.14 is out. I'm going to close this issue in favor of opening targeted issues for specific problems with React 0.14 which can be added to that milestone as appropriate.

**Comment by kevinrenskers** [comment]
I'd really like to try this with React 0.14-beta1, but the [peerDependencies](https://github.com/react-bootstrap/react-bootstrap/blob/master/package.json#L43) make it impossible to install react-bootstrap.

Is there a way to ignore peerDependencies? Or maybe even better, shouldn't it simply be removed from react-bootstrap? NPM 3 is going to get rid of peerDependencies anyway..

**Comment by taion** [comment]
peerDependencies is explicitly not going away: https://github.com/npm/npm/issues/6565#issuecomment-74971689

It's made for exactly this use case and we intend to continue using it in this way.

Maybe we can set up a new branch for React 14 compat as mentioned in https://github.com/react-bootstrap/react-bootstrap/issues/985#issuecomment-121314711?

**Comment by jquense** [comment]
or `npm install -g npm@3.0-latest` if you want to try it out without a branch

**Comment by kevinrenskers** [comment]
npm@3 is [very very beta](https://github.com/npm/npm/releases) though :p

Maybe you could change the peerDependancies to something like `>=0.13 || 0.14.0-beta1`?

**Comment by jquense** [comment]
we aren't going to change the range for a published copy of RB, since it may result in some ppl getting the beta installed instead of an actual compatible version. We can set up a branch tho that you can check out

**Comment by kevinrenskers** [comment]
Sounds good!

**Comment by jquense** [comment]
and there you go: https://github.com/react-bootstrap/react-bootstrap/tree/react-14
