### ISSUE TITLE
Add documentation to describe why you'd want to only import the components you plan to use.

### ISSUE THREAD

**Issue by cassidoo** [react-bootstrap/react-bootstrap#986]
It'd be great to have some kind of "Customize" section just like Bootstrap's, where people can choose to install only some components.

I'd be interested in helping build this, but just because I'm not super familiar with npm: would this be the sort of case where you can add a flag of some kind that installs only certain things, or would that mean having a separate node module for each component?

**Comment by jquense** [comment]
The nice thing about the modules is that you already get custom builds for free, if you only import the modules you are using!

If you are using Webpack, Browserify or similar bundler, they will only include files that your project has actually imported. To facilliate this react-bootstrap gives you two ways to import it:

- everything up front: `require('react-bootstrap)` or `import rb from 'react-bootstrap'`
- import just the one you need: `require('react-bootstrap/lib/Button')` or `import Button from 'react-bootstrap/lib/Button'`

So if you use the second method in your app the resulting bundle will only contain those files (and their dependencies)

**Comment by mtscout6** [comment]
We could probably describe that better on our [getting started](http://react-bootstrap.github.io/getting-started.html) page. We document that you can do it, but not why you'd want to. This is a common question that comes up.

**Comment by rskumar** [comment]
`import rb from 'react-bootstrap' ` does not work with browserify.
I am getting it as undefined. 
Tried `import * as rb from 'react-bootstrap' ` - didn't work.
Tried `import ButtonGroup         from 'react-bootstrap/lib/ButtonGroup';` - didn't work.
And yes, React as well as react-bootstrap already installed through npm.

**Comment by mtscout6** [comment]
@rskumar It seems you are running into an unrelated issue. Can you open a new issue and describe your setup a little more. For example are you using Babel to compile your ES6 with Browserify, and what version of React-Bootstrap do you have installed?

**Comment by okonet** [comment]
Could it be done via babel plugin? Like this one https://github.com/megawac/babel-plugin-lodash?

**Comment by mtscout6** [comment]
@okonet That sounds awesome! Although I will say that the core maintainers are stretched pretty thin as it is. If you're open to putting together a prototype of this in a personal repo that we could look at go right ahead. We would be open to an invite to have that repo transferred to the organization with an invite to join.

**Comment by okonet** [comment]
Sounds good but also not sure if I'll find time any soon. I'll keep in touch.
