### ISSUE TITLE
Survey: Make short bootstrap native constants 'xs sm md lg' for sizes also applicable. Should we ?

### ISSUE THREAD

**Issue by AlexKVal** [react-bootstrap/react-bootstrap#989]
started by https://github.com/react-bootstrap/react-bootstrap/issues/952#issuecomment-119031495

I can do it. It is simple.

Then such code becomes possible too:
```jsx
<Button bsSize='xs' />
```

**Comment by mathieumg** [comment]
No strong opinion on this. It doesn't take anything away from existing users and can make others happy.

**Comment by jquense** [comment]
sounds good to me.
