### ISSUE TITLE
Tooltip in Modal adds permanent divs to DOM.

### ISSUE THREAD

**Issue by ElsewhereGames** [react-bootstrap/react-bootstrap#990]
It seems that when a `Modal` is opened or closed, one or two `div` elements are added to the `body` element. 

This can be reproduced using the "Live Demo" in the [Modal components example](http://react-bootstrap.github.io/components.html#modals); If you observe the Inspector in Firefox or the Elements view in Chrome, you will see a `<div></div>` is added every time you open and close it.

Note that while the online demo adds a `div` every time I open *and* close the modal, in my local tests 2 'div's are added every time I close the modal.

**Comment by ElsewhereGames** [comment]
Something I just noticed: If I try the [sized modals](http://react-bootstrap.github.io/components.html#modal-default-sizing) demo, I don't see this behavior.

**Comment by ElsewhereGames** [comment]
If I remove the following from the demo, the problem goes away:

```
<h4>Popover in a modal</h4>
            <p>there is a <OverlayTrigger overlay={popover}><a href='#'>popover</a></OverlayTrigger> here</p>

            <h4>Tooltips in a modal</h4>
            <p>there is a <OverlayTrigger overlay={tooltip}><a href='#'>tooltip</a></OverlayTrigger> here</p>
```

**Comment by taion** [comment]
https://github.com/react-bootstrap/react-bootstrap/blob/e2bad355143c3e7d86d43566d4d6cb2a68a43f2b/src/Portal.js#L27
