### ISSUE TITLE
Extended typeahead autocomplerer

### ISSUE THREAD

**Issue by binarykitchen** [react-bootstrap/react-bootstrap#991]
I often get stuck when I want to use other React components while 90% of my app is using elements of this react-bootstrap module.

For example I cannot use https://github.com/fmoo/react-typeahead in conjunction with the inputs react-bootstrap comes with.

How do you deal with those conflicts?

**Comment by AlexKVal** [comment]
`Input` component is under heavy refactoring now. :sparkle: 
See at https://github.com/react-bootstrap/react-bootstrap/issues/342
You can help with it as well :+1: 

:cherries:

**Comment by binarykitchen** [comment]
cool, i ll have a look soon ...
