### ISSUE TITLE
DropdownButton invariant violation in IE when component removed in onClick

### ISSUE THREAD

**Issue by jason-wolfe** [react-bootstrap/react-bootstrap#997]
If you remove a DropdownButton component in an onClick handler then something tries to find the node in the DOM where it no longer exists ... on IE only. Every other browser seems to be fine.

Minimal reproduction repo: https://github.com/jason-wolfe/reactbootstrapbug

Verified in IE11, but I have reason to believe this happens in all released versions as well.

Error message: 

```
Invariant Violation: Component (with keys: getDOMNode,getBsClassSet,prefixClass,setDropdownState,handleDocumentKeyUp,handleDocumentClick,bindRootCloseHandlers,unbindRootCloseHandlers,renderButtonGroup,renderNavItem,renderMenuItem,handleDropdownClick,handleOptionSelect,props,context,state,refs,_reactInternalInstance,_onDocumentClickListener,_onDocumentKeyupListener) contains `render` method but is not mounted in the DOM
```

**Comment by yankouskia** [comment]
+1

**Comment by jquense** [comment]
closing for Staleness, let me know if this is still an issue, and we'll find someone with IE to test it :P
